### ISSUE TITLE
A thousand issues deserves cake

### ISSUE THREAD

**Issue by pronoiac** [concourse/concourse#1000]
Hi there!

# Feature Request

## A Modest Proposal

This is issue :100 0 on the concourse/concourse repo. I'm pretty sure that tasty food is called for. 

![Image of 1000! cat](https://media.giphy.com/media/KhIpLH0WogmPe/giphy.gif)

**Comment by joshzarrabi** [comment]
Thanks
http://www.littlebcakes.com/wp-content/uploads/2014/01/Pictures-of-Airplane-Cakes.jpg
Yay
