### ISSUE TITLE
Fly i exits with 0 status code after doing nothing

### ISSUE THREAD

**Issue by neezer** [concourse/concourse#1001]
# Bug Report

I'm trying to debug an error I'm getting about Yaml parsing and thought to use `fly hijack` to examine a log file. However, using it on my most recent container seconds after the container is created, immediately exits with the status code `0`. I can hijack into previous containers (part of the same job) just fine.

You can see an asciicast of the behavior here: https://asciinema.org/a/9jculh7om9tvyc7jvjd6js6d0

Here's the output showing the status code:

![ss](http://d.pr/i/P7Zb+)

The resource for the container I'm trying to investigate is one of https://github.com/robdimsdale/concourse-pipeline-resource

If it helps at all (maybe it's causing the container to bork or become inaccessible, I dunno) the error I'm trying to debug is 

![ss](http://d.pr/i/m13q+)

Bug report filing encouraged by @chendrix, who's been helping me on concourseci.slack.com in #general (relevant conversation is around a similar timestamp to the creation of this issue).

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: DigitalOcean Ubuntu 16.04
* Did this used to work? Nope, never tried it before now

**Comment by neezer** [comment]
Ok, confirmed this has nothing to do with the Yaml parsing error mentioned in the description.

Also confirmed this behavior always occurs when trying to hijack `get` **and** `put` containers from `concourse-pipeline-resource`:

![ss](http://d.pr/i/LTgc+)

**Comment by chendrix** [comment]
@neezer can you try doing the same `fly i` command but add `-- /bin/sh` to the end of the command?

i.e. `fly -t kc hijack -j ks-api-pull-requests/configure-pr-pipeline -- /bin/sh`

**Comment by neezer** [comment]
@chendrix That seems to get me in

![ss](http://d.pr/i/Wpn4+)

**Comment by chendrix** [comment]
Yeah I think it's just because this resource is [based on alpine](https://github.com/robdimsdale/concourse-pipeline-resource/blob/950221a1f4f854f9fc5cc4aa93b437c5d358bbbd/Dockerfile#L1) which doesn't have bash available. The reason the check containers work is those are actually instances of the `docker-image-resource` and not the `pipeline-resource`
