### ISSUE TITLE
[feature] ATC option to redirect HTTP to HTTPs

### ISSUE THREAD

**Issue by dmlemos** [concourse/concourse#1004]
Hi there!

# Feature Request

## What challenge are you facing?

Current deployment is using BOSH in AWS. I got an ELB in front of the ATC, however I have to block the traffic on port 80 to avoid unencrypted to the ATC. The user has to type `https` in the browser.
In order to be able to redirect traffic from HTTP to HTTPs, another load balancer would have to be setup in the middle of the two. I think this is overkill.

## A Modest Proposal

Make a property in the ATC spec to redirect traffic to HTTPs. Default should be `no`.
I imagine many people is using a similar setup and with this feature there is not much need to have another load balancer.

**Comment by vito** [comment]
The ATC will already redirect `http://` to `https://` if it's configured with TLS. I would recommend removing the SSL termination from your ELB and just configuring the ATC instead. You'll also get HTTP/2 for free which is a decent performance boost.

**Comment by dmlemos** [comment]
@vito thanks a lot. I saw the TLS properties, but wasn't sure of the advantages. Updating the docs with this info could help other people.

The only problem I see with this configuration is the TLS will put more load on the ATC. However the performance gains with HTTP/2 probably circumvents that :)
I was using 2x t2.small and still they could as well be t2.micro for the fact.

**Comment by gdamjan-h4** [comment]
AWS ELBs support HTTP/2 and also free certificates

**Comment by gdamjan** [comment]
AWS ELBs (the new style ALB) support HTTP/2 and also they give out free certificates.

but ok, nginx is also a solution
