### ISSUE TITLE
fly hijack returns too many containers

### ISSUE THREAD

**Issue by bbokorney** [concourse/concourse#1005]
# Bug Report

Executing `fly hijack` without specifying the job with `--job`, and instead only specifying the global build ID with `--build` returns many more containers which can be hijacked into than are used in the job. In my case, I see about 955 containers in the list for a job which only has about 10.

Executing `fly hijack` on the same build, but specifying the `--job` param and setting `--build` to the build name (not the global build id) returns the expected list of containers.

This functionality has been working fine for a couple months on the version we're using (`2.6.0`). However, it seems to have stopped working around the time that our Concourse builds surpassed 100,000 builds. (This might be just coincidence but I thought it could be helpful to know.)

Additionally, the list of containers which is returned all appear to be valid containers for other pipelines. It seems that the list of containers is just not be filtered properly by `fly`.

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: OpenStack
* Browser (if applicable): N/A
* Did this used to work?: Yes

**Comment by joshzarrabi** [comment]
Hmmm, thats interesting... I don't really know where this could be coming from, but we recently redid our container management, so hopefully that straightens problems like this out.
