### ISSUE TITLE
Pre-Compile all of the Bosh Packages

### ISSUE THREAD

**Issue by zachgersh** [concourse/concourse#1006]
Quite a bit of the actual concourse installation time (from the bosh release) is spent compiling the packages. Would be nice if concourse could add a step to their pipeline to compile all the packages.

**Comment by clarafu** [comment]
Yep that would be nice. This would also bring `create-env` to get a single-VM Concourse closer to something as nice as `vagrant up`.

**Comment by jtarchie** [comment]
I'd like to expand on this a bit more as there are a lot of details missing from this as an actionable story.

A precompiled bosh release is tied to a specific OS and version. If you look at the documentation for `bosh export-release` you'll see this information. This means that for a pre-compiled release to be useful to a bosh directory, we'd to maintain one for each IAAS and stemcell version.

A bosh director does not care that a precompile binary can work on any stemcell, it looks at the exported release and says I'll use the stemcell it used to compile -- nothing else. The use case is not ideal for an operator as they always want the latest secure stemcell. They would have to wait on the concourse team to then release a pre-compiled release for the latest stemcell.

If we do this story, I'd like to be very deliberate about the deliverables.

**Comment by vito** [comment]
Consolidating this into #1380 which is the primary goal for this being prioritized. The pre-compilation only has to be enough to satisfy the `create-env` workflow it calls for.
