### ISSUE TITLE
Question: 'passed' any of the list

### ISSUE THREAD

**Issue by Rukenshia** [concourse/concourse#1007]
Hello,

We are currently trying to set up CI/CD for updating our npm packages. We want to manually trigger any of the jobs `major`, `minor`, `patch`, `bump_rc` which then run the rest of the pipeline. Is there any way I can configure a job to have an input that has been processed by _any_ of the given jobs in the `passed` list?

Here's an image of what we would like the Pipeline to look:
![image](https://cloud.githubusercontent.com/assets/1899599/24950433/534c8a16-1f71-11e7-9c9b-9ef53db90b05.png)

The problem with the current behavior of `passed` is, that the task will wait until every of the version jobs processed the same version of `source` which is not possible for us.

If you're wondering why there is only `source` and no semver resource being used: we want to use the package.json's `version` field of npm so we only have a "single source of truth" for the current package version.

The only solution with our current approach is to have separate pipelines for every of the `minor`, `major`,... tasks that execute the whole pipeline.

Any suggestions as to how we could organize it better are welcome. Thanks!

**Comment by joshzarrabi** [comment]
It seems to me that you could take off the passed constraints from the version bumping to the `cache` job and it would accomplish what you want. Then, if you trigger any one of those jobs the `cache` job would trigger and the rest of your pipeline would run.

**Comment by chendrix** [comment]
Closing as this question seems to have been answered.

**Comment by qlaffont-smiirl** [comment]
Hi,
I have the same issue. I have tried with version "every" and "latest" without success. Someone can help me, please? ^^

**Comment by makslevental** [comment]
@joshzarrabi how to get access ot the slack channel?
