### ISSUE TITLE
Bug report: animation of previously failed pipeline that is building now "flashes" (can possibly cause epilepsy).

### ISSUE THREAD

**Issue by artem-zinnatullin** [concourse/concourse#1008]
Steps to reproduce:

1. Fail some pipeline
1. Run build again
1. Observe flashing that only gets worse if you try to hover mouse over it or change focus state of browser window

![aweeeee](https://cloud.githubusercontent.com/assets/967132/24956745/b913ce7a-1f91-11e7-934d-e998a7094182.gif)

Environment:
* Concourse version: 2.7.1
* Deployment type (BOSH/Docker/binary): Docker
* Browser: Google Chrome 57.0.2987.133 (64-bit), macOS 10.12.4
* Did this used to work? Yes

**Comment by joshzarrabi** [comment]
This is a good point, we should probably have an option to turn this off... it is really annoying.

**Comment by vito** [comment]
Yeah looks like Chrome has outpaced our UI here and it's super janky now. I'll prioritize this so we can redesign it.

**Comment by andrewedstrom** [comment]
We are definitely still seeing this bug in 3.4.1

**Comment by jama-pivotal** [comment]
Turns out we just had to wait for Chrome to fix it for us, no longer happens on Chrome 70.0.3538.102 (Official Build) (64-bit)
