### ISSUE TITLE
Realtime build log eats ~50% CPU and scrolling is impossible.

### ISSUE THREAD

**Issue by artem-zinnatullin** [concourse/concourse#1009]
Realtime log of the **same build** on Jenkins 2.54 eats about 5% of CPU on my mac and scrolls normally.

I can try to collect perf dump from Chrome if you can't reproduce it.

Environment:
* Concourse version: 2.7.1
* Deployment type (BOSH/Docker/binary): Docker
* Browser: Google Chrome 57.0.2987.133 (64-bit), macOS 10.12.4
* Did this used to work? Yes, I think so.

(sorry for complaining, but I don't have enough expertise in web development to post a PR)

**Comment by artem-zinnatullin** [comment]
I specifically exited all foreground apps and closed all other tabs in Chrome to record that, but wasn't even able to open the build log now (waited 1m+) and CPU was on a constant load…

![720p](https://cloud.githubusercontent.com/assets/967132/24958547/536fc702-1f98-11e7-85c7-4e33771cff2a.gif)

Again, Jenkins 2.54 is able to open logs of exact same builds in few seconds (both realtime and full log once job is completed) without affecting performance of the browser.

---

Since build log is one of the main ui components of the Concourse, it's kinda critical issue…

**Comment by emcniece** [comment]
I'm finding that if the logs are big enough, they crash my Chrome tabs.

**Comment by artem-zinnatullin** [comment]
Yup, saw this today as well.

**Comment by JohannesRudolph** [comment]
We also noticed that concourse's log streaming/recording is extremely inefficient to the point of crashing chrome tabs. We worked around it by heavily dialling back the verbosity of build logs we generate, but it's still very unfortunate. Dealing efficiently with logs is something a CI server should handle well.

**Comment by emcniece** [comment]
As @JohannesRudolph has found, our solution too for now is to `--silent` or `--quiet` any commands that accept these flags. In my case, this is mostly `npm install` and `apt-get install`. It would still be good to have these logs however, in the case that we need to do version comparisons or other troubleshooting.

What ideas or features would help resolve this?

- "Download full logs" link
- Only loading a few chunks of log output in the browser at one time
- "View full logs" link, and only show the last `n` lines?

**Comment by joshzarrabi** [comment]
You can always write your logs to a file and output them with some sort of a resource

This is hard for us because we have optimized this on chrome as much as we can. We only render one line of text at a time. At a certain point there is not much that we can do. Chrome slows down with a huge amount of streaming text.

**Comment by JohannesRudolph** [comment]
I want to vote for reopening this, considering that there's so many similar and linked issues floating around @joshzarrabi

You said:
> We only render one line of text at a time

We'll that may  the culprit then. It should be possible to add some sort of batching. Unfortunately the concourse UI is based on elm which I have no experience with, but drawing from my knowledge of other frontend frameworks it should be possible to minimize the amount of DOM manipulations done (they cause expensive layout recalcs) and simplify the DOM structure for faster layout.
