### ISSUE TITLE
Instability after leaving the concourse docker-compose stack on for a couple of days

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#1017]
## What challenge are you facing?

Leaving concourse up for 5 days usually result in it being inaccessible when I come back...
Trying to restart the concourse-web/ATC container gives the following output:

concourse-web-1       | {"timestamp":"1492501428.056398392","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"2"}}
concourse-web-1       | failed to load authorized keys: open : no such file or directory
concourse-web-1       | {"timestamp":"1492501431.679920912","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"2"}}
concourse-web-1       | failed to load authorized keys: open : no such file or directory
concourse-web-1       | {"timestamp":"1492501435.959055901","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"2"}}
concourse-web-1       | failed to load authorized keys: open : no such file or directory
concourse-web-1       | {"timestamp":"1492501439.663755894","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"2"}}
concourse-web-1       | failed to load authorized keys: open : no such file or directory
concourse-web-1       | {"timestamp":"1492501444.434012175","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"2"}}
concourse-web-1       | failed to load authorized keys: open : no such file or directory
concourse-web-1       | {"timestamp":"1492501450.685797453","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"2"}}
concourse-web-1       | failed to load authorized keys: open : no such file or directory

I am just gonna remove the containers and set them up again from scratch... 
This is something I usually have to do after a while...

The disk has 158Gi free space, 75Gi used.

## A Modest Proposal

Handle failures by cleaning up and restarting internally instead of having the users of concourse have to interfere...

# Bug Report
The following can also be handy:

* Concourse version: 2.7.0
* Deployment type: Docker on OSX on a boot2docker VM
* Did this used to work: stability has always been an issue (I have been a user since before 2.5.0)

**Comment by vito** [comment]
It's pretty much impossible to do anything with this issue. There's no root cause or steps to reproduce. It looks like some volume mounts disappeared or something, which isn't really something we can handle in any reasonable way. Sounds like a problem with your container orchestrator.
