### ISSUE TITLE
fly configure output doesn't show ensure block

### ISSUE THREAD

**Issue by wcamarao** [concourse/concourse#102]
We recently migrated some tasks that were using `conditions` to use the new `ensure` API, and since then it doesn't show the ensure block when we run `fly configure` to show the current configuration.

We've also observed that running `fly configure` with params to update the config doesn't show the diff correctly. It's missing the addition of the ensure block.

cc: @calebamiles

**Comment by robdimsdale** [comment]
one possibility is that fly is slightly old - did you remember to `fly sync` when you upgraded the ATC?

**Comment by wcamarao** [comment]
That's correct @robdimsdale, running fly sync resolved it. Thanks!
