### ISSUE TITLE
HTTP 400 returned when triggering jobs through web UI

### ISSUE THREAD

**Issue by arwineap** [concourse/concourse#1020]
I'm having issues triggering jobs using the web UI.

I have tested these steps with the follow two combinations of pipelines / jobs:
1) pipeline with hyphen
    job without hyphen

2) pipeline without hyphen
    job with hyphen

Reproduction steps:
1) Goto a pipeline page
2) click on a "job box"
3) click on play button to attempt to trigger job

Once you have clicked the play button the web inspector will have returned:
`400 Bad request`

As a note, triggering the job via fly works fine
`fly -t envName trigger-job -j pipelineName/jobName`

* Concourse version: 2.7.3
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: aws
* Browser (if applicable): chromium
* Did this used to work? Yes

**Comment by identity-kit-libraries** [comment]
We're facing the same issue

**Comment by eruvanos** [comment]
Same for pausing versions of resources. No cli workaround for that :/

**Comment by thomasmmitchell** [comment]
I solved this by logging out and logging back in.

**Comment by arwineap** [comment]
It doesn't appear to be related to my pipeline naming.

It seems like my CSRF token in local storage is disappearing

**Comment by arwineap** [comment]
CSRF token does not disappear with extensions removed in incognito mode.

I'm going to close this issue because the original post describes an issue that is clearly related to a third party extension
