### ISSUE TITLE
Concourse 2.7.3 mounts /etc/hosts as UID 65534

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#1021]
# Bug Report

`/etc/hosts`, for all its faults, is a great way to have non-global DNS for smoke tests. Between Concourse 2.7.0 and 2.7.3, it looks like a change was made that bind mounts it into containers as UID 65534, AKA nobody, AKA nfsnobody, depending on who you ask. This breaks the ability of Concourse tasks to use /etc/hosts as a quick and easy split-horizon DNS.

**Comment by vito** [comment]
Closing this as the real fix is in Guardian (the issue referenced above). When Garden ships a new version we'll automatically bring it in, so no need to track this explicitly.

Thanks for opening it on Guardian as well!
