### ISSUE TITLE
finding ips of workers through fly

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#1024]
# Feature Request

Could fly workers should display the actual ip of the worker.

## What challenge are you facing?

- I have a dhcp network and my workers are headless...
- Sometimes i need to login to the workers and debug why the OSX ios Simulator is not working as exepected.

- I then need to be able to login to the worker with an Aqua session on osx, (screen, not just terminal).
- In other cases fly intercept etc is enough.

## A Modest Proposal

print the actual ip of the worker when I run fly workers.

* Concourse version: 2.7.3
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: bare metal
* Browser (if applicable): n/a
* Did this used to work? n/a

**Comment by joshzarrabi** [comment]
@devdavidkarlsson Thats an interesting idea... I would assume that most concourse workers are in private networks, so we would have to think about how we would display public vs private ips...
