### ISSUE TITLE
UI bug when there are multiple pages of resources

### ISSUE THREAD

**Issue by madamkiwi** [concourse/concourse#1025]
# Bug Report

Hello. I'm reporting an issue where the resources span 2 pages, only the first page shows the resources correctly, and when I click on the arrow to go to the next page, the second page will not show any resources and the top bar becomes blue (even thought I'm logged in)

* Concourse version: v2.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Google
* Browser (if applicable): Chrome
* Did this used to work? Not sure

**Comment by joshzarrabi** [comment]
@madamkiwi thanks for reporting this, I think its some sort of url parsing error.... single page apps are hard

**Comment by clarafu** [comment]
About your top bar becoming blue, I'm pretty sure that means your pipeline is paused and not some UI bug. This might mean someone destroyed and recreated your pipeline while you were looking at the resources page. This would explain why all your resource versions disappeared and the pipeline became paused. Let me know if this wasn't the case!
