### ISSUE TITLE
Add OAuth authorities to generic OAuth authentication

### ISSUE THREAD

**Issue by mvdkleijn** [concourse/concourse#1026]
# Feature Request

## What challenge are you facing?

We have an oauth server that we wish to connect Concourse to using the generic OAuth authentication option. However, our oauth server lists the development teams that a user is a member of as "authorities" and not as "scope.

This is due to the fact that OAuth scopes are more for clients than for users. For users, the list of authorities should be used. In terms of Concourse, I'd expect to be able to configure the integration to request a scope of "trust" (for the client) and authority "team-a".

## A Modest Proposal

Add a new param to the generic oauth client: `--generic-oauth-authority <authority name>`

Setting this would require the user to have at least one authority with the specified name. This would be in addition to any scope settings.

**Comment by xtremerui** [comment]
I believe you could now config `groups-key` and `scope` of generic oauth like [here](https://concourse-ci.org/generic-oauth.html) to get the desire mapping.
