### ISSUE TITLE
CSRF token does not propagate between tabs when logging in

### ISSUE THREAD

**Issue by ctaymor** [concourse/concourse#1031]
# Feature Request

## What challenge are you facing?

When using github auth to access the concourse ui, the access time is very short, and for almost every action I take, I have to click to login with github again. This is frustrating and slows us down.  The short logout times seem to be new.

## A Modest Proposal

I would love to be able to configure the access token length to suit the balance of security vs ease of use that is best for my team. Or a longer default. 
Thanks!

The following can also be handy:

* Concourse version: 2.7.3
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: GCP & VSphere
* Browser (if applicable): Chrome
* Did this used to work? Yes, logout times used to seem longer.

~ Caroline

**Comment by vito** [comment]
We haven't changed this. GitHub auth and basic auth all funnel down the same expiry, which is 24 hours. Can you provide steps to reproduce?

**Comment by ctaymor** [comment]
Hmmm. I was seeing it where I had several tabs of the same concourse (different pipelines) up at once. I tried to pause one pipeline (or kick off a build, or any other "write" action, since our pipeline is publicly readable), and was asked to log in. In the next tab, when I navigated to another job and tried to pause it, I was asked to log in again.

I will try to create better reproduction steps if I can reproduce it today.

**Comment by supertopher** [comment]
I can confirm that i have also seen this behavior (same concourse, different user, different chrome extensions, etc...) The time period seems to vary from ~30 minutes to a couple of hours.  This is hard to nail down because I must interact with concourse to notice that I have been logged out =/

**Comment by ctaymor** [comment]
I haven't found a clear enough pattern to get reproductive steps, but continuing to see this issue.

**Comment by vito** [comment]
Hmm. Yeah I can sympathize with the difficulty in reproducing it. I suspect I've actually seen the same thing but just went through the motions of logging in each time, not realizing that I'd already logged in recently due to all the context switching.

I'll reframe this as something to investigate upon picking up, and schedule it for shortly after our next release. It might just take some flailing.

**Comment by mariash** [comment]
@ctaymor can you list the plugins you have installed in your chrome?

**Comment by mariash** [comment]
confirmed, logging in in one tab, does not update auth in another tab.

**Comment by mariash** [comment]
when page is refreshed the local storage appears to be empty in Chrome (missing csrf_token). But all requests are still working, sending csrf token.
