### ISSUE TITLE
setting TLS options via docker-compose failing

### ISSUE THREAD

**Issue by kevinzurek** [concourse/concourse#1033]
# Bug Report

Using docker-compose to deploy Concourse CI in AWS EC2. Under environment in the docker-compose yaml i set 3 variables to configure SSL in the Concourse container:
> CONCOURSE_TLS_BIND_PORT
> CONCOURSE_TLS_CERT
> CONCOURSE_TLS_KEY

When i fire up docker-compose the error below occurs:
```
concourse-web_1    | 1 error occurred:
concourse-web_1    | 
concourse-web_1    | * must specify --tls-bind-port, --tls-cert, --tls-key to use TLS
femrconcoursedeploy_concourse-web_1 exited with code 1
```

By commenting out CONCOURSE_TLS_BIND_PORT i am able to successfully start Concourse without SSL. Any ideas? I can provide more details from docker-compose.yml if that would help... Thank you!!

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by ClaraFuPivotal** [comment]
Make sure `CONCOURSE_TLS_CERT` and `CONCOURSE_TLS_KEY` point to files, not the contents of the cert and key. It looks like the use of env vars is circumventing our validations for this somehow, which should have given you a better error.

**Comment by kevinzurek** [comment]
Hi @ClaraFuPivotal, i tried changing it from the contents to the actual files and ensuring the process had access to them but i still get the same thing :-1: 

Do you know of any examples? Thanks

**Comment by vito** [comment]
You sure it's the same thing? One thing I can see odd there is that your external URL is missing the `https://` prefix, which we have a separate check for, which would be a different error message.

See https://github.com/concourse/atc/blob/master/atccmd/command.go#L554

**Comment by gonzalomarcote** [comment]
You have to copy cert and private key into keys/web/ directory and call them in the docker-compose file pointing to the volume dir, like this:

```
  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["443:443"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_TLS_BIND_PORT: 443
      CONCOURSE_TLS_CERT: /concourse-keys/cert.pem
      CONCOURSE_TLS_KEY: /concourse-keys/privkey.pem
      CONCOURSE_BASIC_AUTH_USERNAME: ...
      CONCOURSE_BASIC_AUTH_PASSWORD: ...
      CONCOURSE_EXTERNAL_URL: ... ```

The cert have to containe the intermediate to the `fly` command not complain about the certificate

**Comment by xtremerui** [comment]
Please reopen if this is still an issue for you.
