### ISSUE TITLE
Removing cached volumes

### ISSUE THREAD

**Issue by kmacoskey** [concourse/concourse#1038]
# Feature Request

## What challenge are you facing?

A problem arose such that we needed to change the git tag of a product release to an annotated tag without additional changes/commits to the repository. This change did not create a new version of the resource, therefore the build pipeline involved would only start new builds with the cached version of the repository. It was needed then to clear that cached resources from the concourse deployment.

We were able to identify the particular volumes with `fly volumes`. With those volume handles and worker id's, we did a baggageclaim api DELETE for each of those volumes on their respective workers. Following that we removed the corresponding rows in the database for the volumes in question. This successfully removed the volumes and the original pipeline in question was able to re-cache the git resource with the updated tag. 

This however had the unintended side effect that all pipelines in the same concourse deployment would occasionally error unpredictably with `error: cannot create volume`. We asked for assistance in the concourse slack and were told there is no clean way to remove cached volumes. The end result was that in order to return to a good working state we had to redeploy all of the workers of the deployment.  

## A Modest Proposal

The functionality and subsequent command in fly to delete a volume by a given volume handle:
`fly delete-volume [handle]`

**Comment by joshzarrabi** [comment]
@kmacoskey We know that this is relatively unfriendly behavior, and we have a story to look into ways to improving our caching strategy. 

Right now concourse relies on strict semver versioning for all of your resources, and any deviation to this basically requires that you recreate your workers. We want to take away some of this pain, but we also don't want to encourage messy versioning, so its something we need to think about...

**Comment by vito** [comment]
This problem arises when resource versions are updated-in-place. Concourse relies heavily on resource versions being immutable (not necessarily semver), for many reasons. If a version changes in the middle of a pipeline run, there's no guarantee that the things that ran before its mutation are still valid (i.e. that it still passes tests). Relying on immutability also allows us to implement caching generically, without resource authors having to implement "cache busting" detectors and such.

That being said, I do see this come up pretty often, so it's worth thinking about, as @joshzarrabi said. **HOWEVER**, this does not necessarily mean that we need a way to bust caches. If we add a `delete-volume`, or an `invalidate-cache`, that could paper over deeper issues, leaving them unsolved and leaving our users constantly running these commands. (The [`knobs`](https://github.com/concourse/concourse/wiki/Anti-Patterns#knobs) anti-pattern.) For example, it could be that the resource's versioning semantics aren't precise enough for your use case, or that you just need a different resource.

The `git` resource for example should probably not include tag metadata at all, as it's bound to be out-of-date. The resource only really versions commits; tags and branches are just metadata that will be stale as soon as we create a cache of it. Can you provide more detail about your workflow and why the bare vs. annotated tagging affected the semantics of your pipeline?

**Comment by joshzarrabi** [comment]
As a member of releng I change my vote and think this a necessary feature.

**Comment by ramonskie** [comment]
is there any update on this?

**Comment by vito** [comment]
Update: I'd be happy to review a PR that adds functionality similar to `fly clear-task-cache`. I think the interface could be something like:

```
fly -t ci clear-resource-cache -r pipeline/resource [--version some:version]
```

The `--version` flag could be optional, and if omitted could just clear all caches for the given resource.

Note: there is some prior discussion here on how `--version` could/should work: https://github.com/concourse/concourse/pull/3131#issuecomment-459874740 - I think it has the same challenges. Adding an API endpoint to list versions by querying fields would help both. (/cc @pivotal-jwinters )

**Comment by vito** [comment]
I'll reopen this and mark it `help-wanted` since I still think this idea would be easy to implement: https://github.com/concourse/concourse/issues/1038#issuecomment-466658736

**Comment by vito** [comment]
This would be nice to handle cases where GitHub releases are created and assets are uploaded after. Right now that causes [build failures](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/build-rc/builds/163) if downstream pipelines fire off before the assets arrive.
