### ISSUE TITLE
Uneven workload causing builds to fail

### ISSUE THREAD

**Issue by aramprice** [concourse/concourse#104]
With two workers (`{cpu: 12, ram: 12_288}`) and two pipelines with ~15 builds per pipeline we are seeing workload distributions of 14 to 0, and 18 to 7 containers.

In these cases some jobs are failing because the specs are CPU bound.

We hare hypothesizing that more fair (cpu / memory / container-count based) would reduce the chance of this. Alternately some kind of anti-affinity for jobs/job-types might help.
- @aramp / @ry4n1m3

**Comment by Osis** [comment]
Seems very similar to https://github.com/concourse/concourse/issues/675. @vito what do you think?

**Comment by topherbullock** [comment]
I agree @osis, looks like this is the same issue as #675 
More traction and discussion there, so I'm going to close this one off.
