### ISSUE TITLE
fly abort-build should accept a build id only

### ISSUE THREAD

**Issue by pdelagrave** [concourse/concourse#1040]
Trying to kill this build:
`97389   one-off n/a  started    2017-04-18@17:57:39-0400  n/a                       361h22m24s+ `

```
fly -t dev abort-build -b 97389
error: the required flag `-j, --job' was not specified
```
Would expect the command not to ask for the job name.

`curl -XPUT http://concourse/api/v1/builds/97389/abort` worked well.

**Comment by mhuangpivotal** [comment]
Closing as the PR was merged.
