### ISSUE TITLE
Can't trigger or cancel jobs from UI on Chrome due to CSRF token failure

### ISSUE THREAD

**Issue by code-engine** [concourse/concourse#1042]
Hi,

* Concourse version: 2.7.4
* Garden version: 1.5.0
* Deployment type: BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome 58.0.3029.96 (64-bit)
* Did this used to work? Yes

Since upgrading to 2.7.4, I am unable to trigger or cancel builds from the web UI on Chrome. Firefox works fine. After clicking either + or x in the build, nothing happens and the console shows the following:

```
https://<redacted>/api/v1/teams/main/pipelines/<redacted>/jobs/<redacted>/builds 400 (Bad Request)
```

I have tried reloading with `Empty Cache and Hard Reload` with no change to behaviour.

If I run a `Copy as cURL`, the command looks like it is missing a CSRF token:

```
-H 'X-Csrf-Token: '
```

and the pasted cURL command also returns a 400.

Any help greatly appreciated.

**Comment by code-engine** [comment]
This also applies to clicking pause / play in the pipeline list

**Comment by ClaraFuPivotal** [comment]
Can you try logging out and logging back in and see if that fixes it? This might just be an issue with getting a new CSRF token on login.

**Comment by mariash** [comment]
it looks like this is an issue in Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=160056 which affects session and local storage. People say if you read the key right away it will persist.

**Comment by pivotal-topher-bullock** [comment]
@code-engine One clarifying question; did you upgrade incrementally from `2.7.3` -> `2.7.4` or from an earlier patch / minor version?
