### ISSUE TITLE
Watch whole pipeline progress with fly

### ISSUE THREAD

**Issue by dmlemos** [concourse/concourse#1044]
# Feature Request
## What challenge are you facing?
The `watch` command only supports _watching_ per job. This means we have to explicitly call fly for every single job to get the feedback from the whole pipeline.

Very low priority to be honest, but thought to put it here for the backlog.

**Comment by ClaraFuPivotal** [comment]
What is your use case for this feature request because i'm not too sure if streaming the outputs of all the running builds to the command line would be useful in terms of visibility?

**Comment by dmlemos** [comment]
I didn't mean to stream all the outputs at the same time. It was more the case of: When the current stream job passes, move to the next one.

**Comment by ClaraFuPivotal** [comment]
Ah I see, but my concern would be for if within the pipeline, the job that `fly watch` is on splits into two or more jobs. How will it know which path of jobs to follow or will it just stream all the logs from every job out?

Why do you need to watch your whole pipeline? I just want to understand your perspective a bit more.

**Comment by marco-m** [comment]
I think that this feature is extremely useful. Considering the question by @clarafu:

> within the pipeline, the job that fly watch is on splits into two or more jobs. How will it know which path of jobs to follow or will it just stream all the logs from every job out?

This is already happening each time a job has multiple tasks in an `aggregate` block.

What about the following: each line of output should be prefixed by the timestamp, the job name, the task name. This allows to see what is happening and, if the user needs it, can do filtering to focus only on one "substream".
