### ISSUE TITLE
An ATC should know not to talk to workers that are out of date or newer

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1047]
# Feature Request

## What challenge are you facing?

Today, if there is a backwards-incompatible change in how the ATC talks to workers, there will be strange behavior during a rolling deploy.

An ATC can be newer than the worker, making API requests the worker can't support, possibly leading to failed builds. This can happen if the Garden or BaggageClaim protocol changes.

An ATC can also be older than a worker, making API requests that may no longer make sense to the worker. We saw this during a 2.7 -> 2.8 upgrade test, wherein the old ATC was creating a volume without specifying a handle, which BaggageClaim required as we moved handle generation to the ATC.

## A Modest Proposal

Workers should register with a version, say `1.2`. This version should *not* be tied to the Concourse version; it should only ever be bumped when there's a protocol change. A minor version bump would be done if a worker supports new functionality but is otherwise compatible with older ATCs. A major version bump would be done if a worker requires a newer ATC to be used. The ATC should be compiled with an expected version, and anything within its major version and newer-or-equal-to its minor version would be used. Older workers would be ignored, as if they're not in the pool.

**Comment by vito** [comment]
Somehow a worker registered with the version of "WORKER_VERSION_REPLACE_ME". It happened twice during a BOSH deploy that updated the VMs to switch from `riemann-emitter` to `telegraf` (as part of #1138). No idea how it happened; the [script](https://github.com/concourse/concourse/blob/04d547f3e3ece611f68334f16fc75fbbe26087c2/jobs/groundcrew/templates/beacon_ctl.erb#L90) looks fine.

Regardless of how it happened, it causes all ATCs to panic with:

```
panic: interface conversion: version.VerSegComp is version.VerSegCompInt, not version.VerSegCompStr

goroutine 838 [running]:
github.com/cppforlife/go-semi-semantic/version.VerSegCompStr.Compare(0xc420895200, 0x19, 0xf7a300, 0xc420171408, 0x3)
        /var/vcap/packages/atc/src/github.com/cppforlife/go-semi-semantic/version/ver_seg_comp_str.go:31 +0x19a
github.com/cppforlife/go-semi-semantic/version.(*VerSegCompStr).Compare(0xc420886a90, 0xf7a300, 0xc420171408, 0x1)
        <autogenerated>:9 +0x6a
github.com/concourse/atc/worker.(*gardenWorker).IsVersionCompatible(0xc4201dcf00, 0xf7e040, 0xc420397800, 0xc4200538c0, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/packages/atc/src/github.com/concourse/atc/worker/worker.go:127 +0x326
github.com/concourse/atc/worker.(*dbWorkerProvider).FindWorkerForResourceCheckContainer(0xc420222000, 0xf7e040, 0xc4204581e0, 0x1, 0xf7a200, 0xc4203ba660, 0xc4208d7560, 0x3, 0xc42
08a39e0, 0x0, ...)
        /var/vcap/packages/atc/src/github.com/concourse/atc/worker/db_worker_provider.go:171 +0x2c4
github.com/concourse/atc/worker.(*pool).FindOrCreateResourceCheckContainer(0xc420220320, 0xf7e040, 0xc4203b4780, 0xf7a200, 0xc4203ba660, 0x0, 0xf783c0, 0x11f6460, 0xc16e5b, 0x5, .
..)
        /var/vcap/packages/atc/src/github.com/concourse/atc/worker/pool.go:247 +0x11e
github.com/concourse/atc/resource.(*resourceFactory).NewCheckResource(0xc42021cbf0, 0xf7e040, 0xc4203b4780, 0x0, 0xf7a200, 0xc4203ba660, 0xc4208d7560, 0x3, 0xc4208a39e0, 0xc16e5b,
 ...)
        /var/vcap/packages/atc/src/github.com/concourse/atc/resource/resource_factory.go:109 +0x156
github.com/concourse/atc/radar.(*resourceScanner).scan(0xc42021a780, 0xf7e040, 0xc4203b4780, 0xf7e5a0, 0xc4208bb2c0, 0xc4203b7da0, 0x0, 0x0, 0x0, 0x10, ...)
        /var/vcap/packages/atc/src/github.com/concourse/atc/radar/resource_scanner.go:263 +0x542
github.com/concourse/atc/radar.(*resourceScanner).Run(0xc42021a780, 0xf7e040, 0xc420178de0, 0xc42047e4d0, 0x10, 0x0, 0x0, 0x0)
        /var/vcap/packages/atc/src/github.com/concourse/atc/radar/resource_scanner.go:119 +0x664
github.com/concourse/atc/radar.(*IntervalRunner).RunFunc(0xc4206097c0, 0xc4202f6240, 0xc4202f62a0, 0x0, 0xc420701f60)
        /var/vcap/packages/atc/src/github.com/concourse/atc/radar/interval_runner.go:47 +0x15f
github.com/concourse/atc/radar.(*IntervalRunner).RunFunc-fm(0xc4202f6240, 0xc4202f62a0, 0x1, 0x9897e4)
        /var/vcap/packages/atc/src/github.com/concourse/atc/radar/scan_runner_factory.go:67 +0x3e
github.com/tedsuo/ifrit.RunFunc.Run(0xc420493ce0, 0xc4202f6240, 0xc4202f62a0, 0xc420701f88, 0xc4203a9140)
        /var/vcap/packages/atc/src/github.com/tedsuo/ifrit/runner.go:36 +0x3a
github.com/tedsuo/ifrit/grouper.(*Member).Run(0xc42013e220, 0xc4202f6240, 0xc4202f62a0, 0xc42027e960, 0xf74100)
        <autogenerated>:1 +0x5e
github.com/tedsuo/ifrit.(*process).run(0xc420371440)
        /var/vcap/packages/atc/src/github.com/tedsuo/ifrit/process.go:71 +0x49
```

We should have a validation on worker registration that the version contains numeric segments. This may also be something to fix in `go-semi-semantic` (/cc @cppforlife).

**Comment by mariash** [comment]
the drain script did not update the version and used to overwrite config file with the original `WORKER_VERSION_REPLACE_ME`. Because beacon continuously retries it might at some point send broken worker.json

**Comment by mariash** [comment]
heartbeat worker should also update the version

**Comment by vito** [comment]
@mariash @clarafu I'm not sure we should bother with having a "patch" segment in these versions.

We would bump the minor version if there's a new feature or behavior that a new ATC may require, but the worker is otherwise backwards-compatible (i.e. old ATCs can still use it).

We would bump the major version if there's a backwards-incompatible protocol change.

I can't think of a scenario where we'd care to bump or depend on the patch version, and I don't think our version comparison logic even looks for it.

Removing the 'patch' segment may also help remove confusion between worker version and Concourse version.

**Comment by vito** [comment]
Also just realized this will make it annoying to develop locally without BOSH, since the ATC will be build with the version `0.0.0-dev`. Let's make it default to blank instead, and if it's blank, don't bother with any version checking; just trust all the workers.

**Comment by vito** [comment]
Switched to patch-less versions and changed the default to blank. Performed an upgrade test that showed everything is working honky-dory. Accepting!
