### ISSUE TITLE
'fly workers' should show the version of each worker

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1048]
needs #1047

# Feature Request

## What challenge are you facing?

If I've got a bunch of workers, some manually deployed, I need a way to know which workers are still out-of-date as I upgrade them.

## A Modest Proposal

`fly workers` should have a column showing the version. It should also show the required version, and highlight any old versions in red. It should also show a missing version as `none`, in red, as a missing version will mean we don't use the worker (just as if it were an old version).

**Comment by mariash** [comment]
we decided to have a separate table for outdated workers with the message `the following workers need to be updated to version (bold)a.b.c(/bold):`
