### ISSUE TITLE
I would like failed builds to persist until I'm done debugging them

### ISSUE THREAD

**Issue by utako** [concourse/concourse#105]
I would ideally like this to be configurable such that I can apply this logic to pipelines, jobs, tasks, etc. depending on my needs, instead of setting a concourse deployment-wide `default_container_grace_time`. I would also like the option to turn this feature on and off.

The workflow I have in mind is as follows:

1. I see that a build has failed, possibly a few hours or a day after the fact. This job has been flaky for a while and I haven't been able to get to the bottom of it.
2. This container has not yet been destroyed and I am able to fly intercept in and look around.
3. Once I am done poking around, I press a button that allows the relevant container(s) to be destroyed.

**Comment by robdimsdale** [comment]
maybe there's a secondary feature request here, which is the 'button to destroy the relevant containers' could be implemented in fly instead: `fly intercept -d`, or something similar.

I'm sure we can come up with a non politically-correct way to destroy something that is currently being hijacked/intercepted...

**Comment by vito** [comment]
I think manually releasing containers would be a bit too hands-on. A simple step we can take is to keep the containers around for a job's latest failed build, and let them expire once the job's next build goes green. We can later expand on this if it's not enough, by e.g. keeping the last N failed build's containers.

We already had a story for this scheduled, so I'll tag this issue with it.
