### ISSUE TITLE
Any sensitive information in the database should be encrypted

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1050]
Today, pipeline config and team auth config are stored in plaintext. This is a pretty big security concern as it means anyone who gains access to the database can then get the credentials for all your resources. Let's, uh, not do that, and encrypt these columns instead.

needed-by concourse/concourse#291 which will build on this for encrypting the Vault key and configuration.

This should be opt-in; if no key is configured, nothing should be encrypted.

The ATC should be statically configured with an encryption key, and pipeline configs and team auth configs should be encrypted with AES GCM (Galois Counter Mode): https://golang.org/pkg/crypto/cipher/#NewGCM. Ask in #concourse-security on Pivotal slack if you have questions.

After doing that, let's have a look for any other places we store sensitive information and consider whether those should be encrypted too.

**Comment by clarafu** [comment]
Resource and job configs should probably also be encrypted.

**Comment by clarafu** [comment]
So this is the current approach I am working on, we have four configs that we need to encrypt (pipeline, team auth, resource and job configs) and every time we encrypt and store the config into the database, we will also store the nonce used to encrypt it. This means we will need to add an extra column in each of the four tables (pipeline, team, resource, and job tables that contain each config) and update that nonce every time we update the config. Also, we will read the nonce from the database whenever we need to decrypt.

**Comment by clarafu** [comment]
As I finished the encryption for team auth, I started looking into the encryption for resources and that lead to me finding radar to still be using some methods from the old db package. After talking with @vito, I'll move the methods over to dbng and only do the encryption from within dbng even for resource type, job and pipeline configs. (Meaning we will move over any methods to dbng that need encryption/decryption)

**Comment by vito** [comment]
Let's start with pre-emptive encryption, i.e. encrypt once the key is configured, rather than doing it only as we perform writes.

**Comment by clarafu** [comment]
Currently, one of the two objects (EncryptionKey and NoEncryption in dbng) are injected into each object (team, pipeline, job, resource, resource type) in atccmd. They are injected depending on if the encryption key flag was passed to atc.
