### ISSUE TITLE
Support RDS IAM Roles

### ISSUE THREAD

**Issue by willejs** [concourse/concourse#1053]
## A Modest Proposal

RDS now supports IAM roles. The IAM service now returns temporary credentials for the RDS instance you can then use to connect to postgres. Which is pretty nice, and secure.

So perhaps we could use the rdsutil package in the awsgosdk to try to get a temporary token for RDS. Im not sure this is that easy of feasible in code though. It does however make configuring concourse on aws secure...

**Comment by chendrix** [comment]
This is if you're using RDS as an external postgres store?

This sounds like a nice-to-have, but probably not something the Concourse team will ever prioritize. There are a possibly-infinite series of configurations of external service dependencies, and we do not want to increase the surface area of Concourse to accommodate that.

This seems to fit pretty naturally in [antipattern: duplicate effort](https://github.com/concourse/concourse/wiki/Anti-Patterns#duplicate-effort)
