### ISSUE TITLE
Forward locally configured CA cert to archive resource config

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1063]
Today the archive-resource needs to `curl -k` to transfer the tarball from `fly execute` if ATC is using an untrusted certificate. It would be better if archive-resource could get a copy of the cacert.

If fly could forward the cacert or -k, depending on how the target is configured, along with the config during `fly execute` that could solve this problem and make Concourse a bit more secure.

---
Moved from concourse/fly#148
/cc @mariusgrigoriu

**Comment by vito** [comment]
this is fixed now
