### ISSUE TITLE
Bad formatting when `fly workers` pipes output

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1064]
```
fly workers
fdcdc43d-cc79-47a6-ba05-a9faaed302d3  0                     none  none  stalled
```

```
fly workers | cat
fdcdc43d-cc79-47a6-ba05-a9faaed302d3  0    none  nonestalled 
```

Expected: The worker status column should have a space in front of it.
Actual: There is no space.

---
Moved from concourse/fly#147
/cc @tom-meyer

**Comment by shashwathi** [comment]
@tom-meyer : Looks like this is fixed in recent versions of `fly`. Closing this issue.
