### ISSUE TITLE
Fly should have a nicer installer on macOS

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1065]
According to [this]concourse/homebrew-tap#1#issuecomment-128770275) the homebrew tap is deprecated, but the recommended alternative (clicking the download link on the ATC) gets me a read-only file called `fly` in my `~/Downloads` directory which macOS Finder (Sierra 10.12.2) thinks is a text file. This is not ideal.

Either a working homebrew formula or a macOS installer .pkg file (which would install fly into a location in my $PATH, set it executable) would be a nicer first-run experience.

---
Moved from concourse/fly#141
/cc @ratkins

**Comment by marco-m** [comment]
I suggest closing this in favour of the rest of the backlog. As a macOS user, I can live with the current status.
