### ISSUE TITLE
Pending builds aren't necessarily pending

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#107]
When a pipeline is paused, no build in it can really be "pending." It would be nice if the pipeline were visibly paused or unpaused without having the sidebar open. One way of doing that would be to introduce a new state to each build that tells you it's not ever going to run while it's paused. Of course, running a one-off build should put the pipeline into actually-pending mode.

**Comment by vito** [comment]
The pipeline bar up top shows up as blue if the pipeline you're in is paused. Granted it comes in via AJAX so it has an annoying delay making it easy to miss at a glance.

A paused pipeline can still have "pending" builds. "Pending" just means no action has been taken yet. "Queued" could be a better word but implies serial semantics.

**Comment by vito** [comment]
This issue is mainly about the terminology which I still think is used correctly. The issue I brought up (slight lag drawing top bar as blue due to AJAX) should be a different issue. Also not sure what you mean by "actually-pending" mode. Gonna mark it closed; I've been staring at it for too long.
