### ISSUE TITLE
Add `fly teams` command

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1072]
**As a** fly cli user
**when I** have targeted a concourse instance
**I can** discover what teams are available to log into with `fly login -n <teamname>`

and

**I can** know what team I'm logged in to currently
**so that** I know

and

**I can** use this list in shell/unix scripts
**so that** I can gather Concourse state across multiple teams if I'm an admin

---
Moved from concourse/fly#129
/cc @cjcjameson

**Comment by vito** [comment]
this was added by a PR
