### ISSUE TITLE
`fly pipelines` is case sensitive to tEam naMe unexpectedly

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1074]
Steps to reproduce:

1. Have a team, such as "Postgres"
2. `fly login -n posTgrEs`
3. Observe that the link in the console corrects the case of the team name in the URL
4. Follow the link -- you are now logged in
5. Observe the following state:
    - `fly pipelines --all` does show all the pipelines, both your team's and other teams' public ones ✅. The team name column shows "Postgres" for your team's pipelines
    - `fly pipelines` shows no pipelines at all 😞 
    - `cat ~/.flyrc` reveals that the case of the original fly login command is kept there 💭 

It's really nice that fly login corrects the case for us to make that smooth. But the corrected case doesn't get persisted into our ~/.flyrc, making further fly commands respond with the wrong information

---
Moved from concourse/fly#128
/cc @cjcjameson

**Comment by cjcjameson** [comment]
I think there had been discussion that this won't be fixed on 2.x but should be fixed for 3.0

Is there a tag or a tracking mechanism that can make sure case-sensitivity in team-names is handled holistically for 3.0?
