### ISSUE TITLE
--exclude-ignored outputs arcane 128 warning when a provided input is not a git directory

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1075]
If you run `fly execute` with `--exclude-ignored` and an `--input` which is not a git directory (i.e. it does not have a `.git` subdirectory), you'll get an error like this: `could not determine ignored files: exit status 128`.  It doesn't seem to break anything but it's likely to confuse users.  The `--exclude-ignored` flag should only apply to inputs that look like git repository roots.

---
Moved from concourse/fly#94
/cc @cjcjameson

**Comment by tanzeeb** [comment]
We're getting this error as well, with the exact same scenario (`-x` with one of the inputs a git directory and the others not). 

However, it looks like it actually impacts the rest of the uploads:

```
could not determine ignored files: exit status 128
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:04:26 --:--:--     0^C
aborting...
```
Nothing gets uploaded, but the command does not exit either.

cc @jama-pivotal
