### ISSUE TITLE
fly execute -x ignores .git directory

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1087]
This presents problems when external dependencies rely on git to compile (_coughetcdcough_).

It'd be great if we could ignore .gitignored files without ignoring .git configuration. 

---
Moved from concourse/fly#55
/cc @cwlbraa

**Comment by marco-m** [comment]
If I understand correctly, you want to upload the .git directory also when -x is specified. This means that fly will potentially upload HUGE amount of data, depending on how big is the git history...

**Comment by cwlbraa** [comment]
this is more than a year old, and I no longer have skin in this game, but at the time I at least wanted the option to upload .git, however large it may be. I doubt etcd is the only project out there that has (had?) git as a build dependency.
