### ISSUE TITLE
fly should offer shell completion

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1098]
Shell completion is very handy. It would be nice if `fly` could offer it the same way `kubectl` does.
- http://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/
- https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/kubectl/cmd/completion.go

---
Moved from concourse/fly#111
/cc @ls-avanier

**Comment by jmcarp** [comment]
See https://github.com/concourse/fly/pull/145, https://github.com/concourse/fly/pull/146. I'm happy to revise those patches as needed if you all have capacity to review, lmk @chendrix !
