### ISSUE TITLE
fly should login automatically if token expired/absent

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1099]
The new `fly login` where there's no need to copy/paste a token is really nice, but usability in general could be improved if instead of running `fly login` manually it would just execute that if it can't find a valid token.

So for example, if I had an expired token and ran `fly execute ...` I should get something like:

```
$ fly execute task.yaml
Could not find a valid token
Please navigate to the following URL in your browser:

    https://terraform.tax.service.gov.uk/auth/github?team_name=main&fly_local_port=54406

or enter token manually:
```

and then proceed to run my task after login.

---
Moved from concourse/fly#131
/cc @cassianoleal

**Comment by cassianoleal** [comment]
🎉
