### ISSUE TITLE
GIFs

### ISSUE THREAD

**Issue by xoebus** [concourse/concourse#110]
![panic-monkey](https://cloud.githubusercontent.com/assets/38814/9101232/2498492a-3b99-11e5-873e-7149119e3f38.gif)

**Comment by xoebus** [comment]
Cold.

**Comment by vito** [comment]
rip

**Comment by pivotal-topher-bullock** [comment]
![](https://media2.giphy.com/media/xTiTneUZ6NoHdYpeE0/giphy.gif)
