### ISSUE TITLE
`fly sync` should exit early if fly is not writable by the user running `sync`

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1100]
I sometimes do this dance:

```
$ fly -t ci sync
downloading fly from https://security.ci.cf-app.com... 
 11.46 MB / 12.59 MB [=========================================================>-----]  91.08% 0supdate failed: open /usr/local/bin/.fly.new: permission denied
$ sudo fly -t ci sync
[sudo] password for pilot: 
downloading fly from https://security.ci.cf-app.com... 
 12.59 MB / 12.59 MB [==============================================================] 100.00% 13s
update successful!
```

It'd be nice if `fly` would exit early if the user running `sync` didn't have write access to `fly` rather than downloading the file and then exiting later.

---
Moved from concourse/fly#132
/cc @krishicks

**Comment by pivotal-topher-bullock** [comment]
Acceptance:
- chmod -w /usr/local/bin
- fly -t ci sync
  version 3.1.2 already matches; skipping
- fly -t wings sync
  update failed:: open /usr/local/bin/.fly.new: permission denied

Update failed prior to downloading the new fly version.
