### ISSUE TITLE
fly set-pipeline returns 1 upon choosing not to apply the configuration

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1104]
`fly set-pipeline` behavior upon a user refusing to apply the changes to a pipeline is not scripting friendly.
One would expect a program to return a code > 0 only when an error happened, the user refusing to apply the changes is not an error and `fly` "bailing out" is totally expected.

It would make more sense to return 0 if no error happened. This would allow for better usability of fly by scripts.

---
Moved from concourse/fly#168
/cc @pdelagrave

**Comment by danger-ranger** [comment]
This is unfortunate. Command failures are easy to handle and work with in a script. Commands happily returning 0, less so.

In our use case after creating a certain kind of pipeline we do a bunch of automated work to it after it is set. With this improvement we have no way to know if the user actually applied the change or not, and so we can't really prevent our scripting from doing all that other stuff when the user made an oops.

**Comment by vito** [comment]
Sounds like we're at an impasse. There are reasons to do both, as requested
by different people. Maybe a flag should be added?

**Comment by danger-ranger** [comment]
Yeah, I was trying to think of a flag to suggest, but I couldn't think of anything that felt right. 

[--error-on-bail-out|-e]

[--bail-out-silently|-b]

??

**Comment by vito** [comment]
That sounds reasonable to me.
