### ISSUE TITLE
Allow startup options to be specified in ENV as an alternative

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1108]
e.g. in Kubernetes I can expose the Pod IP as an ENV VAR for PeerURL usage, but I don't think I can dynamically refer to it in the pod `command` section.

---
Moved from concourse/atc#81
/cc @devth

**Comment by vito** [comment]
@devth I'm not sure what this means. All flags are specifiable as env already. Do you mean to support interpolation of env within the values? Like deferred evaluation?

**Comment by devth** [comment]
Honestly don't remember at this point. If you can already specify all config via ENV then I think this can be closed.
