### ISSUE TITLE
High CPU usage in Chrome with large number of jobs displayed

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1109]
The Diego team has a substantial number of build jobs in its pipeline. When I have a tab open that displays a lot of them, that tab consistently uses 100% CPU or more (screenshots attached). As a result, I typically have to kill that tab in the Chrome Task Manager to conserve battery power on my laptop and to retain enough CPU for the system to perform well, negating the benefit of having the pipeline available continually in a browser tab for quick reference.

Concourse version: 1.3.0
Chrome version: 51.0.2704.84 (64-bit)
OS: Mac OS X 10.10.5
CPU hardware: 2.6 GHz Intel Core i7, 4 cores (hyper-threaded to 8)

Please let me know if there is more information I can provide that would be helpful.

Thanks,
Eric

<img width="1054" alt="chrome-task-manager" src="https://cloud.githubusercontent.com/assets/5836757/16102824/2b20959a-3328-11e6-9378-6d18b9cf2906.png">
<img width="1280" alt="concourse-diego-pipeline-1 3 0" src="https://cloud.githubusercontent.com/assets/5836757/16102823/2a29d08e-3328-11e6-968a-2d11990dec49.png">

---
Moved from concourse/atc#88
/cc @ematpl @vito @jfmyers9 @luan

**Comment by philicious** [comment]
I can add to this that I'm seeing 120% (of 400%) CPU usage on an Intel i7 3+GHz (macbook pro) when the tab is open (firefox) with a very simple pipeline of 2 tasks with 3-4 inputs/outputs.
Concourse: 3.x
MacOS: 10.12

@chendrix your pipeline looks impressive and alot of work must have gone into it. it would probably insta-fry all of my cores.

I didnt even dare yet opening concourse on a RasPi for wallmounted screen

Someone good with frontend stuff should trace this to the culprit. probably some JS madness going on *G

**Comment by chendrix** [comment]
closing as same as #991
