### ISSUE TITLE
rendering bug: resources have resources

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#111]
![screen shot 2015-08-05 at 5 36 14 pm](https://cloud.githubusercontent.com/assets/7230694/9101233/24f35ac2-3b99-11e5-95c9-69d025627e9b.png)

The `p-runtime` resource should be traced back along with the `ert-product`

/ CC @mfine30 @dliebreich

![](http://cdn.meme.am/instances2/500x/1236568.jpg)

**Comment by vito** [comment]
#193 seems to be the same thing and has more info
