### ISSUE TITLE
Bitbucket auth

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1113]
It would be very useful to have Bitbucket authentication added since our organization doesn't use GitHub, and keeping basic-auth doesn't feel like a nice solution.

---
Moved from concourse/atc#106
/cc @kyrias

**Comment by jama-pivotal** [comment]
Linking to a recent PR https://github.com/concourse/atc/pull/215

**Comment by vito** [comment]
Aforementioned PR is now merged - closing!
