### ISSUE TITLE
Login UI does not properly render team name entities

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1115]
In 2.0.0, the login redirect page does not properly render team name entities like spaces.

![screen shot 2016-08-29 at 6 19 35 pm](https://cloud.githubusercontent.com/assets/60754/18072750/7859c412-6e15-11e6-8153-f639b64c2881.png)

---
Moved from concourse/atc#108
/cc @nebhale

**Comment by jama-pivotal** [comment]
Nailed it. Closing 

![screen shot 2017-11-20 at 10 57 28 am](https://user-images.githubusercontent.com/19274230/33027620-9db3c88e-cde1-11e7-92f8-ea70692d385d.png)
