### ISSUE TITLE
API authentication without using basic auth

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1116]
It would be nice to be able to authenticate to the Concourse API in scripts without using basic auth. The current OAuth workflow can only happen in a browser that is logged into Github.

It was mentioned in Slack that there could be another auth type like personal access tokens. There are also other OAuth flows that might make sense.

---
Moved from concourse/atc#42
/cc @mmb @xoebus

**Comment by bonzofenix** [comment]
Where can I read more about concourse/atc#42? We would like to have a way to talk to concourse AP having basic auth and an oauth handler enabled too. Alternatively it would be nice to have a way to generate tokens.

**Comment by n-g-s** [comment]
Good day, any news? It will be nice to have this behavior in Concourse API.

**Comment by sohu234** [comment]
It will be nice to have this behavior in Concourse API.
