### ISSUE TITLE
Option to make pipeline drawer expanded by default

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1118]
Currently the collapsed pipeline 'menu' kind of hides other pipelines for newcomers to the CI until you discover it. Would be nice to be able to have the menu shown be default (and keep hidden toggle state in browser storage) or to be able to set a pipeline overview as starting page instead of the main pipeline.

---
Moved from concourse/atc#48
/cc @aequitas

**Comment by marco-m** [comment]
It looks like the UI changed enough for this to be not applicable any more. @vito ?

**Comment by vito** [comment]
Yeah let's just kill this off. :+1:
