### ISSUE TITLE
Resource icons

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1120]
It would be nice to have icons associated with resources. This way it is easy at a glance to see which type of resource is being in/outputted. And it prevents resource names with the type included.

---
Moved from concourse/atc#64
/cc @aequitas

**Comment by jama-pivotal** [comment]
We'll need to do a few things here:

-[] Get a sense of how those icons will be shown on the UI
-[] specify the preferred image dimensions and preferred formats
-[] define how the icons should be provided (special filename?)
-[] Update docs

**Comment by jama-pivotal** [comment]
Closing in favour of #788
