### ISSUE TITLE
Confusing interface copy for unauthenticated viewers of Concourse instance

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1124]
I work on a project that has open source code in a public GitHub repository, while our Concourse checks for each PR run behind authentication. I noticed a somewhat confusing user experience:

On a public PR (such as https://github.com/18F/cg-docs/pull/434), anyone can click "Show all checks" and click ["Details"](https://ci.fr.cloud.gov/builds/7581) (which is fine). But then the main part of the expected details page shows "loading" and a loading spinner indefinitely (along with "login" in the top right):

![screen shot 2016-09-28 at 2 38 14 pm](https://cloud.githubusercontent.com/assets/391313/18933373/508d28ee-8589-11e6-9610-b94a16c3037f.png)

The console log says I received "401 (Unauthorized)", which makes sense. It would be helpful for this page to explain that it requires login (instead of "loading").

I also noticed that the [homepage for our behind-auth Concourse instance](https://ci.fr.cloud.gov/) is similar - it says "no pipelines configured", but there are pipelines, they're just behind auth - the console log also says "401 (Unauthorized)".

![screen shot 2016-09-28 at 2 48 28 pm](https://cloud.githubusercontent.com/assets/391313/18933649/a684e2c2-858a-11e6-9f2c-49e2ebabaa85.png)

I'm guessing these are things that could be improved in ATC - but if I've guessed wrong and there's actually something wrong with our setup, I'd be curious to know that too. Thanks!

---
Moved from concourse/atc#120
/cc @brittag @kimeberz

**Comment by jama-pivotal** [comment]
we actually fixed part 1 of this, which is that we need to 401 error folks because of users (see #2320 )
