### ISSUE TITLE
UI using Windows (Chrome/Firefox) doesn't load job results.

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1125]
Running the ATC on linux 64bit using standalone binary.
Web UI hangs loading job status using both Firefox and Chrome from Windows systems.

---
Moved from concourse/atc#133
/cc @skyscooby

**Comment by chendrix** [comment]
from @nichegriffy 

>I have confirmed the behavior we are experiencing at my workplace is not a bug with atc, but is instead a bug either with browsers on Windows or is the result of some system misconfiguration. Running the simple SSE server given in this SO answer demonstrates the same behavior: http://stackoverflow.com/a/26089932 . Namely, when accessing the page from localhost or 127.0.0.1, it works as expected, but when accessing it from a non-loopback address (IP or hostname), it hangs indefinitely. Notably, curl is able to access all pages successfully. @skyscooby Can you confirm that you experience the same problem with this server?

> For people who might come across this issue looking for solutions, what we ended up doing as a quick workaround was running a simple proxy server (https://github.com/nodejitsu/node-http-proxy) on our Windows boxes that proxies traffic from 127.0.0.1 to the concourse web server so that the browsers will see a loopback address and be "fooled" into working correctly.

> If someone finds a better solution or is able to pinpoint the true issue, please let me know!

**Comment by skyscooby** [comment]
We did pinpoint this to something within our corporate AV solution.. we are using Sophos End Point Security on all machines which were having this problem.. Unsure if the ATC code is using something rarely used on the greater internet that might be tripping the software.. we stopped digging into exactly what technically was causing it when we found we could whitelist URL's from protection in the policy.
