### ISSUE TITLE
As a user I would like to run a task from the pipeline view

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1129]
# The problem

If I want to run a task manually, I need to open it and click the "+" button on the top right side of a task view. It is inconvenient, because the button is not clickable until the full task output loads its content. So, you have to open view and to wait when the log is loaded and only then you will be able to click the "+" button. 

# Suggested solution

It would be very nice to have some "restart" button with
 :recycle: or :play_or_pause_button: icon on the task in pipeline view. I attached the screenshot how it looks like in the GitLabCI and my suggestion where the button should be.

Thank you.

GitLabCI:
![selection_052](https://cloud.githubusercontent.com/assets/6038179/23616960/55eae034-0283-11e7-9c30-61aba145b686.jpg)

Suggested button in ConcourseCI:
![selection_053](https://cloud.githubusercontent.com/assets/6038179/23616974/601b1380-0283-11e7-8f8d-deaf719c1374.jpg)

---
Moved from concourse/atc#159
/cc @w32blaster

**Comment by w32blaster** [comment]
Awesome! Thanks!
