### ISSUE TITLE
Switching a S3 resource's file from unversioned to versioned causes it to fail with "Specified version doesn't exist"

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#113]
# Reproduction Steps
1. Create a unversioned S3 bucket and add a file ( foo.txt )
2. Create a pipeline that uses a s3 resource pointing to foo.txt
3. Switch the S3 bucket to versioned and upload another file ( bar.txt )
4. Modify the existing s3 resource pointing it to bar.txt
5. At this point foo.txt has no version id and bar.txt does

## Actual
Running the pipeline fails with the following error:
![screen shot 2015-08-06 at 11 23 59 am](https://cloud.githubusercontent.com/assets/1062564/9120202/f20161bc-3c48-11e5-8662-62640ee9144e.png)

## Expected
Running the pipeline should not fail. Pushing the same configuration to a brand new pipeline works.

**Comment by vito** [comment]
This should be working now; `check` will start over from the latest version if the configuration is no longer valid.
