### ISSUE TITLE
Better 404 pages

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1131]
Should be a better 404 page, including a link back to home.

---
Moved from concourse/atc#28
/cc @krishicks

**Comment by Lindsayauchin** [comment]
Proposed Solution: See mock up of new UI for 404 Error page. 

![Error_404.png](https://codetreeusercontent.s3.amazonaws.com/uploads/48c45ff7-a72e-431c-8865-1326bb2fcc95/Error_404.png)

https://www.dropbox.com/s/wdz3g1cha16qfnf/parachute_error_404.svg?dl=0

**Comment by chendrix** [comment]
I think @Lindsayauchin and I also talked a bit about the font and decided to just keep the `font-face: monospace` for the 404 page, so we don't have to worry about figuring out how to include alternative fonts in our design.

**Comment by krishicks** [comment]
Cool.
