### ISSUE TITLE
No timestamps in ATC error logs

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1135]
No timestamps when looking at `atc.stderr.log`, e.g.:

```
failed to set keepalive count: setsockopt: bad file descriptor
failed to set keepalive interval: setsockopt: bad file descriptor
```

Timestamps are in `atc.stdout.log`, e.g.:

```
{"timestamp":"1442945883.213434696","source":"atc","message":"atc.p-redis-deployments:radar.scanner-failed","log_level":2,"data":{"error":"multiple containers found, expected one: 0o59l29o642, 0o546uc66si","member":"p-redis-deployments:bosh-lite-site-changes","session":"1493318"}}
```

---
Moved from concourse/atc#32
/cc @quintessence

**Comment by christophermancini** [comment]
After reviewing the code and production ConcourseCI server logs, I am pretty certain the migration to https://github.com/cloudfoundry/lager resolved this issue. Closing.
