### ISSUE TITLE
Emit metrics directly to InfluxDB

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1138]
# Feature Request

## What challenge are you facing?

We have a Riemann -> InfluxDB -> Grafana metrics stack for some large-scale environments. With more load running against them, we've seen the metrics stop coming in. Restart Riemann fixes it for some time, and then it falls over again later.

## A Modest Proposal

Let's just emit directly to InfluxDB. We should keep Riemann support, as it's still a nice catch-all. This should be pluggable so that we can add more metrics sinks easily in the future or by PR.

**Comment by databus23** [comment]
I just would like to add that I would wish for concourse to alternatively expose prometheus metrics. Maybe the refactoring could also take that into account and make the metrics subsystem pluggable. I'm willing to submit a prometheus driver as soon as a metrics interface allows for that.

**Comment by vito** [comment]
Yep that's the goal; it should be easy to PR providers after this is done.

**Comment by databus23** [comment]
Ok cool. If possible I would like to participate/review as early as possible. Prometheus is a little different from riemann or influxdb as its pull based and more focused around metrics and less on events. Making sure the driver interface works for prometheus is a nice validation that its generic enough to support different metric systems IMO.

**Comment by vito** [comment]
Would https://prometheus.io/docs/instrumenting/pushing/ be sufficient or would that be too annoying to set up? There are some metrics that the ATC emits that don't really make sense in a pull model. For example, builds starting and finishing, per-endpoint HTTP response times, etc.

**Comment by vito** [comment]
Bumping this up in priority since Rieman stability is affecting our ability to monitor our deployments.

**Comment by vito** [comment]
Note: switching from Riemann -> InfluxDB to just emitting directly to InfluxDB, keeping the same dataset, leads to this error:

```
May 11 06:19:24 web-1 atc:  {"timestamp":"1494508763.609342575","source":"atc","message":"atc.worker-containers.emit.failed-to-send-points","log_level":2,"data":{"error":"{\"error\":\"field type conflict: input field \\\"value\\\" on measurement \\\"worker containers\\\" is type int64, already exists as type float\"}\n","session":"241567.1"}}
```

(Probably for other metrics too.)

Seems like Riemann has been emitting everything as `float`s this whole time. These values are really...integers, so we're not gonna switch it out. This means you'll need to blow away your dataset. :( We'll have that in the release notes.

**Comment by vito** [comment]
Also realized that without Riemann we have no toolchain for emitting system metrics (CPU/RAM/disk), as we're relying on the `riemann-emitter`. Going to spin up a [Telegraf](https://github.com/influxdata/telegraf) release to fill that void.

**Comment by timrchavez** [comment]
:+1:
