### ISSUE TITLE
Make it installable with homebrew

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1139]
A lot of Labs projects run CI on Mac Minis. If Concourse was installable with Homebrew, it'd be much easier to pick up and use for client projects.

---
Moved from concourse/bin#13
/cc @jchester

**Comment by jama22** [comment]
@rahulkj built one way to do it; which can be found here https://github.com/rahul-kj/homebrew-tap . It's not maintained by the Concourse core team but its a good start

**Comment by boris1993** [comment]
I still hope that the Concourse core team can maintain an official one.
