### ISSUE TITLE
Misconfiguring a S3 resource doesn't throw an error and job stays in pending state

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#114]
# Reproduction Steps
1. Create a pipeline that uses a s3 resource pointing to a file that doesn't exist
2. Push the pipeline for the first time

## Actual
Job hangs in pending state and doesn't throw an error, while the resource has "Checking Successfully" green.

## Expected
Start the job and throw and error saying fetching resource failed.

## Note
Once a S3 resource has been fetched successfully, then changing the file value to a non-existent field yields the desired error. So the error only happens if the resource has never fetched successfully.

**Comment by TiraO** [comment]
We see a similar issue for a git resource that is configured to run after a build passes, but the build has not passed yet and the step is kicked manually. 

The job animates in the main view, but we see no output and just grey in the job view. Eventually once there is a passing build, it will pick that up and run, but it would be great to see some kind of output like "Waiting for passing build" or something.
