### ISSUE TITLE
Using upstream outputs as inputs is broken on darwin

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1141]
Given the following tasks running on darwin, in this order:

```

---
platform: darwin

inputs:
- name: some-input-from-a-resource

outputs:
- name: some-output

run:
  path: some-input-from-a-resource/some-script
```

```

---
platform: darwin

inputs:
- name: some-input-from-a-resource
- name: some-output

run:
  path: some-input-from-a-resource/some-other-script
```

The bottom task will fail to run because `some-output` has not been mounted in the container. It does **not fail** as you might expect, which is `missing inputs: some-output`.

Using the exact same tasks/scripts on a linux worker was successful.

There were no errors in the garden log associated with this.

---
Moved from concourse/bin#23
/cc @krishicks

**Comment by chendrix** [comment]
issue is https://github.com/vito/houdini/issues/6

---

from @vito

**Comment by andrewedstrom** [comment]
Since vito/houdini#6 was the issue and has now been fixed, I'm assuming this is fixed as well.
