### ISSUE TITLE
Errors returned by the public interface methods are internal

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1142]
I'm trying to use this client library to access to concourse service from inside of one application which I'm developing and because the returned errors are internal, I cannot distinguish them easily (using a type switch or comparing error values) to handle them differently by the logic of my application.
My question is, why errors returned by methods of the public interface are defined in an internal package? Could they be defined in a public accessible package?

Let me show an example of one of the _go-concourse_ functions that I'm using.

I have an instance of a `team` and I'm calling [`Job` method](https://github.com/concourse/go-concourse/blob/master/concourse/jobs.go#L33)

Because `Job` returns a `bool` as second return value, I can clearly identify if [`ResourceNotFondError`]() has been returned by [`connection.Send`](https://github.com/concourse/go-concourse/blob/master/concourse/jobs.go#L45) method because `Job` function has a [`switch` type which is doing so](https://github.com/concourse/go-concourse/blob/master/concourse/jobs.go#L54)

However [`connection.Send`](https://github.com/concourse/go-concourse/blob/master/concourse/internal/connection.go#L72) doesn't only return  such error, it also returns errors from third party libraries or the standard library like [`http.Client.Do()`](https://github.com/concourse/go-concourse/blob/master/concourse/internal/connection.go#L78) and it's ok to return those errors directly to the caller if _go-concouser_ doesn't handle them because it doesn't have any purpose.
What's important for me, and I believe for any consumer of _go-concourse_, is to access to the errors handle/classified by the library, which are defined in [`interna/errors.go`](https://github.com/concourse/go-concourse/blob/master/concourse/internal/errors.go#L27), and returned by [`connection.populateResponse`](https://github.com/concourse/go-concourse/blob/master/concourse/internal/connection.go#L149) which is [called by `connection.Send`](https://github.com/concourse/go-concourse/blob/master/concourse/internal/connection.go#L87)

What I would like is to have the change to identify if the error returned by `Job` method is, for example, an [ErrUnauthorized](https://github.com/concourse/go-concourse/blob/master/concourse/internal/connection.go#L155), just doing simple value comparison check.

Please, if I'm wrong, how I feel that I would have to check these errors, then, I would appreciate if you can tell how I should do it.

Many thanks in advance.

---
Moved from concourse/go-concourse#6
/cc @ifraixedes

**Comment by ifraixedes** [comment]
My apologies to ask you, but I haven't been able to find which is the reason which has closed the issue.
Could you provide me one?
Thanks

**Comment by chendrix** [comment]
This was closed because it's not a development priority for us. It seems like you know the surface area of the issue well enough that maybe you could provide a PR for it?

Please see the [Contributing Guide](https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md) if that interests you!

**Comment by ifraixedes** [comment]
That's I needed to know for being aware what happened with the issue and knowing that you could accept the mentioned change.

Many thanks!
