### ISSUE TITLE
Fligth school corrections

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1143]
## Overall

Error output does not look the same as in the document. 

All red and:
```
hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"./flight-school/ci/test.sh\\\": stat ./flight-school/ci/test.sh: no such file or directory\"\n","Handle":""}

errored
```

Which is actually much harder to read than the error message in the examples.

## Missing steps

- Creating the first script test.sh you need to make the directory `ci` in your flight-school folder. And perhaps better doc about `input`.
- Starting a pipeline, please add something like "Let us create a pipeline: `ci/pipeline.yml`" 
- In general frontload all the filenames and paths. At least I followed along while reading.

Other than that thanks for a step by step, make errors along the way first guide. 

---
Moved from concourse/flight-school#7
/cc @mkrogh

**Comment by davcamer** [comment]
Saw the same bright red error.

**Comment by MasterBroda** [comment]
Hi @chendrix I've just started the flight-school tutorial and I'm facing a similar error.
```
Backend error: Exit status: 500, message: {"Type":"ExecutableNotFoundError","Message":"exec failed: container_linux.go:348: starting container process caused \"exec: \\\"./flight-school/ci/test.sh\\\": stat ./flight-school/ci/test.sh: no such file or directory\"\n","Handle":"","ProcessID":"","Binary":""}

errored
```
I'm not sure how to go forward and ironically the tutorial isn't a big help. This Socratic approach isn't very useful when you're on a deadline.

**Comment by jama-pivotal** [comment]
Closing because we're now pointing folks to use the https://concoursetutorial.com/ by Stark & Wayne instead
