### ISSUE TITLE
Make IP address parametizable

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1144]
There are scenarios were you need/have to change the port this vm is on because of conflicts and whatnot, and you can change it using vagrant but then there are static references to the IP in the repo that causes certain things to break https://github.com/concourse/concourse-lite/search?utf8=%E2%9C%93&q=100

---
Moved from concourse/concourse-lite#16
/cc @scottschulthess

**Comment by vito** [comment]
We'll probably sooner stop providing Vagrant boxes in favor of a `bosh create-env` workflow, which will allow you to pick the IP anyway.
