### ISSUE TITLE
Support service discovery via the magic `127.x.x.x` DNS server

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1145]
Many many people have run into this. Docker Compose and various other magic-Docker-sauce runtimes set up a local DNS server to talk to other components (e.g. a Docker registry or other dependent service), but the address it wires in to the container (`127.0.0.11`) is not reachable from the container's network namespace. Nowadays Garden strips it out, which is an improvement as it won't resolve to the right address anyway, but it'd be nice if this Just Worked.

Is there something we can do, e.g. with https://wiki.archlinux.org/index.php/dnsmasq to forward DNS requests from the container to Docker's DNS server automatically?

Some context for this is in cloudfoundry/guardian#42

---
Moved from concourse/concourse-docker#6
/cc @vito

**Comment by pivotal-topher-bullock** [comment]
Acceptance:
- `docker-compose` with the latest `concourse/concourse-rc` image
- target the composed atc, set a pipeline, run a task, hijack the task container
- from the hijacked container, `apt-get install dnsutils` then `nslookup concoursedocker_concourse-db_1`
- Note that the dns server used is the ip of the host container, and it resolves the ip of the db container :
```
Server:		172.19.0.4
Address:	172.19.0.4#53

Non-authoritative answer:
Name:	concoursedocker_concourse-db_1
Address: 172.19.0.2
```
