### ISSUE TITLE
Funny typo in them identation

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#115]
![screen shot 2015-08-06 at 3 32 05 pm](https://cloud.githubusercontent.com/assets/1062564/9121418/2c7e238c-3c50-11e5-9772-b9ec436db796.png)

## Actual
yaml: line 7: found a tab character that violate intendation

## Expected
yaml: line 7: found a tab character that violates indentation

**Comment by xoebus** [comment]
@xtreme-sameer-vohra As strange as it seems: I think that may be a correct use of grammar. I think *indentation* can be a plural subject so that verb doesn't need to be pluralized too!

If you disagree, please file a bug with the library: https://github.com/go-yaml/yaml

**Comment by xoebus** [comment]
Oh, I didn't see the typo in `intendation`. Yeah, that's broken.

Please could you file a bug upstream at the library above?

**Comment by xtreme-sameer-vohra** [comment]
Done
