### ISSUE TITLE
Add metrics for volumes

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1151]
# Feature Request

## What challenge are you facing?

Currently, the [metrics](http://concourse.ci/metrics.html) only show metrics for the number of containers running on a worker. We would also like to know how many volumes are on each worker, so that we can see if our large Concourse instances are leaking volumes.

## A Modest Proposal

Emit a metric for the number of worker volumes, alongside the number of worker containers.

**Comment by vito** [comment]
Added it to our metrics board. Looks good!

https://metrics.concourse.ci/dashboard/db/concourse
