### ISSUE TITLE
unable to run hello world in macOS Sierra

### ISSUE THREAD

**Issue by davidgarciaMontreal** [concourse/concourse#1158]
# Bug Report

Bug reports are pretty free-form; just replace this with whatever. If applicable, though, please include steps to reproduce. Help us help you!

The following can also be handy:

* Concourse version:
antonios-iMac:con_ci_pipelines antoniogarcia$ concourse -version
2.7.7

* Fly version:
antonios-iMac:con_ci_pipelines antoniogarcia$ fly -version
2.7.7

* Deployment type (BOSH/Docker/binary):
binary
* Infrastructure/IaaS:
* Browser (if applicable):
Safari
* Did this used to work?
First time I try to configure concourse in a Mac OS.
* error:
antonios-iMac:con_ci_pipelines antoniogarcia$ fly -t lite watch --build 16
initializing
no workers satisfying: resource type 'docker-image', platform 'linux'
available workers: 
  - platform 'darwin', tag 'linux'

pipeline for hello.yml: 
[hello.txt](https://github.com/concourse/concourse/files/999496/hello.txt)

**Comment by vito** [comment]
Similar to #533 - we'd need resource types to be implemented for OS X. Currently you need at least one Linux worker to run them.

**Comment by vito** [comment]
I'll leave this open until we document it. @davidgarciaMontreal Is there somewhere in particular you would have expected to see this documented? Maybe in the [Binary installation docs](http://concourse.ci/binaries.html)?

**Comment by vito** [comment]
Note: this should only affect folks running a binary-only setup on OS X. Running Docker technically runs it in a Linux VM.
