### ISSUE TITLE
Configuration to keep successful task containers after completion

### ISSUE THREAD

**Issue by freelock** [concourse/concourse#1160]
# Feature Request

## What challenge are you facing?

After upgrading to 3.0.0, successful task containers are removed immediately after they complete. In our current setup, we hijack into successful containers about as often as failed ones, so it would be useful to keep these around for further diagnosis.

In our case, we have some tasks that output warnings rather than errors -- we don't want them to block the rest of the pipeline, but sometimes may need to investigate further why they are a problem.

In other cases, during development of test scripts we often get unexpected successful results, and it can be very useful to hijack in to see exactly what's going on, as the task containers end up with different environments/tools than we have available elsewhere.

On Slack, @jmcarp notes

> so we could add a `sleep` at the end of the task? it would be nice to configure expiration time in the pipeline yaml or bosh properties instead, but that works

... @vito asked to open an issue to discuss how best to handle.

## A Modest Proposal

For our needs, we don't often need to hijack at all, so it doesn't necessarily make sense to make keeping successful containers around a global setting. I'm thinking most useful would be something along the lines of the "pause" functionality, a button on the task and/or job, along with a corresponding fly command, to "keep next successful container" for the task or all tasks in a job. The containers can then be cleaned up at the next run of the job, or when the option is removed/canceled.

**Comment by pivotal-topher-bullock** [comment]
Might be [antipattern: knobs](https://github.com/concourse/concourse/labels/antipattern%3A%20knobs). I can see how having the option to temporarily keep containers around would be nice, but accidentally leaving that on could be(come) nasty.

**Comment by freelock** [comment]
Well, it might be a knob, but I must say we've been having some trouble with some deployment scripts, and since upgrading to 3.1.0, it's been exceedingly frustrating to try to debug these. When I go to hijack into a successful container, if I don't catch it in the first 5 minutes, it's gone.

Worse, when I manually trigger a job and then hijack in when the task (finally) starts, I'll be in the midst of tracking down the problem when the container is killed and I'm disconnected, mid-diagnosis.

Please do something to make it possible for us to take as long as necessary to get our pipelines working correctly!

**Comment by freelock** [comment]
I would love some sort of manual ability to "keep next run of this job available for debugging" -- a button on the web UI, a fly command. Not a permanent setting, just a flag to debug, which is cleared when the job is next run, or after an hour, or...

We do automatically pause pipelines when they are done, so it would be nice to not have pausing a pipeline kill these debug containers, though I suppose I can revisit our tooling if this turns out to be the best signal to clean them up...

**Comment by vito** [comment]
I think the container being killed while you're debugging might be a Garden
regression. It's supposed to keep the container alive as long as there's an
attached process. I've observed this behavior as well.

/cc @julz

**Comment by vito** [comment]
Opened https://github.com/concourse/concourse/issues/1269 to capture the eager container destroying.
