### ISSUE TITLE
Never ending stream of error messages when attempting `fly login`

### ISSUE THREAD

**Issue by tom-meyer** [concourse/concourse#1161]
I issued `fly -t gpdb5 login` and was confronted with a never ending stream of these messages:

```
or enter token manually: token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token matoken must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually:
```

Pressing Ctl-c is necessary to kill fly.

Our concourse: v2.7.3 (with a [custom fly binary](https://github.com/concourse/fly/pull/164))

**Comment by vito** [comment]
You sure something wasn't piping input to it? e.g. someone holding the enter key? I can't think of any other reason for that to happen. Does this happen every time? Steps to reproduce will be critical for these kinds of weird errors.

**Comment by tom-meyer** [comment]
I reproduced it 3 or 4 times in a row. I'm sure there wasn't a key down, and there was no input piped in to the command.

To resolve this, I deleted the target from the `.flyrc` file, did a `fly login -c` to re-establish the target with a new login token, and after that fly commands executed normally.
