### ISSUE TITLE
Cannot get docker-compose to work, vagrant seems okay

### ISSUE THREAD

**Issue by markalanrichards** [concourse/concourse#1165]
Setup:
-  Xbuntu or Ubuntu Server 16:04 vm in Virtualbox (tried both)
-  Two network adapters 
--  nat translated
--  host-only network adapter.
-  docker-ce from docker repo 
-  docker-compose from pip in a virtualenv
- single pipline from https://concourse.ci/hello-world.html

Note:
I've tested my docker and running bash in a container I can use curl and that is downloading, so I doubt it is my docker setup: it's so simple anyway.

Failure:
Worker is hanging running jobs and fails due to DNS.

Pre 3.0.0 error:
```
* ping https: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:34914->[::1]:53: read: connection refused
* ping http: Get http://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:41184->[::1]:53: read: connection refused
```

3.0.0:
Note: concourse web fails to start first time, failure to migrate db, perhaps because of a race condition with postgres not being available yet, when restarted web seems to be working
Failure:
`{"timestamp":"1494940342.134737968","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to connect to TSA: dial tcp: lookup concourse-web on 127.0.0.11:53: no such host","session":"3"}}
`
I'm not sure why it expects a dns server on 127.0.0.11

Is this just me? Did I miss something I needed to setup?

I've swapped to using vagrant locally which works, but is less secure and I'd prefer docker as an option to deploy to a "prod" env if concourse suits the project.

**Comment by svrc-pivotal** [comment]
the Docker DNS server is always on 127.0.0.11.

What docker network are your containers connecting to?  It looks like for some reason your Docker embedded DNS is not starting up properly.   Do you have a customized /etc/hosts or /etc/resolv.conf ?

**Comment by markalanrichards** [comment]
I haven't modified any config files: it's the most basic install I could think of without customising anything. So brand new vms and just followed the instructions.

Also, if I start another container and run curl to http://registry-1.docker.io/v2/ and that works, suggesting it might be more specific to the concourse container.

I've tried it on two laptops too, on two different networks (I have two broadband lines).

**Comment by chendrix** [comment]
@markalanrichards Is this not the same as #1145

**Comment by markalanrichards** [comment]
@chendrix I'm not sure.
It seems my concourse cannot do anything, it cannot even download docker images.
Whilst #1145 seems to suggest that it only affects local resolution (unless I'm reading it wrong) not internet resolution.
Maybe the recently added https://github.com/concourse/concourse/commit/5aaf83365d3ceee04c6a4a46020c873c99e8afdd will help: I'll give it a go.

**Comment by markalanrichards** [comment]
That seems to have helped!
