### ISSUE TITLE
Members of `main` should be able to see auth type & details of other teams

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1167]
# Feature Request

## What challenge are you facing?

As one of the administrators of a shared Concourse environment, I get a lot of requests for adding teams and changing the authentication of scheme of existing teams. Our organization predominantly uses GitHub team and individual auth. When I administer these teams; I have no way of identifying what Github individual or Github team a concourse team is authenticated against.  Sometimes I just need to know the Github team the Concourse team is set against so I can tell the requester to add themselves to the Github team! 

## A Modest Proposal

When I am logged into main team, when I do `fly -t <team> teams`, in addition to seeing the team name I should see a column telling me what kind of authentication the team is using (basic, git, uaa), and if applicable, the git name / team /org that is attached to the team

**Comment by topherbullock** [comment]
There's an issue which has already made an attempt at this, so we should look into it and whether it fits our needs. Clean it up and merge it 👍 

https://github.com/concourse/atc/pull/181

**Comment by jama-pivotal** [comment]
Hm, I agree there might be some additional security concerns around showing everyone this right off the bat. It would be particularly troublesome in multi-tenant environments to show everyone this information with no sense of roles and responsibilities. I'm going to close this issue for now and potentially revive it when we start tackling RBAC stuff.
