### ISSUE TITLE
resource name with a slash makes resource page inaccessible

### ISSUE THREAD

**Issue by databus23** [concourse/concourse#1168]
Giving a resource a name that contains a slash makes the resource page inaccessible. Apart from that the `/` Doesn't seem to cause any issues.

E.g.:
![image](https://cloud.githubusercontent.com/assets/439223/26130799/c338018a-3a96-11e7-87ee-37305fe66deb.png)

The link generated for this resource is `$EXTERNAL_URL/teams/main/pipelines/$PIPELINE/resources/gcr.io/google_containers/pause-amd64` and it leads to top-most pipeline instead of the resource page for the shown resource.

* Concourse version: `2.7.7`
* Deployment type (BOSH/Docker/binary): `binary`
* Browser (if applicable): `Safari`, `Chrome`
* Did this used to work? `I don't think so`

**Comment by chendrix** [comment]
closing as duplicate of #751
