### ISSUE TITLE
badges are not update on github due to caching

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1169]
# Feature Request

## What challenge are you facing?

Github caches the badges thus the project status is not displaye correctly.

## A Modest Proposal

https://github.com/github/markup/issues/224

According to the above, it is possible for the service to set some http tags to prevent caching without further implications.

The following can also be handy:

* Concourse version: 3.0.0
* Deployment type (BOSH/Docker/binary): Any
* Infrastructure/IaaS: Custom/CoreOS based
* Browser (if applicable): Firefox
* Did this used to work? Before github introduce caching, for sure, now, partially. Old badges are shown instead of current stats.

**Comment by chendrix** [comment]
Closing as same as #835
