### ISSUE TITLE
--vars

### ISSUE THREAD

**Issue by ytolsk** [concourse/concourse#117]
The documentation states that you can pass in values for variables in the yml using --vars "private-repo-key=$(something)", however this inserts an extra "-" before the value, which breaks the yml. It is only possible to get this to work using --vars-from file.

After changing the syntax this is the diff that we got 

 private_key: |-
 private_key: |

**Comment by robdimsdale** [comment]
@vito how do the new fly changes impact this story?

**Comment by topherbullock** [comment]
Closing this issue since it seems to have gone stale, and also:
- interpretation of vars has changed
- Vault integration changes things
- The docs have changed since this issue

If this is still a problem, please re-open another issue
