### ISSUE TITLE
"Hello World" example fails with docker-compose.yml version 3

### ISSUE THREAD

**Issue by mattskone** [concourse/concourse#1173]
Steps to reproduce:
1. Spin up an instance of Concourse in Docker following the [instructions for using the Docker Repsitory](https://concourse.ci/docker-repository.html).
1. Follow the ["Hello, world!" example instructions](https://concourse.ci/hello-world.html), ending with the step "Click the job and then press the [+] button in the top right."

Expected behavior: The task boots up, prints Hello, world!, and completes successfully.

Actual behavior: The task runs for 5 minutes, then fails with error message `resource script '/opt/resource/check []' failed: exit status 137` displayed in the Concourse UI.  The same message is displayed from the Fly CLI if using `watch` to observe the job output in the terminal.

Local environment:
Ubuntu 16.04.1 LTS
Docker version 17.03.1-ce, build c6d412e
docker-compose version 1.13.0, build 1719ceb
concourse/concourse image ID 27473a12ef38

NOTE: Reverting to version 1 in `docker-compose.yml` (remove the `version` and `services` lines) fixes this problem.

**Comment by andrewedstrom** [comment]
Looks like we forgot to add the `CONCOURSE_GARDEN_DNS_SERVER` entry

https://gist.github.com/colthreepv/6b818cfcf296dc1b5c2cf15eb76a140e#gistcomment-1953756

**Comment by Sispheor** [comment]
I have the same issue. But the `CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8` haven't changed anything

Full output
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to unmarshal manifest: error unmarshalling content: invalid character '<' looking for beginning of value
```
