### ISSUE TITLE
Impossible to go into detail view of a job if name contains '/'

### ISSUE THREAD

**Issue by carlo-colombo** [concourse/concourse#1177]
Hi there!

Trying to open the details of job named `send /start` the url change to `http://192.168.100.4:8080/teams/main/pipelines/ttp/jobs/send%20/start` but the view don't change and stays in the home of the pipeline.
![screen shot 2017-05-18 at 5 29 38 pm](https://cloud.githubusercontent.com/assets/505826/26213182/feafcf5e-3bef-11e7-9c9a-d714e79b8d67.png)

* Concourse version: 3.0.1 / 2.7.3
* Deployment type (BOSH/Docker/binary): vagrant
* Infrastructure/IaaS: -
* Browser (if applicable): Chrome Version 57.0.2987.133 (64-bit)
* Did this used to work? no

**Comment by pdelagrave** [comment]
Have you tried escaping the slash `%2f` ?

**Comment by carlo-colombo** [comment]
I tried to encode the / both in the job name and in the address bar.
The job name does not decode (stay `send %2fstart`) and in the url the application get in a  loading state.

![screen shot 2017-05-19 at 9 10 32 am](https://cloud.githubusercontent.com/assets/505826/26239033/727397da-3c73-11e7-9497-77243ab84fcd.png)
![screen shot 2017-05-19 at 9 10 52 am](https://cloud.githubusercontent.com/assets/505826/26239034/7273bd64-3c73-11e7-8dce-9de211eb637c.png)

**Comment by chendrix** [comment]
Closing as same as #751
