### ISSUE TITLE
As a UI user, I would like to have a visual feedback on which pipeline I'm currently looking at

### ISSUE THREAD

**Issue by pdelagrave** [concourse/concourse#1179]
### What challenge are you facing?
It is not obvious for the user to know which pipeline is currently displayed.

Upon selecting a pipeline in the left side list, the pipeline is displayed in the right center section and then there's no more indication of which pipeline you actually chose.

This is especially annoying when you have tens of pipelines that have relatively similar names with relatively similar visual structure and you have to iterate through them.

### A Modest Proposal

1. It would be easy to give the user feedback on which pipeline is currently selected by changing the background color of the currently selected pipeline in the left side list.
2. The top bar could also display the name of the pipeline, as this bar is always visible.

Thanks

Pierre Delagrave

**Comment by chendrix** [comment]
Closing as same as #295
