### ISSUE TITLE
Dialing Postgres should have a reasonable time out

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1182]
This stack dump shows goroutines hanging trying to dial Postgres: https://gist.githubusercontent.com/vito/559fae59677b57a265be22600c101779/raw/83a797db4059413f304a847a98682af6c2882fea/web-1-dump.log

We should have a dial timeout of some reasonable number like 5 minutes.

ref. https://github.com/concourse/wings.concourse.ci/issues/6

**Comment by vito** [comment]
Make sure we retry connecting on timeout. We have a retryable connection driver, just make sure it handles this class of failure.

**Comment by mariash** [comment]
Our hanging server we used for testing:
```
package main

import (
	"fmt"
	"net"
	"os"
	"time"
)

const (
	CONN_HOST = "localhost"
	CONN_PORT = "6543"
	CONN_TYPE = "tcp"
)

func main() {
	// Listen for incoming connections.
	l, err := net.Listen(CONN_TYPE, CONN_HOST+":"+CONN_PORT)
	if err != nil {
		fmt.Println("Error listening:", err.Error())
		os.Exit(1)
	}
	// Close the listener when the application closes.
	defer l.Close()
	fmt.Println("Listening on " + CONN_HOST + ":" + CONN_PORT)
	for {
		// Listen for an incoming connection.
		_, err = l.Accept()
		if err != nil {
			fmt.Println("Error accepting: ", err.Error())
			os.Exit(1)
		}
		// Handle connections in a new goroutine.
		time.Sleep(10 * time.Hour)
	}
}
```

**Comment by pivotal-topher-bullock** [comment]
Nice. Noticed you added it to the atc job's spec here 10a73fed9f3cc8cb81d68eea25f63ce006516498 good stuff!

Used the dummy server process on acceptance on my machine
👍
