### ISSUE TITLE
Metrics for tracking goroutines stuck in "IO wait" for a long time

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1183]
This would reveal when things are stuck, possibly in critical paths which can lead to deadlocks.

ref. https://github.com/concourse/wings.concourse.ci/issues/6

**Comment by mariash** [comment]
It looks like the golang does not expose any API to get goroutines information to nicely filter based on IO wait and how long they are in there. So it seems the only way to do this is to get pprof output and parse it. Similar to https://github.com/golang/go/blob/62956897c1743ee7e79895496180f84432f21d0a/src/net/http/pprof/pprof.go#L199.

**Comment by keithkroeger** [comment]
Can we perhaps make sure that this is not just related to IO wait but any blocking action?
