### ISSUE TITLE
How to get X509 certificates working with S3 compatible resource?

### ISSUE THREAD

**Issue by hgollaEMC** [concourse/concourse#1187]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request

## What challenge are you facing?

Rather than jumping to a solution, describe the problem you're facing, and provide context. It helps us more to understand your problem first. This way we may be able to connect the dots between your issue and others and perhaps come up with a more general proposal, rather than tacking on feature after feature.

## A Modest Proposal

If you've got a suggestion, feel free to place it here - we don't mean to stifle your creativity! It also helps to describe how you arrived at this idea and why it'd work well for you.

# Bug Report

Bug reports are pretty free-form; just replace this with whatever. If applicable, though, please include steps to reproduce. Help us help you!

The following can also be handy:

* Concourse version:
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by chendrix** [comment]
Hi there, this question may be better suited for answering in [slack](https://slack.concourse.ci)
