### ISSUE TITLE
Allow adding a list of private keys for git resources

### ISSUE THREAD

**Issue by mbhave** [concourse/concourse#119]
Currently, if deploy keys are used on github, private submodules cannot be cloned because the same same deploy key can't be used for multiple repos.

**Comment by TiraO** [comment]
We are having this issue as well.

**Comment by xoebus** [comment]
Unfortunately this doesn't look like it's possible with Git. :(

http://stackoverflow.com/questions/10608285/permission-denied-error-when-using-github-deploy-keys

I'd recommend just using robot users who have access to all the submodules instead.
