### ISSUE TITLE
VM as image_resource ?

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#1191]
## What challenge are you facing?

I am investigating concourse (after having used for years buildbot, Jenkins, GoCD) and I have to say the more I understand the "concourse philosophy" (which sadly is not documented) the more I am full of admiration for something really done right.

Although I am a Unix person, I have to deal with products written in C or C++, that need to be built and tested natively on Windows, Mac and Linux.

Since Concourse has container support only for Linux, today the only way to build native code on non-Linux platforms is to do it "old-style" (that is, like all the other CI systems out there):

1. installing (or provisioning with devops tools) all the dependencies needed directly on the worker
2. build and run tests directly on the workers, with the risk of leaving leftovers or changing global state form one build to the other

(At least this is my understanding of Councourse, I am happy to be proven wrong :-)

## A Modest Proposal

Since Windows and Mac do not have container support (yes, maybe Windows starts to have something), I was thinking the following: would it make sense to allow to treat VMs (for example controlled by Vagrant; clone time can be greatly improved by using Virtualbox "linked clone", see https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones) as another type of image_resource / "container" ? The advantage would be the same no-snowflake build experience than Linux/Docker, but on _any_ platform that supports VMs, so at a very minimum Windows and Mac.

Another possibility open by VMs would be to use a Linux concourse worker to perform native builds on Windows VMs (sadly due to Apple's licensing, we would still need a Mac worker to run Mac VMs).

On the other hand, I think that Concourse idea of "streaming" resources from one worker to another (for example, although Windows and Mac workers do not support git resource, it is enough to have a Linux worker to obtain a "magic" streaming of the resource) is simply wonderful, and so I don't need at all these kind of resources available on Windows and Mac.

Would this idea (VM as container) make sense ?

**Comment by chendrix** [comment]
It sounds like you want to write a fake garden implementation that uses VMs instead of real containers.

**Comment by marco-m** [comment]
@chendrix I am still learning concourse and all its concepts and technologies, so I could have missed something (or more!) :-) For me to better understand, what would be the difference between your suggestion of a fake garden implementation and https://github.com/vito/houdini ?

**Comment by chendrix** [comment]
Houdini is also a fake garden implementation, but it just uses folders as its containers. The ask for using VMs would use VMs as the "container"

Sincerely,
Christopher Hendrix

**Comment by marco-m** [comment]
Ah yes, that makes sense! Merci!

**Comment by vito** [comment]
Just chiming in to say a VM-backed Garden backend wouldn't really be "fake". 😛 I think it makes a lot of sense, but we're unlikely to do it ourselves, so I'm going to close this.

If you do tackle this yourself I'd be happy to answer questions about it and maybe even help out - I'll be in Slack!

**Comment by marco-m** [comment]
I have to agree it would be a nice project to learn golang (and Garden and friends) for me!
