### ISSUE TITLE
[Creating Resource] Differences between bash and out scripts

### ISSUE THREAD

**Issue by pfeodrippe** [concourse/concourse#1192]
# Bug Report

* **Concourse version:** 3.0.1
* **Deployment type (BOSH/Docker/binary):** Docker using kubernetes from helm charts with the command ```helm install --name concourse stable/concourse --set imageTag="3.0.1"```
* **Infrastructure/IaaS:** AWS/Kubernetes (using kops)
* **Did this used to work?** Not as a concourse resource

You can check the scripts [here](https://gist.github.com/pfeodrippe/e526ade847d32905cd773b86118c4736), the only difference between the ```script-deis-resource``` and ```out``` are some comments at initialization of the params and at ```cd $source```, I cannot understand what's happening, could someone give me a light here?

I'm to create a deis resource with support only for the ```out``` command, but I'm seeing some differences at the concourse handling between the bash script I've created and the ```out``` script. When I execute ```deis config:push -a $app -p /tmp/env_to_be_pushed``` with the bash script, it works, but it's giving me ```Creating config... ...Error: Unknown Error (409): {"detail":"user changed nothing - release stopped"}``` using the command inside the ```out``` script.

I hijack inside the container and the commands work correctly

**Comment by chendrix** [comment]
Hi there, we were able to fix this issue after talking in slack.

Looks like `deis config:set` changes to take in a file descriptor if the script is called with something on stdin.

Be wary of commands that need stdin inside of resources, and if you ever come to one, you can give the bad command a "fake" stdin by piping `< /dev/null` to it.

**Comment by pfeodrippe** [comment]
I was adressed by @chendrix at slack and the solution was to use `deis config:push -a $app -p $env_to_be_pushed < /dev/null` instead of `deis config:push -a $app -p $env_to_be_pushed`
