### ISSUE TITLE
UAA oAuth redirects to 127.0.0.1

### ISSUE THREAD

**Issue by vChrisR** [concourse/concourse#1196]
# Bug Report

When logging in to a team configured to authenticate against UAA the fly cli returns a url for the user to get a token. The url looks like this: https://ci.domain.com/auth/uaa?team_name=myteam&fly_local_port=38281

When I use that URL I'm can login to UAA but then I get redirected to 127.0.0.1 which is local machine which obviously doesn't give me a token. The token is displayed in the URL though.

When I leave out the "fly_local_port=" part of the url everything works fine.

The problem seems to be in atc/oauth_callback_handler.go. line number 233 shows a hardcoded "127.0.01". If I leave out the fly_local_port it will run line 230 which works fine.

My environment:
Pivotal Cloud Foundry 1.9
Bosh version 260.6
Concourse 3.0.1
Garden-RunC 1.7.0

Problem also existed on concourse version 2.7.0

**Comment by chendrix** [comment]
@vChrisR what did you set up your auth callback in UAA to?

Did you set up your client correctly by following the [UAA Auth docs](http://concourse.ci/teams.html#uaa-cf-auth)?

**Comment by vChrisR** [comment]
Yes I did. And authentication works fine. So I get redirected to UAA, Then redirected back to concourse but the last redirect that should show the actual token is a redirect to 127.0.0.1. As you can see in the code in atc/oauth_callback_handler.go on line 233 that ip (localhost) is hardcoded. 

If I strip out the last part of the url (so just:  https://ci.domain.com/auth/uaa?team_name=myteam) it works perfectly. Bu I don't want to keep telling my users that they should do that. The default should just work imho.

**Comment by mariash** [comment]
@vChrisR fly is going to start a server on localhost. It will automatically open the provided URL in browser for you. Once the redirect happens back to local server, fly will read token from it. Is you fly the same version as concourse (fly sync)? Do you see fly spinning up the server on 127.0.0.1? Is 127.0.0.1 your local machine?

**Comment by labrown** [comment]
I'm running into the same issue.  In my case, I'm running fly on a server that I am ssh'ed into and using Chrome on my desktop.  The URL I receive ends up redirecting to 'http://127.0.0.1:36725/oauth/callback?token=Bearer+....' which doesn't work.

**Comment by vito** [comment]
Closing this; redirecting to 127.0.0.1 is intended, as @mariash said.

@labrown That sounds like a valid case to support - could you open a separate issue?

**Comment by in4sometech** [comment]
@vChrisR Thanks for the workaround. This helps if we running the fly on jump boxes and using URL on local browser
