### ISSUE TITLE
post-stemcell-upgrade, workers are 'stalled' and not working properly

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#1197]
# Bug Report

* Concourse version: 3.0.1
* Deployment type (BOSH/Docker/binary):  BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Any
* Did this used to work? yes

I added a new pipeline to my Concourse last night, which was working fine. This morning, we did a BOSH deploy to update stemcells. My pipeline now has orange inputs for its resources, indicating things like `Get http://127.0.0.1:8080/containers: worker '4dd845d5-4674-450a-a8d9-b324a96bea97' is unreachable (state is 'stalled')`. 

Workers currently look like this:
```
$ fly -t sw workers
name                                  containers  platform  tags  team  state    version
194ac3c7-605a-43b4-acf3-0fc7ba391ce6  27          linux     none  none  running  1.0
23bb2e18-d05a-4993-9036-d184dbbb9542  38          linux     none  none  running  1.0
2ec38083-4838-49fe-8eff-f49b437f7725  24          linux     none  none  running  1.0
4dd845d5-6736-4178-a676-c13982377af4  24          linux     none  none  running  1.0
533c6285-107c-40d6-b31b-f1036702d82a  19          linux     none  none  running  1.0
66637c3a-ce73-4840-8e1c-be5f2ee25827  25          linux     none  none  running  1.0
72fbb47c-1a65-4bd1-9668-0f5f359ad6ae  25          linux     none  none  running  1.0
85526528-aba0-4594-aa28-43682b92454c  31          linux     none  none  running  1.0


the following workers have not checked in recently:

name                                  containers  platform  tags  team  state    version
194ac3c7-3dcf-438e-aeb7-4838c90ff436  93          linux     none  none  stalled  1.0
194ac3c7-9d49-45a6-b9b5-d7baae693a9c  110         linux     none  none  stalled  1.0
23bb2e18-1650-43da-888c-45340ffa9f0e  93          linux     none  none  stalled  1.0
23bb2e18-56ae-4b8d-a742-c8b545dfbaa0  102         linux     none  none  stalled  1.0
2ec38083-7528-4235-946e-509e0ba2b81e  103         linux     none  none  stalled  1.0
2ec38083-9598-4a85-b179-612a0632e8be  105         linux     none  none  stalled  1.0
4dd845d5-4674-450a-a8d9-b324a96bea97  94          linux     none  none  stalled  1.0
4dd845d5-7cbd-4b8b-b8cb-3423e595d289  97          linux     none  none  stalled  1.0
533c6285-40bc-410f-a578-cbd390604cbf  105         linux     none  none  stalled  1.0
533c6285-4c5a-4fce-adde-2cd6f3a2041d  96          linux     none  none  stalled  1.0
66637c3a-8f40-406d-ad9f-f217ff61c595  102         linux     none  none  stalled  1.0
66637c3a-907c-4434-a867-9c037cfaa5f8  81          linux     none  none  stalled  1.0
72fbb47c-3444-41e1-bb7e-d99e73a3a236  88          linux     none  none  stalled  1.0
72fbb47c-7e2b-4f1b-8f58-9bb8e43897b7  99          linux     none  none  stalled  1.0
85526528-1ecb-4e77-b695-40d53cd82bda  82          linux     none  none  stalled  1.0
85526528-51a6-4cfd-842f-0f20b2b164fc  102         linux     none  none  stalled  1.0
```

If I prune all the stalled workers, everything works fine. I suspect half of the stalled workers were caused by a stemcell upgrade yesterday and half of them from today's upgrade, since there are double the amount of stalled workers as current workers.

Something's not right here. The workers should either not become stalled upon VM recreation, or they should be automatically cleaned up, and/or the containers on stalled workers should be recreated on valid workers immediately. Am I missing some configuration in my BOSH manifest that makes this better?

**Comment by vito** [comment]
This likely happened because you performed a parallel deploy with only one TSA.

If all TSAs unreachable during worker draining, the drain exits early without performing the "retire" worker lifecycle: https://github.com/concourse/groundcrew/commit/ad4de166f42b9fa19a6f207fdd5541909fd132bb

This is to avoid having the cluster enter into an unrecoverable state when rotating worker keys, which would leave the workers unable to drain as they cannot connect to the TSA. Another interesting note is that a stemcell update will automatically rotate the default worker key.

In your case the fix is probably to scale up to two TSAs, and explicitly configure a "stable" worker key so that it doesn't get rotated during a stemcell update.

**Comment by geofffranks** [comment]
Thanks, I'll give those both a shot. Should the example manifest on concourse.ci be updated for these changes so others don't run into the issues down the road?

**Comment by andrewedstrom** [comment]
Closing since we seem to have found a fix here.
