### ISSUE TITLE
Aggregate issue: 'too many open files'

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1201]
Please provide:

* Which component is emitting this?
* What files are open? (`lsof -p <process id>`)
* Concourse version
* Deployment type (e.g. binary, Bosh, K8s, Docker)

**Comment by henderjm** [comment]
We saw this a couple of weeks ago, so going by memory
* Which component is emitting this?
  - ATC
* What files are open? (lsof -p <process id>)
  - Socket connections
* Concourse version
  - 2.6.0

Resolution:
1. We initially tried to fix this by bumping our ATC instances, this worked for about a day but ran into the error the next day.
1. So instead, we deployed a [ulimit-release](https://github.com/pivotal-cf/ulimit-release) which increased our number of open files. Have not seen the problem since.

**Comment by defsprite** [comment]
We're seeing a lot of open pipes using the standalone binaries with docker.
It *feels* like they are growing steadily, but I have no definite proof of that yet.

Docker version: `Docker version 17.05.0-ce, build 89658be`
Concourse version: `3.0.1`

```
root@2ba1459bb611:/# date; lsof -Xn 2>/dev/null | wc -l
Wed Jun 21 16:47:52 UTC 2017
1451891
```

When grepping for random pipe, we see something like this:

```
root@2ba1459bb611:/# cat /tmp/lsof-output.txt | grep 713087065
COMMAND     PID   TID     USER   FD      TYPE DEVICE  SIZE/OFF       NODE NAME
concourse     7           root  533r     FIFO   0,10       0t0  713087065 pipe
concourse     7     8     root  533r     FIFO   0,10       0t0  713087065 pipe
concourse     7     9     root  533r     FIFO   0,10       0t0  713087065 pipe
concourse     7    10     root  533r     FIFO   0,10       0t0  713087065 pipe
concourse     7    11     root  533r     FIFO   0,10       0t0  713087065 pipe

<lots more here, TID keeps growing>

concourse     7 65519     root  533r     FIFO   0,10       0t0  713087065 pipe
concourse     7 65522     root  533r     FIFO   0,10       0t0  713087065 pipe
concourse     7 65526     root  533r     FIFO   0,10       0t0  713087065 pipe
runc      45372           root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372  9047     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 11925     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 45374     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 45375     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 45376     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 45377     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 47425     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 47427     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 52636     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 52638     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 61480     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 61486     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 61490     root    1w     FIFO   0,10       0t0  713087065 pipe
runc      45372 61493     root    1w     FIFO   0,10       0t0  713087065 pipe
````

grepping for the PID `45372` shows it's not running anymore (same on the host running docker):

```
root@2ba1459bb611:/# ps ax | grep 45372
28314 ?        S+     0:00 grep --color=auto 45372
```

Of (con)course, the worker with PID 7 is still running:
```
root@2ba1459bb611:/# ps ax | grep  " 7 "
    7 ?        Ssl  1389:15 /usr/local/bin/concourse worker
22851 ?        S+     0:00 grep --color=auto  7 
```

It somehow feels like this should have been cleaned up, or am I missing something?

**Comment by defsprite** [comment]
After moving the (single) worker to bare metal, the situation did not improve at all. We went back to the dockerized version creating a separate concourse worker per team, all hosted on a single host, which resolved the open fd issue.

It seems like the advice of one worker = one physical machine does not work well for bigger hosts and larger team/pipelines setups. Something seems to grow faster than linear with more pipelines/resources/teams.

**Comment by gerhard** [comment]
We are seeing the same issue on concourse/3.3.1, garden-runc/1.6.0 running on bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.15: `dial tcp 10.0.16.38:5432: socket: too many open files`

atc process has a 1024 soft limit & 4096 hard limit:

```sh
cat /proc/$(cat /var/vcap/sys/run/atc/atc.pid)/limits

Limit                     Soft Limit           Hard Limit           Units
...
Max open files            1024                 4096                 files
...
```

**Comment by krishicks** [comment]
I woke up to a reasonably unresponsive Concourse 3.8.0 (BOSH) today.

I tailed the atc logs and found a lot of `too many open files`.

atc.stdout:
```
{"timestamp":"1519924360.727602482","source":"atc","message":"atc.collector-runner.lock-task.acquire.acquired","log_level":0,"data":{"id":[3,-824445620],"session":"55.43157.1","task-name":"collector"}}
{"timestamp":"1519924360.727771759","source":"atc","message":"atc.collector-runner.lock-task.run-task","log_level":0,"data":{"session":"55.43157","task-name":"collector"}}
{"timestamp":"1519924360.727919579","source":"atc","message":"atc.build-collector.start","log_level":0,"data":{"session":"57"}}
{"timestamp":"1519924360.728987694","source":"atc","message":"atc.syncer.lightstep-grafana-plugin:radar.failed-to-get-resource-types","log_level":2,"data":{"error":"dial tcp 10.150.1.3:5432: socket: too many open files","session":"52.91"}}
{"timestamp":"1519924360.729365826","source":"atc","message":"atc.volume-collector-worker-job-runner.failed-to-get-running-workers","log_level":2,"data":{"error":"dial tcp 10.150.1.3:5432: socket: too many open files","session":"63"}}
{"timestamp":"1519924360.729710340","source":"atc","message":"atc.syncer.saladbowl:radar.failed-to-get-resource-types","log_level":2,"data":{"error":"dial tcp 10.150.1.3:5432: socket: too many open files","session":"52.81"}}
{"timestamp":"1519924360.730023623","source":"atc","message":"atc.syncer.sentinel:radar.failed-to-get-resource-types","log_level":2,"data":{"error":"dial tcp 10.150.1.3:5432: socket: too many open files","session":"52.83"}}
{"timestamp":"1519924360.730360985","source":"atc","message":"atc.syncer.streamaggregator:radar.failed-to-get-resource-types","log_level":2,"data":{"error":"dial tcp 10.150.1.3:5432: socket: too many open files","session":"52.85"}}
```

10.150.1.3 is the DB vm. I ssh'd onto that VM and couldn't find any single process with anything approaching the ulimit.

atc.stderr:
```
2018/03/01 17:14:21 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
2018/03/01 17:14:22 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
2018/03/01 17:14:23 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
2018/03/01 17:14:24 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
2018/03/01 17:14:25 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
2018/03/01 17:14:26 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
2018/03/01 17:14:27 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
2018/03/01 17:14:28 http: Accept error: accept tcp 0.0.0.0:443: accept4: too many open files; retrying in 1s
```

Port 80 had the same error as above.

**Comment by krishicks** [comment]
I found on one of the web vms atc had 8272 files open, many of which look like this:

```
atc     20060 vcap 1006u  IPv4 21926737      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:43909->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1007u  IPv4 21927687      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:45518->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1008u  IPv4 21926745      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:43924->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1009u  IPv4 21927491      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:45180->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1010u  IPv4 21926747      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:43928->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1011u  IPv4 21927705      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:45555->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1012u  IPv4 21929118      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:47566->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1013u  IPv4 21929384      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:47856->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1014u  IPv4 21926750      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:43934->bb307894-9c6b-4836-b6b5-6c3afcef8e50.worker.concourse-public.concourse.bosh:7788 (CLOSE_WAIT)
atc     20060 vcap 1015u  IPv4 21954691      0t0    TCP c9f95e3c-5460-4ab0-a73e-b34527d49a6f.web.concourse-web.concourse.bosh:60792->90b7696f-6413-491e-81a2-b74357b24d58.db.concourse-public.concourse.bosh:postgresql (ESTABLISHED)
a
```

**Comment by vito** [comment]
@krishicks Given that those connections are all to BaggageClaim it may be helped by #1959.

**Comment by krishicks** [comment]
Is that a regression from when ContainerTTL was removed?

**Comment by vito** [comment]
Not really, there'd be just as many connections for heartbeating.

**Comment by thelangley** [comment]
We're seeing this behaviour on the web instance which run atc

Concourse version: 4.2.1

We've had to resort to bosh sshing in and amending ulimit soft to higher inside the monit job which starts atc from the current 1024 limit. Once we'd restarted the job via monit, it picked up the new ulimit and has worked nicely.

However, this is not a proper fix as a bosh restart/recreate/upgrade will cause our customisations to be killed.

We did try using the ulimit-release but there appears to be some sort of race condition as the settings were applied to the wrong monit job

From our side, it would be much easier if we could set this via bosh manifest which then get's cascaded down to the atc process. Like this ... https://github.com/concourse/concourse/pull/1530/commits/e9e23a17f87decc571a7851b17759463f58d3518 from @gerhard

**Comment by gerhard** [comment]
The fact that this is still an issue makes me feel sad. What needs to happen for this stop being an issue? Would bpm work?

**Comment by blgm** [comment]
We've just run into this issue with Concourse 4.2.1 but on the baggageclaim job. We've added one pipeline since we upgraded to 4.2.1 but we hadn't seen this issue until we upgraded (we were running 3.14.1 before).

**Comment by michaelklishin** [comment]
After upgrading to 4.x team RabbitMQ has to reap and recreate workers every few days, otherwise no jobs get scheduled. Now that we've found similar reports that point at file descriptors we'll try to `lsof` around on worker VMs next time it happens.

**Comment by thecpdubguy** [comment]
Same here, using 4.0.0 deployed via bosh, I need to recreate vms every few days. Has there been any progress as to identifying what the cause of this is?

**Comment by thelangley** [comment]
Bit of feedback on what we did which vastly improved uptime. Using 4.2.1 now, at scale.

1. Disable syslog config on the web nodes. Our syslog servers are a bit rubbish so don't accept logs sometimes

2. Revert to overlayfs instead of btrfs for baggagereclaim/worker nodes
https://bosh.io/jobs/baggageclaim?source=github.com/concourse/concourse-bosh-release&version=4.2.1#p%3ddriver

3. Ensure that garden-runc-release v1.17.1 is used as it fixes the #1884 bug
https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.17.1

**Comment by vito** [comment]
5.0 will come with an increase to the open files limit, auto-configured in the Bosh release. We don't control how the binaries are deployed though so we can't really do much there, though we may be able to do something for the Docker/K8s setup.

Can anyone affected by this please include a brief description of how their Concourse is deployed? I'll update the issue description to request this as well.

**Comment by thecpdubguy** [comment]
Running into this problem, I have this as a bosh deployment with 1 web vm, one db vm and three worker vms.

The bosh deployment uses these bosh releases
postgres/22
concourse/4.2.2
garden-runc/1.17.1

I was able to bump up the open file limit using some property that I found in another thread but this just prolonged having to recreate the web vm. 

Let me know if you want any more details.

**Comment by kaaustubh** [comment]
We have this issue. But we also have a temporary fix.
We have set up our concourse v4.2.2 on aws instance with one web node instance and multiple worker instance.
On the web node EC2 instance, we increased open file limit as follows.
sudo systemctl -w fs.file-max=16384
sudo vim /etc/sysctl.conf
add line- "fs.file-max=16384"
Save and exit. 
Run the command- sudo sysctl -p

**Comment by xtremerui** [comment]
I dont recall to seeing this in recent versions. Will reopen if it happens again.
