### ISSUE TITLE
You should be able to turn off resource versions in the pipeline

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse#1205]
# Feature Request

## What challenge are you facing?

It seems weird and against the concourse pattern of configuration as code to be able to turn off versions in the UI. 
You can not tell why or when that resource was turned off, and it is difficult to know if it will be safe to turn it back on.

## A Modest Proposal
A resource definition should have a `disabled_versions` attribute, that is a list of disabled versions. It should still show up the same in the UI, but without the power button option to turn it off and on. So, if a version is turned off, there will be a commit message that explains why.

**Comment by jama22** [comment]
I think we addressed most of these concerns with the introduction of pinned resources and adding comments on pinned resources. WDYT @joshzarrabi ?

**Comment by cirocosta** [comment]
Josh might be able to better tell, but I guess the idea is to be able to blacklist versions in the code, rather than adding pinning a single one - is that right, @joshzarrabi ? thx!

**Comment by joshzarrabi** [comment]
@jama22 I agree that its not as much of a concern anymore and I really like the new pinning flow. To @cirocosta's point I think my main concern was being able to change configuration from the UI in the first place, but I guess pinning resources is a special case where it would be annoying to have to `fly set-pipeline` every time you want to try a new version, which is how I assume a lot of people use pinned resources. 

I'll close this issue for now because I don't think its relevant anymore.
