### ISSUE TITLE
Bug Report: animation seems to be stuck flashing in the background!

### ISSUE THREAD

**Issue by mikfreedman** [concourse/concourse#1206]
# Bug Report

We have the public [cf-release pipeline](https://runtime.ci.cf-app.com/pipelines/cf-release) displayed on an information radiator here in the office. 

The machine sleeps every night, but safari had been running the page for a loooooooong time.

I have no real insight into what is deployed how because this is a public pipeline, but it was a weird thing to walk into this morning!

![flashy flashy](http://i.imgur.com/m3fGPHF.gif)

* Concourse version: `v2.7.2`
* Operating system: OSX `10.12.2 (16C68)`
* Browser: Safari `10.0.2 (12602.3.12.0.1)`

**Comment by mikfreedman** [comment]
Also, the GIF doesn't really do justice to the epileptic speed this was actually flashing at

**Comment by jama-pivotal** [comment]
Turns out we just had to wait long enough for Chrome to fix the bug itself! Doesn't happen anymore on new Chrome 70.0.3538.102 (Official Build) (64-bit)
