### ISSUE TITLE
Non Vagrant, Standalone Concourse Running on MacOS getting error base resource type not found

### ISSUE THREAD

**Issue by cjaehnen** [concourse/concourse#1212]
# Bug Report

When running a simple pipeline, hello world, that simply spins up a Ubuntu container and outputs "Hello World" to the console shell, I get this error in the web logs:

{"timestamp":"1495740672.352778673","source":"atc","message":"atc.syncer.hello-world:radar.scan-resource.lock.failed-to-get-lock","log_level":2,"data":{"error":"base resource type not found","pipeline-scoped-name":"hello-world:resource:ci-image","resource":"ci-image","session":"17.489.1.1"}}

Environment info:
Setup custom SSH certs and connects to local PostegreSQL database on same localhost that concourse runs. Modified the default web port to be 9092. Docker is also installed. Deploy pipelines via Fly CLI.

Logs are attached.
[concourse-worker.txt](https://github.com/concourse/concourse/files/1030030/concourse-worker.txt)
[concourse-web.txt](https://github.com/concourse/concourse/files/1030029/concourse-web.txt)

* Concourse version: 3.0.1 (Darwin)
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: macOS
* Browser (if applicable): Chrome
* Did this used to work? Never

Below is what I see from the web interface. The discovering ... just loops endlessly.

<img width="531" alt="screen shot 2017-05-25 at 3 29 39 pm" src="https://cloud.githubusercontent.com/assets/945245/26467251/d12cc562-415f-11e7-939c-fadebd98918f.png">

**Comment by cjaehnen** [comment]
I don't know if this is a bug or something that is missing configuration-wise

**Comment by chendrix** [comment]
@cjaehnen you cannot have a concourse binary deployment without at least one linux worker.

The macOS and windows worker binaries do not come with the base resources, and they also do not use a real containerization solution.

**Comment by cjaehnen** [comment]
So, I just need to download and run a Linux worker to make this function on macOS?

**Comment by chendrix** [comment]
Correct, you need at least one Linux worker talking to your web instance.

Sincerely,
Christopher Hendrix

**Comment by montera82** [comment]
who to setup the Linux worker @chendrix 
i get the same error using the below docker compose file 

``` bash
$ cat docker-compose.yml
version: '3'

services:
  concourse-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: changeme
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
edwin at Edwins-MacBook-Pro-2 in ~/hello_fresh_work/concourse-tutorial-docker

```
