### ISSUE TITLE
Add debug info to step header

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#1216]
There are times when I need to know more information about the environment that a task/step ran in.

For example, knowing which worker the task ran on would let me understand better why an `image_resource` that should have been cached was redownloaded; I'd be able to see which specific worker has downloaded a particular version and be able to investigate better why a particular worker redownloaded the image when I believe it should have been cached.

There are also garden errors that are surfaced, such as `failed to stream in to volume`, that are very hard to debug without knowing which worker the task ran on: Figuring it out means downloading the logs for all workers through `bosh` and `grep`/`zgrep`ing them all, which is tedious.

I'm sure there's more information that would be nice to have in such a debug info section that others could chime in with.

**Comment by mariash** [comment]
@krishicks is there anything else you can think of besides worker name to include in output?

**Comment by mariash** [comment]
including UX area to discuss where to best put this information. It can be first build event for example. Like `running on worker-name`.

**Comment by krishicks** [comment]
The main thing for me is the worker name.

**Comment by krishicks** [comment]
@mariash I've just now seen the retry tab; it would be nice if the debug info contained which information about tries; do these retries run on the same worker?

**Comment by JohannesRudolph** [comment]
+1, I can see this beeing very valuable. With new worker placement strategies hopefully landing in the next release, this debug info would be very valuable to help operators see the actual placement of tasks.

See also the discussion in
https://github.com/concourse/atc/pull/219#issuecomment-342239963
