### ISSUE TITLE
Stalled worker in Concourse 3.0.1

### ISSUE THREAD

**Issue by p-manesh** [concourse/concourse#1217]
# Bug Report

When we moved a working pipeline from Concourse 2.7.2 to 3.0.1 several jobs fails with message 
Post /volumes: net/http: timeout awaiting response headers

we are using three workers and one of the worker stalled [bosh shows all three workers as running]
name                                  containers  platform  tags  team  state    version
264987a4-1db7-4ac0-86a4-acb776e1f6c7  85          linux     none  none  running  1.0
2b54daf7-5667-4669-9282-62aad5543949  86          linux     none  none  running  1.0
AUSE1CICD001                          0           windows   none  none  running  1.0

the following workers have not checked in recently:

name                                  containers  platform  tags  team  state    version
3cba9586-e7f5-460c-8a54-cb8eb03b2478  115         linux     none  none  stalled  1.0

![image](https://cloud.githubusercontent.com/assets/25228625/26508827/e2ee33c8-421b-11e7-8d19-2967c0c6f09f.png)

Baggageclaim error log shows: 
017/05/26 12:36:19 http: Accept error: accept tcp [::]:7788: accept4: too many open files; retrying in 1s
beacon.stdout.log shows entries like:
{"timestamp":"1495423270.562468767","source":"tsa","message":"tsa.connection.channel.register-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: dial tcp 10.40.252.66:7777: getsockopt: connection refused","remote":"10.40.252.66:41728","session":"1.1.1.9"}}
{"timestamp":"1495423270.562944174","source":"tsa","message":"tsa.connection.channel.register-worker.register.failed-to-list-volumes","log_level":2,"data":{"error":"Get http://10.40.252.66:7788/volumes: dial tcp 10.40.252.66:7788: getsockopt: connection refused","remote":"10.40.252.66:41728","session":"1.1.1.9"}}

* Concourse version: 3.0.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work? Yes

**Comment by mariash** [comment]
@p-manesh what do you see when you run `fly workers`?

**Comment by darwin67** [comment]
Not sure if it's the same but I'm seeing something related.

My setup is
- v3.1.1  
- standalone binaries running on AWS instances in an autoscaling group.

What I'm seeing is when autoscale scales down the number of instances, some workers will go `stalled` but ATC will still try to talk to them, resulting in an error message with something like `can't talk to worker ip-10-3-x-x, status is stalled` (will update the error message since it's not happening now)

this mostly happens on resource checking and will block the jobs in the pipeline because new resources will not be retrieved.

**Comment by darwin67** [comment]
actually, nevermind. i totally missed the `--retire-worker` command in the binary and it seems to be working fine now.

**Comment by mariash** [comment]
@darwin67 thanks for update! going to close this issue then

**Comment by p-manesh** [comment]
@mariash Sorry missed your comments. fly workers shows one of the workers as stalled.  BOSH shows all workers as running. 

The following workers have not checked in recently:

name containers platform tags team state version
3cba9586-e7f5-460c-8a54-cb8eb03b2478 115 linux none none stalled 1.0

I was expecting BOSH to restart the worker when the worker was stalled. I had to manully restart/recreate the worker instance with BOSH

**Comment by mariash** [comment]
@p-manesh stalled is worker state in Concourse world. BOSH only will restart worker if it is not running. That means worker was running but for some reason was not able to reach ATC. I would check worker logs next time for errors.

**Comment by p-manesh** [comment]
@mariash Thanks for the clarification. Is there a good way to monitor for stalled worker? (apart from using fly worker)

**Comment by mariash** [comment]
@p-manesh `fly workers` would be a good way. Also, you can setup metrics for concourse monitoring https://concourse.ci/metrics.html. This will show you number of container that is distributed across the workers. If workers are not responding you will see that their numbers drop.
