### ISSUE TITLE
When rebooting worker (offline for more than just a few minutes) not realized as the same identity

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1220]
# Bug Report

Reproduce: Use your laptop as a worker, enable and disable the service (no change in keys or anything) and see the list of unresponsive workers grow.

Since the server in question happens to be powered off by the last person leaving the room, this is quite annoying.

The following can also be handy:

* Concourse version: 3.0.1
* Deployment type: docker/docker
* Infrastructure/IaaS: CoreOS/Fedora

**Comment by drahnr** [comment]
Possible solutions: 
* use ssh keys as identity
* allow to pass a UUID to the worker execution commandline

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/1457. Thanks!
