### ISSUE TITLE
word-wrap job names on pipeline diagram

### ISSUE THREAD

**Issue by mbjelac** [concourse/concourse#1222]
# Feature Request

## What challenge are you facing?

When chaining multiple jobs with triggers and job-passing passing criteria, a pipeline can have 4 or more job "boxes" in its diagram. This means that for non-tutorial pipelines (i.e. real-world stuff), elements of the pipeline diagram are going to be shrunk to fit on the screen horizontally. When the boxes are shrunk, so is their font-size and pretty soon I'll have to zoom in and pan around which will be tedious.

However, vertically there is more space.

## A Modest Proposal

I want to name my jobs more descriptively, e.g. "build" and "deploy" are bad options because as soon as my pipeline achieves the real-world complexity level, I have stuff like "deploy for acceptance tests", "build service", "build simulator", "deploy front-end", etc.

A proposal: Word-wrap the job names on the web pipeline diagram.
Jobs are typically boxes which are more high than wide because of multiple inputs and outputs so they have vertical space for multiple lines of text in them.

The wrap character can be anything, e.g. a dash (since dash-delimiting is a name convention I noticed) or a space (which is accepted in pipeline parsing and display, I checked).

**Comment by mbjelac** [comment]
Hello there again... Not much reaction to my issue except one like and a label. Thanks gals/guys! :)

As the described problem is dangerously near my current CI setup, I wondered if I could solve the issue myself.

However, in a short exploration mission I failed to find a cookbook/documentation of how to setup a local build of the concourse web (I hope I can mock the other parts???). Is there such a thing?

Also, blindly poking around the codebase, I managed to find [this LESS section](https://github.com/concourse/atc/blob/master/web/assets/css/pipeline.less#L93) - could that be the spot to add the word-wrapping for job boxes?

**Comment by jama-pivotal** [comment]
HI @mbjelac , sorry for the lack of response. The labelling activity was actually part of a big research activity we were doing internally to categorize & synthesize common pain points, feedback and feature requests around pipeline visualization. We're actually deep into developing some new pipeline vizualisation schemes and word wrapping will definitely come into play. 

Thanks also for taking some time to try to take a stab at implementing it yourself. If you're still interested, you might find the Contributing guide helpful to getting your local dev Concourse up and running: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
