### ISSUE TITLE
Failing to load long logs after updating to 3.0.1

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#1223]
# Bug Report

Concourse seems to having a hard time loading long logs lately, I have recently updated from 2.7.3 to 3.0.1

The page takes a couple of minutes to load, then becomes "sluggish" and views part of the log... The tab later crashed, when I started to scroll as you can see.

These jobs have beens successful before....

<img width="536" alt="screen shot 2017-05-29 at 14 12 04" src="https://cloud.githubusercontent.com/assets/2795016/26549333/cb40e518-4478-11e7-966d-05cc09a8d32b.png">

The following can also be handy:

* Concourse version: 3.0.1
* Deployment type (BOSH/Docker/binary): Docker
* Browser (if applicable): Chrome
* Did this used to work? Havent noticed this issue before.

![screen shot 2017-05-29 at 14 08 31](https://cloud.githubusercontent.com/assets/2795016/26549314/a9fee756-4478-11e7-80ac-363cfc167a6f.png)
![screen shot 2017-05-29 at 14 05 44](https://cloud.githubusercontent.com/assets/2795016/26549318/afced614-4478-11e7-8981-6ab04ba5dcfb.png)

**Comment by madamkiwi** [comment]
We are also seeing this on v3.8.0.  A workaround is to use `fly watch`.

@acrmp and K

**Comment by jama22** [comment]
Closing due to staleness
