### ISSUE TITLE
use pipeline resource for concourse production pipelines

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1225]
https://github.com/concourse/concourse-pipeline-resource

We should use the pipelines defined in our pipeline repo as the source of truth for our pipelines.

**Comment by robdimsdale** [comment]
If the concourse team is interested, the concourse pipeline resource could probably use some updating - a significant amount of the `fly` codebase was vendored in quite some time ago, so not all new features are available, and updating isn't trivial. We might get some useful feedback on the ATC API too.

**Comment by robdimsdale** [comment]
@vito (and @chendrix etc) it sounds like there may be an issue with configuring pipelines with the resource that was introduced between 2.7.1 and 3.1.1 - see https://github.com/robdimsdale/concourse-pipeline-resource/issues/15

any ideas?

**Comment by andrewedstrom** [comment]
First commit in pipeline-resource that used go-concourse: 2a6ca68ef18de8c8faabbb71d079fc5f9ef3dee4.

So what we need to do is go back to that commit and then readd the changes that have been made to the pipeline-resource repo since, but use fly instead of the api.

**Comment by andrewedstrom** [comment]
Changes since 668e47ad2ff1634c04c50315c609ea5dbf666528:
- Add support for teams
- Update go to 1.6

**Comment by andrewedstrom** [comment]
We have successfully ripped out all the usages of go-concourse and replaced them with fly. Left to be done:

[] Backfill missing tests for out command
[] Add fly sync
[] Turn this into a docker image

**Comment by andrewedstrom** [comment]
Missing tests:
- [ ] What happens if you try to set a pipeline that you don't have auth for.
- [ ] Can you have multiple teams? --> Change existing tests to have third pipeline be for the other team.

fly sync
- [ ] Write tests
- [ ] Run Fly Sync before in and out steps

Docker imagifying
- [ ] Make docker image building jobs in resources pipeline
- [ ] dockerfile needs to have a version of fly in it. The build scripts and/or pipeline itself need to put a version of that binary

**Comment by andrewedstrom** [comment]
We're in the home stretch. Remaining on this story now:

- [ ] Manual testing
All the tests are passing, but we want to spin up a concourse locally and make it update itself using this resource just to confirm it's actually working.

- [ ] Figure out how we want to do the acceptance tests in the resources pipeline
The acceptance tests, like testflight, require that we have a fully functioning concourse installation to update the pipelines on. So we need to either spin up a Concourse when we run the acceptance tests, or we need to have a Concourse sitting around for the tests to run on. We may want to look to the pipeline for acceptance tests that @robdimsdale was using when he owned this resource: https://github.com/robdimsdale/robdimsdale-ci/blob/master/concourse-pipeline-resource-acceptance/pipeline.yml

- [ ] Actually start using this resource to self-update ci.concourse.ci
This was the whole reason we got started on this story. Rewriting the resource and everything else were all yak shaving basically.

**Comment by chendrix** [comment]
We did it!
