### ISSUE TITLE
Refactor DBNG

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1226]
`dbng/pipeline.go` contains several methods which operate on "jobs" exclusively. We should move those over to `dbng/job.go`.

**Comment by andrewedstrom** [comment]
As part of this story, we're also going to attempt to completely kill off the db package once and for all.

**Comment by clarafu** [comment]
After some investigation, the only things left to move over are pipes and locks. Pipe methods will be moved to the team object and the intermediate lock methods are going to be replaced with calling Acquire on the lockFactory itself. The rest of the chore is to clean up code by moving db/lock, db/migrations and db/algorithm to dbng/ and to remove all usages of sqldb in the code.

**Comment by pivotal-topher-bullock** [comment]
Acceptance:
- atc doesn't have a package named `dbng`
- looks like some refactoring happened too :+1:
- also the tests pass still .. LGTM
