### ISSUE TITLE
Migrate flaky atc tests to testflight

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1228]
Some of our tests for the ATC fail randomly and inconsistently. We should move them to testflight in the hope that they will be less flaky

**Comment by jama-pivotal** [comment]
@andrewedstrom do we still want to do this? I know we fixed a lot of flaky tests in tests recently and had to come to terms with some level of flakiness

**Comment by andrewedstrom** [comment]
The atc tests were failing because of the flaky `acceptance` suite. These tests are now skipped when we run the atc unit tests, [as of this commit](https://github.com/concourse/concourse/commit/2f24ab63d6c5a7bffd86e3dede33ff20fcca5ef6) so I am going to go ahead and close this.
