### ISSUE TITLE
S3 resource not triggering jobs

### ISSUE THREAD

**Issue by benmoss** [concourse/concourse#123]
We have an S3 resource that is supposed to trigger a job, but recently it has stopped doing so. We don't control the Concourse deployment, it's Diego's, so not entirely sure if something was changed with it that might have caused it to stop working.

This is the resource: https://diego.ci.cf-app.com/pipelines/main/resources/msi-file. You can see that 487 triggered the job, but after that none of them triggered anything. 492 is the exception because it was manually triggered. Not entirely sure how to determine which version of the S3 resource we are on, but we are on Concourse 139a34a9.

**Comment by xoebus** [comment]
We deployed a fix to the Diego pipeline yesterday to fix stuck builds (v0.59.1). Did this fix the problem?

**Comment by xoebus** [comment]
@benmoss Are you still seeing this issue?

**Comment by benmoss** [comment]
looks like it's been fixed, thanks!
