### ISSUE TITLE
volume issues on darwin worker regression in 3.0.1 or somewhere around that version

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#1231]
# Bug Report

There appear to have been some regressions introduced in the latest versions.

My current workaround on my darwin workers is to change owner of the volumes folder:

    #update permissions:
    chmod -R 755 /opt/concourse/worker/volumes/live/
    sudo chown -R server:staff /opt/concourse/worker/volumes/live

If i dont do this, fastlane or whatever script i run on the workers during my tasks fails, since it cannot create/delete stuff in the volumes.

I also have to run the concourse worker as sudo on the darwin machines, otherwise I get could not create volume... Which makes sense because the /opt/concourse... folders belongs to the root user.

Is there anything that can be done from the concourse side of things to make the darwin worker setup less "hacky"

The following can also be handy:

* Concourse version: 3.0.1
* Deployment type (BOSH/Docker/binary): darwin worker
* Infrastructure/IaaS: na
* Browser (if applicable): na
* Did this used to work? this worked before I upgraded from 2.7.3 to 3.0.1

**Comment by vito** [comment]
I can't think of anything that would have caused this regression. We made it so you *can* run the Darwin binary as non-root, as that's sometimes necessary to e.g. interact with Xcode.

I have no idea what you mean by fastlane and why they wouldn't have permissions. Are they running as a different user than the binary? Are they doing a `su` or something?

You may want to just run the Darwin binary as non-root, and configure `/opt/concourse` to be owned by that user instead.

**Comment by devdavidkarlsson** [comment]
(For other's reference)

During ios development fastlane is just a cli for performing builds and related stuff. It is branch standard.
I am running as sudo, there is nothing in xcode that has any problems with running as a user with root priviledges.

However in the flow of installing pods for project (like npm for ios projects) and performing bundle install 
 it is necessary to be a non root user, hence the su on these commands.

When running tests in the simulator (it is probably what you mean when you say interact with xcode). The root user must have an attached aqua session. That is easily configured.

**So if i remove /opt/concourse and restart the worker as another user the folder will be re-created with permissions for the user that is running the worker?**
