### ISSUE TITLE
Integrate artefact storage

### ISSUE THREAD

**Issue by dmlemos** [concourse/concourse#1232]
# Motivation
At the heart of many pipelines is the building, storage and retrieval of artifacts.

Without an artifact repository, it is up to the developers to configure and decide where to store them. The setup usually ends up being on some IaaS storage account, for instance: `Amazon S3`, `Google Cloud Storage` or `Azure blob storage`. Unfortunately many times the repositories end up actually being Dropbox, OneDrive, etc. :scream_cat: A setup like these brings a myriad of issues, mainly in regards to security, maintainability, quotas, etc.

Yet there is still no clear process how to retrieve and manage them.

These snowflakes, although not directly influenced by concourse, go against the principles of its idempotency.

# Goals
* Concourse should be able to store artifacts
* A job should be able to expose artifacts to concourse in the most clear way
* After a successful job
  * Advertise the artifact URL in the UI
  * Expose an endpoint to download the artifacts from UI and fly :gem:

# A modest proposal
Having had contact with `CircleCI`, I think they make the [best example](https://circleci.com/docs/1.0/build-artifacts/).
Before each build `CircleCI` creates a directory available at `$CIRCLE_ARTIFACTS` environment variable. The artifacts produced by a build can be stored there and become available to use later.

Create settings in concourse to accept a storage endpoint. Either one created as part of the deployment or perhaps managed with a BOSH release.

**This means concourse manages the entire lifecycle of the artifacts:**
* Artifacts belong to a team/pipeline
* Access is inherited from current permissions
* Cleanup of old artifacts - intially in accord with `build_logs_to_retain`

I think upon cleanup, concourse shouldn't care about inacessible links in old jobs.

:gem: `fly` should be able to fetch the artifacts, in similar fashion to [cart](https://github.com/nbio/cart).

**Comment by vito** [comment]
Concourse should never be the source of truth for your assets. That goes against its principle of being an ephemeral tool that externalizes all dependencies. Pipelines should be self-contained and portable from Concourse to Concourse. Your production assets should not be lost when your CI system goes away.

I definitely see the need for better management of "intermediate" artifacts, and UX improvements around accessing those artifacts (especially for things like screenshots from a GUI test suite's failed build). I just don't agree with the initial goal of "Concourse should be able to store artifacts".

The rest of the goals sound like UX improvements for resources, or missing resources, or just avenues not yet explored. For example, you could use a lightweight blobstore like [Minio](https://www.minio.io/) to use the S3 resource in an airgapped environment where S3 itself is not an option. Resources like the S3 resource already have a way of exposing metadata like the URL in the UI, but it could have much better UX (i.e. by making it clickable).

These 3 issues sound relevant to the underlying goals of this issue:

* https://github.com/concourse/concourse/issues/310
* https://github.com/concourse/concourse/issues/365
* https://github.com/concourse/concourse/issues/429

**Comment by dmlemos** [comment]
I can see how the concept is too ambitious for its own good. However some of the ideas in my opinion still carry advantages that shouldn't go against concourse the primitives.

Most of it is UX improvements, but also awareness.

Is the idea of having concourse know about artefacts and being able to get them with `fly` much different than storing logs in a database and retrieving them? Concourse shouldn't care whether these endpoints are valid or not. They become part of a job output, thus stuck in time.

Perhaps the output can be split into too parts. Output log and output results. If it makes sense.

The goal is only to have an optimised lifecycle for artefacts, this is why it is just a proposal (with an important motivation behind it), thanks for replying :)
Anyway I will look into minio. Looks good :)

**Comment by vito** [comment]
Closing this to focus efforts elsewhere. Hope minio is working out for ya!
