### ISSUE TITLE
Movements applied to a pipeline view is applied to all pipelines.

### ISSUE THREAD

**Issue by benbotwin** [concourse/concourse#1234]
# Bug Report

* Concourse version: 3.1.0
* Deployment type: BOSH
* Infrastructure/IaaS: OpenStack
* Browser: Chrome
* Did this used to work? yes in 3.0.1

If you click and drag to move a pipeline around, the movement you applied doesn’t reset when you change the pipeline you’re looking at. The movement applied to the view of one pipeline is applied to all of them.

If I zoom way out of a pipeline and move it just a little bit I'm unable to find any other pipeline when I change views because they have moved just as much, but their view hasn't zoomed out to match. I need to refresh to see any of the pipelines after that because it's faster than dragging the view around looking for them.

**Comment by cfryanr** [comment]
This problem also exists when switching between the tabs at the top of the UI which represent groups.

**Comment by jama-pivotal** [comment]
This should be coming soon! we just closed out #1425 ! Thank you for your patience
