### ISSUE TITLE
Infer from the pipline if a put resource needs to be pulled

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1238]
# Feature Request

## What challenge are you facing?

The problem is in a network constrained environment the `put` step is always followed by a pull.

Instead of always doing a `get` everytime after a `put`, the pipeline contains the information if the resource is used afterwards.

**Comment by dmlemos** [comment]
We have this problem when using the `jtarchie/pull-request` resource on a darwin worker. Some of the repositories are big and it is increasing the build time considerably and unnecessarily!
