### ISSUE TITLE
Failure to run a task using an image containing files with high user and group id

### ISSUE THREAD

**Issue by zaa** [concourse/concourse#1239]
Hi there!

# Bug Report

I am not sure if the issue should be filed with Concourse or Garden/Guardian project, but we first experienced it in Concourse, so I've decided to start here. Feel free to direct me to the correct venue.

## Problem

We have an image built using the following Dockerfile:

```
FROM python:2-alpine

ARG HELM_TILLER_VERSION=v2.4.2
ENV HELM_TILLER_VERSION ${HELM_TILLER_VERSION}

# Helm
RUN mkdir /tmp/helm && \
    curl -L https://storage.googleapis.com/kubernetes-helm/helm-${HELM_TILLER_VERSION}-linux-amd64.tar.gz | tar -C /tmp/helm -xzf - && \
    install -m 755 /tmp/helm/linux-amd64/helm /usr/local/bin/helm && \
    rm -rf /tmp/helm

# helm-diff plugin
RUN mkdir -p /root/.helm/plugins && \
    helm plugin --debug install https://github.com/databus23/helm-diff
```

It turns out that if we try to run the following task in Concourse using the image above:

```
platform: linux
image_resource:
  type: docker-image
  source:
    repository: <IMAGE_REPO>
    tag: <IMAGE_TAG>
run:
  path: sh
  args:
    - -exc
    - |
      pip --version
```

The task stops with an error from pip locating the urllib3 module.

```
+ pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

Funny thing is that the module is there and if we start a docker container from the image, the `pip --version` command works just fine.

I did a bit of digging and found out that the `helm install` command above places the following files into the image:

```
/tmp/helm-diff/diff # ls -la
total 61528
drwxr-xr-x    2 15295480 16945271      4096 Jun  1 06:26 .
drwxr-xr-x    3 root     root          4096 Jun  1 06:26 ..
-rw-r--r--    1 15295480 16945271     11358 May  3 09:13 LICENSE
-rw-r--r--    1 15295480 16945271      1510 May  3 09:13 README.md
-rwxr-xr-x    1 15295480 16945271  62974365 May  3 09:13 diff
-rw-r--r--    1 15295480 16945271       324 May  3 09:13 plugin.yaml
```

Notice the weird user and group ids of the files.
If I change the Dockerfile and add `rm -rf /tmp/helm-*` command after the `helm install`, those peculiar files are not placed into the resulting image and the CI task runs the `pip --version`  without any problems.

FYI, I presume the issue is related to how Concourse and/or Guardian are constructing file system for the container to run a task in. They may hit the issue processing a file with high uid/gid numbers.

* Concourse version: v2.7.3
* Deployment type (BOSH/Docker/binary): Docker + Kubernetes
* Infrastructure/IaaS: AWS

**Comment by vito** [comment]
Can you run `cat /proc/self/uid_map` and `cat /proc/self/gid_map` on the worker container?

If you run the task with `privileged: true`, does it resolve the issue?

**Comment by zaa** [comment]
Results of the uid_map and gid_map run:

```
running sh -exc cat /proc/self/uid_map
cat /proc/self/gid_map
pip --version

+ cat /proc/self/uid_map
         0 4294967294          1
         1          1 4294967293
+ cat /proc/self/gid_map
         0 4294967294          1
         1          1 4294967293
+ pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
failed
```

Creating a pipeline and setting the task's `privileged` attribute to `true` did not help either.

```
+ cat /proc/self/uid_map
         0          0 4294967295
+ cat /proc/self/gid_map
         0          0 4294967295
+ pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

**Comment by vito** [comment]
Might also be worth trying Concourse 3.1.1 which defaults to `overlay` as the filesystem driver.

**Comment by zaa** [comment]
The files are created by the helm-diff plugin installer. It fetches and then extracts the following archive: https://github.com/databus23/helm-diff/releases/download/v2.4.0%2B1/helm-diff-linux.tgz
The archive has the files with uids, gids I mentioned in the report.

ps. ok, we will try to update concocourse and check if the issue is still there.

**Comment by zaa** [comment]
ok, I've tried to run the same task using vagrant box with concourse ci v3.1.1, still no luck

```
executing build 8
initializing
running sh -exc cat /proc/self/uid_map
cat /proc/self/gid_map
pip --version

+ cat /proc/self/uid_map
         0 4294967294          1
         1          1 4294967293
+ cat /proc/self/gid_map
         0 4294967294          1
         1          1 4294967293
+ pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
failed
```

**Comment by vito** [comment]
I don't think there's anything to be done here, to be honest. The `.tgz` has those UIDs in it, we're just preserving them, as did the `helm plugin --debug install` command. You could `chown` them in your Dockerfile to something more reasonable like `0`, or ping the author of the plugin to investigate why the `.tgz` has strange permissions.

I don't know why `pip` is failing but that sounds like it may be a `pip` bug. The behavior is present in both v2.7.3 and v3.1.0, which covers two different filesystems even (`btrfs` and `overlay`), so it doesn't seem like a filesystem issue.

**Comment by zaa** [comment]
I guess the problem is not with the file system, but with the container runtime and how it constructs an image to run.

The thing is, if I start a container with those strange files using docker runtime, I do not get any problems running "pip --version" command. That's why I wanted to check what might be different with the way Concourse runs the image. It appears it does not use Docker to start the container. That's why I presumed the issue has something to do with that runtime (garden, guardian, etc).
