### ISSUE TITLE
Refactor resource cache volume lifecycle to fix overly aggressive duplicate volume GCing

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1243]
Today's volume GCing logic has strayed a bit from the initial model of "when everything I point to is gone, delete me".

Here's the query for finding GC-able volumes:

```sql
SELECT FROM volumes v
LEFT JOIN workers w ON v.worker_name = w.name
WHERE v.initialized
AND v.worker_resource_cache_id IS NULL
AND v.worker_base_resource_type_id IS NULL
AND v.container_id IS NULL
AND w.state IN ('running', 'landing', 'retiring')
```

To be honest, that's pretty straightforward. The only reason for the `workers` join is to not bother trying to GC volumes from stalled workers. The only sketchy bit in my eyes is the `v.initialized` check. We'll get to that later.

There's one gotcha, however: there is *other* logic for GCing volumes, separate from this query. There's a `GetDuplicateResourceCacheVolumes` call we make, which executes this query:

```sql
SELECT FROM volumes v
LEFT JOIN workers w ON w.worker_name
LEFT JOIN volumes dv ON v.resource_cache_id = dv.resource_cache_id AND v.worker_name = dv.worker_name
WHERE NOT v.initialized AND dv.initialized
```

Note that this query does not have some of the constraints from the original.

Here's the user-facing problem: if I've got a build fetching a resource that is a duplicate cache, the volume collector will aggressively remove it, even if the build is in flight. This should never happen.

This relates to the `initialized` value in the first query. I think it's intended to prevent GCing volumes that are actively being written to by a `get` (i.e. in a build), but otherwise would no longer be desired (maybe they're for a version of a resource that we don't want anymore). This is all fine and good, but then the second query provides a loophole.

One other thing to note is that `initialized` is also intended to prevent premature use of a resource cache while it's still being fetched. We look for already-initialized caches, and create one if there isn't one.

So, here's a proposal:

1. When fetching a resource cache, start off with the volume being owned by the container, rather than the resource cache.
1. When fetching is complete, rather than setting `initialized` to `true`, have it additionally point to the resource cache, find-or-creating it if necessary.
1. Remove `initialized`: it's no longer needed! Volumes will only reference a resource cache when they're initialized, and they'll continue to reference the container so long as the container is around, which will prevent the volume from being GCed.

We could even add a `UNIQUE` constraint on `worker_resource_cache_id` to prevent duplicate resource caches from coming in to existence in the first place. Upon hitting a unique constraint failure, we'd just leave the volume to be owned by its container, and it'll go away when the container goes away.

**Comment by clarafu** [comment]
This build demonstrates the problem to fix:

https://ci.concourse.ci/teams/main/pipelines/main/jobs/bosh-testflight/builds/3289
