### ISSUE TITLE
"fly execute --exclude-ignored" broken for mercurial resource

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#1244]
With a pipeline using the mercurial resource

```
resources:
- name: concourse-native
  type: hg
  source:
    uri: https://bitbucket.com/me/myrepo
    branch: default
```

The checked out repo will have a directory named `.hg` (the equivalent of `.git`).

When doing a one-off build with `fly execute`, it will upload the whole repo history, inside the `.hg` directory.

If I try to avoid uploading the `.hg` directory with `--exclude-ignored`, fly prints an error message and stays stuck uploading (have to hit Ctrl-C):

```
 concourse-native> fly -t tutorial execute --exclude-ignored --config ci/build-task.yml
 executing build 34
 could not determine ignored files: exit status 128
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0^C
```

I just double-tested the exact setup but with a git repository and the `.git` directory is not uploaded and the upload succeeds.

* Concourse version: 3.1.1
* Infrastructure/IaaS: Vagrant
* Did this used to work? First time I tried

**Comment by chendrix** [comment]
Moving to the mercurial resource
