### ISSUE TITLE
incorrect certificate for www.concourse.ci

### ISSUE THREAD

**Issue by kkallday** [concourse/concourse#1245]
Hi,

I wasn't sure where to put this issue since its related to the Concourse website - not the product. When navigating to https://www.concourse.ci I'm shown a certificate warning because the server's certificate has a common name  "*.cfapps.io". When navigating to https://concourse.ci the certificate is signed, correctly, for "concourse.ci".

**Comment by chendrix** [comment]
Thank you for letting us know about this!

**Comment by vito** [comment]
I don't think this is worth setting up to be honest. We don't link to or want anyone to go to `www.` and I'd rather not manage two certificates.

**Comment by kkallday** [comment]
Correct me if I'm wrong but I don't think that securing the both `
www.concourse.ci` and `concourse.ci` domains requires two certificates.
Most CAs support this even when you purchase a single domain certificate.

This also runs the risk of breaking old links that use `www.concourse.ci`
domain.

Based on the error message:

```
www.concourse.ci uses an invalid security certificate. The certificate is
only valid for the following names: *.cfapps.io, cfapps.io Error code:
SSL_ERROR_BAD_CERT_DOMAIN
```

Seems like the fix would be to serve up the concourse.ci certificate
(instead of the cfapps one) and the issue would be solved.
