### ISSUE TITLE
Empty pipeline view when viewing a logged-out team's pipeline

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#1249]
The following was discovered on 3.1.0:

When trying to load a page for a different team than the one that I was currently logged in as in a new tab, the new tab showed me: my logged-in team's name in the upper right and that team's viewable pipelines in the sidebar. It also showed me an empty pipeline view.

I would have expected to be shown a login dialog for that target team, or some message stating that I needed to log in to that team to view the pipeline.

To reproduce:

Log in as one team in tab A
In tab B, open a URL to a pipeline that exists for another team
See an empty pipeline view

**Comment by mariash** [comment]
It actually returns 403, not 401, so it does not cause the redirect to login page:

https://github.com/concourse/atc/blob/master/web/elm/src/Pipeline.elm#L160-L161

So we just need to add `||  status.code == 403` everywhere where we handle 401. `loginRedirect` method will redirect to login page of resource's team.

Marking this as `help wanted`.

**Comment by Lindsayauchin** [comment]
[ic_403_error_hand_ic.svg.zip](https://github.com/concourse/concourse/files/1372285/ic_403_error_hand_ic.svg.zip)
![dashboard_403_error](https://user-images.githubusercontent.com/27746614/31392128-70e493c0-ada6-11e7-863b-ed2384ab437b.png)

**Comment by ElfoLiNk** [comment]
Seems still present in Concourse 3.12.

When i open an url of a build on a different team than the one i'm currently logged remains like this

Given: i'm logged in with team A
When: i open an url of a build of team B
Then: i should be redirect to login of team B and then open the required build 

Right now it's stuck in a infinite loading page getting 403.

<img width="118" alt="schermata 2018-05-15 alle 16 07 09" src="https://user-images.githubusercontent.com/1236551/40078988-92bc6c08-5886-11e8-8d93-bacf7bfd80db.png">

**Comment by h4xnoodle** [comment]
Seeing this on 4.2.1

I received a link to a pipeline but when I logged in, I still didn't have access. The console shows 403s that continue to pile up. No UI is shown to alert me of the problem.

![screen shot 2018-11-14 at 11 05 49 am](https://user-images.githubusercontent.com/105841/48495250-922d8900-e7fd-11e8-9e55-c6041f188c8d.png)
