### ISSUE TITLE
Feature request: toggle legend on/off

### ISSUE THREAD

**Issue by rosenhouse** [concourse/concourse#125]
When I have lots of pipelines on my CI board, screen space becomes scarce, and the legend may obscure the pipeline.

![screen shot 2015-08-13 at 1 16 34 pm](https://cloud.githubusercontent.com/assets/4128521/9260602/8cba74f4-41bd-11e5-85de-c3803e07f209.png)

I would like a way to hide the legend in a repeatable way, e.g. via a URL `#fragment` suffix that could be included in a bookmark.

I'm happy to collaborate on a pull-request for this feature, but I'll need some direction on how to get started.

**Comment by xoebus** [comment]
Hi @rosenhouse,

What if we just hid the legend by default until you clicked a small button named "legend" or which had a reasonable icon?

**Comment by rosenhouse** [comment]
That would be cool.

**Comment by jama-pivotal** [comment]
Closing because of the work coming in with #1388  auto-hiding legend. Thanks for the suggestion @rosenhouse and thank you for patiently waiting!
