### ISSUE TITLE
docker-image-resource with ECR workaround broken

### ISSUE THREAD

**Issue by bacoboy** [concourse/concourse#1252]
There is an outstanding issue when doing docker builds via the docker-image resource to ECR for which a workaround was provided [here](https://github.com/concourse/docker-image-resource/issues/101#issuecomment-293661187) by @chendrix.

After the 3.X upgrade, we ran into an issue with the workaround [which is now fixed](https://github.com/concourse/concourse/issues/1178) -- again by @chendrix. 

Since 3.1.? this workaround is now broken again with the only clue being the error message in the console:
```
mount: permission denied (are you root?)
```

@chendrix has confirmed the issue and requested an issue be opened so he can fill in what he knows.  Thanks for the help Chris!

**Comment by p-manesh** [comment]
We also seeing similar error message:

+ mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
mount: permission denied (are you root?)
	
resource_types:
- name: docker-tar-resource
  type: docker-image
  privileged: true
@chendrix : Is there a workaround for this?

**Comment by chendrix** [comment]
there is not currently a workaround other than downgrading to 3.0.1

It's currently prioritized at the top of our backlog, and hopefully we can get someone to look at it for our next release.

**Comment by fverbist** [comment]
I'm running 3.0.1 and get "no basic auth credentials" when trying to push to ECR
what's wrong ?

`resource_types:
  - name: docker-image-2
    type: docker-image
    source:
      repository: concourse/docker-image-resource
      tag: docker-1.12.6
resources:
  - name: genesis-builder-docker-image
    type: docker-image-2
    source:
      repository: xxxx.dkr.ecr.eu-west-1.amazonaws.com/genesis-builder
      aws_access_key_id: concourse-ecr
      aws_secret_access_key: xxxx`

**Comment by chendrix** [comment]
@fverbist

Hi there, we're trying to build up a knowledge base of common questions and answers in StackOverflow and we're trying to use Github for features and bug reports. Would you mind instead posting it to [StackOverflow](https://stackoverflow.com/questions/tagged/concourse)

**Comment by fverbist** [comment]
@chendrix done ;)

https://stackoverflow.com/questions/43733396/jenkins-amazon-ecr-no-basic-auth-credentials

**Comment by chendrix** [comment]
@fverbist why does that say Jenkins and it's from May?

**Comment by fverbist** [comment]
sorry wrong link, I edited since :)

2017-06-28 18:44 GMT+02:00 Chris Hendrix <notifications@github.com>:
