### ISSUE TITLE
possible memory leaks without workers

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1253]
# Bug Report

When running the web node for a few days without a worker, it leaks memory and occupies an order of magnitude more memory than every other process on that machine. The total memory allocation.

dmesg shows
**[473632.390527] Out of memory: Kill process 2068 (concourse) score 862 or sacrifice child
[473632.404931] Killed process 2068 (concourse) total-vm:3277976kB, anon-rss:1819104kB, file-rss:0kB, shmem-rss:0kB**

After a restart (and 2hours idle, no workers) `sudo pmap -x $PID ` shows 699220 kB (which still seems to be quite a bit)

After another reset and 1 worker being present 673728 are consumed.

I only realized this due to the fact that my provider warns me about swap being used extensively.

There are no other services located on this node besides postgres for concourse.

* Concourse version: 3.0.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure: CoreOS

**Comment by chendrix** [comment]
Can you please upgrade to the latest version and let us know whether or not this still persists?

**Comment by drahnr** [comment]
I will test over the next two weeks.

**Comment by drahnr** [comment]
Tested with 3.2.1 over the course of 2 weeks without a worker, no issues popped up.
