### ISSUE TITLE
Proposal: Font Resizing

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#1258]
Issues related to Font size: 

From the Garden team "As you can see, it makes it really hard to see the started/finished information, let alone see the actual times via the hover information. Clicking on the green plus sign is also impossible a lot of the time. We end up having to reduce the font size in Chrome to eliminate the overlap."

![Screen Shot 2017-05-30 at 10.53.04 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/d01aaa13-1d44-408c-b443-56e8da50c62b/Screen+Shot+2017-05-30+at+10.53.04+AM.png)

Also, could be related to:
Logs get weird at different browser sizes #1137 - Can this be solved by allowing the users to adjust the font size up and down?

**Comment by Eulerizeit** [comment]
For further pictorial weirdness:
<img width="709" alt="screen shot 2017-10-16 at 2 23 40 pm" src="https://user-images.githubusercontent.com/9668711/31687274-c67a3d8e-b356-11e7-8644-eafc0e66cd75.png">

**Comment by Eulerizeit** [comment]
Is anything happening with this?

**Comment by jama-pivotal** [comment]
@Eulerizeit we don't have any plans to address it immediately. We're working on new designs for the pipeline view and are hoping to plan for word wrapping and truncation up front. That said, I'm wondering if there's anything we can do short term to make it hurt less while we figure out our new designs 🤔

**Comment by Eulerizeit** [comment]
We have changed out group names and that helps the Group issue. The issue wrt the the timestamps I deal with by shifting it with the Hamburger button.

**Comment by jama22** [comment]
I'm going to close this. We introduced the responsive groups bar and that has solved this immediate problem. And we're always tweaking the UI and font to improve the overall experience. I'm closing this for now. Feel free to enter new suggestions on how the font can be improved :D
