### ISSUE TITLE
Proposal :  Navigation Epic

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#1259]
Navigation Epic to address multiple issues. 
(#1207, #169, #1118, #1117, #125, #1137, #1262, #569, #401, #1130 )

3 pains I see emerging from these issue's and also our user interview's:
I don't know where I am in the system 
I can't see multiple pipelines at once 
When did this pipeline start and when will this be done. 

Issues raised from Users: 

I need to see the current pipeline displayed in the UI showing and the name of the current pipeline.
I need a way to recenter the pipeline view > "reset" button on the pipeline view to resize the pipeline back to it's 
default setting
I need the ability to toggle legend on/off 
I would like a description for each jobs 
I would like a way to show progression through a build 

Supporting Issues/Evidence  
Can't see what pipeline I'm currently looking at in the UI #1207  
Enhancement: more visible display of the current pipeline name #295
concourse/concourse#169 relates to giant pipelines and being able to pan around more efficiently
Option to make pipeline drawer expanded by default #1118
Description in pipeline web page #1117, #569
Feature request: toggle legend on/off #125
Proposal: Font Resizing #1258
Logs get weird at different browser sizes #1137
I would like a simple "global green vs red" view #400
Allow sidebar to be adjustable #1130

Proposal - Through a synthesis of this data and the feedback from our users over the last 2 months. 
I propose the following solution:

Bottom Nav bar 
Contains: 
Breadcrumbs > team and name of the current pipeline 
Settings > Show hide - Legend, re-centre pipeline, Font size 
About > Description of the pipeline with links to Github and Documentation
Share > (TBD) - url link to share out

Hamburger and Home Icon replaced with bottom bar nav
Teams > list 
Pipelines > displayed as a thumbnail

**Comment by topherbullock** [comment]
The new UI should also address the concerns outlined in #1414 and the comments by @paul-guo- 
Specifically lets make sure there is a good view for operators / public pipelines to allow the display of a purpose and a point of contact, so that someone can reach out to a team or pipeline owner.

**Comment by jama-pivotal** [comment]
Closing this because it is a bit messy, but we will be creating follow up issues to address the patterns identified in this mega story (For example, the multi-pipeline stories were created as more actionable issues from the insights derived from this issue)
