### ISSUE TITLE
Bump Postgres Version to 9.5

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1260]
# Feature Request

## What challenge are you facing?

Concourse is currently using PostgreSQL 9.3, a version of Postgres from 2013 [that will be declared "EOL" next year.](https://www.postgresql.org/support/versioning/).

## A Modest Proposal

We should upgrade to 9.5, even though that isn't the most recent version, because a survey with our users showed that 9.5 will provide all the additional functionality that they need. 

9.5 has new semantics including `UPSERT`, something we have had to fake-create for lack of the primitive. Replacing these situations with upserts will likely reduce the total number of queries.

**Comment by vito** [comment]
v3.5.0 enabled a migration path to https://github.com/cloudfoundry/postgres-release. We'll leave our postgres in for one last minor release and then rip it out.
