### ISSUE TITLE
Custom headline in web UI

### ISSUE THREAD

**Issue by jochenehret** [concourse/concourse#1262]
# Feature Request

## What challenge are you facing?

We have many Concourse instances running on different landscapes. The pipelines are always the same. So just from looking at the web UI you can't directly conclude which landscape you are facing. The Concourse VMs are running in a private network and we use SSH tunnels to connect to the web nodes. So the browser URL doesn't tell much about the landscape, either.

## A Modest Proposal

The web UI should have an option to configure a headline. A simple text string right to the "home" icon would be sufficient.

**Comment by Lindsayauchin** [comment]
This is relevant to issue #1259

**Comment by jama-pivotal** [comment]
Closing this issue in favour of https://github.com/concourse/concourse/issues/1508 which will have new designs for navigation bar with breadcrumbs
