### ISSUE TITLE
Volumes for imported worker base resource types should be global, not per-team

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#1266]
Volumes reference a `team_id`, so it seems that we import these every time a different team needs them.

These should be safe to be made global, as opposed to `check` containers, as there should be no form of "hijacking" or anything that can pollute them.

**Comment by xtremerui** [comment]
Done in  https://github.com/concourse/concourse/commit/3a1b5c0926c1f5e4cae0d10cdc08817f77e88372
