### ISSUE TITLE
Feature Request: Paused jobs not to hold `serial_groups` lock

### ISSUE THREAD

**Issue by tscolari** [concourse/concourse#1268]
# Feature Request

## What challenge are you facing?

We have many jobs sharing the same `serial_groups` lock and triggered by the same resource. On each job we are testing a segment of the product, and eventually we need to focus on one of it. The problem is that even if the other jobs are paused (blue) they pulse in graey and hold other jobs from the serial group (that are not paused) from running. Forcing us to cancel that paused run until it releases the lock.

## A Modest Proposal

Once you pause a job, it could not even pulse. Or maybe it could still pulse but only acquire the serial_groups lock once it actually started.

**Comment by clarafu** [comment]
Same as https://github.com/concourse/concourse/issues/520
