### ISSUE TITLE
Containers get destroyed while hijacked

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1269]
# Bug Report

I've noticed that when hijacked into a container, it'll get destroyed even while I'm actively doing things in it. I checked the logs and it looked like Garden's grace-time reaper just straight up killed it. Not our garbage collector, which handles hijacked containers by setting a GraceTime and never touching it again until it disappears from Garden on its own accord.

Seems to be a Garden regression?

/cc @julz

* Concourse version: 3.1.0+
* Deployment type (BOSH/Docker/binary): any
* Infrastructure/IaaS: any
* Browser (if applicable): n/a
* Did this used to work? yes, because we heartbeated to the containers ourselves

**Comment by rogeruiz** [comment]
Thanks. This just bit us again today. 👍🏽

**Comment by dcarley** [comment]
We've been experiencing this too since upgrading Concourse from 2.4 to 3.4.1

We trigger and hijack a task in order to get a shell with the right credentials (from resources). It has been reliably dying with an exit code of 137 after running for 5~6 minutes, regardless of activity.

**Comment by topherbullock** [comment]
Spoke to @julz on the Garden team, and the verdict is that this should work in Garden, so we can leave this on Garden to fix. We don't explicitly remove containers if they have been hijacked, and just leave it up to Garden, mark it as discontinued, and set the GraceTime. Then we check for the container to be actually gone from Garden before finally destroying it in the database.

Going to look into writing a test to verify this against the latest Garden release.

**Comment by jama-pivotal** [comment]
Timebox:  2 days

Spike on this and try and answer the following:
1. When does Garden "pause" the GraceTime counters to stop them from blowing away a container
2. What scenarios do containers with a GraceTime set get removed while hijacked
3. Does this happen when directly using Garden locally, setting a grace time, then hijacking ( using gaol)?

Bonus Round:
1. What's the effort of not using this and implementing our own thing 
2. Is there a regression in Garden we can PR a fix for.

**Comment by pivotal-gabriel-dumitrescu** [comment]
1. Unable to establish when/if Garden calls the pause on the GraceTime, no code found that would make the pause call.
2. Upon expiry of grace time, all containers are removed as expected. 
NOTE/BUG: When the job finished successfully and container was hijacked, the container is still present, but we are unable to access over hijack/intercept commands.
3. It does not happen when using Garden directly with gaol, the grace time is respected. When container is hijacked and connection is still open, the container does not get removed. As soon as the connection is closed, the grace time is respected and the container removed. 

https://github.com/contraband/gaol/blob/master/commands/shell.go#L17-L74 https://github.com/concourse/atc/blob/164ae358c62ef0c05c37dd2779ca7a14c75ffa94/api/containerserver/hijack.go#L86-L218  

``` 
$ docker exec -it 87f7911f7b2a bash 
root@87f7911f7b2a:/# gaol create -r raw:///worker-state/3.6.1/assets/resource-images/archive/rootfs --privileged -g 30s
65fd921e-b1ca-41f0-7785-a732ddf0df9b
root@87f7911f7b2a:/# gaol shell 65fd921e-b1ca-41f0-7785-a732ddf0df9b
65fd921e-b1ca-41f0-7785-a732ddf0df9b:~# ls
65fd921e-b1ca-41f0-7785-a732ddf0df9b:~# exit
root@87f7911f7b2a:/# watch goal list
```

 Bonus Round:
1. Perhaps we can take a look at gaol shell command implementation and understand how Garden container lifecycle works.
2. It does not appear to be a regression in Garden that causes containers to be dropped or become inaccessible.

**Comment by topherbullock** [comment]
Poked at this a bit, and it looks like creating with a grace time and setting the grace time afterwards have slightly different behaviors:
- ✅ As observed creating with a grace time and then running a process and attaching (hijacking)  
- ✅ Creating the container without a grace time, setting the grace time, then hijacking 
- ❌ Creating the container without a grace time, hijacking, then setting the grace time

The issue seems to be with the implementation of grace time, and how it 'pauses' the timebomb to destroy containers.

**Comment by jama-pivotal** [comment]
Blocked on a fix from Garden.
See : cloudfoundry/garden#58

**Comment by pivotal-gabriel-dumitrescu** [comment]
The following test `Hijacked containers [It] does not delete hijacked resource containers from the database, and sets a 5 minute TTL on the container in garden` from `concourse/topgun/hijack_container_gc_test.go:149` has been set to pending until the issue cloudfoundry/garden#58 from garden has been resolved.
