### ISSUE TITLE
Question: Use of the favicon

### ISSUE THREAD

**Issue by elgohr** [concourse/concourse#1270]
Hi there!

Due to the need of having an eye on the pipeline, I developed a notifier which runs as a local application.
The notifier (https://github.com/elgohr/Concourse-Notifier) shows notifications in case of events on the pipeline.
In this way I would like to ask whether it would be ok to use the Concourse favicon as the logo on the system tray?

**Comment by chendrix** [comment]
@vito is probably most knowledgeable about our trademarks

**Comment by chendrix** [comment]
I'm going to say yes.
