### ISSUE TITLE
Write Documentation for Anatomy

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1271]
# Feature Request

## What challenge are you facing?
We have observed that users often request small docs changes, but are resistant to making the changes themselves and then submitting a pull request. 

One possible explanation for this resistance is that we use [anatomy](https://github.com/vito/anatomy) in our docs. Anatomy is a documentation system which is itself undocumented. As a result, if OSS community members want to modify or add to our docs, they have to guess about how anatomy syntax works based on what they see in other files. 

By using an undocumented language like this, we may be scaring off contributors.

## A Modest Proposal
Let's write some docs for anatomy and then point people to them in our docs readme.

(I'm putting this issue in concourse/concourse rather than https://github.com/vito/anatomy because I think it would impact Concourse contributors the most)

**Comment by jama-pivotal** [comment]
Closing issue because of move towards booklit, which is pretty well documented! 
https://github.com/vito/booklit
https://vito.github.io/booklit/
