### ISSUE TITLE
Concourse should always try and parse image_resource/source/tag as a string

### ISSUE THREAD

**Issue by danrspencer** [concourse/concourse#1273]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request

## What challenge are you facing?

While updating one of our tasks we changed to the latest Node image (8.0.0), The guy updating the task was new to Concourse and entered:

```
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8
```

Assuming this was valid since you can `docker up node:8` but we got the error:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to read request: json: cannot unmarshal number into Go struct field Source.tag of type string
```

It looks like field is being parsed as a number by default when possible and is then trying to assign into an incompatible string field. We also tested this with `tag: 8.0` and got the same result.

## A Modest Proposal

A few options / ideas:

- The tag should always be coerced into a string where possible
- A better error message should be generated in the pipeline 
- Possibly during the `set-pipeline` step it could validate it

# Bug Report

As above, could be considered a bug or a feature request depending on your preference :)

**Comment by chendrix** [comment]
This will be fixed in the next version by docker-image-resource#89

Until then you can just quote the number 8.
