### ISSUE TITLE
Missing files in concourse worker running docker-image.  Files exist in non-concourse docker run.

### ISSUE THREAD

**Issue by zambien** [concourse/concourse#1286]
# Bug Report

Using the following Dockerfile:

```
FROM node
RUN npm install -g frisby
RUN npm install -g jasmine-node
RUN npm install -g lodash
WORKDIR /opt/frisby/
ENV NODE_PATH /usr/local/lib/node_modules/
```
 
Files are missing when this is run on a concourse worker.  For example:

```
ls -latr /usr/local/lib/node_modules/jasmine-node/node_modules/jasmine-reporters/src/
total 40
-rw-r--r-- 1 501 dialout   198 Apr 29  2015 load_reporters.js
-rw-r--r-- 1 501 dialout  3312 Apr 29  2015 jasmine.tap_reporter.js
-rw-r--r-- 1 501 dialout 10624 Apr 29  2015 jasmine.nunit_reporter.js
-rw-r--r-- 1 501 dialout 11503 Apr 29  2015 jasmine.junit_reporter.js
drwxr-xr-x 5 501 dialout  4096 Jun 15 01:34 ..
drwxr-xr-x 2 501 dialout  4096 Jun 15 01:34 .
```

Note there are 4 files there.  There are some files missing.

If I run the docker image in docker on the EC2 instance or on my local VM all the files are there:

```
ls -altr /usr/local/lib/node_modules/jasmine-node/node_modules/jasmine-reporters/src/
total 64
-rw-r--r-- 1 501 dialout   198 Apr 29  2015 load_reporters.js
-rw-r--r-- 1 501 dialout  6555 Apr 29  2015 jasmine.terminal_reporter.js
-rw-r--r-- 1 501 dialout  4818 Apr 29  2015 jasmine.teamcity_reporter.js
-rw-r--r-- 1 501 dialout  3312 Apr 29  2015 jasmine.tap_reporter.js
-rw-r--r-- 1 501 dialout 10624 Apr 29  2015 jasmine.nunit_reporter.js
-rw-r--r-- 1 501 dialout 11503 Apr 29  2015 jasmine.junit_reporter.js
-rw-r--r-- 1 501 dialout  4823 Apr 29  2015 jasmine.console_reporter.js
drwxr-xr-x 5 501 dialout  4096 Jun 15 01:29 ..
drwxr-xr-x 2 501 dialout  4096 Jun 15 01:29 .
```

The permissions are the same so this seems like it must be an issue with the filesystem.  I have confirmed that I am pulling the same docker hash for both the concourse worker and the docker containers I am running.

* Concourse version: 3.1.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS:  AWS Ubuntu 16.04
* Browser (if applicable): N/A
* Did this used to work? Unsure.. I started with 3.1.1

**Comment by chendrix** [comment]
I'm confused as to what you mean.

Can you explain more what your reproduction steps are?

**Comment by zambien** [comment]
i just went back to try and reproduce this today and could not so I'm going to close this issue.

I think this had something to do with the version of libraries being pulled by node at the time I was doing a build but since I can't reproduce it I can't be sure.

**Comment by Shugyousha** [comment]
I seem to be encountering the same issue.

We build a container image and use npm and yarn to install our packages
(about 1700 of them). The Dockerfile looks like this.

```
FROM nodesource/jessie
MAINTAINER someone

ENV DISPLAY :99.0

# Add jessie-backports Debian repository
RUN echo "deb http://http.debian.net/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list

# Install dependencies to run Electron
RUN apt-get -qqy update \
  && apt-get -qqy install \
    xvfb \
    libnotify4 \
    libgconf2-4 \
    libnss3 \
    libxtst-dev \
    libc6 \
    libstdc++6 \
    libgcc1 \
    libgtk2.0-0 \
    libasound2 \
    libxrender1 \
    libxss1 \
  && apt-get -qqy install -t jessie-backports --no-install-recommends \
    openjdk-8-jre-headless \
    ca-certificates-java \
  && apt-get -qyy autoremove \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get -qyy clean

# Install yarn
RUN npm install -g yarn@0.17.10

# Install Node.js dependencies
COPY package.json /usr/src/app
COPY yarn.lock /usr/src/app
ARG NPM_AUTH_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > /root/.npmrc \
  && NODE_ENV=development yarn install \
  && rm /root/.npmrc
```

When I run an npm command in the running container using docker
(17.06.0-ce) locally the command succeeds. When I run the same command
in a Concourse task that uses the same container image, npm complains
about a missing module.

It took quite some time to figure it out but it seems like there are files
missing in the container when started for a Concourse task. Those files
are there when looking into the same directory of the container with the
container started locally. The following screenshot illustrates the issue
(note that the image digest of both images are identical).

![missingfiles](https://user-images.githubusercontent.com/500068/29205221-c7e00060-7e7b-11e7-9eed-92fd38fa3116.png)

I saved the output of both "find" commands and compared them below.

[silvan@workarch ~]$ wc -l filesinConcoursecontainer.txt filesinlocalcontainer.txt
   8235 filesinConcoursecontainer.txt
   9566 filesinlocalcontainer.txt

after sorting the two files I get the following results.

[silvan@workarch ~]$ comm -12 filesinConcoursecontainer.txt filesinlocalcontainer.txt | wc -l
8235
[silvan@workarch ~]$ comm -23 filesinConcoursecontainer.list filesinlocalcontainer.txt | wc -l
0
[silvan@workarch ~]$ comm -13 filesinConcoursecontainer.txt filesinlocalcontainer.txt | wc -l
1331

You can see that there are 1331 files/directories missing in the container
started by Concourse. Find the files below.

[filesinConcoursecontainer.txt](https://github.com/concourse/concourse/files/1217200/filesinConcoursecontainer.txt)
[filesinlocalcontainer.txt](https://github.com/concourse/concourse/files/1217201/filesinlocalcontainer.txt)

Do you have an idea why that could be?

**Comment by zambien** [comment]
I was not able to recreate the issue after a few days when I reported this so I closed it.  I guess it may have been an issue in the underlying git clones that were occurring with something being broken in that chain/NPM perhaps with some difference of what was in local cache vs. Concourse.

Of course it could be something else entirely.  Above is just a guess.

If you can recreate this reliably in a fresh local VM and in Concourse maybe this could be looked into by the team?

**Comment by Shugyousha** [comment]
On Sat, Aug 12, 2017 at 12:52:31PM +0000, zambien wrote:
> I was not able to recreate the issue after a few days when I reported
> this so I closed it.  I guess it may have been an issue in the
> underlying git clones that were occurring with something being broken
> in that chain/NPM perhaps with some difference of what was in local
> cache vs. Concourse.

The Concourse build was running several times on our Linux worker, always
printing the same file count. Both my colleague and me got the same
file count which was different from the one in the Concourse task, when
running the container image locally so it was definitely reproducable. We
don't have the same setup anymore though because we had to work around
the issue.


> Of course it could be something else entirely.  Above is just a guess.
> 
> If you can recreate this reliably in a fresh local VM and in Concourse
> maybe this could be looked into by the team?

Since the container contains some proprietary code I sadly won't be able
to make it available. What I can try to do is to search for a minimal
reproducable case. That case will most likely involve NPM in some fashion
since that seems to be the common point in this issue we are having.
