### ISSUE TITLE
Add ability to re-run a job given the same config

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#1287]
Sometimes I want to re-run a job in a pipeline that is configured to pull the latest version of its resources. But when I re-run it, I don't want it to pull the latest; I want to re-run the job as it ran before. I want to run the job with the same input versions it had in some prior run.

Presently to do this I have to check the versions of each of the resources that a particular run of a job ran with, and then disable all of the newer versions of each resource. This is already a chore, but when there are many new versions this becomes an insane chore. At that point it may be seen as easier to re-set the pipeline, but this is then a destructive action that puts the entire pipeline on hold while I'm making my changes, and that's not acceptable.

It would be fantastic if we could just re-run a job with the exact same input versions it had previously.

I also don't want to have to execute a one-off build taking the inputs of the previous job because I want it to be in the build history of that pipeline.

**Comment by chendrix** [comment]
What are you trying to do by re-running a job that you do not currently get out of the way Concourse runs?

Seems very much related to #413

**Comment by krishicks** [comment]
I'm not sure how to elaborate as I believe the use case is called out quite clearly in the issue.

> Sometimes I want to re-run a job in a pipeline that is configured to pull the latest version of its resources. But when I re-run it, I don't want it to pull the latest; I want to re-run the job as it ran before. I want to run the job with the same input versions it had in some prior run.

**Comment by krishicks** [comment]
#413 does cover it, and @vito had it right with his response. My use case is what he calls scenario 2. I'll close this and plus that issue.
