### ISSUE TITLE
Resource cache should be based on resource source and get params

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#1289]
# Bug Report

When using the same resource with different get parameters which version will be cached is at random.

In general get parameters might have a serious effect on the obtained resource - for example, `disable_git_lfs` for git-resource could completely exclude a set of files being fetched.

The cache should be tracked based on combination of the source and the get params, not only on the source

**Comment by vito** [comment]
It already is. We also have explicit tests covering this.

https://github.com/concourse/atc/blob/master/db/resource_cache.go#L29

https://github.com/concourse/testflight/commit/a83993700eba65c322b3e0905c6915a1d413bee3

**Comment by ggeorgiev** [comment]
great. thanks, I was left with the impression that it isn't in the chat. sorry about that.

**Comment by vito** [comment]
no worries!
