### ISSUE TITLE
For Auditing purposes we need to know which logged in / oAuthed user starts/stops a job

### ISSUE THREAD

**Issue by richarddowner** [concourse/concourse#1294]
# Feature Request

## For Auditing purposes we need to know which logged in / oAuthed user starts/stops a job

This may be a duplicate, but I could not find another feature request similar to this.

Currently there is no way to know which user starts/stops a job/task. It is really important to know this for auditing purposes. 

If the user logs in via github oauth, their login name at least should be available to tasks/jobs so that tasks/jobs can send build information to their auditing system of choice. 

@vito (as discussed, apologies could not find a duplicate issue)

**Comment by cnelson** [comment]
It would be extremely helpful to capture who paused / unpaused a job / pipeline as well.

**Comment by marco-m** [comment]
Pretty please :-)

**Comment by chendrix** [comment]
related to #194

**Comment by mariash** [comment]
going to close this issue in favor of this #194
