### ISSUE TITLE
Docker upgrade

### ISSUE THREAD

**Issue by knifhen** [concourse/concourse#1295]
# Bug Report

Hi,
I was running a small concourse 3.1.1 setup in docker-compose. When I updated my docker-compose config to use version 3.2.0 and applied the new config. The web container fails with the following message. The changes I made was to update to the new docker image concourse/concourse:3.2.0 and ran docker-compose up -d to apply. I'm not sure if that is supposed to work or not. I ended up removing the db container and recreating the whole setup to get it working again.

```
failed to migrate database: pq: could not create unique index "volumes_worker_resource_cache_unique"
```

* Concourse version: 3.1.1 to 3.2.0
* Deployment type (BOSH/Docker/binary): Docker compose
* Infrastructure/IaaS: MacMini

**Comment by pms1969** [comment]
I've just hit this too.  On a much larger concourse install.  Both ATC's failing during upgrade.  Previously we were on 3.1.0

**Comment by dumbbell** [comment]
Same here.

* Concourse version: 3.1.1 to 3.2.0
* Deployment type: BOSH
* Infrastructure: AWS

@vito suggested to someone else on the Concourse Slack channel to run the following query on the database to checkt the state:
```
select count(*), worker_resource_cache_id from volumes group by worker_resource_cache_id;
```

In my case, I got the following duplicates:
```
...
     3 |                     1646
     2 |                     1644
     2 |                     2875
...
```

This user had a stalled worker. He pruned it and the duplicated entry was gone. He could update Concourse to 3.2.0 successfully after that.

I don't know how to check for stalled workers or how to prune them now that the ATC is down. I'm sure before the upgrade there was three running workers: two in the same Bosh deployment, one standalone OS X worker not managed by the Bosh deployment. I stopped all of them to no avail.

**Comment by pms1969** [comment]
hmmmmm.  Ok, I've got 1 duplicate after running that select.  I'm currently trying to reload 3.1.0.  But I know prior to the (surprisingly unintended :/ ) upgrade that there were no unpruned workers.  I'll see what happens after I get 3.1.0 back.

**Comment by pms1969** [comment]
OK, looks like I'm completely mullered now.  
```
$ sudo ./start-atc.sh                            
failed to migrate database: Database version (167) is greater than library version (160).
```
guess I'll just have to fix the extra entry.

**Comment by dumbbell** [comment]
I couldn't restore 3.1.1 because the database has now version 167 which is incompatible with version 160 expected by Concourse 3.1.1.

**Comment by pms1969** [comment]
ok, so I just chose one of the volumes (lowest id) from the following query and deleted it.
```
select * from volumes where worker_resource_cache_id = <my duplicate value>;
```

a more succinct way to get the duplicate values is thru

```
select count(*), worker_resource_cache_id from volumes group by worker_resource_cache_id having count(*) > 1;
```

**Comment by dumbbell** [comment]
I just did remove duplicated entries too and it allowed the upgrade to complete. Not sure if the state is correct though.
