### ISSUE TITLE
network access, disable by default

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1302]
# Feature Request

## What challenge are you facing?

Opening concourse to a team of people I never met in RL and I have only limited trust in, need to get access to certain features for the sake of easier debugging for issues that only popup in the CI pipeline. This is - not only - but also the case for open source projects.

## A Modest Proposal

Add a switch per buildplan (next to privileged) to allow to disable network access for most cases.

**Comment by chendrix** [comment]
I don't know what "network access" means, but I'm pretty sure this is already captured in #1209 or #769 or #194 

Closing.

**Comment by drahnr** [comment]
@chendrix I am talking about the container to have not have CAP_NET_ADMIN and friends by default. For CI this would be the default sane behaviour at least for most use cases.

**Comment by chendrix** [comment]
I guess I'm still confused as to what the potential attack vector or problematic behavior is.

What can a person *do* if the container has those permissions set that you don't think they should be able to?
