### ISSUE TITLE
unknown handle ... after cleaning of the workers volumes

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#1305]
# Bug Report

After cleaning of the workers volumes (/opt/concourse/worker/volumes.img) the systems get in state that cannot get out by itself - reporting `unknown handle: ac306f71-3b4a-43eb-5c2d-c1f0fdd11d9c` for most of the resources. Note that the only way to get out of this is to delete all the pipelines that have any of the affected resources - which in most of the cases means all.

The following can also be handy:

* Concourse version: 
3.2.1
* Did this used to work?
Yes, this used to work in 2.x.x

**Comment by chendrix** [comment]
I do not think we have ever officially supported people cleaning out their own volumes.

This *used* to work because volumes used to heartbeat, but it was by virtue of the internals of Concourse, not a supported Concourse pattern.

**Comment by bence-takacs** [comment]
According to @jtarchie: 
"what unknown handle means is that the worker restarted but concourse thinks that worker still has reference to that volume, which it doesn't"
