### ISSUE TITLE
Update release notes to mention that maps cannot be arrays anymore

### ISSUE THREAD

**Issue by mariash** [concourse/concourse#1307]
Apparently prior to 3.2.x params could be provided as array, e.g.

```
params:
- PARAM1: value
- PARAM2: value
```

This is not working anymore and params must be map, e.g.:

```
params:
  PARAM1: value
  PARAM2: value
```

Otherwise, set-pipeline fails with error:

```
error: yaml: unmarshal errors:
  line 14: cannot unmarshal !!seq into map[string]string
  line 44: cannot unmarshal !!seq into map[string]string
exit status 1
```

**Comment by jtarchie** [comment]
@mariash, we did this by [accident](https://github.com/cloudfoundry/loggregator-ci/blob/92d81f62ec52ad4253fe8271e808bce5606ac098/tasks/container-metrics-smoke-test.yml#L4-L5) in another CI deployment. That deployment was on 2.6.x.

**Comment by vito** [comment]
wat

How did this ever work?

**Comment by chendrix** [comment]
bump @vito lol

**Comment by aaronshurley** [comment]
we found this happening to us with `input_mapping`. oops
