### ISSUE TITLE
Please allow custom sorting of jobs organized together vertically

### ISSUE THREAD

**Issue by ry4n1m3** [concourse/concourse#131]
We had 4 parallel pipelines with some conceptual groupings. We recently added a fan-in to synchronize some resource versioning, but in doing so we've lost the conceptual grouping we had without the fan in.

See attached images for a much better idea of what I'm trying to describe (previously, all builds were grouped by upstream source job). The pain we're having is quickly assessing problematic upstream artifacts or any patterns with those artifacts.

Before (grouped by prior job):
![sbtup](https://cloud.githubusercontent.com/assets/384771/9313811/ea154a9c-44d9-11e5-8886-668225691321.png)

After (grouping lost due to fan-in):
![pipeline_ungrouped](https://cloud.githubusercontent.com/assets/384771/9313813/ec56740c-44d9-11e5-8494-4310803a1b58.png)

**Comment by vito** [comment]
We probably won't be implementing custom ordering; in this specific case we should just have a smarter algorithm to figure out a better ordering. There are already similar heuristics in place but it looks like it doesn't figure out this particular configuration.

**Comment by markus0074** [comment]
OK. What I do in this case sounds not nice but it works in my case. I fill up with whitespace to sort it. (ugly)

```
groups:
- name: staging
  jobs:
  - stage-myproject-dev (1. Stage)
  - stage-myproject-test (2. Stage)
  - stage-myproject-int   (3. Stage)
  - stage-myproject-live   (4. Stage)
```

**Comment by nickeeromo** [comment]
For anyone else who sees this: to be clear, the default ordering is first by character size of the job name (smallest on top), THEN alphabetically.

so for 
jobs:
- authorizer
- stripe-setup
- stripe-events

that would be the order. 

but for
jobs:
- applesauce
- candy
- elephantee

The order would be candy, applesauce, elephantee.

You can cascade them like @markus0074 did, basically adding extra characters. This appears to still be the case in 2022.
