### ISSUE TITLE
Fresh Run of ConcourseCI in docker compose yields error w/ Hello World

### ISSUE THREAD

**Issue by cdaringe** [concourse/concourse#1311]
# Bug Report

hi all,

i am not able to run the docker-compose example out of the current concourseci docs.

all services are running fine when exec'ing `docker-compose up` from the cli.

however, on execution of the provided hello world pipeline, the following error occurs.

```
concourse-worker_1  | {"timestamp":"1498099623.253074646","source":"guardian","message":"guardian.create.create-failed-cleaningup.cleanedup","log_level":1,"data":{"cause":"devices: disable multicast snooping: operation not supported","handle":"045f5529-2ed2-4f59-57a9-6cff85cb83b6","session":"24.6"}}
```

```
# docker-compose.yml
version: '3'

services:
  concourse-db:
    image: postgres:9.5
    volumes:
      - '/database:/database'
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: changeme
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
```

```
# hello-world.yml
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
```

<img width="494" alt="screen shot 2017-06-21 at 7 47 45 pm" src="https://user-images.githubusercontent.com/1003261/27415386-9d1a9f76-56bb-11e7-906f-b658b930af1f.png">

it also gives me the following error periodically--its a race of sorts to determine which error message gets posted:

```
Get /volumes/6341693d-5b88-46ca-75e5-360782d3ff3e: worker 'aac9df7a5df9' is unreachable (state is 'stalled')
```

The following can also be handy:

* Concourse version: (uhh errr latest?  pulled today, 6/20/17)
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS: fresh ubu 16.04 on the could
* Browser (if applicable): chrome
* Did this used to work? first time user!

**Comment by thestevenbell** [comment]
I am getting the same error: ` "cause":"devices: disable multicast snooping: operation not supported" `.  
OS: RHEL 7
Concourse Version: 3.3.1
Deployment of Concourse via Docker
Browser: Chrome
Did this used to work: No, this is the first time trying to use Concourse on this RHEL 7 server.  The same build works on a fresh Ubuntu 16 server.

**Comment by cdaringe** [comment]
mine was on an Ubuntu box not RHEL.  I did try on Ubuntu latest and the
problem vanished. :/

**Comment by PurHur** [comment]
Got an result? I wanna try to build my dream... to build a fucking huge dependency shit ci pipeline and that project looks great but all my resources fail with that. time and git.

**Comment by PurHur** [comment]
This bug is not fixed or anything. Why is it closed? Debian doesnt work too.

**Comment by gangefors** [comment]
I ran into this problem too. I'm on Debian jessie with the latest default kernel (3.16).
In the documentation Concourse specifies that it needs kernel 3.19+ (under standalone binary section, not the docker section).

My solution to get this to work was to upgrade to a newer kernel. Hope this helps.

**Comment by che** [comment]
Also doesn't work for Ubuntu (latest or 16.04)

**Comment by ebouaziz** [comment]
Same here, Debian Stretch, Docker 17.12ce
Also, I had to add a "restart" directive to the worker, because it exited when concourse_web did not start fast enough.

**Comment by walidshaari** [comment]
I am testing on centos7 and have the same issue, it is unfortunate as at work are mainly a RHEL shop, and wanted to be able to use concourse there.

**Comment by StevenArmstrong** [comment]
We use fedora as it has the newer kernel that's required.

**Comment by walidshaari** [comment]
@StevenArmstrong in Enterprise production you might not have that privilege. Concourse introduction claims decoupled architecture to enable you to switch to it or from it, not sure if os compatibilities should have been part of the decoupled/independent part of the solution. will check if I can do it with capabilities instead of running privileged

**Comment by StevenArmstrong** [comment]
You can upgrade your kernel worst case scenario.

**Comment by walidshaari** [comment]
upgraded the kernel in centos to 4.18 from ELrepo-kernel. thanks @StevenArmstrong
