### ISSUE TITLE
Allow `#` in pipeline names

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#1312]
A Feature Request

### What challenge are you facing?

We have a script automatically generates pipeline names for people based on their git remote and git branch when they fork a pipeline for individual developers' branches. Some people name their branches with issue tracking numbers (such as Pivotal Tracker) in the format `meaningful_name_#12345678`, and so when we auto-generate the pipeline, the pipeline name is `dev:embeaux_meaningful_name_#12345678`

Indeed, this harkens back to a [previous release note](http://concourse.ci/downloads.html#v272)... we do have weird pipeline names. In the meantime, we agree to stop naming our branches with `#`.

**Comment by jama22** [comment]
Closing and consolidating int #3985
