### ISSUE TITLE
Incorrect time reporting when there is a time difference between client and server

### ISSUE THREAD

**Issue by mkuratczyk** [concourse/concourse#1314]
Hi there!

We noticed a strange behavior where after manually triggering a build, the "started ... ago"  time on the top bar was incorrect - it started counting at "1m57s ago". We found the root cause to be the time difference between the host where the browser was running and Concourse server. While obviously we need to fix NTP configuration on the client, it could be considered to check for the time drift between GUI and server and either adjust the counter or display a warning about the drift.

Thanks,

**Comment by JamesMcMahon** [comment]
Thanks for the report, I have been seeing this issue under 2.7.7 and started to assumed it was an issue with docker container times drifting, https://github.com/docker/for-mac/issues/1260, https://forums.docker.com/t/time-in-container-is-out-of-sync/16566/11, https://forums.docker.com/t/syncing-clock-with-host/10432/16.

Is there any additional tracking on this issue / an eta on the fix?
