### ISSUE TITLE
Missing job events for pre-upgrade jobs

### ISSUE THREAD

**Issue by bstick12** [concourse/concourse#1316]
# Bug Report

We are unable to view pipeline job events for jobs that ran before we upgraded. The job events page hangs with a Loading icon. In the JS console we get the following error message 

`failed to fetch plan: BadPayload "I ran into the following problems at _.plan:\n\nExpecting an object with a field named `task` but instead got: {\"id\`

We upgraded from 3.1.1 -> 3.2.1

* Concourse version: 3.2.1
* Deployment type : BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Yes

**Comment by clarafu** [comment]
This is a known bug that was introduced with 3.2.1. We will have a patch for it out soon!
