### ISSUE TITLE
Feature Request: Supporting templates

### ISSUE THREAD

**Issue by elgohr** [concourse/concourse#1319]
Hi there!

# Feature Request

At the moment I'm finding myself in migration of 15 applications to concourse. In this way I need to setup for example green blue deployment 15 times. If you take a look at the example https://github.com/pivotalservices/concourse-pipeline-samples/tree/master/blue-green-app-deployment this is pretty much copy & paste & configuration for such a standard task. In the end it would be really nice to have a way to avoid this.

I was thinking of changing the cf-resource, to support something like --green-blue. Then I realized that I had to parse the given manifest for generating a dynamic temporary-url and to introduce a way to execute a given Healthcheck-script. This might be an overkill for this resource.

**Comment by chendrix** [comment]
Could you please elaborate on what you mean from this? As it stands now I don't have a clear picture of what you're trying to accomplish here.

**Comment by elgohr** [comment]
The problem I'm facing is, that the configuration of commonly used patterns (e.g. green-blue deployment) produces pretty much configuration, which is just copy & pasted into different products/projects. 
I'm looking for an easy way to implement templates/patterns like https://github.com/pivotalservices/concourse-pipeline-samples/blob/master/blue-green-app-deployment/ci/pipeline.yml

Speaking in Java, I'm looking for something like an abstract class, which implements the pattern and gives me abstract methods (like unit-tests & load-tests from the example), which are implement differently, depending on the product.
deploy-app and promote-new-version will always be the same, but blow up the configuration.

I could be thinking of this like user provided services (https://docs.cloudfoundry.org/devguide/services/user-provided.html). Somebody would provide a template/pattern on the concourse and other teams could reuse it.

**Comment by chendrix** [comment]
It sounds like you're asking for #417 

If so, I'm going to close this for consolidation. If you disagree strongly, please let me know why and I will reconsider.
