### ISSUE TITLE
Unable to spin up concourse worker in Docker Swarm mode

### ISSUE THREAD

**Issue by davidgarciaMontreal** [concourse/concourse#1321]
Hi team,
Would you know if concourse is compitable with swarm mode in Docker?
I am able to spin up concourse web but not the worker. See logs below.
Thanks for your support.

# Bug Report

* Concourse version: fly-version is 3.2.1
fly -version
3.2.1
* Deployment type (BOSH/Docker/binary):Docker
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?yes with docker-compose but not with in a docker swarm mode

ci_concourse-worker.1.sdwlru32wymn@node-ora    | Exit trace for group:
ci_concourse-worker.1.sdwlru32wymn@node-ora    | garden exited with error: Exit trace for group:
ci_concourse-worker.1.sdwlru32wymn@node-ora    | garden-runc exited with error: bulk starter: setting up default chains: iptables: setup-global-chains: + set -o nounset
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + set -o errexit
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + shopt -s nullglob
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + filter_input_chain=w--input
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + filter_forward_chain=w--forward
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + filter_default_chain=w--default
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + filter_instance_prefix=w--instance-
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + nat_prerouting_chain=w--prerouting
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + nat_postrouting_chain=w--postrouting
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + nat_instance_prefix=w--instance-
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + iptables_bin=/worker-state/3.2.1/assets/iptables/sbin/iptables
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + case "${ACTION}" in
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + setup_filter
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + teardown_filter
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + teardown_deprecated_rules
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ /worker-state/3.2.1/assets/iptables/sbin/iptables -w -S INPUT
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + rules=
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + echo ''
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + grep ' -j garden-dispatch'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + sed -e s/-A/-D/ -e 's/\s\+$//'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + xargs --no-run-if-empty --max-lines=1 /worker-state/3.2.1/assets/iptables/sbin/iptables -w
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ /worker-state/3.2.1/assets/iptables/sbin/iptables -w -S FORWARD
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + rules=
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + echo ''
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + grep ' -j garden-dispatch'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + sed -e s/-A/-D/ -e 's/\s\+$//'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + xargs --no-run-if-empty --max-lines=1 /worker-state/3.2.1/assets/iptables/sbin/iptables -w
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -F garden-dispatch
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -X garden-dispatch
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ /worker-state/3.2.1/assets/iptables/sbin/iptables -w -S w--forward
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + rules=
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + echo ''
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + grep '\-g w--instance-'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + sed -e s/-A/-D/ -e 's/\s\+$//'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + xargs --no-run-if-empty --max-lines=1 /worker-state/3.2.1/assets/iptables/sbin/iptables -w
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ /worker-state/3.2.1/assets/iptables/sbin/iptables -w -S
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + rules=
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + echo ''
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + grep '^-A w--instance-'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + sed -e s/-A/-D/ -e 's/\s\+$//'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + xargs --no-run-if-empty --max-lines=1 /worker-state/3.2.1/assets/iptables/sbin/iptables -w
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ /worker-state/3.2.1/assets/iptables/sbin/iptables -w -S
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + rules=
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + echo ''
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + grep '^-N w--instance-'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + sed -e s/-N/-X/ -e 's/\s\+$//'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + xargs --no-run-if-empty --max-lines=1 /worker-state/3.2.1/assets/iptables/sbin/iptables -w
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ /worker-state/3.2.1/assets/iptables/sbin/iptables -w -S FORWARD
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + rules=
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + echo ''
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + grep ' -j w--forward'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + sed -e s/-A/-D/ -e 's/\s\+$//'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + xargs --no-run-if-empty --max-lines=1 /worker-state/3.2.1/assets/iptables/sbin/iptables -w
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -F w--forward
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -F w--default
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ /worker-state/3.2.1/assets/iptables/sbin/iptables -w -S INPUT
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + rules=
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + echo ''
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + grep ' -j w--input'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + sed -e s/-A/-D/ -e 's/\s\+$//'
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + xargs --no-run-if-empty --max-lines=1 /worker-state/3.2.1/assets/iptables/sbin/iptables -w
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -F w--input
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -X w--input
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + true
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ ip route show
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ grep default
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ cut '-d ' -f5
ci_concourse-worker.1.sdwlru32wymn@node-ora    | ++ head -1
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + default_interface=eth1
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -N w--input
ci_concourse-worker.1.sdwlru32wymn@node-ora    | + /worker-state/3.2.1/assets/iptables/sbin/iptables -w -F w--input
ci_concourse-worker.1.sdwlru32wymn@node-ora    | iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
ci_concourse-worker.1.sdwlru32wymn@node-ora    | Perhaps iptables or your kernel needs to be upgraded.
ci_concourse-worker.1.sdwlru32wymn@node-ora    | 
ci_concourse-worker.1.sdwlru32wymn@node-ora    | dns-proxy exited with nil
ci_concourse-worker.1.sdwlru32wymn@node-ora    | 
ci_concourse-worker.1.sdwlru32wymn@node-ora    | baggageclaim exited with nil
ci_concourse-worker.1.sdwlru32wymn@node-ora    | beacon exited with error: failed to dial: failed to connect to TSA: dial tcp: lookup concourse-web on 127.0.0.11:53: no such host
ci_concourse-worker.1.sdwlru32wymn@node-ora    |

**Comment by davidgarciaMontreal** [comment]
btw, i just noticed that this isnt working with docker-compose anymore. 
The only change i've made it's the docker engine. 
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:42 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by chendrix** [comment]
Hi there!

Could you please move this question to [stackoverflow (tagged with `concourse`)](https://stackoverflow.com/questions/tagged/concourse). We are trying to use this repo only for issues and stackoverflow for questions.
