### ISSUE TITLE
Unknown handle makes pipeline unusable

### ISSUE THREAD

**Issue by CalamarBicefalo** [concourse/concourse#1322]
I am running into some issues in concourse 3.0.0 & 3.0.1 with the docker compose setup.

It says `unknown handle: xxxxx-xxxx-xxxx-xxxx-xxxxx` errors, and next time you retry it will stay in pending (guess the worker is dead, although `docker ps` says the container is up and running).

I also found this in the logs

```
concourse-web_1     | 
{
  "timestamp": "1496740784.270793915",
  "source": "atc",
  "message": "atc.syncer.cybertron:radar.scan-resource.tick.find-worker.worker-for-resource-check.garden-connection.retryable-http-client.retrying",
  "log_level": 1,
  "data": {
    "error": "worker 'c14809da049e' is unreachable (state is 'stalled')",
    "failed-attempts": 8,
    "pipeline-scoped-name": "cybertron:resource:api-release",
    "ran-for": "1m3.054560724s",
    "session": "17.1.6.3.1.1.1.1"
  }
}
```
Interestingly the worker itself keeps heart beating according to the logs:

```
concourse-worker_1  | {
  "timestamp": "1496741193.050103903",
  "source": "tsa",
  "message": "tsa.connection.channel.forward-worker.heartbeat.done",
  "log_level": 1,
  "data": {
    "remote": "172.18.0.4:57214",
    "session": "1.1.1.21",
    "worker-address": "127.0.0.1:33749",
    "worker-platform": "linux",
    "worker-tags": ""
  }
}
```
Any ideas? How could I provide more useful insights?

**Comment by chendrix** [comment]
Hi there!

Could you please move this question to [stackoverflow (tagged with `concourse`)](https://stackoverflow.com/questions/tagged/concourse). We are trying to use this repo only for issues and stackoverflow for questions.
