### ISSUE TITLE
Tweak postgres config to try to reduce CPU usage

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1325]
A team here at Pivotal was able to dramatically reduce their Postgres CPU usage by manually adding the following to their Postgres Config: 

```
checkpoint_segments = 64
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
log_checkpoints = on
``` 

# A Modest Proposal

Let's manually add this to our Postgres config in prod and see if it helps. If it does, maybe we can bake it in as a default configuration. This seems like a pretty cheap experiment that could potentially make a lot of difference.

**Comment by vito** [comment]
We're using an external Postgres release now so I'm gonna call this "not our problem anymore". :)
