### ISSUE TITLE
fly set-team and destroy-team should have a --non-interactive flag

### ISSUE THREAD

**Issue by DRuggeri** [concourse/concourse#1326]
# Feature Request

## What challenge are you facing?

Similar to set-pipeline, the set-team command could benefit from having a --non-interactive flag. Currently, I have to `echo "y" | fly -t blah set-team <args>` to get past the confirmation.

## A Modest Proposal

Adding the argument seems to be fairly straight forward. Assuming this capability isn't present for a reason, I can provide a patch/PR to implement it.

**Comment by thomasmmitchell** [comment]
#1056 :)

**Comment by aleksey-hariton** [comment]
I've made PR for this issue - https://github.com/concourse/fly/pull/191

**Comment by x6j8x** [comment]
It seems 3.4.0 broke the `echo "y" | fly...` workaround. 
I'm now getting an ` inappropriate ioctl for device ` error when trying to run `echo "y" | fly set-team` in a concourse job. :-(

**Comment by jama-pivotal** [comment]
Closing this issue because of merged PR  from fly repo and also because of @vito patch to the issue you referenced @x6j8x Please feel free to enter a new issue if our change doesn't address your problem in the upcoming release of Concourse!
