### ISSUE TITLE
Parameterize task output name

### ISSUE THREAD

**Issue by fbiville** [concourse/concourse#1327]
# Feature Request

## What challenge are you facing?

Currently, variables are only interpreted within the "run" part of a task.
I had to duplicate a task the other day just because they did not have the same output.

## A Modest Proposal

It would be super convenient if variables were interpreted in the output declaration.

**Comment by SHyx0rmZ** [comment]
If I understand correctly you can just use an [output mapping](http://concourse.ci/task-step.html#output_mapping) and reuse the task as is, but maybe I'm misunderstand. Can you maybe provide a small example configuration that shows the problem you're facing?

**Comment by fbiville** [comment]
Oooh, that's exactly what I needed! Thanks a lot!
