### ISSUE TITLE
Automatically update versioned pipeline

### ISSUE THREAD

**Issue by fbiville** [concourse/concourse#1328]
# Feature Request

## What challenge are you facing?

In most of the project I have seen, the pipeline file is versioned with the project it builds. Currently, the workflow is a bit confusing as pipelines need to be updated manually (via `fly` e.g.) but the tasks the pipeline jobs run usually are versioned and just need to be pushed.

It happens from time to time that one forgets to push the pipeline (the pipeline is updated manually) or the tasks (as one may think updating the pipeline is enough).

## A Modest Proposal

I was thinking it would be nice to have Concourse automatically detect pipeline files in versioned projects and update whenever there is a change to it.

**Comment by SHyx0rmZ** [comment]
I don't think it makes sense to force that onto everyone using Concourse. You can easily model this using a [git-resource](https://github.com/concourse/git-resource) and either a [pipeline-resource](https://github.com/robdimsdale/concourse-pipeline-resource) or a [fly-resource](https://github.com/mschirmacher/concourse-fly-resource). I'm sure there are more options. There also is the problem of having to provide any variables (or credentials) you might need in the pipeline.

**Comment by fbiville** [comment]
Thanks, I'll look into these options.
