### ISSUE TITLE
Allow getting a specific version of an s3 versioned resource

### ISSUE THREAD

**Issue by ry4n1m3** [concourse/concourse#133]
We produce an artifact for every commit we make. When we release, we record the s3-resource version of these artifacts that correspond to the version of the code we want to release. During our CI pipeline, we have a test that includes the development version and the most recent release. We would like to use the concourse s3-resource to download the most recent release by specifying the s3-resource version, and manually updating this version whenever a new release is created.

~ Ops Manager Team

**Comment by robdimsdale** [comment]
As discussed with @drich10, we think this is probably not the best way to solve the problem you face. The version info should be kept inside concourse - this solution would leak the versions, increasing the potential for things to be confusing and for them to break. This solution would require reconfiguring the pipeline every time you want to change the version.

If you want a single-pipeline solution, you could add a `passed: [some-manual-job]` constraint which will pull whatever version has passed the manually-triggered-job at the end of the existing pipeline, and that manually triggered job would be triggered when the released product is accepted by PM etc.

If you want multiple pipelines, then you have something very similar to the above but without the passed constraint - you're only uploading new versions to the resource via a manually-triggered job so there is no possibility of running with the wrong version (unlesss you upload a new version outside of concourse, which there should be no need to do).

A multiple pipeline solution is probably easier to manage; feel free to ping us if you want further assistance.

**Comment by ry4n1m3** [comment]
Thanks for the detailed response! closing.

**Comment by drich10** [comment]
+1. Thanks for steering us in the right direction! :beers:
