### ISSUE TITLE
fly set-team should offer prompt for auth credentials

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1330]
# Feature Request

## What challenge are you facing?

The current fly CLI (as of 3.1.0) requires the auth credentials for a set-team to be provided as flags.
This is bad practice as credentials will end up in *sh history. 

## A Modest Proposal
Instead, provide a prompt in the fly CLI to enter the credentials.

--

moved from concourse/fly#175 cc @hamid-elaosta

**Comment by xtremerui** [comment]
Now there is `--config` that allows team auth info from a file
