### ISSUE TITLE
BaggageClaim response header timeout of 10 minutes is reached when deployment is under high load

### ISSUE THREAD

**Issue by doty-pivotal** [concourse/concourse#1333]
# Bug Report
Creating a volume can take a while, and the current timeout of 10 minutes is still being reached.

The error:
```
Post /volumes: net/http: timeout awaiting response headers
```

Here are the logs corresponding to this request:

```
{"timestamp":"1498620827.286466360","source":"atc","message":"atc.syncer.toolsmiths-images-dockerfiles:scheduler.tick.scheduling.try-start-next-pending-build.do.put.find-or-create-cow-volume-for-container.failed-to-create-volume-in-baggageclaim","log_level":2,"data":{"build-id":14852,"build-name":"140","container":"be1f39d4-bd5d-4b15-5c7c-e9a28c0561ea","error":"Post /volumes: net/http: timeout awaiting response headers","name":"centos-gpdb-dev-5-gcc4.4-happy-resource","session":"16.2.52594.3.32.11.1.12","volume":"e603bad4-8022-4435-644a-83fbe8d306e5"}}
{"timestamp":"1498620827.287461281","source":"atc","message":"atc.syncer.toolsmiths-images-dockerfiles:scheduler.tick.scheduling.try-start-next-pending-build.do.put.failed-to-create-container-in-garden","log_level":2,"data":{"build-id":14852,"build-name":"140","container":"be1f39d4-bd5d-4b15-5c7c-e9a28c0561ea","error":"Post /volumes: net/http: timeout awaiting response headers","name":"centos-gpdb-dev-5-gcc4.4-happy-resource","session":"16.2.52594.3.32.11.1"}}


{"timestamp":"1498620827.288340330","source":"atc","message":"atc.syncer.toolsmiths-images-dockerfiles:scheduler.tick.scheduling.try-start-next-pending-build.do.put.failed-to-run-action","log_level":2,"data":{"build-id":14852,"build-name":"140","error":"Post /volumes: net/http: timeout awaiting response headers","name":"centos-gpdb-dev-5-gcc4.4-happy-resource","session":"16.2.52594.3.32.11.1"}}


{"timestamp":"1498620827.292856216","source":"atc","message":"atc.syncer.toolsmiths-images-dockerfiles:scheduler.tick.scheduling.try-start-next-pending-build.do.put.errored","log_level":1,"data":{"build-id":14852,"build-name":"140","error":"Post /volumes: net/http: timeout awaiting response headers","name":"centos-gpdb-dev-5-gcc4.4-happy-resource","session":"16.2.52594.3.32.11.1"}}
{"timestamp":"1498620827.301527500","source":"atc","message":"atc.syncer.toolsmiths-images-dockerfiles:scheduler.tick.scheduling.try-start-next-pending-build.finish.errored","log_level":1,"data":{"build-id":14852,"build-name":"140","error":"Post /volumes: net/http: timeout awaiting response headers","session":"16.2.52594.3.32.12"}}
```

FYI - we have a snapshot of all the logs on the deployment tar'ed up and available if you need them.

Here is our environment:

* Concourse version: `3.2.1`
* Deployment type (BOSH/Docker/binary): `BOSH`
* Infrastructure/IaaS: GCP and AWS
* Browser (if applicable): N/A
* Did this used to work? We did not notice this on 2.7.* deployments

Here is how we can reproduce:

We see this issue when the deployment is running a number of jobs at the same time.  We use the following simple script to start all the jobs in a pipeline at the same time, and use it across several pipelines, if we need to reproduce the conditions that we see at various times in production.

```
# You can update the variables in this file (fly_cmd, pipeline_name, target)
# and execute it as below from terminal
# ruby trigger_all_jobs_in_a_pipeline.rb.snippet

require 'yaml'

fly_cmd = '<LOCAL FLY CMD>'
pipeline_name = '<PIPELINE NAME>'
target = '<TARGET>'

parsed = YAML.load(`#{fly_cmd} -t #{target} get-pipeline -p #{pipeline_name}`)
jobs = parsed["jobs"].map{|j| j["name"]}

jobs.each do |j|
  p "#{fly_cmd} -t #{target} trigger-job -j #{pipeline_name}/#{j}"

  # If you need to execute it, uncomment the below line
  #`#{fly_cmd} -t #{target} trigger-job -j #{pipeline_name}/#{j}`
end
```

Here is some things that seem related:
* [Issue 1171](https://github.com/concourse/concourse/issues/1171)
* The corresponding git commit related to the issue [ [commit](https://github.com/concourse/atc/commit/afbd022a12fb27e1d9881f41f6c8327cd8e1dedb#diff-10a3f8bd2ddec1238f276fab00c1a3f6) ]

Questions:

- What service is `atc` connecting to when we see this timeout? (We are assuming that it is baggage claim)
- How can we tie the session we see in the `atc` log to the worker so that we can correlate the logs? Specifically so that we could drop the `baggageclaim` logs here to assist with debugging.
- Would adjusting the log level for one of the services provide any extra context?

**Comment by chendrix** [comment]
Are you using overlay? Do you need to be using overlay? Can you switch back to btrfs?

**Comment by SHyx0rmZ** [comment]
We are also hitting this in about 50% of our pipelines. We are using OverlayFS, having had no luck trying to move back to Btrfs, because kernel errors always appear after a few hour (or even just minutes).

**Comment by doty-pivotal** [comment]
@chendrix:
> Are you using overlay? 
Yes

> Do you need to be using overlay?
We were one of the users that experienced issues with `btrfs` and followed issue [#1045](https://github.com/concourse/concourse/issues/1045) closely.  So without more information, we think we should be using what was released with [v3.1.0](http://concourse.ci/downloads.html#v310).

> Can you switch back to btrfs?
Is there a way to do that while remaining up to date with the latest Concourse release?  I would also like to understand why this is a recommended course of action given all of the details/work documented in issue [#1045](https://github.com/concourse/concourse/issues/1045).

**Comment by chendrix** [comment]
@doty-pivotal @SHyx0rmZ 

They are two different filesystem drivers with different bugs or performance issues.

`btrfs` seems to have a kernel bug (or two), but `overlay` is slow when creating volumes with very large files or lots of files.

We have a baggageclaim header timeout to prevent unnecessary waiting under resource constraints and fail the build, and we originally had the timeout set to 1 minute and increased it to 10 minutes. But it looks like even that's not enough for specific Concourse installations of certain sizes/configurations that are using overlay

**Comment by doty-pivotal** [comment]
@chendrix, Thanks for taking the time to respond.  I hear what you are saying about the tradeoffs, there always are.  That being said, is there a recommendation for moving forward?  We see (as posted initially) where that timeout was set, and after reading the issues related, we are on the same page.  So now from a practical standpoint, the pipelines we have in production are unstable, and this time out error is causing issues<sup>1</sup>.  Is there a path forward? Does it make sense to increase the timeout? Should this error have some failure mode other than going "orange", like moving on to a task's on failure condition? Should we revert to a pre v3 release? Is there some other path forward that I am missing? 

 _If_, and not assuming it is, the recommendation for teams was to revert to `btrfs`, I am not sure what that would look like. I found this comment in the release notes:

> It is only on recreate that they will pick overlay, and only if it makes sense to (i.e. your kernel version is > 4.0, and your disk is not formatted as btrfs already).

From this it seems like then I would need to make sure that my disk is formatted like that.  Is it that, if we choose to deploy with BOSH, and choose to stay with Concourse v3+, then we are committing to using `overlay`?  Or is there a Concourse config option that I am not seeing to allow us to "revert" to `btrfs` (which we could do to evaluate if that set of issues was the better set of trade offs to make for our org).

Also, just want to make sure that there is no other context that could help with this issue, specifically: 

- What service is atc connecting to when we see this timeout? (We are assuming that it is baggage claim)
- How can we tie the session we see in the atc log to the worker so that we can correlate the logs? Specifically so that we could drop the baggageclaim logs here to assist with debugging.
- Would adjusting the log level for one of the services provide any extra context?

-----

<sup>1</sup> For context, we are about to spin out dynamically allocated clusters of VM's from our pipelines, and currently the only way that we leak a cluster is when the pipeline goes "orange", because in that case we can't handle an error using the "on-failure" mechanism provided in the pipeline.

**Comment by SHyx0rmZ** [comment]
@doty-pivotal You can use the `--baggageclaim-driver=[detect|naive|btrfs|overlay]` flag (or set the `CONCOURSE_BAGGAGECLAIM_DRIVER` environment variable) to force baggageclaim to use a certain driver.

@chendrix I know about most of this. Personally, I'm trying to find the time to create a pull request to make the timeout configurable. This would of course still mean that the builds would be slow, but at least they would eventually succeed. Alternatively, I'd probably have us spin up a new tagged worker using the `btrfs` driver every hour or so, so we could keep the pipelines functional until the situation might improve some day.

I also would like to make our Docker images smaller, (as pretty much all of the timeouts happen in `docker-image` `put`s), but there are some limitations, as some teams *really* want to keep using their current base images.

**Comment by doty-pivotal** [comment]
@SHyx0rmZ - Thanks for pointing out that option.

**Comment by chendrix** [comment]
@SHyx0rmZ yeah a PR to make the timeout configurable seems like the best path forward for right now.

We've always tried to maintain sane defaults but in this case the tweakability from an operations standpoint might be a necessary short-term fix.

**Comment by d** [comment]
@doty-pivotal since you're using BOSH, you'll want to set the `driver` property for the `baggageclaim` job to `btrfs` (instead of the default `detect`). See http://bosh.io/jobs/baggageclaim?source=github.com/concourse/concourse&version=3.2.1#p=driver

**Comment by davidgarciaMontreal** [comment]
I am having the same problem: with only one job:
 {"timestamp":"1499436411.899879456","source":"atc","message":"atc.create-job-build.trigger-immediately.try-start-next-pending-build.do.put.find-or-create-cow-volume-for-container.failed-to-create-volume-in-baggageclaim","log_level":2,"data":{"build-id":77,"build-name":"7","container":"578beb77-ec5e-42ce-713b-bd9a8639a4e4","error":"Post /volumes: net/http: timeout awaiting response headers","job_name":"job-ecm-build-baseimage","name":"ecm-base.image","session":"295685.1.1.9.1.6","volume":"01d06b5e-631c-4963-485d-dcc89f00f3ce"}}

fly -version
3.3.0

**Comment by jtarchie** [comment]
We pulled in the PRs from @SHyx0rmZ that make the timeout for baggage claim timeout configurable through the bosh release and atc CLI.

Since there is ongoing work to change the behaviour in #1368, we are going to close this issue.

Please feel free to comment on it if extending the timeout still causes you issues. Thanks!
