### ISSUE TITLE
Failure to pull custom resources if the container is removed

### ISSUE THREAD

**Issue by literatesnow** [concourse/concourse#1336]
# Bug Report

When a pipeline uses a ``docker-image`` custom resource it seems to always try and use the same container from when it first downloaded the custom resource. If the custom resource is updated and the old container is removed from the docker repository then the build fails because Concourse can't find the container.

1. Consider the following resource type:

    ```yml
    resource_types:
    - name: any-custom
      type: docker-image
      source:
        repository: [...]/any-custom-resource
        tag: latest
    ```

1. Build a pipeline which uses the custom resource.
1. Update the custom resource in the docker repository and tag it as latest.
1. Remove the previous image of the custom resource from the docker registry.
1. Build the pipeline and the custom resource step fails with:

    ```
    Pulling [...]/any-custom-resource@sha256:4cfba9ba706b42227f1e1ad079951493ecde383eeb76505f9f777d2204ca1af5...
    Error response from daemon: repository [...]/any-custom-resource not found

    Pulling [...]/any-custom-resource@sha256:4cfba9ba706b42227f1e1ad079951493ecde383eeb76505f9f777d2204ca1af5 (attempt 2 of 3)...
    Error response from daemon: repository [...]/any-custom-resource not found

    Pulling [...]/any-custom-resource@sha256:4cfba9ba706b42227f1e1ad079951493ecde383eeb76505f9f777d2204ca1af5 (attempt 3 of 3)...
    Error response from daemon: repository [...]/any-custom-resource not found

    Failed to pull image [...]/any-custom-resource@sha256:4cfba9ba706b42227f1e1ad079951493ecde383eeb76505f9f777d2204ca1af5.

    resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1
    ```

Is it expected behaviour to destroy and set all the pipelines which are using the custom resource after the resource is updated or should Concourse try and pull the tag when the container doesn't exist?

* Concourse version: 3.2.1
* Deployment type: Binary
* Infrastructure/IaaS: AWS
* Did this used to work? Yes

**Comment by chendrix** [comment]
Is there a reason you're attempting to destroy the old image from Dockerhub immediately?

**Comment by chendrix** [comment]
Concourse spins up a check container to grab any new versions of your custom docker image. But it doesn't happen instantaneously (the default check interval is 1m I think), and should happen when you trigger a new build.

**Comment by literatesnow** [comment]
All untagged images are removed from the docker repository (ECR) overnight because we haven't had a need to keep them around before (I believe there's a hosting cost and image limit reason somewhere too).

Our worker instance isn't running all the time and is terminated overnight when not in use. A webhook starts the worker instance (if none is running) and triggers a build in Concourse. I guess the build is run before check has a chance to detect a new version of the custom resource?

Also Concourse sometimes gets unhappy if the worker isn't there on a new pipeline and ``check-resource`` returns: ``"error": "custom resource type 'any-custom-resource' version not found"``. Although I haven't been able to reliably reproduce that one yet.

**Comment by chendrix** [comment]
Yeah concourse expects a certain level of stability and continuous operation from its workers and its external resources.

The scheduling is all done by the ATC and if there are no workers it doesn't just sit there waiting, it fails the build.

**Comment by literatesnow** [comment]
The path to least resistance sounds like always run a Concourse worker. Thanks.

**Comment by jtarchie** [comment]
@literatesnow, it sounds like your issue has been resolved. Can we close this issue?

**Comment by literatesnow** [comment]
@jtarchie Sure, unless there's a plan to make Concourse work without having a consistent worker running.

**Comment by jtarchie** [comment]
@literatesnow, I am not sure I follow. Can you clarify the last statement?
