### ISSUE TITLE
ATC crashes when listing pipelines when DB is down

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1341]
https://github.com/concourse/atc/blob/c3418208d2332a1f0cb13838532b7c8e1dad7a38/api/present/pipeline.go#L20-L23

Can we change this to not have to do the query in the first place? That'll be n+1 queries for listing pipelines.

**Comment by clarafu** [comment]
The plan is to remove the config from the pipeline object and to save the groups in the config separately in the database. This way, we will not be querying for all the resource/resourcetype/job configs when we only want the groups part of the config. The usages of the pipeline config for resource/resourcetype/job configs will be switched to calling Config() off the resource/resourcetype/job objects itself.

**Comment by clarafu** [comment]
Observed lower response times for ListAllPipelines (went from 16 ms to 2 ms).
