### ISSUE TITLE
The fly hijack/intercept capabilties seem to be broken

### ISSUE THREAD

**Issue by DRuggeri** [concourse/concourse#1342]
# Bug Report

After having upgraded from 3.1.1 to 3.3.0 and executing a `fly sync`, the `fly intercept/hijack` commands no longer seem to work. The error returned is `error: websocket: bad handshake`.

* Concourse version: 3.3.0
* Fly version: 3.3.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable): N/A
* Did this used to work? Yes

Observations:
- Attempts to execute `fly -t blah intercept -j pipeline/job -s foo` seem to attempt placing me in the container. The binary goes into a wait loop (I see poll and futex calls on the socket to ATC) for five minutes with a one minute sleep between tries and then the error is thrown
- Running the above command without specifying the step immediately returns a prompt for which step to intercept (indicating at least some success to communication with the server)
- Doing a nuke and pave of the concourse infrastructure with `bosh recreate --force --skip-drain` seems to make no difference
- Attempts to execute `fly -t concourse intercept -c stl-sandbox-pcf-install-ipsec/product` return the error immediately. Looking at strace output, it seems to also have polls and waits, but gets to the punchline much faster.

I know this is a sparse report - I'm happy to provide any additional details that I can.

**Comment by joris77** [comment]
The same is happening for fly 3.2.1 with the vagrant box

**Comment by svrc-pivotal** [comment]
Same issue with 3.3.1 on docker compose

**Comment by chendrix** [comment]
From a now deleted issue (https://github.com/concourse/fly/issues/108):

>  If you're using nginx or some other reverse proxy, make sure it's configured to support websockets. Local networking (i.e. enterprise VPN/etc) could also be getting in the way.

---

> If you're using an AWS ELB, you have to make sure that the protocol forwarding to concourse:web on port 8080 is `ssl` and not `https`. On Kubernetes, this is achieved in your Service Definition with :
> 
> ```json
> "annotations": {
>       "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:iam::derpderpderp",
>       "service.beta.kubernetes.io/aws-load-balancer-protocol": "ssl",
>       "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp",
>       "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "443"
> }
> ```

---

> To expand on @ls-avanier comment, [this](https://github.com/concourse/concourse/issues/53#issuecomment-107581660) comment to another thread clarified it even further to those who has setup ELB following the concourse installation guide.
> 
> > ...make sure your elb is set up with TCP or SSL listeners and not http or https ... you'll want to keep it that way so hijack can work.
> 
> And our listeners now look like this:
> 
> TCP 80 to TCP 8080
> SSL 443 to TCP 4443
> HTTP 222 to HTTP 2222
> 
> This setup seems to work correctly with intercept/hijack.

---

Also a [comment you *can* see](https://github.com/concourse/concourse/issues/53#issuecomment-107581660)

Does this match your use cases?

**Comment by DRuggeri** [comment]
In my use case I'm using a local, hardware layer 4 (TCP only) loadbalancer. It is configured to forward 443 and 2222. This configuration was working fine, but stopped after upgrading from 3.1.1 to 3.3.0.

After upgrading to 3.3.1, released the other day, I seem to be able to hijack containers again (just not all of them as I've seen a few failures similar to what I opened the issue for). Could this be related at all to the changes since 3.1.1 pertaining to caching of containers?

**Comment by svrc-pivotal** [comment]
Also running locally only.  I think my issue is also related to worker weirdness, this goes away when I recreate the worker vm and prune workers.

**Comment by DRuggeri** [comment]
After letting things settle, similar to what @svrc-pivotal points out, things seem to be OK. Seems maybe this was an unexpected side effect of upgrading. I'll go ahead and close this out until I can find a reliable reproducer of the issue.

**Comment by rjain-pivotal** [comment]
Same issue on helm/kubernetes

**Comment by svrc-pivotal** [comment]
@rjain-pivotal is this after upgrade or first install?  Did hijack ever work with helm? The worker VMs may need recreating if it is an upgrade

**Comment by francoisruty** [comment]
I get this issue too on concourse 3.6.0
fly intercept only works on GET container, everytime I try intercepting a container for an ongoing build or put task, I get "bad handshake"

**Comment by madkinder** [comment]
Same here, hijacking doesn't work for one-off builds.
Concourse 3.14.1 running with docker-compose.

**Comment by peckeltw** [comment]
Thanks @chendrix for the solution, working nicely now on Concourse 3.14.1.
To be more precise, if using Terraform, your ELB listener should contain something like this:
``` 
listener {
    lb_port            = 443
    lb_protocol        = "SSL"
    instance_port      = 8080
    instance_protocol  = "TCP"
  }
```

**Comment by bruzos** [comment]
same with 3.14.1
```
bash-4.4# exit
exit

fly -t gryffindor intercept -j monitoring-visiondashboard/build-master
error: websocket: bad handshake

```

**Comment by mxplusb** [comment]
I'm seeing this same issue on 5.2.0 with AWS ELBs, and my listener config is `HTTPS`, not `SSL`. I can't change the config because my network path is `CLI -> ELB -> gorouters -> ATC` and I need the `X-Forwarded-For` headers the `HTTPS` listener provides.

Any recommendation on a workaround for this?

**Comment by lrstanley** [comment]
We were having the same issue when we first upgraded to v5.x.x, which reduced the cipher suites supported. Our corporate proxy only supported a specific set, so we ended up throwing Nginx in front of each atc and just proxy passed the requests over localhost. Hijacking started failing, and it looks as though it was due to websockets not being properly proxied. Ended up just adding an additional entry in the Nginx config specifically for any endpoint that matched `/hijack$` to do an http upgrade to a socket based connection (i.e. enabling proper websockets). This seems to have solved our hijacking problems. This is now our current Nginx config, if anyone else wants to do similar if they're running Nginx:

```
user              nobody vcap;
worker_processes  2;
error_log         /var/vcap/sys/log/nginx/error.log info;
events{
  worker_connections 1024;
}
http {
  server_tokens off;
  server {
    listen 80;
    return 301 https://$host$request_uri;
  }
  server {
    listen 443 ssl;
    access_log  /var/vcap/sys/log/nginx/access.log;

    ssl_certificate     /var/vcap/jobs/nginx/etc/ssl_chained.crt.pem;
    ssl_certificate_key /var/vcap/jobs/nginx/etc/ssl.key.pem;
    ssl_protocols       TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 10m;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_tickets off;
    resolver_timeout    5s;

    location / {
      keepalive_timeout 0;
      proxy_pass_request_headers on;
      proxy_pass http://127.0.0.1:8080;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_buffering off;
      client_max_body_size 0;
      proxy_read_timeout 36000s;
      proxy_redirect off;
    }
    location ~ /hijack$ {
      keepalive_timeout 0;
      proxy_pass_request_headers on;
      proxy_pass http://127.0.0.1:8080;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      # required for websocket support
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_buffering off;
      client_max_body_size 0;
      proxy_read_timeout 36000s;
      proxy_redirect off;
    }
  }
}
```
