### ISSUE TITLE
fly set-pipeline errors out when using yaml anchors under the key 'variables'

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse#1343]
Hi there!

# Bug Report

We are setting variables at the top of our pipeline file like so:
```
variables:
- &ERT_VERSION "1.12"
- &OPSMAN_VERSION "1.11"
```
and when running `fly set-pipeline` we get the following error. 
```
could not resolve template vars: yaml: unmarshal errors:
  line 738: cannot unmarshal !!float `1.12` into template.VariableDefinition
  line 739: cannot unmarshal !!float `1.11` into template.VariableDefinition
```
It seems that the problem is with the `variables` header above the anchors
```
something-else:
- &ERT_VERSION "1.12"
- &OPSMAN_VERSION "1.11"
```

works as expected.

The following can also be handy:

* Concourse version: 3.3.0
* Deployment type (BOSH/Docker/binary): n/a
* Infrastructure/IaaS: n/a
* Browser (if applicable): n/a
* Did this used to work?
Yes it worked in 2.7.4

**Comment by pivotal-topher-bullock** [comment]
Thanks @joshzarrabi . Looks to be an issue specifically with the variables keyword, likely because we're leveraging templating from the BOSH CLI manifest templating, which has a variables section.

**Comment by pivotal-topher-bullock** [comment]
Thanks @joshzarrabi . Looks to be an issue specifically with the variables keyword, likely because we're leveraging templating from the BOSH CLI manifest templating, which has a variables section.
