### ISSUE TITLE
ATC error message for auth configuration should be more helpful for no-auth

### ISSUE THREAD

**Issue by lnhrdt** [concourse/concourse#1344]
If you're trying to setup a local Concourse with no authentication, it's hard to figure out what property to provide to the atc job.

`errors.New("must configure basic auth, OAuth, UAAAuth, or provide no-auth flag")`

https://github.com/concourse/atc/blob/master/atccmd/command.go#L645

Maybe the error message (or docs) could more directly explain the options. It was hard to figure out that "provide no-auth flag" meant "set the `no_really_i_dont_want_any_auth` property to true".

**Comment by jtarchie** [comment]
I think a PR for the documentation would be great. 😄

**Comment by lnhrdt** [comment]
@jtarchie +1. We were flying fast on a Labs project and I didn't want to lose the context. I'll see if I can use this as an excuse for my first concourse PR.

**Comment by xtremerui** [comment]
Not applicable anymore. To config Concourse Auth, refer to the doc [here](https://concourse-ci.org/configuring-auth.html)
