### ISSUE TITLE
a concourse user can execute a multi-build flow via the command line

### ISSUE THREAD

**Issue by ships** [concourse/concourse#1346]
# Feature Request

## What challenge are you facing?

This is one approach to the classic question, 'how can i `fly execute` a whole job rather than just a task?'

Sometimes, when i have jobs in my pipelines which involve multiple tasks transmitting volumes between one another, I would like to validate that those changes actually do work in concert. Because it is a royal pain to call `fly execute` multiple times, especially when there are several inputs/outputs between the tasks that have to be downloaded and uploaded (using my local machine as a cache), I and my colleagues have developed the unfortunate habit of committing experimental changes to our `ci` directories, waiting for Concourse to pick up the build, and iterating.

As well as a dirty git history, this methodology has an externality on any builds or other pipelines which trigger on new commits in those repos -- they build excessively, producing extra load and sometimes duplicate artifacts. General noise and mayhem in the cloud.

I would like to do something like that:
```
fly -t cc formation -i input0=./in0 -c task1.yml --passthrough-volume output1=input1 -c task2.yml -o output1=./out1
```
where task1 requires input0 and produces an output1, and task2 requires an input1. The `--passthrough-volume` directive instructs baggageclaim to cache the volume temporarily. for longer persistence, you can download the output to the cached directory as well as temporarily caching, just like normal `execute`.

There is a lightweight way of doing this that uses the local machine as a cache anyway.

Open question: how would `input_mapping` play out?

**Comment by marco-m** [comment]
I like the idea, it would be equivalent of a `buildbot try`, which is I think unique among CI systems. 
Small comment about dirty git history: as long as you do the work in a branch (meaning: history rewrite will not impact anybody else), you can keep amending / history rewriting, so history would not be dirty.

**Comment by joshzarrabi** [comment]
@jraqula You should check out [piper](https://github.com/ryanmoran/piper). It is essentially `fly execute` but it runs the task locally in a docker container on your machine. Its super useful.

**Comment by jraqula** [comment]
that is pretty cool, definitely saves me some trouble in certain use cases. Thanks for the reference @joshzarrabi . doesn't stop me from having to do excessive workspace management however, given the conundrum of volumes littering my station between builds that i would `piper` in sequence, right?

**Comment by joshzarrabi** [comment]
@jraqula it wouldn't, i think, but at least you wont have to deal with git.
