### ISSUE TITLE
"check" has weird behavior for now-empty version

### ISSUE THREAD

**Issue by philicious** [concourse/concourse#1347]
Hi there!

# Bug Report

I was recently working on a custom resource for building PRs on Bitbucket (Cloud) repos which is working fine now (got merged into https://github.com/zarplata/concourse-git-bitbucket-pr-resource )

However I noticed a weird behavior which could be a bug:

When `check`-ing I emit a single version, i.e. the latest updated PR. Emitting more than one turned out to confuse concourse, causing no-build, double-builds etc depending on the order of PR being updated.
So with single emitted version this is fine and the list of versions is showing all versions that were created and build over time.
```
# example of emitted version
cat test/payload| ./assets/check .
[
  {
    "id": "3",
    "branch": "feature/MOQ2MVP-161-just-another-pr",
    "commit": "adf8a87d112e"
  }
]
```

Now when the repo transitions to a state where no PRs are open anymore, the version emitted is empty
```
cat test/payload| ./assets/check .
[
  null
]
```
This somehow leads to the task being marked as red but the build log is empty and only showing loading spinner:
![screen shot 2017-06-30 at 12 14 13](https://user-images.githubusercontent.com/404412/27731547-b6707f26-5d8d-11e7-9223-9214e575d7c7.png)
Seems like its triggered but never actually executes anything. 
This isnt more than a cosmetical problem tho.

When I now create a new PR, the pipeline will work as usual and build the branch. HOWEVER, the list of versions in `check` will stay empty and only show `checking successfully`.
Again this is cosmetical and the pipeline is working as it should. 

So I'm not sure if this is a bug in concourse or the resource should output sth different when in "no versions available" state ?

* Concourse version: 3.2.1

**Comment by vito** [comment]
If there are no versions available it should emit an empty array. Granted, Concourse shouldn't choke on a `null` version and should probably emit a sensible error somewhere, but in any case the root of the misbehavior is in the resource.

Emitting more than one version shouldn't confuse anything; that's the normal and expected state for any resource. You should however make sure the order returned is deterministic. It's supposed to even be chronological, but that doesn't really make sense for something like PRs, so.

See https://concourse.ci/implementing-resources.html#resource-check

**Comment by philicious** [comment]
@vito right ok. so just to make sure I understand it correctly: the `null` is the problem and the empty emitted resource should just be ? 
```
[
]
```

multiple emitted versions: 
yes I know from https://concourse.ci/implementing-resources.html how they are supposed to look like. for i.e. git thats working out just fine as you can always return the inputted version (ref) + all refs that happened afterwards (=deterministic and chronological)
However with PRs you loose the history. PR info always points to latest commit, so you can only return that one per PR.
together with the fact that the order of PRs changes, it seemed to confuse concourse. so the only way I got this working 100% was to only emit a single version.

**Comment by vito** [comment]
@philicious yep, the `null` is the problem.
