### ISSUE TITLE
Self-service team auth management

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1348]
# Feature Request

## What challenge are you facing?

Running a multi-tenant Concourse entails bootstrapping teams with some sort of auth config. In our case, we typically bootstrap a team with GitHub auth configured to authorize a particular GitHub team, which involves configuring a client ID/secret.

One feature of Teams is that you can run `fly set-team` against your own team to change this config. For example, if you want to authorize a particular user for a short period of time, without adding them to the existing GitHub team. Or, if you're using basic auth, and want to rotate the password.

This is all well and good but has two problems:

1. With the lack of an explicit "operator role", operators sometimes need to know or change the auth config of their teams in order to view their data. See #1012 and #1209.
1. With GitHub auth configured, the team needs to know the GitHub client ID/secret. That's bad.

## A Modest Proposal

Not sure. Maybe things like GitHub client ID/secret should be moved to a global config, since an entire Concourse should end up with a single auth callback anyway?

**Comment by vito** [comment]
Or can maybe use interpolation like fly set-pipeline and use a cred backend to resolve that information</thinkingoutloud>

**Comment by jama22** [comment]
With the introduction of Users in 4.0.0, GitHub client ID/Secret configuration was at least moved to web start and is a global configuration. The introduction of the `-d` flag has been really helpful as well for teams to understand what is currently configured in roles and whitelisted teams/users/orgs. In the spirit of this issue thought one thing that might be missing in self-service team management is conveying to the user what auth connectors are even available/configured in their current instance of the system.  

Not sure if this issue should be closed...tnoughts @vito ?

**Comment by vito** [comment]
@jama22 I think we can close it. The main goal was being able to re-configure my team without needing a client ID/secret, which we've delivered.
