### ISSUE TITLE
Vault Prefix Property Not Utilized

### ISSUE THREAD

**Issue by mattjbarlow** [concourse/concourse#1355]
After installing Vault 3.3.0, we set the [vault.path_prefix](https://github.com/concourse/concourse/blob/v3.3.0/jobs/atc/spec#L409-L412) in our deployment manifest, but the property does not seem to have any effect and we receive an error from atc indicating it is still looking at the default prefix of `/concourse`.

We also tried manually injecting `--vault-prefix`, as mentioned [here](https://concourse.ci/creds.html), into the generated `atc_ctl` startup script, and received this error:
`unknown flag 'vault-prefix'`

**Comment by pivotal-topher-bullock** [comment]
Looks like you caught two mistakes in one issue 👍 :
1) the `vault.path_prefix` property in the ATC job isn't used by the control script that starts ATC anywhere 
2) the docs reference `--vault-prefix` but the flag is `--vault-path-prefix`
