### ISSUE TITLE
Frequent killed builds and "no workers" since upgrading to > 3.2

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1356]
# Bug Report

* Concourse version: 3.3.1
* Deployment type: docker-compose
* Infrastructure/IaaS: OpenStack, single VM with 8GB RAM and 4vCPU
* Did this used to work: Probably

I'm pretty sure this wasn't a problem before the 3.2 releases, but we quickly moved to 3.3 so I can't say if it started with 3.2 or 3.3.

We frequently need to retry builds because processes in them get Killed (see above, a running maven-surefire test gets killed) and then subsequently no worker is available to update build status either.  However, we don't fiddle with the cluster during builds, so I presume this is some intermittent issue with the worker. 

![image](https://user-images.githubusercontent.com/130103/27875984-886aac42-61b5-11e7-94cb-6796fb3e7cbe.png)

Any logs or details I can provide to help diagnose this issue?

**Comment by vito** [comment]
Looks symptomatic of running out of memory and being killed by the OS. The OS may even be killing the worker process.

**Comment by antitux** [comment]
I am seeing the same thing, moving workers from 3.3.0 to 3.3.1. Rolling the workers back to 3.3.0 allowed them to be picked up correctly by the ATC.

**Comment by antitux** [comment]
```
mgcc119147:scripts grh8dee$ fly -t ent-quote-dev workers -d
name         containers  platform  tags  team  state    version  garden address   baggageclaim url        resource types
worker1-az1  2           linux     none  none  running  1.1      10.91.4.30:7777  http://10.91.4.30:7788  archive, bosh-deployment, bosh-io-release, bosh-io-stemcell, cf, docker-image, git, github-release, hg, pool, s3, semver, time, tracker, vagrant-cloud
worker2-az1  1           linux     none  none  running  1.1      10.91.4.31:7777  http://10.91.4.31:7788  archive, bosh-deployment, bosh-io-release, bosh-io-stemcell, cf, docker-image, git, github-release, hg, pool, s3, semver, time, tracker, vagrant-cloud


the following workers have not checked in recently:

name         containers  platform  tags  team  state    version  garden address  baggageclaim url  resource types
worker1-az2  5           linux     none  none  stalled  1.1      none            none              archive, bosh-deployment, bosh-io-release, bosh-io-stemcell, cf, docker-image, git, github-release, hg, pool, s3, semver, time, tracker, vagrant-cloud
worker2-az2  43          linux     none  none  stalled  1.1      none            none              archive, bosh-deployment, bosh-io-release, bosh-io-stemcell, cf, docker-image, git, github-release, hg, pool, s3, semver, time, tracker, vagrant-cloud

these stalled workers can be cleaned up by running:

    fly -t ent-quote-dev prune-worker -w (name)
```

**Comment by antitux** [comment]
Top 2 are on 3.3.0, bottom 2 are on 3.3.1. ATC is at 3.3.1.

**Comment by antitux** [comment]
Possible fix: Manually prune the stalled workers and allow them to readd themselves. It seems to have cleared up my issue.

**Comment by JohannesRudolph** [comment]
@vito looks like you're right. I've run docker-stats while builds are running and memory usage was indeed _very_ high. I think it's time for us to scale...

For now I was able to reduce parallelism in builds so that individual jobs stay below 4GB of RAM and then limit concurrency in individual pipelines to two. However, there's no inter-pipeline coordination, so our concourse may still overload. 

Some primitive scheduling as requested in https://github.com/concourse/concourse/issues/787 would be extremely nice. If tasks could specify a memory limit declaratively in their YAML, then concourse could schedule them so that they land on a worker that has enough free space.

**Comment by jtarchie** [comment]
@JohannesRudolph, it sounds like your issue has been resolved. Can we close this issue?

The discussion being had in #787 is an ongoing discussion and you are welcome to contribute.

**Comment by JohannesRudolph** [comment]
Yes, we're good now that we actively try to limit the memory used during builds.
