### ISSUE TITLE
Task with forward slash in the name causes incorrect page to load

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#1358]
* Concourse version: 3.3.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Chrome on Linux
* Did this used to work? ?

When clicking a job in a pipeline that has a forward slash in the name e.g. `some/job`, the loaded page is some other pipeline page.

Example: https://some-concourse/teams/main/pipelines/some-pipeline/jobs/some/job took me to another pipeline (the default?).

**Comment by chendrix** [comment]
Closing as same as #751
