### ISSUE TITLE
Add command for checking login status

### ISSUE THREAD

**Issue by tjvman** [concourse/concourse#1360]
# Feature Request

## What challenge are you facing?
We'd like to have a way to check whether or not we're logged in to our Concourse for scripting purposes because doing `fly -t foo login` requires user interaction (clicking on the auth link) that we'd prefer to avoid when possible. 

Currently, we have to rely on the exit status of a command (e.g. `fly workers`) to determine our login status.

**Comment by shashwathi** [comment]
@tjvman : 

Modest Proposal:

`fly -t foo status` command which validates JWT token. If its invalid (expired/malformed/not valid target) then command will exit 1 with helpful error msg.

**Comment by tjvman** [comment]
@shashwathi Thanks! Will this be going out in the next release of Concourse?

**Comment by jama-pivotal** [comment]
Looks like it'll make it into the next release after 3.10.0 @tjvman

**Comment by jama-pivotal** [comment]
@shashwathi just tried this in prod environment (ci.concourse-ci.org) ; rejected it on certain use cases...which I will do my best to capture now:

### `fly status` doesn't report the correct status after logging out

Steps to Reproduce:
1. Login to ci.concourse-ci.org using fly, aka `prod`
2. Execute `fly -t prod status`, you will see `Logged in successfully`
3. Execute `fly -t prod logout`, you will see a confirmation `logged out of target: prod2`
4. Execute `fly -t prod status`
- Expected to see i'm logged out...but still reports that I'm logged in

### `fly status` doesn't use the same error message when given unknown target

The `status` command should give an alternate output when given an unknown. For example
`fly -t fdsa status` gives a response of `Please login again. : unknown target: fdsa`. 

I would have expected the usual response: `error: unknown target: fsda`, which is the same output when trying to do something like `fly -t fsda login`

## `fly status` output should follow the styling of the other output responses
...which happens to not be grammatically correct, but c'est la vie. Generally you'll notice that stdout doesn't capitalize the beginning of sentences, so we should reframe to:

* `logged in successfully`
* `logged out`

**Comment by shashwathi** [comment]
- [ ] Handle case for no tokens(logged out)
- [ ] Update the output to maintain consistent styling
- [ ] Update error msg for unknown target

**Comment by jama-pivotal** [comment]
Looking good, accepting
