### ISSUE TITLE
Opt-in analytics for Concourse versions

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1361]
# Feature Request

## What challenge are you facing?

As a product manager at Pivotal who's helping with Concourse, its hard to make product decisions without data around what versions of Concourse is commonly installed by users. For example, if we discover a nasty bug or a CVE that needs to be patched; the Concourse team would also want to know if we absolutely *need* to patch a prior version as well because of a high density of users around a specific version. Right now, the only way to access this information is through surveys, but it would be nice if we can start collecting anonymous, opt-in analytics. 

## A Modest Proposal

It would be nice to introduce an opt-in analytics package into future versions of Concourse. This function would "phone home" the version of Concourse that is being used. We would not enable this by default, but ask if the user would like to turn it on when they first use the ATC.

**Comment by topherbullock** [comment]
Lets add this as a flag to the binary `--telemetry-opt-in` and default it to false;
Then we can add a BOSH property which configures this flag. (Docker should be free from the magical env vars stuff).

We should also document what we track and assert our responsibility in collecting these metrics, and that we don't track anything specific to the user, atc, ip, whatever personally identifiable info.

**Comment by vito** [comment]
Sounds like there's more work to be done (the "asking a user on ATC start") - removing the `completed` label. This probably needs design now?

**Comment by jama-pivotal** [comment]
Reverted code and closing because we need to think deeper about a responsible data collection strategy
