### ISSUE TITLE
One worker causing resource check errors

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#1366]
# Bug Report

I've been having an issue with one of three workers that I have no clue what could be about (maybe someone here may have more insight).

One of the three workers I'm running, as soon as it starts and registers with the ATC, starts printing the follwing error messages (repeated over and over for different handles and sessions):
```
Jul 07 13:03:54 n0 concourse[25332]: {"timestamp":"1499432634.095834017","source":"guardian","message":"guardian.api.garden-server.get-property.failed","log_level":2,"data":{"error":"property does not exist: concourse:resource-result","handle":"3dd4ff85-1800-44dd-6571-1a9f6f080881","session":"3.1.355"}}
```

In the ATC logs I see this (example - seems to happen to all git and docker image resources whose check containers were assigned to the affected worker):
```
Jul 07 12:45:48 m1 concourse[7151]: {"timestamp":"1499431548.373970985","source":"atc","message":"atc.create-job-build.trigger-immediately.try-start-next-pending-build.do.aggregate.get.create.failed-to-fetch-resource","log_level":2,"data":{"build-id":903,"build-name":"70","error":"resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 128","job_name":"x-build","name":"x-src","session":"1109652.1.1.8.6.3.4"}}
(...)
Jul 07 12:52:51 m1 concourse[7151]: {"timestamp":"1499431971.644186258","source":"atc","message":"atc.syncer.x-service:radar.scan-resource.interval-runner.tick.image.init-image.create.failed-to-fetch-resource","log_level":2,"data":{"container":"c7d24906-5578-4787-4419-b37922b3f300","error":"resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1","pipeline-scoped-name":"x-service:resource:x-maven-cache","session":"16.11.206.1.1839.2.1.4"}}
```
The x-src is a simple git repo resource, the x-maven-cache is a custom resource type (similar to [maven-cache-resource](https://github.com/olhtbr/maven-cache-resource/)

In the web UI the erros I see are the following for git resources:
```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
and for a custom resource
```
resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1
```

When I retire the affected worker and stop it, things go back to normal. I've tried clearing the worker dir completely but after I start the affected worker, these errors start to show up again.
All 3 workers are running the exact same config and are essentially clones of each other (minus their interface IPs ofc).

The only other potentially relevant log messages I see in the worker are:
```
Jul 07 12:28:07 n0 concourse[25332]: {"timestamp":"1499430487.711537123","source":"guardian","message":"guardian.unable-to-load-aufs","log_level":2,"data":{"error":"exit status 1"}}
(...)
Jul 07 12:28:07 n0 concourse[25332]: 2017/07/07 12:28:07 failed to forward remote connection: dial tcp 127.0.0.1:7777: getsockopt: connection refused
```
The former I see in all my workers, the latter is strange because after starting the worker I can see concourse is listening on the mentioned port:
```
$ netstat -tupln | grep -E "7777|7788"
tcp        0      0 127.0.0.1:7777          0.0.0.0:*               LISTEN      25332/concourse 
tcp        0      0 127.0.0.1:7788          0.0.0.0:*               LISTEN      25332/concourse
```

Not sure if this started after updating to 3.2.1 (from 3.1.1) but this particular worker was working fine before. The only other thing I can think of that might be relevant is that my pipelines are all using customer resource types.

My setup:
* Concourse version: 3.2.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: IaaS (all workers running on VMs)
* All workers using overlay
* Did this used to work? Yes

**Comment by jadekler** [comment]
Seeing this, too

**Comment by dmlemos** [comment]
Saw this now on 3.4.0
