### ISSUE TITLE
BaggageClaim volume creation should have an async API

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1368]
We can bump the timeout as much as we want but given that it can be O(N) based on the strategy no timeout will ever suffice for everything.

Let's make it async so we don't even need a crazy timeout.

**Comment by SHyx0rmZ** [comment]
I'm currently trying my hands at implementing this. Progress can be followed at https://github.com/SHyx0rmZ/baggageclaim/tree/async-volume-creation. I will create a pull request once I have verified it's actually solving the problem and have written tests. I'll gladly accept any feedback.
