### ISSUE TITLE
Issues with Concourse on Docker

### ISSUE THREAD

**Issue by conteit** [concourse/concourse#1370]
# Bug Report

I've followed instructions at [https://concourse.ci/docker-repository.html](https://concourse.ci/docker-repository.html) for installing the latest Concourse on my Docker. The only difference is that I've launched it `docker stack deploy concourse` because I've inited _swarm-mode_ (with a single node).

I've tried to run the [hello-world](https://concourse.ci/hello-world.html) but the task (say-hello) states that there are "no workers". I've also tried to build [concourse-maven-spring-boot](https://github.com/spilth/concourse-maven-spring-boot) but in this case the UI reports "checking failed: base resource type not found".

* Concourse version: 3.3.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: VMWare virtual-machine, debian jessie ISO
* Browser (if applicable): Chrome, Safari
* Did this used to work? Never worked

**Comment by jtarchie** [comment]
@conteit, does swarm mode support docker links the same way as a single `docker-compose` does? That could be affecting how they communicate with each other.

**Comment by jtarchie** [comment]
When I tried running this locally, first time stack command, the very first thing I see is `Ignoring unsupported options: links, privileged, restart`.

You might have to modify the references of hostnames to be actual IP addresses.

**Comment by conteit** [comment]
As far as I know `links` is not required since, as long as you refer to the other services with their name (e.g. concourse-db) the internal DNS is able to address the right sibling.

The `restart` option became `restart_policy` and has slightly different syntax, but should not interfere with standard operations.

The `privileged` option seems to be not available. Could it be the issue?

**Comment by chendrix** [comment]
@conteit yes that could very well be the issue.

`docker stack` is not one of the team's supported deployment mechanisms

**Comment by jtarchie** [comment]
@conteit: It looks like it does [support](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#restart) it. Are you able to verify it works for you?

**Comment by conteit** [comment]
I've tried also running it with simple `docker-compose` but the build fails asserting:
`devices: disable multicast snooping: operation not supported`
Maybe something in the VM configuration interferes.

I've also retried to start it with `stack deploy` but know concourse-worker fails 
```
root@vm-docker stacks/concourse# docker stack ps concourse
ID            NAME                          IMAGE                       NODE       DESIRED STATE  CURRENT STATE           ERROR                      PORTS
3gi8rafs98j9  concourse_concourse-worker.1  concourse/concourse:latest  vm-docker  Ready          Ready 4 seconds ago
gqgjo53gpnsf  concourse_concourse-db.1      postgres:9.5                vm-docker  Running        Running 2 minutes ago
r0ul6mw76ma5  concourse_concourse-worker.1  concourse/concourse:latest  vm-docker  Shutdown       Failed 4 seconds ago    "task: non-zero exit (1)"
sxu1il7g6lay  concourse_concourse-web.1     concourse/concourse:latest  vm-docker  Running        Running 41 seconds ago
```

**Comment by gangefors** [comment]
`docker stack deploy` will not work due to no `privileged` support. There is a feature in the works that hopefully will solve this issue. No word on when it will be included though.
https://github.com/moby/moby/issues/32801

But swarm mode aside, not even the documented compose file and instructions work. As @conteit have reported, I get the same error when running the `01_task_hello_world` tutorial from starkandwayne will fail.
```
01_task_hello_world git:(master) $ fly --target tutorial execute --config task_hello_world.yml
executing build 1
initializing
devices: disable multicast snooping: operation not supported
errored
```

Here are the logs from docker-compose: https://gist.github.com/gangefors/8cf08b6e76e56a3b3b2cf3b2d09a7ff0

My system info:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie

---

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:59 2017
 OS/Arch:      linux/amd64
 Experimental: false

---

Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /media/storage/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 147
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.68GiB
Docker Root Dir: /media/storage/var-lib-docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by jtarchie** [comment]
@gangefors, I'm going to close this issue as it is related to `docker swarm`. We've validated that it does not have the feature set needed to work with the docker-compose file we've provided.

As for your issue, please open another or ask in other outlets for help.

**Comment by gangefors** [comment]
I managed to solve my issue by upgrading the kernel from 3.16 to 4.9.

It seems that Debian Jessie's default 3.16 kernel is too old to run Concourse. Concourse needs kernel 3.19+ (which is mentioned in the standalone binary section of the documentation) but if one jumps directly to the docker repository section this information is easily missed.

I'd suggest making it clearer that even when running with docker, the host kernel is as important as the kernel when running with a stand alone binary.
