### ISSUE TITLE
Build details don't load in MS Edge

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1375]
# Bug Report

I'm frequently using lots of different browsers for web dev and just noticed that I can't open build details in MS Edge (e.g. `/builds/2188`)

Instead, I see this error logged on the Javascript Console

```
'EventSource' is undefined
elm.min.js (13,28116)
```
* Concourse version: 3.3.1
* Browser (if applicable): MS Edge
* Did this used to work? Don't know

**Comment by jtarchie** [comment]
Apparently this is a documented [issue](https://wpdev.uservoice.com/forums/257854-project-spartan-platform/suggestions/6263825-server-sent-events-eventsource) with Edge. It doesn't support SSE through Javascript.

Maybe we can use a polyfill to _backwards support_ browsers?

**Comment by iswix-llc** [comment]
I have IE, Edge and Chrome on my machine and Chrome is the only one Concourse will work on.  The other two login and say there are no pipelines.  Fly login returns some stack trace when I try to visit the URL to get my token.  The concourse website itself renders wierd on IE.   I figured I better just use Chrome...

**Comment by labrown** [comment]
I, too, see no pipelines when I log into concourse 3.8.0 from Internet Explorer.  Chrome works fine.

**Comment by jama-pivotal** [comment]
still broken

**Comment by deniseyu** [comment]
We tested in a Windows 10 VM in Edge and validated that build pages are still broken:

<img width="1344" alt="Screen Shot 2019-05-13 at 4 14 08 PM" src="https://user-images.githubusercontent.com/8420094/57651134-85b29f00-759a-11e9-8313-47cc23e7281b.png">

Looks like Edge also isn't rendering the resource icons correctly either.

<img width="1316" alt="Screen Shot 2019-05-13 at 4 15 14 PM" src="https://user-images.githubusercontent.com/8420094/57651140-877c6280-759a-11e9-9dac-3fafc119c89f.png">

cc @jama22

**Comment by taylorsilva** [comment]
Microsoft fixed this by switching edge to be chromium-based: https://en.wikipedia.org/wiki/Microsoft_Edge#Anaheim_(2019%E2%80%93present)
