### ISSUE TITLE
As a user, I should be able to see what version of concourse is running from the web UI

### ISSUE THREAD

**Issue by cobyrne** [concourse/concourse#138]

**Comment by jchester** [comment]
I was about to add this also. When I'm trying to sort out a CLI / web UI mismatch, seeing the version on the web interface would be a helpful hint.

I had a problem where an old version of the `concourse/lite` box was on my local system. When I created a new concourse environment following the 'getting started' instructions, that older box was used. Running `vagrant box update` did not seem to properly upgrade it -- but I didn't have a clear way to tell that. Vagrant's CLI told me everything was hunky dory, `fly` reported its version as 0.0.1 and the web UI gave no clues.

On a hunch I looked for old boxes, nuked them and started from scratch, which resolved my problem.

If I was better acquainted with Concourse development I might have realised that `fly` [lost the `-v` option circa 0.66](https://github.com/concourse/concourse/issues/204).
