### ISSUE TITLE
Web UI URL for viewing the "latest" build of a job.

### ISSUE THREAD

**Issue by jemc** [concourse/concourse#1381]
# Feature Request

## What challenge are you facing?

When setting up [CI badges](http://engineering.pivotal.io/post/concourse-badges/) in my README.md files, I want clicking on the badge image to take me to the build output for the latest build.

Concourse already has a URL for viewing the job itself:

> http://my-server/teams/my-team/pipelines/my-pipeline/jobs/my-job

But I find that when I see a failed status on a CI badge, my most pressing need is always to see the build output, which is an extra click-through from the "View Job Details" page. I've come to expect from other CI systems that the CI status badge will take you directly to the output of the latest build, which you can then use for debugging, etc.

This issue is further compounded with the fact that those viewing the badges for my open source projects may not be familiar with the Concourse UI, and may not know where to click from the "View Job Details" page to see the actual build output.

I'd like to remove that step for them and have a hard-coded link in the README to the latest build output for a given job.

I can already link to the output of a specific build number, as in:

> http://my-server/teams/my-team/pipelines/my-pipeline/jobs/my-job/builds/1

But in the static README, I have know way of getting the correct number for the latest build.

## A Modest Proposal

Add the following UI request path, which resolves to the latest build known to ATC at the time the HTTP request came in:

> http://my-server/teams/my-team/pipelines/my-pipeline/jobs/my-job/builds/latest

**Comment by jama-pivotal** [comment]
Yup
