### ISSUE TITLE
Auto Hiding Legend

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1388]
# Feature Request

## What challenge are you facing?
The legend is a nifty feature to have on the ATC web UI but it starts to get in the way when viewing very large/dense pipelines

![screen shot 2017-07-17 at 11 24 13 am](https://user-images.githubusercontent.com/19274230/28275647-82c33f4e-6ae2-11e7-9cc8-029df0c7b865.png)

## A Modest Proposal
I don't think moving the legend around would be a good solution because of the different size and shapes of pipelines that are out there. I also don't think a "hide" button would be a good idea either, since it kind of goes against the Concourse anti-pattern of "knobs and dials". 

If possible, I would like to auto-hide the legend after 10 seconds of keyboard and mouse inactivity on the browser. This would be really handy especially when I just have my pipelines up on the screen for display

**Comment by mhuangpivotal** [comment]
This feature is complete. Next step is to add a test in testflight. WIP branch: `wip-issue-1388`.

**Comment by clarafu** [comment]
We added a testflight test.

**Comment by jama-pivotal** [comment]
Accepting!
