### ISSUE TITLE
Keyboard Shortcut on Web UI to reset the pipeline and "fit to canvas"

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1389]
Hi there!

# Feature Request
## What challenge are you facing?
When viewing big pipelines, its easy to get lost when zooming in and out in the web UI

## A Modest Proposal
It would be nice if I could hit a keyboard shortcut (e.g. "F") to recenter the pipeline and set the zoom to auto fit everything back into view again!

**Comment by chendrix** [comment]
ok so I've completed this but should we publicize this keyboard shortcut somehow? Do we need some kind of help instead of just the legend?

**Comment by mhuangpivotal** [comment]
This is ready to be merged on branch `wip-issue-1389`. Also consider adding a test in testflight.

**Comment by jama-pivotal** [comment]
Neat!
