### ISSUE TITLE
Vault: drop the Credential Lookup Rules in favor of full Vault paths

### ISSUE THREAD

**Issue by ringods** [concourse/concourse#1391]
# Feature Request

## What challenge are you facing?

I am very grateful for the Vault integration. After my initial reading of the [Credential Management page](http://concourse.ci/creds.html), specifically the *Credential Lookup Rules*, I have the impression that you missed something about how Vault works.

Vault supports multiple secret backends which can be mounted at different top level mount points. When using static secrets, I use the `generic` backend and we mount it typically on `/static`. For dynamic short lived AWS secrets, we use the AWS secret backend (not to be confused with the AWS auth backend), mounted on `/aws_<env>`. For dynamic short lived database credentials, we use the MySQL secret backend, mounted on `/db_<env>`.

In a pipeline, one usually wants to mix static secrets with dynamic AWS and DB secrets. Currently, the lookup strategy locks me up in a single top level path, meaning a single Vault secret backend. As a result, I can't integrate Concourse with how we currently rolled out Vault. With multiple secret backends that is.

## A Modest Proposal

The easiest change that can be done is to drop the `Credential Lookup Rules` implementation and allow full Vault paths in the Concourse pipelines.

**Comment by ringods** [comment]
Given @jtarchie's [comment](https://concourseci.slack.com/archives/C07RY25QF/p1500382692645062) in Slack:

> I think the team is open to other conventions to be discussed. This really was the first past at integration with a 3rd party credential manager. We were basing it off convention that would work for an operator of concourse, not the pipeline devs.

As everybody will probably have different Vault mount points, I'm asking to not come up with another _convention_. You will not be able to match everybody's Vault setup.

**Comment by jtarchie** [comment]
@ringods, does the aws mount support the rotation of keys, too. At the moment, our integration with vault would not fully support that. We don't get a state of the world from vault, we look up each key, so if we happen to look up a set of keys that rotate during lookup, there would be an issue, correct?

This is more my lack of understanding vault backends that I am trying to clarify.

**Comment by ringods** [comment]
@jtarchie it depends a bit how you interpret "rotation". Let me elaborate.

First, the AWS secret backend supports 2 types of AWS secrets: [dynamic IAM users](https://www.vaultproject.io/docs/secrets/aws/index.html#dynamic-iam-users) and [STS secrets](https://www.vaultproject.io/docs/secrets/aws/index.html#sts-credentials).

In Vault, you retrieve a set of credentials by _reading_ a mountpoint. Given the AWS secret backend is mounted on `/aws`, you retrieve credentials matching to a certain AWS role as:
* `/aws/creds/<role name>` for a dynamic IAM user: Vault goes off to AWS and creates an IAM user on demand and links it to the AWS role. After the configured lease time, Vault goes out to AWS again and removes this user.
* `/aws/sts/<role name>` for a set of STS credentials: Vault access the STS API and retrieves a set of credentials which have a standard TTL of 1 hour (enforced by AWS STS). No cleanup needs to be done by AWS.

In Concourse context, I would configure Vault lease times equal or longer than a single build duration. This means that the credentials will be valid during the build and Concourse does not need to think of "refreshing" credentials. I would even urge the Concourse team to keep it simple and just document that Vault users need to adapt lease times to match the build duration.

**Comment by vito** [comment]
I'm pretty confused by this. The current implementation does not lock you in to using one mount path. All the path lookups are `/concourse/<team>/<pipeline>/<name>`. You can mount whatever you like at that path. They can even overlap; Vault allows you to mount a generic store at `/concourse` and then any other type of backend at `/concourse/foo`.

We do not however allow looking at toplevel paths outside of the predefined namespace. We considered supporting it but it raised a few security concerns that we weren't ready to answer (e.g. letting team A trivially read team B's credentials).

**Comment by sarudak** [comment]
I feel like Team A reading Team B's credentials to the extent it's a problem can be easily solved by limiting the auth policy associated with the token you give to concourse.

**Comment by jtarchie** [comment]
@sarudak, this would require more work than that. As the token provided to concourse is on a deployment basis, not a per team basis.

Given @vito's explanation, vault can support mounts in the specific paths. An `aws` mount can be pushed into the `/concourse/path` etc.

**Comment by rappelsen** [comment]
@jtarchie 

i try to get values for our test project from /concourse/secret/tester but i'm not able to get values from a different path expect /concourse/<teamname>/<project> or /concourse/<teamname>
did i miss something?
`
jobs:
- name: aws-test
  plan:
  - task: aws-print-envs
    params:
      path-:
      FOO: ((secret/tester))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: sh
        args:
          - -exc
          - |
            env
`

output:

`+ env
USER=root
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FOO=((secret/tester))
PWD=/tmp/build/c12b7b82`
