### ISSUE TITLE
Check resource fails with 'container disappeared from db'

### ISSUE THREAD

**Issue by jdeppe-pivotal** [concourse/concourse#1392]
# Bug Report

Since upgrading to `3.3.1` we're seeing check resources fail a lot with the error `container disappeared from db`. Subsequent checks will usually pass so the error is intermittent.

The worker's garden log also contains 1000s of errors like:
```
{"timestamp":"1500392331.401661634","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: 85d8e3a6-3473-4ca3-5bb6-a79f2a8364e6","handle":"85d8e3a6-3473-4ca3-5bb6-a79f2a8364e6","session":"4.1.1465276"}}
```
which seem to be related.

* Concourse version: 3.3.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Did this used to work? Yes

**Comment by popov-ilya** [comment]
We are also seeing this problem on 3.3.2, but only when using Vault for getting creds in pipeline. Also the amount of containers varies from ~80 without using Vault to 10-20 with Vault.

**Comment by jdeppe-pivotal** [comment]
Interesting - we've also started using Vault with this release, but I didn't associate this error with that change.

**Comment by popov-ilya** [comment]
You can check it quite simply, even on 3.3.2 you won't see this error if use pipeline with plain-text params.

**Comment by barutm** [comment]
Hi, 
I am having an intermittent resource checking issue as well, just after adding vault on Bosh for credentials management. I am on Concourse 3.3.1.

**Comment by vito** [comment]
Rolling this in to https://github.com/concourse/concourse/issues/1413
