### ISSUE TITLE
small typo in the set-pipeline fly help

### ISSUE THREAD

**Issue by norman-abramovitz** [concourse/concourse#1394]
$ fly --version
3.3.2

There is a typo in the description for yaml-var parameter.   The text is bolded that needs correction.
$ fly set-pipeline -h
...
-y, --yaml-var=[NAME=YAML]    Specify a YAML value **tos et** for a variable
                                    in the pipeline

**Comment by mhuangpivotal** [comment]
This was fixed in https://github.com/concourse/fly/pull/180.
