### ISSUE TITLE
full busybox packaging can cause other colocated release to break

### ISSUE THREAD

**Issue by poblin-orange** [concourse/concourse#140]
Hello,
as concourse has no support for http_proxy (yet), i tried to workaround the issue using cf-networking bosh release (set the default gateway of workers vm to an in house transparent proxy gateway).

Seems thats the full busy box distrib is packaged in concourse, conflicting with the /sbin/route commend see issue https://github.com/cf-platform-eng/networking-boshrelease/issues/1

Should concourse packages add conflicting bins with the root stemcells binary ?

**Comment by vito** [comment]
Replied in the related issue, no idea what this is about. I have the correct version of `/sbin/route` in my environments.
