### ISSUE TITLE
scp (write-only) resource

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#141]
For some of my more low-tech deploy stagess, I find myself scp-ing files across from the worker to the target VM. Currently i'm achieving that with the `scp` command inside a task, but it feels more 'concoursey' to have this as a resource.

I'm happy to create this - just want to get some thoughts before I embark.

In case it's not clear from the title - I anticipate this being an `out` only resource, to avoid any aspects of versioning.

**Comment by joshzarrabi** [comment]
Closing this for now.

**Comment by chris-aeviator** [comment]
@joshzarrabi there's zero documentation provided on the link :-/
