### ISSUE TITLE
Investigate influxdb metrics schema design

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1412]
During the investigation of work in concourse/concourse#1411, it was found that if we were running into issues of needing to set `max-values-per-tag` and `max-series-per-database` we were probably running into [poor schema design](http://docs.influxdata.com/influxdb/v1.0/concepts/schema_and_data_layout/#discouraged-schema-design)

We should further investigate our schema design for influxdb, as it could very well be impacting the amount of memory used.

**Comment by xtremerui** [comment]
The link to influxdb doc indicates it is for v1 client only.
