### ISSUE TITLE
Add description, owner and tags for a pipeline?

### ISSUE THREAD

**Issue by paul-guo-** [concourse/concourse#1414]
Hi there!

# Feature Request

## What challenge are you facing?

I've been seeing this scenario a lot of time: A lot of pipelines are set in a concourse instance, some of them are for product release and some are for personal development or even for testing. So for cross-team corporation, it  is rather inconvenient to find or understand correct pipelines, besides sometimes it is hard to find people to ask or discuss, and after long time it is also not convenient for admin to do cleanup job.

I roughly looked into the concourse job but did not find anything for that.

## A Modest Proposal

So maybe we could allow users to: 1) Add description for each pipeline. 2) Add owners (e.g. team email alias or developer-self) for each pipeline so admin or users could easier contact them (automatically or not). Description and owner could be set in the fly command or set in the pipeline yaml file.

Also maybe we could allow admin to add tags for certification for some important pipeline. (e.g. release pipeline).

**Comment by jtarchie** [comment]
My only hesitation is that this implies a certain workflow. For example, someone *owns* a pipeline. I've been on teams where all team members were responsible for owning the pipeline. Our concourse team name was our internal team name, which meant anyone knew they could come up to us to ask questions.

I don't think concourse should have an opinion about ownership. As every person probably has a opinion about that.

Descriptions, make sense to me. I believe there is an issue for this already.

**Comment by topherbullock** [comment]
https://github.com/concourse/concourse/issues/1117

**Comment by topherbullock** [comment]
Closing this in favour of the more general use cases in the issues above.
@paul-guo- please provide any additional feedback on the existing issues.

**Comment by paul-guo-** [comment]
Maybe I did not express clearly. For the ownership, for example, if I have concern for a new fly-ed or existing pipeline (e.g. the pipeline is probably relevant to my work according to pipeline name or description), I want to email to one who could answer questions for that pipeline. This is needed if: 1) the concourse instance is shared by a big team so sometimes the cross-team communication is not that good. 2) Some developers might always forget to clean up their dev/test/expired pipelines so admin could easily  contact related people.

**Comment by topherbullock** [comment]
@paul-guo- Thanks for clarifying; we're looking into these types of scenarios more. For the new UI issue #1259 we're hoping to add a way for "pipeline developers" to add a free-form description to describe the purpose, point of contact, whatever they want for a given pipeline. Hopefully this will address your need to add an email, and can be leveraged for other workflows as well.
