### ISSUE TITLE
www.concourse.ci should redirect to concourse.ci

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1416]
# Bug Report

When trying to visit [www.concourse.ci](www.concourse.ci) I get an error:
```
404 Not Found: Requested route ('www.concourse.ci') does not exist.
```

The site should just automatically redirect the user to [concourse.ci](concourse.ci)

**Comment by andrewedstrom** [comment]
+1

**Comment by mhuangpivotal** [comment]
I added the route `www.concourse.ci` manually on PWS. Is there a deployment manifest for the `docs` app where the routes are specified?

**Comment by topherbullock** [comment]
This failed when pushing the docs; I don't think its enabled in our CF Org , so we'll have to add it somehow.

https://ci.concourse.ci/teams/main/pipelines/main/jobs/push-docs/builds/62

**Comment by jama-pivotal** [comment]
Changes were made 9 hours ago, and docs were pushed an hour ago with green pipelines. Site looks fine with www and no wwww, accepting!
