### ISSUE TITLE
Configurable default build_logs_to_retain

### ISSUE THREAD

**Issue by jim80net** [concourse/concourse#1417]
# Feature Request

## What challenge are you facing?

We’ve been concerned with concourse’s default behavior to keep an indefinite amount of build history by default. 

Because we have some builds that produce a lot of logs, and since we don't always remember to set build_logs_to_retain, concourse falls over for some DB migrations during upgrades. This is because the migration becomes bottlenecked for several minutes/hours by the IO requirements of reading a bajillion lines of build log. 

Setting a build log limit is optional
https://concourse.ci/single-page.html#build_logs_to_retain

And doing so resolves the issue, but I have to do it for every pipeline. 

## A Modest Proposal

The default build log limit is infinity and unchangeable. 

I believe the default build log limit should be configurable globally, by specifying the value that the team that deploys concourse desires to be the default value, whether it's 100, 10000, or -1.

**Comment by dmlemos** [comment]
I would also like to see this implemented. Over time the build logs on a shared concourse get big.
Many teams also neglect the `build_logs_to_retain` setting, which means there are hundreds of builds that get accumulated and will never be checked.

**Comment by aeijdenberg** [comment]
https://github.com/concourse/atc/pull/258 adds some global options to set build log retention:

```bash
atc ...\
    --default-build-logs-to-retain 10 \
    --max-build-logs-to-retain 1000
```

Hope that's helpful - we hit this issue yesterday whereby our database ran out of space - would be nice to be able to set a global default and maximum.

**Comment by chbiel** [comment]
Hi @aeijdenberg, I found here what I was search for but is there more documentation e.g. does `default-build-logs-to-retain` apply to every job? And is `max-build-logs-to-retain` the max number of build over all jobs? What happens when that number exceeds?
And most important: How to configure this when using the `concourse/concourse` docker container for running concourse? Can this be set via ENV?

Thanks in advance!
