### ISSUE TITLE
External Worker disconnects from Concourse ATC frequently

### ISSUE THREAD

**Issue by mervyn777** [concourse/concourse#1418]
I've setup concourse using docker on my mac mini. I've also setup the darwin worker on the same machine that's connected to the concourse ATC.

Everything works just fine until after few hours (or overnight) the darwin related tasks fail because the build scheduler cant find the darwin worker anymore. When I check the workers status from Fly command the darwin worker is stalled. This happens almost once every 24 hours. The only way I get it back to work is by restarting Docker itself and not the ATC within docker or the external worker. This process takes anywhere between 60 and 90 minutes for everything to get up and running i.e. for the git sources to be checked (cloned) successfully for all the pipelines and turn from orange to black. Also why this long delay just to start checking from git successfully?

Please note I don't even shutdown and restart my darwin worker that heartbeats the messages. So the darwin worker seems to work fine but something is making the ATC lose connection with this worker unless I restart the docker again. Once restarted the ATC reconnects itself back to the worker and all workers are in "running" state when checked through fly.

**Comment by mervyn777** [comment]
Any info on this issue so far?

**Comment by vito** [comment]
To be honest, it's unlikely that we're going to make any headway on this. We run a Darwin worker successfully ourselves and have never seen this happen, so it's unlikely to be a general Darwin issue. It sounds more characteristic of either network issues (which we cannot really hope to debug effectively on our end) or something silly like the machine going to sleep.

**Comment by mervyn777** [comment]
@vito If the issue was with the network or the machine going to sleep how can the worker continue to heartbeat successfully? Shouldn't that also get suspended or killed? I checked the server and its always in running state (Have set to not sleep forever) and its connected to company lan network directly.

We are using this same server for other build purposes too and the services are always up.
