### ISSUE TITLE
Bug: Volume creation issues for Concourse 3.3.3

### ISSUE THREAD

**Issue by kmacoskey** [concourse/concourse#1419]
# Bug Report

We run a large deployment, with an average of 1000 active containers. This is a bosh deployment on AWS.

+ Web: 4 Instances
+ Workers: 20 Instances
+ DB: 1 Instance

```
Workers:
    instance_type: m4.2xlarge
    ephemeral_disk: {size: 400000, type: gp2}
```
Our deployment was running V 2.7.3 successfully for a good length of time. The issue we want to report occurred when migrating the deployment to V 3.3.3. 

After performing the upgrade successfully, the deployment was stable for a few hours, but the following error started to occur in various jobs, tasks, and pipelines: `failed to create volume`. These errors started immediately after the workers came on line. Over time (the course of a day) the error increased in occurrence to the point that check containers were failing and the deployment was becoming unusable. Retriggering jobs that would fail with this error would inconsistently be successful in running without error.

The rest of the information I can provide is many errors being found in logs of the various components in the deployment. I have not tried to correlate specific timestamps across the different components (baggeclaim, garden, atc) because there really is just a giant block of 1000's of these errors that started immediately after upgrading to 3.3.3 (there is no log history above these errors to help).

Because of this problem, we were forced to downgrade to V 2.7.3.

Baggage claim on a worker, many 1000's of this error for many volume ID's:
```
{"timestamp":"1501172476.309107304","source":"baggageclaim","message":"baggageclaim.api.volume-server.create-volume.failed-to-create","log_level":2,"data":{"error":"mkdir /var/vcap/data/baggageclaim/volumes/init/52b34a03-20ac-4ad6-585f-f86668fdfb71: read-only file system","handle":"52b34a03-20ac-4ad6-585f-f86668fdfb71","privileged":false,"session":"5.1.1209877","strategy":{"type":"cow","volume":"dffc2f2c-40ac-4049-7d99-bb8954ab3666"},"ttl":0}}
```
as well many 1000's of this error for many volume ID's:
```
{"timestamp":"1501172470.418607712","source":"baggageclaim","message":"baggageclaim.api.volume-server.destroy.failed-to-destroy","log_level":2,"data":{"error":"rename /var/vcap/data/baggageclaim/volumes/live/a5c7322c-ca32-49c0-6417-1959aaa7e7e0 /var/vcap/data/baggageclaim/volumes/dead/a5c7322c-ca32-49c0-6417-1959aaa7e7e0: read-only file system","session":"5.1.1209871","volume":"a5c7322c-ca32-49c0-6417-1959aaa7e7e0"}}
```
From garden logs, many 1000's of this error for many handles (what are handles in this case?):
```
{"timestamp":"1501172471.342699289","source":"guardian","message":"guardian.destroy.start","log_level":1,"data":{"handle":"ebf6c074-6fe3-4588-722a-fe9f865a28e3","session":"814285"}}
{"timestamp":"1501172471.342769146","source":"guardian","message":"guardian.destroy.finished","log_level":1,"data":{"handle":"ebf6c074-6fe3-4588-722a-fe9f865a28e3","session":"814285"}}
{"timestamp":"1501172471.342786789","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: ebf6c074-6fe3-4588-722a-fe9f865a28e3","handle":"ebf6c074-6fe3-4588-722a-fe9f865a28e3","session":"4.1.890021"}}
```
From the ATC, many 1000's of this error for many container ID's:
```
{"timestamp":"1501174329.887878895","source":"atc","message":"atc.container-collector.run.destroy-container.failed-to-destroy-database-container","log_level":2,"data":{"container":"ebf6c074-6fe3-4588-722a-fe9f865a28e3","error":"pq: new row for relation \"volumes\" violates check constraint \"cannot_invalidate_during_initialization\"","session":"28.4318.388","worker":"0d136953-9398-44eb-81af-af162f42e550"}}
```

#### Web Worker Logs
[gpdb5-ci-concourse.web.0becc346-ebba-44d9-8343-b7e18d1251e0-20170727-133156-107777815.aa.gz](https://github.com/concourse/concourse/files/1183444/gpdb5-ci-concourse.web.0becc346-ebba-44d9-8343-b7e18d1251e0-20170727-133156-107777815.aa.gz)
[gpdb5-ci-concourse.web.0becc346-ebba-44d9-8343-b7e18d1251e0-20170727-133156-107777815.ab.gz](https://github.com/concourse/concourse/files/1183443/gpdb5-ci-concourse.web.0becc346-ebba-44d9-8343-b7e18d1251e0-20170727-133156-107777815.ab.gz)

#### Worker Logs
[gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.aa.gz](https://github.com/concourse/concourse/files/1183451/gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.aa.gz)
[gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.ab.gz](https://github.com/concourse/concourse/files/1183449/gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.ab.gz)
[gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.ac.gz](https://github.com/concourse/concourse/files/1183450/gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.ac.gz)
[gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.ad.gz](https://github.com/concourse/concourse/files/1183448/gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.ad.gz)

I've attached the complete logs for a single worker and for the web worker holding the ATC. I can provide more if desired. To extract, do this:

```
# Github has file size limits... sorry.

# The tarballs don't have a top level directory (thank you bosh)
mkdir -p /tmp/{worker,web}
mv ~/Downloads/gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.*.gz /tmp/worker/
mv ~/Downloads/gpdb5-ci-concourse.web.0becc346-ebba-44d9-8343-b7e18d1251e0-20170727-133156-107777815.*.gz /tmp/web/
cat /tmp/worker/gpdb5-ci-concourse.gpdb-worker.0d136953-76d1-4d6d-b23d-9a9ca5ea3cf5-20170727-132302-46805229.*.gz | tar -xvf - -C /tmp/worker/
cat /tmp/worker/gpdb5-ci-concourse.web.0becc346-ebba-44d9-8343-b7e18d1251e0-20170727-133156-107777815.*.gz | tar -xvf - -C /tmp/web/
```

P.S. JTArchie, thank you for your help on this so far, we very much appreciate it. I was asked to put this in a separate issue.

**Comment by thebeefcake** [comment]
@kmacoskey was this an upgrade to 3.3.3 or did you use a clean database and reset your pipelines, I have encountered the same thing going from 3.3.1 to 3.3.3 and have moved back to 3.3.1. I have not tried the upgrade on a new db and resetting pipelines at this stage.

**Comment by kmacoskey** [comment]
@thebeefcake This was an upgrade from 2.7.3 to 3.3.3 with a live system (by no means a clean database).

**Comment by snarlysodboxer** [comment]
Having the same problem on upgrade from 2.5.1 to 3.3.4 `failed to migrate database: pq: check constraint "addr_when_running" is violated by some row`. We have a small deployment in Kubernetes, and had a clean shutdown before upgrading.

**Comment by dpb587-pivotal** [comment]
We're running into this when upgrading from 2.5.1 to 3.4.0 as well. We truncated a few tables to workaround it in a test environment, but not sure if that's the correct thing to do. We'll have to do the upgrade for our prod environment at some point.

**Comment by kmacoskey** [comment]
@dpb587 What tables did you have to truncate? Did that cause any other issues after migrating?

**Comment by pandeybk** [comment]
I am also running into this problem. In my case I am not upgrading version, its a fresh installation (version 3.4.0). And I am running this in k8s cluster. 

```
{"timestamp":"1503699952.973575354","source":"atc","message":"atc.container-collector.run.destroy-container.failed-to-destroy-database-container","log_level":2,"data":{"container":"45483cb8-75f5-49e6-69fe-4ac42f499c13","error":"pq: new row for relation \"volumes\" violates check constraint \"cannot_invalidate_during_initialization\"","session":"30.9.2","worker":"concourse-worker-3365844120-mc18f"}}
```

**Comment by doty-pivotal** [comment]
@snarlysodboxer and @pandeybk,

I am reading through this issue, and I am a bit confused about the symptoms you are seeing.  In the original bug report:

> After performing the upgrade successfully, the deployment was stable for a few hours, but the following error started to occur in various jobs, tasks, and pipelines: `failed to create volume`.

but you are reporting the following errors:

> `failed to migrate database: pq: check constraint "addr_when_running" is violated by some row`

Are you also seeing the original `failed to create volume`, in your UI, and also have noticed your attached errors in addition? Or, is it possible that we are talking about a different distinct bug?

**Comment by pandeybk** [comment]
@doty-pivotal yes I am seeing original `failed to create volume` in fly cli.

```
fly -t example execute -c build.yml --verbose
2017/08/28 09:48:25 GET /api/v1/info HTTP/1.1
Host: concourse.dev.net
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2017/08/28 09:48:26 HTTP/1.1 200 OK
Content-Length: 43
Content-Type: text/plain; charset=utf-8
Date: Mon, 28 Aug 2017 15:48:25 GMT
X-Concourse-Version: 3.4.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block

{"version":"3.4.0","worker_version":"1.1"}

2017/08/28 09:48:26 POST /api/v1/pipes HTTP/1.1
Host: concourse.dev.net
User-Agent: Go-http-client/1.1
Content-Length: 0
Accept-Encoding: gzip


2017/08/28 09:48:26 HTTP/1.1 201 Created
Content-Length: 239
Content-Type: text/plain; charset=utf-8
Date: Mon, 28 Aug 2017 15:48:25 GMT
X-Concourse-Version: 3.4.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block

{"id":"36a1b603-f6ef-4a4b-461e-1b0f5231b7ea","read_url":"http://concourse.dev.net/api/v1/pipes/36a1b603-f6ef-4a4b-461e-1b0f5231b7ea","write_url":"http://concourse.dev.net/api/v1/pipes/36a1b603-f6ef-4a4b-461e-1b0f5231b7ea"}

2017/08/28 09:48:26 POST /api/v1/builds HTTP/1.1
Host: concourse.dev.net
User-Agent: Go-http-client/1.1
Content-Length: 1060
Content-Type: application/json
Accept-Encoding: gzip

{"id":"59a43b4e","do":[{"id":"59a43b4d","aggregate":[{"id":"59a43b4b","get":{"type":"archive","name":"flight-school","resource":"","source":{"authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmIjoiN2Q5NDk4MjlhMjkxY2Y3N2Q5ZDIwZTVkMzIwY2I2ZmE4YmI4M2VmNzNkMDE3NTl1MyIsImV4cCI6MTUwNDAyMTcwMywiaXNBZG1pbiI6dHJ1ZSwidGVhbU5hbWUiOiJtYWluIn0.mqqHwpheSqOWIGQiXlEKgB-tqi_AISEFQOHuEoDa8U-pKizL1FiX7IVdBpzWu52RBMud4X6eyjRsDAbeoawtjoleTQrdncMBWjLQ66boBqFeRBKyqAVaSG2_11Vnm9ZlCEi4Wr9CoAe1hF1LoWR589ofBV5YTcLvW1NB043FR6g0Lq2Mr0f1kur6Lbm8PMHFzQbtQrhMNc3-kHGX7ZwlRoRCEVcrlx-zCX11mooTw8lHzolJcfIW886IDlPfQspthC5Aa4pvDGvJ653KQPe58bmSSTO_ON4P5Uc1XF0lBF9Ozj0k4j_SzS9-VpJ4k1i66az20MLihYg","uri":"http://concourse.dev.net/api/v1/pipes/36a1b603-f6ef-4a4b-461e-1b0f5231b7ea"}}}]},{"id":"59a43b4c","task":{"name":"one-off","privileged":false,"config":{"platform":"linux","image_resource":{"type":"docker-image","source":{"repository":"busybox"}},"run":{"path":"./flight-school/ci/test.sh"},"inputs":[{"name":"flight-school"}]}}}]}

2017/08/28 09:48:26 HTTP/1.1 201 Created
Content-Length: 105
Content-Type: text/plain; charset=utf-8
Date: Mon, 28 Aug 2017 15:48:25 GMT
X-Concourse-Version: 3.4.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block

{"id":4,"team_name":"main","name":"4","status":"pending","url":"/builds/4","api_url":"/api/v1/builds/4"}

executing build 4
failed to create volume
errored
upload request failed: Put http://concourse.dev.net/api/v1/pipes/36a1b603-f6ef-4a4b-461e-1b0f5231b7ea: EOF

```

**Comment by szeraf** [comment]
We experience the same/similar issue. I don't think it is an upgrade related (it came out weeks after the 3.2.1 -> 3.3.1 upgrade).
On the UI we get the following error message:

`pq: new row for relation "volumes" violates check constraint "cannot_invalidate_during_initialization"`

The logs show these errors:

`{"timestamp":"1503562764.427136421","source":"baggageclaim","message":"baggageclaim.tick.failed-to-reap","log_level":2,"data":{"error":"f
ailed to determine parent of volume '41a1bc67-a5fc-4a75-6e72-dce7535fa839': volume does not exist","session":"1552"}}`

`{"timestamp":"1504001698.984323740","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"container already being destroyed","handle":"42da09ed-16be-4333-4f89-e6e630c07026","session":"3.1.96724"}}`

`{"timestamp":"1503564006.766349316","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: 20cab88e-94df-4329-4a44-e50d7deaa32c","handle":"20cab88e-94df-4329-4a44-e50d7deaa32c","session":"3.1.75205"}}`

We get this only on one job, the other ~dozen does not show similar symptomes.

**Comment by itsdalmo** [comment]
Seeing the same error on 3.6.0. I have multiple tasks (9 in total) running `terraform apply` under an `aggregate:` step - all of the apply's complete, but then I get the `pq: new row for relation "volumes" violates check constraint "cannot_invalidate_during_initialization"` error at the end.

Concourse version: 3.6.0
Installation: binary (pipeline is 1 week old, created with Concourse 3.6)
Backend driver: aurora-postgresql (on AWS)

Error message:

```
Nov 20 09:05:37 <ip> concourse[8128]:
{
    "timestamp": "1511168737.717862129",
    "source": "atc",
    "message": "atc.syncer.divx-account-setup:scheduler.tick.scheduling.try-start-next-pending-build.do.aggregate.retry.task.failed-to-run-action",
    "log_level": 2,
    "data": {
        "build-id": 58,
        "build-name": "2",
        "error": "pq: new row for relation \"volumes\" violates check constraint \"cannot_invalidate_during_initialization\"",
        "session": "<session id?>"
    }
}
```

On manually triggering the job after getting these messages it completed without issue (although I've had it fail with the same error on manual triggers before). I.e., it's an error that sometimes happens, and sometimes does not (on the same pipeline). Also, looking at the server logs I can see that they are basically being spammed with the following errors as well:

```
{
    "timestamp": "1511168830.817101717",
    "source": "atc",
    "message": "atc.volume-collector.run.orphaned-volumes.mark-created-as-destroying.failed-to-transition",
    "log_level": 2,
    "data": {
        "error": "volume cannot be destroyed as children are present",
        "session": "<session-ip>",
        "volume": "b8f86edc-d403-4793-4b99-ae705503e0d8",
        "worker": "<worker-ip>"
    }
}
```

By spammed I mean that several messages (9-14) like the above are logged in 30 second intervals. Seems like it might be related so I figured it was worth including.

**Comment by itsdalmo** [comment]
Some additional info:

Each task (9 in total) in my `aggregate:` step has 2 attempts, and today the job triggered once and failed, and then I manually triggered it 3 times before it finally passed - on the last job that succeeded, 4 of the tasks had produced the `pq: new row for relation "volumes" violates check constraint "cannot_invalidate_during_initialization"` error on the first attempt, and then succeeded on the 2nd attempt. There doesn't seem to be any pattern in which tasks fail or succeed, i.e. it's different ones each time I run it. 

When running `fly -t admin workers` I got the following:

```bash
name            containers  platform  tags  team  state    version
ip-10-9-15-172  30          linux     none  none  running  1.2
ip-10-9-19-225  15          linux     none  none  running  1.2
ip-10-9-21-224  8           linux     none  none  running  1.2
```

And after the job finally succeeded:

```bash
name            containers  platform  tags  team  state    version
ip-10-9-15-172  16          linux     none  none  running  1.2
ip-10-9-19-225  8           linux     none  none  running  1.2
ip-10-9-21-224  2           linux     none  none  running  1.2
```

In the last print of workers, I'm a bit surprised to see so many containers listed considering that nothing is actually running? When I ssh into e.g. `ip-10-9-15-172` and `ps aux | grep concourse` I can see a list of 16 `runc events <id>` as well.

Since the ID's listed with `runc events` have the same format as the `volume` in the 2nd error I pasted above, I figured they might be the same? But searching for any of the `runc events` ID's in the logs turned up 0 results, so none of those containers are actually producing the `"volume cannot be destroyed as children are present"` errors.

No idea whats going on here or how to proceed, but Concourse is basically unusable until this is fixed (can't trust that jobs will actually be run). Happy to provide additional info and/or help debug this any way I can.

**Comment by vito** [comment]
Closing as this is quite stale by now. Too much has changed since the initial report for us to really dig in with confidence.

**Comment by metacoma** [comment]
faced with this problem on 4.2.1 (installed from helm chart with managed postgres db)

```
NAME                             READY     STATUS    RESTARTS   AGE
concourse-web-5dbf64db94-8qnt6   1/1       Running   4          6d
concourse-worker-0               1/1       Running   0          6d
concourse-worker-1               1/1       Running   2513       6d
concourse-worker-2               1/1       Running   1          6d
```
```
{"timestamp":"1539007863.317112923","source":"atc","message":"atc.retiring-worker.failed-to-retire-worker","log_level":2,"data":{"error":"pq: new row for relation \"workers\" violates check constraint \"addr_when_running\"","session":"1255719"}}
```
