### ISSUE TITLE
Write docs about how to update Concourse

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1420]
We should write docs that specify how to upgrade to a new version of Concourse for the following deployment methods:
- BOSH
- Bare metal  
- Vagrant
- Docker-compose
- k8

This document should also answer:
- How do I update my workers? 
- When do I have to update my workers?

**Comment by cirocosta** [comment]
Hi @andrewedstrom ,

We updated the docs: https://concourse-ci.org/upgrading-concourse.html

Regarding the package-specific docs, we're updating them in their corresponding repos (helm/charts / pivotal ...).

thanks!
