### ISSUE TITLE
Concourse/lite Vagrant box is outdated

### ISSUE THREAD

**Issue by jzingler** [concourse/concourse#1421]
# Feature Request

## What challenge are you facing?

The current version of the Vagrant Concourse/lite box is v3.2.1 and the current Docker version is v3.3.3.

Can you update the Vagrant box to be in sync with the Docker version?

**Comment by jtarchie** [comment]
tl;dr: It broke on our pipeline and we don't know how to fix it. ☹️ 

@jzingler, we are phasing out the vagrant box in favor of [concourse-deployment](https://github.com/concourse/concourse-deployment). The vagrant box is becoming difficult to maintain with small team. We don't have the time and expertise to keep up with vagrant's changing API.

If you have questions about [concourse-deployment](https://github.com/concourse/concourse-deployment) we are happy to answer them. We are working on documentation to be more explicit.

**Comment by jzingler** [comment]
Thanks for the quick response @jtarchie !
