### ISSUE TITLE
Leaky Containers

### ISSUE THREAD

**Issue by tiredpixel** [concourse/concourse#1424]
I'm having great troubles with container cleanup on Concourse `3.x` on multiple stacks owned by a client of mine. Whilst it appears to work on another infrastructure I control, in this particular setup, containers appear to be leaking, never being cleaned up correctly, and eventually leading to subnet exhaustion.

```
{"timestamp":"1501490272.642470121","source":"guardian","message":"guardian.destroy.destroy.delete-failed","log_level":2,"data":{"error":"runc create: exit status 1: container init still running\n","handle":"d11beaec-d126-4a39-771b-5856bedcd9b2","session":"440.1"}}
{"timestamp":"1501490272.642591000","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"runc create: exit status 1: container init still running\n","handle":"d11beaec-d126-4a39-771b-5856bedcd9b2","session":"3.1.618"}}
```

I've tried this with a variety of Concourse versions, all Docker images run in Kubernetes `1.7`, a cluster set up by Kops, but I've also tried a cluster built with `1.6`. Concourse `3.3.3` is my current attempt, but `3.3.1` and earlier `3.x` versions yield the same. I've tried nodes based on both Debian `8` and Ubuntu `16.04`. I've tried a variety of kernels, currently `4.12.0-041200-generic` (Ubuntu), but also `4.10-0-28-generic` (Ubuntu). `4.4.79-k8s` (Debian Kubernetes), `4.4.78-k8s` (Debian Kubernetes), and `4.4.65-k8s` (Debian Kubernetes) don't work with the Concourse `3.x` `CONCOURSE_BAGGAGECLAIM_DRIVER=detect` default, but do with `CONCOURSE_BAGGAGECLAIM_DRIVER=naive` (but performance appears to be bad). I've also tried on Concourse `2.7.7` with `CONCOURSE_BAGGAGECLAIM_DRIVER=naive` (again, default doesn't work out-the-box on these clusters).

I'm also running clusters elsewhere. Concourse `3.3.3` works perfectly using Docker Swarm on CentOS `7` with an upgraded `4.12` kernel (again, pre-`4.10` doesn't work for me), with Docker `direct-lvm`. Concourse `2.7.4` used to work on AWS ECS with Docker `direct-lvm`, but `3.1.1` (?) didn't, but that's because the kernel was too old out-the-box. Across all stacks, both working and not, Runc `1.0.0-rc3 spec 1.0.0-rc5` is used (`@6a7398c` on at least one stack).

The problem appears to be a Runc failure in calling `delete` on the container, reporting that `init` is still running. Boxes show lots of zombie processes, one per zombie container, reporting `[runc:[2:INIT]] <defunct>`. `fly containers` command shows high numbers of containers, and Concourse db directly `containers` table shows they're stuck in `destroying`. `fly workers` correctly reports the leaked containers (right up to `256`, at which point the subnets get exhausted, as expected). Using `runc` command directly to inspect the leaked containers shows no processes running inside them. Calling `delete` manually fails. Calling `delete` with the new Runc `--force` flag also fails.

Some tickets that I've gone through in detail that I believe might be related are:
https://github.com/concourse/concourse/issues/1297
https://github.com/concourse/concourse/issues/847
https://github.com/concourse/concourse/issues/1149
https://github.com/cloudfoundry/guardian/issues/54
https://github.com/opencontainers/runc/issues/1432

I would be grateful if anyone has any guidance.

Peace, tiredpixel

**Comment by andrewedstrom** [comment]
We are aware of a container leakage issue and plan to include a fix in the next release. Sorry for the inconvenience.

**Comment by tiredpixel** [comment]
@andrewedstrom, great to hear you're planning to include a fix in the next release. :) If you need someone to test a preview Docker image, I'd be happy to see if it resolves the problems. In the meantime, I'll keep restarting workers every few hours. ;)

**Comment by jamesthimont** [comment]
@andrewedstrom do you have an idea of when that will go live?

**Comment by topherbullock** [comment]
@jamesthimont @tiredpixel 

Next minor release; `3.4.0`. We're releasing a patch release soon with some fixes. 
This issue and #1413  will require more of a refactor of our garbage collection and its interaction with `radar` ( the component that runs the resource check scripts on an interval ).

**Comment by tiredpixel** [comment]
@topherbullock, brilliant. Thanks! :) Ah yes, I think I've seen #1413, too.

**Comment by topherbullock** [comment]
Closing as this issue is covered by #1297, which will ship in v3.4.0 shortly (today).

**Comment by jamesthimont** [comment]
@topherbullock that's great

**Comment by tiredpixel** [comment]
@topherbullock, thanks for the update! :)

**Comment by tiredpixel** [comment]
I haven't investigated in detail, but containers still appear to be leaking, and I'm still seeing
```
{"timestamp":"1503055124.134624243","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"runc create: exit status 1: container init still running\n","handle":"046e7aa3-600c-4217-5e34-4be5ce61d199","session":"3.1.21585"}}
```
periodically in the worker logs. Is this message expected? And did the fix ship with 3.4.0 (which I'm now running)?

**Comment by topherbullock** [comment]
@tiredpixel 3.4.0 fixed one part of the issue, but there's another facet of it we're still working on.
Once #1413 is delivered we should be able to get it out in a release.

**Comment by tiredpixel** [comment]
@topherbullock, okay, thanks for the update. I've had to rollback from 3.4.0 to 3.3.4, meanwhile, since I also hit #1501 and found the release less usable than 3.3.x.
