### ISSUE TITLE
Restore "unbound variable" warnings when no auth backends enabled

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#1426]
# Feature Request

## What challenge are you facing?

Since the addition of auth backends and the move from `{{}}` to `(())` for parameter interpolation, `fly set-pipeline` stopped checking for unbound variables. This makes sense when operators are using at least one auth backend, but not when operators aren't using auth backends. Now I can set a pipeline with missing parameters, and I won't find my mistake until I try to run it.

## A Modest Proposal

The `fly set-pipeline` command should check for unbound variables if no auth backends are enabled. Alternatively, `set-pipeline` should add a flag like `--check-unbound` that forces `fly` to check for unbound variables. Or both!

**Comment by jmcarp** [comment]
Thanks @jtarchie! I think we might be talking about different things here:

* Warn/error when the user provides parameters that the pipeline doesn't use. It looks like that's what you're talking about. I actually proposed that behavior in https://github.com/concourse/fly/pull/155, which I'd be happy to reopen and revise if you're open to a `--vars-unused` flag.
* Warn/error when the user *doesn't* provide parameters that are required. This is what `fly set-pipeline` used to do, and still does with `{{}}` interpolation. That's what I'm asking about in this feature request. Any reason `fly` couldn't reach out to the `atc` before checking for missing variables?

**Comment by jtarchie** [comment]
@jmcarp, a lookup is required on to `vault`. We've put that lookup to the last possible evaluation on purpose. It happens on the evaluation of a `task` and minimizes the amount of time that value exists on the `atc` VM. The same behaviour could probably be duplicated for `fly` it is just another vector that could be exposed/vulnerable.

An example I would give the security exposition would be the login of website. If you fail to log in to a website it says "You could not log in", not that the "Password is incorrect" or the "username/email doesn't exist". Exposing information like that helps narrow down attack vectors. Exposing the variables that are available would be similar.

**Comment by jmcarp** [comment]
@jtarchie: I'm not talking about looking up values from secret backends--I'm talking about asking the `atc` which secret backends, if any, are in use. Anyway, here are my questions:

* Would you be interested in adding a `--vars-unused` flag to `fly set-pipeline`? If so, I'd be happy to revive https://github.com/concourse/fly/pull/155.
* Would you be interested in allowing `fly set-pipeline` to check for missing variables *in some way*? Options include:
    * Checking the `atc` for a list of secret backends (not looking up secret values)
    * Allowing users to specify a flag indicating that all parameters must be including in a `vars` file
    * Allowing some form of markup in the pipeline manifest to indicate which secret backend, if any, a secret comes from. For example, secrets that must be provided in a `vars` file could continue to use the `{{}}` interpolation syntax, since that already works as expected.

**Comment by topherbullock** [comment]
This is going down a road of making the credential management integration more complicated from a configuration and cognitive-load-on-pipeline-developers standpoint. I understand the nice-to-have of being able to know immediately when credentials aren't set in the backend, but this would add a lot of additional rules around how things are checked at the `fly` level, and duplicates logic on the server in the client.

The cost might outweigh the value in the end, but I'm open to more discussion as to why this is an essential feature to add to `fly`

**Comment by jmcarp** [comment]
@topherbullock: for what it's worth, `fly set-pipeline` used to check for missing parameters, and still does with the `{{}}` interpolation syntax. Arguably, dropping the feature is a regression, and as a user, I'm finding the experience of running `set-pipeline` to be slightly but noticeably worse. If restoring the feature isn't worth the extra maintenance cost, that's cool, but in general I want useful features to stay around.

I'm also not sure how complicated this would be. For example, could we ask the `atc` to list secret backends on `set-pipeline`, then use the previous behavior of checking for missing variables if no backends are in use? I'm not suggesting `set-pipeline` actually retrieve secrets, just check which backends are enabled. The user wouldn't need to set any flags or configuration (is that what you mean by knobs?) for this to work.

Also, what do you think about my other question? I think the `--vars-unused` flag is useful in `bosh2` and would be useful here as well:
> Would you be interested in adding a `--vars-unused` flag to `fly set-pipeline`? If so, I'd be happy to revive https://github.com/concourse/fly/pull/155.

**Comment by doty-pivotal** [comment]
Could the behavior can be to only error if the value can't be reasonably expected to come from any of the supported secrets backends, thus not even requiring the ATC to list those that are configured?

Right now the syntax for variable interpolation doesn't really call out that the value is meant to be dynamically interpolated.  You can guess, based on the fact that the Vault variables have `/` in them, but is this enough?  The variables could be parsed, thus allowing `fly` to filter out the ones that contain a `/`. Can the variables left be reasonably assumed to be "un-bound"?  

Is there any thought on whether future backends will have this same path syntax in them, or is it reasonable to assume that when there are 2+ supported backends that we will see something like `((backend:/path/to/secret/foo))` that explicitly tells Concourse which backend to go to for each secret?  If this were the case, then "unbound" variables can again be only those that aren't being interpolated via a supported backend.

**Comment by spikymonkey** [comment]
I'd like to vote for this one too. Just migrated a pipeline definition from the old-style `{{...}}` to new-style `((...))` variable interpolation syntax, and was very surprised that fly didn't catch the missing vars when we set the pipeline on a concourse instance that has no backing store for variables configured. For now I'm going to go back to the old syntax, which fly happily still validates. Got to agree with @jmcarp - if the `{{...}}` interpolation style is being deprecated, this does feel like a regression of a useful feature.
