### ISSUE TITLE
Topgun tests should not keep going after failure

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1428]
# Bug Report

Our topgun tests sometimes keep going even when there are failures in the initial spec setup: https://ci.concourse.ci/teams/main/pipelines/main/jobs/topgun/builds/595

Even so, the entire suite runs before the job goes red. This is not ideal because it prevents us from getting quick feedback if the test fails right away.

Let's not use `-keepGoing` and instead just fail right away.

**Comment by jama-pivotal** [comment]
Closing, sorry @andrewedstrom
