### ISSUE TITLE
Display the name of the pipeline in its view

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#143]
When putting multiple pipeline views on the same build board, it's impossible to tell what each pipeline is, because the name of the pipeline doesn't show anywhere.

![screen shot 2015-09-10 at 10 29 16 am](https://cloud.githubusercontent.com/assets/474000/9795692/e6a6ef16-57a6-11e5-8a89-07ce1e87a63d.png)

**Comment by jadekler** [comment]
@chendrix I think that space is reserved for groups?

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/295 as there's more discussion there - thanks!
