### ISSUE TITLE
Provide a way to watch changes in release notes

### ISSUE THREAD

**Issue by avanier** [concourse/concourse#1432]
# Feature Request

Concourse is awesome, and I use Concourse to check for new Concourse releases with the `github-release` resource. Whenever a new release comes out, there are no release notes to read, which makes for really sad pandas _(aka sysadmins)_.

## A Modest Proposal

Either, make the release notes available as a file in GitHub, as a RSS stream, or something we can watch with a pipeline so our impatient selves don't throw an envy and expectation fit whenever you release shiny new things.

**Comment by jtarchie** [comment]
Why 😢 🐼 ?

The release notes are offered as a link through the releases page -- https://github.com/concourse/concourse/releases. We do this so there is one source of truth.

What problem are trying to solve here? You are able to get the github release and the notes from the site.

**Comment by andrewedstrom** [comment]
@avanier The release notes are actually stored as files in GitHub, at https://github.com/concourse/concourse/tree/master/docs/lit/release-notes. Maybe you could use a git-resource to watch that directory for changes?

**Comment by vito** [comment]
Either the release notes will be broken by linking to unpublished GitHub releases, or the GitHub releases will be broken by linking to unpushed release notes.

In addition, if publishing the GitHub releases fails, I don't want us to push the release notes.

I think the current ordering is the lesser of the two evils.
