### ISSUE TITLE
Feature request: pipeline as oembed component 

### ISSUE THREAD

**Issue by airtonix** [concourse/concourse#1433]
# Feature Request

expose public pipelines as something we can embed in external webpages.

## What challenge are you facing?

Display pipeline status in services like [klipfolio](https://www.klipfolio.com/)

## A Modest Proposal

Ideas about this:

- oembed: `http://concourse.local/teams/web-projects/pipelines/a-website/oembed` returns something compliant with [oembed spec](http://oembed.com/)
- a public java-script file that is used like this `<script src="http://concourse.local/pipeline-embed.js?target=main&team-name=web-projects&pipeline=a-website&element-id=my-element-id"></script>` 

either way, it should render the fancy pipeline we see when on the dashboard.

**Comment by jtarchie** [comment]
@airtonix, you are able to do with some of dashboard servers using `iframe`. I've seen teams do this datadog dashboard for example.

The oembed spec is more sharing content via social media platforms, which are usually static content -- videos, pics, text, etc. It doesn't play well with dynamic content that should not be cached.

**Comment by airtonix** [comment]
@jtarchie wouldn't that also include all the ui cruft? navigation bar, offcanvas menu, legend.

Perhaps if the ELM client could detect a querystring `?graphOnly=true` that caused only the graph to render?

**Comment by SHyx0rmZ** [comment]
To me, it sounds like #1478 could also be of interest for this use case. In theory, we could also expose the SVG elements under their own route, in which case you could just include those and refresh periodically.
