### ISSUE TITLE
Resources Provided With Concourse, Email Resource

### ISSUE THREAD

**Issue by alexander-matsievsky** [concourse/concourse#1434]
## What challenge are you facing?

There is a set of [Resources Provided With Concourse](https://concourse.ci/single-page.html#section_resources-provided-with-concourse), which includes essential parts for Concourse usage out-of-the-box, which is very convenient. Meanwhile, the ability to send email notifications of Concourse build results is provided by [Unsupported Community Resources](https://concourse.ci/single-page.html#section_community-resources), of which https://github.com/pivotal-cf/email-resource seems to be most feature-complete and mature.

Nevertheless, there are some missing features, which are repeatedly mentioned and addressed in https://github.com/pivotal-cf/email-resource/pulls. Unfortunately, there is no response to them since 2016.

## A Modest Proposal

It would be great to have an official out-of-the-box Concourse build email notification resource. The one way to achieve it is to use https://github.com/pivotal-cf/email-resource as a base solution with incorporated https://github.com/pivotal-cf/email-resource/pull/8.

**Comment by alexander-matsievsky** [comment]
If I understand the situation correctly, the resource at question https://github.com/pivotal-cf/email-resource is semi-official due to being developed by https://github.com/pivotal-cf/. That's why I think it's a good idea to promote it to a fully official status.

I do realize that the master repo may not be the most appropriate place for this issue. Unfortunately, it seems that https://github.com/pivotal-cf/email-resource repo does not get much attention.

**Comment by jtarchie** [comment]
@alexander-matsievsky, why does an out of box solution need to provided? Using `resource_types` allows you to extend what resources are available within your pipeline.

The resource above being in pivotal-cf has no status of being semi-official. People in the community maintain this. If it is currently not maintained, maybe some community member could take it over. :wink:

**Comment by alexander-matsievsky** [comment]
@jtarchie By "out-of-the-box" i meant the email resource reviewed and listed under [Resources Provided With Concourse](https://concourse.ci/single-page.html#section_resources-provided-with-concourse), giving it credibility. In my opinion, the email notifications are must have component for a CI solution.

https://github.com/pivotal-cf/email-resource is not actively maintained
![image](https://user-images.githubusercontent.com/3784691/28876543-38d273e2-77a2-11e7-8bf8-370f16766369.png)
and does not respond to https://github.com/pivotal-cf/email-resource/pulls
![image](https://user-images.githubusercontent.com/3784691/28876584-52d0813a-77a2-11e7-8349-4dd03118bfd1.png)

It's true that one can always create a separate repo incorporating the demanded features and PRs. The downside is that this will further split the ecosystem for the most basic necessities.

**Comment by jtarchie** [comment]
Sorry, I understood what "out of the box" meant, I was asking for clarification of why you feel it needs to be.

When taking on resources we have to worry about a few things:
* Does it work within an air gapped environment?
* Does it provide functionality someone cannot easily replicate?
* Does it provide a versioning schema that makes sense for concourse?
* Do we feel we have the expertise to actively maintain and support it?

There may be some exceptions to these questions above, sure.

Then question I would follow up for you would be, what abstraction does this provide that you feel it is necessary for concourse to pull it in? Aren't utilities like `sendmail` on docker image just as easily consumable.

**Comment by alexander-matsievsky** [comment]
@jtarchie The goal (which 2 out of 3 PR above address) is to have access for [concourse build metadata](https://concourse.ci/single-page.html#section_resource-metadata), which is not be accessible outside of the resource.

The use case -- to compose contextualized success/failure build notification subject/body.

**Comment by chendrix** [comment]
Hi there,

We are unlikely to write our own email resource and support it as part of the Concourse core. Resources are an extensible part of the architecture for this very reason, so that community members can create their own resources, fork and maintain them as appropriate.

I hear your pain that the `pivotal-cf` email resource seems to be unsupported. Maybe you can fork it and grab a group of people to maintain your own fork.
