### ISSUE TITLE
monitoring job fails intermittently with 500 "does not exist: Handle"

### ISSUE THREAD

**Issue by seanwolfecsaa** [concourse/concourse#1436]
# Bug Report

I've created a job which launches a container running some Ruby code that checks an Amazon S3 bucket every 6 seconds, to see if a particular file exists. If the file appears, the job triggers a set of cucumber browser tests, publishes results to a slack channel, then resumes monitoring S3.

The CI job is failing intermittently after 30+ minutes with the following cryptic error message:

```Backend error: Exit status: 500, message: {"Type":"","Message":"does not exist","Handle":""}```

Any suggestions about how I can get more context on what's causing the error?

Concourse version 3.3.4 .

**Comment by andrewedstrom** [comment]
You mentioned that the job fails after 30+ minutes. How long does this job usually take?

Could be related to #1413.

**Comment by seanwolfecsaa** [comment]
The job itself stays on permanently as it monitors the S3 bucket for the appearance of the trigger file.

By the way, is there a specific Concourse resource for this use case?

```If a file in an S3 bucket either a) appears or b) has been modified, then trigger a downstream job```

**Comment by andrewedstrom** [comment]
@seanwolfecsaa Yes there is already a resource for that use case. What you're looking for is the [`s3 resource`](https://github.com/concourse/s3-resource/). 

If you still see this issue after switching to the `s3-resource`, will you please post another comment here letting us know?

**Comment by seanwolfecsaa** [comment]
I read up on that but it didn't seem to be able to track files in this way. However everybody seems to agree that it's the right resource to use so I'm going to read up more. Thanks for the pointer ~~

**Comment by andrewedstrom** [comment]
@seanwolfecsaa It does exactly what you described above:

> If a file in an S3 bucket either a) appears or b) has been modified, then trigger a downstream job

If you want some examples of it in use, you may find our own pipelines helpful: https://github.com/concourse/pipelines/tree/master/ci.concourse.ci

**Comment by seanwolfecsaa** [comment]
Okay great, I was looking for some examples. Thanks again ~~
