### ISSUE TITLE
Upgrade Concourse Lite to version 3.3

### ISSUE THREAD

**Issue by zgagnon** [concourse/concourse#1437]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request

## What challenge are you facing?

I need to run a Concourse instance in a mac-only environment without the ability to access cloud resources. So far, Concourse Lite is the only way to do this. The latest version of Concourse Lite (3.2.1) has an issue regarding `unknown handle` in resources. Right now, the only way to address this is to destroy the vagrant box.

## A Modest Proposal

Probably the most expedient way to address this would be to release a version 3.3 Concourse Lite box?

**Comment by jtarchie** [comment]
Please see issue #1421.
