### ISSUE TITLE
`validate-pipeline` doesn't work on pipelines with `((parameter))` templating

### ISSUE THREAD

**Issue by astrieanna** [concourse/concourse#1439]
# Feature Request

## What challenge are you facing?

Our pipelines are heavily templated to maintain support for multiple versions in productions. We've (very happily) taken advantage of the new `((parameters))` that allow complex (arrays, nested structures) as values.

Previously, we used `validate-pipeline` as a way to check our yaml syntax before setting the pipeline. We like to do as much testing as possible before possibly breaking our team's ci. Now, `validate-pipeline` doesn't work for us because it doesn't handle template variables.

## A Modest Proposal

We'd be happy to go back to being able to use `validate-pipeline`. Since we do want to check as much as possible locally, being able to pass `--load-vars-from` to `validate-pipeline` would work well for us because it could template in the actual values and ensure they are the right type.

**Comment by chendrix** [comment]
@jmcarp you wrote the `validate-pipeline` command, would you be willing to writing a PR to fix this?

**Comment by jtarchie** [comment]
This behaviour also affects the [`fmt` command](https://github.com/concourse/fly/blob/06b4e950c2f12120f995761b321e6bc450b2538d/commands/fmt.go#L28) as it uses `{{}}` syntax.

**Comment by jmcarp** [comment]
I'd be happy to take a look at this. What's the ask exactly? As of 3.3.4, `fly validate-pipeline` seems to work fine on pipelines with `(())` interpolation. Is the idea that `validate-pipeline` should accept `--load-vars-from` and validate the (partially) interpolated template? That would be a new feature, but it sounds useful.

Anyway, let me know what you all have in mind, and I'll work up a patch later in the week.

**Comment by jtarchie** [comment]
@jmcarp thanks for the PR.

We might need to validate (eyo!) with @astrieanna. Did you want errors if there are missing/empty `((parameters))` not specified with `--load-vars`?

**Comment by astrieanna** [comment]
We've found that it works fine until the `(())` interpolation involves non-string values -- and then the types don't match and the pipeline doesn't validate even if correct. Having validate put the variables in and check the types for us seems like the only way for validate to still be useful when so much of our pipeline is in variables.

We have a heavily templated pipeline. When we make mistakes in our vars files when using `set-pipeline` we get line numbers in the errors that are for the fully interpolated file, which we don't have access to (because it only exists when set-pipeline is running). It's painful to try to debug with only set-pipeline and so many variables.
