### ISSUE TITLE
Metrics emitted by concourse (blackbox) should have useful, discoverable documentation

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [concourse/concourse#144]
I'd like an easy way to find, for the version of concourse I have deployed, documentation and guidance about the metrics emitted by concourse.  I would like to know:

- the names of all the metrics
- the meanings of all the metrics
- what are the best ways to slice a given metric, e.g. `build.finished` is most useful when broken down by the `job` tag.  The Grafana UI does this for free, and in datadog one has to ask for one graph per job.
- a high level idea of what to look for (what does typical healthy behaviour look like for a given metric, what are some examples of bad behaviour, etc.)

The `build.finished` stuff is awesome btw, pretty great to finally have that!

**Comment by Amit-PivotalLabs** [comment]
Where are the docs?

**Comment by Amit-PivotalLabs** [comment]
Also, concourse-bot says "feel free to reopen", but I don't see the option to reopen.  Is this a GH repo setting to allow reopens?

**Comment by vito** [comment]
docs haven't shipped yet; will be out with the next release (0.63)

do you not have a "reopen and comment" button next to the normal one? i don't see a setting anywhere to reenable it

**Comment by Amit-PivotalLabs** [comment]
Think I read somewhere that if you're not a contributor, you can't reopen
if a contributor closes.

**Comment by vito** [comment]
Yep looks like that's the case. Bummer. I guess it's to deal with trolls.
I'll update the text and think about if a bit more wrt tracksuit.
