### ISSUE TITLE
Large amount of output prevents from aborting the build

### ISSUE THREAD

**Issue by jhvhs** [concourse/concourse#1450]
## A Modest Proposal

When providing output for a build, present the user with the last 1Mb of output. If there is any output before that, it could be either represented by a button, or auto-loaded on scrolling.

# Bug Report

When a job has excessive output, it takes too much time to load, reducing the responsiveness of even freezing the browser. In our case, the claim lock spent several days trying to acquire a lock from a pool that was renamed.

Stopping the build via the UI did not work, we ended up cancelling the build via the CLI.

The following can also be handy:

* Concourse version: 3.3.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome/MacOS latest
* Did this used to work? n/a

**Comment by jtarchie** [comment]
This is a bug report and a feature request. Please separate them out into two issues or narrow this issue to what you want. We'd rather not have bugs with solutions as there may be other ways to resolve this issue.

**Comment by jama-pivotal** [comment]
Closing in favour of the build page improvements and suggestions in #1543 and also the feature request for "tailing" logs in #875
