### ISSUE TITLE
in Concourse CI, can garden container run as ```--network="host" ``` instead of bridge ?

### ISSUE THREAD

**Issue by panpan0000** [concourse/concourse#1455]
Hi there!

# Feature Request

## run Container in host network mode

to run CI test with physical devices , one of my worker should connect the physical devices via a private network (because our product(RackHD) will PXE boot those physical machines via the private network).
denote the worker machine talks with the physical devices via ```eth1``` of the worker machine.

But the garden container which spawn from that worker, they are run as bridge mode.
so our product can't talk with the physical devices, without touch the ```eth1``` of the worker.

like docker-engine, it provides capability like ```--network="host" ``` to run the container on host's network stack. so that we can see the host ```eth1``` inside the container.

I've tried ```"-garden-allow-host-access”```, but it's not what I thought , I can only saw only NIC ```wm8sfdsn0sjr-1 ``` inside container.

I am not familiar with Garden/runC,  is it possible to run the container in ```host network mode``` like docker-engine , to fulfill our need ?

* Concourse version:   3.3.4
* Deployment type (BOSH/Docker/binary):   worker uses binary , the web is not a matter here.
* Infrastructure/IaaS:   the worker runs in a bare metal physical machine. the physical machine connects internet/concourse-web  via eth0, and connects to some device under test via eth1
* Browser (if applicable):   chrome
* Did this used to work?  No

-----------

relevant post from other repos:

https://github.com/opencontainers/runc/issues/1552
https://github.com/cloudfoundry/garden-runc-release/issues/43

**Comment by topherbullock** [comment]
This would be something supported by Garden, and Concourse would just pass flags to Garden from the binaries / in BOSH when running the worker.

Closing this off, since you've created the relevant issue in Garden RunC

**Comment by rosenhouse** [comment]
@panpan0000 As a hackish, insecure workaround, you could look into running a Concourse worker with the [houdini backend](https://github.com/vito/houdini).  Houdini implements the Garden API but doesn't actually containerize anything.  As a result, the workload can directly access everything on the host.

You should only do this if you understand the security implications of it, and trust all the users and tasks that your Concourse might be running.

**Comment by ezraroi** [comment]
so this is now supported? when i am trying to run the concourse worker in docker and using --net=host things not really working... it is failing to connect github for example.... when i use the bridge host everything is working fine
