### ISSUE TITLE
Improve error messages when workers in 'landing', 'landed' or 'stalled' state.

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#1458]
# Challenge

There's been a lot of reports of error messages and issues which result from workers being`stalled` or `landed`:
- `file not found` errors, as reported in https://github.com/concourse/concourse/issues/1251
- `unknown handle` errors, as reported in https://github.com/concourse/concourse/issues/1255
- `fly hijack` shows containers for stalled / landed workers, and stalls (fails silently) when one is selected

# A Modest Proposal

Improve error messages when the errors surface as the worker is stalling ( ideally before it is marked as "stalled" in the db ) and communication isn't possible, instead of surfacing low-level errors from baggageclaim and garden.

# Next steps
Better handling of worker lifecylce to make sure these errors don't occur (could be separate issues after the error messages are cleared up and more descriptive): 
 - don't show containers on landed or stalled workers in `fly hijack`
 - don't try and use containers or volumes on landed or stalled workers

**Comment by topherbullock** [comment]
The next stage of this is to automatically rebalance across other available workers #755 ; once the ATC "knows" that the worker has been put into the stalled state or is currently stalling.

There are some cases, such as not having an available tagged worker, or one supporting a resource type where there will still be an issue, but for tasks and resource checks with a supporting worker, this should just be a retry.

**Comment by gowrisankar22** [comment]
@topherbullock when can we expect a fix for file not found issue from concourse ?

**Comment by mbjelac** [comment]
Thanks @gowrisankar22 - your comment reminded me to review the reports concerning the file-not-found bug(s). I took the time to reconstruct the bug on my environment (I run Concourse in Docker) and I reported the specific case in #1796. During reconstruction I stumbled upon a similar issue (also concerning Docker): #1797.

I also want to ask @topherbullock is it common practice to close user-reported issues and replace them with technical issues? IMHO this makes it harder for users to track what's happening to their problem, especially if a user issue is replaced with several tech issues, such as the case here.

**Comment by vito** [comment]
@mbjelac It's fairly common to close multiple issues that are all fixed by one concerted effort, as is the case here. It's just a way of consolidating and managing the progress from "issue(s) reported -> problem space understood -> fix (possibly a feature) proposed and implemented".

**Comment by mbjelac** [comment]
@vito Understood, thanks.

**Comment by xtremerui** [comment]
closing stall issue. If needed, we can create an issue for `fly hijack` bad containers.
