### ISSUE TITLE
Missing npm module files in docker container run by Concourse. The files exist when the container is run through docker locally.

### ISSUE THREAD

**Issue by Shugyousha** [concourse/concourse#1464]
# Bug Report

We build a container image and use npm and yarn to install our packages
(about 1700 of them). The Dockerfile looks like this.

```
FROM nodesource/jessie
MAINTAINER someone

ENV DISPLAY :99.0

# Add jessie-backports Debian repository
RUN echo "deb http://http.debian.net/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list

# Install dependencies to run Electron
RUN apt-get -qqy update \
  && apt-get -qqy install \
    xvfb \
    libnotify4 \
    libgconf2-4 \
    libnss3 \
    libxtst-dev \
    libc6 \
    libstdc++6 \
    libgcc1 \
    libgtk2.0-0 \
    libasound2 \
    libxrender1 \
    libxss1 \
  && apt-get -qqy install -t jessie-backports --no-install-recommends \
    openjdk-8-jre-headless \
    ca-certificates-java \
  && apt-get -qyy autoremove \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get -qyy clean

# Install yarn
RUN npm install -g yarn@0.17.10

# Install Node.js dependencies
COPY package.json /usr/src/app
COPY yarn.lock /usr/src/app
ARG NPM_AUTH_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > /root/.npmrc \
  && NODE_ENV=development yarn install \
  && rm /root/.npmrc
```

When I run an npm command in the running container using docker
(17.06.0-ce) locally the command succeeds. When I run the same command
in a Concourse task that uses the same container image, npm complains
about a missing module.

It took quite some time to figure it out but it seems like there are files
missing in the container when started for a Concourse task. Those files
are there when looking into the same directory of the container with the
container started locally. The following screenshot illustrates the issue
(note that the image digest of both images are identical).

![missingfiles](https://user-images.githubusercontent.com/500068/29208415-360561b2-7e8a-11e7-838b-e24ec2a74f70.png)

I saved the output of both "find" commands and compared it below.

[silvan@workarch ~]$ wc -l filesinConcoursecontainer.txt filesinlocalcontainer.txt
8235 filesinConcoursecontainer.txt
9566 filesinlocalcontainer.txt

after sorting the two files I get the following results.

[silvan@workarch ~]$ comm -12 filesinConcoursecontainer.txt filesinlocalcontainer.txt | wc -l
8235
[silvan@workarch ~]$ comm -23 filesinConcoursecontainer.list filesinlocalcontainer.txt | wc -l
0
[silvan@workarch ~]$ comm -13 filesinConcoursecontainer.txt filesinlocalcontainer.txt | wc -l
1331

You can see that there are 1331 files/directories missing in the container
started by Concourse. Find the files containing the file lists below.

[filesinConcoursecontainer.txt](https://github.com/concourse/concourse/files/1217469/filesinConcoursecontainer.txt)
[filesinlocalcontainer.txt](https://github.com/concourse/concourse/files/1217470/filesinlocalcontainer.txt)

Do you have an idea why that could be?

A similar issue is this  one https://github.com/concourse/concourse/issues/1286 (please note that I added a description of my issue there as well).

* Concourse version:

3.3.2

* Deployment type (BOSH/Docker/binary):

binary

* Infrastructure/IaaS:

AWS

* Did this use to work?

I did not have issues like this before when running containers in Concourse or anywhere else.

**Comment by jtarchie** [comment]
Are you sure it is the same version of the docker image being used on concourse and docker CLI? You've done `get` on the docker image, how are you providing it to the `task`?

**Comment by Shugyousha** [comment]
On Fri, Aug 11, 2017 at 11:21:18AM -0700, JT Archie wrote:
> Are you sure it is the same version of the docker image being used
on concourse and docker CLI? You've done `get` on the docker image,
how are you providing it to the `task`?

Yes, I am `get`ing the image and then using the "image:" keyword to set
the image to use for the task. I am also not using another image
containing NPM in this pipeline so there is no risk of me confusing
images.

Unfortunately I will be on holidays next week and will only have very
limited access to internet. When I am back I can try to gather more
info. At the moment we are working around the problem by not installing
the NPM modules & yarn in the Dockerfile but only afterwards in the task
itself which seems to work.
