### ISSUE TITLE
Add "last checked" on the resource screen

### ISSUE THREAD

**Issue by mkuratczyk** [concourse/concourse#1465]
Hi there!

# Feature Request

## What challenge are you facing?

When looking at a resource, I don't know when Concourse performed the last check. It would be particularly useful when there is an error, especially when developing a new resource. For example, I push an image with my custom resource and I get this:
<img width="1717" alt="screen shot 2017-08-11 at 11 43 23" src="https://user-images.githubusercontent.com/9566114/29209235-ca927fba-7e8d-11e7-8015-cd585d7891b2.png">
then I make some updates, look at this screen again and still see this error but it's not clear whether Concourse already performed a check again and the issue is still there or is it still the previous error. I need to do `fly check-resource` to be sure.

While we are at it, I'm not sure it's possible but if there was a "next check in ..." counter it could be useful as well. If it's not deterministic enough it could just show the value of `check_every` configured for this resource.

**Comment by xtremerui** [comment]
The UI will looks like
<img width="1404" alt="screen shot 2017-12-15 at 3 43 44 pm" src="https://user-images.githubusercontent.com/1585949/34059846-d8f72784-e1ae-11e7-843b-626176bd9f32.png">

Any thoughts?

**Comment by mkuratczyk** [comment]
Great! The only thing I'd consider adding is check interval for this resource or the estimated time of the next check.

**Comment by jama-pivotal** [comment]
Accepting  @mkuratczyk I've captured your suggestion into a new story that we can pick up later on https://github.com/concourse/concourse/issues/1976
