### ISSUE TITLE
Concourse 3.3.4  worker permission denied on Oracle Linux 7.3

### ISSUE THREAD

**Issue by DaxterM** [concourse/concourse#1467]
# Concourse 3.3.4  worker permission denied on Oracle Linux 7.3
* Concourse version: 3.3.4
* Deployment type (BOSH/Docker/binary): Binary

Using a fresh Oracle Linux VM and single node web and worker install the worker is unable to start containers.  What's interesting is that if I replace the concourse binary with 2.7.7, delete and recreate the ATC DB, and fire it back up I no longer hit this issue. 

Whats even more interesting is if I now revert back to the 3.3.4 binary, and again recreate the DB's the problem is gone in 3.3.4. 

I've confirmed this with an AMI on AWS as well as a local virtualbox instance using http://yum.oracle.com/boxes . It looks like the 2.7.7 is fixing whatever was causing that issue in 3.3.4.

 Full log here https://gist.github.com/DaxterM/8e1d674dd6e87331a0c8866191be9855 

Example entry
`{"timestamp":"1502736556.658256292","source":"guardian","message":"guardian.create.containerizer-create.runtime-create-failed","log_level":2,"data":{"error":"runc create: exit status 1: container_linux.go:264: starting container process caused \"process_linux.go:339: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"tmpfs\\\\\\\" to rootfs \\\\\\\"/var/lib/concourse/volumes/live/4efe9ba5-72bd-460f-6b20-aee03302fd20/volume\\\\\\\" at \\\\\\\"/dev/shm\\\\\\\" caused \\\\\\\"mkdir /var/lib/concourse/volumes/live/4efe9ba5-72bd-460f-6b20-aee03302fd20/volume/dev/shm: permission denied\\\\\\\"\\\"\"\n","handle":"1ba7dc1a-7241-4929-6585-f6aca44cc633","session":"23.2"}}`

Install guide https://github.com/DaxterM/Manual-Concourse/blob/master/redhat.md

**Comment by jtarchie** [comment]
I don't think 2.2.7 is doing anything here.

The error you are showing might be related to a custom resource type. In v3.x, resources no longer run in privileged mode, so that needs to be explicitly defined now.

**Comment by DaxterM** [comment]
Ok thanks @jtarchie . It is strange that after running 2.2.7 that 3.3.4 works. Are you suggesting there is some extra step besides what is in https://github.com/DaxterM/Manual-Concourse/blob/master/redhat.md is required to make 3.3.4 work related to resources in privileged mode?

**Comment by jtarchie** [comment]
Yes. Your pipelines need to be updated.

**Comment by DaxterM** [comment]
@jtarchie Would you be able to provide a sample pipeline that should work with 3.3.4 out of the box? I will try a fresh install to see if it mitigates this issue.  I'm not sure that the pipeline is the issue here, instead I think it's an issue related or oracle linux/redhat specifically.  This is because I did not have the same issue using the same pipeline and fresh install on ubuntu. If you would be interesting in checking it out I'd be happy to replicate the issue and give you access over screen share.

**Comment by topherbullock** [comment]
@DaxterM There's a number of things that could be the issue:

As of [v3.1.0](http://concourse.ci/downloads.html#v310) the default storage driver for volumes uses `overlay` instead of `btrfs`. Oracle Linux 7.3 might not support that fully. There is a flag to adjust this on `concourse worker`: 
`-baggageclaim-driver=[detect|naive|btrfs|overlay]`
You could try setting this to `btrfs` and see if the problem with the latest version persists.

The working directory for the worker needs to be re-formatted when upgrading to versions after  [v3.1.0](http://concourse.ci/downloads.html#v310) in order to migrate to `overlay`. If you're doing all of this on a single VM and you haven't removed the `/var/lib/concourse/` directory, this might be an issue of needing to fully recreate the working directory and restarting the worker.

If you have any custom resources in your pipeline, as @jtarchie pointed out, you need to change their config; see the release notes for [v3.1.0](http://concourse.ci/downloads.html#v310)

**Comment by DaxterM** [comment]
@topherbullock On a fresh VM running 3.3.4 with `--baggageclaim-driver=brtfs` set on the worker I am no longer seeing the issue. It looks like `overlay` is not supported on this machine.  Here is what I tested this on 
```
[vagrant@localhost ~]$ cat /etc/oracle-release 
Oracle Linux Server release 7.3
[vagrant@localhost ~]$ uname -r
4.1.12-61.1.28.el7uek.x86_64
[vagrant@localhost ~]$ 
```
 According to https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#prerequisites for overlay RHEL requires xfs type filesystem for this kernal with f_type set to 1. On the machine I was using it was set to 0.  Reference:  https://linuxer.pro/2017/03/what-is-d_type-and-why-docker-overlayfs-need-it/ 

<pre>
[vagrant@localhost ~]$ xfs_info /dev/sda1
meta-data=/dev/sda1              isize=256    agcount=4, agsize=32000 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=0        finobt=0 spinodes=0
data     =                       bsize=4096   blocks=128000, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 <b>ftype=0</b>
log      =internal               bsize=4096   blocks=853, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
</pre>

I think I will leave it to btrfs. thanks!
