### ISSUE TITLE
Upgrade to 3.x failing with PG error

### ISSUE THREAD

**Issue by wduncanfraser** [concourse/concourse#1468]
Running Concourse with standalone binaries on CentOS 7 servers with Postgres 9.6.

Was attempting to upgrade from 2.7.3 to 3.3.4. Workers upgraded fine, and then when I tried to upgrade the web/master node, It fails on start up with the error:

```
failed to migrate database: pq: there is no unique constraint matching given keys for referenced table "workers"
```

I attempted to upgrade to 2.7.7 first and that went through without issue. I then tried to update to 3.0.1 and got the same error.

I also attempted to retire all workers, validated none were reporting in ```fly workers``` and that the workers table was empty, but attempting to upgrade again resulted in the same error.

**Comment by topherbullock** [comment]
Sounds like this is a specific issue caused by your backup scripts. We should document the process for that so that others don't get stuck when upgrading.

Made and issue for that now #1500
