### ISSUE TITLE
Filter task outputs. eg. for redaction

### ISSUE THREAD

**Issue by dgodd** [concourse/concourse#1469]
# Feature Request

Allow output from tasks to be run through a filter. We would like to be able to filter the output of tasks and remove sensitive information.

## What challenge are you facing?

We have many pipelines which we make public which need sensitive information (eg passwords/keys). Currently we use a bash filter to redact string which is a ENV variables (except for a whitelist), We would like to bake this into the system.

## A Modest Proposal

We find it very handy to use ENV variables for this, since they are what we personally always use to pass the information into our tasks. When doing so, a whitelist is necessary to enable better debugging. We prefer whitelists for this to blacklists to make it easier to not make mistakes.

**Comment by jtarchie** [comment]
@dgodd, can you give an example:

* How you accomplish this? Is it just search-replace some copy?
* What exactly exists in the whitelist, the actual copy to not redact?

**Comment by vito** [comment]
![image](https://user-images.githubusercontent.com/1880/29319301-93f626e8-81a1-11e7-9ea7-000d76ba8f30.png)

This is a feature present on other CI systems but I've found it does more harm than good. It gets you into a mindset of not caring about what your scripts print out, and then the house of cards comes crashing down once those values get printed in a different format (e.g. JSON marshalled). It also is prone to giving away things that are credentials based on the context around them (e.g. censoring "ci" turns "special" into "spe**al" and now everyone knows that's a username).

**Comment by dgodd** [comment]
@vito @jtarchie  I would be happy with a way to add a filter to all tasks for a pipeline. I could then supply the filter and all output would go through it. Then I would be responsible for making it do what I want.

For our current implementation we have something similar to 

params:
  FRED: 1234
  JANE: 1
WHITELIST: [ jane ]

output:
```
hi 1234 bye 1
```

after going through the filter, it looks like

```
hi [redacted FRED] bye 1
```

**Comment by vito** [comment]
Closing this per https://github.com/concourse/concourse/issues/1469#issuecomment-322477192 - sorry!
