### ISSUE TITLE
Comments on builds

### ISSUE THREAD

**Issue by dgodd** [concourse/concourse#1470]
# Feature Request

I would like to be able to add comments to builds. Specifically I would like to be able to inform myself and my team why a build is red, and preferably to be able to distinguish between documented reds and any new red builds. This will minimize duplicate efforts to investigate red builds, particularly any that take a very long time to run.

It would be nice to also be able to easily associate investigation of red builds with individuals.

**Comment by jtarchie** [comment]
We don't have any concept of an _individual_ right now. Every user is the exact same, just on a different team.

Where do you see this comment being displayed?
Would it be tied to a specific build # or just job?

**Comment by dgodd** [comment]
I'm happy with the individual being free form text, I'm even happy if it was just the larger comment and I included my name manually in the text. I would expect to be able to see this comment on the pipeline views  overlaying the red build (possibly on hover). I would also like to see it on a summary, like concourse-summary or the one which I believe the concourse team is discussing making themselves.

**Comment by utako** [comment]
Also: https://github.com/concourse/concourse/issues/476

**Comment by dsabeti** [comment]
Also: https://github.com/concourse/concourse/issues/273

**Comment by xtremerui** [comment]
implemented. Now you can find the button to add build comment on the top right, right beside rerun button
