### ISSUE TITLE
Interpollation not working as expected

### ISSUE THREAD

**Issue by avirkar** [concourse/concourse#1471]
Do you have an sample of how interpolation
[Interpolation Issue.zip](https://github.com/concourse/concourse/files/1225142/Interpolation.Issue.zip)

 can be achieved, my var file has key value pairs like
cf-api-app: api-
cf-dispatcher-app: dispatcher-
cf-space: test

In my pipeline I want to pass param to my task which should look something like

PCF_API_APP_NAME: ((cf-api-app))-((cf-space))
PCF_DISPATCHER_APP_NAME: ((cf-dispatcher-app))-((cf-space))

So my task can get a param based on environment, and it would look something like
PCF_API_APP_NAME: api-test
PCF_DISPATCHER_APP_NAME: dispatcher-test

But I guess somehow, it does not take the combination as expected and is unable to evaluate it.
I even tried using anchor in my config.yml but still it does not work.

aliases: &environ test

cf-api-app: api-*environ (fails)
cf-dispatcher-app: dispatcher-*environ (fails)
cf-space: *environ (works)

Check the attached files to explain exactly what I want to achieve.

**Comment by jtarchie** [comment]
I am not able to reproduce:

Using the above, I created a test pipeline `test.yml` with a `vars.yml`.

> test.yml
```yaml
jobs:
- name: ((cf-api-app))-((cf-space))
- name: ((cf-dispatcher-app))-((cf-space))
```

> vars.yml
```
cf-api-app: api
cf-dispatcher-app: dispatcher
cf-space: test
```

With the `set-pipeline`, I was able to verify it worked:

```
$ fly -t tf sp -p asdf -c test.yml -l vars.yml
jobs:
  job api-test has been added:
    name: api-test

  job dispatcher-test has been added:
    name: dispatcher-test
```

**Comment by jtarchie** [comment]
@avirkar, what version of `fly` and concourse are you using?

**Comment by avirkar** [comment]
I think that was the problem i was using version 2.6 and the 3.2.1 supports it.
