### ISSUE TITLE
Volumes being reaped too early

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#1475]
* Concourse version: 3.0.1+
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable):
* Did this used to work?: Yes, prior to 3.0.0

We have only two workers but frequently see a resource being downloaded more than two times even when the version of the resource hasn't changed. I've seen it for a variety of resource types, including docker-image and pivnet-resource, which are typically larger files.

I've seen it with multiple successive builds, and in a successful build after a failing build; it doesn't seem to matter what the state of the build was.

Here's an example (newest build first):

<img width="974" alt="screen shot 2017-08-15 at 8 46 14 am" src="https://user-images.githubusercontent.com/79357/29323623-553b5910-8196-11e7-894f-4cf985355c79.png">
<img width="981" alt="screen shot 2017-08-15 at 8 46 07 am" src="https://user-images.githubusercontent.com/79357/29323625-5550e906-8196-11e7-81ab-98deba916ad0.png">
<img width="976" alt="screen shot 2017-08-15 at 8 45 52 am" src="https://user-images.githubusercontent.com/79357/29323628-555e1d24-8196-11e7-8e23-55716be75c15.png">
<img width="976" alt="screen shot 2017-08-15 at 8 45 16 am" src="https://user-images.githubusercontent.com/79357/29323624-55509fbe-8196-11e7-94e6-8f8953ebfa6b.png">
<img width="976" alt="screen shot 2017-08-15 at 8 45 08 am" src="https://user-images.githubusercontent.com/79357/29323632-55dd6502-8196-11e7-9436-331107ace5b6.png">
<img width="973" alt="screen shot 2017-08-15 at 8 45 01 am" src="https://user-images.githubusercontent.com/79357/29323626-5553ebba-8196-11e7-8a9a-97284af464ba.png">
<img width="972" alt="screen shot 2017-08-15 at 8 44 53 am" src="https://user-images.githubusercontent.com/79357/29323627-555663d6-8196-11e7-88af-e8e0f0260edc.png">
<img width="973" alt="screen shot 2017-08-15 at 8 44 45 am" src="https://user-images.githubusercontent.com/79357/29323629-556d31ba-8196-11e7-9181-64e9a71f1c64.png">
<img width="973" alt="screen shot 2017-08-15 at 8 44 36 am" src="https://user-images.githubusercontent.com/79357/29323630-55700fc0-8196-11e7-8f66-ae9ad01d95b4.png">
<img width="970" alt="screen shot 2017-08-15 at 8 44 24 am" src="https://user-images.githubusercontent.com/79357/29323631-55711ece-8196-11e7-8d2f-0f38cf6c1191.png">

These builds happened at different times, some different days, but 25-29 all occurred within the same hour, and it was never just streamed from another worker.

**Comment by jtarchie** [comment]
We've had a few people maybe report a related problem. They've come into slack asking why the same version of a git SHA it being cloned 40,000+ per day.

**Comment by topherbullock** [comment]
@krishicks Are you using Vault? This could be related to #1413 ; there's a few cascading deletions that are happening when resource configurations are erroneously deemed outdated when using Vault to fill in their params.

The work on #1413 should tighten up the GC logic and keep those volumes around when there's still a use for them.

**Comment by krishicks** [comment]
@topherbullock We have Vault deployed but we're not using it in these pipelines.

**Comment by jtarchie** [comment]
I was referring to this concourse/git-resource#132
