### ISSUE TITLE
[Multi-Pipeline View] List all Pipelines grouped by their teams

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1478]
This is a child issue to #1442 

# Feature Request
List all pipelines grouped by their teams

* As a developer and/or operator, I'd want to have page where I can see the list of pipelines grouped by what teams they belong to so that I can have an "at a glance" view of the world
* We want to start by creating a page (`/dashboard`) that lists the pipelines grouped by the teams they belong to
* We want to place this page in `dashboard` for now so we can iterate on this view and the information we show before we solve the navigation problems of how to get to and from this summary view

![dashboard_by_team_red_green_states_1442.png](https://codetreeusercontent.s3.amazonaws.com/uploads/7b323c3c-7b08-453e-ac54-46dee542b909/dashboard_by_team_red_green_states_1442.png)

**Comment by vito** [comment]
Completed a first pass at this! Have a few questions:

* We're not sure if the exported image is "to scale" - we assume so but the top bar's throwing us off a bit.
* I noticed there's a new color palette - should this be reflected in the rest of the site?
* We're assuming the page is fluid-width and not always three columns.
* There's one gotcha with pipeline names that wrap - they end up pushing the whole row below them down. We think this may be OK, but noticed in your original mockup it seems to take up the same amount of space, but reduce the padding. This is harder to implement and probably only works for up to two lines of wrapping. We're happy to try something else, though.
* We don't have any rules for ordering. Should it be alphabetical, with your own team at the top?
* We assumed the names should be clickable to go to the pipeline. So we did that. We didn't add a hover/click state or anything though.

![screen shot 2017-08-17 at 1 55 00 pm](https://user-images.githubusercontent.com/1880/29426306-37a19314-8354-11e7-99f5-3433e147a5a7.png)

**Comment by mhuangpivotal** [comment]
Thanks @Lindsayauchin for taking a look! 

> I noticed there's a new color palette - should this be reflected in the rest of the site?

We decided to stick with the existing colour palette and make a site wide update in the future.

> We're assuming the page is fluid-width and not always three columns.

We switched to Flexbox.

> We don't have any rules for ordering. Should it be alphabetical, with your own team at the top?

The ordering should be the same as the sidebar.

> We assumed the names should be clickable to go to the pipeline. So we did that. We didn't add a hover/click state or anything though.

On hover, the background for the pipeline should change colour (colour TBD).
