### ISSUE TITLE
'what is going on' feature set

### ISSUE THREAD

**Issue by dliebreich** [concourse/concourse#148]
We monitor many pipelines, each of which has many groups, and a pain point for us is scanning all of the concourse status displays to see what is going on, and if there have been any failures we need to look at.

We would like:
- a dashboard page, which shows all of the builds in progress at the moment and a list of recent build failures
- an event stream of build events, so we could consume it and (for example) send a message to a slack channel saying "build X failed - (link to build)" or "build X succeeded"

we experimented with polling the builds api endpoint, but it is not in chronological order, does not support pagination, and we had to keep a lot of state in our script in order to detect failures of long-running builds.

**Comment by kris-runzer** [comment]
More or less wha @dliebreich wants is what I would like to see as well.  Doesn't need to be complex; just simple enough to give a quick snapshot of the state of things would be awesome as a first step.

**Comment by SillyMoo** [comment]
I would quite like an overview for a pipeline that shows groups and connections between the groups. Basically like the visualisation that is already present for resource(s)->job->resource(s)->job... but instead resources(s)->group->...->group->resources, just showing the input/output resources.

**Comment by ahelal** [comment]
Would also be cool to have  badge per Pipeline

**Comment by Rukenshia** [comment]
Having an overview would be great.

**Comment by jama-pivotal** [comment]
Regarding dashboard page, I think the new beta dashboards that we've been rolling out in 3.5.0 (/dashboard/) and 3.6.0 (/beta/dashboard) might help you out. Regarding build event streams and notifications, I think the essence of https://github.com/concourse/concourse/issues/1052 addresses that, plus some of the work in https://github.com/concourse/concourse/issues/1538 which we plan on continuing in future versions of Concourse...once we figure out a way to nicely visualize it.

sooo, if ya'll don't mind I'm going to close this issue and consider it done/in progress!
