### ISSUE TITLE
[Multi-Pipeline View] Use amber icons to indicate error'ed pipelines

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1483]
#This is a child issue to #1442 

# Feature Request
Use amber icons to indicate error'ed pipelines

As a developer and/or operator, I want to visually see error'ed pipelines with the amber highlighting and iconography so that I can immediately detect error'ed pipelines from a distance

- [x] Show orange for error'ed pipeline 
- [x] Show orange exclamation point icon for error'ed pipelines

![dashboard_by_team_red_green_states_p1_1442](https://user-images.githubusercontent.com/27746614/29330710-0eec0496-81c8-11e7-8e42-6aeb8e7e24a5.png)

**Comment by ttecho** [comment]
@jama-pivotal Is the view in this picture available on all concourse pipelines?
