### ISSUE TITLE
/opt/resource/check failed: exit status 1 failed to ping registry

### ISSUE THREAD

**Issue by fvclaus** [concourse/concourse#1489]
I am seeing the following error message in the build output while trying to get the hello-world pipeline running:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to ping registry: 2 error(s) occurred:

* ping https: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
* ping http: Get http://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
I have read quite a few issues with the same problem, but haven't found the solution. This are the contents of my /etc/resolv.conf:
```
# Generated by NetworkManager
nameserver 192.168.0.1
```
I also tried the `--garden-dns-server` switch, but that didn't work either. In general, the DNS resolution works in docker images. Here is how I start a worker instance:
` ./concourse_linux_amd64 worker --work-dir worker --tsa-public-key keys/tsa_host_key.pub --tsa-worker-private-key keys/worker_key  --baggageclaim-log-level debug --garden-log-level debug --garden-dns-server 8.8.8.8`

I am running debian jessy without a firewall, at least that's what I think, because the ufw command cannot be found.

* Concourse version:  3.3.4
* Deployment type (BOSH/Docker/binary): binary

**Comment by jtarchie** [comment]
@fvclaus, are you running `docker` on the same machine?

**Comment by fvclaus** [comment]
Yes, everything is running on the same machine:
```
$ docker --version
Docker version 17.04.0-ce, build 4845c56
```

**Comment by jtarchie** [comment]
@fvclaus, sorry, to clarify. Using concourse binaries along with `docker` on the same machine causes problems. The `docker` daemon takes control of many resource for containerization. In short, running two containerization orchestrators on the same machine never fairs well.

Your options:

* uninstall `docker`
* use the [`docker-compose` setup](http://concourse.ci/single-page.html#docker-repository)
* try on a clean `docker` free VM

**Comment by fvclaus** [comment]
If this setup is not supported, can you please add that to the documentation somewhere. I did not find this information and struggled for several hours.

**Comment by adarshaj** [comment]
Still facing this issue. The link by @jtarchie is 404 too now. What's the right setup exactly?
