### ISSUE TITLE
Concourse web ui should provide a URL for hijack/intercept

### ISSUE THREAD

**Issue by cheeseblubber** [concourse/concourse#149]
Figuring how to hijack/intercept is difficult.

**Comment by vito** [comment]
Assuming by URL you meant commandline string to copy/paste?

Is this easier with the interactive hijacking we added a while back? Should just need `-j pipeline/job` now and it'll ask from there.

**Comment by joshzarrabi** [comment]
I'm gonna close this as it doesn't seem to be an issue anymore.
