### ISSUE TITLE
[Multi-Pipeline View] Animate the broken pipeline timer

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1495]
This is a sub-story of the bigger "Thumbnail preview on red pipelines" #1462 

# Features 

This is a follow up story to #1494 as well. It would be nice to animate the tick of the clock using an animation similar to http://paulcuth.me.uk/departure-board/

**Comment by mhuangpivotal** [comment]
WIP on `wip-1495`

**Comment by jama-pivotal** [comment]
The animation was a good idea but its a bit too much for now. Closing
