### ISSUE TITLE
Old workers stay in `stalled` state indefinitely after restart

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#1497]
# Bug Report

After a rolling restart of concourse workers, old workers remain in the `stalled` state until manually pruned:

```
name                                  containers  platform  tags  team  state    version
0eecd635-cacd-413c-a9e5-2446e45ae176  40          linux     none  none  running  1.1
2ae152da-cf79-429c-bb6f-921d8712d658  63          linux     none  none  running  1.1
323e2c8f-4ef6-49bc-9771-0cd531ce70f4  41          linux     none  none  running  1.1
5ba8fa75-1de7-4625-92f8-14a69c63aa21  0           linux     iaas  main  running  1.1
63dbb4d5-0c5b-4043-8f5e-90ef886fb2d6  21          linux     none  none  running  1.1
b8198ced-0601-4b05-ba49-0160ae4f3652  23          linux     none  none  running  1.1
be65bedd-1701-411a-8859-768bb5df2e43  0           linux     iaas  main  running  1.1


the following workers have not checked in recently:

name                                  containers  platform  tags  team  state    version
0eecd635-61ee-436d-b516-927e8888ca7d  122         linux     none  none  stalled  1.1
0eecd635-f983-476a-ba9f-29e684b8b692  97          linux     none  none  stalled  1.1
323e2c8f-6ece-430d-991c-b0a1b03f4ec9  92          linux     none  none  stalled  1.1
323e2c8f-dfa4-44cf-8f62-c9ab636b1d0c  89          linux     none  none  stalled  1.1
5ba8fa75-7805-476c-ac6e-c86a2d1f3562  1           linux     iaas  main  stalled  1.1
5ba8fa75-caf3-4761-961b-7ea7533658f6  0           linux     iaas  main  stalled  1.1
63dbb4d5-6eea-4853-880a-dac8d2766012  87          linux     none  none  stalled  1.1
63dbb4d5-cfcb-4cfa-a036-a63d208b7eb7  105         linux     none  none  stalled  1.1
b8198ced-5dcc-40b7-afc0-6abc316ee81e  119         linux     none  none  stalled  1.1
b8198ced-dee5-453c-afc8-17f71b4b0a31  105         linux     none  none  stalled  1.1
be65bedd-0029-4cbb-9a85-58af3fb8997f  1           linux     iaas  main  stalled  1.1
be65bedd-c674-48c5-a0ad-44ab9006c5a9  0           linux     iaas  main  stalled  1.1
```

Some of those stalled workers are from a recent restart; the others are from a restart over 24h ago.

I would expect old workers to get cleaned up during the deploy process. Or is this expected behavior--are operators supposed to manually prune old workers after every restart?

* Concourse version: 3.4
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: aws
* Browser (if applicable): n/a
* Did this used to work?

**Comment by topherbullock** [comment]
@jmcarp thanks for reporting this. We've seen a couple problems with the BOSH drain scripts and worker management causing stalled workers to persist. A couple questions to clarify what your flow is:
- Did you `bosh restart` or `bosh recreate` the workers in question?
- Were there any tasks in flight on the workers configured with `interruptible : false`?
- Did the workers being restarted go into the "landing" state?
- Were the workers stalled when they were recreated / restarted?

**Comment by jmcarp** [comment]
We've seen workers stuck in a `stalled` state both after upgrading the concourse version (from 3.3.4 to 3.4) and after upgrading the bosh stemcell. I just ran a `bosh restart` and didn't see any stalled workers. None of our jobs set `interruptible`. I don't know whether any workers were stalled before the updates or whether the workers switched to the `landing` state--would that information be in the logs? I can try a `bosh recreate` over the weekend and watch more closely, but we trigger concourse deploys on new concourse versions and stemcells, so we don't normally check worker state before a deploy.

**Comment by jmcarp** [comment]
@topherbullock: we just got another batch of stalled workers on updating stemcells:

```
± fly -t fr workers
name                                  containers  platform  tags  team  state    version
0eecd635-20b7-4fa0-8b48-6d3ac98c389d  250         linux     none  none  running  1.2
2ae152da-838e-4709-bb89-33fdc1721093  250         linux     none  none  running  1.2
323e2c8f-3021-412d-aa3c-69f225fb7bc3  250         linux     none  none  running  1.2
5ba8fa75-78d1-4a0a-9758-010413d48f5b  0           linux     iaas  main  running  1.2
63dbb4d5-6129-4b0d-82ea-56b824a87bc4  249         linux     none  none  running  1.2
b8198ced-28b3-4332-a5aa-9a5f04b4655b  221         linux     none  none  running  1.2
be65bedd-4c0a-427e-be99-b6603ca50487  0           linux     iaas  main  running  1.2


the following workers have not checked in recently:

name                                  containers  platform  tags  team  state    version
0eecd635-955e-48bf-8129-199ab9bce6e0  144         linux     none  none  stalled  1.2
323e2c8f-56de-432f-8c06-22c44a221fac  151         linux     none  none  stalled  1.2
63dbb4d5-6028-4c1c-8093-5becff5166b1  133         linux     none  none  stalled  1.2
b8198ced-0aac-4ca3-a3a0-476575fd2f49  149         linux     none  none  stalled  1.2
be65bedd-1701-411a-8859-768bb5df2e43  4           linux     iaas  main  stalled  1.2
```

I haven't been able to replicate this with `bosh -d concourse recreate worker` after hours. Lots of our pipelines trigger on stemcell updates, so I'm wondering whether workers stay stalled when lots of containers are running. Not sure why that would be--does that sound plausible to you? Thoughts on how to investigate?

**Comment by tyyko** [comment]
+1 on the topic.
I saw the same issue during a concourse upgrade from 3.3.2 to 3.4.0 while many jobs were running.
Only manually calling`bosh recreate worker` helped to fix the issue.

**Comment by poblin-orange** [comment]
+1. can consistently reproduce after each stemcell upgrade. Really annoying as it locks my builds (concourse git scan stay stuck on these non existent workers)

**Comment by vito** [comment]
This happens when you have a single TSA. The workers are configured such that if they cannot reach a TSA while draining, they give up and just get updated without draining. This leaves them stalled.

We should probably just make them more resilient and wait for the TSA to become reachable again.

**Comment by jmcarp** [comment]
This also seems to happen with >1 TSA. We have two "web" instances (running ATC and TSA, like in concourse-deployment) and see this happening regularly.

**Comment by EugenMayer** [comment]
@vito this also happens when the TSA was reachable

**Comment by ahume** [comment]
I can reproduce this on kubernetes when a node VM is destroyed. The worker enters `stalled` state and once rescheduled a few seconds later does not recover without pruning.

Worker logs just print`Process exited with status 1` repeatedly.

**Comment by 2color** [comment]
I'm experiencing the same problem with version `3.8.0` using the official helm chart. 

As @ahume reported, I'm also only seeing worker logs just print `Process exited with status 1` repeatedly.

**Comment by MorrisMatrix** [comment]
I am experiencing this behavior with our Kubernetes v1.11 (AWS EKS) cluster, it seems to happen once a node appears to go `unknown`, I deploy Concourse v4.2.2 using Helm chart v3.7.3 and was able to get my workers back in a `running` state by issuing the command `fly -t cloud prune-workers -w <worker>, <worker>`  on all workers that were in a `stalled` state. It appeared I had to issue the command multiple times before the workers actually joined back. I am using persistent storage for the worker nodes and I am deploying the PostgresSQL Database externally.

**Comment by luispabon** [comment]
I can confirm this is no longer an issue for me in Kubernetes after upgrading to Concourse 4.2.x and passing the `--ephemeral` flag to the workers pod definition, like so:

```
      containers:
        - image: concourse/concourse
          name: worker
          args: [worker, --ephemeral]
```

**Comment by luispabon** [comment]
I cobbled up this https://github.com/luispabon/concourse-workers-cleaner specifically for kubernetes as a cronjob for those who cannot yet upgrade Concourse. It's a bit filthy but it does work.

**Comment by cirocosta** [comment]
> We should probably just make them more resilient and wait for the TSA to become reachable again.

this is still true 🤔  (@vito)

**Comment by asdeshpande1995** [comment]
I was able to delete all the stalled workers in my respective teams. But, I am getting "error: forbidden" when I tried to prune-worker with team as none.
Does anyone know how to delete such workers.
