### ISSUE TITLE
`fly set-pipeline` bails out when automated with `yes`

### ISSUE THREAD

**Issue by thardeck** [concourse/concourse#1498]
We have automated our pipeline deployment with a Makefile. Since `fly` always asks for confirmation before deploying we use the `yes` command with a pipe.

This used to work fine at least before 3.3.0 but if now applied in the same way `fly` exits with the pipeline diff and the message:
```
bailing out
```

Our commands look like this:
`yes | fly -t target set-pipeline -c pipeline.yml -p pipeline`

Without `yes` running the command works fine. Is there a better way to non-interactively deploy pipelines with fly?

* Concourse version: 3.4.0
* Deployment type: Bosh
* Did this used to work? Yes

**Comment by chendrix** [comment]
From the help text of `set-pipeline`:

>       -n, --non-interactive         Skips interactions, uses default values
