### ISSUE TITLE
Tasks sometimes fail when interacting with a vault backend

### ISSUE THREAD

**Issue by jdeppe-pivotal** [concourse/concourse#1499]
# Bug Report

* Concourse version: 3.3.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable):

We have recently started using `vault` to manage some credentials and occasionally see this error when tasks start:
```
Finding variable 'docker-username': Get https://vault.foo.com:8200/v1/concourse/main/docker-username: http2: no cached connection was available
```
The job then fails to start.

Not sure if this is relevant: https://github.com/golang/go/issues/16582

**Comment by jdeppe-pivotal** [comment]
Appears to be a problem with Vault as it's using the old http2 lib: https://github.com/hashicorp/vault/blob/master/api/client.go#L16

**Comment by willejs** [comment]
I get this too, usually when alot of tasks kick off at the same time that need values from vault. Without looking at the net/http2 library I suspect its some sort of connection pooling that takes place thats being exhausted?

**Comment by EugenMayer** [comment]
same here as commented here https://github.com/hashicorp/vault/issues/3203

Seems like this could indeed be a go-lang issue https://github.com/golang/go/issues/16582 ..

Could that be related to https://github.com/golang/go/issues/22091#issuecomment-341585501 in concourse?

**Comment by tredfield** [comment]
Also having this issue. Any update?

**Comment by timrchavez** [comment]
Just hit the issue, myself!

**Comment by smgoller** [comment]
It looks like the golang net library may have been fixed:

https://github.com/golang/go/issues/22091

Can someone take a look at this?

**Comment by vito** [comment]
Finally went and bumped the dependency, sorry for the delay. Had to just stop vendoring in the creds package and use the outer submodules, and bump those for good measure.

I won't be able to really confidently say this is fixed, given that the error is spurious in nature, but I can at least say we're running the code that should have the fix. 😛 

Thanks for your patience!
