### ISSUE TITLE
Can't hijack a container while it's marked 'destroying' but kept because of other hijack

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1503]
# Bug Report

Here's what I did:

* Execute a one-off build.
* Hijack while it's running.
* Wait for the build to finish.
* The previous hijack should keep it alive, so I should be able to hijack again. Instead, I get `websocket: bad handshake`, and the logs say "container-not-found".

The container shows up just fine in `fly containers`, which includes `destroying` containers, so this seems to be an inconsistency in the API. I'm guessing the container is marked `destroying` and hijacked, so it should be subject to Garden's grace time, and I should be able to hijack it as much as I want.

The following can also be handy:

* Concourse version: v3.4.0
* Did this used to work? Yes, pre-life.

**Comment by topherbullock** [comment]
I cried reading this 😢 
10/10

**Comment by topherbullock** [comment]
Happens with creating containers as well
