### ISSUE TITLE
Pipeline view resets itself every few seconds

### ISSUE THREAD

**Issue by sahilm** [concourse/concourse#1505]
# Bug Report

## What happened?
When I zoom-in to a section of a pipeline, the pipeline view resets itself to fit-to-screen after a few seconds. I'm not hitting the `F` key. This seems to be a new issue with `v3.4.0`.

This issue is causing a lot of pain because I can no longer debug my pipeline by visually scanning the resource flow.

## What did I expect to happen?
The pipeline view should stay zoomed-in and not reset itself.

## Concourse version
`v3.4.0`

## Deployment type
BOSH

## Infrastructure/IaaS
GCP

## Browser
Chrome `v60.0.3112.101 (Official Build) (64-bit)`

## Did this used to work?
Yes. It worked on `v3.3.4`.

**Comment by jtarchie** [comment]
@sahilm, do you experience the same issue when visiting our [ci](https://ci.concourse.ci/)? I've been unable to reproduce the issue.

**Comment by jama-pivotal** [comment]
Was just able to reproduce this on 3.4.0 as well. Looks like this happens when the legend auto-hide kick in. The legend disappears and then quickly re-sets the zoom level to default

**Comment by sahilm** [comment]
Thanks for fixing this bug so fast. You folks are the best!
