### ISSUE TITLE
Resource Caches should not be reaped when they're about to be used by a build

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#1510]
#1413 handles the case of Containers being reaped due to some schema issues around resource_configs and their 'use' in tying a checking container to a configuration of a resource, and the resource config check session, which keeps those containers around while that config of a resource is valid. 

This is fixed now, but there's a separate concern of resource caches and their use. This has been observed by others : #1475 #1255 

From @clarafu on #1413 :

> After implementing everything in @vito's comment above, we also found that caches were being reaped for the same reason, the resource cache collector will reap the caches for the next build inputs if the resource and resource_config source hashes do not match. This brings us back to the original problem of if the resource's config has variables coming from vault, the resource's source hash will be of the un-interpolated config and the resource config's source hash will be of the interpolated config. We need to find a workaround to have the resource cache collector not need to use the source hashes so that we can remove the source hash column from the resources table (since the implementation of vault makes source hash in the resources table useless).
> 
> EDIT: We are going to add resource_config_id column to the resources and resource types table in order to tie a resource to a resource config. This will replace the use of the source hash.
> 
* [x] Fill in resource_config_id in the resources and resource_types table during a check in radar
* [x] Remove use of source hash in resource cache collector
* [x] Add gc logic for reaping resource config check session when a resource is paused, inactive or removed
* [x] Remove source hash from resources
* [x] See if we can simplify the resource instance

**Comment by iswix-llc** [comment]
Actually I have switched to web_hook and that's giving me a different issue.  I'll open another issue.
