### ISSUE TITLE
Task flag to indicate which resource was triggered

### ISSUE THREAD

**Issue by gdenn** [concourse/concourse#1511]
# Feature Request

In a concourse job with multiple resources as input i want to be able to give the tasks a flag or env variable which holds information about which resource triggered the job so the tasks can behave accordingly.

In my concourse ci pipeline i have a job which is triggered by cloud foundry buildpack updates and has a task which tests the specific buildpack, compiles it and uploads it to our Cloud Foundry.

Currently i need to test and compile all available buildpacks since i cannot tell which buildpack update triggered the job from inside the task. To have an env variable e.g. RESOURCE_TRIGGER=go-buildpack which tells which resource was triggered would make it possible to only test and compile the buildpack that has been modified.

I know i could make a dedicated task and job for each buildpack e.g. update-go-buildpack, but i want to keep my concourse pipeline as generic as possible not bloating it with repetitive logic.

**Comment by jtarchie** [comment]
I think the restraint of not wanting "bloating it with repetitive logic" is inhibiting you. This is exactly what a pipeline designed for -- fan in, fan out, and different topographies.

The mechanism that you want exists. Each buildpack has a job, this enables the isolation to control what triggers that individual job.

The repetition can be minimized by using a templating language to generate your pipeline, the most common is ERB.

For example:

```erb
jobs:
<% %w(ruby go java python).each do |name| %>
- name: test <%=name%>-buildpack
  plan:
  - get: ci
  - get: buildpack
    resource: <%=name%>-buildpack
    trigger: true
  - task: tests
    file: ci/scripts/test-buildpack.sh
<% end %>
```

Then when you set your pipeline you can evaluate it. `fly set-pipeline -p test -c <(erb pipeline.erb.yml)`

This is pattern that many teams use. It allows you to have control of a pipeline. It also allows you to choose your favorite templating language! 😄

**Comment by gdenn** [comment]
Thank you, this is awesome. I haven't looked at the problem from this perspective.

**Comment by jtarchie** [comment]
@gdenn, good to close this then?

**Comment by gdenn** [comment]
(Y)
