### ISSUE TITLE
Stream digest error

### ISSUE THREAD

**Issue by benzaremean** [concourse/concourse#1514]
I downloaded the concourse-lite.yml file from [downloads page](https://github.com/concourse/concourse/releases/tag/v3.4.0) and followed BOSH installation instructions but I am getting the following error on running 

`bosh create-env concourse-lite.yml
`

```
Started validating
  Downloading release 'concourse'... Failed (00:00:02)
Failed validating (00:00:02)

Failed to download from 'https://github.com/concourse/concourse/releases/download/v3.4.0/concourse-3.4.0-3445.2.tgz':
  Verifying digest for downloaded file:
    Expected stream to have digest 'a9f8182eb5a32ec592f9233c5993d172b357f3cb' but was '43c8ef28fb100441efd0fb80244f979c7859f983'

Exit code 1
```

I have tried on two separate machines but still getting the same error

* Concourse version: v3.4.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work? It worked when I tried it last week

**Comment by jtarchie** [comment]
Yeah, we need to regenerate that. Thanks!

**Comment by benzaremean** [comment]
Cheers for prompt reply.

**Comment by benzaremean** [comment]
This is fixed now
