### ISSUE TITLE
Migration failure when upgrading from 2.7.4 -> 3.4.0

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse#1515]
# Bug Report

When migrating from 2.7.4 -> 3.4.0 we saw the following migration error in the atc logs. 

```
 migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
failed to migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
failed to migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
failed to migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
failed to migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
failed to migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
failed to migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
failed to migrate database: pq: column "size_in_bytes" of relation "volumes" does not exist
```
I believe this [migration](https://github.com/concourse/atc/blob/bd6bc8059278598acbd284d095c6450dc48985d6/db/migrations/migrations.go#L186) causes the failure, as we never had the `size_in_bytes` row in the first place. 

* Concourse version: 2.7.4 -> 3.4.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): N/A
* Did this used to work? N/A

**Comment by vito** [comment]
Wut.

There should be a migration that added it even if it wasn't there before.

Why didn't you have the column? It was added long before 2.7.4.

**Comment by joshzarrabi** [comment]
We got this to work by changing the `migration_version` table to 175 from 174, which worked as atc no longer tried to run the last migration.

**Comment by vito** [comment]
Don't think we'll be able to debug this, to be honest. I can't see a reason for that to have failed, and the environment is no longer in that state.
