### ISSUE TITLE
Unpausing a public pipeline under a different team redirects to a login page that fails

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#1519]
# Bug Report

Given I am logged into a team, when I try to unpause a public pipeline in another team, I am prompted to log into the other team. When I click the "login" button, I get "forbidden".

Both teams were set up with `--no-really-i-dont-want-any-auth`.

* Concourse version: 3.4.0
* Browser (if applicable): Chrome
* Did this used to work? don't know

**Comment by jama22** [comment]
Closing because we added more checks on the UI in 5.2.0 #2428
