### ISSUE TITLE
Concourse keeps creating interfaces

### ISSUE THREAD

**Issue by jeroenjacobs1205** [concourse/concourse#1522]
# Bug Report

My Concourse workers network interface list keeps growing.

output of `ip a | grep 'inet `:

    inet 127.0.0.1/8 scope host lo
    inet 192.168.120.133/27 brd 192.168.120.159 scope global ens160
    inet 172.17.0.1/16 scope global docker0
    inet 10.254.0.97/30 scope global wbrdg-0afe0060
    inet 10.254.0.105/30 scope global wbrdg-0afe0068
    inet 10.254.0.21/30 scope global wbrdg-0afe0014
    inet 10.254.0.133/30 scope global wbrdg-0afe0084
    inet 10.254.0.81/30 scope global wbrdg-0afe0050
    inet 10.254.0.89/30 scope global wbrdg-0afe0058
    inet 10.254.0.181/30 scope global wbrdg-0afe00b4
    inet 10.254.0.5/30 scope global wbrdg-0afe0004
    inet 10.254.0.85/30 scope global wbrdg-0afe0054
    inet 10.254.0.29/30 scope global wbrdg-0afe001c
    inet 10.254.0.41/30 scope global wbrdg-0afe0028
    inet 10.254.0.93/30 scope global wbrdg-0afe005c
    inet 10.254.0.65/30 scope global wbrdg-0afe0040
    inet 10.254.0.13/30 scope global wbrdg-0afe000c
    inet 10.254.0.33/30 scope global wbrdg-0afe0020
    inet 10.254.0.101/30 scope global wbrdg-0afe0064
    inet 10.254.0.9/30 scope global wbrdg-0afe0008
    inet 10.254.0.137/30 scope global wbrdg-0afe0088
    inet 10.254.0.53/30 scope global wbrdg-0afe0034
    inet 10.254.0.145/30 scope global wbrdg-0afe0090
    inet 10.254.0.113/30 scope global wbrdg-0afe0070
    inet 10.254.0.117/30 scope global wbrdg-0afe0074
    inet 10.254.0.125/30 scope global wbrdg-0afe007c
    inet 10.254.0.141/30 scope global wbrdg-0afe008c
    inet 10.254.0.17/30 scope global wbrdg-0afe0010
    inet 10.254.0.25/30 scope global wbrdg-0afe0018
    inet 10.254.0.37/30 scope global wbrdg-0afe0024
    inet 10.254.0.45/30 scope global wbrdg-0afe002c
    inet 10.254.0.49/30 scope global wbrdg-0afe0030
    inet 10.254.0.57/30 scope global wbrdg-0afe0038
    inet 10.254.0.61/30 scope global wbrdg-0afe003c
    inet 10.254.0.69/30 scope global wbrdg-0afe0044
    inet 10.254.0.73/30 scope global wbrdg-0afe0048
    inet 10.254.0.109/30 scope global wbrdg-0afe006c
    inet 10.254.0.1/30 scope global wbrdg-0afe0000

We don't have so many build jobs running on this worker, so I think those interfaces never get cleaned up.

**Comment by jeroenjacobs1205** [comment]
I was just about to post that info. I see quite a few entries like this:

```
6685d9f-f282-41ea-420c-2e5c94042eb2  concourse-001  none                    none                                                                     none  none  check  none              n/a
4409a2df-ac04-429a-42f1-cf1154d402dd  concourse-001  none                    none                                                                     none  none  check  none              n/a
45a9bb52-f707-4c54-7b1c-aa6e45edb6ff  concourse-001  none                    none                                                                     none  none  check  none              n/a
473020a7-f6e5-4157-6791-e976aef0dfb8  concourse-001  none                    none                                                                     none  none  check  none              n/a
47378053-9242-47cb-4ede-50281ce4b9b7  concourse-001  none                    none                                                                     none  none  check  none              n/a

```

Those are all containers doing nothing?

**Comment by jeroenjacobs1205** [comment]
Also, how is the IP range determined that is being used by these containers? How can I customize this?

**Comment by SHyx0rmZ** [comment]
The IP range can be customized via the `--garden-network-pool` flag on the worker, which defaults to `10.254.0.0/22`.

**Comment by vito** [comment]
@jeroenjacobs1205 They are not doing nothing - each resource in a pipeline has a corresponding `check` container for continuously detecting new versions.

I'm going to close this - if you see a leak or something feel free to ping for a reopen!
