### ISSUE TITLE
Suspend Resume Cycle of Worker Node stalls worker 

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1525]
# Bug Report

I tend to suspend a very power hungry GPU/HW node over the weekend.

Until 3.x.x (< 3.4.0) the suspend+resume cycle worked fine and the worker published again.

Since 3.4.0 (or a few versions earlier) this stopped to work entirely, the worker does not seem to do anything anymore. The logs are empty since suspend.

The following can also be handy:

* Concourse version: 3.4.0
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS: docker
* Browser (if applicable): firefox
* Did this used to work? yes

**Comment by vito** [comment]
Let's consolidate this into https://github.com/concourse/concourse/issues/1457. Thanks!
