### ISSUE TITLE
Dev - Gabriel Dumitrescu

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#1527]
## Mailing Lists

- [ ] concourse at pivotal.io
- [ ] wing_alert at pivotal.io

## Calendars

- [ ] Concourse
- [ ] Concourse OOO

## Accounts

- [x] Github
- [x] LastPass
- [x] [Slack][slack]
- [ ] [PagerDuty][pagerduty]
- [x] [Pilots][pilots]

## Github access

- [x] concourse/Pivotal team
- [x] pivotal-cf/concourse-wings

## LastPass access

- [ ] Shared-Concourse

## GCP Project owner access

- [ ] cf-concourse-production

## Slack Channels

- [x] concourseci#team
- [x] concourseci#flight-plan
- [x] Pivotal#concourse-wings

## Dev Setup

- [x] .git-authors

## SSH Keys

- [x] Get USB thumb drive
- [x] [Reformat as encrypted drive][encrypted-drive]
- [x] Create SSH key pair and add to Github account

## Readings

- [x] bit.ly/concourse-wiki

## Checklist

- [x] Update the [template](/concourse/concourse/wiki/Developer-Onboarding-Checklist) with improvements made

[slack]: https://concourseci.slack.com
[encrypted-driver]: http://tammersaleh.com/posts/building-an-encrypted-usb-drive-for-your-ssh-keys-in-os-x/
[pagerduty]: https://cfoundry.pagerduty.com
[pilots]: http://pilots.cfapps.io

**Comment by jama-pivotal** [comment]
Closing, since he's onboarded
