### ISSUE TITLE
Spike: resource causality flow

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1538]
# Feature Request

## What challenge are you facing?

Concourse currently represents a pipeline as a single large graphic, with each job showing the 'current state' of the job.

This is convenient for things like quick navigation and knowing "is the pipeline OK?", but it is not great for knowing *what* is going through the pipeline, and how far it's gotten.

It also somewhat misrepresents how pipelines work. There is no "run" of a pipeline. There is no "triggering" a pipeline. Pipelines have no start or finish. In fact, a pipeline is simply a chain of jobs, and may contain many *sub*-pipelines, where either an entirely isolated sequence of jobs runs, or a new resource may appear in the middle of a larger chain of jobs, and trigger only the things after it.

We've heard a desire in the past to have an alternate, "integral" view of the data Concourse collects: given a particular **version**, what impact did it have on the pipeline? What jobs did it flow through, what outputs were *produced* by those builds, what builds failed or were re-triggered, etc. In short, we're calling this information the *resource causality*.

## A Modest Proposal

This is a whole new area of exploration, so we're going to sort of throw things at the wall and spike on this quickly and see what sticks. Our first approach will be to define a view for a given resource version that conveys a "snapshot" of the pipeline as affected by that version. It may be a linear list intermixing resources and builds, or in the long run we may turn it into something that reflects the pipeline configuration.

Metaphorically, the data we'll be viewing is like a "slice" of the pipeline. Like the [sheets](https://user-images.githubusercontent.com/1880/29876055-b977a5da-8d69-11e7-852b-f2a87939d303.png) for an [overhead projector](https://user-images.githubusercontent.com/1880/29875189-2668401c-8d67-11e7-8ba8-63855326c557.png).

When stacking these sheets with the newest on top, that's how you'd get today's pipeline view. This experiment is to make those sheets first-class citizens and see what useful information they can tell us. It may be that they're a better representation for things like a CI monitor, and a more accurate representation of Concourse's primitives than today's pipeline UI represents.

**Comment by vito** [comment]
We've run in to a few challenges with this, which I'll make note of here (the rest will be in comments as we run in to them):

## How do we represent re-triggered builds?

So far we're tracking causality by tracking "first occurrences" of the given resource. Re-triggered builds will, by definition, not be "first occurrences", but they are important to show why the causality chain continued. Showing the original failures is also important, as someone may be interested in seeing that a particular version took a few tries to make it through.

This may be helped by #413 which would formalize re-triggering, allowing us to directly associate the re-triggered build with the original failure, rather than guessing by whether any inputs changed.

## How do we "follow" a path where one resource triggers everything but then is no longer passed along?

In a scenario like below, from our [resources pipeline](https://ci.concourse.ci/teams/main/pipelines/resources):

![screen shot 2017-08-30 at 9 45 30 am](https://user-images.githubusercontent.com/1880/29875428-02f3abf2-8d68-11e7-8255-510d27841001.png)

Note that the `buildroot` resource feeds in to `buildroot-hg` and causes `buildroot-hg-image` to be built and passed on, but `buildroot` is not. We're currently tracking by "first occurrences", so this limits the result to the first build. We'll probably need to iteratively follow through to explicit outputs of builds, as well.

## If this is used for a CI monitor view, how do we know what to show?

Intuitively, I would expect new commits to show up in the most prominent area of the screen. Does this mean we select for newest versioned resources and show their causality?

What happens when there are multiple streams running? What happens when someone re-triggers a job from a long time ago, with really old inputs?

## How do we represent the causality flows themselves?

So far we've got this:

![screen shot 2017-08-30 at 9 50 17 am](https://user-images.githubusercontent.com/1880/29875648-a75f15b4-8d68-11e7-9586-7ec1da5cd027.png)

But it may be nicer to have it reflect the pipeline's configuration. In this way it could be layered on top of the pipeline view, intuitively leading to the "sheets" metaphor mentioned previously.

**Comment by vito** [comment]
Here's the story so far: there's a newer, better query that no longer special-cases "first occurrences". This means it'll now include re-triggered builds. Yay!

The new query's approach is to do the following:

1. Find all occurrences of the version as an input.
1. Find all explicit outputs of builds the version was an input to.
1. Find all builds with those output versions as an input.
1. Exclude inputs that are to builds where a prior build of the same job created the input.
1. Go back to step 1.

This is done as a single `WITH RECURSIVE ...` query. Kinda neat! Except there's one sub-query, so it's not really a single query, but whatever.

You'll note that step 4 is a bit tricky. This is to handle cases where a job takes version N and produces N+1, which then feeds into the next build. A common example of this would be jobs that bump a version. Without this step as a short-circuit, viewing the causality leading to such a job would end up following all the way from where you started to the latest commit! So that was an interesting finding, and one that was quite tricky to work around, but the current solution seems to work well. (I went pretty far down the recursive query rabbit hole before arriving at that solution.)

The newest problem to tackle is the ordering of the results. Currently it order by build ID, but I just ran into a case where a later build (to a human) can appear before the rest: if a build is queued up and pending on a paused job, and then things run through, and you finally unpause it, its build ID will be lower than the ones that came "before" it in the causality flow, leading it to appear first. We should perhaps just order by start time instead.

**Comment by vito** [comment]
Depending on how we show this to the user (e.g. overlaid on the pipeline), having versioning of the pipeline config becomes more important; we'd want the resource flow to render on top of the config as it *was*.

There's a related question around what happens when you change the config in the middle of a particular version's causality. idk.

**Comment by vito** [comment]
Calling the spike done. Rendering the pipeline for each causality was pretty easy to do and felt pretty useful. It was fun to watch a live pipeline, as well.

**Comment by marco-m** [comment]
Adding a comment here to help searches: this is similar to GoCD value stream map (https://docs.gocd.org/current/navigation/value_stream_map.html)
