### ISSUE TITLE
Dashboard view reorders pipelines on auto-update

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1539]
Pipeline Dashboard view reorders pipelines on auto-update. This can be reproduced on 3.4.1 on [ci.concourse.ci/dashboard](https://ci.concourse.ci/dashboard)

Steps to Reproduce
1. Load up [https://ci.concourse.ci/dashboard](https://ci.concourse.ci/dashboard)
2. Keep an eye on the `web-development` pipeline (which was green) and `hanger` which is paused
3. Wait a while

Expected results
The pipelines shouldn't reorder

Actual Results
The pipelines switch back and forth over time

**Comment by mhuangpivotal** [comment]
Fixed in #1553.

**Comment by jama-pivotal** [comment]
Stared at our ci dashboard for a while, doesnt seem to be swapping around like it used to. Closing

**Comment by mhuangpivotal** [comment]
Reopening since it is still happening now that we are not sorting by status.

**Comment by jama-pivotal** [comment]
Kept staring at it after the fix, looks fixed
