### ISSUE TITLE
[metrics] Prometheus support ?

### ISSUE THREAD

**Issue by talset** [concourse/concourse#1540]
Hi!

We have few concourse (v3.2.1) running on kubernetes and we often have the "stuck in pending" issue (https://github.com/concourse/concourse/issues/844).

We would like to debug the issue via metrics provided by concourse. Currently there is no support for prometheus.

Referencing to : https://github.com/concourse/concourse/issues/1138#issuecomment-300411139
I would like to know if you plan to support prometheus metrics ?

**Comment by vito** [comment]
If someone PRs it we'd be happy to merge, but we don't have the bandwidth for it ourselves.

**Comment by talset** [comment]
Regarding the implementation, do you think it is possible to define a /metrics in order to keep the prometheus pull design or do you prefer to try to use pushing (https://prometheus.io/docs/instrumenting/pushing/) method ?

I think it would depend of the metrics we want to expose and from which component.

**Comment by ebabani** [comment]
@talset Was also looking at this recently. It most likely should be a pull method. Pushing is mostly used for tasks that are not long lived and want to report their metrics. 

Concourse web and workers run continuously so they should just expose their metrics and let prometheus scrape them.

**Comment by ebabani** [comment]
@talset This might not be needed anymore.

https://www.influxdata.com/blog/influxdb-now-supports-prometheus-remote-read-write-natively/

**Comment by talset** [comment]
@ebabani you are right on the fact we might be able to use influxdb format to get the metrics.
Instead of having influxdb server and prometheus to remote read, we might be able to use the prometheus [influxdb_exporter](https://github.com/prometheus/influxdb_exporter).

I will try to validate it. If it works we could agree if we want to expose prometheus metrics natively or via an exporter.

**Comment by talset** [comment]
I can confirm that the influxdb_exporter works. Concourse is able to send metrics to the exporter, and prometheus can pull the metrics via the exporter.

So currently we can use this exporter to have metrics into prometheus.

**Comment by vito** [comment]
@TimSimmons https://github.com/concourse/atc/pull/216 adds the start of this, but it only has metrics for build stats. It should be easy for others to add the other metrics though!

**Comment by marco-m** [comment]
hello any news ?

**Comment by jama-pivotal** [comment]
There's been a whole bunch of prometheus metric emission improvements and PRs since this was last commented on, see https://github.com/concourse/atc/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+prometheus

I would say its safe to close this issue given that the community has PR'ed in the ability to emit to Prometheus starting with 3.7.0 and gets a PR every few weeks.

But then again, feel free to re-open if you think i closed this issue in error
