### ISSUE TITLE
How does someone test their changes on the `time` resource?

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1544]

**Comment by jtarchie** [comment]
Our first approach was changing the time resource to use alpine linux. Peeps should be able to build the docker image locally now.

**Comment by jama-pivotal** [comment]
* Give contributors the ability to test their changes locally 
* Make the tests run against the image, so that it is as close as possible to the running state 
* Make some instructions on the `time` resource `README.md` to explain what the expectations are regarding writing and running tests before making a PR

Why Alpine?
1. Switching over to Alpine will give contributors the ability to test their changes locally 
2. Better understanding of what's packaged into the image
