### ISSUE TITLE
Race condition with resource availability?

### ISSUE THREAD

**Issue by msarahan** [concourse/concourse#1546]
I've created some custom resources for rsync and our package manager, conda.  With these resources, I have a pipeline that gets packages from the rsync resource, and then the package manager resource is used to upload the packages.

There's a get task on the rsync resource, and a put task on the package manager resource.

The command for that put task is:

``anaconda --token ${TOKEN} upload --force $(find . -type f -iname *.tar.bz2)  1>&2``

That fails - the evaluation of the find command comes up with nothing.  If I log into the container with ``intercept``, and re-run that command, it finds the many files in the rsync'ed folder and runs successfully.  Is there any time delay I should be considering?  Any other reason why the rsync resource wouldn't be showing up when running non-interactively?

Concourse version is 3.3.0

**Comment by vito** [comment]
There should be no delay.

To confirm, this fails with a `put`? Are you making sure the `put` is respecting its first argument, which is the location in which to run?

There may be a discrepancy between the `intercept`'d workdir and the workdir for the `out` script. The first argument is the source of truth.

**Comment by msarahan** [comment]
Thanks @vito, the put was not respecting the first argument.  Sorry for the noise.

**Comment by vito** [comment]
No problem!
