### ISSUE TITLE
Linux 32-bit worker or directly running jobs on linux workers

### ISSUE THREAD

**Issue by msarahan** [concourse/concourse#1547]
# Feature Request

## What challenge are you facing?

We have need of 32-bit linux for building software.  We have tried to emulate 32-bit as much as we possibly can with a docker image, but it does not seem possible to reach a complete solution.  We would like to be able to run concourse on "bare metal" Linux hosts - concourse workers that do not spawn containers, but instead perform builds directly on the machine running the concourse worker.

## A Modest Proposal

When the connector section is not present on Linux, make Linux behave like Windows and Mac do - run the task on the server that is running the worker process.

We will also eventually be expanding to PowerPC and ARM architectures.  While we can probably cross-compile for those, it will be extremely helpful to run on native hardware for testing and verification.  The PowerPC and ARM platforms that we target probably will not support docker, but are running linux.

**Comment by jtarchie** [comment]
[houdini](https://github.com/vito/houdini) provides a no-op garden interface. It should work, but I don't know if it has been tested on 32-bit mode.

**Comment by msarahan** [comment]
Thanks. Do you know if this blog post is the best info on how to install Houdini, currently? http://younata.github.io/2016/11/08/concourse-mac-worker/

Obviously I'll need to figure out how to adapt it for Linux. Still, thanks for the pointer.

**Comment by msarahan** [comment]
@jtarchie I have Houdini running, but I can't seem to register it.

The worker is on my local network (same subnet), so I'm trying to use register-worker.

my ssh command is: 

```
ssh -p 2222 remote-concourse-server \
    -i automated-build/concourse-worker/worker_key \
    -o UserKnownHostsFile=automated-build/concourse-worker/tsa_host_key.pub \
    register-worker < worker.json
```

worker.json has:

```
{ "name": "centos6x32",
"platform": "linux32",
"addr": "remote-concourse-server:7777",
"baggageclaim_url": "remote-concourse-server:7788"
 }
```

In both instances, remote-concourse-server is my remote host, running the concourse linux-64 binary as the server.

I have houdini running:
```
{"timestamp":"1504281256.837133408","source":"houdini","message":"houdini.started","log_level":1,"data":{"addr":"0.0.0.0:7777","network":"tcp"}}
```

I'm confused about the baggageclaim and garden servers - are these separate programs that I should be installing and running on the worker?  It seems like the concourse binary wraps all of these in a nice package, but I'm not clear on how to achieve a functional worker with the individual components.  Are there any good examples of doing this that you can point me to?

**Comment by msarahan** [comment]
This suggests to me that I'm missing baggageclaim:

```
{"timestamp":"1504289084.710243940","source":"tsa","message":"tsa.connection.channel.forward-worker.register.failed-to-list-volumes","log_level":2,"data":{"error":"Get localhost:7788/volumes: unsupported protocol scheme \"localhost\"","remote":"192.168.35.120:49112","session":"86.2.1.8"}}
{"timestamp":"1504289084.710454226","source":"tsa","message":"tsa.connection.channel.forward-worker.register.failed-to-reach-worker","log_level":1,"data":{"baggageclaim-took":"234.109µs","garden-took":"2.895221ms","remote":"192.168.35.120:49112","session":"86.2.1.8"}}
```

but I'm lost on how to fulfill that server.  Do I need to compile my own baggageclaim executable from code at https://github.com/concourse/baggageclaim ?  The garden response time seems appropriate for a LAN, and might be working.

**Comment by msarahan** [comment]
One of my colleagues, @nehaljwani, has compiled a baggageclaim binary.  His build steps are at https://gist.github.com/msarahan/6a0e646429919ddf22d4e4e04dd9d0a3

With that, I'm now able to register my linux-32 worker!  I'm excited.  I'm concerned, though, that my worker is showing up under this heading:

```
the following workers need to be updated to version 1.1:

name        containers  platform  tags  team  state    version
centos6x32  0           linux32   none  none  running  none
```

Is that going to make anything not work?  If so, how can I update this?  I guess Houdini needs to be updated?

**Comment by msarahan** [comment]
Update: seems not to work.  Although my worker shows up in fly ws, it is not usable:

```
no workers satisfying: platform 'linux32'

available workers: 
  - platform 'windows'
  - platform 'darwin'
  - platform 'windows'
  - platform 'darwin'
  - platform 'windows'
  - platform 'linux'
  - platform 'linux'
```

**Comment by msarahan** [comment]
Found it.  Only needed to put "version": "1.1" in worker.json.

Closing this issue.  I'll try to write a blog post on how to do all this for posterity's sake.  If it would make more sense to try to submit a docs PR, I can do that too.  Let me know what you'd prefer.

**Comment by jviotti** [comment]
@msarahan Did you end up posting some instructions on how to configure Houdini? I'm trying to do so, but instructions are not very user friendly.

**Comment by msarahan** [comment]
worker.json looks like this for us:

```
{
 "name": "centos6x32",
 "platform": "linux32",
 "version": "1.2"
}
```

Our startup script looks like:

```
#!/bin/bash
export PATH=/opt/conda/bin:$PATH

nohup ./houdini -depot=./containers -listenAddr=0.0.0.0:9999 -debugListenPort=9998 &
nohup ./baggageclaim --driver=naive --volumes=./volumes --bind-port=9988 --log-level=debug &
nohup ./ssh-tunnel.sh &
```

our ssh tunnel script looks like:

```
#!/bin/sh
ssh -p 2222 <concourse web server> \
    -i automated-build/concourse-worker/worker_key \
    -o UserKnownHostsFile=automated-build/concourse-worker/tsa_host_key.pub \
    -R 0.0.0.0:9999:127.0.0.1:9999 \
    -R 0.0.0.0:9988:127.0.0.1:9988 \
    forward-worker  \
      --garden 0.0.0.0:9999 \
      --baggageclaim 0.0.0.0:9988 \
    < worker.json
```
