### ISSUE TITLE
PUT step stalls indefinitly on docker container creation/upload

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1548]
# Bug Report

Bug reports are pretty free-form; just replace this with whatever. If applicable, though, please include steps to reproduce. Help us help you!

The following can also be handy:

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS: VPS, local machine
* Browser (if applicable): firefox
* Did this used to work? yes

I killed them manually. Stalled for 7 hours in the PUT step uploading the image to quay.io.
 
Concourse web:
https://ci.spearow.io/teams/spearow/pipelines/juice-containers/jobs/build-fedora-native

Job description:
https://github.com/spearow/continuous-integration/blob/master/juice-containers.yml#L111-L141

**Comment by topherbullock** [comment]
@drahnr Does this occasionally happen, or is this something which consistently happens against quay.io?

**Comment by drahnr** [comment]
It always happened occasionally which was the motivation to move image generation back to quay.io.
It also does not happen for smaller images with smaller layers that often, but the larger and the more layers an image has (either of them), the more often I see this happening.

**Comment by drahnr** [comment]
See https://github.com/concourse/docker-image-resource/pull/144 this can probably be closed, there is another ticket in *docker-image-resource* convering the issue.

**Comment by gabro** [comment]
I'm seeing this issue too. We have a pipeline that currently has somewhere around 20 jobs stuck in the PUT step of Docker.

![image](https://user-images.githubusercontent.com/691940/30962369-bf64668a-a449-11e7-8459-0f47d0a96b34.png)

The job is yellow, the `build` step has finished successfully and the docker step is not starting. 

@drahnr can you elaborate how concourse/docker-image-resource#144 relates to this issue?

**Comment by drahnr** [comment]
In my investigation I figured out that this is a bug in docker, which starves some threads while uploading and thus timeouting. Reducing the number of threads to `1` made this problem disappear (since there are not network connections/threads the first connection can actually starve). I also filed a ticket against the the docker image resource detailsing this problem as I just did here.
