### ISSUE TITLE
--garden-log-level being ignored for worker heartbeat messages?

### ISSUE THREAD

**Issue by jeroenjacobs1205** [concourse/concourse#1549]
# Bug Report

I'm starting Concourse worker with the following parameter included:

--garden-log-level error

However, my logs still lots of entries like these:

{"timestamp":"1504261909.039619684","source":"tsa","message":"tsa.connection.channel.forward-worker.heartbeat.start","log_level":1,"data":{"remote":"192.168.120.137:9800","session":"2.1.1.3001","worker-address":"127.0.0.1:11013","worker-platform":"linux","worker-tags":""}}

This doesn't seem like an error and shouldn't be included when the log level is set to "errror"

The following can also be handy:

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: vSphere/CentOS7
* Browser (if applicable): NA
* Did this used to work? No idea

**Comment by shashwathi** [comment]
@jeroenjacobs1205 : Concourse worker currently does not take any flags to set log level. So `--garden-log-level error` will not have any impact. 

We could add `--log-level` flag to worker to enable more control for user on logs.

**Comment by shashwathi** [comment]
This change will be present in future versions of concourse binary. `--log-level` will be the flag to use for controlling log level binaries.
