### ISSUE TITLE
Show pipeline even if group in URL does not exist

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#155]
If you try to hit a pipeline page and there's groups in the URL that don't exist, it shows nothing (e.g. `http://my-concourse.ci/pipelines/a-pipeline?groups=noexist`)

Also tested to see if it's just query params in general that fail (`http://my-concourse.ci/pipelines/a-pipeline?something=else`) but it succeeds in showing the pipeline.

**Comment by vito** [comment]
Showing things when requesting only an invalid group is imo more confusing than showing nothing. If you do `?groups=some-valid-group&groups=some-invalid-group` it'll do a set union of the given groups. If you requested entirely invalid groups I'd expect to see nothing.
