### ISSUE TITLE
failed to find created volume in baggageclaim

### ISSUE THREAD

**Issue by aminotsukasa** [concourse/concourse#1550]
Bug Report

When executing task . garden can't find start volume 
$ fly -t lite execute -c hello.yml
platform: linux
image_resource:
type: docker-image
source:
repository: alpine
run:
path: echo
args: ["Hello", "World"]

initializing
failed to find created volume in baggageclaim. Volume handle: 6c6015e3-668d-4f36-5398-563fa42fdefb
errored

Web and worker are working on same host.this is a worker daemon command line
/usr/local/concourse/concourse worker --work-dir /usr/local/concourse/work --tsa-host localhost --tsa-public-key /usr/local/concourse/host_key.pub --tsa-worker-private-key /usr/local/concourse/worker_key

The following can also be handy:

Concourse version: 3.3.4
Deployment type (binary):
Infrastructure/IaaS: aws t2.medium Ubuntu 16.04
Browser (if applicable): Chrome
Did this used to work? yes

After I restart this host and prune worker.but It's not worked.
What a reason?

**Comment by topherbullock** [comment]
When the worker comes back up, I'm thinking it is registering with the same worker name, and the ATC tries to find a volume on the "same" worker it had previously been using to store containers and volumes to run the task config provided.

There's a couple existing issues which cover improving this behavior:
#1458 
#755

In the meantime, I'd suggest using the `concourse land-worker` command if you know the host running the worker is going down, but coming back up with the same name, or `concourse retire-worker` if the name is different between restarts.
