### ISSUE TITLE
Feature request: Fly CLI to support go-patch for pipeline yaml patching

### ISSUE THREAD

**Issue by bsnchan** [concourse/concourse#1552]
# Feature Request

## What challenge are you facing?

Maintaining multiple versions of a pipeline yaml when for different product versions is cumbersome since a lot of the core pipeline content is mostly (minus a few additions and removals here and there). 

We are currently using Concourse's [parameters](http://concourse.ci/single-page.html#parameters) feature to template our pipeline but it can get a little gross when adding/removing resources or tasks in "newer" versions of the pipeline.

We would prefer not to branch the pipeline since the this means our team would need to get into branch management/cherry picking commits.

## A Modest Proposal

Fly CLI to support [go-patch](https://github.com/cppforlife/go-patch/blob/master/docs/examples.md) for pipeline yaml patching (similar to bosh's ops files) so developers can easily template pipelines for different product versions.

**Comment by vito** [comment]
Sorry but I don't want us to do this. Today people use `go-patch`; before that, people used Spruce; before that, people used Spiff; before that, people used ERB, etc. etc. etc.

It's not our place to pick a templating tool. Fly should just accept YAML, and allow `((parameters))` as a simple/intentionally limited/weak solution (vs. full templating) to credential management and simple value insertion. Beyond that, you're free to use whatever templating toolchain you like before the YAML gets passed on to `fly`. Maybe what's really missing is a generic `go-patch` CLI?
