### ISSUE TITLE
[Multi-Pipeline View] URL Link anchors on team names

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1554]
As a team on a multi-tenant Concourse, I'd want an anchor link on a dashboard so that I can jump straight to my team's pipelines on the dashboard view

**Given** That I am on team `main`
**When** I go to `dashboard#main`
**Then** I should be taken to the multi-pipeline dashboard scrolled to the `main` team

**Comment by mhuangpivotal** [comment]
The anchor links work once the page is fully loaded.

Visiting an anchor link directly does not work since the page content is dynamically loaded in. This could be a separate issue.

**Comment by jama-pivotal** [comment]
Its wonkey, it kinda works, but hey I'm gonna accept and close this for now. We're going to want a better way to directly link to JUST view a team's pipelines

**Comment by vito** [comment]
FYI: I'm not sure this ever worked actually; anchor links usually target `<a name="xyz"></a>` elements, not IDs. 

Also changing the URL to have `#foo` at the end now reloads the page, probably because we needed to actually route by URL fragments in order to implement the line selecting feature.
