### ISSUE TITLE
Bug report: Multiple emitters are silently ignored

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#1557]
# Bug Report

If the ATC is configured to run multiple emitters (for example, if the user sets `--emit-to-logs` and `--influxdb-url`), only one will actually run. The `metric` initializer iterates over all registered emitters, then picks the last one: https://github.com/concourse/atc/blob/master/metric/emit.go#L65-L72.

Two straightforward options for fixing this:

* Error if multiple emitters are configured
* Support multiple emitters

I'd be happy to take a crack at either solution. Let me know what the correct behavior is!

**Comment by jtarchie** [comment]
Isn't that pretty standard with most CLI options? Unless explicitly stated in `--help` that it accepts multiple options. Do we error anywhere else when multiple configurations are provided for a singular value?

**Comment by jmcarp** [comment]
Not sure what you mean @jtarchie; different emitters are configured by different CLI flags, so I'm not talking about a single flag taking multiple options.

Influxdb: https://github.com/concourse/atc/blob/master/metric/emitter/influxdb.go#L18
Riemann: https://github.com/concourse/atc/blob/master/metric/emitter/riemann.go#L21
Lager: https://github.com/concourse/atc/blob/master/metric/emitter/lager.go#L13

**Comment by jtarchie** [comment]
Sorry. This is what happens after a holiday weekend and no coffee! 😃 

I'm caught up now!

The most straight forward would be to error or at least have a helpful warning. Until someone really needs support for multiple emitters.
