### ISSUE TITLE
Only permit certain teams to run privileged builds based on a flag

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#1558]
# Feature Request

From http://concourse.ci/single-page.html#section_teams-caveats:

> In the future, we'll probably have this as a flag on a team, indicating whether they're permitted to run privileged builds.

This would be a useful feature for https://github.com/18F/concourse-broker. I started looking into this in https://github.com/concourse/atc/pull/150 but didn't have time to finish--I'd be happy to try again (and finish this time) if you're interested in the feature. Which I infer from the documentation that you are 😃.

**Comment by vito** [comment]
Yep, still interested!

**Comment by topherbullock** [comment]
Renaming this and adding it to our backlog

**Comment by cirocosta** [comment]
This seems like a use case for https://github.com/concourse/rfcs/pull/41

**Comment by xtremerui** [comment]
closing stale issue.
