### ISSUE TITLE
Serial builds cancel previous builds

### ISSUE THREAD

**Issue by crmitchelmore** [concourse/concourse#1560]
# Feature Request

## What challenge are you facing?

We're using Concourse for all of our iOS build projects and I appreciate that it's not the primary use case so this might not be relevant enough to consider. But..

The problem I have is: when we merge PRs in to develop there's a serial pipeline that builds for our alpha deployment channel. As part of the job, the build number is bumped and pushed back to develop if the build is successful. The problem is if multiple PRs are merged within the same window (our builds can take 30 mins) then the builds fail because we can't push changes over a modified develop. 

It would be nice if I could automate the process of cancelling all but the last build when multiple merges happen.

I'm aware that it's possible a bad build could happen in the middle and break things.

**Comment by jtarchie** [comment]
This is what serial is meant to prevent. When `serial` is set, it holds a job as pending until the previous job finishes. That pending build will then be scheduled with the latest versions of all the resource inputs.

If you are having problems over a modified build, have you tried rebasing on top of that build before you commit?

**Comment by crmitchelmore** [comment]
Build 1 checks out develop
Build 2 gets merged to develop before build 1 finishes
Build 1 commits version bump and pushes but fails because there's new commits

So I could try a pull and fast forward like you suggest. Would end up with the version bump in the wrong place but it's not that much worse than cancelling I guess. 

Now, I'm thinking that it's probably a good idea for us to abide by the existing behaviour and have the version bump happen as part of the pr somehow.

Thanks. I'll close the ticket.
