### ISSUE TITLE
Fly set-pipeline-ordering command

### ISSUE THREAD

**Issue by alext** [concourse/concourse#1561]
# Feature Request

## What challenge are you facing?

We automate the creation of our concourse instances, and push several pipelines to them. We'd like a means to set the pipeline ordering so that we can control which pipeline is shown by default.

## A Modest Proposal

I therefore propose adding a `set-pipeline-ordering` command to `fly` to achieve this.

At present we're having to work around this with a script that does a PUT to the `/api/v1/teams/<teamname>/pipelines/ordering` endpoint using creds read out of the `.flyrc` file, and a comma-separated list of pipeline names.

**Comment by shashwathi** [comment]
`feature/order-pipelines` branch on `fly` and `gp-concourse` contains the feature.

**Comment by shashwathi** [comment]
While testing the CLI feature I just realized that  API does not throw an error if one or more pipelines does not exist.

@vito @pivotal-jwinters : Is this desired behaviour?

**Comment by shashwathi** [comment]
I will update the API behavior and add `fly` command.
