### ISSUE TITLE
3.4.x can't run on CentOS7, occur “Segmentation fault (core dumped)“

### ISSUE THREAD

**Issue by lichengbang** [concourse/concourse#1568]
When I upgrade from `3.3.4` to `3.4.x`，run any concourse command always prompt `Segmentation fault (core dumped)` in command line，my OS is CentOS7，kernel version is `4.11.3-1.el7.elrepo.x86_64`.
But before 3.4.x everything is OK.

**Comment by k0nstantinv** [comment]
@lichengbang could you explain kernel vesion ```4.11.3-1.el7.elrepo.x86_64``` is the kernel version of what? ATC? Workers?

**Comment by lichengbang** [comment]
@k0nstantinv  both ATC and workers are run on CentOS 7 which linux kernel version is`4.11.3-1.el7.elrepo.x86_64`

**Comment by xtremerui** [comment]
closing outdated issue.
