### ISSUE TITLE
Don't re-run all Tasks when re-running a Job

### ISSUE THREAD

**Issue by kavinderd** [concourse/concourse#157]
As discussed on the slack channel last week. A performance improvement that would be really nice is if tasks within a job could be cached. So if I make a change to something affecting Task 3 in Job A, Task 1 & 2 don't need to be re-run. A lot of our jobs involve making a docker image, then testing some property of it and then pushing it somewhere, and we're usually only iterating on the second half of our tasks.

**Comment by jvshahid** [comment]
I really like this idea. I think this should be an optional config option per task. This will avoid having concourse understand how the task script run, for example if it depends on current time or external services.

**Comment by vito** [comment]
This is much more doable/useful with the new container retention semantics, wherein all containers for a failed build are kept as long as it's the current build.

**Comment by vito** [comment]
I don't see us targeting this feature in the forseeable future, but if someone wants to chime in with more details in a new proposal, feel free. This sounds like a "nice to have" but the devil will be in the details.
