### ISSUE TITLE
Hello-world documentation doesn't work with docker-compose

### ISSUE THREAD

**Issue by sean-abbott** [concourse/concourse#1570]
# Bug Report

The following can also be handy:

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): docker-compose

You can't use docker-compose with hello-world unless you've got docker-in-docker working, which I'm guessing most folks don't.

Also, there is a zero percent chance I'm going to install bosh-lite just to spike concourse. Vagrant would have a much broader install base.  I'm trying some person's vagrant version of it, but the vagrant boxes are a few versions behind.

**Comment by jtarchie** [comment]
@sean-abbott, thanks for feedback. It is not clear what error you are experiencing. I'm able to follow the docker-compose instructions without using a docker-in-docker.

As for the vagrant boxes, their maintenance cost was becoming to much. The new [concourse-lite](http://concourse.ci/concourse-lite.html) is supposed to one command.

**Comment by jtarchie** [comment]
@sean-abbott, I'm going to close this as there's nothing actionable. Please ask for help in our slack room if you have any issues with the docker-compose or concourse-lite. Cheers!
