### ISSUE TITLE
Concourse Lite 3.4.1 has no internet access

### ISSUE THREAD

**Issue by thardeck** [concourse/concourse#1572]
Concourse Lite Version: 3.4.1
Bosh version: 2.0.33
Virtualbox: 5.1.26
OS: OpenSUSE Leap 42.3

I have downloaded the concourse-lite.yml from the 3.4.1 release on Github and ran `bosh2 create-env ~/Downloads/concourse-lite.yml`.

The instances comes up fine and I can connect via `http://192.168.100.4:8080` but getting the pipeline resources fails because Concourse can not resolve the ip of github.com.

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/SUSE/bosh-linux-stemcell-builder-ci.git/': Couldn't resolve host 'github.com'
```

I have no access to the Concourse vm but when I intercept the resource check with fly I am even unable to ping the ip of the Google DNS so it seems that the Virtualbox vm does not have Internet access.

When I import with vagrant the old Concourse Lite 3.2.1 in the same Virtualbox Internet access works.

Please let me know how I can further debug it.

**Comment by vito** [comment]
Could you try going in to the VirtualBox settings and clearing out all the NAT networks and host-only networks and try again? Maybe there's some old state getting in the way?

<img width="662" alt="screen shot 2017-09-08 at 9 20 39 am" src="https://user-images.githubusercontent.com/1880/30213450-0e4fce66-9477-11e7-910a-776939cf9f01.png">
<img width="662" alt="screen shot 2017-09-08 at 9 20 43 am" src="https://user-images.githubusercontent.com/1880/30213449-0e4b6fc4-9477-11e7-9d67-16aaf7c9372b.png">

**Comment by thardeck** [comment]
@vito I have removed all network interfaces, removed the state.json and ran create-env again but the Internet connection still does not work.

**Comment by thardeck** [comment]
Thanks to @mauromorales I was able to get the Internet connection working.

It seems that the networks are named differently between Linux and Mac. This is the fix:

```
--- concourse-lite.yml  2017-09-18 10:03:38.302426720 +0200
+++ concourse-lite-linux.yml    2017-09-15 14:16:20.460775751 +0200
@@ -86,7 +86,7 @@
   type: manual
 - cloud_properties:
     name: outbound
-    type: natnetwork
+    type: nat
   name: outbound
   type: dynamic
 releases:
```

**Comment by vito** [comment]
@thardeck Just tried on Linux and it worked fine as `natnetwork`.

```
~/workspace $ VBoxManage --version
5.1.28r117968
```

I ran the `hello-world` pipeline from https://concourse.ci, which downloaded an image from Docker Hub and passed.

**Comment by thardeck** [comment]
@vito Did you use an upstream VirtualBox package or a distribution one? Maybe it is just an openSUSE issue.

Would using `nat` instead of `natnetwork` work for your Linux distribution and Mac too?

**Comment by thardeck** [comment]
I have tried it with the upstream version on openSUSE and there the issue does not appear so I am closing the issue and will report it there.

Thanks for the help in debugging it.

**Comment by vito** [comment]
Thanks for following up!
