### ISSUE TITLE
concourse.ci quickstart guide needs updating

### ISSUE THREAD

**Issue by davidje13** [concourse/concourse#1574]
The "Getting Started Takes 5 Minutes" guide on concourse.ci could do with some updates since the old concourse-lite is gone, and a new bosh-based deployment is used:

* There is no mention of the need to download `fly` from the concourse web interface. This will leave people stuck on step 3 wondering where to get `fly` from.
* The first step certainly takes a *lot* more than 3 minutes now! The installation process is closer to 10 minutes in my experience, due to the amount of stuff it downloads and compiles on first run. A warm start (with the environment deleted but all initial files already downloaded) took 6 minutes when I timed it.
* There's no mention of what to do to *restart* the concourse installation after restarting the machine (something I'm not entirely sure of myself; the best I've found is to delete the `concourse-lite-state.json` file and rebuild from scratch, but I'm sure there's a better way.
* `wget` is not installed on OSX by default; might be better to provide an example command which uses `curl` instead (yes it's not as clean but it will work out-of-the-box for more people):

  ```
  curl -L https://github.com/concourse/concourse/releases/download/v3.4.1/concourse-lite.yml > concourse-lite.yml
  ```

**Comment by penmanglewood** [comment]
And on a slight tangent, since bosh is involved now, after running `bosh create-env concourse-lite.yml`, out of curiosity I run `bosh envs` and get the following result.

```
$ bosh environments
URL  Alias

0 environments

Succeeded
```

Concourse is still running and works properly though, but the bosh cli isn't aware of it.

**Comment by jama-pivotal** [comment]
Quickstart no longer makes any bold claims about getting started in 5 minutes!
