### ISSUE TITLE
Shared resources for newly created pipelines do not show up 

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#1577]
# Bug Report

Sometimes a new pipeline will seem hanging. The reason seems to be shared resources with already running pipelines with longer `check-every` interval. For such, it seems that bootstrap pipeline process simply discovers that they are already in the system and does nothing. Depending on the `check-every` interval this could be very unpleasant, but also it is unexpected ... it took me a while to figure out what is going on.

# Modest proposal

Maybe the new pipeline should trigger check for every resource involved at least once, even the shared ones ... or should simply apply the last version for the resource to the new pipeline as well.

**Comment by ggeorgiev** [comment]
I just noticed that this is true for time resources as well.

**Comment by jtarchie** [comment]
Not sure I follow. Do you have a reproducible pipeline to show the error?

**Comment by ggeorgiev** [comment]
To reproduce the issue create a pipeline that has a resource with significant `check_every`, say something like:

```
resources:
- name: 12h_time
  type: time
  source:
    interval: 12h0m0s
  check_every: 12h0m0s
jobs:
- name: foo
  plan:
  - get: 12h_time
    trigger: true
...
```
Deploy this pipeline and wait for a while the resources to get checked at least once.

Now deploy the same pipeline with a different name ... this will make the resource shared because it is the same. You will notice that the second pipeline will not start running some of the jobs for no obvious reason. If you open the resource though it will be checked, with no version.

this is a screenshot of pipeline in such state:

![image](https://user-images.githubusercontent.com/1084892/30236992-98770220-94dc-11e7-9d77-2d813b150b5c.png)

because the time resource shows no version:

<img width="792" alt="screen shot 2017-09-08 at 9 29 18 pm" src="https://user-images.githubusercontent.com/1084892/30237001-e5406b6e-94dc-11e7-987e-6728f54629b8.png">

**Comment by jtarchie** [comment]
@ggeorgiev this issue actually exists on resourced on the same pipeline and different pipelines. It is not a _bug_ as we haven't implemented this as a optimization yet. We have an issue though -- https://github.com/concourse/concourse/issues/1256. 

Thanks for bringing it up. If you could follow #1256 that would be great. Thanks.
