### ISSUE TITLE
`on_failure` on job-level leads to a lot of repetition

### ISSUE THREAD

**Issue by petergtz** [concourse/concourse#1583]
# Feature Request

## What challenge are you facing?

When a job in a pipeline fails, we can use `on_failure` to inform the owner of the pipeline. However, as https://github.com/concourse/concourse/issues/1052 already describes, this requires a lot of copy-pasting of code and clutters the pipeline yaml. Also, it's easy to forget when adding new jobs. https://github.com/concourse/concourse/issues/1052 proposes to solve this by introducing decorators. However, this still requires copy-pasting code and is still prone to be forgotten when adding new jobs.

## A Modest Proposal

While the proposal in https://github.com/concourse/concourse/issues/1052 would reduce the boilerplate, with a global fail handler we could reduce the repetition even further.

An `on_failure` on top level would avoid to reference a decorator in each job and would clearly communicate the intent of defining a common action to run when something in the pipeline goes wrong. Furthermore, it could even live alongside the proposal in https://github.com/concourse/concourse/issues/1052.

Just as https://github.com/concourse/concourse/issues/1052 suggests, the UI could also introduce a better visualization for a global `on_failure`.

**Comment by vito** [comment]
I'd like to peel back a layer here and know what you're trying to do with `on_failure`. If it's notifications, I'd rather stick to discussing proposals in #1052 and maybe just remove the original proposal so it's a more open discussion.

**Comment by petergtz** [comment]
@vito Yes, it's notifications. Just like #1052 and #462 I'd like to get one step closer to notifying the right person after a failed build. And it seems to be such a standard feature of a pipeline that we should somehow make it as simple as possible. Right now I feel like a lot of people have to reinvent the wheel on this one.

That said, I'm perfectly fine closing this one in favor of #1052. In that case, would you mind adjusting the challenge faced to include something that roughly resembles what I tried  to describe in the previous paragraph and what #462 describes? I've opened this one, because I thought #1052 was much more focused on the concept of decorators instead of notifications.

**Comment by vito** [comment]
I'm gonna close all these notification-related issues to corral context into concourse/rfcs#10. The information here will be kept in mind when it comes to authoring the RFC. Thanks!
