### ISSUE TITLE
Resources should error if underlying targets aren't available

### ISSUE THREAD

**Issue by kavinderd** [concourse/concourse#159]
This is an enhancement request. It would be very helpful if when running a pipeline resources would error, show red, and block related jobs from starting in the case that the target resources (e.g. files in git) aren't available. Please advise if there is some existing way to do this.

**Comment by vito** [comment]
This should happen already if the resource is misconfigured: the resource box will be orange, `stderr` will show up on the resource's page, and any jobs depending on it won't be able to schedule.

Do you mean when no versions can be detected? What's the behavior you're seeing today?

**Comment by kavinderd** [comment]
I think we were mistaken in our use of concourse. What you described is correctly working on our end. Feel free to close this issue.

**Comment by kavinderd** [comment]
Closing Issue

**Comment by vito** [comment]
Cool, thanks for following up on it!
