### ISSUE TITLE
Possible Missing Property in ATC spec file causing Vault TLS integration to fail

### ISSUE THREAD

**Issue by mminges** [concourse/concourse#1591]
Vault integration with Concourse fails when configuring Vault's TLS certs and keys.

I believe the spec file for the `atc` job is missing a required property as shown below:
```
  vault.tls.client_cert:
    type: private_key
    description: |
      Client private key for Vault TLS auth.
```

The spec file references the following template: https://github.com/concourse/concourse/blob/master/jobs/atc/templates/vault_client_key.erb

which shows that the path `vault.tls.client_cert.private_key` should be defined, however, this is missing in the spec file.

The error that we get from a bosh deploy of concourse is:
```
Task 65 | 21:46:08 | Updating instance web: web/ae1caa0f-b8be-4f9c-8bb5-678fe759e019 (0) (canary) (00:01:37)
                   L Error: 'web/ae1caa0f-b8be-4f9c-8bb5-678fe759e019 (0)' is not running after update. Review logs for failed jobs: atc
```

After SSH'ing into the `web` VM and checking the logs under `/var/vcap/sys/log/atc/atc.stderr.log` we see the following:
```
tls: failed to find any PEM data in key input
```

We can also see that `vault_client_key` fails to get populated under `/var/vcap/jobs/atc/config/`, whereas both `vault_ca_cert` and `vault_client_cert` have been successfully populated as shown below:
```
web/ae1caa0f-b8be-4f9c-8bb5-678fe759e019:/var/vcap/jobs/atc/config$ ll
total 44
drwxr-xr-x 2 root root 4096 Sep 13 21:46 ./
drwxr-xr-x 5 root root 4096 Sep 13 21:46 ../
-r-------- 1 vcap vcap    1 Sep 13 21:46 cf_ca_cert
-r-------- 1 vcap vcap    1 Sep 13 21:46 postgres_ca_cert
-r-------- 1 vcap vcap    1 Sep 13 21:46 postgres_client_cert
-r-------- 1 vcap vcap    1 Sep 13 21:46 postgres_client_key
-rw-r--r-- 1 root root 1201 Sep 13 21:46 tls_cert
-rw-r--r-- 1 root root 1676 Sep 13 21:46 tls_key
-rw-r--r-- 1 root root 1144 Sep 13 21:46 vault_ca_cert
-rw-r--r-- 1 root root 1194 Sep 13 21:46 vault_client_cert
-rw-r--r-- 1 root root    1 Sep 13 21:46 vault_client_key
```

**Comment by mminges** [comment]
Including releases uploaded to the BOSH Director:
```
Name         Version  Commit Hash
concourse    3.4.1*   6491875
garden-runc  1.9.3*   55956f4
vault        0.6.2*   36e759d6+
```

**Comment by vito** [comment]
What version of the BOSH director? This looks correct; it's utilizing BOSH's recent support for typed release properties, typically satisfied by a [typed var](https://bosh.io/docs/variable-types.html). It looks like our type is incorrect though; it should probably be `rsa`, not `private_key`.

If you're specifying it manually without generated vars, you'd just put `private_key` under the property, like so:

```yaml
vault:
  tls:
    client_cert:
      private_key: # ...
```

**Comment by mminges** [comment]
Thanks for the response. We ended up missing a block style indicator, `|` for the `vault.tls.client_cert.private_key` which was causing our tls error: `tls: failed to find any PEM data in key input`.

This issue can be closed
