### ISSUE TITLE
Task and Job Disable Flag for Debug/Development

### ISSUE THREAD

**Issue by sabjorn** [concourse/concourse#1594]
# Feature Request
## Challenge
I find it can be cumbersome to isolate tasks when developing pipelines. The pipelines i've been developing often have a few heavy tasks which can stand in the way of quick development and debugging of tasks. Generally this results in commenting out the tasks and jobs which are not part of the current feature. This is especially cumbersome when having to reroute `input` and `output` directories.

## Proposal
A `disable flag` for jobs and tasks would be excellent. This would stand in place of having to comment out code.
Not so sure about input/output routing, although it is simple enough to just replace the directory names (but maybe there is clever solution).

**Comment by sabjorn** [comment]
Sorry for no label. Github won't give me any options for selecting a label.

**Comment by jtarchie** [comment]
This would be difficult, if you disabled a job that was a part of some non-linear topologies this would effect propagation. Even with topologies that depended on `outputs` of a previous job would have undefined behaviour.

What exactly do you mean *isolating tasks*? This seems to be your problem. Have you tried `fly execute`?

**Comment by sabjorn** [comment]
@jtarchie I have not tried `fly execute`. Thanks for the tip!

**Comment by sabjorn** [comment]
As for *isolating* tasks, I mean, sometimes I need to run a segment (several `tasks`) of the CI but don't want the a whole `job` (or series of jobs) to run. 

For example, I am currently augmenting a pipeline to have a task which is dependent on a git repo for its input. However, one task in the job is the compile step (which takes roughly 3 hours). Therefore, I will be commenting out this step (and subsequent steps) to test this step without triggering a 3 hours build.

Perhaps `fly execute` will be the solution to my woes.

**Comment by sabjorn** [comment]
@jtarchie Is it possible to load credentials when using `fly execute`?

**Comment by vito** [comment]
This sounds like https://github.com/concourse/concourse/issues/1346 - closing as a dupe.

@sabjorn Credentials will be loaded from a credential management service if configured in your task .yml - you can also set env vars to specify values for `params:` when running `fly execute`.
