### ISSUE TITLE
logout button is still showing after I am logged out

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1596]
# Bug Report

This is something we are observing on a monitor using the dashboard view.

24 hours after logging in to the `main` team with basic auth, our token expires, and we are logged out. This is fine and expected. However, the problem is that the upper right corner of the screen still shows us being logged in to our `main` team, and when we click it, the dropdown has a `logout` button. This is definitely wrong; we are no longer logged in. All of our private pipelines have disappeared from the  dashboard, and if we refresh the page it shows `login` appropriately.

When your token expires, the upper right hand corner of the screen should dynamically update to show a login button instead of the team and a logout button.

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Unknown

**Comment by andrewedstrom** [comment]
This is still broken as of 3.6.0

**Comment by jama-pivotal** [comment]
Repro'ed and validated using hte following strategy:
 
1) open one tab with `/beta/dashboard` 
2) Open another tab with main pipeline view
3) Login in either one of those tabs
4) Logout of your team on the pipeline view. the first tab with dashboard should update back to `login`

Sorry @andrewedstrom the login button won't work yet though :P
