### ISSUE TITLE
Make effort to be listed in awesome-go

### ISSUE THREAD

**Issue by sfrique** [concourse/concourse#1597]
Hello,

There is an list of curated go apps called awesome-go
https://github.com/avelino/awesome-go
https://awesome-go.com/

I've made a [PR](https://github.com/avelino/awesome-go/pull/1581) to awesome to try adding concourse to it but it seems there is a few changes to make it acceptable. 

Right now I don't have the time to try making  a PR with the changes asked. So if anyone have the time, it would be great to be listed there.

Thanks

**Comment by jama-pivotal** [comment]
🤔  @topherbullock recently did a war on linter errors on our codebase. Not sure if we're at the 100% mark yet, and tbh not sure if we have the desire to get up to 100% (its a lot of work)

**Comment by sfrique** [comment]
Great, I'm not sure if it need to be 100%

Either way I will check and try again when I have some time.

Thanks
