### ISSUE TITLE
x509: certificate signed by unknown authority error for valid certs

### ISSUE THREAD

**Issue by GarimaSharma** [concourse/concourse#1599]
# Bug Report

On runing
```
$ fly -t pcf-concourse login
logging in to team 'cloudops-eu'

could not reach the Concourse server called pcf-concourse:

    Get https://<redacted>/api/v1/info: x509: certificate signed by unknown authority

is the targeted Concourse running? better go catch it lol
```
Also, we are using a valid wildcard cert signed by DigiCert. 
I expect no error while trying to target. 

* Concourse version:
`3.3.3`
* Deployment type (BOSH/Docker/binary):
`Bosh`
* Infrastructure/IaaS:
`GCP`
* Browser (if applicable): 
`N/A`
* Did this used to work?: 
`Don't know`

**Comment by jtarchie** [comment]
@GarimaSharma if it is a valid wildcard cert it should work.

* Does your system have the valid ca-certs?
* Wildcard is only good for one level, not multi, so you can do `*.domain.com` not `*.*.domain.com`.
* Are you sure you applied the cert correctly to the load balancer appliance in front of your domain?

**Comment by vito** [comment]
There's not a lot we can do about this - if it doesn't allow the cert, it must either be invalid or may be misconfigured such that `fly` doesn't trust it. We know this works with our own valid certs.

One other thing to check: sometimes you have to configure the full chained cert on the server side.

**Comment by GarimaSharma** [comment]
@vito @jtarchie browsers are accepting the cert as valid so we feel that the configuration is valid. we are not sure why fly thinks it's invalid, any pointers on how to proceed? Thanks.

**Comment by PXMYH** [comment]
@GarimaSharma maybe you'll need to update the concourse server certification bundle, I had a similar issue (not quite since it's a self-signed cert), but the way to resolve it is to get the certification chain from browser and add it to concourse server.

One way to validate is to connect into concourse server and curl from there, you can use `curl --ca-cert` to provide extra certifications for validation.

**Comment by dhoffi** [comment]
running `bucc test` solved this for me
(root-cause was a teardown and fresh setup of concourse in my case)
