### ISSUE TITLE
Docker registry v2 support

### ISSUE THREAD

**Issue by bencalegari** [concourse/concourse#160]
HAWQ-toolsmiths team here: We're experiencing an issue with diego-docker-cache that requires we bump to a newer version, but any of the new versions that have our fix also bump to using the second version of the Docker Registry API. 

Whenever a job generates images and pushes them to our private docker-registry, the existing image does not get cleaned up and we are left with a duplicate image every time the bosh job runs `monit start docker`. `monit stop docker` isn't running `docker rmi` so if you run enough of the same job pushing the same image eventually you will run out of space. 

The [fix is here](https://github.com/cloudfoundry-incubator/diego-docker-cache-release/commit/4e7c077f951d916fa9b00c56a2af05b72ced403f) and we saw that you have a [story](https://www.pivotaltracker.com/n/projects/1059262/stories/100864902) in your icebox but we weren't sure what your priority was around it / whether or not we should spike on updating the API calls ourselves.

**Comment by vito** [comment]
Dragged in the story you linked; should be coming up soon. The `docker-image` resource definitely needs some love.
