### ISSUE TITLE
How to test `tracker resource`

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#1611]
When it comes to contributing to Concourse resources, our projects have a "testability" gap. While the community is more than open to making changes and tweaks to Concourse resources, it is very difficult to write tests for them. This story is an effort to 

1) make the `tracker-resource` resource more test-able
2) provide any resource-specific instructions (if applicable) to run and write tests

**Comment by jmelchio** [comment]
This integrates with a live tracker project. Running these tests within the docker image requires more work.
