### ISSUE TITLE
Postgres indexing error with large versions

### ISSUE THREAD

**Issue by lann** [concourse/concourse#1618]
Postgres indexes have a limit of 8191 bytes (apparently). If a `check` generates a version larger than this, atc fails with e.g.: `"error":"pq: index row requires 14544 bytes, maximum size is 8191"`. This could be fixed by indexing on a hash of the version.

**Comment by lann** [comment]
As a side note, this would have been easier to debug if the error had shown up in the UI on the resource page.

**Comment by marcbachmann** [comment]
I also just ran into this issue. At least it shows up in the ui by now.

**Comment by vito** [comment]
This should be fixed in v3.7.0. Can anyone confirm?
