### ISSUE TITLE
New color theme for multi-pipeline view

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1621]
New colour and new fonts for the multi-pipeline dashboard view.

![dashboard_legend_card_hover_01](https://user-images.githubusercontent.com/27746614/30700401-803522f4-9eb5-11e7-8632-8998f29148c2.png)

Background #333333
Card background #1D1C1C
Card hover: #181818

Green #1FCE6D
Red #ED4B35
Amber #F5A623
Blue:4A90E2

**Comment by pivotal-gabriel-dumitrescu** [comment]
updated colors ![screen shot 2017-09-21 at 5 01 37 pm](https://user-images.githubusercontent.com/9042962/30718663-9c79f582-9eee-11e7-9da4-24c9ff877a73.png)

**Comment by jama-pivotal** [comment]
Closing and accepting. HOWEVER, it is worth noting that there is some jankiness. The black background only appears for the top bit of the page, as you scroll you'll see the old blue re-appear. This is because of how the base styling is treated in the rest of the app. It will look weird like that until we completely change the background color and fonts
