### ISSUE TITLE
Feature: Show pipeline status in pipeline listing

### ISSUE THREAD

**Issue by wrast** [concourse/concourse#1627]
# Feature Request

## What challenge are you facing?

I'd like to know what the most recent status of my pipeline is without having to click on each pipeline in the left navigation. This makes it simple to see the status of all the pipelines at a glance.

## A Modest Proposal

Display an icon with the pipeline's status next to it's name in the listing. Started, Failed, Error, Aborted, etc should all be able to be represented.

**Comment by jtarchie** [comment]
@wrast that whole UI is being redone. #1462 for more details. I'm going to close this in favor of that. 👍

**Comment by wrast** [comment]
Thanks @jtarchie. Didn't see that. Looking forward to the new UI.
