### ISSUE TITLE
Hover state on jobs in multi-pipeline preview

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1630]
Now that we have pipeline visualizations for multi-pipeline dashboard, it would be nice to get a more obvious and immediate feedback on what job my mouse is hovering over.

Right now if you hover on a job it will eventually give you a tooltip with the job name

We should have a version of this that is faster and more apparent, especially since some folks will be looking at this from a TV monitor

What it looks like today: 
![screen shot 2017-09-20 at 3 22 41 pm](https://user-images.githubusercontent.com/19274230/30663110-96bd45ae-9e17-11e7-85c0-898024eac8aa.png)

calling @Lindsayauchin for a design

**Comment by Lindsayauchin** [comment]
Tooltip with a pointer end, oriented to the centre axis of the box 
This will allow the he User can see exactly the box that the tooltip is referencing. ![tooltip_sample_dashboard](https://user-images.githubusercontent.com/27746614/30666144-65cbee3c-9e21-11e7-866f-b04bc914b0a6.png)
