### ISSUE TITLE
Asymetric get/put of /api/v1/teams/:team/pipelines/:pipeline/config

### ISSUE THREAD

**Issue by yevster** [concourse/concourse#1631]
# Bug Report
At the URI ```/api/v1/teams/:team/pipelines/:pipeline/config```, a GET returns a structure of the form
```
{ 
     "config": { <actual config here> },
     "errors":...
      "raw_config": {...}
}
```
However, the same structure is not legal as the body to a PUT request to the same URI. In the absense of documentation, this makes consuming the API mildly agonizing.

Recommend refactoring such that ```/api/v1/teams/:team/pipelines/:pipeline/config``` returns only the full configuration, the same thing that's expected in the PUT operation. Raw config could be obtained by ```/api/v1/teams/:team/pipelines/:pipeline/config?raw=true```, and errors could be obtained by ```/api/v1/teams/:team/pipelines/:pipeline/config/errors```.

* Concourse version: 3.4.1

**Comment by vito** [comment]
Our API is currently provided "as-is" and is intentionally not documented. I agree with this change in principle but until we're actually striving to support and document a stable, versioned API it doesn't make sense for us to prioritize fixing this.

I'd welcome a PR though. Undocumented shouldn't also mean "not improving". :)
