### ISSUE TITLE
Resource hangs

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#1633]
# Bug Report

* Concourse version:

3.4.1

* Deployment type (BOSH/Docker/binary):

binary

* Infrastructure/IaaS:

AWS / ubuntu 16.04

* Did this used to work?

Yes

* Problem

A git resource in a specific pipeline is hanging. This resource has a path (as do others in this pipeline, who are all working), but otherwise there's nothing special about this resource.

`fly -t aws check-resource foo/bar` hangs, and all jobs that interact with that resource hang, too.

I'm able to pause and unpause the resource just fine.

There are no stalled workers and all workers have space on their drives (aplenty).

This issue has been going on for about 3 days.

**Comment by jadekler** [comment]
Removing the path fixed the hanging. Adding the bath back in made it hang again.

**Comment by jtarchie** [comment]
What do yo mean `path`? Can you provide an example?

**Comment by jadekler** [comment]
@jtarchie Git resource `paths` option - sorry for not being more clear!

The weird thing is we have 4 resources pointed at one git repo (a direnv style go-workspace with many apps); each resource has a path to a different part of the go-workspace, and 3 work and 1 hangs.

**Comment by pnikonowicz** [comment]
We had this problem recently and adding a 
```
- path: ['*']
```
unblocked us
