### ISSUE TITLE
Workers cannot check resources "promise already exists in list"

### ISSUE THREAD

**Issue by TimJones** [concourse/concourse#1635]
# Bug Report

I had an issue with some stuck jobs taking a super long time to run (normally 7min jobs running for 40+min without completing) which I killed off then manually triggered. The new jobs were permanently stuck in the 'pending' state. I restarted the web/API component then a lot (but not all) of my resource checks started failing due to `promise already exists in list`. Running the `fly check-resource` command returned
```error: Unexpected Response
Status: 500 Internal Server Error
Body:

```

Killing the workers, pruneing them, then starting new workers 'fixed' the issue.

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Did this used to work? Yes

**Comment by keithkroeger** [comment]
We are seeing this in 3.9.2 as well:
<14>1 2018-05-31T08:24:32.471395Z 24b6373a-7d71-4400-a416-08c6bc02d476.production-web.default.production.bosh atc rs2 - [instance@47450 director="" deployment="production" group="production-web" az="z1" id="24b6373a-7d71-4400-a416-08c6bc02d476"] {"timestamp":"1527755072.006015301","source":"atc","message":"atc.build-tracker.track.failed-to-fetch-image-for-container","log_level":2,"data":{"build":141269,"container":"344c7ac9-7c33-4d54-452f-9bc9c56929f8","error":"promise already exists in list","job":"docker-build-factory","pipeline":"testing","session":"43.705"}}
