### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by emichaf** [concourse/concourse#1641]
# Bug Report

After a few failed builds, concourse generates error msg "no space left on device", but space exists!

Are images not removed after failed builds?

How to remove containers?

* Concourse version: v3.5.0
* Target environment: K8S v1.6.4
* Deployment type : Helm chart stable/concourse 0.5.0

**Comment by jgrau** [comment]
I am no expert (concourse noob actually) but I had the same issue with the same setup as you. Using the overlay driver instead of the naive driver helps tremendously but I had to create a separate GKE cluster using Ubuntu nodes instead of CoreOS nodes for that driver to work.

**Comment by JohannesRudolph** [comment]
We have a similar issue in a different setup (docker on Ubuntu VMs on Meshcloud OpenStack, no K8s). The issues have first appeared with Concourse v3.5 and we were fine on 3.3.1. 

For example we see this: 
```
runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"tmpfs\\\" to rootfs \\\"/worker-state/volumes/live/473c914d-4e1e-4fe8-7bdc-e836d2cbeca2/volume/rootfs\\\" at \\\"/dev/shm\\\" caused \\\"mkdir /worker-state/volumes/live/473c914d-4e1e-4fe8-7bdc-e836d2cbeca2/volume/rootfs/dev/shm: no space left on device\\\"\""
```

`df -H` on our workers shows plenty free space.

**Comment by drahnr** [comment]
Are you using the btrfs storage driver?

**Comment by JohannesRudolph** [comment]
Nope

Am 27.09.2017 3:37 PM schrieb "Bernhard Schuster" <notifications@github.com

**Comment by vito** [comment]
This doesn't look very actionable to be honest. If the OS says "no space left on device," there's no space left somewhere. I don't think you're lying when you say "space exists" but...I don't think the kernel's lying either. 😄 

I'd recommend setting up metrics or something to show that the disk space never reached 100% - it's possible that it peaks, and by the time you go in to check, the space usage is gone.

In any case, there are no known space leaks in Concourse, and I have no reason to believe that we're doing anything complicated or stupid that would result in any more disk space being used than what's actually necessary to run your builds.

Make sure you're using either the `overlay` or `btrfs` driver, as @jgrau mentioned. The `naive` driver will *work*, but it's stupidly inefficient (in both time and space).

**Comment by Sispheor** [comment]
Guys, how to we clean up orphaned images?

I have the same error but it normal. I'm using a testing server with only 10 GB of space for the /var.
As I work on a docker image I'm constantly pushing it into my registry and so concourse pull it.
Just for my understanding, I would like to know if there is a way to clean up all images.

On my system i can do a something like this 
```
docker rmi -f $(docker images | grep "<none>" | awk "{print \$3}")
```

But on my concourse server I only see image used by concourse itself.
```
docker image ls
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
postgres              9.5                 22d09d16c13b        7 days ago          264MB
concourse/concourse   latest              4908e7cfa8d3        4 weeks ago         457MB
```

I suppose they are stored inside a volume. How can I access it to clean it up?

Thanks !
