### ISSUE TITLE
`fly set-pipeline` could `error: invalid configuration:` if `job.plan.task.config.platform` is missing

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#1644]
# Feature Request

## What challenge are you facing?

I am writing a task directly into a pipeline (rather than in a separate task.yml). I forgot to specify `platform:` in the pipeline.yml and only got feedback from the pipeline going orange with this error message:

```
invalid task configuration:
  missing 'platform'
```

## A Modest Proposal

The fly cli could validate this field at `fly set-pipeline` time, so that I get faster feedback.

Maybe this is low-value since the more desirable pattern is to have a separate task yml?

**Comment by pivotal-gabriel-dumitrescu** [comment]
Closed with PR concourse/atc#200.
