### ISSUE TITLE
500 Internal Server Error - Can't cleanup pipeline

### ISSUE THREAD

**Issue by shinmyung0** [concourse/concourse#1645]
# Bug Report

The problem I am having is that during one of my jobs I kept getting this error message:
```
pq: new row for relation "volumes" violates check constraint "cannot_invalidate_during_initialization"
```

I think it was mentioned in a few other issues like this one #1419, but my main problem now is that I cannot event delete the pipeline and start over. When I run `fly dp` command I get this very opaque error: 
```
error: Unexpected Response
Status: 500 Internal Server Error
Body:

```

# Additional info
* Concourse version: v3.4.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Infrastructure
* Browser (if applicable): Chrome
* Did this used to work?: Yes

**Comment by chingcodes** [comment]
I have also hit this issue with v3.3.1

**Comment by panessa** [comment]
Some issue with v3.5

**Comment by shinmyung0** [comment]
When I attempt to destroy the pipeline these are the errors I am getting, which is the same postgres error I was getting.
```
{"timestamp":"1507659258.361013412","source":"atc","message":"atc.syncer.catalog-service:radar.scan-resource-type.interval-runner.tick.versions-found","log_level":1,"data":{"pipeline-scoped-name":"catalog-service:resource-type:maven-resource","session":"17.23.1.1.96223","total":1,"versions":[{"digest":"sha256:7e456755aceb8bd064c856c0a8388cbfddac62f4b4963943fb4cd93731e18867"}]}}
{"timestamp":"1507659259.734313965","source":"atc","message":"atc.destroying-pipeline.start","log_level":1,"data":{"name":"catalog-service","session":"2848540"}}
{"timestamp":"1507659259.752369881","source":"atc","message":"atc.destroying-pipeline.failed","log_level":2,"data":{"error":"pq: new row for relation \"volumes\" violates check constraint \"cannot_invalidate_during_initialization\"","name":"catalog-service","session":"2848540"}}
```

**Comment by headcr4sh** [comment]
Today, I stumbled across the same issue.
I am running Concourse CI v3.5.0 via docker-compose with PostgreSQL v9.6.5 as datastore.


```
{"timestamp":"1508830965.862291813","source":"atc","message":"atc.destroying-pipeline.start","log_level":1,"data":{"name":"my-pipeline","session":"445466"}}
{"timestamp":"1508830965.881769180","source":"atc","message":"atc.destroying-pipeline.failed","log_level":2,"data":{"error":"pq: new row for relation \"volumes\" violates check constraint \"cannot_invalidate_during_initialization\"","name":"my-pipeline","session":"445466"}}
```

The error message itself it seems is this:
> pq: new row for relation "volumes" violates check constraint 
> "cannot_invalidate_during_initialization"","name":"my-pipeline","session":"445466"


**Hint**
I am pretty sure that this pipeline is rather old (I suppose, I created it on Concourse CI v3.3.0 or an even older version...). I updated to v3.5.0 on the day it came out and was able to destroy pipelines created on v3.5.0 without any probelms. So it _might_ be an issue with old pipelines that were created prior to upgrading Concourse CI / ATC.

**Comment by Sharor** [comment]
We had this issue as well, with a BOSH deployed setup. It worked previously, and error'd the same way. Initially SSH git resource just stopped working, and then this happened.

**Comment by itsdalmo** [comment]
Seeing the same error on 3.6.0. I have multiple tasks (9 in total) running `terraform apply` under an `aggregate:` step - all of the apply's complete, but then I get the `pq: new row for relation "volumes" violates check constraint "cannot_invalidate_during_initialization"` error at the end.

**Comment by troykinsella** [comment]
Seeing this in 3.6.0 binaries.

**Comment by chingcodes** [comment]
Any updates?

After hitting this several times during testing, I had to hold back on deploying this system in production.

**Comment by shashwathi** [comment]
@chingcodes : [This](https://github.com/concourse/concourse/issues/2031) is fixed in concourse 3.9.2 version. Can you verify if you are still seeing this issue?

Regards

**Comment by chingcodes** [comment]
Don't have any active instances I could easily test on, the linked issues sounds reasonable.

**Comment by vito** [comment]
Closing; that check constraint doesn't exist anymore as of #2031.
