### ISSUE TITLE
Pipeline shows as green even if git resource by tag was unavailable

### ISSUE THREAD

**Issue by mofrank** [concourse/concourse#1648]
# Bug Report
* Concourse version: v3.3.3
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

When a job shows as complete it was not showing a resource into the next triggered job not being found.   In this case we were using a git repo with a version tag that did not exist.   Nothing in the UI showed the resource did not exist

**Comment by jtarchie** [comment]
@mofrank: Please clarify "not found". It sounds like you typed the `url` incorrectly. Right?

**Comment by rahulkj** [comment]
@jtarchie - the issue @mofrank is referring to is, where the user defines a git tag that does not exist in github, then the pipeline `check-resource` command executes with `checked successfully` output. In reality the git versions did not appear as the tag was missing. So what @mofrank is asking here for is a way to notify the user that the input resource has an issue with the definition

**Comment by vito** [comment]
Is this regarding the [`git`](https://github.com/concourse/git-resource) resource? What do you mean by version tag? Can you provide steps to reproduce, i.e. a configuration we can try?
