### ISSUE TITLE
Fail fast when one aggregated task fails

### ISSUE THREAD

**Issue by bendodd** [concourse/concourse#165]
Given a set of more than one aggregated/concurrent tasks, can the job "fail fast" as soon as one of the tasks in the set fail? 

Especially useful when tests have been parallelised across multiple workers to reduce build time...

**Comment by vito** [comment]
FWIW, I think this would be a pretty easy change to the [`aggregate` step](https://github.com/concourse/concourse/blob/master/atc/exec/aggregate.go). The only change necessary would be to give the sub-steps their own context and cancel it on the first `err` read from the `errs` channel here:

https://github.com/concourse/concourse/blob/02a90a4d0e99ca00767bda0b83189215543efe45/atc/exec/aggregate.go#L32-L34

This should be an optional param though. `fail_fast: true`?

**Comment by vito** [comment]
This was implemented by https://github.com/concourse/concourse/pull/3580 :+1: - it'll be in 5.2
