### ISSUE TITLE
DNS fails to resolve - missing iptables rule

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1667]
# Bug Report

DNS fails to resolve for check/get and all builds fail (yes fail, not error) since things like `github.com` do not resolve.

Temporarily disabling enforcement of all iptables rules on the worker makes the pipelines work again.
```
systemctl stop firewalld
systemctl restart concourse-worker
```

where

the systemd unit file is as follows:
```
[Unit]
Description=concourse worker

After=suspend.target
After=hibernate.target
After=hybrid-sleep.target
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=60s
Environment=CONCOURSE_WORKER_NAME=abyss
Environment=CONCOURSE_TSA_HOST=ci.spearow.io
Environment=CONCOURSE_TSA_PORT=...
Environment=CONCOURSE_TSA_PUBLIC_KEY=...
Environment=CONCOURSE_WORKER_PRIVATE_KEY=...
Environment=CONCOURSE_WORK_DIR=...
Environment=CONCOURSE_KEY_DIR=...
#Environment=CONCOURSE_GARDEN_DNS_SERVER=...
ExecStart=/usr/local/bin/concourse \
		worker \
		--name=${CONCOURSE_WORKER_NAME} \
		--work-dir=${CONCOURSE_WORK_DIR} \
		--tsa-host=${CONCOURSE_TSA_HOST} \
		--tsa-port=${CONCOURSE_TSA_PORT} \
		--tsa-public-key=${CONCOURSE_KEY_DIR}/${CONCOURSE_TSA_PUBLIC_KEY} \
		--tsa-worker-private-key=${CONCOURSE_KEY_DIR}/${CONCOURSE_WORKER_PRIVATE_KEY}
#		--garden-dns-server=${CONCOURSE_GARDEN_DNS_SERVER} # no change
#		--garden-dns-proxy-enable # causes :53 address already in use

ExecStop=-/usr/local/bin/concourse \
		land-worker \
		--name=${CONCOURSE_WORKER_NAME} \
		--tsa-host=${CONCOURSE_TSA_HOST} \
		--tsa-port=${CONCOURSE_TSA_PORT} \
		--tsa-public-key=${CONCOURSE_KEY_DIR}/${CONCOURSE_TSA_PUBLIC_KEY} \
		--tsa-worker-private-key=${CONCOURSE_KEY_DIR}/${CONCOURSE_WORKER_PRIVATE_KEY}

[Install]
WantedBy=multi-user.target
```

One symptom is that guardian exits with exit code `128` which can be retrieved from the logs.

Reduced to the relevant handle:
```
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.835707664","source":"guardian","message":"guardian.api.garden-server.get-properties.got-properties","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","session":"3.1.1651"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.871015787","source":"guardian","message":"guardian.run.started","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.871315002","source":"guardian","message":"guardian.run.exec.start","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.871395826","source":"guardian","message":"guardian.run.exec.prepare.start","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2.1"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.885740280","source":"guardian","message":"guardian.run.exec.prepare.finished","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2.1"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.885795832","source":"guardian","message":"guardian.run.exec.execrunner.start","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2.2"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.891973972","source":"guardian","message":"guardian.run.exec.execrunner.read-exit-fd","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2.2"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.947968721","source":"guardian","message":"guardian.run.exec.execrunner.runc-exit-status","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2.2","status":0}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.948189020","source":"guardian","message":"guardian.run.exec.execrunner.done","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2.2"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.948215723","source":"guardian","message":"guardian.run.exec.finished","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535.2"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.948238611","source":"guardian","message":"guardian.run.finished","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","path":"/opt/resource/check","session":"1535"}}
Sep 27 10:13:49 redbeard concourse[3619]: {"timestamp":"1506500029.948260307","source":"guardian","message":"guardian.api.garden-server.run.spawned","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"d8e0ac2a-a542-4b91-45be-2b0d357c2f78","session":"3.1.1652","spec":{"Path":"/opt/resource/check","Dir":"","User":"root","Limits":{},"TTY":null}}}
Sep 27 10:13:55 redbeard concourse[3619]: {"timestamp":"1506500035.085594416","source":"guardian","message":"guardian.api.garden-server.run.exited","log_level":1,"data":{"handle":"bdbaab09-b183-4838-7719-4f3666896a62","id":"d8e0ac2a-a542-4b91-45be-2b0d357c2f78","session":"3.1.1652","status":128}}
```

The worker still shows up, although with much lower count of containers than expected (= ~50):

```
fly -t spearow workers
name   containers  platform  tags  team  state    version
abyss  5           linux     none  none  running  1.2 
```
The following can also be handy:

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Fedora / CentOS / RedHat
* Browser (if applicable): firefox
* Did this used to work? Broken at least since 3.4.0, not tested before.

**Comment by drahnr** [comment]
```
Sep 27 10:18:50 redbeard concourse[3619]: {"timestamp":"1506500330.092863083","source":"guardian","message":"guardian.api.garden-server.create.failed","log_level":2,"data":{"error":"iptables: create-instance-chains: iptables: No chain/target/match by that name.\n","request":{"Handle":"3f171643-42a4-41b5-43f9-85d4758f055e","GraceTime":0,"RootFSPath":"raw:///media/concourse/volumes/live/dda6d6cd-0d08-4329-59ee-b63d2d546534/volume","BindMounts":[{"src_path":"/media/concourse/volumes/live/48414c11-2128-4eba-68c7-897f68d9fcbd/volume","dst_path":"/scratch","mode":1}],"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"3.1.2057"}}
```

**Comment by vito** [comment]
This may be an issue with systemd's default networking stack. As I recall, it sometimes sets up its own DNS server, possibly on a local address. This will result in a broken `/etc/resolv.conf` being propagated into the container, as it'll just point to the container's own network space, which isn't running a DNS server.

We added support for proxying DNS servers (the `--garden-dns-proxy-enable` flag), but as your config shows in a comment, that'll fail on a systemd stack as they're already running their own server.

Have you tried configuring `CONCOURSE_GARDEN_DNS_SERVER=8.8.8.8`?

Can you paste the contents of `/etc/resolv.conf` on the host machine?

**Comment by vito** [comment]
@drahnr Any word on this?

**Comment by drahnr** [comment]
CONCOURSE_GARDEN_DNS_SERVER=8.8.8.8 makes no difference. Will attach resolv.conf later tonight.

**Comment by richarddowner** [comment]
@drahnr did you find a solution to this? We are seeing what seems to be the same problem.

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.dev.mycompany.com/Repo/Name.git/': Could not resolve proxy: proxy.tpz.mycompany.com
```

**Comment by drahnr** [comment]
Well to some extended, at least it reduced the occurrence frequency:
* masking `firewalld.service` or making sure the worker starts after `firewalld.service` has started, though the latter did not work reliably at all times

Despite this, there is still 1/10 boots where this happens.

**Comment by drahnr** [comment]
Right now I am unable to reproduce this with `3.9.1` and `btrfs` storage driver.

**Comment by brownjohnf** [comment]
We're also experiencing this, running v3.8.0 on CoreOS on AWS. Everything seems to work fine for some period of time, but then start failing with the 128 status code as mentioned in the top post.

**Comment by sevein** [comment]
I was trying Concourse on a machine running Ubuntu with ufw enabled. The following fixes the issue:

    sudo ufw default allow routed

**Comment by sbkg0002** [comment]
@brownjohnf did you find any solution? I have the same problem with CoreOS version > 1550

**Comment by keithkroeger** [comment]
We have now also found this in 3.8.0.
Any solution?

**Comment by keithkroeger** [comment]
Thank you @brownjohnf.

I assume that you're using a BINARY execution of Concourse rather than BOSH, is this true?

Or, did you change the monit files or add some other task to BOSH?

**Comment by brownjohnf** [comment]
Ah yes, sorry. I'm using the binary distribution, and managing it via systemd.

**Comment by keithkroeger** [comment]
Yeah...thank you!

**Comment by sbkg0002** [comment]
Any suggestion on how to solve this with docker (on CoreOS)?

**Comment by brownjohnf** [comment]
Running the worker in Docker, or as a binary on CoreOS? I was unable to make this work on CoreOS when running the worker as a binary; I had other issues with the worker in a Docker container, but I don't remember what they were off the top of my head. I'd prefer to run CoreOS workers though.

**Comment by sbkg0002** [comment]
Running the concourse/concourse docker containers on CoreOS. It's running fine for months now, but we have dns issues on > 3.8.0, or if we upgrade CoreOS to the current version.

**Comment by shokinn** [comment]
I've the same but on Ubuntu 18.04 LTS.

- Concourse version: 3.14.1
- Deployment type (BOSH/Docker/binary): binary
- Infrastructure/IaaS: Ubuntu 18.04 LTS
- Browser (if applicable): firefox
- Did this used to work? Broken at least since 3.14.1, not tested before.

The work around from @brownjohnf (`/sbin/iptables -P FORWARD ACCEPT` didn't worked for me.

**Comment by shokinn** [comment]
Update:
After switching back to Ubuntu 16.04 LTS everything works fine!

**Comment by clintjedwards** [comment]
@shokinn did you have to implement the work around for it to work in Ubunu 16.04?

**Comment by shokinn** [comment]
@clintjedwards no. But the standard iptables policy for forward is accept. So I just didn't changed it.

**Comment by sbkg0002** [comment]
Any updates on this? @shokinn did you find any way to get it working on 18.04?

**Comment by shokinn** [comment]
@sbkg0002 
Yupp, sort of. I use docker now.
If you are interested in how I setup my environment take a look here:  
<https://docs.pphg.tech/software/server/concourse_dockerized/>

**Comment by s432411** [comment]
I use the `quickstart` command and I got the same issue. In my corporate network any public dns is forbidden.

```
oncourse quickstart --postgres-host 127.0.0.1 --postgres-user concourse --postgres-database concourse --postgres-password concourse --add-local-user admin:admin --main-team-local-user admin --worker-work-dir /opt/concourse/worker/  --external-url http://concourse.internal:8080 --worker-garden-dns-server my_dns_server
```

**Comment by vlfig** [comment]
If you're on Ubuntu **18.04 TLS** and the above mentioned `--garden-dns-server` option is no longer available (concourse versions 5.0.0+, perhaps earlier), you can set `CONCOURSE_GARDEN_DNS_SERVER=1.1.1.1` in the shell launching your worker.

Of course DNS servers other than `1.1.1.1` will also do, depending on the case.

**Comment by vito** [comment]
We'll have docs covering this soon. They're written already but we need to
wait on 5.1 before publishing them since they depend on a fix to setting
garden config. :+1:

**Comment by samgurtman** [comment]
@vlfig does CONCOURSE_GARDEN_DNS_SERVER actually work on concourse 5.0.0+. There's some forum posts that indicate it does not have any effect.

https://discuss.concourse-ci.org/t/workers-containers-no-longer-resolve-internal-dns-in-v5-0/1245/8

**Comment by vlfig** [comment]
@samgurtman it did solve the issue back then yes. Sadly, we're parking our move to Concourse here, so I can't give more up-to-date information. Glad the docs are covering this now. :+1:

**Comment by ViktorNova** [comment]
I can confirm that adding CONCOURSE_GARDEN_DNS_SERVER=8.8.8.8
into /etc/worker_environment worked for me on Ubuntu 18.04 server with binary installation

**Comment by jgriff** [comment]
I too can confirm @ViktorNova 's confirmation... 

I'm running Ubuntu 18.04 with Concourse 5.5.1 (binary + systemd).  My little twist is that is all running as a Docker container.  

The one loop I went around for a while was I had to declare a Docker `VOLUME` for my worker's `--work-dir`, or else the worker was unable to create any containers.

**Comment by dfuentes77** [comment]
> Is there any update of this, this is still broken on Ubuntu 18.04 even with the workaround mentioned.
> 
> EDIT: I have been able to get it working by specifying a `--garden-dns-server` manually on the Concourse Worker binary. On AWS it seems to work by specifying the AWS provided local DNS ` --garden-dns-server 169.254.169.253`

I can confirm that this worked for me as well.

**Comment by vito** [comment]
Hi all - hope it's OK for me to close this, since issues are now for backlog items only (per [this post](https://blog.concourse-ci.org/nobody-wants-a-stale-bot/)), and the OP appears to have had their situation resolved a couple years ago (https://github.com/concourse/concourse/issues/1667#issuecomment-379435194).

In addition, the docs I mentioned previously have been written and are available [here](https://concourse-ci.org/concourse-worker.html#troubleshooting-and-fixing-dns-resolution).

Anyone who runs into DNS issues should probably open a new Discussion focused on their particular scenario. This one has turned into a bit of a smorgasboard. :)

Thanks to all who shared their experiences and workarounds!
