### ISSUE TITLE
Show clear error message when `CONCOURSE_EXTERNAL_URI` is malformed

### ISSUE THREAD

**Issue by Granjow** [concourse/concourse#1668]
# Feature Request

## What challenge are you facing?

When submitting a local task, concourse responds with `unsupported protocol scheme ""`.

```
$ fly -t iot execute -c command.yml 
executing build 1437 at http://example.com/builds/1437 
upload request failed: Put /api/v1/pipes/3e07ef59-3880-4d7f-557c-26cabc2d2cd0: unsupported protocol scheme ""
curl: (3) <url> malformed

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
failed
```

This is caused by a wrong entry in the docker-compose.yml file.

```
# wrong
CONCOURSE_EXTERNAL_URL: "example.com"
# correct
CONCOURSE_EXTERNAL_URL: "http://example.com"
```

## A Modest Proposal

Provide an error message which is easier to understand and which points to `CONCOURSE_EXTERNAL_URL`.

**Comment by vito** [comment]
this should be cleaned up by concourse/flag#1 which is now merged
