### ISSUE TITLE
unable to re-deploy using bosh-init

### ISSUE THREAD

**Issue by codeword** [concourse/concourse#167]
I am unable to re-deploy using bosh-init.
my deployment includes baggageclaim and on re-deployment the agent is reporting that it cannot unmount our persistent disk.  This seems to be because baggageclaim has a loopback device still attached to the persistent disk:
```root@c9b2050c-b747-4985-58b0-21424dd60d1d:/var/vcap/bosh/log# umount /dev/sdc1
umount: /var/vcap/store: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
root@c9b2050c-b747-4985-58b0-21424dd60d1d:/var/vcap/bosh/log# losetup -a
/dev/loop0: [0812]:12 (/var/vcap/data/root_tmp)
/dev/loop1: [0821]:393218 (/var/vcap/store/baggageclaim/volumes.img)
/dev/loop2: [0812]:1441795 (/var/vcap/data/garden/garden_graph_backing_store)
```
this is after the agent has stopped all monit processes.

I am going to manually kill that loopback via `losetup -d /dev/loop1` then re-run my bosh-init deploy command which should work but isn't a working solution moving forward.  You may have a bug in your baggageclaim process

...
**Update**
we tried the `losetup -d  /dev/loop1` and it reported a `0` status but the device was still attached.  finally we ran `ummount /dev/loop1` and it finally got removed.

**Comment by aaronshurley** [comment]
We encountered this problem again.  It looks like the bug is not prioritized, but this is a pretty severe bug as we are unable to re-deploy concourse without knowing about the need to manually `losetup -d ...` and `umount ...`  Any word on prioritizing this?

**Comment by nicorikken** [comment]
+1 Would be great to at least have some insight in this progress, as the needed manual actions undermine an otherwise satisfying experience.

**Comment by saliceti** [comment]
+1: Same issue here. Only `losetup -d  /dev/loop1` solved it.

**Comment by vito** [comment]
@nicorikken / @saliceti / @aaronshurley Dragged in, but could use more info for characterizing this.

Do all of your workers have a persistent disk?
