### ISSUE TITLE
More obvious click areas on thumbnail previews on dashboard

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1670]
The new multi-pipeline preview shows the pipeline as a thumbnail that allows users to click into the pipeline, or click into a specific job on the pipeline:

![screen shot 2017-09-27 at 10 00 12 am](https://user-images.githubusercontent.com/19274230/30917760-bb4a7934-a36a-11e7-85a6-64b25ca30b79.png)

In this thumbnail its not obvious that the user can ONLY click on the top area (near the pipeline name basically) to get access to the pipeline itself. 

+cc @Lindsayauchin

**Comment by Lindsayauchin** [comment]
Lets try this split card treatment for the card. This could help with the text wrapping issue as well. 


![dashboard_split_cards](https://user-images.githubusercontent.com/27746614/30939455-7d4acda0-a3ab-11e7-848a-23cbf5ec4bec.png)
