### ISSUE TITLE
We need a solution for long pipelines names in dashboard

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1671]
We need to neatly handle long pipeline names for the multi-pipeline dashboard. Right now the bad actors can show up as: 

![screen shot 2017-09-27 at 9 56 07 am](https://user-images.githubusercontent.com/19274230/30917837-e2933652-a36a-11e7-8d8e-50334ce6b965.png)

which is kind crappy

+cc @Lindsayauchin

**Comment by mhuangpivotal** [comment]
We opted to set a max width on the pipeline name and show ellipsis when it's too long:

<img width="311" alt="screen shot 2017-10-04 at 5 06 53 pm" src="https://user-images.githubusercontent.com/1919762/31199793-862a47d6-a926-11e7-9dc9-5b9c381d558f.png">
