### ISSUE TITLE
Teams are shuffling when logged into multi-pipeline dashboard

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1673]
Teams are shuffling around and its distracting as hell. It seems to only happen when you're logged in to the dashboard.

**Steps to reproduce:**
1. Have at least two teams
2. Login
3. Watch the dashboard view

**Expected Results**
The teams shouldn't shuffle around

**Actual results**
The teams shuffle around!

**Comment by pivotal-gabriel-dumitrescu** [comment]
- can not reproduce the issue on local environment using 10 teams and public, private, paused an unpaused pipelines
- the https://wings.concourse.ci/api/v1/pipelines API response used by dashboard returns different response, with team logged in always at the top and oscillating the rest of the teams

**Comment by jama-pivotal** [comment]
@pivotal-gabriel-dumitrescu should we close this until we have better repro steps, or are we going to keep debugging it?

**Comment by pivotal-gabriel-dumitrescu** [comment]
@jama-pivotal will take a quick look again this morning and if we are not able to figure it out, we can pause it until we have better steps to reproduce the issue locally.

**Comment by pivotal-gabriel-dumitrescu** [comment]
@jama-pivotal we were able to reproduce the issue by changing the order from the sidebar for two separate teams other than main. Fix will involve sorting pipelines by teams to avoid having two pipelines from different teams with same ordering value.
