### ISSUE TITLE
`check-resource --from` is exclusive, meaning I cannot refer to the first-ever version of a resource

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#1679]
# Feature Request

## What challenge are you facing?

Suppose I have a resource which expresses versions in semver format. Suppose I have a source where those semver numbers come from. I might have 4 versions in the source: 1.0.0, 1.1.0, 1.2.0 and 1.3.0.

I want to have my pipeline act on all 4 versions, so I type:

`fly -t example check-resource --from: 'example_version:1.0.0'`

When I go to the UI, I see:

```
product_version: "1.3.0"
product_version: "1.2.0"
product_version: "1.1.0"
```

Version 1.0.0 has been ignored. In fact, I cannot use `--from` to begin at the true beginning of history, I am always stuck with an off-by-one scenario.

## A Modest Proposal

* `--from` should be inclusive of the version given.
* Add `--after`, which has the current behaviour of `--from`.

* Concourse version: 3.3.4
* Deployment type: BOSH
* Infrastructure/IaaS: GCP

**Comment by vito** [comment]
`--from` is *inclusive*, as the resource interface defines that it `check` include the version if it exists.

This sounds like a bug with whichever resource type that is.
