### ISSUE TITLE
Green pipelines in dashboard view should show the amount of time since they turned green

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1680]
# Bug Report

Currently when builds are not green, the dashboard shows the time that the pipeline has been in the current state. (i.e. when the pipeline is red, it shows the amount of time that has passed since the pipeline turned red).

However, when the pipeline is green, it seems to show the total amount of time that the pipeline has existed (we believe). This is confusing. 

When a pipeline is green the timer should say how long the pipeline has been green.

Example: Pipeline is brown
https://imgur.com/WOy3YLP

Then we turn it green:
https://imgur.com/DddwqT0

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work?: No

**Comment by mhuangpivotal** [comment]
This has been fixed in concourse/concourse#1628, but thanks for reporting!
