### ISSUE TITLE
Add a flag to turn off the new "hidden jobs" check

### ISSUE THREAD

**Issue by dumbbell** [concourse/concourse#1686]
## What challenge are you facing?

With Concourse 3.5.0, hidden jobs (i.e. not part of any groups) are considered an error (#1150).

We have many parallel jobs with several resources flowing from and to all of them, thus a single resource is displayed multiple times in the UI, with as many lines as needed to connect jobs. We use hidden jobs on purpose to remove load on the UI: those hidden jobs "gather" resources/lines so we go back to a single "copy" of a resource when we move to the next group.

Here is an example:
![screenshot-2017-10-2 server-release v3 7 x - concourse](https://user-images.githubusercontent.com/159804/31074681-20ae879c-a772-11e7-9b50-596ebfc94c62.png)

At the end of this group, we have a hidden job which does nothing but deduplicates lines. As you see, the UI is already unreadable. Adding the hidden job to the group doubles the height of the graph.

## A Modest Proposal

The real root problem is the UI which is not designed for pipelines with many jobs and resources. But this is not a quick and easy task.

I would love a way to turn off the new check for hidden jobs. I know we could have a useless group for all hidden jobs, but this would be another workaround on top of a workaround.

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS

**Comment by jama-pivotal** [comment]
Ah, that's an interesting (and unforseen) use case! We might want to dial down the check to make it less aggressive so it prompts for a Y/N if you want to proceed with setting a hidden, instead of just straight blocking you

**Comment by dumbbell** [comment]
After thinking a bit more about this, another solution would be to have a way to mark hidden jobs as such in the pipeline configuration directly. In our case, we know which jobs are hidden on purpose, but I would still like to be notified by fly(1) about other jobs not being added to any group. And unlike a flag on the command line or a prompt, this would serve as documentation for those jobs and still allow someone who doesn't know all the details about the pipeline to deploy it.

**Comment by vito** [comment]
Wouldn't one way to mark them as hidden in the config be to just...add them to a "hidden" group? :) That would then get past the validation, as well.

I don't think we should roll it back to support the workaround; a workaround for a workaround is still better than not having the validation. It'll also be more motivation to nag us about fixing the original issue. 😛 (Which we're actually going to start doing soon with the new pipeline UI being cooked up by @Lindsayauchin.)

**Comment by dumbbell** [comment]
It looks like a group named "" (empty string) is accepted (at least in 3.4.1) and doesn't take space in the group tabs bar. I guess it's ok for now.
