### ISSUE TITLE
Keep jobs in UI sorted as they are in the pipeline configuration

### ISSUE THREAD

**Issue by dumbbell** [concourse/concourse#1687]
## What challenge are you facing?

In the UI, jobs in the same column seem to be sorted by the width of their box (or the number of characters in their name which is about the same criteria). Likewise for resources.

We have many jobs and resources and the UI is impossible to read without zooming a lot. And because jobs and resources are "randomized" compared to their order in the pipeline configuration, it makes it even more difficult to e.g. locate a specific job.

## A Modest Proposal

It would help if there was an option to honor the order set in the pipeline configuration.

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS

**Comment by JohannesRudolph** [comment]
I can concur with this. My team runs a modestly complex pipeline for building a handful of microservices and concourse renders our pipeline as a needlessly entangled spaghetti.

This is just a part of it: 
![image](https://user-images.githubusercontent.com/130103/39821973-c2f527f2-53a9-11e8-81a9-feabf23ed978.png)

I would really appreciate if Concourse would layout the pipeline using some intelligent algorithm that minimizes the number of "crossings" between vertices of the graph. It appears to be [NP-hard](https://cs.stackexchange.com/questions/14901/how-to-reduce-the-number-of-crossing-edges-in-a-diagram) to do this, but hey, there are apparently some good approximations and graphs don't tend to get unwieldly large in concourse (not 100s of jobs). 

Alternatively, concourse could respect the order of appearance of jobs in the pipeline as a tie-breaker for laying out the graph and deciding on ordering.
