### ISSUE TITLE
Registering a houdini worker

### ISSUE THREAD

**Issue by kurtmc** [concourse/concourse#1689]
I am having trouble registering a houdini worker. I want to do work outside of a docker container on linux and it looks like my best bet is to use the [houdini](https://github.com/vito/houdini) garden implementation.

I have started houdini like this:
```
houdini -depot /opt/concourse/worker/containers
```

and baggageclaim like this:
```
baggageclaim --volumes=/opt/concourse/worker/volumes --driver=naive --log-level=debug
```

Then forwarding the worker like this:
```
ssh -o CheckHostIP=no -p 2222 ${TSA_HOST} -i /etc/concourse/keys/worker_key -R0.0.0.0:7777:127.0.0.1:7777 -R0.0.0.0:7788:127.0.0.1:7788 forward-worker --garden 0.0.0.0:7777 --baggageclaim 0.0.0.0:7788 < /opt/concourse/worker.json
```

/opt/concourse/worker.json:
```
{
  "platform": "linuxvm",
  "tags": ["my-worker"],
  "version": "1.2"
}
```

This successfully registers the worker, when I run `fly workers` I see:
```
name              containers  platform  tags            team  state    version
10.0.0.108:39011  0           linuxvm   my-worker  none  running  1.2 
```

I then want to test that it works with `fly execute --tag my-worker -c test.yml`.
test.yml:
```
---
platform: linuxvm

run:
  path: echo
  args:
  - test
```

but I get the output:
```
executing build 73426 at ${TSA_HOST}/73426 
initializing
running echo test
hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"chdir /opt/concourse/worker/containers/000000hfgeo/tmp/build/e55deab7: no such file or directory","Handle":""}

errored
```

Is there something that I am missing for registering a houdini worker in my concourse setup?

**Comment by Mantwon** [comment]
I actually had a very similar problem, I thought it was just me being new at this.. I can +1 that there is something weird going on.

**Comment by vito** [comment]
Where'd you get your `houdini` binary from? I haven't published a release of it in a long time, so it's probably out of date. Your best bet will be to build if from source, with `go get github.com/vito/houdini/cmd/houdini`.

**Comment by kurtmc** [comment]
@vito I was using the binary from the github releases. I have now switched to building from source and it's working initially but the worker will stall after a few seconds.

Here's the logs from the forward-worker command:
```
{
  "timestamp": "1507153626.231342554",
  "source": "tsa",
  "message": "tsa.connection.channel.forward-worker.heartbeat.start",
  "log_level": 1,
  "data": {
    "remote": "10.0.0.136:14841",
    "session": "1573.2.1.613",
    "worker-address": "10.0.1.76:33138",
    "worker-platform": "linuxvm",
    "worker-tags": "component-test"
  }
}
{
  "timestamp": "1507153626.241365194",
  "source": "tsa",
  "message": "tsa.connection.channel.forward-worker.heartbeat.reached-worker",
  "log_level": 0,
  "data": {
    "baggageclaim-took": "4.928472ms",
    "garden-took": "4.914944ms",
    "remote": "10.0.0.136:14841",
    "session": "1573.2.1.613"
  }
}
{
  "timestamp": "1507153626.247465611",
  "source": "tsa",
  "message": "tsa.connection.channel.forward-worker.heartbeat.bad-response",
  "log_level": 2,
  "data": {
    "remote": "10.0.0.136:14841",
    "session": "1573.2.1.613",
    "status-code": 405
  }
}
{
  "timestamp": "1507153626.247532606",
  "source": "tsa",
  "message": "tsa.connection.channel.forward-worker.heartbeat.done",
  "log_level": 1,
  "data": {
    "remote": "10.0.0.136:14841",
    "session": "1573.2.1.613",
    "worker-address": "10.0.1.76:33138",
    "worker-platform": "linuxvm",
    "worker-tags": "component-test"
  }
}
```

**Comment by wagdav** [comment]
Would https://github.com/concourse/concourse/pull/3153 solve the issue? If yes, this could be closed.

**Comment by kurtmc** [comment]
@wagdav I think it would.

**Comment by vito** [comment]
@wagdav Ah good catch! I forgot there was an issue for this. This can indeed be closed. This'll be in 5.0.0.
