### ISSUE TITLE
Feature Request: Zoom / Scroll Viewing Mode

### ISSUE THREAD

**Issue by SocalNick** [concourse/concourse#169]
My team has some really LONG pipelines that are very hard to see on our CI board. I was manually zooming / moving our pipeline on our CI board and a feature dawned on me. A view mode that zooms in as far as possible and horizontally scrolls the viewable area such that all the running jobs are shown.

**Comment by vito** [comment]
Collapsing into https://github.com/concourse/concourse/issues/530 - thanks for the idea!
