### ISSUE TITLE
ATC-Authorization cookie gets corrupted - Google Cloud Identity Aware Proxy 

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [concourse/concourse#1693]
We are running concourse in Google Cloud and have enabled Identity Aware Proxy. Once we enabled  IAP we noticed that the ATC-Authorization cookie value is getting corrupted. Specifically, it appears that the space character in the value is being interpreted as the end of the cookie value and consequently gets truncated. So the cookie ends up as ATC-Authorization="Bearer;
Furthermore, it seems that the quotes are simply being interpreted as part of the cookie value. 

Now one could argue that IAP is not correctly parsing the name=value pair based on RFCxxx, and so-and-so needs to fix their bug. However, instead, I would like to propose that concourse base64 encode or url encode the ATC-Authorization cookie value.

**Comment by matthewg** [comment]
Hi, this is a Cloud IAP bug tracked by https://issuetracker.google.com/issues/67426082 . There're more details there, but TL;DR we have a fix internally and I'm *hoping* it will be rolled out by the end of next week.

**Comment by vito** [comment]
Sounds like this was fixed upstream!

**Comment by AmandaHassoun** [comment]
hey @brandon-bethke-neudesic , I'm curious as to how you were able to use `fly` with Concourse behind IAP? I'm currently stuck trying to make this work..

**Comment by brandon-bethke-neudesic** [comment]
I am sorry, I do not recall. Shortly after this issue was filed, we stopped using Concourse. I only remember that we would ssh into a vm on gcp and run the fly tool on that machine which had access to kubernetes where Concourse was running.
