### ISSUE TITLE
zoom level periodically resets

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#1695]
# Bug Report

v 3.4.0 on Chrome

Lately when we're zooming into a big pipeline it periodically resets the zoom level which makes it hard to view a large pipeline. The zoom reset happens approx every 10 to 60 seconds.

**Comment by mhuangpivotal** [comment]
This is fixed in concourse/concourse#1505. Upgrading to v3.5.0 should resolve the issue.
