### ISSUE TITLE
Build Logs Never Load

### ISSUE THREAD

**Issue by bpholt** [concourse/concourse#1696]
I'm using the Hello, World! tutorial after installing Concourse using Docker Compose. I can create and run the pipeline, but when I view a job, the build log never loads. (It just spins with the label "loading…" indefinitely.) This happens in Safari and Chrome, with Docker for Mac 17.09.0-ce-mac33.

I noticed that during a build the status doesn't seem to update from running to finished, either. After reloading the entire page the finished status appears.

Making a request to `/api/v1/builds/2/events` with curl also hangs indefinitely:

```shellsession
$ curl --silent --verbose --cookie ATC-Authorization="Bearer …" http://10.200.10.1:18080/api/v1/builds/2/events
*   Trying 10.200.10.1...
* TCP_NODELAY set
* Connected to 10.200.10.1 (10.200.10.1) port 18080 (#0)
> GET /api/v1/builds/2/events HTTP/1.1
> Host: 10.200.10.1:18080
> User-Agent: curl/7.54.0
> Accept: */*
> Cookie: ATC-Authorization=Bearer …
> 
^C
```

But requesting the logs with `fly watch` works fine:

```shellsession
$ fly -t lite watch -j hello-world/hello-world -b 2
initializing
running echo Hello, world!
Hello, world!
succeeded
```

This is using the `docker-compose.yml` file as it appears in [the Docker installation instructions](https://concourse.ci/docker-repository.html), so I assume it's Concourse 3.5.0. `fly` also reports version 3.5.0:

```shellsession
$ fly -v
3.5.0
```

Here's the pipeline definition, if that's meaningful:

```shellsession
$ fly -t docker get-pipeline -p hello-world
groups: []
resources: []
resource_types: []
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: echo
        args:
        - Hello, world!
        dir: ""
```

(I'm reporting this with build 2, only because the output for build 1 includes a bunch of Docker image download logs which were noisy. The behavior is otherwise the same.)

**Comment by jtarchie** [comment]
Are you running an anti-virus? Some users have reported that it blocks that API endpoint.

**Comment by bpholt** [comment]
🤦‍♂️ 

Yes, we're [using Sophos](https://github.com/concourse/concourse/issues/781#issuecomment-304051553). I'll try to get it disabled and try again. Thanks.

**Comment by bpholt** [comment]
That was the problem. Thanks for the quick response!
