### ISSUE TITLE
Long pipeline name in side bar

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#1697]
# Bug Report

When the pipeline has a long name, the pause/unpause button loses the padding and the text is cut off:

<img width="311" alt="screen shot 2017-10-04 at 3 01 49 pm" src="https://user-images.githubusercontent.com/1919762/31194376-fbbd644a-a914-11e7-8f07-4179de2c2b8d.png">

* Concourse version: v3.5.0
* Browser (if applicable): Chrome
* Did this used to work? probably not

**Comment by jama22** [comment]
After removing the sidebar, bringing it back, and now ellisizing long names and having a toolbar, I think its safe to close this issue now
