### ISSUE TITLE
missing documentation for gitlab-auth

### ISSUE THREAD

**Issue by cforce** [concourse/concourse#1701]
Hi there!
In Concourse 3.3.0 the "feature gitlab auth support" was introduced but there is no doc for this.
What are the parameters top be set, what re defaults howto setup?
Just guessing these: 
* gitlabAuthClientId  Application client ID for enabling GitLab OAuth
* gitlabAuthClientSecret Application client secret for enabling GitLab OAuth
* gitlabAuthGroup GitLab groups (comma separated) whose members will have access
* gitlabAuthAuthUrl  Endpoint AuthURL for GitLab server
* gitlabAuthTokenUrl Endpoint TokenURL for GitLab server
* gitlabAuthApiUrl API endpoint URL for GitLab server

Please provide guidane for gitlab OID/Oauth  integration of Concourse.
Also how this plays together with the "main Team"

https://github.com/concourse/atc/tree/master/auth/gitlab 
https://github.com/kubernetes/charts/blob/master/stable/concourse/templates/configmap.yaml
https://github.com/kubernetes/charts/pull/1493/commits

**Comment by markstgodard** [comment]
Hi @cforce 

The docs should be in fly, I submitted a PR for adding docs: https://github.com/concourse/fly/pull/179

Cheers

**Comment by jama-pivotal** [comment]
I'm going to keep this open for now since we should be updating our Multiple Teams page (http://concourse.ci/teams.html) with the instructions @markstgodard included in his PR

**Comment by marco-m** [comment]
@jama-pivotal the same page (http://concourse.ci/teams.html) is also missing auth information for bitbucket

**Comment by Bak3y** [comment]
Would really appreciate some docs on this, needing to create concourse teams and tie them to GitLab teams

**Comment by jama22** [comment]
Closing because the new auth in 4 and 5 comes with better docs! https://concourse-ci.org/configuring-auth.html 👏
