### ISSUE TITLE
Multiple job control

### ISSUE THREAD

**Issue by iainsproat** [concourse/concourse#1706]
# Feature Request

## What challenge are you facing?

If there are multiple jobs which we need to pause/stop, it takes a while to go through each of them individually.

## A Modest Proposal

I'd like to suggest that there should be a drag-select (or other form of multi-selection) and batch pause/stop all the selected jobs at once.

**Comment by vito** [comment]
By task do you mean job?

**Comment by iainsproat** [comment]
Ah yes, I did mean jobs; I've now corrected the request description.
