### ISSUE TITLE
UI - Logo in dashboard is fuzzy

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#1711]
Logo on the dashboard view is not rendering the way an svg should. Replace with the asset provided here. 

![logo_fuzzy_bug_dashboard](https://user-images.githubusercontent.com/27746614/31443180-b53ed3e4-ae66-11e7-9257-f6e3d8311efd.png)
[concourse_logo_white.svg.zip](https://github.com/concourse/concourse/files/1375751/concourse_logo_white.svg.zip)

**Comment by osis** [comment]
We need those high resolution assets!
