### ISSUE TITLE
[Multi-Pipeline View] Mobile Friendly layout 

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#1712]
## Mobile Friendly layout of the dashboard UI
Some things we can do to make the dashboard look good on a phone. 

- [x] top navigation alignment
- [x] search below logo and team/login
- [x] square corners on search input
- [x] legend > alignment of icons and lables
- [x] legend not overlapping the view but anchored to the bottom of the page
- [x] login/team name on top nav
- [x] svg concourse logo in white

**Current state:**

![dashboard_bugs](https://user-images.githubusercontent.com/27746614/31445287-b9bb1310-ae6b-11e7-895d-06d52a8bed58.png)

**Proposed updates:**

![mobile_dashboard](https://user-images.githubusercontent.com/27746614/31499157-00bfbb64-af32-11e7-9320-0377692dd50b.png)

[concourse_logo_white.svg.zip](https://github.com/concourse/concourse/files/1379537/concourse_logo_white.svg.zip)

**Comment by vito** [comment]
The legend may end up covering the whole UI on a phone with less vertical space - maybe it should just be at the bottom of the page or something (i.e. not floating/overlapping)?

**Comment by osis** [comment]
I would vote for the legend to be something separate or an overlay vs being always in view to save screen real estate. People generally only look at the legend a handful of times.
