### ISSUE TITLE
[Search] Auto complete list

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#1713]
As an Operator, when I am searching, it would be nice to see an auto complete list hinting at the available search operators. Reference the styles used in [Search] No Results Found #1704

[JM] Some implementation details:

1) User focuses on the search bar and is blank, the dropdown should appear with the following hints (as kinda shown by the first screenshot)
* `status:`
* `team:`

2) If the user types the words that match a special search label (e.g. the complete phrase 'status:'), then we should provide hints on the options on that label. 
      - if `status:` then show: 
                - `status:pending`
                - `status:paused`
                - `status:failed`
                - `status:errored`
                - `status:aborted`
                - `status:running`
                - `status:succeeded`
      - if `team:` then show list of first 10 `team:<teamname>`
3) During this time user can use up/down arrow to select from dropdown and ENTER to select the filter
4) If the user just types something that's not even close to `status` or `pending try to match a pipeline name
5) if the text entered just doesnt match anything don't show the dropdown

**Dropdown Hex Codes** 
Background: 2E2E2E, Border: 9B9B9B, Border of the cells(Top +Bottom): 404040,
Font unselected: 9B9B9B 
Font Selected: FFF

![dashboard_search_auto_complete](https://user-images.githubusercontent.com/27746614/31461845-af1e77b2-ae98-11e7-8f7c-69b58ff4763a.png)
![dashboard_search_auto_complete_status](https://user-images.githubusercontent.com/27746614/31465663-9578187c-aea2-11e7-9efd-a28434fe781f.png)

**Comment by jama-pivotal** [comment]
We might want to think of a more sophisticated way of doing the autocomplete. Blatantly drawing inspiration from Gmail search here, but there seems to be a two distinct states:

1. Autocomplete when doing a "vanilla" pipeline search with suggestions for matching pipeline names and allowing you to select them from the dropdown
2. When initiating a keyword search (e.g. `status:`) a differentiated suggestion for permitted keywords  vs pipelines with matching text (e.g. what if there's a pipeline names `bosh_status`) 

<img width="600" alt="screen shot 2017-10-12 at 9 09 43 am" src="https://user-images.githubusercontent.com/19274230/31483557-2f3d0384-af2d-11e7-98af-e8381618ca7d.png">

**Comment by jtarchie** [comment]
@ahennar There isn't away, these are just mockups for prototyping.
