### ISSUE TITLE
Bug - inputs not updating

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#1714]
<img width="1678" alt="screen shot 2017-10-12 at 10 10 42 am" src="https://user-images.githubusercontent.com/3584893/31506769-ab08b622-af35-11e7-89bd-238749e6783b.png">

This git resource registers a new version but none of the detail about it. It also does not trigger the build that is configured to trigger on it.

We are using 3.4.1 on AWS EC2.

**Comment by vito** [comment]
Data is not collected until a build is run (see #534).

Is the bug that the build is not triggering? If so, can we see your configuration?

**Comment by vito** [comment]
Don't have much to go on here. Feel free to reopen with more info.

**Comment by phillbaker** [comment]
Also seeing this occasionally on the latest 3.8 release on AWS EC2 on postgres 9.5 with the pull-request resource.

@vito what configuration details would help? The build plan or configuration of concourse itself?

**Comment by phillbaker** [comment]
Another weird observation - some of the time, restarting atc seems to fix this.

**Comment by phillbaker** [comment]
Seems related to https://github.com/concourse/concourse/issues/1364.
