### ISSUE TITLE
resource scheduling through worker build limit 

### ISSUE THREAD

**Issue by gdenn** [concourse/concourse#1715]
# Feature Request

## What challenge are you facing?
We are facing a problem with our system resources. We have multiple Concourse Pipelines which run in parallel. Since there is no limit on how many Pipelines can be started at the same time, our resources get exceeded on a regular basis.

This gets even worse considering the fact that we have two different Concourse systems running on the same infrastructure as we have two different departments working with Concourse.

The result is that Pipeline tasks fail due to timeouts where our test cases normally should succeed, one of the Concourse system interferes the other...

## A Modest Proposal
Implement a `max_build` property in the worker job for a Concourse bosh cluster deployment that limits the amount of builds, a single worker can open at the same time.

This would be at least some way to restrict the amount of builds a Concourse system can run by `count of workers * max_build`.

* Concourse version: 3.5
* Deployment type (BOSH/Docker/binary): Bosh cluster
* Infrastructure/IaaS: vSphere

**Comment by jtarchie** [comment]
@gdenn: Isn't this what [max-containers](https://github.com/cloudfoundry/garden-runc-release/blob/develop/jobs/garden/spec#L126-L128) is for on garden-runc?

**Comment by gdenn** [comment]
@jtarchie you mean i can restrict my workers by using the max-containers property for the workers garden-runc job?

Mmh ill try that :)
