### ISSUE TITLE
Feature Request - A way to access files across concourse resources

### ISSUE THREAD

**Issue by chewymeister** [concourse/concourse#1716]
Hi there!

# Feature Request

## What challenge are you facing?

Our test scripts commonly have cross dependencies on code found in other concourse resources. For this reason we find ourselves defining a HOME variable that is calculated using BASH_SOURCE[0] and then a plethora of "../../..". When we moved our test or dependency files, this would break our CI scripts and we had to go through and make the appropriate changes.

## A Modest Proposal

What if we had an ENV that always told us the HOME directory from which all our top level concourse resources could be accessed? Then instead of defining `HOME=BASH_SOURCE[0]/../../../..` we would simply access the `$HOME` variable directly.

**Comment by vito** [comment]
Can't you just capture `$PWD` at the start of the task? We don't want to define a special variable because that makes the scripts less portable.
