### ISSUE TITLE
Support on-the-fly cred interpolation for `webhook_token`

### ISSUE THREAD

**Issue by timrchavez** [concourse/concourse#1717]
# Feature Request

## What challenge are you facing?

I would like to manage my `webhook_token` 's in Vault.

## A Modest Proposal

Add the `webhook_token` field to the list of fields that can use interpolation for secrets/credentials.

**Comment by timrchavez** [comment]
This is my first attempt at https://github.com/concourse/atc/pull/271

**Comment by jama-pivotal** [comment]
Closing
