### ISSUE TITLE
Logging pipeline build config

### ISSUE THREAD

**Issue by christophermancini** [concourse/concourse#1718]
# Feature Request

## What challenge are you facing?

When troubleshooting a failed build or unexpected logic in a pipeline, it is cumbersome to have to `fly -t ci get-pipeline` plus the state of the pipeline could have changed since the build had failed. When helping another engineer troubleshoot their build, I have to switch authenticated teams just to view their config.

## A Modest Proposal

That at the beginning of every build, the complete pipeline config is captured with secrets removed and displayed somewhere on the build results screen for the pipeline.

**Comment by timrchavez** [comment]
I see this as two separate issue.

1) Getting the pipeline config that was in place at the time the job built (most problems will probably arise in the business logic of a task, which is not something Concourse tracks, but there's probably a subset of behavioral issues that could arise from a valid pipeline config)

2) Someone that can authenticate with an administrator team, should have, at the very least, read access to teams' pipelines. Presumably this goes back to the RBAC discussion (https://github.com/concourse/concourse/issues/1317). As for filtering secrets, I'm not too concerned about that. If secrets are stored in a credentials backend like Vault, `get-pipeline` will return the uninterpolated parameters.
