### ISSUE TITLE
"unknown handle" errors after upgrading Concourse 2.6.0 to 3.3.4

### ISSUE THREAD

**Issue by derekvanassche** [concourse/concourse#1721]
## What challenge are you facing?

We are heavy users of Concourse and have four different instances running pipelines for our dev workflows. All four of these instances run on Concourse 2.6.0. Recently we upgraded to 3.3.4 on one of these instances and began to see "unknown handle" errors on some of the resources used by the pipelines. However, these errors only occurred on the day of the upgrade and did not appear again for five days. After upgrading a second instance to 3.3.4, we saw the same "unknown handle" errors at a significantly greater frequency on pipelines in both Concourse instances, several times per day. Given enough time, some of these errors seem to resolve themselves when running a job that uses the resource. But most of the time we have to recreate the worker associated to the lost handle in order to resolve, else the job stays in a pending state for a long period of time.

So far we have observed that the error consistently occurs on the same two resource types. One an OOTB git resource type that triggers on changes to the master branch from different repositories. The other is a custom resource type that triggers on pull requests from different repositories. It is also worth mentioning that there is a custom developed git hook that triggers jobs. Overall the issue seems similar to this: https://github.com/concourse/concourse/issues/1255. However, we need help tracking what the exact issue is from the Concourse side and what specifically we should do to rectify it.

I have logs from each worker captured during the time of the failures, an example pipeline configuration that is representative of the pipeline configurations that seem to be affected, and the source code from the custom resource type mentioned above; all ready to share with someone who can help me figure out what the issue is.

* Concourse version: 3.3.4
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Infrastructure
* Browser (if applicable): N/A
* Did this used to work? Yes, we saw no "unknown handle" errors while running 2.6.0

**Comment by derekvanassche** [comment]
To update, noticed in the release notes for 3.1.0 about setting the `privileged` property on custom resource types. Rolling this property change out to our pipelines to see if it addresses our issues.

**Comment by derekvanassche** [comment]
We can reproduce this error by recreating our workers, then run a few jobs in the pipeline, and then iterate through all the resources and run `check-resource` on each of them. The same resource types show an "unknown handle" error until we recreate the worker associated to the handle.

Also we tried removing `garden.default_container_grace_time` from our deployment manifest as suggested in https://github.com/concourse/concourse/issues/1255 but it had no effect, same errors continue regardless of this setting.

**Comment by brandon-bethke-neudesic** [comment]
This 'unknown handle' issue on the resource check happens frequently for us. We are using built-in and custom resources and it happens on both. We are running 3.5.0. 
Taken from the web ui logs

```
{"timestamp":"1508531599.956529617","source":"atc","message":"atc.syncer.mypipeline:radar.scan-resource-type.interval-runner.tick.failed-to-lookup-created-container-in-garden","log_level":2,"data":{"container":"ad
17fd56-5c08-4f9f-405c-e4b9bda57db7","error":"unknown handle: ad17fd56-5c08-4f9f-405c-e4b9bda57db7","pipeline-scoped-name":"mypipeline:resource-type:health-status-file","session":"16.7.41.1.12"}}
"timestamp":"1508531599.956656218","source":"atc","message":"atc.syncer.mypipeline:radar.scan-resource-type.interval-runner.tick.failed-to-initialize-new-container","log_level":2,"data":{"error":"unknown handle: 
ad17fd56-5c08-4f9f-405c-e4b9bda57db7","pipeline-scoped-name":"mypipeline:resource-type:health-status-file","session":"16.7.41.1.12"}}
{"timestamp":"1508531599.957147360","source":"atc","message":"atc.syncer.mypipeline:radar.scanresources-runner-error","log_level":1,"data":{"error":{"Handle":"ad17fd56-5c08-4f9f-405c-e4b9bda57db7"},"session":"16.7
"}}
```

**Comment by brandon-bethke-neudesic** [comment]
Using the latest helm chart. I see this error in the pod history.

```
Liveness probe failed: Fatal error detected: {"timestamp":"15
08540130.715145588","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: 50b62307-38e8-4e35-73e2-1e0e52351e1c","handle":"50b62307-38e8-4e35-73e2-1e0e52351e1c","session":
"3.1.59"}}
{"timestamp":"1508540130.735813379","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: a7f70aa9-2e0b-4f87-5288-eb251fcbdc5c","handle":"a7f70aa9-2e0b-4f87-5288-eb251fcb
dc5c","session":"3.1.61"}}
{"timestamp":"1508540130.767119408","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: a47da79e-ffa7-4c08-43a8-92bf1e2c5e76","handle":"a47da79e-ffa7-4c08-43a8-92bf1e2c
5e76","session":"3.1.64"}}
{"timestamp":"1508540130.807168007","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: 99bbce09-12ee-4f6b-73d6-0e44813f1a94","handle":"99bbce09-12ee-4f6b-73d6-0e44813f
1a94","session":"3.1.65"}}
{"timestamp":"1508540130.807623625","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: f162c9ad-ed3f-431e-55ee-d7622d68853e","handle":"f162c9ad-ed3f-431e-55ee-d7622d68
853e","session":"3.1.66"}}
```

**Comment by derekvanassche** [comment]
To update on this, we are able to reproduce the issue with a simple pipeline configuration that uses the standard Git resource:
`---
groups:
- name: master
  jobs:
  - master-dependencies-test
resources:
- name: master-cheetah
  type: git
  source:
    branch: master
    private_key: REDACTED
    uri: REDACTED
  check_every: 24000h
jobs:
- name: master-dependencies-test
  serial: true
  plan:
  - get: master-cheetah
    trigger: true
  build_logs_to_retain: 50
`

We are also only able to reproduce `unknown handle` errors on our Bosh environment in both 3.3.4 and 3.5.0. After quickly spinning up a Concourse 3.5.0 instance in Docker Compose, we do not see the same errors.

Here are the steps that we use to reproduce this issue on our Bosh environment:
1. Send the pipeline to our Concourse instance.
1. Run `fly check-resource` on the master-cheetah resource. A success response usually returns.
1. Wait a half an hour (<-- the exact timing here seems to vary, but a half hour is usually a safe bet).
1. Run `fly check-resource` on the master-cheetah resource again. This time it returns an "Unexpected Response 500 Internal Server Error".

This impacts us because we have several Concourse instances still on version 2.6.0 that we would like to upgrade to one of the version 3 releases. However, `unknown handle` prevents this because it affects our Git hooks to auto-trigger deployment jobs and for the jobs that do trigger causes them to stay in a "pending" state until someone restarts the affected worker or the error resolves itself (which seems to take upwards of a half hour).

**Comment by derekvanassche** [comment]
We were able to address our `unknown handle` errors by making the following configuration changes:
* Removing the `default_container_grace_time` garden configuration so that the default of 0 applied as suggested in https://github.com/concourse/concourse/issues/1255.
* Override our volume `driver` baggageclaim configuration to use `btrfs`.
