### ISSUE TITLE
Expand Teams integration with CF UAA to SpaceManagers and SpaceAuditors

### ISSUE THREAD

**Issue by chomipi** [concourse/concourse#1722]
**Feature Request:** Expand Teams integration with CF UAA to SpaceManagers and SpaceAuditors

Currently using Concourse v3.5 with PCF 1.10. We have discovered that Concourse Teams authentication is only successful for users with SpaceDeveloper access to the mapped space in PCF. We require the ability for SpaceManagers and SpaceAuditors to be able to authenticate successfully into the Team.

**Comment by jama-pivotal** [comment]
Closing because its not applicable now in 4.x user scheme
