### ISSUE TITLE
Workers seem to slow and become unresponsive

### ISSUE THREAD

**Issue by jkunzelman** [concourse/concourse#1724]
I'm running concourse in docker on a dedicated i7 mac mini. Concourse seems to take a long time doing a build that should only take a few minutes. I have builds that seem to wait 10 - 20 minutes stuck at the git resource or waiting to start the job task. I've reloaded docker and reinstalled docker and concourse fresh a few times with no change. 

* Concourse version:

Latest: 3.5.0
* Deployment type (BOSH/Docker/binary):
Docker
* Infrastructure/IaaS:
Mac
* Browser (if applicable):
Safari and chrome
* Did this used to work?
Yes prior to upgrading to 3.5.0 i did not get this issue.

**Comment by vito** [comment]
We can't really do much about "it's too slow" - it's way too open-ended and would be a guessing game as to why. It could be your hardware, your network, a change we've made (but we don't know what you've upgraded from), it could be the server your pipeline talks to, etc.

Random guess: try switching your worker's Baggageclaim driver to `btrfs`.

**Comment by aphillipo** [comment]
Yes, we too have this issue.
