### ISSUE TITLE
Azure Documentation

### ISSUE THREAD

**Issue by sedouard** [concourse/concourse#173]
Hey there!

The BOSH azure cpi is nearly released and I actually have concourse running on azure, testing BOSH azure cpi. I wanted to share my instructions but I don't have any idea how to render these *.any files in the documentation to look like that of concourse.ci docs.

Can you point me to instructions on doing that?

**Comment by sedouard** [comment]
Here's the initial pull request with the details. I'm not sure what this looks like on the page.

https://github.com/concourse/concourse/pull/174/files

Any commit style guidelines I should follow?

**Comment by vito** [comment]
Closing this to consolidate discussion to the PR.
