### ISSUE TITLE
Sticky Top Nav on the dashboard view

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1730]
Hoping to modify the top nav on the dashboard view to stick at the top of the screen as the user scrolls, but to also incorporate the team name into the toolbar so you can see what team you're on as you scroll. 

Incorporate a nice fade in transition.

**Comment by jama-pivotal** [comment]
@Lindsayauchin lets try a different version with the team name sticky but not in the actual primary nav bar

**Comment by Lindsayauchin** [comment]
![dashboard_hoverstate_job_url_legend](https://user-images.githubusercontent.com/27746614/32190915-b7df684c-bd85-11e7-8278-3b4921a0dd74.png)
![dashboard_team-name_top_nav_sticky scroll](https://user-images.githubusercontent.com/27746614/32190916-b7ec14c0-bd85-11e7-88cb-4cecbe66331d.png)

**Comment by mhuangpivotal** [comment]
We decided to not do the transparent background and fade in transition. 
<img width="1265" alt="screen shot 2017-11-16 at 12 26 08 pm" src="https://user-images.githubusercontent.com/1919762/32905949-843ea740-cac9-11e7-8502-e9f51fa94e3f.png">


Let us know what you think @Lindsayauchin.
