### ISSUE TITLE
Github OAuth team login issue

### ISSUE THREAD

**Issue by LeePorte** [concourse/concourse#1732]
# Bug Report

I have attempted to add Github OAuth using our team. When the team is added logging in fails with the following error

```
{"timestamp":"1508488863.277710438","source":"atc","message":"atc.oauth-callback.callback.verify.not-in-teams","log_level":1,"data":{"have":{},"session":"12.3.1","want":[{"Name":"[team] Government PaaS - People","Organization":"alphagov"}]}}
{"timestamp":"1508488863.711165905","source":"atc","message":"atc.oauth-callback.callback.verify.not-in-organizations","log_level":1,"data":{"have":[],"session":"12.3.1","want":null}}
```

The command used to add the team was;

```
                  fly -t dev set-team -n dev \
                    --github-auth-client-id ${GITHUB_CLIENT_ID} \
                    --github-auth-client-secret ${GITHUB_CLIENT_SECRET}  \
                    --github-auth-team "alphagov/[team] Government PaaS - People"
```
If I add myself by appending `--github-auth-user LeePorte` to the command logging in succeeds. However, atc.oauth-callback.callback.verify.not-in-teams still has an empty array.

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): Bosh
* Infrastructure/IaaS: IaaS AWS
* Browser (if applicable): Chrome
* Did this used to work? Unsure

**Comment by vito** [comment]
We can't really fix this to be honest; we know team-based auth works (we use it ourselves), so this is likely working as intended and your GitHub membership may not be configured correctly.
