### ISSUE TITLE
readonly permission on atc database with postgresql

### ISSUE THREAD

**Issue by gdenn** [concourse/concourse#1733]
# Bug Report
## Problem description
When i try to upload a pipeline to my concourse server using `fly -t my_concourse sp -p test_pipeline -c my_validated_config -l my_credentials` i receive the following error message `failed to save config: pq: cannot execute INSERT in a read-only transaction`.
Furthermore the atc job in the web worker is failing. The log under `var/vcap/sys/log/atc/*` responds with `failed to migrate database: pq: cannot execute CREATE TABLE in a read-only transaction`.

## What i found out
first of i checked if the consul dns responds with the correct postgresql master node ip, which was working fine.
Then i checked the permissions of the atc database in our postgresql. These have been set correctly as well. Finally i used the atc database user to manually insert an entry in the pipelines table of the atc database. Everything worked as it should.

Furthermore all other services that use the postgresql cluster are not responding with any errors. At this moment i guess that the problem is within the atc but i don't know how to debug the problem further.

## What i tried
- I restarted the web job
- I restarted all workers
- I redeployed the Concourse cluster with the same config.

## My System
* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): BOSH cluster with postgresql cluster and consul-dns cluster
* Infrastructure/IaaS: vSphere

best,

**Comment by vito** [comment]
I don't know what this would mean. Concourse doesn't do anything fancy with Postgres (I didn't even know it had read-only transactions), we just use it.

**Comment by gdenn** [comment]
Hi this ticket can be closed, the problem was within the pg cluster-
