### ISSUE TITLE
Fix "worker gravity": Allow more random scheduling of jobs/tasks across workers

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1741]
Our concourse cluster has longs suffered from resource intensive jobs repeatedly gravitating towards a single worker in the cluster over time. This worker then does the majority of jobs, while the rest of the cluster sits idle. 

As a result, our Concourse Cluster requires too much baby sitting: "No space left on device", garden failing to allocate virtual networks etc. are all symptoms caused by this. Others have repeatedly reported similar issues: https://github.com/concourse/concourse/issues/675

Now, we totally love Concourse and since my first golang endeavour (extending the [concourse-swift-resource](https://github.com/Meshcloud/concourse-swift-resource)) went quite well I took the plunge in to the ATC code and tried to figure out how Concourse actually schedules jobs and tasks. 

I think I traced the important bit down to https://github.com/concourse/atc/blob/master/worker/pool.go#L123

As I understand it, the way scheduling works is this:
- for a "ContainerSpec" that details what the container needs (e.g. worker platform, tags, input volumes), find all compatible workers 
- then calculate for each worker, how many of the required inputs are already on that worker
- put those workers into buckets by matching input volume count (e.g. [A,B : 2 volumes], [C: 0 volumes]
- from the bucket with the highest amount of available volumes, select a random worker. 

I think that explains why we see containers in the cluster "gravitating" towards a single worker. Probably also affected by GC of volumes, at some point in time one worker has more volumes left on it than another one. As a consequence, Concourse will schedule jobs/tasks preferably on that worker. Which leads it to have even more resource volumes available on it over time, getting even more jobs ... yadda yadda -> 🔥 

When we reset our three workers they start out with a fairly even distribution of volumes and consequently disk usage. After a couple of days, we would see that a only one worker would do the majority of the work in the cluster and we'd see its disk usage go through the roof. 

While I understand the reason for this scheduling logic (avoid moving inputs unnecessarily through the cluster, and in general increasing locality) I think it creates a sub-optimal distribution of jobs, especially in the long run. Of course, this "gravity" may be a problem that only affects our cluster so badly due to the particular config of the ~20 pipelines that we run. Nonetheless, I think I'd appreciate if there'd be a choice for "more random" scheduling. 

Especially in small clusters, more random scheduling has other benefits. For example, we have a build step that has an `aggregate` step for running 4 quite heavy integration tests suites in parallel. We'd love to see that work spread out across the cluster, however in reality all the 4 tasks get scheduled in parallel on the same worker, because the previous build step on that worker produced all the necessary input volumes. That means at the time of scheduling these 4 tasks, there's only one worker in the cluster that has a matching input volume count of 1, while all others have a 0. 

How to fix this? I have a couple of ideas: 
- allow fully random distribution (probably bad, but an option if configurable) 
- use  "range" buckets with a coarser granularity. E.g. so that workers that have between 0-2, 2-4 etc. matching volumes get thrown into the same bucket. 

Of course, this assessment may be totally wrong, but any input by the experts on the ATC's scheduler is welcome. I'd be happy to try it if we can make e.g. an experimental configuration option.

**Comment by topherbullock** [comment]
Merged in concourse/atc#219 which addresses this issue.

**Comment by JohannesRudolph** [comment]
Cool. Any idea on when we'll see this in a concourse release?

Am 13.11.2017 9:46 PM schrieb "Topher Bullock" <notifications@github.com>:

**Comment by marco-m** [comment]
For people coming to this ticket, the summary of concourse/atc#219 which fixes this issue is:

ATC has now option `--container-placement-strategy`.

Run `concourse web -h` to see the currently available values:

```
--container-placement-strategy=[volume-locality|random]
    Method by which a worker is selected during container placement. (default: volume-locality)
    [$CONCOURSE_CONTAINER_PLACEMENT_STRATEGY]
```
