### ISSUE TITLE
concourse starts with invalid external URL

### ISSUE THREAD

**Issue by bcwaldon** [concourse/concourse#1742]
# Bug Report

I was able to get a cluster up and running fairly rapidly, but I initially ran into trouble in trying to use the gitlab-merge-request-resource. I was seeing the same error when trying to put the resource as reported here: https://github.com/concourse/concourse/issues/921. I sanity-checked my deployment, asserting I was setting `CONCOURSE_EXTERNAL_URL` in the web container. I also took a shot in the dark and set the env vars `CONCOURSE_EXTERNAL_URL` and `ATC_EXTERNAL_URL` in my worker containers, but I could not get around the unbound variable error. I could see the build metadata being set, so I moved on to revisit this issue another day.

That day was today - I started poking at `fly execute`. I immediately ran into issues when trying to use the `--input` flag. The issue was not encountered when I tried the `--input-from` flag. The error message I saw looked like this:

```
download request failed: Get /api/v1/pipes/1aa972ea-512e-4203-63d6-406ca751f528: unsupported protocol scheme ""
```

I write enough golang that this felt familiar to me - somewhere a bare path is being passed around instead of a full URL. Looking at the API responses, I took a guess that the read_url or write_url fields from the `POST /api/v1/pipes` response were the culprit:

```
2017/10/24 11:46:26 POST /api/v1/pipes HTTP/1.1
Host: <REDACTED>
User-Agent: Go-http-client/1.1
Content-Length: 0
Accept-Encoding: gzip


2017/10/24 11:46:26 HTTP/1.1 201 Created
Content-Length: 175
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Tue, 24 Oct 2017 18:46:26 GMT
Server: nginx/1.13.5
X-Concourse-Version: 3.5.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block

{"id":"1aa972ea-512e-4203-63d6-406ca751f528","read_url":"/api/v1/pipes/1aa972ea-512e-4203-63d6-406ca751f528","write_url":"/api/v1/pipes/1aa972ea-512e-4203-63d6-406ca751f528"}
```

I confirmed that `fly`/`go-concourse` were passing around `read_url` verbatim, which, based on the output above would produce the scheme-related error message I received.

I dug back through the `atc` code and it appeared that `--external-url` was simply not being set. I confirmed that I was setting the `CONCOURSE_EXTERNAL_URL` environment variable, but I realized I had set the value to a bare hostname (e.g. `example.com`), not a base URL (e.g. `http://example.com`).

I redeployed the web nodes, prepending a scheme to `CONCOURSE_EXTERNAL_URL` and all was fixed: I can now use `fly execute --input` and `ATC_EXTERNAL_URL` is available when gitlab-merge-request-resource is invoked.

I would ask that `concourse web` is not allowed to start up and bind if it does not have a valid `CONCOURSE_EXTERNAL_URL`.

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): Docker (via Kubernetes)
* Infrastructure/IaaS: AWS

**Comment by jtarchie** [comment]
@bcwaldon, This is would make a great PR! 😉

**Comment by vito** [comment]
Folding into https://github.com/concourse/concourse/issues/1668
