### ISSUE TITLE
General description of architecture and explanation of how each distribution sets things up

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1744]
# Feature Request

## What challenge are you facing?

There's frequent confusion around things like:

* Setting up Houdini/Baggageclaim/other things done automatically for you with the binaries.
* Which components need to talk to which other ones.
* What components scale horizontally or only scale for HA.
* How to configure a load balancer (so that build events can stream and intercepting can work).
* How to upgrade workers.
* How to upgrade everything else.

Some distributions automate portions of this and some others don't (e.g. BOSH vs. binaries). A lot of people don't realize that the binaries *embed* houdini and baggageclaim, and may be misled by out-of-date blog posts and such - most users shouldn't even know/care what Houdini is.

(Full disclosure: this is something I felt passionately about like 2 days ago but I don't quite feel like I captured the idea here. I may come back and edit this with more concrete direction/examples.)

## A Modest Proposal

Let's revamp our architecture docs to cover the *requirements* of a running Concourse installation, without mentioning BOSH, binaries, or *anything*. Then, for each distribution, let's have a slimmer document that simply outlines how it accomplishes those architectural goals, or which aspects it leaves to the user (e.g. the binaries don't automate draining, but the BOSH release does).

**Comment by marco-m** [comment]
Thanks for creating this task. For me, this documentation is more important than any other feature or bug fix. ❤️

**Comment by christophermancini** [comment]
This is a good thing to have a consistent strategy for. Most users will only care about specifics for their environment and trying to get them that information without lots of duplicate effort will be a challenge but will offer a better UX.

**Comment by marco-m** [comment]
Hello @cirocosta, for my understanding, is this closed as done or and wontdo ?

**Comment by cirocosta** [comment]
Hey @marco-m , whoops, sorry for not putting the context on why closing it.

Closed more because of the improvements that were made to the [install section](https://concourse-ci.org/install.html) aside from the current [architecture](https://concourse-ci.org/architecture.html) page in the docs - moving forward, we could then have more specific issues under `concourse/docs` as people see need.

Wdyt?

thanks!

**Comment by marco-m** [comment]
Thanks! That's fine for me :-)
