### ISSUE TITLE
Trigger build shortcut should not allow key repeat

### ISSUE THREAD

**Issue by avanier** [concourse/concourse#1749]
# Feature Request

## What challenge are you facing?

With the introduciton of keyboard shortcuts in `3.6.0`, should one keep `T` pressed while in a build page, an alarming amount of builds may be trigerred. _(Yay! I'm testing autoscaling today!)_

## A Modest Proposal

We should debounce certain key presses. A pressed key should not repeat for the _trigger build_ function.

## Post Scriptum

The keyboard shortcuts are awesome.

**Comment by jama-pivotal** [comment]
de-bouncing +1 !

Also, maybe its just simpler to register the action on-key-release

**Comment by xtremerui** [comment]
FIX in https://github.com/concourse/concourse/commit/9122599654ed6934a7cb9a0e60de158438828897
Miss-spell in the commit message so github didn't pick up automatically

**Comment by jama-pivotal** [comment]
neat, works
