### ISSUE TITLE
fly CLI: add option to disable ANSI color codes

### ISSUE THREAD

**Issue by zmb3** [concourse/concourse#1750]
# Feature Request

Related to #1090 - but rather than auto-detecting when to omit color codes (based on the terminal or whether or not stdout is a TTY), we should also allow the user to manually opt out of colors when using the CLI. 

Note: the diff view you see when running a `set-pipeline` command uses colors alone to identify the diff.  We would probably need another way to render diffs when color is disabled.  

For inspiration, bosh supports a `--no-color` option, and its diffs use `+` and `-` characters to identify additions/removals.

**Comment by shashwathi** [comment]
@zmb3 : Added support for `--no-color` flag and used `+` and `-` to show the config difference.

**Comment by jama-pivotal** [comment]
My Canadian sensibilities wanted to reject this for being `color` and not `coloUr`...OH WELL

**Comment by mhuangpivotal** [comment]
@jama-pivotal @shashwathi We are seeing `+` and `-` characters even when we have colours enabled. From the release notes:

> The fly set-pipeline command can now be given --no-color flag to strip out the color from the diffs. Instead of using color, + and - will be at the start of added and removed lines.

It sounds like we should only display `+` and `-` when the option is set.

**Comment by speculatrix** [comment]
I would like the option to force colourisation ON as well as off, so I can redirect output to a file and then when I view the file still get the colours.
