### ISSUE TITLE
Workers should be smart enough not to fill up their disk

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse#1751]
# Feature Request

The disk on our workers filled up to total capacity, and rather than do anything to try to mitigate the issue, concourse continued on as normal and every job would fail with a `lack of disk space` error. We had to recreate the workers to get around this, and we already have massive disks and don't really want to get larger ones.

# A modest proposal

Baggage claim should tell the atc a worker is about to run out of disk space and the atc should orchestrate the deletion of some volumes.
 
The following can also be handy:

* Concourse version: 3.4.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): N/A
* Did this used to work? no

**Comment by JohannesRudolph** [comment]
Related: https://github.com/concourse/concourse/issues/1741

**Comment by vito** [comment]
I'm concerned that this would be super complicated to implement and not really be as effective as you'd hope.

* The root of the problem is that your disk is filling up. We should make sure to understand *that* before we do something this complicated. Where is the space going? Do you have a misbehaving task? Is your workload simply higher than expected? Would this be helped by using e.g. `btrfs` instead of `overlay`? Are there caches being created but then never used?
* There's no guarantee that we'll even be able to free up enough space to not have it be a chronic scheduling/GC burden. This may just mask the issue, or be completely ineffective. A common and obvious failure with a known resolution could end up being replaced by an indirect one that's harder to diagnose and surprising to some people.

In general, I prefer software to just "fail fast and fail loudly". I would rather get to the root of the issue first.

**Comment by thardeck** [comment]
We have the issue that we have to recreate the workers the latest after two weeks often even earlier even though we had around 80 GB and now even 120 GB.

It is not that bad because Concourse is released often so a cleanup happens often indirectly but still Concourse should be able to run for some time without manual interaction.

And a cache should be treated as a cache so if it takes too much space the longest untouched parts should be dropped to not make the whole worker unusable until an admin runs `--recreate`.

**Comment by phillbaker** [comment]
There might be more that comes out of #1457, but this is a (wholly unsanctioned and gross) script to periodically free up diskspace used by btrfs (run as binaries on aws VMs) 🙈 :

```sh
# as root
service concourse-worker stop # and ensure all concourse processes stopped
umount -fl /opt/concourseci/worker/volumes
sync
losetup -d /dev/loop0
rm -rf /opt/concourseci/worker/volumes.img
systemctl reboot
```

**Comment by codesuki** [comment]
Is there any update on this? 
We experience the same problem. Every few weeks we run out of disk space. Checking with `fly images` shows that old data still seems to be there, instead of being garbage collected. 
Is there an overview of the rules of when something will be garbage collected?
The worker now has 1250 containers but only runs 2 pipelines (one being very small).
I wonder if this is a problem with the GC or a problem of the pipeline configuration that results in some containers never being marked for GC.

**Comment by codesuki** [comment]
In our case this might be the reason: 
```
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(192467, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))

**Comment by phillbaker** [comment]
This may be helped by the work in #1959, but @vito would it be appropriate to move workers to the `stalled` state (or maybe an `errored` state?) if (a) job(s) fail for reasons of `failed to create volume` or `failed to stream in to volume`?

**Comment by keithkroeger** [comment]
This continues in 3.9.2

**Comment by cfasnacht** [comment]
This is still an issue with 4.14.1

**Comment by AndrewMorsillo** [comment]
This is still an issue with 4.2.1. I only have 1 pipeline and I'm using btrfs but it appears that images are never garbage collected. Eventually my 200gb volume fills up on k8s and the easiest way to deal with it is to actually purge and reinstall concourse via helm.

**Comment by ralekseenkov** [comment]
@AndrewMorsillo we ran out of 128gb on Kubernetes PV too and had to temporarily increase the size to 256gb.

are you running ephemeral or not? if an ephemeral worker goes away, TSA purges it from the database, but its containers and volumes keep laying around on Kubernetes PV. so even if it comes back later, there are still orphan containers and volumes. this is an issue for sure... if you are not using ephemeral though, there may be another issue.

**Comment by AndrewMorsillo** [comment]
I'm not quite sure what you mean by ephermal. I only have a single worker and I never delete it. I'm using a very vanilla deployment of the helm chart. Here is the configuration.

```
concourse:
  worker:
    baggageclaim:
      driver: btrfs
  web:
    externalUrl: "http://my-url-goes-here"
    auth:
      mainTeam:
        localUser: "concourse"
secrets:
  localUsers: "concourse:hashedpassword"
web:
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    hosts:
      - my.host.here
    tls:
      - secretName: my-cert-secret
        hosts:
          - my.host.here
  resources:
    requests:
      cpu: "100m"
  extraEnv:
    - name: HELM_HOST
      value: tiller-deploy.kube-system:44134
worker:
  resources:
    requests:
      cpu: 2
      memory: 4000Mi
  replicas: 1
  env:
    - name: HELM_HOST
      value: tiller-deploy.kube-system:44134
persistence:
  worker:
    size: 200Gi
    storageClass: ssdclass
```

**Comment by ralekseenkov** [comment]
@AndrewMorsillo I meant this by ephemeral https://github.com/concourse/atc/pull/247 and https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L478

sounds like you are having another issue though and we might have it too. so you have 1 pipeline and many versions of the same docker image getting checked/pulled in by a resource?

**Comment by cirocosta** [comment]
Hey @ralekseenkov, @kurlzor, and @andrewedstrom ,

Regarding the state of k8s on Concourse and their corresponding disk issues, we've been working on that in separate issues:

- [[stable/concourse] Replaces worker StatefulSet by Deployment](https://github.com/helm/charts/pull/9668) - an idea about making workers be totally "ephemeral"-first;
- https://github.com/concourse/concourse/issues/3104 for including scenarios in our tests to verify possible disk images leaks w/ bttrfs; and 
- https://github.com/concourse/concourse/issues/3091 to possibly remediate leaks that might happen.

Your input, especially on the first one, would be much appreciated!

Thanks!

**Comment by 2rojan** [comment]
Concourse Version 5.2.0
Running in Kubernetes
Baggage Claim driver: OVERLAY

Running out of disk on workers daily, sometimes multiple times a day. 

Couldn't give an exact number of teams/pipelines/jobs/tasks as I haven't found a good way to get that info from the tool - a rough guess would be probably 200 or so pipes, its hard to tell, most aren't exposed.

I have 12 workers, each running 6 CPUs, 65GB Mem and 300GB gp2 pvc disc. 
accessmode: ReadWriteOnce <-- could be the issue?

Dialed resource polling back from every 1 min to  every 1h <-- polling was crushing github - had github reporting polling rates nearly 100,000 over 24 hours 
Fly 5 seems to have dropped "retire-workers" from the cli and "land-workers" is not as helpful as we would like, <-- "lands" for about 3 minutes, only manages to scuttle a small number of containers then goes back to running - so, breaking out the big hammer, kubectl delete pods <--workers do not seem to be getting the shut down signal, SIGUSR2, causing corrupted pvc that needs deleted before worker will successfully restart.
We can't keep running 3.6 TB of storage just for cached "stuff" - Either something is badly misconfigured (very possible) or we need a way to make worker containers more ephemeral, or better scheduling or something. 
I had hoped that maybe 5.3 might address some of this, but I see that task-caches are now decoupled from workers (which would be great, except for the duplicates).

Any thoughts? Things to look at? Things to try?

**Comment by damzog** [comment]
```
worker/efe9e75c-269e-4ac1-93ec-56b973d1920d:/var/vcap/data# du -h | grep G

...
332K	./packages/xfs-progs/8de8f3db35ba3333015db179eabe16e1b38b25f6/share/locale/de/LC_MESSAGES
404K	./packages/xfs-progs/8de8f3db35ba3333015db179eabe16e1b38b25f6/share/locale/pl/LC_MESSAGES
1.3G	./packages
237G	.
worker/efe9e75c-269e-4ac1-93ec-56b973d1920d:/var/vcap/data# cd baggageclaim/
worker/efe9e75c-269e-4ac1-93ec-56b973d1920d:/var/vcap/data/baggageclaim# ls
overlays  volumes  volumes.img
worker/efe9e75c-269e-4ac1-93ec-56b973d1920d:/var/vcap/data/baggageclaim# ls -rlt
total 236835156
drwxr-xr-x 2 root root         4096 May 29 08:03 overlays
drwxr-xr-x 1 root root           24 May 29 08:03 volumes
-rw-r--r-- 1 root root 243085062144 Jun 27 14:54 volumes.img
worker/efe9e75c-269e-4ac1-93ec-56b973d1920d:/var/vcap/data/baggageclaim# ls -rlt
total 236835156
drwxr-xr-x 2 root root         4096 May 29 08:03 overlays
drwxr-xr-x 1 root root           24 May 29 08:03 volumes
-rw-r--r-- 1 root root 243085062144 Jun 27 14:55 volumes.img
```

**Comment by benjoyce** [comment]
Hi.  This is happening in 5.3.0.  Even with a relatively small number of active containers (3) and around 35 volumes, the *actual* volumes under /var/vcap/data/worker/work/volumes is around 237 and consumes the majority of the allocated disk space, resulting in "failed to create volume" as the error for all resources and pipelines.

Recreating the worker resolves this but it does feel like an problem with GC.  I'm seeing volumes created 5 days ago.

**Comment by ddadlani** [comment]
Hi @benjoyce, there is a known issue with the default `btrfs` baggageclaim driver where GC gets queued but may never actually occur. Could you try switching the baggageclaim driver to `overlay` and see if the issue still occurs?

**Comment by p-manesh** [comment]
Having similar issue. Jobs error out when tasks fail with "failed to create volume" message

build-test-workers/deaf44c7-1905-4d6c-b899-58fe280e305d:/var/vcap/data/worker/work/volumes/live$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs            16G   32M   16G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/nvme1n1p1   30G  1.5G   27G   6% /
/dev/nvme0n1p2  167G  156G  2.4G  99% /var/vcap/data
tmpfs           1.0M   12K 1012K   2% /var/vcap/data/sys/run
/dev/loop0      157G  154G     0 100% /var/vcap/data/worker/work/volumes

Concourse Version 5.2.0
Deployment: BOSH
Baggage Claim driver: btrfs

When the disk is full all baggage-claim jobs fail with error message like:

{"timestamp":"2019-08-02T16:09:24.192082866Z","level":"info","source":"worker","message":"worker.volume-sweeper.tick.destroy-volumes.failed-volume-deletion","data":{"session":"7.902.190","status":500}}
{"timestamp":"2019-08-02T16:09:24.192092272Z","level":"error","source":"worker","message":"worker.volume-sweeper.tick.failed-to-destroy-volume","data":{"error":"failed-to-delete-volume","handle":"e8381664-88fb-4090-75f4-a6cf8871b7a8","session":"7.902"}}
{"timestamp":"2019-08-02T16:09:24.192121969Z","level":"error","source":"worker","message":"worker.volume-sweeper.tick.failed-to-destroy-volume","data":{"error":"failed-to-delete-volume","handle":"5c60ac8a-a748-4f19-6ed6-65318479e0d7","session":"7.902"}}
{"timestamp":"2019-08-02T16:09:24.192234587Z","level":"error","source":"baggageclaim","message":"baggageclaim.api.volume-server.destroy.destroy-volume.failed-to-destroy","data":{"error":"rename /var/vcap/data/worker/work/volumes/live/010455c8-f715-4d0c-5bce-cfdd1c07632f /var/vcap/data/worker/work/volumes/dead/010455c8-f715-4d0c-5bce-cfdd1c07632f: no space left on device","session":"5.1.32388.1","volume":"010455c8-f715-4d0c-5bce-cfdd1c07632f"}}
{"timestamp":"2019-08-02T16:09:24.192256909Z","level":"error","source":"baggageclaim","message":"baggageclaim.api.volume-server.destroy.failed-to-destroy","data":{"error":"rename /var/vcap/data/worker/work/volumes/live/010455c8-f715-4d0c-5bce-cfdd1c07632f /var/vcap/data/worker/work/volumes/dead/010455c8-f715-4d0c-5bce-cfdd1c07632f: no space left on device","session":"5.1.32388","volume":"010455c8-f715-4d0c-5bce-cfdd1c07632f"}}

It is not able to clean the containers for failed/aborted jobs 

Only way is to recreate the worker. 

Is there any fix/workaround?

**Comment by ddadlani** [comment]
Hi @p-manesh, what you are seeing with a failure to clean volumes is a known `btrfs` error. If you switch your workers to using `overlay` as the baggageclaim driver, this should not occur

**Comment by p-manesh** [comment]
Hi @ddadlani we tested with overlay it seems to clean volumes. Is there documentation of pros and cons of using overlay vs btrfs baggageclaim driver. Anything we should check before moving from btrfs to overlay?

**Comment by ddadlani** [comment]
Overlay takes a longer time to create privileged volumes, so if you are using a lot of privileged containers you may see a performance hit in terms of step initialization. In practice, if you don't have too many privileged tasks/steps it isn't a big issue.

**Comment by nmiculinic** [comment]
I have the same issue with the overlay driver as well. Version `5.4.1` The 100GB disk gets filled up in a couple of weeks instead of cleaning up the garbage.

**Comment by ddadlani** [comment]
@nmiculinic that seems odd. We haven't seen that on our internal environments. How many pipelines are you running? Do you have large resources in them? Is it possible that 100GB is too small for your workload?

**Comment by nmiculinic** [comment]
Not possible; 100GB is plentiful. We're talking about 100ish pipelines over the last month or two. Not large resources to speak off....mostly they test the kubernetes operator, and all k8s clusters were created via terraform. (( Previously there was some privileged containers using kind, and docker in docker shenanigans )).

I've deleted and restarted the concourse workers, though I can c/p the logs as soon as I verify no sensitive data in them.

**Comment by ddadlani** [comment]
@nmiculinic I need more information about your setup. What do you use to deploy Concourse? What do you mean by 100ish pipelines? IE are they constantly running, or do you leave them paused? How many resources (approximately) are there across your entire deployment? Do you have any tasks that download a lot of things? E.g. maybe a builder task that installs `go`. 

If you go into the volumes directory (on BOSH-deployed Concourse it is `/var/vcap/data/worker/work/volumes`) and run `du` what is the output?

**Comment by nmiculinic** [comment]
> What do you use to deploy Concourse?

helm chart for the control plane, ansible for the worker (( on VM )). The worker config is as follows:

```
[Unit]
Description=Concourse worker
Documentation=https://concourse-ci.org
After=network.target

[Service]
ExecStart=/usr/local/concourse/bin/concourse worker \
    --work-dir /opt/concourse/worker/ \
    --tsa-worker-private-key /etc/concourse/worker_key \
    --tsa-host {{ tsa_host }} \
    --garden-bin /usr/local/concourse/bin/gdn \
    --garden-config /etc/concourse/config.ini \
    --baggageclaim-driver=overlay \
    --ephemeral \
    --tsa-public-key /etc/concourse/tsa_host_key.pub 

Restart=always
RestartSec=10s
LimitNOFILE=40000

[Install]
WantedBy=multi-user.target
```

> What do you mean by 100ish pipelines?

You're right...we only have 2 pipelines, which in total have about 100ish jobs per month. (( that is build executions )). What I mean by that is that we're really sparse. They are not running continuously, but mostly on the PRs. 

Now as the development picked up again with proper CI we're expecting about 100ish run per week, +-. 

> How many resources (approximately) are there across your entire deployment?

Worker VM is on GCP, n1-standard-2 (2 vCPUs, 7.5 GB memory)
Control plane components are inside GKE, on the n1-standard-1 (1 vCPU, 3.75 GB memory) node. The GKE cluster only has concourse running on it. 

> Do you have any tasks that download a lot of things? E.g. maybe a builder task that installs go.

There are building go modules, though it should be properly cached. Abbreviated this is the config:

```
#!/bin/bash

set -e -u -x

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd repo

make lint
make test
make build 

du -sh ${GOPATH}
```

and the config:
```
---
platform: linux

image_resource:
  type: registry-image
  source: {repository: << repo >> }

inputs:
- name: << repo >>

caches:
- path: gopath/

run:
  path: repo/unit.sh

```
There's an additional few jobs/pipelines but they are less frequent. 


Let's first start with `df -h`

```
root@concourse-worker:/home/lpp# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.7G     0  3.7G   0% /dev
tmpfs           748M  1.5M  746M   1% /run
/dev/sda1        97G   18G   80G  19% /
tmpfs           3.7G     0  3.7G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/loop0       89M   89M     0 100% /snap/core/7396
/dev/loop1       65M   65M     0 100% /snap/google-cloud-sdk/95
/dev/loop2       61M   61M     0 100% /snap/google-cloud-sdk/94
/dev/loop3       89M   89M     0 100% /snap/core/7270
/dev/sda15      105M  3.6M  101M   4% /boot/efi
overlay          97G   18G   80G  19% /opt/concourse/worker/overlays/a9e4b6b9-1c2a-4635-6d99-7346632da4a5/<< repo >>
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/278100a2-121a-44a5-6ccd-4e42db2c7de8/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/ab7acc1f-42f8-4506-4375-f0e83ed4302b/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/d0432149-c493-40c3-7b04-4f5fabe732fb/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/97045c14-abfa-4f6f-60ad-ba055e9ee9e7/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/e8ae7791-5757-4598-789e-b6bd0f0984ad/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/5f0e4d3d-8d78-4acf-6fbb-e66c8cf2ecff/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/c955f55a-7a83-4be0-77aa-361d37a38d93/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/f5a96132-96c0-4026-6003-d2b0ad08e3cd/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/861ae04a-846c-4080-5a85-17afca87af94/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/db04f52b-f0f0-4594-511d-fbccd4b1d6cd/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/116af8d4-11f4-422e-77af-886b374d5f48/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/0c61174b-703d-45b0-6b89-61ec396cef48/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/95afc7fc-5f63-4b35-6dd3-1d96849fe7d3/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/e6f89811-3a8c-474b-5bcf-93e1221da279/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/9b799e8f-8354-4436-6cab-95ab7ee4c9f6/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/a10effe6-9fa0-48f9-6662-4853cc08c5b3/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/3c86ff31-5ad7-4b17-563f-3a522f27d8e6/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/bcc50ec9-c19f-4789-461a-e817fc394586/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/40ff72e3-5172-4d3f-68d9-e87c2413c45a/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/dccb5880-bee5-43d4-5fef-5289c4e9f2ff/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/54b50763-4e96-455f-7d2e-35f1a52c5397/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/6f922959-3e32-4004-774a-cdeb0c9dceef/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/3c62604b-c84b-454c-7edd-b3af249f0da4/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/6a5f8ca9-0087-4ca6-59e5-3dc1af9c5cac/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/1c80c22e-1813-41fb-7d19-546453ef8a19/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/965ca579-fec7-4fde-6b27-6cb377ad2c42/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/1cd62f8e-e40a-40b0-64d1-5c7ec9c459d5/volume
overlay          97G   18G   80G  19% /opt/concourse/worker/volumes/live/f71b7222-a252-4f23-67b3-bd391ef929ad/volume
tmpfs           748M     0  748M   0% /run/user/1001
```

and running `du` on the `/opt/concourse/worker/volumes` give a huge number of files. Not sure whether it makes sense c/p it here.

**Comment by nmiculinic** [comment]
There are a few jobs (2-3) running at the moment

**Comment by ddadlani** [comment]
@cirocosta Have you seen anything like this on `hush-house`? Do you have any idea why this may be occurring?

**Comment by kcmannem** [comment]
cc @kcmannem

**Comment by phillbaker** [comment]
I would say we have seen secular improvements in this over the last 18 months, however, it is still an issue that should be addressed.

**Comment by austinbv** [comment]
We are running concourse 5.6.0 deployed via helm and our 20Gi worker running the OCI image build is filling up after less than 5 runs.

We have tried both `overlay` and `btrfs` drivers as well as disabling any cache. We still don't see any garbage collection.

Has anyone found a solution?

**Comment by kcmannem** [comment]
@austinbv theres really no solution to this. We don't store any extra data then what you actually need. A 20Gi worker seems very small and I don't know if there any options I can recommend that would suit a small worker like that.

**Comment by AndrewMorsillo** [comment]
I think this is still an issue, not stale

**Comment by austinbv** [comment]
Still not stale

**Comment by vito** [comment]
I'm going to close this issue as it's a bit of a honeypot for anyone that has run out of disk space, while the original ask was for a specific feature - one that is technically complicated to implement and may just mask the underlying problem. This mix of feature requests, bug reports, and troubleshooting into one comment chain has made the issue pretty difficult to address.

These discussions are valuable, but should be framed as Discussions instead (per the [recent announcement](https://blog.concourse-ci.org/nobody-wants-a-stale-bot/)) - especially since those allow for threading. I could convert this to a Discussion, but that currently fires off a bunch of notification spam, and I think it'd be better if we just embrace this issue as the "honeypot" that it is and start off with a lot more guidance on how disk space is used, the characteristics of each volume driver, and how to help us by providing tips for troubleshooting yourself. So, I just put a lot of time into a new Discussion for just that!  https://github.com/concourse/concourse/discussions/5463

I hope that helps! 🙏
