### ISSUE TITLE
Should credhub.tls.insecure_skip_verify be mandatory?

### ISSUE THREAD

**Issue by jhvhs** [concourse/concourse#1754]
# Bug Report

When upgrading the concourse BOSH release from 3.5.0 to 3.6.0,
we have faced a failure:
```
Task 1428 | 21:25:05 | Updating instance concourse: concourse/4be34fd4-ad49-443e-ab62-37972ea0c905 (0) (canary) (00:05:27)
                    L Error: 'concourse/4be34fd4-ad49-443e-ab62-37972ea0c905 (0)' is not running after update. Review logs for failed jobs: atc
Task 1428 | 21:30:32 | Error: 'concourse/4be34fd4-ad49-443e-ab62-37972ea0c905 (0)' is not running after update. Review logs for failed jobs: atc
```

Rolling back to 3.5.0 made concourse available again.

According to the atc logs, the failure was caused by a nil dereference in atc/creds/credhub/manager.go#NewVariablesFactory. The only property
that was missing from our manifest was the `credhub.tls.insecure_skip_verify`,
so we have decided to put it in. To our surprise and delight, the deployment
has succeeded this time.

##Suggestion
It would be nice to have a default value for the flag, so that everyone could 
re-use their existing manifests without any surprises during upgrades.

## Environment
* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH 263.2.0
* Infrastructure/IaaS: GCP
* Did this used to work? yes

**Comment by vito** [comment]
fixed by https://github.com/concourse/atc/pull/213
