### ISSUE TITLE
ATC connecting to Vault via TLS ignores CN

### ISSUE THREAD

**Issue by TimJones** [concourse/concourse#1755]
# Bug Report

When attempting to use Vault as a credentials manager, a self-signed certificate was issued by my private CA for the Vault server. When configuring Concourse to use it, I get the following error

    Put https://vault.devops-tools.svc.cluster.local:8200/v1/auth/approle/login: x509: certificate is valid for vault, localhost, 127.0.0.1, not vault.devops-tools.svc.cluster.local

But the server certificate has a Common Name of `vault.devops-tools.svc.cluster.local`.

    $ openssl x509 -in tls.crt -text -noout
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number:
                fe:7d:3a:3a:ae:aa:63:ad:94:09:89:e8:3f:1f:07:99
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: C = .., ST = ..., L = ..., O = ..., OU = ..., CN = ... --expire 1460
            Validity
                Not Before: Oct 27 11:20:33 2017 GMT
                Not After : Oct 26 11:20:32 2021 GMT
            Subject: C = .., ST = ..., L = ..., O = ..., OU = ..., CN = vault.devops-tools.svc.cluster.local
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)
                    Modulus:
                        ... snip ...
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Key Usage: critical
                    Digital Signature, Key Encipherment
                X509v3 Extended Key Usage: 
                    TLS Web Server Authentication, TLS Web Client Authentication
                X509v3 Subject Key Identifier: 
                    EF:82:AA:2C:A3:71:D7:1B:49:E1:F5:D2:71:19:40:3E:18:30:C9:B1
                X509v3 Authority Key Identifier: 
                    keyid:0C:1E:50:5C:AE:C9:DC:8E:16:0D:0E:10:91:79:30:6B:46:D8:28:D1
    
                X509v3 Subject Alternative Name: 
                    DNS:vault, DNS:localhost, IP Address:127.0.0.1
        Signature Algorithm: sha256WithRSAEncryption
             ... snip ...

You can see that the certificate has a common name matching the configured server name in Concourse, as well as several Subject Alt Names for ease-of-use. Assuming Concourse uses regular TLS libraries, I'm not entirely sure why the CN is being ignored by Concourse. Connecting from a vault client using the FQDN works.

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: AWS autoscaling groups

**Comment by marco-m** [comment]
I have two suggestions:

it is true that the cert has the correct CN vault.devops-tools.svc.cluster.local; on the other hand the section
```
X509v3 Subject Alternative Name: 
                DNS:vault, DNS:localhost, IP Address:127.0.0.1
```
might be the cause of the problem/bug, since it matches the error message. As a workaround, I would try using a cert without SAN record or adding to the SAN also the CN.

Another throubleshooting measure might be to use
```
openssl s_client -connect vault.devops-tools.svc.cluster.local:8200
```
and verify that the handshake is successful (although you are already mentioning that Vault clients connect successfully).

**Comment by TimJones** [comment]
Can confirm, the CN has to be in the SAN list to be used to verify the certificate. I used Vault PKI backend to generate a certificate rather than by EasyRSA/hand and it worked. They also have a flag especially to NOT include the CN in the SAN list (https://www.vaultproject.io/api/secret/pki/index.html#exclude_cn_from_sans-1) in case of the CN being a human-readable name rather than an FQDN/hostname.
