### ISSUE TITLE
Feature Request: Background images

### ISSUE THREAD

**Issue by DanielJonesEB** [concourse/concourse#1756]
We often have several pipelines visible on one build monitor. I know there's the new dashboard view in beta, but this isn't quite as lovely as the main pipeline view.

How about allowing each pipeline YAML file to specify a background image URL? Most of a Concourse pipeline's view is actually the empty background, so it'd be helpful for those of us that work on multiple pipelines to differentiate them when many are visible, or to ensure that we're looking at the one we think we are.

Seems like it should be a small PR, but I figured there's no point raising one if there's no desire for such a feature to be merged.

**Comment by jama-pivotal** [comment]
I think it might be an interesting way for teams to customize their pipelines further and make them more eye-catching to the relevant teams

**Comment by jama-pivotal** [comment]
Also, given our current focus on dashboard and new UI for build page, I don't see ourselves picking this up anytime soon. PRs more than welcome @DanielJonesEB
