### ISSUE TITLE
Failed to download from 'https://github.com/concourse/concourse/releases/download/v3.6.0/concourse-3.6.0-3468.1.tgz':   Verifying digest for downloaded file:     Expected stream to have digest 'b615cdefd6da904af404f6fc826fa9046f44b36e' but was '43c8ef28fb100441efd0fb80244f979c7859f983'  Exit code 1

### ISSUE THREAD

**Issue by dawg2k3** [concourse/concourse#1758]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request

## What challenge are you facing?

Rather than jumping to a solution, describe the problem you're facing, and provide context. It helps us more to understand your problem first. This way we may be able to connect the dots between your issue and others and perhaps come up with a more general proposal, rather than tacking on feature after feature.

## A Modest Proposal

If you've got a suggestion, feel free to place it here - we don't mean to stifle your creativity! It also helps to describe how you arrived at this idea and why it'd work well for you.

# Bug Report

Bug reports are pretty free-form; just replace this with whatever. You can also help us triage the issue by including steps to reproduce, expected results, and the actual result. Help us help you!

The following can also be handy:

* Concourse version:
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by vito** [comment]
should be fixed now
