### ISSUE TITLE
Keyboard shortcuts don't work on Firefox

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#1759]
After some teseting on non-Chrome browsers, we realized that the new keyboard shortcuts on the build page that we introduced in v3.6.0 don't actually work in the Firefox mainline and nightly 

Steps to Reproduce
---------------------
1. Install firefox (main or nightly)
2. Go a build page on concourse
3. Try the following keys: ? , T, A, h, j, k, l

Expected Results
------------------
They should trigger the relevant shortcuts

Actual Results
---------------
Nothing happens

**Comment by xtremerui** [comment]
After investigation there is no easy way to make shortcuts works for both chrome and firefox. Main reason is the ELM library used for detecting key pressed has bug in Firefox. https://github.com/elm-lang/core/issues/326

we have to either skip firefox or change our shortcuts i.e. make them not case sensitive (T,A are working in Firefox now for example)

**Comment by xtremerui** [comment]
Confirm on Firefox 64 and concourse 5.4 that all keyboard shortcuts are working.
