### ISSUE TITLE
Expose ATC external URL to resource metadata

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#176]
Currently the metadata exposed to the resources contains the following environment variables:
```
BUILD_ID
BUILD_NAME
BUILD_JOB_NAME
BUILD_PIPELINE_NAME
```

It would be very helpful to also have `ATC_EXTERNAL_URL` (or something similar) - this simplifies construction of URLs in notification-esq resources.

**Comment by jchesterpivotal** [comment]
I made a request to @robdimsdale to expose build URLs in the user-agent string of the pivnet resource.

So as far as pivnet log spelunking goes, we +1 this request.

**Comment by zachgersh** [comment]
PR here https://github.com/concourse/atc/pull/43
