### ISSUE TITLE
Stream Digest Error again

### ISSUE THREAD

**Issue by Tokery** [concourse/concourse#1761]
Having the exact same issue as #1514. Only difference is Concourse v3.6.0

`Failed to download from 'https://github.com/concourse/concourse/releases/download/v3.6.0/concourse-3.6.0-3468.tgz':
  Verifying digest for downloaded file:
    Expected stream to have digest 'ff01fc9cf6e2a2af28577747595120e93d2dd31a' but was '43c8ef28fb100441efd0fb80244f979c7859f983'`

**Comment by jtarchie** [comment]
@Tokery, there was an issue where the concourse-lite.yml referenced an incorrect URL. It should have read `https://github.com/concourse/concourse/releases/download/v3.6.0/concourse-3.6.0-3468.1.tgz`.

It has been updated to no longer reference the incorrect URL. Please download the `concourse-lite.yml` and try again.

Thanks!
