### ISSUE TITLE
Run concourse CI on systemd container?

### ISSUE THREAD

**Issue by oneingan** [concourse/concourse#1762]
I am trying to run concourse CI on systemd-nspawn container but I can't. I have been searching for this issue and I dont found anything helpful. I will try to explain what i do:

1. First I make a .raw file that contains all I need (with mkosi).

2. I start a systemd container using this .raw file (sudo systemd-nspawn -bi concourse.raw --capability=all). concourse web and worker services starts without problems. I log into 127.0.0.1:8080 and add my first pipeline (HelloWorld). Then, when I run HelloWorld pipeline I get this error:

`runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:261: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/8638cb95-bbbc-4719-4509-5a1789fb100a: read-only file system\""`

3. I add --bind option and try again (sudo systemd-nspawn -bi concourse.raw --capability=all --bind=/sys/fs/cgroup). I think that adding the --bind option I fixed the first error, because now concourse's container is able to pull docker image, but I get other error:

`runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:69: creating device nodes caused \\"no such file or directory\\"\""`

Both host and container:
$ cat /etc/issue
Ubuntu 17.10 \n \l

$ systemctl --version
systemd 234 +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

I dont know how to solve this errors. It is possible to run concourse CI on systemd container?

Thanks.

**Comment by jtarchie** [comment]
I'm not too familiar with `systemd-nspawn`, does it start a container with privileged access. The man page _kindof_ indicates that is what `--capability=all` does, its a bit sparse.

**Comment by juaningan** [comment]
of course, I'm running with --capability=all

**Comment by juaningan** [comment]
Ask in systemd mailing list:
https://lists.freedesktop.org/archives/systemd-devel/2017-November/039733.html

**Comment by marcbachmann** [comment]
I'm just posting that here because I had exactly the same error on my docker host.
I was able to get rid of that error message by upgrading to a newer linux kernel.
In my case I upgraded from `4.10.8` to `4.13.15`.
The error messages could be better in runc. -.-

**Comment by xtremerui** [comment]
closing for stale issue. Feel free to reopen if it still exists.
