### ISSUE TITLE
Establish a cleaner/more intuitive development flow for the web UI

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1770]
We've ended up with a somewhat fragmented development flow under `web` as we've transitioned between tech stacks.

So let's clean this up a bit!

* The development flow should more clearly show that Elm is everything - it shouldn't be tucked under an `elm/` directory.
* Let's go forward with the JS-based test suite, and similarly move them up rather than having them tucked under `wats`.

In doing all this, we can track all of our development flow via Yarn or NPM, rather than telling the user to install Elm first. We can also track `less`, `uglify-js`, etc., rather than having them as prerequisites on the machine. Then these can be run with something like a `npm run build` or whatever tooling makes sense for JS dev.

At the end of this, it should be easy to have a build, test (elm tests?), end-to-end test (js wats) lifecycle when iterating on the web UI.

Be sure to update `CONTRIBUTING.md` - maybe make a new one under `web` since we may extract it later, and have the one in the root of the repo just link to it?

**Comment by pivotal-jamie-klassen** [comment]
@vito at this point do we just move everything in `web/elm/*` up to `web/*` ?

**Comment by vito** [comment]
@pivotal-jamie-klassen My suggestions:

* nuke `web/acceptance/` - we don't even run it anymore
* nuke `web/cmd` - I don't think this is used - and also nuke `web/proxyhandler`
* assimilate `web/wats` into the toplevel `package.json` and add a `yarn run wats` command or something
  * maybe move `web/wats` to just `wats`, similar to how we have `testflight` at the toplevel?
* do something about the Go code - maybe just copy it all into one file? having a package for each handler feels overkill since they're all just tiny glue code, and it kind of distracts from the "real" `web` code

:+1: / :-1: ?
