### ISSUE TITLE
Build view taking much longer to load

### ISSUE THREAD

**Issue by kurtmc** [concourse/concourse#1771]
# Bug Report

In the web UI the build view is taking much longer to load than previously.

When I load `/teams/main/pipelines/:pipeline/jobs/:build/builds/:id` for a particular pipeline/job and  `id` since the v3.6.0 upgrade it's taking about 17 seconds to load. If I go to an older `id` it will take about 5 seconds.

The web page for builds with large amounts of output is completely unusable now.

Is anyone aware of this problem? Is there any more information I can provide to diagnose the cause for increased load time?

* Concourse version: v3.6.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? Yes in on version v3.5.0

**Comment by jtarchie** [comment]
@kurtmc, please try in Firefox.

**Comment by kurtmc** [comment]
Looking at the network tab in the javascript console for a URL like `https://<host>/api/v1/builds/<id>/events`

Firefox:
New build: 26148 ms
Old build: 5354 ms

Chrome:
New build: 18200 ms
Old build: 4190 ms

**Comment by wieslaw-gat** [comment]
I'm experiencing the same problem, checking builds via the web page is now outrageously slow. I'm normally using Firefox as my main browser and it's working so slowly that the whole thing is unusable.

I'm also having better results in Chrome, at least I can trigger a new build in it (but it's still very slooow).

**Comment by jtarchie** [comment]
Can anyone provide a reproducible example? Or any insight to what is causing it to go slow?

**Comment by timrchavez** [comment]
I think we're hitting this too. Getting 504's on /events endpoint. Restarting the web process (we use the binaries), seems to resolve the issue temporarily. When it happens again, I'll do some more debugging.

**Comment by william-tran** [comment]
@timrchavez @kurtmc To determine whether you're seeing a frontend vs backend issue, in the developer console try "copy as cURL" on the /events endpoint (or the equivalent in non-Chrome), and then curl  the same /events request. Though @timrchavez 504 seems like a backend issue. Check your DB and app monitoring and see if you're maxing out CPU, I've had to resize both the RDS and the number of concourse-web VMs/k8s pods as our number of pipelines has grown.

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/1912 - I suspect they both point to the same root cause
