### ISSUE TITLE
Show better message when intercepting a container fails

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#1774]
When I try to intercept a build that is in pending state (before any resources / tasks are run), I get the following:

```
$ fly -t aws intercept -j v2x/test-rsu-manager
error: websocket: bad handshake
```

This is on 3.5.0.

After the build runs, intercept works again.

**Comment by jtarchie** [comment]
There are no containers to intercept since it is a pending state. Do you just want a better error message?

**Comment by marco-m** [comment]
I think that a better error message would be helpful to remove confusion. As is, the error is too low-level.

**Comment by jtarchie** [comment]
It was not clear that was what was being asked for. I was asking for clarification.

Is there an error message that would useful?

**Comment by marco-m** [comment]
Something similar to `error: cannot intercept a job in pending state, try again later` maybe ?

**Comment by marco-m** [comment]
@vito would this be a good candidate for a first contribution for somebody who is not familiar with the Concourse source code ? I mean: would this be fixable by changing only `fly` or would we need to also follow the `intercept` request on the ATC code and change something there ?

**Comment by vito** [comment]
@marco-m I think a change in the ATC would help. I think this error only happens when fly tries to intercept a container in `CREATING` state. If that were exposed in the API then fly could know it's not yet interceptible.

**Comment by jadekler** [comment]
> There are no containers to intercept since it is a pending state. Do you just want a better error message?

Belated, but yes heh

**Comment by pivotal-saman-alvi** [comment]
Fixed as part of https://github.com/concourse/atc/blob/5703ea830dbaa0e88c6d5683ed52058adf41327f/exec/log_error_step.go

Timeout error now shows as `"timeout exceeded"`
