### ISSUE TITLE
Dashboard should support filtering of pipelines

### ISSUE THREAD

**Issue by akshaymankar** [concourse/concourse#1776]
# Feature Request

## What challenge are you facing?

We have a shared tracker between a couple of teams who work on related projects, we have our separate build radiators. The screen has too many pipelines and a lot of times I don't care about the failures in other team's pipelines. So, I would like to declutter my build radiator.

## A Modest Proposal

If I as the user had an ability to filter out the pipelines, to be absolutely modest, it would be a list of checkboxes. But one could jazz it up by having multiple of on/off buttons.

**Comment by jama-pivotal** [comment]
Hey @akshaymankar thanks for the feedback! If you upgrade to Concourse 3.6.0 and hit up /beta/dashboard you can actually start filtering pipelines on that view. 

Here are a list of the basic commands we implemented:

Search by pipeline name #1682 
Search by pipeline status #1703 
Search by team name #1684 

Hope that helps!

Closing

**Comment by akshaymankar** [comment]
Hey @jama-pivotal, Thanks for the quick response. I am using 3.6.0. But I was looking for more control over filtering than team or pipeline name.
