### ISSUE TITLE
Web pipeline view never updating with build status

### ISSUE THREAD

**Issue by scottschulthess** [concourse/concourse#1777]
![screen shot 2017-11-03 at 11 32 24 am](https://user-images.githubusercontent.com/130153/32382060-b6f4bfe2-c08a-11e7-9eb9-d4079d0bf4f9.png)
<img width="703" alt="screen shot 2017-11-03 at 11 32 52 am" src="https://user-images.githubusercontent.com/130153/32382096-c379d7b6-c08a-11e7-89ed-d62f6c3f6ecf.png">

Despite builds being run successfully, the entire pipeline view stays "gray" on a freshly installed 3.6.0 instance.

**Comment by scottschulthess** [comment]
From the jobs json, I'm getting `[{"id":106,"name":"tests","url":"/teams/main/pipelines/savannah/jobs/tests","next_build":null,"finished_build":null,"inputs":`

**Comment by scottschulthess** [comment]
Still a problem, still a mystery.  Will confirm a 2.5.0 downgrade fixes it, (seems likely as this is only appeared after going from 2.5>2.6

**Comment by vito** [comment]
Have you upgraded to Postgres 9.5?

Our docs for BOSH were out of date for a while, so that may have led to this broken state. They're updated now: https://concourse.ci/clusters-with-bosh.html

The release currently still contains Postgres 9.3 so existing deployments can be migrated. We'll be ripping it out soon.

**Comment by scottschulthess** [comment]
@vito thanks, that did the trick

**Comment by bewatts** [comment]
I just got this problem on a fresh install of 3.6.0, running concourse-lite.  
I'm on postgres 9.6.5

**Comment by vito** [comment]
@bewatts Yes, we mistakenly still shipped the 3.6.0 lite box with the old postgres prior to its removal. The 3.7.0 manifest should be fixed. We don't plan on fixing the 3.6.0 manifest; I'll just remove it from the release.
