### ISSUE TITLE
Concourse Error Regarding Volumes Difficult to Debug

### ISSUE THREAD

**Issue by rfliam** [concourse/concourse#1778]
* Concourse version: 3.3.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: Openstack

Concourse often reports an error of this nature to me: 
```Get /volumes/700ab7c2-d546-46a3-5e8b-6a351a67d92f: net/http: timeout awaiting response headers```

This error is problematic, because it tells me nothing about which one of my 20 workers _had this issue_. I have to manually search all hosts for the volume to identify the problem worker. A bit more context would be nice (what is the timeout, what is the endpoint I was trying to reach, etc.)

**Comment by XenoPhex** [comment]
The CF CLI team is starting to regularly see this issue in our pipelines. Does anyone have any insight into why this occurs?

**Comment by ralekseenkov** [comment]
We are also seeing this on our 4.2.1 pretty frequently, running on Kubernetes with Azure persistent volumes:
![image](https://user-images.githubusercontent.com/609325/48245313-0b148700-e39f-11e8-8aaa-4ff138ce97e6.png)

CC: @vito

**Comment by ralekseenkov** [comment]
Also having this as well:
```
Put /volumes/63a50a9a-19bf-4c60-677e-038ae19054c9/stream-in?path=.: read tcp 10.244.2.237:41300->10.244.2.237:44045: read: connection reset by peer
```

**Comment by XenoPhex** [comment]
We also started seeing this on our OSX Worker, so it looks like it's not limited to windows.
