### ISSUE TITLE
Jobs not getting trigger 

### ISSUE THREAD

**Issue by cheikhniass74** [concourse/concourse#1779]
Hi there!

I am trying out the the attendee-service tutorial  https://github.com/pivotal-education/pcf-attendee-service-code/tree/concourse_deployment but after running the command the job isn't getting trigger  "fly trigger-job -t concourse-lab -j attendee-service/build" the UI build status showing not pause.
Below is the logs from the UI and screenshot .

checking pipeline is not paused
checking job is not paused
discovering any new versions of attendee-service
waiting for a suitable set of input versions
attendee-service - no versions available
checking max-in-flight is not reached

# Bug Report
<img width="516" alt="screen shot 2017-11-03 at 1 58 04 pm" src="https://user-images.githubusercontent.com/9786702/32388791-2bb1f124-c09f-11e7-85e1-09b4ae1f2f8b.png">

The following can also be handy:

* Concourse version: concourse-3.5.0.tgz
* Deployment type (BOSH/Docker/binary): Docker 
* Infrastructure/IaaS:  Mac book Pro/ Virtualbox version 5.13
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by shashwathi** [comment]
@cheikhniass74 : It is clean from the build output as to why the job is not getting triggered. 
Check the resource `attendee-service` to see if any version is available.
