### ISSUE TITLE
Allow multiple users to sign in using Github Oauth

### ISSUE THREAD

**Issue by dlapiduz** [concourse/concourse#178]
Is anyone interested in a feature like this?

I think we should have a way to log in other than basic auth. It would be cool to integrate with UAA too...

**Comment by vito** [comment]
This much at least is already done, and will be in the next release. You'll be able to configure sets of organization[/team]s to permit access. What's not yet done or planned is fine-grained permissions per-pipeline and per-user. I'd like to collect use cases for that first.
