### ISSUE TITLE
Example bosh manifest still uses postgresql from concourse release

### ISSUE THREAD

**Issue by lflux** [concourse/concourse#1782]
# Bug Report

The example BOSH manifest in the [deploying concourse](http://concourse.ci/clusters-with-bosh.html#deploying-concourse) section of the docs instructs the user to use Postgres from the concourse release. This version is too old for concourse, and the manifest should probably reference using the postgresql release (as noted in the [3.5 release notes](http://concourse.ci/downloads.html#v350))

**Comment by vito** [comment]
Should be fixed now.
