### ISSUE TITLE
"500 Internal Server Error" from `fly execute` with Flight School Tutorial + Concourse Lite

### ISSUE THREAD

**Issue by ecowden** [concourse/concourse#1783]
Hey Pipeline Gurus,

Apologies in advance if I'm doing something stupid. I am trying the tutorial, after all! 😬 

I'm working through the [Flight School Tutorial](http://concourse.ci/flight-school.html). I'm hitting this problem right after the line, "Ok, let's save that in build.yml and run our command again." It is the third time the tutorial asks you to run, `fly -t ci execute -c build.yml`. It _should_ upload and run a build. Instead, it immediately returns, 

```
error: Unexpected Response
Status: 500 Internal Server Error
Body:
```

I've installed Concourse using the [Single VM method](http://concourse.ci/concourse-lite.html) with concourse-lite and BOSH.

I'm able to access the web app and run the [Hello World](http://concourse.ci/hello-world.html) pipeline successfully. 

Thanks in advance for any help!

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH with `concourse-lite.yml`
* Infrastructure/IaaS: Local on Macbook Pro; MacOS "Sierra" v10.12.6
* Browser (if applicable): N/A
* Did this used to work? Nope

**Comment by bioxcession** [comment]
Running into the same problem on my end. Troubleshooting now, will update this post if I find a resolution.

**Comment by bioxcession** [comment]
```yaml
master λ fly format-pipeline --config build.yml
groups: []
resources: []
resource_types: []
jobs: []
```

It also isn't working with `hello.yml`

```
λ cat hello.yml
platform: linux
image_resource:
  type: docker-image
  source: {repository: ubuntu}
run:
  path: echo
  args: ["Hello, World!"]
~/code/misc/concourse
λ fly -t ci execute -c hello.yml
error: Unexpected Response
Status: 500 Internal Server Error
Body:
```

There's definitely something wrong on the server-side. I recreated Concourse CI using version 3.5.0 which seemed to fix this regression:

```
wget https://github.com/concourse/concourse/releases/download/v3.5.0/concourse-lite.yml
bosh create-env concourse-lite.yml
fly --target tutorial login --concourse-url http://192.168.100.4:8080
master+ λ cat task_hello_world.yml
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: echo
  args: [hello world]
~/code/misc/concourse/concourse-tutorial/01_task_hello_world
master+ λ fly --target tutorial execute --config task_hello_world.yml
executing build 2 at http://192.168.100.4:8080/builds/2
initializing
running echo hello world
hello world
succeeded
```

No idea what's up with execute not working for tasks though!

**Comment by jchester** [comment]
I think this is a regression. `fly execute` worked in 3.5.0 but is not working for 3.6.0.

**Comment by ecowden** [comment]
Okie dokie, thanks! 👍 

I thought I was losing my mind, unable to get past the first step in the tutorial...

**Comment by mandrean** [comment]
Same here. Tried to follow https://github.com/starkandwayne/concourse-tutorial on `3.6.0` but I get all kinds of weird issues, like `500`'s and forever `Loading` jobs

**Comment by dpb587** [comment]
I ran into this as well.

I ended up switching to postgres-release and restarting the server, and then it started working again. Not sure which of those helped, if either.

**Comment by jtarchie** [comment]
Can someone provide the logs from `atc` (web) of when the errors occurs?

**Comment by xtremerui** [comment]
@ecowden the release note of concourse [v3.6.0](https://github.com/concourse/concourse/releases/tag/v3.6.0) is updated with this on github
```
Note: the concourse-lite.yml in this release was mistakenly shipped with Postgres 9.3, and has been removed as that made the deployment not fully functional.
```

The issue was that starting from v3.6, concourse doesn't ship with postgre anymore. Instead, concourse now requires PostgreSQL v9.5+ which means when doing bosh deployment the release needs to be uploaded. Your concourse-lite.yml is probably outdated.

Try running the flight-school with concourse v3.8.0 and the latest concourse-lite.yml, it should be good.

**Comment by ecowden** [comment]
Thanks @xtremerui! 

I'm on vacation now, but I'll check it out as soon as I get back in a few weeks. If you're confident that's the fix, please feel free to close out this issue. 👍

**Comment by xtremerui** [comment]
Will close the issue for now.
