### ISSUE TITLE
Documentation regarding `tags` lacks details.

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1784]
# Bug Report

The Documentation regarding where to put `tags` is too sparse, the documentation does not state at what level it can be placed and if resources and task/job level tags need to match, nor is a simplistic example given.

Loosely related #1371

**Comment by jtarchie** [comment]
All the the options for steps, tasks, and resources specify their options at the same level.  A resource has `source` and `tags` on the same key-value pair.

Can you be more specific where you had the issue? For example what you interpreted but it actually turned out to be.

**Comment by drahnr** [comment]
The common way of finding this page is by search.

As such there is no context given and the clarity regarding on which level is not given.

I tried to put this on the `task:` level, under `config:`
