### ISSUE TITLE
fly should have a way to print the pipeline configuration before set it

### ISSUE THREAD

**Issue by hkumarmk** [concourse/concourse#1789]
# Feature Request

## What challenge are you facing?

Fly command has get-pipeline option to get pipeline's configurations once the pipeline is set in the concourse. But it would be helpful if we have an option to see the pipeline configuration with all variables interpolations done in order to verify the configuration data before running fly set-pipeline.

## A Modest Proposal

It may be appropriate adding an option to validate-pipeline like --print-config to print the final configuration or even to add an extra option to set-pipeline (like "--dry-run")  so that it just print final configuration and exit without actually setting pipeline.

**Comment by shashwathi** [comment]
@hkumarmk : 
This is already a feature in [`validate-pipeline`](https://concourse-ci.org/single-page.html#fly-validate-pipeline) command.

There are more options which are not documented on this command so try running `validate-pipeline --help`. 

```
[validate-pipeline command options]
      -c, --config=                 Pipeline configuration file
      -s, --strict                  Fail on warnings
      -v, --var=[NAME=STRING]       Specify a string value to set for a variable in the pipeline
      -y, --yaml-var=[NAME=YAML]    Specify a YAML value to set for a variable in the pipeline
      -l, --load-vars-from=         Variable flag that can be used for filling in template values in configuration from a YAML file
```
