### ISSUE TITLE
Pass --no-new-keyring when runc is launched inside a container with blocked keyctl

### ISSUE THREAD

**Issue by juaningan** [concourse/concourse#1790]
# Feature Request

## What challenge are you facing?

Trying to run concourse worker inside a container without access to keyctl syscalls

## A Modest Proposal

Pass --no-new-keyring when runc is launched inside a container with blocked keyctl.
Or permit to pass arbitrary arguments to runc command.

### References:
https://github.com/opencontainers/runc/issues/1369
https://github.com/systemd/systemd/issues/5163

**Comment by vito** [comment]
Closing this since there's no action we can take on our part. We'll see how the upstream issue goes.
