### ISSUE TITLE
Failed to connect to <ip_address> port 80

### ISSUE THREAD

**Issue by tuanphpvn** [concourse/concourse#1792]
Hi there!

Follow the tutorial: https://concourse.ci/flight-school.html

Meet the error: 
![error](https://user-images.githubusercontent.com/7608580/32506594-8b41cb34-c417-11e7-8d80-2bbb7b6b9b34.png)

Here is my web and worker subcommand :

```
sudo concourse web \
    --basic-auth-username myuser \
    --basic-auth-password mypass \
    --session-signing-key /usr/local/etc/concourse/session_signing_key \
    --tsa-host-key /usr/local/etc/concourse/tsa_host_key \
    --tsa-authorized-keys /usr/local/etc/concourse/authorized_worker_keys \
    --external-url http://127.0.0.1 \
    --postgres-data-source postgres://concourse:123@localhost/atc
```

```
sudo concourse worker \
  --work-dir /usr/local/etc/concourse/worker \
  --tsa-host 127.0.0.1 \
  --tsa-public-key /usr/local/etc/concourse/tsa_host_key.pub \
  --tsa-worker-private-key /usr/local/etc/concourse/worker_key \
  --garden-dns-server 8.8.8.8
```

The environment:

OS:  Ubuntu 16.04 (64 bit)

**Comment by shashwathi** [comment]
@tuanphpvn : Default port is 8080. Update fly target to use 127.0.0.1:8080 as ATC URL.

**Comment by jama-pivotal** [comment]
Closing because we've basically abandoned the concourse tutorial on the website in favour of Stark & Wayne's https://concoursetutorial.com/
