### ISSUE TITLE
How to get a specific version of bosh-io-release

### ISSUE THREAD

**Issue by MinsuLim** [concourse/concourse#1795]
# Feature Request

## What challenge are you facing?

I'm using concourse to get release of pivotal-cf/cf-redis-release and deploy it to bosh.
But I don't know how to get a specific version of releases.

'version_family' worked correctly for me in type 'bosh-io-stemcell' to get a specific version.
But I couldn't find any key word for type 'bosh-io-release'. (version, version_family didn't work)
I get always latest version '431.0.0' while I'm looking for a specific version like '429.0.0'

Is there a way to get a specific version of release?
Thank you for helping me in advance.

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary):  BOSH

**Comment by shashwathi** [comment]
@MinsuLim : [`version`](https://github.com/concourse/bosh-io-release-resource#in-fetch-a-version-of-the-release) on bosh-io-resource will fetch specific version.

**Comment by jama-pivotal** [comment]
@MinsuLim hope @shashwathi suggestion was able to help you! Closing for now, but feel free to reopen if you want to revive the conversation
