### ISSUE TITLE
would like to have a user specified link shown in UI for each pipeline

### ISSUE THREAD

**Issue by cppforlife** [concourse/concourse#180]
... so that I can link all my pipelines back to their github repos.

**Comment by robdimsdale** [comment]
+1

**Comment by DenisIzmaylov** [comment]
+1

**Comment by vito** [comment]
What's the navigation flow that drives this out? Seems like a lot of the time people get to a pipeline *from* GitHub. Just wondering if it's really worth threading through more metadata and having it take up valuable screen real estate.

**Comment by cppforlife** [comment]
i go a lot to concourse to see pipelines ;) and want to jump to github.

may be it could be a hover a resource with a link or something. since i may have multiple git repos.

**Comment by aequitas** [comment]
same for me, maybe some kind of freeform area in the corner to allow inserting documentation or links https://github.com/concourse/atc/issues/47

**Comment by vito** [comment]
I like the resource metadata idea - less to maintain in the pipeline if resources do that automatically (i.e. expose UI-oriented metadata, with links and such).

**Comment by majewsky** [comment]
I have the same problem. As a workaround, I've added a "README" job to my pipeline:

<img width="988" alt="screen shot 2017-08-14 at 16 39 07" src="https://user-images.githubusercontent.com/24696/29276523-2a23c6c2-810f-11e7-8e99-753baf53529c.png">

All it does is print some messages (by running `/bin/echo` in an Alpine container):

<img width="883" alt="screen shot 2017-08-14 at 16 41 59" src="https://user-images.githubusercontent.com/24696/29276632-8411e998-810f-11e7-959e-4f9c01345115.png">
