### ISSUE TITLE
Bring back the login button on multi-pipeline/dashboard view

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1801]
# Bug Report

After the upgrade from 3.5.0 to 3.6.0, the login button on our dashboard stopped working. It is now just text saying the team name and cannot be clicked. This is kind of annoying because we have a monitor displaying the dashboard and we need to login every 24 hours, so every time that happens we need to change to a different page of Concourse, login, then retype `/beta/dashboard` in the url.

Can we please have the login button back?

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Yes it worked in 3.5.0

**Comment by jama-pivotal** [comment]
@andrewedstrom FINEEEEE we'll do something about it....hopefully 😄

**Comment by jama-pivotal** [comment]
Going to load this into a mega-story tentatively called "please make the beta route more usable"

**Comment by jama-pivotal** [comment]
Its going to be a while I think until we fully flesh out the beta route and all the views. So, in the mean time we're going to bring back the beta view into `dashboard/` without beta #2051. Once that happens I think we can have the `login` button clickable and just take you to the "old" screens for login. Seems like the least we can do to make the dashboard work-able now that a lot of folks are using / depending on it

**Comment by jama-pivotal** [comment]
Technically works, but completing the login flow should bring me back to dashboard, not `/` WIll create a separate issue
