### ISSUE TITLE
Pass key values between jobs

### ISSUE THREAD

**Issue by regevbr** [concourse/concourse#1804]
# Feature Request

## What challenge are you facing?

Currently, the only way to pass data between jobs is using resources, which requires writing data to some external resource such as s3 or git repo. This is very handy and understandable to pass along big data and file structures.
I was surprised to realize that if you want to pass some key values form one job to another is unfeasible. For example, in the [spring-cloud-pipelines](https://github.com/spring-cloud/spring-cloud-pipelines) project, they pass the current version using a github branch with one file and each worker needs to clone it locally just to get a hold of a simple string value that represents the version.
I think it is only natural to allow to pass out a set of key values between jobs, reducing the redundancy of having to have a resource just for it.

## A Modest Proposal

Create a new type of resource (File?) that gets in the `put` phase a file to send out to the `get` in the following jobs. The only thing is that this resource has no configuration as it is not connected to any external service but being handled only by the Conourse orchestrator.

**Comment by regevbr** [comment]
I will create a resource myself based on the time resource and pass the variables using the version part.
Will update here when done so you can consider making it an official resources

**Comment by jama-pivotal** [comment]
Neat! Would you like to add this resource to our list of resources? http://concourse.ci/resource-types.html  It should be a relatively easy pull request to https://github.com/concourse/docs/blob/master/lit/using-concourse/resource-types.lit

**Comment by regevbr** [comment]
@jama-pivotal already did :-)

**Comment by jama-pivotal** [comment]
Merged @regevbr you should be seeing it on the website soon.  I'll have to ask @vito to weigh in on whether or not we'll be rolling this in as an official resource, but afaik we're actually hoping to shed resources from the default package and work instead on making resources more accessible and discoverable

**Comment by regevbr** [comment]
Perfect thanks!
Keep me posted please

**Comment by vito** [comment]
Looks like this is resolved. As @jama-pivotal indicated we're unlikely to pull this resource into the core, but thanks for making it!
