### ISSUE TITLE
I would like a bosh-init resource to deploy VMs via bosh-init

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#181]
A bosh-init resource would enable a similar workflow to the bosh-resource, but would handle the specifics of bosh-init.

This could also be a part of the bosh-resource itself - happy to reopen this issue there if preferred?

**Comment by vito** [comment]
@hybris did this:

https://github.com/hybris/bosh-init-deployment-resource

https://github.com/hybris/bosh-init-deployment-resource-boshrelease
