### ISSUE TITLE
Pipeline view not updating (v3.6.0)

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#1811]
# Bug Report

Since updating concourse many of our jobs are showing inaccurate states in the pipeline view. Possibly all of them. Many show as active even though they're done. Some show as failed or succeeded even though a more recent run as succeeded or failed, respectively. It seems that clicking on any of these jobs takes you to an old build.

* Concourse version: 3.6.0 (upgraded from 3.4.0)
* Deployment type: BOSH
* Infrastructure/IaaS: AWS with workers on Vsphere and GCP
* Browser (if applicable): Chrome
* Did this used to work? Yup

**Comment by jama-pivotal** [comment]
@xtreme-gavin-enns When you upgraded to Concourse 3.6.0 did you upgrade your pgdb to 9.5+? Instructions are scattered around through the release notes in http://concourse.ci/downloads.html#v360 and http://concourse.ci/downloads.html#v350

**Comment by jama-pivotal** [comment]
talked to the team with @xtreme-gavin-enns and going to close this while they hook up a pgdb to meet the new requirements
