### ISSUE TITLE
Unexpected Newlines on Word Wrap

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#1813]
# Bug Report

Not a big deal, but we're seeing some unnecessary newlines in some of our build outputs. Based on the behaviour we're seeing it looks like the log lines are wrapping because of trailing whitespace. I'm pretty sure this never happened before though, so maybe it's worth knowing about?

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? Pretty sure I never saw it before the timestamps were added

![xfavoat](https://user-images.githubusercontent.com/1178694/32753906-babfdab6-c89c-11e7-94de-186ad937c2eb.gif)

**Comment by jtarchie** [comment]
Can you confirm the version? The log line timestamps weren't introduced till 3.6.

**Comment by xtreme-gavin-enns** [comment]
Oops, yes, that was a typo and this is 3.6.0

**Comment by xtremerui** [comment]
@jama-pivotal doesn't seem like happen anymore in 3.9. What is our take here?

**Comment by mhuangpivotal** [comment]
@xtreme-gavin-enns are you still seeing this in 3.9?

**Comment by xtreme-gavin-enns** [comment]
Yeah, I haven't noticed that in a long time and can't reproduce it now

**Comment by jama-pivotal** [comment]
Thanks for the updates @xtreme-gavin-enns , closing issue
