### ISSUE TITLE
Paused Status in Pipeline Sidebar Not Updating

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#1816]
# Bug Report

Hi. Another small one. We had a bunch of pipelines paused from yesterday. They were unpaused this morning but I didn't realize because the sidebar still showed a blue pause symbol. Refreshing the browser fixed it.

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? I think so

**Comment by jama-pivotal** [comment]
Closing because sidebar is gone now
