### ISSUE TITLE
Delete/clear task caches

### ISSUE THREAD

**Issue by ipsi** [concourse/concourse#1817]
# Feature Request

## What challenge are you facing?

We're running into an issue where our `node_modules` cache has become corrupted somehow, giving us errors like:

```
Error: node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"/tmp/build/faf44d05/ui/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.
```

on doing an `ng build`.

Our task configuration is like so:

```yaml
---
platform: linux
inputs:
- name: ui
run:
  path: ui/ci/tasks/build-ui.sh
caches:
- path: ui/node_modules
outputs:
- name: artifacts
```

The easiest solution for this is to nuke the `node_modules` directory and recreate it. As it stands, the only options for that are (a) remove the `caches` block from the task, (b) re-create the worker(s), (c) rename the task, or (d) modify the script to execute `rm -Rf ui/node_modules/*`.

As we don't have BOSH access to Concourse (only Fly), (b) is out. Since we _do_ want caching (a) isn't really on the table. This leaves (c) and (d), both of which feel like somewhat hacky work-arounds to the issue.

## A Modest Proposal

I'd like to be able to do something along the lines of `fly -t target clear-cache -j pipeline/job -a task_name -c path/to/cache`, which would remove all data in the cache, and present a fresh, squeaky-clean directory the next time the task runs.

Some edge cases:

* What happens if task is running when we clear the cache?
* Will this become horrifically slow if I have a large number of workers?

**Comment by codesuki** [comment]
Agreed, this is something I wanted, too. Additionally it would be cool define a key for the cache by ourselves. My use case for this is, I am building and testing with bazel. My first step runs `bazel test` and of course builds things, and my second step does `bazel build`, but cannot re-use the cache from `bazel test`.

**Comment by vito** [comment]
Just ran into this today. Go's pretty bad a noticing `pkg` has outdated bits, and the only recourse is to disable the task cache.

**Comment by alvaropinot** [comment]
I think it could also be great to have a "clean cache when build fails" feature that could be setup as part of the yml key, something like:

```
caches:
- path: project-src/node_modules
- clean_on_error: true 
```
or even go into a failsafe strategy when a build has failed and clean the cache and retry.


Any thoughts?

**Comment by ghostsquad** [comment]
CircleCI has actually a really nice way of handling this. They let you _name_ the cache, and thus you can create more and more specific caches.

https://circleci.com/docs/2.0/caching/

**Comment by vito** [comment]
Some guidance on this, in case someone wants to submit a PR: I think this just comes down to deleting from the `worker_task_caches` table.

```
fly -t ci clear-task-cache -j my-pipeline/my-job -s step-name [-c path/to/cache]
```

This could hit an API endpoint like so:

```
DELETE /api/v1/teams/my-team/pipelines/my-pipeline/jobs/my-job/tasks/step-name/caches[/path/to/cache]
```

This would simply translate to:

```sql
DELETE FROM worker_task_caches
WHERE job_id = $1 -- just get the id corresponding to the name/pipeline, the API will do this for you
AND step_name = 'step-name'
AND path = 'path/to/cache'
```

The path could be optional, since it could be annoying to have to type that out.

The net effect of this: existing cache volumes will eventually be garbage collected, as their "owner" (the task cache) will have gone away, leaving them orphaned (all owner references will be `NULL`). No volumes will be killed while their build is running; there should be other safeguards for that. So I think this is actually really straightforward - just need an API endpoint and `fly` command!

**Comment by vito** [comment]
This was PR'ed in to v4.1.0. Thanks @edtan!
