### ISSUE TITLE
Dashboard job tooltip position is inconsistent

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#1818]
Normally the tooltip on dashboard job appears on the right side:

<img width="312" alt="screen shot 2017-11-15 at 2 30 14 pm" src="https://user-images.githubusercontent.com/1919762/32856020-8f02a4f0-ca11-11e7-8096-cdd5252ce531.png">

However, when the job tile is small, the tooltip shifts to the left:

<img width="310" alt="screen shot 2017-11-15 at 2 28 16 pm" src="https://user-images.githubusercontent.com/1919762/32855977-6cb3eed6-ca11-11e7-984a-d2fb94404767.png">

* Concourse version: 3.6.1
* Browser (if applicable): Chrome

**Comment by jama-pivotal** [comment]
I think this is "as designed" in the sense that our current implementation does its best-job at trying to place the arrow in the middle vertically and to the right. In the 2nd image the arrow is so big that it appears that its pointing to the leftmost edge but in reality the arrow is just that big. Maybe we should try a versionw here we push the tip of the arrow to the edge of the job box instead? @mhuangpivotal  lets see if that makes it look a bit clearer

**Comment by mhuangpivotal** [comment]
Discussed with @sampeinado and we agreed that the current design is fine.
