### ISSUE TITLE
get rid of Yeller support

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#1819]
# Feature Request

## What challenge are you facing?

Supporting code that no longer can be used for Yeller. It was service exception tracking, but it no longer a service.

We should get rid of it.

## A Modest Proposal

Get rid of this code.

* https://github.com/concourse/atc/blob/d6120e525f7158f36f7ef21ac22053ebb0c0148f/atccmd/command.go#L130-L131
* https://github.com/concourse/atc/blob/d6120e525f7158f36f7ef21ac22053ebb0c0148f/atccmd/command.go#L766-L769
* Remove the properties from the bosh release

**Comment by topherbullock** [comment]
![https://i.imgur.com/LwBs0am.gif?1](https://i.imgur.com/LwBs0am.gif?1)

**Comment by jtarchie** [comment]
That was such a terrible movie to show kids.
