### ISSUE TITLE
Can't Scroll Up on Build Page

### ISSUE THREAD

**Issue by ekcasey** [concourse/concourse#1826]
# Bug Report

Can't scroll up using arrow key on build page

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
![cantscrollup](https://user-images.githubusercontent.com/1994518/33035592-b42d811e-cdf9-11e7-80ea-489858ed5aca.gif)

* Browser (if applicable): Chrome
* Did this used to work? I think so

**Comment by jama-pivotal** [comment]
LOL. @ekcasey  can you try using the new keyboard shortcuts? `gg` for scroll to top and `G` to go to bottom?

**Comment by xtreme-gavin-enns** [comment]
Surprise! This was actually me.

I can't seem to reproduce it right now but I'll let you know next time it comes up. I can say though that scrolling up with the scroll wheel was also broken to some degree.

**Comment by xtreme-gavin-enns** [comment]
I've been able to reproduce it but, you'll love this, only when vnc'ed into a machine in another office.

Steps to repro: 
- VNC into cornelia (machine name, haven't tried it on other machines yet)
- navigate to a failed or in-progress build page
- shift-G
- attempt to scroll up with up arrow key

I'm gonna go ahead and assume this isn't a high-priority use-case but lmk if you want to investigate further.

**Comment by xtreme-gavin-enns** [comment]
One more note: The new "k" shortcut to scroll up is NOT affected, but clicking on the scroll-bar is.

**Comment by xtreme-gavin-enns** [comment]
More data-points: Even cmd + up-arrow is affected.

**Comment by xtreme-gavin-enns** [comment]
VNC was a red herring. Emily is still seeing this behaviour even when I'm no longer vnc'ed in.

Here are our chrome versions

62.0.3202.89 (normal)
62.0.3202.94 (busted)

**Comment by xtreme-gavin-enns** [comment]
Upgrading chrome to .94 on my machine did NOT cause the bug to start

**Comment by topherbullock** [comment]
A++++ gif game @ekcasey

**Comment by xtreme-gavin-enns** [comment]
I have come to the conclusion that this bug is cause by poor handling of continuous inputs by VNC.

Another example is to click and drag with the mouse. If your connection isn't perfect it turns into a series of frantic clicks along the drag path.

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/1930
