### ISSUE TITLE
Make timestamps "user-select: none;" so they aren't highlightable

### ISSUE THREAD

**Issue by utricularian** [concourse/concourse#1827]
# Feature Request

## What challenge are you facing?

Copy pasting out of a task's logs in the web interface now captures the timestamps. We have a few multi-line strings that we copy paste for various operational tasks; and now we have to jump through a few hoops to strip the timestamps.

## A Modest Proposal

There's a CSS tag called `user-select` that when set to `none` disallows selecting that element. We shamelessly stole this idea from github's file viewer (note that you can highlight multiple strings of code there without highlighting the line numbers).

## Version stuff

* Concourse version: v3.6.0
* Browser (if applicable): Chrome

**Comment by vito** [comment]
Dang, good catch. We made a point to support this initially but it looks like that got lost when we had to restructure things a bit.

**Comment by jama-pivotal** [comment]
Assigning to UX Backlog

**Comment by jama-pivotal** [comment]
Verified on Wings, looks like we can copy-pasta away!
