### ISSUE TITLE
Add optional timeout to fly intercept

### ISSUE THREAD

**Issue by sharms** [concourse/concourse#1828]
# Feature Request

## What challenge are you facing?

Some forms of compliance may require a interactive session timeout.  We are interested in adding a timeout variable to ATC / Hijack (https://github.com/concourse/atc/blob/master/api/containerserver/hijack.go) that would allow the user to set a optional timeout value (and default to unlimited).

Would a patch which does this sound ok, or are there other alternatives we should consider?

**Comment by EugenMayer** [comment]
Just as a side note, it could be also the other way around, for us it would not be compliance but rather, longer timeouts to fix issues and analyse them. So setting the timeout would give flexibility for this too, that would be great

**Comment by jama-pivotal** [comment]
@sharms i think that makes sense, given it would be a timeout against a hijack session. I would tend to agree with the idea of defaulting to unlimited, as that would be more backwards compatible with existing functionality

@EugenMayer you described a situation that sounds awfully close to #1269, is that the case?

**Comment by sharms** [comment]
This has been implemented in https://github.com/concourse/atc/pull/222
