### ISSUE TITLE
Display the URI on resource metadata

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1833]
When working with resources, it would be nice to see the actual URI that the resource is pointing to. For example, if I look at the github resource on ci.concourse.ci there is no indication as to what the repo link is: https://ci.concourse.ci/teams/main/pipelines/main/resources/concourse

![screen shot 2017-11-21 at 12 14 55 pm](https://user-images.githubusercontent.com/19274230/33086438-9b19ca22-ceb5-11e7-8560-1386d52abe55.png)

Proposal: 
If a resource has a `uri` field, include that data into the metadata field of the resource page on the web view

**Comment by jama-pivotal** [comment]
So this issue could be rephrased a bit. Looks like whether or not the URI is being displayed comes down to the output of the metadata on the resources themselves. So for this issue, we should focus on the Git Resource first, see if we can get the appropriate metadata out there. Folks should start seeing the required data

**Comment by vito** [comment]
What URI value is this expected to be? A link to a commit? Right now it just has the repo URL, which we should think carefully about exposing as metadata is viewable in public pipelines. There *may* be some people encoding HTTPS auth in the URL.

**Comment by xtremerui** [comment]
If we still want to show the repo URL we can strip the HTTPS auth info out. But yes, not sure if people want to expose the repo URL in metadata.

**Comment by jama-pivotal** [comment]
Going to close this issue as something we won't do for now because this data probably belongs in a general "Resource information" metadata, and not resource version metadata. That said, we should do a story where we link to the actual git commit URI from the version metadata, so I will be making a new issue around that
