### ISSUE TITLE
Running animation should also have the color of the pipeline's currently known state

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1835]
Running animation of the pipeline was recently reverted to just a grey running bar that's agnostic to the pipeline status. Now that we've cleared up the pipeline status colors and order of precedence, wanted to re-incorporate the color onto the running animation

1. Running animation color should reflect the state of the currently pipeline state
2. If the pipeline status changes as a result of the run of the pipeline, then the color needs to change as well (i.e. you'll need to update the running color to reflect the current state of the pipeline as jobs are completed

This is a stand alone animation, only use primary color and the background hex color of the div for the stripping. 

green #11C560, #2A2929 
![running_top_animation](https://user-images.githubusercontent.com/27746614/33094679-fb74e8e8-cece-11e7-940f-2c9885000fee.png)

red #ED4B35, #2A2929
![running_top_animation_red](https://user-images.githubusercontent.com/27746614/33094779-4835b9f0-cecf-11e7-8fa3-3dca3adc2218.png)

amber #F5A623, #2A2929
![running_top_animation_amber](https://user-images.githubusercontent.com/27746614/33094803-61194266-cecf-11e7-9cef-eaad1bd5d0ea.png)

brown #8B572A, #2A2929
![running_top_animation_brown](https://user-images.githubusercontent.com/27746614/33094893-ad1cfce8-cecf-11e7-833f-92e5bddbfe0d.png)

grey #9B9B9B, #2A2929

![running_top_animation_grey](https://user-images.githubusercontent.com/27746614/33094999-0bb5ff52-ced0-11e7-9b92-455e5afa718f.png)

**Comment by pivotal-gabriel-dumitrescu** [comment]
some screenshots for reference

![screen shot 2017-11-22 at 5 50 29 pm](https://user-images.githubusercontent.com/9042962/33153534-4dffc4fc-cfb0-11e7-838d-ce0fcc4bffb3.png)
![screen shot 2017-11-22 at 5 51 13 pm](https://user-images.githubusercontent.com/9042962/33153524-405ac6bc-cfb0-11e7-88e7-150f6b9137d9.png)
![screen shot 2017-11-22 at 5 52 19 pm](https://user-images.githubusercontent.com/9042962/33153522-3c60efc8-cfb0-11e7-8bf4-a36275b07c75.png)
![screen shot 2017-11-22 at 5 52 37 pm](https://user-images.githubusercontent.com/9042962/33153518-38203de2-cfb0-11e7-9a2c-7d7b5f1d4cff.png)
![screen shot 2017-11-22 at 6 55 39 pm](https://user-images.githubusercontent.com/9042962/33154512-c97cc37c-cfb6-11e7-8ad2-3f1837bc6f51.png)

**Comment by jama-pivotal** [comment]
Accepting because its technically what we asked for, but I'm not quite sure about the amount of aliasing on the run bar on top of the thumbnail. @Lindsayauchin to comment and probably fiddle around with
