### ISSUE TITLE
Aborted build reports no start time

### ISSUE THREAD

**Issue by Samze** [concourse/concourse#1839]
# Bug Report

An aborted build has no start time but an end time which results in a duration based on the start of unix time. See output `419822h46m8s`:

```
 fly -t wings builds -j thames/deploy-cf-with-updated-capi
id       pipeline/job                        build  status     start                     end                       duration
1139920  thames/deploy-cf-with-updated-capi  106    aborted    n/a                       2017-11-22@14:46:08+0000  419822h46m8s
```

Not sure what made this build special as all other aborted builds seem to have a start time.

* Concourse version: v3.6.1
* Deployment type (BOSH/Docker/binary): Wings
* Infrastructure/IaaS: Wings
* Browser (if applicable):
* Did this used to work? No idea

**Comment by christophermancini** [comment]
This was fixed.
