### ISSUE TITLE
Fly check-resource fails with 405 if concourse url protocol is http.

### ISSUE THREAD

**Issue by ebabani** [concourse/concourse#1844]
# Bug Report

`fly check-resource` fails with a `405` error if the concourse URL protocol is `http`. Changing to `https` fixes the problem. 

```
error: Unexpected Response
Status: 405 Method Not Allowed
Body:
Method Not Allowed 
```

The behaviour is okay since https should be encouraged, but the fly error message should be improved. 

* Concourse version: 3.6.0
* Deployment type kubernetes
* Infrastructure/IaaS: aws
* Browser (if applicable): -
* Did this used to work? ???

**Comment by daniellavoie** [comment]
I would like to add that the `set-pipeline` and `abort-pipeline` are also concerned about this proble. `set-pipeline` is even worst because you get a success feedback while no configuration change happens. Thanks for reporting this issue. Wouldn't have guessed otherwise.

**Comment by vito** [comment]
Sounds like #1932, which I [could not reproduce](https://github.com/concourse/concourse/issues/1932#issuecomment-357741098). Are you sure there's no intermediary redirect going on outside of Concourse?
