### ISSUE TITLE
targeting armhf platforms

### ISSUE THREAD

**Issue by encodeering** [concourse/concourse#1846]
# Feature Request

Hi, just wanted to know if you could provide a binary for armhf platforms, or if you could explain how to compile the sources from scratch?

Id like to run concourse on a Pi to create a pipeline that triggers remote docker jobs. Jenkins is quite heavy to manage on a Pi and I believe that concourse could be a lightweight option here. I dont think that I'll compile larger projects

Thank you very much.

**Comment by chendrix** [comment]
Hey there @encodeering 

If you have another Concourse instance already running, you should be able to use one of Concourse's open-source [build-linux](https://github.com/concourse/bin/blob/fe774091ab9e5735b09ce30b123461e0028e9f14/ci/build-linux.yml) tasks to build the linux binary, just make sure to also specify `GOOS=linux` and `GOARCH=arm` (or `arm64`).

The tasks also point to the relevant scripts needed, if you want to run it locally.

**Comment by Bo0mer** [comment]
Can you please post the binary if you manage to build it for `armhf`? Thanks!

**Comment by encodeering** [comment]
@chendrix @Bo0mer Im sorry for my late reply. Some other jobs rushed into my queue. I'll definitely evaluate your solution and try to cross build from amd64

**Comment by jama-pivotal** [comment]
Hi @encodeering, closing this issue since it sounds like you have a good lead on building the binary. Looks like there's some interest from @Bo0mer on your results, so please keep us updated (either on this issue, or in our slack!)
