### ISSUE TITLE
.ci TLD is blocked

### ISSUE THREAD

**Issue by danielmoore** [concourse/concourse#185]
Côte d'Ivoire is [sanctioned by the US government][sanctions] and its ccTLD (`*.ci`) is blocked by my employer, a financial services company. The concourse.ci domain is cute, but impractical in this sense. Would it be possible to set up a second, more bland domain? 

[sanctions]: http://www.treasury.gov/resource-center/sanctions/Programs/pages/coted.aspx

**Comment by xoebus** [comment]
Thanks for letting us know.

I've set up http://concourse-ci.com, http://concourse-ci.net, and (when the DNS propagates) http://concourse-ci.org. They each have a *ci* subdomain which will go to our CI in a similar manner to https://ci.concourse.ci. Please be aware that we do not have certificates for these domains and so your traffic to them will be unencrypted!
