### ISSUE TITLE
list volumes API endpoint returns when volume is missing meta information from the database

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#1851]
# Bug Report

When returning a list of volumes from the API endpoint `/volumes`, in the time it is processing volumes could have been reaped. These [lines](https://github.com/concourse/atc/blob/8488346e2c5eaa5d7c43cd3decbbe606d0702d7c/api/volumeserver/list.go#L32-L36) show that if any volume has an error it causes non of the volumes to be listed.

It would be nice to have it not throw a 500 if only one of the volumes had an issue.

We see this issue happen on this [build](https://ci.concourse.ci/teams/main/pipelines/main/jobs/topgun/builds/870).

Output that is important to see
```
STEP: running: /tmp/gexec_artifacts548712525/g459248968/fly -t concourse-topgun-6 --print-table-headers volumes -d
> concourse/f4a3cf27-48d1-4826-a0e7-76209edca7dd: stdout | {"timestamp":"1511452112.725145817","source":"atc","message":"atc.list-volumes.listed","log_level":0,"data":{"session":"508","volume-count":8}}
error: Unexpected Response
Status: 500 Internal Server Error
> concourse/f4a3cf27-48d1-4826-a0e7-76209edca7dd: stdout | {"timestamp":"1511452112.727374077","source":"atc","message":"atc.list-volumes.failed-to-present-volume","log_level":2,"data":{"error":"sql: no rows in result set","session":"508"}}
```

The following can also be handy:

* Concourse version: v3.6.0
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: gcp
* Browser (if applicable): chrome
* Did this used to work? nope

**Comment by vito** [comment]
Same as https://github.com/concourse/concourse/issues/1473 - I've prioritized it in core.
