### ISSUE TITLE
concourse-lite.yml

### ISSUE THREAD

**Issue by BenAychh** [concourse/concourse#1852]
# Bug Report

## What challenge are you facing?

Visual Activity does not show up on pipeline overview on "Single VM" (http://concourse.ci/concourse-lite.html) in 3.6.0. On previous versions (3.5 worked) I could keep a local copy of concourse running on my mac to play around with pipelines. I can still run the pipeline but I get no visual indicator that it is doing anything until I click into the individual boxes (no yellow outline or green or red status)

# Bug Report

I have a feeling this is related to the Postgres version that concourse-lite.yml is using but I don't understand bosh well enough to figure out what version of Postgres is being used. It would be nice to get those indicators back.

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): Bosh (concourse-lite)
* OS: Mac - Sierra
* Browser (if applicable): N/A
* Did this used to work? On version 3.5

**Comment by topherbullock** [comment]
Yeah, this is to do with the postgres version in the manifest.

Fixed by this commit: https://github.com/concourse/concourse-deployment/commit/88f03aca2c144022338be33e873cbd78e4542eb9
