### ISSUE TITLE
Spike : Determine database schema needed for the scheduler to operate on job permutations

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#1853]
Timebox : 2 days

Starting on #1765 brought up some interesting approaches and options around:
- how to determine what inputs and outputs are valid for a build
- what changes are needed to the build_inputs, build_outputs, and builds tables to refer to a job "permutation"
- what a "job permutation" is, and how it is represented (if at all) in the database
- whether the algorithm can be changed to determine what versions should be input to a build.
  -  is this just another rule on top of passed?
  - should the algorithm just operate on only the versions relevant to the job permutation?

Determine what database changes are needed for builds to know about spaces, whether job permutations needs to be a database, and how the scheduler should resolve inputs / outputs of builds.

**Comment by vito** [comment]
@mhuangpivotal Would you mind posting a summary of the result of the spike here, just to make it easier to follow along from the outside?

**Comment by mhuangpivotal** [comment]
We decided on the following database schema:

<img width="653" alt="screen shot 2018-01-12 at 10 29 24 am" src="https://user-images.githubusercontent.com/1919762/34882170-ab9ed706-f783-11e7-960a-cb530ae42d4a.png">

**Comment by vito** [comment]
Thanks!
