### ISSUE TITLE
Jobs getting a "File not found" error after restarting workers.

### ISSUE THREAD

**Issue by derwei** [concourse/concourse#1854]
# Bug Report
We had to power off our concourse deployment over the weekend and when we powered everything back up on Monday, our jobs started to encounter a "File not found" error.
To me it seems like there was an issue with the cached docker images.

Recreating the workers has resolved the issue. I'm not sure if there was a better way to handle this or if there was a better way to power off the workers...

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere

**Comment by gholker** [comment]
Hey @derwei I just had the same problem. Would also prefer the worker to more gracefully handle the shutdown (for me it was just a reboot not a power outage). Topher has an answer that worked for me [1]: use `concourse land-worker` or `concourse retire-worker`. Then I watched the status with `fly  workers`. 
Hope this helps! :D

[1] https://github.com/concourse/concourse/issues/1550#issuecomment-330667985

**Comment by derwei** [comment]
Awesome! thanks for the work around @gholker !! 

I'll close this issue since it seems directly related to the existing one you mentioned.

**Comment by EdwardStudy** [comment]
I just recreated these wrong workers.
