### ISSUE TITLE
Build log streaming broken by anti-virus software

### ISSUE THREAD

**Issue by drewlesueur** [concourse/concourse#1859]
# Feature Request

## What challenge are you facing?

EventSource features (Server-Sent Events) are not working in my environment -- probably because of my anti-virus software.
Example Url: `/api/v1/builds/50/events`
![screen shot 2017-11-30 at 2 28 40 pm](https://user-images.githubusercontent.com/115536/33455961-f81bab56-d5da-11e7-8ea6-7d287ae1d45d.png)

## A Modest Proposal

Is there a way to fall back to http long polling instead of using EventSource for this repo?:
https://github.com/concourse/atc

**Comment by vito** [comment]
Websockets are only used for `fly intercept`. What endpoint are you observing this with?

**Comment by drewlesueur** [comment]
Sorry, correction -- It's EventSource that's not working. I corrected the ticket above.

**Comment by vito** [comment]
Thanks.

There's no way currently for it to fallback to long polling. To be honest this isn't something we're likely to spend time fixing right now, but a PR would be welcome, as long as it doesn't affect the "happy path".

As a work-around, you can see the logs with `fly watch`.
