### ISSUE TITLE
Keep concourse-deployment Up To Date

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#1861]
Currently (post Concourse 3.7.0) the [`versions.yml`](https://github.com/concourse/concourse-deployment/blob/23070984ae554d450584196169d52e3369fd50ab/versions.yml) file in `concourse-deployment` is pointing at the Concourse 3.6.0 BOSH release.  Given that this is now the recommended (and documented) way of installing Concourse with BOSH, this repository should be both kept up to date (updated at the same time as the [GitHub release](https://github.com/concourse/concourse/releases) and [Downloads page](https://concourse.ci/downloads.html)) and tagged on each matching Concourse release.

**Comment by vito** [comment]
Yep! Planning on automating this next.

**Comment by vito** [comment]
done!

https://github.com/concourse/concourse-deployment/commit/64debfba68d429061adba4fb12663684ccb7ae72

auto-bumped by:

https://ci.concourse.ci/teams/main/pipelines/main/jobs/bump-concourse-deployment/builds/2
