### ISSUE TITLE
JAVA SDK for getCallerIdentity for AWS AUTH IAM login

### ISSUE THREAD

**Issue by anillingutla** [concourse/concourse#1863]
# Feature Request
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenService.html#getCallerIdentity-com.amazonaws.services.securitytoken.model.GetCallerIdentityRequest-
Above is all i have to code the JAVA API. 
Iam stumped as to how to get the signed header and what are the AWS ADK api's to set the session credentials, custom header, Action, region etc. It wuld be nice to provide client libraries for the same as most of us are not able to directly use CLI but our own SDK libraries.. any sudo code will help me a lot.

**Comment by jtarchie** [comment]
@anillingutla, I think you created an issue on the wrong github repo. This project does do anything related to AWS SDK and the headers you describe.

Are you trying to do something specific with concourse?
