### ISSUE TITLE
Concourse workers assigned to 1 team use all workers

### ISSUE THREAD

**Issue by ypougeol** [concourse/concourse#1865]
Hi there!

I'm actually running on concourse 3.4.1 and I have like 6 teams. I assigned 4 workers out of 7 to a specific team (team A) but when I connect to that team A, I see all 7 workers with is not want I want !!!
I want team A use only the 4 assigned workers and all others teams use the 3 last one.
Seems it's not possible ... so if we can have some options to do it, it would be great.

Thx

**Comment by jtarchie** [comment]
Assigning workers to a team, does not automatically exclude other workers from their listing.

All workers are assigned to all teams, unless you explicitly define an assignment of workers to team(s).

You have to assign the 3 other workers to be used by the 5 other teams.

**Comment by ypougeol** [comment]
Actually team parameter cannot be defined multiple times which is bad. Can you have for next future release an option like --team-only to only assign workers to a specific team and of course make sure to do not using other workers? Don't know where to push this request ...

**Comment by pooja8787** [comment]
Hey. What is the process to assign workers for a dedicated team? I tried searching for a document but couldnt find it!

**Comment by kurlzor** [comment]
> Assigning workers to a team, does not automatically exclude other workers from their listing.
> 
> All workers are assigned to all teams, unless you explicitly define an assignment of workers to team(s).
> 
> You have to assign the 3 other workers to be used by the 5 other teams.

Is this still true ? I'm trying to have 3 workers dedicated to team A and 3 other workers usable by all teams so I just assigned the 3 to team A. When I `fly -t A containers` I only see containers on the 3 workers assigned to A.

**Comment by vito** [comment]
@kurlzor `fly -t A containers` only shows containers belonging to the target's current team, so that sounds right to me. What does `fly -t B` containers show?

**Comment by kurlzor** [comment]
It only shows containers of builds from team B on the other 3 workers, the 3 assigned to team A don't ever appear.

**Comment by vito** [comment]
...So it sounds like it's working? :stuck_out_tongue:

**Comment by kurlzor** [comment]
From what I read here, I expected build from team A to be scheduled on the workers that aren't assigned to a specific team too.

**Comment by vito** [comment]
@kurlzor Ah, Concourse will actually schedule work on the team's own workers whenever possible, and only use the global workers when that's not possible (e.g. if all of a team's workers are tagged or a different plaform). There's currently no configuration to evenly spread workloads across the team's workers + the global workers.
