### ISSUE TITLE
url for one off builds is malformed

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#1869]
# Bug Report

When using `fly execute` against a production concourse the URL to the one-off build is incorrect.

For example,

```bash
$ fly -t ci execute -j main/bin-docker-testflight -i concourse-docker=/Users/pivotal/workspace/concourse-docker --inputs-from=main/bin-docker-testflight -c ci/testflight.yml -p --verbose

executing build 637915 at https://ci.concourse.ci/teams/main/pipelines/main/jobs//builds/737
```

I believe it has been happening since this [change](https://github.com/concourse/atc/commit/7ee6e3dc9e0ab5c869aa9f679124e8b320494ad3).

The following can also be handy:

* Concourse version: 3.7.x
* Deployment type (BOSH/Docker/binary): bosh

**Comment by ddadlani** [comment]
closing because this has been fixed in https://github.com/concourse/concourse/pull/3540
