### ISSUE TITLE
use vagrant run concourse box error

### ISSUE THREAD

**Issue by AdoHe** [concourse/concourse#187]
FYI. On a Linux Host(Centos 7), I tried to use vagrant to get a Concourse instance going, but always failed. I did have the virtualbox provider. I think the error is related with `VT-x is disabled on BIOS`, but I did try to modify the `vbox` configuration. It seems useless.

**Comment by vito** [comment]
Sounds like your host machine didn't have virtualization enabled? I don't think that's anything Concourse specific, more virtualbox in general on that host. (Closing for that reason.)
