### ISSUE TITLE
[Beta Build View] In-progress jobs are falsely appearing to fail

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1871]
# Bug Report

This build is still in progress, but, in the beta build view, it is red like it has already failed:

![erroneous redness yo](https://i.imgur.com/HslDLJ5.png)

That job ultimately went on to succeed and turn green.

![righteous green](https://i.imgur.com/2GFxesX.png)

Jobs should be yellow when they are in-progress.

* Concourse version: 3.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? It definitely worked in the non-beta build view. I'm not sure if it worked in previous beta build views.

**Comment by jama-pivotal** [comment]
A lot of functionality isn't implemented at all in the `beta` route. We're going to "fix" this by actually working on it...so tempted to just close this
