### ISSUE TITLE
[Multi-Pipeline View] Thumbnails of pipelines with a lot of jobs show up as huge empty boxes

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1872]
# Bug Report

This is definitely an edge-case, but it is negatively affecting the way our dashboard is rendering.

We have a pipeline with like a million jobs that can all run side-by-side: 

![embarassing, I know](https://i.imgur.com/6m8wOEq.png)

The dashboard is rendering the thumbnail for this monstrosity as a very tall, empty box.

![big empty box](https://i.imgur.com/QaJolco.png)

It would be better if this thumbnail showed up as a lot of narrow strips, with each strip representing one job. If that can't be done, maybe the empty box could be limited in height. No matter what, it probably shouldn't render as a comically huge empty box.

* Concourse version: 3.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? It was the same in 3.6.0

**Comment by jama22** [comment]
Adding to the design backlog as something we can maybe address. Instead of trying to even render it we should just swap it out with a placeholder design or something

**Comment by xtremerui** [comment]
closing as problem gone in latest version.
