### ISSUE TITLE
Getting 'certificate signed by unknown authority' when trying to connect concourse to credhub

### ISSUE THREAD

**Issue by xtreme-peter-iskandar** [concourse/concourse#1873]
# Bug Report

The following can also be handy:

* Concourse version: 3.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): 
* Did this used to work? No

When trying to deploy concourse on GCP with credhub, the Web VM does not start up and the logs are giving the following error
`Get https://10.0.0.6:8844/info: x509: certificate signed by unknown authority`
we tripled checked to see that all the certs match and they seem to.

in the ATC job's properties we have the following:
```
credhub:
  client_id: director_to_credhub 
  client_secret: ((credhub_client_secret))
  path_prefix: /concourse
  tls:
    insecure_skip_verify: false
    ca_cert: ((credhub_tls_ca_cert))
```

and we provide the same cert that we use when we create the bosh director, where our credhub lives. We can log into the credhub api via command line with the following
```
credhub api \
--ca-cert=<(bosh int ./creds.yml --path /credhub_ca/ca) \
--ca-cert=<(bosh int ./creds.yml --path /uaa_ssl/ca) \
--server=10.0.0.6:8844
```

we then deploy concourse via BOSH, putting the cert into a params.yml so it will be loaded properly.

```
bosh -e gcp-bosh -d concourse deploy jetway-gcp/concourse/concourse.yml \
	-l /tmp/concourse-creds.yml \
	-v external_url=http://$CONCOURSE_URL \
	-v encryption_key=<ENCRYPTION_KEY> \
	-v credhub_client_secret=<(bosh int ./creds.yml --path /uaa_clients_director_to_credhub) \
	-v credhub_ip=10.0.0.6 \
	-l params.yml
```

params.yml contains the following:
```
credhub_tls_ca_cert: |
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----
```

We've tried chaining the two CA certs from when we log in via command line and that still doesn't work we get the `Get https://10.0.0.6:8844/info: x509: certificate signed by unknown authority` error still.

**Comment by making** [comment]
I have the same issue with 3.8.

Even though

```
curl --cacert /var/vcap/jobs/atc/config/credhub_ca_cert https://<credhub-ip>:8844/info
```

worked from web VM, I also get the following log in `/var/vcap/sys/log/atc/atc.stderr.log`

```
Get https://10.244.1.100:8844/info: x509: certificate signed by unknown authority
```

As a workaround, I configured `insecure_skip_verify: true`

**Comment by vito** [comment]
Just found this in the code, fixing it now. It was simply not using the CA cert flag. Oi.

On the plus side, we're now making sure to test this in our pipeline.
