### ISSUE TITLE
Check if legacy `migration_version` table exists before querying it

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#1874]
Whenever we run migrations we query the legacy `migration_version` table to guard against upgrading from a version of concourse < v3.6.0. However, in versions v3.7.0 and above this table doesn't exist and logs the following error:

```
ERROR:  relation "migration_version" does not exist at character 21
STATEMENT:  SELECT version FROM migration_version
```

This is confusing because it looks like an error, when in fact its expected behaviour. We should probably suppress this message by checking for the existence of this table before directly querying it.

```
SELECT EXISTS(SELECT 1 FROM information_schema.tables where table_name = 'migration_version')"
```

**Comment by learntechie** [comment]
Hello, I'm running into the same problem when i try to run concourse image with docker-compose. Copying part of the log.  Appreciate any pointers.

concourse-worker_1  | {"timestamp":"1513799970.383881807","source":"guardian","message":"guardian.started","log_level":1,"data":{"addr":"127.0.0.1:7777","network":"tcp"}}
concourse-db_1      | ERROR:  relation "migration_version" does not exist at character 21
concourse-db_1      | STATEMENT:  SELECT version FROM migration_version
concourse-db_1      | ERROR:  relation "migration_version" does not exist at character 21
concourse-db_1      | STATEMENT:  SELECT version FROM migration_version
concourse-web_1     | {"timestamp":"1513799970.862541199","source":"tsa","message":"tsa.listening","log_level":1,"data":{}}
concourse-web_1     | {"timestamp":"1513799970.863152027","source":"atc","message":"atc.listening","log_level":1,"data":{"debug":"127.0.0.1:8079","http":"0.0.0.0:8080"}}
concourse-web_1     | {"timestamp":"1513799975.110801935","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"172.18.0.4:56954","session":"1","type":"keepalive"}}
concourse-web_1     | {"timestamp":"1513799975.111286879","source":"tsa","message":"tsa.connection.channel.channel-request","log_level":1,"data":{"remote":"172.18.0.4:56954","session":"1.1","type":"exec"}}
concourse-web_1     | {"timestamp":"1513799975.111749411","source":"tsa","message":"tsa.connection.tcpip-forward.forwarding-tcpip","log_level":1,"data":{"remote":"172.18.0.4:56954","requested-bind-addr":"0.0.0.0:7777","session":"1.2"}}
concourse-web_1     | {"timestamp":"1513799975.111840010","source":"tsa","message":"tsa.connection.channel.forward-worker.forwarded-tcpip","log_level":1,"data":{"bound-port":44628,"remote":"172.18.0.4:56954","session":"1.1.1"}}
concourse-web_1     | {"timestamp":"1513799975.112034798","source":"tsa","message":"tsa.connection.tcpip-forward.forwarding-tcpip","log_level":1,"data":{"remote":"172.18.0.4:56954","requested-bind-addr":"0.0.0.0:7788","session":"1.3"}}

**Comment by queeno** [comment]
I have exactly the same issue 👍

**Comment by pivotal-jwinters** [comment]
Just to clarify - seeing these logs does not indicate there is a problem. In fact you should see them on any deployment of v3.7.0 and above. This issue is to track the fact that these logs are confusing and we should suppress them.

**Comment by shashwathi** [comment]
Added additional check to verify table exists before querying. This should remove db error logs which could mislead users.
