### ISSUE TITLE
pq: syntax error at or near "MATERIALIZED" when running concourse web in installation instructions

### ISSUE THREAD

**Issue by hibbert** [concourse/concourse#1875]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug

# Bug Report

Bug reports are pretty free-form; just replace this with whatever. You can also help us triage the issue by including steps to reproduce, expected results, and the actual result. Help us help you!

The following can also be handy:

* Concourse version: 3.7.0
* Deployment type (BOSH/Docker/binary): Standalone binary
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work? N/A

I am trying to follow the instructions here, main obstacle was installing and configuring postgresql which isn't explained here so I looked elsewhere. When I run the concourse web command I get the following:-

failed to migrate database: migration failed in line 0: BEGIN;
# Bunch of SQL
COMMIT;
 (details: pq: syntax error at or near "MATERIALIZED")

Any ideas as to why this is?

**Comment by vito** [comment]
Are you running Postgres 9.5+?

https://concourse.ci/binaries.html#prerequisites

**Comment by hibbert** [comment]
Yeah, you're right hadn't looked closely enough at the prerequisites. Thanks for your help

**Comment by vito** [comment]
No problem!
