### ISSUE TITLE
v3.7.0 BOSH doesn't error if token signing key is not specified

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#1876]
# Bug Report

As of v3.7.0, the generated token signing key is no longer provided. However the templates for the signing key in ATC + TSA default to `""` when that is not found. As a result, we get a happily-rendered template, and BOSH starts to deploy. However both ATC +TSA fail to start, with the following stderr output:

```
failed to parse session signing key as RSA: Invalid Key: Key must be PEM encoded PKCS1 or PKCS8 private key
```

Should the default empty string be removed from the template, to force the failure before deploy-time?

**Comment by vito** [comment]
Totally, I'll fix that now. Thanks for the report!
