### ISSUE TITLE
Bearer token messaging is confusing

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#1880]
# Bug Report

I am setting up oauth for teams, but I would like to have a long-lived machine login to that team to keep the pipelines up to date. So to make that happen, I went to my OAuth provider, Okta, to get a  [token](https://developer.okta.com/docs/api/getting_started/getting_a_token.html), in keeping with the prompting in `fly`:

```
logging in to team 'oauthtest'

navigate to the following URL in your browser:

    http://192.168.100.4:8080/auth/oauth?team_name=oauthtest&fly_local_port=53746

or enter token manually: literalbearertoken
token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: Bearer literalbearertoken

target saved
```

~./flyrc:
```
targets:
  deploy:
    api: http://192.168.100.4:8080
    team: oauthtest
    token:
      type: Bearer
      value: literalbearertoken
```

This appears to be a proprietary API token with no connection to oauth, so now everything kind of breaks:

```
$ fly targets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x144a9b1]

goroutine 1 [running]:
github.com/concourse/fly/commands.GetExpirationFromString(0xc4201ee580, 0x0, 0x0)
	/Users/pilot/Worker/workdir/volumes/live/7befb896-066b-44e7-68af-dd6296d21790/volume/concourse/src/github.com/concourse/fly/commands/targets.go:59 +0x81
github.com/concourse/fly/commands.(*TargetsCommand).Execute(0x1b1eed0, 0xc4201de9d0, 0x0, 0x1, 0x1b1eed0, 0x1)
	/Users/pilot/Worker/workdir/volumes/live/7befb896-066b-44e7-68af-dd6296d21790/volume/concourse/src/github.com/concourse/fly/commands/targets.go:33 +0x31e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420074cc0, 0xc420088070, 0x1, 0x1, 0xc4200fdb90, 0xc420074de0, 0x7fff5fbff868, 0x0, 0x0)
	/Users/pilot/Worker/workdir/volumes/live/7befb896-066b-44e7-68af-dd6296d21790/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:316 +0x893
github.com/jessevdk/go-flags.(*Parser).Parse(0xc420074cc0, 0x1b1eec0, 0x2, 0xc420074de0, 0xc4201ae5a0, 0x16bdc80)
	/Users/pilot/Worker/workdir/volumes/live/7befb896-066b-44e7-68af-dd6296d21790/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x73
main.main()
	/Users/pilot/Worker/workdir/volumes/live/7befb896-066b-44e7-68af-dd6296d21790/volume/concourse/src/github.com/concourse/fly/main.go:48 +0x2f3
```

I can reproduce with Concourse 3.4, 3.6 and 3.8.

I think what I really should be doing is logging in via the normal flow, and then pulling the bearer token out of ~/.flyrc after the fact.

**Comment by shashwathi** [comment]
@hfinucane : Concourse uses jwt token parser to parse these tokens manually and has a strict format of `BEARER token_value`. Running `fly targets` commands loads the targets with valid tokens from flyrc file, explains the error which you get.  

What is not clear in help msg for entering tokens manually?

**Comment by hfinucane** [comment]
The bug is that if you enter the wrong kind of token at the `fly login` prompt, `login` accepts it, but anything that tries to use it blows up later. Probably it should do that validation on the front-end.

**Comment by shashwathi** [comment]
`feature/token-error` branch in fly project contains this feature.
