### ISSUE TITLE
atc to support multiple metric emitters at once?

### ISSUE THREAD

**Issue by schroederma** [concourse/concourse#1881]
Hi,

I am currrently using the bosh release of concourse in version 3.6.0.
Until now we had used riemann for metrics emitting.
We want to add Influxdb.
If I read the release notes correctly, currently only one emitter is possible.
Is it planned to support multiple at a time?

Many Thanks,
Martin

**Comment by marco-m** [comment]
This should be closed after decision taken in #2896.
