### ISSUE TITLE
Pipeline view stuck in pending

### ISSUE THREAD

**Issue by knifhen** [concourse/concourse#1882]
# Bug Report

Hi,
Since upgrading to version 3.7/3.8 the pipeline view is broken for us. It no longer shows any updates to the status of build jobs. All stages of the pipeline is stuck in the grey  statuses that show before any builds has happened. Clicking the jobs and resources will show the correct statuses though.

We have the same problem with the beta dashboard views. Looking at the overview or an individual pipeline everything is stuck in pending. Going into a job will show things correctly.

Best regards Andreas Knifh

* Concourse version: 3.7.0, 3.8.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Google cloud, ubuntu 16.04
* Browser (if applicable): firefox, chrome, safari
* Did this used to work? Used to work in version 3.5.0

**Comment by jtarchie** [comment]
Did you following the instructions in the release notes about upgrading the Postgres database to 9.5+?

**Comment by knifhen** [comment]
Hi, thx for pointing it out. I had used the defaults for an ansible role and that was set to postgres 9.3. Now running postgres 9.6 it works fine just like you suggested.

Best regards, Andreas Knifh
