### ISSUE TITLE
Trigger build button does nothing while visible when user login to a different team

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#1883]
Hi, This is a # Bug Report

If user login to a team and viewing a build page of a public pipeline that from another team, the `+` button on the top right for triggering build is visible while clicking it does nothing. Since in this case the user has no right to trigger the build (different team), the button should be invisible.

* Concourse version: 3.7
* Deployment type (BOSH/Docker/binary): BOSH
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by timrchavez** [comment]
We hit this all the time.

**Comment by kkallday** [comment]
Yes. We are also noticing this with Concourse 5. When I login as a user that has "Team Viewer" access, I can still see the "+" that allows me to trigger a job. When I click it it doesn't do anything which is *correct* however, I wouldn't expect the button to be there (see screenshot).
![Screen Shot 2019-03-20 at 10 56 18 AM](https://user-images.githubusercontent.com/926865/54707943-7ca7d300-4aff-11e9-9498-20e63f1be07b.png)

**Comment by jama22** [comment]
The general theme here seems to be "how do we treat actions that you don't have permission to do?". 
 
We've talked about two strategies in the past:

1. Hide the action based on your detected role, or 
2. show the anyways and deny you when you attempt the action

Currently, based on the implementation of the API and the backend (1) is impossible. But hopefully its more likely with the work that @pivotal-jwinters is doing. (2) is probably the only thing we can do in the meantime.
