### ISSUE TITLE
Investigate a new approach to Auth

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#1886]
## Background
We are looking into moving all the auth(z) work into its own service. The goal is to eventually overhaul the entire thing and move towards a global `user` model, where each `user` can belong to multiple `teams`.

We are looking at using a third party solution ([coreos/dex](http://github.com/coreos/dex)) to handle all the various provider integrations. The new auth service would then just be a thin wrapper used to exchanged `dex` tokens for a `concourse` token. 

### Tokens
The `concourse` token would contain a `groups` claim that maps to a list of `teams`. The `atc` would use these claims to authorize various actions. 

### Can I use ___________ instead of this new auth component?
In theory, we could swap out this component for other solutions. For example we may be able to use `UAA`. They seem to use `scopes` for group association instead of a `groups` claim, though, so it wouldn't be a clean swap. In theory though if the other service has a way of managing `groups` that they expose through a claim, then, yes, it should be possible.

## Endgame
All this to hopefully enable #1317

**Comment by shinji62** [comment]
@pivotal-jwinters I think before moving to Dex you need to implement UAA connector as some (maybe many) rely on the UAA integration.

**Comment by pivotal-jwinters** [comment]
@shinji62 yeah its on our radar :). We don't plan on breaking support for any existing providers. But as you say, we will likely have to contribute a few connectors back to `dex` to make that happen.

**Comment by pivotal-jwinters** [comment]
Just a couple updates here since we've been making some progress on this track.

## atc start
Each provider you want to support will now be configured at startup, instead of every time you `fly set-team`. This means that you will provide a single set of configuration (`client_id`, `client_secret`, `redirect_uri`, etc.). for each provider and it will be used for every login attempt.

## fly set-team
This command will no longer accept provider configuration. Instead you will supply a list of `users` and `groups` that you want to authorize for that team. Each user or group must be scoped to its provider.

For example `fly set-team -n my-team --user=local:my-username --user=local:my-other-username --group=github:my-org:my-team --group=github:my-other-org`

This basically means this team grants access to two basic auth users `my-username` and `my-other-username` as well as anyone within the `my-org/my-team` team or the `my-other-org` organization on github.

@vito @jama-pivotal @topherbullock

**Comment by vito** [comment]
(Talked w/ @pivotal-jwinters in person, updating to keep this up-to-date)

Since we have to have code/flags in skymarshal anyway for configuring each provider, we might as well also have code/flags there so that we can have nicer flags in `fly set-team` and `concourse web` (for the `main` team). I think it'll make it a bit easier to discover how to configure teams. The flags themselves would just map to whatever `--user/--group` notation is appropriate as described above.

**Comment by lukaslehmann** [comment]
If we connected concourse to a UAA instance is there any option to see which user triggered a certain build?

**Comment by pivotal-jwinters** [comment]
@lukaslehmann yup, the goal is to enable auditing for all kinds of user events. It wont matter what provider/connector you're using.

**Comment by lukaslehmann** [comment]
thanks for your quick feedback here @pivotal-jwinters - is there already any idea available by when this will be possible?
