### ISSUE TITLE
ipv6 support in containers?

### ISSUE THREAD

**Issue by phillbaker** [concourse/concourse#1889]
## What challenge are you facing?

(If I've missed a configuration setting, I apologize - I think this is a feature request, but might just be a documentation clarification.)

Some of the jobs we run make connections to ipv6-only addresses, and currently fail because (I believe) ipv6 support is not enabled when concourse configures garden (which wraps guardian's runc). The hosts we run concourse on are ipv6 enabled. 

There was some support for ipv6 loopback in guardian added in https://github.com/cloudfoundry/guardian/issues/79, and then made more extensible with https://github.com/cloudfoundry/guardian/issues/100. 

## A Modest Proposal

I believe we could configure `AdditionalHostEntries` in [the garden config](https://github.com/concourse/bin/blob/master/cmd/concourse/worker_linux.go) to contain at least the loopback. I don't fully understand how garden is configured for its current ipv4 networking, but would appreciate a few pointers and then would like to submit a PR adding support for ipv6 configuration.

**Comment by vito** [comment]
How is your Concourse deployed? I believe IPv6 is currently disabled in all BOSH stemcells for example. We don't really have any say in the matter from the Concourse side.

**Comment by phillbaker** [comment]
* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): Binary (systemd)
    Infrastructure/IaaS: AWS (but probably irrelevant here)
    Overlay Driver
    Ubuntu 16.04.3 LTS

**Comment by phillbaker** [comment]
Was this closed as a "won't fix" or because it was believed to have been fixed?

**Comment by Infinoid** [comment]
This does not appear to be fixed.  At least with the `concourse/concourse` image on dockerhub, the worker container can have a valid IPv6 configuration, but when the worker runs a task, that task does not have access to IPv6 services.

**Comment by vito** [comment]
@Infinoid Would you mind opening a new Discussion for this? It may be something we can address with the new `containerd` based backend we've been working on.

**Comment by Infinoid** [comment]
I opened Discussion #5919.
