### ISSUE TITLE
Lack of status updates on in-flight put

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#189]
We had a build that was yellow, but all the steps in the build plan that were visible on the screen were green.  We thought this meant that the worker was hung.

We came back to it a few minutes later, and the build was green, and had an extra put at the end, which had just gone green.

We were surprised that there was no indication earlier that there was a pending / in-flight put.  It would be nice to see the reason why a build is still yellow when every visible step is green.

Rob & @rosenhouse

**Comment by rosenhouse** [comment]
A visual example from today:

![what-is-it-doing](https://cloud.githubusercontent.com/assets/4128521/11161652/a0a08e64-8a37-11e5-8db5-57f9b149c29e.png)

The build page stayed like this for several minutes.  Eventually, it turned into this:

![green](https://cloud.githubusercontent.com/assets/4128521/11161665/e561ddc8-8a37-11e5-9a35-fbd7baee1125.png)

That last step was an S3 upload that took a long time to complete.  But we saw no progress.

**Comment by vito** [comment]
We've got some work coming up that may allow us to pre-render the entire sequence of steps and have them become "active" as the plan executes. In this case though the first story to do would probably be to have the s3 resource emit upload/download progress, or at least to render the step as soon as it's executing (which I think we already do for tasks).

**Comment by vito** [comment]
This should be fixed now; the s3 resource emits progressbars, and we show the `put` and `get` steps as active immediately as they start to run.
