### ISSUE TITLE
Give some indication of what's happening between build steps

### ISSUE THREAD

**Issue by timrchavez** [concourse/concourse#1891]
# Feature Request

## What challenge are you facing?

Things are happening between build steps but admins and interested developers have no good (simple) ways to get that information. Is the task being prepared (Is it fetching or syncing resources, mounting volumes, etc) or is it blocked waiting for a place to run?

## A Modest Proposal

This could be implemented as part of https://github.com/concourse/concourse/issues/1890 but I think it might be cool to have this information integrated into the build log view as well, perhaps exposed by toggling a debugging icon or sorts. The idea is generally a developer is mostly interested in the execution of their actual build scripts or tests, but occasionally something peculiar will happen. Maybe there was a cache miss on the worker and it had to fetch something, giving developers a self-service way to explain away behavioral changes in their pipelines, would be :+1:.

**Comment by marco-m** [comment]
@vito After one year of operating Concourse, I believe that this and #1890 are the most important missing pieces of Concourse for troubleshooting and ops. Could you please consider implementing this? Thanks!

**Comment by vito** [comment]
@marco-m Happy to review a proposed UI pattern or something for this to get the ball rolling, but we've got a lot on our plate at the moment.

**Comment by xtremerui** [comment]
close in favor of #4337
