### ISSUE TITLE
Add direct linking to resource versions

### ISSUE THREAD

**Issue by timrchavez** [concourse/concourse#1894]
# Feature Request

## What challenge are you facing?

Sharing information about a particular resource version of a pipeline can be difficult. We have the ability to link to https://concourse.fqdn/teams/TEAM/pipelines/PIPELINE/resources/RESOURCE, but then have to include version information separately, search for it in the list, and click buttons to drill down.

## A Modest Proposal

It would be nice if a permalink was generated for each resource version, e.g. https://concourse.fqdn/teams/TEAM/pipelines/PIPELINE/resources/RESOURCE/VERSION that could be shared. It would open the relevant version of the resource on the pipeline belonging to that team.

**Comment by timrchavez** [comment]
I'm going to look into implementing this one soon-ish.

**Comment by marco-m** [comment]
Hello @timrchavez did you do any progress on this ? I find it useful.

**Comment by jama-pivotal** [comment]
@timrchavez just to echo @marco-m , are you still working on this?

**Comment by jama-pivotal** [comment]
Moving back to icebox since its been a while since we got an update
