### ISSUE TITLE
Pipeline names should be validated for "sensible" characters

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1902]
# Bug Report

I'm not sure how we managed to do it, but our team recently deployed a pipeline to concourse that has a line-break character in it: 

```
concourse> SELECT version,id,name FROM pipelines
+-----------+------+---------------------------+
| version   | id   | name                      |
|-----------+------+---------------------------|
| 1578      | 60   | monitoring-boshrelease    |
| 1584      | 61   | elasticsearch-boshrelease |
| 1593      | 58   | meshfed-gradle            |
| 1539      | 59   | haproxy-boshrelease       |
| 1589      | 62   | kafka-boshrelease         |
| 1597      | 63   | couchdb
-boshrelease                           |
| 1407      | 30   | service-broker-example    |
| 1410      | 36   | service-broker-mongodb    |
| 1411      | 24   | service-broker-mysql      |
| 1518      | 4    | meshfed-release           |
| 1405      | 39   | service-broker-release    |
| 1512      | 48   | rabbitmq-boshrelease      |
| 1585      | 54   | mongodb-boshrelease       |
| 1412      | 25   | service-broker-postgresql |
| 1413      | 27   | service-broker-rabbitmq   |
| 1408      | 45   | service-broker-lbaas      |
| 1517      | 56   | mysql-boshrelease         |
| 1536      | 53   | postgres-boshrelease      |
+-----------+------+---------------------------+
SELECT 18
Time: 0.005s
```

The `fly` cli is not able to delete this pipeline (or at least we weren't able to hand it a properly escaped string). The only way we could remove it was by directly messing with the concourse db. 

It might be worthwhile to restrict the character set for pipeline names to a sensible set (e.g. only printable characters). 

Using Concourse 3.6

**Comment by vito** [comment]
We should probably do this for everything (jobs, resources, steps, inputs, outputs?), to be honest.

See also https://github.com/concourse/concourse/issues/1892

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/3985 which I really really really want to actually get to now. I've poked the bear by suggesting a super narrow character set. Hopefully people reply. :P
