### ISSUE TITLE
Rapid Volume creation when using the `btrfs` driver causes worker to stall

### ISSUE THREAD

**Issue by doty-pivotal** [concourse/concourse#1903]
# Bug Report

* Concourse version: `3.8.0`
* Deployment type (BOSH/Docker/binary): `BOSH`
* Infrastructure/IaaS: `GCP`
* Browser (if applicable): `n/a`

## Behavior: 

Many jobs start at once, and during the course of creating enough volumes to service the influx of jobs, a worker stalls - which is manifested by jobs going orange with errors like:

```
Get /volumes-async/160a9d4f-9701-4386-4b66-dca417e8ffbb: worker '0a1cfcae-bc81-498c-bc56-ba038d6ee589' is unreachable (state is 'stalled')
```

Looking at the worker's vitals:

```
± |master ✓| → bosh -d btrfs vms --vitals
...
Instance                                     Process State  AZ  IPs          VM CID                                   VM Type   VM Created At  Uptime  Load                    CPU    CPU   CPU   CPU    Memory       Swap         System      Ephemeral   Persistent
                                                                                                                                                       (1m, 5m, 15m)           Total  User  Sys   Wait   Usage        Usage        Disk Usage  Disk Usage  Disk Usage
...
worker/0a1cfcae-76a7-4a91-bd02-bf30bcc643c8  running        z1  192.168.2.9  vm-2984ea1b-bee8-4b00-72b2-ff3d18da277e  worker    -              -       217.75, 207.45, 178.66  -      0.2%  1.0%  72.0%  22% (14 GB)  4% (2.5 GB)  43% (33i%)  24% (0i%)   -
```

[ In this snapshot of the worker the CPU wait is high, but often times the CPU wait settles back down to ~ 0% and the worker's still is locked up. ]

The worker never recovers and has to be recreated.

## Desired Behavior:

Since rapid volume creation is known to cause worker stalls, if the root cause is not fixable, perhaps limiting the number of concurrent volume creations would eliminate locking up the worker, at the expense of having the pipelines have to wait for their volumes to be created.

## Notes:

We've had the issue in several versions of `2.*`.  We took the default of `overlay` driver when we upgraded to `3.4.1`.  There are jobs in our pipeline that have to `chown` a large number of files from each volume.  Under a low load this adds ~5 minutes to each test, but when there are a large number of jobs trying to run that operation simultaneously, we have seen the operation take >30mins.  This motivates us to return to the `btrfs` driver, but at an up to date version of Concourse.  We started the upgrade on our smallest deployment which has 

`# of worker`: `5`
`vm_type`: `n1-standard-4`
`disk_size`: `300 GB`
`disk_type`: `pd-standard`
`# pipelines`: `14`
`Avg # containers/worker`: 41

and the workload on this pipeline is not as periodic as our two "production" deployments. The worker stalls in this deployment, and thus we are reluctant to use the `btrfs` driver in our larger deployments.

We have created a smaller deployment that can reproduce the issue. 

`# of workers`: `1`
`vm_type`: `n1-standard-16`
`disk_size`: `600`
`disk_type`: `pd-standard`
`# pipelines`: `variable`
`Avg # containers/worker`: `52`

And we can easily simulate a similar, highly periodic, workload similar to what we see on our production deployments.  We can use this deployment to assist with debugging.  Please let us know what information would be useful to the team.

**Comment by phillbaker** [comment]
@doty-pivotal curious if the fix for https://github.com/concourse/concourse/issues/1966 released in v3.9 would have helped here - are you still seeing the issue?

**Comment by vito** [comment]
Yeah, I'm gonna close this since it's pretty stale and *probably* improved by #1966.

**Comment by doty-pivotal** [comment]
This issue has not been resolved.  We are apparently scheduling time directly with the team to work on this issue.
