### ISSUE TITLE
Additional entries in runC spec file

### ISSUE THREAD

**Issue by juaningan** [concourse/concourse#1905]
When garden creates a container I'd like to add additional entries in config.json (for instance bind mount new devices, an OCI hook, or whatever), is the --garden-image-plugin the way to do? Can you provide an example?

**Comment by topherbullock** [comment]
Concourse provides the specification for the containers it creates in Garden via Garden's [client library](https://github.com/cloudfoundry/garden/blob/master/client.go), so we _could_ **_potentially _** allow some setting to allow each Garden container created by the ATC to have some configuration added to its [ContainerSpec](https://github.com/cloudfoundry/garden/blob/master/client.go#L62-L168).. This would be useful for a global setting of #787.

Going beyond Garden's `ContainerSpec` and directly modifying or adding entries to the `config.json` passed to RunC would be a feature request for Garden itself.

What are you trying to achieve within Concourse with this? Is this for a specific task container, or for all containers?

**Comment by juaningan** [comment]
Actually my usecase is to get kvm acceleration running in runC container on concourse. So I was thinking in OCI hooks to modify the standard config.json that concourse initialize.

Anyways, garden people give me some hints:
https://github.com/cloudfoundry/garden-runc-release/issues/55
(tl;dr: use runtime_plugin and wrapper the runc call to modify config.json)

I think that I can go with this by now
