### ISSUE TITLE
Jobs with a '+' in the name cause a 404 in the web UI.

### ISSUE THREAD

**Issue by alext** [concourse/concourse#1906]
# Bug Report

We're seeing an issue where jobs with a `+` in the name cause a 404 in the UI. When this happens, manually replacing the `+` with a `%2b` in the URL makes the page work.

We discovered this while trying to use the [Concourse Christmas tree](https://gist.github.com/alext/e2de098f733b203bd350e4ccbacfe986).

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Docker for Mac
* Browser (if applicable): Chrome
* Did this used to work?: Unknown

I've also seen this on version 3.4.1 deployed on AWS using BOSH.

**Comment by mhuangpivotal** [comment]
This appears to a problem in rata: https://github.com/tedsuo/rata/blob/master/routes.go#L121. For some reason, `url.PathEscape` leaves `+` as it is, but `url.QueryEscape` escapes `+` to `%2B`.

**Comment by vito** [comment]
Folding into https://github.com/concourse/concourse/issues/1906

**Comment by hfinucane** [comment]
@vito this is #1906?

**Comment by vito** [comment]
@hfinucane ...yeah, and I folded it into it!

(i meant https://github.com/concourse/concourse/issues/1902)
