### ISSUE TITLE
fly support for seeing how teams are configured

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#1913]
We're trying to set up a pipeline to automate how our teams are configured, to make it easier to stand up new concourse servers, or migrate them to other environments, while keeping access for existing users. However, we can't get any configuration data out for who can access which teams, short of diving into the ATC database and parsing out the data from the teams table. It would be really nice if `fly` could do this for us, while still redacting any sensitive info like client_id/secrets.

**Comment by geofffranks** [comment]
I'd also be happy with the ability to configure teams via the bosh release :)

**Comment by marco-m** [comment]
@geofffranks Concourse 5.2 added a new `get-team` subcommand to fly https://github.com/concourse/concourse/releases/tag/v5.2.0#v520-note-12. Is this (and maybe other changes happened in-between) solving your problem? If yes, could you please close this issue? Thanks!

**Comment by vito** [comment]
Yep there's also `fly teams -d` which was added a long while back. I think this can be closed. :+1:
