### ISSUE TITLE
Missing support for generic oauth ca cert in bosh release

### ISSUE THREAD

**Issue by scnewma** [concourse/concourse#1914]
# Feature Request

## What challenge are you facing?

We are trying to setup the Concourse bosh release to add support for generic oauth with the Concourse main team.  Our OAuth provider uses a self-signed certificate, and the current bosh release does not seem to have the option to pass in a ca certificate when configuring auth.

## A Modest Proposal

It would be great to have a `generic_oauth.ca_cert` option in the bosh release to allow users to pass in this option when setting up generic oauth via the bosh release.

**Comment by youngm** [comment]
This issue should be fixed now and can be closed.
