### ISSUE TITLE
It is impossible to run `check-resource` on a renamed resource. 

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse#1916]
# Bug Report

We have a resource that is renamed at the `get` level, like:
```
- get: our-name
  resource: some-resource
```

When we try to run `check-resource` on `some-resource` nothing happens, and we are stuck in with the versions that concourse automatically sees. This is a problem when we had previously pinned the resource version at the `get` level, like 

```
- get: our-name
  resource: some-resource
  version: some-version
```

The only way we think we can get around this issue is to temporarily remove the resource renaming, reset the pipeline, run check-resource, and then reset the pipeline the pipeline back to our desired configuration with the renaming. 

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: N/A
* Browser (if applicable): N/A
* Did this used to work? No

-- Josh and @madamkiwi

**Comment by vito** [comment]
Something else must be going on here. `check-resource` has no connection to build plans, which is where this renaming is occurring; it's simply the pipeline-name/resource-name.

Can you include the command you're running and the config for the pinned version?
