### ISSUE TITLE
Concourse freezes browser for minutes at a time when opening (large) build log

### ISSUE THREAD

**Issue by kdvolder** [concourse/concourse#1917]
This issue is similar to https://github.com/concourse/concourse/issues/1009

However the logs in my case aren't really 'live'. The build in question is already completed. So I'm hoping since this is slightly different (no live streaming of active logs) it might be more easily addressable. 

When I click a failed job to inspect the results, it just sits their with a loading cursor for what seems like forever (a few minutes).

During that time, nothing much happens and it also seems to lock up the browser (Chrome or Firefox) which becomes very unresponsive (takes seconds before it responds to clicks or keystrokes).

Yes, this is a hefty build, it runs for over an hour and produces fairly large logs, but I don't think it isn't 'exceptional' or 'extraordinary'. To give an idea, I just downloaded a copy of the logs from our bamboo build (a build we are thinking of migrating it to concourse but still run it on bamboo).

The logfile is about 4 mb in size has about 30000 lines of log output.

Yes, I have seen the suggestion on the other ticket that we could instead redirect logs to a file and save them to some kind of resource. But honestly I really don't think that should be considered an acceptable solution.

This issue is probably going to be show stopper for us moving some of our more hefty builds to concourse. Much as I love concourse and would like to use it more, the user experience around concourse's log viewing for anything that isn't producing a fairly limited amount of output is simply not acceptable.

**Comment by kdvolder** [comment]
BTW: The experimental pipeline is here, publically viewable. So you can have a look for yourself and judge how bad it is. I'll leave it up there for a while: 

https://ci.spring.io/teams/tools/pipelines/sts3-master/jobs/build-and-test-e47

Try clicking on some of the later logs like for example:

https://ci.spring.io/teams/tools/pipelines/sts3-master/jobs/build-and-test-e47/builds/17

**Comment by Eulerizeit** [comment]
This is a huge problem. It has become impossible to open finished jobs in certain pipelines. 

https://gpdb.data.pivotal.ci/builds/6166  here is an example that took 10 min to load. 

Concourse v 3.8.0

**Comment by kdvolder** [comment]
Agreed. I think we can close this one as a duplicate.
