### ISSUE TITLE
request: fly set-pipeline to display parameters that are no available in credentials manager

### ISSUE THREAD

**Issue by drnic** [concourse/concourse#1920]
# Feature Request

## What challenge are you facing?

I love credentials manager. I even raved about it in https://concoursetutorial.com/basics/secret-parameters/

I love dynamic, last-possible moment, binding of parameters to values stored in credentials manager. The downside is that you don't find out you've not yet setup (or misnamed or placed it in the wrong /concourse/team location) until you're pipeline is running.

## A Modest Proposal

```
fly -t mytarget set-pipeline -p mything -c pipeline.yml
```

This would display a list of parameters that are no yet provided by the underlying credentials manager for target `mytarget`.

**Comment by edtan** [comment]
I've submitted two other PRs to add a `--skipcreds` option to allow skipping the validation, but the default behavior is to validate the credentials.
