### ISSUE TITLE
Prometheus metrics for worker containers and volumes don't coincide with API responses

### ISSUE THREAD

**Issue by william-tran** [concourse/concourse#1921]
# Bug Report

When I `fly workers` or `fly volumes`, the number of containers and volumes per worker reported by the CLI, coming from the /workers or /volumes endpoints, don't coincide with the prometheus metrics. I also noticed that when running multiple ATCs, there could be more than one ATC reporting for a single worker, where only one of those numbers reported is anywhere close to the number reported by the API. This makes reporting difficult, as I can't find a way to tell my Grafana which number to use, `max(concourse_workers_containers) by (worker)` only works if the number is always increasing. But maybe that's just my noobness with PromQL. Nevertheless, among the multiple numbers emitted by prometheus, none equal the API response.

**Comment by william-tran** [comment]
cc @TimSimmons @jmcarp

**Comment by vito** [comment]
should be fixed by https://github.com/concourse/atc/pull/277
