### ISSUE TITLE
Feature request: optional inputs to support gradual evolution of tasks

### ISSUE THREAD

**Issue by rosenhouse** [concourse/concourse#1923]
## What challenge are you facing?
Our team uses [some concourse tasks](https://github.com/cloudfoundry/cf-deployment-concourse-tasks) that are maintained by another team.  That "upstream" team goes to some trouble to maintain [semver](https://semver.org/) tags, which is awesome.

Sometimes they want to introduce a new feature for a task, and the feature depends on a new `input`.  Following the spirit of semver, they ought to be able to do this in a minor version.

But [as the Concourse docs say](http://concourse.ci/single-page.html#inputs):
> If any specified inputs are not present, the task will end with an error, without running.

Therefore, introducing the new input would break existing pipelines that are using the task.  So they have to do it in a major version bump.

This slows the development process, because the upstream team is reluctant to make too many breaking changes.

## A Modest Proposal
An input to a task definition may include boolean flag indicating that the input is `optional`:

```yaml
inputs:
- name: required-thing
- name: other-required-thing
- name: optional-thing-to-support-new-feature
  optional: true
```

If a job runs a task and omits an optional input, the task sees:

- option 1: an empty directory with that name
- option 2: no directory with that name

I don't have a strong opinion between options 1 and 2.

**Comment by rosenhouse** [comment]
I'd be mildly interested in contributing this feature if it isn't on the short-term roadmap for the Concourse team.  Any pointers on where I might start working on this?

**Comment by vito** [comment]
I like it. It's been a TODO in my phone for a long time. :P

I would prefer option 2; seems like it'd be a more obvious way to determine whether the input was provided at all vs. provided but empty.

If this can be PRed that'd definitely be the fastest route to victory - we tend to keep our roadmap filled with larger things like the upcoming "spaces" feature, and general resiliency/bug fixing. This seems like it should be easy enough to contribute, so we prefer to foster those relationships when possible.

I think you could just start in the `exec` package, chasing the types from there. [Here's the line](https://github.com/concourse/atc/blob/master/exec/task_action.go#L366-L368) that throws the "missing inputs" error. This could end up being just a code change to permit optional inputs to be missing, and another change to add the `optional` field to the [`TaskInputConfig` struct](https://github.com/concourse/atc/blob/master/task.go#L345-L348). Plus tests in [`testflight`](https://github.com/concourse/testflight).

See [CONTRIBUTING.md](https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md) for a general dev/test workflow intro.

**Comment by rosenhouse** [comment]
Alright, here we go
- https://github.com/concourse/atc/pull/242
- https://github.com/concourse/fly/pull/202
- https://github.com/concourse/testflight/pull/4
- https://github.com/concourse/docs/pull/20

The `fly` and `testflight` changes depend on the `atc` changes.

Cheers!

**Comment by vito** [comment]
All merged, thanks a bunch for PRing all this!

**Comment by rosenhouse** [comment]
@dsabeti now that this has shipped, I'd love to start seeing this used in `cf-deployment-concourse-tasks`!

**Comment by dsabeti** [comment]
Yeah, we'll definitely use this. We'll probably need to drag behind a _little_ bit while we wait for people to upgrade to 3.9.0, but this definitely makes it way easier to maintain a stable interface to Concourse tasks.
