### ISSUE TITLE
How to build the `concourse` binary?

### ISSUE THREAD

**Issue by concatime** [concourse/concourse#1926]
Hi everyone!

[feature request] Since I'm using Alpine Linux (based on musl), I cannot use the binaries provided (compiled against glibc). It there any resources (steps by steps) to build the `concourse` binary? It should not be that complicated for go app… I hope ;)

Thank you.

**Comment by rosenhouse** [comment]
You might want to look at https://github.com/concourse/bin

**Comment by concatime** [comment]
Thank you. I will try to take a look.
