### ISSUE TITLE
Git clone with non-default SSH port

### ISSUE THREAD

**Issue by peckeltw** [concourse/concourse#1931]
Hi there!

In our project we're using Bitbucket hosted by our client which lets you pull and push via SSH on port 7999, Atlassian's default setting. Setting up a reverse proxy might be possible, but would require a long time I here I assume ...

Is there any way to get Concourse to clone a Git resource on a different port than 22? In the documentation for resource and and the custom resource_types I could not find anything.

Thanks,
Philipp

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): Docker

**Comment by vito** [comment]
It should be specifiable as part of the URI.

```
ssh://git@mydomain.com:7999/myrepo
```
