### ISSUE TITLE
Redundant `--tsa-session-signing-key` flag should be hidden

### ISSUE THREAD

**Issue by EugenMayer** [concourse/concourse#1934]
when running `concourse web --help`

it returns 

```
          --tsa-session-signing-key=                                    Path to private key to use when signing tokens in reqests to the ATC during registration. [$CONCOURSE_TSA_SESSION_SIGNING_KEY]
```

so then session_sign_key is configured by `CONCOURSE_TSA_SESSION_SIGNING_KEY`

but actually its `CONCOURSE_SESSION_SIGNING_KEY`

I guess, naming wise `CONCOURSE_TSA_SESSION_SIGNING_KEY` should be right

**Comment by EugenMayer** [comment]
Also see https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourseci-cluster/0/docker-compose.yml.tpl#L105

**Comment by vito** [comment]
Both are correct. You should actually see two flags in `--help`; `--session-signing-key` and `--tsa-session-signing-key`. The value for this flag defaults to the value of the other var.

This is a result of the `concourse` binaries being a result of gluing the ATC and TSA together.

I agree it can be a bit confusing for both to show up under `--help` though as you'd never want them set to different values.

**Comment by EugenMayer** [comment]
`CONCOURSE_TSA_SESSION_SIGNING_KEY` is not working, hence the issue

**Comment by vito** [comment]
@EugenMayer Ah, makes sense. Do you have a need to set it differently from `CONCOURSE_SESSION_SIGNING_KEY`? Or should we just hide it?

**Comment by EugenMayer** [comment]
@vito `CONCOURSE_TSA_SESSION_SIGNING_KEY` would be the obvious to find for people `CONCOURSE_SESSION_SIGNING_KEY` is very hard to find for not people being core developers :) 

For me, as you might guess, nothing is "needed" - i found it and using the other ( i am not blocked )

But i would suppose other people will trying the same will use `CONCOURSE_TSA_SESSION_SIGNING_KEY` and it will not work and maybe think how that shows off.. and how people will understand what actually failed. So i would say, add support for CONCOURSE_TSA_SESSION_SIGNING_KEY and remove and mention of `CONCOURSE_SESSION_SIGNING_KEY` ( but do not remove support for it until whatever, 4.0? or 5.0? whatever)

**Comment by vito** [comment]
@EugenMayer I think there's some confusion here as to what the value of this field is. The value is more important for the ATC, not the TSA. The other property is more important and seems more obvious once you know what it is/how it's used.

They'll both necessarily have to be the same value. It doesn't make sense to only set the signing key for the TSA; the ATC needs it even more. The ATC needs it for signing user tokens granted by logging in, and verifying tokens. The TSA only needs it to sign its system tokens when talking to the ATC.

For this reason, the binaries automatically set the TSA session signing key to be the same key as set for the ATC, and as a result ignores any value specified for it.

**Comment by clintjedwards** [comment]
Just something additional observed, if you don't provide the `CONCOURSE_SESSION_SIGNING_KEY` at all (I provided the `CONCOURSE_TSA_SESSION_SIGNING_KEY` instead before stumbling upon this thread), upon a worker attempting to join, the concourse web service will crash loop trying to sign the request and error with a null pointer on the signing function.

Assuming on web's startup it should probably validate whether you've supplied a signing key instead, but i'm pretty new to the project.

**Comment by wagdav** [comment]
@clintjedwards I also saw the that crash and opened #2152 about the crash.  It seems like a separate issue.

**Comment by xtremerui** [comment]
now only `--session-signing-key` exists.
