### ISSUE TITLE
Javascript error: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by 21robin12** [concourse/concourse#1939]
# Bug Report

* Concourse version: 3.8.1
* Browser: Google Chrome [Version 63.0.3239.132 (Official Build) (64-bit)]. Seems fine in FF

When clicking on certain web UI elements (e.g. empty areas of the pipeline diagram) the following JS error is thrown:

```
content_script.js:419 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at domText (content_script.js:419)
    at Object.getLocator (content_script.js:429)
    at HTMLDocument.onClick (content_script.js:2040)
```

Note that this can be seen at https://ci.concourse.ci

**Comment by vito** [comment]
We don't have 'toUpperCase' anywhere in our code and it doesn't happen for me on our pipeline. Maybe a faulty Chrome extension?
