### ISSUE TITLE
audit trails and fine-grained access control

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [concourse/concourse#194]
I noticed a series of `auth` stories in your Roadmap, and I was wondering if there was any plan for these two areas.

For audit trails, it would be nice to know whenever someone views a build output, triggers or aborts a build, hijacks a container, pauses or unpauses a pipeline or job; and to know who did the action.  This is especially useful when multiple members of a team are interacting with the Concourse, and you want to know why it's in a particular state.  Is it safe to, e.g. unpause a particular build?  I wonder who paused it in the first place so I can go ask them.

For fine-grained access control, it would be nice to manage permissions on the various actions above.  Maybe only certain users should be able to trigger certain builds, for instance.  I noticed [this story](https://www.pivotaltracker.com/story/show/105045550) but the details aren't quite fleshed out there.

Do you have any plans to support these kinds of features? If so, would they be near term or long term goals?

**Comment by rbuckland** [comment]
As per question and response on Slack - https://concourseci.slack.com/archives/general/p1451495454006790 it would be also good to track changes of the pipelines loaded in.
A nice option (configureable) would be to switch off loading pipelines in via file, and rather pull then from a git hash. This way, audit and history is managed "outside" and does not need to be developed.

**Comment by mariash** [comment]
moving from https://github.com/concourse/concourse/issues/233

* If a build is manually triggered, it should say "manually triggered by "
* If a build was triggered automatically, it should say "automatically triggered by <resource 1>, <resource 2>, ..."

**Comment by cnelson** [comment]
Re: pausing / manual triggers -- I know this would be a big change in the UI as it doesn't really take user input beyond clicks right now, but it's be really useful to allow a line of text input when these actions are taken so it could show

manually triggered by :user: because :reason:

paused by :user: at :time: because :reason:

**Comment by mariash** [comment]
@cnelson there is a separate story for reasons: https://github.com/concourse/concourse/issues/273. Lets keep this issue focused only on auditability of who did what.

**Comment by Zteve** [comment]
It's nice to see this is being taken seriously; but I'm a little concerned that "audit trails" don't address the UI side of the story.  It's all very well collecting this information, but it should also be _visible_ at crucial places in the user experience.  Can you make sure that this is included as part of this issue? (That was the nub of #497.)

One reason for being explicit is the knotty problem of "who is allowed to know". My own thoughts are that if you can influence the pipeline (i.e. abort/pause/trigger builds) you should be able to see this information, but if you are an external viewer maybe you can't?

**Comment by nbrys** [comment]
Is there any update on this issue?

**Comment by 4everinbeta** [comment]
We are running into this as a serious issue when trying to comply with our internal SOX auditing. We need the ability to not only control who can make a a push of a given pipeline, in particular to production, but also the ability to provide an audit trail of who pushed what to where for a given time-period. This is possible in jenkins but I really, really don't want to have to go back to jenkins! :)

**Comment by StevenArmstrong** [comment]
Any update on this? We also require audit of who triggered jobs. Can the user who triggered a job be extracted from the logs in any way in 4.0.0? Is there a recommemdation?

**Comment by Onke** [comment]
+1, any news on this?!

**Comment by jama-pivotal** [comment]
@StevenArmstrong @Onke we've been working away at #2389 and https://github.com/concourse/rfcs/pull/6 for a few weeks now. If you'd like an at-a-glance, check out this rough permission matrix as a v1 https://docs.google.com/spreadsheets/d/1np3hyJy3mVRfB2gcgKykz3QTQg5qEj28QgK523SEmao/edit#gid=0

**Comment by cultavix** [comment]
Not being able to audit who is triggering what, is not allowing us to use Concourse in a PCI DSS compliant environment

**Comment by EduardoAC** [comment]
I consider this really valuable for our company, because this force us to create separate pipelines to warranty who deploys to production

**Comment by StevenArmstrong** [comment]
Yeah recording which user triggered a build is really a must. Not having it
causes issues with security. Can we not bubble this up into the web ui as
"triggered by" or as a start point have it logged in the logs when the +
button is pressed by a user.

**Comment by kstoner-sbux** [comment]
+1 - if not the user, then at least the IP Address of the requester. This is a security issue as well as a serious problem for keeping track of who's doing what...

**Comment by MazterBaker** [comment]
+1 to this. I'm a bit surprised this is not already in place...from a security and auditing point of view,  knowing who made modifications to a pipeline, and who triggered a build seems like a must for any company doing serious production stuff with Concourse pipelines. 

This info should be displayed by the web UI, and should also be available to the pipeline itself... (e.g to allow a slack notification : "User X started Pipeline Y, build Z").

Thanks!

**Comment by pk0024703** [comment]
+1

**Comment by cmpsoares91** [comment]
Hello,

+1 for this one. Can someone update this thread with what's currently planned for this RFF for the newcomers?

This subject is crucial for us to continue using Concourse, or we'll need to migrate soon... :-(

Best regards,
Carlos Soares.

**Comment by AkihiroKitada** [comment]
+1 to this one.

Other than security reasons, it's valuable to have Auditing feature in terms of detecting which team/user consumes worker's resources excessively and so on.

**Comment by vito** [comment]
Simple auditing via logging has been implemented via #3577 which will be in v5.2.

As we have the first pass of RBAC and now auditing I'm going to close this issue - it's a bit open-ended and, well, has to be closed some time. I think we should build on what we have so far with more concrete proposals which can be done in later issues. :slightly_smiling_face: Thanks all!

**Comment by EduardoAC** [comment]
@vito thanks you for your great effort, we are looking forward to upgrade into 5, although it will take some time for us.
