### ISSUE TITLE
After a BOSH Recreate all workers hit max containers

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse#1944]
Hi there!

# Bug Report

Whenever we run a `bosh recreate` or a `bosh deploy` that causes a recreate of of all of our workers, they all immediately jump to max containers, and our pipelines go orange.  We usually have to pause a bunch of pipelines and wait for them to calm down.  After a while (20 or so mins) things come back to normal. 

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): N/A
* Did this used to work? I *think* this started when we upgraded from 3.4.0 -> 3.6.0

**Comment by vito** [comment]
Not much to go on here. This doesn't happen to us and we recreate workers all the time, both for ci.concourse.ci and Wings.

**Comment by joshzarrabi** [comment]
@vito sorry, I should have added logs, I will be sure to do so next time it happens. Interestingly, after I wrote the issue the container count did not go down, and we were at max_containers until the next day when we deleted and workers from the console by hand and then redeployed.

**Comment by jama-pivotal** [comment]
Closing issue for now @joshzarrabi since we don't have much to go on. When it happens next feel free to open a new issue with logs!
