### ISSUE TITLE
POST method not works for creating new build from Concourse API

### ISSUE THREAD

**Issue by charytecholution** [concourse/concourse#1945]
Hi There,

We are running POST method to create new build with bearer token, But we get ```401 unauthorized``` error. 
Whereas we can successfully run the GET method to see the builds and status.

GET Method:
``` 
curl -v --cookie "ATC-Authorization=Bearer LONG_TOKEN" http://<<host>>:<<port>>/api/v1/teams/my-team/pipelines/hello-world/jobs/hello-world/builds/1 -X GET

```

POST Method:
``` 
curl -v --cookie "ATC-Authorization=Bearer LONG_TOKEN" http://<<host>>:<<port>>/api/v1/teams/my-team/pipelines/hello-world/jobs/hello-world/builds/ -X POST
```
The following can also be handy:

* Concourse version: v3.6.0
* Deployment type (BOSH/Docker/binary): BOSH Cluster
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work? yes.

thanks,

**Comment by pivotal-jwinters** [comment]
Try using `-H "Authorization: bearer LONG_TOKEN"` instead of `--cookie "ATC-Authorization=Bearer LONG_TOKEN"`. Requests using cookies required a csrf token.

Also please note that the API is not publicly documented so it may break in the future :)

**Comment by vito** [comment]
Closing per @pivotal-jwinters' comment - that should fix it. (If not, our API is not yet supported/documented, so closing either way.)

**Comment by murali4624** [comment]
@pivotal-jwinters : How are you getting the long_token for authorization? I am trying to access few get API methods and I am using 'Edit this cookie' plugin in chrome to get the Bearer Auth Key value. Is there a better way to do this. I was to store this Auth key in my app and based on the start/finish status of the jobs, I need to update few details in my app.

Got the API from here: https://github.com/concourse/atc/blob/master/routes.go
