### ISSUE TITLE
oAuth Azure

### ISSUE THREAD

**Issue by duga3** [concourse/concourse#1946]
Hi there!

# Feature Request

## What challenge are you facing?

We're using Azure AD for authentication and there's no direct and simple way to configure oAuth to Azure in Concourse.
Using Concourse generic oAuth does not work right away.

## A Modest Proposal

In the long run, it would be great to implement an Azure authentication provider, I'll do that if I find time, for now, I'd like to share how I got it working using generic oAuth.

- TENANT_ID: Can be retrieved from `az show account`
- APP_ID: Application ID of the App in Azure.
- CLIENT_SECRET: Can be created in the Azure App or via az cli, e.g
```bash
az ad app update \
	--id "$APP_ID" \
	--end-date '2099-01-01' \
	--password <very_secret_client_secret>
```

To configure a team with oAuth, use the following snipped:
```bash
fly -t <target> set-team -n <team name> \
    --generic-oauth-display-name=Azure \
    --generic-oauth-client-id="$APP_ID" \
    --generic-oauth-client-secret="$CLIENT_SECRET" \
    --generic-oauth-token-url="https://login.microsoftonline.com/$TENANT_ID/oauth2/token?resource=$APP_ID" \
    --generic-oauth-auth-url="https://login.microsoftonline.com/$TENANT_ID/oauth2/authorize" \
    --generic-oauth-auth-url-param=resource:"$APP_ID"
```
Don't forget to set the callback URL (Return URL in the portal) for the app to: `https://<concourse>/auth/oauth/callback`to get the token exchange working.

**Comment by vito** [comment]
Looks like we might get this for free once we switch to coreos/dex (#1888). Gonna close this for now. If we don't go with dex for whatever reason, auth providers are very easy to implement and PR, so we're not likely to act on this issue ourselves. Thanks for documenting the interim solution here!
