### ISSUE TITLE
The ATC holds a lock on a resource type scan

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#1954]
# Bug Report

The ATC will get into a state where it holds a lock on a resource type scan but doesn't progress.

This results in the following behaviour:

1. `fly check-resource` for a resource with a given `resource_type` doesn't return, it just hangs forever.
1. Setting a new pipeline that uses the given `resource_type` won't ever acquire any versions. 
1. Existing resources of this `resource_type` will continue to work as normal.

# Cause

No idea

# Resolution

Restart the atc

**Comment by pivotal-jwinters** [comment]
We just saw this again on wings.

**Comment by ddadlani** [comment]
We documented the steps we followed to debug this the last time it happened on Wings [here](https://github.com/pivotal-cf/concourse-support/blob/master/incidents/Wings%2010-10-2018-time-resources-stuck.md).

One thing to consider is that in the case where someone runs `fly check-resource` for a resource with a particular config, the `mustComplete` boolean in the for loop below will be true. In that case, execution may get stuck in this loop indefinitely. This *may* be the reason for pending checks on certain resource configs.

https://github.com/concourse/concourse/blob/6fe9813cef84a31c29bccd754feff095349b6fef/atc/radar/resource_scanner.go#L161-L189

**Comment by cirocosta** [comment]
Hey,

For now, we added a bit more of logging in order to facilitate debugging when it happens again.

Leaving this issue as paused for now until the next occurrence.

thx!

**Comment by pivotal-jwinters** [comment]
Saw this again on wings. 

After diving in a bit, it seems like a worker stalled mid way through a resource `check`. This resulted in a container getting created (both in the db and in garden), and then disappearing half way through the `check` flow. 

A dump of goroutines showed things were stuck in `FindOrCreateContainer`. Some were hanging on a garden client request and some were hanging on a baggageclaim client request (so it could also be that the volume disappeared similar to the container). The current assumption is that these requests were being made against the worker that stalled. The garden client should have a [5 minute timeout](https://github.com/concourse/concourse/blob/master/atc/atccmd/command.go#L498) so not sure why it was hanging. ¯\\_(ツ)_/¯

**Comment by ddadlani** [comment]
Moving this back to the backlog for now. Feel free to move back in flight if the investigation is restarted / issue occurs again.

**Comment by clarafu** [comment]
We just saw this again on wings, maybe we should prioritize this? It might be fixed with all the FindOrCreateContainer refactorings that have been happening.

**Comment by clarafu** [comment]
@topherbullock Sorry I forgot to @ mention you. :(

**Comment by clarafu** [comment]
After talking with @vito, if the problem was something in the FindOrCreateContainer hanging it seems like this might be fixed with the ephemeral check containers because with concourse no longer reusing check containers, we don't need the resource checking lock anymore. We probably need to add a checking lock around saving the versions but that would be after the FindOrCreateContainer call.  #3079

**Comment by ddadlani** [comment]
Cool :+1: we'll see if it happens again after ephemeral check containers

**Comment by ddadlani** [comment]
Moving this back to icebox, will be looked at again after #3079 is completed.

**Comment by ddadlani** [comment]
this should be fixed in #4137. closing
