### ISSUE TITLE
I should be able to open an OAuth login url with only a keyboard

### ISSUE THREAD

**Issue by ships** [concourse/concourse#1955]
Hi there!

# Feature Request

## What challenge are you facing?

as a keyboard-oriented developer, it is slow, distracting, and bad for my wrists to have to flip to using the mouse -- especially for only one or two actions before switching back.

The fly cli is easy to automate around, except in the case of `fly login`. I would like a keyboard-only interaction which permits me to perform authentication with only the keyboard.

The trick is, OAuth!

## A Modest Proposal

Though it would be difficult to make the `verification success` page automatically open the terminal window, I can always get back there with system commands.

I would like a way to open the presented GitHub auth URL automatically when I attempt a `fly login`. Maybe sending some kind of signal opens using default system URL open? Alternatively, a way to copy to default system paste buffer? Open to discussing the right interaction/design around this.

**Comment by vito** [comment]
sounds like https://github.com/concourse/fly/pull/190

**Comment by jama22** [comment]
Also realized that somewhere along the line the -b  flag was added and https://github.com/concourse/fly/pull/190 was closed.
