### ISSUE TITLE
pool-resource needs an atomic move operation

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#196]
Currently in order to move an environment between pools (to model state changes) we need to perform separate add and remove operations. This has two downfalls:

1) one operation may fail leaving us with duplicated or deleted environments
2) one operation may take a long time, leaving us temporarily in a state similar to the above

This could be resolved by implementing a move operation that performs both parts of the move in a single commit/push.

**Comment by chendrix** [comment]
Moved to concourse/pool-resource#30
