### ISSUE TITLE
Github OAuth settings for team not retained over bosh recreate.

### ISSUE THREAD

**Issue by alext** [concourse/concourse#1963]
# Bug Report

We're seeing an issue where the Github OAuth settings are not retained when bosh recreates the Concourse VM (eg for a stemcell bump). During this process, the persistent disk volume is retained (and therefore all the contents of the Postgres database including all the pipeline config etc).

We're having to re-run the `fly set-team` command after each rebuild to put this config back.

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work?: Unknown. This hasn't worked since we started using this feature with Concourse 3.4

**Comment by vito** [comment]
Is this for the `main` team? If so, the BOSH manifest is the source of truth.

**Comment by alext** [comment]
This is indeed for the `main` team. Now that I read the docs more closely, I see that this is expected. Thanks for the feedback, I'll update our deployment so that this is set via the manifest.
