### ISSUE TITLE
Job loading causes browser to hang with high CPU usage

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#1964]
Lately I've been having an issue with a job that has a decent amount of logs. Whenever I try to load the Job page it hogs all my CPU and firefox becomes unresponsive on everything being handled by the same content process (can't even change the URL or hit back, everything freezes). Tabs being handled by another content process work just fine but concourse's tab and any other tab in the same content process hangs until the build logs are loaded. Same thing happens with Chromium.

If I wait long enough (>10 min) the job will eventually load. I've ran a [performance analysis](https://drive.google.com/file/d/1F0i7AsSg9VZgmxuPLROqRpDYVKaQ3oJb/view?usp=sharing) with firefox while it was happening (not sure if it will help)

* Concourse version: v3.8.0
* Deployment type: binary
* Browser (if applicable): Firefox 57.0.4 and Chromium 63.0.3239.84
* Did this used to work? :man_shrugging: (I don't remember being this severe before)

I can reproduce it fairly easily so if you need more debug info let me know.

**Comment by timrchavez** [comment]
I haven't looked at the code but do logs always stream to the client or just for running jobs? It would  make more sense for Concourse to assemble the build log on the backend for any job that is completed (but really , it should be able to do that for any job, and then just "catch up" for running jobs and stream from there). We notice ridiculous load times on logs (though I've not heard of anyone encountered these specific issues).

**Comment by timrchavez** [comment]
Totally closed this by mistake. My bad!!

**Comment by vito** [comment]
@elasticdog agreed
