### ISSUE TITLE
Enhancement: Show currently active pipelines

### ISSUE THREAD

**Issue by r-chris** [concourse/concourse#1968]
# Feature Request

I think it would be a great addition to indicate currently active (working) pipelines in the overview menu. This would allow me to easily see which pipelines are currently running without having to click through all of them.

This request could probably be related to: #386 if you think showing progress on the sidebar is a good idea. It could also relate to: #295 if you decide to not only show progress in that sidebar, but also the currently selected pipeline.

**Comment by timrchavez** [comment]
Yeah would be cool to have this overview for all public pipelines that are currently doing something.

**Comment by r-chris** [comment]
Yes, especially the info about which recently failed / succeeded would be so valuable to have in that overview.

**Comment by jama-pivotal** [comment]
@r-chris interesting. Are you on one of the recent versions of concourse? If you access our dashboard (`/beta/dashboard`) and use the search query `status:running` you should be able to get a view of all currently running pipelines!

**Comment by r-chris** [comment]
Thanks @jama-pivotal - yes I'm on the latest release, but I was not aware of the beta page(s) - that's great to know.

**Comment by jama-pivotal** [comment]
neat, yeah its a bit of a hidden feature. Have fun poking around!

**Comment by r-chris** [comment]
If you have any more of those - feel free to share ;)
