### ISSUE TITLE
Worker container crashing all the time: baggageclaim exited with error: Exit trace for group: api exited with error: listen tcp 127.0.0.1:7788: bind: address already in use

### ISSUE THREAD

**Issue by francoisruty** [concourse/concourse#1969]
Hi there!

Concourse version: 3.7.0
Deployment method: docker-compose

Every day, all our builds are frozen, stuck in "pending" state forever, because of check-resources step.
If I try to check resources via CLI, I get an internal server error 500 message.
If I log into the worker container and do "concourse worker", I get this:

 tcp 127.0.0.1:7777: bind: address already in use"}}
Exit trace for group:
baggageclaim exited with error: Exit trace for group:
api exited with error: listen tcp 127.0.0.1:7788: bind: address already in use

Sometimes I get an additional error message that :53 is already in use too.

To work around the issue, here is my procedure:
stop the containers (docker-compose stop)
rm the containers (docker-compose rm)
rm the worker container volumes (docker volume prune)
restart the containers (docker-compose up -d)
then I do a check-resource via the CLI, which does not work because it stalls the worker
then I do a fly prune-worker
I restart the containers (docker-compose restart)
then I do again a check-resource via CLI, it works, and the builds can start

...aaaand the issue reappears a few hours later.
It has been an nightmare so far, and all our production is messed up because of this. I can't even keep debugging further as I have no clue about what the concourse binary is doing inside the containers, why it's having issues binding to ports.

Any advice is welcome

**Comment by vito** [comment]
That error means some other process is already running and listening on that address/port. I wouldn't run `concourse worker` multiple times; it makes sense for that to error since the container you're connected to is alread running the same thing.

Are there any logs from the worker container?

**Comment by francoisruty** [comment]
oh ok I understand, next time it crashes I'll perform a docker log and put the output here (I'll do it within 24 hours)

**Comment by francoisruty** [comment]
mmm I just checked, the script does a docker system prune BEFORE stopping the applications, so it cannot have deleted concourse worker volumes, so the problem comes from somewhere else

**Comment by francoisruty** [comment]
Ok so I have kept investigating, and just restarting the docker-compose app causes the "cannot find baggageclaim volume" error

**Comment by vito** [comment]
There's a lot going on here. The "failed to find created volume" error and "volume-not-found", etc. imply that a worker had its data blown away and then came back under the same name. Workers should be retired or pruned when their data is removed. This will be fixed by #1959, but it sounds like your configuration is a bit messed up if it ends up blowing away data on its own.

**Comment by xtremerui** [comment]
closing stale issue
