### ISSUE TITLE
Trigger job button outline is slightly askew

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#1970]
# Bug Report

Apologies in advance...I know this is very nitpicky.

When you hover over the trigger-job button on the build page, a dark outline appears around the button. This outline does not look to be correctly centered on the button.

![i have ocd](https://i.imgur.com/MuC78RO.png)

Please make it centered (unless I am crazy and just imagining this)

* Concourse version: 3.8.1-RCsomething.
* Deployment type (BOSH/Docker/binary): Our pipelines are on Wings 
* Browser (if applicable): Chrome
* Did this used to work? I'm not entirely sure

**Comment by mockersf** [comment]
I think this can be closed as the button changed and doesn't have this issue anymore

**Comment by vito** [comment]
lol, yep. :+1:
