### ISSUE TITLE
Hide resource metadata for exposed pipeline

### ISSUE THREAD

**Issue by tenjaa** [concourse/concourse#1971]
# Feature Request

## What challenge are you facing?

We want to setup a build monitor that shows the status of our pipelines on a big screen.
Our solution was to get Raspeberry Pi, install dashkiosk and then just iterate through the pipelines we care about.
To be able to see our pipelines, we exposed them.

The problem is that with exposing the pipeline, we also expose all metadata of our resources. So emails, names and maybe some commits we do not want to be publicly available.

## A Modest Proposal

Add the option to not show metadata of resources when exposing pipelines:

`fly -t ci expose-pipeline -p my-pipeline -v "metadata=false"`

**Comment by xtreme-conor-nosal** [comment]
There may be a use case for exposing metadata on a per-resource basis. The sample use case for `fly expose-pipeline` is for a contributor to an open source repo to be able to track their change through the project's pipeline. As an all-or-nothing flag, that visibility can't be provided without also exposing commits from other repos used by the pipeline, any buckets used to store artifacts, any servers backing a resource-pool, etc. There may be 'private infrastructure' behind the public pipeline.

**Comment by xtreme-conor-nosal** [comment]
There are also security concerns around exposed metadata:
- I can see all the s3/gcp buckets in the pipeline, so I can check if any have misconfigured permissions
- resource pool metadata can expose server urls, if there's a CVE I can try to break in
- a resource maintainer may accidentally include a secret in metadata
- etc

**Comment by vito** [comment]
I think this makes sense, at least as an option to set somehow. I think there are definitely use cases for showing it (i.e. pipelines for open-source projects) but I see why you'd want to hide it, too.

Maybe this is another property of the pipeline? Maybe you could mark resources `public: true` just like jobs, and hide metadata by default?

/cc @pivotal-jwinters - not sure if this is interesting for RBAC

**Comment by mhuangpivotal** [comment]
We are thinking of adding a `public` property for resource as mentioned above. When this property is not set or set to `false`, we can hide either the entire resource page or just the metadata (so someone could still see resource versions and builds info). Would it make sense to show the resource versions regardless?

The metadata for the build inputs will still be visible if the job is set to `public: true`. This can be mitigated by setting `public: false` for the job. Would there a valid use case where the job is desired to be public but not the input metadata?

**Comment by vito** [comment]
@Lindsayauchin We're gonna start off by just showing nothing, but maybe we want a UI to indicate that this information has been omitted because the user doesn't have access?

There are a two places we might want a design for this:

* Metadata on resource page (this issue)
* Resource check error message
