### ISSUE TITLE
Using Custom Resource - aequitas/http-api-resource causes build details (events endpoint) to not load

### ISSUE THREAD

**Issue by pranaysharmadelhi** [concourse/concourse#1977]
# Bug Report

When using custom resource aequitas/http-api-resource the build does not load the events endpoint (as per network tab) and UI stays at "loading" state forever.
<img width="626" alt="screen shot 2018-01-22 at 9 10 57 pm" src="https://user-images.githubusercontent.com/11999623/35254568-c92f7cd4-ffb8-11e7-9ec3-2691f84c332f.png">

The following can also be handy:

* Concourse version:v3.5.0
* Deployment type (BOSH):
* Infrastructure/IaaS: Azure
* Browser (if applicable): Chrome (MAC)
* Did this used to work? No

**Comment by vito** [comment]
This is likely a misbehaving custom resource type. I don't see us acting on this at the moment, but if more details can be provided (console error? network payload that caused it to choke?) maybe we can take a look. Otherwise the resource type is likely what needs fixing.

**Comment by pranaysharmadelhi** [comment]
@vito 
The issue is that custom resource is an output only resource, but is showing up as input with null version causing error. Even though it only appears in "put"
Is there a way we can specify in pipeline that the custom resource is only "output".
<img width="575" alt="concourse" src="https://user-images.githubusercontent.com/11999623/35602105-769ddb1c-0604-11e8-99fe-07aba1432213.png">
