### ISSUE TITLE
Contributor License Agreement (CLA) Redesign

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1979]
We would like to redesign the UI for the CLA (https://cla.pivotal.io/) so that its not so scary with Legalese. Our current favourite CLA is the GitHub CLA (https://cla.github.com/) which has a nice TL;DR format. 

There might be some nuances to changing the CLA, since its currently tied to the generic Pivotal CLA. Let's start with creating a new design that we like, then do a tech spike to figure out our best path to implementing the new design (fork the CLA vs tweaking it)

cc @Lindsayauchin for designs on new CLA

**Comment by Lindsayauchin** [comment]
![cla_start](https://user-images.githubusercontent.com/27746614/35293927-3b654862-0043-11e8-808e-fd29cbbe3dca.jpg)


![cla_read](https://user-images.githubusercontent.com/27746614/35294077-b0d043b8-0043-11e8-8358-5f3c1887f376.jpg)

**Comment by jama-pivotal** [comment]
Closing, because we are moving towards DCO!
