### ISSUE TITLE
Method for having a pipeline group with ALL jobs without being individually specified

### ISSUE THREAD

**Issue by drich10** [concourse/concourse#198]
It would be nice if there was a way to have a pipeline group with all the jobs/resources in the pipeline (essentially the default view without groups). This would allow users to not repeat names of jobs, especially since they would have to fly configure in order to realize their mistake, and reduce the overhead of adding new jobs to a pipeline.

**Comment by vito** [comment]
You can also shift+click groups in the UI, which is sort of a hidden feature.

**Comment by jamesmaidment** [comment]
Perhaps utilizing wildcards? eg:
`groups:
  - name: all
    jobs:
      - *
  - name: deploy
    jobs:
      - deploy-*
  - name: test
    jobs:
      - test-*`

**Comment by vito** [comment]
I think this would be more cleanly fixed by https://github.com/concourse/concourse/issues/469 - you'd just not configure a tag filter
