### ISSUE TITLE
Task picks up old resource although job noticed new one

### ISSUE THREAD

**Issue by kkallday** [concourse/concourse#1980]
# Bug Report

Hi Concourse folks,

I've noticed some weird behavior with a container picking up an old version of a resource although the job noticed a new one is available.

Here's what I did:
1. Ran a job and saw that it failed because a file in S3 has an incorrect value.
1. Updated the file in S3
1. Re-ran the job and the `get` step noticed the resource changed (notice the fact that it is highlighted)
![screen shot 2018-01-23 at 12 20 35 pm](https://user-images.githubusercontent.com/926865/35298701-da17775c-0037-11e8-9224-638368df93fc.png)
1. The `run-cats` task uses the resource that changed. It does not have the updated S3 changes and task failed.

Then did a `fly intercept` on the build and went into the step that `get`s the S3 file and saw that the file had the updated S3 file. Then I intercepted the container that uses the S3 file and saw that it had an outdated version.

This sounds like the volume being attached to the `run-cats` container is cached and did not get the new changes although the job states there is a new version of the resource.

Concourse version: v3.8.0
Deployment type: BOSH
IaaS: Google Cloud

**Comment by vito** [comment]
If the file was updated in-place in S3 and the version was not changed, that breaks the immutability contract with resources. A cache on the worker was probably used. I don't see this being fixed any time soon.
