### ISSUE TITLE
Chrome/Safari - Build page doesn't account for header height when scrolling with ctrl-f or spacebar

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#1984]
# Bug Report

When using ctrl-f or when scrolling by a single page using the spacebar the height of the header is not taken into account. Not a big deal, but it can lead to confusion when you ctrl-f for something but can't see it on the page because it's covered by the scroll bar

* Concourse version: 3.7.0
* Browser (if applicable): chrome and safari, but not firefox
* Did this used to work? not that i know of

**Comment by jama22** [comment]
Possibly fixed in 5.0.0? We don't have a screenshot for comparison, but I did a quick test on prod and the styling seems to be ok.
