### ISSUE TITLE
Use BPM for all BOSH jobs

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1986]
# Feature Request

## What challenge are you facing?

Dealing with `monit` in BOSH is super annoying, and templatizing Bash with ERB is error-prone.

## A Modest Proposal

[BPM](https://github.com/cloudfoundry-incubator/bpm-release) changes that and brings things a lot closer to how BOSH should be down the line. Let's look at [switching](https://github.com/cloudfoundry-incubator/bpm-release/blob/master/docs/transitioning.md).

**Comment by xoebus** [comment]
We're hanging around in the `#bpm` channel in the Cloud Foundry Slack if you have any questions or feature requests. The [documentation](https://github.com/cloudfoundry-incubator/bpm-release/tree/master/docs) is in the BPM release repository.

**Comment by jama-pivotal** [comment]
@vito pls, and @vito delivers

**Comment by vito** [comment]
note: used it for `web` but not `worker`; running the worker in a container is somewhat counter-productive since we don't want all of its processes to die on exit
