### ISSUE TITLE
Concourse worker paralyzes whole server

### ISSUE THREAD

**Issue by francoisruty** [concourse/concourse#1989]
Hello, I have issues with concourse worker.

Sometimes, the worker container stalls (builds are frozen, check-resources hang indefinitely), even though still appearing as "running " when using the fly CLI worker command.

Problem is, this container cannot be stopped.
docker-compose stop, docker-compose kill, docker stop, docker kill, all fail with
either "ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information." or no error msg at all.

Stopping/restarting the docker service does not work, rebooting the OS does not work.

Only hard-rebooting the server makes the problem goes away. This is a huge problem imo, since this means I can't run concourse on any important server (I can't reboot production servers just like that).
Problem is, I have no idea what makes the worker crash in a so nasty way

# Bug Report

Bug reports are pretty free-form; just replace this with whatever. You can also help us triage the issue by including steps to reproduce, expected results, and the actual result. Help us help you!

The following can also be handy:

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: bare-metal server
* OS: ubuntu 16.04

**Comment by shashwathi** [comment]
> Sometimes, the worker container stalls (builds are frozen, check-resources hang indefinitely), even though still appearing as "running " when using the fly CLI worker command.

If worker is listed as `running` but not taking on any work it could mean worker is not able to connect/create to garden server which manages container lifecycle. Worker could also have problem connecting to `baggageclaim` server which is responsible for managing volumes for builds.

Is there any logs from worker when it gets into this stage?

**Comment by francoisruty** [comment]
hello, sorry, I don't have particular logs, but I had googled them at the time and there wasn't any particular clue
I ended up running Concourse inside a VM to separate it from my production docker daemon, and all is fine now, and I have a script that shuts down and restart the VM + Concourse inside it in case of

**Comment by marco-m** [comment]
@shashwathi @vito 

> If worker is listed as `running` but not taking on any work it could mean worker is not able to connect/create to `garden` server which manages container lifecycle. Worker could also have problem connecting to `baggageclaim` server which is responsible for managing volumes for builds.

I agree that often we do `fly workers`, see `running` and have no clue wether the worker is "running normally" or "not really ready to do anything".

What about augmenting the worker state reported by `fly workers`, with something like (wild examples here):

* `up`: worker is known to ATC but for some reasons not ready to take any work (this would be the case described in this ticket)
* `running`: worker is really up and running! Known to ATC and connected to all the subsystems it needs (garden, baggageclaim, ...)

Or even better: assume the subsystems are garden, baggageclaim, foo. We represent each of these as one letter: `g`, `b`, `f`:

* `running (gbf)`: the worker is known to the ATC but reported that it didn't connect yet to the 3 sybsystems
* `running (gBF)`: the worker is known to the ATC and reported that it connected successfully to baggageclaim and foo (the letters are now uppercase)

The day Concourse worker has a a new subsystem, say `x`, we just add `x` to the list. Same thing if a subsystem is renamed or removed from Concourse.

This would GREATLY make the life of operators better :-)

**Comment by xtremerui** [comment]
closing stale issue.
