### ISSUE TITLE
github-release-resource not fetching latest version

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [concourse/concourse#199]
Here is an example build:

https://mega.ci.cf-app.com/pipelines/release/jobs/announce-rc/builds/27

Notice how it is picking up v222 of `cf-github-release` even though v223 was out many days before this build run:

https://github.com/cloudfoundry/cf-release/releases/tag/v223

Here is the pipeline configuration:

https://github.com/cloudfoundry/mega-ci/blob/master/pipelines/release.yml

@vito suggested hijacking in and running some tests:

```
AKG :: ~/Documents/workspace/mega-ci/pipelines
$ fly -t mega hijack -j release/announce-rc /bin/sh
1: pipeline: release, build id: 1041, type: get, name: cf-github-release
2: pipeline: release, build id: 1041, type: task, name: announce-rc
choose a container: 1

~ # echo '{"source":{"user":"cloudfoundry","repository":"cf-release"}}' | /opt/resource/check
[]
~ # echo $?
0
~ # echo '{"source":{"user":"cloudfoundry","repository":"cf-release","access_token":"REDACTED"}}' | /opt/resource/check
[]
~ # echo $?
0
~ # echo '{"source":{"user":"cloudfoundry","repository":"cf-release","access_token":"REDACTED"},"version":{"tag":"v222"}}' | /opt/resource/check
[]
~ # echo $?
0
~ # echo '{"source":{"user":"cloudfoundry","repository":"cf-release","access_token":"REDACTED"},"version":{"tag":"v223"}}' | /opt/resource/check
[]
~ # echo $?
0
```

**Comment by evanshort73** [comment]
Currently we ignore all releases unless the tag is a valid semver version (e.g. v0.1.2). To fix this issue, we added support for semi-semantic versioning using [go-semi-semantic](https://github.com/cppforlife/go-semi-semantic). This means that we will no longer ignore version names like v223, and we will order them in an intuitive way (e.g. v222.9.1 < v223 < v223.0.1)
