### ISSUE TITLE
Docker-compose - Worker only works in privileged mode

### ISSUE THREAD

**Issue by avoidik** [concourse/concourse#1992]
## What challenge are you facing?

I have been using docker-compose configuration with the latest 3.8.0 Concourse Docker image on Windows, and found out that I'm able to use its worker only in privileged mode, for example especially adding "-privileged/-p" switch to command line or "privileged: true" in task specification, otherwise I receive following permission denied error.
```
runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:56: mounting \\\"/worker-state/3.8.0/assets/bin/init\\\" to rootfs \\\"/worker-state/volumes/live/a8d3b403-19e7-4f16-4a8a-40409a9b017f/volume/rootfs\\\" at \\\"/worker-state/volumes/live/a8d3b403-19e7-4f16-4a8a-40409a9b017f/volume/rootfs/tmp/garden-init\\\" caused \\\"open /worker-state/volumes/live/a8d3b403-19e7-4f16-4a8a-40409a9b017f/volume/rootfs/tmp/garden-init: permission denied\\\"\""
```

The task I'm trying to execute is the minimal hello-world:
```
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

run:
  path: uname
  args: [-a]
```

With the commands like so:
```
fly -t tutorial execute -c task_ubuntu_uname.yml
```

In the same time as I mentioned this works with:
```
fly -t tutorial execute -c task_ubuntu_uname.yml -p
```

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Docker-machine with the proposed [configuration](https://concourse.ci/docker-repository.html)
* Browser (if applicable):
* Did this used to work? Probably yes, I've found similar issue, but for [MacOS](https://github.com/concourse/concourse/issues/1231)

Additional question I'd like to ask is why concourse worker architecture doesn't leveraging Docker sockets? With the sockets it's possible to workaround Docker-In-Docker issues and use siblings containers. Also this will open opportunity to maintain containers with Docker command-line.

**Comment by avoidik** [comment]
Also I'd like to mention that I've tried to set SUID/SGID for /worker-state folder inside the worker container, but without any luck. Error remains the same `permission denied`.

**Comment by avoidik** [comment]
if I set CONCOURSE_WORK_DIR to something like /opt/concourse/worker, then error is
```
failed to create volume
errored
```
even if /opt/concourse/worker exist

**Comment by avoidik** [comment]
Here is the log file from worker
https://paste.ubuntu.com/26489095/

**Comment by vito** [comment]
This is expected. The worker has to be privileged as it needs to be able to run its own containers, and the example config sets `privileged: true`. Thanks for providing thorough debugging info though!

Concourse doesn't use the Docker API, it uses the higher-level Garden API (which also grants us OS X/Windows/other types of workers) so it can't just be given a socket.
