### ISSUE TITLE
TLS Security issues in ATC

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#1997]
Can settings be added to the ATC to control TLS versions, and ciphers? On v3.8.0 of concourse, it's enabling TLS 1.0, 1.1, 1.2, is susceptible to SWEET32, BEAST, and is enabling the use of 3DES/static ciphers (which our security team is blacklisting)

**Comment by marco-m** [comment]
Yes! For example, see github itself disabling TLSv1/TLSv1.1 on Feb 8 
https://github.com/blog/2498-weak-cryptographic-standards-removal-notice

**Comment by marco-m** [comment]
Thanks for fixing this!
