### ISSUE TITLE
npe when fetching from a git repo

### ISSUE THREAD

**Issue by EugenMayer** [concourse/concourse#1998]
```
01/02/2018 11:39:07goroutine 502 [running]:
01/02/2018 11:39:07github.com/concourse/atc/exec.ValidatingConfigFetcher.FetchConfig(0x0, 0x0, 0xc42428a920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/task_config_fetcher.go:200 +0x73
01/02/2018 11:39:07github.com/concourse/atc/exec.(*ValidatingConfigFetcher).FetchConfig(0xc424280950, 0xc42428a920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
01/02/2018 11:39:07	<autogenerated>:1 +0xb3
01/02/2018 11:39:07github.com/concourse/atc/exec.DeprecationConfigFetcher.FetchConfig(0x12f3d740, 0xc424280950, 0x12f29140, 0xc4241c3860, 0xc42428a920, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/task_config_fetcher.go:82 +0x92
01/02/2018 11:39:07github.com/concourse/atc/exec.(*DeprecationConfigFetcher).FetchConfig(0xc42428a8a0, 0xc42428a920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
01/02/2018 11:39:07	<autogenerated>:1 +0xc5
01/02/2018 11:39:07github.com/concourse/atc/exec.(*FetchConfigAction).Run(0xc4256768f0, 0x12f54220, 0xc4241c3800, 0xc42428a920, 0xc4240cf500, 0xc427fa3800, 0xc420c98320, 0xc420363180)
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/fetch_config_action.go:36 +0x76
01/02/2018 11:39:07github.com/concourse/atc/exec.(*ActionsStep).Run(0xc420c98320, 0xc4240cf500, 0xc427fa3800, 0x17f4da0, 0xc420c982d0)
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/actions_step.go:61 +0xd5
01/02/2018 11:39:07github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc420c982d0, 0xc4240cf500, 0xc427fa3800, 0xc420c982d0, 0x0)
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:44 +0x4c
01/02/2018 11:39:07github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc4242d8280, 0xc4240cf500, 0xc4240cf560, 0x12f4ce40, 0xc423ec5260)
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:58 +0x102
01/02/2018 11:39:07github.com/tedsuo/ifrit.(*process).run(0xc4241c6a40)
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/tedsuo/ifrit/process.go:71 +0x49
01/02/2018 11:39:07created by github.com/tedsuo/ifrit.Background
01/02/2018 11:39:07	/tmp/build/9674af12/concourse/src/github.com/tedsuo/ifrit/process.go:49 +0x117
```

cc.ci 3.8.0 

It happened out of a sudden

**Comment by tahaozket** [comment]
We had same issue on 3.6.0. We couldn't stop or pause pipeline using via web or cli. ATC was crashing. We accessed to postgres and updated job status to "cancelled".


github.com/concourse/atc/exec.ValidatingConfigFetcher.FetchConfig(0x0, 0x0, 0xc420346ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/task_config_fetcher.go:200 +0x73
github.com/concourse/atc/exec.(*ValidatingConfigFetcher).FetchConfig(0xc420f9b9c0, 0xc420346ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0xb3
github.com/concourse/atc/exec.DeprecationConfigFetcher.FetchConfig(0x11307e0, 0xc420f9b9c0, 0x11271e0, 0xc420a3bb60, 0xc420346ec0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/task_config_fetcher.go:82 +0x92
github.com/concourse/atc/exec.(*DeprecationConfigFetcher).FetchConfig(0xc420346e80, 0xc420346ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0xc5
github.com/concourse/atc/exec.(*FetchConfigAction).Run(0xc420394b60, 0x11363a0, 0xc420a3bb00, 0xc420346ec0, 0xc420592240, 0xc42231e360, 0xc421522af0, 0xc42025e000)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/fetch_config_action.go:36 +0x76
github.com/concourse/atc/exec.(*ActionsStep).Run(0xc421522af0, 0xc420592240, 0xc42231e360, 0xbdb580, 0xc421522aa0)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/actions_step.go:61 +0xd5
github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc421522aa0, 0xc420592240, 0xc42231e360, 0xc421522aa0, 0x0)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:44 +0x4c
github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc4214a3310, 0xc420592240, 0xc42126f440, 0xc4214a3310, 0x0)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:57 +0x102
github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc420e845f0, 0xc420592240, 0xc420592360, 0xc4206a7580, 0xc42058f060)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:57 +0x102
github.com/tedsuo/ifrit.(*process).run(0xc420b61f80)
        /var/vcap/packages/atc/src/github.com/tedsuo/ifrit/process.go:71 +0x49
created by github.com/tedsuo/ifrit.Background
        /var/vcap/packages/atc/src/github.com/tedsuo/ifrit/process.go:49 +0x117
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x95b9c3]

**Comment by 2color** [comment]
Same thing with `3.8.0`
```
Panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa83bb3]

goroutine 972 [running]:
github.com/concourse/atc/exec.ValidatingConfigFetcher.FetchConfig(0x0, 0x0, 0xc428e2aea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/task_config_fetcher.go:200 +0x73
github.com/concourse/atc/exec.(*ValidatingConfigFetcher).FetchConfig(0xc428bf3ad0, 0xc428e2aea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:1 +0xb3
github.com/concourse/atc/exec.DeprecationConfigFetcher.FetchConfig(0x12f3d740, 0xc428bf3ad0, 0x12f29140, 0xc4287d5200, 0xc428e2aea0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/task_config_fetcher.go:82 +0x92
github.com/concourse/atc/exec.(*DeprecationConfigFetcher).FetchConfig(0xc428e2ae60, 0xc428e2aea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:1 +0xc5
github.com/concourse/atc/exec.(*FetchConfigAction).Run(0xc420b05520, 0x12f54220, 0xc4287d51a0, 0xc428e2aea0, 0xc42091fda0, 0xc420663440, 0xc4289c4280, 0xc42020a000)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/fetch_config_action.go:36 +0x76
github.com/concourse/atc/exec.(*ActionsStep).Run(0xc4289c4280, 0xc42091fda0, 0xc420663440, 0x17f4da0, 0xc4289c4230)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/actions_step.go:61 +0xd5
github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc4289c4230, 0xc42091fda0, 0xc420663440, 0xc4289c4230, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:44 +0x4c
github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc4297f1090, 0xc42091fda0, 0xc4203de4e0, 0xc4297f1090, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:58 +0x102
github.com/concourse/atc/exec.(*OnSuccessStep).Run(0xc4288c8320, 0xc42091fda0, 0xc42091fe00, 0xc4288e1200, 0x12f4cdc0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:58 +0x102
github.com/tedsuo/ifrit.(*process).run(0xc4208c5ec0)
	/tmp/build/9674af12/concourse/src/github.com/tedsuo/ifrit/process.go:71 +0x49
created by github.com/tedsuo/ifrit.Background
	/tmp/build/9674af12/concourse/src/github.com/tedsuo/ifrit/process.go:49 +0x117
```

**Comment by 2color** [comment]
Update:

I have found the root cause of the build's wrong state. 

In my case I had a job which was:
- building a docker image
- attempting to execute a task with that docker image. 

e.g. 
```
jobs:
- name: my-git-repo-build
  plan:
  - get: my-git-repo
    trigger: true
  - put: my-git-repo-docker-image
    params:
      build: my-git-repo/
      dockerfile: my-git-repo/ci/Dockerfile
      tag: my-git-repo/.git/ref
  - task: run-docker-file
    image: my-git-repo-docker-image
```

With the `config` object missing from the task `run-docker-file` task and no `file` defined, it passed validation and caused concourse to panic with the panic from the [previous comment](https://github.com/concourse/concourse/issues/1998#issuecomment-365162486) right when reaching the task.

Defining a config object solved the problem.

**Comment by xtremerui** [comment]
closing stale issue.
