### ISSUE TITLE
Buttons don't react to interaction in Firefox

### ISSUE THREAD

**Issue by danjahner** [concourse/concourse#1999]
Hi there!

# Bug Report

Interaction with buttons in Firefox doesn't work. The hover-highlight and click reaction that you see on Chrome are absent. The lack of feedback makes me wonder if I've actually clicked it or not, leading to rage clicking and 20 pending builds. 

The following can also be handy:

* Concourse version: 3.8.1
* Browser (if applicable): Firefox 57+
* Did this used to work? Dunno

**Comment by jama-pivotal** [comment]
@danjahner could you give it another shot on Concourse v3.9.0? I just tried clicking around on Firefox 58 (quantum) on my Mac and tested it against ci.concourse.ci and wings.concourse.ci and it worked OK

**Comment by danjahner** [comment]
I'm still seeing the same issue with 3.9.0 using 58.0.2 on Mac without any add-ons enabled. To be clear, the buttons still work, it is just the hover and click effects that aren't working. Attaching a demo gif.

![button-reaction](https://user-images.githubusercontent.com/17714098/36515101-a8264956-172c-11e8-9e17-466810fe8859.gif)
