### ISSUE TITLE
No public docs for using GitHub OAuth

### ISSUE THREAD

**Issue by joshuamckenty** [concourse/concourse#200]
Features don't exist unless there's an example of how to use them, right?

**Comment by mtekel** [comment]
Hi,

there are some docs regarding auth in the [fly-cli login docs]( http://concourse.ci/fly-cli.html) and configuration hints in the [atc job spec](http://bosh.io/jobs/atc?source=github.com/concourse/concourse&version=0.69.1)

**Comment by xoebus** [comment]
boop

https://concourse.ci/authentication.html

**Comment by joshuamckenty** [comment]
Sweeeeeet!

**Comment by drnic** [comment]
This documentation has now moved to https://concourse.ci/teams.html#authentication
