### ISSUE TITLE
Bug: Build number reported in browser tab does not match actual build number

### ISSUE THREAD

**Issue by ollema** [concourse/concourse#2000]
# Bug Report

When I ran an one-off build, and viewing this build through the web UI, I noticed that the build number reported by the Chrome browser tab (in the example below, #33) did not match the actual build number (#141).

`fly -t brkt execute -c a-task.yml`
`executing build 141 at https://<concourse-url>/builds/141`
`...`

Attached is a screenshot of this behavior:
<img width="223" alt="screen shot 2018-02-01 at 14 01 11" src="https://user-images.githubusercontent.com/31876997/35706130-73b35570-0759-11e8-8729-881c0d3b2518.png">

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? Not sure

**Comment by topherbullock** [comment]
![](http://i.imgur.com/UXNTquq.gif)

**Comment by jama-pivotal** [comment]
@olle-brkt hmmm, does this happen all the time? Is it always the running build that reports the wrong number in the title? Does it revert back to reporting the right number once its done running? Is it permanently reporting the right number? 

SO MANY QUESTIONS (sorry). This might be a bit difficult for us to reproduce

**Comment by olle-brkt** [comment]
I'm a bit swamped right now, but let me see if I can find some time to reproduce this afternoon.

**Comment by jama-pivotal** [comment]
@xtremerui I see you marked it as done. What were the repro steps? So i can approve the fix...

**Comment by xtremerui** [comment]
acceptance steps:
1. fly login to concourse ci
2. fly execute a simple job like `fly -t ci execute -c ~/workspace/concourse/ci/fly-darwin.yml -i concourse=/Users/pivotal/workspace/concourse` (use the local path accordingly)
3. Go to the build url output by fly 
4. verify the num# are the same
