### ISSUE TITLE
Filter teams

### ISSUE THREAD

**Issue by dmlemos** [concourse/concourse#2002]
# Feature Request

## What challenge are you facing?

In a shared concourse environment, when many teams exist with quite a few pipelines, it is not easy to look for the team's own pipelines.

## A Modest Proposal

A filter for teams. Ex: If I am logged in in a team, filter other teams pipelines - could be the default

**Comment by jama-pivotal** [comment]
@dmlemos what version of Concourse are you using? If you're using 3.6.0 and above I believe you can try our new beta dashboard under `beta/dashboard` and try using the search filter `team:teamname` for a filtered view

Give it a shot!

**Comment by dmlemos** [comment]
@jama-pivotal We are on 3.8.0.

Great. It is exactly what I describe. Do you have docs for the beta, so people can try out?

**Comment by jama-pivotal** [comment]
@dmlemos neat! I'm going to go ahead and close this issue then.  Unfortunately we don't really document our beta features, as they are truly in-progress and could be pulled from the mainline. That said, when we do roll it out it will be documented
