### ISSUE TITLE
Missing documentation for Kubernetes and AWS ssm credential management

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#2003]
Hello,

documentation at https://concourse.ci/creds.html mentions only Vault and Credhub, while Concourse supports also AWS SSM (AWS Systems Manager Parameter Store) (#1676) and kubernetes.

In general, Concourse has more features than the ones documented, it is a pity because the majority of the users will never know :-)

**Comment by willejs** [comment]
I am trying to use SSM at the moment, I am presuming that setting the ```CONCOURSE_AWS_SSM_REGION``` environment variable would enable it, but it seems like it doesent?

**Comment by marco-m** [comment]
@vito ?

**Comment by willejs** [comment]
I figured out, that you have to pass the flag to atc, and the environment variables `CONCOURSE_AWS_SSM_REGION` or `AWS_REGION` do not work currently. I havnt dug into it properly yet, i was making the assumption that every flag was available as an environment var prefied with `CONCOURSE_` which is wrong!

**Comment by analytically** [comment]
I think the correct variable name is CONCOURSE_AWS_SSM_AWS_REGION

**Comment by ralekseenkov** [comment]
@vito I've started reworking the code for credential managers to support caching and ran into this as well... docs for k8s credential manager completely missing from https://concourse-ci.org/creds.html. is there a docs person on Concourse team who could possibly work on adding the section?

**Comment by eedwards-sk** [comment]
AWS SSM is documented https://concourse-ci.org/aws-ssm-credential-manager.html

However, it wasn't clear that you must provide the region to enable SSM + instance credentials:

>If no access key, secret key, or session token is provided, Concourse will attempt to use environment variables or the instance credentials assigned to the instance.

Maybe something like "to use instance credentials, provide only the `AWS_REGION`" or similar?

Does anyone know if it's actually `AWS_REGION` as per the docs, or `CONCOURSE_AWS_SSM_AWS_REGION` as per @analytically ?

**Comment by vito** [comment]
I've at least corrected the `AWS_REGION` var to `CONCOURSE_AWS_SSM_REGION` but haven't had time to update the docs properly. I'd like to give them the same amount of TLC I gave to the Vault docs recently but just haven't had time. :slightly_frowning_face:

**Comment by eedwards-sk** [comment]
bumping to keep open

**Comment by vito** [comment]
FWIW k8s has docs now thanks to @cirocosta - https://concourse-ci.org/kubernetes-credential-manager.html

The AWS docs could still use some TLC though, mainly to just make them conform to roughly the same structure/style as the others: https://concourse-ci.org/aws-ssm-credential-manager.html + https://concourse-ci.org/aws-asm-credential-manager.html
