### ISSUE TITLE
Visually indicate when latest resource version has been turned off

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#2008]
# Feature Request

## What challenge are you facing?

We like to keep up to date with all of our dependencies, for example the On Demand Service Broker SDK. However, they sometimes break our pipeline and we have to turn off the latest version until we can prioritize the work to fix our stuff. This makes me nervous, because I can't tell without clicking into every resource that we haven't accidentally left some resource version turned off.

## A Modest Proposal

The resource box on a pipeline page could have a visual indicator (grey, instead of black or blue?) that the current resource version has been turned off. We don't *really* need to know about older versions, as they aren't *technically* relevant.

**Comment by jama-pivotal** [comment]
cc @Lindsayauchin and @sampeinado to think about
