### ISSUE TITLE
Reference / best practice / example pipelines for various platforms / languages

### ISSUE THREAD

**Issue by mvdkleijn** [concourse/concourse#2009]
# Feature Request

## What challenge are you facing?

When developing pipelines for Concourse we're currently facing difficulties concerning how to solve the end-to-end pipeline question for various platforms and languages.

For example: what would be considered a best practice pipeline for a NodeJS application?

Do we cache? What do we cache? How to be best do linting, unit testing, releasing, etc...

We are implementing solutions to all of these questions, but feel that they are probably lacking. A reference / example pipeline would be nice.

## A Modest Proposal

Add some reference pipelines for various kinds of applications like:
- NodeJS app
- Java app
- PHP app
- Go app

For extra credit: add docs on these pipelines and (in short) discuss various strategies and why one might choose one over the other.

Another option might be a repository with community generated example / reference pipelines.

**Comment by jama-pivotal** [comment]
I think this is a great idea @mvdkleijn. I've put this under our Community backlog

**Comment by osis** [comment]
Will get around to this in #2898
