### ISSUE TITLE
Authentification is broken in Master-Branch

### ISSUE THREAD

**Issue by jheyl** [concourse/concourse#2011]
Hi there!

I invested several hours with authentification errors with both, github and basic-auth after checking out the master branch. I couldn't work around this problem without checking out version 3.8. After downgrading the version I could deploy the release without a single problem. So there seems to be a Problem with auth in the current Master-Branch.

**Comment by vito** [comment]
Please don't open issues against the master branch - that's where a lot of work is going on, and it's not guaranteed to work yet (or at least how users expect)! Feel free to hop in the #dev channel on Slack though (http://slack.concourse.ci) if you're trying to contribute and we can help figure things out.
