### ISSUE TITLE
Fly: get builds by team name and/or pipeline

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#2013]
# Feature Request

## What challenge are you facing?

Currently it's possible to request builds for a specific job with the `-j` flag. However, I want to be able to run `fly builds` and only get back builds of jobs that are owned by my team. Ideally I'd be able to narrow it down even more and get all builds for a specific pipeline.

## A Modest Proposal

add 2 flags to `fly builds`:
1. `fly builds -t <team-name>` - get all builds for a specific team
1. `fly builds -p <pipeline>` - get all builds for a specific pipeline

**Comment by andrewedstrom** [comment]
I'm going to take a crack at this myself https://github.com/andrewedstrom/fly/

**Comment by andrewedstrom** [comment]
Done! Please review the PRs at your earliest convenience.

concourse/atc#255
concourse/fly#212
concourse/go-concourse#9

**Comment by vito** [comment]
Thanks for doing this!
