### ISSUE TITLE
Credhub version compatibility issue with atc

### ISSUE THREAD

**Issue by rahulkj** [concourse/concourse#2014]
# Bug Report

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere and GCP
* Browser (if applicable): NA
* Did this used to work? New setup

I installed Concourse 3.8.0 with credhub 1.7.1 on vsphere.
Installation went fine, but when I setup a pipeline to test the variables resolution by running the pipeline, I kept getting the error `Malformed Version: `.

The credhub logs showed that the variable `get` request was successful, but atc had the logs like `var not found`

I then deleted the installation and reinstalled using credhub 1.6.5 but kept the concourse version at 3.8.0. The pipeline that failed earlier, now ran successfully. 

I think since the credhub version has been updated, the `atc` module needs to update their credhub-cli version too.

**Comment by jama-pivotal** [comment]
This is a known issue with Concourse 3.8.0. Due to a breaking change on CredHub 1.7.x the cli interface in Concourse 3.8.0 is incompatible with those versions. Concourse 3.9.0 should work with it though, but there are some open issues on that at the moment. Closing for now
