### ISSUE TITLE
Generic oAuth: scope requires type array

### ISSUE THREAD

**Issue by Rukenshia** [concourse/concourse#2015]
# Feature Request

## What challenge are you facing?

We are using [keycloak](https://github.com/keycloak/keycloak) as an Identity Provider. We want to log into concourse using it and were able to configure the client so far. The problem we are facing now is that we want to verify that a user is allowed to log into a team so that we can reuse the oauth client. The concourse documentation states that this is possible using `--generic-oauth-scope scopename`.

Keycloak only allows us to set claims on the access_token based on key: value with value being either a string, boolean or integer. The concourse genericouath however expects an array of strings for `scope` ([relevant code](https://github.com/concourse/skymarshal/blob/757b37d68b2b91a3550784ada60ffbe967bb22d4/genericoauth/scope_verifier.go#L29)). I was not able to find much information on the oAuth spec in regards to `scope`, only [RFC 6749](https://tools.ietf.org/html/rfc6749#section-3.3) which would specify `scope` as
>The value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings.

## A Modest Proposal

Somehow allow me to set the scope to a string and check against that. Also some documentation should be added as it was somewhat hard to figure out why the token could not be verified when `"scope": "scopename"` was set. Maybe the genericoauth could also be changed to allow setting a specific claim to a value and check against that, e.g. `--generic-oauth-claim team:myteam`.

**Comment by stefri** [comment]
+1

**Comment by jasper9** [comment]
+1

**Comment by stefri** [comment]
Can you provide some information how you configured the openid-connector?

**Comment by avanier** [comment]
Something along those lines :

```
fly -t local set-team -n oidc \
  --generic-oauth-oidc-display-name 'Keycloak' \
  --generic-oauth-oidc-client-id concourse-dev \
  --generic-oauth-oidc-client-secret secretysecretysecrety \
  --generic-oauth-oidc-groups sumgroup \
  --generic-oauth-oidc-auth-url https://somedomain.org/auth/realms/sumrealm/protocol/openid-connect/auth \
  --generic-oauth-oidc-token-url https://somedomain.org/auth/realms/sumrealm/protocol/openid-connect/token
  --generic-oauth-oidc-scope openid
```

For the Keycloak configuration we added a group mapper to our client configuration and that was pretty much it.

**Comment by Typositoire** [comment]
don't forget the last line.. It screws up everything otherwise.

**Comment by pivotal-jwinters** [comment]
Closing since its solved by https://github.com/concourse/skymarshal/pull/2
