### ISSUE TITLE
Add verbose logging output for credhub integration hooks

### ISSUE THREAD

**Issue by dr8tsh** [concourse/concourse#2018]
# Feature Request
Request verbose logging be written within the atc.stdout.log to confirm successful credhub integration (successful client auth and variable pull, for example).

## What challenge are you facing?
Currently, should there be an issue with respect to Credhub configuration, there is no log output to suggest causation. Providing some verbosity within the atc.stdout or atc.stderr around Credhub calls here would be greatly beneficial.

## A Modest Proposal
A simple log entry to confirm successful integration into Credhub, perhaps validated through successful client authentication via the credhub_cli along with a sample pull (against the /concourse relative path perhaps) to validate communication.

**Comment by jama-pivotal** [comment]
Adding in a note here that there was also feedback to be given to the CredHub team about how they handle errors as well, so even if we had verbose logging it won't be as helpful if CredHub itself is giving vague messages

**Comment by xtremerui** [comment]
closing stale issue.
