### ISSUE TITLE
[Dashboard: Beta] title of a pipeline (that has an ellipsis) could show it's full name on mouse over

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2026]
Mousing over the title of a pipeline that is too long to display and is truncated with an ellipsis. We could show it's full name with the mouse hovers over the pipeline name. 

**Current:**
<img width="1260" alt="screen shot 2018-02-12 at 2 46 46 pm" src="https://user-images.githubusercontent.com/27746614/36119965-a2ca8e5a-100f-11e8-8330-6798dd5ae904.png">

**Proposed:**
![cursor_expand_pipeline_title](https://user-images.githubusercontent.com/27746614/36120214-71b16766-1010-11e8-8415-92e72c920527.png)

**Comment by jama-pivotal** [comment]
.....Looks a bit weird? But i'm accepting it with the intent of coming back to it in the near future. Still looks a bit jarring and needs finessing.

**Comment by Lindsayauchin** [comment]
Let's go with the simpler option of a tooltip to reveal the too long names?
