### ISSUE TITLE
Can't create containers under latest BOSH stemcell

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#2032]
Paraphrasing from slack; I'm posting here for visibility.

As of BOSH stemcell 3541.2, Concourse fails to create containers with `runc run: exit status 1: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:46: preparing rootfs caused \\\"permission denied\\\"\""`. We're guessing this is related to "further hardening" in https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/stable-3541.2, but not sure what specifically is going on.

Any tips on debugging this @cppforlife @dpb587-pivotal?

cc @sharms

**Comment by jmcarp** [comment]
Looks like the `permission denied` is getting thrown from runc at https://github.com/opencontainers/runc/blob/master/libcontainer/rootfs_linux.go?utf8=%E2%9C%93#L626:

```
return unix.Mount(config.Rootfs, config.Rootfs, "bind", unix.MS_BIND|unix.MS_REC, "")
```

Not sure why, since garden and runc both run as root.

**Comment by dpb587-pivotal** [comment]
I don't have specific insight, but perhaps garden-runc isn't able to load in some of the mounts if they're located in directory paths which are now a-rx.

Related concourse/concourse-deployment#46

**Comment by joshzarrabi** [comment]
@dpb587-pivotal I believe the issue is solved with garden-run 1.11+ which is included with concourse 3.9.0

**Comment by jmcarp** [comment]
@joshzarrabi: we ran into this issue with garden-runc 1.11 and concourse 3.9. Is that combination of releases working for you?

**Comment by vito** [comment]
Let's fold this in to https://github.com/concourse/concourse-deployment/issues/46
