### ISSUE TITLE
It takes way too long to reap failed containers

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2036]
Garbage collection on our large-scale Wings instance basically ground to a halt while reaping failed containers. It looks like we reap each of them individually. Can this be a batch operation instead?

/cc @topherbullock

**Comment by vito** [comment]
Looks like this is the reason for individual deletion: https://github.com/concourse/concourse/issues/2031

kill dat constraint

**Comment by vito** [comment]
Also, adding an index on `containers (state)` would probably help.

**Comment by vito** [comment]
This was done by https://github.com/concourse/atc/commit/27c1f7ee20e1c72d319e7cc80ce79f0518d83f82. Yay!

Though, it looks like it could be simplified further to just `delete from containers where state = 'failed'`, but eh, I'll take it.

**Comment by topherbullock** [comment]
Submitted a PR to simplify per @vito 's suggestions above 😺 

concourse/atc#293
