### ISSUE TITLE
Session in browser or fly client expires after 24h (GitHub OAuth)

### ISSUE THREAD

**Issue by leshik** [concourse/concourse#2038]
# Bug Report

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Ubuntu 16.04
* Browser (if applicable): Google Chrome, fly client

I'm not sure if this is a bug, or I'm doing something wrong, but my session to Concourse in the browser or the fly client lasts for no more than 24h, then I need to reauthenticate again. I'm using GitHub OAuth.

**Comment by avanier** [comment]
I believe this is controlled by this option in `web` :

```plaintext
--auth-duration=
Length of time for which tokens
are valid. Afterwards, users
will have to log back in.
(default: 24h)
[$CONCOURSE_AUTH_DURATION]
```

Have you tried changing that setting and seeing if that affects tokens created through Github?

**Comment by leshik** [comment]
@avanier Oh, I'm sorry – I missed this option somehow. Maybe it's worth adding it to the documentation.
