### ISSUE TITLE
Wonky home-page animation on concourse.ci

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#2039]
# Bug Report

No biggie, just looks pretty funny
https://imgur.com/a/KcWCH

* Browser (if applicable): Chrome
* Did this used to work? Never noticed it before today?

**Comment by vito** [comment]
yeah

we're working on a new site

that image has literally ungracefully degraded ever since we shipped the site

chrome's svg handling seems to be getting worse and worse
