### ISSUE TITLE
option to not auto-hide legend on beta dashboard.

### ISSUE THREAD

**Issue by phynias** [concourse/concourse#2041]
# Feature Request

## What challenge are you facing?

Would like to have a way to keep the legend from hiding at the bottom of the dashboard page.

## A Modest Proposal

I have this up on a big screen and having it hide isn't very helpful. Most people don't know what the colors mean so keeping the legend up would be so helpful.

**Comment by jama-pivotal** [comment]
Hm, interesting! Follow up question: the legend auto-hides in the pipeline view as well. Would you also like to keep that up permanently as well?

**Comment by marco-m** [comment]
For the same use-case (display on big monitor) yes, I would like an option to show the legend also in the pipeline view.

**Comment by dumbbell** [comment]
I would love to have this feature as well (a setting to always show it, or to always hide it), for a different reason: I spend quite some time on the pipeline view and it's disturbing to have the legend come and go frequently. Having this "blinking" corner attracts attention.

**Comment by astrieanna** [comment]
Relatedly, I can't see the bottom of my pipeline when the legend is there.

![screen shot 2018-07-03 at 12 01 48 pm](https://user-images.githubusercontent.com/1205394/42231263-17dacbe8-7eb9-11e8-98e2-9987ea45d157.png)

I can't read the last label and several more jobs are hidden by the non-hidden legend. They appear when it hides.

**Comment by jama-pivotal** [comment]
@astrieanna since the dashboard is in regular old html/css, you could  also use the browser zoom -/+ to make things smaller!
