### ISSUE TITLE
ATC spamming "atc.skymarshal.user.not-authorized" messages at error log level

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#2044]
Not really sure if this a problem on my end but after upgrading to 3.9.0 (from 3.8.0) our ATC has been spamming (3 or 4 per second) the logs with
```
{"timestamp":"1518777935.108379841","source":"atc","message":"atc.skymarshal.user.not-authorized","log_level":2,"data":{"error":"not-authorized","session":"10.58127"}}
```
Is this an indication that something is wrong? (it's the first time I've seen this message) or is this a case where the log level of the message should not be "error" ?

* Concourse version: **3.9.0**
* Deployment type: **binary**
* Did this used to work? Using the exact same auth setup (github auth) we never had this log message before

**Comment by vito** [comment]
This was probably introduced as part of our ongoing work for #1888.

@pivotal-jwinters Is this just a noisy log that we should remove?

**Comment by pivotal-jwinters** [comment]
After chatting with @vito we're going to keep the log, but crank the level all the way down to debug.
