### ISSUE TITLE
Time stats on build step header please

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#2045]
Hi there!

# Feature Request

## What challenge are you facing?

I'm trying to figure out why my tile upgrade tests have jumped from 2 1/2 hrs to over 5 hrs in length. I can get an idea of which steps are taking the longest by comparing the first and last timestamps in their log outputs.  

## A Modest Proposal

But what if the length of a task and maybe even the start and/or end time were in the header bar? That would be super sweet.

**Comment by vito** [comment]
Let's fold this in to https://github.com/concourse/concourse/issues/1788. Thanks!
