### ISSUE TITLE
Is OldResourceGracePeriod actually used?

### ISSUE THREAD

**Issue by codesuki** [concourse/concourse#2049]
I was checking the code for it and cannot find any reference to it.
https://github.com/concourse/atc/commit/043a720c0db47887331569173f1a6928684c8510

This is the commit introducing it.

**Comment by shashwathi** [comment]
@codesuki : Thank you for pointing it out. Cleaned up all references.

Regards

**Comment by codesuki** [comment]
What is the proper way to achieve the effect of that feature? 
I have a job that seems to be caching it's input (GitHub release) I would like to force it to re-download it. Thought about setting this flag to 0.

**Comment by codesuki** [comment]
@shashwathi I didn't mention it in my first comment, because I wanted to know about `OldResourceGracePeriod`, but `ResourceCacheCleanupInterval` doesn't seem to be used either.
https://github.com/concourse/atc/search?utf8=%E2%9C%93&q=ResourceCacheCleanupInterval&type=

**Comment by shashwathi** [comment]
> What is the proper way to achieve the effect of that flag?

There was a refactor done to handle lifecycle of caches by Garbage collector. As a result of this, cache lifecycle flags were removed from atc binaries( but not cleaned up). You seem to be having some other issue and using this flag as a workaround. I would try to debug why new version of resource is not being fetched.

[`check-resource`](https://concourse-ci.org/single-page.html#fly-check-resource) command should be a good starting point to debug.

**Comment by codesuki** [comment]
I have two jobs that were one before. Decoupled them for faster updates. 
They both upload files to the same GitHub release (same version).
So I probably have to restructure the pipeline. Would have been easier with a force download flag :)
