### ISSUE TITLE
Slack channel seems to be in the wrong org

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#205]
Having to join a third Slack org to get my work done is frustrating.

If Concourse is a purely Pivotal-supported product, then it should be in the pivotal slack org.

If it's a CF Foundation effort, it should be in the cloudfoundry slack org.

**Comment by vito** [comment]
It's in the correct organization. The Pivotal slack organization is private, and there are more Concourse users than just people who work a Pivotal. It's also not a CF foundation effort.

**Comment by jchesterpivotal** [comment]
Gotcha. I'll go for the hat-trick.
