### ISSUE TITLE
Allow configuring the default resource check time globally

### ISSUE THREAD

**Issue by thardeck** [concourse/concourse#2050]
# Feature Request

## What challenge are you facing?

At the moment we use three xlarge workers for our Concourse instance. All three workers have all the time at least around 140-170 containers running according to `fly` without nearly any jobs actively running.

If I update Concourse or recreate the workers we often run into the issue that job and resource checks fail because of the error `max containers reached` for some time.

According to the containers list of `fly` nearly all of them are check containers which does make sense because Concourse checks by default each resource every minute.

For each resource each minute a new container is spawned and closed. This accumulates quite quickly if more than a few pipelines are used.

There is a resource option which can be configured for each resource in a pipeline to increase the time but this is quite disruptive especially if upstream pipelines are used.

## A Modest Proposal

It would be great to be able to change the default resource check time in concourse.yml so it does not have to be adapted in each pipeline and resource.

This should allow Concourse to scale much better even when more pipelines are used.

Maybe even changing the default in Concourse would make sense imho. One minute seems very low and should be not needed for most use cases.

* Concourse version: 3.9.0
* Deployment type BOSH
* Infrastructure/IaaS: openStack

**Comment by jtarchie** [comment]
I believe this is what you are looking for. This was taken from the bosh spec file on `atc`.

```
default_check_interval:
    description: |
      The interval, in Go duration format (1m = 1 minute), on which to check
      for new versions of resources.

      This can also be specified on a per-resource basis by specifying
      `check_every` on the resource config.
    default: 1m
```

**Comment by jama-pivotal** [comment]
The parameter @jtarchie should get you sorted @thardeck . Closing issue for now, feel free to reopen if you feel like it doesnt fully capture your use case

**Comment by thardeck** [comment]
Yes, thx, that is exactly what I was looking for. I have checked the concourse documentation for a setting like this but did not stumble about the page https://bosh.io/jobs/atc?source=github.com/concourse/concourse .
