### ISSUE TITLE
Missing support for stemcell version >=3541.5

### ISSUE THREAD

**Issue by amuessig** [concourse/concourse#2055]
Hi there!

# Feature Request

I have concourse pipelines running and updated the stemcell to version `3541.5`. Afterwards, I received the following error:

    runc create: exit status 1: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:46: preparing rootfs caused \\\"permission denied\\\"\""

Downgrading to `3468.*` solved the issue.

The following can also be handy:

* Concourse version: 3.9.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vsphere ESXI
* Browser (if applicable): - 
* Did this used to work?

**Comment by vito** [comment]
Already fixed, not shipped yet; see https://github.com/concourse/concourse-deployment/issues/46
