### ISSUE TITLE
concourse can't integrate with credhub if credhub is running behind a GCP https LB

### ISSUE THREAD

**Issue by RomRider** [concourse/concourse#2056]
# Bug Report
There is an issue when using credhub integration. If credhub sits behind a GCP https load balancer it fails. This issue is referenced in a PR on the credhub-cli repo : cloudfoundry-incubator/credhub-cli/pull/36

Once it's corrected on their side, atc should be compiled against this new version, else atc fails with the same error and we see this error in the logs:
```
invalid character '<' looking for beginning of value
```

The problem is that the credhub cli sends a content-length header for a GET request and GCP https LB filters it and replies with a HTTP 400 Bad Request

* Concourse version: 3.8.0 and 3.9.0
* Deployment: any
* Infrastructure GCP

**Comment by RomRider** [comment]
Hi team, is this something you could integrate in your next concourse release? The credhub-cli team cut a new release (1.7.0) which integrates the PR. It's currently a blocker to deploy credhub behind a GCP L7 Load Balancer if you want to integrate it with concourse.

**Comment by xtremerui** [comment]
closing stale issue.
