### ISSUE TITLE
Beacon job fails silently on 3.9.1

### ISSUE THREAD

**Issue by DRuggeri** [concourse/concourse#2058]
# Bug Report

When using the BOSH release of concourse v 3.9.1 (previous version 3.8.0), monit states that the beacon job couldn't start. No logs are produced. In an attempt to troubleshoot, I executed the following from the beacon_ctl script after setting up the ENV variables expected by this command:

```
/d418b255-98b0-4b46-a195-1fd84a44fb5d:/var/vcap/sys/log#       chpst -u vcap:vcap /var/vcap/packages/worker/bin/worker \
>              --json=$RUN_DIR/worker.json \
>              --beacon-host=$tsa_addr\
>              --beacon-port=1269\
>              --beacon-public-key=${TSA_HOST_KEY}\
>              --beacon-worker-private-key=${WORKER_KEY}\
>              --beacon-registration-mode=direct
/d418b255-98b0-4b46-a195-1fd84a44fb5d:/var/vcap/sys/log# echo $?
0
```

I enabled `set -x` in the beacon_ctl file to get more information from monit:

```
+ mkdir -p /var/vcap/sys/run/groundcrew
+ chown -R vcap:vcap /var/vcap/sys/run/groundcrew
+ mkdir -p /var/vcap/sys/log/groundcrew
+ chown -R vcap:vcap /var/vcap/sys/log/groundcrew
+ WORKER_KEY=/var/vcap/jobs/groundcrew/config/worker_key
+ chown vcap:vcap /var/vcap/jobs/groundcrew/config/worker_key
+ chmod 0400 /var/vcap/jobs/groundcrew/config/worker_key
+ TSA_HOST_KEY=/var/vcap/jobs/groundcrew/config/tsa_host_key.pub
+ chown vcap:vcap /var/vcap/jobs/groundcrew/config/tsa_host_key.pub
+ chmod 0400 /var/vcap/jobs/groundcrew/config/tsa_host_key.pub
+ case $1 in
+ pid_guard /var/vcap/sys/run/groundcrew/beacon.pid beacon
+ pidfile=/var/vcap/sys/run/groundcrew/beacon.pid
+ name=beacon
+ '[' -f /var/vcap/sys/run/groundcrew/beacon.pid ']'
++ head -1 /var/vcap/sys/run/groundcrew/beacon.pid
+ pid=10406
+ '[' -n 10406 ']'
+ '[' -e /proc/10406 ']'
+ echo 'Removing stale pidfile...'
Removing stale pidfile...
+ rm /var/vcap/sys/run/groundcrew/beacon.pid
+ echo 10446
++ cat /var/vcap/packages/worker_version/version
+ WORKER_VERSION=1.3
+ cat /var/vcap/jobs/groundcrew/config/worker.json
+ sed -e s/WORKER_VERSION_REPLACE_ME/1.3/g
++ date +%s
++ hostname
++ cut -d - -f 2-
+ /var/vcap/packages/resource_discovery/bin/resource_discovery /var/vcap/packages/archive_resource/resource_metadata.json /var/vcap/packages/bosh_deployment_resource/resource_metadata.json /var/vcap/packages/bosh_io_release_resource/resource_metadata.json /var/vcap/packages/bosh_io_stemcell_resource/resource_metadata.json /var/vcap/packages/cf_resource/resource_metadata.json /var/vcap/packages/docker_image_resource/resource_metadata.json /var/vcap/packages/git_resource/resource_metadata.json /var/vcap/packages/github_release_resource/resource_metadata.json /var/vcap/packages/hg_resource/resource_metadata.json /var/vcap/packages/pool_resource/resource_metadata.json /var/vcap/packages/s3_resource/resource_metadata.json /var/vcap/packages/semver_resource/resource_metadata.json /var/vcap/packages/time_resource/resource_metadata.json /var/vcap/packages/tracker_resource/resource_metadata.json
+ sed -e 's/"START_TIME_REPLACE_ME"/1519764547/g'
+ sed -e s/HOSTNAME_REPLACE_ME/fdf0-4f54-93fb-cdbb93f9eab7/g
+ tsa_addrs=(REDACTED)
+ true
+ rand=27157
+ tsa_addr=REDACTED
+ exitstatus=0
+ chpst -u vcap:vcap /var/vcap/packages/worker/bin/worker --json=/var/vcap/sys/run/groundcrew/worker.json --beacon-host=stage.concourse.mastercard.int --beacon-port=1269 --beacon-public-key=/var/vcap/jobs/groundcrew/config/tsa_host_key.pub --beacon-worker-private-key=/var/vcap/jobs/groundcrew/config/worker_key --beacon-registration-mode=direct
+ '[' 0 -eq 0 ']'
+ break
```

Given that no output at all is logged and the command immediately exits (which is what monit is also seeing), I am not sure what additional information could help troubleshoot.

**Comment by DRuggeri** [comment]
As a side note... attempting to revert back to 3.8.0, the ATC fails to start with the following error:
`failed to migrate database: file does not exist`

Halp!!!

**Comment by DRuggeri** [comment]
Stemcell version `bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.22`, FWIW

**Comment by scnewma** [comment]
@DRuggeri We had a similar problem.

We were specifying `tsa.host`, `tsa.port`, and `tsa.host_public_key` manually.  I was able to get our machines running again by using bosh links to consume `tsa.host`, `tsa.port`, and `tsa.host_public_key` in the `groundcrew` job (which is the default behavior if not provided) instead of specifying these properties manually.

I don't know if this will help in your situation, but it got us past the problem.

**Comment by DRuggeri** [comment]
Y'know what, @scnewma... gold star for you, mate! You are correct, setting `tsa.host_public_key` was the source of the issue. What was interesting, and why it rang a bell is because for *some* reason at the time I was upgrading from 3.5 -> 3.6 -> and from 3.6 -> 3.8, I had to specify that value from BOSH variables because it was untrusted on the worker-side. Simply removing it in 3.9.1 was enough to get things alive again.

I'll go ahead and keep this issue open for the devs to weigh in for a UX perspective. At the least, I think some sort of issue detailing the type of failure should be found in the logs. Silent failures are scary :-)

**Comment by zankich** [comment]
We've seen this same issue while setting up external workers. The problem we've experienced is that the `groundcrew.tsa.host_public_key` property is not rendered into the `tsa_host_key.pub` template.

I did some investigations using the [bosh-template](https://rubygems.org/gems/bosh-template/versions/2.0.0) gem and have been able to reproduce the issue.

If you create a template-context with the following link based information:
```json
{
  "links": {
    "tsa": {
      "instances": {},
      "properties": {
        "host_key": {
          "public_key":"tsa host public key from link"
        }
      }
    }
  },
  "properties": {}
}
```

You will see that the value is properly rendered 
```bash
→ bosh-template tsa_host_key.pub.erb --context "$(cat template-context-with-link.json)"
tsa host public key from link
```

However if you attempt to render the template with the following property based information:
```
{
  "links": {},
  "properties": {
    "tsa": {
      "host_public_key": "tsa host public key from property"
    }
  }
}
```
You can see that no output is produced
```
→ bosh-template tsa_host_key.pub.erb --context "$(cat template-context-with-properties.json)"

```

The fix for this should simply be the addition of a `puts` on this line https://github.com/concourse/concourse/blob/355bba4910e7edc2948ce711c1a7f6e3427c7077/jobs/groundcrew/templates/tsa_host_key.pub.erb#L3

@vito would this change be accepted as a PR?

**Comment by kmacoskey** [comment]
+1 to fixing this soon. Being able to register external workers is important. It looks as though workers in older versions, 3.8.0 register with a worker version 1.2 which seems to mean they are not compatible. So currently we have no way to get external workers registered.

**Comment by joshzarrabi** [comment]
We would really like this to get resolved as well.

**Comment by vito** [comment]
I think this is kind of in flight already as part of #2059.

@topherbullock @xtremerui Do the problems reported here look familiar? Should we mark this issue in flight too?

**Comment by andypaterson40** [comment]
Any idea of when this will be fixed/released?

**Comment by vito** [comment]
@andypaterson40 It'll be in 3.9.2, which will be out as soon as #2059 is done.
