### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by macropin** [concourse/concourse#206]
Who is the legal entity that is claiming copyright?

https://github.com/concourse/concourse/blame/master/LICENSE.md#L189

**Comment by vito** [comment]
The license file is valid. Those aren't meant to be filled in within the license itself; the text suggests that you may use that as a template for prepending a notice to every source file, which is not *required* (and is a pain in the ass to maintain every year).

**Comment by macropin** [comment]
Sorry, I'm not familiar with the Apache license. In any case a valid copyright statement seems missing. The Apache license approach is to include a `NOTICE` file with a statement in the name of the authors or legal entity claiming copyright.

http://www.apache.org/legal/src-headers.html#notice

**Comment by vito** [comment]
No worries; it's confused people before. Pardon the terseness earlier.

From everything I've heard/seen even the NOTICE file is optional, but we'll double-check. Those are the guidelines for contributing to Apache foundation projects, they don't necessary apply to everything that's using the Apache license. In any case, maintaining a single NOTICE file is a lot easier than adding headers across everything at least. (Though we'd still have to do it in every repo.)

I'll reopen so we remember to follow up on this.

**Comment by vito** [comment]
I remain of the opinion that this whole thing is a silly charade, but I've gone and added `NOTICE.md` files to all of our repos, and have made a [repository](https://github.com/vito/i-fought-the-law-and-the-law-won) to help keep my sanity on January 1st of the forthcoming years.

Thanks for bring this to our attention (and sorry for being an ass).
