### ISSUE TITLE
Build list duplicates itself while build is running

### ISSUE THREAD

**Issue by danjahner** [concourse/concourse#2061]
Hi there!

# Bug Report

When running a job in the web ui, the list of builds sometime will duplicate itself, e.g. if build 3,2,1 exist and you start a new build, it will list 4,3,2,1,4,3,2,1.

The following can also be handy:

* Concourse version: v3.9.0
* Infrastructure/IaaS: Wings
* Browser (if applicable): Chrome 64.0.3282.186 & Firefox 58.0.2

**Comment by danjahner** [comment]
Visual:

![build-dups](https://user-images.githubusercontent.com/17714098/36811706-93771934-1c83-11e8-841b-16201c4803a4.gif)

**Comment by jmelchio** [comment]
@danjahner can you tell us if the list fixes itself again after you refresh the page?

We're also interested to know if you have a slow connection to wings. We find some anomalies when we simulated a slow connection but these clear up upon refresh of the page.

Thanks.

**Comment by danjahner** [comment]
Not sure about connection speed. It does fix itself on refresh (but the bug may recur and duplicate the tabs again). 

FWIW, it is no longer happening on the same setup, so it certainly isn't consistent.
