### ISSUE TITLE
dashboard needs expose

### ISSUE THREAD

**Issue by phynias** [concourse/concourse#2063]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request

beta dashboard needs a expose like the pipeline has.

## A Modest Proposal

allow the dashboard to be exposed so you do not have to login to see it. i use the dashboard on a big screen and it constantly gets logged out.

**Comment by jama-pivotal** [comment]
Hi @phynias, are you (or can you?) using [`expose pipeline`](http://concourse.ci/single-page.html#fly-expose-pipeline) feature that will let you view pipeline state without logging in? You're getting logged out because of the login session timeout we have put in place for user security

**Comment by phynias** [comment]
I'm not view a single pipeline though. Will that work for the /beta/dashboard ?

**Comment by jama-pivotal** [comment]
yep, the dashboard should follow the same rules as the "regular" view. For example, all the pipelines you see http://ci.concourse.ci/ and https://ci.concourse.ci/beta/dashboard are exposed pipelines

**Comment by jama-pivotal** [comment]
Closing due to stale-ness. Feel free to re-open if my response didn't quite fit what you requested!
