### ISSUE TITLE
Concourse dial tcp: i/o timeout Issue

### ISSUE THREAD

**Issue by dilipmighty245** [concourse/concourse#2065]
Hi,

ISSUE:

Error performing request: Get https://mypcfapi.com/v2/jobs/somejob: dial tcp: i/o timeout

TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

error running command: exit status 1

Things we tried so far:
- Increasing CF_DIAL_TIMEOUT: 30
- Increasing App timeout to 600(max)
- Retrying several times(triggering the same pipeline again) 
- Restarting the concourse 
- Increased workers (to 2)

Its happening with all the pipelines and always,

Can anyone please help us with this issue?

* Concourse version: v3.4
* Deployment type : BOSH

**Comment by shashwathi** [comment]
@dilipmighty245 : Looks like there is no process running at that endpoint. `CF_DIAL_TIMEOUT ` is cf cli timeout and this is not related to concourse.
