### ISSUE TITLE
Turn off the timestamps

### ISSUE THREAD

**Issue by Eulerizeit** [concourse/concourse#2066]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request
Turn off the timestamps

## What challenge are you facing?

Currently the timestamps take time and resources to render, break copy and paste and are entirely uninteresting and distracting for me.  My current work around is to use adblock to block the timestamps from concourse. I'd like to be able to toggle them off either in the UI or when the system is initialized. I realize that they are important and useful to some teams but in my particular work they add a huge element of visual garbage. 

## A Modest Proposal

Allow me to turn them off

**Comment by jama-pivotal** [comment]
What version of Concourse are you using? the broken copy and paste was a known issue that was fixed in later release of Concourse, and we made some build page improvements in 3.9.1 to use less resources

**Comment by Eulerizeit** [comment]
We are using Concourse 3.8.0 my understanding is that Concourse 3.9.1 is broken and we are waiting for 3.9.2. 

None of that accounts for the fact that, for people not using them, they add a huge amount of text on the screen that distract rather than help.

**Comment by jama-pivotal** [comment]
If it comes down to aesthetics it seems unlikely that the core team will pick this issue up. We're generally not a fan of adding [knobs-and-dials](https://github.com/concourse/concourse/wiki/Anti-Patterns#knobs). 

If you have a design suggestion to help make the page more read-able for you we'd happily consider it.

**Comment by Eulerizeit** [comment]
Currently on 3.9.2 and we are still consistently unable to load jobs that have large output. 

https://gpdb.data.pivotal.ci/teams/main/pipelines/postgres_merge/jobs/icw_planner_centos6/builds/310

https://gpdb.data.pivotal.ci/teams/main/pipelines/postgres_merge/jobs/icw_planner_ubuntu16/builds/253

**Comment by jama-pivotal** [comment]
Linking to #1543

**Comment by jama-pivotal** [comment]
Update: we've picked up #1543 and if the improvements are to be believed, we might not have to pick this up 😄

**Comment by univ0298** [comment]
This seems to have regressed. For a while the timestamps were not included in any text select/copy .. but now they are again. This, at least for me, is a major usability problem

**Comment by jama22** [comment]
Interesting, looks like that behavior happens in Firefox and not Chrome

**Comment by univ0298** [comment]
I'm using Safari FWIW

**Comment by jama22** [comment]
Thanks, opened a new issue to track separate @univ0298

**Comment by univ0298** [comment]
This issue continues to exist in v5.4.1

**Comment by xtremerui** [comment]
closing stale issue. Reopen if it happens in latest Concourse.
