### ISSUE TITLE
fly login should let a user cancel the request

### ISSUE THREAD

**Issue by utako** [concourse/concourse#207]
when i `fly login` and decide not to enter my credentials for both github and basic auth, i have to `kill -9` the fly process to exit (though there are some edge cases, like entering an incorrect non-empty password).

**Comment by karafelix** [comment]
Specifically, when using github authentication, it will prompt repeatedly until the user enters a token with a space separating the name and pair, which it will save. Entering blank tokens or anything without a space will continue to prompt.
With BasicAuth, entering nothing will continue to prompt endlessly, and entering anything (incorrect) will cause it to fail.
In both cases, entering end-of-input or an interrupt does nothing, meaning that to cancel a github authentication attempt one must either send a SIGKILL or enter something incorrect, which will be saved.
BasicAuth can be cancelled by merely entering anything.
