### ISSUE TITLE
concourse.ci

### ISSUE THREAD

**Issue by Bogdanp** [concourse/concourse#2073]
I didn't know where to post this so I figured I'd just use this repo. In case you were not aware, concourse.ci has been down for the past 4-5 hours. When I visit the website now all I see is https://www.dropbox.com/s/ntxy30l6yf5s6t9/Screenshot%202018-03-07%2017.53.07.png?dl=0 .

**Comment by jama-pivotal** [comment]
Concourse team is investigating the issue, you can use http://concourse-ci.org/ in the meantime while we sort things out

**Comment by Bogdanp** [comment]
Thanks! Apologies for the noise. :-)

**Comment by jama-pivotal** [comment]
no worries!
