### ISSUE TITLE
Setting pipeline credentials via `fly`

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2075]
# Feature Request

## What challenge are you facing?

Right now I have to SSH on to my Vault VM and run `vault` commands from there. It's hokey and error-prone. Not having any simple and consistent way to do this makes credential management feel like a second-class feature, only accessible to operators.

## A Modest Proposal

Let's add some sort of `fly` command for setting credentials. And *maybe* listing and fetching them, but I'm a bit more hesitant to do that for security reasons (sending a single `write` is one thing, transmitting all the credentials out of the manager and over the network is another).

**Comment by vito** [comment]
Good point!

**Comment by baptiste-ls** [comment]
For a more user-friendly interface there's the [goldfish](https://github.com/Caiyeon/goldfish) project that supports many authentication types.

Also clients of Hashicorp have access to their Vault UI feature ($$$$).

**Comment by vito** [comment]
Seems like there's not much pressure for this so I'll just close. I do want to make sure we're making a concerted effort to encourage users to use a credential manager, but from a security standpoint this may not be the best way. Documentation is a start.
