### ISSUE TITLE
Autoscroll in build page is more annoying than helpful

### ISSUE THREAD

**Issue by dumbbell** [concourse/concourse#2077]
# Bug Report

Autoscroll often fails to keep the view at the bottom of the page. This happens when the build script outputs lines quickly or when lines are longer than the window width and they are wrapped. In both cases, it looks like the page grows too fast and autoscroll fails to do its job or determines it shouldn't scroll anymore.

On the other hand, for build scripts with few output lines or when the build is finished, I have to fight against autoscroll to scroll up, whether I'm using a keyboard or a mouse wheel. When I just want to scroll up a few lines, that battle is lost.

I don't have any solution as I have no idea how this works. I find that the same feature on Travis CI is okay. They have a button to turn on or off autoscrolling on the top right corner of the view. When it's on, I never saw it fail to follow a build script output. Of course, if it's on, it's also impossible to scroll up: I have to turn it off manually; perhaps there is a keyboard shortcut, I never tried.

* Concourse version: 3.9.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Firefox
* Did this used to work? No

**Comment by michaelklishin** [comment]
I experienced this as well on the build results page, especially when the window is narrow. Seems to happen less frequently with screen-wide windows (or I could be hallucinating).

**Comment by dolph** [comment]
Even trying to scoll up from the bottom of a job _after the job is complete_ is infuriating - it continuously tries to scroll to the bottom of the page. I've tried scrolling using the mousewheel, Page Up key, Vimium keyboard shortcuts, but it's really difficult to stop the autoscroll behavior. I've tried looking for Chrome extensions or options to block autoscrolling, but haven't really found a workaround.

I could be hallucinating, but I feel like this got worse in a recent release (I'm using 3.9.0 right now).

**Comment by dumbbell** [comment]
Yes, I see this behavior as well. Not always, but quite often.

**Comment by dolph** [comment]
@dumbbell I didn't mean to hijack this issue, BTW; I should have mentioned that I frequently experience the failure "to keep the view at the bottom of the page", along with the (perhaps separate) issue that I described. Regardless, I feel autoscroll needs a thorough overhaul to behave properly, especially with longer task logs (at least 10MB+ in my case).

**Comment by dumbbell** [comment]
No problem, you didn't hijack anything. I had this behavior with finished builds as well, but when I filed this issue and wanted to double-check that, it didn't happen, so I didn't mention it. Thanks for confirming I'm not mad ;)

**Comment by nenadstojanovikj** [comment]
Happens on big builds definitely. I have to use the scrollbar and move it to the top and hold it there for few seconds to stop the autoscrolling somehow. This also happens if the build is finished.

**Comment by Infinoid** [comment]
This is still a problem today.

**Comment by reiser** [comment]
This is still a problem today.

**Comment by reiser** [comment]
+1
