### ISSUE TITLE
Invalid domain: concourse.ci

### ISSUE THREAD

**Issue by russmack** [concourse/concourse#2078]
# Bug Report
There are references to the URL ~https:// concourse.ci~ on your github pages - no longer valid.
Should be https://concourse-ci.org.

**Comment by dbwest** [comment]
concourse-ci.org is not working for me either :(

**Comment by AaronFixer** [comment]
@dbwest Seems to be working okay now. It was definitely having issues though, but seems to be resolved as of now.

**Comment by jama-pivotal** [comment]
Please see Alex's post on the incident https://medium.com/concourse-ci/were-switchin-domains-5597dcd0b48b

**NOTE** Please do NOT visit the old `.ci` site. We have noticed that the hijacker has started uploaded old archives of the site and we are now treating this as a malicious incident

**Comment by vito** [comment]
If you find any more missing references please let us know where in this issue. I'll reopen just in case since there seem to be a few thumbs-ups.

**Comment by etaty** [comment]
All the community ressources would need to update their Readme files https://concourse-ci.org/resource-types.html#community-resources

**Comment by avanier** [comment]
I was going through the [Medium blog articles](https://medium.com/concourse-ci) and most also still `concourse.ci` .

**Comment by jama-pivotal** [comment]
@avanier good catch! I'll take on the responsibility of editing the blog articles

**Comment by Shugyousha** [comment]
Also, the CI instance for Concourse at https://ci.concourse.ci is still accessible but returns an HTTPS certificate error. The URL should probably forward to the new one at https://ci.concourse-ci.org/.
