### ISSUE TITLE
Mistake in task documentation

### ISSUE THREAD

**Issue by danielsiwiec** [concourse/concourse#208]
The task documentation says that you can execute your task.yml by simply running ```fly execute```.

This seems to be incorrect, as I get ```error: the required flag `-c, --config' was not specified```.

To make the task execute, I need to run the standard ```fly execute -c task.yml```

**Comment by danielsiwiec** [comment]
I'm happy to submit a PR for the documentation or fly, depending on the decision.

**Comment by vito** [comment]
Good catch. The docs are out-of-date; we removed the default value from the flag.
