### ISSUE TITLE
`fly execute` using localhost instead of remote server.

### ISSUE THREAD

**Issue by aloisbarreras** [concourse/concourse#2080]
# Bug Report

When running `fly execute` I get this error.

<img width="1109" alt="screen shot 2018-03-09 at 4 44 29 pm" src="https://user-images.githubusercontent.com/15008940/37231441-3d56d476-23b9-11e8-851a-e20cf25e2c1b.png">

It seems like it's trying to upload the file to localhost? The remote is setup properly because I can use set-pipeline fine and all other commands work like `workers`. Here is the output of `fly targets`:

```
name  url                                                                                  team  expiry
ci    http://adaa598e6230111e890ad12712d05218-1283277001.us-east-1.elb.amazonaws.com:8080  main  Sat, 10 Mar 2018 21:35:32 UTC
```

**Concourse version:**
3.9.1

**Deployment type (BOSH/Docker/binary):**
Kubernetes through Helm

**Did this used to work?**
No

**Comment by jtarchie** [comment]
What is the external URL of the concourse web instance set to?

**Comment by aloisbarreras** [comment]
Yep, just had to set the CONCOURSE_EXTERNAL_URL variable. Thanks
