### ISSUE TITLE
'base resource type not found' errors starting with 3.9.1+

### ISSUE THREAD

**Issue by billimek** [concourse/concourse#2081]
# Bug Report

* Concourse version: 3.9.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: VSphere-provided Ubuntu 16.04.3 kernel v4.4.0-62 running Docker v1.13.1
* Browser (if applicable): Chrome
* Did this used to work? Yes, in 3.9.0 and earlier

Starting with release 3.9.1, running concourse via http://concourse-ci.org/docker-repository.html, after loading a pipeline, we see all resources turn orange with the error **base resource type not found**.

Digging through the logs, we see:
**concourse-worker: (these are 'git' resource types)**

```
{"timestamp":"1520631653.062031031","source":"atc","message":"atc.syncer.JavaHelloWorld:radar.start","log_level":1,"data":{"session":"42.3"}}
{"timestamp":"1520631653.063035488","source":"atc","message":"atc.syncer.JavaHelloWorld:scheduler.start","log_level":1,"data":{"interval":"10s","session":"42.4"}}
{"timestamp":"1520631653.085903168","source":"atc","message":"atc.syncer.JavaHelloWorld:radar.scan-resource.interval-runner.tick.failed-to-find-or-create-resource-config-check-session","log_level":2,"data":{"error":"base resource type not found","pipeline-scoped-name":"JavaHelloWorld:resource:HelloWorld","session":"42.3.1.1.1"}}
```

**concourse-web:**

```
timestamp":"1520631240.584894657","source":"guardian","message":"guardian.start.completed","log_level":1,"data":{"session":"6"}}
{"timestamp":"1520631240.585029602","source":"guardian","message":"guardian.list-containers.starting","log_level":1,"data":{"session":"31"}}
{"timestamp":"1520631240.585165977","source":"guardian","message":"guardian.list-containers.finished","log_level":1,"data":{"session":"31"}}
{"timestamp":"1520631240.585197687","source":"guardian","message":"guardian.started","log_level":1,"data":{"addr":"127.0.0.1:7777","network":"tcp"}}
```

**concourse-db: (looks the same in 3.9.0)**

```
PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2018-03-09 21:34:06 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  relation "migration_version" does not exist at character 21
STATEMENT:  SELECT version FROM migration_version
ERROR:  relation "migration_version" does not exist at character 21
STATEMENT:  SELECT version FROM migration_version
```

If we edit the docker-compose to point to v3.9.0 (or 3.8.0), these symptoms go away.  This is confirmed on three diff deployed servers we have so far running concourse.

We have 300+ servers deployed running concourse that get rebuilt to the newest version of concourse every couple of months, so this will become a big issue for us soon and we need to know if we should update the server build template to peg to 3.9.0 to avoid widespread issues.

This is an example of how the resource definition looks for one of the git resources failing:

```yml
resources:
- name: HelloWorld
  type: git
  webhook_token: <redacted>
  source: 
    uri: git@<redacted>.git
    branch: master
    private_key: ((github-private-key-value))
  check_every: 24h
```

This is a sanitized example of the `docker-compose.yml` used for this.  We observed the same behavior with a docker-compose v2 format as well (not that we expect this to have bearing on the issue we see):

```Dockerfile
version: '3'

services:
  concourse-db:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: <redacted>
      PGDATA: /database
  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["80:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      CONCOURSE_EXTERNAL_URL: "<redacted>"
      CONCOURSE_GITHUB_AUTH_CLIENT_ID: "<redacted>"
      CONCOURSE_GITHUB_AUTH_CLIENT_SECRET: "<redacted>"
      CONCOURSE_GITHUB_AUTH_ORGANIZATION: "<redacted>"
      CONCOURSE_GITHUB_AUTH_AUTH_URL:  "https://<redacted>/login/oauth/authorize"
      CONCOURSE_GITHUB_AUTH_TOKEN_URL: "https://<redacted>/login/oauth/access_token"
      CONCOURSE_GITHUB_AUTH_API_URL:   "https://<redacted>/api/v3/"
      CONCOURSE_PUBLICLY_VIEWABLE: "true"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: <redacted>
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ENCRYPTION_KEY: "<redacted>"
      CONCOURSE_VAULT_URL: "<redacted>"
      CONCOURSE_VAULT_AUTH_BACKEND: "approle"
      CONCOURSE_VAULT_AUTH_PARAM: "<redacted>"
  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    restart: unless-stopped
    volumes: ["./keys/worker:/concourse-keys", "/opt/concourse/:/opt/concourse/"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_WORK_DIR: "/opt/concourse/"
      https_proxy: "<redacted>"
      http_proxy: "<redacted>"
      no_proxy: "<redacted>"
```

**Comment by billimek** [comment]
Still seeing this behavior in a fresh install of 3.9.2:

![sad panda](https://i.imgur.com/NwfZwrS.png)

**Comment by billimek** [comment]
After trying different things, we have observed another repeatable pattern with this issue:

* When doing a fresh `docker-compose up -d` for this deployment in 3.9.1 & 3.9.2 we can consistently repeatably reproduce this issue.
* When we stop, remove, and restart only the concourse-worker container, the issue goes away.  This suggests that there may be a timing/concurrency issue with the worker starting too soon in relation to something else (concourse-db?)

Exploring creative ways to 'delay' the concourse-worker startup in the docker-compose but no simple path forward for this so far (the `concourse/concourse` image doesn't seem to have a way to subvert startup with a sleep first or something - it expects only arguments like `land-worker`, `retire-worker`, `web` or `worker`)

**Comment by billimek** [comment]
The other thing we've observed is that when starting up a fresh concourse deployment via the `docker-compose` deployment approach, we never see the worker registered (via `fly workers`), unless we restart the concourse-worker container.  This suggests that perhaps the worker is starting-up too fast in relation to the ATC, or not handling unavailable ATC.

Indeed, if we simply `docker-compose restart concourse-worker`, it now appears in the workers list, and the pipeline doesn't throw any errors about the `base resource type not found`.

Did something change w/respect to how the worker operates since 3.9.0 that could explain this change in behavior?

**Comment by billimek** [comment]
Starting with concourse v3.10.0, this issue doesn't express itself.  Will monitor for a few days and close the issue.

**Comment by phynias** [comment]
fresh install of 3.10.0 and i still get the error.
fresh install of 3.9.0 everything works.

**Comment by billimek** [comment]
@crstamps2 does the worker show-up if you restart the worker container?

**Comment by billimek** [comment]
... by that I mean running sudo systemctl restart concourse-worker

**Comment by crstamps2** [comment]
No, I had tried that a couple of times. I also upgraded to the 3.11.0 release too.

**Comment by yawlhead91** [comment]
I'm getting the same thing, its driving me crazy

**Comment by vito** [comment]
@yawlhead91 What Concourse version are you using?

Is anyone still seeing this with v3.11.0? If so, please include as much information as possible.

@billimek How is everything looking?

**Comment by billimek** [comment]
@vito we've built ~250 new servers using the docker-compose deployment approach (pegged to `concourse/concourse:latest`) since 3.10.0 was released and have not seen this issue since then.

**Comment by crstamps2** [comment]
@billimek helped me to get mine working on DO server. 
The instructions I followed had this set `CONCOURSE_TSA_HOST=127.0.0.1`
Adding the port :2222 on the end got the worker working. I am going to notify the owner of the DO guide.

**Comment by rafikn** [comment]
I had the same issue with a fresh 3.9.1 `docker-compose` install. 
Turned out `docker` was silently stopping my `concourse-worker`.
Do a `docker ps` and make sure that the 3 containers (`web`, `worker` and `db`) are up and running.

**Comment by vito** [comment]
This should be fixed by now (according to @billimek's last comment). If it wasn't already it should almost certainly be fixed by https://github.com/concourse/concourse/commit/78ae5bb29a026afe27155c4952f361d14d34ab9b

Cheers for the debugging everyone!
