### ISSUE TITLE
Question: how to configure btrfs?

### ISSUE THREAD

**Issue by leshik** [concourse/concourse#2082]
# Feature Request

## What challenge are you facing?

What is the proper way to configure `btrfs` when running Concourse in Docker? I'm using the recommended `docker-compose.yml` from the documentation. I've already set `CONCOURSE_BAGGAGECLAIM_DRIVER: btrfs`, but what else? Do I need to set up Docker with `btrfs` volume driver? Maybe format a block storage to `btrfs` and mount it to Concourse somehow to avoid `/dev/loop0` etc.

## A Modest Proposal

Running Concourse in Docker might be documented better, including different options that can be useful in `docker-compose.yml`.

**Comment by jtarchie** [comment]
Are you experiencing an issue?

**Comment by leshik** [comment]
@jtarchie yes, I was experiencing delays. At first, I thought it was related to `docker-image-resource` (https://github.com/concourse/docker-image-resource/issues/181), then tried `btrfs` and things improved. Now I wonder if more thorough configuration needed, except `CONCOURSE_BAGGAGECLAIM_DRIVER: btrfs` (such as `btrfs` formatted external volume).

**Comment by leshik** [comment]
I figured it out – once Docker is configured with separate `/var/lib/docker` formatted in `btrfs` as per [official documentation](https://docs.docker.com/storage/storagedriver/btrfs-driver/), Concourse detects it and [starts using `btrfs` driver](https://github.com/concourse/baggageclaim/blob/master/baggageclaimcmd/driver_linux.go#L29) for baggageclaim.
