### ISSUE TITLE
Completing login flow from `dashboard/` should bring me back to the dashboard

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2084]
Completing login flow from `dashboard/` should bring me back to the dashboard.  This is related to #2051 

Now that we've rolled dashboard into the main route, we should have a somewhat seamless login flow. If you start the login process at the dashboard, the completion of a login should bring you back to the dashboard, not the homepage

As an unauthenticated concourse user looking at the dashboard page, 
I want to be returned to the dashboard page when i complete the login flow

Given that I am unauthenticated and looking at `dashboard/`
when I complete a login flow by clicking on the top right `login` button and complete the flow as a valid user for the selected team
then i should be returned to `dashboard/`

Right now it sends me back to `/`

**Comment by jama-pivotal** [comment]
Other pages that might have this problem is:
* build page?
* job page ?
* resource page ?
* From a specific pipeline? 
* From a specific pipeline + group selectors
