### ISSUE TITLE
[BUG DOC] Concourse "build badge" functionality is undocumented

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#2086]
Although Concourse has build badges (currently for jobs, with some tickets open for pipelines if I am not mistaken), this functionality is undocumented. Only "official" documentation is http://engineering.pivotal.io/post/concourse-badges/, but somebody searching the Concourse web site will not find it.

**Comment by jama-pivotal** [comment]
Opened this bug in the docs repo https://github.com/concourse/docs/issues/41 

I think it makes sense to just directly link to that guide

**Comment by marco-m** [comment]
Thanks. For me directly linking to that guide is enough.

**Comment by jama-pivotal** [comment]
Cool, closing this issue in favor of the docs issue then
