### ISSUE TITLE
Vault secrets access in Concourse pipeline.yml

### ISSUE THREAD

**Issue by soumya-github** [concourse/concourse#2087]
## What challenge are you facing?

I have a pipeline.yml file where I have a resource declared of type git. It is defined as follows:
- name: vaultResource
  type: vault
  source:
          url: http://myip:8500
          auth_method: AppRole
          role_id: 187bd6d4-4f33-ddd6-c5ad-fb702e7fdbe8
          secret_id: ed8288c3-b266-06ca-112a-47b110e3cc89

name: git-demo
  type: git
  source:
      uri: https://myclientbitbucket/scm/conint/mqtt.git
      branch: master
      username: ((gitUserName))
      password: ((gitPassWord))

I am trying to access the Vault secrets using the plan as below. It is successful as I am not getting any issue here and it was showing INFO: Reading secrets from: concourse/main/gitUserName concourse/main/gitPassWord.
      -     plan:
    - aggregate:
      - get: vaultResource
        params:
          paths:
            - concourse/main/gitUserName
            - concourse/main/gitPassWord

I am supplying a template yml file in Fly which has the below definition:
debug-mode: true
#BitBucket Config
gitUserName: (( vault "concourse/main:gitUserName" ))
gitPassWord: (( vault "concourse/main:gitPassWord" ))

I tried giving like (gitUserName)/(gitPassWord) also.

Problem:
I am not able to get the Username for my git resource type and hence it is failing to build.

## A Modest Proposal

I have gone through several sites referred in Concourse and Pivotal as below to come to that solution above.
https://github.com/cesar-rodriguez/concourse-pipelines/blob/master/pipeline-terraform-pr/pipeline.yml
https://github.com/Docurated/concourse-vault-resource
https://github.com/pivotalservices/concourse-pipeline-samples/tree/master/concourse-pipeline-patterns/vault-integration

The following can also be handy:

* Concourse version:
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Teraform/AWS
* Browser (if applicable):Chrome
* Did this used to work?No. But as per sites cited above it is a workable solution.
The entire code is given as below:
Pipeline.yml
resource_types:
  # Fetches secrets custom paths in Vault: https://github.com/therasec/concourse-vault-resource
  - name: vault
    type: docker-image
    source:
      repository: therasec/concourse-vault-resource
      tag: latest

resources:
  # Interacting with vault to get AWS credentials
- name: vaultResource
  type: vault
  source:
          url: http://myvault:8500
          auth_method: AppRole
          role_id: role id generated
          secret_id: secret id generated
- name: git-demo
  type: git
  source:
      uri: https://myclient.com/bitbucket/scm/conint/mqtt.git
      branch: master
      username: ((gitUserName))
      password: ((gitPassWord))

jobs:
  - name: "Docker-Build"
    public: true
    plan:
    - aggregate:
      - get: vaultResource
        params:
          paths:
            - concourse/main/gitUserName
            - concourse/main/gitPassWord
      - get: git-demo
# Runs terraform plan
      - task: terraform-plan
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
                repository: test/test
          inputs:
             - name: git-demo
          run:
            path: sh
            args: [./git-demo/Terraform/conCourseTest/applyCommand.sh]

setting.yml
# Debug Mode will output all info, including sensitive data, in CI scripts to Concourse UI
debug-mode: true

#BitBucket Config
gitUserName: (( vault "concourse/main:gitUserName" ))
gitPassWord: (( vault "concourse/main:gitPassWord" ))

**Comment by pontusarfwedson** [comment]
Why dont you just use `((gitUserName))` in your pipeline and ignore sending in `gitUserName: (( vault "concourse/main:gitUserName" )) ` as parameter? As long as you have the variable in your Vault in either the team path or pipeline path with the same name then Concourse should find it, so no need to care about "telling conocurse". Or am I missing something?

**Comment by soumya-github** [comment]
Hi,
We tried the ((gitUserName)) option also and without sending anything then it did not work. The error thrown was gitUsername could not be found. If we give the id/password hardcoded it worked. Just want to know do we have to do anything extra to integrate Concourse with Vault. Only using the Vault resource type wiil work ?

**Comment by pontusarfwedson** [comment]
Hi!
Not sure what default path you have for concourse but if we run a pipeline for the team "main" and have a variable in vault under "concourse/main/foo" then we can, in every pipeline in main, get the variable by simply doing ((foo)) in our pipeline yaml. Without having to pass in anything. We are running Concourse in Kubernetes using the official helm chart in which we have defined Vault as the used credential manager etc. Not sure what needs to be done when deploying with bosh or something, but you should not have to pass in any params if you have Vault usage enabled.

**Comment by dodizzle** [comment]
I also cannot get the syntax (($KEY)) to work.
I also deployed concourse to k8s using the helm chart, have vault enabled and when I attempt to get a value that I declare ((foo))
I get the following error:

Finding variable 'foo': secrets "test-vault.foo" is forbidden: User "system:serviceaccount:default:concourse-web" cannot get secrets in the namespace "concourse-infrastructure": Unknown user "system:serviceaccount:default:concourse-web"

The key exists in vault:
vault read -field=value  /concourse/infrastructure/foo
bar

From the above error it appears that it is attempting to get the key from a k8s secret not vault.

**Comment by dober** [comment]
Same issue
curl from concourse_web:
```curl -H "X-Vault-Token: token" -X LIST http://vault:8200/v1/concourse/```
```{"request_id":"21227e4b-ae0b-b598-a1d3-2312a33afada","lease_id":"","renewable":false,"lease_duration":0,"data":{"keys":["docker_registry_password","docker_registry_email","docker_registry_user"]},"wrap_info":null,"warnings":null,"auth":null}```



test pipeline:
```---
jobs:
  - name: test
    plan:
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          run:
            path: sh
            args:
              - -exc
              - |
                echo ${USERNAME}
          params:
            USERNAME: ((docker_registry_user))
```

and result is:
```Expected to find variables: docker_registry_user```

I have all env in docker-compose.yml: CONCOURSE_VAULT_URL, CONCOURSE_VAULT_PATH_PREFIX, CONCOURSE_VAULT_CLIENT_TOKEN, CONCOURSE_VAULT_INSECURE_SKIP_VERIFY

**Comment by dober** [comment]
+
This is really strange:

Finding variable 'username': Error making API request.

URL: GET http ://vault:8200/v1/concourse/**main/test_pipeline**/username

Why it uses this search path?

**Comment by dober** [comment]
Sorry, my bad:

https://concourse-ci.org/creds.html
2.4.3.2.2 Credential Lookup Rules

**Comment by trulede** [comment]
Section 2.4.3.2.2 is lacking for an example ... which would be helpful in understanding how to get this all working.

```
vault kv put concourse/main/git_user value=foo
vault kv put concourse/main/git_pass value=bar
```

After that, it works perfectly! These were the setup steps I had for the Vault (in a Docker Stack), in case it helps someone:

```
vault operator init -status
vault operator init -key-shares=1 -key-threshold=1
vault operator unseal 4aj+yc6KAwq0pmLOMPxGb2TywTiaaebAsG9zBa8+OtQ=
vault login 3dfd27d4-8622-01da-0bf7-03ebf98a2692
vault auth enable userpass
vault secrets enable -path=concourse kv
vi /vault/poli
cat poli
    path "concourse/\*" {
    capabilities = ["create", "read", "update", "delete", "list"]
    }
vault policy write conc poli
vault write auth/userpass/users/foo password="bar" policies="conc"
vault login -method=userpass username=foo
```

**Comment by marco-m** [comment]
Hello @soumya-github, for help requests such as this one, please use the forum at https://discuss.concourse-ci.org/. I am closing this issue because to my understanding it has been answered.
