### ISSUE TITLE
Webhooks stopped working in 3.9.1

### ISSUE THREAD

**Issue by cjohansen** [concourse/concourse#2089]
We've been using web hooks for a while with 3.8.0. After upgrading to 3.9.1 our webhooks are now responding with 405 Method not allowed. We installed and upgraded using concourse-up, don't know if that's a factor.

**Comment by hfinucane** [comment]
I don't get 405s, I still get 200s, but they do seem to have quit working in 3.9.1.

**Comment by timrchavez** [comment]
FWIW I setup an experiment and the webhook seems to be working fine in v3.9.2. I get a 200 response, the last checked counter resets, and the build starts. I set `check_every` to `5h` just to be sure it was the webhook firing.

**Comment by jama-pivotal** [comment]
@cjohansen and @hfinucane were you able to upgrade past 3.9.1 to a newer version of Concourse? Do webhooks work for you then? If that's the case I can update the release notes with a warning that webhooks is broken in 3.9.1

**Comment by robtec** [comment]
@hfinucane there is a metric emitted when a webhook is received, I'm using influx for our metrics.

For us on `3.9.2` webhooks are working but we often see `POST` requests taking up to 20 mins in the `http response times` metric, I'm not sure if our butbucket server is hammering concourse and it cannot process all of the hook requests (POSTs), it does process most of them.

Are you gathering metrics from your instance?

**Comment by edude03** [comment]
I'm having the same / a similar issue. I can see in the log that the webhook is being received, and new versions are discovered but new builds aren't starting. We've upgraded from 3.7 (I believe) to 4.0 so it seems like 3.9 might be the culprit.
