### ISSUE TITLE
Missing start_time on canceled job

### ISSUE THREAD

**Issue by sphawley** [concourse/concourse#2091]
# Bug Report

[This job](https://release-integration.ci.cf-app.com/teams/main/pipelines/infrastructure/jobs/remove-claimed-lock-upgrade/builds/1) is stuck displaying `loading` and if we `curl https://release-integration.ci.cf-app.com/api/v1/teams/main/pipelines/infrastructure/jobs/remove-claimed-lock-upgrade | jq .` we see that it has no `start_time` but it does have an `end_time`. Which is strange.

```
{
  "id": 435,
  "name": "remove-claimed-lock-upgrade",
  "url": "/teams/main/pipelines/infrastructure/jobs/remove-claimed-lock-upgrade",
  "next_build": null,
  "finished_build": {
    "id": 73108,
    "team_name": "main",
    "name": "1",
    "status": "aborted",
    "job_name": "remove-claimed-lock-upgrade",
    "url": "/teams/main/pipelines/infrastructure/jobs/remove-claimed-lock-upgrade/builds/1",
    "api_url": "/api/v1/builds/73108",
    "pipeline_name": "infrastructure",
    "end_time": 1513988039
  },
  "inputs": [
    {
      "name": "runtime-ci",
      "resource": "runtime-ci",
      "trigger": false
    },
    {
      "name": "upgrade-pool",
      "resource": "upgrade-pool",
      "passed": [
        "destroy-infrastructure-upgrade"
      ],
      "trigger": true
    }
  ],
  "outputs": [
    {
      "name": "transition-pool",
      "resource": "transition-pool"
    }
  ],
  "groups": [
    "upgrade"
  ]
}
```

This job was run and then cancelled while it was looking to grab an input resource.

**Comment by vito** [comment]
I'm not really sure what would be better, since technically the build never started and was aborted (ending it) while it was 'pending', i.e. before it started. That feels like interesting information to expose. How is this affecting you?
