### ISSUE TITLE
Move Wings onto a new subdomain wings.cfapps.io

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2093]
We should move Wings onto a a separate subdomain separate from the Concourse OSS identity. This will also help reduce the risk of exposing Pivotal engineering work from OSS. Previously suggested domain was *.cfapps.io, but in general we just need to put it somewhere under Pivotal's ownership

**Comment by avanier** [comment]
Just raising the flag. `.io` has a not so great reputation for reliability. You might be interested in checking out other TLDs while you're at it.

- [Article on The Register](https://www.theregister.co.uk/2017/07/10/io_hijacking_in_transition_cockup/)
- [Article about the Stream.io outage](https://hackernoon.com/stop-using-io-domain-names-for-production-traffic-b6aa17eeac20)
- [Thread on `/r/sysadmin` about `.io` TLD pratices](https://www.reddit.com/r/sysadmin/comments/6kk6th/psa_io_domains_can_be_deleted_three_days_before/)

**Comment by jama-pivotal** [comment]
Thanks for the heads up @avanier . The Wings environment ultimately moved to a domain handled by a separate Pivotal team...that's where they wanted it, and that's where it shall be!
