### ISSUE TITLE
OAuth to PCF UAA broke in 3.9.2

### ISSUE THREAD

**Issue by gaigaslab** [concourse/concourse#2097]
We just upgraded from 3.8.0 to 3.9.2 using the bosh release.

We had previously setup oauth authentication with PCF UAA, but we are now getting:
"failed to exchange token"

I don't know where to look.  I appear to be getting a token from UAA.

This is our configuration for each team:
    fly -t app-main set-team -n ${myprojectname} \
      --uaa-auth-client-id concourse-app-1 \
      --uaa-auth-client-secret <uaa client secret> \
      --uaa-auth-auth-url https://login.sys..<DNS Suffix>/oauth/authorize \
      --uaa-auth-token-url https://login.sys..<DNS Suffix>/oauth/token \
      --uaa-auth-cf-url https://api.sys.<DNS Suffix> \
      --uaa-auth-cf-ca-cert ./Hosting_Services_CA.crt \
      --uaa-auth-cf-space ${myspaceguid} \
      --basic-auth-username <basic auth user> \
      --basic-auth-password <basic auth password>

Basic Auth continues to work.

**Comment by jama-pivotal** [comment]
Doesn't look like our pipelines cover UAA. When we investigate this, we should also consider writing tests to validate UAA compatibility

**Comment by pivotal-jwinters** [comment]
@jama-pivotal We just verified that this still works for us on 3.11.0. Not sure testing this in our pipeline is all that practical since we'd need a pcf instance to test against...

@gaigaslab Can you check the logs from the atc. You should see a message like "atc.skymarshal.oauth-callback.callback.failed-to-exchange-token". Can you check the error message it prints?

**Comment by jama-pivotal** [comment]
@pivotal-jwinters thanks for checking! I think you're right, it might not actually be practical to do it. Would still like to hear back from @gaigaslab about the details on their error. If there is a problem with 3.9.2 and Pivotal's UAA

**Comment by pivotal-jwinters** [comment]
@jama-pivotal there doesn't seem to be any significant changes from 3.9.2 to 3.11.0 for what its worth. It could be a certificate issue. If the certificate validation fails it gives the "failed to exchange token" error, but will output a proper message in the atc logs, so now we wait...

**Comment by gaigaslab** [comment]
@jama-pivotal @pivotal-jwinters 
How can I view the ATC Logs directly?

**Comment by gaigaslab** [comment]
From:
/var/vcap/data/sys/log/atc/atc.stdout.log

{"timestamp":"1523996304.364424229","source":"atc","message":"atc.skymarshal.oauth-callback.callback.failed-to-exchange-token","log_level":2,"data":{"error":"oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"unauthorized\",\"error_description\":\"Bad credentials\"}","session":"10.4.44"}}

**Comment by pivotal-jwinters** [comment]
@gaigaslab can you try re-running the `fly set-team` command with your UAA credentials and see if that makes a difference?

**Comment by gaigaslab** [comment]
@pivotal-jwinters 
Yes, I have tried that many times.  I have tried recreating the team(s).

Is there anyone who can reproduce this issue in their environment?  I have reproduced it in two of my environments.

**Comment by pivotal-jwinters** [comment]
@gaigaslab are you able to get a token using `uaac token owner get`?

**Comment by gaigaslab** [comment]
Yes - i.e. for the 'opsman' Client ID (which is not valid for App Manager or CF).  I don't know how to use that command with SSO/SAML authentication, though.

**Comment by gaigaslab** [comment]
@pivotal-jwinters Accidentally hit the wrong button and closed this.  It is not closed.  It is still a bug!

**Comment by pivotal-jwinters** [comment]
@gaigaslab its no big deal, I was just trying to rule out a bad client id or client secret. Usually thats what `{"error":"unauthorized","error_description":"Bad credentials"}` means. 

Do you have access to your UAA logs?

**Comment by gaigaslab** [comment]
Yes, I can get access to them.

**Comment by pivotal-jwinters** [comment]
@gaigaslab can you try logging in with concourse and see if there's anything interesting that shows up in the UAA logs?

**Comment by gaigaslab** [comment]
@pivotal-jwinters For some reason, I didn't get notified of this.  I will try this in the next few hours.

**Comment by jhamon** [comment]
@pivotal-jwinters You should theoretically be able to test concourse against a standalone UAA bosh deployment. UAA has no dependency on the rest of PCF/CF.

**Comment by gaigaslab** [comment]
@jhamon @pivotal-jwinters 
The problem was incorrect handling of special characters in the UAA Client Secret.  We worked around it by changing the password.  Our old working password pre-3.9.2 was supplied to the concourse developers for diagnosis and root cause.

**Comment by pivotal-jwinters** [comment]
@jhamon the `uaa` provider is actually a poorly named `cf` provider since it does authz based on org/space membership. So unfortunately we need CF :(. We could probably get away with using cf dev, but its not a huge priority since we're [revamping the way auth works anyway](#1886)

**Comment by jccarte** [comment]
I ran into the same issue as @gaigaslab, removing special characters from my password is a workaround.

**Comment by akamalov** [comment]
@pivotal-jwinters, I am facing exactly the same issue, but having password without special characters is not solving the issue. I am running Concourse 3.14.0 against PCF 2.0. I get the following error:

```
"source":"atc","message":"atc.skymarshal.oauth-callback.callback.failed-to-exchange-token","log_level":2,"data":{"error":"oauth2: cannot fetch token: 401 Unauthorized\nResponse:{\"error\":\"unauthorized\",\"error_description\":\"Bad credentials\"}","session":"4.4.20"}}
```
My ```--uaa-auth-client-secret password1234``` does not contain any special characters (I just set it to this to see if it works), but nope, it does not work. This is a huge issue for us. Technically, none of teams will be able to leverage Concourse to do their releases against PCF.

**Comment by xtremerui** [comment]
closing stale issue.
