### ISSUE TITLE
Sometimes tasks are waiting to start forever

### ISSUE THREAD

**Issue by haidouks** [concourse/concourse#2098]
# Bug Report
Last week, we have updated Concourse to v3.9.1. After update, we recognized that sometimes tasks never start although the concourse workers are available. In this case, we cancel the build and restart it. 

![image](https://user-images.githubusercontent.com/23384662/37601565-613c0d86-2b9b-11e8-9c00-bc53730e6e09.png)

In our environment, we have 17 linux agents and 2 windows agents. And 220 pipelines are active on Concourse. 99% of these pipelines run on linux workers.
![image](https://user-images.githubusercontent.com/23384662/37601467-1d122a3c-2b9b-11e8-9f1a-c1ac9d1d9437.png)

Prometheus metrics for concourse
![image](https://user-images.githubusercontent.com/23384662/37600742-3d05b270-2b99-11e8-8bca-5f69637cc049.png)

* Concourse version: 3.9.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Ubuntu/VMWare

PS: All screenshots were collected in a problematic time.

**Comment by jama-pivotal** [comment]
Linking to #1298 and the first step to solving this #2290
