### ISSUE TITLE
Fly with latest golang version does not EOF (https://github.com/golang/go/issues/24164)

### ISSUE THREAD

**Issue by anoop2811** [concourse/concourse#2103]
Hi there!

# Bug Report
We seem to be hitting this issue reported in golang: https://github.com/golang/go/issues/24164

If we compile fly with the latest go version, our reconfigure-pipeline binary does not get an EOF and remains stuck. As maintainers of reconfigure-pipeline, this was reported to us by one of the users.
Tried the replication against wings and compiled fly with go version 1.10

**Comment by andrewedstrom** [comment]
Link to reconfigure-pipeline: https://github.com/pivotal-cf/reconfigure-pipeline
