### ISSUE TITLE
Feature Request: Allow for running container

### ISSUE THREAD

**Issue by dean-legalone** [concourse/concourse#2107]
## What challenge are you facing?

I'm currently using dockito to build images securely, but with concource CI i don't have a way to run a container and connect to it in the task without using something like docker-compose 

## A Modest Proposal

add a container resource that runs during a plan execution that the task will be able to use

**Comment by r-chris** [comment]
I'm not exactly sure where you are stuck, but you can currently build docker images and run tasks in any docker image you wish: https://concourse-ci.org/running-tasks.html

Maybe share some pipeline snippets to show what you had in mind?

**Comment by dean-legalone** [comment]
i was suggesting kind of a native support for docker compose, or in other words, keeping "tasks" alive even after they finished running, so that it would be possible to launch a DB container, for example, and use it in another task.

**Comment by vito** [comment]
Consolidating this in to #324 - this is something that's been on the backburner for a long time, we just haven't had time for it vs. other things.

**Comment by edevil** [comment]
@dean-legalone @vito Just to make this clear, it is not possible today to launch services (DB, redis, for example) from docker containers and use them in a later task that does integration testing?

**Comment by vito** [comment]
@edevil correct - you have to do it within one task
