### ISSUE TITLE
How can we trigger individual microservice projects inside single github repo using concourse?

### ISSUE THREAD

**Issue by charytecholution** [concourse/concourse#2110]
Hi Team!

We are using concourse for cicd in our most of the micro-services projects.The challenge we are facing is we are keeping all microservices(14 services) inside single github repo, whenever we push some changes to particular microserice the concourse build will trigger and it tries to build all the microservices and it will push all the microservices images to dockerhub but it is taking 2-3 hours time for every build.

**So we need a solution for following challenge:**
We have a large Git repository with multiple projects underneath. I would like to trigger concourse build when something changes in a specific branch in a specific directory.

Branch dev
Repo
Project 1
Project 2
Project 3
Branch staging
Repo
Project 1
Project 2
Project 3

Thanks in-advance..!

**Comment by holmboe** [comment]
@charytecholution do you keep the microservices in separate paths or separate branches? It seems that @timrchavez is assuming separate paths. I am unsure whether the proposed solution really solves the original problem though -- listing a separate path for each microservice would still trigger on a change to ANY microservice.

**Comment by charytecholution** [comment]
@holmboe i am keeping microservices in separate paths.

**Comment by troykinsella** [comment]
You can create a separate resource and build job per microservice. My org solves the repetition problem by  running the concourse yaml through a template engine.

**Comment by vito** [comment]
Sorry, I'm gonna close this since it sounds more like an open-ended discussion than a bug report/feature request - maybe try the [forums](https://discuss.concourse-ci.org) or StackOverflow instead?
