### ISSUE TITLE
Jobs serialization and letting concourse pick the latest build trigger for the job among all enqueued ones.

### ISSUE THREAD

**Issue by Velann** [concourse/concourse#2113]
Hi 

I have a pipeline which has three parallel jobs (J1, J2, J3) to begin with, once J3 passes J4 will be triggered.
Then J5, J6, J7 will be serially triggered based on the success of all J1, J2 & J4.

Here we are using lock mechanism to control the trigger of the three parallel jobs, Still lot of manual intervention required as sometimes locks has to be released manually. Leaving that apart.

Complete one time execution of the pipeline takes 2 hrs.
So in that 2hrs some more Git check-ins are happening and they are getting enqueued.
So is there a possible way where as when the pipeline is getting triggered for the second time. Only the trigger should happen for the latest checkin and all others should be ignored or dropped as the latest one itself will produce build with all latest changes.

Can someone please let me know a way to do this in concourse.

Eg:

Pipeline is getting triggered at 10:00AM because of checkin "1". And during the execution time of pipeline which is 2 hrs. Further checkins "2","3","4","5" are happening and triggers are getting into the Queue. By the time the checkin "1" triggered execution completes, the trigger due to the checkin "5" should be taken and continued all the other "2","3","4" should be ignored or dropped.

Is there a mechanism in concourse to do that.
As this will help avoiding redundant build creation for four times even though the changes of the checkin"5" is already available.

**Comment by xtremerui** [comment]
closing stale issue.
