### ISSUE TITLE
Using BTRFS for baggageclaim results in freezed server often

### ISSUE THREAD

**Issue by leshik** [concourse/concourse#2115]
# Bug Report

I switched to `btrfs` driver because `overlay2` is painfully slow. Everything was great until it stops working, and when it stops – the only solution is to **physically** restart the underlying VM. I'm using `docker-compose` and when this happens `docker restart concourse_worker_1` doesn't help because docker can't kill the container. Even `systemctl stop docker.service` doesn't help because some processes can't be killed even with `kill -9`. I figured out one of these processes:

```
root      4212  0.0  0.0   2016     4 ?        D    03:12   0:00      |   \_ /worker-state/3.9.2/assets/btrfs/btrfs subvolume snapshot /worker-state/volumes/live/b1598d58-0baf-42eb-7d32-c4fe25ddcc6b/volume /worker-state/volumes/init/28650a54-8d14-4f16-7fa0-06aa8156c3e9/volume
```

Using `overlay2` as a driver is not a solution as it takes more than 40 mins to build something that is usually built in 10 mins with `btrfs`:

Overlay2:
![screenshot 2018-03-27 12 48 47](https://user-images.githubusercontent.com/443678/37960073-4c19201a-31bd-11e8-8aa3-ba198b12943d.png)

BTRFS:
![screenshot 2018-03-27 12 49 08](https://user-images.githubusercontent.com/443678/37960074-4c37114c-31bd-11e8-9930-3c85dda15b63.png)

Any workarounds are welcome!

* Concourse version: 3.9.2
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: Digital Ocean, Ubuntu 16.04

**Comment by vito** [comment]
Kernel version?

**Comment by leshik** [comment]
Sorry, forgot about this – `4.13.0-37-generic` from Ubuntu 16.04 HWE.

**Comment by vito** [comment]
Interesting. Do you see high memory usage prior to the lockups? And possibly once it starts swapping it hangs? Is it consistently `kswapd` in the trace when this happens?

This is the first I've seen this particlar scenario, but a cursor googling of "btrfs kswapd0" yields some interesting results.

**Comment by leshik** [comment]
Honestly, I don’t know as I didn’t look at stack traces before (I checked Concourse logs). I will pay more attention now. As for memory usage, I don’t think so. The application I’m testing is quite conservative on memory usage and my tasks are mostly run in serial fashion. I’ve never seen usage over 60% on this server.

**Comment by JohannesRudolph** [comment]
@vito can you elaborate on this?

**Comment by leshik** [comment]
For me, the problem seems to be solved magically by setting `vm.swappiness = 0`. I'm using separately formatted `btrfs` block storage for `/worker-state/volumes`. I'm still on `3.10` with no downtime since then, so it's a long time comparing to my previous experience...

**Comment by andy-plutoflume** [comment]
@leshik I'll give that a go, thanks.

**Comment by xtremerui** [comment]
closing stale issue.
