### ISSUE TITLE
Logged out users can see build tasks

### ISSUE THREAD

**Issue by benmoss** [concourse/concourse#2116]
* Concourse version: 3.9.2

We noticed that when we refreshed the page on a build while logged out of our Concourse, we were able to briefly see the job information. This seems like a bug since once the page finishes loading it shows us the "Log in to view" message instead.

![concourse-bug](https://user-images.githubusercontent.com/239754/37973238-0a89eb62-31a8-11e8-996c-b59bcb699365.gif)

**Comment by jama-pivotal** [comment]
@benmoss Hmmm, does this happen for all the jobs, or just a specific one? Also, can you provide browser details (in case its browser specific). Trying to reproduce on some of our internal environments here and I'm having difficulty getting repro'd locally

**Comment by benmoss** [comment]
@jama-pivotal it happens for all jobs. [this](whatsmybrowser.org/b/DVUNKMR) is my browser info, though i'm pretty sure it's not browser specific. I think it only happens when you have public pipelines though.

I looked into the API calls that the Javascript is making and it looks like the API is showing the build values and only the UI is hiding them, so I'm not sure if this is intentional or not. The actual logs aren't leaked, just the build plan.

**Comment by xtremerui** [comment]
this is a bug in UX. There is indeed a flash of build plans showing first and then disappear.

**Comment by vito** [comment]
Beyond the UX aspect, this is something we should either document for exposed pipelines (step names are visible through the API) or fix on the server-side (don't allow fetching plan if job isn't public).

Scheduling this for 'API' to explore whether we can just disallow access to that endpoint.

**Comment by pivotal-jamie-klassen** [comment]
so #3392 is marked as 'fixing' this issue, but there are some error cases (specifically 401 errors on the plan and prep endpoints) that need to be handled differently in the UI, because now we have 'endless loading' in the cases described above. @vito do you want to merge this and make a separate issue for the UI part?

**Comment by vito** [comment]
@pivotal-jamie-klassen Right - let's try just making the rest of the changes on the same branch, and then I'll merge it all at once.
