### ISSUE TITLE
Concourse symlinks C: to the volume directory

### ISSUE THREAD

**Issue by jviotti** [concourse/concourse#2117]
# Question

Just out of curiosity, why does Concourse symlinks the drive letter to the volume directory on Windows? ie `C:` seems to symlink to the `concourse/work/live/<uuid>/volume` directory.

**Comment by vito** [comment]
I'm not sure what you mean by this. What symlink?

**Comment by jviotti** [comment]
@vito If I start a Windows job, and within the job I stat `C:`, then it tells me its a symbolic link. If I follow the symbolic link, I end up back in the `volume` directory where my build is running from. I was wondering how this worked, and why.
