### ISSUE TITLE
Build view quits updating in real-time

### ISSUE THREAD

**Issue by timrchavez** [concourse/concourse#2119]
# Feature Request / Bug Report

## What challenge are you facing?

There are situations where a developer will be monitoring their build from the build view in the UI, waiting for it to complete. We have run into a situation where the build page stops updating in such a way that it _appears_  the build is stuck or blocking. More specifically: the build log stops updating, the build view remains yellow (in progress), and the "started" counter keeps ticking. The reality, however, is that the build actually finishes, but the web UI has simply quit updating. While I encourage folk to use Slack or other forms of notification, I could see how this could be confusing, and seems erroneous.

The following can also be handy:

* Concourse version: v3.9.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS:
* Browser (if applicable): 65.0.3325.181 (Official Build) (64-bit)
* Did this used to work? I believe this works in most cases

## A Modest Proposal

I _think_ this is a bug. I don't know what the solution is, but we hit this when we had a degraded Docker registry cause lots of timeouts and general slowness during the `docker push` phase. I'm not sure if these long io waits are the culprit here (5m+ with no events streaming to the UI, for example), but may be a clue.

**Comment by wesm-outreach** [comment]
I'm also experiencing this issue.

**Comment by jama-pivotal** [comment]
Marking this as a bug that needs investigation. I know some of our pages aren't super great at pulling in changes to represent the state of the world so it could fall either way after some poking around. I'll put this high in our Backlog since having build page accuracy is pretty important for us

**Comment by xtremerui** [comment]
I think I have seen this couple times on concourse ci `atc` job where similar behaviour observed. 
[1792](https://ci.concourse-ci.org/teams/main/pipelines/main/jobs/atc/builds/1792), [1786](https://ci.concourse-ci.org/teams/main/pipelines/main/jobs/atc/builds/1786), [1776](https://ci.concourse-ci.org/teams/main/pipelines/main/jobs/atc/builds/1776)

Notice all those builds were running longer than 3 hours and have to be cancelled manually. It might be just a case similar to what mentioned here that the UI stops updating. Will need to check when it happens again next time.
