### ISSUE TITLE
Concourse (garden) doesn't recognise death of init process it spawned in the container

### ISSUE THREAD

**Issue by redbaron** [concourse/concourse#212]
Simple example would be to kill `initd` process spawned for one of resource `check` steps.

If you do so, you'd get following error on resource UI page:
```
checking failed
resource script '/opt/resource/check []' failed: exit status 255

stderr:
start process: container_daemon: connect to socket: unix_socket: connect to server socket: dial unix /var/vcap/data/garden/depot/6g533psdahc/run/wshd.sock: connection refused
```

which doesn't go away even if you reboot worker

**Comment by xoebus** [comment]
@goonzoid @julz This sounds like it belongs to Garden. What do you think?

**Comment by goonzoid** [comment]
@xoebus yes, but I don't know what we'd be able to do about it. If you kill initd, the container is dead. The workaround is to not kill initd :trollface:.
If you've spawned a container with a root user then you're implicitly allowing that user to kill the container. If you kill the container you will not then be able to run future processes in it.

The comment about the error not going away when the worker is rebooted sounds like it's related to snapshot/restore. To restart a worker and have all containers recreated the worker needs to be recreated (rather than just restarted).

**Comment by vito** [comment]
@goonzoid Yeah, I guess it's just a question of whether Garden should realize one of its containers is unrecoverable and have it go away from the API. I could see the argument for not having it do it; in CF your health checks would start failing anyway and the container would probably be destroyed. Having the API be the only way for containers to disappear (either grace time or .Destroy) sounds like the least presumptuous thing to do, which is already the case.

In this case Concourse just keeps trying to run the process, not realizing the container is hopeless.

Perhaps some way to indicate to the caller that the container is unrecoverable would help? Which arguably we'd get for free if we got richer errors back from Garden; we'd handle the known errors (i.e. command not found, network blip) and treat anything else as fatal.

**Comment by goonzoid** [comment]
Agreed, richer errors is certainly something I'd like Garden to provide.

I've put [#109944908](https://www.pivotaltracker.com/story/show/109944908) in Tracker as a placeholder to think about some kind of "container unrecoverable" error type that we can return from `Container.Run` (and possibly other calls).

**Comment by vito** [comment]
Gonna close this out since it's been delegated to the proper team (there's nothing for us to really do on the Concourse side of things).

**Comment by ernado** [comment]
This error occurs when restarting worker with systemd. Cleaning worker folder and rebooting hosts works, but it is annoying. Any updated on this?
