### ISSUE TITLE
ATC database migration SQL script mistakenly assumes "public" schema

### ISSUE THREAD

**Issue by vganoradg** [concourse/concourse#2120]
# Bug Report

I found a problem in the ATC database migration SQL scripts. Line 8 of 1517330648_add_worker_resource_certs.up.sql assumes that the "workers" table is in the "public" schema. (See https://github.com/concourse/atc/blob/1d8e64412cf894801be7c655a95bdfe01e1e86a8/db/migration/migrations/1517330648_add_worker_resource_certs.up.sql#L8 ) Nothing else make that assumption and we've always used a different schema name. I believe line 8 should instead be as follows:

      CONSTRAINT "worker_resource_certs_worker_name_fkey" FOREIGN KEY ("worker_name") REFERENCES "workers"("name") ON DELETE CASCADE ON UPDATE SET NULL

**Comment by vito** [comment]
Good catch! We should definitely fix that.

A PR would be very much appreciated, fwiw.

**Comment by vito** [comment]
thanks for submitting the PR!
