### ISSUE TITLE
fly targets crashes when first fly login fails

### ISSUE THREAD

**Issue by charleshansen** [concourse/concourse#2121]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request

Add a target to fly without logging in.

## What challenge are you facing?

I am attempting to write a workstation setup script that will install fly and add a target to fly. The only way I see to add a target is to use `fly login`, but I cannot programmatically login to fly

## A Modest Proposal

There should be some way to add a target with fly without actually logging in. Maybe the existing `fly login` with invalid credentials flow could be fixed.

# Bug Report

When I try to login with a target for the first time, and the login fails, the target is still partially added to fly. When I run `fly targets`, I get this dump.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1445501]

goroutine 1 [running]:
github.com/concourse/fly/commands.GetExpirationFromString(0xc420183860, 0xc4201aae40, 0xc420113978)
	/Users/pilot/Worker/workdir/volumes/live/249a651f-8944-4cd8-77e4-796b1f9887cc/volume/concourse/src/github.com/concourse/fly/commands/targets.go:59 +0x81
github.com/concourse/fly/commands.(*TargetsCommand).Execute(0x1a48110, 0xc4201a7260, 0x0, 0x1, 0x1a48110, 0x1)
	/Users/pilot/Worker/workdir/volumes/live/249a651f-8944-4cd8-77e4-796b1f9887cc/volume/concourse/src/github.com/concourse/fly/commands/targets.go:33 +0x31e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420080ba0, 0xc420098070, 0x1, 0x1, 0xc420105a70, 0xc420080c60, 0x7fff5fbfcb60, 0x0, 0x0)
	/Users/pilot/Worker/workdir/volumes/live/249a651f-8944-4cd8-77e4-796b1f9887cc/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:316 +0x893
github.com/jessevdk/go-flags.(*Parser).Parse(0xc420080ba0, 0x1a48100, 0x2, 0xc420080c60, 0xc42016d770, 0xc420113c50)
	/Users/pilot/Worker/workdir/volumes/live/249a651f-8944-4cd8-77e4-796b1f9887cc/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x73
main.main()
	/Users/pilot/Worker/workdir/volumes/live/249a651f-8944-4cd8-77e4-796b1f9887cc/volume/concourse/src/github.com/concourse/fly/main.go:46 +0x2f3
``` 

The following can also be handy:

fly version 3.6.0
bosh deployment
Did this used to work? probably not

**Comment by shashwathi** [comment]
related to [issue](https://github.com/concourse/concourse/issues/1880)
