### ISSUE TITLE
I tried using JIRA resource but ended up with an error 

### ISSUE THREAD

**Issue by Rahul-github** [concourse/concourse#2122]
Hello!

I am trying to use JIRA resource type `https://github.com/danrspencer/jira-resource` but ended up with following error in Concourse pipeline.

```
Fri, 30 Mar 2018 20:34:10 GMT jira-resource Sending search: project="AGILE" AND summary~"Example jira ticket" ORDER BY id DESC
Fri, 30 Mar 2018 20:34:10 GMT jira-resource Response: (200) {
  "startAt": 0,
  "maxResults": 1,
  "total": 0,
  "issues": []
}
Fri, 30 Mar 2018 20:34:10 GMT jira-resource Issue doesn't exist, creating new issue...
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/build/put/jira-resource/spec/sample.out'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at module.exports (/opt/resource/src/replaceTextFileString.js:14:22)
```

I have used their [example pipeline](https://github.com/danrspencer/jira-resource/blob/master/ci/pipelines/example.yml)

Can anyone help me how can I use this?

**Comment by shashwathi** [comment]
@Rahul-github 

It is a resource maintained by the community. Feel free to raise github issue on their repo.

Tips to debug: 
-> Verify your concourse deployment has this resource deployed. Check [this](https://github.com/danrspencer/jira-resource/blob/master/ci/pipelines/pipeline.yml) pipeline for sample deployment.

**Comment by jama-pivotal** [comment]
Closing since its not the right project
