### ISSUE TITLE
Link to architecture docs on main README.md (404)

### ISSUE THREAD

**Issue by markstgodard** [concourse/concourse#2123]
Just noticed the link to *Concourse Architecture* on main https://github.com/concourse/concourse page is 404ing.
Link in question is: https://concourse-ci.org/architecture.html

Not sure if its no longer a thing or if during the new site UI link broke.

Cheers

**Comment by jama-pivotal** [comment]
The new link is actually https://concourse-ci.org/components.html , so I can take on updating the README.md to point to the right pages

**Comment by jama-pivotal** [comment]
...and done, closing
