### ISSUE TITLE
Bug: Grafana dashboard issue - deployment name from concourse is missing

### ISSUE THREAD

**Issue by sattan66** [concourse/concourse#2124]
Hi ,

#BugReport

I am using Prometheus bosh release to monitor concourse.  I have followed the below links to setup the monitoring.

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-concourse.yml

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/concourse/enable-prometheus-metrics.yml

I am able to get the metrics in prometheus (Graph and console), but the Grafana dashboards are not showing any metrics. while digging into it, I see the deployment name is not exposed on port 9391.

The following can also be handy:

* Concourse version: 3.9.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vmware
* Browser (if applicable): any browser
* Did this used to work?- no

![image](https://user-images.githubusercontent.com/26006689/38243203-6147e20e-3754-11e8-9d24-fe25ace5a71d.png)

in the attached image, the first query is not working, whereas second query without deployment name is able to plot the graph.

**Comment by vito** [comment]
@jmcarp @TimSimmons Is this because the Prometheus emitter ignores [`--metrics-attribute` flag](https://github.com/concourse/atc/blob/cb54e7f3d8f15269e6aaa736ed943dc3a88944cf/atccmd/command.go#L136)? These values get added on to the attributes for all events emitted, but the Prometheus emitter [selects particular attributes for emitting](https://github.com/concourse/atc/blob/cb54e7f3d8f15269e6aaa736ed943dc3a88944cf/metric/emitter/prometheus.go#L360-L370).

**Comment by TimSimmons** [comment]
It is! It's generally an [anti-pattern](https://groups.google.com/forum/#!topic/prometheus-developers/JyGxKxhQu18) to add labels to all Prometheus metrics. We could however add a `concourse_build_info` metric, similar to what is described here:
https://www.robustperception.io/exposing-the-software-version-to-prometheus/
also of note:
https://www.robustperception.io/how-to-have-labels-for-machine-roles/

So we would expose a metric that looked like:
`concourse_build_info{version="3.9.1"....}` for any of those metric attributes specified, and then you could query using them (albeit in a roundabout way).

**Comment by vito** [comment]
@TimSimmons Thanks for the context! :)

@sattan66 Would that suggestion work for you?

**Comment by xtremerui** [comment]
closing stale issue.
