### ISSUE TITLE
Secrets fail to be interpolated if there are spaces around the parentheses

### ISSUE THREAD

**Issue by brownjohnf** [concourse/concourse#2126]
# Bug Report

If you include spaces around your secrets variable, it's ignored by concourse and inserted as a raw string. For example:

```
GITHUB_USERNAME: (( github-username ))
```

Will contain `(( github-username ))`. If you remove the extra spaces, it interpolates correctly.

* Concourse version: v3.8.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS/on-prem
* Browser (if applicable): n/a
* Did this used to work? Not as far as I know

**Comment by brownjohnf** [comment]
cc @jviotti

**Comment by avanier** [comment]
I'm interested to hear about this one. Might be a good ticket to sink my noob teeth in.

**Comment by jama-pivotal** [comment]
Not sure if its quite a bug, so erring on the side of marking this as an enhancement request to allow whitespace after `((` and before `))`. I mean, the documentation *technically* shows no whitespace. I can see why you would want to have the whitespace for legibility reasons.

**Comment by avanier** [comment]
So, I did a bit of digging, and right now this is deferred [here](https://github.com/concourse/atc/blob/3c7785c3aab803fd966d8f604f3b239626d5e3e8/creds/variables_factory.go) to a library from [`bosh-cli`](https://github.com/cloudfoundry/bosh-cli/blob/master/director/template/template.go#L90).

@jama-pivotal Do you think it's best to :
- PR on the library at the risk of causing mayhem in `bosh-cli`
   - Can we even bump that library without causing mayhem to Concourse?
- Fork said library into the Concourse code base
- Let sleeping dogs lie (don't fix it if it ain't borken <- spelled properly)

**Comment by vito** [comment]
@avanier :turtle: A PR upstream would probably be sufficient. I can't think of a reason not to allow whitespace, aside from wanting to ensure consistent syntax from project to project. In any case it's a change to a dependency so I'd just defer to their decision.
