### ISSUE TITLE
Manually triggered job doesn't fail if resource check it depends on fails

### ISSUE THREAD

**Issue by redbaron** [concourse/concourse#213]
1. make a pipeline where 1 job depends on 1 resource and build it once.
2. make resource check step to fail (killing it's `initd` process helps here)
3. trigger job which depends on a resource and which was built before, it will happily proceed to building a stale (cached) resource even though resource check failed.

**Comment by vito** [comment]
Pretty sure this is fixed now. Reopen if not.
