### ISSUE TITLE
Frequently getting internal failures with messages like Get /volume/... EOF

### ISSUE THREAD

**Issue by pivotal-jbarrett** [concourse/concourse#2132]
We have many jobs that run concurrently in a pipeline. When running some jobs fail randomly in a task with messages like the following. The the frequency of this behavior increased significantly with 3.9.2. We have tried redeploying the whole BOSH deployment but that hasn't cleared anything up. Any other suggestions to try are welcome. We are at the point now that we may trash our deployment and deploy back to 3.8 to get around this issue but would rather find a solution to fix it.

Get /volumes/f7231fc9-42f7-4d09-4a21-7312089dfe96: EOF

* Concourse version: 3.9.2
* Deployment type: BOSH
* Infrastructure/IaaS: AWS
* Did this used to work? Priory to 3.9.x these issues were very infrequent.

**Comment by metatype** [comment]
@smgoller do you have any more context on this error?

**Comment by metatype** [comment]
@pivotal-jbarrett would it help if we shared logs with the concourse team?

**Comment by pivotal-jbarrett** [comment]
Seems resolved in 3.11.
