### ISSUE TITLE
Dashboard footer icon display in Firefox

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#2136]
Dashboard footer icons render weirdly in Firefox (bottom):

<img width="1527" alt="screen shot 2018-04-09 at 9 56 04 am" src="https://user-images.githubusercontent.com/1919762/38518765-dc969a34-3c0b-11e8-9dc6-cc1a4238e5d0.png">

* Concourse version: 3.10
* Browser: Firefox

**Comment by jama-pivotal** [comment]
LOL that looks hilarious
