### ISSUE TITLE
pipeline a job 1 gets same semver version as pipeline b job 2

### ISSUE THREAD

**Issue by dliebreich** [concourse/concourse#214]
If I have 2 pipelines pointing to the same semver resource, either git-backed or s3-backed, and run jobs in each pipeline that do a get (with bump) then immediately do a put, then both jobs can get the same semver version.

We would like to use a single semver resource for multiple pipelines - and we can't because of this interaction between the semver resource and caching.

**Comment by vito** [comment]
Resolved in-person by using `put` to bump versions atomically w/ the `git` driver, instead of `get`.
