### ISSUE TITLE
Add a test to the Concourse pipeline for a fresh install

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2147]
The recent releases of Concourse have been a bit rocky, and I think some of the issues could have been avoided if we wrote tests for a fresh-install of Concourse for our supported installation methods. While BOSH is probably the first method that comes to mind (https://github.com/concourse/concourse/pull/2125 and https://github.com/concourse/concourse/issues/2029 are both examples of BOSH installation problems identified immediately after release), we should test all our supported methods.

We might not need to ruin this test as a part of our regular `develop` group, but probably as a pre-publish job / test?

**Comment by xtremerui** [comment]
IMHO for above issues it'd better fail fast than wait and catch it only before publish. 

We can change the `bosh-test-deploy` job to first delete the deployment then redeploy for a fresh bosh installation (unless you want that bosh to be fresh installed).

For testing docker installation, I think right now the `bin-docker-testflight` is doing a fresh install already (unless you want the docker image `concourse/bin-docker-testflight-ci` that used for this job to be fresh build).

Please correct me if any of my understanding is not true.

**Comment by jama-pivotal** [comment]
We should just apply spaces to test multiple stemcells and never release software becaues we'll eat up all the necessary compute to try every stemcell possible....

J/K sounds reasonable, maybe we don't need to do fresh installs and we should just stick to fail fast and recover fast

**Comment by ywei2017** [comment]
So what is the resolution on this? Both 3.9 and 3.10  broke our exiting installs (BOSH managed), and we had to scramble...
