### ISSUE TITLE
build used pool-resource that was no longer claimed due to add/remove

### ISSUE THREAD

**Issue by dliebreich** [concourse/concourse#215]
A claimed lock (at ref aaaaa) was removed from a pool (at ref bbbbb) and added to a different pool. After the add/remove had completed, a different build was given the lock at ref aaaaa.

I expected the new build not to use the lock at ref aaaaa since it was no longer valid.

**Comment by vito** [comment]
There's a check within the resource to ensure a lock hasn't been modified after the sha it's told. Did that not work?

**Comment by xoebus** [comment]
I think I remember us resolving this in person. Please re-open if that's not the case!

**Comment by bionovastore8** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Succeed! It could be one of the most useful blogs we have ever come across on the subject. Excellent info! I’m also an expert in this topic so I can understand your effort very well. Thanks for the huge help. | <a href="https://orcid.org/0000-0002-8186-5889">car detailing Aylesbury</a>
-- | --



</body>
</html>

**Comment by hitsoftcrack** [comment]
A claimed lock (at ref aaaaa) was taken out of one pool and put into another pool (at ref bbbb[b](https://hitsoftcrack.com/snappy-driver-installer-origin-crack/)).
