### ISSUE TITLE
Concourse resource pull is flakey and requires a web VM restart

### ISSUE THREAD

**Issue by kkallday** [concourse/concourse#2150]
# Bug Report

Hi Concourse folks,

My team has ran into some weird issues with `resources` not checking/updating and resulting in jobs not triggering.

Specifically, today I ran into an issue in which a `resource` wasn't listing artifacts. There were two different pipelines that have the same resource that pull releases using the `pivnet` resource. Both `resources` have the same definition in the pipeline yaml however one was able to list artifacts successfully and the other one wasn't. Furthermore, the `fly check-resource` command hung indefinitely when trying to update the `resource`.

Although restarting the web vms fixed the issue, I'd like to know if there's a specific place I can look into for logs to help diagnose the problem. We have a fairly large concourse deployment (~10 workers) so its kind of hard to track down the which worker might have hosted the check container.

As a stopgap, we are now restarting our vms every day but this feels like a hack.

Thanks,

Kevin

* Concourse version: v3.9.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Did this used to work? We previously didn't have to restart our web vms so often

**Comment by shashwathi** [comment]
@kkallday : 

Can you check the CPU utilization and web vm health before you restart? 

Its possible that `atc` is overloaded.

**Comment by kkallday** [comment]
Hi @shashwathi,

Before restarting the VMs we checked the CPU and memory usage and they were normal.

**Comment by shashwathi** [comment]
@kkallday : 

does increasing number of web nodes to 2 make any difference to the deployment ?

**Comment by kkallday** [comment]
@shashwathi we currently have 2 web VMs deployed and 8 workers.

**Comment by kkallday** [comment]
Hey just a follow up to this issue. I have joined a new team and I am now seeing the issue on their concourse.

The part of the pipeline in question is structured as follows:
Job A -> Job B -> Job C

Job B is triggered by the pool resource and has a passed constraint on Job A. Job C is triggered by the pool resource and has a passed constraint on Job B.

We are witnessing the following scenario:
1. Job A passes
1. Job B is triggered
1. Job B passes
1. Job C never triggers

Job C should trigger because it has never ran with the SHA the pool resource is reporting. Here are screenshots of the whats happening:

Pipeline:
![screen shot 2018-05-17 at 10 03 36 am](https://user-images.githubusercontent.com/926865/40192597-b215d2f4-59b9-11e8-9864-a75a77ea0816.png)

"Job A":
![screen shot 2018-05-17 at 10 05 46 am](https://user-images.githubusercontent.com/926865/40192699-fc89f5c2-59b9-11e8-934e-389492d3127c.png)

"Job B":
![screen shot 2018-05-17 at 10 06 03 am](https://user-images.githubusercontent.com/926865/40192725-06f49986-59ba-11e8-895d-980c770db0c5.png)

Concourse version: v3.8.0
Deployment type (BOSH/Docker/binary): BOSH
Infrastructure/IaaS: GCP

**Comment by pnsantos** [comment]
I think this is the same issue as in #2010

**Comment by vito** [comment]
@kkallday Thanks for following up!

I think we'll need even more info to confirm whether this is the same as #2010 though. Next time it happens could you look for the same message in the ATC logs? (grep for `worker_resource_config_check__resource_config_check_sessio_fkey`)

If that's not a match, your best bet will be to `grep` for logs lines that mention the resource. If that doesn't show anything fishy, a stack dump at least would help. Here's how to do that: https://github.com/concourse/concourse/wiki/Troubleshooting#taking-a-stack-dump

**Comment by vito** [comment]
Closing this as #2010 was fixed and there was no follow-up here to confirm either way. The fix for #2010 will be in v5.0.0.
