### ISSUE TITLE
3.9.2 could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

### ISSUE THREAD

**Issue by davidgarciaMontreal** [concourse/concourse#2155]
Hello,
After we migrated to 3.9.2 from 3.8.2, we are having a lot of virtual interfaces being left by what it seems to me from the concourse worker. i would need someones help on this from the conocurse ci team.

`$ docker-compose up -d`
`Creating network "node2321_default" with the default driver`
`ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network`
`$ ip addr show`
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever`
`2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8d:38:6c brd ff:ff:ff:ff:ff:ff
    inet 142.133.166.82/24 brd 142.133.166.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8d:386c/64 scope link
       valid_lft forever preferred_lft forever`
`4: br-8ac50aa756cf: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:55:b2:3b:ea brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/16 scope global br-8ac50aa756cf
       valid_lft forever preferred_lft forever
    inet6 fe80::42:55ff:feb2:3bea/64 scope link
       valid_lft forever preferred_lft forever`
`261: br-6c20732a31c8: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:96:a9:69:59 brd ff:ff:ff:ff:ff:ff
    inet 192.168.96.1/20 scope global br-6c20732a31c8
       valid_lft forever preferred_lft forever`
`5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:b6:36:94:ce brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:b6ff:fe36:94ce/64 scope link
       valid_lft forever preferred_lft forever`
`265: br-cc0fb7e5a606: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:46:82:82:e4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.112.1/20 scope global br-cc0fb7e5a606
       valid_lft forever preferred_lft forever
    inet6 fe80::42:46ff:fe82:82e4/64 scope link
       valid_lft forever preferred_lft forever`
`274: br-48fae90d1845: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:8e:f7:00:92 brd ff:ff:ff:ff:ff:ff
    inet 192.168.128.1/20 scope global br-48fae90d1845
       valid_lft forever preferred_lft forever
    inet6 fe80::42:8eff:fef7:92/64 scope link
       valid_lft forever preferred_lft forever`
`277: br-671b1cc1c63e: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:c4:d4:7c:26 brd ff:ff:ff:ff:ff:ff
    inet 192.168.144.1/20 scope global br-671b1cc1c63e
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c4ff:fed4:7c26/64 scope link
       valid_lft forever preferred_lft forever`
`289: br-64aeea298218: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:c8:7e:9d:f1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.160.1/20 scope global br-64aeea298218
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c8ff:fe7e:9df1/64 scope link
       valid_lft forever preferred_lft forever`
`40: br-aa980784d84b: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ec:0a:ae:97 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global br-aa980784d84b
       valid_lft forever preferred_lft forever
    inet6 fe80::42:ecff:fe0a:ae97/64 scope link
       valid_lft forever preferred_lft forever`
`301: br-dbf5759016c6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:2e:15:f7:5b brd ff:ff:ff:ff:ff:ff
    inet 192.168.176.1/20 scope global br-dbf5759016c6
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2eff:fe15:f75b/64 scope link
       valid_lft forever preferred_lft forever`
`45: veth4d27eba@veth91d1c94: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff`
`46: veth91d1c94@veth4d27eba: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1500 qdisc noqueue master br-aa980784d84b state LOWERLAYERDOWN group default
    link/ether 36:ce:df:f2:ce:cb brd ff:ff:ff:ff:ff:ff
    inet6 fe80::34ce:dfff:fef2:cecb/64 scope link
       valid_lft forever preferred_lft forever`
`313: br-37b2833cd7ec: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:81:71:12:5f brd ff:ff:ff:ff:ff:ff
    inet 192.168.192.1/20 scope global br-37b2833cd7ec
       valid_lft forever preferred_lft forever
    inet6 fe80::42:81ff:fe71:125f/64 scope link
       valid_lft forever preferred_lft forever`
`66: br-fbf94595d03f: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:34:4b:d7:04 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 scope global br-fbf94595d03f
       valid_lft forever preferred_lft forever
    inet6 fe80::42:34ff:fe4b:d704/64 scope link
       valid_lft forever preferred_lft forever`
`325: br-da9e5f3f7e2f: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:c8:e5:7f:4a brd ff:ff:ff:ff:ff:ff
    inet 192.168.208.1/20 scope global br-da9e5f3f7e2f
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c8ff:fee5:7f4a/64 scope link
       valid_lft forever preferred_lft forever`
`76: br-4ce98dce5f97: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:af:87:1d:c3 brd ff:ff:ff:ff:ff:ff
    inet 172.22.0.1/16 scope global br-4ce98dce5f97
       valid_lft forever preferred_lft forever
    inet6 fe80::42:afff:fe87:1dc3/64 scope link
       valid_lft forever preferred_lft forever`
`340: br-8430d9b9f9c7: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ef:9b:e0:cb brd ff:ff:ff:ff:ff:ff
    inet 192.168.224.1/20 scope global br-8430d9b9f9c7
       valid_lft forever preferred_lft forever
    inet6 fe80::42:efff:fe9b:e0cb/64 scope link
       valid_lft forever preferred_lft forever`
`91: br-084e16c8fa9d: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:87:a8:7e:49 brd ff:ff:ff:ff:ff:ff
    inet 172.23.0.1/16 scope global br-084e16c8fa9d
       valid_lft forever preferred_lft forever
    inet6 fe80::42:87ff:fea8:7e49/64 scope link
       valid_lft forever preferred_lft forever`
`96: br-f09d024bb72a: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:00:55:f8:14 brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.1/16 scope global br-f09d024bb72a
       valid_lft forever preferred_lft forever
    inet6 fe80::42:ff:fe55:f814/64 scope link
       valid_lft forever preferred_lft forever`
`97: vethea27235@veth5c55860: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 02:42:ac:15:00:02 brd ff:ff:ff:ff:ff:ff`
`98: veth5c55860@vethea27235: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1500 qdisc noqueue master br-f09d024bb72a state LOWERLAYERDOWN group default
    link/ether 66:7f:b8:4c:ac:aa brd ff:ff:ff:ff:ff:ff
    inet6 fe80::647f:b8ff:fe4c:acaa/64 scope link
       valid_lft forever preferred_lft forever`
`103: br-b33496e3ef2c: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:15:f9:98:97 brd ff:ff:ff:ff:ff:ff
    inet 172.24.0.1/16 scope global br-b33496e3ef2c
       valid_lft forever preferred_lft forever
    inet6 fe80::42:15ff:fef9:9897/64 scope link
       valid_lft forever preferred_lft forever`
`106: br-15e165d696a3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:d8:d0:73:3e brd ff:ff:ff:ff:ff:ff
    inet 172.25.0.1/16 scope global br-15e165d696a3
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d8ff:fed0:733e/64 scope link
       valid_lft forever preferred_lft forever`
`364: br-84b14adc3ec6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:9a:8a:d2:48 brd ff:ff:ff:ff:ff:ff
    inet 192.168.240.1/20 scope global br-84b14adc3ec6
       valid_lft forever preferred_lft forever
    inet6 fe80::42:9aff:fe8a:d248/64 scope link
       valid_lft forever preferred_lft forever`
`368: vethbf74560@if367: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-84b14adc3ec6 state UP group default
    link/ether 7a:3c:7e:b1:7e:a1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::783c:7eff:feb1:7ea1/64 scope link
       valid_lft forever preferred_lft forever`
`112: br-e3e2e5f08087: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:e9:d1:6e:7d brd ff:ff:ff:ff:ff:ff
    inet 172.26.0.1/16 scope global br-e3e2e5f08087
       valid_lft forever preferred_lft forever
    inet6 fe80::42:e9ff:fed1:6e7d/64 scope link
       valid_lft forever preferred_lft forever`
`123: br-ee5bdc17c953: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ed:85:b0:dd brd ff:ff:ff:ff:ff:ff
    inet 172.27.0.1/16 scope global br-ee5bdc17c953
       valid_lft forever preferred_lft forever
    inet6 fe80::42:edff:fe85:b0dd/64 scope link
       valid_lft forever preferred_lft forever`
`135: br-633bfb80751f: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:63:78:ab:c3 brd ff:ff:ff:ff:ff:ff
    inet 172.28.0.1/16 scope global br-633bfb80751f
       valid_lft forever preferred_lft forever
    inet6 fe80::42:63ff:fe78:abc3/64 scope link
       valid_lft forever preferred_lft forever`
`153: br-1940b142688f: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:7c:47:23:ae brd ff:ff:ff:ff:ff:ff
    inet 172.29.0.1/16 scope global br-1940b142688f
       valid_lft forever preferred_lft forever
    inet6 fe80::42:7cff:fe47:23ae/64 scope link
       valid_lft forever preferred_lft forever`
`169: br-33fb9d842dce: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:e2:e7:92:b8 brd ff:ff:ff:ff:ff:ff
    inet 172.30.0.1/16 scope global br-33fb9d842dce
       valid_lft forever preferred_lft forever
    inet6 fe80::42:e2ff:fee7:92b8/64 scope link
       valid_lft forever preferred_lft forever`
`175: br-f8038e629409: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:f5:03:3a:5d brd ff:ff:ff:ff:ff:ff
    inet 172.31.0.1/16 scope global br-f8038e629409
       valid_lft forever preferred_lft forever
    inet6 fe80::42:f5ff:fe03:3a5d/64 scope link
       valid_lft forever preferred_lft forever`
`181: br-84350c116289: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:17:54:82:6c brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/20 scope global br-84350c116289
       valid_lft forever preferred_lft forever`
    inet6 fe80::42:17ff:fe54:826c/64 scope link
       valid_lft forever preferred_lft forever`
`193: br-735b9c3aa060: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:3b:c3:f4:81 brd ff:ff:ff:ff:ff:ff
    inet 192.168.16.1/20 scope global br-735b9c3aa060
       valid_lft forever preferred_lft forever
    inet6 fe80::42:3bff:fec3:f481/64 scope link
       valid_lft forever preferred_lft forever`
`205: br-11e637d0061b: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:d6:71:fc:f9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.32.1/20 scope global br-11e637d0061b
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d6ff:fe71:fcf9/64 scope link
       valid_lft forever preferred_lft forever`
`217: br-0e1b54c0de12: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:e1:59:c9:cc brd ff:ff:ff:ff:ff:ff
    inet 192.168.48.1/20 scope global br-0e1b54c0de12
       valid_lft forever preferred_lft forever
    inet6 fe80::42:e1ff:fe59:c9cc/64 scope link
       valid_lft forever preferred_lft forever`
`234: br-fb342d1dff8a: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:82:eb:03:97 brd ff:ff:ff:ff:ff:ff
    inet 192.168.64.1/20 scope global br-fb342d1dff8a
       valid_lft forever preferred_lft forever
    inet6 fe80::42:82ff:feeb:397/64 scope link
       valid_lft forever preferred_lft forever`
`249: br-d2acbf3650d9: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:0c:71:db:82 brd ff:ff:ff:ff:ff:ff
    inet 192.168.80.1/20 scope global br-d2acbf3650d9
       valid_lft forever preferred_lft forever
    inet6 fe80::42:cff:fe71:db82/64 scope link
       valid_lft forever preferred_lft forever` 

The following can also be handy:

* Concourse version: 3.9.2
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: dont know
* Browser (if applicable):
* Did this used to work? yes 3.8.2

**Comment by davidgarciaMontreal** [comment]
docker-compose.yml
`version: '2'
`services:`
`  concourse_worker:`
`    image: concourse/concourse:3.9.2`
`    privileged: true`
`    command: worker`
`    volumes: ["/keys/worker:/concourse-keys"]`
`    environment:`
`      CONCOURSE_TSA_HOST: nodex2319`
`      CONCOURSE_GARDEN_DNS_SERVER: 142.133.x.x`
`      HOST_HOSTNAME: nodex2321`
`      HOST_DOMAINNAME: xxx`
`      CONCOURSE_NAME: nodex2321`
`      # CONCOURSE_GARDEN_DESTROY_CONTAINERS_ON_STARTUP: "true"`
`      # CONCOURSE_GARDEN_MAX_CONTAINERS: 8`
`      #--garden-log-level=[debug|info|error|fatal] Minimum level of logs to see. (default: info) [$CONCOURSE_GARDEN_LOG_LEVEL]`
`      CONCOURSE_GARDEN_LOG_LEVEL: "info"`
`      CONCOURSE_GARDEN_CPU_QUOTA_PER_SHARE: 640000`
`    dns:`
`      - 142.133.x.x`
`      - 8.8.8.8`
`    cpu_quota: 760000`

**Comment by xtremerui** [comment]
closing stale issue.
