### ISSUE TITLE
Concourse Groups UI doesn't have a scroll bar

### ISSUE THREAD

**Issue by StevenArmstrong** [concourse/concourse#2156]
Hi concourse team

## What challenge are you facing?

Ran into this issue recently when creating a pipeline for an application, we group by environment, so users can see every single environment individually as many teams deploy this common component. A particular application has over 20 environments so this means not all the group content can be rendered on the screen at the same.
For example:

groups:
- name: (qa1)
  jobs: [deploy_qa1]

- name: (qa2)
  jobs: [deploy_qa2]

...
etc

## A Modest Proposal

Could we have a scroll bar on the pipeline view group tabs so if the number of tabs is greater than the screen size we can scroll along. This will allow concourse to support a large number of groups on the 1 pipeline so users can scroll across to the group they need.

![image](https://user-images.githubusercontent.com/5717694/38769160-3a840b16-3ff6-11e8-8186-e122a26df5aa.png)

* Concourse version: 3.9
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: IaaS
* Browser (if applicable): Chrome, Firefox etc
* Did this used to work? No

**Comment by jama-pivotal** [comment]
@StevenArmstrong thanks for suggestion! We actually have a similar proposal to fix the bad rendering of the groups bar here: https://github.com/concourse/concourse/issues/2130  

IMO that design would scale better for long group names and lots of pipelines. Let me know what you think!

**Comment by jama-pivotal** [comment]
Closing in favor of implementing #2130
