### ISSUE TITLE
Backend error, permission denied?

### ISSUE THREAD

**Issue by acarrigan-pivotal** [concourse/concourse#2161]
Attempting to push small application utilizing Concourse pipeline and receiving error message in CLI on Mac: 

hijack: backend error: exit status: 500, 
message: runc exec: exit status 1: exec failed
container_linux.go: 295: starting container process caused 'git-repo/ci/tasks/build.sh' 
**permission denied**

Having trouble diagnosing which permissions need to be adjusted (git permissions, local permissions, ssh-key, concourse-pipeline?...) 

This is my first time using Concourse and pushing an app to Pivotal Cloud Foundry. 
Concourse 3.6.0

**Comment by vito** [comment]
Make sure your `build.sh` has executable permissions (`chmod +x`).

I don't think this is a Concourse bug, so I'm gonna close it, but feel free to ask for help in Discord or our forums: https://discuss.concourse-ci.org

**Comment by guangliang0209** [comment]
try this git command in your git bash, update the scripts's permission since it's a shell script
`git update-index --chmod=-x path/to/file`

**Comment by ag143** [comment]
Hi,

im trying to execute below concourse file .yml in windows docker

---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
  - name: task-scripts

run:
  path: ./task-scripts/task_show_uname.sh

....
but getting similar error 

ERROR:
Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:346: starting container process caused \"exec: \\\"./task-scripts/task_show_uname.sh\\\": permission denied\"","Handle":"","ProcessID":"","Binary":""}

errored

Does your git update command applicable in windows as well?

**Comment by adamulacha** [comment]
`git update-index` fix doesn't work on Windows (even in git bash).
To workaround this issue you may define your task this way:
```
run:
  path: /bin/sh
  args: ["./script.sh"]
```

instead of this way:
```
run:
  path: ./script.sh
```

**Comment by OphyTe** [comment]
Hi @adamulacha, I really thought that it would work but it didn't ... :-(

And @thatklausfeng, how do you do when you're not in a git repo ?
> try this git command in your git bash, update the scripts's permission since it's a shell script
> `git update-index --chmod=+x path/to/file`

**Comment by RahimTS** [comment]
> `git update-index` fix doesn't work on Windows (even in git bash).
> To workaround this issue you may define your task this way:
> 
> ```
> run:
>   path: /bin/sh
>   args: ["./script.sh"]
> ```
> 
> instead of this way:
> 
> ```
> run:
>   path: ./script.sh
> ```





This didn't work for me.
