### ISSUE TITLE
Concourse web binaries don't run the migration commands

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#2163]
The ATC has a couple utility migration commands. Currently these aren't available in the `concourse web` binary. They probably should be.

**Comment by stewartlord** [comment]
Yes please :+1:

**Comment by vito** [comment]
This is still super janky because it requires additional flags and starts the TSA on the side:

```
~/w/c/s/g/c/bin (master) $ concourse web --current-db-version 
the required flags `--tsa-authorized-keys' and `--tsa-host-key' were not specified
~/w/c/s/g/c/bin (master) $ concourse web --current-db-version --tsa-authorized-keys ~/.ssh/id_rsa_vito.pub --tsa-host-key  ~/.ssh/id_rsa_vito
{"timestamp":"1524667865.287822962","source":"tsa","message":"tsa.listening","log_level":1,"data":{}}
Exit trace for group:
atc exited with error: pq: password authentication failed for user "alex"
tsa exited with nil
```

We should figure out how to arrange this properly so that the migration stuff is its own command or something instead. Gonna accept anyway since at least it can run now.
