### ISSUE TITLE
3.11.0 web/atc memory growth

### ISSUE THREAD

**Issue by billimek** [concourse/concourse#2165]
# Bug Report

* Concourse version: 3.11.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: ubuntu VM
* Browser (if applicable): Chrome?
* Did this used to work? Yes

Beginning with concourse v3.11.0 we observe an almost linear rate of memory growth in the concourse-web container.

Below is a grafana graph showing the host-level metrics over ~24h period:
![](https://i.imgur.com/bpgUvj3.png)

Below is a netdata graph of the host showing the concourse-web container and associated memory growth over ~1hr period:
![](https://cdn.discordapp.com/attachments/413770960089382922/435822481224499202/unknown.png)

Got access to the host in question, and this is what glances shows to confirm the narrative of the web growth story:
![](https://i.imgur.com/uqBgFqI.png)

It may be related to the fact that we have dashboards running on monitors showing the pipeline continually.  When looking at a different installation not running a continuous dashboard/monitor, the same type of memory growth is not observed.

Raising this issue because two other people in discord mentioned seeing the same thing or something similar.

**Comment by stewartlord** [comment]
Thanks for logging this @billimek. We are seeing the same problem in our installation after upgrading to 3.11.0. We do *not* run a continuous dashboard/monitor. I don't think that is related FWIW.

**Comment by vito** [comment]
Looks like we're seeing this too, on Wings: https://snapshot.raintank.io/dashboard/snapshot/K2hZgd0u0PO740SasOKWqYFrVUtAeKeT?panelId=12&fullscreen&orgId=2

Hopefully that makes it easier to debug.

**Comment by pivotal-jwinters** [comment]
@billimek @stewartlord @markstokan what versions were you running before the upgrade?

**Comment by jmelchio** [comment]
Adding more logs to reaper server in worker as this is one of fairly big change from last release.

**Comment by markstokan** [comment]
CF Toolsmiths upgraded to 3.11.0 from v3.9.2

**Comment by billimek** [comment]
We observed this when upgrading from 3.10 to 3.11

**Comment by stewartlord** [comment]
Upgraded from 3.9.2 -> 3.11.0

**Comment by jmelchio** [comment]
- [ ] Add debug server to worker 
- [ ] Add debug server to tsa 
- [ ] Add debug server to baggageclaim

**Comment by iswix-llc** [comment]
I am part of the *we* that billimek speaks of.  It wasn't really an upgrade...  it was spin up a new 3.11.0 instance of concourse to replace a 3.10.0 instance.

**Comment by vito** [comment]
@iswix-llc Not all issues affect everyone. Our instance for example was stable even with the memory leak, as it was very gradual. We have a fix ready to ship, but that doesn't change the fact that 3.11 is still the latest version until we ship it, and has things that other people still want.

**Comment by YorickH** [comment]
@vito Is there an ETA on when you'll ship the new version containing the fix?

**Comment by vito** [comment]
@YorickH Some time this week.
