### ISSUE TITLE
3.8.0+ BOSH error "Handle 'xx' already in use"

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2172]
# Bug Report

* Concourse version: 3.8.0/3.9.2/3.11.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
* Did this used to work? We do not see this in binary environments

When a build takes a while, usually because the docker image needs to be downloaded, we frequently find that we run into the following error
```
Successfully pulled docker.fmr.com/fmr-ap121865/ops@sha256:71dc1397b07a95e1bd93d99be8bf8995464ff6b80a0c2be4bbd2697ef90b5981.
	
running touch test-file/test-20180420084434Z
Handle '6e8b8102-8087-4ceb-67ff-2a53d971bfc0' already in use
errored
```

Re-running the job most likely does not experience this issue

**Comment by scottietremendous** [comment]
@vito - I see that there's a commit here, can we consider this closed?

**Comment by keithkroeger** [comment]
Also exists in 3.13

**Comment by KernelDev** [comment]
We are having the same issue in all of our production environments. Restarting the task seems to fix it. Could you look into this with higher prio?

**Comment by xtremerui** [comment]
closing stale issue.
