### ISSUE TITLE
Login redirect from a resource page goes back to "job" URL that doesn't exist

### ISSUE THREAD

**Issue by dsharp-pivotal** [concourse/concourse#2176]
If I'm on a resource page `https://example.com/teams/main/pipelines/<pipeline>/resources/<resource>` and clicking something (like turning off a resource version) redirects to login, after logging in, the redirect goes to `https://example.com/teams/main/pipelines/<pipeline>/jobs/<resource>?` instead of back to the resource page.

This can be reproduced by logging out in a different tab.

* Concourse version: 3.9.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work?: not sure.

**Comment by mhuangpivotal** [comment]
@dsharp-pivotal We couldn't repro the issue, but we did find a bug that would've resulted in the behaviour you described. The fix should be in the next release (after v3.11.0).

**Comment by dsharp-pivotal** [comment]
@mhuangpivotal Cool, thanks.

I'm surprised you couldn't repro. Here's some more details in case you want to try again:

1. Log in (via GitHub)
1. Navigate to a resource on a pipeline that requires login.
1. In a second tab, log out
1. When you click back to the resource tab page, it will redirect to login. (I noted that the `redirect` url parameter has the correct "resources" URL)
1. Click "login with GitHub"
1. 404 (b/c it has "jobs" instead of "resources" in the URL)

**Comment by dsharp-pivotal** [comment]
Yup, one of our deployments got upgraded to v3.12.0 today, and I can't reproduce it there. Thanks again!
