### ISSUE TITLE
Builds hang because secrets are unavailable

### ISSUE THREAD

**Issue by azuretek** [concourse/concourse#2179]
# Bug Report

* Concourse version: 3.10.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Kubernetes

Sometimes when my kubernetes cluster is flaky my builds fail because it can't pull the secrets from the k8s API. The kubernetes API may become unreachable for lots of reasons but usually it is only temporary so ideally when faced with that situation concourse should fail fast and retry.

```
Finding variable 'username': Get https://100.64.0.1:443/api/v1/namespaces/concourse-devs/secrets/some-pipeline.username: read tcp 100.96.55.56:45248->100.64.0.1:443: read: connection timed out
```

I think the place to add the retry would be somewhere around here:
https://github.com/concourse/atc/blob/5e111aab5cfd6041719a43f4a720a5f4d239d01c/creds/kubernetes/kubernetes.go#L71

**Comment by cirocosta** [comment]
Hey @azuretek ,

I'm not entirely sure, but it looks like the feature got implemented here (https://github.com/concourse/concourse/pull/2717) in a way that k8s secrets probably got covered as well.

Could you please confirm if that solves the case you mentioned?

Thanks!

**Comment by azuretek** [comment]
We ended up switching to the vault backend as it made more sense for us, but that PR does seem like it should fix the issue. I'll close this issue for now since it seems likely to be fixed.
