### ISSUE TITLE
'base resource type not found' error when there are no workers

### ISSUE THREAD

**Issue by billimek** [concourse/concourse#2181]
Not sure if this should be a feature request or a bug report:

It appears that if there are no registered workers (i.e. `fly workers` doesn't show anything), the web UI is showing that resources are failing with `base resource type not found` after someone loads a pipeline.  Most users will not know that this is supposed to mean that they don't haver any workers.

It seems better to give a meaningful error message indicating that there are no workers.

**Comment by timrchavez** [comment]
I believe the error message did use to be "No workers" or something. Maybe this is a different code path or a regression perhaps?

**Comment by eedwards-sk** [comment]
I'm getting this on 5.2.0

**Comment by Savemech** [comment]
![image](https://user-images.githubusercontent.com/8943498/72917678-52452880-3d55-11ea-8262-9185d1e891a3.png)
getting this on 5.8.0

**Comment by mvdkleijn** [comment]
I concur. Getting the no base resource type git error when no workers are loaded. Confused the hell out of me at first. :)

**Comment by xtremerui** [comment]
closing stale issue.
