### ISSUE TITLE
'Parametrized' continuous deployment patterns/best-practice

### ISSUE THREAD

**Issue by pfijalki** [concourse/concourse#2183]
Hi there!

What challenge do I face:

I'd like to create a pipeline where I'd like to trigger deployment on env ENV{X,Y,Z} specific versions of app (not only latest successful). Thus 'parametrized' mean that version of app would be kind of parameter to the job

Solution proposals:
Having considered this challenge I think about two possible solutions

1. Use git as a event-source-like storage for deployment information, and store there 
'deployment manifests', i.e.
   *  demo-env.yml would look like and would be versioned in git
```yaml
versions: 
    backend: 1.0.4
    frontend: 1.0.1
```
  * this git repo would be an input resource for deployment job
 * deployment job on each new version (modified deployment manifesto) would run deployment according to data provided in manifesto
* rollback scenario would involve pushing rollback commit on the repo

2. Second approach is very similar but assumes usage of DB with event sourcing instead of git. This would also mean creating additional resource to emit notification about new versions

In both versions our team would like to provide simple gui for deployment process 

Do you think this is a correct approach to continuous delivery with concourse ? Or maybe you have an existing real-life scenarios or best-practice how to tackle this challange ? Would appreciate all your help and suggestions.

**Comment by marco-m** [comment]
Hello @pfijalki, I suggest to move your question to https://discuss.concourse-ci.org/ and close this ticket. The forum is a better venue for this kind of questions and you will have more answers I think. (Disclaimer: I am not a member of the Concourse team).

**Comment by pfijalki** [comment]
thank you @marco-m  :-) just moved
