### ISSUE TITLE
Add some system's resource management documentation

### ISSUE THREAD

**Issue by kalfa** [concourse/concourse#2184]
# Feature Request

It would be nice to have some documentation about system resource management with atc and workers.

I'm sure this issue is mainly due to my ignorance about concourse, garden and all the other components, but I think that this is an issue also for many other users, who really like the neatness of concourse but don't know how to deal with similar issues (mainly system resoruces tweaking).

I'm particularely interested in deploying concourse to AWS (and other cloud providers)
I do not mean how to deploy, but what kind of resources (e.g instance type, volume size, etc) do a deployment need, maybe with some use cases.

So my questions I'd like to see documented are (as a typical user who would like to use it but is slowed down by similar issues), based on common use cases (which can be discussed, but for sake of info I showed one below)

- What's the best practice in managing resources? (garden/baggaclaim params etc)
- What's the best practice in deploying to AWS? (instance types, volumes, etc)

- What should I look at to manage resoruces in a decent way?
  - I see garden's max-containers, how does it work? I cannot find anything about it's semantic.
    - does it queue resource in need of a container until a "slot" is available?
    - does it just not work is a deployment needs 55 containers and I set it to 54?
    - what are the useful scenarios I can use it and what are the pitfalls/side effects?
  - what does it mean and how to recover from a "unknown handle X"?

## What challenge are you facing?

We are deploying concourse to AWS. For the records, we are using terraform and puppet, but that's a detail and not part of this issue.

At the moment we have a single instance with 1 atc and 1 worker.

Every day about we are having problems of some sorts with resource utilization which leads inevitably to "unknown handle X" for every resource.

Initially we were using a t2.micro, then we moved to a t2.small and we might move to t2.medium (or equivalent).
At the time we had two pipelines:
1. builds a docker image from git and stores it to AWS ECR. Does some compilation, yum-install and pip-install, to obtain a base environment against which builds and test can run
1. builds a python package from git and stores it to a private pypi instance (plus to s3 for minor artefacts)

the former is quite resoruce intensive (on a t2.small) and seeems to be the cause of our problems.

the latter: 
- uses containers built by the former.
- is composed by 3 jobs each having a couple of get:git (passed or not), one or two tasks and some s3:put to store artifacts
- tasks use pipenv which installs several packages as indirect deps, takes lots of time (but that's not a problem)

Then we introduces 5 more pipelines identical to the latter (python's) one.

This seems (didn't expect anything else!) to have increased the number of containers and thereof the load of the machine.

Usually the load is fine until the docker-image pipeline starts, which drags everything down.
Just now it happened that the load was so high (80-100) that the git resoruces (via HTTPS) started having problems with the SSL handshake, failng obtaining new versions.
In the past "unknown handle X" from wich I couldn't (didn't know how to) recover - with the exception of one case - and had to redeploy.

**Comment by marco-m** [comment]
A t2.small is often small, it is too risky (I can say since I have the same deployment: Concourse binary on AWS with Terraform, Packer and SaltStack) :-) Did you check https://concourse-ci.org/operation.html ? It gives some hints about sizing.

I suggest to bring this kind of questions to the forum, https://discuss.concourse-ci.org/, which is better adapted than a github ticket. (Disclaimer: I am not a member of the Concourse team)
