### ISSUE TITLE
Build reaper broken in 3.12.0

### ISSUE THREAD

**Issue by aeijdenberg** [concourse/concourse#2187]
Commit <https://github.com/concourse/atc/commit/553d292f58e6807210c52cab7a16f30d4c107254> refactored the `build-reaper` into a separate `build-log-collector` but omitted to update the name in the call to `constructMembers()` and consequently the `build-reaper` is never invoked.

Fixed by PR <https://github.com/concourse/atc/pull/272>.

**Comment by databus23** [comment]
This can be closed now, right?

**Comment by jama-pivotal** [comment]
That's right @databus23 , thanks!
