### ISSUE TITLE
A cached version of a resource can only be invalidated by recreating all workers

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#219]
Use Case:
I'm trying to override a file on S3 that fetched with a regex (same filename, new bits). Even it I rename the resource (e.g. my-s3-resource-temp) the worker seems to be using the old cached version.

Workaround:
Recreate all workers to ensure the cached version is purged, obviously not great.

**Comment by vito** [comment]
This isn't likely to be improved any time soon. Concourse is strongly built around the mindset that resource versions are immutable; if the bits of a version change willy nilly there's not a lot of elegance to expect from the rest of the system.
