### ISSUE TITLE
fly execute env -> param mapping difficult to discover in documentation

### ISSUE THREAD

**Issue by Fitzoh** [concourse/concourse#2190]
# Feature Request

## What challenge are you facing?

I wanted to execute a one-off task using `fly` with custom `params`.  The docs explain how to do this in [4.2.1.1.4](https://concourse-ci.org/running-tasks.html#fly-execute).  That information took me a while to discover.

The first place I looked was `fly execute -h` which made no mention of input params.

The next place I looked was the [fly CLI docs](https://concourse-ci.org/fly.html) which has no mention of `fly execute`

## A Modest Proposal

Document how environment variables propagate to `fly execute` `params` in the `fly execute` help page.

Add a link to  https://concourse-ci.org/running-tasks.html#fly-execute from the main [fly documentation page](https://concourse-ci.org/fly.html)

**Comment by jama-pivotal** [comment]
Thanks for the suggestion @Fitzoh ! I'll take this on, since its one of the few issues I can probably tackle. For future reference you can submit website and docs related issues directly to the docs repository https://github.com/concourse/docs/issues

**Comment by Fitzoh** [comment]
good to know, thanks!

**Comment by jama-pivotal** [comment]
@Fitzoh  Upon further consideration, I'm not sure it makes sense to add a link to fly execute in the fly CLI section. Did you previously try looking through the entire index of docs under: https://concourse-ci.org/docs.html 

We made a decision to organize our docs to more action and outcome oriented approaches, so you'll notice that `fly` commands are sprinkled throughout the docs. In fact, now that I think about it more, section 4.1 The Fly CLI is more like "Getting Started with Fly" and we might need a way to lead you into another section

**Comment by Fitzoh** [comment]
Nope, had not tried looking at the index... For some reason my brain hadn't even registered that it was there.
Generally my behavior has been `click docs link` -> `scan submenu for thing I want`
![screen shot 2018-05-03 at 10 20 54 am](https://user-images.githubusercontent.com/131809/39582457-fdaa264c-4ebb-11e8-8576-d8ce7ec31130.png)

naturally the first place I looked was `fly`, which has a submenu containing a non-exhaustive fly commands

<img width="181" alt="screen shot 2018-05-03 at 10 28 12 am" src="https://user-images.githubusercontent.com/131809/39582810-be5b4880-4ebc-11e8-91c9-a2f5d273c304.png">

the action/outcome oriented approach definitely makes sense. It would be interesting to know if anyone else falls into the trap I did when looking for a reference on specific fly commands

**Comment by jama-pivotal** [comment]
You're definitely not alone in this! We wrote up an issue on the docs repo here https://github.com/concourse/docs/issues/58  that might be of interest to you

**Comment by jama-pivotal** [comment]
Closing issue for the purposes of shifting feedback to the docs issue mentioned above, and if there's other suggestions I'd like to push it to that repo instead

**Comment by Fitzoh** [comment]
```Document how environment variables propagate to fly execute params in the fly execute help page.```
Should I open a separate issue for mentioning env var propagation in `fly execute -h`?
