### ISSUE TITLE
UAA oAuth redirects to 127.0.0.1

### ISSUE THREAD

**Issue by hmlingesh** [concourse/concourse#2193]
Hello Team, 

still my concourse auth_url is redirecting to 127.0.0.1 even I have configured valid concourse endpoint for redirect .
when I fetch auth list for my team I am getting below this.

http://pipeline.dev.covisintrnd.com/auth/list_methods?team_name=covs-cf-team

[{"type":"oauth","display_name":"UAA","auth_url":"http://127.0.0.1:8080/auth/uaa?team_name=covs-cf-team"}]

Please, any idea how to replace 127.0.0.1 from actual concourse URL?

Regards
Lingesh M

**Comment by hmlingesh** [comment]
Thanks, Shashwathi, I have gone through the source code and realized we have to set CONCOURSE_EXTERNAL_URL to override 127.0.0.1. now concourse server is redirecting to our UAA login page. But now we are getting an error saying "verification failed".

Please, any idea which authorities we are missing from concourse client. Below are the details about concourse client in UAA.


scope: cloud_controller.read
  client_id: concourse
  resource_ids: none
  authorized_grant_types: refresh_token client_credentials authorization_code
  redirect_uri: http://pipeline.dev.covisintrnd.com/auth/uaa/callback
  autoapprove: 
  access_token_validity: 3600
  refresh_token_validity: 3600
  authorities: cloud_controller.admin
  name: concourse
  lastmodified: 1525353791000

**Comment by shashwathi** [comment]
@hmlingesh : https://concourse-ci.org/authentication.html#uaa-cf-auth
You need to also configure a team and provide CF details.

**Comment by hmlingesh** [comment]
Wow, Thanks, why this same setup is not working for the main team when I try to do the default setup for the concourse.

**Comment by shashwathi** [comment]
Default setup of concourse does not come up with uaa/cf providers. Use [this](https://github.com/concourse/concourse/blob/master/jobs/atc/spec#L210-L238) spec to define manifest properties in bosh setup

**Comment by hmlingesh** [comment]
Thanks a lot, shaswathi.
