### ISSUE TITLE
alternative to container resource

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#2197]
# Feature Request

## What challenge are you facing?

Currently the docker resource consumes a docker file and all the heavy lifting is done in the resource.
The docker approach also causes huge spikes in worker load for some reason and the resource itself is quite complex.
Another reason is that I think that Docker is not a good solution for containerization nor are Dockerfiles an adequate description of a container.

## A Modest Proposal

Use another tooling such `buildah` ( https://github.com/projectatomic/buildah ) to run a arbitrary command in the context and push the resulting image as container to a registry.
This would match the whole concourse pipeline idea of input / output way better.

This is something I've been thinking about for a while and would like to spark a discussion / feedback on what people's painpoints are (if any!).

**Comment by marco-m** [comment]
I cannot google anything useful for `ahbuild`. Could you please give some pointers ?

**Comment by vito** [comment]
Very similar discussion has been had in https://github.com/concourse/docker-image-resource/issues/190 - leading to a Kaniko task example
