### ISSUE TITLE
worker not working on ubunto 14

### ISSUE THREAD

**Issue by ezraroi** [concourse/concourse#2199]
# Bug Report

I am trying to run the concourse worker in the following way:
`
/infrastructure/concourse/concourse worker --baggageclaim-driver=btrfs --work-dir  /infrastructure/concourse/worker-state --tsa-host concourse-web.ger.corp.intel.com:2222 --http-proxy=proxy-chain.intel.com:911 --https-proxy=proxy-chain.intel.com:912 --no-proxy=10.109.80.95,127.0.0.1,localhost,.intel.com --tsa-public-key /infrastructure/concourse/keys/tsa_host_key.pub --tsa-worker-private-key /infrastructure/concourse/keys/worker_key 
`

I am seeing the following error:
`
{"timestamp":"1525704710.857030153","source":"guardian","message":"guardian.create.create-failed-cleaningup.cleanedup","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:348: starting container process caused \"
process_linux.go:402: container init caused \\\"rootfs_linux.go:46: preparing rootfs caused \\\\\\\"permission denied\\\\\\\"\\\"\"\n","handle":"1284f352-5f60-4d3c-69b6-3dfa26031b5c","session":"450.3"}}
`

The following can also be handy:

* Concourse version: 3.13.0
* Deployment type binary
* Infrastructure/IaaS: Linux concourse-w03 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Browser (if applicable):
* Did this used to work? no

**Comment by vito** [comment]
You may need to check that `/infrastructure/concourse/worker-state` is readable by other users, i.e. minimally chmodded as `0755` (that goes for `/infrastructure`, `/infrastructure/concourse`, and `/infrastructure/worker-state`).

Unprivileged containers run as non-root so they need to be able to see the path to their own filesystem.
