### ISSUE TITLE
Executing a `fly` command from terminal logs me out of concourse in my browser

### ISSUE THREAD

**Issue by johannasmith** [concourse/concourse#2201]
# Bug Report

When using the `fly` cli in addition to the concourse web UI:

* If I execute a `fly` command from terminal, it logs me out of concourse in my browser. 
I think using both simultaneously just invalidates the browser token. Does not seem to happen in the reverse order: I stay logged in on terminal and can continue to use `fly` without having to log in again. 

* Commonly occurs when: building/iterating on pipelines

* Concourse version: most, but recently confirmed on `3.11.0`
* Browser: Chrome
* Did this used to work? no

**Comment by xtremerui** [comment]
Could you provide the fly command you ran to cause the issue? Thx

**Comment by pnsantos** [comment]
I've noticed this too. With 3.13.0 if I log into a team with the web browser, then run a fly login (`fly -t <target> login`) for another team, the web browser session will switch to the team associated with the target used with fly.

This didn't use to happen with 3.11 or previous versions as far as I can remember.

We're using github auth btw.

**Comment by xtremerui** [comment]
@pivotal-jwinters does this ring a bell anywhere when skymarshal was introduced?

**Comment by xtremerui** [comment]
This will be fixed in #2418. Closing.
