### ISSUE TITLE
Stuck in screen when rendering

### ISSUE THREAD

**Issue by Eulerizeit** [concourse/concourse#2206]
# Bug Report

When you select a job that takes a long time to render you are trapped in the loading stage until it renders or you restart your browser. 

Ideally if I click on a stuck job and I realize that it is going to take forever to render I'd like to be able to click elsewhere on the application to get out of a never ending load screen. 

![image](https://user-images.githubusercontent.com/9668711/39760409-36820e22-52a3-11e8-93c5-ee999c3eff12.png)

The following can also be handy:

* Concourse version: 3.9.2
* Browser (if applicable): Firefox
* Did this used to work? The screens used to render better / faster before the timestamp addition, however, you have never been able to navigate off the page while rendering

**Comment by jama-pivotal** [comment]
Linking to #1543 , this should be "fixed" once we improve the performance of the Build page
