### ISSUE TITLE
Gitlab provider is broken

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#2207]
The golang/oauth2 library has a [list of external connectors](https://github.com/golang/oauth2/blob/master/internal/token.go#L93-L130) that require the `client_id`, `client_secret` to be sent as part of the body (instead of in a basic auth header) for all requests to the `token` endpoint. I'm not sure if something changed recently in gitlab, but it seems that our existing connector is broken, and adding `https://www.gitlab.com` to the list fixes it.  Since this is a core golang library, the timeline for a fix might be long.

I started a topic on the [golang-nuts forum](https://groups.google.com/forum/#!topic/golang-nuts/iYrYz8YZuPM) and filed and [issue with gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/46214)

**Comment by pivotal-jwinters** [comment]
So it seems I was able to scan over this file about a dozen times and miss the [most important lines](https://github.com/golang/oauth2/blob/master/internal/token.go#L142-L144) as it relates to this issue.

It's not pretty, but it seems like we can dynamically register our gitlab host in the provider implementation.

**Comment by xtremerui** [comment]
It seems oauth2 core applied another solution to this problem https://github.com/golang/oauth2/commit/80673b4a4bfc6c2c58a0b44cf9106913fe293994

Upon testing Gitlab auth is working fine for concourse 5.8. I will close this issue.
