### ISSUE TITLE
Setting --cli-artifacts-dir does not appear to be respected

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#2212]
# Bug Report

Howdy, in an attempt to keep things out of /tmp, I tried adding `--cli-artifacts-dir /var/local/lib/concourse/` as an argument to my binary Concourse deployment, but it seems to still be reading from /tmp/cli-artifacts anyway. I'm still on Concourse 3.9.1, but I don't think this bit of code changes much. I tried manually placing the fly binaries in /var/local/lib/concourse/ and /var/local/lib/concourse/cli-artifacts, in case this flag also disabled the directory creation, but no luck.

**Comment by hfinucane** [comment]
Yeah, I'm trying to avoid `tmpwatch`, `systemd-tmpfiles-clean`, etc.

**Comment by shashwathi** [comment]
@hfinucane : 

Path of tmp directory can be changed by setting environment variable `TMPDIR`. Golang should recognize this and create any further tmp dir under that path 

Ref docs: 
https://golang.org/src/os/file.go?s=9724:9745#L304
https://golang.org/pkg/os/#TempDir

**Comment by jama-pivotal** [comment]
@hfinucane looks like @shashwathi was able to help you out. Closing this issue, feel free to reopen if you feel like we've missed something
