### ISSUE TITLE
Add a health check API to verify Credential Manager(s) configured correctly

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2216]
Currently an operator doesn't have much insight into whether a credential manager has been successfully configured. We don't fail on initializing a connection to the manager in the ATC, as there may be cases where the cred manager's server component is not up yet, because... _**the cloud**_.

It would be nice to provide a way for users to query what credential managers are currently active and configured for a given Concourse deployment; with authentication details redacted. Ideally this should contain more information that just "there exists a valid set of configuration parameters for Vault", and give some more details about Concourse's ability to connect to Vault using that config. 

A couple things to consider:
- Should the credential manager interface include a new method for establishing / testing a connection to the backing server to display the health of that connection? This would allow a more useful check of the health of the connection to the backing server.
- Do we want to limit this to just the admin "main" team? Are there cases where the operator who configures the cred manager and holds the keys to it wants that information hidden from teams on the cluster?
- Does this need to be supported as a `fly` command, or just an API?

**Comment by phyllisodwyer** [comment]
+1

**Comment by keithkroeger** [comment]
I like this as well.

To note, in the logs, the values not being found (in a working credential provider) or a credential provider not being reached result in the same error, Expected to find variables....

Can the logs potentially be more descriptive?

**Comment by pivotal-jwinters** [comment]
We've added a endpoint under `/info/creds` to list any credentials managers that have been configured. 

We haven't added any actual health checking but we did fix an issue where if vault was unreachable concourse would just hang forever anytime it had to resolve creds.

Hopefully those two solutions are good enough, so I'm just going to close this for now. Feel free to re-open it anyone wants to investigate some sort of actual health checking.

**Comment by keithkroeger** [comment]
Thank you, @vito
