### ISSUE TITLE
Trigger jobs with an OR/ANY behavior

### ISSUE THREAD

**Issue by cellofellow** [concourse/concourse#2217]
# Feature Request

## A job may need to run after any of its dependencies change, not only all.

I have a job that has dependencies (resources with "get" steps set to `trigger: true`) D, E, and F. If any 1 of these dependencies changes, the job should run. _i.e_ `D || E || F` triggers the job, not `D && E && F`.

## A Modest Proposal

Perhaps some configuration on the job like `trigger_any: [D, E, F]` would be doable. I'm unsure how this changes the internals.

**Comment by shashwathi** [comment]
@cellofellow 

If job has D,E,F resources and all them are set to `trigger: true`, then job will be triggered if new version is available for D or E or F.

**Comment by cellofellow** [comment]
Ok. It didn't appear so from documentation or from my own experience, but if so then thanks.

**Comment by alpha-er** [comment]
Do we have something for the opposite condition then, i.e. trigger on `D && E && F`?
