### ISSUE TITLE
Add fly command to land worker

### ISSUE THREAD

**Issue by lochlainnw** [concourse/concourse#2221]
# Feature Request
It would be nice to be able to fly land workers the same way that is possible for pruning.   Currently the process for landing requires with keys on the ATCs. 

Not a big one but it would be nice to have.

## A Modest Proposal

Fly land [workername]

* Concourse version: 3.8
* Deployment type (BOSH/Docker/binary): bosh and binary. This would be more useful for binary.
* Infrastructure/IaaS: openstack
* Did this used to work? No

**Comment by shashwathi** [comment]
Are you using `fly` to manage lifecycle of workers?

**Comment by lochlainnw** [comment]
Hi, we would use this in our binary environment.  If the container limits are reached, or a network blip occurred, we need to be able to bring the workers back up. This requires landing the workers to stop any running DB connections, then pruning and recycling to restart the app.  Pruning is a relatively easy task but landing takes a little more effort.

Regards,
Lochlainn

**Comment by shashwathi** [comment]
> If the container limits are reached

It could be an indicator that there is too much workload for workers or workers are not cleaning up fast enough. You could use GC flag for fine tuning. 

>  network blip occurred

This will stall the worker but it should be listed as running again soon. 

> Pruning is a relatively easy task but landing takes a little more effort.

True and that is how it is designed. Landing actually cleans up corresponding containers, volumes which takes sometime. Pruning expects the cleanup to be done already and it cleans up worker DB record. 
Irrespective of running this in fly or using binary, it is a bit time consuming action.

**Comment by lochlainnw** [comment]
As it takes more time, all the more reason to make this command easier to use. :)

**Comment by xtremerui** [comment]
changes are made in 2925a4a58a2308ec1c262d39ac288e59d2e36fb7
