### ISSUE TITLE
Question: Vanilla Resource Type

### ISSUE THREAD

**Issue by robtec** [concourse/concourse#2222]
Hi,

I'm trying to create a task file that does not need to download a Docker Image to work.

This would apply to `resource_type` also

```bash
---
platform: linux

image_resource:
  type: vanilla

run:
  path: echo
  args: "hi, i'm in a vanilla container :)"
```

The above example would be nice to have, `vanilla` would be a key word to tell concourse to spawn a vanilla linux rootfs, from a local `assets/` then do the echo.

Why?

We would like the option to use an out-of-the-box `rootfs` when we cannot rely on a network to download a docker image etc.

Is this possible?

**Comment by robtec** [comment]
Thanks for the link, interesting approach for sure and definitely an option.

I've been playing around with `rootfs_uri` in my task file VS `image_resource`

Have you ever played around with this?

**Comment by marco-m** [comment]
No I haven't. You may also want to ask these kind of questions on the Concourse forum https://discuss.concourse-ci.org/
