### ISSUE TITLE
AWS ELB `http: TLS handshake error from 10.10.224.184:31458: tls: no cipher suite supported by both client and server`

### ISSUE THREAD

**Issue by cunnie** [concourse/concourse#2223]
### Bug Report

* Concourse version: **3.13.0**
* Deployment type (BOSH/Docker/binary): **BOSH**
* Infrastructure/IaaS: **AWS**
* Browser (if applicable): n/a
* Did this used to work? Yes, in 3.9.2

#### AWS ELB cannot negotiate a common cipher with atc when communicating via HTTPS

The workaround is to **communicate via HTTP between the ELB and the atc**.

FYI, AWS ELB does not support the more modern cipher suites; negotiation to the back-end fails:

Wireshark output (from ELB to atc):
```
TLSv1.2 Record Layer: Handshake Protocol: Client Hello
    Content Type: Handshake (22)
    Version: TLS 1.0 (0x0301)
    Length: 143
    Handshake Protocol: Client Hello
        Handshake Type: Client Hello (1)
        Length: 139
        Version: TLS 1.2 (0x0303)
        Random: 99aca6427c30c2ef609181a4506e5631df821dbdc683217d...
        Session ID Length: 0
        Cipher Suites Length: 58
        Cipher Suites (29 suites)
            Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
            Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
            Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
            Cipher Suite: TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (0x0084)
            Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
            Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
            Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
            Cipher Suite: TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (0x0041)
            Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
            Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 (0x00a3)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x006b)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x006a)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x0038)
            Cipher Suite: TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA (0x0088)
            Cipher Suite: TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA (0x0087)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 (0x00a2)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x0067)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x0040)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x0032)
            Cipher Suite: TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA (0x0045)
            Cipher Suite: TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA (0x0044)
            Cipher Suite: TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (0x0016)
            Cipher Suite: TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x0013)
            Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
        Compression Methods Length: 1
        Compression Methods (1 method)
        Extensions Length: 40
        Extension: SessionTicket TLS (len=0)
        Extension: signature_algorithms (len=32)
```
There's **no overlap** with the restricted list of cipher suites introduced in Concourse 3.10.0. Here are the five allowed suites and their hex codes according to the [RFC 5289](https://tools.ietf.org/html/rfc5289#section-3.2):
```
     CipherSuite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384  = {0xC0,0x2C};
     CipherSuite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384    = {0xC0,0x30};
     CipherSuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256    = {0xC0,0x2F};
     CipherSuite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384    = {0xC0,0x28};
     CipherSuite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384  = {0xC0,0x24};
```
There's no overlap. In fact, AWS doesn't support any Galois Counter Mode-Based Cipher Suites.

**Comment by jama-pivotal** [comment]
I think it might have to do with the fact that we implemented this issue: #1997 , which restricted the allowed ciphers

**Comment by rohitkhera** [comment]
hi, we have a list of approved internal TLS ciphersuites, rather than point you to the internal standards doc, let me just select a few suitable ciphers suites from the above list, if none of these are mutaually supported by the TLS peers, then please get back to me and I may be able to give you some alernatives. Pls try the following, in order of preference (first one is best):

1. `TLS_DHE_RSA_WITH_AES_256_GCM_SHA384` (RSA KEY SIZE must be 3072bits, DH group ID should be MODP GROUP ids 15, 16, 17 and 18)

2.`TLS_DHE_RSA_WITH_AES_128_GCM_SHA256` (RSA KEY SIZE must be 3072bits, DH group ID should be MODP GROUP ids 15, 16, 17 and 18)

**Comment by cunnie** [comment]
Hi @jama-pivotal,

Would it be more expedient for us to submit a PR or would you prefer to add another TLS cipher suite or are you not considering adding additional suites? We (PWS, i.e. Pivotal Web Services) would like to offer our customers end-to-end encryption, but the inability of Concourse & ELB to negotiate a common cipher suite is a bit of a monkey wrench. Sure, there are workarounds — we could colocate an reverse-proxy nginx BOSH release, or deploy a custom version of the ATC — but we'd like it to work out of the box.

/cc @socalnick

**Comment by jama-pivotal** [comment]
@cunnie I personally wouldn't mind but I'm gonna tag @topherbullock and @vito on this for them to weigh in

**Comment by Freyert** [comment]
For anyone else looking into this: this is only an issue with the classic load balancer. It works fine with the HTTPS application load balancer.

**Comment by cunnie** [comment]
@jama-pivotal If an ALB works, then we don't need the cipher suite expanded (i.e. `atc` does not need to be modified)

**Comment by cunnie** [comment]
I'm closing this issue because there's a workaround.
