### ISSUE TITLE
pq: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by l-wang** [concourse/concourse#2224]
Hi there!

# Bug Report

This error intermittently happens during build execution but without anything pointing to the cause. When it occurs, the build errors. We have seen this in task and resources steps. I doesn't happen very often, and we have nothing to correlate when it happens. 

```
pq: current transaction is aborted, commands ignored until end of transaction block
```
This error message is printed in the build output log, if logs from other components are necessary, we just need to know which one to attach. This could be difficult because we can't reproduce the problem on demand. 

* Concourse version: 3.9.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Google Cloud Platform
* Browser (if applicable): N/A
* Did this used to work?: Sometimes

**Comment by p-manesh** [comment]
Got the same error message: pq: current transaction is aborted, commands ignored until end of transaction block

Concourse version: 3.9.2
Deployment type (BOSH/Docker/binary): BOSH
Infrastructure/IaaS: AWS

**Comment by benjefferies** [comment]
Same error with environments

Concourse version: 3.13.0
Deployment type (BOSH/Docker/binary): BOSH
Infrastructure/IaaS: AWS

**Comment by databus23** [comment]
Got this with 3.14.0 for three slack resource put steps simultaneously just now.

**Comment by talset** [comment]
duplicate issue : https://github.com/concourse/concourse/issues/2108

**Comment by vito** [comment]
Logs from the ATC and screenshots of the web UI would be really helpful for debugging this. The error is sort of a "secondary" error - we'll need to see why the transaction was aborted.

**Comment by benjefferies** [comment]
Logs from task in UI
```
[INFO] cf version 6.35.2+88a03e995.2018-03-15
Setting api endpoint to https://api.system.devtest.onsclofo.uk...
OK

api endpoint:   https://api
api version:    2.85.0
Not logged in. Use 'cf login' to log in.
API endpoint: https://api
Authenticating...
OK
Use 'cf target' to view or set your target org and space.
[INFO] Executing create-service: rm-pg-db
api endpoint:   https://api
api version:    2.85.0
user:           concourse
org:            rmras
space:          ci
Creating service instance rm-pg-db in org rmras / space ci as concourse...
OK
Service rm-pg-db already exists
[INFO] Waiting for service: rm-pg-db
[INFO] Service is ready: rm-pg-db

pq: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by JohannesRudolph** [comment]
This is buggering the hell out of our Concourse instance on 3.14.1 this week. Is there any fix in sight? 

I can offer this insight from our ATC logs https://gist.github.com/JohannesRudolph/9f4d3752f1e64e82139221796a332c9a

**Comment by ghostsquad** [comment]
I'm also seeing this problem

**Comment by timrchavez** [comment]
Just happened to me on 3.14.1

**Comment by NickGrantONS** [comment]
Regularly happening with 3.13.0

**Comment by IizunaK** [comment]
Happened today in Concourse v4.2.1, in an aggregate of several puts. One of them returns that after a success.

```	
Deployment in progress...
Deployment in progress...
FINISHED: SUCCESS!
	
pq: current transaction is aborted, commands ignored until end of transaction block
```

The problem seems to happen at the update of the metadata values at the end of our resource (assets/out). Don't know if it helps.

**Comment by talset** [comment]
Still happens randomly on `4.2.3`

**Comment by vito** [comment]
Still true (from https://github.com/concourse/concourse/issues/2224#issuecomment-408194085):

> Logs from the ATC and screenshots of the web UI would be really helpful for debugging this. The error is sort of a "secondary" error - we'll need to see why the transaction was aborted.

To get to the bottom of this we'll need to see all of the logs pertaining to the build, from the `web` node. Additionally logs from the the `db` node may help; hopefully it logged the query that caused the transaction to fail.

**Comment by talset** [comment]
Could we re-open this issue ?

I just had this random `pq: current transaction is aborted, commands ignored until end of transaction block` again on my `4.2.3` concourse.

Here is the web/atc logs during the issue

```
{"timestamp":"1570547304.351601362","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.244.0.0:46228","session":"2059312","type":"keepalive"}}
{"timestamp":"1570547305.126325846","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.244.0.0:40688","session":"2714131","type":"keepalive"}}
{"timestamp":"1570547305.548127651","source":"atc","message":"atc.syncer.customer-staging:scheduler.tick.scheduling.try-start-next-pending-build.failed-to-save-output","log_level":2,"data":{"build-id":18853,"build-name":"73","error":"pq: current transaction is aborted, commands ignored until end of transaction block","session":"20.62.238097.3.12"}}
{"timestamp":"1570547305.548168898","source":"atc","message":"atc.syncer.customer-staging:scheduler.tick.scheduling.try-start-next-pending-build.errored","log_level":1,"data":{"build-id":18853,"build-name":"73","error":"pq: current transaction is aborted, commands ignored until end of transaction block","session":"20.62.238097.3.12"}}
{"timestamp":"1570547305.551226139","source":"atc","message":"atc.syncer.customer-staging:scheduler.tick.scheduling.try-start-next-pending-build.finished","log_level":1,"data":{"build-id":18852,"build-name":"71","exit-status":0,"session":"20.62.238097.3.11","version-info":{"Version":{"timestamp":"1570547303"},"Metadata":null}}}
{"timestamp":"1570547305.578049898","source":"atc","message":"atc.syncer.customer-staging:scheduler.tick.scheduling.try-start-next-pending-build.finish.errored","log_level":1,"data":{"build-id":18853,"build-name":"73","error":"pq: current transaction is aborted, commands ignored until end of transaction block","session":"20.62.238097.3.12.43"}}
{"timestamp":"1570547306.340940237","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.3.5.70:23462","session":"2715357","type":"keepalive"}}
{"timestamp":"1570547306.550357342","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.3.5.70:55992","session":"2709803","type":"keepalive"}}
```

**Comment by vito** [comment]
@talset That version's pretty old; does it still happen in v5.6?

**Comment by talset** [comment]
> @talset That version's pretty old; does it still happen in v5.6?

We plan to upgrade in 5.x soon. I will let you know

**Comment by vito** [comment]
Dang no-response bot, calm down. (I need to remove the label.)
