### ISSUE TITLE
Setting the Time Zone

### ISSUE THREAD

**Issue by rs017991** [concourse/concourse#2226]
# Feature Request

## What challenge are you facing?

Times throughout concourse (in tooltips/logs/etc) are not labeled with a time zone, and seem to be some mixture of local times of the client/server.

We'd really just like to be able to set it all to UTC so that there is no ambiguity when working on global solutions.

**Comment by jama-pivotal** [comment]
Hm, interesting. If we pick this up, I wonder if its easier to attach the TZ to the output. Could make for an interesting `design-snack`

**Comment by pivotal-jamie-klassen** [comment]
For the moment, the API is rendering Unix timestamps (milliseconds since epoch *in UTC*). So we just need to fetch the timezone the browser is in when rendering.
