### ISSUE TITLE
Duplicate alias (st) documented in fly command help output

### ISSUE THREAD

**Issue by donkeybanana** [concourse/concourse#2229]
`fly` cli reports both `set-team` and `status` as being aliased as `st`:

```
❯ fly | grep 'aliases: st'
  set-team           Create or modify a team to have the given credentials (aliases: st)
  status             Login status (aliases: st)
```

Executing the alias `st` shows the alias actually refers to `set-team`
```
❯ fly st
error: the required flag `-n, --team-name' was not specified

❯ fly set-team
error: the required flag `-n, --team-name' was not specified
```

### Expected behaviour

I would expect checking login status would take precedence over `set-team`, given it requires fewer flags (namely `-t`), though that is not the case:

```
❯ fly -t ci st
error: the required flag `-n, --team-name' was not specified
```

### `fly` version

```
❯ fly --version
3.13.0
```

### User Satisfaction Level

```
[=====================] 100%
```
Keep up the good work!

**Comment by jama-pivotal** [comment]
Thanks for submitting an issue @donkeybanana ! I think we simply forgot that `st` was already used up by `set-team` at the top level alias. I think we should probably just use a new alias for status... `sa`?
