### ISSUE TITLE
Dev - Jamie Klassen

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#2231]
## Mailing Lists

- [x] concourse at pivotal.io
- [x] wing_alert at pivotal.io

## Calendars

- [x] Concourse
- [x] Concourse OOO

## Accounts

- [x] Github
- [x] LastPass
- [x] Discord
- [x] Discourse
- [x] PagerDuty
- [x] Pilots

## Github access

- [x] concourse/Pivotal team
- [x] pivotal-cf/concourse-wings

## LastPass access

- [x] Shared-Concourse

## GCP Project owner access

- [x] cf-concourse-production

## Slack Channels

- [x] Pivotal#concourse-wings

## Dev Setup

- [x] .git-authors

## SSH Keys

- [x] Get USB thumb drive
- [x] [Reformat as encrypted drive][encrypted-drive]
- [x] Create SSH key pair and add to Github account

## Readings

- [x] bit.ly/concourse-wiki

## Checklist

- [x] Update the [template](/concourse/concourse/wiki/Developer-Onboarding-Checklist) with improvements made

[slack]: https://concourseci.slack.com
[encrypted-drive]: https://github.com/pivotal-legacy/usb-login-scripts
[pagerduty]: https://cfoundry.pagerduty.com
[pilots]: http://pilots.cfapps.io

**Comment by shashwathi** [comment]
Welcome Jamie

**Comment by pivotal-jamie-klassen** [comment]
thanks!
