### ISSUE TITLE
resource type not found : git

### ISSUE THREAD

**Issue by chandrusatheesh** [concourse/concourse#2234]
Hi there!

I am setting up a concourse pipeline and its throwing error. Please find the details below,

* Concourse version: 3.13.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Azure
* Browser (if applicable):Chrome
* Did this used to work?First time trying

Additional notes : concourse web, concourse worker running in same ubuntu VM. Please find the ubuntu version
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

![image](https://user-images.githubusercontent.com/7940791/40432293-fcf7e228-5ec6-11e8-8027-617423aa1eb9.png)

Please check and help me in this regard,

Regards,
Satheesh

**Comment by shashwathi** [comment]
@chandrusatheesh : 

Can you list workers ? (Run `fly -t target workers`) There should be atleast one running worker.

**Comment by chandrusatheesh** [comment]
@shashwathi 

I am unable to find worker list. 

![image](https://user-images.githubusercontent.com/7940791/40466008-3e1f424e-5f41-11e8-8267-992b174894f3.png)

Concourse Installation problem ??

**Comment by chandrusatheesh** [comment]
@shashwathi 

I have created another concourse VM. And now i could able to see the worker list.

![image](https://user-images.githubusercontent.com/7940791/40480121-263b3e56-5f6b-11e8-8f94-1403453af6ac.png)

I set the pipeline and getting new error, Any Ideas on this. 

Please find below,

![image](https://user-images.githubusercontent.com/7940791/40480171-47ac66d2-5f6b-11e8-878f-3b7ceccc0d26.png)
