### ISSUE TITLE
Tab crashes on Chrome beta, unable to access web

### ISSUE THREAD

**Issue by Rukenshia** [concourse/concourse#2236]
# Bug Report

I've just upgraded our concourse to 3.13.0 but I cannot view the web at all anymore. After shortly seeing the UI build up, I can get the lovely "Aw, Snap" page: 
![image](https://user-images.githubusercontent.com/1899599/40467410-238de6b8-5f2a-11e8-8686-a71818c59ce9.png)

The following can also be handy:

* Concourse version: 3.13.0
* Deployment type (BOSH/Docker/binary): BOSH
* IaaS: Runs on AWS, ELB is configured with SSL Listener (443 -> 8080)
* Browser (if applicable):

Google Chrome | 67.0.3396.56 (Official Build) beta (64-bit)
-- | --
Revision | eff3e3f46cf53019f8f43c3d4678e87fa7086fb8-refs/branch-heads/3396@{#682}
OS | Mac OS X
JavaScript | V8 6.7.288.42
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.56 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --top-chrome-md=material-refresh --enable-features=SecondaryUiMd --flag-switches-end

* Did this used to work? Yup

**Comment by Rukenshia** [comment]
Turns out all I have to do is completely wipe the cache from the Settings menu. Not sure why, but that solves it.

**Comment by Rukenshia** [comment]
Was a bit too quick there. As soon as I log in, the issue resurfaces.

**Comment by Rukenshia** [comment]
@jama-pivotal any page after I logged in, there's no logs visible in the Developer Console before the crash.

**Comment by Rukenshia** [comment]
It seems like this happens as soon as I directly navigate to a page that renders a pipeline, just going to https://ci.concourse-ci.org/ also crashes the tab on the latest Chrome beta version.

**Comment by williamdenton** [comment]
Anecdotally, I seem to be able to render a pipeline so long as its not currently executing.

**Comment by williamdenton** [comment]
Installed chrome stable 67.0.3396.62  and its working fine now. Same version numbers... weird.

**Comment by nexus49** [comment]
I'm also seeing this problem, Mac Chrome (67.0.3396.62) Concourse (3.13.0)

**Comment by jfmyers9** [comment]
I would like to mention that I am also seeing this issue on Concourse (3.13.1) and `Version 67.0.3396.62 (Official Build) Arch Linux (64-bit)` of Chromium which is not a beta version.

There does not seem to be a work around for this at the moment.

**Comment by iswix-llc** [comment]
I have 1 of 50 pipelines that does this.  If a job is running everything is fine.  If no job is running  Chrome crashes.

Google Chrome is up to date
Version 67.0.3396.62 (Official Build) (64-bit)

**Comment by CamiloGarciaLaRotta** [comment]
Today I encountered the same issue with Google Chrome versión `67.0.3396.62`.  
I was able to work all day with a problem with Firefox.

**Comment by mhuangpivotal** [comment]
Hi all, we have identified the offending CSS that's broken in Google Chrome 67 (likely a Chrome bug). We will most likely ship a new release next week that will fix the issue. In the meantime, the dev/canary versions of Google Chrome should work, as well as other browsers like Firefox and Safari.

**Comment by jama-pivotal** [comment]
@mhuangpivotal pushed a fix that removes two lines of CSS  that predominately causes the crash. It doesn't do anything valuable anyways so things should be less crashy now

**Comment by topherbullock** [comment]
Here's the revert commit for this: 
https://github.com/concourse/web/commit/aacb05973b4b42e7f065b522d5851fede84fbc15
