### ISSUE TITLE
Feature request: Expose pipeline to other teams (but not unauthenticated users)

### ISSUE THREAD

**Issue by itsdalmo** [concourse/concourse#2237]
# Feature Request

## What challenge are you facing?

I want teams to be able to see each others pipelines (and/or build logs) *without* making the publicly available. Right now this is not possible.

## A Modest Proposal

I can only see two solutions:
- Read-only members in teams.
- Change both [`expose-pipeline`](https://concourse-ci.org/managing-pipelines.html#fly-expose-pipeline) and the [`public`](https://concourse-ci.org/jobs.html#job-public) flag so we can set accessibility to one of `team` (default), `authenticated` (members of any team) or `all` (anyone).

Either solution would fix the problem. I'd be happy to submit a PR if I got some guidance :)

**Comment by xtremerui** [comment]
Should be done by [RBAC](https://concourse-ci.org/user-roles.html#configuring-rbac) feature.
