### ISSUE TITLE
Dashboard: visual indicator on the dashboard when resources that are in an error state

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2239]
## Users would like a visual indicator that a resource is in an error state

Erroring resources are orange in the pipeline view and this is currently not being surfaced or indicated in the dashboard view. 

"We just realized that one of our pipelines has resources that have been missing for a long time, but we didn't notice because it was showing up as all green in the dashboard." @andrewedstrom

## A Modest Proposal

We propose a small corner flag to be added to the pipeline card to indicate on the dashboard level there is an errored resource(s) on a pipeline. The pipeline remains the same if all resources are functioning as normal.

![screen shot 2018-05-25 at 12 37 56 pm](https://user-images.githubusercontent.com/27746614/40555872-83a8d9ce-6018-11e8-9638-1a61d1ab6685.png)

Error Orange:#F5A623
Asset: [resource_fail _ic.svg.zip](https://github.com/concourse/concourse/files/2040103/resource_fail._ic.svg.zip)

**Comment by marco-m** [comment]
Very good idea!

**Comment by jama-pivotal** [comment]
Icon is intentionally missing in our first implementation! CSS is hard

**Comment by andrewedstrom** [comment]
hot
