### ISSUE TITLE
Storage stats per pipeline

### ISSUE THREAD

**Issue by mkb** [concourse/concourse#224]
[Per @vito and @jim80net I am creating issues for several requests from the CloudOps team.]

We would like a way to know when the build logs for a particular pipeline get too big and we need to trim them down.

**Comment by vito** [comment]
This seems like a lot of work for not much gain vs. just looking at db metrics, or work we should be doing on other features to prevent this from being an issue. Not likely for us to do this any time soon to be honest. Sorry!
