### ISSUE TITLE
Breadcrumbs/team name overflows with a narrow viewport

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#2241]
# Bug Report

When the browser window is narrow or the team/pipeline/job names are long, the text overflows out of the top bar, and blocks other elements such as the trigger build button:

<img width="576" alt="screen shot 2018-05-28 at 10 02 33 am" src="https://user-images.githubusercontent.com/1919762/40618054-436f5502-625e-11e8-98ac-326669370660.png">

* Concourse version: v3.13.1
* Browser (if applicable): Chrome
* Did this used to work? Probably not

**Comment by mhuangpivotal** [comment]
@Lindsayauchin could you help with this?

**Comment by jama-pivotal** [comment]
@mhuangpivotal is it possible to increase the height of the bar to encompass the breadcrumb overflow?
