### ISSUE TITLE
Github OAUTH fails when specifying team name

### ISSUE THREAD

**Issue by rgcosma** [concourse/concourse#2243]
# Bug Report

Same issue as described in #1732 - Github auth works when specifying a list of usernames for a team, but not with a Github team or the entire Github org. Org and team name are definitely correct, and I can change them to any value if that helps with debugging.
With team name:
```
fly -t devel set-team -n perso --github-auth-client-id=123 --github-auth-client-secret=123 --github-auth-team=cosmaname/zztest

{"timestamp":"1527589243.065740347","source":"atc","message":"atc.skymarshal.oauth-callback.callback.verification-failed","log_level":1,"data":{"session":"4.4.4"}}
{"timestamp":"1527589542.830112696","source":"atc","message":"atc.skymarshal.oauth-callback.callback.verify.not-in-teams","log_level":1,"data":{"have":{},"session":"4.4.5.1","want":[{"Name":"zztest","Organization":"cosmaname"}]}}
{"timestamp":"1527589543.204930305","source":"atc","message":"atc.skymarshal.oauth-callback.callback.verify.not-in-organizations","log_level":1,"data":{"have":[],"session":"4.4.5.1","want":null}}
{"timestamp":"1527589543.624583483","source":"atc","message":"atc.skymarshal.oauth-callback.callback.verify.not-validated-user","log_level":1,"data":{"have":"rgcosma","session":"4.4.5.1","want":null}}
{"timestamp":"1527589543.624655008","source":"atc","message":"atc.skymarshal.oauth-callback.callback.verification-failed","log_level":1,"data":{"session":"4.4.5"}}
```
And I get just this in the browser: 'verification failed'
With username:
```
fly -t devel set-team -n perso --github-auth-client-id=123 --github-auth-client-secret=123 --github-auth-user=rgcosma

{"timestamp":"1527589894.422834635","source":"atc","message":"atc.skymarshal.oauth-callback.callback.verify.not-in-teams","log_level":1,"data":{"have":{},"session":"4.4.6.1","want":[]}}
{"timestamp":"1527589894.840902090","source":"atc","message":"atc.skymarshal.oauth-callback.callback.verify.not-in-organizations","log_level":1,"data":{"have":[],"session":"4.4.6.1","want":null}}
```
And I am logged on

* Concourse version: any, tried 3.10 to 3.13
* Deployment type (BOSH/Docker/binary): Linux binary & Docker
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome&Ffox
* Did this used to work? No

**Comment by jama-pivotal** [comment]
Interesting. I'm leaving this open with the desire to add docs

**Comment by eyJhb** [comment]
Please do add this to the docs. I've just spent about 2 hours before I found this issue.
Please let me know if I can be of any help.

**Comment by eyJhb** [comment]
Lets hope it gets merged.

**Comment by vito** [comment]
@eyJhb Thanks for the PR! I'm working on integrating it into the docs for 4.0 now that we've revamped auth.

Can someone clarify the behavior here? What is it that requires the client to be created under the organization? Does creating it as a regular user only permit e.g. that user or specified users to log in, while having creating it under the org permits org/team-based access? I don't see why it would be any different, so this seems like a strange restriction that we should document, but I just need to know how to word it.

**Comment by eyJhb** [comment]
@vito creating the app as a regular user, only allows to specify access for specified users, that use your app. This means, that it is not possible to specify "org/teamname", as it seems not to have access to see organisation information, and therefore has to be created as a application under that org.

**Comment by eyJhb** [comment]
I hope that makes sense, else I'll have to test it again. But since I don't have that much time to spare, I would rather avoid that :)

**Comment by vito** [comment]
@eyJhb Thanks for clarifying! Updated the docs in the above commit.
