### ISSUE TITLE
Prometheus metrics include dead workers

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#2244]
# Bug Report

The prometheus metrics emitter never resets or deletes metrics for dead workers, so the prometheus endpoint reports container counts, volume counts, etc. for workers long after they're retired. We noticed this because one of our workers had a high container count right as it was retired, and we alert on high container counts, so we saw a phantom alert firing even though the worker it referenced didn't exist.

Not sure how to fix this with the current metrics interface, since the prometheus emitter doesn't know when workers get garbage collected.

cc @TimSimmons @databus23 

The following can also be handy:

* Concourse version: 3.13.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): n/a
* Did this used to work? n/a

**Comment by marco-m** [comment]
Given the very good explanation by @TimSimmons on the impedence mismatch between Concourse metrics architecture (designed to push) and Prometheus (who wants to pull), and given that I completely agree that additional code just add complexity and bugs, would it make sense to just require to use the Prometheus PushGateway ? This would 

1. simplify Concourse code dealing with Prometheus
2. resolve this bug

At work we collect all infra metrics with Prometheus and I would have no problems in adding a VM running the PushGateway only to collect sensible metrics for Concourse. If people complain they have to add a PushGateway, well, let them complain :-)

Opinions ?

**Comment by vito** [comment]
Thanks for the info everyone!

I'm definitely seeing the friction here with Concourse's push style metrics vs. Prometheus's pull. I hope we can find a way in the future to not have so much custom (per-metric) code for the Prometheus backend. Right now it seems like every metric we add involves adding more code to the Prometheus engine to handle it, and I'm not at all confident that all engineers will remember to do that as we add them. I like to think of metrics as being in the same boat as logging, and want to be able to sprinkle them in cheaply.

Maybe we could have more information on the metrics types themselves so the Prometheus backend can generically process them? For example an `.EphemeralKey() string` marker which will result in the metric being reaped after a certain amount of inactivity from that same key? :man_shrugging:

**Comment by vito** [comment]
Closing as https://github.com/concourse/atc/pull/277 was merged. Thanks!

**Comment by marco-m** [comment]
Adding a comment to this closed bug because it seems to me that this thread contains good discussion about what Prometheus expects and the difficulty in making it work for Concourse.

I found https://www.robustperception.io/its-easy-to-convert-pull-to-push which explains the problems in adapting to pull (that is, to Prometheus) a system designed to push (as Concourse). They explain that on the other hand, if a system is designed for pulling, then it is easier to adapt it to pushing. This (although I understand would be a major undertaking) looks a promising path.

Opinions ?
