### ISSUE TITLE
pound sign in pipeline name breaks sidebar link (aka number sign aka hash tag)

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#2246]
# Bug Report

Tried to make a pipeline named after a branch named after a tracker story number. Got 404'ed instead! Url in link included the # without url encoding. Manually changing that allows us to see the pipeline.

![404ed](https://user-images.githubusercontent.com/1178694/40741212-f020e20a-6418-11e8-98dc-12e6d492ddea.gif)

* Concourse version: 3.9.1
* Browser (if applicable): chrome
* Did this used to work? *shrug_emoji*

**Comment by jama-pivotal** [comment]
Closing because sidebar is gone now
