### ISSUE TITLE
Improve performance of `REFRESH MATERIALIZED VIEW`

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#2253]
## What challenge are you facing?

On our wings deployment, our SLI pipeline had accumulated over 500,000 builds. Running the query `REFRESH MATERIALIZED VIEW CONCURRENTLY transition_builds_per_job` (the longest of the three) was taking more than 30 seconds. With lots of builds finishing in quick succession, we were seeing the db in locked-up state due to the slow queries.

## A Modest Proposal

- Investigate ways to optimize the query
- Instead of using materialized view, could we use a column on the builds table instead to keep track of the transition build?

**Comment by jama-pivotal** [comment]
Let's investigate this now that @xtremerui fixed our slowness. This might have been a red herring because the entire system was slow

**Comment by pivotal-nader-ziada** [comment]
After clearing out the `builds` table and removing the `check_order` index, this query is way faster and has not since slowed down. We're calling this issue a red herring.

**Comment by keithkroeger** [comment]
Hello @vito,

This looks like it won't be fixed based on tagging.

Is there any index that can be added while we wait to upgrade to 5.0.0?

Thank you

**Comment by xtremerui** [comment]
@keithkroeger what version of concourse are you running? These views `transition_builds_per_job` for example, is not used after v4.2 and thus I believe this issue is not valid anymore.
