### ISSUE TITLE
Large amount of active connections on Wings GCP sql DB that degrade overall performance

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#2254]
# BUG Report

## What challenge are you facing?

Running the following query on Wings db shows there is a large amount of active connections (about 158 out of 196)
```
select * from pg_stat_activity where datname = 'atc' and state='active'
```

All of them are used for a kind of query that is for getting versioned resource, for example
```
SELECT v.id, v.enabled, v.type, v.version, v.metadata, v.modified_time, v.check_order FROM versioned_resources v, resources r WHERE r.name = 'strabo-properties-s3' AND r.pipeline_id = 5 AND v.resource_id = r.id ORDER BY check_order DESC Limit 1
```
Running above query manually shows it take about 10 sec on wings db. Using postgres analyze matches the result
```
EXPLAIN ANALYZE
SELECT v.id, v.enabled, v.type, v.version, v.metadata, v.modified_time, v.check_order FROM versioned_resources v, resources r WHERE r.name = 'strabo-properties-s3' AND r.pipeline_id = 5 AND v.resource_id = r.id ORDER BY check_order DESC Limit 1

Limit  (cost=0.83..492.99 rows=1 width=101) (actual time=10494.315..10494.315 rows=1 loops=1)
  ->  Nested Loop  (cost=0.83..120087.40 rows=244 width=101) (actual time=10494.314..10494.314 rows=1 loops=1)
        Join Filter: (v.resource_id = r.id)
        Rows Removed by Join Filter: 859587
        ->  Index Scan using versioned_resources_check_order on versioned_resources v  (cost=0.42..105257.11 rows=988124 width=105) (actual time=0.013..7873.692 rows=859588 loops=1)
        ->  Materialize  (cost=0.41..8.43 rows=1 width=4) (actual time=0.001..0.001 rows=1 loops=859588)
              ->  Index Scan using unique_pipeline_id_name on resources r  (cost=0.41..8.42 rows=1 width=4) (actual time=0.023..0.024 rows=1 loops=1)
                    Index Cond: ((pipeline_id = 5) AND (name = 'strabo-properties-s3'::text))
Planning time: 0.655 ms
Execution time: 10494.354 ms
```

When this happens on Wings, since there is no available connection for fetching new resource version, the resource checking will fail and causes builds being in pending state much longer.

## A Modest Proposal

1. Find out why this query is slow on Wings db i.e. migrations?
1. ~~~If not found~~~, optimize this kind of query to make sure there is no DB performance degradation in a large concourse deployment that has thousands of resources ticking. For example, adding `modified_time` in `order by` for the above slow query, it yields same result but is way fast ( 1 ms vs 10000 ms)
```
EXPLAIN ANALYZE
SELECT v.id, v.enabled, v.type, v.version, v.metadata, v.modified_time, v.check_order FROM versioned_resources v, resources r WHERE r.name = 'strabo-properties-s3' AND r.pipeline_id = 5 AND v.resource_id = r.id ORDER BY check_order DESC, modified_time Limit 1

Limit  (cost=2262.75..2262.75 rows=1 width=101) (actual time=1.008..1.008 rows=1 loops=1)
  ->  Sort  (cost=2262.75..2263.37 rows=246 width=101) (actual time=1.006..1.006 rows=1 loops=1)
        Sort Key: v.check_order DESC, v.modified_time
        Sort Method: top-N heapsort  Memory: 25kB
        ->  Nested Loop  (cost=0.83..2261.52 rows=246 width=101) (actual time=0.037..0.812 rows=403 loops=1)
              ->  Index Scan using unique_pipeline_id_name on resources r  (cost=0.41..8.42 rows=1 width=4) (actual time=0.017..0.018 rows=1 loops=1)
                    Index Cond: ((pipeline_id = 5) AND (name = 'strabo-properties-s3'::text))
              ->  Index Scan using versioned_resources_resource_id_idx on versioned_resources v  (cost=0.42..2244.60 rows=850 width=105) (actual time=0.020..0.713 rows=403 loops=1)
                    Index Cond: (resource_id = r.id)
Planning time: 0.326 ms
Execution time: 1.041 ms
```

Concourse version: v3.13.1-rc.38

**Comment by xtremerui** [comment]
Updated:

The commit with the migration that cause the issue is found:
https://github.com/concourse/atc/commit/7cce79a47bdd19b3a2e37b2f5b51de025b72c54e#diff-ee1950c294e90f0f5e431392880baac9

**Comment by vito** [comment]
This is coming from `(db.Pipeline).GetLatestVersionedResource`, which is used for the period checks, and so gets called every minute for every resource in every pipeline.

This query is hitting a lot of rows for something called so often, and this approach may only get worse with concourse/rfcs#1. Can we reduce it to a simple join by tracking `latest_versioned_resource_id` on the `resources` table instead? We can set this value every time there are new versions to save.
