### ISSUE TITLE
Feature Request: Add MySQL support as backend database

### ISSUE THREAD

**Issue by devtdeng** [concourse/concourse#2255]
# Feature Request

## What challenge are you facing?

Currently concourse bosh-release only supports single master and psql as backend database. In order to take a safe backup, as operator I have to stop concourse operation, as result concourse users can't use pipeline during backup.   

I want to keep concurse accessible/operable during backup. We have MySQL cluster supports zero-down time backup feature, so that I appreciate MySQL can be supported besides of psql.  

## A Modest Proposal

Enhance concourse to support MySQL database.

**Comment by jama-pivotal** [comment]
Thanks for submitting the request. IIRC, Concourse takes advantage of a lot of tooling and functions specific to postgres, so I'm not sure if this can happen without some serious refactoring!

**Comment by jama-pivotal** [comment]
+1 to @shinji62 As a counterpoint,  I'd also add that the pgdb holds the team configurations; and if you have a sufficiently large Concourse installation with lots of teams; this can be a huge pain to recreate if you haven't externalized it. That said, you could always just back up the entire database..

Another interesting hidden feature is BBR compatibility in Concourse 3.10.0 and above. We've also recently written this issue to take a more serious look at BBR #2332

**Comment by kedare** [comment]
What kind of PostgreSQL specific feature are you using that could make the compatibility impossible to achieve?

PITR and H.A is still years behind on PostgreSQL compared to MySQL/MariaDB.

**Comment by vito** [comment]
@kedare We use `LISTEN`/`NOTIFY` and directly write queries left and right that assume PostgreSQL semantics.

I'm sorry but it is just extremely unlikely that we would do this. It's too much constant overhead to support multiple database backends. I would rather focus on core feature functionality and continue with the philosophy that "the database is ephemeral" and that everything mission-critical should be safely contained in portable pipelines, audit trails should go to an external persistent sink, and build logs should be exported to a syslog sink if you want to keep them around forever. This mitigates the risk of PostgreSQL being a single point of failure.
