### ISSUE TITLE
install failure in LXC/LXD environment due to "operation not permitted" with Docker layer

### ISSUE THREAD

**Issue by erno** [concourse/concourse#2257]
I made a security.nesting=true container on my Ubuntu 16.04 machine and did the quickstart steps from the Concourse-CI web page. Having downloaded https://concourse-ci.org/docker-compose.yml I ran docker-compose:

root@concourse:~/concourse-install# docker-compose up
Pulling concourse (concourse/concourse:)...
latest: Pulling from concourse/concourse
b234f539f7a1: Pull complete
55172d420b43: Pull complete
5ba5bbeb6b91: Extracting [==================================================>]     619B/619B: Download complete
f6c9c6de4190: Download complete
6dff0319d3d0: Download complete
 32.62MB/33.21MBwnload complete
e9fbde0d7ae4: Download complete
ERROR: failed to register layer: Error processing tar file(exit status 1): operation not permitted

This happens with the latest Docker version (Docker version 18.05.0-ce, build f150324).
There is an old Docker bug open with a matching error message (https://github.com/moby/moby/issues/35245), this is with some probability just hitting that bug. But I'm leaving this issue here so others won't duplicate effort investigating.

**Comment by dgengtek** [comment]
also related if you run the worker binary inside an lxc container with the following configs set for the container
```
security.nesting true
security.privileged true
linux.kernel_modules overlay
```
the worker will exit with

> runc run: exit status 1: container_linux.go:348: starting container process caused "operation not permitted"

**Comment by xtremerui** [comment]
closing stale issue
