### ISSUE TITLE
build_events should contain the columns that it is partitioned off of

### ISSUE THREAD

**Issue by nelsam** [concourse/concourse#2259]
# Feature Request

I think this counts more as a feature request than a bug report, but it's a little bit of both.

## What challenge are you facing?

When we were running some automated tests that created and deleted teams and pipelines, we generated around 16,200 child tables of `build_events`.  As a side effect of #2169, these child tables weren't cleaned up.

[Constraint exclusion](https://www.postgresql.org/docs/9.1/static/ddl-partitioning.html#DDL-PARTITIONING-CONSTRAINT-EXCLUSION) would normally make this perfectly fine - queries would ignore the child tables that couldn't contain data that they needed.  However, the `build_events` table is actually partitioned on columns that require a `JOIN` to get access to, so the child tables can't have any check constraints, so constraint exclusion can't come in to play.

The end result is that any query against `build_events` would scan all 16,000 tables.  This caused most queries (including the garbage collector query) against that table to eat up an enormous amount of RAM and get OOM-killed.

## A Modest Proposal

Would you accept a PR that adds (nullable) `team_id` and `pipeline_id` fields to the `build_events` table and also to any queries where they make sense?  That would allow any queries that could reference the `team_id` and/or `pipline_id` to rely on constraint exclusion for performance.  Queries not referencing those columns would *work*, but would still end up scanning all child tables.  I know we programmers hate the idea of redundant data, but redundant narrow columns for performance reasons is a pretty common thing in the postgres world - this scenario is one, but I've also had to use it to reduce the need for joins in some particularly nasty queries.

I know that having 16,000 teams and pipelines is a pretty niche use case right now, but it's a reasonably cheap addition that would completely eliminate the problem we ran in to.  The scan for that delete statement would automatically run against two child tables (`team_build_events_{team_id}` and `pipeline_build_events_{pipeline_id}`) instead of 16,000.

The only other fix I can think of would be to replace all queries against `build_events` with queries against the child tables, but that would just make the `build_events` table nothing more than a template for the `pipeline_build_events_*` and `team_build_events_*` tables to be based off of.

**Comment by jama-pivotal** [comment]
@vito thoughts?

**Comment by vito** [comment]
@nelsam Sorry for the long delay on this one! Yeah, the proposed change sounds good to me, since those tables all grow unbounded. If it gets crazy slow over time we should definitely fix it.

**Comment by nelsam** [comment]
D'oh, time has been unkind to my memory.

I'm still trying to find time to actually work out a PR for this, but I think it's fairly important to make sure the columns are there for those query constraints.  I'll uh ... try to ... free up my schedule somehow...
