### ISSUE TITLE
Shareable Search on dashboard

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2265]
The search feature on the current `dashboard/` UI is really convenient and it would be nice if we could actually pass those search queries around. The suggestion is to put the search parameters in the URL so a user could simply bookmark that search state and have it show up every time: e.g. https://ci.concourse-ci.org/dashboard?search=web

We might have to break down the search parameters by filters as well?

**Comment by marco-m** [comment]
Yes please! I also have another use case for this feature: use the search in the URL to reduce the number of pipelines shown in the dashboard for a build monitor / TV screen.

**Comment by jama-pivotal** [comment]
Moving this into "in-progress". The team is currently working on the PR from @SHyx0rmZ but we need to make some changes to our PR pipeline so that we can run the changes through the MOST appropriate test suites
