### ISSUE TITLE
new breadcrumb view should render spaces correctly

### ISSUE THREAD

**Issue by StevenArmstrong** [concourse/concourse#2267]
## A Modest Proposal

The new breadcrumb view should render spaces correctly rather than having %20

![image](https://user-images.githubusercontent.com/5717694/41193496-c4649a6e-6c04-11e8-90fd-9a3a8372e4fd.png)

The following can also be handy:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: IaaS
* Browser (if applicable): N/A
* Did this used to work? No

**Comment by jama-pivotal** [comment]
doh! we should also make sure emojis render properly (not being sarcastic, we use lots of emojis)
