### ISSUE TITLE
Concourse not triggering jobs when new resource versions detected

### ISSUE THREAD

**Issue by anthonysroberts** [concourse/concourse#2270]
# Bug Report
Running concourse v3.13.0 on GCP multiple AZ from https://github.com/concourse/concourse-deployment.git
Deploy type: Bosh
3 web (VM Type N1-STANDARD-1)
3 workers (N1-STANDARD-2)
Using Postgress Google SQL service for concourse
OS ubuntu-trusty 3468.21

Problem: A resource change that triggers pipeline (in this case it was cf-deployment 1.40) failed to trigger the dependant pipeline jobs
Concourse identified the resource change (CF-Deployment 1.40) within a minute of it being released.
This was working fine previously.
When assessing monitoring of concourse for the period when the cf-deployment came out (18:50 UTC 8th June 18)
Workers: CPU load was only 1 CPU (2 allocated), Memory at 9%
Web:: CPU load 0.2 (of 1 allocated), Memory at 9%
PostgressSQL connections pretty static at 25
Disk util 17%
So nothing to point in the direction of resources available to concourse.

Workaround: Restart of concourse web resolved the issue - dependant job kicked off immediately (3 days after it should have)

**Comment by anthonysroberts** [comment]
For reference this occurred again today on the lastest version of concourse. (V3.14.1)

**Comment by sbkg0002** [comment]
We have the exact same issue with version 3.8.1

**Comment by vito** [comment]
Possibly another instance of #2010?

In any case, this is super difficult to look into after-the-fact without steps to reproduce and without logs to reference, so I'm going to tentatively close this in hopes that the same fix for #2010 will fix this. The fix will be out in 5.0.
