### ISSUE TITLE
3.14 UI not working in Safari

### ISSUE THREAD

**Issue by rjosephwright** [concourse/concourse#2272]
# Bug Report

After upgrading to 3.14.1, pipelines no longer show in the default UI view when using Safari. The legend is also overlayed over the group tabs. The only way I could find to get to the main pipeline visualization is to first go to the dashboard and click on the pipeline from there.

<img width="720" alt="screen shot 2018-06-11 at 10 37 28 am" src="https://user-images.githubusercontent.com/342102/41239966-665991ea-6d67-11e8-8aa6-f65d36365f8d.png">

**Comment by jama-pivotal** [comment]
Weird. We're running 3.14.1 (ish) on https://ci.concourse-ci.org and it seems to load fine on my Safari. I'm running Safari Version 11.1.1 (13605.2.8) , are you running the same version @rjosephwright ?

**Comment by rjosephwright** [comment]
Hi @jama-pivotal, it was my Safari version. I was on 10.1.2 (12603.3.8). After updating it looks fine. This is on a work machine, which normally gets automatic updates, and I made the wrong assumption that Safari was up to date.

**Comment by jama-pivotal** [comment]
@rjosephwright no worries! thanks for updating us on your progress
