### ISSUE TITLE
Web UI Suggestion: Persistent Groups Bar

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [concourse/concourse#2273]
# Feature Request

## What challenge are you facing?

As both a pipeline maintainer and a developer whose code is passed through the pipelines, I enter and exit Jobs very often to validate the output of every Task. As such, I have found a `rough-edge` of the UX/UI.

For any given pipeline, to go through various Jobs in different groups the user has to return everytime to the main pipeline view.
I can see this pattern happening for all the users of Concourse:
- click on the pipeline of interest
- click on a group of interest
- click on the job of interest
- ... after going through the job ...
- click on the same pipeline (again)
- select the same or other group
- click on the next job of interest
- repeat

## A Modest Proposal

To render the UX more fluid by cutting the number of clicks required to go from job to job in a set of groups of a pipeline.

Simply by making the Groups bar persistent, users would be able to analyze multiple jobs of the pipeline across groups without clicking on the pipeline to return to the view with the Groups bar

The pattern would be something like so:
- click on the pipeline of interest
- click on a group of interest
- click on the job of interest
- ... after going through the job ...
- click on the same or other group
- click on the next job of interest
- repeat

I understand this is not a drastical change, nor a critical issue.
I am expressing this matter more as `customer feedback` in case the Dev Team and other users consider it a useful addition.

Cheers

**Comment by jama-pivotal** [comment]
I think that's fair. Groups persisted in the past and I think you make a reasonable case for persisting it through Jobs and Resources pages. Prioritizing relatively highly in our backlog

**Comment by aoldershaw** [comment]
A bit late, but @clarafu and I got sufficiently annoyed by this as well that we wrote https://github.com/concourse/concourse/pull/7307 - this doesn't keep the groups bar around when you navigate to the build page, but remembers what group you were viewing when you clicked on the job and returns there if you navigate back to the pipeline.

Going to close this as it should address the same annoyance
