### ISSUE TITLE
Dashboard search query should be separated at the `:` with a space

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2275]
Can we add a space after the colon? ": result" so that it is easier for users to read the results of the query?
Current:
![screen shot 2018-06-11 at 1 44 35 pm](https://user-images.githubusercontent.com/27746614/41248237-648188de-6d7e-11e8-9f6b-c89d777ecbe6.png)
Proposed:
![screen shot 2018-06-11 at 1 47 58 pm](https://user-images.githubusercontent.com/27746614/41248254-710cfbec-6d7e-11e8-8d23-3b89e2d45a57.png)

**Comment by jama-pivotal** [comment]
Closing in favor of #2387
