### ISSUE TITLE
Navigation arrows become invisible on mouse hover

### ISSUE THREAD

**Issue by walterdolce** [concourse/concourse#2276]
# Bug Report

Hi,

When hovering over the arrows in the web UI I noticed this minor issue. Please see below.

<img width="966" alt="screen shot 2018-06-12 at 14 53 00" src="https://user-images.githubusercontent.com/6195629/41294645-778eac0e-6e50-11e8-9ca7-2dbe8da79411.png">

Please note the grey circle has the mouse hovering over it (you can't see due to macOS's screenshot taking component hiding the cursor).

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): N/A
* Infrastructure/IaaS: N/A
* Browser (if applicable): Google Chrome
* Did this used to work? I just noticed it now.

Thank you.

**Comment by jama-pivotal** [comment]
good catch!
