### ISSUE TITLE
Expose repository source in git resource UI representation

### ISSUE THREAD

**Issue by walterdolce** [concourse/concourse#2277]
# Feature Request

## What challenge are you facing?

When looking at the following:
<img width="962" alt="screen shot 2018-06-12 at 15 00 56" src="https://user-images.githubusercontent.com/6195629/41295652-024d1a4a-6e53-11e8-95c5-654a506705cb.png">

If I am someone who does not know, nor need to know, where the pipeline definition is (therefore I can't see the value of the `source: uri:` for the `git` resource type); or needs to quickly look up where that commit hash comes from for whatever reason (assuming the previous point holds true); or whether or not that `uri` has changed at some point, I would not be able to get this information by just looking at the UI. Especially if I am not in the team developing/maintaining the pipeline, I think it would be useful to visually see the repository source on the UI under each `ref`.

## A Modest Proposal

Show the repository source as defined in `source: uri:`, ideally before `commit`.

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): N/A
* Infrastructure/IaaS: N/A
* Browser (if applicable): N/A
* Did this used to work? N/A

**Comment by marco-m** [comment]
What we do as a workaround is to require to follow a naming scheme for all pipelines we host. If a git repository has name `really-super-name`, we require the corresponding Concourse git resource to be named `really-super-name-maybesomethingmore.git`, so in case of doubt we just remove "maybesomethingmore" and we know the repo name. Also the `.git` suffix is handy when looking at the pipeline graph, especially when complicated.

**Comment by jama-pivotal** [comment]
Linking to #1833 for contextual and organizational purposes :D
