### ISSUE TITLE
Scripts for executing a Concourse Rollback/Downgrade on Wings

### ISSUE THREAD

**Issue by nader-ziada** [concourse/concourse#2278]
This note was inspired by the big wings incident May 18. During the pandemonium folks were struggling with rolling back the change. Some theories about why this was hard:
* it could have had to do with special considerations for rolling back with multiple ATCs ("first scale to 1, then migrate, then scale back up")
* it could have had to do with the load of tasks for the bosh director, since the same bosh environment had many deployments ("we had to pause the jobs on prod before rolling back"):
    * prod
    * wings
    * upgrades
    * downgrades
    * topguns

Overall, it seems reasonable to expect that having more regular coverage of downgrade scenarios could ease the pain of future wings deployments, but this requirement should be made more precise. Some considerations:
* currently bosh-downgrade job does this on a small deployment. Should these jobs just run against something more wings-like?
* Part of the reason for creating a prop environment is to help get earlier feedback about the behaviour of wings. Reading between the lines, then, it seems reasonable to regularly execute these hypothetical "upgrade/downgrade" scripts against prop. However, we have already made some compromises in how prop is deployed which may make it unsuitable for this case:
    * we are using draupnir to manage prop, but wings is not managed by draupnir, lowering the parity. Plus we don't have a clearly-defined notion of "downgrade" in draupnir.
    * prop has its own bosh director; wings does not
* part of the stated purpose of topgun is to exercise changes to the bosh deployment and infrastructure. does it make sense for these kind of downgrade scenarios to be "documented" via topgun tests?

**Comment by jama-pivotal** [comment]
1. get Wings on draupnir
2. upgrade/downgrade jobs can run against prop
3. and then the conditions of the original issue will be satisfied :D
