### ISSUE TITLE
Pipeline names on HD view

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2286]
![mvimg_20180622_135030](https://user-images.githubusercontent.com/27746614/41791543-fcb6c2e2-7623-11e8-8765-ec4d6b2097a0.jpg)

Current: ![screen shot 2018-06-18 at 10 10 06 am](https://user-images.githubusercontent.com/27746614/41541142-c8a640a0-72df-11e8-908b-b4cc1b696e08.png) 

Proposed:
Optimize to accomodate more use cases of long, long, extra long names in teams with many pipelines. To do this we could add in more responsive font rendering with bucketing of more breakpoints to pipelines. 

![screen shot 2018-06-18 at 10 13 02 am](https://user-images.githubusercontent.com/27746614/41541350-372505c0-72e0-11e8-8c3d-b3b607d0e3ea.png)

**Comment by jama-pivotal** [comment]
Closing due to some of the more recent fixes that came as a part of the 4.0.0 release

**Comment by StevenArmstrong** [comment]
I noticed it still truncates it in 4.0.0 if you have underscores so my_long_pipeline_name gets truncated but my-long-pipeline-name is fine.
