### ISSUE TITLE
Non JSON formatted log message (3.14.1)

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#2288]
# Bug Report

I think this might be a bug (not entirely sure) but we got this in the ATC log:
```
concourse[29398]: 2018/06/18 14:26:47 http: multiple response.WriteHeader calls
```
Not sure if the log message itself indicates a problem, but it's not being printed in a JSON formated string. 

We're running with `CONCOURSE_LOG_LEVEL=error`

* _Concourse version:_ 3.14.1
* _Deployment type (BOSH/Docker/binary):_ binary
* _Did this used to work?_ Don't remember seeing it in previous versions

**Comment by vito** [comment]
Hmm pretty sure these go to stderr not stdout. The only stream that should be full json is stdout.

**Comment by vito** [comment]
Yeah, I think that's the way to go. I don't think we'll be changing this - `stderr` has no structure, and probably never will because there'll always be things like Go panics/stack dumps which will send output there.
