### ISSUE TITLE
Installation instructions for environments without BOSH

### ISSUE THREAD

**Issue by cgrotz** [concourse/concourse#229]
At our environment we sadly haven't the possibility to use BOSH.
Is it possible to run concourse without BOSH? Can somebody provide instructions how to install concourse without BOSH?

**Comment by vito** [comment]
I'd like to expand on this before 1.0 and document a bunch of install methods. The first thing we do may be to make `.deb` installers available. Would that work for you or do you think you'll end up building from source? (Or do you use some other package manager, e.g. `pacman` or `yum`).

The Concourse components themselves are pretty straightforward to build from source; ATC should just be `go get github.com/concourse/atc`, though you may want to build from our release repo (this one) instead to ensure you're building with the correct dependencies.

The Garden Linux server (used for containerization) is a bit trickier, owing some of its complexity to containerization tech being a constant moving target, which makes portability difficult.

@goonzoid / @julz Do you know if Guardian is/will be any easier than Garden-Linux to bootstrap without BOSH knowledge? I haven't been keeping up lately.

**Comment by goonzoid** [comment]
I don't know about Guardian being much easier, but it certainly won't be any harder, and it's currently not that hard. I recently updated the [Garden-Linux README](https://github.com/cloudfoundry-incubator/garden-linux/blob/master/README.md) with instructions for running it without BOSH, and it's really not that many steps, nor are any of them very complicated.

That said, if you find some part that's annoying to deal with when you're doing the packaging work, let us know and we can see if there's anything that might be tweaked to make it simpler.

**Comment by vito** [comment]
@goonzoid Cool, thanks! I'll dig in some more tomorrow and let you know how it goes.

**Comment by anorsich** [comment]
I also curious about the ways to setup standalone concourse instance without a need to invest time into learning Bosh. Is it possible to just run concourse within docker container? @vito while dev/yum packages makes a lot of sense, docker seems a much simpler option. 

I was completely sold after reading philosophy of the concourse. In addition, to that I almost finished migrating our CI server scripts to the concourse (using vagrant), but stuck while setting up production instance.

@vito Any tips/pointers would be highly appreciated. @cgrotz Any findings so far?

**Comment by vito** [comment]
@anorsich Docker images are on the roadmap, but we'll probably start with `.deb` and/or prebuilt binaries first, which are more universal. Should be easy to build a Docker image based on them.

Tricky part with Docker images for everything is that Garden itself is a containerizer, and running containerizers in containerizers gets tricky pretty quickly. A Docker image for the ATC would be trivial though.

Have you tried the Vagrant boxes? There's also an AWS box, but we don't document it as there's no way to configure auth after you spun it up. We'll be fixing that soon.

**Comment by anorsich** [comment]
@vito Looking forward to having either .deb or prebuilt binaries! I think I'll stay with the vagrant box for our production environment.

Do you have any plans to support concouse scaling without bosh? For bigger projects we typically use apache mesos for everything (ci, databases, queues, application services, etc). 

Thank you once more for the all the work you do. I am really impressed by concourse!

**Comment by cgrotz** [comment]
We have yum here. Prebuild binaries would be good, but Docker would be even better. :-)
I will try to build it manually, and see how far I come.

**Comment by vito** [comment]
@anorisch We may not develop all the different ways to spin up a cluster, but we'll be keeping it pretty easy to do so with your own tooling. It's really just a matter of pointing multiple ATCs at the same Postgres and making sure they have URLs they can reach each other with (`--peer-url`). We'll have docs for this as well. We're intentionally keeping it simple so you don't *need* a big tool like BOSH to deploy it.

We'll probably stick to BOSH ourselves since it's nice to have the development team able to focus on one tool/test cluster/development workflow. It's our preferred solution for scalable clusters generally, but that doesn't mean we want to force others to switch to it (you probably have your own stack). PRs welcome for contributing docs/templates for other deployment schemes; we'll happily refer to them from the main site as long as they're maintained.

**Comment by anorsich** [comment]
@vito Just wanted to check if you had a chance to work on prebuit binaries / docker image for deploying standalone instance of concourse. Thank you!

**Comment by vito** [comment]
@anorsich Still workin' on it. You can get a sneak peek here: https://github.com/vito/concourse-bin Prereleases available as GitHub releases; check the README for instructions. Some squeaky hinges here and there but it's coming along nicely.

**Comment by anorsich** [comment]
@vito Thanks for the great job! I was able to install concourse just by following README. I haven't tested  any piplelines, but based on logs I can say that both worker & web roles works. I put together my Ansible installation scripts together (nginx as proxy, postgresql via docker, concourse web & worker under upstart) in [this repo](https://github.com/anorsich/concourse-ansible-deploy) which might help to someone.
I had to disable ssl mode (`sslmode=disable`) right in connection string to postgresql to make it finally work. This is fine for me, because postgresql will be located on same machine as concourse and protected by firewall.

**Comment by anorsich** [comment]
@vito Simple pipeline(just pulling sources out of git repo) panicing. Here is build log:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/concourse/fly/commands.(*JobFlag).UnmarshalFlag(0x71df00, 0x7fff5fbff9bb, 0x12, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/job_flag.go:19 +0x3f5
github.com/jessevdk/go-flags.convertUnmarshal(0x7fff5fbff9bb, 0x12, 0x4315c0, 0x71df00, 0x16, 0x16, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/convert.go:157 +0x176
github.com/jessevdk/go-flags.convertUnmarshal(0x7fff5fbff9bb, 0x12, 0x45c1a0, 0x71df00, 0xd9, 0x1a, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/convert.go:162 +0x2ab
github.com/jessevdk/go-flags.convert(0x7fff5fbff9bb, 0x12, 0x45c1a0, 0x71df00, 0xd9, 0x582720, 0x60, 0xc820015aa0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/convert.go:173 +0x79
github.com/jessevdk/go-flags.(*Option).set(0xc820112000, 0xc8200fba28, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/option_private.go:41 +0x5e9
github.com/jessevdk/go-flags.(*Parser).parseOption(0xc820016870, 0xc8200ab5f0, 0x7fff5fbff9b7, 0x3, 0xc820112000, 0xffffffffffffff01, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser_private.go:186 +0x642
github.com/jessevdk/go-flags.(*Parser).parseLong(0xc820016870, 0xc8200ab5f0, 0x7fff5fbff9b7, 0x3, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser_private.go:220 +0xe4
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc820016870, 0xc82008c010, 0x7, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser.go:230 +0xbaa
github.com/jessevdk/go-flags.(*Parser).Parse(0xc820016870, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser.go:154 +0x9b
main.main()
	/var/vcap/packages/fly/src/github.com/concourse/fly/main.go:14 +0x62

goroutine 3 [syscall]:
os/signal.loop()
	/var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4-879879219167b8e7b3c3232048c6e95f096aa90a/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4-879879219167b8e7b3c3232048c6e95f096aa90a/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by vito** [comment]
Cool, glad it's working out!

That panic should be fixed with the latest fly.

**Comment by vyshane** [comment]
I noticed that there's a [concourse/concourse-ci](https://hub.docker.com/r/concourse/concourse-ci/) Docker image. Is there any documentation on how to use it?

**Comment by vito** [comment]
That image is for our own CI pipeline, and doesn't have Concourse in it
(just random test dependencies). It's not for external consumption. The
docs for official distribution formats would live at https://concourse.ci -
we're currently revamping it and will document the binaries soon, which
come from https://github.com/concourse/bin

**Comment by vito** [comment]
This is now out there officially with v1.0:

https://concourse.ci/binaries.html

**Comment by johnscancella** [comment]
I know this has been closed but I would also like to vote for a package (yum and deb). For everything else on my server I can just do `yum update` and know everything has been upgraded to the latest version for security. Also, you could have the package setup and install and configure the dependencies for concourse (like postgres and the atc database).
