### ISSUE TITLE
Pipeline names shouldn't render %20 as a space in the page title

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2291]
Noticed this issue while doing acceptance on #2267 ; we're not properly rendering whitespaces on the pipeline name in the tab title element, see below

![screen_shot_2018-06-18_at_1_18_12_pm](https://user-images.githubusercontent.com/19274230/41551649-780d5848-72fa-11e8-9ed0-6f0aedae1105.png)

Steps to reproduce are quite straightforward; set a pipeline with a whitespace in its name and check the web ui

**Comment by walterdolce** [comment]
Note that in `3.14.1`, #2267 is still an issue. Please see below.
![screen shot 2018-06-26 at 16 06 11](https://user-images.githubusercontent.com/6195629/41921488-dfe36ab4-795a-11e8-84e2-1798e89889f7.png)

**Comment by jama-pivotal** [comment]
@walterdolce #2267 is resolved on the dev line and should appear in the next release of Concourse. The general rule of thumb is that if a closed issue doesn't have a Milestone its waiting to be released

**Comment by walterdolce** [comment]
@jama-pivotal oh I see. Thanks for the clarification! :)

**Comment by jama-pivotal** [comment]
Accepting! But i found another semi-related bug that i will write up in a new issue
