### ISSUE TITLE
Investigate any breaking changes from CredHub 2.0

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2293]
CredHub team sent a note recently notifying us that their new 2.0 release will include some breaking changes. We'll need to investigate whether or not they affect our integration for creds management

**Comment by xtremerui** [comment]
where is doc of breaking changes? @jama-pivotal

**Comment by crawsible** [comment]
@jama-pivotal @topherbullock This is a touch premature, nothing to investigate on your end yet; we're pretty far from cutting 2.0 and we don't know all the breaking changes we'll be making yet. We'll post back here once we have a better idea.

**Comment by jama-pivotal** [comment]
Thanks for following up @crawsible , i'll de-prioritize then

**Comment by ryanmattcollins** [comment]
Hey @jama-pivotal, we were planning on upgrading both our Credhub and Concourse to the latest major versions. Any chance Concourse 4.x supports Credhub 2.0 and this issue just hasn't been updated? :)

**Comment by crawsible** [comment]
@ryanmattcollins CredHub PM here — I'd recommend against it! We made quite a few significant changes to CredHub's API. It's pretty unlikely that everything will Just Work with Concourse today. @jama-pivotal and I have some planning to do!

**Comment by shauravg** [comment]
Hey @crawsible wanted to follow up on this from CloudOps. We see that this issue (https://github.com/EngineerBetter/concourse-up/issues/58) says that Concourse v4 and CredHub 2 are fine but would love to get official confirmation before we do the upgrade.

**Comment by crawsible** [comment]
I'm no longer working on this, but @athornton2012 may be able to give you an answer

**Comment by cirocosta** [comment]
Hi @shauravg,

We prioritized this and are going to be more actively testing this very soon!

**Comment by cirocosta** [comment]
I'll close this issue for now as a way of keeping everything under https://github.com/concourse/concourse/issues/2723#issuecomment-467077668. 

Thanks for all of your input!
