### ISSUE TITLE
Unable to find Amazon Secrets Manager secret.

### ISSUE THREAD

**Issue by Amiedeep** [concourse/concourse#2297]
Hi,

I am using docker concourse version 3.8.0. I want to setup concourse Credential Management using aws secrets manager. I setup my web node on aws ecs with CONCOURSE_AWS_SECRETSMANAGER_SECRET_KEY, CONCOURSE_AWS_SECRETSMANAGER_ACCESS_KEY and AWS_REGION environment variable. when I use a secret in my pipeline configs it is unable to resolve it. Please help if there is anything I'm missing here or you need more information on it.

**Comment by fiftin** [comment]
I have similar problem. How you solve it?

Looks like `CONCOURSE_AWS_SECRETSMANAGER_ACCESS_KEY` not used in Concourse 5. But it not removed from docs.
