### ISSUE TITLE
Add CI integration for web PRs

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#2305]
# Feature Request

## What challenge are you facing?

We want to run WATS and WATS-js for web PRs as part of the PR process so that breaking changes can be surfaced.

## A Modest Proposal

- Create a dev release with concourse on `master`, and `web` on the PR branch merged in
- Deploy to BOSH
- Run WATS and WAT-js against the deployment
- Delete the deployment

**Comment by mhuangpivotal** [comment]
We added the job https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/web in the `prs` pipeline.

The idea is to trigger a new build whenever a web PR has a review approved, by setting `require_review_approval: true` for the pull-request resource. This works well for the initial commits, but once the first set of commits is approved, subsequent commits will trigger new builds without additional approval.

@xtremerui opened an [issue](https://github.com/jtarchie/github-pullrequest-resource/issues/193) for the resource.

**Comment by xtremerui** [comment]
Turned out to be a repo configuration problem. Closed the issue and we should be unblocked now.

**Comment by jama-pivotal** [comment]
Blocked on an issue that @vito is yet to write. But when he does it'll be great and super informative.  

#366  <-- this has a lot to do with it
