### ISSUE TITLE
Fly errors on build inputs for `execute` when job name is specified incorrectly

### ISSUE THREAD

**Issue by h4xnoodle** [concourse/concourse#2306]
# Bug Report

Fly errors on build inputs for `execute` when job name is specified incorrectly.

E.g.
```
$ fly -t production execute -j mypipeline/jobs/myjob -c mytask.yml -i input=.
error: build inputs not found
```
I would expect that the job is assessed for correctness and the error is for the job flag. This error seems like a red herring. 

```
$ fly -v
3.12.0
```

**Comment by xtremerui** [comment]
Concourse used to allow '/' in job name thus in the execute cmd it actually consider `jobs/myjob` a valid job name.

However in the future '/' will be a reserved char for concourse thus it will return validation error in this case.
