### ISSUE TITLE
Dashboard shows pipeline as red when there are no red jobs

### ISSUE THREAD

**Issue by astrieanna** [concourse/concourse#2307]
# Bug Report
Our pipeline has nearly all the jobs green; the ones that aren't green are either paused or have never run at all. In this situation, I would expect the pipeline to be green. However, in the dashboard view, the pipeline is summarized as red:

![giant green-but-yet-red pipeline](https://user-images.githubusercontent.com/1205394/41680763-90c3e706-74a0-11e8-9371-2972e8ee593c.png)
Our concourse is public, so you can see this dashboard/pipeline here: https://buildpacks.ci.cf-app.com/dashboard

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: gcp
* Did this used to work? I have no idea.

**Comment by mhuangpivotal** [comment]
This is because the latest build for the paused job is a failed build.

@jama-pivotal @Lindsayauchin We should probably ignore the builds for paused jobs when determining the pipeline status, what do you think?

**Comment by jama-pivotal** [comment]
@mhuangpivotal ah interesting. I think your suggestion makes sense.
