### ISSUE TITLE
`reaped` link is not valid since moved to new website

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#2308]
# Bug Report

The reaped link points to
https://concourse-ci.org/configuring-jobs.html#build_logs_to_retain
which yields a 404

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by drahnr** [comment]
![reapedlink](https://user-images.githubusercontent.com/667047/41701317-4fd8abfa-752c-11e8-85ec-d4d85060827e.png)

**Comment by jama-pivotal** [comment]
Looks like the new url is https://concourse-ci.org/jobs.html#job-build-logs-to-retain

**Comment by drahnr** [comment]
Since I upgraded to 4.0 it's fine, with 3.14.1 it did not. It's the `reaped` on the RIP page.
