### ISSUE TITLE
Eliminate relative path WORKSPACE_DIR boilerplate in scripts

### ISSUE THREAD

**Issue by ctaymor** [concourse/concourse#2311]
# Feature Request

## What challenge are you facing?
Most task scripts I've seen on many different teams start with something like 
```
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$( cd "${MY_DIR}"/../../.. && pwd )"
```
This `WORKSPACE_DIR` variable is needed to access other inputs to the job. For instance the next line might be:
`BOSH_IP=$(cat ${WORKSPACE_DIR}/bosh-lite-info/external-ip)`

It's boilerplate that must be repeated again and again, and is easy to get wrong. The relative paths are also fragile, as the script will break if the script gets moved up or down a directory in the ci repo. I'd love to see the absolute path of the "workspace" directory (where all the input and output directories live) handled by councourse, and exposed to these scripts in some way, so that teams can reduce this fragile boilerplate.

**Comment by marco-m** [comment]
Unless I am missing something :-), I see a problem in this request: with the current situation with relative paths, we are able to use exactly the same build scripts both on Concourse and on the developer machines with a local Docker container, which is a big plus for reproducibility. I see relative paths as a trade-off.

**Comment by StevenArmstrong** [comment]
So the relative path in question is on the container. So on containers concourse executes commands from the path /tmp/build/(container uuid)/ then concourse puts resources under this. So it will form /tmp/build/(container uuid)/(resource_name) but when scripting you need to know the container uuid for absolute paths. So having a param that gave the /tmp/build/(container_uuid) that could be called from scripts would mean it can be used to do operations on the container If required.

**Comment by ctaymor** [comment]
@marco-m I think this could be implemented in such a way as not to block running the scripts in a local docker container. I'm envisioning an ENV_VAR that your scripts can rely on, or not if you prefer relative paths.

Yes @StevenArmstrong, that's what I was envisioning.

**Comment by eedwards-sk** [comment]
Not sure if it's relevant, but if this means I could get control over an absolute path for my tasks I'm big time 👍 

I've had to do a silly amount of work with [concourse-terraform](https://github.com/Snapkitchen/concourse-terraform/) just to manage migrating inputs from concourse's working directory into the absolute path `/tmp/tfwork/terraform` because terraform requires absolute paths when [running in automation](https://learn.hashicorp.com/terraform/development/running-terraform-in-automation#plan-and-apply-on-different-machines).

If I could just tell the tasks to always use a known absolute path, then I could skip this entire additional burden of file management (which requires testing and is prone to issues).

I understand why vito probably [disagrees](https://github.com/concourse/concourse/issues/1022#issuecomment-296704534), but if I'm aware of the risks I'd still opt-in to the feature.

**Comment by vito** [comment]
Why is the boilerplate any more than just `export WORKDIR=$PWD` at the start of the script? :thinking: 

We intentionally don't expose a var for this to reduce coupling of scripts to Concourse, and because there's already an easy way to do it if you actually need to in your script.

**Comment by eedwards-sk** [comment]
Unfortunately, getting the cwd doesn't solve my use case because the cwd changes every time.

but I think my use case is probably a separate request.

**Comment by ctaymor** [comment]
@vito I think it could, but I don't think there's widespread knowledge that it could. I've seen the pattern (in the first post) of getting the workspace dir based on the relative path of the script on many teams. This becomes painful when you reorganize scripts.

I only recently learned that the scripts run from the workspace dir, so `export WORKDIR=$PWD` will do. My team has started cutting over our scripts to use this pattern instead. I do think that's a good solution, but not a well-known one. Maybe this actually would be best solved by a docs change? (I couldn't find a clear reference in the docs to where the task scripts are run from. One can guess, from the example scripts, but it's not obvious).

Though, to be fair, with many teams who've been using concourse a long time, they might not see a docs change.

**Comment by vito** [comment]
@ctaymor Yeah, sounds fair. It's documented [here](https://concourse-ci.org/task-environment.html) but, to your point, most Pivots are probably past the point of reading these docs again, and this page might have not existed at their first introduction to Concourse. The Concourse tutorial also mentions this [pretty early on](https://concoursetutorial.com/basics/task-inputs/), which we also link to from the home page now.

Maybe this was just growing pains?

**Comment by jamie-pate** [comment]
> It's documented [here](https://concourse-ci.org/task-environment.html)

has moved to https://concourse-ci.org/tasks.html#task-environment
