### ISSUE TITLE
Auth token is shown on browser address bar after logged in and redirected back to web UI

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#2313]
# Bug Report
With new auth changes, now if I logged in through dex and redirected back to concourse page, there is `token=...` showing as url param.

<img width="1675" alt="screen shot 2018-06-21 at 11 27 05 pm" src="https://user-images.githubusercontent.com/1585949/41756516-ee5a642a-75aa-11e8-8a35-15edf1f4cb80.png">

The following can also be handy:

* Concourse version: 3.14.2

**Comment by pivotal-jwinters** [comment]
Yeah this is so fly can extract and store the token in the `.flyrc`.

**Comment by jama-pivotal** [comment]
You can still see a flicker of the token when logging in, but while browsing you can't see the token. Going to accept
