### ISSUE TITLE
failed to stream in to volume

### ISSUE THREAD

**Issue by akamalov** [concourse/concourse#2314]
* Concourse version: ```3.14.0```
* Deployment type (BOSH/Docker/binary): ```binary```
* Infrastructure/IaaS: ```VMware```
* Browser (if applicable): ```Chrome / Firefox```
* Did this used to work? ```Initial Test```

I am using https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/issues/14 pipeline to automate PCF ecosystem backup. Out of three jobs running in parallel , job #1 (```bbr-backup-ert```) and job #2 (```export-om-installation```) finish successfully. However, job #2 (```bbr-backup-director```) errors out with the following message:

```failed to stream in to volume```.

This is it. No more information. Won't tell me why it failed.

![image](https://user-images.githubusercontent.com/7885257/41778562-14c98378-75fd-11e8-9243-2cd538c4f88f.png)

![image](https://user-images.githubusercontent.com/7885257/41778584-20696d38-75fd-11e8-9f9a-fdf83c302fe6.png)

How can I troubleshoot this? Any ideas?

Thanks a lot.

Alex

**Comment by jama-pivotal** [comment]
I dont think we'd be able to help you with the specific error, but to your point @akamalov we can do some work to expose / surface the specific errors...that's why I'm adding the `enhancement` label

**Comment by DaxterM** [comment]
@akamalov I think you might be able to change your start command for `web` or `worker` to redirect to a file  i.e 

```
concourse web \
  --basic-auth-username myuser \
  --basic-auth-password mypass \
  --session-signing-key session_signing_key \
  --tsa-host-key tsa_host_key \
  --tsa-authorized-keys authorized_worker_keys \
  --postgres-host 10.0.32.0 \
  --postgres-user user \
  --postgres-password pass \
  --postgres-database concourse \
  --external-url https://ci.example.com \
  --peer-url http://10.0.16.11:8080 \
  1>>tmp/concourse-web.stdout.log \
  2>>tmp/concourse-web.stderr.log
```

If you do this you may have to take on some additional log clean up responsibilities that syslog might be doing for you. 

Also, I'd expect that you have a more detailed error message in your worker logs due to  ```hLog.Error("failed-to-stream-into-volume", err)```

**Comment by akamalov** [comment]
Thanks @DaxterM! I will reconfigure ATC to log to file to see what the problem is. On another note, I just received a message from BBR team saying that backup did succeed, based message posted, but upload to S3 has failed, apparently - https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/issues/16. Hence, they're suggesting me to talk to Concourse team that maintains S3 resource.

**Comment by akamalov** [comment]
I enabled debug logging, increased memory and storage and restarted the job. The failure apparently is within garden failing to create a container:

```
Jun 26 10:02:27 akjump001 concourse[2222]: {"timestamp":"1530021747.360919237","source":"atc","message":"atc.syncer.bbr-backup-bosh:scheduler.tick.scheduling.try-start-next-pending-build.failed-to-create-container-in-garden","log_level":2,"data":{"build-id":548,"build-name":"1","container":"7ef5313b-3e3d-448f-4207-9de5aeb93a58","error":"failed to stream in to volume","session":"33.4.5.3.2"}}
Jun 26 10:02:27 akjump001 concourse[2222]: {"timestamp":"1530021747.362359762","source":"atc","message":"atc.syncer.bbr-backup-bosh:scheduler.tick.scheduling.try-start-next-pending-build.errored","log_level":1,"data":{"build-id":548,"build-name":"1","error":"failed to stream in to volume","session":"33.4.5.3.2"}}
Jun 26 10:02:27 akjump001 concourse[2222]: {"timestamp":"1530021747.776275873","source":"atc","message":"atc.syncer.bbr-backup-bosh:scheduler.tick.scheduling.try-start-next-pending-build.finish.errored","log_level":1,"data":{"build-id":548,"build-name":"1","error":"failed to stream in to volume","session":"33.4.5.3.2.44"}}
```

**Comment by akamalov** [comment]
Hey @DaxterM 
 
You were right. It was a volume-related problem.  However, I what I discovered was that allocating more volume is not going to solve the problem.  Once volume allocated and Concourse restarted, it will resize docker volume image to match the size allocated to volume. However it **DOES NOT** resize BTRFS, still resulting in an error.  You need to resize BTRFS manually.
 
Below is a Troubleshooting page I wrote:
 
**Troubleshooting: Failed to Stream in to Volume**
 
You try to kick-off concourse BBR pipeline job (or any), but your job errors out wit the following message:
 
```failed to stream in to volume```
 
What does it mean? What this means is that your worker volume is sized too small. Here is what you need to do:
 

1. Add more storage to the VM running Concourse worker
2. Reboot the worker / or restart worker so Concourse would resize loopback volume image appropriately
3. Manually resize BTRFS filesystem (yes, manually, because while Concourse resizes loopback volume to match the allocated size, it does not resize BTRFS filesystem, so you must do it instead.

 
Display current filesystem - BTRFS
 ```
root@akjump001:~# btrfs filesystem usage /opt/concourse/volumes
Overall:
    Device size:      36.65GiB
    Device allocated:      3.02GiB
    Device unallocated:     33.62GiB
    Device missing:        0.00B
    Used:      332.28MiB
    Free (estimated):     34.34GiB  (min: 17.53GiB)
    Data ratio:           1.00
    Metadata ratio:         2.00
    Global reserve:     16.00MiB  (used: 0.00B)
 
Data,single: Size:1.01GiB, Used:296.19MiB
   /dev/loop0    1.01GiB
 
Metadata,DUP: Size:1.00GiB, Used:18.03MiB
   /dev/loop0    2.00GiB
 
System,DUP: Size:8.00MiB, Used:16.00KiB
   /dev/loop0   16.00MiB
 
Unallocated:
   /dev/loop0   33.62GiB
root@akjump001:~#
 ```
Resize BTRFS filesystem:
 ```
root@akjump001:~# btrfs filesystem resize max /opt/concourse/volumes
Resize '/opt/concourse/volumes' of 'max'
 ```
Display filesystem usage:
 ```
root@akjump001:~# btrfs filesystem usage /opt/concourse/volumes
Overall:
    Device size:     232.53GiB
    Device allocated:      3.02GiB
    Device unallocated:    229.51GiB
    Device missing:        0.00B
    Used:      332.28MiB
    Free (estimated):    230.23GiB  (min: 115.47GiB)
    Data ratio:           1.00
    Metadata ratio:         2.00
    Global reserve:     16.00MiB  (used: 0.00B)
 
Data,single: Size:1.01GiB, Used:296.19MiB
   /dev/loop0    1.01GiB
 
Metadata,DUP: Size:1.00GiB, Used:18.03MiB
   /dev/loop0    2.00GiB
 
System,DUP: Size:8.00MiB, Used:16.00KiB
   /dev/loop0   16.00MiB
 
Unallocated:
   /dev/loop0  229.51GiB
root@akjump001:~#
 ```
Once resized, this error will go away.

**Comment by DaxterM** [comment]
@vito @jama-pivotal  interested in your thoughts on if the concourse worker should be able to detect when it's workdir has increased on startup and manage btrfs file system size accordingly?  I think this would  only provide value to  binary deploys as bosh would would recreate if you changed the vmtype
