### ISSUE TITLE
Error 'pq: insert or update on table 'volumes' violates foreign key constraint 'fkey_container_id'

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2319]
# Bug Report

We are occasionally seeing the following error in our tasks:
  ```pq: insert or update on table 'volumes' violates foreign key constraint 'fkey_container_id'```

This appears to go away if the user re-tries the task once again, but this can be no only a nuisance but also reputation-ally undesirable.

Environment:
* Concourse version: 3.9.2
* Deployment type (BOSH/Docker/binary): BOSH (database on separately deployed)
* Infrastructure/IaaS: Openstack

Are there any thoughts about what details would be required to debug this further or if this is a known issue.  (Searches do find _similar_ issues, but not the same.)

Thank you, in advance, for your help and explanation.

**Comment by JohannesRudolph** [comment]
possibly related: https://github.com/concourse/concourse/issues/2108

**Comment by colmtuohy** [comment]
+1

**Comment by vito** [comment]
That error means the container row was removed while Concourse was trying to do something with it. The only way I can really imagine that happening is if the worker that the container was placed on was pruned.

**Comment by draeron** [comment]
if it can help, we run concourse on kubernetes, we started seeing this issue when we upgrade the ressource limit/request of our postgres database and it rebooted. We also had a worker node which was stalled and eventually we had to prune manually.
