### ISSUE TITLE
`log in to view` feels misleading

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2320]
# Feature Request

## What challenge are you facing?

When I'm logged in as myself, looking at the build page for a job that I'm not authorized to view (for example, the pipeline has been exposed, but I'm not a member of the team to which it belongs), I see a button saying `log in to view`. When I click it, I'm redirected to a login page. But I'm already logged in, and even if I re-login, nothing changes! I feel confused.

Something similarly confusing can happen when I'm not logged in, and then I click the `log in to view` button and log in, only to see that confusing button once again.

## A Modest Proposal

That message could say `you're not authorized to view this` or `not a member of the required team` or `not a member of <actual name of team>`. Also the UI element maybe shouldn't be a button that redirects to a login page, because authentication really isn't the problem in that case. Maybe just some text.

**Comment by jama-pivotal** [comment]
Prioritizing highly since we need to get this resolved before we push Users out in a release. 

I agree with @pivotal-jamie-klassen proposal to swap it out for a message and nuke the button. I'd prefer the message to read: `You are  not authorized to view the details of this pipeline`

**Comment by pivotal-jwinters** [comment]
![screen shot 2018-06-27 at 2 54 12 pm](https://user-images.githubusercontent.com/1072233/41993630-10ab3194-7a1a-11e8-922e-e717e982dc4c.png)

Something like this styling?

**Comment by jama-pivotal** [comment]
@pivotal-jwinters @Lindsayauchin We should do a design with metal detectors like at an airport security queue!

**Comment by jama-pivotal** [comment]
After clicking around, I'd also suggest we not use the specific phrase "resource" since you can get this error message when viewing a job / build! Maybe just "You are not authorized to view this content" ....then again that's quite boring

**Comment by Lindsayauchin** [comment]
In light of IPM discussion, we are going forward with a 401 error with a nice illustration. 

<img width="590" alt="screen shot 2018-07-17 at 5 22 24 pm" src="https://user-images.githubusercontent.com/27746614/42846138-14174c1a-89e6-11e8-9a52-90b72ed4821f.png">

<img width="210" alt="screen shot 2018-07-17 at 5 22 38 pm" src="https://user-images.githubusercontent.com/27746614/42846140-16592b2e-89e6-11e8-80ff-e9e287bb6127.png">

Asset:
[passport_officer_ic.svg.zip](https://github.com/concourse/concourse/files/2203446/passport_officer_ic.svg.zip)

**Comment by xtremerui** [comment]
@Lindsayauchin should it match to the style of 404 not found page? Right now one is colorful and the positions of status code are different.

<img width="309" alt="screen shot 2018-07-19 at 5 08 34 pm" src="https://user-images.githubusercontent.com/1585949/42970099-667fc5b8-8b76-11e8-8efa-0bb151f2c63b.png">

**Comment by jama-pivotal** [comment]
I just did some acceptance with Lindsay. She its fine and maybe we can look at new icons down the road.
