### ISSUE TITLE
Paused jobs that would run if they weren't paused show up in dashboard as if they were running

### ISSUE THREAD

**Issue by astrieanna** [concourse/concourse#2323]
# Bug Report

In the following pipeline, all the left-hand column jobs are paused except the bottom one. Despite this, there are two with the moving-diagonal-"I'm running" stripes.
 
![screen shot 2018-06-26 at 5 24 55 pm](https://user-images.githubusercontent.com/1205394/41940257-1dc906c6-7966-11e8-84dd-b598973f60cd.png)
[From this pipeline](https://buildpacks.ci.cf-app.com/dashboard)

These jobs would like to run, but are waiting to be unpaused before starting. If they aren't going to look just like not-trying-to-run paused jobs, I'd expect blue diagonal stripes (to distinguish them from actually running jobs).

* Concourse version: v3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Probably not.

**Comment by pivotal-jamie-klassen** [comment]
If I'm understanding properly - the idea here is that in the pipeline preview, a job's 'paused' status takes priority over whatever its most recent build status is, or whether it has a pending build. If this is the case, I agree.
