### ISSUE TITLE
Feature - Don't kill previous task container until new build is complete

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#2327]
# Feature Request

## What challenge are you facing?

Sometimes you have a) a job that takes a long time and b) you want to debug the last failure while the next build is running. 

It seems like the current behaviour is to clean up the old build's containers as soon as the new build gets started. This means that I can't continue to debug my last failure using `fly hijack` while the new build is running because the old build's containers are already cleaned up.

## A Modest Proposal

Don't clean up the containers for a previous build of a job until the new build of that job has completed, not merely started.

**Comment by xtreme-gavin-enns** [comment]
Wait, I might be wrong about this? I had "connection closed by peer" or "remote host" or something but then later on it seems I was still connected. But then I closed the terminal window so I can't go back and check. 

Lol. Maybe delete this? I'll make it again if I can prove it!

**Comment by jama-pivotal** [comment]
oookay, closing for now
