### ISSUE TITLE
Show what resource change or user triggered the build

### ISSUE THREAD

**Issue by zrob** [concourse/concourse#233]

**Comment by jdub** [comment]
Thought: Showing the user (or 'a user' if unauthenticated) for manually triggered builds would be extra fancy. Perhaps even distinguishing between web and api calls?

**Comment by cjcjameson** [comment]
Bump for both the original request and jdub's comment -- we think this is a good idea and would be good for an external contributor. Can you add the appropriate "help requested" tag?

**Comment by vito** [comment]
@cjcjameson Sure!

For anyone who looks at this as a result:

* Building @jdub's comment, it sounds like we some sort of "created by" attribute of a build, which can either be a resource (or multiple resources) with `trigger: true` changing, or a user triggering it manually. Not sure how this should look in the database.
* For knowing the user, we'll want to start extracting that information as part of the OAuth flow, so we can say "@vito" triggered it, not just "authenticated user". We don't have this information yet.

**Comment by mariash** [comment]
going to close this issue in favor of this https://github.com/concourse/concourse/issues/194
