### ISSUE TITLE
Inaccurate resource-error alerts on dashboard

### ISSUE THREAD

**Issue by astrieanna** [concourse/concourse#2333]
# Bug Report

On the dashboard, I believe that the orange triangle marks pipelines with resource errors.
![screen shot 2018-06-29 at 12 09 15 pm](https://user-images.githubusercontent.com/1205394/42102950-8ac65dba-7b95-11e8-814f-69dbaf759431.png)

However, when I look at this pipeline, there are no orange resources.
https://buildpacks.ci.cf-app.com/teams/main/pipelines/cflinuxfs2

The following can also be handy:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? No idea. It also *does* correctly flag actual resource errors & has gone away when they're fixed on other pipelines. I just can't figure out what it's upset about with this one.

**Comment by jama-pivotal** [comment]
WEIRD, we might reach out to you directly to get some more info about the pipeline. Prioritizing highly, because this can surely cause some pain

**Comment by astrieanna** [comment]
This is not just the one pipeline - we have 7 pipelines where I can't find any orange resources but the dashboard shows an orange triangle.

**Comment by alpha-er** [comment]
We've had these as well but we figured out the resources in error were output resources in the pipeline. They're not obvious when viewing the pipeline because they weren't orange.

**Comment by jama-pivotal** [comment]
Update: we started looking at this with @mhuangpivotal and it looks like there IS a resource "failing" in your case @astrieanna , it was https://buildpacks.ci.cf-app.com/teams/main/pipelines/cflinuxfs2/resources/cflinuxfs2-cf-deployment  

which failed to check

So we're looking into the difference in logic to see what makes more sense

**Comment by mhuangpivotal** [comment]
As @jama-pivotal mentioned above, this is actually an issue with the pipeline view where output resources with checking erorrs are not shown as `errored`. The dashboard is reporting the correct status.

We made a fix to the pipeline view logic so the error indication will be consistent with the dashboard.

**Comment by jama-pivotal** [comment]
Accepting based on some testing I did on wings. Fix should be coming in next release @astrieanna !
