### ISSUE TITLE
Restrict use of "/" in job and resource names

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#2336]
# Feature Request

## What challenge are you facing?
Now "/" in job and resource name introduces complication on escape url #2211 #1892 #1877 #1906
```
/teams/main/pipelines/test-pipeline/jobs/some%2Fjob
/teams/main/pipelines/test-pipeline/jobs/some%2Fresource
```
and fly flag validation #2306
```
fly execute -j pipeline/some/job
fly check-resource -r pipeline/some/resource
```
In the future when we have multi-level of jobs/resources this might lead to more trouble.

## A Modest Proposal
"/" won't consider as a valid char in job/resource name anymore. Tasks needs to be done

- [ ] clean up UI tests that allowing job/resource name with "/"

- [ ] remove unnecessary url escape in web if applicable

- [ ] change `fly set-pipeline` to return error when there are "/" in job/resource name in config yaml

- [ ] update doc to notify user so they could update their pipeline yaml accordingly

**Comment by xtremerui** [comment]
This lead to a bigger question: what kind of character should we allow in job/resource names?

Taking kubernetes for example: it allows alphanumeric, `.`, `-` and`_`, beginning and ending with alphanumeric only.
[kebunetes label syntax](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels#syntax-and-character-set)

**Comment by dprotaso** [comment]
@xtremerui 
> "/" won't consider as a valid char in job/resource name anymore.

Given there are no restrictions on the job & resource name any changes will break existing pipelines. Effectively this would be a backwards incompatible change.

![throwingcaution-300x201](https://user-images.githubusercontent.com/18562/49086473-9789cb00-f222-11e8-8c6e-60c49682704f.jpeg)

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/3985
