### ISSUE TITLE
VaultAPI RenewSelf is called with increment of "0"

### ISSUE THREAD

**Issue by andrew-edgar** [concourse/concourse#2339]
# Bug Report

VaultAPI RenewSelf is called with increment of "0" which does NOT extend the vault token.  When the original token expires then subsequent vault renew requests fail with 403.   The code needs to be updated to pass in time (hopefully the original expiry time) so that the renew will extend.

This is detailed in the Vault code ...

https://www.vaultproject.io/docs/concepts/lease.html#lease-durations-and-renewal

Which means that it should extend the lease by the time listed.  But we always say "0" so it does not get extened.  We end up in a situation where our new requests to renew fail with 403.

* Concourse version: 3.14
* Deployment type (BOSH/Docker/binary): BOSH

**Comment by zmb3** [comment]
I too have seen this problem, but I'm not certain the `0` is what's causing the problem.

From: https://www.vaultproject.io/api/auth/token/index.html#increment-1

>  An optional requested lease increment can be provided. This increment may be ignored. 

Note however that `increment` is actually a string like `24h` or `60m`, and the ATC's API expects an `int` - that's probably not right.
