### ISSUE TITLE
No way to log out from UI

### ISSUE THREAD

**Issue by mtekel** [concourse/concourse#234]
When you log in to concourse, either using basic auth or github based authentication, the interface:
* doesn't indicate that you are logged in (it could print the user name - this is useful when you're working with multiple instances of concourse which have same pipelines, e.g. dev/test/staging/production and you have different logins to each)
* there is no log out button. I tried really hard to find it but no success. There is `/login` URL path, but no `/logout`

**Comment by superbeeny** [comment]
+1

**Comment by jadekler** [comment]
+1
