### ISSUE TITLE
Can't intercept containers GKE

### ISSUE THREAD

**Issue by jonasdkhansen** [concourse/concourse#2340]
# Bug Report

I can't intercept any containers running. If i try to do a fly -t ci intercept -j my-pipe/my-job i get a list of the steps been running:
```
1: build #68, step: master-image, type: get
2: build #68, step: git-checkout-pr, type: get
3: build #68, step: git-checkout-pr, type: put
4: build #68, step: test-pr, type: task
choose a container:
```
And if i choose any of them, it just exit with no error. I have also tried doing a -b -s but then i get a 
```
no containers matched your search parameters!
they may have expired if your build hasn't recently finished.
```
The pipeline just ran, and if i do a fly -t ci containers, i can see that the container is stilling up and with the right pipeline, job and step.

If i add the --verbose to intercept, there is no errors only 200, and it exit with no errors.

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): Helm
* Infrastructure/IaaS: GKE

**Comment by jtarchie** [comment]
Do the containers have bash in them?

**Comment by peckeltw** [comment]
@jonasdkhansen as mentioned by @jtarchie make sure your container has Bash installed as this is the default shell for intercept/hijack. If not, simply use `[...] intercept -j [YOUR_PIPELINE/YOUR_JOB] sh` to use sh shell.
