### ISSUE TITLE
fly "--open-browser" broken on MacOS with any browser

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#2342]
# Bug Report

The fly "--open-browser" option that comes with Concourse 3.14 is broken on MacOS with any browser, at least when using Bitbucket OAuth.

On MacOS, issuing

```
fly --target developers login --concourse-url=https://builder.example.com \
    --team-name=developers --open-browser
```

does open the default browser, but adds some garbage at the end of the URL. Instead of

```
https://builder.example.com/auth/bitbucket-cloud?team_name=developers&fly_local_port=54057
```

it passes to the browser the trailing `%0A`:

```
https://builder.example.com/auth/bitbucket-cloud?team_name=developers&fly_local_port=54057%0A
```

This happens with Chrome, Firefox and Safari.

The following can also be handy:

* Concourse version: 3.14.1
* fly version: 3.14.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome, Firefox, Safari
* Did this used to work? "--open-browser" is a new feature of 3.14

**Comment by scnewma** [comment]
Looks like this issue was fixed [here](https://github.com/concourse/fly/pull/235).

**Comment by marco-m** [comment]
@scnewma ah yes, it looks like the same bug indeed.

**Comment by xtremerui** [comment]
duplicated. Closing.

**Comment by marco-m** [comment]
Adding the same link in a way that should be detected by github
concourse/fly#235
