### ISSUE TITLE
ATC uses 100% CPU and ~40 DB connections

### ISSUE THREAD

**Issue by wagdav** [concourse/concourse#2346]
Hi there!

Thanks for making Concourse!

# Bug Report

Just after updating from 3.13.0 to 3.14.1 we noticed 100% CPU usage and a 10x increase in the DB connections on the ATC:

* the high CPU usage lasts for about 3 minutes with a period of 5 minutes ![atc-cpu](https://user-images.githubusercontent.com/514775/42284073-b15bc752-7fab-11e8-8dbb-0f0bf782c700.png)
* when the CPU usage is high, the ATC seems to be busy with checking resources
* the "build scheduling duration" shows a peaks of ~20minutes, similarly to the CPU load, with 5 minutes period ![atc-scheduling-duration](https://user-images.githubusercontent.com/514775/42284100-c41c8458-7fab-11e8-8474-204845c1bed2.png)
 * the worker load graph forms a sawtooth like shape, also with 5 minutes period ![worker-load](https://user-images.githubusercontent.com/514775/42284126-d7010760-7fab-11e8-9090-1ec0df38d4d2.png)
 * the number of database connections goes as high as 40 (the nominal value is around 4) also the number of database accesses increases ![atc-db](https://user-images.githubusercontent.com/514775/42284148-e1ed747e-7fab-11e8-939d-18b52e208c61.png)

In relation to this problem (not sure if it's a cause or effect) the our SSM credential store starts to throttle and the resource checks fail.

Very similar behavior is reported in
* this issue #2300 
* in this forum post https://discuss.concourse-ci.org/t/increased-db-connections-after-upgrade-to-3-14-1/301

I have the _feeling_ that when a resource check fails, the ATC leaks DB (and possibly other) handles. This results in an avalanche of queries to the credential store. 

The following can also be handy:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work? yes, in 3.13.0 it worked fine

# Workaround

We managed to stabilize the system by increasing the resource check interval from 1 minute to 5 minutes.

**Comment by jama-pivotal** [comment]
WEIRD, and you're not using CredHub at all? Just Amazon SSM for cred management?

**Comment by wagdav** [comment]
@jama-pivotal Thanks for handling this! No, we don't use CredHub at all. We store our secrets in AWS SSM.

**Comment by vito** [comment]
@wagdav High CPU usage on the ATC is what jumps out the most here to me. Maybe we could do some profiling and try to see where the CPU time is being spent? The ATC by default runs a debug server listening on `127.0.0.1:8079`, so you could try running this on the `web` node to capture a 30 second CPU profile (I guess be sure to run this when the CPU usage is at its highest):

```
go tool pprof http://127.0.0.1:8079/debug/pprof/profile
```

The other metrics could possibly be a result of just *everything* being slowed down by CPU contention, so this seems like the most interesting place to start. Almost everything else the ATC does is network/IO bound, so high CPU usage is kind of telling.

**Comment by wagdav** [comment]
@vito Thanks for the profiling tip, I managed to set it up.  The bad news is that I couldn't trigger this behavior anymore :-(  What I got out of pprof seems nominal:

```
Showing top 10 nodes out of 513 (cum >= 1540000000ns)
      flat  flat%   sum%        cum   cum%
         0     0%     0% 2800000000ns 30.87%  github.com/concourse/atc/radar.(*intervalRunner).Run
         0     0%     0% 2550000000ns 28.11%  github.com/concourse/atc/radar.(*Runner).scanResources.func1
         0     0%     0% 2540000000ns 28.00%  github.com/concourse/atc/radar.(*resourceScanner).Run
         0     0%     0% 2540000000ns 28.00%  github.com/concourse/atc/radar.(*resourceScanner).scan
         0     0%     0% 2470000000ns 27.23%  runtime.systemstack
         0     0%     0% 1760000000ns 19.40%  crypto/tls.(*Conn).Handshake
         0     0%     0% 1730000000ns 19.07%  crypto/tls.(*Conn).clientHandshake
         0     0%     0% 1730000000ns 19.07%  crypto/tls.(*clientHandshakeState).handshake
         0     0%     0% 1570000000ns 17.31%  crypto/tls.(*clientHandshakeState).doFullHandshake
         0     0%     0% 1540000000ns 16.98%  net/http.(*persistConn).addTLS.func2

```

It's in our production system so my experimentation options were limited.  The parameters I could reproduce were:

* (virtual) hardware conditions (in particular the instance size of the DB and ATC instance)
* ATC command line options (most importantly --resource-check-interval 1s)
* the SSM throttling exception as the checks are too frequent

What I couldn't reproduce:

* the number of pipelines (hence the total number of resource checks) were different because in the meantime we introduced a pipeline reaper that destroys all the feature branch pipelines without their backing branch.  This is to avoid failing checks on the git resource.


I also tried to see how the behavior is affected if there's a parameter in the resource definition, like so:

```
resources:
 - name: repo.git
   type: git
   source:
     uri: git@repo_url
     private_key: ((from_ssm_parameter_store))
     branch: ((from_the_command_line))
```

Adding a handful of simulated pipelines like this will make the resource check fail consistently with 

```
Finding variable 'from_ssm_parameter_store': ThrottlingException: Rate exceeded
    status code: 400, request id: 4f783c2d-5c44-4e15-a372-71c613e3b71a
```

My understanding is that the ATC is using the Go AWS SDK to connect to the SSM service.  Shouldn't the SDK respect the rate limits? That is if the rate limit is exceeded the SDK automatically backs off (looks like this is implemented in the [default retryer](https://github.com/aws/aws-sdk-go/blob/master/aws/client/default_retryer.go))

**Comment by ebilling** [comment]
We ran into the same issue, and got around it by changing the frequency from 1m to 5m as well.

But we are seeing a very different profile.  We reset back to 1m to capture a profile though.

Maybe this will be helpful:

(pprof) cum
(pprof) top 20
Showing nodes accounting for 0, 0% of 31.87s total
Dropped 813 nodes (cum <= 0.16s)
Showing top 20 nodes out of 337
      flat  flat%   sum%        cum   cum%
         0     0%     0%     24.49s 76.84%  github.com/cenkalti/backoff.Retry
         0     0%     0%     24.49s 76.84%  github.com/cenkalti/backoff.RetryNotify
         0     0%     0%     24.36s 76.44%  database/sql.(*DB).conn
         0     0%     0%     24.34s 76.37%  database/sql.(*dsnConnector).Connect
         0     0%     0%     24.34s 76.37%  database/sql.dsnConnector.Connect
         0     0%     0%     24.34s 76.37%  github.com/concourse/atc/db.(*connectionRetryingDriver).Open
         0     0%     0%     24.34s 76.37%  github.com/concourse/atc/db.(*connectionRetryingDriver).Open.func1
         0     0%     0%     24.34s 76.37%  github.com/lib/pq.(*drv).Open
         0     0%     0%     24.34s 76.37%  github.com/lib/pq.DialOpen
         0     0%     0%     24.34s 76.37%  github.com/lib/pq.Open
         0     0%     0%     24.29s 76.22%  github.com/lib/pq.(*conn).ssl
         0     0%     0%     23.81s 74.71%  github.com/lib/pq.(*conn).verifyCA
         0     0%     0%     20.99s 65.86%  github.com/concourse/atc/radar.(*intervalRunner).Run
         0     0%     0%     17.60s 55.22%  database/sql.(*DB).QueryContext
         0     0%     0%     17.60s 55.22%  database/sql.(*DB).query
         0     0%     0%     16.25s 50.99%  github.com/concourse/atc/radar.(*Runner).scanResources.func1
         0     0%     0%     16.25s 50.99%  github.com/concourse/atc/radar.(*resourceScanner).Run
         0     0%     0%     16.25s 50.99%  github.com/concourse/atc/radar.(*resourceScanner).scan
         0     0%     0%     14.84s 46.56%  github.com/Masterminds/squirrel.QueryRowWith
         0     0%     0%     14.77s 46.34%  github.com/Masterminds/squirrel.(*selectData).QueryRow
(pprof) flat
(pprof) top 20
Showing nodes accounting for 22.82s, 71.60% of 31.87s total
Dropped 813 nodes (cum <= 0.16s)
Showing top 20 nodes out of 337
      flat  flat%   sum%        cum   cum%
     7.81s 24.51% 24.51%      7.81s 24.51%  math/big.addMulVVW
     4.08s 12.80% 37.31%      8.90s 27.93%  math/big.nat.divLarge
     1.49s  4.68% 41.98%      2.62s  8.22%  runtime.scanobject
     1.13s  3.55% 45.53%      1.13s  3.55%  runtime.memmove
     1.11s  3.48% 49.01%      8.91s 27.96%  math/big.nat.montgomery
     0.90s  2.82% 51.84%      0.90s  2.82%  math/big.subVV
     0.79s  2.48% 54.31%      0.79s  2.48%  math/big.mulAddVWW
     0.79s  2.48% 56.79%      0.86s  2.70%  runtime.heapBitsForObject
     0.76s  2.38% 59.18%      0.76s  2.38%  runtime.memclrNoHeapPointers
     0.64s  2.01% 61.19%      4.10s 12.86%  runtime.mallocgc
     0.55s  1.73% 62.91%      0.55s  1.73%  runtime._ExternalCode
     0.42s  1.32% 64.23%      0.46s  1.44%  syscall.Syscall
     0.38s  1.19% 65.42%      1.52s  4.77%  math/big.basicMul
     0.33s  1.04% 66.46%      0.33s  1.04%  math/big.nat.norm
     0.33s  1.04% 67.49%      0.59s  1.85%  runtime.greyobject
     0.28s  0.88% 68.37%      0.28s  0.88%  math/big.greaterThan (inline)
     0.28s  0.88% 69.25%      0.30s  0.94%  runtime.(*bucket).mp
     0.26s  0.82% 70.07%      0.26s  0.82%  math/big.shlVU
     0.25s  0.78% 70.85%      0.25s  0.78%  runtime.nextFreeFast (inline)
     0.24s  0.75% 71.60%      0.30s  0.94%  runtime.step

**Comment by ebilling** [comment]
Is anyone actively looking at this?  It seems as if the CPU is showing up due to TLS negotiation because it's trying to reconnect to the Postgres DB.  Perhaps the reason most people aren't seeing this is because they aren't using encrypted connections.

This call graph may be helpful to someone with more background in this code than me.

 [
[atc.pprof.pdf](https://github.com/concourse/concourse/files/2489593/atc.pprof.pdf)
](url)

**Comment by marco-m** [comment]
@ebilling which version of Concourse are you using ? My understanding is that Concourse 4.x fixes this problem. We opened this ticket on Concourse 3.x

**Comment by ebilling** [comment]
We are running an older version, 3.14.  We will definitely prioritize upgrading and see if the problem persists.

**Comment by wagdav** [comment]
We think the issue was that the ATC instance was simply too small for our deployment. Resource checks also consume resources so increasing check interval got us out from this state.

The dithering CPU load graph was because we used a T2 burstable instance which consumed all its CPU credits (again because of the heavy load).

**Comment by ebilling** [comment]
I still see this issue as of v5.1.0.  The issue is that the system is not re-using the TLS connections to Postgres. We could just throw more hardware at the problem, but this is a fundamental flaw in how the system is using the db connections.  I'm going to try to take a look at it in the next couple of weeks and see if there is a "simple" fix in there somewhere.

**Comment by ebilling** [comment]
After some investigation, I'm seeing that the lock connection is separate and created with a max idle and max open of 1, so what I think might be happening is that on a very active system, you have many threads trying to get a lock, and as a result, they keep running into these limits and closing connections or having to wait to get the one open connection.  I'm going to try running a test with a higher limit and see what I get.

**Comment by vito** [comment]
@ebilling Thanks for looking into this! Would you mind opening an issue for what you're seeing so the discussion doesn't get lost? This one was closed by the OP so I'm not sure if I should re-open.
