### ISSUE TITLE
Jobs don't get triggered; fixed by restarting `web` instance

### ISSUE THREAD

**Issue by astrieanna** [concourse/concourse#2347]
# Bug Report

This may have been reported before, but we've been seeing (about weekly) concourse stop triggering jobs. This is fixed by having BOSH restart the `web` instance.

We aren't sure what causes it, but the solution works every time. There is no actual error display from concourse; we just notice when we expect a pipeline to be running, and it isn't, and the resource is displaying the correct state but the job isn't triggering. As soon as we restart web, the job gets triggered.

This effect is seen across all our pipelines, so it's not a job/resource/pipeline specific effect.

The following can also be handy:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: gcp
* Did this used to work? This is not new; the symptom and solution has been known for a long time.

**Comment by pn-santos** [comment]
This _seems_ the same as #2010 and #2150

**Comment by pn-santos** [comment]
This _seems_ the same as #2010 and #2150

**Comment by astrieanna** [comment]
For context, this has been happening for a very long time (at least over a year). We just wanted to make sure it was reported.

**Comment by astrieanna** [comment]
This looks more similar to #2010 because our resources *do* show the new versions when the jobs aren't triggering.

Also, the vms appear healthy and not overloaded before we restart the `web` one.

**Comment by heycait** [comment]
We're also experiencing this issue where new resources are pulled but the trigger jobs aren't running. However, we are using a nightly build of 4.0.0.

cc @davewalter @mcwumbly

**Comment by pivotaljohn** [comment]
Ran into these symptoms again.  Our workaround is to have a Concourse job that restarts the web VMs every night at 2am.

- Concourse version: 4.0.0

@mcwumbly

**Comment by vito** [comment]
This might be related to https://github.com/concourse/concourse/issues/2438

Next time someone sees this, could you collect a [stack dump](https://github.com/concourse/concourse/wiki/Troubleshooting#taking-a-stack-dump) and maybe look in the ATC logs for anything that sticks out?

**Comment by jfmyers9** [comment]
Sup @vito. We ran into this today. Attached a goroutine dump of the atc when it was happening.
[atc-goroutines.txt](https://github.com/concourse/concourse/files/2389954/atc-goroutines.txt) Let us know what you find.

**Comment by vito** [comment]
Going to tentatively close this as #2010 was fixed. This will be in v5.0.0. If it happens again (after 5.0 is out) let us know! There were a flurry of GitHub issues about this and #2010 was the only one that appeared to have a smoking gun.
