### ISSUE TITLE
Unnecessary scrollbar in build page on Chrome

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#2348]
# Bug Report

In Chrome, the build page has a scrollbar even when the output is less than a page:

<img width="1270" alt="screen shot 2018-07-05 at 2 29 17 pm" src="https://user-images.githubusercontent.com/1919762/42341123-fccac256-805f-11e8-8721-97f27fc6f2a5.png">

Firefox and Safari do not have the same issue.

The following can also be handy:

* Concourse version: v3.14.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Not sure

**Comment by pivotal-jamie-klassen** [comment]
after further investigation, this seems to have been caused by a chrome extension.
