### ISSUE TITLE
Concourse seems to have a limit of 256 containers per worker

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#235]
Hi gang,

We're seeing the following error in our CI:
```
insufficient subnets remaining in the pool
```

And when we run `fly workers`, we see that one worker has 256 containers:
```
$ fly -t concourse workers
name                                  containers  platform  tags
6077fe29-fd93-4eaf-8a34-cb09fd0cb3dc  256         linux     none
bcb69d65-ccf7-4a34-ac7e-b31aae4af20b  0           linux     aws
c4014445-7173-4eb8-8686-a25c102668a2  109         linux     none
d45d970c-a817-487a-8efd-711b53881995  0           linux     vsphere
e550fbac-063c-422d-b58f-300214992521  134         linux     none
```

Is this 256 container limit artificially imposed / is there some workaround to increase this limit?

**Comment by xoebus** [comment]
Thanks for the bug report.

This error comes from Garden we just bubble it up. @julz @goonzoid - Is there a way to increase this limit? If so, is it documented anywhere? Should it be increased?

**Comment by julz** [comment]
You can increase max_containers [here](https://github.com/cloudfoundry-incubator/garden-linux-release/blob/develop/jobs/garden/spec#L67), if you do this you also likely want to increase [the subnet pool size](https://github.com/cloudfoundry-incubator/garden-linux-release/blob/develop/jobs/garden/spec#L71) to make sure it has enough IPs (the default /22 CIDR only gives you enough for 256 containers).

**Comment by xoebus** [comment]
:+1: Thanks Julz.

**Comment by zachgersh** [comment]
just for history - I am going to add to this issue and note that at present garden-runc doesn't respect the `max_containers` setting for anyone that may stumble into this issue when searching. The true way to raise the number of containers is to bump the subnet pool size that @julz mentioned but going much about 300 seems to make the network throughput on the worker slow for every other container.
