### ISSUE TITLE
Long-running ATC Go-routines

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2350]
# Bug Report

We have experienced partial outages since upgrading to 3.13.0 where builds are pending for quite some time while retrieving custom resources.  What's been found is that go-routines are running for quite some time (1971 minutes...) with no end in sight.  We resolved this by restarting the ATC services, but we now see that there is a potential to improve here.

Is there some way to have a timeout for the routines across the system so that there would at least be some failure?

Example:
```
goroutine 1 [select, 1971 minutes]:
github.com/tedsuo/ifrit.Invoke(0x199b340, 0xc42049abd0, 0xc4207628a0, 0x2)
	/var/vcap/packages/atc/src/github.com/tedsuo/ifrit/process.go:29 +0x11b
github.com/concourse/atc/atccmd.(*ATCCommand).Execute(0xc420458c80, 0xc420516000, 0x0, 0x7c, 0x0, 0x0)
	/var/vcap/packages/atc/src/github.com/concourse/atc/atccmd/command.go:321 +0xb7
main.main()
	/var/vcap/packages/atc/src/github.com/concourse/atc/cmd/atc/main.go:24 +0xe4

goroutine 18 [syscall, 1971 minutes]:
os/signal.signal_recv(0x0)
	/var/vcap/data/packages/golang/1c2ef7b133c34600b3e4bc21bf13189a0b9533d6/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/var/vcap/data/packages/golang/1c2ef7b133c34600b3e4bc21bf13189a0b9533d6/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/var/vcap/data/packages/golang/1c2ef7b133c34600b3e4bc21bf13189a0b9533d6/src/os/signal/signal_unix.go:28 +0x41
```

The following can also be handy:
* Concourse version: 3.13.0 (stemcell 3468.22)
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
* Browser (if applicable):
* Did this used to work?

**Comment by jama-pivotal** [comment]
Linking to #787 and #1284 for your reference. Those two issue that are being tackled next by the Runtime track

**Comment by keithkroeger** [comment]
Thank you...related to limits for interaction so that the worker doesn't allow itself to be destroyed by users.

**Comment by topherbullock** [comment]
That goroutine is the first one spawned by main `atccmd.command` in the ATC binary, which kicks off all of the sub-components; this is basically giving you the uptime of the ATC.
https://github.com/concourse/concourse/blob/85124fbc08f28c41e3b777752d1b75ed3f212eaa/atc/atccmd/command.go#L318-L325

We have a couple of issues around operator insight and control over the long-running components and periodic operations of the ATC:
-  #2290 : see what goroutines are are related to a pipeline 
-  #2473 : allow pausing of components which run periodically (resource checks, scheduling, etc)

**Comment by xtremerui** [comment]
closing stale issue
