### ISSUE TITLE
Why using UAA scope cloud_controller.read?

### ISSUE THREAD

**Issue by drnic** [concourse/concourse#2354]
In https://concourse-ci.org/authentication.html#section_configuring-the-uaa-client it requires that the concourse UAA client have the scope `cloud_controller.read` - why did you reuse a scope that's meaningful to Cloud Foundry API resource server? Perhaps we could move to `concourse.read` etc for the ATC API as an OAuth resource server?

**Comment by pivotal-jwinters** [comment]
@drnic we need this scope so we can retrieve the user's cf `org`/`space` memberships.
