### ISSUE TITLE
Allow to configure userinfo endpoint for oauth/oidc auth

### ISSUE THREAD

**Issue by thomasdarimont** [concourse/concourse#2356]
# Feature Request

## What challenge are you facing?

When trying to configure concourse to authenticate against [Keycloak](https://www.keycloak.org/) via OIDC or with plain Oauth2 one cannot configure the userinfo Endpoint that should be used. 
concourse seems to infer the userinfo endpoint from the auth-URL which is wrong in case of Keycloak.
## A Modest Proposal

It would be great if one could configure the userinfo endpoint explicitly with a configuration option.
```
--generic-oauth-userinfo-url=
--generic-oauth-oidc-userinfo-url= 
```
* concourse version: 3.14.1

**Comment by jama-pivotal** [comment]
tagging @PavelTishkin since he wrote the original OIDC connector 

also, @pivotal-jwinters would we be able to configure the userinfo endpoint with our generic oauth connector in dex?

**Comment by xtremerui** [comment]
https://github.com/concourse/concourse/blob/405cd5f1a7aa6f0f19a86d3a6255d9f3bbf7f573/skymarshal/skycmd/oauth_flags.go#L26 is implemented and released.

Closing this issue.
