### ISSUE TITLE
tsa.connection.handshake-failed on concourse-web pod

### ISSUE THREAD

**Issue by wpalmeri** [concourse/concourse#2357]
# Bug Report

A vanilla helm install on my AWS k8s cluster will not start up cleanly. The `concourse-web` pod is tight-loop spamming the logs (thousands per second) with `tsa.connection.handshake-failed` messages. concourse-web, concourse-worker, and concourse-postgresql are all running and passing liveness/readiness probes. The logs on the workers look healthy.

```kubectl get pods -n concourse -o wide
NAME                                       READY     STATUS    RESTARTS   AGE       IP               NODE
qa-concourse-postgresql-854d555fd7-dc4jb   1/1       Running   0          1h        192.168.73.153   ip-10-42-16-211.us-west-2.compute.internal
qa-concourse-web-796b755c6b-ft7f5          1/1       Running   0          52s       192.168.112.36   ip-10-42-24-245.us-west-2.compute.internal
qa-concourse-worker-0                      1/1       Running   1          56m       192.168.73.154   ip-10-42-16-211.us-west-2.compute.internal
qa-concourse-worker-1                      1/1       Running   0          56m       192.168.73.206   ip-10-42-23-170.us-west-2.compute.internal
```

Example logs:
```
{"timestamp":"1531017163.291735888","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.119.128:62039","session":"4616655"}}
{"timestamp":"1531017163.291858912","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"10.42.24.245:27303","session":"4616665"}}
{"timestamp":"1531017163.292025328","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.73.192:17695","session":"4616662"}}
{"timestamp":"1531017163.292572021","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"10.42.24.245:27298","session":"4616664"}}
{"timestamp":"1531017163.292642832","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.90.128:9508","session":"4616660"}}
{"timestamp":"1531017163.292761087","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.73.192:17699","session":"4616668"}}
{"timestamp":"1531017163.292785168","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.119.128:62051","session":"4616673"}}
{"timestamp":"1531017163.292829514","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.73.192:17694","session":"4616666"}}
{"timestamp":"1531017163.293066025","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"10.42.24.245:27307","session":"4616675"}}
{"timestamp":"1531017163.293168068","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.117.192:11562","session":"4616672"}}
{"timestamp":"1531017163.293213606","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.117.192:11603","session":"4616676"}}
{"timestamp":"1531017163.293610573","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.90.128:9514","session":"4616674"}}
{"timestamp":"1531017163.293661118","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.73.192:17703","session":"4616678"}}
{"timestamp":"1531017163.293664932","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"10.42.24.245:27311","session":"4616681"}}
```

From my understanding of concourse, tsa tries to make reverse tunnels back to the workers. You will notice there that none of the 192.168 addresses are the cluster IPs of the worker pods, and it even looks to be attempting to connect to the IP of one of the k8s nodes directly at `10.42.24.245` (which happens to be the node that concourse-web is running on.

Of note, the cluster is set up with nodes across mutiple availability zones by running Calico in IPIP mode. My working theory is that the tsa networking is not seeing the correct source address, or properly unwrapping IPIP packets?

The web-ui is being served fine and I can log in with basic creds, but attempting to execute a pipeline with fly hangs.

Any suggestions on where to look next or how to resolve?

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): helm
* Infrastructure/IaaS: k8s on AWS

**Comment by ralekseenkov** [comment]
we are seeing a similar issue. the log is full of:
```
{"timestamp":"1531202434.600827217","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"read tcp xx.xxx.x.xx:2222-\u003exx.xxx.x.x:62224: read: connection reset by peer","remote":"xx.xxx.x.x:62224","session":"230"}}
```

**Comment by wpalmeri** [comment]
concourse maintainers, even if there's user error here, there's an issue in that tsa will generate over 1GB of these logs in 30 minutes which is not acceptable behavior in a multi-tenant k8s cluster

**Comment by jmlambert78** [comment]
I have the same issue on a concourse deploy on azure aks

**Comment by ralekseenkov** [comment]
FYI - we are running on aks as well
the log is full of "handshake-failed" messages, but pipelines seem to work just fine.

**Comment by danielsand** [comment]
Struck the same problem. Web Pods are after some time constantly restarting with
```
{"timestamp":"1534839011.779429197","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"172.100.3.176:61513","session":"50546"}}
{"timestamp":"1534839011.779739618","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"172.100.3.176:61512","session":"50541"}}
{"timestamp":"1534839011.779801607","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.180.64:60598","session":"50544"}}
{"timestamp":"1534839011.779855013","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.240.0:36003","session":"50543"}}
{"timestamp":"1534839011.779946566","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.240.0:26932","session":"50545"}}
{"timestamp":"1534839011.780049324","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"172.100.3.176:49290","session":"50548"}}
{"timestamp":"1534839011.780103445","source":"tsa","message":"tsa.connection.handshake-failed","log_level":1,"data":{"error":"EOF","remote":"192.168.180.64:16976","session":"50547"}}
```
which makes the webinterface pretty much unusable.

Im running also on AWS K8S 1.10.x with internal ELB for the WebUI.

i have the feeling that this is also the problem - some configuration is missing to reach TSA propperly

**Comment by danilopopeye** [comment]
Having the same problem here with `4.1.0`.
I've managed to track the requests to the AWS ELB Health Check 😥

**Comment by Jeeppler** [comment]
I have the same problem. I use the stable/concourse Helm chart: https://github.com/helm/charts/tree/master/stable/concourse

Helm App Version: 3.14.1
Kubernetes: AWS EKS 1.10

**Comment by topherbullock** [comment]
Is the ELB performing some kind of health check pings to the TSA? The TSA is a TCP server listening on `2222`, so maybe the health checks aren't expecting to be hitting a TCP server.

We use GCP, and all of our load balancers are TCP load balancers ( we also only have health checks for the ATCs on 8080 )

**Comment by topherbullock** [comment]
per:  https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html#w280aac13c11c13b5 

You may want to ensure that Ping Protocol is TCP, or remove the TSA heath checks ( the TSA and ATC are both on the same binary, so you can just check the ATC )

**Comment by danilopopeye** [comment]
> per: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html#w280aac13c11c13b5

I'm not using the Classical LB but the [Network LB](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html#health-check-settings). 

> You may want to ensure that Ping Protocol is TCP, or remove the TSA heath checks ( the TSA and ATC are both on the same binary, so you can just check the ATC )

Today I have configured the Health Check to ping the ATC port like you mentioned but even if is the same process I'm not exactly comfortable with this solution.

**Comment by saedalavinia** [comment]
As mentioned above, we were able to resolve the issue by changing the protocol to TCP. The problem here is that when we specify `web.service.type=LoadBalancer` , you create 1 `svc` for ATC and TSA. ATC works at HTTP/HTTPS  level while TSA works at TCP. 

At least one AWS, you can't use a list in `service.beta.kubernetes.io/aws-load-balancer-backend-protocol`, see:  [Github Issue 40244](https://github.com/kubernetes/kubernetes/issues/40244)"

We were able to resolve this by settling for the TCP in place of HTTP/HTTPS for ATC. 

The annotations would look like this 

```yaml
 service:
    ## For minikube, set this to ClusterIP, elsewhere use LoadBalancer or NodePort
    ## ref: https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types
    ##
    type: LoadBalancer
    ## Annotations to be added to the web service.
    ##
    annotations:
    #   prometheus.io/probe: "true"
    #   prometheus.io/probe_path: "/"
    #
    #   ## When using web.service.type: LoadBalancer, enable HTTPS with an ACM cert
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "<some_policy>"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<some_cert>"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-backend-port: "atc"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```
Note the use of: 
```yaml 
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
```
Instead of 
```yaml 
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http OR https"
```

This will result in creation of TCP listener for `TSA` and TCP/SSL listener for `ATC`. If this not ideal, you can have a lambda function to flip this back to HTTP/HTTPS if desired.

**Comment by cirocosta** [comment]
Hey,

It feels like this is something that might be better tackled in the Concourse chart itself ([`helm/charts#stable/concourse`](https://github.com/helm/charts/blob/master/stable/concourse/README.md)) instead of here.

Would you mind creating it there?

Feel free to to let us know if you think that there's something on the Concourse side specifically that would need to be done.

Thx!
