### ISSUE TITLE
Drag to reorder pipelines on dashboard

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2364]
In an effort to reach feature parity with the silly sidebar, we'd like to add the ability to re-order pipelines in the dashboard

The idea is to be able to click and drag thumbnails to re-order the pipelines.

**Comment by Lindsayauchin** [comment]
Can we add an icon to the card to indicate the card is draggable? 

There are a lot of hotspots for tooltips etc. so lets add an icon to turn on the ability to drag the pipeline card around. 


<img width="627" alt="screen shot 2018-07-17 at 7 37 14 pm" src="https://user-images.githubusercontent.com/27746614/42851119-f093dcf0-89f8-11e8-9694-6e0479d96431.png">

Asset: 
[drag_card_ic.svg.zip](https://github.com/concourse/concourse/files/2203725/drag_card_ic.svg.zip)
Flat Shadow specs for active card: x 2px, y 2px, no blur, #000000 alpha 50%.

**Comment by jama-pivotal** [comment]
Closing since this feature is shipped in 4.0.0. Moving @Lindsayauchin designs for a draggable section to new issue #2426
