### ISSUE TITLE
Pipeline pause / play on dashboard

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2365]
In an effort to reach feature parity with the silly sidebar, we'd like to add the play/pause function onto the pipeline thumbnail preview on the dashboard

If the pipeline is running:
 - we should have a button to pause it

If the pipeline is paused
- we should have a button to play it
- we need to somehow indicate that the pipeline is paused. 

cc @Lindsayauchin  for designs

**Comment by Lindsayauchin** [comment]
![screen shot 2018-07-09 at 1 49 24 pm](https://user-images.githubusercontent.com/27746614/42467348-a8318af4-837f-11e8-9668-4cc020b38c9e.png)
![screen shot 2018-07-09 at 1 55 09 pm](https://user-images.githubusercontent.com/27746614/42467376-be09ba4a-837f-11e8-9e1a-dfe4a628db81.png)

**Comment by Lindsayauchin** [comment]
[play_pause_ic.zip](https://github.com/concourse/concourse/files/2182035/play_pause_ic.zip)

**Comment by jama-pivotal** [comment]
Rejecting because I can't seem to play/pause the pipeline when i've created a search filter. Steps to reproduce:

1. do a search for a pipeline
2. try to play or pause any of the pipelines you have ownership of
