### ISSUE TITLE
No space left on device while trying to run backups. The workers are all filled up. How to increase workers size? 

### ISSUE THREAD

**Issue by pooja8787** [concourse/concourse#2367]
Hi there!

When we try to run ert-backup it always fails at renaming file. The workeres /var/vacp/data is filled up everytime to 100% when we run that and is there a way to increase worker size. WE configured 2xlarge.disk for workers and it has 221g on the filesystem. But my backups are using almost 161gb and when we rename file and move to .tar it is failing at that point as there is no space left. 

Renaming with <number>
mv: write error: No space left on device 

But we have enough space on the backups folder and when we checked the workers they are all filled up.  Do workers clear the volume by themselves or we need to manually clear all the volumes? Can you help me with this issue. Thanks in advance.

**Comment by jama-pivotal** [comment]
Sorry for the late response. Regarding your question on worker volumes, I describe a little bit of it on my recent blog post: https://medium.com/concourse-ci/suspicious-volume-usage-on-workers-72131cff9bfd

Sounds like you're using something like BBR to do automatic and periodic backups on the PAS ERT. You'll definitely want a lot more volume, something like 500gb might be good; though I've seen some folks use up to 1 tb.  If you're using something like BOSH to manage the concourse lifeccycle then upping the size of the workers should be quite straightforward.

I hope this was able to help you in someway. Closing for now.
