### ISSUE TITLE
Windows worker crashes when pipeline task send CTRL_C_EVENT to subprocess

### ISSUE THREAD

**Issue by odormond** [concourse/concourse#2368]
Hello,

I have experienced workers dying while executing a python test task in a pipeline on Windows.

The test is basically doing:
```#! python
import subprocess
import signal

def test_signal_handling():
    # PSEUDO-CODE
    proc = subprocess.Popen([executable_path], stdout.subprocess.PIPE, stderr=subprocess.PIPE)
    proc.send_signal(signal.CTRL_C_EVENT)
    assert proc.returncode == 0
    assert 'cleaned up' in proc.out
```

The python documentation notes that using `CTRL_C_EVENT` requires to create the subprocess in a distinct process group by passing an additional keyword argument to `Popen`: `creationflags=subprocess.CREATE_NEW_PROCESS_GROUP`. Doing so made the test pass and prevented the worker process from dying.

So in my understanding, the CTRL_C_EVENT was sent to the whole process group of which the concourse worker was part and it thus was killed with it. I don't think this is a desirable behaviour.

Note, I'm anything but a Windows expert.

* Concourse version: v3.14.1
* Deployment type: binary
* Infrastructure/IaaS: AWS
* Did this used to work? no

**Comment by xtremerui** [comment]
closing stale issue
