### ISSUE TITLE
Documentation format and toolchain are too obscure

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#237]
We have to install Rubinius (!) in order to install a gem (anatomy) to edit the docs. To the best of my knowledge, only Concourse is using anatomy for documentation.

I feel as though using a more common doc format and toolchain -- eg markdown or asciidoc on top of the teeming multitude of popular documentation builders -- would make it easier for 3rd parties to contribute.

**Comment by jchesterpivotal** [comment]
It also transpires that [we need to install LLVM](https://github.com/postmodern/ruby-install/issues/184#issuecomment-163094426) in order to install Rubinius so we can install anatomy. 

Then those instructions don't work, so we had to hand-compile and install Rubinius.

Except that doesn't work. We can't get rbx to install.

Three of us worked on this an hour and smacked the "too hard" button; expect a forthcoming PR based on us guessing at what the rendered output will look like.

**Comment by xoebus** [comment]
'fly -t TARGET execute -c ci/build-docs.yml -i concourse=. -x -o built-docs=/tmp/docs'

'open /tmp/docs/index.html'

**Comment by vito** [comment]
Yep it's a bit of a pain to install Rubinius ATM. We probably won't be
switching toolchains though since all the other doc tools just solve the
same boring problems and don't actually make authoring any easier.

If you don't want to install Rubinius you could just use our `build-docs`
task:

```
fly e -c ci/build-docs.yml -o built-docs=./built-docs
```

...and then peruse `built-docs/index.html`

**Comment by xoebus** [comment]
My phone can't back tick.

**Comment by vito** [comment]
Neither can mine. Weird.

**Comment by jchesterpivotal** [comment]
I'm not sure I agree with the argument, but in any case, we just turned on LaTeX highlighting and submitted a PR anyhow.

**Comment by vito** [comment]
Closing as this likely won't be changing. We went through quite a few tools trying to find one that met our needs and wants (and even hopped around a couple times), and Anatomy is still the best option for us.

If you want to build the docs yourself without getting Rubinius set up there's always the `fly` one-liner that we had in the previous comments, which I'll put in a README under `docs/`.

**Comment by jchesterpivotal** [comment]
It sounds like quite a tale. Maybe worth a blog post for engineering.pivotal.io?
