### ISSUE TITLE
Update Color App-wide

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2370]
Feedback on the merging of the dashboard and pipeline color schemes

Pipeline: 'started' and 'errored' yellow and amber look very similar.

![screen shot 2018-07-10 at 10 44 36 am](https://user-images.githubusercontent.com/27746614/42528428-646d68cc-8449-11e8-80f7-96f68c184be4.png)

Build page: Highlighted input color is still from the old blue scheme.

![screen shot 2018-07-10 at 1 57 18 pm](https://user-images.githubusercontent.com/27746614/42528421-5fb2063a-8449-11e8-8c7c-9a692e7cd5bb.png)

**Comment by vito** [comment]
Also, the rings around jobs in the pipeline have the wrong value for the black background part (visible in the first screenshot, but this also affects 'failed' jobs).

**Comment by mhuangpivotal** [comment]
@Lindsayauchin this is the palette: https://github.com/concourse/web/blob/master/assets/css/_vars.less

**Comment by vito** [comment]
Dark text is hard to read:

![darktext](https://user-images.githubusercontent.com/1880/42890321-842b9134-8a7a-11e8-8058-abbdd4063733.png)

**Comment by Lindsayauchin** [comment]
## Update
**Build page**
- [ ]  .timestamped and .ansi-bright-black-fg
 - color: #504B4B = ##7a7373;
![screen shot 2018-07-23 at 10 00 32 am](https://user-images.githubusercontent.com/27746614/43081127-470c1b32-8e5f-11e8-8505-36b240de2dd5.png)

- [ ] Highlighted input color 

color: #3D4A58; = #9B9B9B

![screen shot 2018-07-23 at 10 05 12 am](https://user-images.githubusercontent.com/27746614/43081616-20227c0e-8e60-11e8-842f-d0ca04a43792.png)


**Pipeline view**


Pipeline: 'started' and 'errored' yellow and amber look very similar.
- [ ] Halo animated - should be the same as the background
color:# 1E1D1D
