### ISSUE TITLE
Switch upgrade/downgrade testing jobs to the binaries

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2371]
The current jobs won't work in the event of a stemcell change; they rely on the old code being present on the `web` node.

Let's redo these with the binary distribution instead. I suspect this is a more common use case and should be easier to work with in the tests, since you can just have both binaries available via resources (latest rc and latest final).

**Comment by pivotal-jamie-klassen** [comment]
commit message [here](https://github.com/concourse/concourse/commit/c02dd656bf41f26e3d6b350ad9005bf2390bd0b1) is relevant.

**Comment by pivotal-jwinters** [comment]
We think that its probably easiest to stick with BOSH for the deploys, but then run a task which uses the `concourse` binary to run the actual down migration.

#2380 should make this a lot easier.
