### ISSUE TITLE
Once lost, database migration errors can be difficult to recover

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2372]
## What challenge are you facing?

Once upon a time, my atc failed a migration. Since then, my error logs are clogged with a message like this:

```
failed to migrate database: Dirty database version 1522178770. Fix and force version.
```

This scenario is very similar to the one in #2074. As an operator, I find this pretty opaque. I don't really know what 'Fix' means. However, if I'm lucky and my logs haven't rotated, I might be able to go back and find what caused the database to be in this dirty state. Something like:

```
Could not migrate to version: 1522178770 Reason: pq: malformed array literal: "{develop}}"
```

This is still not the best error message, but at least it relates to the problem I'm going to have to solve.

## A Modest Proposal

Instead of just complaining that the database is dirty, the atc could remember the error it saw when the migration first failed. Thus my logs would fill up with messages more like

```
failed to migrate database: Dirty database version 1522178770. Fix and force version.
Last migration error was:
> Could not migrate to version: 1522178770 Reason: pq: malformed array literal: "{develop}}"
```

**Comment by vito** [comment]
Seems like this is better now that we've switched to our own migration library.
