### ISSUE TITLE
CredHub interactions take 97% of ATC CPU time

### ISSUE THREAD

**Issue by DanielJonesEB** [concourse/concourse#2373]
# Bug Report

Given a Concourse with secrets backed by CredHub, we were seeing 97% of the ATC's CPU time going to TLS handshakes when it was looking up secrets.

This is because `credhub-cli` (understandably, as a CLI library) was not using HTTP Keepalive, forcing each secret lookup to use a new connection, and this a new TLS handshake. The issue was fixed in this PR: https://github.com/cloudfoundry-incubator/credhub-cli/pull/45

This has since been fixed as of commit https://github.com/cloudfoundry-incubator/credhub-cli/commit/08873874034020de155ae5026720a571703669c4. Bumping to this version will see a significant performance improvement for those using CredHub.

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Did this used to work? No.

Before:
![screen shot 2018-07-06 at 13 27 30](https://user-images.githubusercontent.com/11817552/42624442-532a9c4a-85bd-11e8-9ebf-c9217eadd7b2.png)

After:
![screen shot 2018-07-06 at 13 27 37](https://user-images.githubusercontent.com/11817552/42624457-5a713c70-85bd-11e8-8fb4-55cb20c1c27d.png)

Difference:
![screen shot 2018-07-06 at 13 28 11](https://user-images.githubusercontent.com/11817552/42624542-7f1053fe-85bd-11e8-9684-f81dc6e96c11.png)

**Comment by jama-pivotal** [comment]
Pretty sure this is similar, if not the same, as #2300

**Comment by DanielJonesEB** [comment]
'ello @jama-pivotal! We think this is orthogonal. Proper engineers wot write proper code could tell you more, but it's to do with the way the stream is being read or something, so instantiation isn't relevant.

**Comment by takeyourhatoff** [comment]
@jama-pivotal Hi, without the fix for #2300 then https://github.com/cloudfoundry-incubator/credhub-cli/pull/45 will have no effect on ATC. They are two separate problems however. I actually had to downgrade concourse to v3.13 to expose this issue. The reason #2300 was so bad was because as part of the client construction credhub-cli reads and parses all of the system CA files.

With neither issue fixed, the flame graph is all parsing system root certificates, with #2300 fixed, it's all in TLS handshakes to credhub, and with both fixed ATC can actually get on and do work 🎉

**Comment by DanielJonesEB** [comment]
Hey @jama-pivotal,

We (read: @takeyourhatoff) just realised the fix in #2300 doesn't work because the method that does the lazy initialisation had a non-pointer receiver, so was acting on a fresh instance of the `lazyCredhub` struct each time.

We're just testing a fix for that, so disregard this until we've had a chance to address #2300. We'll verify it with a profiler before raising a PR.

**Comment by jama-pivotal** [comment]
thanks for the context @takeyourhatoff @DanielJonesEB . Gonna watch the PR closely for the fix, looking forward to it 🙏
