### ISSUE TITLE
Enable to versioning credential with vault.

### ISSUE THREAD

**Issue by cappyzawa** [concourse/concourse#2374]
# Feature Request

## What challenge are you facing?
I and my company users want to use vault's versioning function.
Vault has versioning function enabled from v0.10.0(https://github.com/hashicorp/vault/pull/4155).

But the version of vault currently used by this product is 0.9.6.

## A Modest Proposal
1. Upgrade vault
2. When using kv(ver2) as secret backend of vault, the path to read changes from `concourse/team/foo` to `concourse/data/team/foo`
3. In order to maintain compatibility, it is necessary to change the path to be read by secret backend.

**Comment by FraserPol** [comment]
+1

**Comment by emcniece** [comment]
Very much needed.

There is a `vault-path-prefix` [config parameter](https://concourse-ci.org/creds.html#vault-path-prefix) that defaults to `concourse/` - could this be modified to `concourse/data/`?

**Comment by emcniece** [comment]
It looks like solving this is just a matter of updating the `vaultapi "github.com/hashicorp/vault/api"` package dependency.

**Comment by eedwards-sk** [comment]
I would also like support for v2 / versioning backend

since it's not uncommon in a ci environment with vault to automate the provisioning of secrets where you may never see the real value, it's also possible to accidentally destroy that auto-generated secret

having versioning support would allow for easier DR scenarios with a lot of dynamically generated secrets

**Comment by vito** [comment]
Linking to https://github.com/concourse/rfcs/issues/5 - maybe this is in scope too?

**Comment by cappyzawa** [comment]
I think this is scoped https://github.com/concourse/rfcs/issues/5.
> The current implementation forces users to use the "generic" backend, if they're using recent releases of Vault.

The claim of this issue is that we want to activate kv(ver2) as well as generic.
