### ISSUE TITLE
Concourse wouldn't start pipelines

### ISSUE THREAD

**Issue by sarunask** [concourse/concourse#2376]
Hi,

We have latest concourse v3.14.1 running in AWS infrastructure. We use Ubuntu 18.04 LTS to run  Worker and Web component.
We run 1 Web node and 1 Worker node.
Setup is like this:
Internet---> Route53 DNS --> ELB --> Web Node
Worker is connecting to WebNode via --tsa-host EXTERNAL_DNS:2222
I would go through check list on this ticket: https://github.com/concourse/concourse/issues/844
1. Are all of your workers present?
Yes
```bash
name            containers  platform  tags  team  state    version  garden address   baggageclaim url        resource types
ip-172-16-2-28  2           linux     none  none  running  2.1      127.0.0.1:42399  http://127.0.0.1:44029  bosh-deployment, bosh-io-release, bosh-io-stemcell, cf, docker-image, git, github-release, hg, pool, s3, semver, time, tracker
```
2. Is there a check container present for each of the inputs to your job? (fly hijack -c pipeline-name/resource-name) 
```bash
fly -t 90poe_main hijack -c integration-service-master/golang-tools-docker-image
no containers matched your search parameters!

they may have expired if your build hasn't recently finished.
```
3. What is the uptime of your workers and ATC?
24 minutes for Web
10 minutes for Worker
4. Are your workers registered directly (BOSH default) or forwarded through the TSA (binary default/external workers registering with BOSH deployment)?
TSA
5. Which IaaS? 
AWS
Can you reach the workers from your ATC? (curl http://<worker ip:port>/containers) You can collect the IP + port from fly workers -d.
```bash
curl http://127.0.0.1:42399/containers
{"Handles":["95ad75ac-a980-451b-6f3a-1cee72b7a585","96a8fd02-1176-4b62-78b4-1dacc03ec12d"]}
```
6. stack dumps
https://drive.google.com/open?id=12F2I0WlPWrteGaKpFNJnjnDMruTNnq0W

**Comment by sarunask** [comment]
It appears that issue is with DNS, similar issue is described here: https://github.com/concourse/concourse/issues/1229
Issue with DNS is that on Ubuntu 18.04 DNS is done by system-resolved service, and Concourse containers don't see DNS in our setup (we are using Terraform to build cluster).
So solution was to add such configuration into concourse-worker.service:
```
Environment=CONCOURSE_GARDEN_DNS_SERVER=169.254.169.253
```

**Comment by jama-pivotal** [comment]
That's fine, thanks for following up with your discovery
