### ISSUE TITLE
High density pipeline names rendered differently from normal dashboard view pipeline names

### ISSUE THREAD

**Issue by StevenArmstrong** [concourse/concourse#2378]
## A Modest Proposal

In concourse 4.0.0 implementation https://ci.concourse-ci.org/hd
The high density view renders long pipeline names in a much nicer way than the regular dashboard view
High density:
![image](https://user-images.githubusercontent.com/5717694/42722664-edd81fe8-8747-11e8-959b-bfbcdd1053ee.png)
Regular dashboard:
![image](https://user-images.githubusercontent.com/5717694/42722669-1335f454-8748-11e8-86e9-ca6c5d983897.png)
Could they both be made consistent. We have had users complain that the truncated text looks ugly so they don't want to use it as a wallboard and asked for us to create a tool for this instead. It seems this has been half fixed with the high density view looking nice.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): N/A
* Infrastructure/IaaS: N/A
* Browser (if applicable): chrome
* Did this used to work? No

**Comment by xtremerui** [comment]
high-density view mean to be space saving so now it is actually consistent with regular view, which is one single line.
