### ISSUE TITLE
investigation aid - which worker is causing build failures

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#2379]
# Feature Request

## What challenge are you facing?

Currently I am having a set of workers in very different environments with a range of different network connections.
To diagnose problems of individual builds due to network events, it would be really helpful to know which worker was running this particular job. That why a simple manual/automated lookup in the logging infrastructure could explain hickups and lead to further targeted investigations rather than do do guesswork why the build failed.

## A Modest Proposal

It would be nice to see which worker is running which job in `fly builds` as well as in the web UI.

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: custom/self-hosted
* Browser (if applicable): firefox

**Comment by drahnr** [comment]
Same issues still with concourse workers 5.8.0

**Comment by xtremerui** [comment]
one build could have multiple steps that could be ran by different workers.

Now in web UI within each step you can see which worker is picked up to run the step.
