### ISSUE TITLE
Dashboard should show teams you are whitelisted into even if it has no pipelines

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2382]
With the change of the login mechanism to be user based, you can't selectively choose to login to specific teams now from the UI. This becomes problematic when creating new teams with no pipelines. 

Consider this scenario
1. I get the information about the new team such as their name and the list of users
2. I create the team with `set-team`
3. I notify the team lead that they can login now
4. the team is confused because they don't see their team name on the Dashboard, and they dont see anything in the sidebar

## Proposal 
We should show teams on the dashboard even if there are no pipelines

**Comment by Lindsayauchin** [comment]
**Proposal:** 

Dashboard will display a 'blank' card with little illustration and will read "no pipelines set" when no pipelines are set for a new team. 

In the sidebar empty state will read "no pipelines set".

![dashboard_no_pipeine_set_team_login](https://user-images.githubusercontent.com/27746614/42774654-40528484-8900-11e8-926c-ccb9c72a30ec.png)

**Comment by xtremerui** [comment]
@Lindsayauchin how about HD dashboard ?

**Comment by Lindsayauchin** [comment]
![dashboard_no_pipeine_set_team_hd](https://user-images.githubusercontent.com/27746614/42898765-13f49f56-8a92-11e8-89cb-b3a12a231d8f.png)

**Comment by xtremerui** [comment]
@Lindsayauchin could you give the color code of "no pipelines set"? Thx.

**Comment by Lindsayauchin** [comment]
The padding between the team name with pipeline(s) and a team without is not consistent. 

## Current: 
 ![screen shot 2018-07-27 at 2 19 57 pm](https://user-images.githubusercontent.com/27746614/43339933-c3e9f042-91a8-11e8-9cca-7ad4649247a3.png)

## Expected: 

![screen shot 2018-07-27 at 2 29 33 pm](https://user-images.githubusercontent.com/27746614/43340196-894b419c-91a9-11e8-81e7-b6c792131485.png)


-[ ]add padding to no-set pipeline

```
.dashboard .dashboard-pipeline.no-set {
    margin: auto;
    padding-bottom: 25px;
    padding-top: 25px;
    cursor: default;
}

```
