### ISSUE TITLE
Dashboard search: polish

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2387]
**Current State:** 

<img width="342" alt="screen shot 2018-07-16 at 4 46 47 pm" src="https://user-images.githubusercontent.com/27746614/42782884-3d8589d2-8918-11e8-834c-c80b8a5c8bb9.png">

### **Unselected State:**

~~- [ ] Close Icon: #9BA2A8~~
~~- [ ] Input border #323435~~
<img width="458" alt="screen shot 2018-07-16 at 5 18 48 pm" src="https://user-images.githubusercontent.com/27746614/42784218-749ea602-891c-11e8-91f6-6bbccc112f5b.png">

### **Selected State:**

- [x] Space after the search operator ie." status: succeeded "
- [x] Close/Clear Icon in input is active # ffffff

<img width="379" alt="screen shot 2018-07-16 at 5 40 30 pm" src="https://user-images.githubusercontent.com/27746614/42785170-6b01b62c-891f-11e8-9e85-d31f0df27f3f.png">

<img width="438" alt="screen shot 2018-07-16 at 5 18 36 pm" src="https://user-images.githubusercontent.com/27746614/42784239-87aeadbe-891c-11e8-961a-73187268917a.png">

Selected Operator:
- [x] Font Color #ffffff
~~- [ ] Input background #202121~~

<img width="491" alt="screen shot 2018-07-16 at 5 42 08 pm" src="https://user-images.githubusercontent.com/27746614/42785204-a35f0772-891f-11e8-971e-fe497b42186c.png">

- Asset 'close' [ic_close_white.svg.zip](https://github.com/concourse/concourse/files/2225120/ic_close_white.svg.zip)

- Asset transparent [ic_close_transparent.svg.zip](https://github.com/concourse/concourse/files/2225138/ic_close_transparent.svg.zip)

**Comment by mhuangpivotal** [comment]
Whitespace in search query is captured in a separate issue: #2275.

**Comment by jama-pivotal** [comment]
Marking as accepted for now because the styles match what was asked for. However this introduces a new bug with team search, will open a new issue
