### ISSUE TITLE
Support for building arbitrary git branches based off regex for branch name (without requiring a GitHub pull request)

### ISSUE THREAD

**Issue by thewoolleyman** [concourse/concourse#239]
E.g. like [Circle CI](https://circleci.com/docs/configuration), [Travis CI](https://docs.travis-ci.com/user/customizing-the-build/#sts=Building Specific Branches), and [Jenkins](https://www.cloudbees.com/blog/advanced-git-jenkins) (although [GoCD apparently still doesn't](https://github.com/gocd/gocd/issues/298))

This is necessary for our workflows (on the Pivotal Tracker sub-teams), because we often work on feature branches, and want these branches to automatically build, run tests, deploy to a test PWS instance for acceptance, etc., without having to manually add the branches/jobs/etc to the concourse config and redeploy.

As an example, we already have this working, implemented as a reusable resource and a reusable job than can perform any arbitrary build tasks for any arbitrary branches:

https://github.com/pivotaltracker/git-branches-resource
https://github.com/pivotaltracker/concourse-branch-manager

This is all well tested, documented, standalone, and open source.  We would be glad to contribute this back to the Concourse community as soon as [there's a official place to do that](https://github.com/concourse/concourse/issues/191).

Thanks,
-- Chad

**Comment by tracker-common** [comment]
Post-1.0 ping as requested @vito

**Comment by thewoolleyman** [comment]
Post-1.0 ping as requested @vito

**Comment by thewoolleyman** [comment]
Ideally, this should not be tied to Pull Requests, because many teams do not use PRs for branches.

**Comment by jkamenik** [comment]
👍

**Comment by muv** [comment]
@thewoolleyman Haven't seen the ability to build from pull requests in the official docs. Are you refering to https://github.com/jtarchie/pullrequest-resource?

**Comment by muv** [comment]
For implementation, I'd like to have jobs with parameters that are passed to `fly` instead of spawning pipelines. So that I could `fly trigger-job mypipeline/build myrepo/test-branch` and so.

**Comment by thewoolleyman** [comment]
@muv yes, the PR resource works, and is a simpler approach, but it has some drawbacks compared to the branch-manager approach (aside from requiring the use of PRs, it's difficult to find and re-run builds for specific branches/PRs).  

However, it is also much less resources intensive (many containers created) than branch-manager, so the PR resource may be a good choice for teams with 
many active branches and sensitivity to resource cost (read: are running on AWS).


Everything considered, the lack of official support for building arbitrary branches in an efficient way with a reasonable UX is still a significant barrier to concourse adoption for any team which actively uses feature branches, whether they are via PRs or not.

**Comment by muv** [comment]
Exactly. Reading official docs I wondered for awhile how to build feature branches. Until I finally realized how to compose a proper google request and found this.

**Comment by vito** [comment]
There are two approaches made possible by `version: every` without the need for a separate server.

Travis-style: see https://github.com/concourse/concourse/issues/525#issuecomment-231906357

Pipeline per branch: you could use a [`git-branches`](https://github.com/vito/git-branches-resource) resource (which I'd forgotten you already wrote, but mine's a bit different) and a [`concourse-pipeline`](https://github.com/robdimsdale/concourse-pipeline-resource) resource (which just needs support for deleting pipelines).

I also want to put together a plan for having pipeline hierarchies, so you don't end up with a flat set of pipelines with generated names for each branch: https://github.com/concourse/concourse/issues/532

**Comment by thewoolleyman** [comment]
Yes, a `git-branch-heads` resource would be useful.

However, with the "Travis-style" approach, you still have the same UX issues as the [pullrequest-resource](https://github.com/jtarchie/pullrequest-resource).  Specifically, because your "version" is a concatenation of two independent values (branchname+sha, or pr#+sha), if that feeds into a single job in a single pipeline, you lose the ability to re-run a specific build for a specific branch/PR, or to see the isolated build info for a single branch/PR.

So, the pipeline-per-branch approach is much more friendly, from a UX perspective, to projects and teams that use branches/PRs heavily, and fits more logically into the Concourse resource paradigm, because it uses standard `git` resources, and avoids the aforementioned problems of `pullrequest-resource` (and I presume `git-branch-heads`) because doesn't try to munch two independent values into a single resource "version".

But, regardless of how it's implemented, the pipeline-per-branch approach still has the downside of multiplying containers for resources/jobs/tasks across every pipeline that is created, which can (as we found out) really blow up your resource requirements (and costs, if you are running on AWS or other paid hosted service). This is why it's critical to have support for regex-branch-selection (more on that below)

So, @vito - I'm not positive exactly how you envision combining git-branches and concourse-pipeline to achieve the original goals of this issue.  Could you elaborate more?

The [git-branches-resource](https://github.com/pivotaltracker/git-branches-resource) and [concourse-branch-manager job](https://github.com/pivotaltracker/concourse-branch-manager) are already working to achieve this, without the need for a separate server, and address several issues we encountered during our actual usage of it for several months.  Specifically, I'd like any final solution to have the following features (all of which are addressed by `concourse-branch-manager` (except for the first "easy to see a list of all branches" UX one, which may already be fixed in new groups UX):

1. Allow for easy reuse/templating of resources/jobs/tasks which will be very similar across all pipelines, except for the branch/PR.  Hopefully this one is easy, but the existing pipeline variable substitution method was too primitive for our needs (as we discussed), which is why we went with ERB (if you don't like the usage of ERB, we could avoid that by just improving the existing pipeline variable support).

2. Support selecting branches to build by regex.  This is extremely important from a container cost perspective, because even if you can get large teams to clean up old branches (a big IF on many teams), you still will always have branches you don't care about building (inactive, WIP, spike) and don't want to take up resources.

3. A decent UX experience.  E.g.:
  * Easy to see a list of all branches currently being built, and select yours from it
  * Easy to see the build history for a single branch in isolation, without any builds for other branches mixed in
  * Easy to see input resource history (triggered builds/jobs) for a single branch in isolation.
  * Easy to force a (re)build for a single branch via the UI.

Thanks,
-- Chad

**Comment by vito** [comment]
`version: every` is what allows the guarantee of running a build for every branch change. Once #413 is done you can then re-run them.

Pipeline-per-branch and Travis-style flows are both perfectly valid use cases. One is more general than the other, but sometimes you don't need that. I'm not proposing we pick one or the other, just that both can be done pretty easily with resources.

`concourse-branch-manager` is basically the same approach I was thinking, except by using the `concourse-pipeline-resource` instead, and leaving pipeline template generation up to the user (rather than assuming ERB/etc.). It seems like a cleaner separation to me, since the pipeline resource already exists, but it boils down to the same stuff.

**Comment by thewoolleyman** [comment]
@vito 

OK, so I can see concourse-branch-manager turning into something simpler which leverages the approaches you describe, but with a works-out-of-the-box-job approach to pipeline config generation/composition/templating/reuse, for people who don't want to roll that on their own.

But, what about #2 above (the "arbitrary branches" requirement of this issue)?  This is currently solved by [git-branches-resource](https://github.com/pivotaltracker/git-branches-resource) being able to select branches to build (generate pipelines for) via a regex.  Again, this is very important in order to manage container count/AWS cost.

What would provide that in your proposed approach?  Some support in the `git-branch-heads` resource?  Or something else?

**Comment by vito** [comment]
@thewoolleyman Yep, branch name pattern matching makes sense. I didn't get around to implementing it in my `git-branches` resource yet.  Also makes sense for `git-branch-heads`.

I forgot you had a git-branches resource when I wrote mine. I think the only thing mine has that yours is missing is the reporting of which branches were added or removed from the last check. Yours has the rest (pattern matching and such). Also mine worked without having to clone the repo which is kinda neat: https://github.com/vito/git-branches-resource/blob/master/assets/check#L26

In any case, we should probably merge them.

**Comment by thewoolleyman** [comment]
@vito OK, sounds good.  If I understood, if I just switched to the `ls-remote` approach to avoid a clone and updated tests accordingly, mine would be good?  If so, what org/repo should it live in?  Should we go ahead and make one in the concourse org?

**Comment by vito** [comment]
@thewoolleyman That and the fact that the resource provided the delta (branches added and removed), which makes it quite easy to automate pipeline management. Yours just emits the current set of branches, plus an increment value to make sure it's always a new version (which mine may need, actually, if a branch is added and removed repeatedly). With just the current set of branches, you'd then need to talk to Concourse to figure out which branches to remove, which is extra work that would have to live in a task (and need credentials and such).

Once we get things consolidated we could look at moving it into the `concourse` organization, though I'd want to take a bit more time and establish a pattern using the `concourse-pipeline` resource first, and document it if things work out.

**Comment by thewoolleyman** [comment]
Yes, we had to [add the increment value](https://github.com/pivotaltracker/git-branches-resource/commit/ef097ba471bc8c5e0cd61b67a12c7cf064597909) in order to force a new version to be emitted in some cases:  - it also helps with chronological sorting in the resources view, which is incidentally also a problem with the s3 resource when using non-numeric alphabetic (e.g. SHA) pre-release versions.

**Comment by jtarchie** [comment]
I'm having a little trouble following.

Does this resource actually check out the branch, or does it just provide the meta information of what branch to run?

**Comment by vito** [comment]
@jtarchie `git-branches` resource just emits metadata about the branches. `git-branch-heads` has an interesting `check` which emits giant versions containing the current HEAD sha of each branch, compares each branch to the previous version, and emits a version for each of the branches that changed. Its `in` then fetches the repo, same as the `git` resource.

So the version would look something like:

```json
{
  "changed": "some-branch",
  "some-branch": "abcdef",
  "some-other-branch": "abcdef"
}
```

And if both `some-other-branch` and `some-branch` have different shas at `HEAD`, it would emit one version each, with `changed` naming the branch.

`/in` would then clone whichever branch changed, at its given sha.

**Comment by thewoolleyman** [comment]
@vito So, how exactly do you envision the `git-branch-heads-resource` being used?

It doesn't seem necessary for the pipeline-per-branch approach, right?  All that needs is a list of branches which changed via the `git-branches-resource`, and the the `concourse-pipeline-resource` would then create/delete pipelines based on existing branches which match the regex.  Then, each created per-branch pipeline would just use the standard `git-resource` pointing to the branch (which is exactly what `concourse-branch-manager` does).

**Comment by vito** [comment]
@thewoolleyman It's not necessary but is much simpler for less complicated projects where you just want assistance from CI to give you a feedback loop at the unit level.

**Comment by thewoolleyman** [comment]
@vito Makes sense.  I'd like to see an example of it used in an actual pipeline/job, though (once it's written), to see how it could be used to manage the build of multiple branches.

**Comment by vito** [comment]
Finally got around to whipping up that `git-branch-heads` resource:

https://github.com/vito/git-branch-heads-resource

Example pipeline:

https://github.com/concourse/concourse/blob/d0053847af8d68da8521b52e7bb3fc5446d7851e/ci/pipelines/wip.yml

And here it is in our CI:

https://ci.concourse.ci/teams/main/pipelines/wips

(...not that it's particularly impressive at the moment)

**Comment by vito** [comment]
I think enough has come out of this discussion to warrant closing the issue; there are a few approaches that work to varying levels, and what's left isn't very actionable as it's kind of open-ended.

**Comment by mzelinsky** [comment]
can we reopen this issue as `concourse-pipeline-resource` is not really suitable for the task (due to https://github.com/robdimsdale/concourse-pipeline-resource/issues/10 which is not yet implemented)? it seems the concourse is the only CI/CD that doesn't have a proper support for multiple branches, in terms of UX and overall workflow experience.

**Comment by vito** [comment]
For all those keeping up with this issue, please see #1707 and the stories it led to. :)

See also our [post](https://medium.com/concourse-ci/sneak-peek-spatial-resources-d0eed9bb3fa) announcing it (which...basically just links to that issue).

**Comment by thewoolleyman** [comment]
@vito Awesome, thanks for putting in the hard work to come up with a good solution to this.
