### ISSUE TITLE
Concourse output doesn't handle multipart ANSI code sequences

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [concourse/concourse#2390]
We have a task that produces output with green text using ANSI escaped color codes:
```
[38;5;41m  ✔  valid_owners_fim_check: Check if FIM is owned by root[0m
```

When viewing the output in concourse, the text has a red background and blinks:
```
<span class="ansi-red-bg ansi-blink" style="font-weight: normal; text-decoration: none; font-style: normal;">  ✔  valid_owners_fim_check: Check if FIM is owned by root</span>
```

* Concourse version: v3.14.1
* Deployment type: BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome 67.0.3396.99

**Comment by xtreme-conor-nosal** [comment]
It appears that concourse is not handling combinations of ANSI codes correctly.

The sequence "[38;5;41m" represented in 256-color mode:
 - 38: I am setting foreground color
 - 5: I am providing an 8-bit color code, not an RGB triplet
 - 41: color code for green

Concourse is treating the three values as separate codes:
 - 38: Set foreground color to ?
 - 5: slow blink
 - 41: background color red

Resource:
https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

**Comment by jama-pivotal** [comment]
I labeled this with web-ui assuming you were seeing this problem in the browser...lmk if i'm wrong!

**Comment by vlad-ro** [comment]
We are facing this issue for inspec tests output

**Comment by agurney** [comment]
See https://github.com/vito/elm-ansi/issues/4

**Comment by damouse** [comment]
I am seeing this in the browser.
