### ISSUE TITLE
HD view: polish

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2391]
## Current
![hd_view_current_state](https://user-images.githubusercontent.com/27746614/42840873-3cd075c4-89d6-11e8-9fff-8f209a6d45c1.png)

## CSS Updates:

```
.dashboard-hd .dashboard-pipeline-content a {
    letter-spacing: 1px;
    display: table-cell;
    vertical-align: middle;
    text-align: left;
    font-size: 19px;
    line-height: 18px;
    padding-left: 4px;
}
```

![screen shot 2018-07-24 at 9 51 44 am](https://user-images.githubusercontent.com/27746614/43142791-39ded5f8-8f27-11e8-8b95-f7ea4ea1035e.png)

**Comment by jama-pivotal** [comment]
Verified CSS and styling on prod. @Lindsayauchin dropping css bombs on stories 👍
