### ISSUE TITLE
Probleme release notes for Concourse v3.6.0

### ISSUE THREAD

**Issue by gdenn** [concourse/concourse#2393]
# Bug Report

hi we tried to update from Concourse version 3.6.0 to 3.13.1 and had trouble updating the workers and db instance.

## db 
I think the release notes for Concourse 3.6.0 can lead to some misunderstandings. 

In the release notes for 3.6.0 it says
```
Concourse now requires PostgreSQL v9.5+. If you're already up-to-date, you've got nothing to worry about.
```
And in the release notes for 3.5.0 it says
```
The next version of Concourse will require version 9.5+ of Postgres, so action is required either now or upon the next release to upgrade.

The postgresql job in our release should now be considered deprecated, and will be removed in the next release.
```
This let us to believe that our Concourse deployment with version 3.6.0 is already on a postgresql version 9.5+ which was not the case. 

In fact we deployed pg version 9.3.4 (@see https://github.com/concourse/concourse/blob/v3.6.0/packages/postgres-unknown/packaging#L5)  with the pg job from the Concourse. But according to the 3.5.0 releae notes, it should not be possible to use the pg job in the Concourse release anymore.

This lead us to a problem updating from Concourse version 3.6.0 to 3.13.1. We could solve this problem following the db migration instruction described in the Concourse 3.5.0 release notes.

## worker
The recreation of the worker instances failed due to baggageclaim processes that could not be stoped by monit.

We could solve this problem by the following procedure:
- bosh ssh worker
- ps aux | grep baggageclaim
- Use kill -9 to terminate the remaining baggageclaim processes

Afterwards the recreation of the instance vms was possible.

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome

**Comment by jama-pivotal** [comment]
Ah, I think I see the confusion? When we said `If you're already up-to-date` we meant up to date on your postgres, not the Concourse version. That probably led you down the path of ignoring your pg and leaving git at 9.3.4.  If I'm right, then I can tweak the phrase to something like `If you're already up-to-date on your PostgreSQL version, you've got nothing to worry about`
