### ISSUE TITLE
Timeout awaiting response headers during GET http://..../volumes and impact

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2402]
# Potential Bug Report

We have been experiencing performance issues in our system, including when utilizing custom resource types.  We are seeing periodic messages such as the following:
`"message":"tsa.connection.channel.forward-worker.heartbeat.failed-to-list-volumes","log_level":2,"data":{"error":"Get http://24b6373a-7d71-4400-a416-08c6bc02d476.production-web.default.production.bosh:37881/volumes: net/http: timeout awaiting response headers"`

This error appeared far more frequently in 3.13.0 but appears in 3.9.2 as well.  We are seeing the cause either as 'timeout awaiting response headers' or 'connection refused'

What would be the impact of this type of message or is this expected behavior that will simply be handled in some area of logic?

* Concourse version:  3.13 and 3.9.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack

Thank you!

**Comment by vito** [comment]
To be honest this just looks like typical network instability. It's working as expected - the heartbeats are there to notice this kind of thing. If it happens for long enough the worker will stall, and Concourse will stop using it until it comes back (when the network recovers).

If this happens for long enough I'd try digging into the IaaS and seeing if you can reproduce this with fewer moving parts. As of right now I'm not sure what action we could possibly take ourselves in order to resolve this. Sorry!

**Comment by rentiansheng** [comment]
If you use the golang net/http class library and http.client uses transport, please check if your transport has the ResponseHeaderTimeout parameter set. If it is set, it may be caused by this parameter. The request execution time of the http call exceeds the time set by ResponseHeaderTimeout

**Comment by keithkroeger** [comment]
Thank you, @vito  and @rentiansheng

**Comment by keithkroeger** [comment]
I can see that the value is used in https://github.com/concourse/tsa/blob/master/tsacmd/server.go#L649.

Should there be a possibility to configure this?

**Comment by dmpgpro** [comment]
Hi, All!

Is may be added set-up of HTTP-timeouts from environment variables for highload cases? Today on  Windows workers and concourse version 4.2.1 - I am observe periodical errors:

Put /volumes/449b8e69-fa43-4bdb-569d-5f8a89f598c2/stream-in?path=.: net/http: timeout awaiting response headers

**Comment by tjvman** [comment]
We've been seeing the same error as @dmpgpro describes pretty frequently in our Windows jobs/tasks as well.

**Comment by cirocosta** [comment]
Hi @dmpgpro ,

It can be configured through `CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT` in `concourse web`:

```
How long to wait for Baggageclaim to send the response header. (default: 1m)
--baggageclaim-response-header-timeout
[$CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT]
```

---

By the way, for who might be looking at this issue, this is a great visualization of the timeouts in a typical request from a client:

<img width="707" alt="screen shot 2019-03-06 at 6 55 04 am" src="https://user-images.githubusercontent.com/3574444/53879765-43d70c80-3fdd-11e9-96f5-aed68dd4700d.png">

Being this particular one there in the "resp headers" section right after the HTTP portion starts (see https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/).
