### ISSUE TITLE
Update UI assets from Font awesome to Material Icons

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2405]
### Current:

![screen shot 2018-08-08 at 11 34 06 am](https://user-images.githubusercontent.com/27746614/43847628-09eb8542-9aff-11e8-9a86-c5618677bbe8.png)

### New: 
![screen shot 2018-08-08 at 11 34 50 am](https://user-images.githubusercontent.com/27746614/43847657-18fb57ec-9aff-11e8-964a-f1b1a15fcd3e.png)

### Assets:
[chevrons_pagination.zip](https://github.com/concourse/concourse/files/2270893/chevrons_pagination.zip)

### Current:

![screen shot 2018-08-08 at 12 00 09 pm](https://user-images.githubusercontent.com/27746614/43849175-cd83f928-9b02-11e8-99e2-7c6aa5894376.png)

### New: 

![screen shot 2018-12-05 at 10 47 43 am](https://user-images.githubusercontent.com/27746614/49525195-3c3b8680-f87b-11e8-94dc-e6db85eb74a2.png)

![screen shot 2018-12-05 at 10 49 17 am](https://user-images.githubusercontent.com/27746614/49525301-786ee700-f87b-11e8-8977-3b3b24b29a96.png)

### Assets:
[ic_add_circle_outline_white.svg.zip](https://github.com/concourse/concourse/files/2649502/ic_add_circle_outline_white.svg.zip)

**Comment by xtremerui** [comment]
Linking to #1976 so it could be done altogether

**Comment by pivotal-jamie-klassen** [comment]
CLI download icons are currently font awesome as well.

**Comment by pivotal-jamie-klassen** [comment]
* abort build (`fa-times-circle`)
* loading spinners in various places (`fa-circle-o-notch`)
* resource check errors, build step errors (`fa-exclamation-triangle`)
* build page step headers ( failure `fa-times`, success `fa-check`, task `fa-terminal`, get `fa-arrow-down`, put `fa-arrow-up`)
* build page preparation/pending (`fa-cogs`)
* job page play/pause (`fa-play`, `fa-pause`)
* job page inputs/outputs (`fa-arrow-up`, `fa-arrow-down`)

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen updated icons inline. 

* abort build (`fa-times-circle`)
[ic_abort_circle_outline_white.svg.zip](https://github.com/concourse/concourse/files/2658740/ic_abort_circle_outline_white.svg.zip)

* resource check errors, build step errors (`fa-exclamation-triangle`)
[ic_exclamation-triangle.svg.zip](https://github.com/concourse/concourse/files/2658831/ic_exclamation-triangle.svg.zip)

* job page play/pause (`fa-play`, `fa-pause`)
[play:pause icons.zip](https://github.com/concourse/concourse/files/2658835/play.pause.icons.zip)

* job page inputs/outputs (`fa-arrow-up`, `fa-arrow-down`)
[job page inputs:outputs  arrows.zip](https://github.com/concourse/concourse/files/2658744/job.page.inputs.outputs.arrows.zip)

* CLI icons
[CLI_logos.zip](https://github.com/concourse/concourse/files/2658896/CLI_logos.zip)

**Comment by Lindsayauchin** [comment]
WIP Loading Assets: 

- loading spinners in various places (fa-circle-o-notch)

- build page preparation/pending (fa-cogs)

* build page step headers ( failure `fa-times`, success `fa-check`, task `fa-terminal`, get `fa-arrow-down`, put `fa-arrow-up`)

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin perhaps worth nothing here that there don't seem to be material design icons for the Tux the linux penguin, the Windows logo or the Apple logo that we have been using for the CLI download icons?

**Comment by Lindsayauchin** [comment]
- [ ] build page step headers ( failure fa-times, success fa-check, task fa-terminal, get fa-arrow-down, put fa-arrow-up)[build page step headers icons.zip](https://github.com/concourse/concourse/files/2673633/build.page.step.headers.icons.zip)

- [ ] build page preparation/pending (fa-cogs)
[ic_cogs.svg.zip](https://github.com/concourse/concourse/files/2673637/ic_cogs.svg.zip)

**Comment by Lindsayauchin** [comment]
Looking at the example from materialize (https://materializecss.com/preloader.html)

![loading_spinner_example](https://user-images.githubusercontent.com/27746614/49901904-7636fa80-fe30-11e8-8248-6f07cb90bbdf.gif)
- [ ] update loading spinners in various places (fa-circle-o-notch)
- [ ] Can we replace the current with the Circular animation and update the color to @blue-primary: #4A90E2; 
- [ ] Scale according to situation based on the current spinners that we are replacing

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin for the trigger button on the build page (for a non-one-off build), if `disable_manual_trigger` is true for the job in question, I'm assuming there will simply be a default cursor and no highlight on hover (but still with the 'tooltip' as discussed in #1496). If this is not desirable, let's make another issue because this one's already a doozy.

**Comment by pivotal-jamie-klassen** [comment]
Also on the job page it might make sense for the colored banner to blue when the job is paused now, because in this view it's not super obvious that the job is paused:
<img width="641" alt="screen shot 2018-12-31 at 4 04 46 pm" src="https://user-images.githubusercontent.com/22056320/50567691-e3de9400-0d15-11e9-8164-e8ba563afa89.png">

**Comment by pivotal-jamie-klassen** [comment]
prototype for build pagination on job page

![screen shot 2019-01-03 at 4 06 20 pm](https://user-images.githubusercontent.com/22056320/50661582-8fcfeb80-0f71-11e9-8e72-ce5c04e1c435.png)

```
<div id="pagination" style="display: flex;align-items: stretch;"><div style="
    padding: 5px;
    display: flex;
    align-items: center;
    border-left: 1px solid #3d3c3c;
"><div style="background-image: url(/public/images/baseline-chevron_left-24px.svg);background-position: 50% 50%;background-repeat: no-repeat;width: 24px;height: 24px;padding: 5px;opacity: 0.5;"></div></div><div style="
    border-left: 1px solid #3d3c3c;
    display: flex;
    align-items: center;
    padding: 5px;
"><div style="background-image: url(/public/images/baseline-chevron_right-24px.svg);background-position: 50% 50%;background-repeat: no-repeat;background-color: #504b4b;border-radius: 50%;width: 24px;height: 24px;padding: 5px;"></div></div></div>
```

* disabled chevron is `opacity: 0.5`
* enabled chevron is `opacity: 1`
* enabled and hovered chevron has `background-color: #504b4b; border-radius: 50%`

**Comment by pivotal-jamie-klassen** [comment]
a quick update to keep the details straight. As of today I have still to do the following (in presumably decreasing order of effort required):
* [ ] build page step headers
* [ ] loading spinners throughout
* [ ] pagination chevrons on resource page
* [ ] CLI icons on pipeline page
* [ ] resource check status on resource page

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin We noticed that the build page also makes use of a non-spinning `fa-circle-o-notch` 
for pending steps during a running build and `fa-circle` for steps that were never reached in a finished build. We were unable to find obvious material design equivalents for these icons -- please help!

**Comment by pivotal-jamie-klassen** [comment]
spinners should be white

**Comment by vito** [comment]
Accepting, since we broke the rest out in https://github.com/concourse/concourse/issues/3022
