### ISSUE TITLE
Improve documentation on Concourse's requirements

### ISSUE THREAD

**Issue by rafaelmagu** [concourse/concourse#241]
Following on from a conversation in the Slack channel, I have found that trying to set up a VPC from scratch to use Concourse is nearly impossible. Considering [BOSH's documentation covers the basics](http://bosh.io/docs/init-aws.html#create-vpc), I'd expect Concourse's to be even simpler.

It seems to basically consist of:
- 2 security groups
- 1 ELB
- 1 route table
- 1 NAT instance
- 2 subnets

While I understand the [CloudFormation template](https://github.com/concourse/concourse/blob/master/manifests/cloudformation.json) provided works great for spinning up infra, it does very little to explain what the infrastructure requirements actually are for Concourse. This is made worse by the fact there is virtually zero documentation on how to set Concourse's individual components up.

Importing a third-party CF template into an AWS production account is almost never a good idea, for security reasons. A list of Concourse requirements for the VPC on top of BOSH's would go a long way in demystifying Concourse's setup.

**Comment by mavenraven** [comment]
@rafaelmagu Would making a separate AWS account to spin up concourse in solve your security concerns? What information are you looking for that is isn't in the Cloud Formation template?

**Comment by rafaelmagu** [comment]
CloudFormation templates are not the most human-friendly documents around. What I am missing here (and basically anywhere in the docs) is the actual list of resources that will be setup when I import this CloudFormation template into AWS.

Or, basically, an answer to the question "what resources does Concourse need?"

**Comment by mavenraven** [comment]
Looking at that slack conversation, I'd agree with @robdimsdale. The bosh.io AWS docs have had subtle things wrong in the past that made them incorrect. A terraform configuration would be cool though.

**Comment by rafaelmagu** [comment]
Pipe dream would be to be able to deploy just the binaries onto any setup you want, without relying on BOSH. But yeah, Terraform would simplify understanding a little bit. As it is right now, because I'm a noob with BOSH, getting those templates right seems to be taking too much time, so I'm back to using CF.

**Comment by rafaelmagu** [comment]
Is there a diagram available anywhere that explains the information flows between the multiple Concourse components?

**Comment by vito** [comment]
Is this addressed in any way now that 1.0 and its binaries are out?:

https://concourse.ci/binaries.html
https://concourse.ci/architecture.html

**Comment by rafaelmagu** [comment]
Yes, it is much clearer now. 👍
