### ISSUE TITLE
Dashboard: Long pipeline names

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2411]
Turn off scrolling on the pipeline name and add a tooltip for pipelines with too long names only. 

### Dashboard

![screen shot 2018-07-24 at 5 06 08 pm](https://user-images.githubusercontent.com/27746614/43166214-f9dc92a0-8f63-11e8-8c14-12764c2905b4.png)

### HD View

![screen shot 2018-07-30 at 10 40 17 am](https://user-images.githubusercontent.com/27746614/43404252-05b7305a-93e5-11e8-839a-71fd2d3f3c95.png)

## Proposed:
- [ ] update width of the text box

```
 .dashboard-pipeline-name {
    color: #fff;
    text-align: left;
    font-size: 1.5em;
    letter-spacing: .1em;
    padding: 12.5px;
    **width: 206px;**
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
![screen shot 2018-07-27 at 11 54 18 am](https://user-images.githubusercontent.com/27746614/43331461-f85f148e-9193-11e8-9766-48f2d8a670df.png)

- [ ] Tooltip for long pipeline names only
## Proposed:
* Tooltip would only show when name is too long and had to be shortened by (...)
* use more of the whitespace in the thumbnail
* turn off scroll completely 

### Dashboard
![screen shot 2018-07-30 at 1 50 07 pm](https://user-images.githubusercontent.com/27746614/43413995-8cc929c6-93ff-11e8-9d9c-9a2011a0067e.png)

### HD View
![screen shot 2018-07-30 at 1 54 41 pm](https://user-images.githubusercontent.com/27746614/43414226-287ff5f2-9400-11e8-8e34-770a8e5a3106.png)
![screen shot 2018-07-30 at 1 57 12 pm](https://user-images.githubusercontent.com/27746614/43414349-7db990aa-9400-11e8-8188-c699f8cc2efe.png)

**Comment by eedwards-sk** [comment]
Thank you thank you thank you for making this issue. I was prepared to make a stab at it and you described it so perfectly and wonderfully!

I'm loving the new dashboard view, pipeline name length aside, by the way :D

**Comment by xtremerui** [comment]
update:

After discuss with @Lindsayauchin the position of the tooltip on dashboard view would be slightly different. It will be left alignish with the card instead of centering. And the arrow will align with the first letter of the pipeline name. 

![screen shot 2018-08-22 at 10 05 56 am](https://user-images.githubusercontent.com/1585949/44468358-038cdf80-a5f3-11e8-8728-cbf4af2a0416.png)
