### ISSUE TITLE
Font polish

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2413]
- [x] Add Bold to the Job name on Pipeline view and the Job page

![screen shot 2018-07-25 at 9 26 51 am](https://user-images.githubusercontent.com/27746614/43204852-fcad40c4-8fef-11e8-9076-6c66afe794ff.png)

- [x] Bump up the body on the logs to 14 px

![screen shot 2018-07-25 at 9 51 02 am](https://user-images.githubusercontent.com/27746614/43204976-4a698f34-8ff0-11e8-8971-037f0a5a5794.png)

**Comment by Lindsayauchin** [comment]
- [ ] Add Bold to the Job name on Pipeline view and the Job page

![screen shot 2018-07-25 at 9 26 51 am](https://user-images.githubusercontent.com/27746614/43204852-fcad40c4-8fef-11e8-9076-6c66afe794ff.png)

- [ ] Bump up the body on the logs to 14 px

![screen shot 2018-07-25 at 9 51 02 am](https://user-images.githubusercontent.com/27746614/43204976-4a698f34-8ff0-11e8-8971-037f0a5a5794.png)

**Comment by jama-pivotal** [comment]
Build title is indeed bold and font is bumped up to 14px, accepting
