### ISSUE TITLE
fly command not accepting user input after returning from auto login flow

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#2414]
# Bug Report

Step to repro:
1. `fly -t ci logout`
1. `fly -t ci set-pipeline -p test -c something.yml`
1. click the link to auth in browser
1. try to type `y` to apply pipeline configuration
1. notice some of the user inputs do not register

Related PR: https://github.com/concourse/fly/pull/200

The following can also be handy:

* Concourse version: v4.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Not sure

**Comment by mhuangpivotal** [comment]
There are two ways to complete `fly login`, either by following the login URL or by entering the auth token manually. Two goroutines are responsible for handing the callback from the login URL and scanning user input for the manual entry. However, when the auth is complete through the login URL, the input scan in the second goroutine is not terminated, and would swallow inputs from a subsequent command.

https://github.com/concourse/concourse/blob/master/fly/commands/login.go#L174-L204

Specifically, `Scanf` on https://github.com/concourse/concourse/blob/master/fly/commands/login.go#L291 blocks until the user enters a token. The fix would be to cancel the scan when the auth callback is complete, but I'm not sure if that's something possible in go.

**Comment by mhuangpivotal** [comment]
Had to revert the commit since it hangs in Linux/Windows.

**Comment by cirocosta** [comment]
Hey @mhuangpivotal ,

Maybe doing some like described here (http://ixday.github.io/post/golang-cancel-copy/) might allow us to fix this issue.

We could switch from `scanf` to performing `io.Copy` w/ cancellation and then cancel the reading from stdin.

Wdyt?

thx!

**Comment by xtremerui** [comment]
@cirocosta with current login flow there is no easy way to terminate the go routine that blocked by `scanf`. In the example you mentioned it would still block on io.read if it doesn't return promptly (mentioned in the comment), which is exactly the issue for `scanf` here.

I think we might need to review the current login flow for listening manual token input as this is really a rare use case. Ideas are welcome!

**Comment by jama-pivotal** [comment]
Would it be easier if this autologin flow only supports browser callback based token transmission?
