### ISSUE TITLE
concourse.ci cert is invalid

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#2416]
# Bug Report

https://concourse.ci/ gives a cert error instead of a redirect, and I guess many people have this address in their browser cache

**Comment by vito** [comment]
We announced the new domain [back in March](https://medium.com/concourse-ci/were-switchin-domains-5597dcd0b48b) in connection to dubious security regarding the `.ci` TLD. Folks will have to switch over some time. I've updated the cert for now but eventually we should just let it expire.

**Comment by drahnr** [comment]
@vito agreed, but 5 months are not quite enough - browser bar autocompletion stays around for a way longer than you'd expect

**Comment by vito** [comment]
I expect it lasts forever. :P We're not waiting for autocompletes to
expire, we're giving people time to fix muscle memory and bookmarks. If
nothing ever cues it it'll never happen.

We could put a bouncer page in front to warn them to update it.

**Comment by drahnr** [comment]
The cert of concourse.ci is valid for concourse-ci.org, but not concourse.ci

The link in
https://docs.cloudfoundry.org/buildpacks/buildpack-ci-index.html
for integrating buildpacks into ci still points to the old one.

**Comment by vito** [comment]
Fixed (again) - it'll just take a bit for the DNS to propagate.
