### ISSUE TITLE
Feature Request: Push notification when specific build ID is done

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#242]
We have some jobs that take a long time to complete, and although we normally don't pay attention to every build, sometimes we have performed some manual intervention and care when a specific build finishes. I would like to ask a build # to text me when it has completed.

For example, I would like /pipelines/complicated-pipeline/jobs/long-job to mostly be silent, but when I kick off build #584, I would like to ask /pipelines/complicated-pipeline/jobs/long-job/builds/584 to text a specific phone number when it has completed. This would prevent me from spending superfluous cycles checking in on it, or craning my neck to keep checking my CI display.

Secondary feature request: Send the build completion as a toast to OS X's Notification Center. Would require installing something on my desktop, though.

**Comment by robdimsdale** [comment]
Alternative title: "SMS or Push Notification resource (out only)"

@vito @xoebus adding to the conversation in https://github.com/concourse/concourse/issues/191 which talks about existing resources, what's the plan for discoverability of requested resources? Issues on this repo are ok, but a little hard to discover

**Comment by xoebus** [comment]
I wouldn't implement these as resources. Adding an queryable stream of events and an interface to register callbacks (similar to GitHub) would be preferable. Many of the current resources don't model versionable external artefacts and are only resources because that's the only way to extend the system at the moment.

I think these notification features would be better modeled as a service which can consume an event stream or receive callbacks and then talk to Twilio, Google Cloud Messaging, APNS, etc. This has a number of advantages over an explosion of resources:

* Concourse doesn't need to know about your messaging system.
* This drives out the development of the callbacks API which will be more valuable to more applications.
* It keeps the resource interface from being misused and being driven in the wrong direction. (e.g. the environment variables we added to let you know which build and job a resource was being accessed from)

**Comment by robdimsdale** [comment]
I agree with everything said above. Callbacks are a better solution than resources.

@xoebus to clarify, in the above proposal, the event-stream consumer lives outside of concourse and is accessed via the callbacks API?

**Comment by xoebus** [comment]
Yep, you would register the messaging service with your Concourse server and then when an event happened (build started, build finished, pipeline added, pipeline deleted, etc.) it would send a message to the consumers who were interested in that event. They could then take that and do whatever they would like with it.

**Comment by xoebus** [comment]
It can be called `pan-pan`.

**Comment by robdimsdale** [comment]
Sounds like you could hook it up to Pivotal Notifications Services for enterprise use

**Comment by xoebus** [comment]
Bingo.

**Comment by xoebus** [comment]
Er. `s/Callbacks/Web Hooks` everywhere above.

**Comment by wendorf** [comment]
I only want one notification, though, not a notification for every similar event. I don't care when every pizza is delivered, only the one I just ordered! e.g. "\<a onclick='gimmeYourDigits()'\>Let me know when this build is done\</a\>"

**Comment by xoebus** [comment]
Sure, what gets sent is up to the service that is consuming the events. Some events will be a no-op. Some events (about a build someone has subscribed to) can send things.

**Comment by XenoPhex** [comment]
Can't this also be accomplished by supporting CCMenu?

**Comment by xoebus** [comment]
I think that CCMenu (and Checkman etc.) lack the push-yness that @wendorf wants.

**Comment by XenoPhex** [comment]
True, it's not going to exactly when the build ends, but you can set CCMenu (not sure about checkman) to inform you when builds finish. You can also set the check interval every n number of seconds, so it can be pretty close.

**Comment by xoebus** [comment]
Interesting. I wonder if a similar feature could be added to Checkman as we already have support for that.

**Comment by maryamklabib** [comment]
+1

**Comment by vito** [comment]
There are existing resources for sending notifications via Slack and other means. There is work to be done on improving the workflow for these specific types of resources, but I'm going to close this issue out as it's gotten pretty stale.

We've identified notifications as a potential vector for extending Concourse in more usable ways (i.e. not forcing you to explicitly configure resources everywhere). But this specific issue probably won't be something we explicitly implement ourselves.
