### ISSUE TITLE
default team auth not configured: No auth methods have been configured.

### ISSUE THREAD

**Issue by sanjay2916** [concourse/concourse#2421]
Hi Team,
 
I am deploying concourse on kubernetes , previously it worked fine but now i am getting the below error
kubectl get pods

NAME                            READY     STATUS    RESTARTS   AGE
concourse-8f98c8749-drhgh       0/1       Error     1          18s
concourse-db-668bd87dc9-cprrk   1/1       Running   0          1h

ubuntu@ip-172-31-21-12:~/concourse/concourse$ kubectl logs concourse-8f98c8749-drhgh

default team auth not configured: No auth methods have been configured.

concourse-deployment.yaml:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: concourse
  name: concourse
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: concourse
    spec:
      containers:
      - args:
        - quickstart
        env:
        - name: CONCOURSE_BASIC_AUTH_PASSWORD
          value: "admin"
        - name: CONCOURSE_BASIC_AUTH_USERNAME
          value: "admin"
        - name: CONCOURSE_EXTERNAL_URL
          value:
        - name: CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH
          value: "true"
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        - name: CONCOURSE_POSTGRES_HOST
          value: concourse-db
        - name: CONCOURSE_POSTGRES_PASSWORD
          value: concourse_pass
        - name: CONCOURSE_POSTGRES_USER
          value: concourse_user
        - name: CONCOURSE_WORKER_GARDEN_NETWORK
        image: concourse/concourse:latest
        imagePullPolicy: Always
        #resources:
         #   requests:
          #    cpu: 500m
        name: concourse
        ports:
        - containerPort: 8080
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
status: {}

**Comment by jama-pivotal** [comment]
@sanjay2916  ....did you try configuring an auth? https://concourse-ci.org/install.html#auth-config

**Comment by ezraroi** [comment]
it can't be done as the web server is not starting.... so the `fly set-team` can't be used

**Comment by jama-pivotal** [comment]
@ezraroi In concourse 4.0.0 you'll need to add allowed auth providers on startup. For example, the docs I lined above show and example of creating a basic auth user on `web` startup

```
concourse web \
  --add-local-user myuser:mypass
```

**Comment by sanjay2916** [comment]
@jama-pivotal  i have added below parameters then pod is running fine but not able to login to the concourse 

yaml file:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: concourse
  name: concourse
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: concourse
    spec:
      containers:
      - args:
        - quickstart
        env:
        #- name: CONCOURSE_BASIC_AUTH_PASSWORD
         # value: "admin"
        #- name: CONCOURSE_BASIC_AUTH_USERNAME
        #  value: "admin"
        - name: CONCOURSE_EXTERNAL_URL
          value:
        - name: CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH
          value: "false"
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        - name: CONCOURSE_POSTGRES_HOST
          value: concourse-db
        - name: CONCOURSE_POSTGRES_PASSWORD
          value: concourse_pass
        - name: CONCOURSE_POSTGRES_USER
          value: concourse_user
        - name: CONCOURSE_WORKER_GARDEN_NETWORK
        - name: CONCOURSE_ADD_LOCAL_USER
          value: admin:admin
        - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
          value: admin
        image: concourse/concourse:latest
        imagePullPolicy: Always
        #resources:
         #   requests:
          #    cpu: 500m
        name: concourse
        ports:
        - containerPort: 8080
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
status: {}

**Comment by keithkroeger** [comment]
We are seeing the same.

We also note that https://github.com/concourse/concourse/blob/v4.0.0/jobs/atc/spec#L162 notes that the password should be bcrypted, but when this is done, the bcrypted password is actually the user's password.

What we find is we get redirected to:
/sky/callback?code=u7uxgcap4stjlfu7noecr6x3g&state=eyJyZWRpcmVjdF91cmkiOiIvIiwiZW50cm9weSI6IjYxYTdkMmFlMDJkOGJmMzg0NzViZjFkNjY3YWFhYTU5ODllYjBmNzJmMjAxOTkzMjFjYjgwM2Q2YTUxZjc0N2YifQ%3D%3D

**Comment by sanjay2916** [comment]
@keithkroeger  i have added password in bcrypt password but not able to login

    - name: CONCOURSE_ADD_LOCAL_USER
       value: admin:$2y$12$Dbx4XIWdULXe.eGR1FDK5O1k9WNWNep/KcTrsXgz.bsR1OXYXmcPa

**Comment by keithkroeger** [comment]
Thank you, @sanjay2916, what we found is that we bcrypted, we got an 'invalid password' error.  If we didn't, we were routed to the 'callback' that didn't finalize

**Comment by sanjay2916** [comment]
I have tried to deploy old versions but it giving below error

"failed to migrate database: file does not exist"

**Comment by sanjay2916** [comment]
@AnianZ  i have added above parameter and pod is running fine but not able login to UI

- name: CONCOURSE_EXTERNAL_URL
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        - name: CONCOURSE_POSTGRES_HOST
          value: concourse-db
        - name: CONCOURSE_POSTGRES_PASSWORD
          value: concourse_pass
        - name: CONCOURSE_POSTGRES_USER
          value: concourse_user
        - name: CONCOURSE_WORKER_GARDEN_NETWORK
        - name: CONCOURSE_ADD_LOCAL_USER
          value: test:$2y$12$o63qgMyIIs9F.ctCsPnBquJdTuqWmxatjY02U5y5gxmEcT6v.Yq/G
        - name: CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS
          value: "true"

**Comment by AnianZ** [comment]
Did you use your actual password or did you try to use `$2y$12$o63qgMyIIs9F.ctCsPnBquJdTuqWmxatjY02U5y5gxmEcT6v.Yq/G` as the password as well. I'm far from an expert there, but I'm not sure if a salted and hashed password works there.

**Comment by AnianZ** [comment]
The alternative to `CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS: "true"` is to give access to the main team for a local user via `CONCOURSE_MAIN_TEAM_LOCAL_USER: myuser`. That option is documented in the flags for the quickstart deployment. I missed that first.

**Comment by sanjay2916** [comment]
@AnianZ  are you able to login to the concourse UI after deploying latest version

**Comment by AnianZ** [comment]
Yes. I managed to upgrade my old instance, log in and also deploy a new one with gitlab auth.

**Comment by torarnv** [comment]
This also affects the quick start, and https://concoursetutorial.com/, which no longer starts up.

**Comment by SHyx0rmZ** [comment]
This is just a wild guess, but can you try turning every `$` in the bcrypted password into `$$`?

**Comment by torarnv** [comment]
Looks like I was using an outdated compose file, this one seems to have the right stuff:
https://concourse-ci.org/docker-compose.yml

- Tor Arne

**Comment by sanjay2916** [comment]
@vito @torarnv I have deployed concourse latest version with "add-local-user" parameter changes on kuberntes environment


 env:
        - name: CONCOURSE_ADD_LOCAL_USER
          value: test:$2y$12$mLCjC0r4AIoJxuvRHlxgs.D4iCawcKcOmdRFZpx./JU0iWx3Td7kW

When I try to login to the concourse Ui, its redirecting to the below url:

sky/callback?code=sv5r7cw6fw3atl7s7xfwkrzny&state=eyJyZWRpcmVjdF91cmkiOiIvIiwiZW50cm9weSI6ImZkNWExMjBjZjU5NjE2N2FkOTc5ZWQyZjNlMmVkMmE3YTcwZjZhOGNlODUzZmY3NWJmMmE4ZGFjNTU3ZjEwNmUifQ%3D%3D

anything we need to add before password

**Comment by keithkroeger** [comment]
Hello @sanjay2916, should we open a new issue for all of the discussion of not being able to log on with basic auth and the redirect to /sky... occurring?

**Comment by torarnv** [comment]
I also saw that issue with the redirect, I just refreshed a few times and logged in and out and somehow it went away :smile:

**Comment by sanjay2916** [comment]
@keithkroeger  after adding CONCOURSE_EXTERNAL_URL it redirecting to concourse url , instead of localhost:8080

**Comment by sanjay2916** [comment]
thanks to all 
now its working as expected

**Comment by keithkroeger** [comment]
Thank you, @sanjay2916, but we're redirecting to https://concourse-canary.fmr.com/sky/callback?code=i3uo5vh4gfq2vgzzwgi2avblp&state=eyJyZWRpcmVjdF91cmkiOiIvIiwiZW50cm9weSI6IjY2NWRhMDVhMDYxNmNhMDJiYmJlYmQ2ZGM0YjAzYWVmZjY0MTJjZGZmMGYwYjM2MmVlMDU0OWFkNzJkNzljNjEifQ%3D%3D

**Comment by sanjay2916** [comment]
@keithkroeger  i am using 4.0.0

**Comment by phynias** [comment]
i was having this problem. first i tried to add the user like you said here but i was getting this error: 
```
concourse web   --add-local-user user:pass --tsa-host-key /etc/concourse/tsa_host_key --tsa-authorized-keys /etc/concourse/authorized_worker_keys
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25c854c]

goroutine 1 [running]:
main.(*WebCommand).populateTSAFlagsFromATCFlags(0xc4204ec308, 0x2, 0x2)
	/tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:81 +0x5c
main.(*WebCommand).Runner(0xc4204ec308, 0xc42019c540, 0x0, 0x7, 0x2149481, 0xc42051ee80, 0xc420755660, 0x21499d0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:56 +0x6d
main.(*WebCommand).Execute(0xc4204ec308, 0xc42019c540, 0x0, 0x7, 0x28b59a0, 0x2b52f80)
	/tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:42 +0x4d
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7ff853888360, 0xc4204ec308, 0xc42019c540, 0x0, 0x7, 0x1, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/vito/twentythousandtonnesofcrudeoil/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4200a1620, 0xc42004c090, 0x7, 0x7, 0xc420755840, 0x21492df, 0xc4200a1620, 0x2bb0ae6, 0xa)
	/tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:314 +0x7c7
github.com/jessevdk/go-flags.(*Parser).Parse(0xc4200a1620, 0x2bb0ae6, 0xa, 0xc42051ff80, 0x0, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/main.go:33 +0x1a4
```

then i added thew CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS: "true" to get passed that and now when i start web i get this:
```
Aug  3 22:14:37 ci systemd[1]: Started Concourse CI web process (ATC and TSA).
Aug  3 22:14:38 ci concourse[3868]: server: no connectors specified
Aug  3 22:14:38 ci systemd[1]: concourse-web.service: Main process exited, code=exited, status=1/FAILURE
Aug  3 22:14:38 ci systemd[1]: concourse-web.service: Unit entered failed state.
Aug  3 22:14:38 ci systemd[1]: concourse-web.service: Failed with result 'exit-code'.
Aug  3 22:14:38 ci systemd[1]: concourse-web.service: Service hold-off time over, scheduling restart.
Aug  3 22:14:38 ci systemd[1]: Stopped Concourse CI web process (ATC and TSA).
```
