### ISSUE TITLE
New resources are no longer highlighted in UI

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#2423]
# Bug Report

Highlighting of new resources broken in Concourse 4.0.0, which was a super useful feature to see what triggered a given build. In previous releases the resources versions which changed since the last build were highlighted in the UI but now all the resource bar appear as the same color:

![screen shot 2018-07-27 at 11 13 21 am](https://user-images.githubusercontent.com/1923644/43339404-1b35a4ba-918e-11e8-9f5a-698c0f1ad634.png)

Looks like a missing CSS rule. I installed a browser plugin to define custom CSS rules when the site loads and this fixes it:

```
.build-step.first-occurrence > .header {
    background: #5f5b5b; /* probably not exactly the right shade */
}
```

Back to normal:

![screen shot 2018-07-27 at 11 10 35 am](https://user-images.githubusercontent.com/1923644/43339379-0454b8e4-918e-11e8-989a-caa42daf7216.png)

The following can also be handy:

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: N/A
* Browser (if applicable): Chrome and Safari
* Did this used to work? Worked prior to 4.0.0

**Comment by Lindsayauchin** [comment]
- [ ] Update icons to #F1C40F

![screen shot 2018-07-30 at 10 13 10 am](https://user-images.githubusercontent.com/27746614/43402834-98096274-93e1-11e8-9397-3f3df90a9aaf.png)
