### ISSUE TITLE
Pipeline pause/play icons should be disabled if you don't have the ability to pause/play that pipeline

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2428]
* Clearly indicate that it is "disabled" (i.e. fade it out)
* No hover state
* Show "not authorized" tooltip if logged in but don't have permission, "not logged in" if...not logged in

**Comment by pivotal-jamie-klassen** [comment]
pushing this down the backlog a bit to give @Lindsayauchin a chance to weigh in - the requirement here is for the icon to look clearly "disabled" without having to hover, which requires some sort of design choice.

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen Can we try an opacity style of 0.2 to indicated disabled in this case? (This is probably the limit of contrast for accessibility. )

## Disabled Play/Pause:

![Screen Shot 2019-04-11 at 5 23 41 PM](https://user-images.githubusercontent.com/27746614/55994019-9c559580-5c7e-11e9-9257-a0d7dab6adda.png)


## Tooltip:

![Screen Shot 2019-04-11 at 5 27 26 PM](https://user-images.githubusercontent.com/27746614/55994213-1dad2800-5c7f-11e9-87eb-638b88104f38.png)
