### ISSUE TITLE
Support retry limits on container creation

### ISSUE THREAD

**Issue by a459259** [concourse/concourse#2429]
# Feature Request

## What challenge are you facing?

We've experienced an issue where our internal Docker hub has not been accessible - Concourse workers spiraled with container creations as a result until a 256 max was reached and the application became a dead duck.  The operations teams shutdown the workers until the issue with docker hub was resolved and recreated the workers. 

## A Modest Proposal

Instead of spiraling in its attempt to create containers perhaps there should be a retry limit which when breached can result in a failed job/resource-check and information back to the user on why the retry limit was breached.

**Comment by jama-pivotal** [comment]
We addressed some of this in 4.0.0 with:
https://github.com/concourse/docker-image-resource/pull/227
and related commit https://github.com/concourse/docker-image-resource/commit/7ed28aa73075512a7b153ac9ecaf5fc57ec96db4 😄

**Comment by topherbullock** [comment]
Related: #755

**Comment by scottietremendous** [comment]
@a459259 - Can we consider this one closed?

**Comment by topherbullock** [comment]
@scottietremendous @a459259

Went through the flow of container creation with @cirocosta and we're fairly confident that it won't run away and create lots of containers if docker is down or the resource fails (https://github.com/concourse/docker-image-resource/pull/227) . 

There are other concerns in #755 around retry if the worker is dead, but in the case of DockerHub being down, or the Docker Daemon failing we'll either fail to create or hang until the check session expires. There's related discussion on #2988 around making the re-use of those container configurable, and potentially making checks more light-weight by not keeping the containers around at all #3079
