### ISSUE TITLE
Feature Request: Change favicon color to indicate build status

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#243]
If I'm on a build page, I'd love the black airplane favicon to change color to represent the state of the build. When it goes green or red, I know my build is done!

```
 |\_/|     
 (. .)
  =w= (\   
 / ^ \//   
(|| ||)
,""_""_ .
```

**Comment by xoebus** [comment]
I like it. We'll have a new favicon coming soon so this should wait until after that though.

**Comment by wendorf** [comment]
Hi @xoebus ,

Is there an issue where I can track the new favicon?

**Comment by xoebus** [comment]
https://github.com/concourse/concourse/issues/70
