### ISSUE TITLE
No results found text not properly aligned when page is scrolled

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2435]
There are specific steps to reproduce:

1. Load the dashboard (any resolution) https://ci.concourse-ci.org/
2. Scroll so that the team name stickies
3. Search for something with no users found

This is what happens:

![screen shot 2018-07-30 at 10 08 32 am](https://user-images.githubusercontent.com/27746614/43402368-955e8262-93e0-11e8-8cd5-8cabb21f5eda.png)

**Comment by pivotal-jamie-klassen** [comment]
this is really tough to test and prevent regressions (we'll need some more sophisticated assertions in watsjs, someday), but did in fact get fixed as a consequence of our hand-rolled sticky header solution in #2430.
