### ISSUE TITLE
Support for pinning a resource to a given version across the pipeline

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2439]
# Feature Request

## What challenge are you facing?

Today you can pin versions on individual `get` steps (via [`version`](https://concourse-ci.org/get-step.html#get-step-version), however sometimes I simply know I'll only ever want to use a particular version across the entire pipeline. This often comes up with an upstream dependency with loose coupling but conservative bumping, or if a regression in introduced in recent versions and I want to just go back to the prior version.

Today this is accomplished by disabling all versions after the one I want, and (optionally) pausing the resource. But that takes a lot of clicking and that information is lost when the pipeline is relocated (since it has no reflection on the config).

## A Modest Proposal

Let's allow users to specify `version` directly on the resource, like so:

```yaml
resources:
- name: my-resource
  source: {repository: ruby, tag: '2'}
  version: {digest: "sha256:d30dd035da0c3aa42210e5f84dedc22d9a6c419bcfe376f76188d74ad08e77b0"}
```

This would have the same effect as pinning all `get` steps to the given version.

If any `get` steps referring to the resource already have a pinned version, their version should take precedence.

Later, we can add a button in the web UI to do this while "in anger" and trying to quickly un-break a pipeline: https://github.com/concourse/concourse/issues/1288

This will also be improved by concourse/rfcs#1 which will ensure that the pinned version is always present in the history. (Don't worry about that as part of this story - the situation will go away entirely in the future!)

This also mitigates one concern in https://github.com/concourse/concourse/issues/2386 regarding pausing pipeline resources. Once we have this feature, I think we can get rid of "resource pausing".

**Comment by mhuangpivotal** [comment]
After discussing with @vito, we find it more intuitive for pinned versions on the resource to take precedence over pinned versions in `get` steps. This also works better for a later story that will add the ability to pin versions of a resource in the UI (#1288).
