### ISSUE TITLE
Removal of sidebar for pipeline groups makes navigation difficult

### ISSUE THREAD

**Issue by mcwumbly** [concourse/concourse#2440]
Hi there!

# Feature Request

## What challenge are you facing?

[Our team uses concourse heavily](https://releng.ci.cf-app.com/). We currently have 41 pipelines (and that's after removing a number of them recently). We regularly have to monitor several of these pipelines concurrently, as we are responsible for regularly shipping patches to 4 versions of 4 products. Each of these pipelines are large. For example, here's a typical one (of these 41) pipelines that has ~80 jobs split into ~10 pipeline groups:

![one-pipeline](https://user-images.githubusercontent.com/2217652/43414075-924d2802-93e6-11e8-979b-9c8cff828568.png)

![ten-groups](https://user-images.githubusercontent.com/2217652/43414081-967cc612-93e6-11e8-9730-78a5ad1e62c0.png)

Before, upgrading to 4.0, there was a sidebar with our ~40 pipelines so when we were viewing one, we could relatively easily navigate to another.  Now, we have to go back and forth to the dashboard, which is much more cumbersome.

Using [high density mode](https://releng.ci.cf-app.com/hd) does make things a little better, but it still requires one to go back and forth quite a bit, or to keep a tab open and remember to open new pipelines in new tabs... 

## A Modest Proposal

Please bring back the persistent sidebar menu in some form so that we can navigate from one pipeline to another with a single click, regardless of where we are in the hierarchy of the UI.

**Comment by Lindsayauchin** [comment]
@mcwumbly 

An alternative could be adding global search to the top nav. This would be a quicker way than bringing back the sidebar to get to another pipeline. 

But, this has the added complication of introducing ability to search/filter the pipeline page as well as the user would expect to 'search'/filter the page they are on. This ability though would be nice for quickly navigating to a resource, job page or error. 

![screen shot 2018-08-14 at 12 09 11 pm](https://user-images.githubusercontent.com/27746614/44103683-e704ed5a-9fba-11e8-8f37-7b4b12510923.png)

![screen shot 2018-08-14 at 11 32 45 am](https://user-images.githubusercontent.com/27746614/44101713-0af308d2-9fb6-11e8-9de8-6477fb7457dd.png)

**Comment by Lindsayauchin** [comment]
@vito @mcwumbly @pivotal-jamie-klassen 

- [ ] The list can be vertically scrolled independently of the rest of the screen’s content.
- [ ] Sidebar starts at the same level as the content below the top app bar and the sidebar will push the content to the right (not on top of the content as some users like to keep the sidebar expanded at all times. 
- [ ] Pipelines will be grouped by team
- [ ] Toggling a chevron icon on the left of the team name expands the list of pipelines for that team. This expanded list of pipelines remains persistent to the user. 
- [ ] Team icon will appear beside the team names
- [ ] Pipeline icon appears beside the pipeline the use is currently in
- [ ] Hover state on list will follow the UI style used for the groups bar on the pipeline view. 


## Bring back the sidebar proposal: 

### Pipeline
**Expanded:**
![Screen Shot 2019-04-10 at 2 57 29 PM](https://user-images.githubusercontent.com/27746614/55906218-b9686680-5ba1-11e9-8c18-98b4664cf47e.png)

**Collapsed:**
![Screen Shot 2019-04-10 at 2 57 11 PM](https://user-images.githubusercontent.com/27746614/55906232-c2f1ce80-5ba1-11e9-981b-51fe05b92c40.png)

### Dashboard:
![Screen Shot 2019-04-10 at 2 56 43 PM](https://user-images.githubusercontent.com/27746614/55906236-c7b68280-5ba1-11e9-834b-b78c0baa1760.png)

### Build page:
![Screen Shot 2019-04-10 at 2 56 58 PM](https://user-images.githubusercontent.com/27746614/55906242-cbe2a000-5ba1-11e9-85b2-cd3e44f014ee.png)

### Resource Page
![Screen Shot 2019-04-10 at 3 01 45 PM](https://user-images.githubusercontent.com/27746614/55906251-d00ebd80-5ba1-11e9-90ae-3e70dc08d95d.png)

**Comment by mcwumbly** [comment]
@Lindsayauchin we use "groups" pretty heavily to keep pipelines organized. Is there any consideration in the design to also group by pipelines by group?

You can browse our pipelines here to get a better sense of our concrete problem: https://releng.ci.cf-app.com/

**Comment by Lindsayauchin** [comment]
@mcwumbly something like this?

![Screen Shot 2019-04-11 at 9 50 30 AM](https://user-images.githubusercontent.com/27746614/55964226-5bd82680-5c42-11e9-841a-f1731f37571f.png)
Chevron would indicate that the pipeline has groups and can be expanded to show them. 

Do you think it make sense to display the groups at this level? It could be collapsed away and then the user expands a keeps them persistent. 

Thoughts?

**Comment by mcwumbly** [comment]
Yes, I think that would be helpful for us!

**Comment by vito** [comment]
given that i have the sidebar open and some teams expanded,
when i refresh the page
then the sidebar should still be open but all the teams collapsed.

**Comment by vito** [comment]
MVP is no groups in sidebar

**Comment by vito** [comment]
@jama22 separate story for status icons on sidebar pipelines

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin how about tooltips for long team/pipeline names? Might as well get that in before release, as I can imagine some users who consistently have long team names who will find a 275px sidebar unusable.

Also as I play with this feature I find myself craving a keyboard shortcut to toggle the sidebar. @vito

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen 
something like this?

![Screen Shot 2019-05-06 at 4 22 35 PM](https://user-images.githubusercontent.com/27746614/57252833-34933000-701b-11e9-8847-75c2e9d0e386.png)
