### ISSUE TITLE
Allow concourse to support global secrets

### ISSUE THREAD

**Issue by StevenArmstrong** [concourse/concourse#2442]
## A Modest Proposal

Currently concourse only supports secrets scoped to a team or a pipeline as per the documentation 
E.g /concourse/main/foo 
      /concourse/team_a/mypipeline/foo
I have multiple common secrets that sit across multiple teams and I want to minimise the duplication in vault. 
It would be helpful if there was a  namespace
/concourse/global
This would allow secrets to be shared across teams if they are generic and minimise duplication that could be imported to all teams.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Iaas
* Browser (if applicable): N/A
* Did this used to work? No

**Comment by vito** [comment]
sounds like https://github.com/concourse/rfcs/issues/5 is relevant?
