### ISSUE TITLE
Document how to provide lists via environment variables

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#2445]
# Feature Request

## What challenge are you facing?

I wanted to provide a list of local users via environment variable, but didn't know how. My intuition, to use commas to separate, was correct, but I only learned that after embarrassingly asking in the forums and being told my guess was right. :)

## A Modest Proposal

The CLI `--help` (which, as far as I know, is the only place that documents that environment variables can be used?) has a section describing how to specify lists in environment variables. It'd be extra nice if it explained how to include commas in the values without splitting. (e.g. if my org name happened to be `comma,fans`).

**Comment by jama-pivotal** [comment]
Thanks for the suggestion @wendorf ! I hope you don't mind but I'm going to migrate this issue to our docs repo here: https://github.com/concourse/docs/issues/98
