### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by mikemol** [concourse/concourse#2449]
# Feature Request

## What challenge are you facing?

Authenticating users as having access to teams.

## A Modest Proposal

Within an enterprising using the GitHub Enterprise product, GHE is available as a useful authentication mechanism, and Concourse's other supported mechanisms may not be available. Concourse supports GitHub authentication, but doesn't expose the configuration necessary to point the ATC at a private GitHub installation instead of the public one.

If you expose the necessary configurations to point the ATC at a GitHub Enterprise installation, this is obviously solved, and it (shouldn't) require significant new work.

**Comment by SHyx0rmZ** [comment]
Which necessary configuration where you thinking about? Concourse already takes `--github-host` and `--github-ca-cert`, which I would assume would be enough (I have no experience with GitHub Enterprise, though). Could you please also let us know how you deploy Concourse, as this might simply be caused by a deployment method not exposing these options well enough.

**Comment by superbeeny** [comment]
We use GHE as the backing provider for authentication, this might help you out some - https://docs.pivotal.io/p-concourse/authenticating.html

**Comment by vito** [comment]
We already support this as documented here: https://concourse-ci.org/install.html#github-auth-config

**Comment by mikemol** [comment]
Sorry it's taken me so long to respond.

@vito, those docs only talk about GitHub, not GitHub Enterprise.

@SHyx0rmZ, where are `--github-host` and `--github-ca-cert` documented? I've only seen the docs @vito referenced.

**Comment by vito** [comment]
@mikemol 

> If you're configuring GitHub Enterprise, you'll also need to set the following flags:

Having a separate header would help, but it's there. :)

**Comment by mikemol** [comment]
Ok, color me embarrassed, but that's fair. :)
