### ISSUE TITLE
Concourse Pipelines are in paused state

### ISSUE THREAD

**Issue by arpitvipulsharma** [concourse/concourse#2457]
Hello All, We are facing issue with concourse. We have 3 concourse server(version 3.14.1). We have  one database node of postgres(10.4). Suddenly concourse stopped working on all nodes. It was showing pipelines in pending stage(gray colored).  This thing generally happened on all servers at same time, as we are facing this issue 3rd time. When I try to login into server, it hangs and i am not able to login there. I need to restart all server from management panel. Even after restarting, it doesnt work. I need to restart web and worker service 2-3 times. After restarting server, If I upload new pipeline(hello world pipeline), it will work. But old pipeline need restarting service 2-3 times.it shows worker in fly command, uptime for ATC was 3-4 days as we faced this issue 3-4 day ago also.its binary installation.we have installed this setup in vms on ESXi.Can anybody help me?
![untitled](https://user-images.githubusercontent.com/30121845/43600632-6fcba478-968b-11e8-80e7-0086f604ffbf.png)

**Comment by marco-m** [comment]
Hello, I strongly suggest to setup metrics to enable monitoring of your Concourse installation, see https://concourse-ci.org/metrics.html. Without metrics, you are blind and you don't see problems coming, you discover them when it is too late. See also https://discuss.concourse-ci.org/t/things-to-monitor/278.
