### ISSUE TITLE
fly set-team deprecates CF space GUIDs

### ISSUE THREAD

**Issue by x6j8x** [concourse/concourse#2460]
Hi,

we're using a service broker to hand out Concourse teams on our Cloud Foundry platform. 

4.0 deprecated cf-space-guids on `set-team` which seems unnecessary and even dangerous...

- Space & org names can (and do) change! So it's a rather bad idea to rely on them instead of the Guids. If you want to keep the ux of passing space & org names as args for `set-team`,  you should resolve them to Guids and only store and use the guids. 

Using the org:space names as claims in the access token can also lead to undesired effects (after org/space renaming - which is easy to do on the CF side) - like having no access anymore or even the wrong people having access.

https://github.com/concourse/dex/blob/6ec745c7f7ad6b5f1e8b1d4e4f6ac6f3bb22044d/connector/cf/cf.go#L271

- When taking the service-broker route to create concourse teams, you get the OrgGuid & SpaceGuid from the service broker (and no!! names).

**Comment by eruvanos** [comment]
Any update on this issue?

**Comment by xtremerui** [comment]
No. `space-guid` should be kept. https://github.com/concourse/concourse/pull/5035 is submitted.
