### ISSUE TITLE
Support manual token entry during login when running `fly` from a remote shell

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2464]
`fly` listens on `127.0.0.1` for the callback, but that won't work if I'm running `fly` somewhere different from where my browser is running. So e.g. my Chromebook (which runs Linux in a container/VM via Crostini) or if I'm in a remote shell.

The `fly` command will let you insert a bearer token manually, but there's no way to get this token via the login flow. I've been hacking it by setting the redirect URI to `https://httpbin.org/anything` which is...not great security-wise.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): any
* Infrastructure/IaaS: any
* Browser (if applicable): any
* Did this used to work? yes - I could remove the `&fly_local_port=` part of the URL, and the page I landed on had just the token string which I could then copy-paste. (also not a great workflow but at least it worked)

**Comment by issmirnov** [comment]
Any thoughts on a potential ETA?

**Comment by ddadlani** [comment]
@issmirnov this should now be done. After login, the token can be found at `/sky/token`. 

This should be shipped in the next release (likely v4.2.0).

**Comment by vito** [comment]
@ddadlani The endpoint is there but there's no `fly` UX done for this yet. I think we just need some way for the user to know about or be redirected to the new endpoint.

Maybe rather than just asking for the token, we could say something like 'if you are logging in from a remote shell, please go to this URL instead and enter the token:'

and then show the URL with the redirect URI set to `/sky/token`

or something

it's kinda verbose

idk

**Comment by ddadlani** [comment]
The endpoint should also be changed from /sky/token to something else since supporting GET requests on /sky/token violates the OAuth spec.

**Comment by xtremerui** [comment]
`--remote` or `-r` is added to fly login command so the redirect after logged in goes to `/sky/token`, which allow user to copy the token and manually enter it in terminal.
