### ISSUE TITLE
Alias ATC_EXTERNAL_URL with CONCOURSE_EXTERNAL_URL

### ISSUE THREAD

**Issue by analytically** [concourse/concourse#2465]
Proposal: add CONCOURSE_EXTERNAL_URL that is the same as ATC_EXTERNAL_URL. For people unfamiliar with Concourse, ATC_EXTERNAL_URL is confusing.

**Comment by r-chris** [comment]
As far as I know there already is a `CONCOURSE_EXTERNAL_URL` used when setting up the web service - would that not be more confusing? (I have to admit I'm unfamiliar with `ATC_EXTERNAL_URL`)

**Comment by xtremerui** [comment]
`CONCOURSE_EXTERNAL_URL` is the only one now.
