### ISSUE TITLE
Concourse LDAP Integration - Successful Lookup, but Fails to Login - missing following required attribute(s): [\"\"]"

### ISSUE THREAD

**Issue by akamalov** [concourse/concourse#2466]
**Environment:**

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): binary
* PAAS: Pivotal Cloud Foundry: 2.0
* Infrastructure/IaaS: vsphere
* Fly: 4.0
* Browser (if applicable): Chrome

**Problem:**

Trying to integrate Concourse with LDAP.  Receiving the following error:

```
Aug  6 10:35:52 akjump001 concourse[25488]: {"timestamp":"1533566152.971009493","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{"connector":"LDAP"},"message":"performing ldap search ou=Users,dc=XXXXXXXXX,dc=localnet,dc=com sub (sAMAccountName=alex123)","session":"6"}}
Aug  6 10:35:53 akjump001 concourse[25488]: {"timestamp":"1533566153.043900728","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{"connector":"LDAP"},"message":"username \"alex123\" mapped to entry CN=XXXXXXXXXX\\, Alex,OU=Users,DC=XXXXX,DC=localnet,DC=com","session":"6"}}
Aug  6 10:35:53 akjump001 concourse[25488]: {"timestamp":"1533566153.090707302","source":"atc","message":"atc.dex.event","log_level":2,"data":{"fields":{},"message":"Failed to login user: ldap: entry \"CN=XXXXXXXX\\\\, Alex,OU=Users,DC=XXXXXXXXXX,DC=localnet,DC=com\" missing following required attribute(s): [\"\"]","session":"6"}}
Aug  6 10:35:53 akjump001 concourse[25488]: {"timestamp":"1533566153.747877836","source":"tsa","message":"tsa.connection.channel.channel-request","log_level":1,"data":{"remote":"XXXX.XXX.XXX.XXX:40992","session":"11.1","type":"exec"}}
```

My Concourse LDAP integration configuration is following:

```
# LDAP Integration
# CONCOURSE_LDAP_DISPLAY_NAME=concourse
CONCOURSE_LDAP_DISPLAY_NAME=LDAP
CONCOURSE_LDAP_HOST=ldap.localnet.local:636
CONCOURSE_LDAP_BIND_DN='XXXX\\XXXXXXXXX'
CONCOURSE_LDAP_BIND_PW='XXXXXXX'
CONCOURSE_LDAP_INSECURE_SKIP_VERIFY=true
CONCOURSE_LDAP_START_TLS=false
CONCOURSE_LDAP_USER_SEARCH_USERNAME="sAMAccountName"
CONCOURSE_LDAP_USER_SEARCH_BASE_DN="ou=Users,dc=XXXXXXXX,dc=localnet,dc=com"
CONCOURSE_LDAP_USER_SEARCH_SCOPE="sub"
CONCOURSE_LDAP_USER_SEARCH_ID_ATTR="uid"
CONCOURSE_LDAP_USER_SEARCH_EMAIL_ATTR="mail"

CONCOURSE_LDAP_GROUP_SEARCH_BASE_DN="ou=Groups,dc=XXXXXXXX,dc=localnet,dc=com"
CONCOURSE_LDAP_GROUP_SEARCH_USER_ATTR="sAMAccountName"
CONCOURSE_LDAP_GROUP_SEARCH_GROUP_ATTR="member"
```

It looks like a user lookup is successful...

```
"username \"alex123\" mapped to entry CN=XXXXXXXXXX\\, Alex,OU=Users,DC=XXXXX,DC=localnet,DC=com","session":"6"}}
```
 but Concourse is looking for additional  attributes ?

```
missing following required attribute(s): [\"\"]","session":"6"}}
```

Can anyone tell me what is it I am doing wrong here?

Thanks so much!!

**Comment by akamalov** [comment]
Really, no one ? Not even label ?

**Comment by breed85** [comment]
@akamalov 
I had a similar issue when I set it up initially, but was able to get it working. For me, I received the error you posted when I referenced an attribute that wasn't available on in our LDAP data. I also had a lot of issues dealing with quotes in the configuration. 

I used docker-compose to define the environment variables and in that case I wasn't able put quotes around anything without it erring. You may want to try taking the quotes out and see if that improves things. 

Here is an example of how I defined everything:
```
version: '3'

services:
  concourse-web:
    environment:
    - CONCOURSE_LDAP_USER_SEARCH_EMAIL_ATTR=mail
    - CONCOURSE_LDAP_USER_SEARCH_NAME_ATTR=displayName
    - CONCOURSE_LDAP_USER_SEARCH_ID_ATTR=sAMAccountName
    ...

```

**Comment by xtremerui** [comment]
Hi @akamalov , this error seems come from dex https://github.com/coreos/dex/blob/036e5d050dacdb3aa51029206e2bc26862abfbc3/connector/ldap/ldap.go#L333

Did you check their docs about ldap connector config [here](https://github.com/coreos/dex/blob/master/Documentation/connectors/ldap.md)?

Note we do use concourse fork of Dex so there could be potential fixes (if applicable here) missed here.

**Comment by vito** [comment]
@akamalov I'm sorry we're not able to dig in to every issue and give everyone the attention they deserve. But please be more patient. This isn't a paid support channel, we're doing the best we can.

**Comment by loghen41** [comment]
I had the similar issue, but I found the problem in my case was that the defaulting of the `CONCOURSE_LDAP_USER_SEARCH_EMAIL_ATTR` parameter.

Looking at Dex's codebase, you are required to provide the User id attr, and the user email attr.  You can optionally provide the name attr, as shown in this snippet:
```
	// Fill the identity struct using the attributes from the user entry.
	if ident.UserID = getAttr(user, c.UserSearch.IDAttr); ident.UserID == "" {
		missing = append(missing, c.UserSearch.IDAttr)
	}
	if ident.Email = getAttr(user, c.UserSearch.EmailAttr); ident.Email == "" {
		missing = append(missing, c.UserSearch.EmailAttr)
	}
	// TODO(ericchiang): Let this value be set from an attribute.
	ident.EmailVerified = true

	if c.UserSearch.NameAttr != "" {
		if ident.Username = getAttr(user, c.UserSearch.NameAttr); ident.Username == "" {
			missing = append(missing, c.UserSearch.NameAttr)
		}
	}
```

I found that if you do not set either the email or userid attr, that error message will come up empty, as it expects the attribute to exist.  (which is what happened to me as the email attribute did not default correctly)  

In your case, you are setting both of the required attributes, but not the optional name attribute.  You might try setting that name attribute, and see if it fixes the issue for you.

**Comment by akamalov** [comment]
Thank you so mucgh @loghen41. I will give it a shot and see if can get through it!

**Comment by akamalov** [comment]
worked. Thank you so much @loghen41 and @vito. Thanks yet again!!
