### ISSUE TITLE
4.0.0 - cannot unpause a pipeline after logging in through fly

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/concourse#2467]
# Bug Report

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Docker (web / linux worker) Darwin (worker)
* Infrastructure/IaaS:
* Browser (if applicable): Chrome
* Did this used to work? No? (New Auth Flow)

After launching a 4.0.0 cluster and logging in through the web, then setting a pipeline from the CLI, then attempting to unpause the pipeline from the web again, received a 403 not authorized in the browser network tab and unable to unpause.

Steps to Reproduce:

1) stand up new concourse cluster with a single main team user `admin` with password `admin`

2) launch cluster (I used docker compose)

3) log in to web UI

4) return to CLI and execute a `fly set-pipeline` without logging in from CLI first

```
could not find a valid token.
logging in to team 'main'

navigate to the following URL in your browser:

  http://concourse.service.local.consul:8080/sky/login?redirect_uri=http://127.0.0.1:58944/auth/callback
```

5) Use login redirect url as per above

6) After setting pipeline, return to web UI

7) attempt to unpause the pipeline

Expected Results:

Pipeline Unpauses

Actual Results:

No indication in UI, no UI response whatsoever. Develop tools network tab shows request to `unpause` endpoint returned a 403 unauthorized.

Workaround:

Log-out from Web UI and Log In again

**Comment by xtremerui** [comment]
Hi @eedwards-sk , this should be solved by https://github.com/concourse/concourse/issues/2418, which would be included in next release.

Will close for now. If you still seeing the issue after next release, feel free to reopen this issue. Thx.

**Comment by eedwards-sk** [comment]
Cheers :D
