### ISSUE TITLE
BOSH drain script infinite loops if worker is not healthy

### ISSUE THREAD

**Issue by osis** [concourse/concourse#2469]
Noticing in environments that are under provisioned will max out on containers, get stuck, and will be unable to drain properly resulting in stuck deployments.

BOSH's --skip-drain option helps with this but seems to result with workers not reporting properly when they return as new VMs with the same name. This is fixed ~but~ by landing and retiring the workers, when then re-register right away. Then the stats return to normal.

The following can also be handy:

* Concourse version: 3.13.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Azure
* Browser (if applicable): N/A
* Did this used to work? Yes, is healthy.

**Comment by osis** [comment]
Would be cool if Concourse could figure this out on its own since no one is comfortable setting a value for this. Will close this out for now I suppose.

**Comment by svrc-pivotal** [comment]
The issue here isn't the default setting, it's that even if you specify a value, the drain script hangs indefinitely.    

Our favorite customer was setting 10 min, and so does the default bosh manifest.

https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/concourse.yml#L78
