### ISSUE TITLE
Allow an operator to pause periodic goroutines (radar, scheduling, etc) on the ATC

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2473]
[ATCCommand](https://github.com/concourse/atc/blob/master/atccmd/command.go) is really just a bag of [Ifrit](https://github.com/tedsuo/ifrit)-managed goroutines, some of which are run periodically (eg. GC, Scheduling, Radar) and some which are kept up (eg API & Web servers). 

As an operator (especially when there's a fire), it would be nice to be able to turn off internal components of the ATC, so that the system can be recovered. Often operators are left doing some manual surgery to the DB while rolling their workers and chanting incantations hoping their users' pipelines don't all come crashing down. It would be nice if an operator could disable things like scheduling  ( so that no new builds are created ), or radar ( so that all resource checking is paused )

This would work really well in conjunction with #2290

**Caveats / Wild Thoughts**
- How do we surface this to end users of the cluster?  (for now, maybe we don't) 
- Should there be kill-switches per-pipeline for scheduling, or [just one big lever ](https://media1.tenor.com/images/f24da444ddafffd37d64ed92401850f9/tenor.gif?itemid=5692196) ?
- Should this be on an internal debug endpoint similar to the pprof stuff?
- Everything is constructed in the `atccmd` package currently, so we'll need to figure out how to stop those `ifrit.Runner`s and respawn them while keeping the dependencies passed in originally (db connection, metrics and logging mostly). There could be one big periodic goroutine spawner which ensures each component which isn't enabled is up, and an endpoint to enable/disable them.
- Should each of these things just be separate microservices so they're [easier to digest](https://media.giphy.com/media/xgShOMMjjDb0Y/giphy.gif)?

**Comment by pivotal-jamie-klassen** [comment]
#4583 opens up some possibilities here
