### ISSUE TITLE
OIDC: HostedDomains

### ISSUE THREAD

**Issue by rubenv** [concourse/concourse#2474]
# Feature Request

## What challenge are you facing?

Configuring OIDC with Google Accounts currently allows everyone on the internet to log in using their Google account. We'd love to restrict this to just the people in our organization.

## A Modest Proposal

Dex has a `HostedDomains` config field that allows restricting this:

```go
	// Optional list of whitelisted domains when using Google
	// If this field is nonempty, only users from a listed domain will be allowed to log in
	HostedDomains []string `json:"hostedDomains"`
```

A config parameter that allows specifying a domain would allow us to limit access to just the users of our domain.

I'm guessing this is just a matter of passing the right parameters around, since Dex already has all the code in place to do the validation.

Would this be something that could be accepted into Concourse?

**Comment by rubenv** [comment]
Note: volunteering to fix this (as it would really solve our needs). Just would like to know if a PR will be accepted before wasting my time. Might also be that we're just doing things wrong.

**Comment by xtremerui** [comment]
@rubenv thx for volunteering on this. I think you can go ahead adding the flag here https://github.com/concourse/skymarshal/blob/master/skycmd/oidc_flags.go

**Comment by rubenv** [comment]
Will do, thanks for the hint!

**Comment by vito** [comment]
https://github.com/concourse/skymarshal/pull/4 has been merged - closing!
