### ISSUE TITLE
Misleading error when using new migration library to migrate the database

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#2475]
# Bug Report

When using the new migration library, if you attempt to run a migration through `atc` without specifying postgres login parameters, you get a misleading error saying:

`Must upgrade from db version 188 (concourse 3.6.0), current db version: 186`

This is caused by the login error falling through to another part of the code and then being swallowed. It would be better if we could see the actual error instead, to make the problem more clear.

* Concourse version: 4.0.1

**Comment by vito** [comment]
@ddadlani Does this only affect users that are attempting to skip v3.6.0? Or does this affect any user that tries to run Concourse with a misconfigured Postgres? If it's the latter, I should probably prioritize this highly.

**Comment by ddadlani** [comment]
@vito we saw it occurring when trying to run `atc migrate`, not when running Concourse. I would think that a misconfigured Postgres error would be caught before the migrations were run when running `atc run`, but I'll need to investigate further to be sure.

When you run `atc migrate` without the Postgres login info though, this error occurs regardless of the version you are attempting to migrate from, so it probably should be fixed sooner rather than later.

**Comment by vito** [comment]
Hmm, I can't figure out how to get this to happen on `master`. Gonna bump it out of v4.1.0 but leave it prioritized so y'all can take a look at it without it blocking the release.

**Comment by vito** [comment]
Couldn't get this to happen. Closing with `wontfix`!
