### ISSUE TITLE
when can we expect a new release so pr #2420 is getting fixed?

### ISSUE THREAD

**Issue by ramonskie** [concourse/concourse#2477]
when can we expect a new release so #2420 is getting fixed?

**Comment by eedwards-sk** [comment]
based on their [release page](https://github.com/concourse/concourse/releases) they seem to release concourse once or twice a month, on average, so I doubt it will be long :)

**Comment by jama-pivotal** [comment]
That's right, we are on an approximately once per month cadence, so it should be soon now
