### ISSUE TITLE
Can't mount container cgroup in worker

### ISSUE THREAD

**Issue by willejs** [concourse/concourse#2478]
# Bug Report

When running concourse 3.14.1 on docker 18.06.0-ce I get the following error when the git or git pull request resource runs:
```
runc run: exit status 1: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"cgroup\\\" to rootfs \\\"/worker-state/volumes/live/c5394811-e709-4bf9-4a29-f2fd3d216db8/volume/rootfs\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /var/lib/docker/btrfs/subvolumes/470b2ee541feb7441ac6b53d7443f16154c1e4308f64a735cbdeee484ab8e36a/sys/fs/cgroup/systemd/garden/7a7a2575-4341-4712-4d8d-fd8174503f85: permission denied\\\"\""
```

Initially the git resource works, but then fails. The docker image resource seems to work fine. The github pull request resource never works.

The `/sys/fs/cgroup` path exists

I have tried this with the official amazon linux ecs optimised ami, and ubuntu 18.04.

I think this is more garden related, as it will be dealing with the underlying runc lib. This is also a runc error... However, it seems to only happen in concourse. 

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: AWS ECS
* Did this used to work? Yes in 3.8.1

**Comment by vito** [comment]
Is your worker running in a privileged container?

**Comment by willejs** [comment]
Yes. The only thing i have changed is the version of the concourse container between deploys.

**Comment by larssb** [comment]
Have the same issue. See [Rootfs permission denied, mount error](https://github.com/concourse/concourse-docker/issues/27)

**Comment by willejs** [comment]
I think this got fixed in the latest release.

**Comment by larssb** [comment]
Hi @willejs,

I don't agree. I have this in v4.2.1 and above. Haven't tried v5. Are you sure you have it working in v4+?

Thank you

**Comment by larssb** [comment]
@willejs are you there :-)
