### ISSUE TITLE
Worker resources are orange

### ISSUE THREAD

**Issue by cunnie** [concourse/concourse#2481]
Our resource-checks are orange.

We believe the problem lies with file-descriptor exhaustion on the `atc` (#1201):
```
# tail atc/atc.stderr.log
2018/08/09 18:35:54 http: Accept error: accept tcp 0.0.0.0:8080: accept4: too many open files; retrying in 1s
2018/08/09 18:35:55 http: Accept error: accept tcp 0.0.0.0:8080: accept4: too many open files; retrying in 1s
2018/08/09 18:35:56 http: Accept error: accept tcp 0.0.0.0:8080: accept4: too many open files; retrying in 1s
2018/08/09 18:35:57 http: Accept error: accept tcp 0.0.0.0:8080: accept4: too many open files; retrying in 1s
2018/08/09 18:35:58 http: Accept error: accept tcp 0.0.0.0:8080: accept4: too many open files; retrying in 1s
# the log just goes on like this...
```

It appears the large number of file descriptors are from long-stale connections from our workstation (whose IP has shifted over the last 20 days (DHCP)).

When we run `lsof -p $ATC_PID`, we see a very large number (963) of open sockets on high ports to the workstation we use to view our pipelines and run `fly` commands from. 

```
# lsof -np 28419  | wc -l
1026
# lsof -np 28419 | grep '10\.64\.5' | wc -l
963
```

(There are several IP addresses starting with 10.64.5 (Pivotal Palo Alto); they are the same workstation after multiple DHCP leases and renewals.) Approximately **94%** of our open sockets originate from the same workstation, and some have been open for a very long time (up to 20 days).

We're not sure whether the fly command or the web UI is leaking sockets, but FWIW we use the web UI a lot more.

Some information about our deployment:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Chrome
* Did this used to work? haven't seen this problem on another environment but we typically use load balancers to access our web VM and this environment is not load balanced.

cc @rowanjacobs

**Comment by jama-pivotal** [comment]
Strange. Do you suspect it has to do with the IP shift from 20 days ago?

**Comment by cunnie** [comment]
@jama-pivotal Yes, I suspect it has quite a bit to do with the IP shift. I also suspect that the ATC doesn't tear down stale connections. Typical keepalives are a common mechanism to tear down stale connections. On Linux, unlike *BSD, TCP keepalives are opt-in (you can't it set it system-wide; each socket has to use the setsockopt(2) system call to enable it <https://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#setsockopt> ). There may be darker forces at work, too.

**Comment by cunnie** [comment]
@jama-pivotal FYI, @rowanjacobs and I are no longer troubled by this problem because our IP addresses are no longer volatile, so the problem hasn't cropped up, so you can close this issue if you want.
