### ISSUE TITLE
Frequent (dex?) `invalid_client` error

### ISSUE THREAD

**Issue by x6j8x** [concourse/concourse#2483]
Hi there!

After the switch to 4.0 we experience a lot of problem logging into Concourse using Github auth. 

In > 80% of all cases we end up with 

```
{"error":"invalid_client","error_description":"Invalid client credentials."}
```

after being re-redirected to `.../sky/callback?code=...` 

Our configuration at least seems to be ok - we've configured:

github_auth.client_id & github_auth.secret
main_team.auth.github.teams (on team in org:team notation)

We've configured `.../sky/issuer/callback` as redirect url in Github. 

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Safari

**Comment by cirocosta** [comment]
Hey @x6j8x , 

it seems to me that your issue might be related to https://github.com/concourse/concourse/issues/2425? 

Maybe you're running multiple ATCs without session affinity in AWS like reported in the #2425 issue?

thx!

**Comment by x6j8x** [comment]
@cirocosta Yeah, we're running 2 ATCs behind an ELB (v1). I'll look into #2425

**Comment by Typositoire** [comment]
I do run into this with an ELB (v1) and 3 ATC. Had to scale back to 1

**Comment by vito** [comment]
Folding this into https://github.com/concourse/concourse/issues/2425 (already in flight) as it's likely the same root cause. Thanks!
