### ISSUE TITLE
4.0.0 pq: insert or update on table "worker_resource_config_check_sessions" violates foreign key constraint "worker_resource_config_check__resource_config_check_sessio_fkey"

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/concourse#2485]
# Bug Report

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Docker (web / worker / db) Darwin (worker)
* Infrastructure/IaaS:
* Browser (if applicable): Chrome
* Did this used to work? Yes?

I just got this on a check container.

Fresh stack, fresh storage, fresh DB...

Manually triggered a job, and another job (which was not being manually triggered but just waiting) failed to check on an output resource (which wouldn't have existed yet anyway).

The resource turned orange and produced error:

```
pq: insert or update on table "worker_resource_config_check_sessions" violates foreign key constraint "worker_resource_config_check__resource_config_check_sessio_fkey"
```

Once the job triggered automatically (due to valid upstream resource), the orange resource returned to normal.

Edit: Got a recurrence of this on a fresh pipeline. Was on an output resource, S3.

**Comment by marco-m** [comment]
This seems to be a duplicate of #1598

**Comment by eedwards-sk** [comment]
@marco-m thanks for finding that issue! (the title isn't terribly helpful, but I probably could have found it if I had searched better)

closing this as duplicate

**Comment by marco-m** [comment]
@eedwards-sk I agree the title of the previous issue is a bit generic. And, wonder how I found both ? I just got the same error on 4.2.1, luckily it went away in a few minutes all by itself ;-)
