### ISSUE TITLE
Introduce Pipeline Status and Build Duration On a Subset of Jobs Using Tags

### ISSUE THREAD

**Issue by StevenArmstrong** [concourse/concourse#2489]
# Feature Request

## What challenge are you facing?

As an operator concourse is a fantastic tool for modelling pipelines to visually represent different stages for a continuous delivery process. 
However, in terms of reporting overall pipeline status of a subnet of jobs and cumulative timings of pipeline jobs it has a big disadvantage compared to other ci/cd solutions.
This makes tracking kpis such as health of an environment (a subset of jobs in a pipeline) that is often visualised by pipeline group level, or duration for a cumulative set of jobs to deliver new releases into an environment difficult to track. This is a major drawback compared to other solutions such as jenkins and gocd that provide these metrics out the box and can be a source of complaint when migrating to concourse. A use case is that the team is asked to continually improve the speed of deployment pipelines so tracking a cumulative set of jobs and their timings is a must.

## A Modest Proposal

A pipeline in concourse is a combination of jobs scheduled in a sequential or parallel order which are triggered by resources. 
Would it be possible to introduce a status that reports the success or failure of a specified set of jobs in a pipeline and their overall duration (timing)? 
This could be done via adding a named tag to a job and this would then display an overall status and duration in the pipeline view for the selected tagged jobs based on the tags.

So the tag could be introduced as a job level construct that would be flexible for operators on how they are applied based on their use case.

So as an example the following tag: pipeline would be applied as follows:

- name: trigger pipeline for netbox qa7
  **tag: pipeline**
  serial: true
  public: true
  build_logs_to_retain: 10

and display the key in the dashboard view:
 
![image](https://user-images.githubusercontent.com/5717694/44001701-87601c4a-9e2e-11e8-80c2-ae68bf5bbc75.png)

The status would display passed or failed. So 1 failed job would mean the cumulative status is red and failed otherwise if all are green it would be set to passed.
The duration timing would be based on the sum of how long all the jobs take that have the tag: pipeline applied. It would only need to display the last run as a start point, as historical data could be recorded by forwarding to a time series database or datastore to include historical trends.

Another thought were that a pipeline group is currently used to visually represent a cut down subset of the pipeline. The pipeline group be used to show a pipeline subset status/duration so it isn't applied everywhere as you may have different subsets of tags in a pipeline that shouldn't be displayed everywhere.

groups:
- name: qa7
  **tag: 
    - pipeline**
  jobs: 
    - trigger pipeline 
    - setup pre-requisites 
    - create network
    - launch instances

As shown the key is applied to the pipeline group qa7 only:

![image](https://user-images.githubusercontent.com/5717694/44001423-c51986ca-9e29-11e8-81b5-14aa0b72adc1.png)
 

This would also become beneficial for the dashboard view, as users could display subsets of jobs and pipeline status of them by searching for the tag: pipeline as some teams aren't interested in a whole pipeline. 

![image](https://user-images.githubusercontent.com/5717694/44001688-5dbe1630-9e2e-11e8-9194-88d15ca4552a.png)

A use case is the shift operations team could filter the dashboard to only show the production environment jobs and see if any releases break there.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Iaas
* Browser (if applicable): N/A
* Did this used to work? No

**Comment by jama-pivotal** [comment]
Interesting! I appreciate the thought you've put behind this. We've been thinking a lot more about how to model the health of pipelines and jobs; and i think this might be an interesting first approach

**Comment by jchesterpivotal** [comment]
A nitpick: I'd suggest tags be an array, so we can set many of them. This is very useful for all sorts of purposes.

I'd also consider whether to use the Kubernetes style of having labels (intended to group together multiple resources) and annotations (intended to be distinct to that particular resource).
