### ISSUE TITLE
Bosh can't stop processes of worker instance processes during update

### ISSUE THREAD

**Issue by gdenn** [concourse/concourse#2490]
Hi ,

# Bug Report
We tried to update Concourse from "3.13.1" to "4.0.0" with bosh-concourse-deployment and received the following error during the deployment:

```
Task 2763 | 08:04:16 | Updating instance db: db/3bcbad14-dc1a-42fd-aa79-0002edea17c7 (0) (canary)
Task 2763 | 08:04:16 | Updating instance web: web/bd194fd8-9d4d-4152-bb38-d51623de3b2c (0) (canary)
Task 2763 | 08:04:16 | Updating instance worker: worker/c447f497-b5ec-4a28-aefc-c509a9051479 (0) (canary)
Task 2763 | 08:06:37 | Updating instance web: web/bd194fd8-9d4d-4152-bb38-d51623de3b2c (0) (canary) (00:02:21)
Task 2763 | 08:07:10 | Updating instance db: db/3bcbad14-dc1a-42fd-aa79-0002edea17c7 (0) (canary) (00:02:54)
Task 2763 | 08:07:23 | Updating instance worker: worker/c447f497-b5ec-4a28-aefc-c509a9051479 (0) (canary) (00:03:07)
Task 2763 | 08:07:23 | Updating instance worker: worker/dc551cb0-6910-4816-85cb-1e01e597c6b3 (1) (00:10:04)
                     L Error: Action Failed get_task: Task ed1f5928-c2fe-40c5-7bc1-6f937a46f3e1 result: 1 of 1 drain scripts failed. Failed Jobs: worker.
Task 2763 | 08:17:27 | Error: Action Failed get_task: Task ed1f5928-c2fe-40c5-7bc1-6f937a46f3e1 result: 1 of 1 drain scripts failed. Failed Jobs: worker.
```

We encountered this problem before when we updated from 3.8.0 to 3.13.1 and it seems to be related to some processes in the worker instances which could not be terminated by monit.

As of now our workaround is to do a `bosh delete-deployment -d concourse && bosh deploy` during which we loose our build informations.

best,
D

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Chrome
* Did this used to work? No, the problem was also during the update from 3.8.0 to 3.13.1

**Comment by xtremerui** [comment]
closing stale issue.
