### ISSUE TITLE
Inspect Papertrail logs to see what logs we should silence or what filters we should apply

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2493]
Our Papertrail account filled up! We've got 500GB capacity per month, which seems like it should be plenty.

Can we go over the logs and see what the most common log lines are? Are there any logs that are printed way too much and should be removed? Are there any filters we should set up?

Tip: the `papertrail` CLI (https://github.com/papertrail/papertrail-cli) is pretty good for quick local inspection. You could probably take a sample of a day or so of logs and do some `jq` magic to see the count per log message or something.

The Papertrail credentials are in LastPass.

/cc @scottietremendous

**Comment by YoussB** [comment]
We found a big chunk of logs from TSA on prod : https://papertrailapp.com/systems/2094006952/events?focus=968283218954575912&selected=968283218950381622-968283218958770226

**Comment by YoussB** [comment]
these are 4 log lines for the same method. Removing 3 of them and keeping only one log line will decrease the atc log size by about 36%.
