### ISSUE TITLE
Unable to login when Concourse uses HTTPS with internal CA

### ISSUE THREAD

**Issue by jeroenjacobs79** [concourse/concourse#2498]
# Bug Report

Bug reports are pretty free-form; just replace this with whatever. You can also help us triage the issue by including steps to reproduce, expected results, and the actual result. Help us help you!

The following can also be handy:

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Kubernetes
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

I'm running Concourse 4 in Kubernetes, the web UI is exposed via an ingress rule and a TLS key/cert was generated and is being used.

Parameters passed to concourse:
```
          --add-local-user=myuser:mypass
          --main-team-local-user=myuser
```
Error in concourse logs:

`{"timestamp":"1534453741.615332842","source":"atc","message":"atc.sky.callback.failed-to-fetch-dex-token","log_level":2,"data":{"error":"Post https://concourse.internal.headincloud.be/sky/issuer/token: x509: certificate signed by unknown authority","session":"4.7"}}`

I'm using an internal CA, which is really common practice in enterprises. Not everyone exposes their CI environment to the Internet.

Please advice on how I can instruct Concourse to trust this certificate. 

This internal CA is trusted in my browser, so it's certainly not a client issue.

**Comment by jeroenjacobs1205** [comment]
Tried a workaround, by adding my internal ca to the trust store, and using that docker image instead:

```
FROM concourse/concourse:4.0.0
COPY root_ca.pem /usr/local/share/ca-certificates/root_ca.crt
RUN update-ca-certificates
```
Strangely enough, the error remains the same. It feels like Concourse is not even using the truststore of the Ubuntu-based docker image.

**Comment by habnux** [comment]
Hi @jeroenjacobs1205. I also had the same problem. Adding the certificates, as you mentioned, solved the problem in my case.

**Comment by eedwards-sk** [comment]
I'm not familiar with go, but I did a little digging and maybe this can help.

here's an article about loading CAs from the system in a go app: https://forfuncsake.github.io/post/2017/08/trust-extra-ca-cert-in-go-app/

and this section of the ATC seems related to certs, and does make a call to `x509.SystemCertPool()`: https://github.com/concourse/atc/blob/084a5efe2f5c5af12f7285fd73df2826e4112c8a/atccmd/command.go#L490
