### ISSUE TITLE
Metrics for tracking number of workers by state

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2499]
## What challenge are you facing?

I started seeing our per-worker container counts go up on Wings, and it took way too long to notice that it wasn't the number of containers that was increasing, it was the number of running workers that had gone down. A bunch of them were in `retiring` state, so they weren't being allocated any containers, resulting in the remaining workers being overloaded.

## A Modest Proposal

Having some way to notice workers in `retiring`, `landing`, `landed`, and `stalled` states (in addition to the happy state, `running`) would have made this way easier to notice.

Arguably we could have also noticed that the total container count hadn't spiked, which we can already do in our dashboards by summing up the existing containers metric (instead of grouping by worker). But being able to see workers stalling and un-stalling over time could also be a nice win long-term.

**Comment by hprotzek** [comment]
Hi @vito is there any hidden complexity what I don't see? Why not just emit a new metric with the state string in `HeartbeatWorker` and then map the state to an `int` in the PrometheusEmitter. (didn't look at the other emitters). I am happy to help :-)

**Comment by vito** [comment]
@hprotzek One complexity is that if a worker fails to heartbeat it'll transition to `stalled` state, which we'd also want metrics for (and that would inherently not come from `HeartbeatWorker`). I think this might just need to be its own periodic emitter.

**Comment by cirocosta** [comment]
Oops, 

I just noticed that in https://github.com/concourse/concourse/commit/e7ee26a3219c7cfb281beba08cde9612a38d8e46 we missed the fact that `prometheus` has its own "switch" to decide which metrics to emit.

To quickly reproduce that:

1. enable Prometheus locally

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 1b7dc7b03..eaa90a482 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -18,7 +18,7 @@ services:
     - .:/src
     command: web
     depends_on: [db]
-    ports: ["8080:8080"]
+    ports: ["8080:8080", "9391:9391"]
     environment:
     - CONCOURSE_POSTGRES_HOST=db
     - CONCOURSE_POSTGRES_USER=dev
@@ -28,6 +28,8 @@ services:
     - CONCOURSE_ADD_LOCAL_USER=test:test,guest:guest
     - CONCOURSE_MAIN_TEAM_LOCAL_USER=test
     - CONCOURSE_LOG_LEVEL=debug
+    - CONCOURSE_PROMETHEUS_BIND_IP=0.0.0.0
+    - CONCOURSE_PROMETHEUS_BIND_PORT=9391

   worker:
     build:
```

2. check the exposed metrics

```sh
curl --silent localhost:9391/metrics | awk '/HELP concourse/'
```

thx!
