### ISSUE TITLE
fly suddenly just shows error: forbidden for pipeline commands

### ISSUE THREAD

**Issue by phynias** [concourse/concourse#2501]
running latest version (concourse/fly). set this all up yesterday with concourse-up, everything was running fine. added all pipelines and they are working fine as well.

tried to modify a pipeline today and fly just shows me 
error: forbidden

i get this message for all commands that have to do with pipelines.

i can show workers. show jobs. show volumes.
status shows me as logged in.

but when i do a set-pipeline, get-pipeline, checklist or anything where i have to specify '-p',  i get the forbidden error.

**Comment by ymage** [comment]
What was the issue ?

**Comment by robin-rpr** [comment]
**@phynias:** Could you share your solution to the issue with us?
