### ISSUE TITLE
Web Representation - degraded readability after upgrade to 4.0.0

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#2502]
# Bug Report

Readability suffered greatly due to the reduced contrast for error'd jobs and a less legible font compared to before 4.0.0

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable): Firefox 61.0.1 & 62.0.2 x86_64 Fedora Linux
* Did this used to work? Yes, 3.14.x and before were beautfilul.

**Comment by vito** [comment]
Could you provide screenshots or more helpful information?

**Comment by drahnr** [comment]
https://screenshots.firefox.com/BtNWkqO88V0KfoyD/ci.spearow.io

Once you zoom out a tiny little bit, the font is getting really fuzzy and hard to read. The font used in 3.14.x was way more legible on all zoom levels.

The contrast for errored resources/jobs between the orange and the white-ish font colour is (combined with the font issue) is way too low.

**Comment by drahnr** [comment]
Obsolete
