### ISSUE TITLE
Migration to 4.0.0 with multiple github orgs in 3.14.x

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#2503]
# Bug Report

I used to have multiple github orgs using the same concourse instance.

Now I have configure `--github-client{id,secret}` with an app that has access to both organisations, yet I seem to be unable to modify one orgs pipelines. I can't pause theim, neither from web nor using `fly`.

How can I prune them?

Is that even meant to be supported? I understand that dex does only support one github token pair, but in this case there is only one and the actual access control should be mandated by github based on what access I granted.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: custom
* Browser (if applicable): Firefox 61.0.2 x86_64 Fedora Linux
* Did this used to work? 3.14.x

**Comment by vito** [comment]
Dumb question but have you tried logging out and back in? The token embeds which teams you're authorized for, so sometimes it's stale if team auth config was changed, and `fly` also just reuses the token if you were already logged in to the UI.

**Comment by drahnr** [comment]
Yes, I did. Not sure if the fact the pipeline is a public one makes any difference here?

**Comment by drahnr** [comment]
Resolved. The issue sat behind the screen.
