### ISSUE TITLE
"No pipelines set" page should include the Concourse version number

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2504]
Didn't realize this until @eamonryan mentioned this to me, but the "No Pipelines set" page doesn't mention the Concourse version on the page. It would probably be useful information to show to the user. 

cc @Lindsayauchin for design ideas

**Comment by Lindsayauchin** [comment]
We can add the version number below the messaging  for ' fly set pipeline' 
![screen shot 2018-08-28 at 10 43 30 am](https://user-images.githubusercontent.com/27746614/44730600-54974a80-aaaf-11e8-97cc-768fa366885e.png)

**Comment by Lindsayauchin** [comment]
Linking to #3633
