### ISSUE TITLE
Windows worker fails to handle a cache volume

### ISSUE THREAD

**Issue by wagdav** [concourse/concourse#2506]
Hi there!

# Bug Report

On Windows when the cache volume is enabled, a task can randomly fail with an "failed to create volume" error message. The failure happens after all commands in the task have been run, independently of their returned error code.

The corresponding part of the Worker logs read:

```
{"timestamp":"1534429366.541503429","source":"baggageclaim","message":"baggageclaim.repository.create-volume.failed-to-materialize-strategy","log_level":2,"data":{"error":"exec: \"cp\":      executable file not found in %PATH%","handle":"dc0f75b3-82e7-427b-7391-f9e6196f78dd","session":"1.4439"}}
{"timestamp":"1534429366.541503429","source":"baggageclaim","message":"baggageclaim.api.volume-server.create-volume-async.failed-to-create","log_level":2,"data":{"error":"exec: \"cp\":       executable file not found in %PATH%","handle":"dc0f75b3-82e7-427b-7391-f9e6196f78dd","privileged":false,"session":"2.1.498","strategy":{"type":"import","path":"C:                             \\Users\\concourse\\worker\\volumes\\live\\bc65606b-8353-4c0b-68d3-affe4649f9ed\\volume","follow_symlinks":false},"ttl":0}}
```

The error message suggests that the command `cp` is invoked, however this command does not exist on Windows.

We only observe this error on the Windows worker.  We're running the ATC with the `random` container placement strategy.

The following can also be handy:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): 
* Did this used to work?: probably not

**Comment by jama-pivotal** [comment]
@vito wondering if your commit above helps with this issue?

**Comment by vito** [comment]
Yep, this can be closed.

**Comment by topherbullock** [comment]
@vito Seems like with this change Windows workers will always fail to set up Cert Propagation : 
https://github.com/concourse/concourse/blob/4e03469fd060cd1c11196814566f526a98a3ec6f/atc/worker/volume_client.go#L250-L255

@cirocosta and I are wondering whether we should be using something portable like [`os.Readlink` ](https://golang.org/src/os/file_posix.go?s=459:501#L8) to resolve symlinks cross-OS?

wdyt?

**Comment by topherbullock** [comment]
Misclick on the reject button.. oops!
