### ISSUE TITLE
Error when a pipeline provides params to a task that doesn't configure them

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2510]
Restore https://github.com/concourse/atc/pull/297 to its original behavior. It was merged but then we turned it into a warning instead for backwards-compatibility.

**Comment by jtarchie** [comment]
Is this still on the path for v5.0.0?

**Comment by vito** [comment]
Yeah

**Comment by ljfranklin** [comment]
@vito we currently have a use case for relying on specifying params in the pipeline that are not defined in the `task.yml`. We're creating a re-usable set of tasks that will be used across many pipelines. We want the authors of those pipelines to be able to specify env vars with a given prefix, e.g. `BOSH_some_variable`, and the `task.sh` will consume all env vars starting with that prefix similar to `bosh --vars-env BOSH interpolate some-template.yml`. So we have a shared task authored by one team with the pipeline env vars and the config template being authored by other teams. Would y'all consider somehow supporting this use case going forward?

**Comment by anEXPer** [comment]
Yeah, is there some way we could have this optionally allowed? It adds a whole brittle layer to the maintenance of concourse tasks if every env var supported by a CLI being wrapped, for example, has to be specified in the task. `pass_all_params` or something?

This has been a very useful point of flexibility in developing shared concourse tasks, such as `cf-deployment-concourse-tasks`.

**Comment by vito** [comment]
@ljfranklin @anEXPer Sounds legit. Could you open an issue for that and we can spitball a design?

**Comment by vito** [comment]
Blocked on https://github.com/concourse/rfcs/issues/7
