### ISSUE TITLE
4.0.0 some resources silently fail to produce input artifacts

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/concourse#2525]
# Bug Report

I started seeing this with the github release resource, and opened https://github.com/concourse/github-release-resource/issues/75

However, I've now reproduced this with multiple resources. Most recently, a git resource.

Basically, a resource succeeds on a 'check', and shows a valid version, and the input directory gets created during the pipeline job, however it's empty!

Somehow concourse seems to think it's correctly downloading or downloaded or cached the resource, but whenever it runs there's nothing in the directory.

`fly check-resource` does not fix it, neither does pausing and unpausing the resource, or marking the versions as unavailable - triggering a build without valid versions available, and then enabling the versions again...

The only thing I've found to fix it is destroying and re-creating the pipeline so the resources are completely re-created.

This is happening on a local dev stack install, where sometimes I 'stop' the cluster (e.g. stop the darwin worker and all the docker containers, leaving all volumes intact) and then start it back up later. When I do this, the pipelines all come back, etc, but occasionally this strange resource bug happens.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Docker (web / db / linux worker) Darwin (worker)
* Infrastructure/IaaS:
* Browser (if applicable): Chrome
* Did this used to work?: Yes?

**Comment by eedwards-sk** [comment]
This is worse than I thought. Multiple resources are being staged, but empty.

Destroying and re-creating the pipeline does NOT fix it. This means I have to destroy and re-create my concourse stack to fix it. This is bad.

**Comment by eedwards-sk** [comment]
More details:

Here's the directory that got spawned by the job.

Notice how some of the input directories (`homebrew`, `homebrew-ci`) are empty when I `ls` them, even though homebrew says it grabbed the resources (see the screenshot after).

```
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker/volumes/live/77025b54-ed0f-4822-4d66-f0b5c21b6328/volume ○ [10:50:41]
→ ls -la
total 0
drwxr-xr-x  15 eedwards  staff  480 Aug 23 10:46 .
drwxr-xr-x   6 root      staff  192 Aug 23 10:46 ..
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 bash-util-repo -> /opt/concourse/local/worker/volumes/live/0baaa7d5-9c8a-4bac-4fd0-980054c71411/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 bottle -> /opt/concourse/local/worker/volumes/live/d22b12be-2275-4182-50ab-95a8a38b78e0/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 build-manifest -> /opt/concourse/local/worker/volumes/live/9b61aa61-0472-4638-77d1-ea7e68db6fe6/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 dist-bottle -> /opt/concourse/local/worker/volumes/live/bbe97aff-29e6-4485-6af5-bb20242f6b04/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 homebrew -> /opt/concourse/local/worker/volumes/live/94e78816-e0ca-41f0-51ca-a2f4cc36005c/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 homebrew-ci -> /opt/concourse/local/worker/volumes/live/98cab229-c7cc-4c81-433c-36a086597538/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 homebrew-core -> /opt/concourse/local/worker/volumes/live/cd7b6e1c-9ff3-4a89-5fd7-754bff006b4d/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 homebrew-install-cache -> /opt/concourse/local/worker/volumes/live/4359b7b6-06ec-4107-7064-5ed4b87fb7cb/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 snap-dev-repo -> /opt/concourse/local/worker/volumes/live/c2fb8204-8b27-45c5-5cc7-d4afe4d6e9b2/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 source -> /opt/concourse/local/worker/volumes/live/a2ce1a1f-d7b7-45b4-5b7f-91212b64cf2d/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 source-dist -> /opt/concourse/local/worker/volumes/live/ddee25d6-d169-4f49-7cca-c95b18cf63de/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 updated-snap-dev-repo -> /opt/concourse/local/worker/volumes/live/8ae92a19-2a9a-4bf6-7482-996ea4d55b58/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 23 10:46 version -> /opt/concourse/local/worker/volumes/live/2f705ddd-2d2b-400f-47a9-160fe12bc5fa/volume
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker/volumes/live/77025b54-ed0f-4822-4d66-f0b5c21b6328/volume ○ [10:50:42]
→ ls homebrew/
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker/volumes/live/77025b54-ed0f-4822-4d66-f0b5c21b6328/volume ○ [10:51:03]
→ ls homebrew-ci/
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker/volumes/live/77025b54-ed0f-4822-4d66-f0b5c21b6328/volume ○ [10:51:05]
→ ls homebrew-core/
Aliases              CODE_OF_CONDUCT.md   CONTRIBUTING.md      Formula              LICENSE.txt          README.md            cmd                  formula_renames.json tap_migrations.json
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker/volumes/live/77025b54-ed0f-4822-4d66-f0b5c21b6328/volume ○ [10:51:09]
→
```

<img width="1435" alt="screen shot 2018-08-23 at 10 52 20 am" src="https://user-images.githubusercontent.com/34585329/44536740-c2fc9700-a6c2-11e8-90e3-652825d233a6.png">

**Comment by eedwards-sk** [comment]
Tried stopping the darwin worker, pruning it after stalling, and destroying all of its container/volume data before starting it again, and the issue persisted.

Then tried stopping the linux worker container (it's docker), retired it, destroyed its container and volume, and re-created it... that finally got the resources to work again.

So it appears to be a problem with the linux worker, where it thinks it has containers with the resources in them, but either they're empty or it's not copying the contents from them during the get steps.

**Comment by eedwards-sk** [comment]
Hmm I can seem to repro this consistently by doing a docker stop on the worker then later doing a docker start and trying to use the worker again. I'm going to try enabling the option to delete the containers on startup, I think that might fix it.

**Comment by eedwards-sk** [comment]
Enabling delete containers on startup just causes all the resources to show as `unknown handle` and then they never properly check. Damn.

**Comment by eedwards-sk** [comment]
Issuing a 'retire-worker' and then allowing the worker to re-register itself automatically has allowed the containers to start checking again.

**Comment by eedwards-sk** [comment]
I'm now properly landing the workers before stopping the docker containers, yet when bringing them back up, they STILL silently fail... resource says it was checked okay but NOTHING is in the destination.

**Comment by eedwards-sk** [comment]
This might be related to how the linux docker image persists or does not persist worker state. Based on some old lines in https://github.com/EugenMayer/concourseci-server-boilerplate/blob/e5d6c5fd5590957aeb3909d52c047d2af4fa2fef/docker-compose.yml that was setting the hostname and worker state dir.

I'm going to do some investigating into how the state is stored and see if I can ensure it's being persisted.

**Comment by eedwards-sk** [comment]
Dockerfile https://github.com/concourse/concourse-docker/blob/master/Dockerfile seems to persist the state...

```
# volume for non-aufs/etc. mount for baggageclaim's driver
VOLUME /worker-state

# auto-wire work dir for 'worker' and 'quickstart'
ENV CONCOURSE_WORK_DIR /worker-state
ENV CONCOURSE_WORKER_WORK_DIR /worker-state
```

So the volume should be good after a restart. This really feels like a bug.

**Comment by eedwards-sk** [comment]
So wtf... I'm landing the workers before stopping. I'm persisting hostnames, worker names, and volumes.

After starting back up, I get unknown handles, and the contents of the worker work dir has changed drastically:

before stop/start

```
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker ○ [12:33:54]
→ find . -name "*homebrew*"
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-install
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-install/Homebrew/var/homebrew
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-install/Homebrew/Library/Taps/homebrew
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-install/Homebrew/Library/Taps/homebrew/homebrew-core
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-install/Homebrew/Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-install-cache
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-ci
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-core
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew
./volumes/live/36cf39f9-dfb6-4d21-588e-1db351de06ad/volume/homebrew-downloads
./volumes/live/86eca5fc-91c8-4632-5cc4-d3c781aa3948/volume/ci/homebrew-formulas
```

after stop/start

```
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker ○ [12:43:16]
→ find . -name "*homebrew*"
./volumes/live/6f50d1f2-1467-4598-4b84-9f47c45f96d9/volume/homebrew-archive-checksum
./volumes/live/6f50d1f2-1467-4598-4b84-9f47c45f96d9/volume/homebrew-core-revision
./volumes/live/6f50d1f2-1467-4598-4b84-9f47c45f96d9/volume/homebrew-cache-string
```

what gives? Looks like the darwin worker is cleaning up check containers or something but then concourse thinks they're still there?

**Comment by eedwards-sk** [comment]
This is REALLY fucking annoying. So the worker says 'unknown handle' for a while as per above, and then eventually the resources finally do show as successfully checked.

However, same issue as above... STILL... the task runs but there is NO DATA.

```
source /opt/concourse/local/worker/volumes/live/78bfeb9a-2ea4-4573-75b0-9efc1a01f18a/volume/homebrew-ci/concourse/task-scripts/lib.bash
source/ci/concourse/task-scripts/build-it: line 508: /opt/concourse/local/worker/volumes/live/78bfeb9a-2ea4-4573-75b0-9efc1a01f18a/volume/homebrew-ci/concourse/task-scripts/lib.bash: No such file or directory
```

<img width="1436" alt="screen shot 2018-08-26 at 12 54 21 pm" src="https://user-images.githubusercontent.com/34585329/44631264-3571af00-a92f-11e8-9bea-18380f071b7b.png">

<img width="1435" alt="screen shot 2018-08-26 at 12 54 34 pm" src="https://user-images.githubusercontent.com/34585329/44631266-3c002680-a92f-11e8-9551-9fe490d7f0bb.png">

The volume it's pointing to does exist:

```
→ ls /opt/concourse/local/worker/volumes/live/78bfeb9a-2ea4-4573-75b0-9efc1a01f18a/volume/
bash-util-repo         build-manifest         homebrew               homebrew-core          snap-dev-repo          source-dist            version
bottle                 dist-bottle            homebrew-ci            homebrew-install-cache source                 updated-snap-dev-repo
```
```
→ ls -la /opt/concourse/local/worker/volumes/live/78bfeb9a-2ea4-4573-75b0-9efc1a01f18a/volume/
total 0
drwxr-xr-x  15 eedwards  staff  480 Aug 26 12:53 .
drwxr-xr-x   6 root      staff  192 Aug 26 12:53 ..
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 bash-util-repo -> /opt/concourse/local/worker/volumes/live/3b7e1b09-65de-45be-42a8-7635c102a83c/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 bottle -> /opt/concourse/local/worker/volumes/live/6811d5ef-3485-4bab-68a9-bf3aec82f9ea/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 build-manifest -> /opt/concourse/local/worker/volumes/live/8014b689-0d13-440f-584c-e4dd40a3c11d/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 dist-bottle -> /opt/concourse/local/worker/volumes/live/0a852e0a-e906-486c-44c8-355ad1cf2d84/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 homebrew -> /opt/concourse/local/worker/volumes/live/5942661e-55de-41c0-6a33-e70421bcd3d9/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 homebrew-ci -> /opt/concourse/local/worker/volumes/live/6767ff08-1d66-47a7-6bc4-ddf0c9ac1e66/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 homebrew-core -> /opt/concourse/local/worker/volumes/live/78055f30-c4e7-48c0-450d-7b2bc4dbeb69/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 homebrew-install-cache -> /opt/concourse/local/worker/volumes/live/164beed1-4171-4232-5f3e-1d2e7a9557d8/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 snap-dev-repo -> /opt/concourse/local/worker/volumes/live/01d75d40-8bba-49e8-6089-11afbe186555/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 source -> /opt/concourse/local/worker/volumes/live/96ebe6fb-f6ac-4278-45a4-3f5e5723754e/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 source-dist -> /opt/concourse/local/worker/volumes/live/1882cbd9-c9e8-43a0-76de-5a2280b893c9/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 updated-snap-dev-repo -> /opt/concourse/local/worker/volumes/live/293e8c30-76e9-478a-619f-34cd9afdf43e/volume
lrwxr-xr-x   1 eedwards  staff   84 Aug 26 12:53 version -> /opt/concourse/local/worker/volumes/live/4124d6fb-56f7-4985-492c-fbe13ae90ff6/volume
```

but the contents of `homebrew-ci` is EMPTY:

```
→ cd /opt/concourse/local/worker/volumes/live/6767ff08-1d66-47a7-6bc4-ddf0c9ac1e66/volume
$ eedwards @ EEDWARDSLT-MAC in /opt/concourse/local/worker/volumes/live/6767ff08-1d66-47a7-6bc4-ddf0c9ac1e66/volume ○ [12:56:29]
→ ls -la
total 0
drwxr-xr-x  2 eedwards  staff   64 Aug 26 12:30 .
drwxr-xr-x  6 root      staff  192 Aug 26 12:53 ..
```

**Comment by eedwards-sk** [comment]
Where should the data be showing up after a check? If I retire the mac worker and try the above build again (which runs on a darwin worker), all the checks still appear to succeed, and it fails on 'no workers' as expected, however checking the contents of the linux worker I don't see any of the resources there either.

I would expect if concourse is saying it checked the resource successfully that it actually is stored somewhere?

```
→ docker exec -it local-concourse-worker sh
# ls
bin  boot  concourse-keys  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tmp  usr  var	worker-state
# find / -name "*homebrew*"
/worker-state/volumes/live/1116ec19-4b14-4016-4c7d-6daff9a4ac2b/volume/tmp/git-resource-repo-cache/ci/homebrew-formulas
/worker-state/volumes/live/358db3ac-63f1-4082-6f77-9ce2e25e428f/volume/ci/homebrew-formulas
/worker-state/overlays/cde12e65-f8e7-43fc-70a0-b75fb008af5b/tmp/git-resource-repo-cache/ci/homebrew-formulas
/worker-state/overlays/1116ec19-4b14-4016-4c7d-6daff9a4ac2b/tmp/git-resource-repo-cache/ci/homebrew-formulas
/worker-state/overlays/be9df7bf-e3b5-4532-623f-b2717def951a/tmp/git-resource-repo-cache/ci/homebrew-formulas
/worker-state/overlays/1cd0898a-7bc1-4648-5c87-98a28804fa05/ci/homebrew-formulas
/worker-state/overlays/358db3ac-63f1-4082-6f77-9ce2e25e428f/ci/homebrew-formulas
# exit
```

```
→ concourse fly workers
name                    containers  platform  tags  team  state    version
concourse-linux-worker  18          linux     none  none  running  2.1
```

**Comment by eedwards-sk** [comment]
At this point I don't know what else to do. Hopefully someone else runs into this too, or can advise on what I'm doing wrong.

Here's the (simplified) orchestration steps which seem to reproduce the issue:

startup:

```
1) docker run postgres db
2) docker run web
3) docker run linux worker
4) start darwin worker
```

run a build:

```
set pipeline
allow auto trigger on source or trigger build
```

shut down:

```
1) land darwin worker
2) stop darwin worker
3) land linux worker
4) docker stop linux worker
5) docker stop web
6) docker stop db
```

restart:

```
1) docker start db
2) docker start web
3) docker start linux worker
4) start darwin worker
```

run build:

```
new source commit or manually trigger build
```

**Comment by vito** [comment]
@eedwards-sk Yo, I understand that this is frustrating but please try to keep the language tame. :slightly_smiling_face: See our [Code of Conduct](https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md#our-standards). No one's happy to run into a bug but we're gonna have to work together to fix it, no?

Do you have a pipeline `.yml` we can use when trying to repro this? I just want to be sure we test this accurately since there's a chance it could have something to do with the artifacts being fetched.

FWIW, none of the volumes on the Darwin worker should have anything to do with `check` operations or containers - that'll all happen on the Linux workers, as there is no Darwin implementation of any of the resource types. The only volumes present on the Darwin worker should be volumes streamed to/from the worker as builds are running.

**Comment by eedwards-sk** [comment]
@vito Sorry Vito, long weekend of frustrating headbanging. Apologies.

**Comment by vito** [comment]
@eedwards-sk No worries!

**Comment by eedwards-sk** [comment]
Okay, attempted a basic repro with this pipeline (it's a severely stripped down subset of my pipeline... replace `your-mac-username` as appropriate).

I set the pipeline, triggered a build, then shut down the cluster as per above (land, stop, land, stop, stop, stop) and started it back up again.

Then proceeded to trigger another build.

The `homebrew` resource went orange with invalid handle and never recovered automatically. I then issued a `fly check-resource` but it still failed with invalid handle.

Unlike above, where for whatever reason the resource eventually started checking again, I cannot get past that to then test a repro of the input artifact issue.

Note how the pipeline is stuck in pending, even though the pipeline build status reports that it has a valid version.

<img width="739" alt="screen shot 2018-08-27 at 11 38 48 am" src="https://user-images.githubusercontent.com/34585329/44672387-e8084700-a9ed-11e8-839a-a0807bc6d176.png">
<img width="560" alt="screen shot 2018-08-27 at 11 38 55 am" src="https://user-images.githubusercontent.com/34585329/44672396-ec346480-a9ed-11e8-8847-b434442222bf.png">
<img width="506" alt="screen shot 2018-08-27 at 11 40 35 am" src="https://user-images.githubusercontent.com/34585329/44672441-0b32f680-a9ee-11e8-9482-043dae1817e9.png">


```
resources:

# homebrew resources
# ==================

- name: homebrew
  type: github-release
  check_every: 12h
  source:
    owner: Homebrew
    repository: brew

- name: homebrew-core
  type: git
  check_every: 12h
  source:
    uri: https://github.com/Homebrew/homebrew-core.git
    branch: master

# ==================================================

jobs:

# build jobs
# ============

- name: build-it
  plan:
  # get dependencies
  - aggregate:
    - get: homebrew
      params:
        include_source_tarball: true
    - get: homebrew-core
      params:
        depth: 1
  # build it!
  - task: build-it
    config:
      platform: darwin
      inputs:
      - name: homebrew
      - name: homebrew-core
      # using chown instead of the user param due to
      # https://github.com/concourse/concourse/issues/807
      # also this lets us pass the user as a task
      # variable rather than hard coding it
      PARAMS:
        HOMEBREW_USER_NAME: your-mac-username
        HOMEBREW_USER_GROUP: staff
      run:
        path: bash
        args:
        - -c
        - |
          : "${HOMEBREW_USER_NAME:?"must provide user name to run homebrew script as"}"
          : "${HOMEBREW_USER_GROUP:?"must provide user group to run homebrew script as"}"
          set -x
          set -u
          set +H
          chown -R "${HOMEBREW_USER_NAME}:${HOMEBREW_USER_GROUP}" ../volume || exit 64
          chown -R "${HOMEBREW_USER_NAME}:${HOMEBREW_USER_GROUP}" ./*/ || exit 64
          # sudo -H -E -u "${HOMEBREW_USER_NAME}" source/ci/concourse/task-scripts/build-it || exit 64
          ls -la 'homebrew/' || exit 64
          ls -la 'homebrew-core/' || exit 64
```

**Comment by eedwards-sk** [comment]
and here's the run commands for the docker containers (basic admin:admin pass):

db

```
docker run -d -e POSTGRES_DB=concourse -e POSTGRES_PASSWORD=concourse_pass -e POSTGRES_USER=concourse_user -e PGDATA=/database -p 54320:5432 --hostname local-concourse-db --name local-concourse-db --restart=no postgres
```

web

```
docker run -d -v /Users/eedwards/.ssh/concourse/local/web:/concourse-keys -e CONCOURSE_POSTGRES_HOST=concourse-db.service.local.consul -e CONCOURSE_POSTGRES_PORT=54320 -e CONCOURSE_POSTGRES_USER=concourse_user -e CONCOURSE_POSTGRES_PASSWORD=concourse_pass -e CONCOURSE_POSTGRES_DATABASE=concourse -e CONCOURSE_EXTERNAL_URL=http://concourse.service.local.consul:8080 -e CONCOURSE_ADD_LOCAL_USER=admin:$2a$10$P14vZUihHOYndiFE0PppO.qn/eZRBwVIxm9hSIijijZLWop8SQdha -e CONCOURSE_MAIN_TEAM_LOCAL_USER=admin -p 8080:8080 -p 2222:2222 --hostname local-concourse-web --name local-concourse-web --restart=no concourse/concourse:4.0.0 web --log-level=info
```

linux worker

```
docker run -d -v /Users/eedwards/.ssh/concourse/local/worker:/concourse-keys -e CONCOURSE_TSA_HOST=concourse-tsa.service.local.consul:2222 --hostname local-concourse-worker --privileged --name local-concourse-worker --restart=no concourse/concourse:4.0.0 worker --name=concourse-linux-worker --log-level=info --baggageclaim-log-level=info
```

and the plist for the darwin worker:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>local.concourse.worker.local</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/sudo</string>
        <string>/opt/concourse/local/bin/concourse</string>
        <string>worker</string>
        <string>--name=concourse-mac-worker</string>
        <string>--work-dir=/opt/concourse/local/worker</string>
        <string>--tsa-host=concourse-tsa.service.local.consul:2222</string>
        <string>--tsa-public-key=/Users/eedwards/.ssh/concourse/local/worker/tsa_host_key.pub</string>
        <string>--tsa-worker-private-key=/Users/eedwards/.ssh/concourse/local/worker/worker_key</string>
        <string>--log-level=info</string>
        <string>--baggageclaim-log-level=info</string>
        <string>--bind-port=7777</string>
        <string>--bind-debug-port=9099</string>
        <string>--baggageclaim-bind-port=7788</string>
        <string>--baggageclaim-bind-debug-port=8099</string>
    </array>
    <key>StandardOutPath</key>
    <string>/tmp/concourse.worker.local.stdout</string>
    <key>StandardErrorPath</key>
    <string>/tmp/concourse.worker.local.stderr</string>
    <key>RunAtLoad</key>
    <false/>
    <key>KeepAlive</key>
    <false/>
    <key>ThrottleInterval</key>
    <integer>30</integer>
</dict>
</plist>
```

**Comment by StevenArmstrong** [comment]
I have had this when you have a stalled worker and register a new one with
the same ip or hostname. I would advise pruning then retiring the worker
and then restarting it. This happens more frequently using docker
containers too with docker compose after an act or db restart.

**Comment by eedwards-sk** [comment]
@StevenArmstrong Thanks for the response. I'm already landing the worker before stopping it. The documentation on the correct way to orchestrate workers for outages or service is somewhat unclear, so my process may not be perfect.

Unfortunately for this issue, I don't consider retiring the worker to be a valid solution. Retiring implies that the worker is going away permanently, but my worker is coming back. In addition, my workers are not stalling.

My goal here is to put the workers, web, and db down and bring them back up with their existing data and resume on existing pipelines. Thus, landing workers before stopping them, keeping volumes, etc.

**Comment by StevenArmstrong** [comment]
Yeah I have never been able to put down a docker worker and had it resume
as it is registered with the atc and db with the same name it doesn't work
for some reason.
I have always had to stop the worker, prune then retire then restart the
worker container when I do a stop. This isn't the same scenario if you run
workers on vms as you can stop/start on demand and resume. I was just
giving a heads up on how to work round it as you only need to retire the
worker. If you want to work with the concourse team on the why that is cool
😊

**Comment by eedwards-sk** [comment]
@StevenArmstrong Thanks Steven. Not even sure it's a darwin issue since supposedly the linux worker is where the check resources are coming from. I'll keep my hopes up :)
