### ISSUE TITLE
login breaks if `--session-signing-key` is not provided

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2533]
# Bug Report

### Reproduction steps:
1. Edit `dev/atc` and remove the line
```
--session-signing-key $KEYSDIR/web/session_signing_key \
```
1. Start concourse with `dev/start`
1. Try to login, e.g. `fly -t local -c http://localhost:8080 login -u test -p test` or by navigating to
`localhost:8080` in a browser, clicking `login` in the top right, typing in username `test` and password `test` and clicking `login`.

### Expectation:
You are logged in. Or maybe the ATC barfs on startup asking for a session signing key.

### Reality:
```
logging in to team 'main'

error: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}
```
with fly or
```
{"error":"invalid_client","error_description":"Invalid client credentials."}
```
in the browser.

Logging in seems like it can never work if you don't provide a session signing key.

* Concourse version: 4.0.1
* Deployment type (BOSH/Docker/binary): binary (modified `dev/start`)
* Infrastructure/IaaS: local
* Browser (if applicable): Chrome, Safari, fly, etc
* Did this used to work? Not sure, doesn't seem to be tested

**Comment by pivotal-jamie-klassen** [comment]
@xtremerui and I ran into this while trying to debug the failing `integration_test.go` in ATC (e.g. https://ci.concourse-ci.org/teams/main/pipelines/main/jobs/atc/builds/2161). Doing some initial investigation yielded the following:
* logs from dex seem to consistently say `keys expired, rotating`. Not sure if this is related.
* adding some log lines, we noticed that there is a function called `loadOrGenerateSigningKey`, which suggests that the signing key should be an optional parameter. This function gets called twice when the ATC starts, because `RunCommand.Runner` calls `RunCommand.constructMembers` twice -- once for the `apiMembers` and once for the `serviceMembers`. Tracing these calls we notice that a fresh key gets generated both times -- in both cases, `skyserver.NewSkyServer` is called, being passed a shasum of the signing key for the client secret. While `dexserver.NewDexServer` also gets called with these two client secrets, it's hard not to wonder whether the two might go out of sync, since the skyserver seems to only store this client secret in memory whereas dex stores it in postgres.

**Comment by pivotal-jamie-klassen** [comment]
While working this story, we found ourselves considering the following edge case: A concourse deployment with multiple ATCs, none of which have been provided with a `--session-signing-key`. The current implementation would have each of these ATCs generating its own session signing key and storing it in memory. The problem here is that if I log into one ATC and then make a authorization-requiring request to a different one, it won't be able to tell if my token is valid because it won't have access to the signing key that generated it.

This suggests two possible avenues:
1. Make the `--session-signing-key` required. This way operators will be responsible for managing this secret and appropriately distributing it to all of their instances.
2. Store the session signing key in the database. Then whenever an ATC starts up it can first check to see if the cluster has a key, and if not it can generate it. This is probably a security concern.

@vito you had prioritized this issue thinking of our `concourse quickstart` users. We learned that the quickstart flow actually generates its own session signing key -- it does not rely on the "generate" part of `loadOrGenerateSigningKey` in skymarshal. So `quickstart` would be unaffected by choosing to make `session-signing-key` required. Given all this context, what do you think?

**Comment by vito** [comment]
@pivotal-jamie-klassen I don't think we should make it required. Having it generated by default is useful when you're developing, or just kicking the tires, or only need one ATC. (Your tokens will expire on restart, but who cares.)

I also don't think it's worth the effort (& potential risk) to put it in the database. We already document that with multiple ATCs you have to generate a single signing key and share it across all of them, and I think that's been fine, we just broke the dev/single-ATC flow a bit. Maybe this is another cause for the errors people have been seeing?

It sounds like the code is broken in that it ends up generating it twice - can we fix that and have it covered in integration tests, assuming this would have negatively impacted those running a single ATC with no signing key specified?
