### ISSUE TITLE
Runnning State on a Build page

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2535]
In response to the issue #2520 "The "errored current" colour and "started" colour are very similar"

## A Modest Proposal

Adding the running state of an animated background (similar to the stripped animation used in the Dashboard) in the background of the area where the job name lives to provide contrast to the amber errored status behind the build number.  

![screen shot 2018-08-27 at 1 59 02 pm](https://user-images.githubusercontent.com/27746614/44676515-83ef7e00-aa01-11e8-8b68-341eb6b0a462.png)

**Comment by jama-pivotal** [comment]
Closing in lieu of #2520 

@Lindsayauchin can you please post the contents of your issue under #2520 ?
