### ISSUE TITLE
Standard auditing columns - PIPELINES and other tables?

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2536]
# Feature Request

## What challenge are you facing?

If you wish to see when a pipeline was created or even when last updated, there's no way to do this.
For example, if we wanted to delete all pipelines created over 10 days ago and never run, we couldn't do this.

## A Modest Proposal

Possibly create the usual columns (created, last updated) for tables such as pipelines.

Could last-scheduled be null, perhaps, if never scheduled.  Could also apply to resource last-checked.

**Comment by jama-pivotal** [comment]
Assigning into the Operations backlog for now, thought I suspect it would be useful information to surface in the UI view
