### ISSUE TITLE
Enhancement for validate-pipeline command

### ISSUE THREAD

**Issue by sravankumar777** [concourse/concourse#2537]
Hi there!

# Feature Request
Enhancement for validate-pipeline for earlier identification of json unmarshal error. 

## What challenge are you facing?

Initially, had defined the attribute value as ```instances: 10``` in pipeline manifest. 
After executing with fly -t <target> validate-pipeline -c <manifest.yml>, This operation confirms as pipeline looks good.

> fly -t example validate-pipeline -c pipeline.yml
looks good

However, after ```set-pipeline``` with this pipeline.yml , pipeline is triggered.

Pipeline reports with json unmarshal error.

> error reading request from stdin: json: cannot unmarshal number into Go value of type string

After re-check with pipeline.yml file manually, it is found that attribute should defined like ```instances: "10"``` instead of ```instances: 10```.

## A Modest Proposal

> fly -t example validate-pipeline -c pipeline.yml should report these errors initially while validating the pipeline. 

The following can also be handy:

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Vsphere
* Browser (if applicable): Chrome
* Did this used to work? Yes.

Thanks.

**Comment by cirocosta** [comment]
Hey @sravankumar777 ,

<br />

Thanks for submitting the issue! 

Have you tried the same pipeline with the latest version of Concourse? 2.7.0 seems to be pretty old: https://github.com/concourse/concourse/releases/tag/v2.7.0.

Anyhow, could you please provide the pipeline configuration?

<br />

Thanks!
