### ISSUE TITLE
4.0.0 - auth login should not succeed if you don't have permissions

### ISSUE THREAD

**Issue by ralekseenkov** [concourse/concourse#2539]
# Bug Report

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Helm
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable): Chrome on Mac OS

Steps to reproduce:
1) Use OIDC provider

2) Create team `another-team` pointing to non-existent user `x`
```
fly -t main set-team -n another-team --oidc-user="x"
```

3) Log into this team using any existing user:
```
fly login -c {URL} -n another-team -t another-team
...
target saved
```

4) Create a pipeline
```
fly -t another-team set-pipeline -c pipeline.yml -p test
error: forbidden
```

Expected behavior:
- login through CLI into 'another-team' should fail
- UI dashboard should not display empty box 'another-team: no pipelines set'

Observed behavior:
- login succeeds, but set-pipeline fails
- UI shows team names to users which are not authorized to view them

**Comment by vito** [comment]
Dev suggestion: How about we peer into the token (either client-side or via /sky/userinfo) and just check if the team they requested is there?

**Comment by xtremerui** [comment]
The changes are made to fly that it will do client-side token parse when it is authenticated by either password grant or auth code. If the `teams` field in token payload doesn't include the requested team, it will fail the login by error 
```
error: user [USER_NAME] is not in team [TEAM_NAME]
```

which indicates either the auth is not configured properly or the token from web UI is outdated (should logout and log in again)
