### ISSUE TITLE
Error while running .sh file as a part of .yml 

### ISSUE THREAD

**Issue by 7thwik** [concourse/concourse#2540]
`resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/7thwik/Java-Concourse
    branch: master
jobs:
- name: run-java
  public: true
  plan:
  - get: git-repo
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: openjdk
          tag: 8-jdk
      inputs:
        - name: git-repo
      run:
        path: git-repo/java1.sh`

When i run this i'm getting the following error.

`Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:348: starting container process caused \"exec: \\\"git-repo/java1.sh\\\": permission denied\"\n","Handle":"","ProcessID":"","Binary":""}`

**Comment by danilopopeye** [comment]
@7thwik the `java1.sh` script has execution permission in the repository?

**Comment by 7thwik** [comment]
Yes it has execution permission.
I have done that using
Chmod +X java1.sh

**Comment by cirocosta** [comment]
Hey @7thwik ,

That doesn't look like an actual Concourse issue.

Did you end up getting it to run at some point with something else? Looking at the repository that you're feeding as an input, it feels to me that `java1.sh` doesn't really exist (looking at https://github.com/7thwik/Java-Concourse/tree/b0709d7e22045408d6e2134f34ceb659185f8e42), although a `java.sh` does, so maybe changing `java1.sh` to `java.sh` in your pipeline will make it work.

Could you give a try and let us know?

thx!

**Comment by jama-pivotal** [comment]
Closing due to stale-ness. @7thwik let us know if @cirocosta response was helpful. Also, please feel free to re-open

**Comment by timbarrass** [comment]
For anyone else visiting this in the future -- it might be worth changing your equivalent of:

run:
path: git-repo/java1.sh

to this instead:

run:
path: /bin/sh
args: ["git-repo/java1.sh"]

**Comment by jinxac** [comment]
thank you @timbarrass for the answer, this works for me

**Comment by kgkoutis** [comment]
That did it! Thanks @timbarrass!
