### ISSUE TITLE
Create a "Display Full Pipeline" tab for Pipeline Groups

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#2545]
# Feature Request
## What challenge are you facing?

When dealing with a large pipeline, there are scenarios where the pipeline is broken down into numerous groups. This makes it a bit annoying to display the full pipeline, since you need to individually click each tab. 

![screen shot 2018-08-31 at 11 08 46 am](https://user-images.githubusercontent.com/15380649/44921225-f026f600-ad0f-11e8-9b0e-816ce30dbff9.png)

![screen shot 2018-08-31 at 11 09 06 am](https://user-images.githubusercontent.com/15380649/44921238-fb7a2180-ad0f-11e8-87cd-e65bf2d95f7d.png)

## A Modest Proposal

Create a tab which will display the entire pipeline in one click

**Comment by Lindsayauchin** [comment]
How about adding in a keyboard shortcut? ` ctrl+A` to select and display all groups?
