### ISSUE TITLE
No longer highlighting new resource versions in 4.0.0

### ISSUE THREAD

**Issue by jenspinney** [concourse/concourse#2546]
# Bug Report

(If this change was intentional, consider this a feature request 😄)

Prior to 4.0.0, if a resource version changed from the last time a particular job was run, the resource header in the build output would show up as a lighter gray color, indicating that the last time the job was run, that resource had a different version. When a build fails, the first thing I'm in the habit of checking is which resource has changed, but that information doesn't seem to be highlighted anymore.

This is how it used to look:
![image](https://user-images.githubusercontent.com/3200507/44921980-53328000-ad44-11e8-861b-f842378d9147.png)
In that example, I could easily see that the `cloud_controller_ng` resource is new, and that would factor into my debugging. In 4.0.0 all the resource headers are the same color, and the process of determining what changed between builds is more tedious.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome on Mac
* Did this used to work? Yes, before 4.0.0

Thanks!
Jen

**Comment by topherbullock** [comment]
Hyia @jenspinney 

This is a known issue, and it will be fixed in Concourse's next release (`4.1.0`).
Going to close this off as there is an existing closed issue - see: https://github.com/concourse/concourse/issues/2423
