### ISSUE TITLE
Users are sometimes unexpectedly logged out of Concourse after an hour or two.

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#2547]
# Bug Report

We've had some complaints regarding our Wings environment, that users (and their CI monitors) are getting logged out of Concourse about an hour or two after logging in, even though the auth token is set to expire after 24 hours. It also occurred on our prod environment today, but it doesn't seem to happen all the time so it's a bit difficult to reproduce. At first we thought it was related to #2425 but the fix for that was deployed to Wings yesterday and the problem is still occurring.

This issue is to investigate why this is occurring and fix it.

* Concourse version: 4.0.0 and 4.1.0
* Deployment type (BOSH/Docker/binary): Wings
* Did this used to work? Yes

**Comment by vito** [comment]
This happened to me today. The logs even show that it was the same ATC that logged me in both times:

```
Sep 02 19:13:38 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh atc/rs2:  {"timestamp":"1535930018.809253454","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector \"github\", username=\"vito\", email=<snipped>, groups=<snipped>","session":"5"}}
Sep 02 20:45:41 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh atc/rs2:  {"timestamp":"1535935541.217003822","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector \"github\", username=\"vito\", email=<snipped>, groups=<snipped>","session":"5"}}
```

Though I guess that's not exactly conclusive because it doesn't show that the same ATC considered me "logged out", only that it let me log in again. I don't think any requests were rejected either so there are no logs of my requests being considered "logged out". Will have to try that next time.

I do see a ton of log lines like this which aren't very helpful:

```
{"timestamp":"1535934137.468713522","source":"atc","message":"atc.sky.userinfo.failed-to-parse-authorization-header","log_level":1,"data":{"session":"4.35529"}}
```

We should probably change the log level there or remove it, cause it seems to be happening constantly.

**Comment by ddadlani** [comment]
We tested this by logging in to Wings, copying the auth token and waiting until we were logged out again. Once we were logged out of the UI, we tried running `fly -t wings pipelines` with that token, which worked. This implies that the issue is limited to the web UI, no backend changes occurred to cause the logout.

**Comment by ddadlani** [comment]
This was the offending code: https://github.com/concourse/skymarshal/commit/69d2a77bb2617dc65c7c5e4bbe2c440649ec2a28#diff-79bb0d16b18540c1dfe62b7f3c2f4776R58

`claims["exp"]` returned an `int64`, not an `int`, so the cookie expiry on the first login was set to 1h instead of 1d.
