### ISSUE TITLE
Tasks extremely slow to start

### ISSUE THREAD

**Issue by AndrewMorsillo** [concourse/concourse#2548]
Running concourse 3.9.0 on GKE (cos nodes) via the helm chart. I am using the naive baggage claim driver because overlay/btrfs doesn't work with cos.

I'm seeing simple tasks take over 15 minutes to start. The web UI shows nothing happening, one task finishes then there are no spinners or output on the UI for a long time before the next task starts normally.

This doesn't always happen, but it is pretty crippling to have steps waiting 15 minutes or more between them. Not sure how to debug this, I'm very new to concourse.

**Comment by AndrewMorsillo** [comment]
I switched my nodes to ubuntu and my baggage claim driver to btrfs. Also backed my storage with ssd instead of standard class. I still see random delays in starting tasks, up to a few minutes, but not as bad as before.

**Comment by jama-pivotal** [comment]
Sorry for the late response 🙏 . Glad you were able to get things towards a bit more reliable state. I'd also suggest trying some of the newer versions of Concourse. I know we did some improvements with the fs drivers starting from 3.10 and on. If possible, maybe give  4.2.1 a try!

Closing for now, but feel free to re-open if you've got some more feeback

**Comment by AndrewMorsillo** [comment]
I've upgraded to 4.1.0 and it is somewhat better, but there are still somewhat random delays just nowhere near as long as before.
