### ISSUE TITLE
--postgres-data-source is not respected in 4.1

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#2549]
# Bug Report

* Concourse version: 4.1
* Deployment type (BOSH/Docker/binary): Helm chart on Kubernetes
* Infrastructure/IaaS: AWS
* Did this used to work? Yes

In Concourse 4.0, I used to specify the `CONCOURSE_POSTGRES_DATA_SOURCE` environment variable (see the [Helm chart](https://github.com/helm/charts/tree/master/stable/concourse)), which worked great. When I have the exact same config with Concourse 4.1 (e.g. `CONCOURSE_POSTGRES_DATA_SOURCE=postgres://concourse:concourse@my-concourse/concourse?sslmode=disable`), then the ATC cannot connect to my database and I receive the following log:

`failed to perform migrations: creating migration table: dial tcp 127.0.0.1:5432: connect: connection refused`

I've also tried setting the `--postgres-data-source` flag instead of the environment variable, and cannot get it to work. By switching to the (admittedly non-deprecated) `--postgres-host`, `--postgres-user`, `--postgres-password`, and `--postgres-database` (or their env vars), my connection succeeds.

`--postgres-data-source` and Concourse 4.0: works
individual `--postgres-*` flags and Concourse 4.0: works
`--postgres-data-source` and Concourse 4.1: does not work
individual `--postgres-*` flags and Concourse 4.1: works

It looks like the `--postgres-data-source` flag is just no longer getting passed through, so Concourse tries instead to use default values.

**Comment by vito** [comment]
I think it's time to just remove the flag as it's been deprecated since v2.7.2 (!).

**Comment by headcr4sh** [comment]
Can't we just update the release notes for 4.1.0? The missing configuration flag *is* a breaking change, as far as I can tell? Took me about an hour to figure out what went wrong with my setup after upgrading from 4.0.0 to 4.1.0....

**Comment by vito** [comment]
@headcr4sh Sure, I'll add something to the release notes.
