### ISSUE TITLE
Logging in after leaving a browser open for a long period causes a 400

### ISSUE THREAD

**Issue by enugentdt** [concourse/concourse#2550]
# Bug Report

If you are left on the login window (sample url: http://10.101.101.41:8080/sky/issuer/auth/local?req=xlacv7fccmk3fx5z5sjlp7bwp) for a long period of time, and log into Concourse, it causes a 400 error from Sky.

I'm going to guess this is because the `req` parameter has a ttl, and when it expires the application doesn't know how to handle it?

Here's the URL that throws the 400:

`http://10.101.101.41:8080/sky/callback?code=depk3aleqik64zkzqas7rxh52&state=eyJyZWRpcmVjdF91cmkiOiIvdGVhbXMvbWFpbi9waXBlbGluZXMvaXNvc2NyaWJlLWZyb250ZW5kLXNlcnZlciIsImVudHJvcHkiOiJhZTk4NjYwNWZjZGM1YTIyODdiYmQ1OTBhZDViOTQwY2ZjNjE0ZGFhYjgyMzFiY2NjYzY0MDA5MTlmNTRlMGIxIn0%3D`

* Concourse version: >=4.0.0
* Deployment type (BOSH/Docker/binary): Docker & binary tested
* Infrastructure/IaaS: Both GCP & hosted locally
* Browser (if applicable): Google Chrome
* Did this used to work? Pre-4.0.0, yes

I couldn't find any error logs, but I'll look through to see if anything jumps out at me.

**Comment by cirocosta** [comment]
Hey @ddadlani ,

I suppose this issue just got fixed by https://github.com/concourse/concourse/issues/2547#issuecomment-418893701. Is that right?

thx!

**Comment by ddadlani** [comment]
@cirocosta I'm not sure the two issues are related. #2547 would occur after the user was logged in, not while on the login page. It had to do with the expiry of the auth cookie. This one may require more investigation.

**Comment by pivotal-jwinters** [comment]
Its probably because of this line:
https://github.com/concourse/concourse/blob/master/skymarshal/skyserver/skyserver.go#L136

I can't see any real reason why it needs to be this short so I'm going to bump it to 1hr.
