### ISSUE TITLE
how to tag the docker image with release tag name dynamically

### ISSUE THREAD

**Issue by sanjay2916** [concourse/concourse#2551]
Hi Team,

I am running the below task script to get the latest release tag name dynamically, but not able to store output in s3/git using semver resource

eg:

- name: version
   type: semver
    source:
      driver: git
      #initial_version: 0.0.0
      uri: https
      branch: master
      file: version
      

    - task: update-git-tag
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine/git
          inputs:
          - name: nginx-deployment
          outputs:
          - name: tags
          run:
            dir: nginx-deployment
            path: sh
            args:
            - -excu
            - |
              git clone https://example.git
              cd bv-demo
              mkdir tags
              git describe --tags $(git rev-list --tags --max-count=1) > tags/tag.txt
              echo $(cat tags/tag.txt)>tags/tag.txt

   I need to pass above output value in above semver resource

-----------------------------------------------
- get: version
      - put: version
        params:
          file: version/version
          tag: tags/tag.txt ###not able to pass the output value here
----------------------------------------------

Thanks,
Sanjay

**Comment by vito** [comment]
Please use the [forums](https://discuss.concourse-ci.org) for questions like this - this is neither a bug report nor an enhancement. :)
