### ISSUE TITLE
Remove reliance on Garden Properties for re-attaching to a Task/Resource processes

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2554]
We have logic in exec/task_step.go to set the process ID in Garden for a task container to the running task script (https://github.com/concourse/atc/blob/aa86856bb66bd82e1aefa268266f367398c53ef2/exec/task_step.go#L25), but we also check for a property set on the container in Garden for the pid.

As [this comment](https://github.com/concourse/atc/blob/master/exec/task_step.go#L214-L215) states; this is "for backwards compatibility with containers that had their task process name set as property". Those containers are going to be [very, very old](https://github.com/concourse/atc/commit/12080578c96fd65b663a2e05a0221b679857997b), so its probably safe to just rely on this behaviour. 

Resource containers could be given the same treatment, but it [looks as if we haven't done the work for those yet](https://github.com/concourse/atc/blob/ca5bba4f10a249e5b8a22c5ffdc9a7e94cb67244/resource/run_script.go#L53-L104). We could add a process id constant to resource/run_script.go, follow the same flow as exists for task, and decide when to remove this later... OR just rip the bandaid off and deal with it.

**Comment by pivotal-saman-alvi** [comment]
- Removed the backward compatibility from the `task_step.go` file, since it is a very old change in the way we tag the garden container in order to be able to get it again if atc fails and comes back.
- Removed an extra test from the `task_step_test.go` that tested the backward compatibility code.
- The resource run script still needs checking to make sure it is safe to make the same change.

**Comment by topherbullock** [comment]
Seems legit! Looks like we don't set the ID if the script is non recoverable ( https://github.com/concourse/atc/blob/master/resource/run_script.go#L90-L96 ), which means check containers are okay, because we don't run checks as recoverable :+1:
