### ISSUE TITLE
`/api/v1/resources` and `/api/v1/jobs` return null instead of empty list

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2555]
# Bug Report

When accessing these endpoints when unauthenticated or with no pipelines, the response body is just `null`. This makes life perhaps needlessly harder for the Elm code.

The following can also be handy:

* Concourse version: 4.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: local
* Did this used to work? no, these endpoints were recently added for the dashboard

**Comment by vito** [comment]
done by #2789!
