### ISSUE TITLE
Cached auth provider config overrides actual config

### ISSUE THREAD

**Issue by edtan** [concourse/concourse#2556]
# Bug Report

I'm trying to set up an OAuth2 provider and I'm able to set the configuration (e.g. `--oauth-*` params) properly the first time, and can see the new OAuth2 login option on the login page.  However, if I change any of the OAuth2 config parameters, or remove the OAuth2 parameters completely, the original OAuth2 configuration is used/displayed on the login page.  It seems like the original configuration is cached and used.

* Concourse version: 4.1.0
* Deployment type (BOSH/Docker/binary):  Docker
* Infrastructure/IaaS:  Local dev machine
* Browser (if applicable):  Chrome
* Did this used to work?  don't know

**Comment by edtan** [comment]
It looks like Dex's login page looks for `Connectors` which are populated by [`s.storage.ListConnectors()`](https://github.com/concourse/dex/blob/master/server/handlers.go#L170).  `s.storage` is built in `NewDexServerConfig()` as [`store`](https://github.com/concourse/skymarshal/blob/master/dexserver/dexserver.go#L74) which stores all the connectors in postgres.  However, `NewDexServerConfig()` only contains logic to [add new connectors](https://github.com/concourse/skymarshal/blob/master/dexserver/dexserver.go#L117-L134), and seems to be missing logic to update/delete the connectors in postgres.

As a workaround, I've just manually removed the outdated row from `connector`.

**Comment by edtan** [comment]
The same issue seems to happen for local users - the workaround for those is to remove the outdated row from the `password` table.

**Comment by vito** [comment]
Should be fixed with https://github.com/concourse/skymarshal/pull/6 - thanks!
