### ISSUE TITLE
x509: certificate signed by unknown authority (even though it is)

### ISSUE THREAD

**Issue by professor** [concourse/concourse#2557]
# Bug Report

From Chrome, we can see that we have a valid, signed certificate. However, when we use fly login we see the error:

```
fly login -t NAME
logging in to team 'main'

could not reach the Concourse server called NAME:

    Get https://pks-releng.ci.cf-app.com/api/v1/info: x509: certificate signed by unknown authority

is the targeted Concourse running? better go catch it lol
```

![screen shot 2018-09-04 at 3 40 13 pm](https://user-images.githubusercontent.com/14758/45061358-0b1fa000-b059-11e8-9127-8b2a7e23af5b.png)

The work around is to use `fly login -k -t NAME`

*  version: 3.14.1 
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: 
* Browser (if applicable): Chrome

**Comment by vito** [comment]
Make sure you're configuring the chained certificate for the ATC (so main cert + any intermediate certs appended after it). Go applications tend to be pickier than browsers for some reason.

**Comment by cirocosta** [comment]
Hey,

Looking at the result from `ssllabs`:

<img width="935" alt="screen shot 2018-09-05 at 10 02 23 am" src="https://user-images.githubusercontent.com/3574444/45098422-f1cb3200-b0f2-11e8-84f8-9694316646b0.png">

**Comment by professor** [comment]
Thank you so much for your feedback.
