### ISSUE TITLE
Feature Request: on_recovery / on_new_failure task/job action

### ISSUE THREAD

**Issue by artamonovkirill** [concourse/concourse#2564]
# Feature Request

## What challenge are you facing?
We are using `on_failure` and `on_success` job/task properties to notify our team via Slack about our builds' statuses.
* There's quite some noise in our slack notifications at the moment if the build is failing and there are consecutive attempts to fix it.
* We practically never use 'on_success', as it will produce even more noise with frequent commits per day.

## A Modest Proposal
Two new options:
* on_recovery - performs an action (e.g., slack notification) when a build is successful and previous finished one was not successful => 'your recent action broke the build'
* on_new_failure - performs an action (e.g., slack notification) when a build is not successful and previous finished one was successful => 'your recent action fixed your build'

**Comment by vito** [comment]
I think the use case for this definitely makes sense but I don't like adding more hooks and pipeline features just for notifications. Notification support via resources is pretty awful right now; it's extremely verbose and just doesn't cleanly express common use-cases like this without tacking on more complicated pipeline features.

IMO we should think about this as part of https://github.com/concourse/rfcs/issues/10 which doesn't have a proper proposal yet, but collecting these use cases is the most important first step. If you agree feel free to leave a comment there with your use case and close this issue out. :slightly_smiling_face:

**Comment by artamonovkirill** [comment]
@vito , added a comment in concourse/rfcs#10
