### ISSUE TITLE
Github resources with long commit messages are not displayed correctly in UI

### ISSUE THREAD

**Issue by balesh2** [concourse/concourse#2566]
# Bug Report

When github resources are fetched at the start of a job and the most recent commit has a long message, the timestamped logs get squashed to be one character wide.
See example under the "geode" step [here](https://concourse.apachegeode-ci.info/teams/main/pipelines/develop/jobs/Build/builds/444)

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable): Firefox 61.0.2
* Did this used to work? Unknown

**Comment by jama-pivotal** [comment]
@balesh2 if possible, could you attach a screenshot to how its showing on your Concourse? I can't login to your instance so I can't check for myself. Make sure to scrub out any sensitive information! Thanks :)
