### ISSUE TITLE
Bitbucket OAuth doesn't work

### ISSUE THREAD

**Issue by vanjan** [concourse/concourse#2567]
Hello, 

I'm using Concourse 4.1 binary on macOS.

I'm trying to configure Concourse to use Bitbucket oauth:

```
./concourse web \
  --oauth-display-name="Bitbucket" \
  --oauth-client-id="<redacted>" \
  --oauth-client-secret="<redacted>" \
  --oauth-auth-url="https://bitbucket.org/site/oauth2/authorize" \
  --oauth-token-url="https://bitbucket.org/site/oauth2/access_token" \
  --oauth-scope "account" \
  --main-team-oauth-user="<my bitbucket username>" \
  --tsa-host-key tsa_host_key \
  --tsa-authorized-keys authorized_worker_keys \
  --session-signing-key session_signing_key
```

I've set up an oauth consumer in Bitbucket like so:
- callback url: http://127.0.0.1:8080/sky/issuer/callback
- permissions:
  - account: read
  - team membership: read
  - repositories: read

When I try to authenticate in Concourse I get "Internal Server Error. Failed to return user's identity." in the UI and the following in the logs:

```
{"timestamp":"1536337334.296978474","source":"atc","message":"atc.dex.event","log_level":2,"data":{"fields":{},"message":"Failed to authenticate: OAuth Connector: failed to execute request to userinfo: Get : unsupported protocol scheme \"\"","session":"5"}}
```

Note that Bitbucket doesn't provide the optional userinfo endpoint ([docs](https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication)).

**Comment by JohannesRudolph** [comment]
As far as I'm aware the bitbucket integration that also correctly checks authorization (i.e. via access to a specific repo/team-membership) was dropped in 4.0. While you may be able to set up bitbucket auth via a generic oauth consumer, that will only handle authentication and not fine-grained authorization for you.

See also: https://stackoverflow.com/questions/45605786/how-to-integrate-bitbucket-cloud-with-concourse-ci/51679762#51679762

**Comment by edtan** [comment]
It looks like the generic OAuth provider in Concourse currently requires a userinfo URL to be specified ([link](https://github.com/concourse/dex/blob/master/connector/oauth/oauth.go#L150-L153)).  If this is required, maybe we should add a `(Required)` to the [description](https://github.com/concourse/skymarshal/blob/master/skycmd/oauth_flags.go#L26)?

Anyways, I'm thinking about writing a Bitbucket connector so hopefully we can have Bitbucket support.

**Comment by edtan** [comment]
I've got a basic Bitbucket (Cloud) Dex connector working on [my Dex branch](https://github.com/edtan/dex/tree/add-bitbucket-support) and [Skymarshal branch](https://github.com/edtan/skymarshal/tree/add-bitbucket-support).  I'm going to spend a few more days playing around with it before submitting a pull request.

**Comment by shuraa** [comment]
Is there any news? Which concourse version might have the issue fixed?

**Comment by jama-pivotal** [comment]
@shuraa as you can see above @edtan made the PRs and we merged it in a few weeks ago. We're in the process of re-architecting our pipelines based on the changes towards one big repo. The fix should be out in our next release, which should hopefully be soon

**Comment by jama-pivotal** [comment]
Closing because of @edtan contribution to bitbucket support 🙏
