### ISSUE TITLE
GitLab authentication sends incorrect OAuth client ID

### ISSUE THREAD

**Issue by borntyping** [concourse/concourse#2571]
I've set the `CONCOURSE_GITLAB_CLIENT_ID` value as an environment variable.

When I click the GitLab login button in the Web UI it redirects me to my GitLab instance which returns an error page (_"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."_).

The `client_id` in the URL does not match the value set by the `CONCOURSE_GITLAB_CLIENT_ID` environment variable. If I modify the URL to use the same value as the one I've configured in GitLab and am using for `CONCOURSE_GITLAB_CLIENT_ID`, GitLab's authentication flow continues correctly.

I am not sure where the `client_id` that results in an error is coming from. The same client ID appears even on a fresh installation of Concourse.

```
https://gitlab.example.invalid/oauth/authorize?client_id=91d5b5ea68b13eacdb58e85d025b31eca943d7f222725b12e0ed7151b7e41296&redirect_uri=http%3A%2F%2Fconcourse.local%2Fsky%2Fissuer%2Fcallback&response_type=code&scope=read_user+api&state=hzrxzs33ehwvyd4cmavwumjq7
```

With the following config:
```
CONCOURSE_EXTERNAL_URL: 'http://concourse.local'
CONCOURSE_GITLAB_HOST=gitlab.example.invalid
CONCOURSE_GITLAB_CLIENT_ID=be3da258e58990ab4dec6afdc36441423a616248d55cc9bf5fad9fef1ebfd045
```

* Concourse version: 4.1.0 
* Deployment type: Docker
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable): Firefox
* Did this used to work? Unknown

**Comment by edtan** [comment]
4.1.0 had a bug where the initial auth configuration was cached and always used (#2556).  Is it possible that you had initially set a client ID, and then changed it later?  Not sure if it's the same issue though, because you mentioned it happening on a fresh install.
