### ISSUE TITLE
The Dashboard high-density view should indicate teams I am a member of vs exposed to

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2572]
Corresponding changes to the HD view from issue #2427

The 'member' and 'exposed' labels should appear below the team name inthe HD Dashboard view. 

![screen shot 2018-09-10 at 12 17 53 pm](https://user-images.githubusercontent.com/27746614/45310176-95ea1a00-b4f3-11e8-8464-ee2fa2e419ae.png)

![screen shot 2018-09-10 at 12 17 41 pm](https://user-images.githubusercontent.com/27746614/45310180-9b476480-b4f3-11e8-9cc2-cbca90a8271a.png)

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin right now prod uses the label "PUBLIC" for groups of pipelines that you can see even though you are not on the relevant team. However, I think that "EXPOSED" is better, and this change is on the way
