### ISSUE TITLE
Utilize `gdn` Guardian binary rather than importing their code directly

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2574]
ref. #2534 

# Feature Request

## What challenge are you facing?

The Garden team now creates standalone `gdn` binaries which embed everything they need, available at [`garden-runc-release`](https://github.com/cloudfoundry/garden-runc-release).

Right now we directly import their `guardiancmd` package and handle the building and embedding of all of its dependencies (`iptables`, `runc`, ...) ourselves, which is a lot of work as well as duplicate effort (since they're doing that already for `gdn`, the source of truth). It also means it's difficult to get up and running on a local dev machine because you have to figure out all these dependencies yourself.

## A Modest Proposal

Rather than directly importing, how about we use their `gdn` binary? As a developer I can just install it somewhere on my `$PATH`. This shouldn't take much upkeep.

Note that by doing this all the `--garden-X` flags will no longer be available. I propose that instead we support a single `--garden-config` flag, which we can pass along to the `gdn` binary (since it supports loading config from `.ini` files now). One advantage of this is that `concourse worker --help` would shrink substantially, and it would be a bit easier to tell that by configuring Garden you're "popping open the hood" a bit. (Side note: this may make setting Garden config a little more difficult in some situations like Docker, since folks have been taking advantage of the `CONCOURSE_GARDEN_X` env vars.)

This will break everyone using the existing flags and env vars, so we should call this out very loudly in the release notes and give clear instructions on how to transition. We could also collect feedback to determine whether there should be higher-level configs for things that folks are currently setting directly on Garden.

Maybe as a first pass we can assess which flags people are currently setting, and still support them with a deprecation warning? From a quick glance I suspect there are folks specifying the following:

```
--garden-max-containers
--garden-dns-server
--garden-deny-network
--garden-allow-host-access
--garden-additional-dns-server
```

**Comment by vito** [comment]
We'll need to tweak the self-contained `gdn` binary so that it doesn't try to initialize the `grootfs` store on startup. This requires `xfs` and we won't even be making use of `grootfs`, so it's wasted effort. It currently does that unconditionally: https://github.com/cloudfoundry/guardian/blob/526a20c6c190f5b551b9a9a1efacc110fc884ed7/guardiancmd/command.go#L326-L352

**Comment by vito** [comment]
* [ ] PR to `gdn` to skip grootfs initialization
* [ ] Add support for common `--garden-X` flags with deprecation warning

**Comment by vito** [comment]
I decided to forego support for `--garden-*` flags in favor of supporting all `CONCOURSE_GARDEN_*` env vars (*without* being deprecated). I figure most people are setting these via env in their Docker/K8s deployments, and supporting individual flags is a bit of a maintenance burden. People using the flags can either switch to a config file (as they're probably not using Docker/K8s where doing so is painful) or switch to the env vars.

**Comment by vito** [comment]
This is "done" but I'm just waiting on a new release of Garden-runC so we have a binary that doesn't force initialization of the `grootfs` store (which Concourse doesn't use). We need v1.16.6+.

As a note for acceptance, once the new `gdn` is out we should start passing `--no-image-plugin` and remove all the loopback setup/cleanup code from `docker-compose-testflight` (and any other CI tasks that do it).

**Comment by marco-m** [comment]
FYI Garden-runC 1.16.7 is out (https://github.com/cloudfoundry/garden-runc-release/releases)
