### ISSUE TITLE
Independently version all "core" resource types

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2576]
ref. #2534

# Feature Request

## What challenge are you facing?

Today a "core resource type" just means "resource types that are baked in to our BOSH release". They're not versioned on their own, and we just push to `latest` and then bump a blob in the release to embed the resource type's rootfs. This is all fine and dandy but if we want to have the *binary* become the source of truth for the BOSH release (#2575), we'll need to figure this out, because right now the binary is built by grabbing those blobs from the release.

(Note: we may also want to shrink the set of core resource types, which will be easier to do once they're all independently versioned. Let's do that later though as we'll need to first warn people for a while.)

## A Modest Proposal

Let's come up with a process for versioning these things on their own. Rather than automatically building and pushing to `latest`, we can use proper semver and only "ship" them when we want new stuff in the upcoming release. Maybe we can even put release notes on the resources themselves, and have the Concourse release notes just link to them when a core resource type has been bumped.

**Comment by jchesterpivotal** [comment]
I'd suggest a single semver resource shared across everything. In my experience trying to provide versions for each component just leads to a giant thick cord of versions having to be threaded through the whole pipeline to ensure consistency.

**Comment by vito** [comment]
This ended up being pretty easy after templatizing all the resource pipelines via [`jsonnet`](https://jsonnet.org/)! Someone recommended it in Discord and we were using a parameterized ERB  template before but some resources strayed off the template, so it felt like a good opportunity to consolidate and clean up. It feels pretty nice for pipelines once you get over the somewhat less friendly JSON syntax. Here's the template: https://github.com/concourse/pipelines/blob/master/ci.concourse-ci.org/resources/template.jsonnet

Each resource is now versioned on its own, and they've all been pushed and tagged as `1.0.0` (and `1.0` and `1`). Except `registry-image`, which I kept at `0.1.0` as we haven't officially started putting it out there. A GitHub release is also created with the rootfs and resource metadata attached as a `.tgz`, which will be easy to consume in the binary.
