### ISSUE TITLE
Workers do not report the its disk usage correctly

### ISSUE THREAD

**Issue by brunograz** [concourse/concourse#2579]
Hi!

We have observed recently that Concourse workers are not reporting the correct disk usage for its ephemeral disk usage. This seems to happen ever since the change from overlay to btrfs but cannot confirm it.

Here is more info: 
```
worker/0:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G  4.0K  3.9G   1% /dev
tmpfs           799M  4.8M  794M   1% /run
/dev/sda1       2.9G  1.2G  1.6G  43% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            3.9G     0  3.9G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/sdb2        89G   80G  4.0G  96% /var/vcap/data <---
/dev/loop0       79G   49G   24G  68% /var/vcap/data/baggageclaim/volumes <---
tmpfs           1.0M   16K 1008K   2% /var/vcap/data/sys/run
/dev/loop1       89G   33M   89G   1% /var/vcap/data/grootfs/store/unprivileged
/dev/loop2       89G   33M   89G   1% /var/vcap/data/grootfs/store/privileged
```
![image](https://user-images.githubusercontent.com/8091247/45412832-fdc96d80-b677-11e8-89cd-4d84be3b1099.png)
![image](https://user-images.githubusercontent.com/8091247/45412850-0a4dc600-b678-11e8-9a34-8aee4b9b4671.png)

Is this supposed to be the expected behavior or is there a configuration that I might have perhaps missed? 
  

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Did this used to work?

**Comment by vito** [comment]
I'm not sure what's wrong about this. It seems to be reporting both accurately. It makes sense that `/var/vcap/data` may be mostly full because it has committed space for the `/var/vcap/data/baggageclaim/volumes` backing file, whereas the usage within that "mount" is only 68%. What values did you expect to see reported?
