### ISSUE TITLE
Enrich prometheus build metrics

### ISSUE THREAD

**Issue by bradbeam** [concourse/concourse#2584]
# Feature Request

## What challenge are you facing?

We're attempting to monitor the pipeline, we're facing issues with not enough data available via prometheus. 
The two components we feel are missing are:
- I don't have a good way to know if my most recent pipeline run was successful or a failure. The existing counters provide some visibility, but not enough to definitively say what the status of my most recent run was.
- I don't have a way to identify which job in a pipeline failed. In our pipelines, we've got a different job for each environment ( dev/staging/prod ) that executes serially. If the dev or staging job fails, we could route that to slack, but if a prod job fails, we'd want to be paged. 

## A Modest Proposal
I think both of these could be addressed by including an additional metric, something like the following

```
	lastBuildStatusVec := prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "concourse",
			Subsystem: "pipeline",
			Name:      "status",
			Help:      "Status of the most recent pipeline ( 0 = success, >0 = failure ).",
		},
		[]string{"team", "pipeline", "job"},
)
```
This would allow me to  monitor the pipeline as a whole ( `sum(concourse_pipeline_status{pipeline="deploy"}) > 0` ) or monitor the individual jobs ( `concourse_pipeline_status{pipeline="deploy",job="prod"} > 0` )

**Comment by vlfig** [comment]
Another motivation beyond status or availability checks, is to get deployment frequency metrics directly from concourse without resorting to emitting custom ones.

**Comment by jpluscplusm** [comment]
@bradbeam So whilst I selfishly wrote #2785 to fix my specific problem, I'm not sure if it solves all your observability challenges, especially at the whole pipeline level. What's your feeling about if this issue still describes an unsolved problem?

**Comment by Houlistonm** [comment]
Our use case is for Prometheus/Alertmanager (healthwatch) to scrap concourse metrics and alert when backup jobs (platform automation) have failed.
The current implementation of separate counters for success/failure/error/aborted make this impossible.

**Comment by xtremerui** [comment]
done in https://github.com/concourse/concourse/pull/8826
