### ISSUE TITLE
GC shouldn't drop *database-only* container GC jobs when the worker is not running

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2586]
Currently the worker job runner  [drops jobs](https://media.giphy.com/media/5ckweEFDXcLeM/giphy.gif) if the worker isn't in its synced list of running workers [here](https://github.com/concourse/atc/blob/master/gc/worker_job_runner.go#L69-L73). But we only need the worker to be running when the container to be deleted has been hijacked, and we need to set the grace time and [wait for it to 'expire' from Garden](https://github.com/concourse/atc/blob/master/gc/container_collector.go#L182-L219). 

This means that non-running workers' containers won't be GC'd from the DB until they're running ( or they are pruned and everything gets deleted )

**Comment by cirocosta** [comment]
Hey, 

@mhuangpivotal  and I just did it at https://github.com/concourse/atc/tree/feature/2586
