### ISSUE TITLE
Very slow on simple steps building docker images

### ISSUE THREAD

**Issue by AndrewMorsillo** [concourse/concourse#2587]
Concourse 3.14.1 running on GKE via the helm chart. Using btrfs baggage claim driver backed by ssd storage. One worker with 2 cores reserved and plenty of memory.

Some simple steps of my builds are taking a very long time to complete. For example the last few steps of my dockerfile

```
Step 26/28 : WORKDIR /app
Removing intermediate container 5615a8c91284
 ---> cb88082276f6
Step 27/28 : EXPOSE 80
 ---> Running in 69e87cdad51d
Removing intermediate container 69e87cdad51d
 ---> 354cb16727a9
Step 28/28 : CMD ["node", "index.js"]
 ---> Running in 78661a473430
Removing intermediate container 78661a473430
 ---> 6ad704f9a190
```

These last simple steps are taking 3+ minutes each to complete. These should be near instant. I'm not really sure how to go about debugging this. It is making my overall builds take a very long time. A local build takes ~5 minutes where the same concourse build takes 40+ minutes.

**Comment by aterreno** [comment]
Finding concourse (4.10) v. slow, used to be ok. 

I wonder if we have a lot of docker images and the local registry/index is too large to cope with.

**Comment by dbaumgarten** [comment]
Any news on this? Docker builds on (at least my) concourse (v5.4.0) are still horribly slow.
