### ISSUE TITLE
NewRelic Emitter should be added to the BOSH spec

### ISSUE THREAD

**Issue by filidav** [concourse/concourse#2593]
# Bug Report

NR emitter
https://github.com/concourse/atc/blob/master/metric/emitter/newrelic.go

Spec file does not mention newrelic
https://github.com/concourse/concourse/blob/master/jobs/atc/spec

  jobs:
  - name: atc
    release: concourse
    properties:
      newrelic:
        account_id: <id>
        api_key: <key>
        service_prefix: <some value>

The spec file has all the other emitters 
https://github.com/concourse/atc/tree/master/metric/emitter

I updated manifest as above and redeployed.  No metrics.
Am I missing something?

The following can also be handy:

* Concourse version:  3.14.1
* Deployment type (BOSH/Docker/binary):  bosh
* Infrastructure/IaaS:  azure
* Browser (if applicable):
* Did this used to work? first time

**Comment by jama-pivotal** [comment]
This is a nitpick but I'd consider this a feature request. The concourse project frequently gets PRs for new metric emitters and tweaks to existing metric emitters. Those features are usually PR'ed into the core binary first, and if someone wants it in the BOSH release they'll PR that in too. A good example of this was in the DataDog emitter, where it was first added as a PR into the ATC https://github.com/concourse/atc/pull/269 and then later added to the manifest by a different contributor https://github.com/concourse/concourse/pull/2266

That said, I'm going to edit your original report a little bit to reflect that

**Comment by xtremerui** [comment]
closing stale issue.
