### ISSUE TITLE
Upgrading concourse from 3.10 to 4.10 results in json exception on starting web nodes

### ISSUE THREAD

**Issue by samgurtman** [concourse/concourse#2595]
Bug Report:

After upgrading concourse to 4.10, the concourse web node cannot be started. It gives the error `json: cannot unmarshal object into Go value of type []string`. 

This happens when using add-local-user, main-team-local-user and main-team-github. This appears to be due to migration not properly migrating the authentication in the team table between 3.x format and 4.x format. 

The fix is to set the `auth` field to null on the main team row in the teams table. After doing this the concourse properly recreates the auth field in the main team row in the teams table.

**Comment by rweberhart** [comment]
@samgurtman,
Do you mind expanding on how "set the `auth` field to null"? We are having this exact issue going to 4.2.1 and have been unable to find any resolution other than your post.

Thanks

**Comment by samgurtman** [comment]
@rweberhart

Once you've connected to the Concourse DB using a database explorer find the 'teams' table. There should be a row for the main team. Set the Auth column for that row to Null.

**Comment by rweberhart** [comment]
@samgurtman 

Thanks for the help, we were able to get on the DB VM directly and update that table. Everything started up properly now.

**Comment by topherbullock** [comment]
Thanks @samgurtman + @rweberhart we've had a couple other reports of this, but haven't successfully found the combination of manifest / property changes to reproduce it.

Are you able to share what your settings (redacted where necessary) for main team auth were before the upgrade and after?

**Comment by rweberhart** [comment]
@topherbullock, the value we cleared out and the value after are below.

Before: `{"basicauth":{"username":"*******","password":"*****************************"}}`
After:  `{"groups":[],"users":["local:*******"]}`

The Migration history only shows data from the 10/12/18 when we first attempted the upgrade.

```
  version   |            tstamp             | direction | status | dirty
------------+-------------------------------+-----------+--------+-------
 1524079655 | 2018-10-12 23:11:52.779678+00 | up        | passed | f
 1525442981 | 2018-10-12 23:11:52.831525+00 | up        | passed | f
 1525724789 | 2018-10-12 23:11:52.841429+00 | up        | passed | f
 1528314953 | 2018-10-12 23:11:52.843552+00 | up        | passed | f
 1528470872 | 2018-10-12 23:11:52.85252+00  | up        | passed | f
 1529692120 | 2018-10-12 23:11:52.889222+00 | up        | passed | f
 1530037770 | 2018-10-12 23:11:53.047754+00 | up        | passed | f
 1530823998 | 2018-10-12 23:11:53.057105+00 | up        | passed | f
 1530824006 | 2018-10-12 23:11:53.060367+00 | up        | passed | f
 1532706545 | 2018-10-12 23:11:53.062629+00 | up        | passed | f
 1533136021 | 2018-10-12 23:11:53.086088+00 | up        | passed | f
 1533739478 | 2018-10-12 23:11:53.091274+00 | up        | passed | f
 1533934775 | 2018-10-12 23:11:53.442756+00 | up        | passed | f
```
To add some follow up context, we aren't sure where we went wrong with this. We have two environments both as bosh deployments at 3.13.0 installed and configured in the same manner. Environment 1 upgraded just fine after we updated everything to use the [basic-auth.yml](https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/basic-auth.yml) ops file and the variable `local_user.username` and `local_user.password`.  

Environment 2 however did not upgrade properly and that is when we ran into `atc` not starting and the `json: cannot unmarshal object into Go value of type []string.` error.

We set the value to null, restarted `atc`, validated the new table value and everything worked fine from there.

I hope this helps

**Comment by topherbullock** [comment]
@rweberhart do the two environments have identical usernames and passwords? I'm wondering whether there are special characters which cause the migration to fail? We've tried various scenarios of upgrades so far (and ran them hundreds of times over) and haven't managed to find a repro, so any help is appreciated 🙃

**Comment by rweberhart** [comment]
@samgurtman we do have the same username/password for both environments. The the password that is getting set has a '!' but other than that, no other special characters.

**Comment by fewknow** [comment]
Had this same issue when upgrading and fixed with the update to the table.  Thanks!
