### ISSUE TITLE
Admins would like a way to display some sort of name on the dashboard

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2597]
Teams would like a way to display their instance name on the dashboard UI.
Proposing a name added beside the concourse logo on the dashboard view. 

<img width="619" alt="screen shot 2018-09-20 at 11 36 42 am" src="https://user-images.githubusercontent.com/27746614/45829694-8031dd00-bcc9-11e8-96c0-e47924a77c03.png">

**Spec:** Lowercase, Inconsolata, 21px, #ffffff, letterspacing = 0.1 em.

**Comment by domdom82** [comment]
Great! This is exactly what we need :)

**Comment by jama-pivotal** [comment]
Maybe we could let the operator supply the instance name through `concourse` binary and/or the BOSH manifest

**Comment by domdom82** [comment]
We deploy one concourse in each region and we deploy using BOSH so that would work just fine.
