### ISSUE TITLE
"No results for..." message on Dashboard isn't centered

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2599]
I think this is a regression that can be reproduce in 4.2.1. When using the dashboard search the "No results for.." message is left-aligned, but it should be centered.

Steps to reproduce:
https://ci.concourse-ci.org/?search=fdafdfsafdfdssd
or
![screen shot 2018-09-17 at 5 22 02 pm](https://user-images.githubusercontent.com/19274230/45651024-374a1080-ba9e-11e8-8b41-84e5df61f739.png)

Expected is:
![34733360-071a142e-f536-11e7-9afc-f23fa73fa437](https://user-images.githubusercontent.com/19274230/45651067-4f219480-ba9e-11e8-8c96-2f060952f59d.png)

**Comment by pivotal-jamie-klassen** [comment]
yes, looks like this regression was introduced when we added styles for the `MEMBER/EXPOSED` tags on the dashboard. Without something like elm-css, I don't know that there's much of a good test that we can add to prevent future regressions of this sort.
