### ISSUE TITLE
[req] Status badges for readmes

### ISSUE THREAD

**Issue by drnic** [concourse/concourse#26]
As a project I'd like to show off my current CI pipeline status in my README. Ideally to distinguish that I'm using concourse I'd like the badge to be an actual view of the pipeline itself - green/orange/red boxes connected by lines - rather than a simplistic green/red badge. Concourse does more and so perhaps the badge could indicate this.

![image](https://cloud.githubusercontent.com/assets/108/7337775/ae940c58-ebea-11e4-8f5f-23c901181cd0.png)

**Comment by robdimsdale** [comment]
+1 This would be really useful for migrating OSS projects away from hosted solutions like travis etc, where the community would like to see the state of the project.

Could it be implemented as a resource? I would image we would need some server that hosts the image and then the resource could take a snapshot of the pipeline SVG and upload it. I wonder if this presents itself as an odd user-experience though. Depending on the frequency at which the snapshot runs, the result image could be confusing for people - e.g. it's not clear which commit triggered the pipeline.

Perhaps a better idea is to have a new pipeline image taken and uploaded whenever any job changes state? This way the image is always up to date.

Separately, if we want a basic badge, we should consider conforming to the http://shields.io/ standard

**Comment by xoebus** [comment]
I've attached the Tracker story that has some other discussion about this above [#72388008](https://www.pivotaltracker.com/story/show/72388008).

I think going with something like http://shields.io makes the most sense to begin with. The endpoint on the ATC that serves up the images should probabaly allow for specifying multiple jobs which should be joined together in a conjunction when determining whether or not the image should show success or not.

**Comment by cunnie** [comment]
+1 to Rob's comment—having badges would be useful for migrating OSS projects away from hosted solutions like Travis. Admittedly it's more of a marketing feature ("we're serious about testing our [Android] project and have the badge to prove it") than a technical feature, but let's not understate its emotional import—It's the biggest single feature I miss when I migrated my project from Travis.

**Comment by tylerschultz** [comment]
+1 I'd really like to have something to show in on a readme.

**Comment by wfernandes** [comment]
+1 to Rob's comment. Loggregator has been seeing flakiness on travis and would love to have build badges for the CI we truly rely on.

**Comment by cunnie** [comment]
With @xoebus 's help we wrote a first pass at serving an image (SVG) indicating the status of a job's build: https://github.com/concourse/atc/pull/77

**Comment by cunnie** [comment]
Description of how to use badges: http://engineering.pivotal.io/post/concourse-badges/

**Comment by wfernandes** [comment]
@cunnie The link is 404-ing

**Comment by drnic** [comment]
Warren - if using v2.0 then need to add /teams/main to the URL and to "fly expose-pipeline" I think






On Tue, Aug 30, 2016 at 5:44 AM +1000, "Warren Fernandes" <notifications@github.com> wrote:












@cunnie The link is 404-ing

**Comment by cunnie** [comment]
Sorry @drnic @wfernandes for the 404-ing — that was my bad. It should work now.

I published the post the same weekend as v2.0.0 of Concourse was released, and discovered that my blog post was stale, that the endpoint had changed. @vito was kind enough to re-establish the endpoint for me in 2.0.1, but in the interim I unpublished the blog post.

I re-published the blog post on Friday with a footnote describing the special endpoint that v2.0.0 requires.
