### ISSUE TITLE
Concourse 4.2.0 fails to connect to Postgres when running on systemd

### ISSUE THREAD

**Issue by peckeltw** [concourse/concourse#2600]
# Bug Report

We've been running Concourse 3.14.1 successfully without any issue on AWS EC2 instances using systemd with a couple of commandline flags.

    cat >/etc/systemd/system/concourse_ci_web.service <<-EOF
    [Unit]
    Description=Concourse CI Web
    After=network.target
    
    [Service]
    Type=simple
    RestartSec=3s
    Restart=always
    WorkingDirectory=/opt/concourse
    MemoryLimit=infinity
    LimitNPROC=infinity
    LimitNOFILE=infinity
    TasksMax=infinity
    User=root
    Group=root
    ExecStart=/usr/local/bin/concourse web \
      --[SOME MORE REDACTED] \
      --postgres-host=${postgres_host} \
      --postgres-user=${postgres_user} \
      --postgres-password="$${POSTGRES_PASSWORD}" \
      --postgres-sslmode=require \
      --log-level=debug \
     -- [SOME MORE REDACTED] \
    
    [Install]
    WantedBy=default.target
    EOF
    
    systemctl enable concourse_ci_web.service
    systemctl start concourse_ci_web.service

When using the same configuration and Concourse version 4.2.0, Concourse is not able to find the database because systemd complains:

> systemd: [/etc/systemd/system/concourse_ci_web.service:17] Unknown lvalue '--postgres-user' in section 'Service'

> systemd: [/etc/systemd/system/concourse_ci_web.service:18] Unknown lvalue '--postgres-password' in section 'Service'

> systemd: [/etc/systemd/system/concourse_ci_web.service:19] Unknown lvalue '--log-level' in section 'Service'

This results in:
> concourse: {"timestamp":"1537219245.670908928","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 127.0.0.1:5432: connect: connection refused","session":"3"}}

Concourse does not get the DB hostname and therefore tries to connect to localhost. **Switching to Concourse version 4.0.0 makes Concourse connect to the database successfully.**

The following can also be handy:

* Concourse version: 4.2.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS EC2
* Browser (if applicable):
* Did this used to work? yes

**Comment by jstephenson** [comment]
I'm not sure why that would have worked before, but you need line continuations (backslash in this case) to break `ExecStart` in the way you're trying to there.

So it should look more like (notice the line endings):
```
ExecStart=/usr/local/bin/concourse web \
--[SOME MORE REDACTED] \
--postgres-host=${postgres_host} \
--postgres-user=${postgres_user} \
--postgres-password="$${POSTGRES_PASSWORD}" \
--postgres-sslmode=require \
--log-level=debug \
-- [SOME MORE REDACTED]
```

**Comment by peckeltw** [comment]
Thanks @jstephenson,

I did not copy & paste correctly, the backslashes are there of course.

And only the three values I mentioned are not picked up by Concourse.

**Comment by peckeltw** [comment]
@jstephenson correction:

Not my error, Github does not display them. When I go to edit, I can see them :-)

**Comment by marco-m** [comment]
@peckeltw github doesn't display the `\` because you didn't format the code. If you format the code with Markdown (in your case, just indent 4 spaces), the `\` will be displayed and everybody will understand better. There is a "preview" tab in each comment window.

**Comment by habnux** [comment]
I have the same error with version 4.2.1 

`concourse: {"timestamp":"1537219245.670908928","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 127.0.0.1:5432: connect: connection refused","session":"3"}}`

**Comment by peckeltw** [comment]
@habnux the issue with 4.1.0 on Kubernetes seems to be a different one, because here Concourse actually gets the database host name 

> "error":"dial tcp: lookup concourse-experimental-postgresql on 10.0.0.10:53: read udp 10.244.0.32:48037-\u003e10.0.0.10:53: i/o timeout","session":"3"

And I assume you're not using a systemd service on Kubernetes?

**Comment by habnux** [comment]
Yes you're right, This is an issue with the DNS. So version 4.1.0 can be ignored.
```"error":"dial tcp: lookup concourse-experimental-postgresql on 10.0.0.10:53: read udp 10.244.0.32:48037-\u003e10.0.0.10:53: i/o timeout","session":"3"```

**Comment by FearlessHyena** [comment]
Thanks a bunch I'll try that out
I'm installing this on a kubernetes cluster actually (using helm stable/concourse) but hopefully the settings are the same

**Comment by marco-m** [comment]
I have a _feeling_ (might be completely wrong) it is the DNS, so putting an IP address (if you can afford) might help, at least to throubleshoot.

**Comment by FearlessHyena** [comment]
Thanks for the hint @marco-m you might be right. I'm not explicitly specifying one right now

v3.14.1 was the last version that worked

**Comment by peckeltw** [comment]
It's working fine for us now on v4.2.1.

**Comment by rjain15** [comment]
Doesn't work 4.2.1 
`kubectl describe pod concourse-worker-1`
```

Events:
  Type     Reason                 Age               From                                                  Message
  ----     ------                 ----              ----                                                  -------
  Normal   Scheduled              13m               default-scheduler                                     Successfully assigned concourse-worker-1 to gke-cluster-default-pool-bec82955-2sfc
  Normal   SuccessfulMountVolume  13m               kubelet, gke-cluster-default-pool-bec82955-2sfc  MountVolume.SetUp succeeded for volume "concourse-worker-token-j6ksm"
  Normal   SuccessfulMountVolume  13m               kubelet, gke-cluster-default-pool-bec82955-2sfc  MountVolume.SetUp succeeded for volume "concourse-keys"
  Normal   SuccessfulMountVolume  13m               kubelet, gke-cluster-default-pool-bec82955-2sfc  MountVolume.SetUp succeeded for volume "pvc-d449ebb3-c363-11e8-bccc-42010af000ec"
  Normal   Pulled                 9m (x4 over 13m)  kubelet, gke-cluster-default-pool-bec82955-2sfc  Container image "concourse/concourse:4.2.1" already present on machine
  Normal   Created                9m (x4 over 13m)  kubelet, gke-cluster-default-pool-bec82955-2sfc  Created container
  Normal   Started                9m (x4 over 13m)  kubelet, gke-cluster-default-pool-bec82955-2sfc  Started container
  Normal   Killing                9m (x3 over 11m)  kubelet, gke-cluster-default-pool-bec82955-2sfc  Killing container with id docker://concourse-worker:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy              8m (x4 over 12m)  kubelet, gke-cluster-default-pool-bec82955-2sfc  Liveness probe failed: Still trying to clean up before starting concourse. 'fly prune-worker -w concourse-worker-1' might need to be called to force cleanup.
  Warning  FailedPreStopHook      2m (x7 over 11m)  kubelet, gke-cluster-default-pool-bec82955-2sfc  Exec lifecycle hook ([/bin/sh -c while ! concourse retire-worker --name=${HOSTNAME} | grep -q worker-not-found; do
  sleep 5
done]) for Container "concourse-worker" in Pod "concourse-worker-1_default(3d5fb2a7-c370-11e8-bccc-42010af000ec)" failed - error: command '/bin/sh -c while ! concourse retire-worker --name=${HOSTNAME} | grep -q worker-not-found; do
  sleep 5
done' exited with 137: failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
, message: "failed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\n"

```

**Comment by cloud-rocket** [comment]
+1 

Version 3.14.1 works. Version 4.2.1 fails with postgres connectivity

**Comment by topherbullock** [comment]
@rjain15 That looks like issues with the worker coming up and the `PreStopHook` not being able to talk to the TSA, nothing postgres-related there.

**Comment by Zyzle** [comment]
@FearlessHyena I came across the same error when attempting to deploy the helm chart. It looks like this is caused by the environment variables for the charts postgresql database not being applied correctly to the `-web` pod

The root cause of this seems to be typo's in the charts `web-deployment.yaml`, a PR for this is currently waiting here https://github.com/helm/charts/pull/8725 

Deploying the chart with this patch applied fixes the issue for us

**Comment by peckeltw** [comment]
Closing this issue because the problem has been solved.
