### ISSUE TITLE
Many Check resources get unknown handle during bosh upgrade

### ISSUE THREAD

**Issue by andrew-edgar** [concourse/concourse#2603]
# Bug Report

We are doing a bosh deploy to upgrade 4.1 to 4.2.1.

While the workers are rolling several resources went "orange" with "unknown handle: XXXXX" errors.

output of check resource did not fix them ...

```
aedgar1macbook:~$ fly -t sl2 check-resource -r public-cfd-deploy/lonys1-lock
error: check failed with exit status '70':
unknown handle: 3004f4d8-4461-4e53-5e38-691711dd7016
```

The following can also be handy:

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Bosh
* Infrastructure/IaaS: SoftLayer
* Browser (if applicable): N/A
* Did this used to work? Yes

This is occuring during the upgrade process.  Once all the workers upgraded.  It was ok.  But during the upgrade we had lots of issues.

**Comment by scottschulthess** [comment]
I ran into the same problem, some subtle differences
- I experienced this after a bosh deploy consistently.  Not like a concourse upgrade, just any bosh deploy that touched the workers (for example changing a setting, in our case upgrading a newrelic package_
- The resources did not appear to fix themselves at all after the bosh deploy succeeded.   The remained in "unknown handle" no matter what I did.  In our case all the resources were simple `git` resources.  

The only fix I found was to delete the entire deployment and recreate it, though I didn't try using the concourse retire-worker commands.   `fly workers` did not report any issues.

**Comment by tjhiggins** [comment]
Hitting this on 5.8

checking failed
unknown handle: c256efb9-5ab4-4897-5952-ad6c345698e9

**Comment by nkrrkn** [comment]
If I ungracefully terminate a worker, the volumes previously on that worker seem to be stuck for some time once the worker comes back, showing these "unknown handle: ..." for any jobs using them.

If I then shut down the worker correctly (so it retires) then start it, these messages stop.

Hope it helps.

Concourse 5.8.0 here

**Comment by xtremerui** [comment]
closing stale issue.
