### ISSUE TITLE
DNS issue with implementation of New Relic on Concourse CI Application server 

### ISSUE THREAD

**Issue by ghost** [concourse/concourse#2612]
- Concourse version: v4.2.1
- Deployment type (BOSH/Docker/binary): docker-compose,
- Docker Compose Version: docker-compose version 1.18.0, build 8dd22a9
- Docker Version: Docker version 18.06.1-ce, build e68fc7a
- Infrastructure/IaaS: Setup on Virtual Machines Ubuntu 16.04
- Browser (if applicable): Chrome, FireFox, Safari
- Did this used to work? Previous version of CC worked. Version 4.1.0

## What challenge are you facing?

- DNS issue with implementation of New Relic on Concourse CI Application server 
```
{"timestamp":"1537473134.928564072","source":"atc","message":"atc.periodic-metrics.tick.database-connections.emit.failed-to-send-request","log_level":2,"data":{"error":"Post https://insightscollector.newrelic.com/v1/accounts/1865268/events: dial tcp: lookup insights-collector.newrelic.com on 127.0.0.11:53:server misbehaving","session":"2.785.2.1"}}
```

**Comment by xtremerui** [comment]
closing stale issue.
