### ISSUE TITLE
Dashboard 4.2.1 unresponsive/frozen

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#2613]
## Bug Report

We recently tried to upgrade from 3.14.1 to 4.2.1 and ran into a strange issue. After the upgrade anytime anyone logs in (with Github) to the homepage (dashboard) the page becomes unresponsive (with the associated web process with a constant 100% CPU usage). 

If we use a local user to login everything works.

All publicly exposed pipelines show up fine (for an unauthenticated user).

All fly commands work perfectly (login, getting pipelines, etc.).

After I login if going directly to some pipeline URL works fine, and so does navigating the jobs and builds of any pipeline. But as soon as the dasboard is accessed while being authenticated, page freezes and high CPU usage ensues.

If I add a local user to an existing team, and instead of github auth I login with the local user, then everything works too.

## Steps to Reproduce

1. Open the URL defined as the external url
2. Login via Github

## Expected Results

Expected to see all pipelines (visible to the associated user)

## Actual Results

Page completely freezes (cannot interact with anything). High CPU usage.

## Additional Context

We run our concourse instance behind a reverse proxy (nginx) which terminates the SSL connection. I've set `CONCOURSE_COOKIE_SECURE` to false and the `CONCOURSE_EXTERNAL_URL` is set to the url used to reach the ATC via the reverse proxy. However, I've tried tunneling in directly, bypassing nginx and same thing happens.

As mentioned this only happens when anyone logins via Github.

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS:
* Browser (if applicable): Firefox or Chromium (same result)
* Did this used to work? Yes

**Comment by pn-santos** [comment]
So, found out it's a particular team that's causing the browser crash. We have around 10 teams, some with 10-30 pipelines other with only a couple. Since all teams are authenticating against the same github org, once anyone logs in they have full visibility of all pipelines.

As soon as I removed the team in question from the github org association, no more crashes. However if I log in into that team using a local user then the browser crashes after login. Dashboard view in 3.14.1 was working fine for this team, so this _seems_ like some javascript processing corner case resulting in an infinite loop?

Going to try and find out today if it's a particular pipeline that's causing the issue. FYI the team has around 67 pipelines (which I think is more than any one team, but not more that the aggregate of the other teams).

**Comment by mthomasuk** [comment]
Hi guys, just to add to this - have added a screenshot from FF profiler. Seems like elm calls `requestAnimationFrame` which never completes; the error on the `Minor GC` calls is `Nursery is full` - which is a garbage collection warning in the JS engine FF is using (but this issue is not isolated to FF)

![screen shot 2018-09-21 at 10 42 20](https://user-images.githubusercontent.com/5039295/45873815-37daf380-bd8b-11e8-8d88-3720870c7545.png)

Hopefully this isn't an elm issue, but hope this is informative

**Comment by pn-santos** [comment]
I found the cuplrit. The pipeline had a self-referencing `passed` constraint:
```
jobs:
- name: job1
  (...)
  - get: some-resource
    passed: 
    - job1
```
However this seems to pass validation and there are no errors in the logs either. I can get the pipeline with fly but the UI crashes.

Unless I'm missing a scenario, a self-referenced passed constraint should be an "impossible" config right? (i.e. one that shouldn't pass pipeline validation)

**Comment by marco-m** [comment]
@pn-santos See #2174 and the other bugs mentioned there.

**Comment by pn-santos** [comment]
Thanks for the link @marco-m I guess I'll close this one (no point in having duplicates opened)
