### ISSUE TITLE
Public credential not loaded from AWS SecretsManager

### ISSUE THREAD

**Issue by eruvanos** [concourse/concourse#2614]
## Bug Report

Public credential not loaded from AWS SecretsManager, if a pipeline private secret existed and was marked for deletion.

## Steps to Reproduce

- Setup Concourse with AWS SecretsManager as credential backend
- create secrets:
    - `some-pipeline/some-secret`
    - `some-secret`
- delete secret `some-pipeline/some-secret`
- create a pipeline `some-pipeline` using the secret `some-secret`

## Expected Results

Concourse loads the public secret `some-secret`.

## Actual Results

Error occurs:
```
Finding variable 'some-secret': InvalidRequestException: You can’t perform this operation on the secret because it was deleted.
	status code: 400, request id: xxxxxxxx
```

## Additional Context

AWS SecretsManager does not delete secrets immediately. Secrets getting marked for deletion and expire after some days (min 7, max 30). 

## Version Info

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS

**Comment by peckeltw** [comment]
@eruvanos 

Using [AWS CLI for Secretsmanager](https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/delete-secret.html) you can use `--force-delete-without-recovery` to immediately delete a secret. 

This should fix your issue.

Can this be closed?

**Comment by eruvanos** [comment]
@peckeltw 

Thank you very much, 
did not saw that such an option was added after our implementation.
