### ISSUE TITLE
Show the job titles in the boxes on main page.

### ISSUE THREAD

**Issue by 0815fox** [concourse/concourse#2615]
## What challenge are you facing?

I want to have an overview panel in the office, where everyone can see the state of all projects without having to use input devices (mouse / keyboard). The overview page already gives a good overview, but there are just colored boxes.

## What would make this better?

Instead of only showing the title on mouse hover, the title should be shown in the colored boxes and abbreviated in case they don't fit.

## Are you interested in implementing this yourself?

In principle yes, but I do not have the time to work through your code base entirely. I would need a direct pointer on the place where to fix this. However, probably the task is so extremely small, that the one pointing me to the appropriate place could as well just do it.

**Comment by marco-m** [comment]
This request would in my opinion uglify the dashboard and in any case would be impractical for any complicated pipeline. There is a reason why the current behavior is to show the names only on mouse hover, see the CI for Concourse itself: https://ci.concourse-ci.org/. There is simply no space.

A suggestion that might work is to take an existing build information radiator and customize it for your case.

**Comment by jama-pivotal** [comment]
I'd +1 @marco-m comment that it would be impractical and make things quite cluttered. The CI thumbnails can get quite dense. I'd love to hear if you have any novel ways of presenting the job titles on the boxes on the thumbnail. To give you a flavor of the thumbnails we see, I've attached a few examples: 

![screen shot 2018-10-01 at 12 33 38 pm](https://user-images.githubusercontent.com/19274230/46302107-3d4bf100-c576-11e8-903c-362748dc8916.png)
![screen shot 2018-10-01 at 12 33 32 pm](https://user-images.githubusercontent.com/19274230/46302108-3de48780-c576-11e8-9558-1a89d99887f6.png)
![screen shot 2018-10-01 at 12 33 28 pm](https://user-images.githubusercontent.com/19274230/46302109-3de48780-c576-11e8-9639-c29487456e6e.png)
![image](https://user-images.githubusercontent.com/19274230/46302120-476def80-c576-11e8-9635-f234d432e896.png)

**Comment by 0815fox** [comment]
Okay okay okay, I am convinced.
