### ISSUE TITLE
Add migration to remove `versioned_resources`

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2616]
#2386 removed the use of this table, but we don't quite want to blow everything away since we want people to be able to downgrade if things go wrong. Let's just stop using the table and drop it in a later release (wherever we schedule this) once everything seems safe.

Things to do in the migration:
- Remove versioned_resources table
- Remove paused column in resources table
- Remove build_inputs/build_outputs tables

**Comment by clarafu** [comment]
The code for it

**Up Migration**
```
  DROP TABLE versioned_resources;
```

**Down Migration**
```
  CREATE TABLE versioned_resources (
      id integer NOT NULL,
      version text NOT NULL,
      metadata text NOT NULL,
      type text NOT NULL,
      enabled boolean DEFAULT true NOT NULL,
      resource_id integer,
      check_order integer DEFAULT 0 NOT NULL
  );

  CREATE SEQUENCE versioned_resources_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;

  ALTER SEQUENCE versioned_resources_id_seq OWNED BY versioned_resources.id;

  ALTER TABLE ONLY versioned_resources ALTER COLUMN id SET DEFAULT nextval('versioned_resources_id_seq'::regclass);

  ALTER TABLE ONLY versioned_resources
    ADD CONSTRAINT versioned_resources_pkey PRIMARY KEY (id);

  CREATE INDEX versioned_resources_resource_id_idx ON versioned_resources USING btree (resource_id);

  CREATE UNIQUE INDEX versioned_resources_resource_id_type_version ON versioned_resources USING btree (resource_id, type, md5(version));

  ALTER TABLE ONLY versioned_resources
    ADD CONSTRAINT fkey_resource_id FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE CASCADE;
```

**Comment by clarafu** [comment]
We delegated the removing of the `paused` column within resources to a later release in order to ensure a smooth downgrade with keeping `paused` resources. The other alternative was to pause the resources that had the `api_pinned_version` column set to not nil in the downgrade migration but this might cause resources that have been manually pinned in the api to become paused when the user downgrades.
