### ISSUE TITLE
Network issue with non-docker concourse?

### ISSUE THREAD

**Issue by rchady** [concourse/concourse#2617]
I'm having an issue with concourse that my lack of understanding does not let me solve on my own.  I have concourse set up not using docker (concourse-web / concourse-worker daemons running) and am trying to do one of the simple hello-world pipelines.

When I unpause the pipeline, it sits for a long time and then spits out:

* ping https: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Which I have found referenced in multiple issues here, but all the resolutions appear to be aimed at docker based setups.

Among my numerous questions is the key one of, how does concourse-worker actually create containers?  Where can I look to see what is being created and what can be adjusted?

Additionally, when I look at the running containers, it claims there is 1 but I can't hijack it.  I'm assuming that container is not really there yet, but concourse-worker is trying to ping registry-1.docker.io to get the image to create the container?

```
[rchady@fornost:~/d/concourse ] fly -t ci containers                   1   9:53
handle                                worker   pipeline     job          build #  build id  type   name       attempt
73044524-a625-441f-79b3-db7dee6ea7f1  fornost  hello-world  hello-world  2        15        task   say-hello  n/a
875bea82-b0bd-4a53-6cd9-81dd3eddd133  fornost  none         none         none
```

```
[rchady@fornost:~/d/concourse ] fly -t ci hijack -j='hello-world/hello-world'
no containers matched your search parameters!

they may have expired if your build hasn't recently finished.
```

Any help is appreciated on this!

**Comment by username-is-already-taken2** [comment]
Hi there, Did you ever get to the bottom on this?  I to have the same issue with a new setup.  I'm using 5.1.0.  I've tried setting the dns to use 8.8.8.8 which I can see it taken within the logs but still no joy.  Did you manage to workout out a way to hijack them?  if I use the container handle I get a handshake error :(

**Comment by vito** [comment]
Sorry for the abrupt closure, I think you'll have more luck in the support areas rather than here. :)
