### ISSUE TITLE
Generic OAuth - Missing user id in verified claims

### ISSUE THREAD

**Issue by jshingler** [concourse/concourse#2618]
## Bug Report

OAuth configuration failing with Missing user id in verified claims

{"timestamp":"1537809843.578565836","source":"atc","message":"atc.sky.callback.failed-to-issue-concourse-token","log_level":2,"data":{"error":"Missing user id in verified claims","session":"4.105"}}

I have reproduced this error with both keycloak and okta.

NOTE: OIDC Connection appears to work but we need to use OAuth config.

## Steps to Reproduce

Configure Generic OAuth authentication, NOT OIDC, to keycloak or okta. then attempt login and look at logs, ... Grep for atc

## Expected Results

Work like OIDC results

## Actual Results
error:

{"timestamp":"1537809843.578565836","source":"atc","message":"atc.sky.callback.failed-to-issue-concourse-token","log_level":2,"data":{"error":"Missing user id in verified claims","session":"4.105"}}

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Kubernetes
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Unsure

**Comment by pivotal-jwinters** [comment]
This has to do with the implementation of the OIDC and OAuth connectors in our fork of `dex`.

The OIDC connector uses the `sub` claim from the id_token (which is required by the OIDC spec), whereas the OAuth connector looks for a `user_id` field from the `user_info` endpoint. There's no standard when dealing with generic oauth endpoints. 

To resolve this we could add an additional check in the oauth connector for a `sub` field, or perhaps we could make this configurable.

**Comment by keithkroeger** [comment]
Hi, any thoughts about what we can do here at this time?  This would be a blocker to moving forward with a 4x environment for us.

**Comment by keithkroeger** [comment]
Hello @pivotal-jwinters , is this potentially related to https://github.com/concourse/concourse/issues/2683?

**Comment by pivotal-jwinters** [comment]
@keithkroeger yup. Closing in favour of #2683
