### ISSUE TITLE
Outgoing Database Network Traffic Grows Proportionally to the Number of Builds

### ISSUE THREAD

**Issue by mceldeen** [concourse/concourse#2624]
## Bug Report

In order to provide monitoring for our concourse instance, we are running a canary build (that exercises various pieces of functionality) every 30 seconds. This creates a large number of builds (~2800 / day). To help mitigate this, we have set `build_logs_to_retain` to `3000`. Over the time that we've been running this canary build, we have observed a consistent growth of outgoing database network traffic (bytes sent / time period) that seems to be proportional to the number of builds. Deleting all old canary build rows, except the last 3500, cut our outgoing network traffic in half. (We deleted around 64K builds.)

We do not have any monitors that show the canary pipeline's UI and people only occasionally look at the canary pipeline's UI on weekdays. Given that, we can probably rule out the web requests since this network traffic steadily grows on weekends. On a related note, we believe this to be due to a process on the web node because the CPU utilization dropped on the web node when we cleared old build rows from the database.

## Steps to Reproduce

1. Run a bunch of builds over time (with `build_logs_to_retain` set to  a reasonable number).
1. Observe the outgoing network traffic from the database steadily grow without requesting the job's build history from the web.

## Expected Results

The bytes sent / time period should be relatively constant once the system reaches a steady state.

## Actual Results

The bytes sent / time period grows proportionally to the number of builds (not build logs).

## Additional Info

We're pretty sure this is due to a read query who's number of results grows with the number of builds.

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Did this used to work? Unknown

**Comment by mceldeen** [comment]
We tried to do a bit of debugging and `BuildFactory.GetDrainableBuilds()` does seem to grow proportionally to the number of builds. However, we did not configure syslog drain as part of our bosh deployment. As far as we can tell, that query doesn't run unless we have a syslog drain configured.

**Comment by colmtuohy** [comment]
I'd be interested in how you safely trim the resources tables. Assuming you trim the build tables via the build_logs_to_retain setting?

**Comment by mceldeen** [comment]
@colmtuohy In order to trim the resource table, we executed manual delete statements on the postgres database. We also did this with builds table. We're guessing that this is not something that concourse wants its operators doing which is why we filed an issue.

**Comment by Typositoire** [comment]
We're also seeing this. I had open https://github.com/concourse/concourse/issues/3412 until someone pointed me here :p

**Comment by avanier** [comment]
Yeah, we're running [Oxygen Mask](https://github.com/concourse/oxygen-mask) to monitor our clusters and well, needless to say it creates a few builds. >.< Right now we're fine on our _general purpose pipelies_, but this will catch up to us eventually.

**Comment by vito** [comment]
This is a known issue with the current approach to build input candidate computation - I've opened https://github.com/concourse/concourse/issues/3602 to track some work we've started recently to re-implement it to be much more efficient.

**Comment by vito** [comment]
This should be resolved in [v6.0](https://github.com/concourse/concourse/releases/tag/v6.0.0)!
