### ISSUE TITLE
Unpausing pipeline after `set-pipeline` results in 401

### ISSUE THREAD

**Issue by bryaneburr** [concourse/concourse#2629]
## Bug Report

After logging in and flying a pipeline with `fly -t <target> set-pipeline ...`, clicking the "play" button on the pipeline results in a 401 response from the server from `PUT .../teams/<team-name>/pipelines/<pipeline-name>/unpause`

## Steps to Reproduce

1. Log in to concourse with `fly --target <target> login --team-name <team-name>`
2. Fly a new pipeline with `fly --target <target> set-pipeline --pipeline <pipeline-name> --config <config-file>.yml`
3. Navigate to Concourse ATC in browser (we're using chrome) and see that new pipeline is in the paused state
4. Click "play" button 

## Expected Results

- Pipeline is un-paused and this is reflected by the UI

## Actual Results

- UI does not reflect that pipeline has been un-paused
- Developer console (opened with Cmd+Option+J on chrome) shows error: `PUT <concourse-url>/unpause 401 elm.min.js?id=18701b041d48f77c150ba19dedd849da:1 ` 

## Additional Context

Pipeline can be un-paused successfully if we 
- log into concourse with another browser and click "play" button on the paused pipeline. This change is registered successfully on the other browser (where we received the `401` response)
- Un-pause the pipeline from the command line

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Yes

**Comment by h4xnoodle** [comment]
I also just experienced this issue on 4.2.1. Unpausing from the CLI worked for me as well. cc @pivotal-saman-alvi

**Comment by eedwards-sk** [comment]
I've repro'd this almost daily on a local 4.2.3 stack

**Comment by xtremerui** [comment]
closing stale issue.
