### ISSUE TITLE
Cache both privileged and unprivileged volumes for resources

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2630]
## What challenge are you facing?

Running privileged tasks can be quite slow when using the `overlay` driver, because the image and all inputs have to be converted to 'privileged' permissions prior to mounting them to the container. This pain is felt on every single build because we only ever keep the unprivileged format of each volume.

## What would make this better?

If we kept both the privileged and unprivileged version of each cache, we could limit this overhead to one time per worker, and builds would incrementally speed up over time. This may be enough to hold people over until `shiftfs` comes out.

**Comment by ddadlani** [comment]
Do we want to simply use `shiftfs` instead? When will `shiftfs` be on the BOSH stemcell?

This issue would also allow us to recommend overlay to everyone, including those that use a lot of privileged containers

**Comment by ddadlani** [comment]
Clarification: we should only cache privileged volumes when we create them, rather than creating a privileged version of every cache proactively.

**Comment by ddadlani** [comment]
We might also look into the `metacopy=on` flag in overlay, which defers copying until you write to the new file.

**Comment by ddadlani** [comment]
if we switch to `containerd` in #4350 this does not need to be worked on.
