### ISSUE TITLE
ATC returns non existent workers's containers metric persistently.

### ISSUE THREAD

**Issue by kkitai** [concourse/concourse#2634]
## Bug Report
Hi.

I'm getting atc metric for determining to scale worker vms. (using a promethues)
but, Somewhere down the line It have been returning non existent worker's container metric even though its worker name doesn't exist on DB.

Furthermore, those metrics are getting to increase gradually. Why?

```
# max(concourse_workers_containers{bosh_deployment="concourse"}) by (bosh_deployment, worker)
{bosh_deployment="concourse",worker="f253d325-ac39-41a1-9a1c-cd255c569336"}  147
```

```
atc=> select * from workers where name = 'f253d325-ac39-41a1-9a1c-cd255c569336';
(0 rows)
```

## Version Info

* Concourse version: v3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
* Browser (if applicable): Chrome
* Did this used to work?

**Comment by marco-m** [comment]
Is this related to #1921 ?

**Comment by vito** [comment]
should be fixed by https://github.com/concourse/atc/pull/277
