### ISSUE TITLE
Concourse Notification.

### ISSUE THREAD

**Issue by segsik** [concourse/concourse#2635]
Hi,

New starter on concourse CI and I have been playing around with the slack and email notification resource. pcfseceng/email-resource, cfcommunity/slack-notification-resource.

I know I could get a notification based on Job to build success or failure, but I was wondering if there's a way to get notified only when all the job in a pipeline is successful, or failed

**Comment by OvermindDL1** [comment]
You should post your pipeline yaml file.  You should be able to put the `on_success` on the top pipeline instead of in a task.

**Comment by segsik** [comment]
Hi, 
Thanks for your response. Will it support the on_success properties at the top of the pipeline? just tested and it complained about the resource email_notify_aws not found. as i want the complete pipeline build notification to AWS.

`resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource
    tag: latest

resources:
- name: mygit
  type: git
  source:
    branch: develop
    private_key: ((ci-private-key))
    uri: git@bitbucket.org:mygit/mygit.git

- name: engine_dev 
  type: docker-image
  source:
    repository: myimage1

- name: api_dev 
  type: docker-image
  source:
    repository: myimage2

- name: dev
  type: docker-image
  source:
    repository: myimage3

- name: notify-slack
  type: slack-notification
  source:
    url: hookurl  

- name: email_notify_aws
  type: email
  source:
    smtp:
      host: email-smtp.eu-west-1.amazonaws.com
      port: "587"
      username: bla
      password: bla sercret
    from: ci_update@myc.com
    to: [ email1, email2 ]

jobs:
- name: build_dev
  plan:
  - get: mygit
    trigger: true
  - task: copy-dir-for-docker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "18.04"
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r /environments/live_dev/* web_dev/

      inputs:
      - name: mygit
      outputs:
      - name: dev
  - put: dev
    params:
      build: dev
    on_success:
      put: notify-slack
      params:
        text_file: /environments/live_dev/build_notification/slack_message_success.txt
        text: |
          :grin: Great News!!! The Frontend-Dev Build Is Successfull See link below if you want:
          $BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          Now we wait for Backend build to complete Successfully
    on_failure:
      put: notify-slack
      params:
        text_file: environments/live_dev/build_notification/slack_message_failure.txt
        text: |
          :scream_cat: Aw Snap!!! Frontend-Dev Build failed horribly Check it out Now:
         $BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          This failure will not be built on AWS. Fix It 

- name: build_backend_dev
  plan:
  - get: mygit
    trigger: true
  - task: copy-dir-for-docker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "18.04"
      run:
        path: sh
        args:
        - -exc
        - |
          apt-get update && \
          apt-get upgrade -y && \
          apt-get install -y build-essential clang openjdk-8-jdk curl libssl-dev zlib1g-dev libopenblas-dev liblapacke-dev libgoogle-perftools-dev libcurl4-openssl-dev

          export CC=clang
          export CXX=clang++

          echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
          curl https://bazel.build/bazel-release.pub.gpg | apt-key add -

          apt-get update -y && \
          apt-get install -y bazel
          apt-get upgrade -y bazel
          apt-get install -y libssl-dev zlib1g-dev libopenblas-dev liblapacke-dev libgoogle-perftools-dev

          curl -sL https://deb.nodesource.com/setup_9.x | bash -
          apt-get install -y nodejs
          npm install -g yarn

          cp -r environments/live_dev/engine/Dockerfile backend_dev/EngineDockerfile


          cd backend_dev/api
          yarn install
          cd ../..

          mkdir -p /myc
          cp -r myc/data /myc/

          cd backend_dev/engine
          bazel test ...
          bazel build ...
          mkdir -p bin
          cd ../..
          cp backend_dev/bazel-bin/engine/* backend_dev/engine/bin/
      inputs:
      - name: mygit
      outputs:
      - name: backend_dev 
  - put: engine_dev
    params:
      build: backend_dev
      dockerfile: backend_dev/EngineDockerfile 
    on_failure:
      put: notify-slack
      params:
        text_file: environments/live_dev/build_notification/slack_message_failure.txt
        text: |
          :scream_cat: Aw Snap!!! Engine-Dev Build failed horribly Check it out Now:
         $BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          This failure will not be built on AWS. Fix It!!!
    on_success:
      put: notify-slack
      params:
        text_file: environments/live_dev/build_notification/slack_message_success.txt
        text: |
          Phew!!! :sweat_smile: The Engine-Dev Build Is Successfull See link below if you want:
$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          
  - put: api_dev
    params:
      build: backend_dev
      dockerfile: backend_dev/ApiDockerfile
    on_success:
      put: notify-slack
      params:
        text_file: environments/live_dev/build_notification/slack_message_success.txt
        text: |
          :fastparrot:: The Api-Dev Build Is Successfull See link below if you want:
         $BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      put: notify-slack
      params:
        text_file: environments/live_dev/build_notification/slack_message_failure.txt
        text: |
          :scream_cat: Aw Snap!!! The Api-Dev build failed horribly Check it out Now:
 $BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          This failure will not be built on AWS. Fix It

- name: email_notify_aws_build
  plan:
  - aggregate:
    - get: dev
      passed: [build_dev]
    - get: engine_dev
      passed: [build_backend_dev]
    - get: api_dev 
      trigger: true
      passed: [build_backend_dev]
      on_success:
        put: email_notify_aws
        params:
          subject_text: "Concourse ${BUILD_ID} Successful"
          body_text: |
            Great!! Build is Successfull
            Build ID: ${BUILD_ID}
            Build Name: ${BUILD_NAME}
            Build Job Name: ${BUILD_JOB_NAME}
            Build Pipeline Name: ${BUILD_PIPELINE_NAME}

`

**Comment by OvermindDL1** [comment]
Right now your `on_success:`'s are inside a task-level thing, move it 'up' to the same level as `plan:` calls if I recall correctly.

**Comment by OvermindDL1** [comment]
With it at the same level as plan and name then it will only be called if all plans succeed, which when on the last plan of a pipeline should finish.  Groups of pipelines are more interesting though (a semaphore object could be interesting...)

**Comment by segsik** [comment]
@OvermindDL1 do you mean this block of code? 

```
- name: email_notify_aws_build
  plan:
  - aggregate:
    - get: dev
      passed: [build_dev]
    - get: engine_dev
      passed: [build_backend_dev]
    - get: api_dev 
      trigger: true
      passed: [build_backend_dev]
      on_success:
        put: email_notify_aws
        params:
          subject_text: "Concourse ${BUILD_ID} Successful"
          body_text: |
            Great!! Build is Successfull
            Build ID: ${BUILD_ID}
            Build Name: ${BUILD_NAME}
            Build Job Name: ${BUILD_JOB_NAME}
            Build Pipeline Name: ${BUILD_PIPELINE_NAME
```

**Comment by OvermindDL1** [comment]
Yep, though if it is already `serial: true` then you don't need to (keeping `on_success` at the end-most plan works there fine, or in this case you could even put the `on_success` on the `aggregate` task instead of the `get: api_dev` task).

Regardless, for your original inquiry:

> I know I could get a notification based on Job to build success or failure, but I was wondering if there's a way to get notified only when all the job in a pipeline is successful, or failed

Then having the `on_success` on the top level object should do it?

**Comment by segsik** [comment]
@OvermindDL1 Great!! let me give this a try and get back to you. thanks

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Great!! let me give this a try and get back to you. thanks

Cool, I'm quite curious if that will do what you want.  I'm still learning it all myself.  :-)

**Comment by segsik** [comment]
@OvermindDL1 

Tried your approach but still doesn't accomplish what i wanted. 

email_notify_aws_build should fail if any of the build listed in the aggregate param failed. i thought that was the whole idea. please correct me if am wrong @vito

**Comment by OvermindDL1** [comment]
> email_notify_aws_build should fail if any of the build listed in the aggregate param failed.

If it is placed inside the aggregate or on the pipeline itself then it should and I'm using that pattern myself.  Can you post your yaml file again with the recent changes?

**Comment by segsik** [comment]
@OvermindDL1 That is the only change i have made so far. Moving the `on_success` up the plan.
```
- name: email_notify_aws_build
  on_success:
        put: email_notify_aws
        params:
          subject_text: "Concourse ${BUILD_ID} Successful"
          body_text: |
            Great!! Build is Successfull
            Build ID: ${BUILD_ID}
            Build Name: ${BUILD_NAME}
            Build Job Name: ${BUILD_JOB_NAME}
            Build Pipeline Name: ${BUILD_PIPELINE_NAME}
  plan:
  - aggregate:
    - get: mapp_dev
      passed: [build_mapp_dev]
    - get: engine_dev
      passed: [build_backend_dev]
    - get: api_dev 
      trigger: true
      passed: [build_backend_dev]
```

**Comment by OvermindDL1** [comment]
> That is the only change i have made so far. Moving the on_success up the plan.

Yeah, in that case that will only be called if *all* the plan entries are successful as well, that is precisely how I'm using it for note.

**Comment by segsik** [comment]
@vito 

Strugling with this as it doesn't work as @OvermindDL1 proposes, when Fe_Dev fails, it continues with the build and doesn't stop or fail the other builds.

**Comment by OvermindDL1** [comment]
Yeah if `Fe_Dev` is still in an aggregate, that definitely sounds like a bug:
https://concourse-ci.org/aggregate-step.html
