### ISSUE TITLE
Replace `fly status` with `fly userinfo`

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#2639]
## What challenge are you facing?

When trying to make sure that a user is logged in, `status` is not really capable of doing so (as seen on https://github.com/concourse/concourse/issues/2532), although it promises that:

```sh
fly help | grep status
  status               Login status
```

That is because `fly status` only:

- parses the token you have locally (performing some validations along the way, like making sure that the expiration date has not been reached); and
- doesn't verify if the token is valid from the server point of view.

i.e, It doesn't provide very useful information regarding "login status".

On the other hand, we could have a new command, `fly userinfo`, which could:

- check if the token is valid from the server point of view (by really making an authenticated call to `/sky/userinfo`);
- retrieve user info (like teams and roles).

With information like `teams` and `roles` in hand, it would provide a good way for users to make sure that they have access to certain resources.

Wdyt?

thx!

**Comment by marco-m** [comment]
Hello Ciro, I see the reasoning, what is not clear to me is why this liveliness feature should be added as a new fly command instead of enhancing `status` ?

**Comment by jama-pivotal** [comment]
I wanted to +1 this request, but for the other reason of; its really damn hard to keep track of WHO you are logged in as while using `fly`. This might be a biased opinion since not everyone is using `fly` the way I used it for story acceptance (constantly switching between teams and users). 

The main problem I have with fly today is that the target only encapsulates the URL and Team. It doesn't actually connect me with what USER i'm tied to since that's not specified until I get redirectly to the web UI for login. So when I get denied on actions in Concourse 5.0 with RBAC, I HAVE NO IDEA WHY 😕

**Comment by xtremerui** [comment]
In #2532 `fly status` will use /userinfo endpoint to verify the token state.

Here `fly userinfo` will also use that endpoint but it will actually show the user infos.

The example json response is 

```
{
	"csrf": "xxxxxxxxxxxxxxxxxxxxxxx",
	"email": "john@concourse.com",
	"exp": 1546094102,
	"is_admin": true,
	"name": "",
	"sub": "xxxxxxxxxxxxxxxxxxxxxxxx",
	"teams": {
		"examples": ["owner"],
		"main": ["owner"],
		"monitoring-hush-house": ["owner"],
		"resources": ["owner"]
	},
	"user_id": "1234456",
	"user_name": "john"
}
```

Similar to some other fly commands that supports `--json`, `fly userinfo --json` could show the full response body in json. How should the output be formatted without `--json` @jama-pivotal?

**Comment by xtremerui** [comment]
To align with other fly commands like `teams`,

fly userinfo will show
```
username        team/role
john            example/owner, main/owner, monitoring-hus-hous/owner, resources/owner
```

**Comment by vito** [comment]
(accepting finally!)
