### ISSUE TITLE
Only the last entry in `no_proxy` is propagated from worker to resource

### ISSUE THREAD

**Issue by hstenzel** [concourse/concourse#2640]
## Bug Report

The `no_proxy` environment variable contains a comma separated list of hosts and domains which should not to through the `http_proxy` or `https_proxy`. By failing to propagate all but the last entry, traffic is going to a proxy server that is inappropriate for the proxy, leading to at best more latency for the pipeline and more load on the proxy to at worst failure to access the content.

## Steps to Reproduce

- Start concourse with the `http_proxy`, `https_proxy`, and `no_proxy` environment variables set.
- Be sure that there are at least two comma separated entries in `no_proxy`
- With `docker exec` or `kubectl exec`, verify that the worker has the full `no_proxy` environment variable set
- With `fly hijack` observe that the resource container only has the last entry from the `no_proxy` env var

## Expected Results

I expected the `no_proxy` environment variable in the resource container to be identical to the `no_proxy` environment variable in the worker.

## Actual Results

I only saw the last of the entries in the worker's `no_proxy` in the resource's `no_proxy`.

## Version Info

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: IaaS
* Browser (if applicable): n/a
* Did this used to work?: Unknown

**Comment by mattburgess** [comment]
We've just run into this too. 3.14.1 binary (Linux) deployment.  However, I think this might already be fixed in v4.0.0 by this commit: https://github.com/concourse/concourse/commit/5f5a9861c69c80a63631913b4e70e1a01ba1add4

**Comment by hstenzel** [comment]
That would be excellent! Moving above v4 is a bit more work, but it is something we're looking at. I'll definitely check, thank you!

**Comment by xtremerui** [comment]
closing stale issue.
