### ISSUE TITLE
fly volumes ouput contains a bunch of spaces after each entry

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#2641]
## What challenge are you facing?

Not sure if this is particular to my system, but when I do `fly -t <target> volumes` each entry is followed by around ~2400 space characters. All other commands seem to work fine.

When I output with `--json` there doesn't seem to be any spaces anywhere, so I guess this is a formatting/display issue on fly?

## What would make this better?

Not printing the spaces? ^_^

## Are you interested in implementing this yourself?

I'd be happy to but I have no idea where to start (I guess it will be somewhere where fly renders/builds the table display?)...

## Potentially relevant info:

* Concourse/Fly version: `4.2.1`
* OS: `Linux Mint 18.3 / 4.15 Kernel`

**Comment by xtremerui** [comment]
closing stale issue.
