### ISSUE TITLE
Dashboard should have a loading icon for the gap period between pausing / resuming pipelines

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2645]
Dashboard should have a loading icon for the gap period between pausing / resuming pipelines. For context, the Dashboard allows you to pause / unpause pipelines. However, there is a slight lag in the UI between clicking Pause and a full UI state change. This is incredibly aggravating and I have no feedback as to what's happening. See below for an example of this delay:

![oct-02-2018 11-30-09](https://user-images.githubusercontent.com/19274230/46359135-91b6a580-c636-11e8-8d18-6aa62c41e425.gif)

## Proposal
We should swap out the icon with a loading icon / gif while we wait for a response, that way I don't end up smashing the pause button

**Comment by Lindsayauchin** [comment]
Would be nice to add in a material design styled determinate circular indicator here to show the progress of the request. 

**Example:** 

![determinate_progress_indicator](https://user-images.githubusercontent.com/27746614/46361065-c4629d00-c63a-11e8-9088-c83e5bcbbfb1.gif)

**Comment by jama-pivotal** [comment]
Scope creeping myself and saying that we should do this for #2903 as well
