### ISSUE TITLE
Ability to view pipeline diff before applying pipeline

### ISSUE THREAD

**Issue by romangithub1024** [concourse/concourse#2653]
## What challenge are you facing?

We have a large number of pipelines in Concourse. Some of those pipelines are dynamically generated using Jinja (e.g. time triggers such as 'nightly' included/excluded based on certain labels, some job groups appear/disappear based on certain labels, etc). For our use case dynamic pipelines is a necessity.

When a change is made to a pipeline template, it might affect a number of "rendered" pipelines. As a preflight check that nothing gets broken, we want to be able to see the diff of changes BEFORE applying them.

## What would make this better?

Right now we can only do validate-pipeline (it will just print "looks good"), and then set-pipeline will apply and print the diff at the same time as changes are applied.

Instead, the ideal workflow would be:
- validate-pipeline
- set-pipeline with a dry run flag: missing today (it would print diff without applying)
- set-pipeline

## Are you interested in implementing this yourself?

Somewhat. Either way, it seems like a very helpful enhancement. Otherwise, without this functionality, you know that you are applying good changes and a valid pipeline, but you can't preview what exactly will be changed as a result of applying...

**Comment by marco-m** [comment]
I tried and it is possible to obtain the dry run as follows:

```
echo "N" | fly -t devs set-pipeline -p my-pipeline -c my-pipeline.yml
```

:-)

**Comment by ralekseenkov** [comment]
hmmm. that's an interesting approach :)
I've always used `--non-interactive`, so never thought something like is possible

**Comment by xtremerui** [comment]
I believe now setting pipeline shows diff and ask for confirmation from user.
