### ISSUE TITLE
Ambiguous example in versioning documentation

### ISSUE THREAD

**Issue by alidaka** [concourse/concourse#266]
On this page:
> https://concourse.ci/versioned-s3-artifacts.html

AKA
> https://github.com/concourse/concourse/blob/master/docs/examples/versioned-s3-artifacts.yml

There is an example of wildcarding a parameter:
```
- put: my-product-rc
    params: {from: build-artifact/my-product-.*.tgz}
```

The last period before "tgz" should be escaped. This caused us some confusion when comparing against normal path parameters.

**Comment by vito** [comment]
fixed this in https://github.com/concourse/concourse/commit/9a4bc8c8ccbec03ff6c3a8c34e1d015a99e164de by using `file` instead of `from`, which is deprecated anyway

thanks!
