### ISSUE TITLE
Concourse should tell me that it can be upgraded

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#2661]
## What challenge are you facing?

I and many other Concourse operators are often unaware of newer Concourse versions being available. 

There are various ways to become aware, but all of them are manual: revisiting the download page, visiting the forum, lurking in the discord chat.

## What would make this better?

Automation!

Firstly, tell me in the UI and in `fly` that a newer version is available. It should be slightly obnoxious.

For the web UI, I can imagine some kind of banner across the top of each page. A dismissable banner, please, we are not barbarians.

For `fly`, I can imagine receiving a note each time I perform a `fly login`.

Secondly, this will require some kind of endpoint. That endpoint should come with a Concourse resource that checks it. This way I can, in theory, have a fully self-updating Concourse, or at least a Concourse that manages other Concourses. 

For simplicity this can just be a text file sitting in an S3 or GCP bucket.

## Are you interested in implementing this yourself?

Since this requires some action to set up a canonical source of release versions, I can't.

**Comment by jama-pivotal** [comment]
Great idea! I mean, iirc even JetBrains just points you to their website to download the latest release, so MVP could even just be a link back to concourse-ci.org, with a part 2 being self-updating Concourse

**Comment by jchesterpivotal** [comment]
In some sense I don't need Concourse to self-update, I just want to make that easier to do.

I think the file-in-a-bucket idea works best, since you can host JSON files or YAML files in there.

Going one better: each version should look for a file for _its_ version, so that the format can be progressively updated for newer versions.

For example, version 4.4 might look for `releases.concourse-ci.org/4.4.json`. Inside it finds something like:

```
{
"latest_version": "4.4.2",
"display_message": "Upgrade the thing, yo"
}
```

Then later we add a feature to signal which upgrades are CVEs. Version 4.4 doesn't understand that yet, so its particular JSON doesn't use the new format. So when we release 4.5, we get two files -- `4.4.json` and `4.5.json`.

`4.4.json` looks like:

```
{
"latest_version": "4.5.0",
"display_message": "Upgrade the thing, yo"
}
```

And our hypothetical 4.5, which now understands CVEs, has:

```
{
"latest_version": "4.5.0",
"display_message": "Upgrade the thing, yo"
"cve_release": true
"cve_score":"medium"
}
```

**Comment by domdom82** [comment]
this!

**Comment by domdom82** [comment]
We are currently doing regular deployments of concourse itself along with an automated upload of pipelines. Atm we have to apply care that we don't run other stuff at the same time to avoid friction while concourse itself is being updated. So making this easier as a native part of concourse is greatly welcome!

BTW: This has also been one of the requests of an open-space discussion during the unconference at this year's CF Summit in Basel :)
