### ISSUE TITLE
Exit status git 128 on restarting container

### ISSUE THREAD

**Issue by hosamhany** [concourse/concourse#2663]
## Bug Report
- Using the docker deployment, the following error shows on checking the git resources. This error starts showing only on restarting the docker containers.

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
## Steps to Reproduce
- deploy concourse using docker
- set the pipeline 
- trigger the pipeline
- restart the docker containers
- re-trigger the pipeline

## Expected Results
- Expected to run normally when re-triggering the pipeline

## Actual Results
![concourse](https://user-images.githubusercontent.com/10808728/46607060-d7c0ad00-caff-11e8-9f1a-83edc087c36b.PNG)

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Docker
* Docker version: 17.03.2-ce
* Infrastructure/IaaS: VM on premises 
* Did this used to work?

**Comment by rjosephwright** [comment]
I can confirm we are experiencing the same issue with Concourse 4.2.1, but with binary deployment. It happens in `check` as well as `get` containers.

**Comment by hosamhany** [comment]
@rjosephwright So after checking this, it was basically a DNS mapping problem. The host machine itself was not able to map the hostname to the relative IP. This was fixed by using the direct IPs instead of the hostname.
