### ISSUE TITLE
Unable to find rollback concept for docker images

### ISSUE THREAD

**Issue by shru6** [concourse/concourse#2664]
Hello Team,

As we are trying to implement roll back feature for docker images, but couldn't find a way how to achieve.

The idea is that the developer should able to redeploy old version of docker image on docker environment whenever latest image fails which should trigger through the concourse pipeline.

Thanks in advance.

**Comment by marco-m** [comment]
Hello @shru6,

I suggest to post this question on the Concourse forum at https://discuss.concourse-ci.org, and to close this ticket.

**Comment by shru6** [comment]
Hello marco,

Thanks for the prompt response, created an issue with the mentioned link. Closing this issue here.
