### ISSUE TITLE
Concourse Web UI times out to the "experiencing turbulence" page

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2665]
Concourse Web UI times out to the "experiencing turbulence" page. Pretty sure this has been happening since 4.2.1. I'll load up a Concourse webui page like https://ci.concourse-ci.org/ and leave it open. After going home and coming back to my workstation (so...12 hours?) I come back to the Concourse page set to the "experiencing turbulence" page but with no buckle icon

Could possible be due to Chrome's aggressive tab shutdown? Easily fixed with a page refresh though

**Comment by larssb** [comment]
I concur. Experience the same thing. On v4.2.1 as well.

**Comment by viveksuhanda** [comment]
We are facing the same issue on v3.4.0 on IE and Firefox as well.
Can you help us in understanding the issue ?
