### ISSUE TITLE
Fix broken getting started link in Helm Chart

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2666]
When Concourse is deployed using the Helm chart, we suggest the following to users: 

> * If this is your first time using Concourse, follow the tutorial at https://concourse-ci.org/hello-world.html

The link to the tutorial is broken. We should point this to a different place.

**Comment by chrishiestand** [comment]
I'd imagine that issue should be filed here instead: https://github.com/helm/charts/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+concourse

**Comment by cirocosta** [comment]
That's right @chrishiestand 

Thanks for the fix, @topherbullock !

https://github.com/helm/charts/commit/032a5577f1d6516248f95e770f03101a6d80f14a#diff-9f6a59f6cd047f10cb23219e06ba0be8
