### ISSUE TITLE
UI fails to load in Internet Explorer due to JavaScript error

### ISSUE THREAD

**Issue by xtreme-steve-elliott** [concourse/concourse#2667]
## Bug Report

Loading the Concourse web UI in Internet Explorer fails to load more than the blue background due to a JavaScript error relating to "startsWith".

## Steps to Reproduce

Open Concourse on Internet Explorer on Windows (we were using Windows Server 2012 with Internet Explorer 11).

## Expected Results

I expected it to load the UI as it does in Chrome and other browsers.

## Actual Results

Only a blue background appears, and in the JavaScript window, there is an error saying it can't find the method "startsWith".

![46478893-e0da1300-c7bb-11e8-8ffd-12aa723c656d](https://user-images.githubusercontent.com/19274230/46871955-c11c9d80-ce00-11e8-8dfc-694e81dc390f.png)

## Version Info

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH Deployment
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Internet Explorer 11
* Did this used to work? This is the first time I've tried loading it in Internet Explorer.

**Comment by pivotal-jamie-klassen** [comment]
as of 27548767084130ae87a3fc5bbd95b4629c4aef3c (1 week ago) we are no longer using `String.startsWith` (which is indeed only supported in IE 12+) in `web/public/index.html`. Might be worth checking if there are any other incompatible JS functions we're using though.
