### ISSUE TITLE
Pausing/unpausing a job when not authorized just seems to hang indefinitely

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#2672]
## Bug Report

If you are not logged in to a team, but you try to pause/unpause a job in that team, the loading icon appears and there is no feedback that you didn't have permission/your action didn't work.

## Steps to Reproduce

1) Click on a job name in an exposed pipeline that does not belong to your team.

2) Click the pause/unpause button to try to pause/unpause the job

## Expected Results

I would expect some kind of feedback that my action is unauthorized/did not work

## Actual Results

The loading icon is shown for an indefinite period and there is no way to tell if the page is stuck or if your action did not work. 

* Concourse version: v4.2.2

Related to #2428 and #1915 

Screenshot:

![screen shot 2018-10-11 at 4 55 15 pm](https://user-images.githubusercontent.com/36862811/46833399-8b32d700-cd76-11e8-91c5-ac08e78686f5.png)

**Comment by ddadlani** [comment]
@Lindsayauchin @jama-pivotal FYI

**Comment by ddadlani** [comment]
@h4xnoodle just guessing here but if you got added to a new team, you may need to log out and log back in for the changes to apply. If you used basic auth to log in to `fly` without going through the UI, your token in `fly` could have your team info but not the one in the UI.

**Comment by h4xnoodle** [comment]
@ddadlani I was not added to a new team unfortunately. This team I've been on for a while, and I was able to add a new pipeline and unpause it approx. a day before. I logged in with Github on the UI, and with the typical `fly -t [team] login` on cli.
