### ISSUE TITLE
Emit metrics for locks held in the DB

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2674]
## What challenge are you facing?
As an operator its often hard to know when a component stops working because a lock in the DB cannot be acquired ( due to another lock being held, or DB issues)

## What would make this better?
Concourse could emit metrics for the type of lock and object id being acquired and released by the [LockDB](https://github.com/concourse/concourse/blob/master/atc/db/lock/lock.go#L122-L123)

## Are you interested in implementing this yourself?
![AWW YISS](https://media.giphy.com/media/9PsgUfyrNiKK4/giphy.gif)

**Comment by topherbullock** [comment]
@concourse/pivotal Picking this up today for Freedom Friday

**Comment by vito** [comment]
implemented by https://github.com/concourse/concourse/pull/2681

**Comment by xtremerui** [comment]
Tested with local influxdb and grafana. Could see the metric `lock-held` on grafana datasource. Accepted.

**Comment by cirocosta** [comment]
Hey,

Regarding the `objectId` field - is there a use case where one would create a graph that makes use of it?

From my understanding, that's an ID that we generate for specific "pieces" of the DB that we want to lock, right?

Could you please clarify how one can use that field?

thx!
