### ISSUE TITLE
Enhance Volume Streaming Data

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#2675]
**Summary**

Recently, while troubleshooting an issue where a build was stuck for ~5 days, we wanted to run the build from one worker on another worker. 

We knew the volume the build was streaming into but we don't know what volume it was streaming from. This made the issue tough to troubleshoot. 

**Proposal**

It would be good to somehow store where volumes are streaming from somewhere in the db.

**Comment by jama-pivotal** [comment]
Let's look at removing the logger from the `taskArtifactSource` here:
https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L439-L452

We could then just make that type be one that adds additional behaviour to a `worker.Volume`, and pass a logger to each method.

**Comment by ddadlani** [comment]
- [ ] Add the `logger` as a parameter to each of the `artifactSource` methods
- [ ] Remove the logger from the `artifactSource`
- [ ] Expose the `db.Volume`'s worker name to the `worker.Volume`
- [ ] Log the src volume name, src worker name, dest volume name, dest worker name at start and end
