### ISSUE TITLE
fly login does not work on machines without a browser via oidc/oauth/etc

### ISSUE THREAD

**Issue by amuessig** [concourse/concourse#2685]
## Bug Report

When logging in to Concourse using fly, callback URLs are returned if I do not add the password to the command itself.

## Steps to Reproduce

        # fly -t concourse login -u admin
    logging in to team 'main'
    
    navigate to the following URL in your browser:
    
      http://<ip>:8080/sky/login?redirect_uri=http://127.0.0.1:38805/auth/callback
    
    or enter token manually:

It works if I add the password to the `fly` command:

        # fly -t concourse login -u admin -p ${concourse_password}
    logging in to team 'main'
    target saved

## Expected Results

I expect that I do not have to access any URIs with random ports if I login using the password without putting it into the environment. I usually do not have network access to any random ports.

## Actual Results

A redirect URI was returned.

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vsphere
* Browser (if applicable): n.a.
* Did this used to work?
No, login was restructured with `v4.0`

**Comment by ralekseenkov** [comment]
if you don't provide password, fly wants you to authenticate via your browser. but your browser should then pass the result to fly at the very end. it's done via a random port that fly opens on your localhost http://127.0.0.1:38805/auth/callback.

how else would you suggest the flow should work, if you don't specify a password?

**Comment by benjoyce** [comment]
I'm sure in earlier versions it would prompt you for a Username and
Password.

The browser-based flow does not work if you're SSH'd into a browserless
server.

Ben

**Comment by OvermindDL1** [comment]
As a related aside, I wish I could specify the callback server other than being localhost and have that work, right now the port it exposes is not on all interfaces and appears to only be localhost, meaning I have to cut out most of the response URL, change the `+` to a space, then copy paste it over every time...

**Comment by ralekseenkov** [comment]
makes sense. never ran into this because our Devs at Aptomi use fly from their laptops. for the rest we use gitops - devs commit pipeline & parameters to git and they get automatically validated and set-pipeline'd via a separate Concourse "service account" for the respective team

may be we can change the name to "fly with doesn't work on machines without a browser via oidc/oauth/etc"?

**Comment by jama-pivotal** [comment]
@ralekseenkov @OvermindDL1 We recently fixed this issue which allows you to do manual token entry through `fly`, does that help your use case? https://github.com/concourse/concourse/issues/2464

**Comment by jama-pivotal** [comment]
@OvermindDL1 neat, throwing it in UX bucket then

**Comment by predatorian3** [comment]
So, to run in a serverless setup, in a server that creates these jobs automatically, how would one get that bearer token, or be able to use `fly -t myTarget login --concourse-url=https://ci.concourse.net --username=myCi --password="mypassword"` to login with GitHub OAuth? 

I saw something that was a shell script doing a bunch of stuff
https://github.com/concourse/concourse/issues/2809#issuecomment-421153852

What should I look into to get to where I can login without a browser being accessed in the middle?

**Comment by vito** [comment]
Closing this as 5.0 removes the dependence on the local port, and allows you to copy the token to your clipboard.

Let's centralize on #3208 for discussing browser-less login for other auth providers in general.

**Comment by mattskone** [comment]
Adding a comment for future searches: this also seems to be a problem when running `fly` from inside a Docker container, where the random redirect port hasn't been mapped on the container.

**Comment by moshmage** [comment]
I.. just wrapped the whole thing on a puppeteer run and some child processes, go mad https://gist.github.com/moshmage/9daee9f9c14702ab71ce8f6ecf507acd
