### ISSUE TITLE
Search across multiple builds

### ISSUE THREAD

**Issue by domdom82** [concourse/concourse#2689]
## What challenge are you facing?

This issue was raised in an open space discussion during the CF Summit unconference at Basel 2018.

As a user, I would like to filter for all builds on a job that match a certain query. For example, I would like to see all builds containing the words "failed to get x from y" or "timeout during z". 
This would help me analyze error patterns from historical build data and improve the stability of my pipeline.

## What would make this better?

In the job view there should be a search bar that allows me to filter on all past builds and only display those that fit a certain criteria. e.g. "status: failed" or "contains x,y,z" because it is hard to sift thru dozens of build logs manually by opening them one at a time.

## Are you interested in implementing this yourself?

Sorry, not a UI guy :)

**Comment by jchesterpivotal** [comment]
In [`concourse-build-resource`](https://github.com/jchesterpivotal/concourse-build-resource) I added the ability to retrieve logs as a JSON file for basically this purpose. I feed this into a PostgreSQL database with some basic fulltext search indexing.

**Comment by domdom82** [comment]
Thanks for the update. Your resource is great to pull out the data to another location and search it there. But I guess the people I've been talking to argued for a UI enhancement of the concourse UI that  would allow them to display only the builds from history that matched their pattern. The gist was that the UI felt a little too lightweight for serious enterprise use.

Then again the answer could be to feed the data into a separate db alongside another UI that allows for more advanced features like you suggest. Not sure how much resources the concourse UI team can put into these kinds of extensions.

**Comment by cirocosta** [comment]
Hey @domdom82 ,

Thx for letting us know about the feature request!

Regarding feeding the data into a separate `db`, there's been some work a while ago on streaming build logs to syslog targets: https://github.com/concourse/concourse/issues/2104.

**Comment by jama-pivotal** [comment]
Interesting, so this would introduce a search feature into the Builds page!

**Comment by jchesterpivotal** [comment]
PostgreSQL supports full text search but I'd be wary of baking it into the core, without at least fairly strict limits on how large an index will be stored.

A possible alternative: allow the web UI to target some other search API, so that indexing and searching can be offloaded.
