### ISSUE TITLE
Pipeline orientation: top-botton vs. left-right

### ISSUE THREAD

**Issue by domdom82** [concourse/concourse#2690]
## What challenge are you facing?

This issue was raised in an open space discussion during the CF Summit unconference at Basel 2018.

By default, the pipeline tree is oriented left-to-right. I.e. the first job gets placed on the left, dependent jobs are added to the right of it.

In large pipelines, people get annoyed as the need to scroll from left to right as they learned from web browsing that typically scrolling happens from top to bottom. 

## What would make this better?

A UI button that allows people to change the orientation of a pipeline view from left-right to top-bottom would help greatly here.

## Are you interested in implementing this yourself?

Sorry, not a UI guy :)

**Comment by jama-pivotal** [comment]
Interesting idea, though given some of the concepts we're developing with the new Concourse Spatial Resource pipeline this might not be prioritized very highly

**Comment by domdom82** [comment]
I agree this is rather special. Does not reflect my personal opinion but I wanted to collect all opinions nonetheless.
