### ISSUE TITLE
Serial groups across pipelines

### ISSUE THREAD

**Issue by domdom82** [concourse/concourse#2691]
## What challenge are you facing?

This issue was raised in an open space discussion during the CF Summit unconference at Basel 2018.

In our deployment, various pipelines exist for specific teams. For example there is something like an "update pipeline" for daily ops that is running continuously and a "maintenance pipeline" for special jobs like db backups or cleanup jobs that happen only on a weekly basis.

The problem we are facing is that some jobs in one pipeline share resources with other jobs in another pipeline. So the jobs can not run at the same time but they also can not be synchronized using serial groups as those do only work within one pipeline.

There have been efforts to synchronize using git repositories or things like [locker](https://github.com/cloudfoundry-community/locker-resource) but we feel since serial groups are part of the core concourse spec, they should be enhanced instead.

## What would make this better?

Since serial groups are basically tags, their domain could be enhanced to span across pipelines.
To be compatible with the old functionality, serial groups across pipelines could get a `global:` prefix and only those tags would be visible to other pipelines. The UI should probably also be enhanced to indicate that a job is waiting for another job in a different pipeline. 

## Are you interested in implementing this yourself?

Yes! If you accept this proposal just ping me and let us iterate the changes.

**Comment by dhavalpowar** [comment]
Can anyone confirm is this issue has been already fixed? If not, are there plans to fix it?

**Comment by BancarelValentin** [comment]
> Can anyone confirm is this issue has been already fixed? If not, are there plans to fix it?

From https://github.com/alphagov/notifications-govuk-alerts/commit/d70f11b5f3b543170f6e04ec84a4108f881eeaff 
>  - We wouldn't be able to prevent concurrent runs of the functional tests across pipelines [1].

It is unclear but it looks like no. And I feel as this issue is closed we won't ever get an answer. Maybe @benthorner could clarify please ?
