### ISSUE TITLE
feature request - read-only permissions to team/s

### ISSUE THREAD

**Issue by drduker** [concourse/concourse#2695]
## What challenge are you facing?
Need support folks to be able to see what is going on without risk of them triggering things.  Adding "public: true" to specific pipelines is nice but not managed.  This also makes pipelines available to the world to see without authenticated.  What I propose below would force auth to see the read-only pipelines.

## What would make this better?
Using a command like this is what I could foresee:
fly -t <target> set-team -n team1 --local-user=mainuser  --local-user-readonly=mainuser --ldap-group-readonly="team1group" --ldap-group="teat2group"  --non-interactive

**Comment by jama-pivotal** [comment]
@drduker have you had a chance to checkout our RFC for RBAC https://github.com/pivotal-jwinters/rfcs/blob/proposal/rbac/03-rbac/proposal.md  

We've actually just finished our first implementation of this and will be looking to test some of this out locally before our next release! 

Closing the issue for now in favor of RBAC
