### ISSUE TITLE
allow disabling intercept/hijack ability

### ISSUE THREAD

**Issue by lrstanley** [concourse/concourse#2699]
In situations where a pipeline contains quite a bit of sensitive information, even if vault/credhub/etc is used, the build containers left that can be hijacked/intercepted, can be used to pull the credentials out via environment variables from the parent PID, even if nothing is written to disk. Yes, if one has access to a team, they could technically update the pipeline to print out additional variables that would normally not be necessarily shown in the build output, but this is more difficult to do. And in the case of security, making more hoops to jump through is better.

I think it would be best to have the ability to disable hijack/intercept access. This could be on the pipeline level, team level (to maybe better ensure someone can't just re-enable?), but a global option would also be good too. Disabling access like this is similar to what cloud foundry does with SSH access on a global, per org, and app level. I would like to see the same thing here.

As a temporary workaround, we may just make it impossible for someone to login after we do the necessary sensitive work (e.g. chmod 000 /usr/bin or something similar), but it's not a good solution.

**Comment by jama-pivotal** [comment]
Hi @lrstanley , have you had a chance to check out the RBAC rfc? https://github.com/pivotal-jwinters/rfcs/blob/proposal/rbac/03-rbac/proposal.md  Specifically, we outlined some roles in this handy dandy rules matrix: https://docs.google.com/spreadsheets/d/1np3hyJy3mVRfB2gcgKykz3QTQg5qEj28QgK523SEmao/edit#gid=0 

In there we described a world where we have a "team admin" vs a "team member". Check it out! I think that'll suit your needs. The work actually just finished and we're going to try to test this locally before we release this in the upcoming version. Closing issue for now, in favor of the RBAC rfc. Feel free to re-open if you feel that I've done this in error
