### ISSUE TITLE
[req] Private Registry Support

### ISSUE THREAD

**Issue by BugRoger** [concourse/concourse#27]
The concepts in Concourse are really nice. Implementing resources as Docker containers is genius. Very promising project. I feel like its feature set is dearly missing from other CI tools. :smile: Unfortunately I ran into some showstoppers immediately. 

We are running a private Docker registry. It uses a self-signed certificate. I couldn't get tasks with custom docker images to work. There was a timeout in garden-linux' logs. 

I am currently using the Vagrant box. I modified `/var/vcap/jobs/garden/bin/garden_ctl` to include `-insecureDockerRegistryList` or `-registry` but that didn't make a difference. Are there any workarounds to inject our custom root CA certificate into it? And if so, I am probably going to have to add our corporate proxy next.

**Comment by vito** [comment]
Thanks! What format did you use when specifying insecureDockerRegistryList?
Looks like it expects IP:port pairs. I think that flag should have worked.

In addition to tweaking the flag manually, there is a property you can set
as part of a bosh deployment manifest, which you'd have to stop using the
concourse/lite boxes to use. Could try bosh lite.

See
http://bosh.io/jobs/garden?source=github.com/cloudfoundry-incubator/garden-linux-release&version=0.198.0
and http://concourse.ci/deploying-with-bosh.html

Currently there's no way to specify auth credentials with the registry, so
that may be a second showstopper (unless you just run your registry within
your private network with no auth).

**Comment by BugRoger** [comment]
Thanks for your help, @vito. I tried various other combinations but no dice. :unamused: 

Seems like there are some related issues for garden-linux already: https://github.com/cloudfoundry-incubator/garden-linux/issues/31, 
https://github.com/cloudfoundry-incubator/garden-linux/issues/24

**Comment by jbayer** [comment]
@BugRoger there are instructions for running lattice (also uses garden-linux) with a private docker registry here: http://lattice.cf/docs/private-docker-registry/

**Comment by BugRoger** [comment]
@jbayer Thanks for the link. 

We got this working. More or less. We are now building our own Bosh release and monkey our certificates and proxy configuration into various places.

It still is a big struggle to get the configuration into every layer of the Docker onion. For example, we currently are reworking the docker-image-resource to allow login to our registry.

I suppose not everyone is running their own Root Certificate Authority and is plagued with a corporate proxy. But running a private registry in HTTPs is pretty common, I think.

**Comment by hamid-elaosta** [comment]
This is a feature I'm interested in too. I just deployed our private registry which is self-signed, unfortunately, using the insecure-registry options, although working, is not acceptable for our environment. 

I am not overly familiar with the structure of Concourse, but I suspect that the resource running as a Docker container is what is preventing the docker-image resource pushing to my registry from picking up the CA certs registered with the host machine. 

I need a way to have the worker trust our registry by providing it with the corporate CA we use.

**Comment by aquavitae** [comment]
This is a major issue for me too. Any progress on this?

@BugRoger how did you end up monkey patching docker-image-resource?  It's the one piece I can't figure out how to get working

**Comment by endzyme** [comment]
So this is confusing - is the change being made into mainline?

**Comment by vito** [comment]
@endzyme it was done and shipped a while back: https://concourse.ci/downloads.html#v130

**Comment by endzyme** [comment]
Thanks!
