### ISSUE TITLE
Adding syslog flags on ATC break build log reaping

### ISSUE THREAD

**Issue by StevenArmstrong** [concourse/concourse#2705]
## Bug Report

Setting syslog forwarding flags on the concourse ATC seems to stop build logs from being reaped as per the set retention schedule. 

## Steps to Reproduce

Start the concourse ATC with the following flags added:

--syslog-address=xxxxx:514 
--syslog-transport=udp 
--syslog-drain-interval=30s 

Then build log retention is not respected and all new logs remain even when they exceed the keep threshold.

## Expected Results

syslog flags and build logs to retain should be able to be applied to the ATC and work in tandem with logs still being reaped.

## Actual Results

 --default-build-logs-to-retain 10 
 --max-build-logs-to-retain 1000 

are not respected on jobs.
Removing the syslog flags and restarting the ATC and logs are reaped as normal based on the build log retention

## Version Info

* Concourse version: 4.2.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): N/A
* Did this used to work? Not sure

**Comment by xtremerui** [comment]
There is indeed a check to make sure build logs are drained before they got reaped. 
https://github.com/concourse/concourse/blob/b216f374dd1fe7824d271418ce0035c44d50cbf0/atc/gc/build_log_collector.go#L125-L129

One assumption is a race condition that logs are not drained while this process runs; then in the next cycle while logs are drained but that process can't reach to the same batch of build log anymore (as new builds got pushed to top of the stack?)
