### ISSUE TITLE
Add descriptions to graphs in Grafana

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#2711]
**Summary**

New users/operators often have trouble figuring out what the different metrics within Grafana mean. We can improve this experience by adding descriptions along with the metric names within the Grafana dashboard. These descriptions should be persisted in src control.

**Comment by cirocosta** [comment]
Hey,

<br />

We're still in the progress of adding the descriptions, but meanwhile, we've been taking some notes:

- maybe we can leverage some other metrics from the dbstats obj? For instance, we might be able to detect saturation by seeing the `waitcount` going up; or detect problems w/ idle connections ...
https://golang.org/pkg/database/sql/#DBStats

- why `database queries` says `(1m)`?

- maybe we can leverage http response codes given that we have the whole http request path being controlled by the metric middleware?

- maybe it'd be interesting to also capture http resp/duration from baggageclaim?

- eventually we might want to have extra dashboards that are specific by node type (e.g., `worker` and `web)
   - this way, we could have a variable `host` that would allow us to filter out all the metrics by `host` (making the process of cross-referencing them easier)?

- Add `procstat` to `prod` so we can have the same metrics as we have from wings

- Eventually make use of `procstat` to retrieve metrics from `baggageclaim`?
