### ISSUE TITLE
Add Error Log Metrics

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#2712]
**Summary**

For troubleshooting purposes, we should emit a metric for every logger.Error statement on Wings. 

**Solution**
We'll need to display/track this metric through some Dashboard (eg. Grafana+Influx) after we successfully emit the logger.Error metric. 

We'd want to look at the amount of error events over a period of time and setting up an alert around that.

**Comment by cirocosta** [comment]
Hey,

Just some notes,

@YoussB and I were playing around with the idea of registering a new [Sink](https://github.com/cloudfoundry/lager#sinks), something in the lines of:

```go
package main

import (
	"fmt"
	"os"

	"code.cloudfoundry.org/lager"
)
 
type CustomSink struct{}

func (c *CustomSink) Log(f lager.LogFormat) {
	if f.LogLevel == lager.ERROR {
		fmt.Println("ooops, err!", f)
	}
}

func main() {
	customSink := CustomSink{}

	logger := lager.NewLogger("my-app")

	logger.RegisterSink(&customSink)
	logger.RegisterSink(lager.NewWriterSink(os.Stdout, lager.INFO))

	logger.Info("doing-stuff", lager.Data{"informative": true})
	logger.Error("doing-stuff", fmt.Errorf("error!!11"))
	logger.Info("doing-stuff", lager.Data{"informative": true})
}
```

The benefit of that is that we can increment the metrics in a single place and let the periodic collector take care of emitting those metrics.

(still experimenting with it)

**Comment by cirocosta** [comment]
Hey,

Marking this as `paused` right now as I'm not actively working on it.

What's missing there is making sure that we don't extrapolate the cardinality in terms of possible error messages (see more https://github.com/concourse/concourse/pull/2754#issuecomment-443905349).

**Comment by cirocosta** [comment]
Hey, 

Removing the `paused` label as on Friday I just got the code updated with an `opt-in` flag so we can eventually test this out before deciding about the `depth` of the errors to collect (see the discussion here: https://github.com/concourse/concourse/pull/2754#issuecomment-443905349)

Thanks!

**Comment by cirocosta** [comment]
https://github.com/concourse/concourse/pull/2754
