### ISSUE TITLE
Add link to Dex documentation in Concourse auth setup (LDAP) docs

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#2714]
## What challenge are you facing?

We use Dex for our auth flow, but our Concourse docs don't really reflect that, which means that people don't know to look at Dex's documentation for help with configuring auth. For example, the LDAP connector has a few flags that need to be specified correctly, but we don't have an LDAP section in the auth docs and it isn't clear what flags are needed.

## What would make this better?

We should add a link to [Dex connector docs](https://github.com/dexidp/dex/tree/master/Documentation/connectors) somewhere on the auth documentation page.

**Comment by jama-pivotal** [comment]
Resolved in https://github.com/concourse/docs/pull/122
