### ISSUE TITLE
top bar is broken on pipeline, job, resource and build pages

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2716]
## Bug Report

On the aforementioned pages, the top bar is missing the dashboard icon and the user menu styles are all messed up.

## Steps to Reproduce

Take a look at any of those pages -- 

## Expected Results

See nice dashboard icon and user menu, similar to
![screen shot 2018-10-22 at 5 55 46 pm](https://user-images.githubusercontent.com/22056320/47321745-c3ae9c80-d623-11e8-9291-a11779730ce8.png)

## Actual Results

you'll see something like
![screen shot 2018-10-22 at 5 53 45 pm](https://user-images.githubusercontent.com/22056320/47321668-7c281080-d623-11e8-8ccc-402a3a4c1a56.png)

## Additional Context

This was definitely introduced while refactoring the dashboard topbar to use elm-css -- turns out the project was not using a "single source of truth" for these styles, and I deleted the file `newtopbar.less` recently even though those other pages were still using some CSS classes from that file.

## Version Info

* Concourse version: 4.2.2 (master)
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): all
* Did this used to work? yes

**Comment by pivotal-jamie-klassen** [comment]
@jama-pivotal this is an embarrassing regression and should probably be fixed before the next release.

**Comment by osis** [comment]
![username](https://user-images.githubusercontent.com/347097/48450865-dd03be00-e775-11e8-8765-abbdb2fa4e3b.gif)
