### ISSUE TITLE
Ability to turn off the sticky header on the web view

### ISSUE THREAD

**Issue by Moxinilian** [concourse/concourse#2720]
## What challenge are you facing?

The Concourse Web UI has a lot of content to display, but a lot of the available room is hidden by the large sticky header.

![image](https://user-images.githubusercontent.com/30992420/47365468-eac8a500-d6db-11e8-8759-3ed1a8d5cbb5.png)

## What would make this better?

The ability to choose whether or not the header is sticky, either in the web UI or directly in the app's configuration, could help leave a lot more room for actually useful content.

## Are you interested in implementing this yourself?

Unfortunately I am not familiar at all with the code base. But it shouldn't be too huge I believe.

(on a side note, maybe being able to increase the contrast on the build logs could help a lot, because right now I am having trouble reading it, Travis CI for example has #FFFFFF on #000000 so that it's very easy to read)

**Comment by Lindsayauchin** [comment]
@Moxinilian what size screen are you viewing Concourse on?

We haven't heard this complaint from other users but, we are improving the responsiveness across the app so, it would be helpful to understand how you are viewing the app. 

To James point above to add in a knob or dial is an anti-pattern.

**Comment by Moxinilian** [comment]
Thank you very much for your answers.

![image](https://user-images.githubusercontent.com/30992420/48094991-dc1dda00-e213-11e8-8b4e-a594b9c84ed4.png)

Here is a full screenshot of the window to get a better idea of the scale.
As you can see, the main issue I have with this is that it pops a lot of information I don't really care about when I have my mind focusing on sometimes complicated logs. This is especially strong when I try to zoom in (as I sometimes find the text a bit too small for my laptop screen).

![image](https://user-images.githubusercontent.com/30992420/48095240-80078580-e214-11e8-818b-6eda1ce045c0.png)

However I now totally understand why such a feature should not be added in the client itself.
I have not seen something like this, but is it possible to customize the CSS on the backend server maybe? That way it would be easier to tweak contrast levels and other visual aspects of the UI.

While I'm at it, I don't know if it's a configuration issue or something else, but I find it somewhat difficult to find the important logs when I open up a Concourse job.

![image](https://user-images.githubusercontent.com/30992420/48095364-d8d71e00-e214-11e8-8d9a-36e759c19bf6.png)

Here, when I open up the job, the important logs are under the "tests" category. But they are hidden, I sometimes need to scroll a bit to open it up. Now fortunately we get used to it, but I just thought it might be interesting to let you know about that. The Concourse UI is a bit scary for users, so when an occasional  contributor needs to check out the reason why their PR failed CI, they get a bit overwhelmed by the amount of information on this page when they, as a non-maintainer, only care about the build logs.
