### ISSUE TITLE
Uncaught errors  just before the responses panic

### ISSUE THREAD

**Issue by pivotal-saman-alvi** [concourse/concourse#2728]
## Bug Report

As a result of Issue #2676 we want to add in I/O timeouts to the ATC as with the addition of the PR'd ifrit network library changes, we will have the possibility of panics. We need to investigate how to restructure the current handlers in api/ to potentially have a parent wrapper or a post-hook where the I/O error is checked.

## Steps to Reproduce
set the read timeout in http_server.NewSeverWithTimeout to something small (5*time.Second).
`mkfifo pipeName`
`cat "hello" > pipeName`
`docker-compose up --build`
`curl -X PROTOCOL $URL:PORT -data=@pipeName`

## Expected Results

5 seconds after the curL, you will see an I/O timeout panic

## Actual Results

I/O timeout panic
This is not exclusive to IO timeouts, any uncaught errors will panic because we use `log.Fatalf(err)`

**Comment by pivotal-jwinters** [comment]
Just don't use log.Fatal(err)?
