### ISSUE TITLE
Paused/canceled builds should have a reason

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#273]
When I come to a build that was paused or canceled, I'd like to know why. I'd like concourse to ask a user to provide a reason for pausing/canceling a build, and then show that reason in the UI

**Comment by zachgersh** [comment]
hey @robdimsdale - what if as a first step this just listed the github username that paused the build? Would be a great reason to force people to disable basic auth?

**Comment by robdimsdale** [comment]
I could get on board with that. It at least communicates the "who" even if it doesn't communicate the "why" or the "when".

Somewhat tangentially, but I don't think disabling basic auth is always necessary - for example there's no other way to programmatically configure pipelines

**Comment by jadekler** [comment]
+1 for this feature

**Comment by pronoiac** [comment]
I'd like to see both the username and an optional reason for pausing. They'd both be useful: 
* someone paused an upgrade pipeline months ago, but the reason hasn't been recorded anywhere, and that person has probably forgotten why. 
* someone paused something frequent, time-based, and timely this morning, then unpaused it, without telling anyone else. maybe it was an accident. maybe it was for a serious reason. when trying to figure out what happened, knowing _who_ paused it would be a much better starting point. 
These are real use cases, not theoretical.

**Comment by dsabeti** [comment]
+1

**Comment by njbennett** [comment]
We (CF Release Integration) lose engineer time to figuring out why a build was paused every time we have a build paused for longer than a day.
