### ISSUE TITLE
Improve volume streaming between workers

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#2735]
## What challenge are you facing?

Jobs with either lots of resources and/or very large resources that may be executed across several workers have the following data transfer path for the volumes;

> worker 1 (`volume.StreamOut()`) ===>  ATC (via the TSA ) ===> worker 2 (`volume.StreamIn()`)

In the case of remote workers, the ATC is most likely in a different network and potentially on a different IaaS and the impact is even more severe.

## What would make this better?

If `remote worker 1` and `remote worker 2` were on the same network, then could a potential transfer path be as such;

>  worker 1 (`volume.StreamTo(path, targetWorker)`?) ===> worker 2

**Comment by jchesterpivotal** [comment]
I'd be interested to hear what this might look like when using container orchestration and volume-management systems outside of Concourse as it is today. As an outsider I am anxious for Concourse to get out of the business of being a third entire distributed platform (others being Diego and Kubernetes) so that engineering bandwidth is freed up for Concourse-specific value adding.

**Comment by topherbullock** [comment]
👀@a459259 you may be interested in this issue around volume streaming for external workers

**Comment by kcmannem** [comment]
Some thoughts...

We really need to be careful with how we design this. It may even turn out that for our desired requirements we'll introduce too much entanglement to make the improvement worth it. A key benefit for concourse so far has been the separation between how much the worker knows and how much the ATC knows. It makes ops and debugging very easy when something does go wrong.

Workers can be commanded but don't really know what they're doing. Workers create containers without knowing whats running in them or populate volumes without knowing what data is stored. We might want a similar analogy for streaming. Workers send data through a transport without knowing where/who its going to. This separates the responsibility of composing the transport to the ATC and the send/recv of data to the Worker. We are kinda doing this right now but in a very simple form which has disadvantages. The state of the stream is hidden away in the network libraries and the only knobs we're able to turn are the timeouts configurable in http. We might have better luck by building on top of the http layer than relying on it directly. For example we could use a simple handshake to identify key transition in the stream. Any knowledge more than what we have now, lets us build and test more resilient streaming.

**Comment by antonu17** [comment]
Another negative effect of current volume streaming shows up when concourse-web is running in kubernetes with `fewest-build-containers` or `random` container placement strategy. Whenever kubernetes recreates concourse-web pod (e.g. pods scaling out, or evicting from the cordoned node), running builds get errored with "volume not found" error. (or sometimes with `Get http://127.0.0.1:8080/containers: read tcp 'concourse-web-1-pod-ip'->'concourse-web-1-pod-ip': read: connection reset by peer`)
It would be nice if workers could stream volumes directly to one another. Also, it would be nice if concourse-web had a graceful shutdown to prevent errors related to the sudden termination of a concourse-web pod.
