### ISSUE TITLE
Frequent errors from docker.io on external worker

### ISSUE THREAD

**Issue by flawedmatrix** [concourse/concourse#274]
We're seeing the following error about one out of every five builds on our external vSphere worker.

```
Get https://registry-1.docker.io/v2: net/http: request canceled while waiting for connection
```

Are there any steps to improve the reliability of connections to docker.io, or a feature to introduce additional retry logic?

**Comment by superbeeny** [comment]
+1 we're seeing this as well

**Comment by vito** [comment]
This should be better now with `image_resource` + the Docker resource performing retry logic.
