### ISSUE TITLE
Add "stalled since" to the worker object

### ISSUE THREAD

**Issue by YoussB** [concourse/concourse#2741]
## What challenge are you facing?

It is not easy for someone using fly to know when the worker got stalled. Knowing that info can allow the operator to filter out temporary blips. 
 - if a worker has been stalled for a long time then it is easy to decide to prune it and recreate it.
 - if it hasn't been a lot since the worker became stalled, then it may be just a blip.

## What would make this better?

adding `stalled since` to the output of the `/api/v1/workers`. This should also reflect in the output of the `fly workers` command.

**Comment by marco-m** [comment]
very nice idea indeed! We often experience blips.
