### ISSUE TITLE
Create a Topgun (deployment acceptance tests) equivalent for the Helm Chart

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2742]
We should test out out the common deployment scenarios for the Concourse Helm chart.

- Worker Lifecycle
  - landing
  - failing
  - retiring
  - stalling
- Various worker configurations (# Replicas, BaggageClaim Driver, Ephemerality, Resource Limits? ) and sizes (Persistent Volume size, Pod)
  - baggageclaim driver

- Smoke test X-compatibility with other Helm-deployed services (Vault, Prometheus, Etc)
  - https://github.com/concourse/concourse/issues/2849
- Scale a multiple ATC setup
  - https://github.com/concourse/concourse/issues/2851
- Test Rebalancing
  - https://github.com/concourse/concourse/issues/2850
- Find compatible helm topgun tests from BOSH test suite
  - https://github.com/concourse/concourse/issues/2852

**Comment by scottietremendous** [comment]
Reference this as a starting point: https://github.com/concourse/concourse/issues/2693

**Comment by topherbullock** [comment]
We've got a decent start on making Topgun 's helpers modular, and deploying the Helm chart in a suite under `topgun/k8s` configured with ephemeral workers.

One thing we're running into constantly is the liveness/readiness probe for the worker making it hard to consistently know when the worker is actually ready to use. The deploy finishes with `-wait`, which waits for all the pods to be `"Ready"` but the worker isn't registered properly until much later.

We're going to take a look at #2753 and see if we can create a better health check for the readiness and liveness of the worker.

**Comment by cirocosta** [comment]
Hey,

From our first iteration getting some functionality tested there we can improve some things:

- [ ] remove `prometheus` as the direct dependency in `concourse/charts`
  - instead, deploy the dependencies in a different step
- [ ] make use of namespaces to isolate the executions
  - right now we're running everything under `default`

To the tests, I'd also say that it's probably a good idea to test as well (from getting some knowledge getting hush-house up):

- [ ] the default k8s secrets integration
- [ ] use of different baggageclaim drivers (naive, btrfs, and overlay)

thx!

**Comment by cirocosta** [comment]
This TODO-list is getting nasty, sorry for that!

I'll do a bit of triaging on them and create the corresponding issues to put under https://github.com/concourse/concourse/projects/9 so we can more easily keep track of that.

Please let me know if you see the need for any extra test!

Thanks!

**Comment by cirocosta** [comment]
Hey, I'll close this one in favor of https://github.com/concourse/concourse/projects/9 so we can keep track of what's missing there.

Thanks!
