### ISSUE TITLE
Vault Service Is Interrupted It Can Cause 100% CPU Usage and Fill Disk

### ISSUE THREAD

**Issue by goldstar611** [concourse/concourse#2744]
## Bug Report
When running concourse-web as systemd service and integrated with hashicorp vault, concourse-web service may infinitely loop without any delay or backoff if vault service is interrupted.

I had a 10G /var/log/syslog file in a matter of minutes after stopping the vault service (which was running locally on my dev machine).

Concourse-web generates about 6500 syslog messages / second that look like the following:
```
Oct 30 10:51:01 concourse-testing concourse[77736]: {"timestamp":"1540914661.306685686","source":"atc","message":"atc.credential-manager.login.failed","log_level":2,"data":{"error":"Put https://127.0.0.1:8200/v1/auth/cert/login: dial tcp 127.0.0.1:8200: connect: connection refused","name":"vault","session":"3.21340211"}}
```

Syslog file size
```
user@concourse-testing:/var/log$ ls -alh /var/log/syslog
-rw-r----- 1 syslog adm 10G Oct 30 11:15 /var/log/syslog
```

Line count for Oct 30 10:51:01
```
user@concourse-testing:/var/log$ grep "Oct 30 10:51:01" syslog | wc -l
6846
```

## Steps to Reproduce
Install and initialize HashiCorp Vault
Generate some Vault token that Concourse can use
Install and set up Concourse as a systemd service
Update Concourse configuration to use Vault as a secrets engine/database
Stop vault service
Notice high CPU usage and large syslog file

*It may be necessary to configure some pipeline to use a secret in vault* I have not tried a vanilla setup without a pipeline.

## Expected Results

Concourse should have some delay or back off built in. 

## Actual Results

Concourse-web attempted to connect to Vault 6500 times/second which is a bit resource intensive

## Version Info

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Ubuntu VM
* Browser (if applicable): N/A
* Did this used to work? Yes

**Comment by xtremerui** [comment]
We should check if this also applies to other credential manager

**Comment by xtremerui** [comment]
Hi, I think this issue is fixed in https://github.com/concourse/concourse/commit/a99abcc5e075163c408c9bc6f7f75ac2a6b6f20e

which should be shipped in > 4.2.0

Upon verifying myself I definitely not seeing logs rate at 6500/sec, instead the default retry config https://github.com/concourse/concourse/blob/74dfbb7f5020dce1f33668b67025322dd0a29e52/atc/creds/vault/manager.go#L44-L45
are respected.

Please try with new version of concourse and close this issue if it works. Thx!

**Comment by goldstar611** [comment]
That's great news and a really easy fix. I will update the binaries and report back in a few days time

**Comment by goldstar611** [comment]
Yes, It looks like this has been resolved. Thanks for tracking that specific commit down, I appreciate how you guys do business around here!
