### ISSUE TITLE
Spike : Can Knative Help Run Concourse Tasks?

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#2746]
We'd like to do some preliminary investigation into K8s as a Concourse runtime. We believe a good place to start would be to investigate whether Knative can run Concourse tasks.

**Comment by chenbh** [comment]
Now that there's an RFC for this at https://github.com/concourse/rfcs/pull/22, should we move this to the Runtime track?

**Comment by cirocosta** [comment]
Hey @chenbh , I'll actually close this one and let the k8s runtime track move on with its own issues at https://github.com/concourse/concourse/projects/14 👍 

Thanks!
