### ISSUE TITLE
Display who triggered a build, not just date when it was triggered (for audit purposes)

### ISSUE THREAD

**Issue by ralekseenkov** [concourse/concourse#2752]
## What challenge are you facing?

It's a must-have for any enterprise use case (including ours) due for audit/compliance purposes. All CI systems have this already (Jenkins, Teamcity, etc.)

* If a build was triggered manually by UI or CLI, Concourse should store and display username of who triggered the build
* If a build was triggered automatically, it can just display name/version of the resource

If something happens and you are trying to dig into build history of a particular job, you need to be able to know why each build was triggered and by whom.

## Are you interested in implementing this yourself?

Possibly. Not sure if this will require DB schema changes + translations or not.

**Comment by StevenArmstrong** [comment]
+1

**Comment by loghen41** [comment]
Has there been any update to this particular issue? or a timeline as to when this may be implemented?

**Comment by loghen41** [comment]
I've put in a pull request to respond to at least a part of this issue (pretty much focused on manually triggered jobs)

https://github.com/concourse/concourse/pull/3313

I'm open to this needing to be expanded to fit other issues.  This seemed a lightweight solution to at least resolve a portion of the problem.

**Comment by ralekseenkov** [comment]
@loghen41 nice! how does it look from the UI standpoint?

**Comment by loghen41** [comment]
@ralekseenkov That's a good question.  After reviewing what you had originally posted, I realize that my submitted pull request approaches this problem with a slightly different paradigm than what you originally put. 

It's likely a good first step, but doesn't approach updating the database or the UI.  I was more focused on ensuring that the logs produced by Concourse declare the user information on a manual trigger.  This was a very lightweight approach which didn't require a database/UI change, but implements one of the first items needed to create an audit history.  (ie. the logs)

that being said, @pivotal-jwinters  reviewed by pull request and informed me that there are some upcoming changes that will have some merge conflicts with what I did, so I'll be in the process of reviewing it anyway. 

I can take a look at taking this to another level to store/display the user data associated with the job while I'm at it.

**Comment by vito** [comment]
This should be done now that #6369 is merged, though it's not currently shown in the web UI (only `fly builds`). Going to leave #4120 open since it's more specifically asking about the web UI.
