### ISSUE TITLE
Improve the liveness probe for the Helm Chart's Worker StatefulSet.

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2753]
By default the workers will retire (and then be pruned) if the following are logged by the worker: 
```
guardian.api.garden-server.create.failed
```
```
baggageclaim.api.volume-server.create-volume-async.failed-to-create
```

This means that any failure to create a container will retire the worker. Creating a container can fail for any old reason, even a poorly written task, so this is less than ideal.

**Comment by ralekseenkov** [comment]
we filed this a while ago, with one specific example
https://github.com/concourse/concourse/issues/2656

**Comment by william-tran** [comment]
lifecycle related: #2757

Should this be changed? a worker coming back up after not having cleaned itself up yields this error: ```guardian.attach.lookup-failed```

What about btrfs errors? disk out of space errors? We really need to disambiguate any old error from ones that require a worker restart to fix.

**Comment by topherbullock** [comment]
@ralekseenkov Thanks for linking that! Definitely sums up the exact case we figured would cause the liveness probe to retire the workers.

@william-tran 
> We really need to disambiguate any old error from ones that require a worker restart to fix.
I'm thinking we'll likely want a health check of some sort on the worker itself rather than rely on logs. We don't have much control over Garden's logs, so differentiating the root cause behind a failure to create purely by reading logs would be a pain.

**Comment by topherbullock** [comment]
@cirocosta and I are spiking on a worker component to ping Garden (via the /ping endpoint) and Baggageclaim (no /ping .. but we'll figure something out.. ).

Will add more details on what we discover.

**Comment by cirocosta** [comment]
Hey @topherbullock ,

I just submitted to `concourse/charts` a branch that, like `concourse/dex`, keeps a bunch of PRs / branches merged into a single view:

- https://github.com/concourse/charts/blob/maintenance/run.sh

That allows us to reference `concourse/charts#merged` and move forward with the work.

Do you think that is enough to consider this issue not blocked?

Thx!

**Comment by cirocosta** [comment]
Hey,

Just a quick update; https://github.com/concourse/concourse/pull/3025 adds the functionality I described above.

Thanks!

**Comment by cirocosta** [comment]
Hey, I'll consider this one as `closed` as in `master` (see https://github.com/concourse/concourse/commit/a7e13ce40e6f57b0b7ab3be95b0b11d664eb8b77) we already have the healtcheck endpoint there which is used by the release candidate chart.

Work goes on in #3025 :+1:
