### ISSUE TITLE
Build page logs are hard to read

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2765]
## Proposal

Build page logs need a bit more contrast. The current UI does not provide sufficient contrast for legibility and ease of reading.  

![screen shot 2018-11-06 at 1 51 55 pm](https://user-images.githubusercontent.com/27746614/48088810-e79be180-e1d0-11e8-8f52-fa4934111ed8.png)

Part 1: A quick fix could be... 
 - [ ] updating the log font colour to white. 

Part 2: Larger (global colour impact)updates to the back ground could be:
- [ ] updating the background to #2A2929 (used on the groups background currently)
- [ ] updating the highlighted/select log line background colour to #666666

**Implications of making the background darker is that we lose the contrast on the 'steps'. as they cannot get any darker than black** 

![screen shot 2018-11-06 at 2 53 03 pm](https://user-images.githubusercontent.com/27746614/48089968-b244c300-e1d3-11e8-8138-9b09e70c0873.png)

**Comment by osis** [comment]
Noticed this as well. Newer build log styling defaults to a grey-on-grey that is much harder to read.

**Comment by Lindsayauchin** [comment]
related to this issue https://github.com/concourse/concourse/issues/2765

**Comment by xtremerui** [comment]
@pivotal-jamie-klassen not sure the current state of build page logs. Is this sth still worth look into?
