### ISSUE TITLE
Workers endpoint returns 0 for `active_volumes`

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2766]
The `/api/v1/workers` endpoint is currently returning 0 for `active_volumes` on every worker returned. Since this API is used by `fly workers` that command also lists workers as having 0 active volumes.

**Comment by pivotal-kahin-ng** [comment]
Currently when using `fly workers`, `active_volumes` will only show up if the user uses the `--json` configuration. Would it be beneficial for `volumes` to be one of the columns in the default `fly workers` table output?

**Comment by cirocosta** [comment]
@topherbullock , 

I'd say this can be already accepted (it's still in Icebox, but I guess we can move it), wdyt?

thx!

**Comment by topherbullock** [comment]
Closed as this is merged and accepted. thx @cirocosta :D
