### ISSUE TITLE
Proposal for the resource to pass metadata to Spinnaker

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#2769]
Use cases
- Pass git reference
- Pass Concourse Metadata for traceability. From Spinnaker, I'd like to determine which build in Concourse triggered a Spinnaker pipeline

Types of metadata to be passed
- Concourse metadata (eg. BUILD_ID )
- Dynamic build params (eg. git sha )
- Static pipeline params 

Questions
- How does Jenkins integrate with Spinnaker

**Comment by xtreme-sameer-vohra** [comment]
Questions: 
 - Is there an API that provides pipeline builds in spinnaker?
 - Can we get build metadata?
 - What is a version gonna be in concourse? (success only?, a new run? ... etc)
 - Adding attachments to the pipelines api in spinnaker?

**Comment by xtreme-sameer-vohra** [comment]
For a Get, there is a pipeline execution endpoint `GET /pipelines/{id}`

For Check, there is an application/pipelines endpoint `GET /applications/{application}/pipelines`

For a Put, the body only takes JSON, so support for files

**Comment by jama-pivotal** [comment]
Closing and deferring to RFC
