### ISSUE TITLE
Remove support for direct worker registration from the TSA

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2774]
## What challenge are you facing?

Kind of a precursor to #2415 - direct worker registration is more efficient but is a pretty big security hole. Forwarding works in more situations (since it only requires the worker to be able to reach the ATC, not vice versa) and something we have a better chance at securing.

## What would make this better?

Let's just use forwarding mode. The binaries already do this by default. Some folks are already using this with large installations, so we should make sure it works well, and the easiest way to do that is to have it be the only way, force out any issues, and fix'em.

## Are you interested in implementing this yourself?

Already did! (#2748) I'm just recording this for the release notes and tying the refactor to the feature it's intended to help (#2415).

**Comment by philandstuff** [comment]
I don’t think this has been fully documented - the concourse internals page still references direct worker registration: https://concourse-ci.org/internals.html#component-tsa

**Comment by vito** [comment]
@philandstuff good catch - submitted https://github.com/concourse/docs/pull/351 if you'd like to review it!
