### ISSUE TITLE
Webhooks can take too long to return

### ISSUE THREAD

**Issue by timrchavez** [concourse/concourse#2775]
## Bug Report

Because version checking is happening in the context of the webhook http request, it can potentially add considerable time to the response, and could result in the webhook being timed out by the client.

## Steps to Reproduce

Configure 20 - 30 webhooks in GitHub that map to 20 - 30 resources in 20 - 30 different pipelines. For every commit, you will trigger 20 - 30 webhooks. Create lots of PRs and make commits to them over a few hours to simulate "working ours". Observe over time. For us, we're seeing lots of Service Timeouts. The problem may be slightly exaggerated for us because we use GitHub Enterprise and need to protect other consumers of webhooks, so we have to use aggressive timeouts to prevent the queue from getting too unmanageable (GHE defaults to processing 12 webhooks at a time and will wait on up to two timeouts (connection and response time) to occur before giving up and moving to the next webhook), e.g. creating a backlog of thousands of webhooks to process.

## Expected Results

The webhook to return 200 as soon as Concourse acknowledges it. Webhook client does not need to know whether the version check was successful, just that Concourse handled it. Webhooks should be fire and forget.

## Actual Results

The webhook client block waiting for Concourse to determine if the version check was successful.

## Version Info

* Concourse version: v4.2.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Droplets (DigitalOcean VMs)

**Comment by timrchavez** [comment]
https://github.com/concourse/concourse/pull/2767

**Comment by christophermancini** [comment]
#2767 has been merged which should significantly improve the performance of webhook processing times. Thanks @timrchavez!

**Comment by exchgr** [comment]
This is still happening for me on 4.2.2

**Comment by christophermancini** [comment]
@exchgr the change has been merged to master but not released. It should be in the next major / minor release, 4.3 or 5.0.

**Comment by exchgr** [comment]
ah, thanks!
