### ISSUE TITLE
Add 'concourse generate-key' command

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2779]
## What challenge are you facing?

Context: https://github.com/concourse/docs/pull/124

Apparently good ol' `ssh-keygen` isn't quite foolproof enough on some machines. It's also not really something we can assume on most Windows deployments.

## What would make this better?

It'd be easier and more portable if we just had a command to generate the keys. Then we could guarantee that Go would be happy with them, since we have more control over how they're generated in the first place.

To be honest this command could just straight-up mimick the behavior of `ssh-keygen`, maybe with opinionated defaults for heightened security (e.g. block size 4096?). I haven't put much thought into this though. We could make it super fancy and know to generate the set of keys that Concourse needs (signing key, ssh gateway (tsa) key, worker key), but that may be overkill since people may want to run it to just generate individual worker keys, too. So maybe it should just be one key per invocation.

## Are you interested in implementing this yourself?

If I only had the time!

**Comment by eedwards-sk** [comment]
I've used [cfssl](https://github.com/cloudflare/cfssl) a bunch and I believe if uses go if y'all are looking for some inspiration.

This would definitely be a useful addition.
