### ISSUE TITLE
fly set-pipeline after auth prompt loses keystrokes during confirmation prompt

### ISSUE THREAD

**Issue by larham** [concourse/concourse#2780]
Using fly 3.14.1, and some previous versions we think, we notice that keystrokes seem to be lost by the fly app.

### Steps:

* fly logout
* fly sp <some args>
* authenticate using browser
* It shows a diff of changes to pipeline, and then asks `apply configuration? [yN]: `
* type some characters

### Expected:

* each and every character is echoed on command line and functions

### Actual:
* it seems like every other character is swallowed, or one character out of several is accepted

### Example
In the example below, we typed `123456789123456789123456789` at the prompt (very rapidly, by swiping across the keys). Only a few of those characters were echoed to the screen.

```
→ fly -t prod set-pipeline -p [...] -c [...] -l [...]
could not find a valid token.
logging in to team 'main'

1: GitHub
2: Basic Auth
choose an auth method: 1

navigate to the following URL in your browser:

    https://prod.ci.gpdb.pivotal.io/auth/github?team_name=main&fly_local_port=49934

or enter token manually:
token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'
or enter token manually: target saved
jobs:
  job demo has been added:
+ name: demo
+ plan:
+ - task: hello world
+   config:
+     platform: linux
+     run:
+       path: bash
+       args:
+       - -c
+       - echo hello world
+   image: bash

apply configuration? [yN]: 369251379
```

CC: @dsharp-pivotal

**Comment by jama-pivotal** [comment]
Linking to #2414  because its the same root cause
