### ISSUE TITLE
Web NavBar Refactor

### ISSUE THREAD

**Issue by pivotal-saman-alvi** [concourse/concourse#2796]
## What challenge are you facing?
We are in the process of shifting over to a new NavBar in the web codebase to handle a few things:
* different screen sizes
* the various components being rendered onto the nav bar (pinning, search, login UI, breadcrumbs)
* a way of doing styling that both allows for easy testing and for the longer term Concourse StyleGuide that @Lindsayauchin is thinking of making

Proposing a refactor to one NavBar before we proceed forward with other NavBar related stories to deal with the following issues (so we are not duplicating work later):
- [ ] Responsiveness
- [ ] Composable UI components
- [ ] Information routing (pipeline page -> top bar, dashboard -> top bar)
- [ ] Styles

**Comment by pivotal-jamie-klassen** [comment]
even though the commits aren't tagged, changes relating to this issue have introduced a regression that should be addressed before closing: #3226

**Comment by pivotal-saman-alvi** [comment]
PR: https://github.com/concourse/concourse/pull/3252
