### ISSUE TITLE
Dev - Richard Godden

### ISSUE THREAD

**Issue by goddenrich** [concourse/concourse#2797]
# File an Ask Ticket (ask-cf@pivotal.io)

    Hi Ask!

    We have a new team member on Concourse.

    First and last name: Richard Godden
    Email:
    Location: London
    Affiliation: PIVOTAL
    Github Username: goddenrich
    Do you have 2 factor authentication enabled on your GitHub profile:
    New hire or rotation: 

    Please add them to the following
    Mailing lists:

    LastPass groups:

    Salesforce:

    Sincerely,
    The Concourse Team

# Ask a PM/Anchor
- Calendars
    - [ ] Concourse
    - [ ] Concourse OOO
- Github access
    - [ ] concourse/Pivotal team
- Discord (Alex)
    - [ ] `pivots` list

# Do yourself/with a pair
- Accounts
    - [ ] Github
    - [ ] LastPass
    - [x] Discourse
    - [ ] Discord (check Discourse for invite)
    - [ ] Parrit
- GCP Project owner access
    - [ ] cf-concourse-production
- Slack Channels
    - [ ] Pivotal#concourse-private
    - [ ] Pivotal#concourse-wings
- Dev Setup
    - [ ] .git-authors
- SSH Keys
    - [ ] Get USB thumb drive
    - [ ] [Reformat as encrypted drive][encrypted-drive]
    - [ ] Create SSH key pair and add to Github account
- Readings
    - [ ] bit.ly/concourse-wiki
- Checklist
    - [ ] Update the [template](/concourse/concourse/wiki/Developer-Onboarding-Checklist) with improvements made

[slack]: https://concourseci.slack.com
[encrypted-drive]: https://github.com/pivotal-legacy/usb-login-scripts
[pagerduty]: https://cfoundry.pagerduty.com
[pilots]: http://pilots.cfapps.io

**Comment by jama-pivotal** [comment]
Hi @goddenrich , welcome to Concourse! Are you looking to be a contributor on the project? The checklist you saw is mostly for Pivots who are joining the team locally in Toronto. If you're interested in just doing normal contributions you can check out the Contributing docs https://github.com/concourse/concourse/blob/master/.github/CONTRIBUTING.md or hang out with us on Discord #contributors channel

**Comment by goddenrich** [comment]
ah! yep I got a little confused thanks for the clarification. I have introduced myself in #introductions and requested to be added to #contributors

**Comment by jama-pivotal** [comment]
neat! see you there!
