### ISSUE TITLE
When a resource is used in >1 builds, the ordering is wrong

### ISSUE THREAD

**Issue by voelzmo** [concourse/concourse#280]
Using concourse 0.72.1

Not sure how to describe this properly, see attached screenshot of a resource's detail view. I would expect to see builds of `bats-ubuntu-manual` and `bats-centos-manual` in the order of build numbers, e.g. 129,130,131,132. Not sure why they are listed as 130,131,132,129.

<img width="895" alt="screen shot 2016-02-16 at 14 52 26" src="https://cloud.githubusercontent.com/assets/2256887/13078136/800eac6e-d4bd-11e5-8caa-9809f539819f.png">

**Comment by vito** [comment]
We'll probably sooner redo that entire page before fixing this. :P Just gonna close for now.
