### ISSUE TITLE
fly execute randomly can no longer properly relatively resolve inputs

### ISSUE THREAD

**Issue by Freyert** [concourse/concourse#2807]
I have been using `fly execute` successfully all morning and then all of a sudden this error starts happening 100% of the time when using relative paths.

```
➜  Desktop fly --target ci execute --config `./pipeline/ci/tasks/task_deploy_stack.yaml` --input pipeline-scripts=../../../scripts
executing build 41 at https://XXXXXX/builds/41
initializing
failed to upload input 'pipeline-scripts': Put https://XXXXX/api/v1/builds/41/plan/5b058e31/input: tar compress failed (exit status 1). output: "tar: ci/tasks/deploy_environment.yaml: Cannot stat: No such file or directory\ntar: Error exit delayed from previous epipeline-scripts: 12.42 MiB/s 0s
Put /volumes/065afdce-adf9-4529-59af-516c96a4db9e/stream-in?path=.: unexpected EOF
errored
```
When I rename the config file to be `./pipeline/ci/tasks/deploy_environment.yaml` it starts working again. 

I guess the issue is. What must I do to rename the config file?

**Comment by xtremerui** [comment]
This should be fixed in https://github.com/concourse/concourse/commit/ad411a6c10f33911372948bf28f87f5da3a38f43#diff-62caaeee500b443fb4d2392d98afed61
