### ISSUE TITLE
A way of preventing multiple pipelines from running concurrently

### ISSUE THREAD

**Issue by Jonty** [concourse/concourse#281]
We have several pipelines that absolutely must _not_ be executing at the same time as they operate on the same resources.

We are currently using the `pool` resource to lock between these pipelines, however this is very messy and often requires manual intervention to release locks when the pipeline fails.

Ideally an option resembling `serial_groups` could be added operating at the pipeline level, `pipeline_groups`.

**Comment by vito** [comment]
Do you mean separately configured pipelines, or multiple runs of one pipeline (i.e. prevent earlier jobs from running until things have run through as far as they can in the pipeline)?

Pipelines are entirely namespaced from each other (and we plan to keep it that way) so if you need to synchronize them your only hope is something like the Pool resource.

**Comment by Jonty** [comment]
I mean separately configured pipelines - https://github.com/concourse/concourse/issues/282 is actually about multiple runs of the same pipeline!

If you have no plans to implement this, feel free to close it.

**Comment by vito** [comment]
Yeah it's very important for us to treat pipelines as entirely separate; they're the "top" of the conceptual model meant to be portable, reusable, etc. The idea is that if you have coupling between parts of separate pipelines either they should be merged or you should represent the coupling as a resource.

I agree that the `pool` resource has its UX quirks, but it still feels like the best direction to be looking for improvements, perhaps made to Concourse itself, to make using it easier.
