### ISSUE TITLE
Feature Request: fly interpolate

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [concourse/concourse#2811]
Given a pipeline configuration and a set of variables, I would like to be able to view the final pipeline (with interpolated variables) to verify I have supplied the right variables and they are correctly formatted.

Past requests (https://github.com/concourse/fly/issues/163 https://github.com/concourse/concourse/issues/1789) have been closed with instructions to use `validate-pipeline`, but that only prints `looks good` (for v3.14.1)

Current workaround is:
`fly set-pipeline`
`fly get-pipeline`

**Comment by xtremerui** [comment]
PR merged. Closing.
