### ISSUE TITLE
feature request - delete a target

### ISSUE THREAD

**Issue by chrishiestand** [concourse/concourse#2816]
The same as https://github.com/concourse/fly/issues/120. Was there a regression since that issue was closed? `fly logout` does not delete the target in `3.14.1`

Steps to reproduce:
1. `fly login -t mytarget`
2. `fly logout -t mytarget`
3. `fly ts`

The target is still listed by `fly ts`.

**Comment by xtremerui** [comment]
I think this is expected as fly logout won't delete the whole target but just clear token

**Comment by jama-pivotal** [comment]
Closing this in favor of #2659
