### ISSUE TITLE
Using fly sync to downgrade from v4.0 to v3.14 invalidates login information

### ISSUE THREAD

**Issue by saedalavinia** [concourse/concourse#2818]
There seems to be a minor backward compatibility issue introduced with the introduction of the new Auth method. 
Using fly v4.0.0, when you use fly sync command to downgrade to v3.14.0, the login information are invalidated and requires relogin. 

So if our build machine has fly v4.0 and our server is v3.14, we need to do something like this: 

```sh 
fly -t <target> login
fly -t <target> sync  
fly -t <target> login  
```

**Comment by jama-pivotal** [comment]
There might be no workaround for this since the auth schemes are different between 3.x and 4.x. Alternatively, you could keep two fly binaries `fly3` and `fly4` to reduce that weirdness

**Comment by marco-m** [comment]
Given that Concourse is now 5.0 and that it doesn't issue maintenance releases, maybe this issue can just be closed.
