### ISSUE TITLE
fly login asks for choosing auth method

### ISSUE THREAD

**Issue by elgohr** [concourse/concourse#2819]
In case you have multiple auth methods configured (e.g. UAA & Basic Auth) fly asks you to choose one and blocks for input since 4.0.0. This also happens when you already provide username and password and makes it unusable for scripting.

```
fly -t x login -n aTeam -c https://my.ci -u userName -p password  
logging in to team 'x'  
1: UAA  
2: Basic Auth  
choose an auth method (2):  
```

**Comment by xtremerui** [comment]
Could not repo this on v4.2.1. Is it possible for you to try this on latest version? Thx.

**Comment by elgohr** [comment]
Same on v4.2.2

**Comment by xtremerui** [comment]
hmm this is what I got
```
fly -t push login -c https://xxxxxx.ci.cf-app.com  -n main -u ci -p xxxxxxx
logging in to team 'main'

1: GitHub
2: Basic Auth
choose an auth method (2): 2


target saved
```
with latest fly and concourse v3.14.1

Just to make sure, after you picked 1 or 2, the stdin input is swallowed and you would have to kill it by ctrl-c ? Does it happen all the time or just occasionally?

**Comment by elgohr** [comment]
The problem is that I have to choose between 1 & 2. How would you automate this selection in a script?

**Comment by xtremerui** [comment]
Can't you just pipe an input to your fly command?

`echo 2 | fly .....` will pick option 2 with non-interactive input

**Comment by elgohr** [comment]
So you consider `echo 2` to be understandable for everybody?
But I will try this as an additional workaround

**Comment by xtremerui** [comment]
I see. This seems like a regression that being broken long time ago (traced back to [v3.14.2](https://github.com/concourse/fly/commit/b470a7d130522711157fdcaad2629ed0fc9fe484) when we worked on adding legacy auth support) so I mistakenly thought it was expected behaviour. It shouldn't ask for input if username and password is provided. 
Thx for reporting!
