### ISSUE TITLE
Feature Request - `fly set-team` should warn against including '/'s in 4.x

### ISSUE THREAD

**Issue by ryanmattcollins** [concourse/concourse#2820]
Due to changes introduced in concourse 4.0, using the old style of separating `org` and `git team` with a `/` no longer works. However, the `fly set-team` command still accepts '/'s.

```
→ fly -v
4.0.1

→ fly -t wings set-team -n cloud-ops --github-team="my-org/old-fashioned-team"  --github-team="my-org:new-relevant-team"
Team Name: some-team

Users:
- none

Groups:
- github:my-org/old-fashioned-team
- github:my-org:new-relevant-team

apply configuration? [yN]: y
team updated

→ fly -t wings teams -d
name              users  groups
some-team    none   github:my-org/old-fashioned-team,github:my-org:new-relevant-team
```

This can be particularly troublesome because if someone had stored their set-team command somewhere and it ran automatically, it could cause them to lose access to their concourse team.

**Comment by pivotal-kahin-ng** [comment]
@ryanmattcollins Would it be helpful to just automatically replace `/` with `:` to avoid running into any issues when scripting `set-team` or do you prefer to have some sort of warning/error/exit so users have to explicitly update/change their configuration?

**Comment by marco-m** [comment]
@pivotal-kahin-ng in my opinion fly should error out in this case, with a clear error message.
