### ISSUE TITLE
Adds stdin support for some fly commands (e.g. set-pipeline configuration)

### ISSUE THREAD

**Issue by loganmzz** [concourse/concourse#2821]
It would be nice if Concourse CLI can read some data from stdin instead of always relying on files.

For example, reading pipeline definition from stdin:

```bash
fly -t local set-pipeline --pipeline hello-world --config - <<EOF
jobs:
- name: hello-world
  plan:
  - task: say Hello World
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: alpine, tag: 3.8 }
      run: { path: echo, args: ['Hello World'] }
EOF
```

**Comment by mattdodge** [comment]
I think stdin support makes sense, beyond the process substitution workaround.

We use [spruce[(https://github.com/geofffranks/spruce) for merging pipeline YMLs and it would be awesome to be able pipe the output of spruce to the `set-pipeline` command of fly.

Propose to have this re-opened.

**Comment by yashbhutwala** [comment]
any updates on this?
