### ISSUE TITLE
Upgrade from 4.0.0 to 4.2.1 results in timeout for any fly command

### ISSUE THREAD

**Issue by jschaul** [concourse/concourse#2824]
## The problem

After upgrading concourse from 4.0.0 to 4.2.1, and after doing a `fly sync` (which was successful), `fly <any command>` causes a `Get https://<url>/api/v1/info: dial tcp: i/o timeout`, even though the ATC is perfectly reachable 1) via browser and 2) via curl:

(<url> denotes an actual URL that I can reach, sanitized for creating this issue)

```sh
curl https://<url>/api/v1/info
```
```json
{"version":"4.2.1","worker_version":"2.1"}
```

## Some details

By downloading previous versions of fly, it is apparent that the problem occurred between `4.0.0` and `4.1.0`:

The following works:

```
curl -Ls https://github.com/concourse/concourse/releases/download/v4.0.0/fly_linux_amd64 > fly400  && chmod +x fly400 && \
./fly400 -t demo login -c 'https://<url>' --verbose
```
(and tells me to sync, see details)
<details>
logging in to team 'main'

2018/09/18 17:52:05 GET /api/v1/info HTTP/1.1
Host: <sanitized>
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

2018/09/18 17:52:06 HTTP/1.1 200 OK
Content-Length: 43
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Tue, 18 Sep 2018 15:52:06 GMT
Pragma: no-cache
Server: nginx
X-Concourse-Version: 4.2.1
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block

{"version":"4.2.1","worker_version":"2.1"}

WARNING:

fly version (4.0.0) is out of sync with the target (4.2.1). to sync up, run the following:
</details>

whereas this fails with a timeout

```
curl -Ls https://github.com/concourse/concourse/releases/download/v4.1.0/fly_linux_amd64 > fly410  && chmod +x fly410 && \
./fly410 -t demo login -c 'https://<url>' --verbose
```
<details>

```
logging in to team 'main'

2018/09/18 18:11:28 GET /api/v1/info HTTP/1.1
Host: <url>
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


could not reach the Concourse server called bridge:

    Get https://<url>/api/v1/info: dial tcp: i/o timeout

is the targeted Concourse running? better go catch it lol
```

</details>

From external, using `<url>:443` (adding the ssl port specifically) does not help.

## Background to our setup

We front concourse with a nginx server accepting only https traffic, which does SSL termination (There is no http->https redirect, for instance - firewalls prevent any incoming traffic other than on port 443)

`./fly421 -t demo login -c 'http://127.0.0.1:8080' --verbose` on the ATC server itself works. 

## Speculation

Is it possible that you ignore the `https` part of the URL and try to make a plain http call? Neither my workstation nor the server/networking has changed (except for an upgraded version of concourse), and none of the concourse/fly versions from 2.x to 4.0.0 had this issue. Any ideas what could have changed between 4.0.0 and 4.1.0 that could be related?

**Comment by xtremerui** [comment]
duplicate to #2740
