### ISSUE TITLE
--cli-artifacts-dir flag not respected

### ISSUE THREAD

**Issue by nbering** [concourse/concourse#2831]
I did a little digging, and found that while the flag appears in `concourse web --help`, it seems it is actually hard-coded to use the OS tmp dir.

I'm not certain that I traced this down correctly, but I am certain it is not being respected.

https://github.com/concourse/bin/blob/0f8248eb03062a20391fb7bb6824bbc91e950993/cmd/concourse/web.go#L44

I originally discovered this due to a permissions issue when I started the service as root first accidentally, and then tried to run again as an unprivileged user. Wouldn't bother me if it isn't fixed, but the help description of the flag is misleading and led me to waste about an hour figuring out why the flag didn't work.

Here's some details about my setup when I found this:
**Installation Method:** Standalone Binary
**OS**: Linux (Debian 8)
**Arch:** amd64
**Release Version:** [v3.8.0](https://github.com/concourse/concourse/releases/tag/v3.8.0)

**Comment by xtremerui** [comment]
This should be fixed in latest version
https://github.com/concourse/concourse/blob/ee3b4cf8b6aa1ae49d5901e6083bc7f84846978e/bin/cmd/concourse/web.go#L46-L48
