### ISSUE TITLE
fly execute does not exit when executing a task yaml

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#2834]
## Bug Report

If I fly execute a task file and I'm unable to pull the docker image (let's say authentication fails). Fly execute does not exit. It also does not respond to SIGTERM.

## Expected Results

If fetching the task image fails then fly execute should exit with an error.

## Actual Results

Terminal hangs

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): docker compose
* Browser (if applicable): N/A
* Did this used to work? I dunno

**Comment by xtremerui** [comment]
This should be fixed in https://github.com/concourse/fly/issues/248

Will be included in next release.
