### ISSUE TITLE
Volumes that exist in baggageclaim but not in the database should be deleted

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#2835]
## Bug Report

On Wings and Prod, we have sometimes noticed live volumes that are not cleaned up for days (were created on Nov 12, still existed on Nov 20) in the worker, but do not exist in the database. This should not happen, but we should account for them when sweeping volumes and add a metric for when this happens again so we can investigate it sooner.

## Steps to Reproduce

There is a snapshot of the broken worker in our gcp project. There should be 19 live volumes in there which do not exist as of right now in the ATC database.

To reproduce the issue, you should be able to start up the worker and a new ATC and see the volumes not being cleaned up.

## Expected Results

These volumes should not exist. The DB is the source of truth and we should check for these 'orphaned' volumes during sweeping and remove them. 

## Actual Results

Orphaned volumes exist in the worker.

## Additional Context

We should also add a metric for when these start to show up, so that we can investigate it and prevent it from happening.

We generally notice this occurrence at the same time as when the worker is experiencing disk usage issues, but that may or may not be related.

Handles of the live orphaned volumes we found: 
```
1054b3ba-1134-424e-7a1f-d07f87ecaeb3
18da9d9c-4007-4c7c-410d-fc1effd97295
1bf0346f-733f-4a1d-7244-cdea459f90e7
1761318b-65c2-4502-56be-58433a178984
2c128a87-a0a5-430f-52cf-b1a971bba748
20e54fde-e7fb-4fde-450f-e78f33b90e4c
129cf80e-a8b8-4b54-6396-ddc308aaae68
333764e7-6aeb-44c9-633d-8e0434893514
15a51999-5b7d-4783-531d-c2433ae6ad23
27d4019a-3190-4aa7-74f7-ea56ffb27680
2666a3af-fb8c-4bd5-7a4e-f0d03315a811
04b1241a-523e-43b6-4576-fbc54efd908d
1c0a065b-ad28-4b60-754b-ff3f3fef3d9c
02274e62-3b09-411f-5a39-cc64023bf9cb
2b64aa3b-b572-401e-6c14-46788e720bc6
190adcc1-60b4-40be-6b3a-9863299d7df0
0e4e0914-713f-4fb6-43ac-61a5617e2df8
15933438-ba6e-4b24-5d97-bf90dcab5765
04e652f1-2b30-4214-5277-09dcd82fbda7
```

* Concourse version:
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by ddadlani** [comment]
FYI to delete these volumes, use the baggageclaim API and not just `rm -rf` the volume folders because that will just remove the data but the volumes will still exist. The API call will delete the volumes using `btrfs` which should delete the volumes as well.

**Comment by kcmannem** [comment]
apparently btrfs needs to be groomed when it grows too much, we need to make sure the next time worker disk usage reaches 50%, that we try a btrfs rebalance.

**Comment by gchenuet** [comment]
We faced the same issue.
We have ~ 250 volumes in DB per workers and ~2500 in workers.
So around 2250 orphans volumes for a period of 2 months.

We created a workaround script to sweep them, running it each night.
We are in 4.2.1 with 3 web and 15 workers and ~ 100 pipelines.

**Comment by samgurtman** [comment]
@gchenuet Could you link the script. Wer'e having the same issue.

**Comment by lrstanley** [comment]
We're at ~1,400 pipelines though with our dev cluster, and 16 fairly beefy workers. Over 4600 volumes total. An example worker with the issue, I see ~253 volumes active, but on the worker I see 592...

Would love to know the API endpoints which delete those worker volumes.. guess I'll have to dig through the source.

I'm just tempted at this point to just recreate the workers every night during non-peak hours.

**Comment by kcmannem** [comment]
@lrstanley We don't expose a user facing endpoint for deleting volumes. The endpoint is listed in `baggageclaim` however you shouldn't be deleting the manually as it will not reflect to concourse's internal system state. Something will break. Could you check `/var/vcap/data/worker/work/volumes/dead` and see volumes are being built up there. They should usually be deleted moments after they are moved into that dir. If you see folders lingering from far before, thats a bad sign and you should recreate the worker. Recreating workers  is the best way to clean up volumes and update concourse system state.

**Comment by lrstanley** [comment]
Can't check now, as I recently recreated the workers, but I'll give it a week or so and see what happens. I'm not seeing btrfs errors logged anywhere though.

> Recreating workers is the best way to clean up volumes and update concourse system state.
There are many things wrong with this statement.

1. There should really be no need to clean up volumes and update concourse system state. Concourse should do this itself.
2. Recreating workers being the 'right thing to do', is just silly. We as operators should not have to shovel the mess left behind by concourse.

**Comment by kcmannem** [comment]
@lrstanley 
1. We're keeping an eye on these edge cases. Our internal deployment hasn't seen this issue for about a month now. Nor have we recreated workers for a month. These errors seemed to subside when we turned on `fewest-build-containers` placement strategy and global-resources. It reduces the amount of containers in general and distributes load better.

2. Agreed.

**Comment by kcmannem** [comment]
Found something interesting on the btrfs cli docs.

```
delete [options] <subvolume> [<subvolume>…]
Delete the subvolume(s) from the filesystem.

If <subvolume> is not a subvolume, btrfs returns an error but continues if there are more arguments to process.

The corresponding directory is removed instantly but the data blocks are removed later in the background. The command returns immediatelly. See btrfs subvolume sync how to wait until the subvolume gets completely removed.

The deletion does not involve full transaction commit by default due to performance reasons. As a consequence, the subvolume may appear again after a crash. Use one of the --commit options to wait until the operation is safely stored on the device.

Options

-c|--commit-after
wait for transaction commit at the end of the operation

-C|--commit-each
wait for transaction commit after deleting each subvolume
```
It looks like theres a risk where btrfs hasn't commited its deletes and crashes. Where from Concourse's view of the world volumes were deleted and Btrfs forgot that a delete had taken place.
We should consider a sync/commit to mitigate this issue.
