### ISSUE TITLE
Dashboard team labels updated to display User Role 

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2843]
In Concourse 4.0 - 4.2.1, the Concourse Dashboard indicates to you whether you are a member of a team or whether the pipelines you are seeing on a team is because of an exposed pipeline:

<img width="1228" alt="screen_shot_2018-11-21_at_1_59_17_pm" src="https://user-images.githubusercontent.com/19274230/48864045-611efc80-ed99-11e8-98a3-f85551724571.png">

# Proposal
With the completion of RBC https://github.com/concourse/rfcs/pull/6 , it would be nice for Concourse now to show you specifically what **role** you have against a team.  Instead of simply `MEMBER` it should show pills for the roles you have on that team e.g. `VIEWER`, `MEMBER`, or `OWNER`. 

# Designs

cc @Lindsayauchin  for design help

**Comment by Lindsayauchin** [comment]
## Proposed Design Updates: 

Add lock icon to represent the private pipelines and the unlocked to represent exposed pipelines on the Pipeline cards. 

Update the 'pill' label for the roles VIEWER, MEMBER, or OWNER.
![screen shot 2018-11-26 at 10 13 01 am](https://user-images.githubusercontent.com/27746614/49022912-02280180-f164-11e8-9a5f-891afdce12b7.png)


## Assets: 
[Lock_assets.zip](https://github.com/concourse/concourse/files/2616099/Lock_assets.zip)

**Comment by Lindsayauchin** [comment]
![screen shot 2018-11-26 at 3 52 48 pm](https://user-images.githubusercontent.com/27746614/49041499-5eeee080-f193-11e8-8569-135954dc9831.png)

**Comment by pivotal-jamie-klassen** [comment]
only show the "biggest" role the user has for each team: e.g. if `/sky/userinfo` reports that a user has both the `owner` and `viewer` roles for team `A`, only show an `owner` pill on that team.

**Comment by pivotal-jamie-klassen** [comment]
In the interest on maintaining a single source of truth about RBAC, we are introducing a change to the `userinfo` endpoint such that the array of roles for each team will be sorted in decreasing order.

**Comment by pivotal-jamie-klassen** [comment]
In previous stories about the order in which to display teams on the dashboard, we had decided to show teams you are a member of first, followed by teams that you are only seeing because of exposed pipelines. We're going to assume here that in this story, the requirement is to sort teams on the dashboard according to your role:
1. `owner`
1. `member`
1. `viewer`
1. teams you are only seeing because of exposed pipelines, or because you are an admin.

@jama-pivotal please complain if this is bad.
