### ISSUE TITLE
Dashboard Exposed Pipeline state should be on the pipeline

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2844]
Starting from Concourse 4.2.0 we started showing `EXPOSED` on teams when you were seeing pipelines/teams because another team exposed that pipeline:

<img width="302" alt="screen shot 2018-11-21 at 2 30 23 pm" src="https://user-images.githubusercontent.com/19274230/48864258-04701180-ed9a-11e8-94fd-a5335c3603f2.png">

This was done so that users can distinguish between pipelines they can access because they are members vs exposed pipelines where they have limited access. 

# Proposal
The enhancement we are proposing is to push the iconography of "exposed" onto the pipeline thumbnail itself. This would help team owners who have already exposed pipelines to visually identify which pipelines have already been exposed

This is somewhat linked to #2843  in that the design changes will be intertwined

# Design

cc @Lindsayauchin for design help

**Comment by Lindsayauchin** [comment]
![screen shot 2018-11-26 at 3 51 06 pm 1](https://user-images.githubusercontent.com/27746614/49044666-78e0f100-f19c-11e8-8aa7-94423679abde.png)
Assets:
[eye_icon.zip](https://github.com/concourse/concourse/files/2617459/eye_icon.zip)

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin currently there are two horizontal dividing lines on a pipeline card -- one near the top between the header and the preview, and the other near the bottom between the  between the footer and the preview. These mockups only show the top dividing line. Should we remove the lower dividing line as part of this story?

**Comment by Lindsayauchin** [comment]
my mistake! I was using an older mock. Updated the screen to our changes made as per our conversation with James. 

![screen shot 2018-11-28 at 4 55 59 pm](https://user-images.githubusercontent.com/27746614/49184915-89c16c00-f32e-11e8-992b-25e83853c824.png)
