### ISSUE TITLE
Owners and Members should be able to Pause/Resume their Pipelines from the Pipeline view

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2847]
With the removal of the sidebar in Concourse 4.x, users have lost the ability to Pause or Resume their pipeline from the pipeline view. 

In the past, a user would be able to open the sidebar, find their pipeline name and use the play/pause buttons to pause/resume their pipelines. This is no longer possible and the user must now go back in their browser, find their pipeline on the dashboard and pause/resume their pipeline. That's pretty annoying

# Proposal
We introduce the Play/Pause buttons on the pipeline view so users can get this functionality back

# Design

cc @Lindsayauchin for Design help

**Comment by Lindsayauchin** [comment]
![screen shot 2018-12-05 at 5 02 44 pm](https://user-images.githubusercontent.com/27746614/49547068-c3a2ed00-f8af-11e8-8fcd-9295fee8cede.png)
![screen shot 2018-12-05 at 5 02 35 pm](https://user-images.githubusercontent.com/27746614/49547069-c43b8380-f8af-11e8-87b4-4fe0a7359199.png)
