### ISSUE TITLE
Dashboard "zoom"

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2848]
The Concourse Dashboard in 4.x has two "views": normal thumbnail view and HD view. As our userbase trends towards having even MORE teams on their Concourse, even the HD view might not be good enough for finding teams. We basically need a list mode

# Proposal
Zoom is probably the worst way to describe this proposed feature but it would be interesting to experiment with a new way of viewing team/pipeline data using the "zoom" as a metaphor. Instead of a binary toggle for HD mode, we instead have a slider that lets you change the resolution of details; kinda like google photos. The three scales I'm imagining for now are:

* Thumbnails
* HD view
* List view

# Design

cc @Lindsayauchin

**Comment by Lindsayauchin** [comment]
Closing this in favour of a new RFC to allow users to customize the Dashboard view/CI Monitor.  #4782
