### ISSUE TITLE
topgun/k8s: Scaling a multiple ATC setup

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#2851]
**Acceptance Criteria**

- Start with one instance and scale to two instances while ensuring that you can target the new instance.

**Comment by cirocosta** [comment]
Hey,

An update on this - given that we already have a test related to scaling down (`topgun/atc_shutdown_test`) and `topgun/k8s/rebalance` is already testing the case where we have multiple atcs w/ workers rebalancing between them, I'd say that we'll end up having the end goal of covering "scaling a multiple ATC setup covered" once we bring those generic tests.

Does anyone feel like this is not the case?

Thx!

**Comment by jama22** [comment]
Was this issue for testing how to scale multiple ATCs on helm, or documenting it @scottietremendous or @cirocosta

**Comment by cirocosta** [comment]
Hey @jama22 , this one, in particular, is about putting a test on it
