### ISSUE TITLE
Pipeline Name in the breadcrumb to be used a a way to navigate to other pipelines

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2853]
With the elimination of the sidebar in 4.0 and the subsequent requests to [bring it back](https://store.steampowered.com/app/637090/) we've been thinking a lot about how to reproduce a lot of the same functionality. In addition to giving you the option to pause/resume the pipeline from the pipeline view #2847 a lot of users need to jump around to different pipelines without having to go back through the heavy Dashboard

# Proposal
We can use the breadcrumb element to maybe introduce a dropdown where users can do a quick switch into another pipeline. This might be a horrendous idea for Concourse installations with terribly long lists of teams though

# Design

cc @Lindsayauchin

**Comment by jpluscplusm** [comment]
How about being able to access the dashboard's search box from both a pipeline view and a job view? I don't think `/` is aliased to anything on those screens, yet ... :-)

**Comment by Lindsayauchin** [comment]
Closing in favour of Omnisearch story #3630
