### ISSUE TITLE
Expand search to be available app-wide, with a stronger search syntax

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2855]
# Proposal
Similar to #2853 , It would be interesting to let users jump around resources without having to back out onto the pipeline and jump into another resource. 

# Design

cc @Lindsayauchin

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen @jama22 @mcwumbly

Would a dropdown from the breadcrumbs as a secondary navigation help? The list of resources could get very, very, long. We would need to add an overflow scroll to really long resource lists. (see example below) But, we should try it as an experiment. Thoughts?

## Proposal 

### Hover Resource Page
![screen shot 2019-02-12 at 9 35 31 am](https://user-images.githubusercontent.com/27746614/52642741-983d0f80-2ea9-11e9-8f9c-f8227ebf9df7.png)

### Selected Resource Page
![screen shot 2019-02-12 at 10 32 30 am](https://user-images.githubusercontent.com/27746614/52646865-9119ff80-2eb1-11e9-8300-2df8ba8502df.png)

**Comment by Lindsayauchin** [comment]
After some debate on the floor here there is a second proposal to introduce a fuzzy search to the pipeline page and resource page in a similar pattern that github uses. 

We could introduce a fuzzy search that lives before the breadcrumbs indicated by a '/'. Similar to git we could invoke the search with '/'  or selection by cursor. The dropdown would expand and take over the area where the breadcrumb now lives. The user could then fuzzy search to navigate to pipelines in their instance or resources. List of results displayed below the input. 

### collapsed
![screen shot 2019-02-12 at 2 10 20 pm](https://user-images.githubusercontent.com/27746614/52661481-2af0a500-2ed0-11e9-9b6e-8f5590925cd3.png)

### expanded 
![screen shot 2019-02-12 at 2 13 53 pm](https://user-images.githubusercontent.com/27746614/52661692-9470b380-2ed0-11e9-80ae-25996cacacd5.png)

**Comment by Lindsayauchin** [comment]
This issue has two separate design ideas, so I'm closing this in favor of a new issue that just focuses on omni search
