### ISSUE TITLE
Toggling high density causes the entire screen to flickr

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#2857]
## Steps to Reproduce

I have a single pipeline with one task. In the dashboard view toggling high density causes the screen the flicker.

## Expected Results

It does not flicker and the transition isn't so abrupt.

## Actual Results

It flickers and the transition is abrupt.

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Docker Compose
* Browser (if applicable): Version 70.0.3538.102 (Official Build) (64-bit)
* Did this used to work? I dunno

**Comment by pivotal-jamie-klassen** [comment]
at present switching between dashboard and HD is implemented via clicking a link to a different route -- this tends to imply a page reload. We certainly could achieve the desired effect, but I would think that the 'Expected' behaviour is for a page to reload if your URL changes. so maybe a feature, not a bug?

**Comment by dprotaso** [comment]
I'd agree with your counter argument

**Comment by pivotal-jamie-klassen** [comment]
After the refactoring leading up to #2881 this should be pretty easy

**Comment by dprotaso** [comment]
Famous last words?
