### ISSUE TITLE
unpause pipeline in pipeline view

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#2859]
I'm finding I'd like to pause and unpause my pipeline from the pipeline view.

ie. from the page http://127.0.0.1:8080/teams/main/pipelines/[some-pipeline]

It's a bit taxing to go back to the dashboard and then back to the pipeline. Doing this also loses my previous view (if I where zoomed in)'

Concourse 4.2.1 via docker-compose

**Comment by jama-pivotal** [comment]
Thanks for the feedback! Closing in favour of #2847 since it has a bit more details
