### ISSUE TITLE
Update worker README with information about its dependencies

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#2860]
## What challenge are you facing?

A newcomer looking at the `./worker` package might not quickly realize where they should look for the actual implementations of either the baggageclaim or garden API.

e.g., we had under `concourse-bosh-release`:

```
* [Garden](https://github.com/cloudfoundry-incubator/garden) is a generic
  interface for orchestrating containers remotely on a worker
* [Baggageclaim](https://github.com/concourse/baggageclaim) is a server for
  managing caches and artifacts on the workers
```

although it makes more sense to have it under `./worker`.

## What would make this better?

Include in `./worker/README.md` a description of each of the possible implementations that are usually used as implementations of the Garden API (e.g., guardian and houdini), as well as a reference to Baggageclaim. 

## Are you interested in implementing this yourself?

yess 🙌

**Comment by sundeepk1** [comment]
Hi 

I would like to implement this update. Kindly let me know where to find the information to update it in the readme file.
