### ISSUE TITLE
Mock resource check fails sporadically

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#2861]
## Steps to Reproduce

I configured a mock resource with no special parameters

## Expected Results

It returns a single version `mock`

```
- name: some-mock
  type: mock-resource
```

## Actual Results

It returned a single version mock but then subsequent check failed

```
Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:348: starting container process caused \"process_linux.go:90: adding pid 53055 to cgroups caused \\\"failed to write 53055 to cgroup.procs: write /sys/fs/cgroup/cpu/garden/fe571cbe-0abd-47a5-7258-a24f22b6df3f/cgroup.procs: invalid argument\\\"\"\n","Handle":"","ProcessID":"","Binary":""}
```

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): docker compose

**Comment by ralekseenkov** [comment]
We have seen this on Azure. Likely related to the old version of Docker.

**Comment by topherbullock** [comment]
Will leave this open to check on when we bump Garden.

@dprotaso Which garden version is the worker this happens on using? Are you able to narrow down anything novel about it happening sporadically? ie. is it just one specific worker?

**Comment by dprotaso** [comment]
I’m just using the default docker compose repo
