### ISSUE TITLE
pipeline view viewport 'jumps' unexpectedly

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#2862]
## Steps to Reproduce

1. View some really tall pipeline (larger than your screen)
2. Navigate into a job
3. Navigate out of a job
4. Try to move the pipeline with your mouse

## Expected Results

The pipeline's view remains when navigating back from a job. Moving the pipeline does not cause it to 'jump' abruptly

## Actual Results

Sometimes the pipeline 'tries' to centre itself vertically when moving back to the pipeline view. Then when moving the pipeline it moves from it's original position.

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Docker Compose
* Browser (if applicable): Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by jama-pivotal** [comment]
Interesting, looks like this is actually a regression of #1532. Its definitely an annoying one
