### ISSUE TITLE
Allow users to unpin a resource version from the top bar in Concourse 5.0.0 

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#2870]
Within the 5.0.0 release, pausing of resources will be removed and replaced with a pinned resource to the most recent version. When a user upgrades to 5.0, we want to ensure that their paused resources do not get checked (for cases where users that paused their resource in order to make sure that certain jobs do not get triggered) by pinning the previously paused resource to the latest version before the migration. This will mean that the `api_pinned_version` column will contain the latest version of the resource after the migration, but no versions would exist yet within the `resource_config_versions` table. In the case where the resource is unique (meaning that the resource is the only one pointing to a specific resource config), the resource config will never be checked. Currently, the only way to unpin a version is to click on the unpin button on that specific resource version, and in this case where no versions will ever exist there will be no way to unpin the resource.

There are a few proposals:
- Display a message saying something along the lines of "There are no versions for this resource but if you want to unpin it, use `fly unpin-resource`. Also we would need to add a `fly unpin-resource`.
- Add a button to the pin-bar for unpinning the resource no matter if the version exists
- **For the future**: Add a "concourse" comment says a message about using fly unpin resource to un pin this version (this relies on the commenting on pinning versions issue to be finished)

**Comment by jama-pivotal** [comment]
Cross-referencing to the UX and Design backlogs. After some discussion we agree that pinning the paused resource is the best recourse for the upgrade. This leaves the question of what the best way to communicate to users that we did this.

We are leaning towards doing pin messaging, where we would default the pin action with a "system user" message saying "hey, we pinned this for you as a part of upgrading". This has the side effect of us implementing the first version of resource commenting..

cc @Lindsayauchin for design help!

**Comment by pivotal-jamie-klassen** [comment]
while we're at it, this might be a good time for the resource endpoint to return the version ID of the pinned version, not just its value. There is a potential bug in the current version of the code where if a resource has multiple identical versions, the resource page could show the wrong thing.

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin I'm going to assume that showing a pointer cursor when mousing over the active pin bar is enough indication that it has an associated action -- starting this story now, but if you decide you want some more obvious hover state let me know.

**Comment by Lindsayauchin** [comment]
Pointer cursor is great. Could we add a darker background behind the pin icon to the hover state?
<img width="660" alt="screen shot 2018-11-28 at 12 39 05 pm" src="https://user-images.githubusercontent.com/27746614/49170656-a0ee6280-f30a-11e8-9baf-8ccaa03efa5b.png">
<img width="348" alt="screen shot 2018-11-28 at 12 38 46 pm" src="https://user-images.githubusercontent.com/27746614/49170663-a64bad00-f30a-11e8-902d-63cf3ec8dfaa.png">
