### ISSUE TITLE
Pipeline search is broken

### ISSUE THREAD

**Issue by antonu17** [concourse/concourse#2872]
## Bug Report

When the dashboard page gets loaded there is an error in console:

``` javascript
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at Array.<anonymous> ((index):75)
    at Function.onEffects [as func] (elm.min.js?id=18701b041d48f77c150ba19dedd849da:1)
    at A3 (elm.min.js?id=18701b041d48f77c150ba19dedd849da:1)
    at onMessage (elm.min.js?id=18701b041d48f77c150ba19dedd849da:1)
    at Object.callback (elm.min.js?id=18701b041d48f77c150ba19dedd849da:1)
    at step (elm.min.js?id=18701b041d48f77c150ba19dedd849da:1)
    at work (elm.min.js?id=18701b041d48f77c150ba19dedd849da:1)
```
And pipeline search doesn't work. This happens occasionally, I can't provide more information at the moment.

## Version Info

* Concourse version: 4.2.1
* Deployment type: Docker
* Browser: Google Chrome 70.0.3538.77 (Official Build) (64-bit)

**Comment by jama-pivotal** [comment]
Hrm, I havent been able to reproduce this in my local dev instance

**Comment by xtremerui** [comment]
Can't reproduce this on exact same chrome version. Do you have any pipeline with long name that got truncated in this case? Since `offsetWidth` is used for tooltip of truncated pipeline name.

**Comment by antonu17** [comment]
Hi @jama-pivotal, @xtremerui.
I've collected more data on the issue.

### Cluster size

We have 45 teams and 250 pipelines on our concourse cluster. And our main requirement is that developers should have access to all teams. So all our concourse teams were created with `fly set-team --allow-all-users`. Now, when one open dashboard they see 250 pipelines, which takes 3-5 seconds to be fetched and rendered.

### How to reproduce the error

The error `Cannot read property 'offsetWidth' of undefined` mentioned in the first message, is thrown if you hover any pipeline box on the dashboard. After the error thrown search stops working, but if you manage to safe mouse pointer form pipeline box hovering, search works.

### Possible solutions

I'm not sure about the original problem fix, but I would be cool if there was a team filter on the dashboard and dashboard shows only selected teams. It should reduce size of api payload fetching from API, if API supports this sort of fitering, of course.

**Comment by xtremerui** [comment]
@antonu17 There might be some race conditions there when dashboard takes long time to load. Thx for the context, will try set up couple hundreds of pipelines to reproduce it.

For a "team filter", for a temporary solution you can append`search` param in your url when open dashboard. Then it will filter pipelines by team, which should reduce the rendering time (unfortunately data fetching time is still the same). For example, if you want to filter by `team-1` 
the url would be
```
https://your-concourse-url/?search=team%3Ateam-1
```

**Comment by aleksandrzhiliaev** [comment]
Hi @jama-pivotal , @xtremerui 
I am working in the same company as @antonu17.

Here are our chrome stats on the main page:
![screen shot 2018-12-04 at 3 48 50 pm](https://user-images.githubusercontent.com/12209346/49449929-45294b00-f7dc-11e8-8180-d9a0888f8700.png)

As you can see browser calls `/jobs` endpoint periodically and jobs payload is 1.6 MB
Right now we have 280 pipelines and it is impossible to use the dashboard and do search on it.

Maybe we can configure dashboard and leave only search form with loaded teams on it, or maybe we can hide all that green-red "boxes" on main dashboard, wdyt?

**Comment by xtremerui** [comment]
It is definitely in our radar here https://github.com/concourse/concourse/issues/2644 and here https://github.com/concourse/concourse/issues/2776

**Comment by antonu17** [comment]
> @antonu17 There might be some race conditions there when dashboard takes long time to load. Thx for the context, will try set up couple hundreds of pipelines to reproduce it.
> 
> For a "team filter", for a temporary solution you can append`search` param in your url when open dashboard. Then it will filter pipelines by team, which should reduce the rendering time (unfortunately data fetching time is still the same). For example, if you want to filter by `team-1`
> the url would be
> 
> ```
> https://your-concourse-url/?search=team%3Ateam-1
> ```

Hey @xtremerui,

this is exactly how we open a dashboard so far. But the problem is, even if you open only one team using search parameter, it still `Cannot read property 'offsetWidth' of undefined` on mouse over. And after all, when a user clicks on the concourse logo at the top left (which they always do) it opens the whole dashboard again :smiley:
Also, pause/unpause doesn't work after this exception thrown. Given that it gets thrown when mouse hovers pipeline box, the only way to pause/unpause is `fly`.

**Comment by antonu17** [comment]
Ok people. I've found why this exception gets thrown. This comes from jQuery, actually. We have teams with the "." (dot) symbol in the name. And this renders as `<div id="team.name">` and jQuery can't find it here https://github.com/concourse/concourse/blob/fcb16b75af076d85985c82e8b8cd789f85c546e5/web/public/index.html#L113-L118
If we replace all `.` in the `pipelineTeamName` with `\\.` it will work.

**Comment by RTodorov** [comment]
Hey @xtremerui, what do you think about https://github.com/concourse/concourse/pull/2915? merging it would be of a great help for us, our users are complaining a lot about search not working, even after loading the 2mb+ payload.

Thanks for your input.
