### ISSUE TITLE
Status bar doesn't stick to the bottom at mobile resolution

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#2878]
Bottom bar on multi pipeline page isn't at the bottom when I shrink the window

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): 
* Infrastructure/IaaS: BOSH
* Browser (if applicable): Chrome Version 70.0.3538.110 (Official Build) (64-bit)
* Did this used to work?

![screen shot 2018-11-28 at 11 24 27 am](https://user-images.githubusercontent.com/18562/49165876-30dadf00-f300-11e8-96f9-52260ee4f647.png)

**Comment by jama22** [comment]
We actually fixed this recently and it will appear in the Concourse 5.0.0 release. If you'd like to check out the fix in action hop on over to https://ci.concourse-ci.org/
<img width="497" alt="screen shot 2019-01-20 at 10 58 20 pm" src="https://user-images.githubusercontent.com/19274230/51452183-e590eb80-1d06-11e9-8427-06766ed8f903.png">

**Comment by dprotaso** [comment]
@jama22 On 5.0.0 I see the status bar disappear and never come back.

Chrome iOS Version:  71.0.3578.89

**Comment by pivotal-jamie-klassen** [comment]
@dprotaso on Android chrome or disappears after 5 seconds but reappears if I tap on the background - would you say you expect the legend to reappear when scrolling?

**Comment by pivotal-jamie-klassen** [comment]
Potentially related is #2914

**Comment by dprotaso** [comment]
@pivotal-jamie-klassen feel free to close this issue and make a new one.
