### ISSUE TITLE
Users should be able to see teams they belong to on the dashboard with no pipelines set

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2881]
Concourse shows me the `No Pipelines set` screen when I am logged into concourse and none of my teams have pipelines set.

For example, consider that I am logged in as `Member1` and I belong to two teams `Team1` and `Team2` with no pipelines yet. When I log in I get:

![screen shot 2018-11-28 at 11 06 28 am](https://user-images.githubusercontent.com/19274230/49174963-7fdf3f00-f315-11e8-852d-f805f1936f67.png)

The moment I set a pipeline on `Team2` I see:
![screen shot 2018-11-28 at 11 09 14 am](https://user-images.githubusercontent.com/19274230/49175021-a309ee80-f315-11e8-8323-355110357246.png)

# Proposal
The lazy solution would be to repeat the second screenshot and have all teams report `no pipelines found`. But I think we can do better and use the `No Pipelines Found, pls download fly` screen to list team names that you have the option of working against

cc @Lindsayauchin

**Comment by Lindsayauchin** [comment]
## Updated Design: 

![screen shot 2018-12-03 at 10 30 11 am](https://user-images.githubusercontent.com/27746614/49383328-77588100-f6e6-11e8-9aec-cb6863317002.png)

![screen shot 2018-12-03 at 10 31 01 am](https://user-images.githubusercontent.com/27746614/49383363-8f300500-f6e6-11e8-844b-2e8ec4aaaed9.png)

**Comment by Lindsayauchin** [comment]
![dashboard_empty_state_member1_no-pipelines](https://user-images.githubusercontent.com/27746614/49654468-e0e9cf80-fa05-11e8-8e81-62f8a3ed3284.png)

**Comment by jama-pivotal** [comment]
text should actually read `fly set-pipeline` in that mock.

**Comment by Lindsayauchin** [comment]
![dashboard_empty_state_login_welcome](https://user-images.githubusercontent.com/27746614/49760866-7f3e9500-fc93-11e8-837a-34908e1787a9.jpg)

**Comment by Lindsayauchin** [comment]
![animation_start_screen](https://user-images.githubusercontent.com/27746614/49811613-9e8bff80-fd31-11e8-8c53-cc94072618a1.gif)

**Airplane svg asset**
[airplanes_welcome_ascii.svg.zip](https://github.com/concourse/concourse/files/2668243/airplanes_welcome_ascii.svg.zip)

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin @jama-pivotal how about the high-density view?

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin it seems like the big card has a background color that is ever-so-slightly lighter than the pipeline cards. is it ok to use the same color as the pipeline cards?

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen good catch! Somehow I let an old Isoveka font sneak in there. 

![screen shot 2018-12-11 at 4 58 53 pm](https://user-images.githubusercontent.com/27746614/49833006-3e638080-fd66-11e8-82bd-abbeba0e1813.png)

- [ ] "welcome to concourse!" is 32 px
- [ ] body copy is 12 px

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen Can we disable the legend until a pipeline is set? 
So, that there is no path for a user to get to that view until they set pipeline and the legend is then visible? What do you think?

![dashboard_empty_state_member1_no-pipelines](https://user-images.githubusercontent.com/27746614/49833262-f98c1980-fd66-11e8-9822-583520ff6e81.png)

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin i think that's a good idea from an implementation perspective (it lets us reuse some of the `Hover` messages), and it has good design sense because none of the pipeline status indicators will be on the page when there are no pipelines anyway, but people can still navigate directly to `/hd`.

It's not hard to just show this view even if they navigate to `/hd`, if that's really what we want. I guess that's the real question.

PS. While it may make sense not to show the legend, I wouldn't be totally sure we don't want to show the bottom bar at all -- like it *might* still be useful to see the concourse version in the bottom right, but I wouldn't really defend that.

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin @jama-pivotal also want to confirm that the plan is not to show the search bar when the page is in this state? Consequently I would think you can't filter the list of (empty) teams.

**Comment by pivotal-jamie-klassen** [comment]
* remove legend from bottom bar and align info section to the right
* when there are no pipelines, redirect requests to `/hd` back to `/`.

**Comment by pivotal-jamie-klassen** [comment]
[CLI_logos.zip](https://github.com/concourse/concourse/files/2672847/CLI_logos.zip)

**Comment by Lindsayauchin** [comment]
## For animated airplane art
Link to ascii generator: http://picascii.com/
Original plane art: [planes.png.zip](https://github.com/concourse/concourse/files/2672884/planes.png.zip)

**Comment by pivotal-jamie-klassen** [comment]
'welcome to concourse!' - 32px font
'first download...' - 16px font
CLI icons are 32px square
card height is 200px

**Comment by pivotal-jamie-klassen** [comment]
One last narrowing of the scope: the animated background belongs in a separate issue.
