### ISSUE TITLE
Logging out from a Concourse with no exposed pipelines takes you to a "no search results found" page

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2884]
Logging out from a Concourse with no exposed pipelines takes you to a "no search results found" page. 

**Steps to reproduce**
1. Load up a new concourse
2. Login as a user
3. Logout

**Expected**
For consistency it should at least take you back to the no pipelines configured page
![screen shot 2018-11-28 at 11 06 28 am](https://user-images.githubusercontent.com/19274230/49182982-b3c45f80-f329-11e8-8f9a-554ba568084f.png)

**Actual**
You are taken to the no search results page. Also, the URL itself is for the homepage (in this case http://localhost:8080/) 

![screen shot 2018-11-28 at 4 22 35 pm](https://user-images.githubusercontent.com/19274230/49183035-d5bde200-f329-11e8-87b0-702f43ae4711.png)

**Comment by jama-pivotal** [comment]
minor nit-pick, after logging out now I'm taken to a blank state, but I would have expected to see the `no pipelines configured` state

**Comment by vito** [comment]
(Asked @pivotal-jamie-klassen and he thinks not - gonna stamp it with `unreleased`.)
