### ISSUE TITLE
Navigating issue - ?search=team%3A%20teamname before main screen is loaded

### ISSUE THREAD

**Issue by drduker** [concourse/concourse#2888]
## Bug Report
Navigating issue - Screen will not load if you move quickly to load a team after going back to the main screen.
?search=team%3A%20teamname before main screen is loaded causes nothing to load on screen.

Hitting refresh/reload on the page with the additional search url string "?search=team%3A%20teamname" do not resolve.

## Steps to Reproduce
Drill down to a team and then to a job within a team.  Drill down to a step within the job.
Then click back to the job to see the job overview.
Then click on the fan icon on the top left to go back to the main screen.
Within a couple of seconds or less, click on the search field and select the team that you want to use.
If you select the team which places "?search=team%3A%20teamname" after your url **BEFORE** the main screen loads all team content (assuming you have access to multiple teams), then it will just be stuck and not load anything below.

**How you have to fix it:**
Log out and log back in.
Remove everything after the main url and reload the page.

## Expected Results
I would expect that if I work faster than the page to load that it would eventually load my team search that I have selected.
## Actual Results
Nothing loads.

## Version Info
* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome - latest
* Did this used to work? not since upgrading to 4 no - because version 4 implements teams

**Comment by jama22** [comment]
Added a needs-investigation because we should try to see if we can repro it in Concourse 5.x before digging deeper. We did a lot of refactoring for this release so it might be "fixed"
