### ISSUE TITLE
Document how to use custom Resource types

### ISSUE THREAD

**Issue by afeld** [concourse/concourse#289]
I'll preface this issue by saying that I'm very new to Concourse and BOSH.

There is a guide about [how to implement a Resource](https://concourse.ci/implementing-resources.html) and a list of [Unsupported Community Resources](http://concourse.ci/resources.html), but (from what I can tell) there aren't any instructions about how to use one of these custom Resource types. Would be very helpful for us newbies!

**Comment by vito** [comment]
We'll be making this easier very soon - keep an eye on https://github.com/concourse/concourse/issues/250. We'll be sure to document that approach it once that lands.

**Comment by allomov** [comment]
@afeld you can follow instructions from [this README](https://github.com/starkandwayne/flowdock-concourse-notification-resource#concourse-testing) to build resource as a docker image and then make concourse use it as a custom resource. Upcoming `resource_types` feature is going to greatly ease this process.

**Comment by afeld** [comment]
:tada: http://concourse.ci/configuring-resource-types.html

**Comment by elementsweb** [comment]
I've been developing custom resource types for a while, I ended up building a Yeoman generator to make the process easier for me. See https://github.com/elementsweb/generator-concourse-resource to see how the generator can help you.
