### ISSUE TITLE
Visualization of Job and Task result hooks

### ISSUE THREAD

**Issue by osis** [concourse/concourse#2890]
## Bug Report

It's hard to visually distinguish the difference between Task and Job result hooks.

## Expected Results

Would think the Job hooks shouldn't be indented the same as the Task hooks? @Lindsayauchin, what do you think?

## Actual Results

https://ci.concourse-ci.org/teams/examples/pipelines/hooks/jobs/job/builds/4

<img width="757" alt="screen shot 2018-11-30 at 1 48 33 pm" src="https://user-images.githubusercontent.com/347097/49308583-af718100-f4a6-11e8-8ee2-e385ccc3dab7.png">

## Version Info

* Concourse version: 4.2.2
* Browser (if applicable): Chrome Canary Version 72.0.3625.0 (Official Build) canary (64-bit)
* Did this used to work? I'm not sure.

**Comment by osis** [comment]
Added a photo since that pipeline isn't accessible yet. cc/ @pivotal-jamie-klassen

**Comment by osis** [comment]
Better picture...

<img width="700" alt="screen shot 2018-11-30 at 2 35 33 pm" src="https://user-images.githubusercontent.com/347097/49310800-5ce79300-f4ad-11e8-9518-664d4ced4e6d.png">

**Comment by osis** [comment]
@Lindsayauchin should we kill this?

**Comment by vito** [comment]
I'll put this in the 'build page redesign' epic since I just put https://github.com/concourse/concourse/issues/2890 there which is general feedback about how steps are rendered, though we might break it out into a separate epic later on.
