### ISSUE TITLE
Develop/contributor documentation?

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#29]
I don't see any documentation aimed at developers and contributors. Maybe I'm missing something that already exists, maybe it doesn't exist yet. Either way it would be helpful to link to it from the README.

What I'm looking to see is something like the following:

- How can I validate that a deployment of concourse bosh-release runs fine against e.g. bosh-lite.
 - Are there are acceptance/end-to-end tests, perhaps against a bosh deployment?
 - How should I run tests against concourse submodules without running the tests against all the dependencies?
- What is my development workflow?
 - What external, non-golang dependencies do I need to install and/or configure? For example I've already identified that ATC requires postgres and phantomjs
 - What (if any) githooks should I set up?
 - What scripts should I run before commiting
 - Should I run some/all tests in a docker container? I see various docker files, what are they all for?

**Comment by vito** [comment]
Thanks, added a story to track this:

https://www.pivotaltracker.com/story/show/93750718

In the short-term, here's the tl;dr:

* PRs go to develop branch of release repo, master of individual components (ATC/etc.)
* To run testflight, create and upload the release to BOSH-Lite, and then run `./scripts/local-test` from the testflight repo. You'll also need a garden-linux release uploaded, which you can grab from [bosh.io](http://bosh.io/releases/github.com/cloudfoundry-incubator/garden-linux-release)
* The release repo is your `$GOPATH`; the `.envrc` file will automate it via direnv

**Comment by robdimsdale** [comment]
Great thanks, that's really helpful.

**Comment by zachgersh** [comment]
PR - open for this now over at #37
