### ISSUE TITLE
Bring back a pruned worker

### ISSUE THREAD

**Issue by pivotal-saman-alvi** [concourse/concourse#2901]
## What challenge are you facing?
When `prune-worker` is done and a worker is removed due to potential issues, it would be useful to have a way to bring it back. Similar to how `bosh` will allow you to temporarily `ignore` and then `unignore` vms.. This could let you isolate problematic workers for a period of time, without involving `bosh`, and let the control happen from `concourse` itself.

## What would make this better?
`fly -t unprune worker` potentially?

## Are you interested in implementing this yourself?
Yes (Concourse)

**Comment by marco-m** [comment]
My 2 cents: the effect of pruning a worker has a clear meaning, it cannot be undone. I looks to me, as @cirocosta mentions, that the final goal can be achieved with the concept of cordoned worker.
