### ISSUE TITLE
Clicking on exposed "eye' to toggle pipeline exposure

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2903]
With the completion of #2844 and the "eye" icon beside the actionable "play/pause" buttons, most users will probably expect that button to be click-able. We should do that.

Specifically:
- [x] When clicking on the exposed pipeline (filled eye) the user will be hiding the pipeline (effectively doing a `fly hide-pipeline`
- [x] When clicking on a hidden pipeline (eye with \) the user will be exposing the pipeline (doing a `fly expose-pipeline`)
- [x] Only Owners and Members should be allowed to execute this action
- [x] If a Viewer tries to click on it nothing will happen

**Comment by Lindsayauchin** [comment]
Can we add a tooltip to this to explicitly tell the user the implications if they take action on this icon? 

<img width="593" alt="Screen Shot 2019-03-18 at 6 09 36 PM" src="https://user-images.githubusercontent.com/27746614/54567069-05602b00-49a9-11e9-8901-23d98734760f.png">
