### ISSUE TITLE
multi-object build advice

### ISSUE THREAD

**Issue by afeld** [concourse/concourse#292]
I'm relatively new to Concourse, so am looking for some advice about how to structure certain types of pipelines. Of the pipelines and resource types I've seen, they all seem to be centered around a set of tasks for a single "thing", where that "thing" is usually a repository. I'm interested in using Concourse to do somewhat broader tasks, where there are multiple "things" that are being run through a single pipeline. Some concrete examples:

* Get the list of repositories from our GitHub org, run some scan on each of them (e.g. checking for a `LICENSE.md`), then open and issue/pull to the corresponding repository if missing.
* Get a list of domains we control from an API, then check to make sure each responds with a 200 and passes a vulnerability scan, upload the results to S3, then send a notification to the corresponding project team on any failures.

I see a couple of ways of going about these:

* Cram all of the functionality into a loop in a script in a task
    * Presumably the overall build should pass regardless of whether there were failures on the individual repositories/domains?
    * The existing [built-in resource types](http://concourse.ci/resources.html#section_what-types-are-supported) only let you fetch/create one thing (repository, S3 file, etc.). Seems like using/making a custom resource that accepts/returns multiple objects is the "right" thing to do?
* Use parameterized pipelines for checking a single domain/repository, and automatically create a pipeline corresponding to each
    * This would make the list of pipelines veeery long.

Neither seems _quite_ right...any advice? Feel free to close this if you want to keep the open issues limited to bugs/features.

/cc @linuxbozo @davidebest @adrianwebb @dlapiduz

**Comment by challiwill** [comment]
Hi,

So you may want to wait for @vito or @xoebus's input, but my initial reaction would be to create a custom resource that deals with data as is necessary for your case.

I don't see a beautiful implementation right now for you, but thinking about the second example here: 

The definition for success/failure of a build would be up to you depending on what you want the job to reflect. If you want it to reflect that it's notifying the appropriate teams successfully then you wouldn't want it to fail if a domain is unreachable or vulnerable. However if you want it to reflect that the domains are secure and reachable then you'd want to make the job fail. 

In terms of implementation  you could imagine a resource who's `get` corresponds to getting a list of domains, and returns a file to you with that list. Then you'd have a task that would ping each domain and places the failures in a new file `unreachable-or-vulnerable-domains` which is specified as an output. A `put` would send that to S3. A second task could go through the file and notify the appropriate teams. That could also be a second job. 

This would require loops in the script as you suggested, but should just be a simple loop making one pass through a file.

**Comment by afeld** [comment]
That all makes sense...just a shame that I wouldn't be able to make use of the existing resource types (`git`, `s3`, etc.)

**Comment by robdimsdale** [comment]
@afeld you can create a custom resource that utilizes other resources - you'd essentially add the binaries for those resources to the rootfs (docker image) of your resource, and then shell out to them.

We did this in the [pivnet-resource](https://github.com/pivotal-cf-experimental/pivnet-resource/blob/master/s3/s3_client.go#L76-L101) where we shell out to the s3-resource multiple times to upload multiple files.

As far as your actual question, I'd probably consider some combination of custom resources and tasks to glue them together. For example, your first example sounds like you want a github resource:
- `get` the repo with the normal git resource
- a task that checks for license
 - on that task's failure, you would `put` to the github resource

This doesn't answer the question of scaling horizontally - how do I run the above sequence on all repos? I would suggest that you keep the mapping one-to-one (i.e. one repo -> missing license -> one PR to that repo), and not try to create a custom resource that aggregates over many repos. This feels more aligned with what concourse resources are intended to represent.

I might solve the scaling problem with one pipeline that has many jobs and resources. If the list of repositories doesn't change too frequently, update that pipeline by hand. If it's changing quickly, I would write a tool that generates the pipeline for you based on the list of repositories.

**Comment by mmb** [comment]
We have a similar situation where we want the resource to see all versions in the "in". The use case is also scanning and we need to scan every version, not just the latest one in a batch.

We currently work around this in our resource by the check script combining multiple versions into a single version and the in script breaking it apart again.

/cc @mandyozhao

**Comment by robdimsdale** [comment]
@afeld we are starting to see more people want to solve similar issues of task-composability and reuse - https://github.com/concourse/concourse/issues/417 might be relevant

**Comment by vito** [comment]
Interesting developments here: https://github.com/concourse/concourse/issues/534#issuecomment-236256398

**Comment by vito** [comment]
closing in favor of #684
