### ISSUE TITLE
[Chore] GCP cleanup

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2925]
Kill prop, airbus and GCP resources with the words "draupnir" and "mainlamb'

**Comment by cirocosta** [comment]
Hey,

I noticed that we have *a bunch* of disks there that are not in use by any machine.

Some were created by tests we used to run in CI for k8s (as a result of making use of persistent volumes for postgres & workers), but lots of others seem to have been created by BOSH a very long time ago.

note.: SSD persistent disks seem to be one of our major expenses there, but not all of those disks are SSD based. Still, worth cleaning 'em up 👍

**Comment by scottietremendous** [comment]
Worth having a look into AWS
