### ISSUE TITLE
Don't use `concourse` tokens.  

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#2936]
## What challenge are you facing?

* [Users need to log out and log back in every time they change their auth config](https://github.com/concourse/concourse/issues/2441).
* Fly can't implement a proper oauth flow because `skymarshal` gets in the way.

Currently concourse issues its own auth tokens. 

Originally this happened for two reasons:
1) We encode all your team memberships into your token to make downstream requests more efficient. We figure out all your team memberships once, instead of upon each request. The drawback here is that since your teams live in your token. They don't change unless you log out and log back in.

2) `dex` doesn't support client credentials (yet). Any internal components (`tsa`) that need to talk to the API will generate their own auth tokens. They do this because they have no way of requesting a token from `dex`. Once `dex` supports the `client_credentials` grant type, each component can request a token through the proper channels.

## What would make this better?

We could use `dex` tokens directly... or we could let people configure whatever external auth provider they want. 

At the end of the day, all we need to know is:
* The unique identifier of the user/service
* What teams you should be a member of

This means _in theory_ we should be able to let people configure whatever auth provider they want, and we would provide a way of configuring how `claims` map to `teams`.

The way we do this is already quite free form. The `auth_config` for a `team` contains two fields for each `role`: `users` and `groups`. We take the `sub` and `groups` claims out of your token, iterate over every `role` for every `team`, and try and match your identity to anything thats been configured.

### So should we abandon dex?... No

`dex` is great because it has a really nice pluggable connector model. It lets you write custom logic to integrate with services that don't expose group information through a claim in your token. And it adds a very simple mechanism for maintaining a pool of local users. Plus, it's written in go, which means we can embed a dex server directly in the concourse binary. 

So instead of letting people configure whatever auth provider they want, maybe we just continue to use `dex` as the middle layer. It has connectors for `oidc` and `oauth2` support. This means dex would proxy groups from a 3rd party and return them to concourse in the `groups` claim (in a format that it will understand). Yes its an extra layer, but maybe that's fine.

Regardless of what we decide, I think we would want to continue to ship the concourse binary with _out-of-the-box_ `dex` support, and (it we so choose) give people the ability to bypass it.

**Comment by pivotal-jwinters** [comment]
Couple prereqs
- [ ] Have the webserver handle all the cookie csrf logic #2963
- [ ] Dex needs to support the client credentials grant type 
- [ ] Make dex clients configurable

**Comment by vito** [comment]
@pivotal-jwinters Would this help with #3208?

**Comment by pivotal-jwinters** [comment]
I don't think what they're asking for in #3208 is actually possible. We definitely don't want to enable password grants for third party services. We also don't want to create an endpoint that you can curl to expose the access token.

If we support the client credentials grant type, they could potentially log into fly using their client credentials. But it would depend on how RBAC will apply to clients (vs users). Maybe clients have full access to everything, maybe they are mapped to specific actions? It's something we would have to think about.

**Comment by pivotal-jwinters** [comment]
I've started spiking on this. Everything has been committed in a halfway working state to a `generic-tokens` branch. 

So far these have been the major changes to get this working:

- Adding the `client_credentials` grant type to our fork of dex. That work can be found on the `generic-tokens` branch in concourse/dex.

- Getting the tsa to request a token via the `client_credentials` grant type instead of generating its own token.

- Moving all the dex (users, groups) -> concourse (teams) mapping out of the login flow, and into the `access.AccessorFactory` so that it happens on each request (instead of once at login).

- Splitting up the web and api into two separate components. We want to do this so that the web can make requests to its `webserver` which will handle all the `cookie`/`crsf` logic and proxy the request to the api with the proper `Authorization` header in place.
