### ISSUE TITLE
better Inconsolata antialiasing

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2938]
I've noticed that when I try to reproduce @Lindsayauchin's designs, my fonts look kinda fat and blurry. Then I discovered https://stackoverflow.com/questions/28217486/font-renders-thicker-in-browsers and when I used `-webkit-font-smoothing: antialiased` it looked just like the designs.

## changes across the whole app

However I'm hesitant to just apply this across the whole app because we've gotten used to how things look with the current, slightly-different-than-the-designs version and I wouldn't want to make such a cross-cutting (potentially breaking) change. So here's a place to document this fear and think about how to do antialiasing better

## cross-browser compatibility

It kinda looks like the "equivalent" property for Firefox/Gecko on OSX is `-moz-osx-font-smoothing: grayscale;`, but I haven't noticed it making a big difference. Maybe I'm testing with the wrong version of Firefox or something, haven't taken the time to check, but it gives me anxiety.

**Comment by pivotal-jamie-klassen** [comment]
@vito @pivotal-jwinters should this be in https://github.com/concourse/rfcs?

**Comment by pivotal-jwinters** [comment]
@vito just posted new [RFC guidelines](https://github.com/concourse/rfcs/pull/16)

**Comment by cirocosta** [comment]
Hey, FWIW I use both `text-rendering: optimizeLegibility;` and `-webkit-font-smoothing: antialiased;` on my blog to improve the fonts 🤔

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen Looks like adding the -webkit-font-smoothing: antialiased removed some of the boldness of the fonts in the build logs and the resource page. 

In my sketch mocks, I am using an Inconsolata bold so if we could update a couple spots with some bold style to Inconsolata I think we are there!

Can we add `font-weight: 700;` ( or however you decide to implement bold style) to the body font on the following?:

### Pipeline view
_screenshot without style_ 

![screen shot 2019-01-07 at 11 36 53 am](https://user-images.githubusercontent.com/27746614/50780835-f276ff00-1271-11e9-9559-e456cad1b8ae.png)


_with   ` font-weight: 700;`_
![screen shot 2019-01-07 at 11 37 29 am](https://user-images.githubusercontent.com/27746614/50780789-d83d2100-1271-11e9-881c-f7ad1dc90ba8.png)


### Breadcrumbs
_screenshot without style_ 

![screen shot 2019-01-07 at 11 40 03 am](https://user-images.githubusercontent.com/27746614/50780468-fe15f600-1270-11e9-9e76-fa2be233dcc2.png)

_with   ` font-weight: 700;`_

![screen shot 2019-01-07 at 11 39 55 am](https://user-images.githubusercontent.com/27746614/50780475-02421380-1271-11e9-9574-f433bfd9c0c8.png)


### Resource page

![screen shot 2019-01-07 at 11 30 09 am](https://user-images.githubusercontent.com/27746614/50779913-a0cd7500-126f-11e9-9c5b-15f5641f3ef7.png)
_L screenshot without style  R screenshot with `font-weight: 700;`_


### Build page logs
This is also realted to https://github.com/concourse/concourse/issues/2765

On the Build page, the log output texts need a bit more contrast with some bold added to the font style. Adding the bold to the style attribute of `timestamped-content` td (in addition to adding it to the body) will help  improve the readability of the logs. 

![screen shot 2019-01-07 at 10 55 28 am](https://user-images.githubusercontent.com/27746614/50779750-23a20000-126f-11e9-94b5-d6f92eae0cfb.png)

_L screenshot without style  R screenshot with `font-weight: 700;`_

**Comment by jama-pivotal** [comment]
My bad, accepting his story and creating a new one for Lindsay's feedback on the bolding of Inconsolata font
