### ISSUE TITLE
true/false: defined as boolean values in a task yaml, but defined as strings in pipeline config

### ISSUE THREAD

**Issue by APShirley** [concourse/concourse#294]
Hi,

We've noticed a problem when a task config defines a boolean param, without quotes:
```
params:
    MY_PARAM: false
```
The problem is that evaluating `$MY_PARAM` in the task script gets rendered as a `0` rather than as `false`. On the other hand, if you try to override the value in the pipeline config, the value gets rendered instead as a string: `"false"`.

Thanks,

Al && @dsabeti

**Comment by voelzmo** [comment]
Yup, very unexpected behavior which bit us recently as well.

**Comment by d-reinhold** [comment]
We hit this today too. After an upgrade from 67.1 to 73.0, one of our tasks stopped working, because our env vars weren't right anymore.

We stringified them as a workaround, but this is totally a bug.
