### ISSUE TITLE
No bosh release published for 4.2.2

### ISSUE THREAD

**Issue by BooleanCat** [concourse/concourse#2940]
## Bug Report

No bosh release published for 4.2.2

## Steps to Reproduce

From the concourse download page, navigate to the bosh release 4.2.2, see that it doesn't work. Additionally, the garden-runc-release release referenced I thought was supposed to be 1.17.1 rather than 1.16.3.

## Expected Results

The link should work.

## Actual Results

The link 404s

**Comment by xtremerui** [comment]
The 4.2.2 is on https://bosh.io/releases/github.com/concourse/concourse-bosh-release.

We should fix the broken link and make it clear where to find the latest concourse bosh release.

Do we need to keep both concourse/concourse and concourse/concourse-bosh-release on bosh.io? If not could the concourse/concourse be marked to deprecated or even removed?

**Comment by vito** [comment]
The link from the downloads page has been fixed.

@xtremerui Not sure if it can be marked as deprecated. A redirect would be nice. I'm not sure we should remove it yet as there may still be manifests referencing the old URL.
