### ISSUE TITLE
check_every not working, resource not checking at all

### ISSUE THREAD

**Issue by frankbecker** [concourse/concourse#2945]
## Bug Report

After creating my pipeline, the resource that triggers the pipeline does not get checked.
Check needs to be executed manually with the fly command, and after that is done successfully, the check does not trigger the job, nor does it pass the retrieved version by the check process.
I check manually by running the following command:
`fly -t dev check-resource --resource`
The check is successful, but never triggers or passes the value to the job.

## Expected Results

I expect the check to run automatically after creating the pipeline.

## Actual Results

Pipeline is not checking, pipeline remains stale. I have to check it manually and after a successful check, the job never gets triggered.

## Version Info

* Concourse version: version: | v3.13.0

**Comment by mratoms** [comment]
We're seeing this with Concourse version 3.14.1 as well

**Comment by mratoms** [comment]
A related issue we've seen is that in existing pipeline, _check_every_ does not work as expect either. For example, one of our resources is set to check every 2 hours, yet when viewed through the UI, we will occassionally see last checked: 5+ hours ago

**Comment by vito** [comment]
If `check-resource` is returning as if everything's OK and the check interval is still not bumping that usually means either the pipeline is paused, the resource is paused (<5.0), or the resource is pinned (5.0+). Not much to go on with the information provided so far though. :thinking: 

Can the issue be reproduced with 5.0?
