### ISSUE TITLE
Cannot login to concourse via fly with username & password (400 error)

### ISSUE THREAD

**Issue by jessedye** [concourse/concourse#2952]
I'm getting a 400 error when attempting to do a fly login when providing credentials. I am currently using fly version 4.2.1

```
fly --target $TARGET login -c $URL --username $USER --password $PASSWORD --insecure

logging in to team 'main'
error: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_request","error_description":"Requested connector does not exist."}
```

**Comment by xtremerui** [comment]
You will need to set up local user first as I mentioned in your other issue.

**Comment by vito** [comment]
This sounds more like a support request so I'm gonna close it out, but if you're still stuck you could try out [forums](https://discuss.concourse-ci.org)!
