### ISSUE TITLE
Need an easier way to get token via fly command line.

### ISSUE THREAD

**Issue by jessedye** [concourse/concourse#2953]
I would like to propose a better way to log in to concourse via the CLI without having to get the token through the browser. Currently it's really clunky going to get a token via browser and does not fit well into many automation solutions.

![image](https://user-images.githubusercontent.com/17808103/50185983-66fbf500-02e7-11e9-9749-476c7e54d1d6.png)

To make this better I would like to be able to username/password credentials to the CLI to log in. This will make it easier when switching between different concourse environments.

**Comment by xtremerui** [comment]
If you set up [local user](https://concourse-ci.org/install.html#local-auth-config) you can do `fly -t ci login -u username -p password`.

If this is what you want please close the issue thx!

**Comment by cdugga** [comment]
The local user suggestion mentioned above requires control of the Concourse installation. Going back to the original question, is there a way to get token from command line through script rather than making it manual process?
