### ISSUE TITLE
no search on dashboard when there are no pipelines

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2955]
## What challenge are you facing?

If there are no pipelines to see, it's hard for users to understand what the search bar is there for. It might even draw attention from the important message in the middle of the page.

## What would make this better?

Get rid of it! with no pipelines, there's no need for a search bar. Similarly I think we should disable the `/` shortcut to focus the search bar.

## Are you interested in implementing this yourself?

👍  another prerequisite for #2881

**Comment by jama-pivotal** [comment]
Confirmed this works nicely. No search bar when there's no pipelines, and when I set a pipeline you can search!
