### ISSUE TITLE
Expiring the Auth Cookie shouild set 'HttpOnly' and 'Secure' fields

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2957]
In the logout flow we set the users cookie with an expiry in the past, but it does not include the `HttpOnly` and `Secure` attributes when setting that expiry.

Despite this being the logout flow (`/sky/logout`) and not exposing anything, we should still set those attributes as a best practice for all cookies.

**Comment by vito** [comment]
fixed via https://github.com/concourse/concourse/pull/3031
