### ISSUE TITLE
Remove GET /sky/token route

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2962]
This endpoint was added so that people can copy their token to `fly` more easily, and is no longer necessary now that we have the new login UI (#2845):

https://github.com/concourse/concourse/blob/d5b95215cf0652ccca86a37205c6ee59f29c86ce/skymarshal/skyserver/skyserver.go#L278-L288

**Comment by xtremerui** [comment]
Not sure if the file is using but it needs to be cleanup  (probably some other places too) by this change

https://github.com/concourse/concourse/blob/fe72da8c5fd4e8cf6998eea560fa990476228eae/ci/tasks/scripts/k8s-testflight#L40

**Comment by kalrashubham49** [comment]
Hi @vito - Is there any way we can fetch the token programatically , as i would required this for implementing my pipeline completely as code through Rest HTTP Endpoints??

If not available , please suggest what should be done ??
