### ISSUE TITLE
Invalid argument for flag `/c, /config' (expected atc.PathFlag)

### ISSUE THREAD

**Issue by ChrisMooy** [concourse/concourse#2966]
Hi,
When try to deploy the project by execute the shell, it always throws exception like:
=== setup integration service setup pipeline ===
error: invalid argument for flag `/c, /config' (expected atc.PathFlag): path 'ci/pipeline/integration-service-pipeline.yml' does not exist.

The content of the shell yml file:
echo "=== setup integration service setup pipeline ==="
fly -t main set-pipeline \
  -p integration-service-ci -n $CON_TEAM \
  -c pipeline/integration-service-pipeline.yml \
  -l pipeline/config.yml \
  -l credentials/credentials.yml

The construction of the ci like:
![2018-12-31 11_26_30-integration-service_ci_install-integration-ser](https://user-images.githubusercontent.com/46273159/50554088-4c664a80-0cef-11e9-8d9e-9424f89412ab.png)

**Comment by vito** [comment]
This sounds more like a support request than a bug, so I'm gonna close it, but feel free to ask in the [forums](https://discuss.concourse-ci.org) instead. I can't think of any reason why it would think a file doesn't exist if it actually does. :man_shrugging:
