### ISSUE TITLE
pin on resource box in pipeline view sometimes has wrong position

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2967]
The positioning of the little pin icon is wrong sometimes, as in

<img width="534" alt="screen shot 2018-12-31 at 11 39 37 am" src="https://user-images.githubusercontent.com/22056320/50564266-a700a600-0cf1-11e9-9384-788545ae8773.png">

The circumstances under which this occurs are unclear, but I finally remembered to take a screenshot when I saw it.

Obviously we'd expect the pin to always be vertically centered inside the purple box.

## Version Info

* Concourse version: 4.2.2 (master)
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): Chrome
* Did this used to work? no

**Comment by clarafu** [comment]
It seems like I can reproduce it if I freshly login and go to the Drills pipeline in ci.concourse-ci.org. It does seem to reset to the correct position when it auto refreshes.

**Comment by pivotal-jamie-klassen** [comment]
seems like most likely `imageHeight()` is evaluating to 0 here: https://github.com/concourse/concourse/blob/master/web/public/index.js#L125... Might be a race condition somehow in the d3 code? I don't really know the evaluation model of d3, but I could imagine that there's some kind of deferred evaluation where the `image` node doesn't get appended until after all the properties have been computed. This would explain the fact that autorefresh fixes the positioning, since all the pinned resources already have `image` nodes inside them.

**Comment by pivotal-jamie-klassen** [comment]
For the record, the image node was consistently being appended, but the race seemed to be around computing its height -- I guess the d3 code was racing the layout engine and if the layout engine hadn't finished deciding the bounding box for the pin icon, it would have a height of 0.
