### ISSUE TITLE
Pipeline output page hangs when job logs around 1MB

### ISSUE THREAD

**Issue by jamiemonserrate** [concourse/concourse#298]
We have a pipeline in which one of the jobs had output of around 1MB. 

The Concourse UI page takes really long to render this page. It would be nice if there was a way to stream the data, or load it in parts to give a quicker UI experience. 

Or maybe load a truncated version of the output of the job, with a link to view the full output. (Similar to Travis and GoCD)

**Comment by vito** [comment]
This should be a lot better now; we've made a lot of improvements in the area including a ~10-12x speedup for downloading the logs.
