### ISSUE TITLE
Prometheus Locks state metric has unbound cardinality

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#2980]
## Bug Report

Right now, `concourse_locks_state`(introduced in https://github.com/concourse/concourse/pull/2681) has a label that can get wild in terms of cardinality given that it exposes `objectId` that seems to be almost unbounded:

<details>
<summary>sample</summary>
<pre>
concourse_locks_state{lockType="Batch",objectId="-629780414"} 0
concourse_locks_state{lockType="Batch",objectId="-630800735"} 0
concourse_locks_state{lockType="Batch",objectId="-631227151"} 0
concourse_locks_state{lockType="Batch",objectId="-63332322"} 0
concourse_locks_state{lockType="Batch",objectId="-65043860"} 0
concourse_locks_state{lockType="Batch",objectId="-653188958"} 0
concourse_locks_state{lockType="Batch",objectId="-654479246"} 0
concourse_locks_state{lockType="Batch",objectId="-655227815"} 0
concourse_locks_state{lockType="Batch",objectId="-656004949"} 0
concourse_locks_state{lockType="Batch",objectId="-656531228"} 0
concourse_locks_state{lockType="Batch",objectId="-665949219"} 0
concourse_locks_state{lockType="Batch",objectId="-668941765"} 0
concourse_locks_state{lockType="Batch",objectId="-672275628"} 0
concourse_locks_state{lockType="Batch",objectId="-673747273"} 0
concourse_locks_state{lockType="Batch",objectId="-674451151"} 0
concourse_locks_state{lockType="Batch",objectId="-676382477"} 0
concourse_locks_state{lockType="Batch",objectId="-677811811"} 0
concourse_locks_state{lockType="Batch",objectId="-678350638"} 0
concourse_locks_state{lockType="Batch",objectId="-680122896"} 0
concourse_locks_state{lockType="Batch",objectId="-68260188"} 0
concourse_locks_state{lockType="Batch",objectId="-684084400"} 0
concourse_locks_state{lockType="Batch",objectId="-684971574"} 0
concourse_locks_state{lockType="Batch",objectId="-692834064"} 0
concourse_locks_state{lockType="Batch",objectId="-697969430"} 0
concourse_locks_state{lockType="Batch",objectId="-711165751"} 0
concourse_locks_state{lockType="Batch",objectId="-71154364"} 0
concourse_locks_state{lockType="Batch",objectId="-712431973"} 0
concourse_locks_state{lockType="Batch",objectId="-713216575"} 0
concourse_locks_state{lockType="Batch",objectId="-71332552"} 0
concourse_locks_state{lockType="Batch",objectId="-713386219"} 0
concourse_locks_state{lockType="Batch",objectId="-713418067"} 0
concourse_locks_state{lockType="Batch",objectId="-714215770"} 0
concourse_locks_state{lockType="Batch",objectId="-716500176"} 0
concourse_locks_state{lockType="Batch",objectId="-718523030"} 0
concourse_locks_state{lockType="Batch",objectId="-723478603"} 0
concourse_locks_state{lockType="Batch",objectId="-726154852"} 0
concourse_locks_state{lockType="Batch",objectId="-726734651"} 0
concourse_locks_state{lockType="Batch",objectId="-729636423"} 0
concourse_locks_state{lockType="Batch",objectId="-730132639"} 0
concourse_locks_state{lockType="Batch",objectId="-742744856"} 0
concourse_locks_state{lockType="Batch",objectId="-744337015"} 0
concourse_locks_state{lockType="Batch",objectId="-74633629"} 0
concourse_locks_state{lockType="Batch",objectId="-748944240"} 0
concourse_locks_state{lockType="Batch",objectId="-749376581"} 0
concourse_locks_state{lockType="Batch",objectId="-75451409"} 0
concourse_locks_state{lockType="Batch",objectId="-755017"} 0
concourse_locks_state{lockType="Batch",objectId="-755112703"} 0
concourse_locks_state{lockType="Batch",objectId="-766286370"} 0
concourse_locks_state{lockType="Batch",objectId="-766587077"} 0
concourse_locks_state{lockType="Batch",objectId="-767682651"} 0
concourse_locks_state{lockType="Batch",objectId="-768541208"} 0
concourse_locks_state{lockType="Batch",objectId="-776446719"} 0
concourse_locks_state{lockType="Batch",objectId="-783132389"} 0
concourse_locks_state{lockType="Batch",objectId="-784293720"} 0
concourse_locks_state{lockType="Batch",objectId="-78466213"} 0
concourse_locks_state{lockType="Batch",objectId="-788426070"} 0
concourse_locks_state{lockType="Batch",objectId="-790881409"} 0
concourse_locks_state{lockType="Batch",objectId="-791503434"} 0
concourse_locks_state{lockType="Batch",objectId="-797241799"} 0
concourse_locks_state{lockType="Batch",objectId="-802056519"} 0
concourse_locks_state{lockType="Batch",objectId="-806355622"} 0
concourse_locks_state{lockType="Batch",objectId="-810726128"} 0
concourse_locks_state{lockType="Batch",objectId="-813089783"} 0
concourse_locks_state{lockType="Batch",objectId="-824445620"} 0
concourse_locks_state{lockType="Batch",objectId="-835031345"} 0
concourse_locks_state{lockType="Batch",objectId="-835487333"} 0
concourse_locks_state{lockType="Batch",objectId="-8460593"} 0
concourse_locks_state{lockType="Batch",objectId="-848979949"} 0
concourse_locks_state{lockType="Batch",objectId="-849493595"} 0
concourse_locks_state{lockType="Batch",objectId="-856565946"} 0
concourse_locks_state{lockType="Batch",objectId="-865223042"} 0
concourse_locks_state{lockType="Batch",objectId="-871359964"} 0
concourse_locks_state{lockType="Batch",objectId="-872108649"} 0
concourse_locks_state{lockType="Batch",objectId="-873978515"} 0
concourse_locks_state{lockType="Batch",objectId="-87412245"} 0
concourse_locks_state{lockType="Batch",objectId="-875293770"} 0
concourse_locks_state{lockType="Batch",objectId="-876889966"} 0
concourse_locks_state{lockType="Batch",objectId="-883292253"} 0
concourse_locks_state{lockType="Batch",objectId="-884473057"} 0
concourse_locks_state{lockType="Batch",objectId="-888476255"} 0
concourse_locks_state{lockType="Batch",objectId="-892666952"} 0
concourse_locks_state{lockType="Batch",objectId="-895936758"} 0
concourse_locks_state{lockType="Batch",objectId="-896122673"} 0
concourse_locks_state{lockType="Batch",objectId="-897914404"} 0
concourse_locks_state{lockType="Batch",objectId="-903146083"} 0
concourse_locks_state{lockType="Batch",objectId="-903503460"} 0
concourse_locks_state{lockType="Batch",objectId="-904106753"} 0
concourse_locks_state{lockType="Batch",objectId="-907510253"} 0
concourse_locks_state{lockType="Batch",objectId="-908377212"} 0
concourse_locks_state{lockType="Batch",objectId="-910601075"} 0
concourse_locks_state{lockType="Batch",objectId="-912212451"} 0
concourse_locks_state{lockType="Batch",objectId="-912299731"} 0
concourse_locks_state{lockType="Batch",objectId="-913782851"} 0
concourse_locks_state{lockType="Batch",objectId="-91740456"} 0
concourse_locks_state{lockType="Batch",objectId="-91929358"} 0
concourse_locks_state{lockType="Batch",objectId="-919695664"} 0
concourse_locks_state{lockType="Batch",objectId="-921579138"} 0
concourse_locks_state{lockType="Batch",objectId="-926444584"} 0
concourse_locks_state{lockType="Batch",objectId="-932803930"} 0
concourse_locks_state{lockType="Batch",objectId="-933036000"} 0
concourse_locks_state{lockType="Batch",objectId="-935097342"} 0
concourse_locks_state{lockType="Batch",objectId="-935945152"} 0
concourse_locks_state{lockType="Batch",objectId="-94588137"} 0
concourse_locks_state{lockType="Batch",objectId="-946012538"} 0
concourse_locks_state{lockType="Batch",objectId="-946443134"} 0
concourse_locks_state{lockType="Batch",objectId="-948429946"} 0
concourse_locks_state{lockType="Batch",objectId="-960132524"} 0
concourse_locks_state{lockType="Batch",objectId="-963268056"} 0
concourse_locks_state{lockType="Batch",objectId="-968604628"} 0
concourse_locks_state{lockType="Batch",objectId="-97195456"} 0
concourse_locks_state{lockType="Batch",objectId="-975371411"} 0
concourse_locks_state{lockType="Batch",objectId="-980120779"} 0
concourse_locks_state{lockType="Batch",objectId="-991720309"} 0
concourse_locks_state{lockType="Batch",objectId="-992162414"} 0
concourse_locks_state{lockType="Batch",objectId="-992376537"} 0
concourse_locks_state{lockType="Batch",objectId="-99419541"} 0
concourse_locks_state{lockType="Batch",objectId="1004572459"} 0
concourse_locks_state{lockType="Batch",objectId="1011146207"} 0
concourse_locks_state{lockType="Batch",objectId="1014346401"} 0
concourse_locks_state{lockType="Batch",objectId="1014615774"} 0
concourse_locks_state{lockType="Batch",objectId="1020175866"} 0
concourse_locks_state{lockType="Batch",objectId="1020239338"} 0
concourse_locks_state{lockType="Batch",objectId="1020531875"} 0
concourse_locks_state{lockType="Batch",objectId="1022009169"} 0
concourse_locks_state{lockType="Batch",objectId="102467591"} 0
concourse_locks_state{lockType="Batch",objectId="1025303615"} 0
concourse_locks_state{lockType="Batch",objectId="1028841135"} 0
concourse_locks_state{lockType="Batch",objectId="103278494"} 0
concourse_locks_state{lockType="Batch",objectId="1033298774"} 0
concourse_locks_state{lockType="Batch",objectId="1037473715"} 0
concourse_locks_state{lockType="Batch",objectId="1038888828"} 0
concourse_locks_state{lockType="Batch",objectId="1039292705"} 0
concourse_locks_state{lockType="Batch",objectId="1043089277"} 0
concourse_locks_state{lockType="Batch",objectId="1053840109"} 0
concourse_locks_state{lockType="Batch",objectId="1054569121"} 0
concourse_locks_state{lockType="Batch",objectId="1055279954"} 0
concourse_locks_state{lockType="Batch",objectId="1056561282"} 0
concourse_locks_state{lockType="Batch",objectId="1062221598"} 0
concourse_locks_state{lockType="Batch",objectId="1064168550"} 0
concourse_locks_state{lockType="Batch",objectId="1068326702"} 0
concourse_locks_state{lockType="Batch",objectId="1070953327"} 0
concourse_locks_state{lockType="Batch",objectId="1074227536"} 0
concourse_locks_state{lockType="Batch",objectId="1075271092"} 0
concourse_locks_state{lockType="Batch",objectId="1084982757"} 0
concourse_locks_state{lockType="Batch",objectId="1087674324"} 0
concourse_locks_state{lockType="Batch",objectId="1092416625"} 0
concourse_locks_state{lockType="Batch",objectId="1100655923"} 0
concourse_locks_state{lockType="Batch",objectId="1100905002"} 0
concourse_locks_state{lockType="Batch",objectId="1101522371"} 0
concourse_locks_state{lockType="Batch",objectId="1117117914"} 0
concourse_locks_state{lockType="Batch",objectId="1120730483"} 0
</pre>
</details>

<br />
cc @topherbullock  (original author of the PR)

## Steps to Reproduce

1. run concourse with prometheus support activated (set `CONCOURSE_PROMETHEUS_BIND_IP` and `CONCOURSE_BIND_PORT`);

2. run few things in concourse (set a pipeline here and there); 

3. look for the `concourse_locks_state` metric under `concourse:CONCOURSE_PROMETHEUS_BIND_PORT/metrics`

## Expected Results

Should not have too many object ids (maybe just drop that label for now?).

## Version Info

* Concourse version: master (f1035ff9ccefa19183c480f89e8d0ad262661342)
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS: -
* Browser (if applicable): -

**Comment by marco-m** [comment]
As a Prom user, good catch! :-)

**Comment by topherbullock** [comment]
Good catch @cirocosta! Not sure anyone will in practice need/want to know the id of the underlying object (build id, pipeline id, [etc](https://github.com/concourse/concourse/blob/481abfc098f5970ae0d7631d07de7917d9bef316/atc/db/lock/lock.go#L27-L53) ) related to a lock; which is what the intent was for the `object_id` field.

**Comment by topherbullock** [comment]
Closing because  #3041 is merged! 🙌
