### ISSUE TITLE
Enabling Kubernetes In Cluster overrides Vault as Credential Manager

### ISSUE THREAD

**Issue by mattlqx** [concourse/concourse#2981]
## Bug Report

Running Concourse with `CONCOURSE_KUBERNETES_IN_CLUSTER=true` seems to take precedence as using it for a credentials manager instead of whatever other ones are configured (in my case, Vault).

## Steps to Reproduce

Configure Concourse web with Vault and `CONCOURSE_KUBERNETES_IN_CLUSTER=true`.

## Expected Results

Referenced credentials via `((mysecret.mykey))` to successfully be fetched from Vault and used.

## Actual Results

Referenced credential tries to pull from Kubernetes secret. These log lines are from prior to adding a Role so that concourse's ServiceAccount can access secrets in the namespace.

```
{"timestamp":"1546464374.246833086","source":"atc","message":"atc.syncer.mypipeline:radar.scan-resource.interval-runner.tick.failed-to-evaluate-resource-source","log_level":2,"data":{"error":"Finding variable 'github.private_key': secrets \"mypipeline.github\" is forbidden: User \"system:serviceaccount:concourse:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"concourse-main\"","pipeline-scoped-name":"mypipeline:resource:concourse","session":"20.1.99.1.1"}}
{"timestamp":"1546464374.250164747","source":"atc","message":"atc.syncer.mypipeline:radar.scanresources-runner-error","log_level":1,"data":{"error":{"Err":{},"Cause":{"ErrStatus":{"metadata":{},"status":"Failure","message":"secrets \"mypipeline.github\" is forbidden: User \"system:serviceaccount:concourse:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"concourse-main\"","reason":"Forbidden","details":{"name":"mypipeline.github","kind":"secrets"},"code":403}}},"session":"20.1"}}
{"timestamp":"1546464374.259128571","source":"atc","message":"atc.credential-manager.k8s-secret-error","log_level":2,"data":{"error":"secrets \"mypipeline.github\" is forbidden: User \"system:serviceaccount:concourse:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"concourse-main\"","name":"kubernetes","namespace":"concourse-main","pipelineSecretName":"mypipeline.github","secretName":"github","session":"17"}}
```

After adding the Role, it simply says it can't find an non-existing secret.

```
{"timestamp":"1546466294.253921509","source":"atc","message":"atc.credential-manager.k8s-secret-not-found","log_level":1,"data":{"name":"kubernetes","namespace":"concourse-main","pipelineSecretName":"mypipeline.github","secretName":"github","session":"17"}}
```

I can set `CONCOURSE_KUBERNETES_IN_CLUSTER=false` and the credential pulls from Vault successfully.

## Additional Context

I don't see any documentation about the Kubernetes integrations of Concourse and I'm a new user to Concourse. It runs out of my Kubernetes cluster right now but I don't want to use it as a credentials manager. I'm unsure if setting `CONCOURSE_KUBERNETES_IN_CLUSTER` gives me additional features beyond that.

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by vito** [comment]
I think this is a case of confusing naming. `CONCOURSE_KUBERNETES_IN_CLUSTER` really means "configure Kubernetes secrets as my credential manager automatically please". :slightly_smiling_face: 

So setting it to `false` is really all you need to do, but I do think we should rename that to be a bit more explicit, since right now it sounds like something that you should just set if you're running in a Kubernetes cluster assuming it configures other things appropriately or something. But really it's just an easy way to enable the K8s secrets manager.

I've opened https://github.com/concourse/concourse/issues/2987 to make this clearer. Thanks for the report!

**Comment by mattlqx** [comment]
Thanks for the clarification! Exactly what I needed.
