### ISSUE TITLE
Destroy Team doesn't Destroy Pipelines

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2986]
## Bug Report

Destroying teams does not destroy the teams pipelines.
In fact, if you destroy a team, you may end up corrupting your environment.

## Steps to Reproduce

- create team
- create and run pipelines
- destroy team

## Expected Results

- team deleted and all related data

## Actual Results

- team deleted
- pipelines remain and reference team
- resource checking fails due to the process reviewing all pipelines, even the orphaned ones, in an outer join to teams.
Error:
```
"timestamp":"1544723203.891162395","source":"atc","message":"atc.syncer.proxy-dev:scheduler.tick.failed-to-update-pipeline-config","log_level":2,"data":{"error":"sql: Scan error on column index 5: unsupported Scan, storing driver.Value type \u003cnil\u003e into type *string","session":"36.3392.107758"
```

## Version Info

* Concourse version: 3.13
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack and VMWare

**Comment by vito** [comment]
erm... I don't think this is true. It sounds like your database schema may be corrupted and has lost some constraints? This is easy to verify on a new installation:

```
concourse=# \d pipelines
                                               Table "public.pipelines"
     Column     |           Type           | Collation | Nullable |                      Default                       
----------------+--------------------------+-----------+----------+----------------------------------------------------

...

 team_id        | integer                  |           | not null | 

...

Foreign-key constraints:
    "pipelines_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
```

What does that show for you?

**Comment by keithkroeger** [comment]
I do find the following constraints for teams in other environments rather than the one we are seeing


 child_column | parent_table | parent_column |                      conname
--------------------------------------+---------------------------------------------------
 team_id      | teams        | id            | builds_team_id_fkey
 team_id      | teams        | id            | containers_team_id_fkey
 team_id      | teams        | id            | pipelines_team_id_fkey
 team_id      | teams        | id            | volumes_team_id_fkey
 team_id      | teams        | id            | worker_resource_config_check_sessions_team_id_fkey
 team_id      | teams        | id            | workers_team_id_fkey

**Comment by vito** [comment]
@keithkroeger There are no docs for that because there's really no reason users should even know anything about it. Were there operations run against your database that may have corrupted it? Maybe a faulty backup/restore or something?

**Comment by keithkroeger** [comment]
The teams table was dropped and re-created with a restore, so i can see that issue happening

I'd guess just those 6 fks and then teh team build tables might do it...

**Comment by vito** [comment]
No thoughts other than keep the logs next time you do a backup/restore and check for any suspicious errors I suppose. I'm gonna close this for now though since I don't think this should affect regular use cases.
