### ISSUE TITLE
volume '74054ca0-96a1-492c-737d-becd9d7268cf' disappeared from worker XXXX

### ISSUE THREAD

**Issue by cperry169** [concourse/concourse#2993]
volume '74054ca0-96a1-492c-737d-becd9d7268cf' disappeared from worker 'dev-worker-18'

## Steps to Reproduce
fly login -c https://IP_ADDRESS:8443 -k -t  TARGET - u USER -p PASSWORD
fly sp -t TARGET -p PIPELINE -c NAME.yaml -l credentials.yaml
 
## Expected Results
Pipeline should be running as expected.
Chads-MacBook-Pro:~ chadp$ fly workers -t TARGET
name           containers  platform  tags  team  state    version
WORKER-NAME  30           linux     none  none  running  2.1
## Actual Results

```
Chads-MacBook-Pro:~ chadp$ fly workers -t TARGET
name           containers  platform  tags  team  state    version
dev-worker-18  0           linux     none  none  running  2.1
volume '74054ca0-96a1-492c-737d-becd9d7268cf' disappeared from worker 'WORKER'{"timestamp":"1546634317.440117836","source":"tsa","message":"tsa.connection.channel.forward-worker.heartbeat.start","log_level":1,"data":{"remote":"IP_ADDRESS","session":"1914.1.1.40","worker-address":"127.0.0.1:36679","worker-platform":"linux","worker-tags":""}}
```
## Version Info
* Concourse version: 4.2.1 
* Deployment type (Docker): docker version 18.09.0, build 4d60db4
* Depoyment type (Docker-Compose) docker-compose version 1.21.0, build 5920eb0
* Infrastructure/IaaS: Ubuntu 18.04.1 LTS"
* Browser (if applicable): FireFox 60.04 Oesr

**Comment by vito** [comment]
Not a whole lot to go on here, but this is something that 5.x recovers from via #2588

**Comment by Bluesboy** [comment]
I'm experiencing the same issue, using Concourse 5.8.0 though.

**Comment by schmurfy** [comment]
I still get this not sure when with 6.6.0.

**Comment by f0o** [comment]
Likewise on 6.7.1

**Comment by schmurfy** [comment]
I experience the same, workers are running as VM but are ephemeral too.

**Comment by f0o** [comment]
I solved for me by adding systemd's `${INVOCATION_ID}` to the name of the worker. That will guarantee unique names.

Only drawback is that you may end up with `stale` workers when the workers die unexpectedly. But I can live with that, it's just a cronjob to clean those away

**Comment by schmurfy** [comment]
@f0o this can be solved by adding `--ephemeral` when  staring the workers :)
