### ISSUE TITLE
Ability to select worker tags dynamically as part of a build (e.g. acquire from pool)

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#300]
We would like to be able to consume environments from a shared pool containing a mixture of iaas types. This way we could supplement our v-sphere environments with aws environments when demand is high.

Unfortunately our vsphere environments are not visible from our untagged aws workers. This means that we must decide what iaas our environment is hosted on, then define our pool-resource and worker tags to match.

It would be preferable to be able to claim an environment, determine it's iaas, and then decide what worker tags the task needs, all in the course of a single job build.

**Comment by vito** [comment]
Interestingly, this may be something we get for free from https://github.com/concourse/concourse/issues/534#issuecomment-235650894 - if we implement it super generically

**Comment by vito** [comment]
closing in favor of #684
