### ISSUE TITLE
ATC Rebalance properties exposed via the BOSH Release

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#3006]
## What challenge are you facing?
The properties to leverage atc rebalancing are not exposed via the BOSH release.

## What would make this better?
Review & merge the [branch with the changes](https://github.com/concourse/concourse-bosh-release/commit/8c0afd24f74c1a2da768ab953f0ac7d6c18eb46b)

**Comment by vito** [comment]
This is already there actually:

https://github.com/concourse/concourse-bosh-release/blob/master/jobs/worker/spec#L119-L127

I think that branch can be deleted.

**Comment by xtreme-sameer-vohra** [comment]
ah, sweet 👍 
didn't notice the property got renamed.
