### ISSUE TITLE
Log Rotation for Concourse

### ISSUE THREAD

**Issue by nimakaviani** [concourse/concourse#301]
With the new release of concourse, database migration, and the potential downtime it may cause, have become serious problems because of the size of history kept in the database.

It would be good for concourse to make history rotation (re-)configurable so that the deployer can choose how much history data is required to be kept in the database.

**Comment by xoebus** [comment]
I wonder about a component that can archive build logs into a blobstore. Configuring it with a Null Blobstore would be equivalent to deleting old events.

May also be useful for people who want to perform log analysis in RedShift or something.
