### ISSUE TITLE
Filter by teams not exact match

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#3010]
## Bug Report

When you filter by team concourse also displays teams whose name "contains" the selected team name.

I think when using the qualifier `team:` then the results should only include exact matches to team name.

It's surprising that after selecting from a drop-down list, effectively saying I want pipelines for "teamX", to get also all other teams that contain "teamX" in their name.

## Steps to Reproduce

1. Create a team "team-one"
2. Create a team "team-one-two"
3. Add user to both teams
4. Select `team: team-one` search

## Expected Results

Only `team-one` pipelines shown

## Actual Results

Both `team-one` and `team-one-two` pipelines are shown

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): binary
* Browser (if applicable): Firefox 64.0
* Did this used to work? Not sure

**Comment by jama-pivotal** [comment]
Was struggling to decide if this was a bug or enhancement. We first implemented the non-exact match as a way to capture most use cases. I can see the a case for exact-matching if you're looking to ONLY show your specific team. Maybe we can copy Google's (old?) search syntax by using `"` to specify exact matching e.g. `team: "team-one"`

**Comment by pn-santos** [comment]
That would be perfectly ok, but then I'd suggest that when one selects from the auto-complete (where it shows the team list) that the selection is added to the search box with double quotes. From my pov, UX-wise, when selecting from a list of teams it's unexpected to then see pipelines from multiple teams.
