### ISSUE TITLE
Builds failed due to worker errors don't abort/restart

### ISSUE THREAD

**Issue by osis** [concourse/concourse#3011]
## Bug Report

When a build has failed due to workers being stalled/unreachable, they continue to be in the 'running' state indefinitely until manually corrected.

## Steps to Reproduce

Run a build and kill thy worker 😱
Run all commands from the root of the `concourse/concourse` repo.
```
# start concourse
docker pull concourse/dev

docker-compose up -d --build

fly -t dev login -u test -p test -n main

# set the pipeline
fly -t dev sp -p test -c ./topgun/pipelines/task-waiting.yml

# unpause
fly -t dev up -p test

# start and watch the job. wait for the output `waiting for /tmp/stop-waiting to exist`
fly -t dev tj -j test/simple-job --watch

# in another terminal; stop the worker container. it will enter the retiring state, same as the topgun/k8s/worker_lifecycle test
docker stop concourse_worker_1
```

## Expected Results

I would expect the build to abort. Re-running would be a nice-to-have, but aborting would ensure that a job that is ```serial: true``` will be able to run other incoming triggered builds.

## Actual Results

The job gets stuck in the running state indefinitely.

## Version Info

* Concourse version: 
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): 4.2.2

**Comment by osis** [comment]
Seems like https://github.com/concourse/concourse/issues/2581 might be a prerequisite.

**Comment by marco-m-pix4d** [comment]
This is still happening with at least 5.2

**Comment by marco-m** [comment]
This is still happening with at least 5.2

**Comment by xtreme-sameer-vohra** [comment]
Was able to repro this on master ( latest released version v5.5.1 )

What would be the desired behaviour in the following scenarios that Concourse would not be able to distinguish between ( the operator may be able to ) ?
1. Worker is dead/killed at T1, the worker is marked as `stalled` at T2
    
2. There is network blip at some time T1, the worker is marked as `stalled` at T2

In scenario 1, its clear, we'd like Concourse to mark the build as `errored`, while, in scenario 2, we may desire to hold off until some time T3. 
If the worker is able to heartbeat before T3, then the build can resume. If the worker isn't heard from and T3 elapses, then Concourse marks the build as `errored`.

**Comment by marco-m** [comment]
@xtreme-sameer-vohra if I understand correctly, since Concourse is not able to distinguish scenario 1 from 2 (actually no distributed system could make the distinction), then to me the only sane _and_ simple approach is to always hold off until this T3 before declaring the build as `errored`.

On the other hand, i think that this T3 should be configurable by the operator, because they are the ones who know how flaky their network/builder are.

Does it make sense?

**Comment by xtreme-sameer-vohra** [comment]
Yes @marco-m, Concourse cannot distinguish between the 2 scenarios, hence a proposed solution would involve configuring a Δt, that Concourse will wait for after T2 ( when worker is marked as `stalled` ), after which the build should be marked as `errored`

**Comment by marco-m** [comment]
Yes, I should have said delta T (interval duration), not T3 (point in time).
