### ISSUE TITLE
Can't authenticate with team that has two github orgs

### ISSUE THREAD

**Issue by kkallday** [concourse/concourse#3018]
## Bug Report

Hi all. I'm trying to configure a concourse team that allows folks from org-1:team-a and org-2:team-b to login. I am part of team org-2:team-b however when I try to fly pipelines the cli outputs `forbidden`

## Steps to Reproduce

```bash
$ fly --target some-target set-team --github-team org-1:team-a --github-team org-2:team-b
$ fly --target some-target login --team-name some-team --concourse-url https://example.com
$ fly --target some-target set-pipeline ...
error: forbidden
```

## Expected Results

Expected to be able to fly a pipeline.

## Actual Results

:

```bash
$ fly --target some-target login --team-name some-team --concourse-url https://example.com
$ fly --target some-target set-pipeline ...
2019/01/09 10:55:28 GET /api/v1/teams/some-team/pipelines/test-pipeline/config HTTP/1.1
Host: some-host
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2019/01/09 10:55:28 HTTP/1.1 403 Forbidden
Content-Length: 9
Content-Type: text/plain; charset=utf-8
Date: Wed, 09 Jan 2019 18:55:28 GMT
X-Concourse-Version: 4.2.1
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block

forbidden
error: forbidden
```

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Google Cloud
* Browser (if applicable):
* Did this used to work? Not sure. First time creating a team with two github orgs.

**Comment by xtremerui** [comment]
There is no way to reproduce your issue if the step of configure `some-team` is not provided.

How did you set the team `some-team`? You can find docs for team auth [here](https://concourse-ci.org/authentication.html).

**Comment by kkallday** [comment]
@xtremerui my apologies. I thought I pasted that. I just updated the description.

**Comment by xtremerui** [comment]
Hi, I couldn't reproduce your issue. If you are able to login, which indicates `org-2:team-b` is taking effect, then you should be able to perform admin tasks through fly.

If you got access to your concourse db, you can verify that in the db `teams` table, there should be an entry like

`
2 | some-team | FALSE |   |   | {"owner":{"groups":["github:org-1:team-a","github:org-2:team-b"],"users":[]}} 
`

Also look into your concourse web node logs when doing `fly set-pipeline` might help.
