### ISSUE TITLE
Show date in Concourse UI

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3019]
## Bug Report

As the subject, Concourse UI doesn't show date, task log lines contain only time. And build info only shows like "2d 14h ago", which is hard to read especially when a job has a long history of builds.

## Steps to Reproduce

You can see this in every Concourse build.

## Expected Results

Add an option when start "concourse web", or on UI, to show date of builds.

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: VM
* Browser (if applicable): Any
* Did this used to work? No

**Comment by marco-m** [comment]
I have to say I found this relative time like "2d 14h ago" confusing when troubleshooting, one has to do mental gymnastics to convert to an approximate absolute timestamp :-) I like this feature request.

**Comment by evanchaoli** [comment]
Is there an ETA for the feature request? If you point out where, I mean which part of code, to do this change, I may contribute.

**Comment by evanchaoli** [comment]
I just did a quick browse and found the change might be in https://github.com/concourse/concourse/blob/master/web/elm/src/BuildOutput.elm. I guess that should be small change to switch time to date in log lines. But unfortunately nobody from my team is familiar with ELM. Can you guys prioritize this request and get is shipped as early as possible?

**Comment by vito** [comment]
> Can you guys prioritize this request and get is shipped as early as possible?

That's not how it works! 🙂 Everyone has their own feature requests, we can't simply do them all ourselves. This is an open-source project, and for the project to succeed *everyone* needs to take part when they can, not just our small team. Keep in mind how many different people use CI systems like Concourse and have their own different needs. It's impossible for one entity (company, person, whatever) to do everything for everyone as a top priority.

Please see the [contributing guide](https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md) if you need tips on getting started. That document goes over everything you need to know in order to make changes locally and test them out.

**Comment by jama-pivotal** [comment]
Before jumping into this I've added the `design-snack` label to think this through a bit more. Specifically, there are a few areas where we would have to add dates:
* Dashboard thumbnail
* Build page
* In the timestamps somehow?
* Job page

Maybe we do some fancy rules, where once its past 24 hours, we switch over to the dates?

**Comment by jesse-c** [comment]
> Maybe we do some fancy rules, where once its past 24 hours, we switch over to the dates?

If doing so, I'd recommend using `label`s to have the timestamp always available.

On another note, I've been writing Elm for over a year at my current job and could maybe help out with some implementation or review.

**Comment by vito** [comment]
This was actually done, we just forgot to close the issue. :slightly_smiling_face:

@jesse-c Nice to hear from others using Elm for work! I don't think we wnt with `label` but the timestamp value is available in the element `title=` attribute.

**Comment by jesse-c** [comment]
Haha no worries. That's a good approach too! :)

**Comment by GergelyKalmar** [comment]
If this is already done is there any info when will it get shipped and how will it exactly work? Thanks!

**Comment by evanchaoli** [comment]
@GergelyKalmar This enhancement has been included in 5.0.0. On the build page's top bar, if "started" or "finished" time are more than 24 hours, then it will show absolute time. See the screen shot.
![tmp](https://user-images.githubusercontent.com/18585861/60474970-8ec11200-9ca7-11e9-91b0-6faca433b658.png)

**Comment by GergelyKalmar** [comment]
@evanchaoli Ah, now I see. Thanks for the info!
