### ISSUE TITLE
Personal pipelines

### ISSUE THREAD

**Issue by mvdkleijn** [concourse/concourse#3021]
## What challenge are you facing?

I'm using Concourse to run some simple personal pipelines apart from pipelines for our team or those of other teams. For example, I'm running a pipeline that checks a git repo with HTML presentations (reveal.js) and pushes them to a Cloudfoundry install so users can view the latest version.

Since Concourse is only about teams, the pipelines end up on the level of my team. This creates confusion and clutter.

## What would make this better?

My suggestion would be to have a virtual team of "me" that you can set a (possibly limited?) amount of pipelines on. This would de-clutter the team level and still allow for longer running experiments, personal pipelines of various kind, etc.

There are multiple precedents for the idea, for example in the form of personal git repositories.

## Are you interested in implementing this yourself?

Unfortunately, this is probably beyond my capabilities in both knowledge and time. If I had more time, I could work on the associated learning curve and do this myself but sadly not an option for me at this time.

**Comment by mvdkleijn** [comment]
> What would determine if a user is able to do this? Currently you can only log in if you're part of a Concourse team, which doesn't necessarily imply that you can create your own pipelines independent of that team.

My initial thought would center around two simple options which could be used separately from each other:

1. A general setting: `enable_personal_pipelines` (boolean) or something to that effect.
    This would allow anyone who is able to login (fyi - we use an oauth server) to use personal pipelines with their virtual team called "me". (for example)

2. A more specific setting: `groups_allowing_personal_pipelines` (string or array) in the config.
    This would allow the admin to specify one or more groups whose members are allowed to use personal pipelines.

This second option is very similar to what we are doing now by limiting who belongs to a certain team with the set-team fly command: ```fly -t main set-team -n mywonderfullteam --oauth-group mywonderfullgroup```

**On the topic of creation and cleanup**

The system could create a new personal "team" named the same as the username, similar to how to can talk to yourself in Slack. :smile: 

Of course, if a user doesn't login for a long time, personal pipelines would clutter the system. To prevent this, admins could maybe set an "auto-expire time" that deletes a pipeline after a set amount of time of not having logged in.

**Comment by vito** [comment]
@mvdkleijn Because no one's doing anything about it! We adopted this policy because opening feature requests is cheaper than actually doing it, and as a result they just pile up.

I can re-open, but GitHub issues aren't a backlog that people go through and just implement. If you want to see activity on features you want, the best way is to get involved yourself. If no one is interested enough to keep the discussion going or start on a PR or RFC, there's not much reason to keep it open.

Here's a related issue that has had recent movement: #4510 - I actually mentioned 'personal pipelines' in my comment.

**Comment by mvdkleijn** [comment]
@vito Thanks for the clarification. I understand the reasoning. Also thanks for the additional mention. I'll try to see if I can contribute on a possible PR for this or for #4510, but my last attempt at doing a PR for Concourse was, frankly speaking, a horrible experience in several ways. Nevertheless, I'll make another attempt. :smile:

**Comment by evanchaoli** [comment]
@mvdkleijn It would be greatly appreciated if you can contribute a PR to #4510. After several PRs getting merged, I feel not bad with working on Concourse PRs. 😄

**Comment by vito** [comment]
@mvdkleijn I'd be happy to hear feedback about the PR process, we've been working on it a lot and using it ourselves so hopefully it's a lot easier than last time you tried. :slightly_smiling_face:

**Comment by mvdkleijn** [comment]
@vito I'd be happy to give you feedback. My last attempt was before the renaming / reordering of the repos so perhaps that'll be enough for me.
