### ISSUE TITLE
icons for unresolved step states on build page

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3022]
## What challenge are you facing?

While transitioning to the material design icon set in #2405, we noticed a lack of good icons to represent the following states for a step on the build page:
1. Pending - the build is currently running, but the step in question has not yet started.
1. Interrupted - the build stopped while the step in question was running.
1. Cancelled/Never reached - the build stopped before the step in question started.

## What would make this better?

Initial ideas are
1. Pending - circle?
1. Interrupted - dashed circle
1. Cancelled - circle with a diagonal line through it, like a "cancel" icon

## Are you interested in implementing this yourself?

👍

**Comment by pivotal-jamie-klassen** [comment]
Since were using the fontawesome icon `fa-circle-o-notch` for both pending build steps and unknown build preparation fields, it probably makes sense to reuse whatever the new icon for pending build steps is for unknown build preparation fields.

**Comment by Lindsayauchin** [comment]
<img width="797" alt="screen shot 2019-01-13 at 8 29 23 pm" src="https://user-images.githubusercontent.com/27746614/51093496-148ce780-1772-11e9-8ec3-0d2189137f66.png">
<img width="784" alt="screen shot 2019-01-13 at 8 29 35 pm" src="https://user-images.githubusercontent.com/27746614/51093499-18206e80-1772-11e9-8470-a71046882745.png">
<img width="804" alt="screen shot 2019-01-13 at 8 30 12 pm" src="https://user-images.githubusercontent.com/27746614/51093503-21114000-1772-11e9-8a63-74dc3bff05b7.png">
<img width="840" alt="screen shot 2019-01-13 at 8 30 00 pm" src="https://user-images.githubusercontent.com/27746614/51093504-253d5d80-1772-11e9-90cc-c147d0f4aed2.png">
