### ISSUE TITLE
Include team and tag in worker metrics

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3036]
## What challenge are you facing?

In our cluster, we created a special worker pool with extra CPU and RAM in order to run heavy pipeline task, like "mvn build". All workers in this special pool are tagged with 'B747'.

We emit metrics to InfluxDB and use Graphana to monitor metrics. For worker metrics, I want to separate normal pool and the special pool into different charts. But according to the code https://github.com/concourse/concourse/blob/master/atc/metric/metrics.go#L126-L129, Concourse doesn't include `tag` in worker metrics, so that we are not able to split worker metrics based on tag.

One of my team member is going to submit a pull request, that will include both `team` and `tag` in worker metrics. I'm creating this issue to track the change.

## Are you interested in implementing this yourself?

Yes

**Comment by cirocosta** [comment]
Hey @evanchaoli ,

Thanks for creating this issue!

I'd like to just add some two cents on the idea of having instead a separate metric that would output these extra informations.

<br />
From a Prometheus perspective, it seems fairly common to have a metric that exposes info about a particular instance/thing when you need to cross reference that later.

For instance, in the case of [`kubestate`](https://github.com/kubernetes/kube-state-metrics), there's [`kube_pod_info`](https://github.com/kubernetes/kube-state-metrics/blob/fd65206d7dbba19bbf78c6552375932447b80fc1/pkg/collectors/pod.go#L41-L66):

```
kube_pod_info{
	...
	namespace="kube-system",
	node="gke-cluster-1-preemptible-worker-pool-e3099e3f-6rd1",
	pod="kube-proxy-gke-cluster-1-preemptible-worker-pool-e3099e3f-6rd1",
	pod_ip="10.128.0.19",
	release="hush-house",
}	
```

Prometheus itself has `prometheus_build_info`:

```
prometheus_build_info{
	branch="HEAD",
	goversion="go1.11.3",
	instance="localhost:9090",
	job="prometheus",
	revision="dbd1d58c894775c0788470944b818cc724f550fb",
	version="2.6.0",
}	
```

That way, you can expose these extra information without having to add it to every metric, while still being possible to reference such when needed.

What I'm not sure, is if this is a common pattern in InfluxDB as well. Are you aware if that's the case? If so, WDYT about going through such direction?

Thx!

Any thoughts @marco-m ?

**Comment by marco-m** [comment]
Summoning @databus23 for Prometheus-fu

**Comment by evanchaoli** [comment]
@cirocosta thanks for your comment. I think InfluxDB is a time-serial DB, it just stores individual metrics. We use Telegraf to emit worker VM's cpu/memory/disk etc metrics to InfluxDB (Telegraf and InfluxDB are from same company), and Telegraf supports global tags, we put a worker's 'team' and 'tags' in Telegraf's global tags, so that every metric (cpu/memory/...) will contain 'team' and 'tags', so we can monitor a team/tag's workers in a separate chart on Graphana. We want Concourse to emit worker related metrics in same way.

@marco-m I don't think this request is a Prometheus related request. Can you please help review the pull request https://github.com/concourse/concourse/pull/3037?

**Comment by marco-m** [comment]
@evanchaoli the relationship with Prometheus is the following: Concourse emits metrics to various backends, among them Prometheus (which is a pull model) and InfluxDB (which is a push model).
If care is not applied when touching Concourse metrics, the result is that either Concourse requires to rewrite the same code per metric emitter, or, even worse, the different metric emitters report different values. This already happened in the past, and this is why @cirocosta is asking for my input. For additional background, see #2896.

**Comment by cirocosta** [comment]
Yeah, and I'm also afraid of is having those added to every metric that relates to a worker, which might increase soon as we tackle some more problems related to the operability of Concourse for more large scale use cases.

I'd just like to let that PR on hold a bit to gather some more thoughts around it from other folks 👍

**Comment by evanchaoli** [comment]
As PR #3037 has been merged, this issue is resolved.
