### ISSUE TITLE
Refactor ContainerProvider.FindOrCreateContainer

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#3043]
This story arose out of the discussion in #2926. 

As part of the refactor investigation, we noticed a number of issues revolving around `containerProvider.FindOrCreateContainer`. Namely,
* The method is hard to read and understand because of the number of conditions created by the existence of `CreatingContainer`, `CreatedContainer`, `gardenContainer`. 
* It is called from `gardenWorker.FindOrCreateContainer`, but then it also creates a `gardenWorker` which it uses to get the container image, which seems odd.

The objective for this story is to simplify `containerProvider.FindOrCreateContainer` and hopefully remove the need for a `gardenWorker` to be created.

**Comment by ddadlani** [comment]
This was completed by https://github.com/concourse/concourse/commit/4b1fb963dcae514fe70c7cc4b641cc42e9ce4dbc .

Here are some thoughts/observations that we encountered on the way:

* In `dbWorkerProvider.NewGardenWorker`, the `imageFactory` is now passed to the `gardenWorker` which allows us to get the image in `gardenWorker.FindOrCreateContainer` and eliminates the need to create a `gardenWorker` in containerProvider.FindOrCreateContainer`. However, `containerProvider.createGardenContainer` still calls `NewGardenWorker` which means that the `containerProvider` still needs to be passed an `imageFactory`. Hopefully this can be cleaned up as part of the ongoing refactor.

* To get rid of the `gardenWorker` in `createGardenContainer`, we would need to create the volumes at a previous stage and pass them in to `createGardenContainer` directly. This resonates with @pivotal-jwinters' comment in https://github.com/concourse/concourse/issues/2926#issuecomment-449149707

**Comment by ddadlani** [comment]
For posterity, here is a pseudocode explanation of what was changed in `containerProvider.FindOrCreateContainer`:

OLD containerProvider.FindOrCreateContainer:
in loop:
- finds created or creating container in db worker
- if created container != nil
	- looks up garden container
	- creates and returns gardenWorkerContainer
- if creating container != nil
	- looks up garden container
- if garden container == nil
	- if creating container == nil
		- creates creating container
	- acquires lock
		- if not, continues
	- fetches image
	- creates garden container from creating container
- creates created container from creating container	
- constructs and returns gardenWorkerContainer



NEW containerProvider.FindOrCreateContainer:
in loop:
- finds created or creating container in db worker
- if created container != nil
	- looks up garden container
	- creates and returns gardenWorkerContainer
- if creating container == nil
	- creates creating container

- look up garden container
	if garden container == nil
		- acquires lock
			- if not, continues
		- fetches image
		- creates garden container from creating container
- creates created container from creating container	
- constructs and returns gardenWorkerContainer

**Comment by marco-m** [comment]
Hello @ddadlani if I understand correctly this has been merged into master and can be closed, right ?

**Comment by ddadlani** [comment]
Hi @marco-m, yes, I think this was just overlooked :)
