### ISSUE TITLE
Decouple container and volume creation in FindOrCreateContainer

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#3052]
Related to #2926.

After #3043, [ContainerProvider.FindOrCreateContainer](https://github.com/concourse/concourse/blob/f4075856f392c5cdfee44fbf6e1cdb7b0f607fa9/atc/worker/container_provider.go#L93) is easier to read and part of its responsibilities have been moved to [Worker.FindOrCreateContainer](https://github.com/concourse/concourse/blob/f4075856f392c5cdfee44fbf6e1cdb7b0f607fa9/atc/worker/worker.go#L146)

However, there are still some redundancies:
1. [containerProvider.createGardenContainer](https://github.com/concourse/concourse/blob/f4075856f392c5cdfee44fbf6e1cdb7b0f607fa9/atc/worker/container_provider.go#L304) still creates its own `gardenWorker`
1. `containerProvider` and `gardenWorker` are both passed a `volumeClient`, `db.Worker`, `gardenClient` and `imageFactory`, despite the fact that the `ContainerProvider`'s two exposed methods are only called from the `gardenWorker`.
1. If, in the future, we want to create the volumes at an earlier stage in the process, we need to move volume creation up one level since currently it is deeply intertwined with container creation.

This issue is meant to capture the work required to untangle the functionality of `gardenWorker` and `containerProvider` and maybe reduce the responsibilities of `containerProvider` as well.

**Comment by ddadlani** [comment]
As part of the detangling, we moved all functionality of the `containerProvider` into the `gardenWorker`, however, this doesn't make it easier to remove the cyclic dependency. A lot of the logic requiring the `gardenWorker` in `containerProvider.createGardenContainer` is because of the creation or inflation of volumes, which requires a `gardenWorker`. This strengthens the argument for decoupling the volume lifecycle from the container lifecycle.

Currently, to create a db volume, you need a container ID, which means that the creation of a volume must come after the creation of a `creatingContainer`. Creating a volume without a container ID will cause the volume to be GCed because it is considered orphaned.

Our next steps will be to investigate adding lifecycle states and timestamps to the database `volumes` table. This may either be a separate `initializing` state, or a replication of the container lifecycle states (`creating`, `created`, `destroying`) depending on what works best. Volumes in the `initializing` or `creating` state would not be GCed. This would eliminate the need for a containerID in the volume.

This raises the following questions:
1. How will volumes and containers be associated, if not by a container ID? Can we perhaps use the `build` ID to associate both? What would be the added cost of running db queries for containers and volumes based on a common build ID?
2. What happens to volumes that remain `orphaned` because their associated container errored during creation? Should there be some cleanup logic based on the build ID if the build failed? Should we add a `state_changed_at` timestamp field and GC volumes whose state hasn't changed for x amount of time?

**Comment by ddadlani** [comment]
Some other work that would be needed to decouple the volume and container lifecycles:

1. Database migrations: the volume lifecycle states are currently represented as an enum `volume_state` in the database. This enum would need to be replaced in order to use the `attached` volume state.
2. A bunch of the `volume_repository` methods (which run database queries) would need to change to reflect this new lifecycle
3. GC needs to be changed to account for the new state
4. Volume creation can then be separated out from container creation in `worker.gardenWorker` or `containerProvider`, as the case may be.

**Comment by ddadlani** [comment]
Thoughts for continuing work later:
* Next step is to modify the methods in `volume_repository.go` to return attached vs created volumes where it makes sense
* For methods called through the API, we may need to also make changes to `fly` to show created vs attached volumes. One such method to consider is `GetTeamVolumes`.
* We need to add `build_id` and timestamp columns to the `volumes` table and modify GC to consider those.

This will allow us to create volumes before attaching them to the container to simplify container creation and task execution logic. The `build_id` is stored in the containerMetadata which is passed to the `worker.GardenWorker` in `FindOrCreateContainer`, so we can split that up to create volumes first and use the `build_id` to link volumes to containers before attaching them.

One possible problem may arise when trying to match a volume to a step, since each step runs in its own container. Investigation is pending.

**Comment by ddadlani** [comment]
Our previous strategy was to create a different `attached` state for volumes but that had a variety of repercussions:

* `Created` and `attached` states were very similar and the interface methods would need to be repeated anywhere created volumes were used.
* Adding a new state would drastically change volume GC and did not account for container creation failures occurring after the volume was created.
* Altering the volume state enum type would need to be done in a non-transaction DB migration, creating the possibility that databases might be left dirty if the migration failed.

To mitigate the GC issue, we considered adding a timestamp to `volumes` which would indicate an `expiry` time, i.e. if at expiry time, the volume did not have a container attached, the volume could be GCed. However, this forces the existence of a minimum time before volumes can get GCed and doesn't account for all cases i.e. ATC being down for a while, etc.

We are now investigating using `ContainerOwner`s as owners for both volumes and containers. Here is how GC works in different cases:
* If the volume has been created but the container doesn't exist yet, it shouldn't be GCed.
* If the volume is created and is attached to a container but the container is in use, it shouldn't be GCed.
* If the build passed or failed and the container has been GCed, the volume should also be GCed.

This means that if the `ContainerOwner` and `container` are both removed, the volume is safe to delete.

**Comment by ddadlani** [comment]
For now we are going with separating out container and volume creation from after the `creatingContainer` stage because there may be other changes in the future which direct any future decoupling work.

We are removing a loop in `FindOrCreateContainer` https://github.com/concourse/concourse/blob/b4b283d712ca07adf8cb6d3d51e55ed02b339651/atc/worker/container_provider.go#L111 which appears to be unused, from looking at the logs. There are also locks around scheduling and running builds which should enforce that only one ATC creates a specific container. 

However, we should ensure that we have an integration/top-level test that checks for race conditions in the case that multiple ATCs are trying to create the same container.

**Comment by ddadlani** [comment]
waiting on 5.0 release to merge

**Comment by marco-m** [comment]
@topherbullock @ddadlani is the `blocked` label still valid ? Asking since I see progress on branch `refactor/3052`. Does it refer to branch `issue/3052` which had last commit in 2019-02 ? Merci :-)
