### ISSUE TITLE
Concourse tasks fail with 'Failed to stream out from volume' error 

### ISSUE THREAD

**Issue by sprash98** [concourse/concourse#3061]
## Bug Report

I installed Concourse/Fly 4.2.2 on a Google Cloud VM, running CentOS 7. Prior to the install, I had upgraded the kernel to the latest version and installed postgres 9.6. After the installation, I set up the environment files for the web and worker services, and started them. Both of them are up and running and the UI is reachable via the external URL.  I then installed Docker and Docker compose (v 18.09) on the VM, configured a simple task based on the Concourse tutorial and ran it. I can see the docker image getting pulled, but the task(s) always fail(s) with 'failed to stream out from volume' error. 

I am a Concourse newbie, so any pointers would be great!

## Steps to Reproduce

This is my task:

`---
platform: linux

image_resource:
  type: docker-image
  source:
     repository: centos

run:
  path: ls
  args: [-a]`

[prashanth@concourse-ci ~]$ uname -r
4.20.2-1.el7.elrepo.x86_64

[prashanth@concourse-ci ~]$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

[prashanth@concourse-ci ~]$ docker --version
Docker version 18.09.1, build 4c52b90

## Actual Results

[prashanth@concourse-ci ~]$ fly -t test status
logged in successfully

[prashanth@concourse-ci ~]$ fly -t test e -c test.yml
executing build 11 at http://35.192.60.127:8080/builds/11
initializing
failed to stream out from volume
errored

When I look into /var/log/messages:

Jan 16 16:48:06 concourse-ci concourse_web: {"timestamp":"1547657286.078695536","source":"atc","message":"atc.create-build.running","log_level":1,"data":{"build":17,"job":"","pipeline":"","session":"2871"}}
Jan 16 16:48:06 concourse-ci concourse_worker: {"timestamp":"1547657286.109888792","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"4.2248","volume":"3af2ae87-99b4-4bde-7c61-d522e0373b6a"}}
Jan 16 16:48:06 concourse-ci concourse_worker: {"timestamp":"1547657286.109961748","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"5.1.527","volume":"3af2ae87-99b4-4bde-7c61-d522e0373b6a"}}
Jan 16 16:48:06 concourse-ci concourse_worker: {"timestamp":"1547657286.778207779","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"4.2250","volume":"c6654fd1-82af-4684-740b-413cddf488e3"}}
Jan 16 16:48:06 concourse-ci concourse_worker: {"timestamp":"1547657286.778265953","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"5.1.532","volume":"c6654fd1-82af-4684-740b-413cddf488e3"}}
Jan 16 16:48:07 concourse-ci concourse_worker: {"timestamp":"1547657287.324405432","source":"guardian","message":"guardian.create.start","log_level":1,"data":{"handle":"c88ab8a7-37df-4e57-68a0-bbad8fa8ad00","session":"298"}}

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Host is a VM on google cloud, running CentOS 7.6, kernel 4.20
* Browser (if applicable): Safari
* Did this used to work?

**Comment by vito** [comment]
Could you check for errors in the worker log that may be related?

**Comment by sprash98** [comment]
> Could you check for errors in the worker log that may be related?

Are they normally sent to /var/log/messages?

**Comment by sprash98** [comment]
I do see these there though:

Jan 16 16:42:17 concourse-ci concourse_web: {"timestamp":"1547656937.703443289","source":"atc","message":"atc.create-build.running","log_level":1,"data":{"build":14,"job":"","pipeline":"","session":"2574"}}
Jan 16 16:42:17 concourse-ci concourse_worker: {"timestamp":"1547656937.731833458","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"4.1961","volume":"c7c0e2f7-2129-4e0d-648b-382aa9a65f57"}}
Jan 16 16:42:17 concourse-ci concourse_worker: {"timestamp":"1547656937.731883287","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"5.1.448","volume":"c7c0e2f7-2129-4e0d-648b-382aa9a65f57"}}

**Comment by vito** [comment]
Not sure where the logs are - Concourse logs to stdout but I'm not sure where your stack redirects that.

Those logs don't look like a smoking gun - there should be another error logged when this error occurs, probably coming from baggageclaim.

**Comment by sprash98** [comment]
It looks like it's being dumped into /var/log/messages. And the only ones related to baggageclaim that I can find are these :

Jan 16 19:21:50 concourse-ci concourse_worker: {"timestamp":"1547666510.896482468","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"5.690","volume":"d67e1f50-5567-4be8-4432-7e9ce35bfcfb"}}
Jan 16 19:21:50 concourse-ci concourse_worker: {"timestamp":"1547666510.896529913","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"6.1.138","volume":"d67e1f50-5567-4be8-4432-7e9ce35bfcfb"}}
Jan 16 19:21:51 concourse-ci concourse_worker: {"timestamp":"1547666511.489358425","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"5.692","volume":"37035b54-5932-438c-5131-75cc2e555362"}}
Jan 16 19:21:51 concourse-ci concourse_worker: {"timestamp":"1547666511.489412069","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"6.1.143","volume":"37035b54-5932-438c-5131-75cc2e555362"}}

**Comment by vito** [comment]
Hmmm maybe your kernel doesn't have user namespaces enabled? I believe that's a requirement.

**Comment by sprash98** [comment]
Yes, there was that, and the issue of SELinux as well. After configuring namespaces and rebooting the instance (along with disabling SELinux), I don't see this issue anymore. This is off-topic, but I have SSH keys required for git to clone my repo that is on bitbucket. I can manually run git clone using the private key and get the repo on my box, but when I do it through the resource section of my pipeline, it says that the host key is invalid. Should I have to explicitly specify the private key someplace in the yml file?

`- name: demo
  type: git
  source:
    branch: master
    uri: git@bitbucket.org:<path-to-repo>`

**Comment by vito** [comment]
Yep, it's configured as `private_key` under the source:

https://github.com/concourse/git-resource

Gonna close this since the original issue has resolved. I'd suggest using the [forums](https://discuss.concourse-ci.org) for support in the future - issues are meant for bugs/feature requests.

**Comment by sooraj-sky** [comment]
Facing the same issue on M1 Mac
