### ISSUE TITLE
Quick start example fails (must be run as root)

### ISSUE THREAD

**Issue by mdhender** [concourse/concourse#3065]
The command given in the quick start section fails to run on Linux.

```
$ concourse quickstart \
  --add-local-user myuser:mypass \
  --main-team-local-user myuser \
  --external-url http://my-ci.example.com \
  --worker-work-dir /opt/concourse/worker

{"timestamp":"1547670117.530842304","source":"worker","message":"worker.setup.already-done","log_level":1,"data":{"session":"1"}}
worker must be run as root
```

The error message is understandable and it's easy enough to add `sudo` to it, but starting off the example with a failure seems odd. The postgres issues are at least mentioned (though it'd be nice to at least hint at `createdb atc` for the casual developer that just installed postgres to "kick the tires").

**Comment by vito** [comment]
Ah, yeah good point. FWIW the source for the docs is https://github.com/concourse/docs if you're interested in a quick PR.

**Comment by mdhender** [comment]
Do I need to move this issue over to the docs repo?

**Comment by vito** [comment]
@mdhender Nah that's ok, thanks for the PR!
