### ISSUE TITLE
Human-readable timestamps in logs

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3069]
## Bug Report

A concourse log line is like:

    {"timestamp":"1547682843.011340380","source":"tsa","message":"tsa.connection.channel.sweep-containers-worker.finished-getting-sweep-containers","log_level":1,"data":{"handles":"[]\n","remote":"10.163.95.58:59527","session":"244619.1.1"}}

The `timestamp` only shows seconds, which doesn't make much sense for debugging. Say we obverse a failure, and want to check ATC log around the time when the failure occurs, but it's very hard because `timestamp` in log is not obvious.

## Expected Results

Expecting log lines to contain human readable `YYYY-MM-DD hh:mm:ss TZ` formatted timestamp.

## Version Info

* Concourse version: 4.4.2

**Comment by vito** [comment]
I mean, it's a UNIX timestamp, which...makes sense, but I agree it could be prettier. In any case, this is not a bug.

**Comment by marco-m** [comment]
I was playing around with `jq`, I think there is a way to invoke its `todateiso8601` function to convert on the fly, but than I ran out of time tinkering.

**Comment by evanchaoli** [comment]
@vito  I just raised a PR https://github.com/concourse/flag/pull/3, please help review it. This is a single line code change in Concourse/flag, after the commit, logs will look like:

    {"timestamp":"2019-01-28T03:34:01.843406000Z","level":"error","source":"atc","message":"atc.sky.login.failed-to-parse-claims","data":{"error":"square/go-jose: error in cryptographic primitive","session":"5.3"}}
