### ISSUE TITLE
Couldn't fly login by ldap username & password direct login same as basic auth

### ISSUE THREAD

**Issue by devindaiyu** [concourse/concourse#3089]
* Concourse version:4.2.2
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):Google Chrome
* Did this used to work?

When I use command `fly --target "target" login --concourse-url "https://concourse.concourse.com" -k -u "ldapusername" -p "ldappassword"` to login concourse by using  ldap username & password, I got the below error:
```
error: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"access_denied","error_description":"Invalid username or password"}
```
I checked the code and found that only local authentication is supported. How can I use ldap username & password to login concourse by fly login  direct login same as basic auth.?

**Comment by devindaiyu** [comment]
> https://discuss.concourse-ci.org/t/how-to-set-ldap-auth/820/7

I could fly login by access the callback URL and enter the ldap username and password then successfully login and return to fly. I want to use ldap username and password direct login same as basic auth.

**Comment by vito** [comment]
That is currently not supported. Sounds like a feature request?

**Comment by devindaiyu** [comment]
> That is currently not supported. Sounds like a feature request?

I have raised the feature request https://github.com/concourse/concourse/issues/3096

**Comment by vito** [comment]
Thanks!
