### ISSUE TITLE
fly login by ldap username & password direct login same as basic auth

### ISSUE THREAD

**Issue by devindaiyu** [concourse/concourse#3096]
When I use command `fly --target "target" login --concourse-url "https://concourse.concourse.com" -k -u "ldapusername" -p "ldappassword"` to login concourse by using ldap username & password, I got the below error:

```
error: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"access_denied","error_description":"Invalid username or password"}
```

I checked the code and found that only local authentication is supported. How can I use ldap username & password to login concourse by fly login direct login same as basic auth.? such as 

`fly --target "target" login --concourse-url "https://concourse.concourse.com" -k --ldapusername "ldapusername" --ldappassword "ldappassword"
`

**Comment by predatorian3** [comment]
I get the same for GitHub OAuth. I imagine that its because its trying to use local auth, instead of trying to use the provider.

**Comment by Fahrenholz** [comment]
That would be a really useful feature!

**Comment by deadlysyn** [comment]
we hit this at a customer site...this would be a nice feature to have, or better understand why we shouldn't have it :-)
