### ISSUE TITLE
topgun/k8s: ensure container limits work

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3102]
When not running on top of BOSH, we lack some of the control we have over base VM image (in our current testing infrastructure - [GKE](https://cloud.google.com/kubernetes-engine/) -, there's no such thing as our use of [Stemcells](https://bosh.cloudfoundry.org/docs/stemcell/)), which might be a problem for the way we set container limits as it might be the case that certain platforms don't enable things like cgroup swap accounting (e.g., see https://github.com/Azure/acs-engine/issues/3107).

Going with an approach like we do for baggageclaim drivers (see https://github.com/concourse/concourse/blob/1b1b9ef171f7bc3fbb81e27fa7afa256a3c707b0/topgun/k8s/baggageclaim_drivers_test.go#L90-L119) where we explicitly test the behavior for each possible VM image in GKE (Ubuntu and [Container Optimized](https://cloud.google.com/container-optimized-os/)), we can be more sure about how our platform coverage looks like.

**Comment by YoussB** [comment]
@pivotal-bin-ju & I have created the needed tests, but it looks like setting `cgroups` configs for ubuntu is unsupported.

we got the following error:
```
runc run: exit status 1: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 1073741824 to memory.memsw.limit_in_bytes: open /sys/fs/cgroup/memory/garden/105b72a1-4b41-4c9c-5229-a651fc9590ee/memory.memsw.limit_in_bytes: permission denied\\\"\""
```
Do you know if there is anything that we might be missing?
@cirocosta @topherbullock 

will also push the changes to a feature branch `feature/3102-container-limits` so you can take a look.

thanks!

**Comment by cirocosta** [comment]
The results @YoussB mentioned seems related to https://github.com/concourse/concourse/issues/3055 🤔
