### ISSUE TITLE
`fly execute -o` fails if the build takes longer than an intermediary routing tier's idle timeout

### ISSUE THREAD

**Issue by zaksoup** [concourse/concourse#311]
Fly CLI panics and crashes and burns and cries and you get the point when you're using `--output` on a concourse behind an ELB with a timeout shorter than the task you're running.

**Comment by joharohl** [comment]
I have the same type of issue. Just wanted to share. We are using 2.0.1 behind an nginx proxy for ssl and to serve additional content. When running a single task using `fly execute` trying to save nginx closes the connection if it takes longer than the `proxy_read_timeout` timeout. 

I'm not an expert at proxies, but it seems to me that concourse is setting up a connection for sending the output data when the task starts and then waits for the task to finish. If the connection was made at the end of the task instead, it would not trigger the timeout. No idea how hard it is to fix though...

**Comment by vito** [comment]
This is fixed now that we have 'user artifacts', which `fly` downloads after the build finished rather than starting an idle request when the build starts. (/cc @pivotal-jwinters )
