### ISSUE TITLE
asset path broken on 401 page

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3118]
the browser is trying to display `images/passport_officer_ic.svg`, but we renamed it to `passport-officer-ic.svg` [here](https://github.com/concourse/concourse/commit/b58e7f7461d5ec2bdceb180b37f1f7b5d0e98e5d) while working on #2405. Broken image is ugly.
![screen shot 2019-01-22 at 9 27 01 am](https://user-images.githubusercontent.com/22056320/51541875-ebcab900-1e27-11e9-88ee-914358c8658c.png)

**Comment by vito** [comment]
Should we do one big `grep` for asset paths with an underscore? Seems like there have been a lot of loose ends.
