### ISSUE TITLE
read: connection reset by peer (in get step of pool-resource)

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#312]
Get http://<ip>:<port>/volumes?initialized=yep&resource-params=<some_hash>&resource-source=<another_hash>&resource-type=pool&resource-version=<yet_another_hash>: read tcp <same_ip>:<different_port>-><same_ip>:<original_port>: read: connection reset by peer

**Comment by vito** [comment]
Gonna need a lot more info. That URL looks bogus.

**Comment by xtreme-gavin-enns** [comment]
I fixed the markdown in the original message. I didn't recognize the hashes in the url so I redacted them all. If it helps to see more details I can message you privately
