### ISSUE TITLE
Investigate ATC memory leak

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3140]
This doesn't look good:

https://metrics.concourse-ci.org/dashboard/db/concourse?panelId=12&fullscreen&orgId=1&var-deployment=prod&from=1546962810917&to=1548280902604

Here's a mirror for posterity: https://snapshot.raintank.io/dashboard/snapshot/Rtcom5elFWfdRCHKZn8Si6dfwn4xfjH5

Let's pop open the profiler and see where this memory is being used. There's one known issue regarding leaked connections (#3132) - but I'm not sure if that's all it is.

**Comment by cirocosta** [comment]
Yeah, saw this in hush-house sometime ago as well:

<img width="767" alt="memory-increasing" src="https://user-images.githubusercontent.com/3574444/51640701-3a647a00-1f32-11e9-8dab-a0457a0f1489.png">

**Comment by vito** [comment]
Noticed that https://github.com/concourse/concourse/issues/3132 does at least leak a cert pool along with each connection, which contributes to the leak. But if this is still happening in an environment without syslog draining configured, there may be more to look into.

**Comment by vito** [comment]
Attaching a heap dump from ~1 hour after the deploy:

[heap-before.gz](https://github.com/concourse/concourse/files/2809618/heap-before.gz)

**Comment by vito** [comment]
This is looking a lot better now with the syslog leak fixed:

![screenshot from 2019-02-01 14-47-44](https://user-images.githubusercontent.com/1880/52145943-5d78e300-2630-11e9-84bc-59e3daa9bc40.png)

https://snapshot.raintank.io/dashboard/snapshot/Y3vooyBszNLgqf74cut3fwpGY7KVGhT8

There's still a gradual leak but looking at the heap dumps so far I'm not seeing something immediately obvious. One thing to note is that we have a few pipelines configured with frequently-firing `time` resources, which will cause memory usage to grow over time because `LoadVersionsDB` loads every version into its head. Note that the initial memory use post-deploy is already higher than it was at the beginning of the previous deploy, possibly due to there just being more versions.

Will leave this to sit over the weekend just to make any leaks more obvious to the eye.

**Comment by vito** [comment]
@cirocosta Is there a goroutine metric for hush-house? Maybe something to keep an eye on.

**Comment by vito** [comment]
I think this can be closed now - looks like syslog was the culprit, as shown by the deploys with the fix:

https://snapshot.raintank.io/dashboard/snapshot/P81P2q8vltvc8O07KsEnlIIXEwVBLrOc?panelId=12&fullscreen&orgId=2

If there's any remaining leak it's very very slow; there hasn't been a significant increase over ~3 days.
