### ISSUE TITLE
Support large JWT token in web UI

### ISSUE THREAD

**Issue by making** [concourse/concourse#3141]
## Bug Report

Currently web UI stores a JWT in cookie (`skymarshal_auth`). Most browsers support cookies of up to 4096 bytes.
If JWT is too large, access to `/sky/userinfo` returns 401 since `skymarshal_auth` is not stored in the cookie. Authentication itself succeeds but the user cannot see any information related to the user in Web UI.
This can eventually happen when the number of teams the user belongs is increasing in a large foundation since a JWT contains all team names.
We saw this issue when then number of teams was more than 200. Concourse operators belonged to all teams.

## Steps to Reproduce

1. Assign a lot of teams to a user that makes the size of JWT over 4096 bytes.
1. Login to the Web UI. Log message says "Login successfully" but user info does not show in the UI. (`fly login` works)

## Expected Results

User info can be seen in Web UI regardless of the size of JWT.
I'd suggest to use LocalStorage instead of cookies. 

## Actual Results

User info can not be seen in Web UI if JWT cannot be stored in cookie.

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: OpenStack
* Browser (if applicable): Chrome / Safari / Firefox

**Comment by pivotal-jamie-klassen** [comment]
Related: #2936

**Comment by cirocosta** [comment]
Hey @vito, 

we've decided that we want to take a look at this and https://github.com/concourse/concourse/issues/3853  - it's currently in the Backlog of API - is that a problem?

Thanks!

**Comment by vito** [comment]
@cirocosta :turtle: Nope, go ahead!

**Comment by lrstanley** [comment]
Looks like there are still issues with the approach in #4280 with the fly cli. Using concourse v5.6.0 and fly v5.6.0, when running fly from a remote environment and a user has a massive amount of teams, copying the token from the browser leads to fly returning `could not find a valid token`. Unfortunately we run most of our commands from an external environment, from where our browser is located. Guessing this got looked over as it's probably not too common.

Example:

```
[...]
navigate to the following URL in your browser:

  https://concourse-env.domain.com/login?fly_port=46428

or enter token manually: Bearer <my-massive-token-here>

could not find a valid token.
logging in to team 'myteam'

navigate to the following URL in your browser:

  https://concourse-env.domain.com/login?fly_port=46070
<hangs>
```
Another issue is the bug I created in https://github.com/concourse/concourse/issues/4298 which the fly cli hangs when attempting to login to various things (if logged in in the past and the token expired). If the first command being used isn't a login, it prompts for the url to be put into your browser but doesn't have an input prompt to paste a token.

**Comment by pivotal-jamie-klassen** [comment]
@lrstanley yep, the fix was intentionally focused on the web and local fly login flows to keep the scope smaller (we wanted to deliver it pretty quickly!). Your edge case (at least on Darwin) is described in a fair amount of detail in #4339, but if you have other details to share, please add them there! The root cause is a hard-coded buffer size on the STDIN stream of the fly process. The full-time Concourse team probably won't have bandwidth to address that any time soon, but if you wanted to approach it there might be workarounds (some discussed [here](https://superuser.com/a/219304)). Probably in the long-term it's worth thinking about how to actually make the tokens smaller.

**Comment by lrstanley** [comment]
The above was experienced on a rhel7 linux box. I don't think it's an edge case, it's actually very common, as I've seen others frequently use this in other reported issues.

Making the tokens smaller isn't a solution, it's a bandaid to a bug. We have over 1200 pipelines in our dev environment, and 500-600 in our higher environments. The thought of shoving all of those pipelines into fewer teams makes me want to drink more alcohol.

**Comment by pivotal-jamie-klassen** [comment]
@lrstanley I don't say 'edge case' to suggest your scenario is unimportant. It's definitely a full feature that we designed and I'm not trying to say you're using it by accident. I guess I could have chosen more neutral language, but my purpose was just to illustrate a scenario that involved similar constraints and to give you as much context as possible to help you (or anyone reading) have the tools to ease this pain on behalf of everyone! When I said 'if you wanted to approach it', I was talking about you issuing a PR to Concourse.

As for the 'making tokens smaller' I was not implying that _you_ need to have fewer teams, I was again speaking to the audience of Concourse contributors to say that Concourse needs to produce smaller tokens! There's no reason the token size needs to scale with the number of teams - the choice to serialize all team memberships into the token was definitely made too lightly without regard to these scenarios. At least amongst the full-time Concourse contributors, something like 
#2936 could be a path to the 'solution'.
