### ISSUE TITLE
At Login, Do Not Display Username/Password If No Local Users Configured

### ISSUE THREAD

**Issue by jasonmfehr** [concourse/concourse#3149]
## What challenge are you facing?
Our Concourse deployment started with local auth.  We have since switched to using OIDC and have removed all local users created at start up using the `--add-local-user` flag on the `web` node.  We also removed the `--main-team-local-user` flag.  We then went in and re-set up all teams so that they do not have a local user assigned.  When logging in to the Concourse web ui, it still shows "Username/Password" as an option for logging in.

## What would make this better?
We would like for the "Username/Password" option to be hidden on the login screen and either our OIDC provider used automatically or be listed as the only option.

## Are you interested in implementing this yourself?
Possibly.  I would need to know that this feature is approved for implementation before starting development.

**Comment by vito** [comment]
Hmm sounds like that could be a bug. Definitely seems like it shouldn't be showing that prompt if there are no local users configured anymore. I wonder if it's not clearing them out or something?

**Comment by vito** [comment]
@vito Maybe check the `password` table? That seems to be where users are stored.
