### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3155]
### Native modules to ports

Let's really try to add some certainty around these things. Adding unit tests for the JS side of the ports would be good if possible, or else enough watsjs tests to protect against regressions.

- [x] EventSource
- [x] Favicon
- [x] Redirect
- [x] Scroll

### Dependencies

* We have a bunch of different approaches to URL parsing throughout the codebase, and my hope is that we can standardize on one. Specifically, whichever is easiest to migrate to https://github.com/elm/url.

@mhuangpivotal has done some investigation here and I invite him to add comments.

### Tests
A bit of uncertainty here, but I believe https://github.com/elm-explorations/test is the new standard for tests, and we'll see what the new equivalents for the elm-html-test functions are.

**Comment by mhuangpivotal** [comment]
In additional to porting the native modules, there are a few incompatible dependencies we'll need to update/replace. Some standard modules will also require code update.

### dependencies
- [ ] Bogdanp/elm-querystring
- [ ] Bogdanp/elm-route
- [x] chendrix/elm-matrix
       - only `Grid.elm` uses this and `Grid.elm` is not used
- [ ] elm-lang/websocket
- [ ] mgold/elm-date-format
- [ ] sporto/erl
- [x] vito/elm-ansi

### code changes
- elm/browser
  - [ ] Change code using AnimationFrame.* to use Browser.Events.onAnimationFrame*
  - [ ] Change code using Navigation.program* to use Browser.application
  - [ ] Use the Browser.Key passed to your init function in any calls to Browser.Navigation.pushUrl/replaceUrl/back/forward
  - [ ] Change code using Window.* to use Browser.Events.onResize
- elm/core
  - [ ] Replace uses of toString with String.fromInt, String.fromFloat, or Debug.toString as appropriate
- elm/time
  - [ ] Replace uses of Date and Time with Time.Posix
- elm/html
  - [ ] If you used Html.program*, install elm/browser and switch to Browser.element or Browser.document
  - [ ] If you used Html.beginnerProgram, install elm/browser and switch Browser.sandbox
- elm/url
  - [ ] Changes uses of Navigation.Location to Url.Url

**Comment by pivotal-jamie-klassen** [comment]
elm-lang/websocket is unused

**Comment by pivotal-jamie-klassen** [comment]
It probably makes sense to try to cut over from our native Scroll module to [Browser.Dom](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#getViewport) -- hoping that our watsjs tests keep our confidence up for this part.

**Comment by Twiknight** [comment]
`evancz/url-parser` seems not to have a 0.19 build, so probably it should be replaced?

**Comment by pivotal-jamie-klassen** [comment]
@Twiknight yeah, our thinking was that, of all the url/route-related libraries we were using/were available, `evancz/url-parser` had an API most similar to [`elm-url`](https://package.elm-lang.org/packages/elm/url/latest/Url), which hopefully makes for an easier transition.

**Comment by pivotal-jamie-klassen** [comment]
The technology we have been using to query/report visibility of DOM nodes is a bit kudgey. Hopefully https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#getElement can save us once we upgrade.

**Comment by pivotal-jamie-klassen** [comment]
While I'm thinking about it, I want to mention that using a lighter-weight method for querying element visibility might make for a good partial approach to optimize loading build logs (cf #3521, #3499)
