### ISSUE TITLE
Docker Toolbox can't connect to gitlab Docker registry

### ISSUE THREAD

**Issue by MrMedTech** [concourse/concourse#3157]
Hi
I developed a Microservice Architecture and now I want to deploy it on an external vm in our local vpn Network.
I developed with spring boot in windows 10. Because of having trouble with the hypervisor I changed to docker toolbox. I can build my Images und run a local docker compose.
Now I want to push my images to the git lab docker registry in our vpn network. 
Therefor I tried to follow the git lab documentation and tried
`docker login IP:PORT`
after that I have to enter my credentials.
The error I get is:
`Error response from daemon: Get https://ip:port/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

I tried to add 
```
{
    "insecure-registries" : [ "ip:port" ]
}
```
in the deamon.json.
But also after a restart, nothing happens.
I can ping the url from within my Docker quickstart terminal but a connection is not possible.
is there maybe some extra configuration to do?
Thx in advance

**Comment by haseebr** [comment]
have you tried setting a proxy on the machine ? 

https://docs.docker.com/network/proxy/

**Comment by MrMedTech** [comment]
Thank's for the hint.
I wasn't able to find a deamon.json file so I created one in 
`C:\ProgramData\Docker\config\deamon.json`
Don't know if this is the right way.

**Comment by vito** [comment]
Hi - we use issues for feature requests and bug reports, but this looks more like a support request/question - please consider using our [forums](https://discuss.concourse-ci.org) instead.
