### ISSUE TITLE
Resource metadata can squish build output when text is too long

### ISSUE THREAD

**Issue by sohrab-** [concourse/concourse#3164]
## Bug Report

In the step (via web ui), when I expand the git resource section, the panels are splitting strangely. Note the log panel vs the commit info panel in below screenshots (half width and full width respectively).

![image](https://user-images.githubusercontent.com/4444588/51907082-f71a7780-2419-11e9-8cfe-9256aa89a820.png)

![image](https://user-images.githubusercontent.com/4444588/51907108-04cffd00-241a-11e9-8ad8-2516d1d6e782.png)

## Steps to Reproduce

1. Start Concourse via docker-compose: https://concourse-ci.org/docker-compose.yml
1. `git clone https://github.com/starkandwayne/concourse-tutorial.git`
1. `cd concourse-tutorial/tutorials/basic/pipeline-resources`
1. `fly --target tutorial login --concourse-url http://127.0.0.1:8080 -u test -p test`
1. `fly -t tutorial sp -c pipeline.yml -p hello-world`
1. `fly -t tutorial up -p hello-world`
1. Navigate to the build that ran in the web ui

Reproduced in both Chrome and Safari.

## Expected Results

For the resource section in the web UI to not look weird

## Actual Results

The resource section in the web UI _does_ look weird

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Local (MacOS)
* Browser (if applicable): Chrome 71.0.3578.98 / Safari 12.0.3 (13606.4.5.3.1)
* Did this used to work? Yes, it used to not look weird

**Comment by sohrab-** [comment]
Ok, it looks like it has to do with the long commit messages. Should this wrap around?

![image](https://user-images.githubusercontent.com/4444588/51908715-ae18f200-241e-11e9-93f9-6a9bd4e2531b.png)

**Comment by vito** [comment]
Yep, we could probably word-wrap the metadata instead of squishing the output.

**Comment by deniseyu** [comment]
Looks like this has been fixed and released in 5.0.0.

**Comment by cirocosta** [comment]
Indeed! Thanks, @stigtermichiel !

<img width="1757" alt="Screen Shot 2019-05-17 at 8 35 55 AM" src="https://user-images.githubusercontent.com/3574444/57928486-de29bb00-787e-11e9-8420-8514833221ca.png">
