### ISSUE TITLE
Resource types displayed on details page

### ISSUE THREAD

**Issue by osis** [concourse/concourse#3169]
<img width="1041" alt="screen shot 2019-01-29 at 3 46 08 pm" src="https://user-images.githubusercontent.com/347097/51939335-37a7d000-23dd-11e9-8dc2-d309c3f410df.png">

## What challenge are you facing?

It's hard to tell what resource type a resource is when looking at the resource details page.

## What would make this better?

It would be great to display a resource's current type in the web UI so all context is available. Right now, putting types in the resource name is the way you provide context to the metadata display on that page.

## Are you interested in implementing this yourself?

Heck yaw!

/cc @ddadlani

**Comment by marco-m** [comment]
Very similar to #788.
FYI, GoCD uses icons for resources like a git repo (they call these resources "material"). 

It would be super nice to have icons for the resources, instead of doing workarounds such as calling resources `foo.git`, `bar.s3` and so on.

See for example
![gocd-value-stream](https://user-images.githubusercontent.com/3075069/51964629-6bc7d300-2467-11e9-8449-c82e45c1fcb1.png)

**Comment by Lindsayauchin** [comment]
## Proposed Design:
### Resource View
![screen shot 2019-02-06 at 5 09 36 pm](https://user-images.githubusercontent.com/27746614/52377160-08730d80-2a32-11e9-87dd-1e64cfeac9f0.png)

 Small svg icon set packaged in the release that users would configure in their yml? Displayed before a Resource name on that page and also on the pipeline view on the Resource. 

### Pipeline View

![screen shot 2019-02-06 at 5 09 30 pm](https://user-images.githubusercontent.com/27746614/52377407-ce563b80-2a32-11e9-82aa-f400f5e38f65.png)

**Comment by marco-m** [comment]
@Lindsayauchin yes yes yes 💯 thanks!

**Comment by astromoose** [comment]
@Lindsayauchin would the svgs be baked into the resource image? That would be neat :)

**Comment by Lindsayauchin** [comment]
@mockersf fixed this with #3581!
