### ISSUE TITLE
Single-page docs would be pleasant

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#317]
http://concourse.ci/ Would be more of a delight if all the text were on one page, and the sidebar dynamically highlighted the section I was in (e.g. the [Stripe API docs](https://stripe.com/docs/api)).

This would 1) allow me to search for text very simply (even though the Concourse search box is fantastic) 2) lazily scroll through to find information and 3) remove inconsistencies in presentation (e.g. http://concourse.ci/concourse-vs.html uses subheaders to navigate within a single document, but http://concourse.ci/concepts.html uses them to navigate between documents).

**Comment by vito** [comment]
We now generate a single-page form in addition to the existing form (which I still prefer for linking): https://concourse.ci/single-page.html - reachable via a link tucked below the search field for now (seemed like the most practical place).

**Comment by wendorf** [comment]
Looks great! Thanks!
