### ISSUE TITLE
Expose build info ENV to task

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3179]
## What challenge are you facing?

I found same feature request had been closed https://github.com/concourse/concourse/issues/494. But I'd like to raise this again.

Many tasks need build info, like job name, build id, etc, in order to generate notification message, docker-image tag, etc.

As build ENV variables are only seen in `get` and `put`, we now have to use a resource to generate a env file via `get`, then `source the_env_file` in task, which just adds complexity of pipeline.

I don't see any harm of exposing build ENV variables to tasks. Is there any consideration of not doing so?

**Comment by vito** [comment]
This won't be added, and the reasoning is documented [here](https://concourse-ci.org/implementing-resources.html#resource-metadata) - though admittedly that's kind of hard to find in the docs.

**Comment by ADustyOldMuffin** [comment]
I'm going to pop in here and say the reasoning of 

> They should not be used to emulate versioning (e.g. by using the increasing build number). They are not provided to task steps to avoid this anti-pattern.

Is a terrible reason to not do this. There's plenty of use cases around building messages and other things from the resulting build besides just versioning, and even if being used for versioning I'd say it's up to the user not the pipeline to worry about it.

**Comment by clarafu** [comment]
@ADustyOldMuffin The reason why it is an anti-pattern is because we want to keep Concourse as stateless as possible. This comment (especially case 3) https://github.com/concourse/concourse/issues/3325#issuecomment-465401803 explains the reasoning for this design decision in further detail.
