### ISSUE TITLE
Support variable substitution in task file

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3180]
## What would make this better?

When we use `-v` or `-l` to pass some variables to `fly set-pipeline`, those variables can be properly substituted in the entry YAML file, but variables in task files cannot be substituted. (We noticed that if a variable can be found in Vault, then it can be substituted in task file.)

The use case of one of our users. The product has a lot of Git repos, each Git repo needs a CI pipeline, all pipelines are similar. So the pipeline admin wants to template those pipelines via variables. But a problem the user facing is that, variables defined in task files cannot be substituted. 

## Are you interested in implementing this yourself?

Yes

**Comment by vito** [comment]
This is already done via #2770 and will be in 5.0
