### ISSUE TITLE
Support team hierarchy

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3182]
## What challenge are you facing?

Concourse now supports only one layer of teams. Here are some use cases that multi-layer teams would be helpful:

Use case 1. A big organization has many team, the directory who manages all the teams wants to overview status of all teams' pipelines. Now we have to add the directory to all teams. If multiple layers of teams is supported, we may just added the directory to a parent team, so that he can access all child teams' pipelines.

Use case 2. Still, A big organization has many team. We want to create a worker pool that can be shared by all teams of the organization (because all teams' budges are from this organization). Current concourse seems to have no way to archive that, only workaround I can come out is to use tag. But tag has no authorization. If multiple layers of teams is supported, we may create a worker pool to parent team (organization), then all child teams will consume workers from the pool.

This is an initial idea, no design yet. Calling for thoughts and comments.

**Comment by vito** [comment]
@pivotal-jwinters this sounds kinda RBAC-related

I think there's a bit more subtlety in what you're proposing. The two use cases sound interesting but I wonder if there's some other way to accomplish them - perhaps they should just be their own issues?

For example, maybe RBAC for worker access or something would work for the second use case. I worry that making the teams themselves hierarchical might make things a bit more complicated in other sensitive areas.
