### ISSUE TITLE
Trigger and abort button feedback

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#3185]
I'm not sure if I'm just used to the old design but I feel like the new trigger button color might make it look a little too separated from the job itself? 🤔 

<img width="1391" alt="screen shot 2019-01-31 at 12 14 47 pm" src="https://user-images.githubusercontent.com/19290703/52072223-9773b780-2552-11e9-9465-08ae1ec06924.png">

I think I might feel this way because the color of the button is the same as the grey page background and it makes the button seem disconnected or less important.

Another thing I noticed was when I trigger a new build, the abort button appears to the left of the trigger button. 

<img width="1397" alt="screen shot 2019-01-31 at 12 32 36 pm" src="https://user-images.githubusercontent.com/19290703/52083012-538dac00-256c-11e9-8064-23ce0c8d705e.png">

![job](https://user-images.githubusercontent.com/19290703/52083957-e891a480-256e-11e9-9aef-fcc5a288392d.gif)

I was wondering if we can make it a bit more scary or more obvious that it is a completely different button from the trigger one because at a quick glance it might seem quite similar but the abort button results in a destructive action.

cc @Lindsayauchin @vito 

Thanks! 👍

**Comment by clarafu** [comment]
I had a chat with @pivotal-jamie-klassen and he explained to me a bit more about the design decisions behind these changes. For the button being separated by the job/build header bar, this might be leading into the issue with adding a running state to the header bar. We also agreed that we could explore the possibility of adding some red colour to the abort button in order to make it more alarming to the user.

**Comment by Lindsayauchin** [comment]
@clarafu the thought behind the design was to make the icons move button like. Maybe we could take the design a step further in that direction with background colours and hover states on not only the icon but the background so, that we are clear that these are buttons. Thoughts? 

![screen shot 2019-02-15 at 11 57 52 am](https://user-images.githubusercontent.com/27746614/52871829-f28fd780-3118-11e9-9e30-28069eb9ccf2.png)

![screen shot 2019-02-15 at 11 57 24 am](https://user-images.githubusercontent.com/27746614/52871800-e3a92500-3118-11e9-965e-43bc6a4d5c03.png)

**Comment by Lindsayauchin** [comment]
Looks good on the builds page as well. 
![screen shot 2019-02-15 at 4 09 50 pm](https://user-images.githubusercontent.com/27746614/52884646-88892980-313c-11e9-81a9-4074db6a330f.png)

**Comment by clarafu** [comment]
@Lindsayauchin I see, the consistent style in buttons totally makes sense. The darker colour on the buttons and the red on the abort button does look really good! I really like it! ❤️

**Comment by pivotal-jamie-klassen** [comment]
After @vito's feedback [here](https://github.com/concourse/concourse/pull/3436#pullrequestreview-212585712), we're going to switch to a design like

![Screen Shot 2019-03-11 at 11 23 10 AM](https://user-images.githubusercontent.com/27746614/54135755-c8b49280-43f0-11e9-8acd-2f9dba110754.png)
