### ISSUE TITLE
support for bool and int parameters 

### ISSUE THREAD

**Issue by longnguyen11288** [concourse/concourse#32]
This is from using `--vars-from`

Use case:
With cred.yml file
```
cf-api: https://api.10.244.0.34.xip.io
cf-username: admin
cf-password: admin
cf-organization: admin
cf-space: admin
skip-ssl-check: true
```

skip-ssl-check would actually be "true" and break cf resource

**Comment by rosenhouse** [comment]
:+1: we hit this with https://github.com/pivotal-cf/email-resource trying to use an integer port number.

**Comment by xoebus** [comment]
Er. Short log closed lots of random stuff.

**Comment by longnguyen11288** [comment]
ooo reopened

**Comment by vito** [comment]
Hmm yeah that shortlog thing is unfortunate. It'd be nice if it skipped merge commits altogether and just shows the actual commits.

**Comment by mariash** [comment]
this should be supported now in v0.75.0
