### ISSUE TITLE
Fly sync deadlock

### ISSUE THREAD

**Issue by loewenstein** [concourse/concourse#320]
We are currently facing the following deadlock situation after a concourse update (0.75->0.76)
```
$ fly -t cc sync
targeting http://x.x.x.x

not authorized. run the following to log in:

    fly -t cc login

$ fly -t cc login
fly version (0.75.0) is out of sync with the target (0.76.0). to sync up, run the following:

    fly -t cc sync

cowardly refusing to run due to significant version discrepancy
```

The obvious workaround is of course to manually download the cli.

However this behaviour is probably not as intended. At the very least it is not very convenient. ;)

Best regards

**Comment by vito** [comment]
good catch, thanks for the report. hmm. I suppose we should have the
version check just be a warning for `login`?
