### ISSUE TITLE
topgun/k8s: use of team external workers

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3203]
## What challenge are you facing?

Before https://github.com/helm/charts/pull/10885, there was no way for one to include team-specific external workers with a public SSH key that is different from the one already used for the regular workers. With that change in place, we can now cover such use case.

## What would make this better?

Having the test in place - as an acceptance criterion:

- have a worker joining the cluster with an SSH pair that is different from the one used by the regular workers.

## Are you interested in implementing this yourself?

👍

**Comment by scottietremendous** [comment]
If it's not possible to use the helm chart to deploy the external worker use the simplest way to deploy the worker (pod?).
