### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by nbraud** [concourse/concourse#3204]
## Bug Report

A fresh, idle Concourse instance uses >700MB of RAM (on a VM with 1GB available) on startup.
After a while, this drops to ~300MB

## Steps to Reproduce

On a fresh system:
```
# apt install ansible
# ansible-pull -U https://github.com/duckinator/boop-infra.git ci
```

## Expected Results

Concourse uses reasonable amounts of resources.

## Actual Results

Concourse uses over 700MB at startup, then drop to ~300MB.

## Additional Context

For comparison, the PostgreSQL database used in the setup uses 18MB of RAM.

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Docker
* Did this used to work?  Unknown

**Comment by duckinator** [comment]
As a note: The Ansible configuration may change.

As of when I deployed the system, it was in this state: https://github.com/duckinator/boop-infra/tree/ff3ce94

Using this docker-compose.yml: https://github.com/duckinator/boop-infra/blob/ff3ce94/roles/concourse/files/root/concourse/docker-compose.yml

And had an nginx reverse proxy from :80 (external) to :8080 (internal-only): https://github.com/duckinator/boop-infra/blob/ff3ce94/roles/concourse/files/etc/nginx/conf.d/ci.boop.ws.conf

**Comment by vito** [comment]
This might be better now that we've changed how the binary is deployed and it no longer holds all the resource types in its head on start.

ref #2576 

This would be out in v5.0.
