### ISSUE TITLE
Worker rebalancing doesn't seem to be working on prod

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3214]
It seems to be configured correctly, as I'm seeing `rebalancing` in the worker logs:

```json
{"timestamp":"1549250744.104410410","source":"worker","message":"worker.beacon.rebalance.rebalancing","log_level":0,"data":{"session":"7.22740"}}
{"timestamp":"1549252544.104246616","source":"worker","message":"worker.beacon.rebalance.rebalancing","log_level":0,"data":{"session":"7.22741"}}
{"timestamp":"1549254344.104365587","source":"worker","message":"worker.beacon.rebalance.rebalancing","log_level":0,"data":{"session":"7.22742"}}
{"timestamp":"1549256144.104175091","source":"worker","message":"worker.beacon.rebalance.rebalancing","log_level":0,"data":{"session":"7.22743"}}
{"timestamp":"1549257944.104233742","source":"worker","message":"worker.beacon.rebalance.rebalancing","log_level":0,"data":{"session":"7.22744"}}
```

However, `fly workers -d` still shows them all on one `web` node:

```
name                                              containers  platform  tags  team  state    version  garden address                                                          baggageclaim url                                                               resource types                 
36a53431-2b92-481a-ad2f-964f218b9da5              31          linux     none  none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:34893  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:39773  git, mock, registry-image, time
4fd44d6a-8ec1-4d71-8e83-6a9c3489a8bc              49          linux     none  none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:34437  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:46137  git, mock, registry-image, time
69c32ad9-b4b2-40b9-b85f-8395acab8213              0           linux     pr    none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:44467  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:40579  git, mock, registry-image, time
81ceede8-75de-490e-995c-b45193b23060              80          linux     none  none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:37913  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:45177  git, mock, registry-image, time
942fbb30-041a-40e5-9b37-3a7252e7d8fb              0           linux     pr    none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:33855  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:41999  git, mock, registry-image, time
a2d0d6fc-de12-440d-bf4d-14dfa5325358              0           linux     pr    none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:33907  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:33387  git, mock, registry-image, time
cfee4482-0d7e-4903-8df8-464708916b28              77          linux     none  none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:41265  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:37169  git, mock, registry-image, time
darwin-worker                                     0           darwin    none  main  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:35943  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:37899  none                           
ea27e1e4-vm-60875547-af52-46e6-6c39-e12945d5d040  0           windows   none  none  running  2.1      0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:39885  http://0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:37545  none      
```

The env seems to be configured correctly:

```sh
export CONCOURSE_TSA_HOST=0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:2222,f2801c9b-3653-4d55-93b0-3be8d7ee977f.web.web.concourse-prod.bosh:2222

# ...

export CONCOURSE_REBALANCE_INTERVAL=30m
```

I wonder if the worker is only picking up the first TSA host listed or something? Maybe a bug with handling env config?

**Comment by cirocosta** [comment]
Just a datapoint: seems to be working fine in `hush-house` (3 workers, 2 web) 🤔 

<details>
<summary>
some data
</summary>
<pre>
for i in $(seq 1 100); do fly -t hh workers --details | awk '{ print $1,$8 }' | sort ; sleep 60 ; echo "-----" ; done

hush-house-worker-58ddd49565-8szv9 10.11.4.7:40419
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:46037
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:33273
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:40419
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:46037
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:33273
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:42431
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:46545
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:33273
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:42431
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:46545
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:33273
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:42431
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:46545
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41445
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:42431
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:46545
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41445
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:42431
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:46545
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41445
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:36893
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:37211
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:34827
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:34535
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:43509
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:44923
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:34535
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:43509
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:44923
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:34535
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:43509
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:44923
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:34485
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:42129
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:44923
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:34485
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:42129
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:44923
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:34485
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:42129
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39889
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:34485
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:42129
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39889
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:34485
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:42129
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39889
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:46165
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:44611
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39889
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:46165
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:44611
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39889
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:46165
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:44611
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41639
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:46165
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:44611
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41639
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:46165
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:44611
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41639
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:36809
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33131
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41639
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:36809
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33131
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:41639
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:36809
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33131
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:36199
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:36809
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33131
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:36199
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:36809
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33131
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:36199
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:36111
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33075
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:36199
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:36111
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33075
hush-house-worker-58ddd49565-pqwwf 10.11.4.7:36199
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:36111
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33075
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39439
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:36111
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33075
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39439
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.8:36111
hush-house-worker-58ddd49565-dzl8h 10.11.4.7:33075
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39439
-----
hush-house-worker-58ddd49565-8szv9 10.11.4.7:46441
hush-house-worker-58ddd49565-dzl8h 10.11.4.8:43631
hush-house-worker-58ddd49565-pqwwf 10.11.4.8:39439
</pre>
</details>

**Comment by vito** [comment]
@cirocosta And that's configured via env too, right? Hmm...

**Comment by vito** [comment]
Hmm, this seems to be working on prod, but it still seems to be favoring a particular `web` node fairly often:

```
00411b6d-23dd-4119-878a-b0baa7a2b836 running 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:41673
2108cbfe-4248-48c2-a131-b9438f537a27 running 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:41661
36a53431-89b1-43f0-a416-90eff16cc69d running 6ae730cc-cbab-4de6-80ff-ebf529fc3f44.web.web.concourse-prod.bosh:45631
40e8b592-e977-43b5-8384-e31fea081f98 running 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:37903
4fd44d6a-1de3-4e00-abe7-4d469c329958 running 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:34155
81ceede8-2b65-47e8-ae8e-0b500a136536 running 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:42977
cfee4482-4bb1-404f-8b0e-232ac942ea4b running 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:42187
f28cac08-96c9-4b77-9e29-4327d039f20b running 0bf41d14-e50b-45c8-a5ed-a1480c0c6c7f.web.web.concourse-prod.bosh:43079
```

This screenshot shows that they're at least changing now and then - it's just odd that every time I look it's not very balanced at all:

![screenshot from 2019-02-15 10-57-03](https://user-images.githubusercontent.com/1880/52868129-798c8200-3110-11e9-9e7e-8d4ad0a0e89f.png)

Maybe this randomness isn't enough?:

https://github.com/concourse/concourse/blob/62d606ebfd1b0fdf10bd0075767b1b025417912d/tsa/client.go#L369-L379

It seems like it currently relies on Go randomising hash iteration order. Which is a little janky.
