### ISSUE TITLE
Pinned Resource Hover Style

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#3224]
When a resource has a pinned version, hovering over it in the pipeline view removes the padding between the pin icon and the text.

![resource](https://user-images.githubusercontent.com/1919762/52359090-2ecf8380-2a07-11e9-89f5-ff91ef4cf02b.gif)

* Concourse version: dev
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: local
* Browser (if applicable): Chrome
* Did this used to work? N/A

**Comment by pivotal-jamie-klassen** [comment]
related: #2967. That little purple box could definitely use some TLC.

**Comment by cirocosta** [comment]
Hey, I noticed that some issues related to padding seem to also appear on resources with long names (even when not pinned):

![padding](https://user-images.githubusercontent.com/3574444/52382242-660f5600-2a42-11e9-99c9-9282f4ca5231.gif)
