### ISSUE TITLE
Escape key no longer blurs the dashboard search input

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3226]
## Bug Report

as part of the introduction of the stop-gap `NewestTopBar` module we seem to have mixed up the words 'focus' and 'blur'.

## Steps to Reproduce

1. Have at least one visible pipeline.
1. Visit the dashboard.
1. Focus the search input.
1. hit the Escape key.

## Expected Results

The search input is blurred and the autocomplete dropdown dismisses.

## Actual Results

The search input is still focused and the autocomplete dropdown is still there.

## Additional Context

Looking back a bit, [this](https://github.com/concourse/concourse/commit/50cdabf266a93f30767594813ac2ab7bd953ce66#diff-e15c61fff176e32aa5029ea91a239d87L297) is ultimately the offending change, but we should have tests to protect against this, too.

## Version Info

* Concourse version: 5.0.0 (master)
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): Chrome
* Did this used to work? Yes, it works on 4.2.2 on wings.

**Comment by pivotal-saman-alvi** [comment]
Fix for this is in the PR for the web nav bar. Commit: https://github.com/concourse/concourse/commit/406e4821eea27b6cd4b21f43739b9f284cebca28

**Comment by pivotal-jamie-klassen** [comment]
Reconsidering this. Pressing escape does cause the dropdown to dismiss, but does not blur the autocomplete as it used to.
