### ISSUE TITLE
visiting a job build page by ID should still show breadcrumbs

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3227]
I've noticed this because when the PR resource integrates with github it links directly to the `/builds/:id` URL and it feels kinda jarring to see the empty top bar instead of `prs / <job name>` in those cases.

<img width="296" alt="screen shot 2019-02-06 at 1 36 58 pm" src="https://user-images.githubusercontent.com/22056320/52364946-4f520a80-2a14-11e9-8ca1-9b6b60bb7215.png">

**Comment by vito** [comment]
yes pls

thankfully you can at least click the build number and it'll take you to a page that has it
