### ISSUE TITLE
fly intercept exits container after 30 seconds

### ISSUE THREAD

**Issue by alexandruast** [concourse/concourse#3257]
## Bug Report

When running fly intercept, after 30 seconds, I get logged out of the container

## Steps to Reproduce

```
date +%H:%M:%S;fly -t factory-ci intercept --check dev-site-deploy/dev-site;date +%H:%M:%S
09:49:14
bash-4.4# 09:49:45
```

## Expected Results

Do my debug session on the container

## Actual Results

I am disconnected from the container after 30 seconds

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: GKE
* Browser (if applicable):
* Did this used to work? Don't know

**Comment by vito** [comment]
Hi - we use issues for feature requests and bug reports, but this looks more like a support request/question - please consider using our [forums](https://discuss.concourse-ci.org) instead.

In particular I would check if your load balancer has any sort of idle timeouts or something.
