### ISSUE TITLE
If I `fly execute` with `-j`, the URL for the build winds up taking me to the dashboard

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3262]
## Bug Report

`fly execute` with `-j` creates a pipeline-scoped build. but the web UI doesn't recognize routes like `/teams/:team/pipelines/:pipeline/builds/:build_id` so just shows you the dashboard instead.

## Steps to Reproduce

1. Run `fly execute` with `-j`.
1. When fly tells you the URL that your build is running at, visit in a browser.

## Expected Results

Your browser shows the build page for that build.

## Actual Results

Your browser shows the dashboard.

## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): bosh (prod)
* Infrastructure/IaaS: gcp
* Browser (if applicable): chrome
* Did this used to work? 🤷‍♂️

**Comment by pivotal-jamie-klassen** [comment]
I see two options:
1. Fly should tell you to visit a build page by ID (i.e. `/builds/:build_id`)
1. Web UI should know how to route to pipeline-scoped builds, so that we can leave fly the same and make the fix on the web side (probably better).

**Comment by pivotal-jamie-klassen** [comment]
#1869 is similar and involves the same setup, but the reported problem is not identical. Strictly speaking it may already be resolved, so I figured I'd mention it here anyway.

**Comment by vito** [comment]
@pivotal-jwinters This is one unfortunate result of having `fly execute -j` associate the build to a job.

**Comment by pivotal-jwinters** [comment]
Option 1 above is actually quite easy to implement on the API side. After a build is created we include a link to the build in the API response, so fly wouldn't have to change.

This way we avoid having to implement more logic on the web side.

**Comment by pivotal-jwinters** [comment]
Nevermind. The API is actually returning the `/builds/:build_id` route in the both cases. Fly does something weird. 

@pivotal-jamie-klassen Let's make this change in `fly execute` and always just show the link to `/builds/:build_id`?

I'll keep this in the API backlog, since the change conflicts with stuff we're currently working on.

**Comment by mhuangpivotal** [comment]
Added a `fly` fix on branch `feature/3262-fly-execute-build-url`. The branch is based on `feature/3240-the-great-decoupling`. To avoid managing multiple PRs, we can create a PR once https://github.com/concourse/concourse/pull/3307 is merged.
