### ISSUE TITLE
Access the local host's docker.sock to deploy updates to a swarm stack / manage CD containers

### ISSUE THREAD

**Issue by SvenDowideit** [concourse/concourse#3263]
## What challenge are you facing?

I want to use concourse for updating/deploying services to a host running Docker, or Docker Swarm. At this point, I've not needed to put the Docker socket on the network, and I'd much prefer not to....

mmm, relatedly, i'd like to be able to react to things that happen in my swarm - if a service/container starts, or fails to start, or if a volume has something happen to it etc - and as I can pin a worker to run on my docker swarm manager node/s, it feels like i should be able to connect something in concourse to the local socket (tbh, i expect there are other local host resources that a thinger might want to thing on)

I'm surprised that this isn't a documented use case - so if i've failed to find the docs, I'd be :heart_eyes: 

## What would make this better?

Some way to access the local host's filesystem? 

Is this something that could be written as a resource type?

Or if this is actually already supported, writing documentation / updating a tutorial

## Are you interested in implementing this yourself?

Yup

**Comment by SvenDowideit** [comment]
related to https://github.com/concourse/docker-image-resource/issues/182

**Comment by lecardozo** [comment]
I have a similar use case (just not running swarm). I run both Concourse and docker in the same host and would like to deploy/run local containers after successfully testing/building them in my pipeline. Is it currently possible to access a local docker host without exposing its socket to the network (i.e. using the docker unix socket)?

**Comment by vito** [comment]
@lecardozo Correct - there is no way to expose worker state to builds right now, as in general that would be an example of the [`worker-state` anti-pattern](https://github.com/concourse/concourse/wiki/Anti-Patterns#worker-state).

Not shutting this down, but I'm gonna give it that label anyway. Happy to discuss proposals but the risks of the anti-pattern are still something to keep in mind.

**Comment by lecardozo** [comment]
Thanks, @vito! Yeah, this would definitely fall into the worker-state anti-pattern. I don't have any official proposals for now. Initially I was thinking about some kind of "local machine" resource in which we could `put` some commands to be executed in a local machine. Something like this:
```yaml
resources:
 - name: local-machine
   type: local-machine

jobs:
  - name: Write file to local machine
    plan:
      - put: local-machine
        params:
          command: "echo 'abc' > /path/to/local/file.txt"
```
Naturally, for this to be possible, we would need some kind of specialized worker (maybe falling into the worker-state anti-pattern?) that can execute arbitrary commands on the local machine.

**Comment by SvenDowideit** [comment]
ok, so first up this isn't that simple.

I do _not_ actually want to run commands on the local host, I want to make changes to a Docker swarm, from concourse runners that I am running inside swarm containers.

I would much prefer to avoid making a docker socket proxy - which doesn't actually avoid this worker-anti-pattern, it just increases the complexity of using concourse.

What is frustrating me atm, is that concourse seems to label doing "things" to a host as both "what it does" and "a bad thing", without reducing the contributor-burden (or worse the user-burden) by giving some good examples of how you might use concourse to do things like this.

atm, i'm contemplating giving my confluence job an ssh key to allow it to ssh into one of the master hosts, or making a container, running on a swarm master, which has sshd and the docker socket mapped in, to achieve the same thing.

both this "non-worker-state" workarounds don't just feel like a concourse purity penalty for the user, but also a security risk (by adding a network path to the socket) compared to just being able to mount the docker socket into my job.

mostly, I'm finding the barrage of "what you're asking for is an anti-pattern" a pretty strong demotivator - I was hoping that the experts would have suggestions for solutions - which would then be excellent examples to write up.

**Comment by vito** [comment]
> mostly, I'm finding the barrage of "what you're asking for is an anti-pattern" a pretty strong demotivator - I was hoping that the experts would have suggestions for solutions - which would then be excellent examples to write up.

The intent of these labels isn't to reject the use case, it's to call out the risk that we need to carefully design around. I can see how it would be perceived that way, though, and I'll try to be more careful to add disclaimers around this in the future as I sometimes have in the past.

> both this "non-worker-state" workarounds don't just feel like a concourse purity penalty for the user, but also a security risk (by adding a network path to the socket) compared to just being able to mount the docker socket into my job.

Being able to mount paths from the host into the container sounds like a bigger security risk to me, if we're not careful about it. For example, if it's up to the task config to decide what paths get mounted in, this could allow someone to submit a pull request that trivially gains access to sensitive information. So we obviously shouldn't do that.

> What is frustrating me atm, is that concourse seems to label doing "things" to a host as both "what it does" and "a bad thing", without reducing the contributor-burden (or worse the user-burden) by giving some good examples of how you might use concourse to do things like this.

I'm not sure what you mean by this tbh (in particular "what it does"). You requested a feature, we're attempting to discuss it and work around a design, we don't have a solution yet, so it'd be nice if we could collaborate and get there while *also* keeping in mind the security risks and other downsides of the 'worker-state' anti-pattern which the project is trying to avoid.

**Comment by SvenDowideit** [comment]
first up - my reaction isn't to the issue label. its based in part on reading as many issues and requests for help doing similar things here, seeing them met with many words amounting to "anti-pattern", and so far, no shared experiences in (i'm presuming) redefining what we, as newbs are asking into better practice.

To be honest, I didn't raise this expecting a new feature - I was hoping and expecting that some concourse expert would be able to tell me i'm looking at the problem from the wrong direction, and that to talk to the swarm without adding a network proxy with the additional security burden, I just needed to do XYandZ.

I _don't_ want to mound random host paths, I'm happy to predefine them when configuring concourse, the worker, or whatever - but i'm somewhat hamstrung trying to both work out how to write pipelines, coming from a docker-world, and not knowing garden and how to trick it into doing what i want.

**Comment by siredmar** [comment]
Hi! I am currently in some sort of the same situation only for balena (https://github.com/balena-io/balena-cli)
The thing i want to do is use `balena-cli` to build a balena application release which actually needs a running docker instance to access. 
The message i receive is: `Docker seems to be unavailable. Is it installed and running?`
So it seems that even if i installed docker in that docker image i am using it can't be accessed.

This is a snippet of my dockerfile where i am installing docker ce 
```
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN  add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
RUN apt-get update && apt-get install -yqq docker-ce docker-ce-cli containerd.io
```
This is intended not to use the docker socket from the host.
Running this image locally works just fine.
