### ISSUE TITLE
Remove peer url

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#3267]
## What challenge are you facing?

Once #3225 gets merged, we no longer need the `peer url`.

## What would make this better?

 Remove it.

**Comment by vito** [comment]
I don't think we can do this entirely - left a comment here: https://github.com/concourse/concourse/commit/368d6df4f06b9ee63e9ad5fb9c4ddfc1b976823a#r32507947

We can at least stop passing it to the ATC though.

**Comment by vito** [comment]
We could also replace this with `--peer-ip` which is probably clearer, at least for the TSA's use case.
