### ISSUE TITLE
Check params from credhub before parsing the pipeline YAML to avoid cryptic error messages like "cannot unmarshal !!map into string" 

### ISSUE THREAD

**Issue by bengtrj** [concourse/concourse#3269]
## What challenge are you facing?

Because of human error (mine!) I mistakenly set a task param as a Credhub var that was a YAML, not a string. I spent almost an entire day trying to figure out what the error message `line 4: cannot unmarshal !!map into string` meant. The line didn't make any sense and all yaml looked valid.

## What would make this better?

Check if what returns from Credhub using the user provided key makes sense, it should be a string. The Credhub credential name was "admin" so I assumed it was the username - when it was actually a full blown credential of type `user` that is indeed a `yaml` by itself.

## Are you interested in implementing this yourself?

Maybe, this looks like it's high in value and low in implementation complexity. The code that gets the value from Credhub could check if the result is a on-liner string.

This issue/feature request is related to https://github.com/concourse/concourse/issues/3098

**Comment by xtremerui** [comment]
There is `fly -t ci set-pipeline --check-creds` . Have you tried using that in your case?

**Comment by bengtrj** [comment]
No, I didn't! Thanks! I'll add that to our `set_pipeline` scripts.
