### ISSUE TITLE
UI shows a resource on top of a job

### ISSUE THREAD

**Issue by rosenhouse** [concourse/concourse#327]
![overlap](https://cloud.githubusercontent.com/assets/4128521/14054514/1697766a-f297-11e5-8089-0a74001ee5c9.png)

[Pipeline config here](https://github.com/cloudfoundry-incubator/container-networking-ci/blob/6274d87fd8fb9a5514fcd3f254ecf535d713a54a/pipelines/ducati.yml)

This is 0.75.0.

**Comment by vito** [comment]
Opting to punt on this since we'll likely redo that UI before fixing this issue.
