### ISSUE TITLE
Is it possible to avoid use import modules from golang.org directly?

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3273]
## What challenge are you facing?

Some modules are newly added to `go.mod`:

    48061620 (Alex Suraci       2019-01-27 01:02:09 +0000 154)      golang.org/x/crypto v0.0.0-20190123085648-057139ce5d2b
    48061620 (Alex Suraci       2019-01-27 01:02:09 +0000 155)      golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3 // indirect
    917a982b (Alex Suraci       2019-01-10 14:51:03 -0500 156)      golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
    48061620 (Alex Suraci       2019-01-27 01:02:09 +0000 157)      golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4 // indirect
    917a982b (Alex Suraci       2019-01-10 14:51:03 -0500 158)      golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2 // indirect

which is really making trouble to users who locate in China because golang.org is walled from China. I used to be able build and run concourse on my MacBook, but now I'm not able to do so. Though I have my company's VPN. Via the VPN I can access google, but still fails to access golang.org:

    go: golang.org/x/crypto@v0.0.0-20190123085648-057139ce5d2b: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
    go: golang.org/x/sync@v0.0.0-20181221193216-37e7f081c4d4: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
    go: golang.org/x/net@v0.0.0-20190125091013-d26f9f9a57f3: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
    go: golang.org/x/sys@v0.0.0-20190124100055-b90733256f2e: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

## What would make this better?

I wish Concourse to set a rule to avoid import module directly from `golang.org`, instead, to use mirror from `github.com`.

**Comment by vito** [comment]
This could maybe be done with a series of `replace` rules in go.mod pointing each `golang.org/x/` url to their mirror.

**Comment by evanchaoli** [comment]
I'm not only raise this issue for myself. I can use my company's proxy that enables my build to succeed. But this issue will prevent large base of China users from contributing to Concourse. So I hope we can add some checks PR pipelines to block `golang.org` imports.
