### ISSUE TITLE
fly error: address family not supported by protocol

### ISSUE THREAD

**Issue by pumazi** [concourse/concourse#3278]
## Bug Report

`fly` appears to be defaulting to use an IPv6 connection. I do not have IPv6 configured on my network interface.

## Steps to Reproduce

I don't understand the problem enough to provide you with reproduction steps.

## Expected Results

I expected the login to work. I would expect that `fly` would default to using IPv4 when the network interface doesn't have an IPv6 address.

## Actual Results

I'm experiencing the following error when trying to login. Note, the domain name has been changed.

```
$ fly --verbose -t example login -c https://example.org
logging in to team 'main'

2019/02/12 11:54:36 GET /api/v1/info HTTP/1.1
Host: example.org
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


could not reach the Concourse server called example:

    Get https://example.org/api/v1/info: dial tcp: lookup example.org on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol

is the targeted Concourse running? better go catch it lol
```

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?: Works with local instances of Concourse CI setup using docker-compose.

**Comment by vito** [comment]
What's in your `/etc/resolv.conf`?

**Comment by pumazi** [comment]
I've got an empty `resolve.conf`.
```
$ cat /etc/resolv.conf 
# Resolver configuration file.
# See resolv.conf(5) for details.
```
However, I am able to resolve the domain using `getent`. My knowledge of the system at this level is limited. So I'm likely missing something.
```
# where example.org is the actual domain I'm trying to reach
$ getent hosts example.org
sss.ttt.uuu.vvv     example.org
```
This does resolve to the correct ipv4 address.

Seems like this may be may just be my system setup that is the issue. Please close this issue if you feel that this is most likely my setup. I can always seek help in the forum and/or other sources.

**Comment by vito** [comment]
Hmm I see anything odd in our code for this. It should be fairly vanilla Go network calls. I'm not sure how Go is discovering that IPv6 address but I don't know if there's anything we can do on our end to fix it. I think I'll close this but feel free to look for assistance in the forums.

If you want to poke around the code yourself, it starts [here](https://github.com/concourse/concourse/blob/master/fly/commands/login.go).
