### ISSUE TITLE
Concourse could not pull docker images from public registry

### ISSUE THREAD

**Issue by aiven715** [concourse/concourse#3282]
## Bug Report
I'm getting the following error, when executing a new task(running on my laptop local machine):
```
ci:$ fly -t tutorial execute -c task_hello_world.yml
executing build 1 at http://127.0.0.1:8080/builds/1
initializing

resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to ping registry: 2 error(s) occurred:

* ping https: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
* ping http: Get http://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

## Steps to Reproduce
OS **Ubuntu 18.10**

- Create [docker-compose.yml](https://gist.github.com/aiven715/d3b4ad4ee391fb6c31c140cd0464f378) file
- Run `docker-compose up`
- Log in using `fly --target tutorial login --concourse-url http://127.0.0.1:8080 -u test -p test`
- Execute a [new task](https://gist.github.com/aiven715/5b2a7be0682eee6fc6f48b516cbf8025) `fly -t tutorial execute -c task_hello_world.yml`

## Expected Results

I expect concourse to be able pull docker images without an issues

## Actual Results

Docker image is not pulling

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by marco-m** [comment]
This is often due to a misconfiguration, around `CONCOURSE_EXTERNAL_URL`. Please try to use the docker compose file available in the repo: https://github.com/concourse/concourse/blob/master/docker-compose.yml.

Please for these kinds of problems, before opening a bug, try asking on Discord IM or https://discuss.concourse-ci.org/ forum. See https://concourse-ci.org/community.html

**Comment by Die4Uube** [comment]
@marco-m I reported the same issue here (https://github.com/concourse/concourse/issues/1667#issuecomment-462754611) .  In my corporate network public dns is forbidden there should be someway to refine dns settings. The compose file doesn't show anything related to dns. Am I missing something?

**Comment by aiven715** [comment]
@marco-m thanks for the Discord link.

I've also tried https://github.com/concourse/concourse/blob/master/docker-compose.yml that docker compose file - the issue persists in that case as well

**Comment by vito** [comment]
Sorry - closing this as it sounds more like something for the forums.

**Comment by Die4Uube** [comment]
ok I give it up :)

**Comment by aiven715** [comment]
@Die4Uube what OS are you using btw?
