### ISSUE TITLE
Encourage users to switch to `registry-image` resource when possible in release notes

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3284]
In light of the recent `runc` CVE (see #3276) which affected privileged containers, we should start encouraging people to switch to the `registry-image` resource, since it runs without privileges.

We could also begin the process of deprecating the `docker-image` resource.

**Comment by ralekseenkov** [comment]
I just built the latest 5.0 from master and it looks like tasks based on docker-image just fail with "unsupported resource type" 

seems like a pretty steep deprecation process :)

**Comment by ralekseenkov** [comment]
Shared more details here https://github.com/concourse/concourse/issues/3295
