### ISSUE TITLE
Remove references to build containers

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#3293]
We use build containers (task, get, put) for the `fewest-build-containers` strategy and depend on the container metadata type to determine whether or not a container is a build container. However after #3079 check containers are going to be ephemeral and separate from the GC path, so build containers are now just...containers? We should update any logic to reflect this.

There are other things such as #3292 (PR #3083) which may not be necessary, but we may need other "types" of containers such as 'health-check containers`(PR #3025) so this may change entirely.

**Comment by marco-m** [comment]
Hello @ddadlani sorry for pestering you :-) This issue description mentions multiple issues but it is not clear to me which ones are blocking and which ones are simply related. Could you please list explicitly the blocking issues? Thanks!

**Comment by ddadlani** [comment]
Hi @marco-m, this issue is meant to be a placeholder or reminder for the future. Once check containers are made ephemeral in #3079, they will no longer be tracked in the database. Therefore the concept of "build" containers goes away, since all containers (`get`, `put` and `task`) will be "build" containers. This issue is to remind us to stop referring to them as "build" containers in the code, and to remove any specialized code treating them differently.

If we add other kinds of containers, such as temporary "healthcheck" containers in #3025, calling these "build" containers may still be valid.

That is a long-winded way for me to say that we should revisit the concept of "build" containers in a few months' time :)

**Comment by marco-m** [comment]
merci!
