### ISSUE TITLE
Spike: during container placement, account for other containers concurrently being placed

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#3304]
This arose from #3301. For use cases like aggregate steps, we would need to know what other work is being placed on a worker to accurately place containers in the `fewest-build-container` strategy.

**Comment by wagdav** [comment]
@kcmannem @ddadlani could this be now closed after #3902 ?

**Comment by ddadlani** [comment]
Yep! We ended up doing all the work in #3902. Closing
