### ISSUE TITLE
Dashboard doesn't match order of jobs in pipeline view

### ISSUE THREAD

**Issue by crstamps2** [concourse/concourse#3308]
## Bug Report

In the dashboard view, the boxes of any given pipeline are in reverse order from what they are in the pipeline view. See screenshots for reference:

![image](https://user-images.githubusercontent.com/1142313/52811867-2c52d680-3064-11e9-9e24-c8e71ba9e8cd.png)

![image](https://user-images.githubusercontent.com/1142313/52811986-71770880-3064-11e9-87f6-c571497124a5.png)

## Steps to Reproduce

See screenshots

## Expected Results

The order of the green boxes to match in both areas.

## Actual Results

> (what actually happened?)

## Additional Context

I am probably going to submit a PR myself to fix this, just wanted to have an issue to go along with it. Of course it may be a moot point in v5.

## Version Info

* Concourse version: 4.2.2

**Comment by vito** [comment]
This'll actually be pretty hard to sync up. I would recommend against trying to PR this. :sweat_smile:  We're in a sort of awkward transition point and will be phasing out the current pipeline UI in favor of one more similar to the dashboard. At that point it'd be *much* easier to keep them the same order.

The challenge right now is that they're completely different codebases (Elm vs. regular JS) with completely different algorithms for determining the ordering of the boxes. We should be able to re-use the same algorithm once we work on the new pipeline UI.
