### ISSUE TITLE
Any chance you could add the slack app to the concourse repo?

### ISSUE THREAD

**Issue by jdimmerman** [concourse/concourse#3315]
Hey - Can you add this app to all of the concourse public repos or just the concourse repo?
https://github.com/integrations/slack

It would allow us to subscribe to the concourse releases from our slack instance, which would help us stay up to date. Of course understood if not but I thought I'd ask!

Unfortunately this is the only way it could work, though we can likely write our own bot.
https://github.com/integrations/slack/issues/454

Thanks in either case!
Jason

**Comment by vito** [comment]
Could you point something at the Atom feed for the releases instead?:

https://github.com/concourse/concourse/releases.atom

This feels like a bit of an intrusive change so I'd rather avoid it given there are already mechanisms for subscribing to release feeds.

**Comment by jdimmerman** [comment]
I didn't realize that there was an atom feed, but that works perfectly.  Thanks so much @vito!
