### ISSUE TITLE
Loading Spinner Spasming

### ISSUE THREAD

**Issue by osis** [concourse/concourse#3318]
## Bug Report

Looks like there is a double loading spinner when loading builds? Might be something else, I'm not sure. 🤔 

## Steps to Reproduce

Load a build and look at the loading spinner for the steps.

## Expected Results

Loading spinners as of 4.2.1...

![good_spinners](https://user-images.githubusercontent.com/347097/52871586-5ebe0b80-3118-11e9-85f9-10cd86120a40.gif)

## Actual Results

Loading spinners in 5.0...

![spinners](https://user-images.githubusercontent.com/347097/52871458-1868ac80-3118-11e9-9137-a53eec0ca934.gif)

## Version Info

* Browser: Version 74.0.3705.0 (Official Build) canary (64-bit)

**Comment by vito** [comment]
weird - i can't get this to happen

**Comment by osis** [comment]
Willing to tag it as a Chrome Canary-ism that might one day hit main Chrome, but also might not. Found a longer loading spinner which might be a better indicator.

![longer-spinner](https://user-images.githubusercontent.com/347097/52881097-b2891e80-3131-11e9-8dd7-d134c16ab511.gif)

**Comment by osis** [comment]
![funky-spinners](https://user-images.githubusercontent.com/347097/53264799-87ab4700-36aa-11e9-944f-85837b4617fc.gif)

Might be a Chrome Canary thing. This is Concourse 4.2.3 on latest Canary.

**Comment by osis** [comment]
Actually, I updated to latest latest and it has corrected itself. Back in the original state of this issue.

**Comment by osis** [comment]
Fixed in the latest build of Chrome - 74.0.3729.0 (Official Build) canary (64-bit)
