### ISSUE TITLE
More helpful error logs when container fails to create

### ISSUE THREAD

**Issue by ndarilek** [concourse/concourse#332]
My setup:
 * Concourse on a very stock Ubuntu 15.10 VM, worker/web/database on the same host. All I've done is install Nginx as a proxy, download the binary, create a few systemd units and enable/start them.
 * Concourse 0.76.0
* UFW installed, tried with it both enabled and disabled
 * Worker running as root

I have defined a job but can't get it to run. I'm starting Concourse via systemd and see this in the logs:

```
Mar 28 15:12:09 concourse concourse[15283]: {"timestamp":"1459177929.600615740","source":"garden-linux","message":"garden-linux.pool.release.release-system-resources","log_level":2,"data":{"error":"exit status 1","id":"g0a40onig10","session":"8.59"}}
Mar 28 15:12:09 concourse concourse[15283]: {"timestamp":"1459177929.600647211","source":"garden-linux","message":"garden-linux.garden-server.create.failed","log_level":2,"data":{"error":"container: start: exit status 2","request":{"Handle":"","GraceTime":0,"RootFSPath":"/var/lib/concourse/linux/resource-images/git","BindMounts":null,"Network":"","Privileged":true,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{}}},"session":"11.32"}}
Mar 28 15:12:10 concourse concourse[15283]: {"timestamp":"1459177930.208368540","source":"garden-linux","message":"garden-linux.pool.acquire.created","log_level":1,"data":{"handle":"g0a40onig11","session":"8.57"}}
Mar 28 15:12:10 concourse concourse[15283]: {"timestamp":"1459177930.391544580","source":"garden-linux","message":"garden-linux.container.start.command.failed","log_level":2,"data":{"argv":["/var/lib/concourse/linux/depot/g0a40onig11/start.sh"],"error":"exit status 2","exit-status":2,"handle":"g0a40onig11","session":"91.1.1","stderr":"Failed to create container: containerizer: run pivotter: exit status 2","stdout":"","took":"116.894337ms"}}
```

Thoughts on what to try? I have a firewall enabled, but disabling it doesn't help. Happy to provide any additional details, but otherwise it would be helpful if this start.sh could print at least stderr in its logs if it fails.

Thanks.

**Comment by xoebus** [comment]
@goonzoid @julz Hiya, how would you like to track this?

I think it's on Concourse to support deployment environments outside BOSH but having better error messaging here would be great.

**Comment by vito** [comment]
Similar issue occurs if Garden fails to start with `failed-to-setup-backend`. It just says e.g. `exit status 127` with no stdout/stderr which is super unhelpful.

**Comment by vito** [comment]
This is pretty out-of-date; we're on garden-runc now which is totally different. In any case, it'd probably be on them to fix the logs, not us.
