### ISSUE TITLE
'git-resource' resources took old commit

### ISSUE THREAD

**Issue by DimitarVoynov** [concourse/concourse#3324]
## Bug Report

Hello, 

we faced a very strange issue with Concourse: a job execution failed because it  referenced a very old commit in its 'git-resource' (with the next runs the job builds were fine as the current commit from 'master' was used). 
**Note**: this happened right after concourse nodes (workers and web nodes) were recreated with bosh. We couldn't think of a reason why this might had happen? We were thinking this might be some 'corner-case' bug ..? Thanks!

Actually 3 different builds (corresponding to 3 different jobs) that were started at exactly the same minute - all grabbed this old commit.

## Steps to Reproduce

Here is how our git resource looks like: 
https://gist.github.com/DimitarVoynov/1cc43f2d2e07683e429f78f811151308

## Expected Results

latest commit from 'master' to be used during git resource usage

## Actual Results

old commit (more than one months old) was taken

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: OpenStack
* Browser (if applicable):
* Did this used to work? yes

**Comment by DimitarVoynov** [comment]
Hi @vito, 

we would be happy ourselves if we could reproduce this, but unfortunately we can't. 

Another interesting thing we noticed though, that hopefully can bring some ideas: one of the Concourse jobs that used old commit - has a time-resource (https://github.com/concourse/time-resource) apart from the git-resource. This time-resouce also reported an old time (time | 2019-01-10T15:30:54.713154259Z) - the same data that the old commits are from!? 

Best regards, 
Dimitar

**Comment by D031121** [comment]
Hi,

this issue happened again and while investigating the jobs which were running with the old commits, we have seen that that in the resource section of the job log, there is no "branch" info shown.
As shown in the provided git-resouce config, the resource has set the branch parameter.
When the job was executed with this commit initially months ago the branch info was shown, this time, no branch info although the git resource is configured with it.
Hoping that this additional info helps in getting an idea why ATC picks up these old commits.

Cheers,
Martin

**Comment by vbakayov** [comment]
Hi @vito,

Here we provide more insights for the issue:
-    Both occurrences happened after update of the Concourse deployment
-    While comparing the containers the one which took old commit and the one which took right commit have one property difference i.e: concourse:exit-status 143
-    It has been found that some of the tables contain entries for the erroneous old resources (e.g resource_caches), but it is maybe rather consequence than cause. The old commit id's are after the most recent (correct) commit.
-    Both ids and time of insertion are in the correct order, which means the “check” mechanism is successful. The “in” mechanism is the one which seems to be fetching wrong version of the resource. The  HEAD  git  file from the git-resource shows the HEAD moved from master to the "old" commit.
-    The problematic builds were already associated with the old commits in the "builds_inputs" table.
-    The time of the worker nodes was changed as a test, but the Concourse was able to handle this correctly
-    As the database keeps all versions of all resources, the “in” mechanism collects them all and then reduces them to a single version of each resource. We tested this part of the code but could not reproduce the issue.
-    We isolated and ran this part of the code. We ran the test for every job in the “update pipeline”, but unfortunately the results were as expected. We studied the sorting logic, but there is a little cause for concern.
-   It was verified that all jobs which run with old resource versions were not triggered manually and were not triggered based on successful job on which is depends. For example, job_1 depends on successful execution of job_2 the expected  behavior is that job_1 will be started only after job_2 is successfully completed with the given. When the problematic runs occurred, the jobs on which the failing jobs depends did not have any runs at all.

Best Regards,
Viktor
