### ISSUE TITLE
Pipeline Chrome tab memory footprint grows rapidly and seemingly without bound

### ISSUE THREAD

**Issue by xtreme-james-thomson** [concourse/concourse#334]
[memory_hog_pipeline.zip](https://github.com/concourse/concourse/files/193994/memory_hog_pipeline.zip)

The same pipeline on our iMac workstation was using over 2Gb of memory. 

This was on 0.74

**Comment by bechtoldt** [comment]
I don't know why but it happened to me, too. It was consuming so much memory and swap space that I was forced to kill my Mac.

Very strange..


* Chrome Version 49.0.2623.110 (64-bit)
* Vagrant box concourse/lite 0.76.0

**Comment by xtreme-gavin-enns** [comment]
We didn't mention it, but ours (xtreme-james-thomsons and I) was on an aws deployment, not local.

**Comment by xtreme-gavin-enns** [comment]
And it's completely reproducible with this pipeline

**Comment by svenvarkel** [comment]
I'm facing the same issue on OSX.

**Comment by xtreme-gavin-enns** [comment]
Just to clarify, the starkandwayne tutorial issue referenced above is probably unrelated. This issue is about viewing a pipeline in chrome, that one is about memory leaks when running concourse lite in vagrant (I think)

**Comment by vito** [comment]
This should be a lot better now.
