### ISSUE TITLE
4.2.3 BOSH Release is not published

### ISSUE THREAD

**Issue by DanielJonesEB** [concourse/concourse#3343]
The BOSH release for 4.2.3, with the rather important CVE fix, doesn't appear to be online.

Repro steps:

* Visit https://concourse-ci.org/download.html
* Navigate to BOSH section
* Click 4.2.3 link
* Observe `expected 1 glob match, but found 0` error page
* Visit https://bosh.io/releases/github.com/concourse/concourse-bosh-release?all=1
* Observe no 4.2.3 release

**Comment by jama22** [comment]
Sorry about that folks! There's been a lot of pipeline wrangling going on while we dig up 4.2.x and 3.13.x pipelines to test and patch against the newer versions of Garden runC with the CVE fix. As you noted one of the steps that didn't work so well was the publish to bosh.io. While we work towards patching 3.13.x and then fixing our publish action to bosh.io, you can download the release directly from our s3 bucket here https://s3-us-west-2.amazonaws.com/concourse-nightly-releases/concourse-4.2.3.tgz

**Comment by vito** [comment]
It's now available here:

https://bosh.io/releases/github.com/concourse/concourse-bosh-release?version=4.2.3
