### ISSUE TITLE
Gracefully handle "unknown handle" if volumes are deleted

### ISSUE THREAD

**Issue by enugentdt** [concourse/concourse#3354]
## Bug Report

Essentially, if one were to delete volumes.img or any of the volumes files, it would cause Concourse to error out for several hours, stating that there is an `unknown handle`. Here are a couple of errors:

```
volume '7fddf53e-735e-4696-5e2a-c777dd7d4a76' disappeared from worker 'worker2'
```
```
unknown handle: c7892658-445d-4f84-72d5-087873bacb01
```

## Steps to Reproduce

Delete `/opt/concourse/worker/volumes.img`, and try to run a build

## Expected Results

Honestly, I'm not entirely sure what I expected to happen, however, my Concourse install should _not_ become unusable for several hours.

## Actual Results

Concourse fails to regenerate the volumes, and makes the pipelines unusable until it decides to clean itself up.

## Additional Context

I know, I know, this is user at fault. However, this comes hand-in-hand with cleaning up unused volumes, because Concourse will use upwards of 20GB/worker of stale volumes. When concourse runs out of space and I can't extend it, I've found this to work in the long term.

I'm really sorry for being "that user." I honestly am...

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Binary, but could happen on Bosh as well
* Infrastructure/IaaS: ESXi VMs, however, can happen on any VMs

## A Modest Proposal

Solving #1038 may be half the solution to this. If old volumes are cleared, it would remove the need for me to drain concourse's blood with a rusty knife. Trust me, that is an insult against nobody but myself.

If clearing volumes cleanly - and making volumes cleared by GC - were implemented, this issue would at least have a lower incidence. Maybe just keep the most recent volume for a given build/artifact, and delete after 1 week of non-use? Not sure what would be the answer, but I also don't fully understand the concept of volumes.

Hope I can be of help!

**Comment by vito** [comment]
This is fixed in 5.0 via #2588
