### ISSUE TITLE
Volume binding in Docker not working / certificate not updating

### ISSUE THREAD

**Issue by moepkid** [concourse/concourse#3358]
Hello,

We are using concourse on docker and in one phase, it runs mvn-sonarqube-runnen and connects to out sonarqube server. However, this does not work as it can't find the correct ssl certificate due to "pkix path building failed unable to find valid certification path to requested target". 

the "volume - etc/ssl/certs:etc/ssl/certs" option within the docker compose file is ignored and therefore concourse does not see the certificate. 

Is there a correct way to add the certififcate to the concourse docker so the all child workers (mvn java images) also can use them?

**Comment by vito** [comment]
Have you configured `CONCOURSE_CERTS_DIR=/etc/ssl/certs` on the worker container?

**Comment by moepkid** [comment]
also note that --cert-worker=/etc/ssl does bnot get recognized when put in the command clausule.

**Comment by moepkid** [comment]
Okay, we did the following:

- added the crt and pem and der to the /etc/ssl/certs and keytool respectively. 
- set the --worker-certs-dir command to point to /etc/ssl/certs

still, the concourse-sonar-runner mvn gives us the PKIX error using this compose.yml

concourse:
    restart: always
    image: concourse/concourse:4.2.1
    command: quickstart --worker-certs-dir=/etc/ssl/certs
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes:
    - /etc/ssl/certs:/etc/ssl/certs
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=###
    - CONCOURSE_ADD_LOCAL_USER=test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_WORKER_GARDEN_NETWORK
    - CONCOURSE_WORKER_CERTS_DIR=/etc/ssl/certs
    networks:
      hbr-concourse:

**Comment by vito** [comment]
Running out of ideas here, sorry.

This comment isn't very helpful to you right now, but fwiw this is probably more motivation for concourse/rfcs#9.
