### ISSUE TITLE
Scrolling and Font in High-density Dashboard View

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#3363]
## Bug Report

The horizontal scrolling appears to be broken in high-density dashboard view, and there is an extraneous vertical scroll that should not be there. Long team names also push out the columns.

## Steps to Reproduce

Log on https://wings.pivotal.io, and visit https://wings.pivotal.io/hd

## Expected Results

Horizontal scrollbar should appear. Left/right arrows keys should scroll horizontally.

Vertical scrollbar should not appear. There should not be vertical scrolling.

Long team names should wrap or truncate.

## Actual Results

Horizontal scrollbar does not appear. Left/right arrows do not work.

Vertical scrollbar appears.

Long team names do not wrap or truncate.

<img width="1508" alt="screen shot 2019-02-21 at 4 29 29 pm" src="https://user-images.githubusercontent.com/1919762/53202999-ef538a80-35f5-11e9-98d4-35bcb45ed736.png">

## Version Info

* Concourse version: v5.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? yes

**Comment by Lindsayauchin** [comment]
Vertical scroll is broken in this example captured on Chrome. Resulting in pipelines hidding below the browser bottom. These pipelines can be viewed when a user reduces the browser zoom. 

<img width="1535" alt="screen shot 2019-02-25 at 9 58 50 pm" src="https://user-images.githubusercontent.com/27746614/53384448-f0afea80-3948-11e9-8a7a-0cd029651203.png">
<img width="1050" alt="screen shot 2019-02-25 at 9 59 31 pm" src="https://user-images.githubusercontent.com/27746614/53384454-f60d3500-3948-11e9-8606-cc6ae3c434de.png">

**Comment by pivotal-jamie-klassen** [comment]
Based on a brief discussion with @mhuangpivotal and what I can remember it seems we have never established an overflow behaviour for team names on the HD dashboard -- so far the options presented are

1. wrapping long team names over multiple rows
1. truncating/ellipsizing long team names.

I'd like to suggest making a separate issue to capture this decision. @Lindsayauchin does this make sense?
