### ISSUE TITLE
Incorporate k8s-testflight back to the pipeline

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3365]
With the migration to the new pipeline, we end up not putting `k8s-testflight` back.

This morning I just run it against a k8s deployment and it seems to be almost working fine - just a single failure.

Given that it provides some coverage that `smoke` and `topgun` doesn't provide, I'd say it's valuable to have it there back again.

**Comment by vito** [comment]
Hmm which test failed? We used to use `testflight` be the de-facto test suite for each platform, but I don't think it's very effective like that; most of the tests are never going to fail due to platform differences, as they're designed to be feature-level. So it ended up just being a bit slow test suite that we ran many redundant times.

If the test caught something real that's platform-dependent, maybe we could add an equivalent test to the 'smoke' suite?

**Comment by cirocosta** [comment]
That makes sense 🤔 

The test that failed:

```
• Failure [26.685 seconds]
image resource caching
/Users/cirocosta/Development/concourse/concourse/testflight/image_resource_caching_test.go:10
  gets the image resource from the cache based on given params [It]
  /Users/cirocosta/Development/concourse/concourse/testflight/image_resource_caching_test.go:29

  Saw:
      started tf-pipeline-11-50b7f24b-e4dd-45ee-7e3d-3d33b563a710/image-resource-with-params #1

      initializing
      INFO[0000] fetching version: 4cc1b04a-44a9-4dec-5bf0-9a7b78da13a8
      INFO[0000] mirroring self image                          via_params=false
      running /bin/true
      succeeded

  Which matches the unexpected:
      fetching

  /Users/cirocosta/Development/concourse/concourse/testflight/image_resource_caching_test.go:36
```

which, as you mentioned, is not platform-dependent (I noticed I didn't provide a specific `digest` for the image in this deployment, maybe that's why it failed with such assertion).

And given that we're already running testflight tests against a containerized version of concourse, I guess that makes a `k8s-testflight` even more redundant hmmm

Closing it 👍

**Comment by vito** [comment]
@cirocosta 👍 

fwiw, that test looks like it could fail if there are multiple workers, since I think it expects to see a cache hit. Maybe the k8s deployment had multiple and that caused it to fail?

**Comment by cirocosta** [comment]
@vito yeppp that was indeed the case :+1:  :+1:
