### ISSUE TITLE
--certs-dir is not honored by `concourse quickstart`

### ISSUE THREAD

**Issue by headcr4sh** [concourse/concourse#3366]
## Bug Report

It seems that `--cert-dir` (or the environment variable `$CONCOURSE_CERTS_DIR` is *not* honoured, when starting web/act + worker via `concourse quickstart`

## Steps to Reproduce

```sh
concourse quickstart --worker-work-dir=/tmp --certs-dir=/tmp
```

## Expected Results

Concourse quickstart should launch.

## Actual Results

Error message:
`unknown flag `certs-dir'`

## Additional Context

A downstream bug was reported to the concourse-sonarqube-resource:
https://github.com/cathive/concourse-sonarqube-resource/issues/30

## Version Info

* Concourse version: 4.2.3
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: on-prem
* Did this used to work: not sure / never tried before

**Comment by vito** [comment]
With `quickstart`, each worker flag has to be preceded by `--worker-` (just like `--worker-work-dir`). Otherwise there are ambiguities. So there should be a `--worker-certs-dir` flag available.

**Comment by headcr4sh** [comment]
Oh darn. I wasn't able to figure that out. Thanks for helping out, @vito.
