### ISSUE TITLE
LDAP authentication method

### ISSUE THREAD

**Issue by gtmtech** [concourse/concourse#338]
Would it be possible to have LDAP authentication in Concourse CI?

So many organisations have single signon done (and not through oAuth), it would be very useful to be able to run something like Concourse CI in these places.

**Comment by allomov** [comment]
@gtmtech right now the work is in a backlog, [there are plans](https://github.com/concourse/concourse/blob/13b003eb5a252801d6abdaa5037c7f6fedbf4f48/docs/setting-up/restricting-access.any#L95-L106) to make creation of new authorization sources easier.

I guess, the main focus will be set on integrating Concourse with UAA, multi tenant identity management service used by Cloud Foundry and BOSH. UAA has LDAP support, so the answer to your question is "yes", in some close future Concourse will have LDAP support :)

**Comment by allomov** [comment]
@gtmtech if this answered your question, please close the issue.

**Comment by kitsirota** [comment]
@allomov, if there is any way to add vanilla LDAP auth that would be ideal for us.  We're on the open source CF and hoping to minimize the dependencies on CF in general (including UAA).

Thank you!!!

**Comment by lordmortis** [comment]
This feature would also make us switching to pivotal a no-brainer

**Comment by mattfarina** [comment]
Anyone have a pointers on where one would get started?

**Comment by allomov** [comment]
@mattfarina hey!

[Here](http://concourse.ci/teams.html#uaa-cf-auth) is a doc that contains instructions on how to run concourse together with UAA.

[This docs](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md) integrate UAA with LDAP.

I hope this will help you to start.

**Comment by idcmp** [comment]
Looks like there's a decent golang ldap client here: https://github.com/jtblin/go-ldap-client

Being a member of a teams would ideally map to an OU membership.

**Comment by drywheat** [comment]
I think, realistically, you'll have to support LDAP in order to gain market share with large organizations that leverage AD, SimpleAD or OpenLDAP to handle their user management. 

Is there any movement here? I inspected the PT story and didn't see any change in state.

**Comment by wrast** [comment]
UAA should not be a requirement for LDAP integration

**Comment by codesplicer** [comment]
Has there been any progress on this? Kind of a non-starter for a lot of orgs without LDAP/AD support. Relying on deploying a UAA server as an additional dependency for AD integration is a workaround sure, but all the other tools in this space have native LDAP support. Would love to introduce concourse for the team here, but without native LDAP support its a 🚫

**Comment by jama-pivotal** [comment]
@codesplicer i think there's an open PR for a first draft of it in the ATC repo https://github.com/concourse/atc/pull/202 Its been a while since the original author responded to our feedback though

**Comment by venth** [comment]
PR is closed. Any progress with ldap integration?

**Comment by vito** [comment]
@venth see https://github.com/concourse/atc/pull/202#issuecomment-352123839

**Comment by jama-pivotal** [comment]
Linking to our user auth work #1888 , will close this issue when that one is released

**Comment by vito** [comment]
This is now in 4.0.0! But we haven't documented it.
