### ISSUE TITLE
Dashboard search dropdown is displaying without styles on Chrome

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#3381]
![screen shot 2019-02-25 at 10 33 28 am](https://user-images.githubusercontent.com/27746614/53348369-efe76c00-38e8-11e9-9f28-568c74b7a0cb.png)
When viewing the Dashboard in Google Chrome (Version 72.0.3626.109) the dropdown displays without the UI concourse style inconsistently. 

Sometimes the concourse styled dropdown returns after a mouse event but, the unstyled dropdown returns displaying overtop of the styled dropdown. 
![screen shot 2019-02-25 at 10 37 37 am](https://user-images.githubusercontent.com/27746614/53348637-713efe80-38e9-11e9-974c-54bfccdae019.png)

**Comment by pivotal-jamie-klassen** [comment]
this is the same as #3255. I did some poking around, and it sounds like autocomplete in Chrome is a [known pain point](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill). Adding `autocomplete="off"` to the input seemed to work when I was playing around in devtools.
