### ISSUE TITLE
Builds page polish: add border to title. 

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#3385]
## What challenge are you facing?

There is a border missing on the title area of the builds page. 

<img width="1564" alt="screen shot 2019-02-25 at 6 12 18 pm" src="https://user-images.githubusercontent.com/27746614/53375486-61dfa580-3929-11e9-8662-f68af4a3a71b.png">

## What would make this better?

Please add in a 1px border #3D3C3C to show that these are separate areas. 
 
![screen shot 2019-02-25 at 6 13 43 pm](https://user-images.githubusercontent.com/27746614/53375492-660bc300-3929-11e9-9bc7-02dad478bc0d.png)

**Comment by vito** [comment]
I think we'll probably just get rid of that page via the [build page redesign]( https://github.com/concourse/concourse/projects/12). Probably not worth polishing until then. :thinking:
