### ISSUE TITLE
GUI displays badly when metadata is very long

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3394]
## Bug Report

A pipeline uses a `git` resource as trigger, and one git commit has very long comment, which causes Concourse GUI display badly, see the screen shot:

![bad-display](https://user-images.githubusercontent.com/18585861/53466714-201c3f80-3a8e-11e9-8c51-cfda2f176583.png)

## Steps to Reproduce

Create a simple pipeline with a git resource as trigger. Then push a commit to git with multi-lines comment.

## Expected Results

Expected the GUI to show metadata properly.

## Actual Results

The GUI shows abnormally.

## Additional Context

I also tried this on a latest 5.0 build. 5.0 shows the long git comment properly.

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: k8s
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by vito** [comment]
As you noted, this is already fixed and will be in 5.0.

**Comment by evanchaoli** [comment]
@vito Is there any ETA for 5.0? We want to plan our work accordingly, because we are waiting for several important new features of 5.0.
