### ISSUE TITLE
high-density dashboard choice could be persisted

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3397]
## What challenge are you facing?

If you're on a team that regularly needs to use the high-density dashboard (like you are often clicking amongst a huge number of pipelines), you might prefer if every time you click the Concourse logo in the top right, you go to the high-density dashboard instead of always going to the default dashboard view. Having the extra click to turn on high-density every time you go back to the dashboard seems like it could be inconvenient.

## What would make this better?

Bikeshedding abounds - in increasing order of consistency (and also estimated complexity)

1. What if, within a local app 'session' (i.e. i'm clicking around between pages, but I've never refreshed), the most recent high-density setting was persisted?
1. What if your high-density setting was persisted in browser localStorage?
1. What if the *database* persisted it for your user!?

## Are you interested in implementing this yourself?

If it's actually a desirable feature, yes! This is a possibility we ran into while doing some refactoring (it lines up with a decent separation of responsibilities in the implementation), and we're interested in getting some feedback.

**Comment by Twiknight** [comment]
vote this up.

It is a real problem I came across when using concourse as we have 90 more pipelines now. It would cost 7 ~ 15 seconds before something shows up.

I would vote for solution 2 or 3, since they both eliminate the horrible experience every morning you open the concourse home : ).

**Comment by stringfellow** [comment]
This would also be great if the search box could be persisted in the same way after clicking into a pipeline and back to the main dashboard, for similar reasons (small team working on one thing at a time with many pipelines, some of which are related to each other by a key word)
