### ISSUE TITLE
Document `go generate` procedure for contributors

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3404]
Hey,

Looking at a recent code review from @pivotal-jwinters (https://github.com/concourse/concourse/pull/3313#issuecomment-467983548) and then comparing that comment to our current [contributing guide](https://github.com/concourse/concourse/blob/e19711506043a1af0ad273e76c2ece8d97c72ae9/CONTRIBUTING.md) available at , it's noticeable that we're lacking informing the need of re-generating the fakes when mutating the interfaces that are annotated with [`go:generate`](https://blog.golang.org/generate). 

In there we could also describe the need of ensuring that one must use the latest versions of [counterfeiter](https://github.com/maxbrunsfeld/counterfeiter) as the introduction of `go mod` support is a recent feature (https://github.com/maxbrunsfeld/counterfeiter/pull/94).

Thanks!

---

Leaving the `triage` as I'm not sure if just `enhancement` and `community/dev` is all we need.
cc @vito

**Comment by vito** [comment]
I think this was done in https://github.com/concourse/concourse/commit/7be3c122a56795dcb79cc091b9c744d8ac629203 :+1:
