### ISSUE TITLE
Postgres database performance becomes bad overtime with pipelines that runs often

### ISSUE THREAD

**Issue by Typositoire** [concourse/concourse#3412]
## Bug Report

Overtime, postgres db performance takes a hit with pipelines that runs oftens

## Steps to Reproduce

- Deploy https://github.com/concourse/oxygen-mask and wait ~2 month

## Expected Results

DB CPU and Bandwidth should stay normal

## Actual Results

CPU and Bandwidth are super high.

## Additional Context

https://cdn.discordapp.com/attachments/413770960089382922/550331854876573696/unknown.png
https://cdn.discordapp.com/attachments/413770960089382922/550331895192223747/unknown.png

Those graphs are at the time I deleted the whole thing a recreated it
- Cpu from 75% to 32% and Network from 10Mb/s to 2.5Mb/s

## Version Info

* Concourse version: 4.2.3
* Deployment type (BOSH/Docker/binary): Docker (Helm)
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable): N/A
* Did this used to work? N/A

**Comment by marco-m** [comment]
Seems to be a variation of #2624 ?

**Comment by Typositoire** [comment]
Indeed Oo Totally missed it.

Closing. I'll update https://github.com/concourse/concourse/issues/2624 instead.
