### ISSUE TITLE
Investigate Wings trigger job slowdown

### ISSUE THREAD

**Issue by chenbh** [concourse/concourse#3426]
As part of the [Run Existing Job](https://github.com/concourse/oxygen-mask/blob/master/monitor.yml#L101-L148) SLI we expect to take less than 5 seconds to trigger a build on an existing job.
  
Between Wednesday Feb 27 at 10 pm and Saturday March 1 at 12 pm some pipelines took up to 24 secs to trigger.
![image](https://user-images.githubusercontent.com/17577073/53742299-50852480-3e66-11e9-9496-2b7272ce482e.png)

Notes:
- There was no deployment when the issue started occurring (the previous deployment was on the 22nd and the next on the 28th)
- The issue was resolved without a deployment (at least no automatic deployment was recorded)
- Issue only applied to certain pipelines: a job with 147575 builds took over 10 secs whereas a job with only 120 builds took less than a second
- Logs were not searchable past last 24 hours so not much to go on there

**Comment by YoussB** [comment]
- We're not yet able to find a specific cause for the problem. Also, not having any logs is making things harder. 
- One possible cause can be network latency connecting to the db or db query time. If we had a metric that measures the time taken by a query to get executed, then we can tell if db or network are a cause of the issue.

cc: @pivotal-bin-ju

**Comment by cirocosta** [comment]
> If we had a metric that measures the time taken by a query to get executed, then we can tell if db or network are a cause of the issue

@pivotal-jwinters had some similar thoughts around having metrics for such queries 🤔

**Comment by YoussB** [comment]
@cirocosta 
I will echo @pivotal-bin-ju here, If we have such metric, it won't say there is a network latency for sure, yet it will indicate that there is a problem from the db end.

**Comment by YoussB** [comment]
findings:
- there are some functions that run when `CreatejobBuild` is run, most importantly: `CreateBuild` under `job.go:493`.
- This function runs a transaction that creates build data in the db.

Possible causes:
- network latency between the `oxygen mask` pipeline and the actual job it is running.
- many pipelines running at the same time adding more transactions to the db.
- network latency between atc and db (especially if they are not hosted on the same network).

Possible Mitigation/further research:
- add a metric for the time taken by the db to respond to queries.

**Comment by chenbh** [comment]
The problem came back at March 7th 2:23pm. 
![image](https://user-images.githubusercontent.com/17577073/53995903-95c68200-4104-11e9-9c06-7a1b138189bb.png)

- still `simple-job` with over 150k build history having trouble while `auto-triggering` with 116 builds triggering in less than a second
```
$ time fly -t monitor tj -j monitoring/simple-job
started monitoring/simple-job #152025
       60.68 real         0.12 user         0.07 sys
$ time fly -t monitor tj -j monitoring/auto-triggering
started monitoring/auto-triggering #117
        0.43 real         0.12 user         0.07 sys
```
- logs were searchable this time but there was nothing interesting in them

- one thing to note is that this time, the CloudSQL db we're using hit 100% utilization about 3 hours before the incident occurred
![image](https://user-images.githubusercontent.com/17577073/53995784-2ea8cd80-4104-11e9-8479-63a838f636c5.png)

Looking back, the db appears to be operating normally during the first incident so this might just be a coincidence
![image](https://user-images.githubusercontent.com/17577073/53995850-6ca5f180-4104-11e9-801a-5bce341f15f9.png)

**Comment by chenbh** [comment]
potentially related to https://github.com/concourse/concourse/issues/2624

**Comment by chenbh** [comment]
Summarizing what we found out:
- Whenever the ATC tries to schedule builds it will eventually get to `tryStartNextPendingBuild` and run https://github.com/concourse/concourse/blob/ef6d43589a566c380ba4164511de044a5774b4f7/atc/scheduler/buildstarter.go#L112
- which runs a query that wastes a lot of time indexing https://github.com/concourse/concourse/blob/ef6d43589a566c380ba4164511de044a5774b4f7/atc/db/pipeline.go#L694-L709
- https://github.com/concourse/concourse/issues/3460 and https://github.com/concourse/concourse/issues/3459 have been created to figure out a better index
- the random times where it fixed itself was due to the db vacuuming efficiently

cc @clarafu @pivotal-jwinters @jchesterpivotal @topherbullock
