### ISSUE TITLE
Cannot login to Concourse Web using Firefox

### ISSUE THREAD

**Issue by amuessig** [concourse/concourse#3438]
## Bug Report

When using Firefox, a login is not possible since the cookie cannot be set.

## Steps to Reproduce

1) Deploy Concourse v4.2.3 (HTTPS enabled)
2) Use Firefox 65.0.2 to access the Concourse WEB UI
3) Login to concourse (tested with a local user and LDAP user)

> (please include any pipelines/tasks using https://gist.github.com)

## Expected Results

I expect to be successfully logged into concourse

## Actual Results

After entering the username/password and submitting this page, a blank page is shown.

## Additional Context

Logs in atc show that the login is successful. However, the error says that a cookie cannot be set.

`/var/vcap/sys/log/atc/atc.stdout.log`:
```
{"timestamp":"1551778162.090207577","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"garbage collection run, delete auth requests=1, auth codes=0","session":"5"}}
{"timestamp":"1551781379.318979025","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{"connector":"LDAP"},"message":"performing ldap search DC=<....>","session":"5"}}
{"timestamp":"1551781379.320216894","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{"connector":"LDAP"},"message":"username \"<username>\" mapped to entry CN=<....>","session":"5"}}
{"timestamp":"1551781379.324945211","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector \"ldap\", username=\"<username>\", email=\"<email>\", groups=[]","session":"5"}}
{"timestamp":"1551781379.332607746","source":"atc","message":"atc.sky.callback.failed-to-fetch-cookie-state","log_level":2,"data":{"error":"http: named cookie not present","session":"4.25"}}
```
This occurs only using firefox. It works well in chrome.
I also checked if cookies are disabled in firefox but didn't find anything. I explicitly allowed cookies for this domain and tried to turn off all security features that could be related to that.

## Version Info

* Concourse version: 4.2.3
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vsphere
* Browser (if applicable): Firefox 65.0.2
It also works with latest Chrome version `72.0.3626.121`
* Did this used to work? Yes

**Comment by xtremerui** [comment]
What OS are you using? We can't reproduce your issue using same version of firefox under mac 10.13.6.

**Comment by amuessig** [comment]
For this I am using Windows 10.

**Comment by jama22** [comment]
Weird, I just tried on my Firefox browser on Windows 10 and I couldn't repro. I'm logging in via GitHub though, not sure if that makes a difference

Firefox Quantum 65.0.2 (64-bit)
Windows 10 pro Version	10.0.17763 Build 17763

**Comment by michaelklishin** [comment]
I cannot reproduce. Have you tried looking at the JS console for any possible exceptions? What about clearing the cache in Firefox?

**Comment by vito** [comment]
Could be a bug with starting the login flow on the wrong URL - it has to match the external URL. e.g. if your external URL is `localhost:8080` but you're logging in through `127.0.0.1:8080` I think you'll get that sort of error.

**Comment by jdelic** [comment]
I ran into the same problem today. It turned out that when I upgraded the box from concourse 4.x to 5.x I hadn't set up a link between the Oauth2 `groups` claim and the concourse team using `fly`. Interestingly, this seems to fail "earlier" in Firefox then in Chrome. Chrome shows a `401 access denied` page, where Firefox just draws a blank page and logs 

```
{"timestamp":"1551781379.332607746","source":"atc","message":"atc.sky.callback.failed-to-fetch-cookie-state","log_level":2,"data":{"error":"http: named cookie not present","session":"4.25"}}
```

In both cases an error page for the missing match between a concourse team and the Oauth2 groups claim and a log message to that effect would be very useful.

**Comment by ruuda** [comment]
> Could be a bug with starting the login flow on the wrong URL - it has to match the external URL. e.g. if your external URL is localhost:8080 but you're logging in through 127.0.0.1:8080 I think you'll get that sort of error.

Thanks! I ended up at this issue after searching for the `atc.sky.callback.failed-to-fetch-cookie-state` error message that appeared in the logs. Using `localhost` on the `fly` command-line while the server was listening on `127.0.0.1` was indeed the issue. It may be worth mentioning this case in the docs explicitly.

**Comment by swizzley** [comment]
I just get a blank screen in firefox

```{"timestamp":"2019-06-06T15:59:19.180133864Z","level":"error","source":"atc","message":"atc.sky.redirect.invalid-redirect","data":{"error":"Unsupported redirect uri: http://127.0.0.1:54278/auth/callback","session":"5.8"}}```

**Comment by ramonskie** [comment]
don't know it this is relevant.
but when i upgraded from 4.x to 5.x
i received 400 error when loggin in with fly
the login url was `https://mydomain.com/sky/login?redirect_uri=http://127.0.0.1:39599/auth/callback`
but the new 5.x way of loggin in is via `https://mydomain.com/login?fly_port=57566`

this seem to be related due to the fly versions
fly 4.x is the `redirect_uri`
and 5.x uses `login?fly_port`

you think with a simple fly sync it would solve the problem but as you are on fly 4.x
you can't because if you want to sync you need to login..

the workarround is use the  `https://mydomain.com/login?fly_port=57566`
copy the token and login and sync your fly binary

**Comment by jdelic** [comment]
@ramonskie is correct.

I ran into the same issue. Concourse 5.x should probably have backwards-compatible URL redirects for older `fly` versions.

**Comment by prein** [comment]
Just upgraded from 5.8 to 6.6. Blank (gray) page in FF, works in Chrome. Using local user.
Can't figure out from reading this thread if there's a fix for this I can apply.

**Comment by xtremerui** [comment]
@prein are you running concourse locally? Is there any logs from the FireFox developer console or Concourse web node?

**Comment by prein** [comment]
@xtremerui thanks for looking into it. I am running concourse on Kubernetes, deployed with Helm. Firefox developer console comes with the following line
```
SyntaxError: expected dot, got '('[Learn More] elm-setup.js:1:37 
```
Additional finding. after checking with different FF versions. The error occurs with 63.0 and 64.0 (64-bit) while it doesn't with 68.0.2 (64-bit) and 81.0.2 (64-bit). I guess I should not raise alarms over errors in old browser versions.

**Comment by xtremerui** [comment]
@prein interesting. Thx pinning it down to certain versions. 

It seems the JS engine has issue with importing path.
https://github.com/concourse/concourse/blob/b41c66badebc8eac5efe58aa1532df7947797f89/web/public/elm-setup.js#L1

Will see if this happens again with future FF releases.
