### ISSUE TITLE
Standalone linux worker fails with: "execveat: Function not implemented"

### ISSUE THREAD

**Issue by flaub** [concourse/concourse#344]
Running Ubuntu Server 14.04 64-bit. When using `fly` to execute a one-off task, I get the following output:

```
$ uname -a
Linux ci 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ fly -t ci execute -c build.yml
targeting http://ci:9090

executing build 14
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1028M    0 1028M    0     0  17.0M      0 --:--:--  0:01:00 --:--:-- 11.9M
initializing
error streaming in: exit status 1. Output: execveat: Function not implemented

errored
```

**Comment by flaub** [comment]
Reviewing the installation docs, I realized that using kernel 3.19+ wasn't optional, so once I used this kernel, everything appears to work.

**Comment by emcniece** [comment]
@flaub any tips for a fix?

**Comment by flaub** [comment]
I think the issue here was that I wasn't using a supported kernel.

**Comment by emcniece** [comment]
Where is this requirement documented? This is failing for me on 3.16

**Comment by alex-bender** [comment]
@emcniece, probably here: [Prerequisites](https://concourse.ci/binaries.html)

**Comment by emcniece** [comment]
This works as expected after upgrading kernel to 4.9.
