### ISSUE TITLE
Missing garbage collection metrics for Prometheus

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3445]
Metrics related to garbage collection of either volumes or containers are not reported by the Prometheus emitter.

Looking at the Concourse metrics that we currently convert to Prometheus metrics, those like "orphaned volumes to be garbage collected"

https://github.com/concourse/concourse/blob/4eb581a8592e0fc47a4c75a2c7a9af00f9db3986/atc/metric/metrics.go#L156-L170

do not appear in the `switch` that the Prometheus emitter uses:

https://github.com/concourse/concourse/blob/0e5afd0dffe363e06edcaedccd1f7109ff2d9a21/atc/metric/emitter/prometheus.go#L322-L355

Hopefully, https://github.com/concourse/concourse/issues/2896 will help alleviate these problems 🙌  

--

Raising this from https://github.com/concourse/hush-house/issues/14

**Comment by cirocosta** [comment]
whooops, we still miss them

**Comment by aledeganopix4d** [comment]
@cirocosta does #4446 fixes this one too?

**Comment by cirocosta** [comment]
Hey @aledeganopix4d,

it actually doesn't 😅 That was about fixing the way we do GC for counters  & gauges that are not meant to be kept track of anymore.

This particular issue here is about adding new counters & gauges that'd keep track of how many containers / volumes are being GCed.
