### ISSUE TITLE
Two credential managers are instantiated

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3448]
## Bug Report

In testing Vault integration while improving the docs, I noticed duplicated renewal logs:

```
concourse_1     | {"timestamp":"2019-03-07T22:24:59.547356629Z","level":"info","source":"atc","message":"atc.credential-manager.renew.succeeded","data":{"lease-duration":10,"name":"vault","policies":["concourse"],"session":"8.24","token-accessor":"zLtPLHgKfIxV4B6GJY0xEoqo"}}
concourse_1     | {"timestamp":"2019-03-07T22:24:59.547458076Z","level":"info","source":"atc","message":"atc.credential-manager.renew.succeeded","data":{"lease-duration":10,"name":"vault","policies":["concourse"],"session":"17.24","token-accessor":"3Dg27UQJVZiPbluuFMRE7hG9"}}
```

## Steps to Reproduce

Configure Vault (or anything I guess, but Vault is easiest to observe due to its token renewal) and start Concourse.

## Expected Results

I should only see one renewal loop.

## Actual Results

I see two.

## Additional Context

Looks like the variables factory is being constructed in two places:

* https://github.com/concourse/concourse/blob/c0422a90aed2ff18b8411b9f5dcaf87b784802b8/atc/atccmd/command.go#L547
* https://github.com/concourse/concourse/blob/c0422a90aed2ff18b8411b9f5dcaf87b784802b8/atc/atccmd/command.go#L744

## Version Info

* Concourse version: 5.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by demamoh** [comment]
@vito Wanted to add an additional question to this that may become standalone. Have you been noticing this weird error with vault after authenticating with approle succeeds. `"data":{"error":"Finding variable 'username': Error making API request.\n\nURL: GET http://vaullt:8200/v1/%!C(MISSING)nil%!E(MISSING)/main/testservice/username\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n","pipeline":"testservice","resource":"testApp","session":"20.1.3.1.1","team":"main"}}`

**Comment by vito** [comment]
@demamoh that seems unrelated - please open a different issue or ask in the forums/discord if you need assistance

**Comment by demamoh** [comment]
@vito  No problem moved the issue to a new one. It can be referenced here https://github.com/concourse/concourse/issues/3481

**Comment by vito** [comment]
fixed by https://github.com/concourse/concourse/pull/3615
