### ISSUE TITLE
[Feature Request] Use rsync algorithm for execute command

### ISSUE THREAD

**Issue by flaub** [concourse/concourse#345]
When the source directory is large, it takes awhile to copy the working directory up to the `atc`. It would be nice if I could have a reusable session wherein execute would only need to upload deltas instead of the entire working directory again.

**Comment by baszalmstra** [comment]
+1

**Comment by vito** [comment]
I don't think we'll be doing this; it'd be very complicated to implement and doesn't seem worth it to me. There's nothing correlating `execute` with one another and the semantics seem hard to define. Thanks for the feedback though!
