### ISSUE TITLE
5.0 upgrade: ErrAuthNotConfiguredFromFlags

### ISSUE THREAD

**Issue by luispabon** [concourse/concourse#3450]
## Bug Report

Upon upgrade to 5.0, I get the following error from the `web` deployment:

`default team auth not configured: ErrAuthNotConfiguredFromFlags`

## Steps to Reproduce

  - Install concourse 4.2.x in a docker deployment
  - Use the env var ` CONCOURSE_ADD_LOCAL_USER` to add a single local user to the main team
  - Upgrade to 5.0 by simply running 5.0 against the same database

Error above happens.

## Expected Results

Doesn't happen?

## Actual Results

The web container fails to start with the message above.

## Additional Context

So I have a very simple deployment of concourse on a small kubernetes cluster I run some personal projects on.

Concourse is split into two deployments: `web` and `worker --ephemeral`, backed by a postgres instance. See https://pastebin.com/VYGsXtJG for simplified kubernetes setup. 

There's a single concourse admin user added via the env var detailed above. Since I didn't restrict the deployment to a specific tag like I should have, today concourse updated to 5.0 as I cycled the kubernetes nodes. Upon starting the `web` container, the error above happened.

## Version Info

* Concourse version: 4.2.3 >> 5.0.0
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS: kubernetes
* Browser (if applicable): n/a
* Did this used to work? n/a

**Comment by xiaozhu36** [comment]
I use [docker-compose.yml file](wget https://concourse-ci.org/docker-compose.yml
) to quick statrt concourse, and got the same error:
```
concourse_1     | default team auth not configured: ErrAuthNotConfiguredFromFlags
concourse_1     | {"timestamp":"2019-03-07T15:53:03.586003592Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":259325,"session":"1"}}
root_concourse_1 exited with code 1
```

**Comment by nzwei** [comment]
besides CONCOURSE_ADD_LOCAL_USER, have you added CONCOURSE_MAIN_TEAM_LOCAL_USER?

**Comment by luispabon** [comment]
@nzwei no, as that didn't seem to be necessary before. What am I supposed to add in there?

**Comment by nzwei** [comment]
@luispabon the username
    - CONCOURSE_ADD_LOCAL_USER=test:test
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=test
did it for me

**Comment by xtremerui** [comment]
@luispabon refer to https://concourse-ci.org/download.html#v500-note-2

The `--allow-all-users` is removed in 5.0, so you have to specify user for every team explicitly, for example see @nzwei 's commend above.

**Comment by luispabon** [comment]
Rogerto, I'll do this and report back :+1:

**Comment by luispabon** [comment]
Report ok, thank you for your help :+1:
