### ISSUE TITLE
Proposal: keyboard shortcut to move from job-view to containing-pipeline-view

### ISSUE THREAD

**Issue by jpluscplusm** [concourse/concourse#3452]
## What challenge are you facing?

Almost all of the time I jump into a specific job from the pipeline view, my next page move is back to the pipeline view.

The pipeline name, top left of the UI, has relatively poor affordance and isn't trivial to mouse back to.

## What would make this better?

It would be really handy to have a keyboard shortcut to take me from a job view to the pipeline view of the job's containing pipeline. 

## Are you interested in implementing this yourself?

Slightly, but it's 100% outside my dayjob!

I /suspect/ someone who knows the codebase and existing shortcuts could slam this in in pretty short order ... especially as they "only" have to lop off the `/jobs/<jobname>/builds/<Id>` suffix from the URI :-)

**Comment by pivotal-jamie-klassen** [comment]
`-` feels like a good choice to me, inspired by netrw.
