### ISSUE TITLE
Comparisons using text (md5) or jsonb for resource versioning

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#3460]
The `build_resource_config_version_inputs/outputs` and `resource_disabled_versions` tables in the database have `version_md5` text columns instead of a `version` jsonb column with the purpose of faster comparisons to find the resource version from the `resource_config_versions` table.

We would like to confirm whether using a `version_md5` text column or a `version` jsonb column will result in faster lookups. This is also taking into consideration that there will most likely be indexes created on these columns.

EDIT: Confirm which is fastest out of the following options (including indexes for them)
- `version_md5` text
- `version_md5` bytea
- `version` jsonb

**Comment by jchesterpivotal** [comment]
Another alternative to try in the bake-off is using `bytea` instead of `text` for storing `version_md5`.

**Comment by clarafu** [comment]
@jchesterpivotal Thanks! I'll add that to the issue :)

**Comment by jchesterpivotal** [comment]
Also noticed, this might replace #3459?
