### ISSUE TITLE
Retiring workers takes more than 10 hours

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3462]
## Bug Report

I retired some workers yesterday, "fly" shows "retiring" state for those workers:

     name                                    containers  platform  tags  team  state     version
     worker-175                             77          linux     none  none  retiring  2.1
     worker-177                             94          linux     none  none  retiring  2.1

It has been more than 10 hours, they are still "retiring". Count of containers doesn't decrease at all.

## Steps to Reproduce

Not sure.

## Expected Results

Retiring a worker should take less than 1 hour as no task should last more than 1 hour.

## Actual Results

Retiring workers has taken more than 10 hours.

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: VM
* Browser (if applicable): any
* Did this used to work? No sure

**Comment by vito** [comment]
Not much we can do here without steps to reproduce.

> Retiring a worker should take less than 1 hour as no task should last more than 1 hour.

Have you configured a task timeout or a drain timeout or anything? What makes you say no task should take more than 1 hour?

**Comment by evanchaoli** [comment]
Because no task will run longer than 1 hour, or in the worst case longer than 10 hours.

So that, after 2 days, there are still 2 workers in "retiring" state. I have even killed `concourse worker` process, but `fly` still shows they are retiring:

worker-164    88          linux     none  none  retiring  2.1
worker-173   94          linux     none  none  retiring  2.1

**Comment by evanchaoli** [comment]
ATC loops the following logs:

    {"timestamp":"1552275465.118041754","source":"atc","message":"atc.collector.tick.volume-collector.mark-volumes.mark-created-as-destroying.failed-to-transition","log_level":2,"data":{"error":"volume cannot be destroyed as children are present","session":"23.12348.9.2.17","volume":"19b54b08-9bfa-47ee-4c90-e5dfcdfd6b82","worker":"worker-164"}}
    {"timestamp":"1552275467.582719326","source":"atc","message":"atc.collector.tick.container-collector.orphaned-containers.queue.worker-not-found","log_level":1,"data":{"job-name":"created-containers-38","session":"23.14375.8.1.5","worker-name":"worker-164"}}
    {"timestamp":"1552275467.599389791","source":"atc","message":"atc.collector.tick.volume-collector.mark-volumes.mark-created-as-destroying.failed-to-transition","log_level":2,"data":{"error":"volume cannot be destroyed as children are present","session":"23.14375.9.2.3","volume":"3717271e-cfd1-4e1a-41bf-a19e9e43f1c0","worker":"worker-164"}}
    {"timestamp":"1552275467.604191542","source":"atc","message":"atc.collector.tick.volume-collector.mark-volumes.mark-created-as-destroying.failed-to-transition","log_level":2,"data":{"error":"volume cannot be destroyed as children are present","session":"23.14375.9.2.5","volume":"25cbd7d7-d83e-4404-558f-322677eba7b9","worker":"worker-164"}}

Finally, I have to use `fly` to prune those workers.
