### ISSUE TITLE
Vault 403 error with malformed get request %!C(MISSING)nil%!E(MISSING)

### ISSUE THREAD

**Issue by demamoh** [concourse/concourse#3481]
## Bug Report

Vault integration is erroring out trying to get a secret. The credential manager is authenticated with approle, and that succeeds.  This comes up when trying to access a secret when a pipeline runs. 

### Follow these steps below in order
- CONCOURSE_VAULT_AUTH_BACKEND = "approle"
- CONCOURSE_VAULT_AUTH_PARAM = "role_id:example,secret_id:example"

## Expected Results

The secret should have been retrieved and should continue on with pipeline

## Actual Results

`"data":{"error":"Finding variable 'username': Error making API request.\n\nURL: GET http://vault:8200/v1/%!C(MISSING)nil%!E(MISSING)/main/testservice/username\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n","pipeline":"testservice","resource":"testApp","session":"20.1.3.1.1","team":"main"}}`

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version:
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by vito** [comment]
Seems like something is configuring the credential path prefix as `<nil>`?

**Comment by demamoh** [comment]
@vito you are correct. I was using an older version of the concourse helm chart which had the default prefix, and the newest version did not, that fixed the issue. Thank you.
