### ISSUE TITLE
Can't use vars from documentation example

### ISSUE THREAD

**Issue by NatashaKramarenko** [concourse/concourse#3482]
## Bug Report
Example for vars from official documentation does not work
https://concourse-ci.org/task-step.html#task-step-vars

When creating pipeline with vars I get error

error: invalid configuration:
unknown/extra keys:
  - jobs[0].plan[1].vars

[pipeline.yml](https://gist.github.com/3468f6dfca0a4f8684d5ddc58cc693ec.git)
---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/NatashaKramarenko/concoursetest.git
    branch: master

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
  - task: good-morning
    file: resource-tutorial/tasks/task_hello_world.yml
    vars:
      text: "Hello world!"

## Steps to Reproduce

Command line:
fly -t tutorial sp -p hello-world -c pipeline.yml

## Expected Results

Hello World! to be printed out in the pipeline job

## Actual Results

error: invalid configuration:
unknown/extra keys:
  - jobs[0].plan[1].vars

## Version Info

* Concourse version:version: v4.2.1
* Deployment type (BOSH/**Docker**/binary):2.0.0.3 
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work? Not Sure

**Comment by marco-m** [comment]
Hello,

from the bug report you are using 4.x, while `vars` has been introduced in 5.0, see https://concourse-ci.org/download.html#v500-note-11

I know the Concourse team is making the documentation version-aware but is seems it is not ready yet.

I think this ticket can be closed :-) Consider also asking your questions on https://discuss.concourse-ci.org/

**Comment by vito** [comment]
as @marco-m said this is a 5.0 feature, so closing, though it would be nice if the docs noted which version these params first appeared in

**Comment by vergissberlin** [comment]
Or even better, having a switch for the versions like on https://docs.readthedocs.io/en/stable/

**Comment by marco-m** [comment]
@vergissberlin if I am not mistaken, what you are asking for is coming in https://github.com/concourse/docs/tree/ci-build-all-versions. Is this correct @osis ?

**Comment by osis** [comment]
Yep!
