### ISSUE TITLE
Can all workers use same tsa-worker-private-key?

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3483]
## Bug Report

This is actually a query instead of a bug.

I thought each worker should have a different key, and I even wrote a worker key manager. But today I happened to find that when I deployed multiple workers with same worker key, all workers got up and running normally.

Before I through away my worker key manager, I just want to confirm if a workers can share a single worker key?

## Version Info

* Concourse version: 4.2.2 and 5.0.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: VM
* Browser (if applicable): Any
* Did this used to work? NA

**Comment by vito** [comment]
Yes, they can, but please don't open bugs just for questions. Use the [forums](https://discuss.concourse-ci.org) or Discord instead.

**Comment by marco-m** [comment]
Yes, all workers can share the same key. On Concourse 3.x, 4.x, 5.x.

**Comment by marco-m** [comment]
Yes, all workers can share the same key. At least on Concourse 3.x, 4.x, 5.x. I think this question can be closed. Please for this kind of questions consider posting to https://discuss.concourse-ci.org/ before :-)
