### ISSUE TITLE
OIDC with Okta doesn't get username or groups

### ISSUE THREAD

**Issue by MartinLeedotOrg** [concourse/concourse#3486]
## Bug Report
I have followed the steps at:
https://concourse-ci.org/generic-oidc-auth.html

I have created an app in Okta with the implicit flow and mapped all groups.

## Steps to Reproduce

Following environment variables:
export CONCOURSE_OIDC_DISPLAY_NAME=Okta
export CONCOURSE_OIDC_CLIENT_ID=clientid
export CONCOURSE_OIDC_CLIENT_SECRET=clientsecret
export CONCOURSE_OIDC_ISSUER=https://issuer.issuer.com
export CONCOURSE_MAIN_TEAM_OIDC_GROUP=dev-concourse
export CONCOURSE_OIDC_GROUPS_KEY='groups'
export CONCOURSE_OIDC_SCOPE='openid groups'

## Expected Results

Username and groups to be passed to concourse to allow user to join the main team

## Actual Results

HTTP 401 returned to clients, following in logs:
```
{"timestamp":"2019-03-12T17:03:17.480427687Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"oidc\", username=\"\", email=\" foo@bar.com (unverified)\", groups=[]","session":"6"}}
{"timestamp":"2019-03-12T17:03:17.532387726Z","level":"error","source":"atc","message":"atc.sky.callback.failed-to-issue-concourse-token","data":{"error":"user doesn't belong to any team","session":"5.40"}}
```
## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: debian
* Browser (if applicable): N/A
* Did this used to work? N/A

**Comment by mattskone** [comment]
I'm experiencing and troubleshooting the same, but with 4.2.2 on Kubernets via Helm.  Possibly some overlap with https://github.com/concourse/concourse/issues/2683?

**Comment by MartinLeedotOrg** [comment]
In okta you can specify a regex for which groups get passed through in the groups claim. I've specified .* (and verified that works in another application).

`dev-concourse` is a group I've set up for this test.

I can see that username might not be supported - looks like it falls back to sub? That's fine for me - less than ideal but works. Groups not working is a bigger problem though.

I can have okta only allow authentication for certain users, is there a combination of the configuration that would allow me to say "All users authenticating by OIDC should be in the main team"?

**Comment by MartinLeedotOrg** [comment]
For those who get here from google - here's a clunky workaround:

Log in with a username/passwrd

Run `fly -t dev set-team -n main --oidc-user=subjectid`

You can get the sub id from Okta by looking at the logs and checking the "ID" for the user involved.

**Comment by cludden** [comment]
Is this related to this dex issue: https://github.com/dexidp/dex/issues/1065 and corresponding PR that is apparently blocked https://github.com/dexidp/dex/pull/1066?

**Comment by gbvanrenswoude** [comment]
plus 1 on this issue

**Comment by cappyzawa** [comment]
I think this similar to https://github.com/concourse/concourse/issues/3855

**Comment by gbvanrenswoude** [comment]
@MartinLeedotOrg Did you get the groups claim working?

**Comment by MartinLeedotOrg** [comment]
I'll be honest, I gave up on concourse for now for reasons other than auth (mainly related to how pipelines get versioned with code).

**Comment by andy-lumiq** [comment]
seems like with okta OIDC, `groups` claim is not passed in id token, unless you're using implicit flow and concourse / dex force the use of auth code flow. I faced similar stuff in Argo CD, however it allows usage of implicit flow, hence it's possible to get the groups information

**Comment by Sluggerman** [comment]
Hit this issue with groups claim, wonder if anyone is looking into this.

**Comment by andy-lumiq** [comment]
I used generic oauth instead, and it's able to get the groups claim

**Comment by Sluggerman** [comment]
yep, ended up going with oauth as well, works.

**Comment by samgurtman** [comment]
Has anyone had any success yet with using Okta OIDC? It seems that some Okta subscriptions do not allow Oauth2.

**Comment by hfinucane** [comment]
Totally not the right forum, but for those of you who got groups working with OAuth, how did you configure Okta & Concourse?

**Comment by gbvanrenswoude** [comment]
In the web flags:

--oidc-display-name "Corp OKTA" \ --oidc-scope "openid profile email phone address groups" \ --oidc-issuer "https://corp.okta-something.com/oauth2/default" \ --oidc-client-id "zzzzzzzz" \ --oidc-client-secret "evenmorezzzzz" \ --oidc-user-name-key "email" \ --main-team-oidc-group "concourse-main" \ --oidc-groups-key "groups" 

And in OKTA enable the group claims setting.

**Comment by acarsercan** [comment]
Anyone got this working with helm chart? what a pain

**Comment by acarsercan** [comment]
Using oauth2 instead

**Comment by mlopez-eb** [comment]
This is an issue I'm running into now. Okta OIDC & OAUTH were both set up for this and neither pick up the group claims.

Concourse 6.1.0
Installed with Helm

![Screen Shot 2020-08-05 at 5 32 05 PM](https://user-images.githubusercontent.com/52426536/89466644-35e16a00-d742-11ea-8a22-be69f0c4408c.png)
![Screen Shot 2020-08-05 at 5 33 34 PM](https://user-images.githubusercontent.com/52426536/89466646-38dc5a80-d742-11ea-8ac5-7bde4cf5f45a.png)
![Screen Shot 2020-08-05 at 5 35 28 PM](https://user-images.githubusercontent.com/52426536/89466653-3b3eb480-d742-11ea-8400-5a1f437d1936.png)

I'm able to log in, but not in the main group which my user is a part of (created in Okta, and enabled in screenshot #1)

No matter what the set up, groups comes back empty in the logs:

`[ec2-user@ip-10-13-1-211 ~]$ docker logs 18c12ffab476 | grep dex
{"timestamp":"2020-08-05T19:59:03.840703634Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"oauth\", username=\"\", email=\"My_Name@BlahBlahBlah.com\", groups=[]","session":"14"}}
{"timestamp":"2020-08-05T21:38:30.557195483Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"oidc\", username=\"My_Name@BlahBlahBlah.com\", email=\"My_Name@BlahBlahBlah.com (unverified)\", groups=[]","session":"14"}}`

This really needs to be re-opened. Okta OIDC & OAUTH are major ID providers to not be working with this application.

🙏🏽🙏🏽🙏🏽

**Comment by samgurtman** [comment]
I also really would like this to be reopened. We've been wanting to use Okta. Some plans in Okta only allow openId Connect so we can't use oauth2.

**Comment by adnankobir** [comment]
It appears that if you want groups scope returned from Okta, you need to enable [API Access Management](https://developer.okta.com/docs/concepts/api-access-management/). Furthermore, you'll likely need to enable "custom scopes" via a [Custom Authorization Server](https://developer.okta.com/docs/guides/customize-authz-server/overview/). This is a paid feature in Okta. 

The free alternative is to use SAML #5998 - which I have tested successfully with Okta.

**Comment by danpilch** [comment]
@samgurtman-zz @mlopez-eb I have opened a PR to fix this https://github.com/concourse/concourse/pull/8353
