### ISSUE TITLE
Investigate Postgres CPU Utilization after migrating to 5.0.0

### ISSUE THREAD

**Issue by YoussB** [concourse/concourse#3487]
## Bug Report

After upgrading to 5.0.0 on Wings we noticed an increase in the CPU utilization on Google Cloud SQL 

<img width="943" alt="Screen Shot 2019-03-12 at 12 03 35 PM" src="https://user-images.githubusercontent.com/17758967/54223850-bdd02f80-44ce-11e9-832f-10936949f1b3.png">

## Additional Context

- Might have to do with extra joins added to SQL queries as of 5.0.0.

## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): Bosh, Google cloud SQL
* Infrastructure/IaaS: GCP

**Comment by Typositoire** [comment]
We do have the same thing here. We're seeing a 10% increase load with 5.0.0

**Comment by vito** [comment]
Addressing this in #3602 - closing!
