### ISSUE TITLE
Do we use baggageclaim's Reaper functionality?

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3495]
Hey,

Yesterday, I was trying to troubleshoot why we're seeing [such high system CPU utilization in one of our installations](https://github.com/concourse/hush-house/issues/22), and after tracing the node which is running `concourse worker`, noticed that a big percentage of the time we're spending is related to Baggageclaim's `Reaper.Reap`.

https://github.com/concourse/baggageclaim/blob/685f90a56bed9a883301df0857e70559b3fe9a7e/reaper/reaper.go#L29

<img width="1920" alt="Screen Shot 2019-03-13 at 11 21 38 AM" src="https://user-images.githubusercontent.com/3574444/54291905-a99a3a00-4583-11e9-9349-d9d08f652b68.png">

*(essentially, the bigger you go on the horizontal axis, the bigger the percentage of the samples captured in such code path)*

As far as I remember, we don't rely on any of that logic at the moment. Is that right?
If so, should we get rid of it? 

Thanks!

---

Update: note that each of the workers run with ~1k volumes each, so those `ListVolumes` call end up being quite expensive.

**Comment by cirocosta** [comment]
cc @kcmannem @ddadlani

**Comment by kcmannem** [comment]
https://github.com/concourse/baggageclaim/blob/1997f65aac8e792cdff3cded3c2ded346b190c79/volume/repository.go#L467-L481

This is a big sink to our CPU resources. Reading/Decoding ~1000 json files (properties.json) probably doesn't scale well.

I really don't know what the point of the reaper is currently. I can only imagine it was part of the old GC flow. Any context @vito

**Comment by kcmannem** [comment]
https://github.com/concourse/baggageclaim/blob/1997f65aac8e792cdff3cded3c2ded346b190c79/volume/repository.go#L467-L481

Reading/Decoding ~1000 json files (properties.json) probably doesn't scale well to be done on an interval such as what the reaper is doing. We can't figure out why we use it either. Any context @vito? Is it just remnants of the old GC flow?

**Comment by vito** [comment]
Yeah, it's a remnant of the days when we relied on volume TTLs for volume destroying. It's what made volumes expire, and what made sure to reap child volumes before parent volumes.

We do all of this in the ATC now, including the parent/child protection (see #1780). If we want to remove it we should probably just remove *all* TTL handling from BaggageClaim.

**Comment by kcmannem** [comment]
@vito we're killing it with fire. 🔥

**Comment by cirocosta** [comment]
oooh nice to know! thanks!!

**Comment by cirocosta** [comment]
It's gooooone
