### ISSUE TITLE
fly becomes unresponsive after login succeeds; cancel and re-do as workaround

### ISSUE THREAD

**Issue by larham** [concourse/concourse#3503]
## Bug Report

fly becomes super slow to respond after "inline" login succeeds.  However, if I cancel and re-do the same command, which uses the newly-minted auth, it is fine. 

## Steps to Reproduce

* in bash, run a command like this with an auth for target "dev" that is expired:
`fly -t dev i -u https://<some URL>`

Output:
```  
could not find a valid token.
logging in to team 'main'

navigate to the following URL in your browser:

  https://<someURL>auth/callback`
```
* click on link, authenticate successfully in browser
* alt-tab back to the `fly` context in console. 
* the list of numeric options is on screen
* however, typing even one letter is almost impossible because of slowness

## Expected Results

normal speed

## Actual Results

At this point, often the response time is super delayed, even to see typed characters

## Additional Context

workaround:  cancel out of current session with control-c, reuse same command line again, which uses the newly-minted auth and does *not* prompt for auth, it is fine--normal response times as expected.

## Version Info

* Concourse version:
concourse, fly 4.2.1

* Deployment type (BOSH/Docker/binary):
bosh, as part of  pivotal team pipelines
* Infrastructure/IaaS:
gcp 
* Browser (if applicable):
lastest chrome on macos

**Comment by vito** [comment]
This was fixed in 5.0 :+1:
