### ISSUE TITLE
Add Content-Security-Policy Directive

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#3512]
## What challenge are you facing?
Currently, configuring `x-frame-options` with a value of `allow-from` lacks support in several browsers. Using  `Content-Security-Policy` is the replacement for `x-frame-options`.

References
* [The W3C Webapp Spec - 6.3.2.2. Relation to X-Frame-Options ](https://w3c.github.io/webappsec-csp/#frame-ancestors-and-frame-options)
* [Preventing Clickjacking OWASP](https://github.com/OWASP/CheatSheetSeries/blob/7d94e9a29174b8fd76235ca60f47245d1f34df1e/cheatsheets/Clickjacking_Defense_Cheat_Sheet.md)
* [X-Frame-Options Compatibility](https://caniuse.com/#search=X-Frame-Options)
* [Content Security Policy v2 Compatibility](https://caniuse.com/#feat=contentsecuritypolicy2)

## What would make this better?

Being able to configure both `x-frame-options` & CSP would present the most secure experience across all browsers

**Comment by thelangley** [comment]
This would be ace to prioritise. We're having issues with this as we use Chrome :(

**Comment by combor** [comment]
Apart from that, it's imposible to disable `x-frame-options`. We have a simple monitoring board for multiple concourse instances which is embeding them using iframes. This option made it broken as it doesn't help setting `x-frame-options` to sameorigin.

**Comment by jimconner** [comment]
+1 same issue here. We have a concourse screen as part of a monitoring display which is using iFrames to pull info from many sources. No config options for being able to set X-Frame-Options for anything  other than the default.

**Comment by pivotal-jamie-klassen** [comment]
The cluster that runs https://ci.concourse-ci.org actually has `--x-frame-options` unset via a BOSH ops-file: https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/x-frame-options-unset.yml, and you can see it working in an iframe at the bottom of https://concourse-ci.org/examples.html. If you're not using BOSH, you should be able to do it via a startup flag or even an environment variable. In fact, I just tried applying the following patch to https://github.com/concourse/concourse/blob/master/docker-compose.yml:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 400598ee0..feadbcfaa 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -29,6 +29,7 @@ services:
       CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
       CONCOURSE_MAIN_TEAM_LOCAL_USER: test
       CONCOURSE_CLUSTER_NAME: dev
+      CONCOURSE_X_FRAME_OPTIONS: ""

   worker:
     build: .
```
and then I get
```bash
$ curl -sv localhost:8080/ >/dev/null
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Xss-Protection: 1; mode=block
< Date: Thu, 18 Jul 2019 00:04:16 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
<
{ [10466 bytes data]
* Connection #0 to host localhost left intact
```
where there is no `X-Frame-Options` header. @combor @jimconner I'm feeling like our [docs](https://concourse-ci.org/concourse-web.html#web-ingress) on this topic must be lacking. Do you think you could suggest an improvement? Would it be enough to add another phrase mentioning that an empty string is how you unset it?

**Comment by thelangley** [comment]
Hey, @pivotal-jamie-klassen. yeah this is our issue too.

I'm going to give this ops file a whirl, I didn't see that one 👍
