### ISSUE TITLE
ci: delete test deployments after run (bosh)

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3514]
Hey,

Looking at the instances that we keep around after the execution of our tests, the number is quite big:

```
Deployment 'concourse-smoke'
1 instances

Deployment 'concourse-test-downgrade'
3 instances

Deployment 'concourse-test-downgrade-4-2-x'
3 instances

Deployment 'concourse-test-upgrade'
3 instances

Deployment 'concourse-test-upgrade-3-13-x'
3 instances

Deployment 'concourse-test-upgrade-4-2-x'
3 instances

Deployment 'concourse-topgun-credhub-test-1'
4 instances

Deployment 'concourse-wats'
3 instances

Deployment 'concourse-wats-3-13-x'
3 instances

Deployment 'concourse-wats-4-2-x'
3 instances
```

That sums up to 29 instances that could at least be not around during the night and weekends.

Is there a specific reason why we'd like to not delete them after the test runs otherwise?

Thanks!

**Comment by xtremerui** [comment]
We've talked about this in retro @clarafu and yes they should be cleaned up.

There is `cleanup` in bosh-deployment-resource that could be utilized. 
Also we might need to check related tests to make sure it cleans up resources in the `after` clause in each suit even the test failed or got interrupted.

**Comment by cirocosta** [comment]
Hey,

Looking at this with @pivotal-jwinters, we looked at the costa associated with them, and after our credits get applied, it really doesn't bring significant benefit to add the jobs to remove them (as such use is covered by the credits anyway).

I'll leave this out of `CI Pair` then, feel free to grab it though!

Thanks!
