### ISSUE TITLE
atc template failure

### ISSUE THREAD

**Issue by schabiyo** [concourse/concourse#352]
Hi,

i'm getting the error below when trying concourse Bosh release during a deployment. It is complaining about a method named **link** in atc_ctl.erb. I checked the source code and can't seem to find the definition of that method.

 command 'deploy' failed:
  Deploying:
    Building state for instance 'concourse/0':
      Rendering job templates for instance 'concourse/0':
        Rendering templates for job 'atc/e44603e71586baa24b0dcb0bf03d8e314d61c158':
          Rendering template src: atc_ctl.erb, dst: bin/atc_ctl:
            Rendering template src: /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/bosh-init-release882697360/extracted_jobs/atc/templates/atc_ctl.erb, dst: /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/rendered-jobs542159102/bin/atc_ctl:
              Running ruby to render templates:
                Running command: 'ruby /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/erb-renderer713795653/erb-render.rb /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/erb-renderer713795653/erb-context.json /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/bosh-init-release882697360/extracted_jobs/atc/templates/atc_ctl.erb /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/rendered-jobs542159102/bin/atc_ctl', stdout: '', stderr: '/Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/erb-renderer713795653/erb-render.rb:180:in `rescue in render': Error filling in template '/Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/bosh-init-release882697360/extracted_jobs/atc/templates/atc_ctl.erb' for atc/0 (line 35: #<NoMethodError: **undefined method link for** #<TemplateEvaluationContext:0x007fa67210a548>>) (RuntimeError)
	from /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/erb-renderer713795653/erb-render.rb:166:in `render'
	from /Users/sanichabiyo/.bosh_init/installations/c8a87237-fd11-46ab-60de-36eb3f732bd0/tmp/erb-renderer713795653/erb-render.rb:191:in `<main>' 

Thanks,

**Comment by joek** [comment]
@schabiyo Have you solved the issue? They are using quite new features of bosh. If he can not find the link method, you should try to update your bosh server to the latest version. 

Please make sure you upload the release again after you updated the bosh server... It took me about 3 hours to figure out that some information out of the upload process was missing in the database...

**Comment by vito** [comment]
Yeah this looks like you weren't on BOSH 2.0+
