### ISSUE TITLE
Support atomically switching pins

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3522]
Occasionally I want to swap from one pinned version to another. Right now I have to unpin the old version and pin a new one which doesn't feel as nice as if I could just click the new one. It also has a race condition since something could be scheduled in between clicks.

**Comment by vito** [comment]
As acceptance, I would like to run `pin-resource-version` twice and have the second run swap the pin.

**Comment by xtremerui** [comment]
@pivotal-jamie-klassen @vito just want to confirm that in this issue it will only change the API part so one can pin a resource with a version without unpin it first.

 Do we need to create an issue for the UI work?

**Comment by pivotal-jamie-klassen** [comment]
implemented by #4448 on the backend and #4561 on the frontend
