### ISSUE TITLE
Run Concourse on Cloud Foundry

### ISSUE THREAD

**Issue by mastertinner** [concourse/concourse#353]
Is it somehow possible to run Concourse as an app (either using the Go Buildpack or the Binary Buildpack) on Cloud Foundry? If yes, is there a tutorial or some instructions somewhere?

**Comment by jtarchie** [comment]
@mastertinner, it is not possible, right now.

There are two limitations of cloud foundry, which concourse would need:

1. Being able to run on multiple ports in the same app instance. When running `concourse web` it actually binds to two ports -- 2222 and 8080.
2. Having privileged access so garden, the containerization, can run its own containers.

As of right now, the best solution is either deploying with BOSH to a Cloud provider, or use the the concourse binaries on your own server.

**Comment by mastertinner** [comment]
thanks for the answer, @jtarchie!
