### ISSUE TITLE
Baggageclaim process hangs and causes unresponsive worker

### ISSUE THREAD

**Issue by burise** [concourse/concourse#3537]
## Bug Report

On one of our workers the baggageclaim process seems to be hanging (see error log below) and at the same time CPU and ephemeral disk usage are increasing until the worker gets unresponsive. After recreating the respective worker the same issue immediately appears on another one.

## Expected Results

Distributed load on all 7 workers.

## Actual Results

High CPU and ephemeral disk usage on one worker which as a result becomes unresponsive. All builds running on the worker fail either with "failed to create volume" or with timeouts.

## Additional Context

The observed high CPU is caused by the baggageclaim process (about 30%) and kswapd0 (about 30%). Ephemeral disk usage goes up to 90% and stays there for about an hour until the worker gets recreated automatically.
The baggageclaim.stderr.log of the problematic worker is full of such errors:

[...]
goroutine 1140281 [syscall, 301 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x139f7c, 0xc000373748, 0x1000004, 0x0, 0x0, 0x10, 0xc00079e850, 0x0)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc0007e2570, 0x4, 0xc0003738b0, 0xc0007e2570)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc0007e2570, 0xc000373888, 0x6e9f7d, 0xc00000e380)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(0xc0007e2570, 0x81e950, 0x81e958, 0x81e948)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/os/exec.go:125 +0x2b
os/exec.(*Cmd).Wait(0xc000a4e000, 0x0, 0x0)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/os/exec/exec.go:465 +0x5b
os/exec.(*Cmd).Run(0xc000a4e000, 0x81e8f8, 0xc00000e360)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/os/exec/exec.go:309 +0x5c
github.com/concourse/baggageclaim/volume.(*repository).streamIn(0xc000062580, 0x7f88f035f000, 0xc00092ef00, 0xc0005474a0, 0x54, 0x0, 0x0, 0x0, 0x0)
        /var/vcap/packages/baggageclaim/src/github.com/concourse/baggageclaim/volume/stream_in_out_linux.go:22 +0x158
github.com/concourse/baggageclaim/volume.(*repository).StreamIn(0xc000062580, 0xc0000f69ca, 0x24, 0xc0000f69f4, 0x1, 0x7f88f035f000, 0xc00092ef00, 0x0, 0xc0000f69c0, 0x35)
        /var/vcap/packages/baggageclaim/src/github.com/concourse/baggageclaim/volume/repository.go:396 +0x5d9
github.com/concourse/baggageclaim/api.(*VolumeServer).StreamIn(0xc0000625c0, 0x86e6c0, 0xc0002c7260, 0xc0005fd000)
        /var/vcap/packages/baggageclaim/src/github.com/concourse/baggageclaim/api/volume_server.go:455 +0x33e
github.com/concourse/baggageclaim/api.(*VolumeServer).StreamIn-fm(0x86e6c0, 0xc0002c7260, 0xc0005fd000)
        /var/vcap/packages/baggageclaim/src/github.com/concourse/baggageclaim/api/handler.go:35 +0x48
net/http.HandlerFunc.ServeHTTP(0xc000051620, 0x86e6c0, 0xc0002c7260, 0xc0005fd000)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/net/http/server.go:1964 +0x44
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc00000d200, 0x86e6c0, 0xc0002c7260, 0xc0005fd000)
        /var/vcap/packages/baggageclaim/src/github.com/bmizerany/pat/mux.go:117 +0x155
net/http.serverHandler.ServeHTTP(0xc000170000, 0x86e6c0, 0xc0002c7260, 0xc0005fd000)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0001a4960, 0x86ea80, 0xc00092ee80)
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /var/vcap/data/packages/golang/ffcee0f371a96b48caf061ecaacc00cc6619e9fa/src/net/http/server.go:2851 +0x2f5
[...]

## Version Info

* Concourse version: v4.2.1
* Deployment type (BOSH/Docker/binary): Bosh
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work? Yes

**Comment by cirocosta** [comment]
Hi @burise , would you mind sharing few other details?

1. what baggageclaim driver was it using?
2. was the worker running out of ram?

Also, if this ever happens again (or if it happend to a machine that didn't get recreated), would you mind seeing if there are any error messages under `dmesg`? 

Thanks!

**Comment by burise** [comment]
Hi @cirocosta , turns out this may be a bug in kswapd process. I will close this issue and open a new one if necessary.
