### ISSUE TITLE
version pinning breaks fly check-resource

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#3542]
## Bug Report

version pinning breaks `fly check-resource`

## Steps to Reproduce

Consider the pipeline

```
resources:
- name: booklit
  type: git
  source:
    uri: https://github.com/vito/booklit
    branch: master

jobs:
- name: unit
  plan:
  - get: booklit
    trigger: true
```

Let's set it

```
fly -t prod-developers set-pipeline -p pinning-bug -c pipeline.yml
```

The last 5 commits in repo https://github.com/vito/booklit at the time of writing are

```
> git log -5 --oneline
8efdca9 (HEAD -> master, origin/master, origin/HEAD) special-case / to render /index.html
3742983 switch to Go plugins, speed up server mode
6ab6216 write search index once, at the end
595a7df (tag: v0.7.0) add section Next/Prev
6bdccf3 tiny change for testing concourse stuff
```

Let assume that the git resource knows about the last 3 commits and that we pinned commit 3742983:

![pin-1](https://user-images.githubusercontent.com/3075069/54607458-b1a81d00-4a4e-11e9-8f12-e9f72338fb65.png)

The bug is the following:

If I ask the git resource to check for additional commits in the past, nothing happens, no error is reported and the exit code is 0:

```
> fly -t prod check-resource -r pinning-bug/booklit -f ref:6bdccf3
> echo $status
0
```

the list of commits know to the git resource stay as the previous image.

If on the other hand I unpin and then re-run the check resource command as above

```
fly -t prod check-resource -r pinning-bug/booklit -f ref:6bdccf3
```

then at this point the git resource is correctly updated with all the commits:

![pin-2](https://user-images.githubusercontent.com/3075069/54607480-ba98ee80-4a4e-11e9-8d69-ad4c2d8d2982.png)

## Expected Results

When the git resource is pinned and I execute fly `check-resource`, I expect one of the 2 behaviors:

1. The git resource is refreshed and collects the other commits, as if it was not pinned.
2. Maybe a pinned version is a sort of "locked" state; in this case, the git resource should stay with the same number of commits BUT `fly check-resource` should report an error (something like "pinned at version XXX; to check-resource, you must unpin first") and return a non-zero exit code.

## Actual Results

the git resource doesn't increase the number of commits known to it AND fly doesn't mention any error and the exit code is 0, leaving the user unable to understand if there was an error.

## Additional context

Related to #3541

## Version Info

* Concourse version: 5.0
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work? version pinning is new with 5.0

**Comment by vito** [comment]
Looks like we should special-case forced checks - this is probably the 'don't bother checking if it's pinned anyway' optimization getting in the way.

**Comment by vito** [comment]
@pivotal-jwinters Is this fixed by #3788? I'm thinking now that `check-resource` just chucks an entry onto the queue, it should just be the `scanner` which cares whether the resource is pinned, and the `checker` will just handle the queue entry regardless.

**Comment by pivotal-jwinters** [comment]
@vito yep, exactly as you described.

**Comment by vito** [comment]
Sweet! I'll close this as part of acceptance.
