### ISSUE TITLE
Not able to retire worker using tsa-team-authorized-keys only

### ISSUE THREAD

**Issue by gaelL** [concourse/concourse#3549]
## Bug Report

**Context :**

Tested against Concourse 4.2.3 and 5.0.0.

I have a mutualized Concourse server. I don't have any default workers, all my workers are assigned/forced to a team using `--tsa-team-authorized-keys=NAME:PATH`

Let's assume : `--tsa-team-authorized-keys=team1:/opt/team1_keys --tsa-team-authorized-keys=team2:/opt/team2_keys`
My `--tsa-authorized-keys` file is empty as I don't want users to be able to connect default workers for security reason.

Everything works correctly, worker in `/opt/team2_keys` are only able to register to `team2` using `--team team2` param

**Issue**

When I try to retire a worker using `concourse retire-worker --name ...` I get the following error message :

Concourse 5.0.0 error message
```
{"timestamp":"2019-03-19T10:47:00.091430284Z","level":"error","source":"retire-worker","message":"retire-worker.run.command-failed","data":{"command":"retire-worker","error":"Process exited with status 1","session":"2"}}
web_1     | {"timestamp":"2019-03-19T10:41:54.756671366Z","level":"error","source":"tsa","message":"tsa.connection.channel.exited-with-error","data":{"error":"key is authorized for team team2, but worker is global","remote":"172.18.0.4:43566","session":"18.1"}}
```

Concourse 4.2.3 error message
```
{"timestamp":"1552046632.086245775","source":"tsa","message":"tsa.connection.channel.retire-worker.worker-not-allowed","log_level":1,"data":{"authorized-team":"team2","remote":"...:44624","request-team":"","session":"24.1.1"}}
{"timestamp":"1552046632.086518288","source":"tsa","message":"tsa.connection.channel.retire-worker.failed-to-retire-worker","log_level":2,"data":{"error":"worker-not-allowed-to-team","remote":"...:44624","session":"24.1.1"}}
```

I think error from 4.2.3 give a good lead with `"authorized-team":"team2"` and `"request-team":""`

If I add my worker key into the global `--tsa-authorized-keys` file, I'm able to retire my worker. But as side effect, having my worker key into `--tsa-authorized-keys` allow it to register on unwanted team like `--team team1`.

## Steps to Reproduce

Using the Concourse v5.0.0 docker-compose, I updated web params to add `tsa-team-authorized-keys` as follow `--tsa-team-authorized-keys=team2:/concourse-keys/authorized_worker_keys_team2`
And made sure the worker key is not present in the `tsa-authorized-keys` file by replacing this line https://github.com/concourse/concourse/blob/master/Dockerfile#L24 by a simple `touch /concourse-keys/authorized_worker_keys`.

On the worker side, I added the env var `CONCOURSE_TEAM: team2` to make it part of the team when register.

So run `docker-compose up` and when the web is running, make sure to create this test2 team :

```
fly -t dev set-team -n team2 --local-user test
```

Concourse worker should be able to register itself to that team2 without any issues.

When the worker is registered, simply connect to it and try to retire it :

```
docker exec -it concourse_worker_1 bash
concourse retire-worker --name ...
```

it should fail with the log above.

## Expected Results

Be able to have ONLY dedicated team worker (`tsa-team-authorized-keys`). And be able to retire them.

## Actual Results

As described in the issue, I can't retire a worker, the worker stay in running state. And the retire-worker command produce an error message.

## Additional Context

I was able to patch it locally on my Concourse by adding a `--team` param on retire-worker command and adding it as param to worker instance here https://github.com/concourse/concourse/blob/master/worker/retire/retire_runner.go#L23-L25

Note : I had also some others issue patching it into Concourse 4.2.3 related to the generated token using `teamName` instead of `teams` in the JWT token : https://github.com/concourse/tsa/blob/master/token_generator.go#L38 but this issue seems to have been fixed into the 5.0.0 version.

## Version Info

* Concourse version: 5.0.0 and 4.2.3
* Deployment type (BOSH/Docker/binary): tried with binary and Docker using 5.0.0 docker compose

**Comment by gaelL** [comment]
Note : Looking on k8s charts for Concourse 5.0.0 : https://github.com/helm/charts/blob/907b57881b3a38d17b0665e2861778fc8640883e/stable/concourse/templates/worker-statefulset.yaml#L87

I tried as workaround to retire worker by using signal :

```
kill -s SIGUSR2 1
```
 and it worked. So this issue concern only the `concourse retire-worker` command

**Comment by vito** [comment]
fixed by https://github.com/concourse/concourse/pull/3929 - thanks!
