### ISSUE TITLE
Task file not found when running in AWS

### ISSUE THREAD

**Issue by jobpsdk** [concourse/concourse#355]
Using an AMI in AWS with the binary download of Concourse it seems the worker fails to find the task file even though the file is present in the sources it has checked out from GIT. The maven-package task reports "file not found: pipeline/maven-package.yml"

The example project is https://github.com/nitram509/concourse-java-maven-test-prj and works fine in vagrant.

I have added the packer scripts, as well as the concourse startup scripts for illustration.

[concourse.packer.txt](https://github.com/concourse/concourse/files/207021/concourse.packer.txt)
[setup.sh.txt](https://github.com/concourse/concourse/files/207022/setup.sh.txt)
[concourse.sh.txt](https://github.com/concourse/concourse/files/207023/concourse.sh.txt)
[concourse-worker.sh.txt](https://github.com/concourse/concourse/files/207026/concourse-worker.sh.txt)

**Comment by vito** [comment]
Sorry for the delay. I don't think anything went wrong in Concourse here since that's a pretty common flow. But it's been a while and I'm not sure if you've figured it out by now. Gonna close to clean this up, but feel free to reply if you're still stuck!
