### ISSUE TITLE
Retry fetch of value from credential management.

### ISSUE THREAD

**Issue by designed4device** [concourse/concourse#3557]
## What challenge are you facing?

Jobs and resource checks will fail due to failing to fetch a value from credential management because of intermittent network issues.
```
Finding variable '.credential-key': Get https://example.com:8080/v1/secret/team: dial tcp 10.100.100.101:8080: connect: connection refused
``` 
## What would make this better?

Adding a retry to the credential fetch would help mitigate this issue.

**Comment by vito** [comment]
This was added in 5.0: https://concourse-ci.org/download.html#v500-note-15
