### ISSUE TITLE
Calls to APIs with invalid or expired tokens can return empty 200s rather than 401

### ISSUE THREAD

**Issue by jkschneider** [concourse/concourse#3558]
For example, `/api/v1/pipelines`.

@vito explained that Concourse views these calls as *this is what you have access to given your status* and in that case not being logged in is not an error condition and suggested prefacing calls to resources like this with a call to `/sky/userinfo` to check the login status.

Unfortunately, we can't make calls to `/sky/userinfo` atomically with the follow on request so I  can never be sure if my token is expired when making a resource request or if the resource is truly empty.

I'd expect that a call to `/api/v1/pipelines` with an invalid/expired token returns 401.

**Comment by vito** [comment]
Endpoints like `/api/v1/pipelines` can still return pipelines if you're not logged in, but it seems worth making a distinction between 'no token at all' and 'you've got a token but it's invalid/expired'.

@pivotal-jwinters Would it be reasonable to just have the API outright reject requests with invalid/expired tokens with a 401?

**Comment by pivotal-jwinters** [comment]
@vito yeah makes sense
