### ISSUE TITLE
[ui] pipeline groups overlap if the browser windows isn't wide enough

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [concourse/concourse#3561]
## Bug Report

If a pipeline has many groups and the browser window is narrow enough to force wraparound, the second row of groups overlaps the first.

## Steps to Reproduce

1) Create a pipeline with many groups
2) Make the browser window narrow

## Expected Results

2 neat non-overlapping rows of groups

## Actual Results

rows overlap, reducing legibility

## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome

**Comment by xtreme-conor-nosal** [comment]
![Screen Shot 2019-03-21 at 9 32 06 AM](https://user-images.githubusercontent.com/1062633/54755734-fc47a780-4bbc-11e9-82c4-2fe14668ecde.png)

**Comment by cirocosta** [comment]
Here's another example:

<img width="1440" alt="Screen Shot 2019-04-04 at 4 57 32 PM" src="https://user-images.githubusercontent.com/3574444/55588031-c21cf080-56fa-11e9-92f5-8e77368d1745.png">

(that's on 5.0.1)
