### ISSUE TITLE
Make use of proper points batching in metric emissions

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3570]
Hey,

Right now, the metrics emission channel is fixed at 1000:

https://github.com/concourse/concourse/blob/c2eadab7603d670f5c3aa2d11f3636660440ea75/atc/metric/emit.go#L100

In installations like Wings where we produce a lot of data in the form of metrics, this queue gets full all the time as the rate of new metrics datapoints seem to be much higher than the rate at which we send them.

This results in a bunch of error logs due to the channel being full:

https://github.com/concourse/concourse/blob/c2eadab7603d670f5c3aa2d11f3636660440ea75/atc/metric/emit.go#L133-L137

To remediate that we could improve our rate of emissions by properly batching the points. For instance:

https://github.com/concourse/concourse/blob/c2eadab7603d670f5c3aa2d11f3636660440ea75/atc/metric/emitter/influxdb.go#L55-L57

is creating a batch with a single event.

Thanks!

**Comment by vito** [comment]
There's a fork that fixes this - see https://github.com/concourse/concourse/issues/3674#issuecomment-491225375. I've pinged them about submitting a PR. :slightly_smiling_face:
