### ISSUE TITLE
Autoscale worker

### ISSUE THREAD

**Issue by qoomon** [concourse/concourse#3578]
Please implement something like autoscaling runners from gitlab https://docs.gitlab.com/runner/configuration/autoscale.html
I would like to be able to ramp up a dedicated EC2 instance for each task and than kill the instance.
This is needed cause of potential docker in docker security issues. And for  speed up pipeline runtime for parallel tasks.

Than concourse would be production ready and we will switch over

**Comment by vito** [comment]
Concourse doesn't do any provisioning and doesn't integrate with any existing provisioners, so this feels like a lot to ask of Concourse itself. It seems like it would be better to rely on your own infrastructure and ops tooling to determine when to auto-scale and create new workers.

The existing Concourse APIs for dynamic worker registration and draining should already support this to some extent. Is there something more that you need?

**Comment by qoomon** [comment]
docker machine does provisioning already, maybe this can be utilized

**Comment by marco-m** [comment]
@qoomon In addition to what vito mentions, remember that Concourse is not only Linux and containers. It is also Windows and Mac and anything else.

**Comment by qoomon** [comment]
Ah didn't know that. However that's a bummer. The scalability is the only thing that is holding us back to move to concourse.

**Comment by marco-m** [comment]
FYI, you can already autoscale actually. Granted, you have to do some work yourself, but you can. In my team we autoscale with AWS ASG (so at the worker VM level), using the `ASGAverageCPUUtilization` dynamic target tracking. (this is not the right place to discuss about this, you might want to post on https://discuss.concourse-ci.org/ instead).

**Comment by qoomon** [comment]
Ok, On last comment from my side.
I'm aware of the aws asg solution, however I have security concerns with that cause an instance is reused for multiple pipelines, and because we need to run docker containers within docker containers the build container can get root access through the mounted docker socket. Thats the reason why it would be great if works could be configured in a way to only run one step and then shout down again.
Cya at https://discuss.concourse-ci.org/

**Comment by vito** [comment]
Closing as it sounds like this'll continue in the forums. :slightly_smiling_face:
