### ISSUE TITLE
Rename last checked and last check finished

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#3587]
Maybe to make the purpose of these columns clearer, we can rename them from `last_checked` and `last_check_finished` to `last_check_start_time` and `last_check_end_time`.

**Comment by vito** [comment]
Sounds good, I'll put this in 5.1.0.

**Comment by xtremerui** [comment]
After go through the schemas I think there are some more cleanup could be done. Here is a full list.

[ ] remove `cache_invalidator` table. It has only one column `last_invalidated` as timestamp, which is not used anywhere in our code.
[ ] rename `last_scheduled` in `pipelines` table to `last_scheduled_time` or `last_scheduled_at`(given there are some places we use `created_at` for timestamp)
[ ] rename `last_checked ` to `last_check_start_time`
[ ] rename `last_check_finished ` to `last_check_end_time`

**Comment by vito** [comment]
Let's have the API report end time, not start time.
