### ISSUE TITLE
please add a "MOVED" notice into github.com/concourse/fly

### ISSUE THREAD

**Issue by lrstanley** [concourse/concourse#3589]
https://github.com/concourse/fly is now archived, and the code for fly now lives in this repository. However, it's very unclear that it's deprecated in favor of `concourse/concourse/fly`. Took me like 15 minutes to figure out what was going on...

Can someone unarchive, add a banner to the top of the README and in the title line thing where it says "Concourse CLI for interacting with the ATC API" that this repo is the new location, and re-archive?

**Comment by vito** [comment]
:+1: fair - I'll try to get to this soon, it's a bit of a pain 'cause there are so many repos but I'll do it when I have time.

**Comment by vito** [comment]
Taking a look at this now - I'm thinking I'll also remove all the code from the repos to make it even more obvious that everything has moved. This way anyone depending on `master` will notice the breakage so they know to point at the new repo. They can always just pin to the prior commit if they don't want to migrate immediately.

(I don't actually expect this to affect anyone though.)

**Comment by vito** [comment]
All done!
