### ISSUE TITLE
Panics in pipeline/build scheduling should not bring down the whole Concourse

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3594]
Go's `net/http` is careful to recover panics in HTTP handlers and log them instead of crashing the whole server. Can we do the same for general pipeline scheduling and build tracking and anything else that's affected by user data?

One example of a panic: https://github.com/concourse/concourse/issues/3582

**Comment by vito** [comment]
Note: we should definitely not use this to just paper over errors - we should make them very easy for operators to notice. `net/http` does this by logging them to `stderr` instead of `stdout` for example, so maybe we could do that too?

In the linked example, users would have been able to notice this because the build would never finish. They probably would have thought to open a bug, and at least would be able to abort the build to prevent it from hanging the whole pipeline.

**Comment by marco-m** [comment]
I suggest to be careful before embarking along this path, which can be a slippery slope. The example in `net/http` is for user-supplied handlers, while here we are talking about Concourse core itself. Coming from Erlang "crash early" philosophy, I prefer Concourse crashing (I can set up an alarm on high restart frequency) than having no alarms due to a Concourse without one leg that uses a crutch to stand :-)

**Comment by vito** [comment]
@marco-m Erlang's "crash early" are typically limited in scope - they don't bring down the *entire* Erlang VM and require a full system-level process restart, right?

As an operator I would rather set up alerts for panics like this than worry about a bug that allows users to submit pipelines that DOS my untrusted-multitenant Concourse instance.

**Comment by marco-m** [comment]
@vito an Erlang crash begins indeed very limited, the granularity is the same as of a goroutine. Each Erlang "process" is inserted in a supervisor tree, which is what makes Erlang crash early powerful and effective. The crash begins at a leaf of the tree and, if the limited restart doesn't solve the problem, can bubble up the tree until it reaches the Erlang VM. Actually it can even go outside the Erlang VM and reboot the host :-)

You know better than me Concourse ;-), I am only suggesting to be careful.

**Comment by vito** [comment]
@marco-m Agreed - we'll try to be conservative with this, I definitely don't want to sprinkle `recover()` everywhere and call it a day. :+1:

**Comment by vito** [comment]
Adding this to 6.0 since I'm on mobile and can't add it to a project instead. Hopefully we get to it by then!

**Comment by vito** [comment]
If we can do this with minimal invasive changes, we should go ahead and do it, but if we have to add `defer` every little place it's probably not worth it vs. just tackling the `panic` reports we see through GitHub issues and trying to cover these situations in tests.

**Comment by vito** [comment]
...eh, after having been on a call with a customer who's entire cluster was in a crash loop because of one errant build, I think this is worth reconsidering.

It might feel like a wack-a-mole problem, but at the end of the day there's a finite number of steps to audit and a finite number of goroutines to keep in check.
