### ISSUE TITLE
Concourse workers fail to retire and remain in retiring state

### ISSUE THREAD

**Issue by phyllisnoester** [concourse/concourse#3597]
## Bug Report

The worker fails to retire and remains in retiring state until manually pruned. 

## Steps to Reproduce

Retiring worker through executing the following bash script:

`while ! concourse retire-worker | grep -q worker-not-found; do
    sleep 5
done`

## Expected Results

worker retires

## Actual Results

Worker goes into retiring state but does not retire, the number of containers on the worker remains unchanged. After the worker remained in retiring state for 12+ hours we pruned it.

## Additional Context

We set up Concourse using AWS EC2 instances for workers and web. The workers use a load balancer to communicate to the web. Both workers and web instances are set up using systemd. The bash script mentioned above is run by a systemd timer that retires workers after a fixed amount of time. This is due to an issue we encountered where the maximum number of memory Cgroups was reached on a worker after some time. 

## Version Info

* Concourse version: v3.14.1

**Comment by vito** [comment]
We can't really do a whole lot with this without steps to reproduce that actually reproduce it - not just the command that was run that showed the symptoms. :thinking:
