### ISSUE TITLE
Paused jobs show as running in the dashboard view when a new build is pending

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#3599]
## Bug Report

When I have a pending build on a job that's paused, the job shows in the dashboard as running, even though it's actually paused and that build won't start until it becomes unpaused.

## Version Info

* Concourse version: 5.0.1 (on Wings)
* Browser (if applicable): Chrome
* Did this used to work? Unknown

**Comment by pivotal-jamie-klassen** [comment]
I believe this is a duplicate of #2323

**Comment by andrewedstrom** [comment]
I think so too
