### ISSUE TITLE
Where/when is build-gate.yml task run?

### ISSUE THREAD

**Issue by drnic** [concourse/concourse#36]
Starting to review how concourse is built up/run. I see `ci/build-gate.yml` calls to `ci/scripts/build-gate.sh` but `ci/build-gate.yml` doesn't seem to be mentioned in either pipeline. When is it run?

**Comment by vito** [comment]
Never; we should clean that up. Gate is a component that is no longer part of the release (it used to be what registered workers with the ATC).
