### ISSUE TITLE
Update missing flags in Chart PR

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3603]
Hey,

We've been having `k8s-check-helm-params` blocking our test for a while.

Keeping that task running smoothly is important as it ensures that we're always in sync with the changes that happen in `master`, which get used in the image that gets used by the chart, thus needing those changes.

At the moment, these are the flags needed:

```
CONCOURSE_CONTAINER_SWEEPER_MAX_IN_FLIGHT
CONCOURSE_VAULT_SHARED_PATH
CONCOURSE_VOLUME_SWEEPER_MAX_IN_FLIGHT
```

(https://github.com/helm/charts/pull/12436)

Thanks!

**Comment by YoussB** [comment]
The missing params have been added as Apr 3, 2019 and the [build passes](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-check-helm-params/builds/1225) 😁
