### ISSUE TITLE
Document Resource Caching

### ISSUE THREAD

**Issue by gscho** [concourse/concourse#3605]
## What challenge are you facing?

We are building an image (ami) with a concourse worker pre-installed so that we can spin up an ephemeral worker for each build. We would like to build an image with resources already downloaded so the worker does not need to download several containers to run a job. The challenge here is it's unclear how the docker images get downloaded and used on the worker which is making this task difficult.

## What would make this better?

Maybe some documentation around the way concourse workers download, cache and use resources.

## Are you interested in implementing this yourself?

Should be done by someone with intimate knowledge of how this works.

**Comment by xtremerui** [comment]
There is a blog post might help https://medium.com/concourse-ci/concourse-resource-volume-caching-7f4eb73be1a6
