### ISSUE TITLE
Re-attempt task only on Concourse error

### ISSUE THREAD

**Issue by glend** [concourse/concourse#3606]
## What challenge are you facing?

I'm using Concourse with GCP preemptive nodes. When one of the workers disappears, the jobs result in a failure. I tried making use of `attempts:` but it was also retrying jobs on valid build failure, which isn't desirable especially when it's a heavy job/build.

## What would make this better?

Need a way to specify which kind of failure can trigger attempts.

Something like:

```
attempts:
  amount: 3
  on: worker_failure
```

**Comment by marco-m** [comment]
This is a dup of #2581 and #755.

**Comment by vito** [comment]
@marco-m agreed - thx!
