### ISSUE TITLE
Deep Link to Logs

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#361]
As happy users of Concourse, we regularly experience failures in our tasks that we'd like to communicate to other team members.  Currently, if we want to reference a specific part of the build output, we're reduced to describing it verbally (or writing it out longhand).  It'd be useful to be able to deep link to specific lines in the output like you can in GitHub source listings.

**Comment by vito** [comment]
Noticed one issue with the implementation so far: when the build logs word-wrap, they're no longer aligned with the timestamps.

**Comment by vito** [comment]
Woops, accidentally broke the behavior for old builds:

https://ci.concourse.ci/teams/main/pipelines/main/jobs/bosh-wats/builds/205

Turns out the impossible is possible. Fix is easy.
