### ISSUE TITLE
Can not resolve non-FQDN domain names inside K8s cluster.

### ISSUE THREAD

**Issue by emempi** [concourse/concourse#3610]
## Bug Report

After upgrading concourse from 4.2.2 to 5.0.1, our containers don't seem to be able to resolve non-FQDN local kubernetes names.

## Steps to Reproduce

1. Launch any pipeline task 
2. Hijack the container
  (assuming `concourse` is deployed to namespace `default` using concourse helm chart)
3. `ping concourse-web.default` doesn't work
4. `ping concourse-web.default.svc.cluster.local` does work
5. (additionally) /etc/resolv.conf in the containers contains a single line pointing to current pod's IP address

## Expected Results

Both ping commands should behave the same way, as configured by worker's pod's /etc/resolv.conf

## Actual Results

Since the task's container contains a resolv.conf that doesn't correspond to the workers, there's a search stanza missing and resolving of non-FQDN names of kubernetes objects is not possible.

## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): kubernetes/docker
* Infrastructure/IaaS: GKE
* Browser (if applicable):
* Did this used to work? Yes, the same pipeline worked fine with concourse 4.2.2 .

**Comment by emempi** [comment]
I was able to work around this by explicitly disabling the worker dns proxy.

**Comment by cirocosta** [comment]
Hi @emempi , thanks for sharing your experience! I'm glad to know you found a way around it!

We have a story for putting such behavior into a test that we can then verify that we're not introducing new breaks in terms of such "contract" with whoever is consuming the chart: https://github.com/concourse/concourse/issues/3103 - it contains a brief description of what that proxy is doing.

Once the team gets to that one, the person working on it can come back to this one then 👍 

Thanks!

**Comment by cirocosta** [comment]
Hi @emempi ,

We just finished adding some testing around the behavior of DNS resolution - here's a breakdown of it:

https://github.com/concourse/concourse/blob/3504ac7584165ae7c036734e82ceb6a708f67794/topgun/k8s/dns_proxy_test.go#L86-L117

I'll consider this closed for now, please let me know if you have any further questions / concerns about it 😁  

Thanks!
