### ISSUE TITLE
Resources should support a 'delete' action

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#362]
## Use Case

I'm working on a [terraform resource](https://github.com/ljfranklin/terraform-resource) which includes an option to run terraform destroy via a 'put':

```
- put: terraform
  params:
    action: destroy
```

This action destroys the infrastructure, removes the state file from S3, and returns the current timestamp as the `version`. Prior to the destroy step the `version` is the last modified time of the state file.

## Issue

The `put` action is followed by an [implicit `get`](http://concourse.ci/put-step.html). In the normal case, a `get` would return an error if that state file could not be found. However, the implicit `get` should no-op after a `put` destroys the state file. My current workaround is to use `get_params` to tell `get` to no-op:

 ```
- put: terraform
  params:
    action: destroy
  get_params:
    action: destroy
```

This works, but requiring the user to specify a duplicate `get_params` action is confusing / error-prone. I think this problem would also apply to other resources that could destroy things like the CloudFormation and bosh-deployment resources.

## Updated Suggestion from @vito and @robdimsdale 

Supporting a `delete` resource option in addition to `get` and `put` clearly describes the intent of the action and avoids hacky patterns around destructive `put` operations.

## Original Suggestion

One possible fix could be allowing  resource authors to disable the implicit `get` following a destructive `put` via a new `out` field:

```
{
  "version": { "last_modified": "2016-04-09T19:20:47Z" },
  "metadata": [],
  "disable_implicit_get": true
}
```

Thanks!

**Comment by robdimsdale** [comment]
There are multiple resource that need to solve this problem. I think the right way to solve this it is for concourse to support `delete` as a resource operation, similar to `get` and `put`.

That would map more obviously to the underlying operation, rather than relying on esoteric params in the `put` that likely would differ between resources.

**Comment by vito** [comment]
:+1: to @robdimsdale - this feels more appropriate with a `delete` action. I don't like the idea of resources saying to not perform a `get` after a `put`. If you've produced something (the intent of `put`) you should be able to fetch it. Sometimes that means doing a no-op.

**Comment by robdimsdale** [comment]
@vito is a `delete` on the radar? Any stories to keep an eye on?

**Comment by vito** [comment]
kinda: https://www.pivotaltracker.com/story/show/91815814

**Comment by ljfranklin** [comment]
:+1: to you both. A first-class `delete` option would be ideal, I re-worded the issue to reflect this.

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/362

**Comment by oppegard** [comment]
@vito Now that this issue is closed, where is the feature being tracked so I can follow along?

**Comment by vito** [comment]
https://github.com/concourse/concourse/issues/534 - messed up my link
