### ISSUE TITLE
remove `Debug.todo`s and build elm code with `elm make --optimize`

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3622]
We use `Debug.crash` (which we are forced to replace with `Debug.todo` in 0.19) in several places. This prevents us from using the excellent [--optimize](https://elm-lang.org/0.19.0/optimize) flag for the time being.

**Comment by pivotal-jamie-klassen** [comment]
In #3641 we removed all the `Debug.todo`s so one that is merged we can start on this

**Comment by pivotal-jamie-klassen** [comment]
We also need to remove the `Debug.toString`s

**Comment by stigtermichiel** [comment]
Any reason we are not making use of the uglifyjs optimizations proposed by elm here: https://elm-lang.org/0.19.0/optimize ?

I've tried using: 
`uglifyjs elm.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=elm.min.js`
locally and it got elm.min.js to below 200k.

**Comment by vito** [comment]
@stigtermichiel I don't think there's any reason, feel free to open a PR!
