### ISSUE TITLE
Solution a better way to view large build logs

### ISSUE THREAD

**Issue by jduv** [concourse/concourse#3624]
## What challenge are you facing?

Basically this:

<img width="851" alt="Screen Shot 2019-03-28 at 4 47 13 PM" src="https://user-images.githubusercontent.com/591405/55191717-490d1e80-5179-11e9-91e6-cf70ba9eb762.png">

We have a job that periodically pings a server to see if it's up. Wonderful thing, it is. After a couple of weeks this job approaches 11's of thousands of hits. Previously we were retaining all build logs, but that brought down our entire concourse cluster. So, we only retain 10 build logs--but the concourse UI allows us to click back to logs that no longer exist.

## What would make this better?

I imagine even if you retain build logs it will become difficult to view large build histories over time. To be honest I don't know that I actually *care* about retaining histories past a certain point because I'm never going to dig back to three years ago to find out what my build server did. From a long term sustainability perspective there should be some way to either forget entirely or paginate sufficiently large builds so that my poor web UI doesn't choke when rendering 11000 divs with a build number on it.

## Are you interested in implementing this yourself?

Sure. My team uses concourse extensively (we are 11 thinking doing humans). We'd need to understand the final solution though, because we are not UX nor do we want to be UX. I just know that it's a pain to use, don't ask me how to fix it :D.

**Comment by marco-m** [comment]
I understand the problem about the performance getting worse and worse and I agree it is real.

Now, for your particular use case (pinging a server to see if it is up) I would argue that a better approach is to use Prometheus, blackbox exporter and Prometheus AlertManager. You can configure the AlertManager to send you notifications on multiple channels.

**Comment by jduv** [comment]
@marco-m Sure, I can use a myriad of other tools to solve the use case above. Ignore that please and let's focus on the problem of displaying build logs 😄.

**Comment by vito** [comment]
This should already be fixed by https://github.com/concourse/concourse/pull/3446 - the build history loads lazily as you scroll.
