### ISSUE TITLE
Install helm deployed Concourse on PKS

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#3642]
**Summary**

As part of our effort to offer a helm-deployed Concourse instance, we'd like to see how the chart interacts on PKS. This will give us empathy with our customer's use case as many will be deploying Concourse on top of PKS. 

**Estimated Steps**

- Deploy PKS
  - We'll want to discuss this with Toolsmiths
- Install helm deployed Concourse on top of PKS
- Run metrics

**Acceptance Criteria**
- [ ] All steps are documented as markdown within the issue
- [ ] Any issues or limitations are opened as new issues

**Comment by scottietremendous** [comment]
@cirocosta - Anything to add?

**Comment by cirocosta** [comment]
Hey @scottietremendous ,

I'll actually close this one for now until we see the need of having a long-running deployment of Concourse (like `hush-house`) on PKS.

So far, with https://github.com/concourse/concourse/issues/4097 we're able to validate most of what we need, so I'll close this for now.

Thanks!
