### ISSUE TITLE
Investigate Logs on PKS

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#3644]
**Summary**

See issue #2642

As part of our investigation with PKS, we'd like to investigate logging. What can we use for logs on PKS. What would we need to change from our current logging setup. 

**Acceptance Criteria**

- [ ] Document Findings

**Comment by cirocosta** [comment]
Hey,

As the same rationale for https://github.com/concourse/concourse/issues/3642 applies (running the Topgun tests being enough for now), I'll close this one (we can reopen it if we see the need of having a long-running Concourse instance on PKS).

Thanks!
