### ISSUE TITLE
Resource page: way to tell who pinned and when

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#3650]
## What challenge are you facing?

The Concourse team, like many teams practicing continuous integration, sometimes has flaky builds. When a build fails due to flakiness, we have been using the pinning feature to re-trigger it with the same inputs. When somebody does this, it's usually done in a hurry and they often don't stick around to wait for the build to schedule and then un-pin. However, it's hard to be sure, and you we don't want to accidentally un-pin when we shouldn't.

## What would make this better?

It would be very helpful if the pin action automatically added a comment containing the pinning user's username and the time they pinned, so that teammates who wish to modify the same resource know who to ask about the pin. This feels fairly MVP and non-invasive.

Immediately upon pinning, I'd expect to see a screen like
![Screen Shot 2019-04-01 at 9 54 53 AM](https://user-images.githubusercontent.com/22056320/55332925-486bd500-5464-11e9-8b86-a3acc3945fc8.png)
(showing ISO 8601 timestamp with user's local time zone)

## Are you interested in implementing this yourself?
👍

**Comment by vito** [comment]
In the long run it probably makes sense to track this info in the database and show it in the UI, but in the meantime this sounds like a nice incremental step. :+1:
