### ISSUE TITLE
High Density View Does Not Scroll on Concourse 5.0.1

### ISSUE THREAD

**Issue by lockan** [concourse/concourse#3661]
## Bug Report

Cannot scroll High Density view to see large numbers of pipelines on Concourse 5.0.1

## Steps to Reproduce

1) Create a large number of pipelines. For example, our organization has 132 pipelines split across 13 teams. 
2) Log in to Concourse Web UI as a user that has visibility across all pipelines
3) Toggle High-Density view
4) Note that no scroll bars are present and user, user is unable to scroll to see all pipelines. 

## Expected Results

Able to scroll the high-density view, either horizontally or vertically, to see all pipelines

## Actual Results

Concourse 5.0.1 gives a fixed screen with no scrollbars. Only a limited number of pipelines are viewable, and the full list appears to extend beyond the viewable screen space. 

## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: AWS 
* Browser (if applicable): Tested on Chrome, Safari, Firefox
* Did this used to work? : Yes, this worked fine for us in 4.2.1.

**Comment by pivotal-jamie-klassen** [comment]
This is fixed in #3515 so you don't see this problem in the latest RCs, but that change is not in 5.0.1. @vito I'm thinking the plan is to recommend upgrading once 5.1 ships, rather than patching 5.0? I don't want to close this prematurely in case I'm wrong.

**Comment by vito** [comment]
@pivotal-jamie-klassen yep
