### ISSUE TITLE
Groups are not working

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#3662]
## Bug Report

Groups are not working in the pipeline view.

## Steps to Reproduce

1. Go to https://ci.concourse-ci.org/teams/main/pipelines/concourse
1. Click on any of the groups

## Expected Results

The pipeline view updates to the selected group.

## Actual Results

The pipeline view is not updated, but the URL is (e.g. .../?groups=bosh)

* Concourse version: v5.1.0 dev
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? yes

**Comment by pivotal-jamie-klassen** [comment]
Yep, regressed when switching URL parsing libraries during the 0.19 upgrade -- mixed up the URL parameter (`group` vs `groups`). I encountered this and it's actually fixed in #3653.
