### ISSUE TITLE
error aborting build

### ISSUE THREAD

**Issue by robwhitby** [concourse/concourse#3676]
## Bug Report

aborting a running build does not work for some pipelines/jobs. 

## Steps to Reproduce

click the abort button while a build is running

## Expected Results

the build should be aborted

## Actual Results

Build is not aborted. API request to `/api/v1/builds/<id>/abort` returns `500`

Example log error:
```
{
   build:  479084    
   error:  "pq: payload string too long"    
   session:  "603475"    
  }
  level:  "error"   
  message:  "atc.abort.failed-to-abort-build"   
  source:  "atc"   
  timestamp:  "2019-04-03T13:11:22.626108169Z"   
 }
```

I tried to investigate, and believe it may be due to an 8000 char limit in postgres notification events. But I don't know anything about how they work or Concourse uses them.

Perhaps it is related to the length of the pipeline name and/or job name?

## Version Info

* Concourse version: 4.2.3 and 5.0.1

**Comment by vito** [comment]
...Huh. How long was your pipeline name? There shouldn't even be a payload for these notifications so the only value should be the name. And I think those are relatively short (only containing build ID).

/cc @pivotal-jwinters while notification stuff is fresh in our minds.

**Comment by pivotal-jwinters** [comment]
I tested this out and it looks like postgres will actually truncate the channel name if its too long (and still send the message).

```
NOTICE:  identifier "chaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanel" will be truncated to "chaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
NOTIFY
```

**Comment by robwhitby** [comment]
> I tested this out and it looks like postgres will actually truncate the channel name if its too long (and still send the message).

sorry I don't understand the implications of that.

I've tried some variations and the length of the pipeline name is not important. I *think* it has more to do with the plan, because the abort succeeds if done quickly while still in the `preparing build` stage, but then fails once running a task. I'll try to narrow it down further.

**Comment by pivotal-jwinters** [comment]
@robwhitby This was in response to [this comment](https://github.com/concourse/concourse/issues/3676#issuecomment-479516932). 

As @vito mentioned we don't send a payload with the NOTIFY. So I wanted to test if a really long channel name would produce the same error. It doesn't, it simply truncates the channel name.

**Comment by robwhitby** [comment]
we now discovered this error was caused by our own code, so I'll close the issue :(
