### ISSUE TITLE
Last pipeline not visible at the bottom of pipelines

### ISSUE THREAD

**Issue by sks** [concourse/concourse#368]
PFA the screenshot:

![screen shot 2016-04-12 at 2 02 41 pm](https://cloud.githubusercontent.com/assets/570239/14475562/75c81a4e-00b7-11e6-8947-689555203ace.png)

There is one more pipeline to the end of the list, which is not visible on UI,

Setting the height of ` .pipelinesNav-enabled .pipelines  ` to ` 95% ` seems to show it

**Comment by vito** [comment]
This should be fixed already; see https://github.com/concourse/atc/issues/70
