### ISSUE TITLE
Specify alternative container network segment/subnet

### ISSUE THREAD

**Issue by dingxiangfei2009** [concourse/concourse#3686]
> Please remove all lines starting with '>' before submitting!
>
> CI systems have a ton of users, so naturally they'll get a ton of feature
> requests. We don't want to just implement all of them, because we want
> Concourse to stay simple.
>
> We use feature requests to capture use cases that Concourse could support
> better. This means the *context* for a request is often more important than
> the suggested feature.
>
> We try to target use cases that we understand the most, and make changes that
> have the widest possible impact so that we satisfy many use cases at once.
> This also means it can take a long time for a feature request to be
> satisfied. To speed this up, check out `CONTRIBUTING.md`:
>
>     https://github.com/concourse/concourse/blob/master/.github/CONTRIBUTING.md

## What challenge are you facing?

We would like to specify alternative network segment/subnet of the container network, because it might accidentally capture critical service that is in the currently default network subnet `169.254.0.0/16`.

For instance, Google Compute Metadata API server is located at `169.254.169.254` and it serves DNS, OS Login, metadata and many other critical services. Even if one can add a static route to this IP address on the Internet-facing interface, it does not prevent `concourse`/`garden-runc` from assigning this address to a container network interface.

> Without jumping to a solution, describe the problem you're facing, and
> provide context. It helps us more to understand your problem first. This way
> we may be able to connect the dots between your issue and others and perhaps
> come up with a more general proposal, rather than tacking on feature after
> feature.

## What would make this better?

> If you've got a suggestion, feel free to place it here! It also helps to
> describe how you arrived at this idea and why it'd work well for you.

## Are you interested in implementing this yourself?

> Let us know! We're happy to help you put together and iterate on a pull
> request.

**Comment by vito** [comment]
This can be specified as `CONCOURSE_GARDEN_NETWORK_POOL`:

https://github.com/cloudfoundry/guardian/blob/master/guardiancmd/command.go#L136

**Comment by dingxiangfei2009** [comment]
This is due to `dhcpcd`, or other ZeroConf service assigning the link-local address to these interfaces, since no DHCP server will ever run on them.
