### ISSUE TITLE
Enhancement: Build tags or labels

### ISSUE THREAD

**Issue by markstgodard** [concourse/concourse#369]
There are cases where it would be nice to be able to "tag" (not version control tag) with a label so that you could provide additional information. 

For example, a common case is flakey builds (not due to Concourse of course :) 
But it would be nice to "tag" a build.. similar to a label in Pivotal Tracker.
Then this could be searched to find all builds that contain a specific tag  (vs. sifting thru builds and looking for specific content).

Another example was that recently we were doing load testing and we did runs with different config and changes, etc...  Yes we could look at git SHAs, etc.  but sometimes it would be nice to tag the build so it would be easier to eyeball.. oh, that was the build with foo enabled, etc.

Anyway, it could be any tag value and would just be used for additional information added from the UI.

TeamCity for example has Build Tags and Comments....  however I am thinking more like Pivotal Tracker type labels in Concourse Builds.

Cheers

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/369 - sounds like the same thing
