### ISSUE TITLE
Fly and split DNS no longer working

### ISSUE THREAD

**Issue by dkuntz2** [concourse/concourse#3691]
## Bug Report

Upgrading from Concourse/Fly 4.2.3 to 5.0.1 has introduced an issue where fly is no longer able to access our concourse instance, which is behind a VPN using split DNS.

Because of some of our security requirements, we can't forward all DNS traffic through the VPN, and we would rather not add a private IP to a public DNS entry.

## Steps to Reproduce

1. Run concourse in a private network
2. Run OpenVPN Access Server to allow connections into the private network
3. Attempt to use any `fly` command, specifically `fly -t target login`

## Expected Results

`login successful`

## Actual Results

```
could not reach the Concourse server called target:

Get https://concourse.internal-address/api/v1/info: dial tcp: lookup concourse.journera.net on <public dns ip>:53: no such host

is the targeted Concourse running? better go catch it lol
```

## Additional Context

From my understanding, this is most likely because Go implemented their own DNS lookup system, which uses `/etc/resolv.conf`, instead of calling `gethostbyname`. Because of the split DNS, `/etc/resolv.conf` is not updated with the private DNS addresses, go is unable to lookup the address (it would work perfectly if it just used the cgo resolver).

The fact that it's listing my DNS address instead of the VPN's DNS address is telling, and is why I think it's the go DNS resolver issue.

## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS/Single server for web and worker/behind VPN
* Did this used to work? yes, in 3.x and 4.x releases

**Comment by dkuntz2** [comment]
Confirmed that `fly` is using go's DNS resolver

```
$ export GODEBUG=netdns=cgo+1
$ fly -t target login

logging in to team 'main'

go package net: built with netgo build tag; using Go's DNS resolver
could not reach the Concourse server called aws:

    Get https://concourse.internal-address/api/v1/info: dial tcp: lookup concourse.journera.net on <public dns>:53: no such host

is the targeted Concourse running? better go catch it lol
```

**Comment by dkuntz2** [comment]
Building a fresh version of fly with `CGO_ENABLED=1` allows for the split DNS setup.

**Comment by bacoboy** [comment]
This may be related to a terraform issue I've been following here: https://github.com/hashicorp/terraform/issues/3536

This has been a long running question/issue in golang which appears to have come to some kind of resolution in the last month: https://github.com/golang/go/issues/12524#issuecomment-470998867

Not clear if the concourse binary itself also needs to be compiled this way, but I suspect yes.

**Comment by eedwards-sk** [comment]
This change also broke my local orchestration tooling.

I'm relying on using consul DNS and resolver overrides on OSX so that DNS lookups to `*.service.consul` go to my local consul DNS on a custom port.

Keeping an eye out for any workarounds.

**Comment by dkuntz2** [comment]
@eedwards-sk you can build your own copy of fly, you just need to run

```
CGO_ENABLED=1 go build github.com/concourse/concourse/fly
```

You should get a fly binary in `$GOPATH/bin`. If you want to build it somewhere else you can use the `-o $path` flag in the build command.

**Comment by eedwards-sk** [comment]
Thanks @dkuntz2 that worked.

I wonder if we can expect this change to fix official fly or if we'll have to build it ourselves from now on.

**Comment by bacoboy** [comment]
I think the point of this ticket is to fix the official build.  It is silly to force people to do this individually.

**Comment by vito** [comment]
I've added this to v5.3, we'll look into why it's building without cgo. Seems unintentional.

**Comment by vito** [comment]
Ah ha, looks like this started happening because we have Darwin and Linux share the same 'fly' build script. Previously Linux would rely on its Docker image having set `CGO_ENABLED=0`, but it later moved to the script, thereby affecting both.

https://github.com/concourse/concourse/blob/master/ci/tasks/scripts/fly-build#L21

I'll investigate and see if we really need either to be static.

**Comment by jgriff** [comment]
I'm experiencing this same issue again with `5.7.2`.  

I'm on a Mac, targeting a Concourse instance behind a VPN with similar circumstances as @dkuntz2 originally described.

Rebuilding `fly` from source as mentioned [above](https://github.com/concourse/concourse/issues/3691#issuecomment-493790016) also fixes the problem for me.

Is this still a known issue?

**Comment by cadethacker** [comment]
So am I missing something here?  It is a good 10 months later and I'm running into this exact issue on my mac.  And the same work around is still valid, which is to build fly yourself.  I mean, it isn't difficult, but highly unexpected and took me a good 2 hours to figure out the answer.   Kind of deflating actually...

The only thing I would add to the comments above about building, is that if you are running a slight older version of concourse like 5.8.1 you should make sure to checkout that version and build that one.  I build latest from master and tried to connect to 5.8.1 and odd things occurred.

**Comment by taylorsilva** [comment]
Haven't dug deeper into this issue but we definitely compile the macos binary with `CGO_ENABLED=1`. I can see it in the build output of our pipelines. The task script is here: https://github.com/concourse/ci/blob/master/tasks/scripts/fly-build#L21

Haven't worked on reproducing this myself on my mac.

**Comment by archoversight** [comment]
Are the macOS binaries being built on macOS? Or are they being cross-compiled?

**Comment by vito** [comment]
@archoversight They are built on macOS, not cross-compiled.

**Comment by aghassemlouei** [comment]
Updating thread with some specifics for posterity. ConcourseCI version 6.7.1 and macOS 11.1 are still affected by this same scenario.

**Comment by archoversight** [comment]
> @archoversight They are built on macOS, not cross-compiled.

Sorry, I was asking stupid questions. Thanks!

**Comment by archoversight** [comment]
Oh, so taking a look at the Concourse build steps, there's this:

> go build --tags 'netgo osusergo' -a -ldflags "$ldflags" -o $output/fly ./fly

Reading here:

https://www.arp242.net/static-go.html

> net can use the C standard library to resolve domain names, but by default it uses the Go client. The C library has a few more features (e.g. you can configure getaddrinfo() with /etc/gai.conf) and some platforms don’t have a resolv.conf (e.g. Android), but for most cases the Go library should work well.

> Your binary will no longer be statically linked if your program imports one of those two packages, either directly through a dependency. Especially the net one is quite common.

> You can use the osusergo and netgo build tags to skip building the cgo parts:

So by building with `netgo` you are explicitly opting out of the `net` parts of cgo. This will build the binary with Go's built in DNS resolution which breaks the split DNS functionality.

Those of us building at home, just build with cgo enabled and without adding any tags to disable cgo functionality. At the end you won't have a binary that is statically linked, BUT it should only be linked against macOS libraries that exist on the system and thereby should still be easily distributable.

**Comment by archoversight** [comment]
@vito I see this commit here: https://github.com/concourse/ci/blob/master/tasks/scripts/fly-build#L21 replaced the use of CGO entirely, which means that on macOS split DNS will continue to be broken.

**Comment by vito** [comment]
@archoversight ahh good call, sorry I didn't notice your replies earlier. Will look into this asap! I wonder if we can work out a smoke test for this so it doesn't regress again. 🤔

**Comment by archoversight** [comment]
It seems to me that there needs to be some if statements sprinkled in that build script to build with CGO on macOS so that it builds against the system provided libraries for DNS resolution.

I have no idea how to smoke test it so it doesn't regress again.

**Comment by archoversight** [comment]
I will note that the fly that is distributed with concourse 6.7.3 is linked against the same libraries as the fly I built with CGO_ENABLED:

```
C02CG59EMD6M ~/Projects/3rdparty/concourse/fly % ./fly --version
0.0.0-dev
C02CG59EMD6M ~/Projects/3rdparty/concourse/fly % otool -L ./fly
./fly:
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 0.0.0, current version 0.0.0)
C02CG59EMD6M ~/Projects/3rdparty/concourse/fly % ~/Applications/fly --version
6.7.1
C02CG59EMD6M ~/Projects/3rdparty/concourse/fly % otool -L ~/Applications/fly
/Users/c5309377/Applications/fly:
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 0.0.0, current version 0.0.0)
```

So it doesn't add any extra dependencies on libraries that may not exist on the users macOS installation.

**Comment by xtremerui** [comment]
https://github.com/concourse/ci/commit/945bf8a1e1744a1a7b4459ad178834f5cbc67888 

In next release `fly` with be built with cgo net library. We also added a check to make sure no regression again. @vito

**Comment by vinodkumartr88** [comment]
Hi all, I am facing this same issue with fly in macOS. I saw the above work around as "Building a fresh version of fly with CGO_ENABLED=1 allows for the split DNS setup." but i didn't fully understand on how to build a fly myself in my laptop. If someone can redirect me to any article or tutorial which explains on 'Building a fresh version of fly with CGO_ENABLED=1' it would be really helpfull. Thanks all
