### ISSUE TITLE
Fallback DNS to 8.8.8.8/8.8.4.4/1.1.1.1(?)

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3694]
Can we detect if `/etc/resolv.conf` only contains loopback addresses and, if so, default Garden to a public DNS server?

**Comment by vito** [comment]
related: https://github.com/concourse/concourse/issues/1667

**Comment by bacoboy** [comment]
In our case, we don't want a public server, but one that we specify internally.

Perhaps instead of having a magic transparent fallback when these situations arise, the application should just fail to start with a clear error message says "set/configure XXXX since we can't resolve DNS"?

**Comment by vito** [comment]
@bacoboy Wouldn't you just need to explicitly set it, then? The point here is to have sane defaults for first-time users, as this is a common pitfall with most Linux distributions these days. Docker has been using this default for quite a while and I haven't heard any loud complaints - it's just a default, after all:

https://docs.docker.com/config/containers/container-networking/#dns-services

**Comment by bacoboy** [comment]
Yes, but some setups are crazy and things don't always just work.  If it falls thru to a non-usable address (like 127.0.0.1 or 127.0.0.53) then it depends if this is a quick user setup or production setup.  If I was a user trying to run this for the first time, sure I'd love to see `WARN: can't figure out your DNS so defaulting to 8.8.8.8.  Set --dns-server flag if you want something else`.  But in a production environment where you aren't looking at the logs of EVERY server every day all day, having this buried in logs will just get lost.  We use an internal DNS that must be specified and if it can't use that we WANT the startup to fail.  THAT we will notice and go fix.

I hesitate to suggest a `DISABLE_MAGIC_CONFIGS=true` flag which disables these kind of ease of use magic fallback behaviors which are likely undesirable in production setups.

**Comment by cirocosta** [comment]
Hey, sorry if I misunderstood the issue, but **is this about completely getting rid of the DNS server?**

Some "data": since the creation of https://github.com/concourse/concourse/issues/3103 (a story more focused on DNS under k8s to ensure that our expectations hold true there), we saw two cases of people disabling it:

- https://github.com/alphagov/gsp-ci-system/pull/20
- https://github.com/concourse/concourse/issues/3103#issuecomment-478139747

Thanks!

**Comment by vito** [comment]
@cirocosta This is just for having a sane default/fallback, typically for binary deployments, though in principle it could also be used for the Docker case if we want to get rid of the proxy server. They're both examples of the default `resolv.conf` containing addresses unreachable by the container.

**Comment by marco-m** [comment]
I agree with @bacoboy reasoning. No magic, fail fast and clear. In the past we got bitten by this one also. Since my team is very smart, they figured out was going on.

**Comment by vito** [comment]
Fair enough. Closing!
