### ISSUE TITLE
concourse.ci only listening on IPv6, not able to configure for IPv4

### ISSUE THREAD

**Issue by bf16574403** [concourse/concourse#370]
When concourse is started up, by default it listens on 8080 , via IPv6 only.

ie;    #netstat -an | grep LISTEN
...
...
tcp6           0              0    :::8080                   :::\*            LISTEN

There is currently no way for it to be switched over to IPv4, so users using IPv4 only (like myself) cannot access concourse!

Please allow for the ability to configure which IPv protocol is used / listened to.

Thanks.

**Comment by edysli** [comment]
Are you sure it is IPv6-only? I think the socket may be both IPv4 and IPv6 when shown as "tcp6" by netstat. Have you tried reaching concourse over IPv4? If I run `curl -v --ipv4 http://localhost:8080/`, mine is reachable over IPv4 as well:
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 01 Mar 2017 11:56:58 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< 
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Concourse</title>
...
```

If you want to force the Concourse TSA to use only IPv4, you can start it with `--bind-ip=127.0.0.1`.
