### ISSUE TITLE
Eliminate the pipeline syncer!

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3704]
...AND ITS STUPID FLAKY TEST

**Comment by vito** [comment]
We can do this once...:

* `radar` is no more and `lidar` has taken its place
* the new algorithm is in place

**Comment by vito** [comment]
Might want to also split the build starter out from the scheduler, which can also be a global process.

**Comment by clarafu** [comment]
After #4534, we can remove the pipeline syncer and have a global scheduler that will schedule per job. This global scheduler will run once per tick throughout the entire deployment and will schedule all the jobs for all pipelines, the implementation will be really similar to the lidar scanner.

**Comment by vito** [comment]
In eliminating the syncer it became apparent that we would need to load all jobs and resources across the cluster into memory to do an "all at once" scheduling tick, which seems pretty expensive considering these are real `db.Job` and `db.Resource` objects, not just integers like they were with the old algorithm.

So instead of scheduling literally everything on a fixed interval, we're gonna see if we can only schedule pipelines which have actually changed and need scheduling to run.

To do this, we would need to know what 'changes' require scheduling to run. So far, we've thought of:

* Detecting new versions of a resource.
* Finishing a build (because `passed` constraints).
* Disabling a resource version.
* Pinning/unpinning a resource version.
* Changing a pipeline config.
* Updating a resource's `resource_config`.

This approach has a lot of upside:

* When a pipeline stabilizes, there will be no additional scheduling overhead on the database and `web` nodes.
* We won't need to bump `last_scheduled` on the `jobs` table anymore, which will save on a ton of writes.

The downside is we'll need to remember to mark the pipeline as 'needs scheduling' on any of these state changes. But this isn't a new problem; there's a `cache_index` column on the `pipelines` table, and it's bumped in some of these cases already. The intent of this column is to tell the old algorithm that it needs to run `LoadVersionsDB` again to load a fresh dataset for the pipeline. So, pretty similar to what we want here.

The set of state changes seems small enough that this shouldn't be a huge maintenance burden. They're also pretty easy to reason about.

**Comment by vito** [comment]
One complication: `version: every` means that we'll need to schedule again after we've chosen the "next" version so we can run with the "next next" version. So within the algorithm we'll detect the situation where there is another candidate version and the scheduler itself will just re-request another scheduling after it's done.
