### ISSUE TITLE
Pipeline filter css not working as expected for lots of filters

### ISSUE THREAD

**Issue by kardolus** [concourse/concourse#3717]
## Bug Report

When you have lots of pipeline filters the filter buttons overlap. See screenshot below

![Screen Shot 2019-04-10 at 3 04 58 PM](https://user-images.githubusercontent.com/8877664/55906473-5b884e80-5ba2-11e9-9e41-2a5f79526890.png)

## Steps to Reproduce
You could check out our dependency-builds pipeline here:
https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds

## Expected Results
Everything looks awesome! :)

## Actual Results
Buttons overlap

## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: ??
* Browser (if applicable): Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Did this used to work? Yes

**Comment by vito** [comment]
already fixed by #3692
