### ISSUE TITLE
Rolling update of web nodes

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3721]
Hey,

I got confused while trying to understand how one could perform a rolling update of Concourse when having multiple web nodes.

Assuming that we have two ATCs at version `X` at a particular moment (time0):

```
	time0     

		atc1     (X)
		atc2     (X)
```

And we try to perform a rolling update to version `Y` (at `time1`) having old instances being taken down *before* having new ones up:

```

	time1     

		atc1     (X)
		atc2     (X) --> dies


	time2

		atc1     (X)
		new-atc2 (Y)


	time3

		new-atc1 (Y)
		new-atc2 (Y)

```

From my understanding (and conversations with @ddadlani0), at `time2`, when `new-atc2` comes up:

1. `new-atc2` acquires a lock for the migrations table, preventing other ATCs to perform any migrations, then
2. `new-atc2` starts performing the migrations

Meanwhile, `atc1` (which is at version `X`):

- still serves traffic
  - adding new pipelines to the DB, for instance
- continues scheduling work

Is the above right? If so:

- are there any concerns that one should have around the fact that one would have ATCs operating with an old version while another ATC performs the migrations?
- should we recommend people to take down all of the ATCs before starting the new instances with new versions in order to ensure that they do not touch the database while that happens?
- should we lock the entire DB when doing the upgrades?

Thanks!

**Comment by pivotal-jwinters** [comment]
@cirocosta yes! all of your concerns are valid.

**Comment by taylorsilva** [comment]
I have two questions, just to help give me context:
- What's the current official upgrade path for users? 
- Does it involve **some** downtime or **zero** downtime?

**Comment by xtreme-sameer-vohra** [comment]
Few thoughts

If Concourse's business logic is baked into the DB models via constraints (eg. FK constraints, Not Null constraints), then the following can be said about the system
1. At `time2`, API requests to `atc1` could fail if DB constraints are not satisfied
1. The DB constraints prevent `atc1` from putting the DB into an inconsistent state

**Comment by xtreme-sameer-vohra** [comment]
Supporting zero downtime during an upgrade that includes db migrations under load would require assessing our DB migrations and splitting them off into multiple steps. This would require more complex breakdown and coordination.

[Reference on on how it may be achieved](https://thoughts-on-java.org/update-database-schema-without-downtime/)

**Comment by ddadlani** [comment]
I am in favour of locking the DB / preventing any other work from being done while an upgrade is in progress.

Aside from migrations, another reason we would want to do this is for #3810. If we are streaming base resource types from the ATC over to the workers, we need to account for the scenario where the base resource type versions are being updated. 

We can't have a scenario where ATC 1 is updated with new base resource type versions, and has started streaming them over to the workers, while ATC 2 is still trying to schedule work with the old versions.

**Comment by pn-santos** [comment]
Going to add that in order to do a DB snapshot before an upgrade one would also need to bring down both instances gracefully to ensure a consistent state (for a backup restore).

**Comment by cirocosta** [comment]
@vito is this something that core would take a decision/action on? 🤔

**Comment by vito** [comment]
Locking the database during an upgrade sounds simpler but I'm not sure how it would actually work mechanically. :thinking: It might end up being more moving parts than it sounds.

Zero-downtime migrations (as @xtreme-sameer-vohra said) feels a bit more ambitious, but I think it's a noble goal to strive for. I think we'd need to do some exploration on this idea to really know how to accomplish it and guarantee that we have coverage for this sort of thing in the pipeline.

There's a side-concern here around which approach will be easier for contributors. I have some concern that zero-downtime migrations will be more difficult, but I'd like to validate that first. If it's something we can at least have automated tests for, that gives me some hope. And maybe we can land on a pattern that isn't all that complicated to reason about.

Rough idea: maybe we could have an 'upgrade test' where we leave the cluster 50% upgraded (diagraded?) and assert that `testflight` is able to run successfully? I'm not sure if that would cover enough scenarios, but it seems like a start. :thinking: 

As for when we get around to this...I'm not sure. I don't think we've seen an upgrade path that resulted in permanent damage to the cluster or data yet, have we?
