### ISSUE TITLE
Database migration inserts `inputs: null` to Put and Get steps

### ISSUE THREAD

**Issue by dingxiangfei2009** [concourse/concourse#3725]
> Please remove all lines starting with '>' before submitting!
>
> Bug reports on this repo should be related to core Concourse functionality.
>
> If the bug has more to do with *running* Concourse, consider opening the
> issue on a platform-specific repository instead:
>
>    BOSH: https://github.com/concourse/concourse-bosh-release
>    Docker: https://github.com/concourse/concourse-docker
>    Kubernetes: https://github.com/concourse/charts
>
> It's OK if you open it here, but we may move it to a more appropriate repo.
>
> If you're not sure that this is a bug and just need help with something,
> please ask in our support forum instead:
>
>     https://discuss.concourse-ci.org/c/support

## Bug Report

> (summarize the issue)

Upgrade from some 5.0.0-rc to 5.0.0 causes ATC database migration, which automatically inserts `inputs: null` to put and get steps in all pipelines. This breaks resources that needs to read data from the input resource, since setting `inputs: null` will exclude its own resource data.

## Steps to Reproduce

> (please include any pipelines/tasks using https://gist.github.com)

Upgrade from 4.9.x all the way to 5.0.1.

## Expected Results

Pipeline configurations according to `fly get-pipeline` stay the same.

## Actual Results

`inputs: null` are inserted. Put steps, in particular for some resource types like `github-pr-resource`, stop functioning because they cannot read into its own data.

## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: GCP
* Browser (if applicable):
* Did this used to work? Yes

**Comment by vito** [comment]
This is the danger of release candidates!
