### ISSUE TITLE
fly does not know about resource icons

### ISSUE THREAD

**Issue by chenbh** [concourse/concourse#3729]
## Bug Report

After #3581 was merged, it seems like fly is not aware of the `icon` field which results in:

1. `fly set-pipeline` and `fly get-pipeline` does not show the field in the output
1. Changing the icon and setting the pipeline again will result in `no changes to apply`

**Comment by vito** [comment]
have you run `fly sync` and/or downloaded `fly` from the web UI?

**Comment by chenbh** [comment]
Hmmm, both running `fly sync --force` and downloading from the UI on local concourse still had this issue.

Used the fly from ci.concourse-ci.org and it did not have this issue, which probably means I forgot to build it during the docker-compose stuff

**Comment by chenbh** [comment]
did a little more poking around:

- we're rebuilding the `concourse` binary but not the `fly` binaries every time we do `docker-compose up`
- the fly binaries are pre-baked into the dev image
- docker-compose prefer to use cached images over pulling the latest ones
- have to remember to do a `docker pull concourse/dev` once in a while
- we can rebuild the fly binaries in docker-compose but that would only apply to the linux binary, no good way of rebuilding other ones
