### ISSUE TITLE
Merge cf pagination fix from concourse/dex

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#3730]
We need to re-merge all our pr branches into a new master branch in concourse/dex then bump the dependency in concourse/concourse.

**Comment by vito** [comment]
https://github.com/concourse/dex/pull/6 was merged, so now we just need to re-sync `master` via the `maintenance` script and bump the dependency in `concourse/concourse`

**Comment by xtremerui** [comment]
PR created #3765

**Comment by vito** [comment]
#3765 is merged
