### ISSUE TITLE
topgun/k8s: Add coverage for RBAC

### ISSUE THREAD

**Issue by YoussB** [concourse/concourse#3733]
## What challenge are you facing?

- currently, we don't have any topgun/k8s coverage for [RBAC](https://github.com/concourse/rfcs/pull/6)

## What would make this better?

- Adding coverage to make sure role-based access is working with different versions of the chart.

**Comment by cirocosta** [comment]
Hey,

We have this test:

https://github.com/concourse/concourse/blob/d64843ce1bbab2309213ff677e25aadb950fc33b/topgun/k8s/mainteam_role_test.go#L57-L67

Is that enough? 🤔 

Thanks!
