### ISSUE TITLE
Display resource related builds in the build page

### ISSUE THREAD

**Issue by mockersf** [concourse/concourse#3734]
## What challenge are you facing?

When viewing a build in Concourse, I can't easily check other builds that may have been triggered by the same version of a resource, or builds that have been triggered by a new version of a resource produced by the current build. I have to remember the version of the resource, go to the resource page, select my version to view it's inputs to / outputs of

Resource version details in a build:
<img width="983" alt="Screenshot 2019-04-15 at 00 52 04" src="https://user-images.githubusercontent.com/8672791/56100425-d0e47e00-5f18-11e9-8009-bffb19bc1868.png">

Resource version details in the resource page:
<img width="983" alt="Screenshot 2019-04-15 at 00 52 21" src="https://user-images.githubusercontent.com/8672791/56100434-e0fc5d80-5f18-11e9-96fc-df66b9773df5.png">

## What would make this better?

Either display the same information in the build page when clicking on a resource, or provide a link to the resource page with the related version already opened.
The resource screen is using the ID from the `resource_config_versions` table which can easily be added to the response from the `api/v1/builds/<build-id>/resources` call for either linking or fetching the related information on click.

I think displaying "inputs to" on the build page when the version is clicked would work best, but it would push down resource logs and add more information to the build page.

## Are you interested in implementing this yourself?

Yes!

**Comment by vito** [comment]
Sounds like a good idea. I'm not a huge fan of the current resource page (it's pretty janky and a little slapped-together), but I do agree that it'd be nice to be able to navigate to that page - it makes the pipeline feel more 'cohesive'. This could end up being even nicer with 'causality' (https://github.com/concourse/concourse/issues/1538).

Maybe this could be done by adding an individual-version view and having the build's version link to it?

**Comment by pivotal-jamie-klassen** [comment]
@vito having a page at `/teams/:team/pipelines/:pipeline/resources/:resource/versions/:id` does feel pretty intuitive, now that I think about it. I could imagine some of the page components being similar to the build page (like a scrolling list of tabs for each version). Maybe a button in the top right to enable/disable the version (parallel to the pause button on the pipeline page)...

**Comment by chenbh** [comment]
This was added in #6662 and released in 7.2.0
