### ISSUE TITLE
Dashboard doesn't show job color if there's too many jobs

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [concourse/concourse#3741]
## Bug Report

We have a pipeline with ~140 jobs in the first 'column' when viewing the concourse dashboard view. The layout has space for all jobs, and mouse-hover tooltips show all jobs are being rendered, but only a subset have a red/green color, the rest are invisible.

## Steps to Reproduce

Deploy a pipeline with 140 jobs that do not depend on another job. View the low-density dashboard.

## Expected Results

All jobs should be visible as a colored box reflecting the job state

## Actual Results

Only a scattered subset of jobs are visible, but all jobs have a click target/hover text.

## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? With ~120 jobs the dashboard displayed correctly
![Screen Shot 2019-04-16 at 10 57 27 AM](https://user-images.githubusercontent.com/1062633/56221074-86a5ee80-6037-11e9-81b4-1f7d70175228.png)

**Comment by mockersf** [comment]
They are actually all displayed, but each has a height of 0.34px... and the browser shows only some of them randomly.

The box in the dashboard has 3 sizes, depending on how many jobs there are in the longest columns, changing at 12 and 24. The tallest is 608px, and each line has margins of 2px. The maximum number of jobs that will actually be displayed is 121, more than that and there will be less than 1px remaining per job.

Solutions could be to either use reduced margins for the special case where there are more than 120 jobs, or add a new box size
