### ISSUE TITLE
`fly login` token transfer does not work in Safari

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#3747]
## Bug Report

When `fly` does not have a valid token and redirects to the web to generate one, the webpage does not properly send the token back to `fly`.  If the user attempts to paste in the token, `fly` never accepts it.

## Steps to Reproduce

1.  Given a `fly` target without a valid token
2.  `fly -t workers` (generates a link)
3.  Navigate to the link in a browser (does not send token to `fly`)
4. Copy token and past into `fly` (token is never accepted and action is not taken)

## Expected Results

I'd expect the token to properly redirect back to `fly` as it did before 5.0.0.  In the case where it does not, I'd expect that pasting the token back into `fly` would be successful.

## Actual Results

![fly-token](https://user-images.githubusercontent.com/60754/56301396-97646c00-60ec-11e9-8ace-2dbc5c68fbaf.gif)

## Version Info

* Concourse version: 5.1.0 (started in 5.0.0)
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Safari 12.1 (14607.1.40.1.4)
* Did this used to work?Yes, prior to 5.0.0

**Comment by xtremerui** [comment]
Hi, manual token input is only available for `fly login`. The change is made in this [commit].(https://github.com/concourse/concourse/commit/6baf90cf5ecdb8092fc2a480517470d91dc3d91b#diff-6d58f4e91826adc9b2eba8b1a7df3a15)

**Comment by nebhale** [comment]
@xtremerui Understood, but given that I can be prompted for the token in _any_ command, manual addition needs to be available any place that the prompt is.

I think this is especially important since my guess is that the magical redirect won't be fixable for Safari (and likely Firefox though I haven't tested).  And I'm guessing that the end might come for Chrome as well given that the problem is up-leveled security that prevents redirects from secure to non-secure URIs:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/60754/56583557-d476a580-65a7-11e9-94a3-65827458c15f.png">

**Comment by xtremerui** [comment]
@nebhale in this case you would have to break the flow to `fly login` and `fly workers`. The reason of that is in the comment of https://github.com/concourse/concourse/issues/2414#issuecomment-427509169.

**Comment by nebhale** [comment]
You've described a technical limitation that causes this behavior.  You haven't addressed the issue that as a user experience, this is problematic.  As you can see from the video above, there's nothing to indicate to a user what is going on, other than that the input hangs after the instructions on the webpage are followed.

**Comment by xtremerui** [comment]
@jama22 should we add a text output after the `navigate to the following URL..` part that if browser redirect doesn't work and user sees `copy to clipborad` page, they have to `ctrl-c` and do `fly login` first?

**Comment by vito** [comment]
There are a few things in play here, so let's unfurl them:

* The automatic logins *can not* actually prompt for a token via user input - this is a design decision and not just a technical limitation. We decided not to prompt for a token in this case because the user may be running a command and piping input to it. We don't want the input stream to be partly read (and thus corrupted) by the token prompt.
  * We could improve the UX here by sending a param indicating whether there's a prompt available to copy the token into or whether we need to tell the user to run `fly login` explicitly.
* Some browsers don't allow a request to `http://127.0.0.1`. We'll probably need to do some research on each browser's current and planned content policy enforcement before we can figure out the next step to take.

**Comment by alnaranjo** [comment]
I've notice this happening on Safari Version 12.1 (14607.1.40.1.4) but not on Chrome Version 74.0.3729.169 (Official Build) (64-bit) for fly 5.0.1

**Comment by simonjohansson** [comment]
This is a constant issue in with our users. 

Adding a `click here to forward token to fly binary`[1] button would be 👍 as its one less step than clicking copy and then pasting in the terminal. Tested in safari and it works.

[1] `<a href="http://127.0.0.1:{flyPort}/{authToken}> click here to forward token to fly binary</a>"

**Comment by pivotal-jamie-klassen** [comment]
I have struggled with this issue for weeks and just today realized that I can only reproduce it if Safari is accessing Concourse over HTTPS.
