### ISSUE TITLE
[performance regression] dashboard exhausting cpu

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [concourse/concourse#3748]
## Bug Report

Rendering the dashboard uses excessive amounts of cpu. Usage remains high even if the animations are outside the viewport, or if no jobs are running (no animations)

## Steps to Reproduce

Run many (>150) jobs simultaneously, view low density dashboard.

## Expected Results

Dashboard should not consume all cpu. Cpu usage should drop if animations are outside the viewport.

## Actual Results

Browser renders at < 5 FPS
![Screen Shot 2019-04-17 at 12 04 58 PM](https://user-images.githubusercontent.com/1062633/56303039-110a5300-6109-11e9-8d6e-e41538735cc8.png)

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Yes in 5.0.1

**Comment by jama22** [comment]
quick clarification @xtreme-conor-nosal , is this increase of CPU on your local computer or on the web node (ATC)

**Comment by xtreme-conor-nosal** [comment]
On the local computer. The browser struggles to render the animations.

**Comment by xtreme-conor-nosal** [comment]
Just checked again now that our concourse is idle, and browser rendering is still slow. It's not related to the animations.

**Comment by xtremerui** [comment]
I think when hitting dashboard of ci.concorse-ci.org the browser renders slower in 5.1 too.
