### ISSUE TITLE
[topgun/k8s] worker_lifecycle test doesn't clean up when it fails + flakiness

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#3749]
The `worker_lifecycle` test in `k8s-topgun` doesn't clean up after itself. If the test fails then it leaves behind the namespace and pods that it made. If it fails multiple times in a row (like it has recently) then we end up using all the resources in the k8s cluster.

We should fix the test to ensure cleanup is always being done.

**Comment by taylorsilva** [comment]
We figured out that the `worker_lifecycle` test is a bit flakey. Sometimes it passes and sometimes it doesn't.

This is the error the test is giving:

```
STEP: making sure the first build has succeeded
STEP: [1555623000.865638971] running: /var/folders/41/rll24f7n1wn88_29pfvgwgtw0000gn/T/gexec_artifacts121396621/g937632648/fly -t concourse-topgun-k8s-1 builds -j some-pipeline/simple-job
Handling connection for 50781
1  some-pipeline/simple-job  1  errored  2019-04-18@17:29:09-0400  2019-04-18@17:29:10-0400  1s  main
STEP: [1555623001.007029057] running: helm delete --purge topgun-wl-654986-1
release "topgun-wl-654986-1" deleted
STEP: [1555623001.961277962] running: kubectl delete namespace topgun-wl-654986-1 --wait=false
namespace "topgun-wl-654986-1" deleted


• Failure [156.284 seconds]
Worker lifecycle
/Users/pivotal/workspace/concourse/topgun/k8s/worker_lifecycle_test.go:15
  retiring a worker
  /Users/pivotal/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/extensions/table/table.go:92
    gracefully [It]
    /Users/pivotal/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/extensions/table/table_entry.go:46

    Got stuck at:
        1  some-pipeline/simple-job  1  errored  2019-04-18@17:29:09-0400  2019-04-18@17:29:10-0400  1s  main

    Waiting for:
        succeeded

    /Users/pivotal/workspace/concourse/topgun/k8s/worker_lifecycle_test.go:97
```

We've had two theories:

1. The first job is starting too soon after the worker process has started
    - Tried to fix this by adding a `sleep` after seeing the worker come up. We tried 30s and then 60s but the error still came up
2. We're hitting a race condition. Theory is that if you send `SIGUSR2` after a job has started but before a volume is created then the job will error out. 
    - Tried to resolve this by adding a 2s sleep after the job has started. This did not work either.

This may be a condition we have to think about more.

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
1. The 2 `sleep`s are for investigating the issues, seeing the behavior, NOT a solution for the test case.
2. These 2 `sleep` CAN ensure the test cases for worker lifecycle success.
3. the 2nd sleep can ensure the job/task actually start running. Removal sometimes will cause:
```
tmp $ fly -t local watch -j some-pipeline/simple-job
initializing
fetching busybox@sha256:f79f7a10302c402c052973e3fa42be0344ae6453245669783a9e16da3d56d5b4
fc1a6b909f82 [======================================] 738.1KiB/738.1KiB
running sh -c until test -f /tmp/stop-waiting; do
  echo 'waiting for /tmp/stop-waiting to exist'
  sleep 1
done

echo done

waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
waiting for /tmp/stop-waiting to exist
worker topgun-wl-185429-1-worker-0 disappeared while trying to reach it
errored
```
***TODO***:
- experiments on the 1st `sleep`
- understand the `status` we should be before the 2 `sleep`s. aka. What status we should check to ensure we can succeed the test case.
- A talk with OSS should happen we we are ready with the experiments conclusion.

**Comment by cirocosta** [comment]
Update: we spent quite a good time trying to figure out what's the underlying problem that is causing the flake, but we're still not 100% sure of what is - some times there's a problem with volume creation, which causes the failure to happen.

This *still* needs investigation, but we'll leave it here with a temporary solution so we can move on with the `hush-house` preparation.

Thanks!
