### ISSUE TITLE
Remove hardcoded value for BBR-compatible postgres in the pipeline

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3750]
Hey,

After BBR's fix for https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/issues/14 we're now able to not have the value hardcoded:

https://github.com/concourse/concourse/blob/d64843ce1bbab2309213ff677e25aadb950fc33b/ci/pipelines/concourse.yml#L1407-L1412

Once we ensure that the tests indeed pass, we can then ask them to close to issue as well.

Thanks!

**Comment by mhuangpivotal** [comment]
The hardcoded postgres version was removed in https://github.com/concourse/concourse/pull/3815. Once CI passes, we can close both this issue and cloudfoundry-incubator/backup-and-restore-sdk-release#14.

**Comment by cirocosta** [comment]
It's good now 🙌 

https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-topgun/builds/387#L5cd045af:1302:1322

Thanks!!
