### ISSUE TITLE
Regression: pipelines/ci?groups=$GROUP_NAME no longer works

### ISSUE THREAD

**Issue by klakin-pivotal** [concourse/concourse#3761]
## Bug Report

The `groups` query parameter to the `pipelines/ci` endpoint is no longer recognized. It appears to have been renamed to `group`. Either both spellings should be accepted, or the long-standing spelling of `groups` should be used.

For the past several years, the CF Toolsmiths have been using a Concourse Dashboard that creates hyperlinks to Concourse Groups in the following form: `https://wings.pivotal.io/teams/toolsmiths/pipelines/deploy?groups=slack-related`. At some point within a week or so of Monday, April 15th, those links stopped working and started sending you to the first Group in the Pipeline.

## Steps to Reproduce

1) Open a pipeline in your web browser that has multiple Job Groups
2) Navigate to the second -or subsequent- Group
3) Replace the substring `group=$GROUP_NAME` with `groups=$GROUP_NAME`
4) Watch as you get redirected to the first group in the set.

If you have the privs to see this pipeline, here's a demo URL: https://wings.pivotal.io/teams/toolsmiths/pipelines/deploy?groups=slack-related

## Expected Results

I expected to see the desired group.

## Actual Results

I saw the first group in the set of groups in the Job.

## Additional Context

This regression is live on Wings at the time of this writing.

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): Whatever Wings is using
* Infrastructure/IaaS: Whatever Wings is using
* Browser (if applicable): Chrome 73
* Did this used to work? Yes

**Comment by vito** [comment]
This is pretty low priority for us to be honest. :confused: The new URL scheme is more "technically correct", and our URLs and endpoints have never been a public contract. The mitigation seems straightforward.

If you want to PR this change yourself, I believe the code is here:

https://github.com/concourse/concourse/blob/c7c2a47cb251894c2d9a064353618c113083c113/web/elm/src/Routes.elm#L190

It could be changed to handle both `group` and `groups`.

**Comment by klakin-pivotal** [comment]
I've been meaning to learn some Elm. I'll see what I can do and what tests I need to update.
