### ISSUE TITLE
Icon should be on resource_type

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3762]
## What challenge are you facing?

First, thank resource icon introduced by 5.1.0 for making pipelines look more vivid.

I noticed that `icon` can only be defined on resources, while I think `icon` should be defined on resource_types. Because icon, say a slack icon, is actually an attribute of a resource type. If I have multiple resources of same type, duplicate defining same icon on multiple resources is kinda overhead.

## What would make this better?

1. Support `icon` on resource type.

2. Built-in resource types, say `git` resource type, should also be defined with an icon. A pipeline may contain multiple `git` resources, it would be more convenient if built-in resource type has defined an icon on `git` resource type.

3. We may still support `icon` on resources, so that user may overwrite `icon` defined on resource_types.

## Are you interested in implementing this yourself?

Yes, we can if the original author of the icon feature has no bandwidth is make this enhancement.

**Comment by xtremerui** [comment]
linking https://github.com/concourse/concourse/issues/3755

**Comment by evanchaoli** [comment]
@mockersf Can you please comment on this?

**Comment by vito** [comment]
@evanchaoli I agree with the sentiment, however we're already planning on having resource types provide icons via the resource interface itself - concourse/rfcs#24 specifies it as part of the `Info` response: https://github.com/vito/rfcs/blob/generalized-resources/024-generalized-resources/proposal.md#interface-types

I'm not sure if it's worth taking this intermediate step; we already intended for the manually-specified `icon:` approach to be the stopgap solution until the new resource interface lands. I'll leave it open in case you want to PR it anyway, but I do want to warn that it'll probably involve a lot of boring plumbing work.

**Comment by mockersf** [comment]
I looked at the time on how to add it to the resource type and let it be overridable at the resource, and it looked like it would need a lot of plumbing that would need to change completely for the generalized resource types.

And `git` resource is a very good example why we need at resource level, as the various git providers (github, gitlab, bitbucket) have very well known icons that are more recognisable than the git icon.

With the resource interface, the resource will be able to decide on which icon to used based on it's configuration 👍

**Comment by evanchaoli** [comment]
@mockersf I think it's arguable to use `git` as a sample. Because the majority resources have just unique implementations, `sonarqube`, `jira`, etc.. Defining icon on resource just leads pipeline authors to duplicately add icon every resources. If icon can be defined on resource type, for those built-in resource types, pipeline will by default icons, which is really cool.

In our concourse cluster, we add many more frequently used resource type as built-in, if icon can be defined on resource types, our users will benefit more, because most of pipeline resources will by default get an icon.

**Comment by vito** [comment]
@evanchaoli We're in agreement that it's nice to have, we're only calling into question whether this is really something worth spending time on *right now* because we already have a different long-term plan in sight and it's a lot of not-fun work to implement the short-term solution.
