### ISSUE TITLE
5.1.0 Release notes: --tsa-peer-ip

### ISSUE THREAD

**Issue by aledeganopix4d** [concourse/concourse#3770]
Hello,
Just a very small correction: the very first entry of the release notes for the 5.1.0 release should also mention that `--tsa-peer-ip` has gone and `--peer-address` replaces **both** `--tsa-peer-ip` and `--peer-url`, unless my understanding is not correct.

Thanks!

**Comment by vito** [comment]
Updated the release notes, let me know if it's still confusing! I actually didn't expect anyone to be using `--tsa-peer-ip` since I thought `--peer-url` would take precedence, so I didn't bother mentioning it.

**Comment by aledeganopix4d** [comment]
@vito That's perfect! Thank you!
