### ISSUE TITLE
Attempts step in a build job not loaded in the UI

### ISSUE THREAD

**Issue by margitabo** [concourse/concourse#3771]
## Bug Report

When a build job with attempts step modifier on it has finished we would like to check how each individual retry has finished. All the attempts numbers in the build job look like they have passed (all the numbers look like active i.e. none of them is colored grey) so we are able to click on them (there is a hand icon when hovering on the numbers) but after clicking on the numbers the build attempt is not loaded. But instead the 1st attempt is selected and the loaded build output looks like the last finished successfully attempt. 

## Steps to Reproduce

Add attempts step modifier to a task like:
```
  - task: deploy-concourse
    attempts: 3
```
We tried with 3 and 6 attempts.

## Expected Results

When clicking on an attempt number in a build job we would like to load the selected attempt and its build output.

## Actual Results

When clicking on an attempt in a build job the respective attempt is not loaded. The selection is returned to the 1st attempt and it seems the build output is from the last retry finished successfully. 

## Additional Context

When opening the finished build job the selection is on the 1st attempt and it seems the last successful build output is loaded:

![image](https://user-images.githubusercontent.com/7422973/56566656-dcd8db80-65bb-11e9-8039-9d5a2b905f4d.png)

After clicking on the 4th attempt, for example, the selection is returned again to the 1st attempt. 

![image](https://user-images.githubusercontent.com/7422973/56566399-3391e580-65bb-11e9-9942-074b43fc29c8.png)

## Version Info

* Concourse version: v5.1.0
* Deployment type: BOSH
* Infrastructure/IaaS: OpenStack, nova project version is 12.0.0
* Browser (if applicable): Chrome Version 73.0.3683.86 (Official Build) (64-bit) and Version 73.0.3683.103, Safari Version 12.1 (14607.1.40.1.4)
* Did this used to work? Yes, it worked as expected on Concourse v4.2.1 we were able to load the build output of the selected attempt.

**Comment by margitabo** [comment]
Hi, could you please update us when a new version containing the fix is expected to come out? Also is this the right git repo for the issue. In case it is not, could you please tell us which is the right git-repo/channel to open the bug there. 
Thanks and regards!

**Comment by vito** [comment]
Closing in favor of https://github.com/concourse/concourse/issues/3814 which includes a work-around (shift+click). This is prioritized in the UX backlog and will hopefully be in v5.3 (it'll probably miss the v5.2 release). This is the right repo - sorry for the delay!

**Comment by univ0298** [comment]
Unfortunately Shift is not available on iOS/Safari and presumably other cellphone browsers
Also https://github.com/concourse/concourse/issues/3814 is a closed issue. So this issue and that one are both closed...

**Comment by vito** [comment]
@univ0298 #3814 isn't closed.
