### ISSUE TITLE
Can't scroll job output on chrome mobile

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#378]
On chrome on mobile I can't scroll through the logs of a failed job. It just jumps around all wonky, especially at the bottom

**Comment by xtreme-gavin-enns** [comment]
I took a screen recording but it's too big to upload here. Lmk and I can send it by other means. 
![screenshot_20160415-194414]

(https://cloud.githubusercontent.com/assets/1178694/14577499/eccf2c76-0342-11e6-8128-b989f2973167.png)

**Comment by xtreme-gavin-enns** [comment]
I tried taking a shorter recording and now it says I can't upload a video file type :/

**Comment by xtreme-gavin-enns** [comment]
FYI if I zoom out all the way until I can't scroll sideways anymore the problem goes away, but I can't read the text anymore :( 

As soon as I zoom in even a little bit the jitter is back

**Comment by vito** [comment]
Have you tried this with Concourse 1.1? I think we just fixed that, at least the desktop equivalent - hopefully the fix applies to mobile too.

**Comment by vito** [comment]
Confirmed that this is fixed for me in 1.1 - reopen if it's still broken for you.
