### ISSUE TITLE
Pin resource version for task

### ISSUE THREAD

**Issue by fiftin** [concourse/concourse#3780]
## What challenge are you facing?

I use one resource in some tasks. And I want pin version of resource only for one tasks. Now I can't do this. And I have to create some of the same resources.

## What would make this better?

It will be good to have ability to pin resource version separately for each task which use it .

## Are you interested in implementing this yourself?

Yes

**Comment by vito** [comment]
What do you mean by 'now I can't do this?' Was this something you could do previously?

You can also pin on each `get` step: https://concourse-ci.org/get-step.html#get-step-version
