### ISSUE TITLE
Delete pipeline via the UI

### ISSUE THREAD

**Issue by pivotal-saman-alvi** [concourse/concourse#3783]
## What challenge are you facing?
When setting up test pipelines, it becomes aggravating to have to delete each one via fly.

## What would make this better?
It would be helpful if we could delete a pipeline (perhaps with a confirmation?) via the UI itself

**Comment by bencao** [comment]
Since pipeline delete is definitely a change to the pipeline itself, I feel it breaks the simplicity a little bit. 
Especially it makes the UI design asymmetric: If delete can be done via UI, should create/edit be possible via UI?
