### ISSUE TITLE
Resource check queue

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#3788]
Instead of checking resources synchronously we want to add them to a queue (table in the db). This way we get better visibility into what resource checks are happening, better de-duping of concurrent checks and allow for rate limiting.

**Comment by pivotal-jwinters** [comment]
We've been investigating a two component approach: `scanner` and `checker`

### scanner
The scanner is responsible for determining if a new `check` should be added to the database. It should be concerned with things like paused jobs/pipelines, pinned resources, disabled resources, check interval, etc... 

### checker
The checker is responsible for running any checks (and type checks) that get added to the database. The check will scan the table and grab a lock to run the check. If it can't get the lock it will simply retry next time it runs. The checker should run regardless of any preconditions that the scanner might care about.

**Comment by pivotal-jwinters** [comment]
One thing we need to keep in mind is the fact that the `resource_checks` table could get quite large. So we'll need to figure out how we're going to gc things.

**Comment by vito** [comment]
@pivotal-jwinters Should they just be marked as completed after the check is done and/or removed?

Or, could we track the queue time and reap anything queued before the `last_checked` value?

**Comment by pivotal-jwinters** [comment]
While working through this issue we've hit a bit of a wrinkle.

Ever since we introduced global resources, radar's behaviour has been a bit strange. Basically every `resource` still has its own check interval, but if two resources share the same `scope`, then only one will actually get the lock and run the check. This makes sense in the current context of all the things we need to run a check, however moving forward we want to remodel things a bit. 

In the context of our two component system (outlined above), the `scanner` will still interact at the `resource` level, but once we get to the `checker` we will have no more knowledge of which resource the check actually ties back to. We started thinking about how we could run a check with the actual resource:

> Since the `scope` doesn't actually know the `atc.Source` to run the check against, we'll need to store it in the `checks` table. This starts to look a LOT like a build `plan` for checks, so why not actually make it such.

This lead us down the path of [refactoring the exec package](https://github.com/concourse/concourse/pull/4000) so that we can add a `exec.CheckStep`. We are going to have to change a few more things along the way, but it seems like this is a pretty good path forward.

**Comment by vito** [comment]
Notes from IPM regarding the handling of missing versions for parent resource types:

* Let's have `fly check-resource` fail fast if the parent resource type has no version.
* Let's add `fly check-resource --recursive` which will recurse into the parent types and perform checks for them, and then check the specified resource.
* Then have `fly check-resource` print the command to run when it hits that error.

Also: be sure to not surface 'orange boxes' for missing resource type versions - just show a special message in the UI, since we expect this state to happen when a resource is first configured.

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta #4444

**Comment by kcmannem** [comment]
Some observations after deploying 5.6 with Lidar on our internal supported concourse env wings.

Looking at the graph below, the blue line splits time before and after lidar. We can see that CPU loads drops from ~45% to ~30%. And a great reduction on transactions/min from ~35k/min to ~25k/min.
![Screen Shot 2019-10-02 at 2 22 20 PM](https://user-images.githubusercontent.com/9054726/66159483-121b3800-e5f6-11e9-8b7a-f6b1d9a3bc50.png)

Something we also noticed is that the Web nodes now have less variance in the amount of queries they make, this is great progress towards making concourse scale horizontally a lot easier.
![Screen Shot 2019-10-02 at 2 33 20 PM](https://user-images.githubusercontent.com/9054726/66159509-23fcdb00-e5f6-11e9-818a-afa893610913.png)

Although the number of queries has decreased, its important to note that the aggregate amount of resource checks across all web nodes remains the same. :party:
![Screen Shot 2019-10-02 at 2 26 15 PM](https://user-images.githubusercontent.com/9054726/66159539-34ad5100-e5f6-11e9-9cdc-f29699620b8e.png)

The throughput from the perspective of DB has increased even though the amount of transactions has reduced.
![Screen Shot 2019-10-02 at 2 24 55 PM](https://user-images.githubusercontent.com/9054726/66159579-45f65d80-e5f6-11e9-88c7-7aee5d983461.png)

looking at the GC activity that we mentioned before (that we had to wait to see it kicking off), we can see that it indeed does what we wanted (after 6 hours, storage stabilized).
![Screen Shot 2019-10-03 at 10 19 33 AM](https://user-images.githubusercontent.com/9054726/66159606-59092d80-e5f6-11e9-9ea9-114be4b62b19.png)

**Comment by kcmannem** [comment]
Another set of observations from our internal supported concourse env hush-house. This set takes a closer look at how the go runtime is performing after Lidar is enabled.

We see a 1k (50%) drop in the amount of goroutines being spawned.
<img width="1031" alt="Screen Shot 2019-10-03 at 12 47 24 PM" src="https://user-images.githubusercontent.com/9054726/66159758-aab1b800-e5f6-11e9-812f-a0a80907920a.png">

Something we're still curious about is that GC for the go process increased a significant amount. Even though q75 is still very negligible after the increase, q100 the worst offenders is magnitudes greater.
<img width="915" alt="Screen Shot 2019-10-03 at 1 04 51 PM" src="https://user-images.githubusercontent.com/9054726/66159762-abe2e500-e5f6-11e9-8d4e-067cf63e858a.png">

<img width="919" alt="Screen Shot 2019-10-03 at 1 07 05 PM" src="https://user-images.githubusercontent.com/9054726/66159768-ad141200-e5f6-11e9-8953-efffc6be2952.png">
