### ISSUE TITLE
Namespace MDI Icons for icon configs

### ISSUE THREAD

**Issue by Templarian** [concourse/concourse#3789]
It was just brought to my attention that MDI was added as a dependency recently. We're really happy you enjoy the icons! Small suggestion reading your documentation below:

https://concourse-ci.org/resources.html#resource-icon

It may be a good idea to add a namespace/prefix to the icons. We have a lot of guidelines around which icons we add. Especially around brand icons where it may be more ideal to use https://simpleicons.org/ (ex: `si:` prefix could be used). Just want to set realistic expectations.

For instance we've seen this work great in Home Assistant. Their config requires one to prefix their `icon:` properties with `mdi:`. As you've already released it may be easier to detect a `:`, but maybe move in that direction for the future (or display a warning or auto-update with a prefix).

Example: https://www.home-assistant.io/docs/configuration/customizing-devices/#icon

I'm on Twitter `@Templarian` if you have any questions or want to know about things before a release makes it to NPM.

**Comment by vito** [comment]
Hey, thanks for the heads-up! :slightly_smiling_face: It sounds like this is just proposing we be less tightly-coupled to Material Design and explicitly declare whether it's Material Design via a known prefix such as `mdi:` so if we want to support other icon sets in the future we can add them as alternative prefixes. Does that sound right?

Makes sense to me. Ultimately we want these icon values to be coming from the developers that write Concourse resource types (if you're not familiar with Concourse, think of them like plugins), so we're adding it to the resource interface itself in concourse/rfcs#24 as part of the resource type's meta-information. I'll add a note to take this into account. :+1:

**Comment by Templarian** [comment]
Exactly. Yeah, basically we already have other third parties that only use MDI, which is awesome, but unfortunately that ends up with their users thinking the only way an icon can be added is through MDI.

This can be closed if it's already being tracked. 😃

**Comment by vito** [comment]
I've added namespacing to the RFC in the above commit. :+1: Thanks!
