### ISSUE TITLE
Programmable abort behaviour for tasks and resources

### ISSUE THREAD

**Issue by jdub** [concourse/concourse#379]
**Use case:**

I discovered a problem recently when I had reason to abort an execution of my in-development [Packer resource](https://github.com/jdub/packer-resource). Some Packer builders create resources outside the context of the local process tree / file system, such as launching an EC2 instance to build an AMI. While Packer handles SIGINT to clean up after itself, Concourse (ATC?) simply terminates the container. Thus, if a user aborts a build during a Packer run, AWS resources will be orphaned… and charged by the hour.

**Current state:**

@vito explained to me on Slack that resource containers are sent a TERM signal followed by a KILL signal 10 seconds later. This is not currently documented.

**Suggestion:**

While I pondered how one might configure signals and timeouts, @vito suggested a `cleanup` script, defined alongside `run` (referring to tasks). I think perhaps `abort` would be a better name, as `cleanup` implies it would be run at the end of every execution.

Similarly, an optional `abort` script could live alongside the `in`, `check`, and `out` scripts in a resource. My `abort` script would just run `killall ---signal INT packer`, neatly solving my use case.

**Comment by gowrisankar22** [comment]
@vito 
We currently miss the state of a concourse job in our influxdb in case the job times out. 
If concourse kills the job before the script reaches to influxdb write function(), no data is written.
Does it get a SIGTERM signal or any other signal which can be trapped?

**Comment by vito** [comment]
@gowrisankar22 Timeouts behave the same as aborting the build; your script should receive a `SIGTERM`. I'm not sure what you mean by influxdb write function - do you mean the event Concourse emits? Are you emitting to influxdb in a task or something?

**Comment by gowrisankar22** [comment]
@vito Actually we are using a script at the end of the each and every job to report the job status “success” or “failure” to influxdb. Actually during the job “timeout” the job was not reaching to a script which does the reporting of the job status. That’s why I wanted to check during the timeout script receives the SIGTERM We can do a bash trapped.. or do you have any better suggestion for my usecase ????

Do you also have plans to emit the concourse metrics via concourse itself(ex:my above usecase job status ) ???

**Comment by vito** [comment]
Concourse already emits those metrics if you enable the InfluxDB emitter:

https://concourse-ci.org/metrics.html#build%20finished

**Comment by gowrisankar22** [comment]
@vito Thanks for the info but these events are just emitted once - it will have some implications - if a single event is lost, it is lost...???

**Comment by vito** [comment]
@gowrisankar22 This is getting kind of off-topic. Please ask in the [forums](https://discuss.concourse-ci.org) instead.

**Comment by gowrisankar22** [comment]
@vito thanks 👍
