### ISSUE TITLE
Concourse git resource returns tags that are not on the specified branch

### ISSUE THREAD

**Issue by vivobg** [concourse/concourse#3794]
## Bug Report
When using the git resource, and specifying a tag filter and branch, the resource returns versions that are not on the specified branch.

**NOTE: PR available:** https://github.com/concourse/git-resource/pull/260

## Steps to Reproduce

To reproduce, use the following pipeline:
https://gist.github.com/vivobg/460715da8b4aed4f82b419477bd3bf7d

![image](https://user-images.githubusercontent.com/2729991/56817214-08b6c400-683d-11e9-9848-150f12bfd23e.png)
And for the git repo, initialise a new repo with a readme, and then run the following steps from the root of the repo to recreate the setup above:
https://gist.github.com/vivobg/c56c71e1e57a954f4833c510f76e7431

## Expected Results

The expected result is that only 
1.0.0.5
1.0.0.4
1.0.0.1
versions will be detected.

## Actual Results

1.0.0.5
1.0.0.4
1.0.0.3 <- should not appear
1.0.0.2 <- should not appear
1.0.0.1
are detected

## Additional Context

I already have a PR for the git-resource with a fix: https://github.com/concourse/git-resource/pull/260
I have built a custom resource with the fix and currently using it it my concourse templates with no negative impact and it correctly doesn't pick up the tags that are not on master

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? I don't think this has worked, looking at past versions of the resource

**Comment by xtremerui** [comment]
Hi thx for submitting the PR.

When you tag a commit in a branch, the tag references the commit. So when the branch got merged back (with the commit now in master), the tag is still valid even the branch is deleted later. 

I think in this case, IMHO `tag_filter` who fetched tags for master SHOULD include `1.0.0.2` and `1.0.0.3`. The fact that while you are in master and still be able to git co `1.0.0.2` or `1.0.0.3` indicates those are valid tags in the branch.

**Comment by vivobg** [comment]
In the use case given above, the commits are rebased on top of master, which results in new commits being created, with the old commits still hanging off on the (deleted) branch, because of the tags pointing at them. The tagged commits are not part of master, only their tagless copies created by the rebase. As such, they should not be returned when a master branch filter is specified.

I also noticed that when running `tags=$(git tag --list "$tag_filter" --sort=creatordate --contains $ref)` locally, with $ref=1.0.0.1, I get all 5 tags, but if I specify `$ref=1.0.0.2` or `1.0.0.3`, I only get these 2 tags, but not `1.0.0.4` or `1.0.0.5`, which results in a dead-end. Passing `--merged master` ensures `1.0.0.2` and `1.0.0.3` are never returned.

**Comment by xtremerui** [comment]
I noticed there is a difference between your example and mine, which is you rebase master to branch first then merge the branch back to master. In this case yes the commit are recreated with different hash and I agree a `--merged` would help here.

Will merge the PR. Thx for the fix!
