### ISSUE TITLE
git push --force make concourse to stop detect any commits

### ISSUE THREAD

**Issue by kwladyka** [concourse/concourse#3799]
## Bug Report

Concourse stop detect changes after `git push --force` for first commit.

Why does it matter? Because first commit is usually the one with many changes to start the repo.

## Steps to Reproduce

1) make empty repo
2) add 1 commit to the repo
3) `fly set-pipeline` to watch the git repository by concourse git resource.
4) Unpause pipeline, let it consume first commit.
5) change commit by `git commit --amend --no-edit`
6) `git push --force`

It happen only with first commit.

PS 2,3 order doesn't matter.

**## Workaround**

How I deal with it?

git commit -m "init empty" --allow-empty

## Actual Results

Any new commit will be not detected. Only one way to unblock concourse is to do `fly destory-pipeline` and `fly set-pipeline`.

## Expected Results

1) I can use `git push --force` without make concourse unable to detect any commits for resource.

2) If you don't want to fix it, consider adding solution with `--alow-empty` to the doc and inform users about this issue and best practice.

## Version Info

This issue happen about a year ago and is happening for this days. I am using concourse `5.1.0` now.

**Comment by marco-m** [comment]
It is not clear to me at which point, in the 4 steps sequence above, you issue fly set-pipeline. If you could edit the text with this reference it would help to reason about the behavior.

**Comment by kwladyka** [comment]
Hmm not sure about what you are asking.

If I do `git push --force` changing first commit in git, then concourse will stuck with this resource forever. There is no way to fix it. I need to destroy pipeline and create it again.

**Comment by marco-m** [comment]
To use Concourse, sooner or later you need to set a pipeline that refers to this repository. I was asking when you are issuing fly set-pipeline.

**Comment by kwladyka** [comment]
Hmm I think there is some misunderstanding, but not sure where.

1. I set pipeline in concourse with git resource
2. git push --force on first commit
3. concourse stuck with this resource.

I don't have issue with set-pipeline. I have issue with detecting new commits in resource in pipeline after git push --force.

**Comment by marco-m** [comment]
Are you sure the sequence is chronologically right ? You set the pipeline and then you create the repo (1. make empty repo) ?

**Comment by kwladyka** [comment]
Sorry, I did update.

**Comment by kwladyka** [comment]
Issue still exist.

**Comment by kwladyka** [comment]
.

**Comment by MikeC-BC** [comment]
issue still exists
