### ISSUE TITLE
Notes on builds

### ISSUE THREAD

**Issue by zrob** [concourse/concourse#380]
It would be great to be able to add notes to builds.  This would allow us to comment on why we think there are failures across a series of builds as well as maintain context for when different devs look at failed builds.

**Comment by vito** [comment]
We'll probably start on this after Teams is done, which is around the time we'll start collecting user information (i.e. so that we can know you're @vito on GitHub who left the comment).

**Comment by zrob** [comment]
Closing in favor of #476
