### ISSUE TITLE
File perms are not preserved in `fly execute`

### ISSUE THREAD

**Issue by Callisto13** [concourse/concourse#3803]
## Bug Report

Locally `execute`d builds often fail with:
```
Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:345: starting container process caused \"exec: \\\"cbug/dummy\\\": permission denied\"\n","Handle":"","ProcessID":"","Binary":""}
```

On my machine:
```
 cbug > ll ci
total 16
drwxr-xr-x  4 pivotal  staff  128 Apr 29 16:15 .
drwxr-xr-x  4 pivotal  staff  128 Apr 29 16:15 ..
-rwxr-xr-x  1 pivotal  staff   21 Apr 29 15:58 dummy
-rw-r--r--  1 pivotal  staff  173 Apr 29 16:15 dummy.yml
```

Inspection of the bind-mounted volume after a privileged build shows that permissions and ownership were not preserved\* and therefore the `run.path` executable could not be called.

On the worker both uploaded files have `0666` perms and are owned by `root`:
```
worker/28fe13ea-1333-497c-ac89-b6cb2eb51ab2:/var/vcap/data/worker/work/volumes# ll ./live/f6301c44-0ae1-479d-6eeb-4fb1d544aa1f/volume/ci/
total 8
drwxrwxrwx 1 root root  28 Apr 29 15:16 ./
drwxrwxrwx 1 root root  24 Apr 29 15:16 ../
-rw-rw-rw- 1 root root  21 Apr 29 14:58 dummy
-rw-rw-rw- 1 root root 173 Apr 29 15:15 dummy.yml
```

The parent directory, `ci`, is `0777`:
```
worker/28fe13ea-1333-497c-ac89-b6cb2eb51ab2:/var/vcap/data/worker/work/volumes# ll ./live/f6301c44-0ae1-479d-6eeb-4fb1d544aa1f/volume/
total 4
drwxrwxrwx 1 root root  24 Apr 29 15:16 ./
drwxr-xr-x 1 root root  72 Apr 29 15:16 ../
drwxrwxrwx 1 root root  28 Apr 29 15:16 ci/
```

While for a successful run, the Volume has been laid down with `0755` and the correct owner:

```
worker/28fe13ea-1333-497c-ac89-b6cb2eb51ab2:/var/vcap/data/worker/work/volumes# ll live/c6477ce5-a3f6-48a0-5dfa-c8bea76123ec/volume/ci
total 8
drwxr-xr-x 1 pivotal staff  28 Apr 29 15:16 ./
drwxr-xr-x 1 pivotal staff  24 Apr 29 15:15 ../
-rwxr-xr-x 1 pivotal staff  21 Apr 29 14:58 dummy*
-rw-r--r-- 1 pivotal staff 173 Apr 29 15:15 dummy.yml
```

And the parent `ci` is `0755`:
```
worker/28fe13ea-1333-497c-ac89-b6cb2eb51ab2:/var/vcap/data/worker/work/volumes# ll live/c6477ce5-a3f6-48a0-5dfa-c8bea76123ec/volume/
total 4
drwxr-xr-x 1 pivotal staff  24 Apr 29 15:15 ./
drwxr-xr-x 1 root    root   72 Apr 29 15:16 ../
drwxr-xr-x 1 pivotal staff  28 Apr 29 15:16 ci/
```

We see this happen at a rate of approximately 1 in 6 `fly execute`s.
We see this on priv and unpriv execs.
We have not seen it happen (yet) through a pipeline build.

&nbsp;

 \* _I am aware that ownership would change in the case of unprivileged containers._

## Steps to Reproduce

[Repro Gist](https://gist.github.com/Callisto13/400121077cfaf0849c8577d2a696f927)

## Expected Results

The file should have the correct permissions and the `execute` should succeed.

## Actual Results

The above `permission denied` failure.

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Did this used to work? Yes

**Comment by Callisto13** [comment]
bump @vito any chance of this getting look at? it's a very annoying bug

**Comment by vito** [comment]
The gist you've linked is missing a `chmod +x ci/dummy`, but after making that correction it seems fine for me:

```
root@6d0c2601-731c-4f19-5769-bdf94dfff35e:/tmp/build/e55deab7# ls -al cbug/ci/
total 8
drwxr-xr-x 1 root staff  28 May 15 12:37 .
drwxr-xr-x 1 root staff   4 May 15 12:37 ..
-rwxr-xr-x 1 1000  1000  20 May 15 12:32 dummy
-rw-r--r-- 1 1000  1000 172 May 15 12:37 dummy.yml
```

It's passing in a loop, and both file permissions look correct. I'm not sure how they ended up with 0666 permissions on your worker, and why it only happens ~1 in 6 times. Maybe something is wrong with one of your workers?

I would recommend using `fly intercept` for debugging the file permissions; should be easier than poking around on the worker itself.

**Comment by Callisto13** [comment]
@vito it happens on all our workers, and I have looked at file perms using both intercept and at the volumes on the workers.

(and yeh sorry about the forgotten `+x`)

We hit this several times a day, even after recreating the workers today, and the incidence seems to have increased; my last 5 consecutive runs hit this.

**Comment by vito** [comment]
I had it running all morning and none of them failed. 😕 This is also something our CI would have probably caught by now if it was as simple as the issue describes. All I can suggest at this point is poking around your deployment to see if anything looks suspicious, and/or try to reproduce in a smaller deployment (i.e. `docker-compose`).

**Comment by Callisto13** [comment]
curious 🤔 okay we will look further.

**Comment by Callisto13** [comment]
@vito update on the case!

So our concourse has 4 Linux workers and 1 Windows worker. Just for lolz we removed our Windows worker... and the problem disappeared (safe after 100 runs). We put it back and hit the problem again on the second run. We have repeated enough times to be sure.

Does your CI have envs with a Linux/Windows mix? This feels completely bizarre to us, do you have any idea what could be going on?

**Comment by vito** [comment]
@Callisto13 Ha, funnily enough we *do* have a Linux/Windows mix in our CI. But we don't run `fly execute` all that often.

@pivotal-jwinters Here's a theory: when we upload user artifacts for `fly execute`, how do we pick the worker that the artifact's volume goes on? Maybe there's a chance that we pick the Windows worker, resulting in the file permissions being stripped?

**Comment by yulianedyalkova** [comment]
@vito did you get a chance to look into this?

**Comment by vito** [comment]
@yulianedyalkova I've placed this on the top of the Core backlog. 👍
