### ISSUE TITLE
Increase highlighting of highlighted-line

### ISSUE THREAD

**Issue by tvon** [concourse/concourse#3805]
## What challenge are you facing?

When sharing a link to a specific line or a selection of lines the timestamps stand out but the related log lines blend in.

## What would make this better?

The UI background is `#3d3c3c`, changing the `.timestamped-line.highlighted-line` background to `#2d2c2c` (or some other color) is subtle but helps to make the relevant lines "pop" a bit more.

Before:
![Screen Shot 2019-04-30 at 12 36 20 AM](https://user-images.githubusercontent.com/25628/56941118-5010af00-6ae0-11e9-98e3-4099411ac50a.png)

After:
![Screen Shot 2019-04-30 at 12 36 27 AM](https://user-images.githubusercontent.com/25628/56941111-46874700-6ae0-11e9-891a-5e4d58e438e5.png)

## Are you interested in implementing this yourself?

I would take some familiarization with the UI code but I could figure it out if there is interest.  Or if someone with the domain knowledge wants to bang it out... whatever works.

**Comment by vito** [comment]
@tvon I like it! I've marked this as 'good first issue' - [`CONTRIBUTING.md`](https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md) should be a good start if you're interested in PRing it. :+1:

**Comment by cirocosta** [comment]
Thanks, @tvon ! https://github.com/concourse/concourse/pull/3866
