### ISSUE TITLE
Health field for `api/v1/info/creds` missing when configured with Kubernetes

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3807]
Hey,

@mhuangpivotal and I noticed that when using the Kubernetes credential manager, the `health` field is lacking from the `api/v1/info/creds` response.

https://github.com/concourse/concourse/blob/0ecb0381931e47ed9ac77091bdf0a92c21c2113b/atc/creds/kubernetes/manager.go#L21-L28

https://github.com/concourse/concourse/blob/0ecb0381931e47ed9ac77091bdf0a92c21c2113b/atc/creds/kubernetes/manager.go#L46-L48

In https://github.com/concourse/concourse/issues/2216 is where we did the initial implementation of `health` for other credentials managers (like Vault), but in the commit that closed such issue (https://github.com/concourse/atc/compare/e77446374a838ac81bbc80a839d17df69e6eb375...2e90c26e6139f9afe471d6ab6203881a5462d0fd) we explicitly added a `TODO` for implementing the same for Kubernetes, which was never done.

Having such `health` fields would be very important for those scenarios where you're not sure whether you have configured the right access control for `web` to communicate with Kubernetes.

Thanks!

**Comment by xtremerui** [comment]
AFAIK, there is no specific health endpoint for secrets. Maybe [getting secret list]( https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#list-secret-v1-core) ?

Is there any better option?

**Comment by cirocosta** [comment]
hmmmm that's a good point, it indeed has no `health` 🤔  

Right now we don't even grant the `List` action to the `web` ServiceAccount (as we only perform `GET`s directly) - see 
https://github.com/helm/charts/blob/4cf31427ec68a4463f838ba5c6b1a6f72d2746f3/stable/concourse/templates/web-role.yaml#L13-L16)

If we go with `list`, should we then try performing a `list` over *each* team namespace? As it could be that the operator forgot to allow the `web` role to perform such actions in such namespace.

Wdyt?

Thanks!

**Comment by xtremerui** [comment]
Ideally we might want an endpoint that allows concourse to pull k8s secret "service" status without involving any concourse logic (like going through teams here). For example, this one [ComponentStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#componentstatus-v1-core) sounds good. But I am not sure if k8s secret counts as a "component" or not.
