### ISSUE TITLE
Add test to ensure that one-off builds are possible having Kubernetes credential management

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3809]
Hey,

@mhuangpivotal and I noticed that there are no tests covering the case where a one-off build needs to have variables interpolated, a feature that is advertised to work with the other credential providers.

Thanks!

**Comment by zoetian** [comment]
Dev Note:

@pivotal-bin-ju and I spent all day investigated on how the credential manager gets selected and verified the secret in the codebase (mostly using dlv). We also set up k8s pods for concourse on local to run one-off build script. 

So on local, we tested with `fly -t local execute -c $one-off-test-script`

[Useful links] 
https://github.com/concourse/docs/pull/213 (doc to understand k8s CM)
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/

Next Step:
1) Research on how to work with k8s credentials (we intended to try out the below):
- `kubectl apply -f $secret-yml-file`

2) if the k8s pods can work with the credential,  add the tests in https://github.com/concourse/concourse/blob/master/atc/creds/kubernetes/kubernetes_test.go 
  - if no namespace/ team to read from
  - if has namespace/ team to read from:
      - can read secret
      - cannot read secret
  - consider for one-off build:
     - only look in the team path

**Comment by taylorsilva** [comment]
Created tests in topgun to cover this use-case: https://github.com/concourse/concourse/pull/4008
