### ISSUE TITLE
Change Task Caches to be Worker Agnostic

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#3811]
Following up on #3607, We need to remove the ownership of task_caches from runtime.

Currently we keep  track of which worker contains a certain task_cache. But if workers become a runtime concern, Core should keep track of which task_caches are available and should be invisible to runtime. Continuing our move to the "artifact" abstraction, we should move this responsibility over to core. This will mean that task_caches can no longer be worker specific. This will cause implementation changes where task_caches may be cached across multiple workers in the pool.

**Comment by ddadlani** [comment]
Part 1 of this issue is to separate out the functionality of `worker_task_caches` into `task_caches` and `worker_task_caches`, similar to `resource_caches` and `worker_resource_caches`. Then we should be able to remove `worker_task_caches` as part of the work for #3607.

**Comment by ddadlani** [comment]
@xtremerui You can merge into master, we rebase from that regularly and it shouldn't be too hard to do at this stage. 

Thank you!
