### ISSUE TITLE
Concourse Page Reloads on clicking a failed attempt tab

### ISSUE THREAD

**Issue by manali14** [concourse/concourse#3814]
## Bug Report

For any task in pipeline job, if u specify attempts parameter (https://concourse-ci.org/attempts-step-modifier.html), and if you click on any of the previous failed attempts, the page reloads itself.

## Steps to Reproduce

- Create a task with attempts parameter set to greater than 1.
- Add task definition such that it will fail everytime.
- Click on failed attempt.

## Expected Results

- It should show logs of that attempt rather than reloading the page.

## Actual Results

- The page reloads.

## Version Info

* Concourse version: v5.1.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Infrastructure
* Browser (if applicable): Chrome
* Did this used to work? Yes, used to work on previous versions

**Comment by vito** [comment]
Confirmed - prioritizing in UX backlog.

@pooja-dhupar Thanks for the workaround!

**Comment by univ0298** [comment]
Unfortunately Shift is not available on iOS/Safari and presumably other cellphone browsers
