### ISSUE TITLE
Add alternate Compression algorithms

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#3819]
I've experimented with using zstd as a compression algorithm instead of gzip while streaming in and our with baggageclaim. From my totally scientific findings, its worth putting effort into. TLDR is its about 3x faster while maintaining the same compression ratio. For the test I compressed the Golang docker image rootfs. @cirocosta pointed out that we should be streaming inputs in parallel as this will help in scenarios like strabo, the only disadvantage to this was killing the worker by decompressing too much. This would not be a problem with Zstd or lz4. It was also pointed out that the rabbitMQ team would rather not have compression at all as they've seen it use too much CPU and since network is cheap, they wanted to experiment if it posed better results. This would be a good resolution for them as well.

Results:
**With ZSTD**
```
root@3bd4d72c2e4b:/tmp/test# time go run too_fast.go
&{/bin/tar [tar --exclude=./sys --exclude=./proc -C /dev/fd/3 -cf - .] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}

real	0m14.181s
user	0m9.600s
sys	0m3.750s

-rw-r--r--  1 root root 287M May  4 21:12 wholeworld.tar.zstd
```
`too_fast.go` is just `stream_in_out_linux.go` with a few modifications to use zstd.

**With GZIP**
```
root@3bd4d72c2e4b:/tmp/test# time tar --exclude=/sys --exclude=/proc --exclude=/tmp -czf wholebadworld.tar.gz /

real	0m45.507s
user	0m36.370s
sys	0m2.880s

-rw-r--r--  1 root root 297M May  4 21:16 wholebadworld.tar.gz
```

cc @ddadlani

**Comment by kcmannem** [comment]
the `stream_in_out_linux.go` modified with zstd code https://gist.github.com/kcmannem/c823da052f80cf20b3536d4c270d7f31

**Comment by cirocosta** [comment]
ooooh nice! Is `zstd` the one that has no differences in terms of expected flags? 

Also, I hope their dual license (BSD & GPLv2) isn't a problem 😬 Not sure how dual licensing works.

Looking forward to seeing this in flight!

**Comment by kcmannem** [comment]
@cirocosta lz4 is the one with no difference. I chose to go with zstd since its fast enough and we can package it like a regular go dependence. With lz4 we'd have to ship it as a bosh release or expect it to be installed on the machine if your just use the binary

**Comment by cirocosta** [comment]
Oh, I see.

> With lz4 we'd have to ship it as a bosh release or expect it to be installed on the machine if your just use the binary

Another option is going with the same approach that we take for `btrfs` - using `blobs` (https://github.com/concourse/concourse-bosh-release/blob/master/config/blobs.yml#L1-L4 and https://github.com/concourse/concourse-bosh-release/tree/master/packages/btrfs_tools)

Thanks!

**Comment by kcmannem** [comment]
@vito any reason to keep gzip compression around and allow a choice? I can't think of any scenarios.

**Comment by vito** [comment]
@kcmannem If it's low enough maintenance I'd like to support both, just from the stance that Baggageclaim is a generic API and `gzip` is extremely common.

**Comment by kcmannem** [comment]
@ddadlani and I ran through a test where a pipeline streamed over a bunch of resources(heavy docker images) to a single task. Heres the initialization times we saw.

| using Zstd  |  using Gzip | Improvement |
| ------------- | ------------- | ------------- |
| 1m 46s  |  6m 36s | 4m 50s |
| 1m 40s  |  4m 40s | 3m |
| 3m 5s  |  7m 30s | 4m 25s |
| 3m 19s  |  8m 12s | 4m idk s |

Notes:
1. for the third/fourth test, the network was throttled to about a third of the bandwidth other tests had.
2. the differences in time between builds may be influenced by the placement strategy being set to volume-locality. We did not notice any meaningful changes in cpu/memory usage.

**Comment by kcmannem** [comment]
@ddadlani and I ran through a test where a pipeline streamed over a bunch of resources(heavy docker images) to a single task. Heres the initialization times we saw.

| using Zstd  |  using Gzip | Improvement |
| ------------- | ------------- | ------------- |
| 1m 46s  |  6m 36s | 4m 50s |
| 1m 40s  |  4m 40s | 3m |
| 3m 5s  |  7m 30s | 4m 25s |
| 3m 19s  |  8m 12s | 4m idk s |

Notes:
1. for the third/fourth test, the network was throttled to about a third of the bandwidth other tests had.
2. the differences in time between builds may be influenced by the placement strategy being set to volume-locality. We did not notice any meaningful changes in cpu/memory usage.

**Comment by cirocosta** [comment]
woow that's pretty cool!

**Comment by cirocosta** [comment]
woow that's pretty cool!

**Comment by kcmannem** [comment]
Here are what the CPU usage graphs looked like:

With GZIP:
![image](https://user-images.githubusercontent.com/9054726/59617988-5b9e5080-90f5-11e9-95eb-0042bbe5e6d8.png)

With ZSTD:
![image](https://user-images.githubusercontent.com/9054726/59618009-6658e580-90f5-11e9-8e98-22ee3684c69c.png)


It looks like GZIP has sustained CPU usage over a longer time, but has a lower peak, while zstd is more bursty over a shorter time period.

**Comment by kcmannem** [comment]
Here are what the CPU usage graphs looked like:

With GZIP:
![image](https://user-images.githubusercontent.com/9054726/59617988-5b9e5080-90f5-11e9-95eb-0042bbe5e6d8.png)

With ZSTD:
![image](https://user-images.githubusercontent.com/9054726/59618009-6658e580-90f5-11e9-8e98-22ee3684c69c.png)


It looks like GZIP has sustained CPU usage over a longer time, but has a lower peak, while zstd is more bursty over a shorter time period.
