### ISSUE TITLE
Kubernetes credential manager regression - malformed secret path

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3821]
## Bug Report

After the merge of #3628 , the Kubernetes credential manager tests (https://github.com/concourse/concourse/blob/37dd02b20741a9c90b362f3f4edeb918a674caa9/topgun/k8s/kubernetes_creds_mgmt_test.go) started failing:

```
running: kubectl create secret generic foo --namespace=topgun-k8s-cm-664743-1-main --from-literal=value=bar
secret/foo created
running: kubectl create secret generic caz --namespace=topgun-k8s-cm-664743-1-main --from-literal=baz=zaz
secret/caz created

fly -t concourse-topgun-k8s-1 set-pipeline -n -c ../pipelines/minimal-credential-management.yml -p pipeline
jobs:
  job unit has been added:
+ name: unit
+ plan:
+ - task: run
+   config:
+     platform: linux
+     image_resource:
+       type: registry-image
+       source:
+         repository: busybox
+     run:
+       path: /bin/sh
+       args:
+       - -c
+       - |
+         echo plain-secret=((foo))
+         echo nested-secret=((caz.baz))
```

There might be something in the caching logic that is not working for that credential manager.

## Steps to Reproduce

Run the credential manager test. 

## Expected Results

Continue working.

## Actual Results

Fails.

## Aditional context

I didn't go through the new caching logic, but it seems like the way that paths are passed to `Get` is not working correctly, at least when caching is not enabled. It might be that it works with caching, but I didn't test that yet. 

## Version Info

* Concourse version: master (https://github.com/concourse/concourse/commit/7b846eeac9a5ca232d521f25b2c0c410e72e02de)
* Deployment type (BOSH/Docker/binary): Kubernetes
* Did this used to work? yes

**Comment by ralekseenkov** [comment]
looking into it
