### ISSUE TITLE
Pipeline dashboard incorrect view for aborted jobs

### ISSUE THREAD

**Issue by LedRevolver** [concourse/concourse#3822]
## Bug Report

In the dashboard view of a concourse pipeline, when a job is aborted quickly after the job is started (before the first step can occur) in the UI the build number will stay in a state of pending even after verifying that the job is aborted and shows the correct state in the fly CLI . It is expected that the dashboard show the job as aborted. What occurs is that the dashboard shows the job as pending (moving stripes) and then colored by the last build status (errored, failed, aborted, or succeeded).

## Steps to Reproduce

Run a build and immediately cancel it, then view the status in the web-ui (it will say pending) then verify it was aborted in the fly-CLI.

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary):binary
* Infrastructure/IaaS: AWS EC2
* Browser (if applicable): Firefox & Chrome
* Did this used to work? unknown

**Comment by pivotal-jamie-klassen** [comment]
@pivotal-jwinters - those 'running' bars show up whenever there is a 'nextBuild'
field in the `/api/v1/jobs` JSON object corresponding to the job in question.
Ok if I tag this `core/api`?

**Comment by vito** [comment]
I think this was fixed by #3566 - should be in 5.2!
