### ISSUE TITLE
Builds fail with pq: insert or update on table "resource_cache_uses" violates foreign key constraint "resource_cache_uses_container_id_fkey"

### ISSUE THREAD

**Issue by analytically** [concourse/concourse#3831]
We're seeing 

```pq: insert or update on table "resource_cache_uses" violates foreign key constraint "resource_cache_uses_container_id_fkey"```

This fails some of our builds.

## Version Info

* Concourse version: 5.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Did this used to work? Yes

**Comment by lrstanley** [comment]
Noticing this as well, with v5.7.0.

**Comment by lrstanley** [comment]
Looks like this happened right around the same time that we had a network issue, and our ephemeral workers disconnected/reconnected, and the ATC GC'd everything that were on those workers. Sounds like a worker disappearing, some tasks can be caught in a weird state and don't always return the "worker went away" message.
