### ISSUE TITLE
Inconsistent resource resolution when a single resource is pinned

### ISSUE THREAD

**Issue by kmdouglass** [concourse/concourse#3832]
## Bug Report

I have discovered an inconsistency in the behavior of the mechanism that determines the versions of the inputs to a build when at least one input is pinned to a particular version. I noticed it in a small experimental pipeline that I created to test the release process for an app. In short, the resource versions that are used as inputs to the build depend on which resource is pinned, but not in a way that is consistent with the order in which new versions of the resources are created within the pipeline.

The inconsistency suggests that resource pinning in a pipeline can result in unpredictable versions of input resources to a build.

The example pipeline is pictured below. It is comprised of four resources (semver, git, and two S3 resources) and three jobs:

1. **bump-rc** - Bump the release candidate number in the semver. Its inputs are a semver resource and git resource. Its output is the updated semver.
2. **make-me-some-pizza** - The app is "built" in this job. Its inputs are the semver resource and the git resource. Its output is the app artifact which is uploaded to S3 in a bucket for release candidates.
3. **ship-it** - The app is "released" in this job. The job is manually triggered. The artifact from the previous job is moved from the release candidate bucket to the final release bucket. In addition, the patch number of the semver is bumped and the release candidate number is reset to 0. Its inputs are the semver resource, the git resource, and the S3 resource. Its output is the final artifact uploaded to the final release bucket.

![image](https://user-images.githubusercontent.com/3697676/57377012-a72e1800-71a1-11e9-8cfd-4a30e04f9f4a.png)

The development cycle proceeds as follows:

- Commits are made to the git repository. Each commit triggers the `bump-rc` job, which bumps the rc number of the semver.
- Each time the semver version changes, it triggers the `make-me-some-pizza` job. This produces an artifact for each rc that is put in the `pizza.s3` resource.
- After multiple rc's are created the release engineer decides that one should be the final release. **(S)he pins the version of just one of the git resource, the semver resource, or the `pizza.s3` resource, then launches a build in the `ship-it` job.**
  
At this point, I observe these outcomes depending on which resource is pinned:

1. If the git resource is pinned, then the corresponding versions of the semver and `pizza.s3` resources are pulled into the ship-it job. For example, if commit `abcdef` produced semver `1.2.3-rc.5` and `pizza-1.2.3-rc.5.txt`, then these versions of the resources will be used as inputs to the `ship-it` job. This suggests that Concourse can correctly resolve which versions of resources to use in a job when only one resource is pinned.
2. If the `pizza.s3` is pinned to the version that contains `pizza-1.2.3-rc.5.txt`, then latest versions of the git resource and semver are used is inputs, which may or may not correspond to commit `abcdef` or semver `1.2.3-rc.5`. This means that Concourse can only resolve *downstream* artifacts (ones that are created after the pinned resource), but not *upstream* artifacts.
3. If the semver resource is pinned to `1.2.3-rc.5`, then the commit `abcdef` and the artifact `pizza-1.2.3-rc.5.txt` are used as inputs to the `ship-it` job. This violates the hypothesis that only *downstream* versions of resources are resolved because the git resource is created upstream of the semver resource.

### Summary

To summarize, it seems that I cannot easily predict which of the three resources I should pin to the `ship-it` job to ensure that the corresponding versions are used as inputs.

If I pin the git resource or the semver resource, then the corresponding versions of the other two resources are used as inputs to the `ship-it` job. If I pin the `pizza.s3` resource, then the latest versions of the other two resources are used as inputs.

## Steps to Reproduce

The pipeline configuration and task configuration files are located
at https://gist.github.com/kmdouglass/85b17b999b93266775aca4b86c2656a3

1. Create a new git repo called `concourse-release-test` with the following directory structure:

```sh
$ tree concourse-release-test
concourse-release-test/
└── ci
    ├── pipelines
    │   └── concourse-release-test-template.yml
    └── tasks
        ├── delivery.yml
        └── pizza.yml
```
2. Set the pipeline with `fly --target=foobar set-pipeline --pipeline=concourse-release-test --config=ci/pipelines/concourse-release-test-template.yml`
3. Make an empty commit `git commit --allow-empty -m "delicious"`, push the commit, force a check on the git resource in the pipeline and allow the `bump-rc` and `make-me-some-pizza` jobs to run to completion.
4. Repeat step 3 two more times. You should now have semvers `0.1.0-rc1`, `0.1.0-rc2`, and `0.1.0-rc3`.
5. Pin the version of the semver that corresponds to `0.1.0-rc2`.
6. Launch a build in the `ship-it` job. Note that the commit from the git resource and the artifact on `pizza.s3` that correspond to the `0.1.0-rc2` semver are used as inputs.
   
Now, repeat steps 3 through 6 above two more times, but instead of pinning the semver resource in step 5, pin the git resource and the `pizza.s3` resource. Each time, be sure to pin a version of the resource that is not the latest version. When pinning the `pizza.s3` resource, note that the latest versions of the git and semver resources are used, not the versions that produced the pinned artifact in `pizza.s3`.

## Expected Results

I expect that either

1. the unpinned versions of resources should always resolve to the corresponding version of the pinned resource, or
2. that the versions of the unpinned resources should always resolve to the latest versions, regardless of what was pinned.
   
## Actual Results

I observe both behaviors described above depending on which resource is pinned.

## Additional Context

I believe that issue #3602 is likely related.

@marco-m @wagdav this is the issue we discussed at standup.

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): N/A
* Did this used to work? No

**Comment by vito** [comment]
One thing that may be problematic is that `bump-rc` job will always have two versions of `version` associated with a given commit: one for the *previous* version (via the `get: version`), and another for the `put: version`.

Another way to write `bump-rc` to avoid this issue is by just having a single `put` step that does an in-place bump:

```yaml
jobs:
  - name: bump-rc
    plan:
      - get: concourse-release-test.git
        trigger: true
      - put: version
        params: { pre: rc }
```

...which is actually how the `put` step has been working in your example, as you're missing a `file: version/version` param.

Does the version selection work as expected with the `get` step removed?

Either way I'll be curious to see how the new algorithm handles this.

**Comment by kmdouglass** [comment]
Thanks for the fast reply, @vito !

You're right that `get`ing the `version` semver resource is not necessary, so I removed it from the `bump-rc` job as suggested. The results are still the same. Assuming I have these three groups of resources:

- Commit: abc, version 0.1.0-rc.1, pizza-0.1.0-rc.1.txt
- Commit: def, version 0.1.0-rc.2, pizza-0.1.0-rc.2.txt
- Commit: ghi, version 0.1.0-rc.3, pizza-0.1.0-rc.3.txt

Then pinning one of them produces the following results in the `ship-it` job:

*Pin commit def*: version 0.1.0-rc.2 and pizza-0.1.0.-rc.2.txt used as inputs to `ship-it`
*Pin version 0.1.0-rc.2*: commit def and pizza 0.1.0-rc.2.txt used as inputs to `ship-it`
*Pin pizza-0.1.0-rc.2.txt*: commit ghi and version 0.1.0-rc.3 used as inputs to `ship-it`

So pinning the git resource or the semver resource produces the expected resolutions of the inputs in the `ship-it` job, but pinning the `pizza.s3` resource does not.

Are my expectations wrong, or is this a bug in the current scheduler?

**Comment by vito** [comment]
@kmdouglass Your expectations sound correct. I think I'll keep this open as acceptance criteria for #3602 since we've already got this in flight - I'll try and reproduce it with the old algorithm and see that the new algorithm fixes it. Thanks for the details!

**Comment by kmdouglass** [comment]
Thanks @vito . I appreciate the feedback. Let me know if I can help.

**Comment by vito** [comment]
Just confirmed that the new algorithm fixes the inconsistent version selection. Here's a `shipit` build from when I pinned the `pizza.s3` input to `rc.2` - the commit and version are correct:

![image](https://user-images.githubusercontent.com/1880/74982207-ad744480-5401-11ea-883e-4df1820fce77.png)

One thing to note is that with the new pinning behavior this sort of testing flow behaves a bit different than what you might expect from before. Pinning now converges all of the jobs on the pinned version, so when I pinned e.g. the git repo or the version input, jobs downstream of the pinned version would automatically run if they had `trigger: true` configured. This didn't actually affect the testing of the inconsistent version selection, just thought I'd mention it.

(Also this was all contingent upon fixing `bump-rc` to not have a `get: version` step.)

**Comment by vito** [comment]
Follow-up to this...:



> One thing to note is that with the new pinning behavior this sort of testing flow behaves a bit different than what you might expect from before. Pinning now converges all of the jobs on the pinned version, so when I pinned e.g. the git repo or the version input, jobs downstream of the pinned version would automatically run if they had `trigger: true` configured. This didn't actually affect the testing of the inconsistent version selection, just thought I'd mention it.

We think this is pretty odd behavior and we're going to fix it with https://github.com/concourse/concourse/issues/5220

**Comment by kmdouglass** [comment]
Thanks a lot @vito . A lot of people are going to be happy to see this :)

**Comment by vito** [comment]
And as another follow-up, we decided to back out the change that led to the aforementioned "odd behavior" altogether, since it's not completely necessary for the new algorithm and was initially done as an optimization: https://github.com/concourse/concourse/issues/5274
