### ISSUE TITLE
Sidebar feedback round 1

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3834]
Follow-up to https://github.com/concourse/concourse/pull/3829.

Feedback 1: in the open state, I feel like the toggle button should feel more 'connected' to the sidebar - note the different background color:

![image](https://user-images.githubusercontent.com/1880/57383528-fada3a80-717c-11e9-8b27-a81643744c39.png)

This is more pronounced when the pipeline is paused:

![image](https://user-images.githubusercontent.com/1880/57383479-e302b680-717c-11e9-9e10-58fbc1c15d91.png)

Feedback 2: the 'selected/active' border feels a little too strong/eye-catching. For example, it's stronger than the active border for groups:

![image](https://user-images.githubusercontent.com/1880/57388453-2f9ebf80-7186-11e9-9d50-ec5d5f07c386.png)

Maybe we could try just changing the background color of the active rows?

Feedback 3: I ended up expecting the sidebar to stick open after a refresh. I think I feel this way  because it stays open while navigating around.

Feedback 4: when viewing a job, I expected the sidebar to have the job's pipeline marked 'active' (and the team sub-tree to be expanded).

Feedback 5: we may want to make the full width of each row clickable, so that it's easier to hover between pipelines with different name lengths. Right now I have to click the text itself. Being able to scan vertically and have the background color indicate the active target would feel nicer. This is already the case for the team expand/collapse element, just not pipeline names.

**Comment by vito** [comment]
@pivotal-jamie-klassen I also noticed the scrolling behaviour for build output is different now - it's a scrollable element rather than scrolling the whole page. As a result, Home/End/PageUp/PageDown keys only work with the element focused (by clicking it). Structurally, this feels more sound, and cleans up a lot of janky margin/padding business we had to do before, but it'd be nice if those keys work. Maybe we could handle them just like `g`/`GG`?

**Comment by Lindsayauchin** [comment]
Feedback 1: Can we make the background of the side bar the same as the background for the active side bar (#282828) ?
![Screen Shot 2019-05-08 at 11 24 33 AM](https://user-images.githubusercontent.com/27746614/57387199-e188bc80-7183-11e9-93a1-ae7f1eb81e60.png)

Can we also use the same CSS as the Groups active and inactive, and hover states?

**Comment by vito** [comment]
Another bit of broken build scrolling: deep-linking to logs doesn't seem to scroll it into view after the logs are loaded:

https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-topgun/builds/387#L5cd045af:1302:1322
