### ISSUE TITLE
Internal server error when trying to authenticate with a Github account that has an unverified primary email

### ISSUE THREAD

**Issue by luan** [concourse/concourse#3837]
## Bug Report

Having a github account in which the primary email is not verified causes concourse to choke unhelpfully with a 500.

## Steps to Reproduce

1. Any concourse setup with Github auth configured
1. Login to Github with account in which the primary email address is not yet verified
1. Try to sign in to concourse

## Expected Results

A helpful error message about the email address not being verified. This will help point users in the right direction to get the issue resolved for them.

## Actual Results

Internal server error with no description.

## Additional Context

We're not able to update to v5 yet to validate if this is still an issue there so if it's already fixed feel free to just close this and we'll make sure to accelerate our upgrades. But we couldn't find an existing issue about this either open or closed here.

## Version Info

* Concourse version: v4.2.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Google Cloud

**Comment by jama22** [comment]
Iirc this the github API returns a generic error when a user tries to login without an unverified primary email, and we have no way of knowing that it is this specific error condition in the API response from github

**Comment by pivotal-jamie-klassen** [comment]
@pivotal-jwinters can you answer off the top of your head whether dex/github swallows/down-casts the unverified email error?
