### ISSUE TITLE
How do I pass the local folders to Concourse Pipeline ?

### ISSUE THREAD

**Issue by vjsairam** [concourse/concourse#3838]
I have some project dependencies which are not pushed to GIT, so I need to pass those files as input to the pipeline. 

This is similar to passing files as arguments specified in docker build. When I try to run the pipeline with the input flag, I get an error **error: unknown flag `i'**.

**Comment by marco-m** [comment]
Hello, this looks like a question, not a bug. For these kind of question, could you please use the forum (https://discuss.concourse-ci.org/) or the chat (see https://concourse-ci.org/project.html) ? Thanks.

**Comment by vjsairam** [comment]
Thanks, Created a topic in https://discuss.concourse-ci.org
