### ISSUE TITLE
Concourse Build Output Collapses Whitespace and Ruins Indentation

### ISSUE THREAD

**Issue by JesseTAlford** [concourse/concourse#384]
It looks like Concourse's build output has its leading whitespace collapsed in the GUI. For things like bosh template errors (see screenshot below) this can be pretty misleading. Ideally, indentation would be preserved in this output.

We got confused and tried to fix the wrong property because we didn't notice that the error we wanted was indented under a problem for another job.

<img width="1778" alt="screen shot 2016-04-19 at 10 32 02 am" src="https://cloud.githubusercontent.com/assets/6201221/14649056/43541f1e-061a-11e6-802d-ff791647c3d4.png">

**Comment by vito** [comment]
This should be already fixed in 1.1.
