### ISSUE TITLE
Build metrics

### ISSUE THREAD

**Issue by cdugga** [concourse/concourse#3840]
Does Concourse provide a feature to surface build metrics? This was rised before https://github.com/concourse/concourse/issues/31 however i cant see if progress was made

The fly CLI provides most of the data however I dont think its possible fetch using timeframe

./fly -t example  builds -c 100

**Comment by jchesterpivotal** [comment]
I wrote [this resource](https://github.com/jchesterpivotal/concourse-build-resource) to help me collect build metrics; though note I have been putting off working on authentication support.

I tested it against v3 and v4, I haven't tried it with v5.

**Comment by cirocosta** [comment]
Hi @cdugga ,

You can also get measurements for both `BuildStarted` and `BuildFinished` (see https://github.com/concourse/concourse/blob/1c2ece53c4446082ea535c4768d7ef4df1b507f8/atc/metric/metrics.go#L302-L355).

https://concourse-ci.org/metrics.html

The exact name that you'll see in your metric system depends on which one you choose, e.g., in the case of Prometheus, you can get an idea of how long builds are taking by consuming the Histogram measurements from `concourse_builds_duration_seconds`.

Thanks!

**Comment by cdugga** [comment]
thanks @cirocosta that's what I need
