### ISSUE TITLE
Concourse should allow users to set retention on number of resource versions to keep

### ISSUE THREAD

**Issue by StevenArmstrong** [concourse/concourse#3846]
## What challenge are you facing?

As an operator of concourse, I utilise many resources in my pipelines. Over time these resources generate multiple versions. This causes exponential growth against the database to the point the cpu incrementally rises and concourse grinds to a halt.
Operators then have to write custom db scripts to clean tables, which is really something the concourse application should allow as it feels hacky purging the db using external scripts.

## What would make this better?

concourse resources should each implement a retention period like logs, that can be specified at a pipeline level. Using something like:
 **resource_version_retention : 20**
This would only keep the last 20 builds and allow users to control db growth.
## Are you interested in implementing this yourself?

I have implemented all the queries as per my cleandown script that is run outside concourse directly on the db.  So this has all the queries needed on the resource related tables that could be helpful to integrate this as a concourse feature.

[concourse_resource_cleanup.zip](https://github.com/concourse/concourse/files/3169409/concourse_resource_cleanup.zip)

**Comment by vito** [comment]
I believe we are already addressing the root of this problem in #3602. To me there is nothing intrinsically bad about keeping resource history as long as it's just consuming DB space (which is relatively cheap). The problem right now is they all feed into the algorithm, causing a continuous increase of network transfer and CPU usage, exacerbated by usage of the `time` resource.

This may further be mitigated by concourse/rfcs#24 which will lead to a better representation of the `time` resource which won't involve keeping a full history in the first place.

I'm gonna close this as I feel like we have a good understanding of the problem and a plan in place (and work in flight) for fixing it. Feel free to ping me if you feel it's not properly addressed and I'll re-open. :slightly_smiling_face:
