### ISSUE TITLE
Concourse web crashes when session key is not provided

### ISSUE THREAD

**Issue by edtan** [concourse/concourse#3847]
## Bug Report

If you try to run `concourse web` but don't specify `--session-signing-key`, it crashes.  This is very similar to #2152 but with Concourse v5.1.0.

## Steps to Reproduce

This example only provides the minimum number of arguments to reproduce the error.  Running `concourse web --tsa-host-key /path/to/a/host-key` results in:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16b57b6]

goroutine 1 [running]:
main.(*WebCommand).populateTSAFlagsFromATCFlags(0xc000421b08, 0xa, 0x0)
	/home/ed/src/concourse/cmd/concourse/web.go:76 +0x76
main.(*WebCommand).Runner(0xc000421b08, 0xc0000ede30, 0x0, 0x3, 0x2, 0x6, 0xc0003adae0, 0xc000248200)
	/home/ed/src/concourse/cmd/concourse/web.go:47 +0x52
main.(*WebCommand).Execute(0xc000421b08, 0xc0000ede30, 0x0, 0x3, 0x1984da0, 0x1b82460)
	/home/ed/src/concourse/cmd/concourse/web.go:34 +0x5c
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7f3e64e8f3b8, 0xc000421b08, 0xc0000ede30, 0x0, 0x3, 0x1, 0x0)
	/home/ed/go/pkg/mod/github.com/vito/twentythousandtonnesofcrudeoil@v0.0.0-20180305154709-3b21ad808fcb/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000089020, 0xc00003a0d0, 0x3, 0x3, 0xc000313b18, 0x16a037f, 0xc000089020, 0x1bc3398, 0xa)
	/home/ed/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:314 +0x7c7
github.com/jessevdk/go-flags.(*Parser).Parse(0xc000089020, 0x1bc3398, 0xa, 0xc000153780, 0xc000184900, 0x0)
	/home/ed/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186 +0x71
main.main()
	/home/ed/src/concourse/cmd/concourse/main.go:31 +0x1ac
```

## Expected Results

It should either give a user-friendly error indicating the missing parameter or generate the key.

## Actual Results

See above in the `Steps to Reproduce` section.

## Additional Context

It looks like the issue is that `cmd.RunCommand.Auth.AuthFlags.SigningKey` is `nil` here: https://github.com/concourse/concourse/blob/master/cmd/concourse/web.go#L76.

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Local dev machine and an EC2 instance
* Browser (if applicable): n/a
* Did this used to work?

**Comment by marco-m** [comment]
Probably the place to add tests for this regression is in the context of #3774 ?

**Comment by edtan** [comment]
Thanks Marco.  With the PR, I started a general sort of integration test suite for the `concourse` binary, and hopefully we can incorporate the other commands including `quickstart`.  I've been playing around with trying to create some unit tests as well, but it may involve some more work.

**Comment by marco-m** [comment]
Thank you! @edtan :-)
