### ISSUE TITLE
Super admin user

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#3853]
[@cirocosta  update]:

**Summary**

Concourse operators have a hard time managing pipelines across multiple
teams - doing all things across all teams.

We'd like to explore ways of making that easier.

**Context**

As Concourse scopes the visibility of pipelines and the actions
that one can perform in a per-team basis, operators wanting to
have a view of all that was hapenning in their installation (and
acting upon requests / problems), end up adding themselves to
all of the teams available.

Practically, such practice is problematic as it leads to two
problems:

1. **the token gets too big, prohibiting the use of the UI**

Looking at the `jwt` tokens that Concourse generates, we can see
that all of the team information gets embedded into it:

```
{
  "csrf": "6ce3688e5df9...",
  "email": "...",
  "exp": 1564422536,
  "is_admin": true,
  "name": "",
  "sub": "CgczNTc0N...",
  "teams": {
    "PE": [ "owner" ],
    "cf-notifications": [ "owner" ],
    "cf-tools": [ "owner" ],
    ...
  },
  "user_id": "3574444",
  "user_name": "cirocosta"
}
```

Put too many teams there and you'll exceed the 4096 bytes cookie
size limit.

2. **`fly` operations against are per-team**

Most of the endpoints that we have are team-scoped:

```
			 .---> team!!1
			 |
{Path: "/api/v1/teams/:team_name/pipelines/:pipeline_name/pause", Method: "PUT", Name: PausePipeline},
{Path: "/api/v1/teams/:team_name/pipelines/:pipeline_name/unpause", Method: "PUT", Name: UnpausePipeline},
{Path: "/api/v1/teams/:team_name/pipelines/:pipeline_name/expose", Method: "PUT", Name: ExposePipeline},
```

To overcome that, `fly` targets end up with a `team` field
specified that is then used as the team that fills that
`:team_name` field:

```yaml
targets:
  ci:
    api: https://ci.concourse-ci.org
    team: main	 # <<< you have to have the right team here
    token:
      type: Bearer
      value: eyJhbGciOiJ
```

This leads to folks either having to create multiple targets
(one per team), or mutating their `flyrc` to target a different
team.

**Comment by pivotal-jwinters** [comment]
This might solve #3141 for the specific use case where people want to add a local user to a large number of teams.

**Comment by clarafu** [comment]
Related #1012

**Comment by evanchaoli** [comment]
If there is a super admin user, then nobody should suppose to be in all teams, then issue #4116 should seldom been hit. Can we prioritize this task?

**Comment by jama22** [comment]
@evanchaoli this issue will be picked up by the Concourse for PCF team in the coming weeks

**Comment by scottietremendous** [comment]
**Acceptance Criteria**

- [ ] Identify the change and the impact of this proposed change
- [ ] Epic(?) created for chosen solution

**Comment by zoetian** [comment]
The following are affected because they all assume a a team name is given/provided:
- The API
  - usually checks to see if user is part of the team that the pipeline is owned by
- The Fly cli
  - scopes all commands to the currently logged in team but superadmin would want to see everything regardless of what team(s) they're part of
- The web UI
  - Only displays the pipelines for the teams the user is part of. Superadmin would need to see all pipelines

**Comment by taylorsilva** [comment]
Created an epic to implement "super admin": #4192
