### ISSUE TITLE
Two bugs in the `concourse_workers_registered` Prometheus metric

### ISSUE THREAD

**Issue by aledeganopix4d** [concourse/concourse#3856]
## Bug Report
We are observing two faulty behaviors for the metric `concourse_workers_registered`.
In summary:

1. The labels `stalled` and `retiring` never reports a value lower than 1 (when 0 is expected)

2. The label `stalled` does not reset (not even to 1 as per above bug) when `prune-worker` is executed from `fly`, only much later on (several hours) at seemingly random times.

## Expected Results

1. `stalled` and `retiring` should report 0 when no workers are either stalled or retiring, respectively.

2. The label `stalled` should be updated when the stalled workers are pruned through `fly`

## Actual Results

1. Over a 20 days period we observe that `stalled` and `retiring` labels for the metric are never lower than 1. Even while `fly workers` reports no workers in either states.

2. Over the same period we observe a that while the stalled metric assumes the correct value when the workers first become stalled, the value of the label takes long and seemingly random amount of time to reset.

## Additional Context
Some screenshots from our Grafana (getting the data from Prometheus).

1. `stalled` and `retiring` labels of the metric `concourse_workers_registered`, never below 1:
![01_metric_never_below_one](https://user-images.githubusercontent.com/40891147/57695702-3a0dfd00-764f-11e9-8ca7-705b4edb4b43.png)

2. `stalled` workers, keep in mind that every night at 3 am we run a pipeline that prunes all the stalled workers, but the metric never "resets" at 3 am:
![02_long_stalled_workers](https://user-images.githubusercontent.com/40891147/57695863-b274be00-764f-11e9-9154-059e21f6ba44.png)

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Did this used to work? No, it's the first time we try to use `concourse_workers_registered` since its introduction.

**Comment by antonu17** [comment]
Hi there. Any updates on this regard? :blush:

**Comment by vivobg** [comment]
We are seeing the same with Concourse v5.2.0. We are quite keen to use the Prometheus metric, so we can alert from it and trigger automated actions to recover the workers.

**Comment by kirillbilchenko** [comment]
any updates there?
