### ISSUE TITLE
UI dashboard performance etc. 100% cpu, slow animation and tooltip

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#3869]
## Bug Report

There is an interesting use case that if there is large amount of jobs in pipelines, dashboard choking heavily.

## Steps to Reproduce

open the dashboard by https://ci.rabbitmq.com/

## Expected Results

First load of the dashboard could be slow due to the large amount of jobs. However I would expect the UI to be fast once the rendering of pipelines, jobs is finished.

## Actual Results

CPU 100% by browser. Animation is slow. Tooltip of jobs take couple seconds to show.

## Version Info

* Concourse version: 5.1
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? It was better before.

**Comment by vito** [comment]
I believe this is the same as #3748
