### ISSUE TITLE
[docs] Grafana configuration

### ISSUE THREAD

**Issue by till** [concourse/concourse#3874]
concourse already includes Grafana, which is great, is there a way to configure the included Grafana for Github Auth? 

Configuration is straight forward:
https://grafana.com/docs/auth/github/

Is there anything to pass along to a `concourse-up` to enable that?

**Comment by vito** [comment]
Sorry but this doesn't really sound like a bug report or feature request - `concourse-up` is an EngineerBetter product, not ours: https://github.com/EngineerBetter/concourse-up

**Comment by till** [comment]
@vito Indeed it is, I am sorry for posting here.

**Comment by vito** [comment]
No worries!
