### ISSUE TITLE
Set teams via config yml doc

### ISSUE THREAD

**Issue by aegershman** [concourse/concourse#3877]
## What challenge are you facing?

Creating, configuring, and managing Concourse teams through a bash script. It's difficult to make it a "self-service" model where people fork/submit PRs to the config document from github.

It also means there are separate processes for managing teams && managing the auth of those teams: the `./set-teams.sh` script, and any configuration documents for each of those teams. `set-teams`.

## What would make this better?

[Similar to how you can pass auth roles via `--config` to `set-teams`](https://concourse-ci.org/managing-teams.html), the ability to _define teams themselves_ in yml.

So instead of having a bash script that looks like this...

```sh
#/usr/bin/env bash

# many more teams above...

fly -t main set-team \
	--non-interactive \
	--team-name eprescribing-services \
	--github-org erx-devops \
	--github-org erx-spaces \
	--github-org erx-core \
	--github-org erx-devops \
	--github-org erx-services \
	--github-team groundworks:cernercf-operators \
	--local-user eprescribing-services

fly -t main set-team \
	--non-interactive \
	--team-name emerging-app-dev \
	--github-org ops-portal \
	--github-team groundworks:cernercf-operators

fly -t main set-team \
	--non-interactive \
	--team-name argus \
	--github-org Argus \
	--github-team groundworks:cernercf-operators

# etc...
```

You could define both the team definition and the permissions in a yml structure:

```yml
# Not sure what the actual schema should be?
teams:
- team-name: foo
  users:
    local:
   - some-user
  groups:
    github-teams:
    -  ...
    github-orgs:
    - ....

# permissions could be co-located in this document.
```

This document could be split up into different files and individually validated / labeled as part of github pull request workflows. It could have it's schema validated. Perhaps it could fields like "renamed-from" to rename teams. And overall it would be easier to store the configuration as code in git, since it's purely a _config document_ and not both a config *and* executable document.

## Are you interested in implementing this yourself?

Sadly I'm not smart enough to implement this.

More than happy to answer workflow questions or give feedback if desired. Also very open to feedback on the idea. Thanks for your time and any consideration of the use-case.

**Comment by cirocosta** [comment]
Hey @aegershman,

Did you check out the `--config` param that can be used with `set-team`? (https://concourse-ci.org/managing-teams.html#setting-roles).

[`hush-house`](https://github.com/concourse/hush-house) used to leverage that in the past: https://github.com/concourse/hush-house/commit/7a13ca826edac8424470f79b528cdd83d8124a96, but we end up removing that as teams end up changing their own configurations by just using `fly set-team` by themselves, so we didn't want to be "on their way" of doing so (we give teams on `hush-house` `owner` permissions so they can self-serve).

Still, that's a `per-team` config that you must apply in a per-team basis 🤔

**Comment by aegershman** [comment]
Ahh @cirocosta alright my bad I think I've misunderstood the doc; I was under the impression you do `fly -t main set-team <create-team-data-here> --config myteam.yml`, where `<create-team-data-here>` should include all the users/orgs/etc. such as `--github-org=blarf`, `--github-team=flarf:glarf` that would be used within a `--config` to set the roles.

In other words, I thought you had to define the values you wanted to use within a `myteam.yml` config yml in the `set-team` command string **before** you could use it in the config yml. But now I believe I see that you can do `fly -t main set-team --team-name gershman --config myteam.yml`, and have all the roles in the document.

I'm very much pro-self-service as well, very anti-ticket process (JIRAs, github issues, etc.) & don't want to step on anyone's toes, but also need to maintain traceability. So I think for the time being I'll basically steal the work you shared in that hush-house commit & turn it into a concourse pipeline. I'll have the pipeline listen on `git` master for the repo the config is stored in && it'll update concourse itself. This way I can make the git repo fork-able by teams & they can submit their own PRs to their team's config yml. It's not as fast as giving over `owner` access, but that's okay. [We basically do the exact same process for cloudfoundry using a tool called `cf-mgmt`](https://github.com/pivotalservices/cf-mgmt) and this process will be the same.

It will still rely on bash scripting to iterate over a folder structure to handle the iteration of `fly -t set-team --team-name=<iteration-of-teamnames-for-each-file-in-teams-folder>`, because, as you said, this is done on a `per-team` config... but it's better than doing so much of this all in bash as I thought had to be done. Certainly better than I had it at the moment, so thank you for pointing out my goobishness and for sharing that git commit. I should have experimented with concourse 5.x's `set-team` / rbac model more.

**Comment by aegershman** [comment]
With all this said, just rapping this idea out, here's some thoughts on the use-case for defining the team structure within yml so you wouldn't need to use a bash script to iterate over `fly set-team`...

- If you defined all the teams _and_ their auth config within a single document, it could get pretty honkin' big quickly
- If you defined all the teams within a single document _but_ made the team's config.yml a path to a file, it would break up config nicely (imagine how `task:` points to a file). E.g.:

```yml
teams:
- name: gershman
   renamed-from: blershmen
   file: ../../teams/gershman.yml
- name: anotherteam
   file: ../../teams/anotherteam.yml
```

- possibly makes it easier to lint and validate, meaning it could be coupled with [a github pr resource](https://github.com/telia-oss/github-pr-resource)?
- this opens up possibility for adding config rules like `enable-delete-undefined-teams: true`, which could remove any team _not_ defined in the `teams.yml` (sounds scary, but would enable a git-based way to offboard concourse teams than having an admin do it from their cli?)
- also opens up possibility for having keys like `renamed-from: `, which renames teams in declarative fashion

Just wanted to put the idea out there. This is definitely a hypothetical operational delighter.

Interested in thoughts or feedback, but feel free to close this issue whenever.

Thanks so much for all you all do 👍

**Comment by mohsen0** [comment]
@aegershman have you guys discuss this internally? what are your thoughts about it?

**Comment by aegershman** [comment]
Will temporarily re-open this @mohsen0 there hasn't been any further discussion that I'm aware of. Here's how I'm solving it:

Imagine a repo following this structure:

```
~/projects/concourse-mgmt(master ✔) tree
.
├── concourses
│   ├── ci-concourse-4
│   │   ├── set.sh
│   │   └── teams
│   │       ├── apple
│   │       │   └── set.sh
│   │       ├── banana
│   │       │   └── set.sh
│   │       └── coconut
│   │           └── set.sh
│   └── ci-concourse-5
│       ├── README.md
│       ├── set.sh
│       └── teams
│           ├── foo
│           │   └── team-config.yml
│           ├── bar
│           │   └── team-config.yml
│           └── flarp
│               └── team-config.yml
```

Under `concourses/` we have a folder for each concourse deployment. In our case, ci-concourse-4 is a concourse on v4.2.3, and ci-concourse-5 is on concourse v5.4.x.

Why does that matter? Because concourse 5.x introduced the ability to pass `fly set-team --config`, whereas concourse 4.x still requires passing `--github-org` and such during `fly set-team`, so we have to structure differently.

Why haven't we upgraded the Concourse 4 to 5.x? Because we didn't do a great job about pipeline governance, and now we're scared that if we upgrade to Concourse 5, people's pipelines will re-trigger with unexpected results, such as re-pushing their apps to prod, etc. So the solution is to deploy a NEW Concourse, and slowly bleed people over to Concourse 5 where people are allowed to use pre-built pipelines... That's a story for a different day. The point is, for now, assume we have to manage multiple Concourses

Under `ci-concourse-4`, the root `set.sh` looks basically like this:

```sh
case "$1" in
set)
    for team in $(ls teams); do
        echo "--- ${team} ---"
        ./teams/"${team}"/set.sh
    done
    ;;
esac
```

Each Concourse team gets it's own folder ({apple, banana, coconut} as examples), and within each is another `set.sh`. Each team's `set.sh` looks like this:

```sh
#!/usr/bin/env bash

fly -t ci-concourse-4 set-team \
  --non-interactive \
  --team-name apple \
  --github-org EnterpriseApple \
  --github-team appleops:concourse-operators
```

This pattern repeats for _every team_. The idea is to allow for teams to make pull requests against this "concourse-mgmt" repository; they have to follow the pattern of including the team name as a folder name, and a `set.sh` that describes the Concourse team + auth flags such as `--github-org`, etc.

Once admins review the PR, it's merged in, and then an ADMIN manually runs the root `set.sh`, which idempotently configures all the Concourse teams for `ci-concourse-4`.

Why not do it in one big script? We used to do that, but it got cluttered really quick. It was impossible to setup github autolabeler rules ("if anything in `apple/` changes, label it as `org: apple`", etc.). And it didn't conceptually fit with how we could define team config in Concourse 5.

Why don't you automate the `set.sh` so when a PR is merged, Concourse handles the `set` for you? I mean, we could, but to be honest we didn't want to generate another `local` user & do a BOSH redeploy. Plus the convenience barrier is so low that we just haven't done it yet. No reason we couldn't, just haven't.

Why don't you allow teams to set their OWN configuration without this central PR thing? We don't want teams setting their own configuration. It needs to be stored as config in git. We need configuration auditing. Everything goes through a pull request; it allows for PR reviews, comments on the PRs, tracability, history of decision making, helps with SOC2 compliance, etc. A PR is such a low barrier to entry, that this really isn't a big deal. But encouraging allowing teams to do their own thing would be more problematic than ensuring everything goes through a quick PR process.

---

As for ci-concourse-5, it's a very similar process, except the root `set.sh` looks like this:

```sh
case "$1" in
set)
    for team in $(ls teams); do
        echo "--- ${team} ---"
        fly -t ci-concourse-5 set-team \
            --non-interactive \
            --team-name ${team} \
            --config=teams/${team}/team-config.yml
    done
    ;;
esac
```

and under each folder representing `<some-team>`, instead of a `set.sh` that's called, it's a `team-config.yml`.

---

Problems:
- It requires sticking to a folder structure
- The usage of all the `bash` scripting and folders feels a bit hacky? But it's better than nothing
- Doesn't handle renaming a team, deleting a team, etc.

Benefits:
- There's a logically coherent pattern (at least in my view it's logically coherent?)
- It's a logically coherent pattern that works for both concourse 4.x and concourse 5.x, or multiple concourses in general
- It's still self-service, e.g. teams can fork the repo and submit their changes as a PR. Minimizes ticketing process in favor of direct action.

What I think would be beneficial:
- Something similar to [`cf-mgmt`](https://github.com/pivotalservices/cf-mgmt) used for managing orgs/spaces/quotas/etc. for Cloud Foundry, except for Concourse. That's what I've _loosely_ tried to model this "concourse-mgmt" repo off of, at least somewhat conceptually. This repo approach lacks a _declarative_ way to things like rename or delete teams, still requires the script to traverse a folder structure, etc. It feels a liiiiittle bespoke, but so far it seems to be a pattern that's working fine.

Very much open to thoughts or feedback. Hope this was helpful! 👍
