### ISSUE TITLE
Feature request: Purge pipeline history after 'x' amount of runs

### ISSUE THREAD

**Issue by bsnchan** [concourse/concourse#388]
We have a pipeline that runs every 5 minutes which causes the pipeline's history to collect a lot of pipeline runs over time.

We find that the resource gets "stuck" in a hanging state and causes our tasks to hang and eventually build up many pending jobs. Our current workaround is to delete the entire pipeline and recreate it. Deleting the pipeline is also slow since it needs to purge the entire history of the pipeline from the db. 

It would be nice if Concourse purged old pipeline history in the background or if there was a way to customize this feature.

**Comment by vito** [comment]
Deduping this in favor of #301 which has some discussion and more detail.
