### ISSUE TITLE
UI is preventing users from viewing logs of other retries

### ISSUE THREAD

**Issue by maplain** [concourse/concourse#3886]
## Bug Report
for a job with multiple retries, UI is preventing users from viewing logs of other retries

## Steps to Reproduce
have a job with multiple retries, eg: 5. Abort it on the second retry. If you click "1", trying to view the failure message in the first try. UI will automatically bring you back to the second retry.

## Expected Results
UI will display logs of the first retry when i click "1";

## Actual Results
UI stays on the failed retry

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Chrome
* Did this used to work? N/A

**Comment by vito** [comment]
Duplicate of #3814
