### ISSUE TITLE
Get rid of the random container placement strategy

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#3888]
## What challenge are you facing?

In my understanding, the `random` container placement strategy (#1741, https://github.com/concourse/atc/pull/219) has been introduced as an attempt to avoid having too many build containers landing on the same worker (due to the fact that the given worker already has the input volumes needed by the tasks). As soon random has been released, we (Pix4D) have been using it in production.

Then [Concourse 5.0.0](https://github.com/concourse/concourse/releases/tag/v5.0.0) in March 2019 saw the introduction of `fewest-build-containers` placement strategy (#2577). We have been running fewest-build-containers in production since then and it turned out to be always way better than random (the only open issue is #3301 that I list here for completeness but I don't think it has an impact in this decision).

## What would make this better?

As such, my understanding is that there is no more reason of existence for `random`. We should remove it and update the documentation suggesting to either go back to default or to use fewest-build-containers.

This would have the following advantages:
* less code (=> less bugs, more clarity)
* force users to use better alternatives
* one less thing to know (cognitive load)

I am pinging here the various people I saw involved to double-check that my analysis is correct: @JohannesRudolph, @phillbaker, @ddadlani, @kcmannem, @topherbullock, @jchesterpivotal, @wagdav and @vito.

## Are you interested in implementing this yourself?

Yes.

**Comment by JohannesRudolph** [comment]
FWIW we're also running fewest-build-containers and it's been working good for us. In order of descending preference: 

- make concourse schedule tasks to k8s or similar and let it deal with cpu, ram & disk allocation (i.e. prefer volume locality as long as there's enough cpu and ram available, use `limits` / `request` style)
- fewest-build-containers
- random

Random was a good starter and solved a real problem for us, but I guess it has served it's purpose.

**Comment by marco-m** [comment]
@JohannesRudolph 
> Random was a good starter and solved a real problem for us, but I guess it has served it's purpose.

I forgot to mention this explicitly, but random saved our day for a long time, and especially showed that it was possible to add alternative container placement strategies to Concourse, so it has been super useful. Thanks for it! ❤️

**Comment by jchesterpivotal** [comment]
I agree that fewer strategies is better, since `fewest-build-containers` is going to outperform `random` in any long-running scenario. I'd hold onto the original strategy for now as there will _sometimes_ be workloads dominated by asset locality.

**Comment by ddadlani** [comment]
I don't think we should get rid of `random` just yet, at least until #3301 is fixed. Right now, when rolling all the VMs (e.g.) during a deploy, there is a tendency for all jobs to kick off on the same worker because they are all scheduled at almost the same time. We are using `random` on a few internal deployments to get around this issue.

In addition, all these strategies would probably go away / be merged somehow when #3695 is implemented.

**Comment by jchesterpivotal** [comment]
About the thundering herd problem -- how does `random` help with that? That feels like it's more of a job for build buffering, when that becomes possible.

As for `check` containers, could they use `fewest-build-containers`?

**Comment by kcmannem** [comment]
@jchesterpivotal we can't because fewest-build-containers only takes into account build containers. Checks would pile up on a worker and cause max_containers problem. Another thing is that checks are mostly timebound and aren't resource intensive, so we don't really need to be too smart about it.
