### ISSUE TITLE
Spike: Use containerd as a runtime for Concourse

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#3891]

**Comment by ddadlani** [comment]
This is technically 2 spikes:
1. Use `containerd` (without Garden)
2. Use docker

**Comment by ddadlani** [comment]
Also investigate using an off-the-shelf solution for container networking (e.g. docker/libnetwork) rather than implementing our own

**Comment by ddadlani** [comment]
Another concern is, how are we going to interface with containerd on the worker?

**Comment by vito** [comment]
Turned this into the [`containerd workers` epic](https://github.com/concourse/concourse/projects/44).
