### ISSUE TITLE
Uniqueness of username in audit logs

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3893]
## What challenge are you facing?

After the introduction of audit logs (see [Auditor PR](https://github.com/concourse/concourse/pull/3577)), one is now able to keep track of which users performed which actions in the system by following the trail of logs that `web` generates.

```
{... "message":"atc.audit","data":{"action":"GetPipeline","parameters":{":pipeline_name":["monitoring"],":team_name":["main"]},"user":""}}
{... "message":"atc.audit","data":{"action":"ListJobs","parameters":{":pipeline_name":["monitoring"],":team_name":["main"]},"user":""}}
{... "message":"atc.audit","data":{"action":"ListResources","parameters":{":pipeline_name":["monitoring"],":team_name":["main"]},"user":""}}
{... "message":"atc.audit","data":{"action":"Info","parameters":{},"user":""}}
{... "message":"atc.audit","data":{"action":"Info","parameters":{},"user":""}}
{... "message":"atc.audit","data":{"action":"Info","parameters":{},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"DeletePipeline","parameters":{":pipeline_name":["new-pipeline"],":team_name":["main"]},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"Info","parameters":{},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"GetConfig","parameters":{":pipeline_name":["new-pipeline"],":team_name":["main"]},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"SaveConfig","parameters":{":pipeline_name":["new-pipeline"],":team_name":["main"]},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"Info","parameters":{},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"UnpausePipeline","parameters":{":pipeline_name":["new-pipeline"],":team_name":["main"]},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"Info","parameters":{},"user":"admin"}}
{... "message":"atc.audit","data":{"action":"ListJobBuilds","parameters":{":job_name":["auto-triggering"],":pipeline_name":["new-pipeline"],":team_name":["main"],"limit":["50"]},"user":"admin"}}
```

<img width="1075" alt="Screen Shot 2019-05-21 at 10 27 21 AM" src="https://user-images.githubusercontent.com/3574444/58104607-0d0f9c00-7bb3-11e9-800f-ea4cf897e6a7.png">

<p align="center">
<i>what was <code>cirocosta</code> doing in <code>hush-house</code> over the last two days?</i>
</p>

As Concourse allows one to configure multiple auth providers though, it could be that a user named `cirocosta` in GitHub is not the same as `cirocosta` in Bitbucket and/or CloudFoundry and/or any other authentication provider. 

Such behavior can be even more clear for things like `admin` or `system`.

## What would make this better?

Somehow have a way of disambiguating users across multiple auth providers.

Thanks!

cc @pivotal-jwinters

**Comment by pivotal-jwinters** [comment]
@cirocosta we can use the `sub` from the token. It's unique across providers.
