### ISSUE TITLE
concourse-web: SIGILL: illegal instruction

### ISSUE THREAD

**Issue by christophermancini** [concourse/concourse#3897]
## Bug Report

Users reported that builds failed with the error, `no workers`, and received 401s intermittently. This was a sign that one of our two web nodes was not happy. I checked the systemd service and saw that one of them had been restarted very recently. I searched the logs around that time and found that the go process generated a SIGILL and was terminated.

Good news is, systemd restarted the process and the system returned to a stable state.

## Steps to Reproduce

No idea...

## Expected Results

Not to get a SIGILL.

## Actual Results

[concourse_crash_20190521.txt](https://github.com/concourse/concourse/files/3203945/concourse_crash_20190521.txt)

## Version Info

* Concourse version: v5.1.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: DigitalOcean Droplets running Ubuntu 18.04
* Browser (if applicable):
* Did this used to work? Never encountered this before.

**Comment by christophermancini** [comment]
This issue occurred several more times on the same web node. I decided to replace the droplet and the new droplet has not produced the same error. This must have been an issue with maybe the kernel on an old version of the Ubuntu image on that droplet and a CGO dependency.

**Comment by vito** [comment]
Thanks for following up! Definitely seemed like something out of the ordinary like that. The only clues I could find seemed unrelated (i.e. running Go on ARM).
