### ISSUE TITLE
Restarting a concourse web node results in doubling of containers on the workers

### ISSUE THREAD

**Issue by vivobg** [concourse/concourse#3906]
## Bug Report

Restarting the web nodes results in doubling of the containers on the workers.

## Steps to Reproduce

Web nodes placed behind a load balancer.
Workers connecting to web nodes via load balancer.
Restarting the web nodes results in doubling of the containers on each worker, and the count does not return back to normal, which ends up hitting the 256 limit on each worker.

As a workaround, we stop the workers, change the work directory to a new one, and start them up again, or deploy new workers.

## Expected Results

Worker container count does not increase after a web restart.

## Actual Results

Container count doubles, and isn't cleaned up. Workers reached 256 container limit

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS EC2
* Browser (if applicable):
* Did this used to work? Yes, we didn't see this behavior in the past.

**Comment by clarafu** [comment]
Do you see the doubled count of containers from `fly containers`? Or does the ATC not know about those doubled containers but it exists within the workers?

We have seen a couple of cases where containers have `gone missing` they are just left within the workers without the ATC knowing about them, therefore no proper gc to get rid of them.
