### ISSUE TITLE
Uploading artifact failed - output /bin/tar: unrecognized option - busybox

### ISSUE THREAD

**Issue by MBarendregt** [concourse/concourse#3907]
## Bug Report

when running a simple `fly -t dev execute -c config.yml`  I will get the following error: 

```
error: 'uploading test' failed: Post someurl: tar compress failed (exit status 1).

output: "/bin/tar: unrecognized option: null
BusyBox v1.28.4 (2018-12-31 18:05:13 UTC) multi-call binary.

Usage: tar c|x|t [-ZzJjahmvO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [--exclude PATTERN]... [FILE]...

Create, extract, or list files from a tar file

Operation:

c    Create
x    Extract
t    List
 -f FILE    Name of TARFILE ('-' for stdin/out)
 -C DIR     Change to DIR befo re operation
 -v    Verbose
 -Z    (De)compress using compress
 -z    (De)compress using gzip
 -J    (De)compress using xz
 -j    (De)compress using bzip2
 -a    (De)compress using lzma
 -O    Extract to stdout
 -h    Follow symlinks
 -m    Don't restore mtime
 -T FILE     File with names to include
 -X FILE     File with glob patterns to exclude
 --exclude PATTERN    Glob pattern to exclude
```

this happened when running on a alpine docker image with concourse 5.2.0 
I saw since 5.1.0 it automatically updates en downloads inputs in parrallel. So it seems that this behaviour breaks for tar in combination with busybox. 

Because if i run this on an Amazon linux instance or ubuntu docker image it works fine 

Btw, adding `--input code=.` does not work either

## Steps to Reproduce

simple:

    fly -t dev execute -c config.yml

[config](https://gist.github.com/MBarendregt/6fae9a56c8f474b85a194111a9e09c96)

## Expected Results

an execution of the yaml file. 

## Actual Results

see error 

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): binary 
* Infrastructure/IaaS: Running docker (alpine image) 
* Browser (if applicable): 
* Did this used to work? yes, till 5.0.1 (bumped from 5.0.1 to 5.2.0

**Comment by marco-m** [comment]
Hello, could you please edit your post and use markdown formatting? thanks.

**Comment by MBarendregt** [comment]
Sure, sorry, better?

**Comment by hfinucane** [comment]
If you install gnu tar does it start working?

**Comment by MBarendregt** [comment]
installing tar did the trick, apparently busybox doesn't have that natively, my bad. Thanks a lot
