### ISSUE TITLE
Plaintext passwords visible in Concourse build/deploy log

### ISSUE THREAD

**Issue by marie-cd** [concourse/concourse#391]
Hey! I'm pretty new to Concourse, so apologies if this is lacking in detail or if you'd prefer to receive the issue a different way.

While looking through the [deploy build logs for one of our apps](https://toolsmiths.ci.cf-app.com/pipelines/deploy/jobs/deploy-gitbot-commercial/builds/29), I noticed that the app passwords are visible in plaintext on Concourse. This made me feel weird.

If access control makes this a non-issue, feel free to resolve this, but wanted to call it out.

```
runtime: failed to create new OS thread (have 5 already; errno=11)
fatal error: newosproc
+ mkdir -p /root/.ssh
+ ssh-keyscan github.com
# github.com SSH-2.0-libssh-0.7.0
# github.com SSH-2.0-libssh-0.7.0
no hostkey alg
# github.com SSH-2.0-libssh-0.7.0
no hostkey alg
+ cp cfgitbot-config-commercial/manifest.yml cfgitbot
+ cp cfgitbot-config-commercial/config.yml cfgitbot
+ cd cfgitbot
+ '[' -z '$PLAINTEXT_APP_PASSWORD' ']'
+ cf login -a https://api.run.pivotal.io -u cfaccounts+cfbots@pivotallabs.com -o pivotal -s community -p '$PLAINTEXT_APP_PASSWORD'
API endpoint: https://api.run.pivotal.io
Authenticating...
OK
```

**Comment by vito** [comment]
It's up to you to make sure your public jobs aren't leaking credentials.
Concourse does everything it can to prevent this, including having jobs opt
in to being public, even when the pipeline is publicly visible.
