### ISSUE TITLE
Side bar: Drill into groups

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#3911]
Continuing on from IPM and our discussion of the next iteration of the sidebar. Related to issues #2440, #2273,  #3872 . 

Teams, like Release Engineering in PCF(@mcwumbly), have large pipelines that are using the groups feature to manage the density of jobs displayed on the pipeline view. They would like to drill into the groups of a pipeline from the sidebar to allow for easily navigating back to a specific pipeline group. 

## Proposed Design: 
![Screen Shot 2019-05-23 at 3 07 47 PM](https://user-images.githubusercontent.com/27746614/58279577-c1085700-7d6c-11e9-8167-cbbaff5747b5.png)

![Screen Shot 2019-05-23 at 3 08 44 PM](https://user-images.githubusercontent.com/27746614/58279581-c2d21a80-7d6c-11e9-8468-aec1a50bbb26.png)

## Spec:
- [ ]  add a chevron to the pipeline names that contain groups that would expand on click and remain persistent until the user collapses the groups list by clicking again on the chevron toggle. 
- [ ] use mostly all the UI rules from https://github.com/concourse/concourse/issues/3872 except for the background colour on the container. 
- [ ] ^^ Background on the groups side bar container is hex #2A2727 (the dark grey from the cards on the dashboard) to differentiate it from the sidebar and other black and grey elements surrounding it.

**Comment by vito** [comment]
We decided against this during IPM in favor of redesigning the 'groups' metaphor as groups associated to jobs (i.e. #469), having group filters on the pipeline UI act like search filters on the dashboard UI, and keeping the tags present on the build/job page (https://github.com/concourse/concourse/issues/2273).
