### ISSUE TITLE
Resources API leaks IP addresses on failed checks.

### ISSUE THREAD

**Issue by mxplusb** [concourse/concourse#3914]
## Bug Report

API results from the `/api/v1/resources` call can leak IP addresses.

## Steps to Reproduce

1. Deploy pipeline with task which has connection reset issues.
1. Make an authenticated call to `/api/v1/resources`.
1. Search payload for IP that can't be connected to.

## Expected Results

The IP address should be scrubbed or the error message should be simpler.

## Actual Results

```
{"name":"deploy","pipeline_name":"test-deploy","team_name":"main","type":"cf","last_checked":1558641232,"failing_to_check":true,"check_error":"connection: decode failed: read tcp x.x.x.x:33996: read: connection reset by peer"}
```

## Additional Context

This was found after an OWASP ZAP scan, there were multiple occurrences of IP addresses leaking into the API results.

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): OWASP ZAP proxy (Selenium)
* Did this used to work?

**Comment by marco-m** [comment]
I might be missing something, but if the call is authenticated, what is the problem of leaking that IP address?
