### ISSUE TITLE
Pipeline Status Aggregator Across Installations

### ISSUE THREAD

**Issue by osis** [concourse/concourse#3916]
## What challenge are you facing?

I have a lot of pipelines spread across many Concourse CI installations that I would like to keep track of and make sure they are healthy.

## What would make this better?

A central place to pull in statuses for the things I care about. Something like a blessed version of https://github.com/cppforlife/checkman would be ideal since it would get around a lot of the network access quirks that might come up. An application running somewhere might be better for the team scenario though since you'd be able to keep views in sync more easily? 🤔 

## Are you interested in implementing this yourself?

Yarp.

**Comment by osis** [comment]
Example of what Checkman looks like

![image](https://user-images.githubusercontent.com/347097/58347840-e9f02100-7e2c-11e9-9122-be5c4fdab321.png)

**Comment by Lindsayauchin** [comment]
@osis 
![Screen Shot 2019-05-24 at 3 24 15 PM](https://user-images.githubusercontent.com/27746614/58351906-1198b680-7e38-11e9-80d0-27fb4fe1a75d.png)

**Comment by Lindsayauchin** [comment]
@osis 
![Screen Shot 2019-05-24 at 3 38 18 PM](https://user-images.githubusercontent.com/27746614/58352576-fa5ac880-7e39-11e9-8530-b263eac4962f.png)

## Assets: 
[icons_status_tray.zip](https://github.com/concourse/concourse/files/3218348/icons_status_tray.zip)

**Comment by osis** [comment]
It works!

![Screen Shot 2019-05-24 at 5 03 24 PM](https://user-images.githubusercontent.com/347097/58356575-e321d800-7e45-11e9-9778-7039c915da4e.png)

**Comment by vito** [comment]
Seems like there are options available for doing this so I'm gonna close it. We also support CCtray: https://concourse-ci.org/observation.html#ccxml

**Comment by osis** [comment]
I was wondering where that page went. Thanks @vito!

**Comment by osis** [comment]
Note that the endpoint needed for CCtray needs team credentials even if the pipelines are public. Checkman doesn't this limitation.
