### ISSUE TITLE
Pausing a pipeline should not result in its versions being garbage-collected

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3918]
## What challenge are you facing?

After pausing the pull requests pipeline, I noticed that the version history was wiped out after un-pausing it. This made me sad.

## What would make this better?

Don't do that.

## Are you interested in implementing this yourself?

Nope.

**Comment by xtremerui** [comment]
Noticed this as well. Possibly when one pipeline is paused here  https://github.com/concourse/concourse/blob/5587bbed3566d5b75bd21af6cf74b5fb72cd552b/atc/db/pipeline.go#L633-L634

the related versions got GC since both `resource_config_id` and `resource_config_scope_id` become nil.
