### ISSUE TITLE
DEV build elm results in slower UI

### ISSUE THREAD

**Issue by ciriarte** [concourse/concourse#3919]
## Bug Report

The UI was built in DEV mode

## Steps to Reproduce

On a production deployment of concourse, just open the browser’s console.

## Expected Results

To not see elm’s warning about a dev build.

## Actual Results

As of 5.1.0 we see the warning

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure: gcp 
* Browser (if applicable): Chrome/Firefox
* Did this used to work? Unsure.

**Comment by pivotal-jamie-klassen** [comment]
It's fixed in 5.2 !
https://github.com/concourse/concourse/issues/3622
https://github.com/concourse/concourse/blob/v5.2.0/package.json#L27
