### ISSUE TITLE
Spike: Use a blobstore instead of/alongside baggageclaim

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3924]
One of the possible implementations of a `Store` interface for runtime could be using a blobstore instead of baggageclaim. This would be helpful for other runtimes (e.g. kubernetes).

This issue is to spike on what the world would look like if we used a blobstore. Would it make sense to use baggageclaim as an interface to a blobstore? Could baggageclaim be used as a worker-specific "cache" to the blobstore?

-- by @ddadlani

**Comment by marco-m** [comment]
For my understanding, are you are thinking of a blobstore like Minio or something different?

**Comment by vito** [comment]
@marco-m Right, something like S3/GCS/Minio/etc. This is primarily important for other backends like Nomad and K8s where we have less control over data locality. If we had a central blobstore we could just use [`artifact`](https://www.nomadproject.io/docs/job-specification/artifact.html) to fetch a container's inputs regardless of where the workload gets scheduled. Also supposedly traffic within GCP to GCS is supposedly wicked fast.

There's a lot to figure out here so we're putting together a spike with Nomad as the first use case to validate it (we'd do K8s but there are already a few other challenges that would get in the way).

**Comment by marco-m** [comment]
I am drooling.

**Comment by xtreme-sameer-vohra** [comment]
### How to get an inputs into a container

#### With Garden + Baggageclaim
- A previous step would have run that would result in a created volume for the input
- Instantiate a container with the input volume mounted

#### With K8s
- Instantiate a pod with one container & empty volume for every input and one container for the task
- The input container is responsible for fetching the input and storing it inside the empty volume


With that in mind, we can consider the set of interfaces we would need to consider
### RunStore Interface - Execute a step with outputs
#### Garden + Baggageclaim
- Run the container with a empty volume mounted for output
- The output is baggageclaim volume ids for every output

#### K8s
- Instatiate a pod with one container for the task and one container to store outputs to the blobstore
- The output is blobstore links for every output

### Run Interface - Execute a step with inputs
#### Garden + Baggageclaim
- A previous step would have run that would result in a created volume for the input
- Instantiate a container with the input volume mounted

#### K8s
- Instantiate a pod with one container & empty volume for every input and one container for the task
- The input container is responsible for fetching the input and storing it inside the empty volume

### Store Interface - Fly execute with inputs
#### Garden + Baggageclaim
- Create baggageclaim volume with content

#### K8s
- Store content in blobstore

**Comment by jchesterpivotal** [comment]
Distantly related, I experimented with deploying Minio alongside workers: https://github.com/jchesterpivotal/concourse-with-minio-deployment

Deploying as a DaemonSet would I think achieve a similar outcome.

Another option I would hold open is to use the Registry v2 API, with an eye to a future where node-local registries become common.
