### ISSUE TITLE
Remove examples/hello-world-every-minute.yml and move into documentation

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#3927]
A few months ago, an example pipeline was added into the main repo, and it was amended to show parallel step execution as part of a feature contribution: https://github.com/concourse/concourse/commits/master/examples

It is a bit odd for this pipeline to live by itself here. It would be more logical for this pipeline to live amongst the other examples in the documentation: https://concourse-ci.org/examples.html

There is also a typo `eccho` in the second step.

Adding it as a new page to this folder would do the trick: https://github.com/concourse/docs/tree/562fda81fa6060367afb263bc132bd99dcf3fa7f/lit/examples

**Comment by deadlysyn** [comment]
Since I've done some recent doc work, mind if I work on this?

**Comment by zoetian** [comment]
Hey @deniseyu,

Seems like the `examples` directory has been removed before.... Can we close this issue? Or do we still want to add this example to the book-lit?

Thanks!

**Comment by deniseyu** [comment]
Good catch @zoetian, let's close this!
