### ISSUE TITLE
Add API for querying versions by version fields

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3932]
In order to support e.g. `fly pin-resource-version -r concourse/concourse -v ref:abcde`, we should have an API endpoint for finding version numbers by querying fields of the version. This idea first came about in https://github.com/concourse/concourse/pull/3131#issuecomment-459874740.

This API should implement partial field matching, since some versions contain auxiliary information that is difficult to provide as a user. For example, PR versions look like this:

![image](https://user-images.githubusercontent.com/1880/58494418-0c42b100-8143-11e9-891c-f0074b36e8e3.png)

...so in this case I'd like to be able to just say `-v pr:3931` without having to specify all the other fields.

This kinda relates to https://github.com/concourse/concourse/pull/3920 where we mulled over how to URL-encode versions. I'd like to make the common case look nice, e.g. just `ref:abcdef`. We'll have to deal with funny values in edge cases, and for those I guess we can just do ugly URL encoding.

Rough sketch of common + edge cases:

| version | url |
| - | - |
| `{"ref":"abcdef"}` | `/api/v1/teams/foo/pipelines/bar/resources/baz/versions?filter=ref:abcdef` |
| `{"ref":"some value"}` | `/api/v1/teams/foo/pipelines/bar/resources/baz/versions?filter=ref:some%20value` |
| `{"some ref":"some value"}` | `/api/v1/teams/foo/pipelines/bar/resources/baz/versions?filter=some%20ref:some%20value` |
| `{"ref":"some%value"}` | `/api/v1/teams/foo/pipelines/bar/resources/baz/versions?filter=ref:some%25value` |
| `{"ref":"some%value","another":"field"}` | `/api/v1/teams/foo/pipelines/bar/resources/baz/versions?filter=ref:some%25value&field=another:field` |

@pivotal-jwinters wdyt?

**Comment by xtremerui** [comment]
One thing nice to have is a hint in response when nothing matches the field. Something like
`field not found. Available fields are base_sha, pr, message, url ...` taking pull request resource for example.

**Comment by pivotal-jamie-klassen** [comment]
what about colons (`:`) in the keys or values of the version?

**Comment by pivotal-jamie-klassen** [comment]
| version | url |
| - | - |
| `{"key:with:colon":"abcdef"}` | `/api/v1/teams/foo/pipelines/bar/resources/baz/versions?filter=key%3Awith%4Acolon:abcdef` |

**Comment by vito** [comment]
@pivotal-jamie-klassen Good call, there are actually some resources with `:` in the value (e.g. `sha256:abcdef`). 🤔 Kinda weird to encode it there but not the key:value separator, but I can't really think of a better option atm. I guess the semantics are "split on , and : and then url-decode the key-value strings."

**Comment by pivotal-jamie-klassen** [comment]
@vito the kicker when it comes to colons will be deciding on comfortable UX for fly. Something like `fly versions -v 'digest:sha256\:abcdef'` or else even forcing fly to only filter on one of the version keys, so you get `fly --version-key digest --version-value sha256:abcdef`.

**Comment by mockersf** [comment]
the backend knows the list of keys, maybe let it do the splitting?

**Comment by pivotal-jamie-klassen** [comment]
@mockersf that sounds like a great idea! I can imagine a performance hit taken by scanning all the versions for a given resource and gathering up the keys, so let's ensure we benchmark if we use that strategy.

**Comment by xtremerui** [comment]
@vito I assume the current requirement of the "partial match" is partial match in fields of a version however the value of the field is still full match?

For example, `pr:3941` for pull request resource would return this version
```
{"pr": "3941", "commit": "2622ae55c2f1a752e64xyz", "committed": "2019-06-05T16:26:46Z"}
```

How about `commit:2622` in this case? I think for some resource versions a partial match on field value is also useful? 

Another example, git resource version has only 
```
{"ref": "dded25db7b66367cede96f84a266de275d790b98"}
```
query with a full commit hash here might be a bit heavy? Thx!

**Comment by vito** [comment]
@xtremerui I think it should match exact field values. If for example I search `pr:1` I wouldn't want it to match `pr:10` and `pr:123`. If you have the first 6 characters of the commit hash you can probably get the rest pretty easily.

**Comment by vito** [comment]
https://github.com/concourse/concourse/pull/4048 has been merged

**Comment by joshzarrabi** [comment]
It would be super cool if this would work in the pipeline too. Having to know the entire resource hash makes it difficult to template out our pipelines.
