### ISSUE TITLE
"discovering new versions of ..." in build preparation should show 'spinning' while we're waiting on it

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3939]
## What challenge are you facing?

Manually triggered builds will not run until all of their input resources have had a `check` perform after the build's creation timestamp. If one of the `check`s is stuck, I currently have no way of knowing besides manually going and checking all the resources.

## What would make this better?

We already have an entry in the build preparation that says 'discovering new versions of ...' but it looks like this is just always checked. Can we have it show a spinner until the resource's 'checked' timestamp is after the build's creation timestamp?

**Comment by xtremerui** [comment]
i think this is exact the same as #3904

**Comment by vito** [comment]
@xtremerui yep, i'll close the other one since this one's in flight

**Comment by xtremerui** [comment]
Just a quick update for fast reproduce the issue. One can set up the pipeline and just disconnect from Internet to make the resource check hanging.
