### ISSUE TITLE
Add example of how to deploy metrics

### ISSUE THREAD

**Issue by zachgersh** [concourse/concourse#394]
For anyone reading [the metrics page](http://concourse.ci/metrics.html) it would be nice to have a sample manifest provided so that someone could actually deploy metrics and start to use them.

**Comment by evanshort73** [comment]
In the meantime, here's our manifests with the credentials removed:
https://concourseci.slack.com/files/eshort/F12PYQ38X/concourse.yml
https://concourseci.slack.com/files/eshort/F12PX98SU/metrics.yml

**Comment by karthidec** [comment]
Hi Evan, how to login into above links ?  on click, asking for login credentials... not seeing any option to sign up ...

**Comment by evanshort73** [comment]
@karthidec you can join the slack channel using the Slack Inviter as linked on this page: http://concourse.ci/community.html

**Comment by jama-pivotal** [comment]
@karthidec i know its been a while, but were you able to use some of those sample manifests that @evanshort73 provided?
