### ISSUE TITLE
Job names with + characters break links to builds page

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#3941]
## Bug Report

For a job named '+', or just containing a '+', links from the build log to the builds page don't work.

http://127.0.0.1:8080/teams/main/pipelines/christmas/jobs/%2B/builds/53 links to http://127.0.0.1:8080/teams/main/pipelines/christmas/jobs/+ instead of http://127.0.0.1:8080/teams/main/pipelines/christmas/jobs/%2B
 
## Steps to Reproduce

This makes the [Concourse Christmas Tree](https://gist.github.com/alext/e2de098f733b203bd350e4ccbacfe986) a less compelling demo.

## Expected Results

All the links in this silliness should work.

## Actual Results

404 pages

## Version Info

* Concourse version: v5.2.0
* Deployment type (BOSH/Docker/binary): binary
* Browser (if applicable): Chrome
* Did this used to work? I think so

**Comment by vito** [comment]
I'm going to consolidate this into https://github.com/concourse/concourse/issues/3985 which has been a long time coming. Thanks!
