### ISSUE TITLE
UI timestamps seem off by one

### ISSUE THREAD

**Issue by mmb** [concourse/concourse#3942]
## Bug Report

In a task that prints the current date you would expect the printed date to roughly line up with the date in the Concourse UI.

The last date is correct but all the ones before that seem to be off by 1.

## Steps to Reproduce

Create a task that prints the date and then sleeps for 30 seconds. Verify that the date output matches the Concourse UI timestamps.

## Expected Results

I expected the Concourse UI date to match the output date for all lines.

## Actual Results

![image](https://user-images.githubusercontent.com/24275/58581434-648db780-8204-11e9-91bf-e0c53431aaa9.png)

## Version Info

* Concourse version: 5.1.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: vSphere
* Browser (if applicable): Chrome
* Did this used to work? not sure

**Comment by vito** [comment]
Yeah this has been bugging me for a while. I'll toss it into the backlog!

**Comment by jomsie** [comment]
Update, previous fix had a bug within, reopening!
