### ISSUE TITLE
Read password from file when a path is provided

### ISSUE THREAD

**Issue by dirkschneemann** [concourse/concourse#3950]
## What challenge are you facing?
When starting up Concourse (e.g. the web UI via `concourse web`) and passing in a secret, e.g. via `--ldap-bind-pw=top-secret` or prior `export CONCOURSE_LDAP_BIND_PW=top-secret`, the secret needs to be submitted via the command-line and easily ends up in my shell history if I do not pay attention.

Not necessarily tied to Docker but especially in a Docker context with the recent additions of Docker secrets, it has become common practice to store secrets in a file and make the application read the secret from it, e.g. `concourse web --ldap-bind-pw=/path/to/secret/file` where the file at `/path/to/secret/file` contains the secret. While I still have to make sure not to expose this file to the public, at least the secret will not end up in my shell history.

As of now, if I provide such a path to `--ldap-bind-pw` (or any other similar flag), it will be interpreted literally as the password which obviously will not work.

## What would make this better?
When providing a file path to start-up arguments or environment variables that contain secrets, Concourse will read the secret from this file instead of interpreting the path literally as the secret.

Not sure how to handle this if somebody decides on a literal password that looks like a file path though.

## Are you interested in implementing this yourself?
Not at the moment, I just started recently working with Concourse and have no familiarity with the code base at all yet.

**Comment by eedwards-sk** [comment]
What prevents you from setting it using an environment variable (`CONCOURSE_LDAP_BIND_PW`)?

concourse web often runs from a service manager (e.g. systemd) in which case you can already accomplish your use case by providing an env file.

**Comment by marco-m** [comment]
I had the same reaction as @eedwards-sk, then I though that you are starting concourse from the shell to do experiments. In this case, you can already today obtain what you want using the shell:

```
concourse web --ldap-bind-pw=$(cat /path/to/secret/file)
```

I believe this solves your request. If you agree, then please close this ticket :-)

**Comment by dirkschneemann** [comment]
@eedwards-sk : Environment variables in a Docker context easily leak to the outside, e.g. when exporting them literally in your shell before starting the application, when people with access to the host inspect the container etc. As an alternative, [Docker secrets](https://docs.docker.com/engine/swarm/secrets/) (or bind mounts if secrets are not available) store secrets in mounted files which helps to keep them a bit more secure.

Thanks, @marco-m , in fact this is what I also came up with in my `docker-compose.yml` file which I use during development with Concourse.

Putting a file path into the environment variable would be even more convenient (e.g. to put it next to all other environment variables into an `.env` file) but this is also good enough for now.
