### ISSUE TITLE
Mobile UI: Inertial scrolling is broken since 5.2

### ISSUE THREAD

**Issue by CyrilPeponnet** [concourse/concourse#3956]
## Bug Report

Smooth scrolling of task logs is broken on mobile. It kills the UX as there is no way to finish a scroll in a human life time.

## Steps to Reproduce

Open a task log on your mobile and try to scroll.

## Expected Results

Inertial scrolling that allow you to move through logs quickly

## Actual Results

Line by line scrolling

## Additional Context

Was working fine on 5.1

## Version Info

* Concourse version: 5.2
* Deployment type: k8s charts
* Infrastructure/IaaS: gke
* Browser (if applicable): Safari / Chrome
* Did this used to work? YES

**Comment by pivotal-jamie-klassen** [comment]
`build-body` needs `overflow-y: scroll` and `-webkit-overflow-scrolling: touch`
