### ISSUE TITLE
Bunch of resource versions went missing

### ISSUE THREAD

**Issue by jpalermo** [concourse/concourse#3957]
## Bug Report

Several of our resources look like they are missing versions we expect to be there. At least one of them is missing all the resources and is a daily timer at midnight. 

We have not renamed any of these resources recently.

We still have builds with history that shows the build was triggered with the versions that no longer exist.

We confirmed in the database that the rows are actually missing from the `resource_` tables, it's not just a display bug.

## Steps to Reproduce

No clue

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP

**Comment by jpalermo** [comment]
We did have the pipeline paused for ~36 hours, no idea if this is related or not.

**Comment by marco-m** [comment]
To gather an additional data point, do you have global resources enabled? (https://concourse-ci.org/global-resources.html)

**Comment by analytically** [comment]
There is a bug in 5.2 that upon pausing, resource versions get deleted. Probably related.

**Comment by jpalermo** [comment]
No global resources enabled.

That bug does sound likely, is there work being done on that somewhere, or another issue for it?

**Comment by analytically** [comment]
https://github.com/concourse/concourse/issues/3918

**Comment by jpalermo** [comment]
Thanks, guess that didn't come up in my search since I was searching for "resources"
