### ISSUE TITLE
Unable to auth via Bitbucket Cloud

### ISSUE THREAD

**Issue by grabekm90** [concourse/concourse#3959]
## Bug Report

After a successful login on Bitbucket Cloud, I am redirected to not existing site on my-server.

## Steps to Reproduce

1. Add OAuth consumer in Bitbucket settings with
Callback URL: http://my-server/sky/issuer/callback
Permissions: Account: Email+Read, Team membership: Read

2. Set environment variables for Concourse web and start it:
https://github.com/MGBI/concourse-docker/blob/master/docker-compose.yml#L32

3. Try to log in to the main team:
fly -t target login -c http://my-server -b -n main
Or click 'Login' on Web GUI at http://my-server

## Expected Results
Successful login via BitbucketCloud to Concourse Web

## Actual Results

Site unavailable:
http://my-server/sky/callback?code=khim...&state=eyJyZWRpcmVjd...
To point it out:
*/sky/callback* not */sky/issuer/callback*

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Hetzner Cloud
* Browser (if applicable): Chrome 72, Firefox 60
* Did this used to work? YES

### Important!
It does work if I change to commented out GitHub auth:
https://github.com/MGBI/concourse-docker/blob/master/docker-compose.yml#L27

**Comment by xtremerui** [comment]
Could you provide the logs of web node when the login fails?
