### ISSUE TITLE
Feature Request: Manually queued builds that are cancelled immediately shouldn't make my pipeline sad

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#396]
/cc @kimeberz 

I had a paused job with an automatically queued build, and accidentally clicked the "Trigger Build" button instead of unpausing.

When I saw I had triggered a new build, I immediately cancelled it and unpaused my job instead. The previously-queued job went green (hooray!) but my manually triggered and cancelled job made my pipeline look brown (oh no!).

Can we have a "forget I ever tried to trigger that build" feature? Or maybe just secretly delete manually triggered builds that are cancelled before doing any work?

Thanks!

**Comment by maryamklabib** [comment]
I was going to make an issue for this but yay Dan. +1.

**Comment by chendrix** [comment]
Is there a reason why your "pipeline being sad" is of super duper importance to you?

I'm going to close this as I don't think it's a development priority, but please feel free to chime in with rationale, and maybe we can make some kind of meta-issue.

**Comment by wendorf** [comment]
Thinking about it in a broader context is a good idea. If I have an information radiator (CI monitor, Slack notifications, etc.), a non-green pipeline is going to grab the attention and time of my team. Even if I know that a "sad" (brown/red) box on the pipeline visualization is a false negative, I've forgotten that throughout the course of a day or week and kept re-checking it.

A non-green job indicates unhealthiness to me, and is a signal that I should take action. For my workflows, a manually cancelled "whoops" build should not indicate unhealthiness, but is indistinguishable at a glance from other issues like broken workers.

If there were a meta-issue, it'd likely be a discussion about visualization and proper calls to action. Maybe for some pipelines there's no call to action in the case of a manually-cancelled build, or it's conditional on some additional aspect. Is the real conversation here around more customization regarding types of Concourse events and appropriate calls to action?

**Comment by chendrix** [comment]
It sounds like your rationale is that you don't want to care about it if it wasn't something that should be actionable.

To me, this request is better served with something like #273

**Comment by chendrix** [comment]
Or also #401 (which you wrote)
