### ISSUE TITLE
Spike: Look into writing a driver for the nomad backend

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#3966]
Because Nomad doesn't provide artifact upload functionality, we should look into creating our own driver to enable this so that we can investigate using a blobstore with Concourse.

What would it take to write our own driver/augment an existing driver to implement ordering logic or do an upload automatically?

Related to #3925

**Comment by vito** [comment]
Docs for doing this are here: https://www.nomadproject.io/docs/internals/plugins/task-drivers.html

**Comment by marco-m** [comment]
Additional information related to task upload and ordering for Nomad:

https://github.com/concourse/concourse/issues/3925#issuecomment-508908422

**Comment by ddadlani** [comment]
We are looking to use `containerd` in place of `garden`, and also building out a container interface so closing this for now.
