### ISSUE TITLE
Feature Request: Job pausing/unpausing button should be more obvious

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#397]
/cc @kimeberz 

I spend a lot of time at https://my-concourse.biz/pipelines/:name/jobs/:name/builds/:id, and am used to clicking on buttons on that page to control my job. When I have a paused job, I see the nice "+" button (for "Trigger Build") and click it instinctively, which causes #396. If pausing weren't buried in the https://my-concourse.biz/pipelines/:name/jobs/:name page (which I only know how to get to because I once tried to click the job name on a .../builds/:id page), or if the .../jobs/:name page were more obvious to get to, I'd make fewer silly mistakes.

Thanks!

**Comment by sampeinado** [comment]
See proposed solution below. I have changed the structure of the page slightly by moving the green/red/blue bar beneath the list of builds and putting the build number and build timing info within that bar. I also changed the styling of the trigger build button and added a new button which can be used to pause the the job. This pause button is left aligned while the trigger build button is right aligned, which should hopefully help to avoid the silly mistakes mentioned in this issue.

Pause button normal state:
![green](https://user-images.githubusercontent.com/35495560/38200708-5bb7e63c-3663-11e8-9ed2-37e8f315143e.png)
Pause button hover state:
![pause hover](https://user-images.githubusercontent.com/35495560/38200714-6245929c-3663-11e8-9665-9b0124943e38.png)
Pause button clicked state:
![pause click](https://user-images.githubusercontent.com/35495560/38200716-65a14d6e-3663-11e8-929f-c09de7a99c25.png)
Play button normal state:
![paused](https://user-images.githubusercontent.com/35495560/38200734-70a810bc-3663-11e8-9ec8-cd230f3444ad.png)
Play button hover state:
![play hover](https://user-images.githubusercontent.com/35495560/38200723-6c0ece10-3663-11e8-9658-e4d7306a55b1.png)
Play button clicked state:
![play click](https://user-images.githubusercontent.com/35495560/38200743-75b3a206-3663-11e8-8dd2-621acf5662b6.png)
For a job which is currently running, the cancel button appears within the build status section:
![currently running cancel build](https://user-images.githubusercontent.com/35495560/38200745-783312e6-3663-11e8-8a48-89864e913ef4.png)

**Comment by wendorf** [comment]
Thanks for the mockup! Glad to see movement here.

My first reaction to that screenshot was thinking that the pause button paused the current active build, not the job. I think because there are generally no controls on that page other than the "new build" button that are at the job level.

I'm thinking about how that would look when the job is unpaused and a build is currently running. I'd probably think that clicking pause would pause my active build.

I've made a mockup not to suggest a final direction (there are major concerns, like losing the region tie-in between the job header and the selected build) but just to show my "feelings":

![pause job mockup](https://user-images.githubusercontent.com/407342/38456382-29d6cadc-3a39-11e8-86d4-967b0b4ef285.png)

**Comment by Lindsayauchin** [comment]
@wendorf 
we have been thinking about how to better organize the job header and the controls on the page for the build page. 

A proposed solution is as follows: 
![concourse_build_pause_play_build_01](https://user-images.githubusercontent.com/27746614/38629645-9ab51334-3d82-11e8-8b6d-093a21fb2501.png)


In this proposal, we are moving elements out of the subhead, timestamps build and #,  to avoid some of the concerns you are having above around confusion with the pause button appearing that it has paused the current active build, not the job. 

Resume job/ pause job button is beside the job name. This shows the status of the job without confusing it with the status of a completed build. 

Triggering a build is located at the beginning of the list of builds, current and historical. This seems to make the most sense as the triggered build will be the next in the series, a new build. 

Abort is located on the current running build.

**Comment by jama-pivotal** [comment]
Linking this to #1915

**Comment by wendorf** [comment]
Looks great! Couple nitpicks:

- It's a little unclear from the mockup which build is selected. I think it's 103244 because it's brighter, but it's not immediately obvious.
- I still feel a little disconnect between the "atc" job title and the "resume job" button. Just take this (and my other nits) as a data point. I'm not convinced it's a very interesting nit.
- It would be nice if the "trigger build" button changed to reflect the paused status of the job, so I don't click it expecting a build to be started.

**Comment by jama-pivotal** [comment]
@wendorf I'm migrating your comment to issue #1915 because I want to centralize the convo for when an engineer picks up the work...and for @Lindsayauchin to not go insane bouncing between two issues and updating the designs on both
