### ISSUE TITLE
Publish Concourse API

### ISSUE THREAD

**Issue by ukabu** [concourse/concourse#3974]
## What challenge are you facing?

All interaction with Concourse are done thru the `fly` command line. This is work fine for many use cases.

Sometime we need to extract information from many pipelines/teams. We want to expose some information in an app that already expose many kind of metrics and information from other tools like BitBucket, SonarQube and others.

Scripts can do some of this, but an API would be much more useful.

There is no documentation for the ATCs API

## What would make this better?

To have a published API to interact with Concourse.

We can use the current API, but the fact that it is not documented and published is risky as you could change it without notice.

## Are you interested in implementing this yourself?

No time :-)

**Comment by wagdav** [comment]
@ukabu this is a duplicate of #1122 Would you please close this issue? Thanks!

**Comment by ukabu** [comment]
done
