### ISSUE TITLE
Feature request: Errand for performing concourse backup

### ISSUE THREAD

**Issue by bonzofenix** [concourse/concourse#398]
We are interested in having an errand that can perform a DB backup before performing a deployment. We can allocate some of our resources to submit a PR. We were wondering if this would be something that would get merged.

@cloud-dude && @bonzofenix

**Comment by vito** [comment]
I'm not sure; I would rather remove Postgres from our release in the long run so folks can use a more well-supported release like https://github.com/cloudfoundry/postgres-release
