### ISSUE TITLE
Horizontal scroll shown on build page

### ISSUE THREAD

**Issue by jomsie** [concourse/concourse#3982]
## Bug Report

A horizontal scrollbar exists on the bosh topgun build page.

## Steps to Reproduce

Visit: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-topgun/builds/443

## Expected Results

No horizontal scrollbar should exist.

## Actual Results

A horizontal scrollbar exists.

![Screen Shot 2019-06-05 at 10 58 56 AM](https://user-images.githubusercontent.com/2362482/58967046-682fba00-8781-11e9-9d84-8a31f1e2aead.png)

## Additional Context

Does not seem to happen on firefox.

## Version Info

* Concourse version: v5.2.0
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: gcp
* Browser (if applicable): chrome
* Did this used to work? yes

**Comment by matthewpereira** [comment]
@jomsie Can't seem to reproduce this - maybe it's a wrinkle that's been ironed out in some of the work that happened between 5.2.0 and 5.5.0?

We have new stylish scrollbars now, but I don't see any horizontal scrolling (tested in Chrome 76.0.3809.132).

Could you confirm whether this is still an issue for you?

**Comment by jomsie** [comment]
@matthewpereira i'm going to go ahead and close this, seems like it's alright on my comp!

thanks for reminding me :)
