### ISSUE TITLE
[Web UI] Can't view previous attempt of a task

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [concourse/concourse#3986]
## Bug Report

If a task in a job is configured with multiple attempts, only the most recent attempt can be viewed.

## Steps to Reproduce

Have a task with multiple attempts, that fails. 
Wait for the second attempt to start.
Click on the `1` above the task

## Expected Results

To see the output of the first attempt of the task

## Actual Results

Full page refresh, displays the most recent attempt of the task

## Version Info

* Concourse version: v5.2.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? yes

**Comment by marco-m** [comment]
Ah, I just checked on our Concourse 5.2. Yes, I can confirm this bug.

**Comment by xtreme-james-thomson** [comment]
Hi @xtreme-conor-nosal, I think it's this issue: https://github.com/concourse/concourse/issues/3814. It should go into the next release. (Let me know if I'm wrong!)

For the time being, there is a workaround in the issue, (shift click). Sorry for the inconvenience!

**Comment by pivotal-jamie-klassen** [comment]
Yep, fixed in 5.3.0
