### ISSUE TITLE
Difficulty diagnosing SSH key problem on external Windows worker

### ISSUE THREAD

**Issue by a-b** [concourse/concourse#3991]
## What challenge are you facing?

When setting up an external Windows worker, we saw some SSH errors in the logs. We believed that either the TSA public key on the worker was wrong, or that the worker public key saved in Concourse was wrong, but we could not tell from the log messages which key was wrong.

The error message was `{"error":"failed to construct client connection: ssh: handshake failed: remote host public key mismatch","session":"4"}`.

We were using Concourse 4.2.3.

In case it helps someone, here are the particular details of why our TSA public key was wrong. On Linux workers, we would have something like `ssh-keyscan -p 2222 some.concourse.org > tsa-public-key.pub`. When we translated that to PowerShell for the Windows worker, we arrived at `$(ssh-keyscan -p 2222 some.concourse.org).replace("[some.concourse.org]:2222 ", "") | Out-File C:\concourse\tsa-public-key.pub`.  However, the PowerShell commandlet `Out-File` defaults to UTF-16 encoding. This meant that the bytes on disk were different, but that the output when we printed the file looked the same.

For reference, this is the command that eventually let us create a working key:
```
[IO.File]::WriteAllText("C:\concourse\tsa-public-key.pub", $(ssh-keyscan -p 2222 some.concourse.org).replace("[some.concourse.org]:2222 ", ""))
```

In this case, both the SSH key pairs we were working with looked correct when visually inspected, so we wasted a lot of time trying to rule out different things because we could not tell from the Concourse logs which key pair was incorrect.

## What would make this better?

If the message had said which SSH key on the worker was involved in the authentication failure, we would not have lost time ruling out the correct key. Because setting up an external worker involves two key pairs, we think it would help if error messages specifically said which key pair was involved.

Thanks!
@a-b and @willmurphyscode

**Comment by yasn77** [comment]
I ran into a similar problem using `Out-File`, and if it wasn't for this issue I would have wasted a lot of time trying to figure it out.

In my case, we use Hashicorp Vault to distribute secrets (the worker private key). When querying vault and using `Out-File`, I would get the following error upon starting concourse: 
```
invalid argument for flag `/tsa-worker-private-key' (expected *flag.PrivateKey): Invalid Key: Key must be PEM encoded PKCS1 or PKCS8 private key
```
So in this case, I knew it was private key file but wasn't clear what exactly was wrong with it (considering this key file works in Linux).

Having some additional message regarding the key files would definitely be useful.
