### ISSUE TITLE
Parallel Input Streaming

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#3992]

**Comment by kcmannem** [comment]
@cirocosta pointed out from the difficulties incurred by the rabbitmq team that streaming artifacts to a scheduled task takes a very long time. A large amount of inputs could lead to slow startup times, making it look like concourse scheduling is slow or lagging. We've addressed this in two ways; Gzip is a CPU heavy and also slower at compressing/decompressing resources for transfer so we switched it over to zstd #3880 and this where we will request resources to be streamed in all at once. This should mean the startup time is now limited to the time it takes for the largest resource being streamed..

**Comment by ddadlani** [comment]
We could rate limit the number of parallel streams and expose that number as a command-line flag for configuration. We may need to test on prod/wings and have a benchmark to see the actual benefit that this provides.

We shouldn't merge this before #3819 which will reduce the cost of streaming, but we should benchmark both of these changes separately.

**Comment by kcmannem** [comment]
running drills tests where we stream 6 heavy docker images to a task. Heres the findings...

| In Serial  | In Parallel |
| ------------- | ------------- |
| 7m 30s  | 3m 45s  |
| 7m 17s | 1m 43s  | 
| 4m 43s | 2m 34s  | 
| 7m 13s | 3m 34s  | 

Note:
-  I think we got really good volume locality on the second run so ignore this

Here are the network/cpu graphs of serial streams vs parallel streams, each hump relates to a build being run in the order of the table above.
![Screen Shot 2019-06-18 at 12 42 01 PM](https://user-images.githubusercontent.com/9054726/59702782-84dae180-91c6-11e9-9417-8f75db19bafc.png)
![Screen Shot 2019-06-18 at 12 43 41 PM](https://user-images.githubusercontent.com/9054726/59702881-bce22480-91c6-11e9-906c-b36ef35689d2.png)

![Screen Shot 2019-06-18 at 12 40 14 PM](https://user-images.githubusercontent.com/9054726/59702789-886e6880-91c6-11e9-9814-9996e3e04bc9.png)
![Screen Shot 2019-06-18 at 12 43 48 PM](https://user-images.githubusercontent.com/9054726/59702887-c10e4200-91c6-11e9-8bd3-b816b1390094.png)

cc @ddadlani

**Comment by cirocosta** [comment]
Thanks for sharing! Do you have web CPU usage as well? Thanks!

**Comment by kcmannem** [comment]
@cirocosta good thought, it does in fact consume cpu 
![Screen Shot 2019-06-18 at 2 10 43 PM](https://user-images.githubusercontent.com/9054726/59708534-f325a100-91d2-11e9-82d2-90f94f4b620c.png)

**Comment by kcmannem** [comment]
We repeated the test again and saw the the total transmitted between the two deployments are the same. Conclding that even though the network peaks and sustains at different amounts, we are transmitting the same amount of data.

![Screen Shot 2019-06-19 at 11 24 30 AM](https://user-images.githubusercontent.com/9054726/59778744-0bee8f00-9285-11e9-8c65-fb13d602c3f7.png)
![Screen Shot 2019-06-19 at 11 24 23 AM](https://user-images.githubusercontent.com/9054726/59778748-0e50e900-9285-11e9-9ff0-0fafb83473ad.png)

**Comment by kcmannem** [comment]
we took a look at why the cpu spkies during streaming. It has to do with the tcp buffers. 
![Screen Shot 2019-06-19 at 2 41 56 PM](https://user-images.githubusercontent.com/9054726/59791584-75c86200-92a0-11e9-8cbc-8c0ddd3d9797.png)

**Comment by kcmannem** [comment]
@vito we ran strabo with the changes and they're pretty good. We redployed hushhouse to test this. It has a 1 core cpu and when the streaming started, we maxed out the cpu but it didn't cause any errors and it was for a short amount of time. It's also important to note this is a very small web. We hit peak bandthwidth of 2Gibs.

![Screen Shot 2019-06-19 at 5 53 36 PM](https://user-images.githubusercontent.com/9054726/59854911-d3f95180-9341-11e9-9536-81132dea7878.png)

The initialization time for goes from 1h 20m to 4m

![Screen Shot 2019-06-20 at 9 41 19 AM](https://user-images.githubusercontent.com/9054726/59854947-ebd0d580-9341-11e9-89be-964a608c8d65.png)
![Screen Shot 2019-06-20 at 9 40 24 AM](https://user-images.githubusercontent.com/9054726/59854952-f0958980-9341-11e9-8dbe-a9b9be9b3025.png)

**Comment by kcmannem** [comment]
updated the helm deployed concourse to 3 cores to see how far we can push bandwidth. We get upto 3Gbps and only reach 60% cpu utilization. We didn't observer any other metrics be affected other than Go runtime's GC taking a 60ms pause afterwards. Thats also really negligible.

![Screen Shot 2019-06-20 at 10 49 24 AM](https://user-images.githubusercontent.com/9054726/59858723-841e8880-9349-11e9-96df-61ea80682db3.png)

**Comment by cirocosta** [comment]
Thanks for sharing, @kcmannem !

With those results, I'd say we should probably also update https://concourse-ci.org/concourse-web.html#web-properties to account for the fact that streaming of volumes is something that should be factored in the decision of scaling vertically the web nodes.

Thanks!
