### ISSUE TITLE
Conditional step type

### ISSUE THREAD

**Issue by kadamanas93** [concourse/concourse#3999]
## What challenge are you facing?

I would like to run a step in a job that triggers other steps on success or failure. For example: Step A:
1) `on_success`: execute Step B, C
2) `on_failure`: execute Step X, Y

The idea is not to let step A determine if the job succeeded or failed but let subsequent `on_success` or `on_failure` steps to make the final determination.

## What would make this better?

A conditional step type called `conditional` where you have to define one of `on_success` or `on_failure` steps. 

If one of `on_success` or `on_failure` is not defined, the omitted one automatically is considered success and the parent step is also considered successful if it triggers the omitted step.

**Comment by vito** [comment]
Sounds like an `if`/`then`/`else`? This comes up every now and then. I'm a *little* skeptical of wiring conditionals into build plans since their current design is primarily to encourage a single idempotent flow. What's your use case?
