### ISSUE TITLE
abort doesn't when task is waiting for user input

### ISSUE THREAD

**Issue by ukabu** [concourse/concourse#4006]
## Bug Report

When a task is waiting on user input (this shouldn't be, I know) aborting the job doesn't work.

## Steps to Reproduce

Create a job with a task that waits for user input. Run it. Then abort.

## Expected Results

The job aborts.

## Actual Results

The job doesn't abort. There is stilll a loading indicator on the task waiting for user input.

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Azure
* Browser (if applicable): Chrome
* Did this used to work? Not sure.

**Comment by vito** [comment]
What do you mean by user input?
