### ISSUE TITLE
abort doesn't when pending (waiting on resource version)

### ISSUE THREAD

**Issue by ukabu** [concourse/concourse#4007]
## Bug Report

When a job is started but pending on discovering resource version, aborting the job doesn't work

## Steps to Reproduce

Have a job that has a passed for resource generated by a previous job.
Trigger the job without having run the previous job.
The job will be pending on a new version of the resource. (grey color)
Now click abort on the pending job.

## Expected Results

The job is aborted.

## Actual Results

The job isn't aborted.

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Azure
* Browser (if applicable): Chrome
* Did this used to work? Not sure.

**Comment by cappyzawa** [comment]
this issue might have been fixed by https://github.com/concourse/concourse/pull/3922 (?)
