### ISSUE TITLE
I would like a way to annotate/group failure causes

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#401]
/cc @kimeberz 

My team has spent some time tracking failures outside of Concourse (using tools like spreadsheets and issue trackers). It would be nice to be able to 1) annotate why something failed so that future spelunkers can get a high-level overview 2) see at a glance which failures have been annotated and which need spelunking 3) group failures by annotation, either a free-form text field, the specific task that failed, or some other delightful grouping.

Thanks!
@wendorf

**Comment by utako** [comment]
+2

**Comment by wendorf** [comment]
Closing in favor of #476

**Comment by vito** [comment]
Reopening per discussion in #476
