### ISSUE TITLE
name_to_handle_at() no longer supported

### ISSUE THREAD

**Issue by DennisDenuto** [concourse/concourse#4011]
## Bug Report
Hello, we are running into an issue in one of our 'integration tests'.

This test starts up an `nfs-server` and then runs tests against it.

Our `nfs-server` is `seg faulting` since the upgrade to `5.3.0`. It appears that when the nfs-server makes the `name_to_handle_at()` sys call, it is getting a not supported `EOPNOTSUPP` error.

## Steps to Reproduce
On 5.3.0:
1. fly execute (privileged) with this image mitcdh/nfs-ganesha 
2. start the server in the background with `/opt/start_nfs.sh &`
3. mkdir -p /tmp/mnt && mount -t nfs localhost:/ /tmp/mnt

## Expected Results

It should mount the directory

## Actual Results

The mount hangs and ganesha server seg faults.

## Version Info

* 5.3.0:
* BOSH (Wings)
* Did this used to work?  Yes

/cc @paulcwarren @julian-hj

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta I believe this is more a function of switching the baggage claim driver from `btrfs` to `overlay`, rather than something intrinsic to the 5.3.0 release?

**Comment by cirocosta** [comment]
@pivotal-jamie-klassen , Yeah, here's my comment in the slack thread:


 > Hi @dleon, we recently moved from `btrfs` to `overlay` there in Wings - I wonder if that could've been the problem :thinking_face:  Assuming that it's a problem related to that, I'd give a try at mounting or performing whatever operation you're trying against `/scratch`, which serves as a bypass to the underlying disk filesystem (IIRC this should be ext4 there in Wings).

> Would you mind providing a small reproducible that we could run against to validate?

For this issue, yeah, having a small reproducible would be great 😁  

Thanks!

**Comment by DennisDenuto** [comment]
@cirocosta @pivotal-jamie-klassen 

Thanks for the reply. Here is a fly command to reproduce this issue:

```
fly -t persi execute -p -c <(cat <<EOF
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfpersi/nfs-certification
    tag: 2.2.1-rc.1

inputs: []

params:
  TRANSPORT: tcp

run:
  path: /opt/start_nfs.sh

EOF
)
```

upon running this, you will see the following line in the ganesha nfs server stdout: `init_export_root :EXPORT :CRIT :Lookup failed on path, ExportId=0 Path=/data/nfs FSAL_ERROR=(Operation not supported,95)` When run with `strace` it seems the root cause is the system call to name_to_handle_at 'not a supported operation'.

In a second terminal, if you `fly hijack` into the build running the ganesha server, and attempt to mount a directory (i.e. `mkdir -p /tmp/mnt; mount -t nfs localhost:/ /tmp/mnt`) then the ganesha server segfaults.
