### ISSUE TITLE
Update ImageTag in Helm Chart

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#4014]
We forgot to update the image tag to `5.3.0`

https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L22

Missed in this PR: https://github.com/helm/charts/pull/14292/files

**Comment by taylorsilva** [comment]
# Issue Status
###### Keep editing this comment with the current status of the issue

***

### Task List

- [x] Updated imageTag and tested that the chart used `5.3.0`
- [x] Made PR
- [ ] Waiting for PR to be merged: https://github.com/helm/charts/pull/14786

**Comment by cirocosta** [comment]
thankss!! 🙌
