### ISSUE TITLE
Improve error for workers switching teams

### ISSUE THREAD

**Issue by elgohr** [concourse/concourse#4020]
## Bug Report

When trying to switch an external worker to another team and the worker is not pruned in the old team, ATC returns http 500 during startup of the newly configured worker.

## Steps to Reproduce

- add an external worker to team a
- switch the worker to team b without pruning in team a

## Expected Results

Wouldn't an error like http 409 or 412 be more meaningful? In addition 500 indicates a server error, which it isn't.

## Actual Results

Http 500

## Version Info

* Concourse version: 3.14
* Deployment type (BOSH/Docker/binary): Bosh

**Comment by marco-m** [comment]
Hello @elgohr do you have any chance to reproduce this with a more recent Concourse version? We are now at 5.3

**Comment by elgohr** [comment]
Sadly there are a few security issues, like https://github.com/concourse/concourse/issues/2460 , because of which we can't update.
