### ISSUE TITLE
Question: How does Concourse use the output of the check, in, and out scripts when implementing a Resouce Type?

### ISSUE THREAD

**Issue by jrahhali** [concourse/concourse#4023]
[Question cross-posted from StackOverflow](https://stackoverflow.com/questions/56623103/implemented-a-resource-type-how-does-concourse-use-the-output-of-the-check-in), copy and pasted here:

Reading the Concourse documentation about [Implementing a Resource Type](https://concourse-ci.org/implementing-resource-types.html), in regards to what the check, in, and out scripts must emit, it is not clear why this output is needed or how Concourse uses it. My questions are:

1) How does Concourse use the output of the check script, the in script, and the out script?
2) And, why is it required that the in and out script emit the version? What happens if you don't?

---

For context, here is the relevant parts of the documentation:

1) For the check script:
> ...[it] must print the array of new versions, in chronological order, to stdout, including the requested version if it's still valid.
For example:
```
[
  { "ref": "61cbef" },
  { "ref": "d74e01" },
  { "ref": "7154fe" }
]
```

2) For the in script:
> The script must emit the fetched version, and may emit metadata as a list of key-value pairs. This data is intended for public consumption and will make it upstream, intended to be shown on the build's page.
For example:
```
{
  "version": { "ref": "61cebf" },
  "metadata": [
    { "name": "commit", "value": "61cebf" },
    { "name": "author", "value": "Hulk Hogan" }
  ]
}
```

3) Similar to the in script, the out script:
> The script must emit the resulting version of the resource. For example, the git resource emits the sha of the commit that it just pushed.
For example:
```
{
  "version": { "ref": "61cebf" },
  "metadata": [
    { "name": "commit", "value": "61cebf" },
    { "name": "author", "value": "Mick Foley" }
  ]
}
```

**Comment by evanchaoli** [comment]
Basically `check` generates new versions. A `check` may return zero or multiple versions. If a resource is defined `trigger: true` with `get`, then once its `check` returns new versions, new builds will be triggered, where `get` is passed with a version that `check` returned.

`check` only returns versions, `get` take a version and generate artifacts that can be consumed by the job. A `get` should always return input version and plus some metadata. Metadata will show on UI.

`put` is used to do something, but `put` cannot leave artifacts to following steps. For example, if a resource's `put` does code scan, it will wants to generate a report file for following steps to consume, then the report file can only be generated by the implied `get` after `put`. `Put` returned version will be passed to implied `get`, it's a way to tell implied `get` how to generate artifacts.

Hope this helps.
