### ISSUE TITLE
Build log retaintion policy to support keep last N success builds

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4026]
## What challenge are you facing?

In order to save database space, we always educate our users to set as small `build_log_retention` as possible. One problem we have seen is that, when a pipeline is being constructed, or some bad code pushed, a pipeline may continuously fail, which lead to no any success build log viewable. However comparing success build with a failure build is a useful method when debugging issues.

## What would make this better?

Add an optional parameter `success_builds` under `build_log_retention`. If `success_builds` is set, when clean up build logs, retain such number of success builds.

## Are you interested in implementing this yourself?

My team can try.

**Comment by evanchaoli** [comment]
After reading some Concourse code, I think the change should be in function `buildLogCollector.Run()` in `atc/gc/build_log_collector.go`. I may raise a PR.

**Comment by jama22** [comment]
Wanted to ask some clarifying questions if you don't mind @evanchaoli.

For example in this scenario: 
![example](https://user-images.githubusercontent.com/19274230/61237248-0f502b80-a708-11e9-9124-2f52cb9d56ea.png)

with a log retention of 5, Concourse would only then keep  907, 906, 905, 901, and 900?

**Comment by evanchaoli** [comment]
@jama22 That's not the idea. Say we define log-rotation to 5, and success_builds to 2, then concourse would keep 907, 906, 905, 904 and 903. Because latest  5 builds (907-903) has included 2 success builds. 

Let's change the sample data a little bit. Say 907-902 are red, 901 and 900 are green. Then Concourse will keep 907, 906, 905, 901, and 900. Because it needs to keep at least 2 success builds.

**Comment by jama22** [comment]
Thanks for the clarification!
