### ISSUE TITLE
Allow to manually trigger job from pipeline view

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4030]
## What challenge are you facing?

This request is from one of our users. This user's pipeline contains multiple jobs, and jobs are triggered in serial. In other words, job1 will generate an artifact that will trigger job2, and job2 will generate an artifact that will trigger job3, and so on. Thus if he manually triggers job1, that equals to triggering the entire pipeline.

He feels a little burden to always enter job1 in order to manually trigger his pipeline to run. Thus he raised a feature request to me that to add a "+" sign on pipeline view to trigger job1.

## What would make this better?

From a generic perspective, a Concourse pipeline jobs doesn't have to run in serial. A pipeline may contain multiple independent jobs, thus adding a "+" would be confusing in such case.

So I changed his feature request a little bit. I think we can add a "+" on every job (e.g. on top-right corner of job box) to manually trigger the job. As a plus, we may also show current build name on bottom-right concern of job box.

## Are you interested in implementing this yourself?

We may try.

**Comment by eedwards-sk** [comment]
I like this idea but I would be concerned over accidentally triggering a job when my intention was to go into the job view.

e.g. my workflow involves clicking into the boxes so regularly, I could see a new clickable button in the same area being easy to misclick
