### ISSUE TITLE
Ability to enumerate active users

### ISSUE THREAD

**Issue by zoetian** [concourse/concourse#4035]
## Why we want to enhance this feature?
There's no accurate measure on the number of active users on a concourse cluster.

We proposed two ways of doing this:
1. Parsing Log. As @pivotal-jwinters suggested, we could filter out the event `atc.dex.event`
 from the log for the past 60 days.
2. New DB Table. @YoussB proposed to add a new database table `active_user` in current DB to update the user `last_login_date` to enumerate the active users. This would require additional changes to the current login flow. The table schema may look like below:

| username      | last_login_date |
| ----------- | ----------- |

And the Pros and Cons we (@pivotal-bin-ju and I) can think about for now:

|   | Pros       | Cons |
|----------- | ----------- | ----------- |
| 1. Parsing Log | - No need to modify source code <br> - Only need to parse the logs    | - Get access to the users' log <br> -  Analyzing Logs for 2 months of the size roughly 20G can be time consuming <br> - It is hard to keep the Log  from last 2 months for some users |
| 2. New DB Table| - Cleaner way to enumerate active users  |  - Extra effort on modifying the login flow and database schema <br> - Increase certain DB usage  |

***

### Issue Status

Working is being done on the [feature/4035-active-users](https://github.com/concourse/concourse/tree/feature/4035-active-users) branch

***

**Sidenote** (@taylorsilva): when logging in as a user that's not part of any team (`guest` user in docker-compose) we get a HTTP 400 back and a blank screen at the `/sky/callback` endpoint. Logs show `"error":"user doesn't belong to any team"`. Thinking this may be a regression. This note is to remind us to check this out and potentially report.
and fly:
```
fly -t local login -u guest -p guest
logging in to team 'main'

error: oauth2: cannot fetch token: 400 Bad Request
Response:
```

**Sidenote 2** (@cirocosta): Concourse allows operators to set the duration of the tokens that are generated (see https://github.com/concourse/concourse/blob/e5bcd88fa311d0c35342e9e34bbb7c7f7c72b10f/skymarshal/skycmd/flags.go#L48), potentially allowing folks to take a very long time to have to re-authenticate.

**Comment by agurney** [comment]
From my perspective (large enterprise, many users) a logging approach is very reasonable, given that we already have infrastructure for log processing, security analytics / SIEM, etc. We are also interested in characterizing usage in finer detail - not just when logins happened, but what people did - which is the kind of thing that detailed logs can provide.

**Comment by marco-m** [comment]
Unsure if this could be good enough, but are you aware of https://concourse-ci.org/concourse-web.html#audit-logs ?

**Comment by YoussB** [comment]
- @agurney, I agree with @marco-m about the audit, you can get logs from all API calls.
- There is also a log event that is thrown by Dex with the message `atc.dex.event` and the data starts with `login successful`. This log shows the user's info as well. 
- In our case, we are mostly going to go with the database solution for 2 reasons:
  1. Not all users of Concourse have a mean of log aggregation, and logs can easily get lost if they are not aggregated. The could be as simple as recreating a VM if using bosh, or deleting the pod if using k8s.
  2. In the other case of a long-running deployment, the log size can be huge, so parsing these logs can take a lot of time and processing.

**Comment by cirocosta** [comment]
Hey,

We've been working on what could be a possible implementation going the table
way to validate if that's something that could easily (or not) fit what we have
in mind:

- a quick way for folks to get a list of the last users who logged into their
  Concourse installation (view limited to `admin` users).

Even though we strongly recommend people to have log aggregation (and metrics
too), that's not always the case.

While it's already possible for people to know the activity of the users in
their installations if they already have `audit`ing enabled (+ log aggregation),
for those other ones who are incapable of easily doing so, being able to
retrieve that information from the `api` would work as an alternative.



Here's the task list that we've been tackling:

- [ ] db 
	- [x] Table creation (`users`)
		- [x] up migration
		- [x] down migration
	- [x] `User` "model" and factory
	- [ ] user updates without ID bumps
		- currently, `update` means `delete + insert`
			- if we do an UPSERT, then we don't bump user IDs
- [ ] api
	- [x] capture logins
		- [ ] callback-based flow 
		- [ ] basic auth
	- [x] list all users  (`GET /api/v1/users`)
	- [ ] list all users logged in a given time frame



With those, I'd say we're in a good place to move forward with some more
feedback from both Core and API to validate if we're moving to a good direction
(or not :grin:).

- [ ] fly
  	- [ ] go-concourse
	- [ ] `fly users` (all users?)
	- [ ] `fly users --<some_flag>=<some_arg>` (period-based querying)

Something to keep in mind:

- Concourse does allow people to set the expiration time of their tokens,
  meaning that it's possible to have installations where people log in very
  rarely.



Thanks!

**Comment by cirocosta** [comment]
related: https://github.com/concourse/concourse/issues/3893

**Comment by taylorsilva** [comment]
Getting an error in CI related to this issue and its PR. Similar to errors we were seeing while working on the PR:

https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke/builds/448

```
waiting for ATC at http://35.194.26.47:8080 to be running{"version":"5.4.0","worker_version":"2.2","external_url":"http://35.194.26.47:8080"}
	
ok!
	
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	
                                 Dload  Upload   Total   Spent    Left  Speed
	
100 19.9M  100 19.9M    0     0  71.6M      0 --:--:-- --:--:-- --:--:-- 71.6M
	
5.4.0
	
logging in to team 'main'
	
error: oauth2: cannot fetch token: 401 Unauthorized
	
Response:
```

**Comment by taylorsilva** [comment]
Figured out the issue was the migration didn't run because it appears a "one-time" migration got run and the version number was wayyyyy higher than anything we would recently make. Manually deleted the migration. When prod is back up we can run the job again and it should Just Work ™️

**Comment by taylorsilva** [comment]
It's passing now: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke/builds/451
