### ISSUE TITLE
Concourse job fails when CONCOURSE_PEER_ADDR is changed

### ISSUE THREAD

**Issue by metacoma** [concourse/concourse#4036]
## Bug Report

Concourse pipeline fails,if the concourse peer address is changed during job execution.

## Steps to Reproduce

1. Create a pipeline with name `hello-world`
https://gist.github.com/metacoma/3229b6edbef453e5f1b4ccb1cf40a218
2. Trigger a pipeline
```
> seq 1 30 | xargs -P10 sh -c "fly -t concourse trigger-job -j 'hello-world/hello world'"
```
3. Wait about 30 seconds and delete concourse-web pod
```
> kubectl -n concourse delete pod -l app=concourse-web
```
4. Wait for concourse up
5. Check job status

## Expected Results

The job completed successfully

## Actual Results
![actual-results](https://user-images.githubusercontent.com/5146707/59808895-46047300-930f-11e9-8823-02b2c5a38477.png)

Hello-world job has failed with error:
`
Get http://127.0.0.1:8080/containers: dial tcp 10.244.2.127:38811: connect: no route to host
`
## Additional Context

I feel this is related to how core HA works in Concourse, and it’s also important for zero-downtime upgrades. So you can take down and replace atc/tsa with newer versions without failing any jobs. Therefore I decided to open this here instead of in a Helm chart

It’s important to note that atc/tsa internal IP address changes after a pod restart, and thus peer url changes as well. May be that’s what is causing the issue. If that’s the case it would be great to discuss how Concourse could tolerate this, because this is a normal situation in Kubernetes world and you can’t really make an assumption that the address will stay the same.

```
> kubectl -n concourse get pods -l app=concourse-web -o wide
NAME                            READY   STATUS    RESTARTS   AGE    IP             NODE                       NOMINATED NODE
concourse-web-6db697b85-sjmrr   1/1     Running   0          5m7s   10.244.2.127   aks-nodepool1-10878448-1   <none>

# show PEER address
> kubectl -n concourse exec -ti concourse-web-6db697b85-sjmrr -- /bin/sh -c 'echo $CONCOURSE_PEER_ADDRESS'
10.244.2.127
```

Restart pod
```
> kubectl -n concourse delete pod -l app=concourse-web 
pod "concourse-web-6db697b85-sjmrr" deleted
```

Check PEER address again
```
> kubectl -n concourse exec -ti concourse-web-6db697b85-hvgcq -- /bin/sh -c 'echo $CONCOURSE_PEER_ADDRESS'
10.244.1.69
```

## Version Info

* Concourse version: `5.3`
* Deployment type (BOSH/Docker/binary): `stable/concourse helm chart, version 6.2.1`
* Infrastructure/IaaS: `aks/azure`

**Comment by YenTheFirst** [comment]
We are also seeing this issue. Could this be reopened? Is there any useful information to collect towards debugging it?

**Comment by YenTheFirst** [comment]
Investigating this a bit more, I believe I have a workaround.

1) Have only 1 replica of the web pod running
2) set the `concourse.web.peerAddress` to `127.0.0.1` in the helm chart.

Using this setup, I was able to get green builds for the steps-to-reproduce above. (Using the default setup, I do get the same error)

It's actually not clear to me how the multiple-web-pod-with-forwarding case is working in kubernetes right now, even without pods dropping, as I don't see how those additional ports get opened for listening on the pod IP.

Thinking about this a bit more, I'm not sure that there's any way to make this work reliably in kubernetes, as-is, without having only at most 1 TSA.
