### ISSUE TITLE
Vagrantbox malformed metadata

### ISSUE THREAD

**Issue by carroarmato0** [concourse/concourse#404]
I'm getting the following when trying to pull down the vagrant box:

> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'concourse/lite' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> ==> default: Loading metadata for box 'concourse/lite'
>     default: URL: https://atlas.hashicorp.com/concourse/lite
> The metadata for the box was malformed. The exact error
> is shown below. Please contact the maintainer of the box so
> that this issue can be fixed.
> 
> Caught Encoding::CompatibilityError at '{"description":"A bo': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
>

**Comment by vito** [comment]
Not sure about this. The latest boxes seem to be fine, at least

**Comment by WGautier** [comment]
I hit this issue and solved it by updating Vagrant to 1.9.0.
