### ISSUE TITLE
Resources should indicate when they last checked (if ever) rather than assuming success

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#405]
This makes it impossible to tell in the web ui whether a new resource has:
A) Checked successfully and returned no version
B) Not yet performed a check

It's not a huge deal but it's annoying when testing out new custom resources. The addition of a force-check in the cli helps this a bit, but it would be nice if the web ui would say "check pending" or something when it hasn't actually happened yet.

**Comment by xtremerui** [comment]
Related to #1465

**Comment by jama-pivotal** [comment]
Closing because #1465 has been fixed and delivered
