### ISSUE TITLE
Add a sidecar container to pods to communicate with ATC

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4055]
We need a sidecar for a few things:

* Pod GC - we should manually GC pods the way we do garden containers currently.
* Streaming build logs back to the ATC
* Hijacking/intercepting a step

This issue is to add a sidecar container to every pod to allow us to do these things.

**Comment by ddadlani** [comment]
We do still need to deal with the things above, but it might not be through using a sidecar. Feel free to change the title as required.

**Comment by nader-ziada** [comment]
Covered in #4295
