### ISSUE TITLE
Can't access Resource Check log output (stderr) for successful checks

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#406]
It's difficult to debug custom resources since debug logs are only available when checking fails.

Two suggestions:
1) the fly watch command could support watching a resource check stderr output
2) the web ui could allow the logs for a resource to be expanded even in successful states

**Comment by tomyan** [comment]
Also finding it difficult without being able to see messages from the check (even in success) - to the extent I'm modifying the custom resource to fail, just so I can see the messages.

**Comment by draeron** [comment]
i am in the same situation, i have a custom resource which return a successful check but i see no metadata. Right now it's almost impossible to figure out what was sent to my resources and what was answered.

This wouldn't need to be in the UI (that'd be nice though) but at least some workaround with the `fly` command line would be very useful. For example when manually doing a `fly check-resource`

**Comment by vito** [comment]
@draeron fwiw metadata doesn't get saved until a `get` or `put` runs - it's not immediately available from `check`. this will be changed by concourse/rfcs#1

**Comment by draeron** [comment]
i am in the same situation, i have a custom resource which return a successful check but i see no metadata. Right now it's almost impossible to figure out what was sent to my resources and what was answered.

This wouldn't need to be in the UI (that'd be nice though) but at least some workaround with the `fly` command line would be very useful. For example when manually doing a `fly check-resource`

**Comment by draeron** [comment]
thx, good to know!

still having a way to get the stderr output of the resource during the check would be useful for developing custom resources.
