### ISSUE TITLE
add yarn task to run Lighthouse analysis

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4062]
https://developers.google.com/web/tools/lighthouse/ gives some pretty interesting information. It could be a decent way to get earlier feedback on some scale/performance problems in the UI.

**Comment by jomsie** [comment]
<img width="882" alt="Screen Shot 2019-07-26 at 11 55 17 AM" src="https://user-images.githubusercontent.com/2362482/61964608-4510d200-af9c-11e9-847c-054e0f135026.png">

👀
