### ISSUE TITLE
Builds can get stuck pending when the ATC restarts before it is started

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#4065]
For pipelines that have serial true jobs, builds can be stuck in pending if the ATC restarts between the time that it is scheduled but not yet started. (Within this time frame in the code https://github.com/concourse/concourse/blob/master/atc/scheduler/buildstarter.go#L159-L194) 

It gets stuck because the pending build becomes scheduled but then gets lost when the ATC restarts and since the job is set to serial true, it finds that pending build when we try to fetch all running builds by serial group (https://github.com/concourse/concourse/blob/90a604c940b240a520b284e9a4ba5ad7062c4189/atc/scheduler/maxinflight/updater.go#L46) and we return that same pending build here https://github.com/concourse/concourse/blob/90a604c940b240a520b284e9a4ba5ad7062c4189/atc/scheduler/maxinflight/updater.go#L52. 

One possibility to fix this bug is to make it so that we check if the build returned by the running builds by serial group is the same as the one we are trying to start.

**Comment by pivotal-jwinters** [comment]
Can we just make that whole block atomic?

**Comment by vito** [comment]
This will be delivered in 6.0 with the new algorithm.

**Comment by clarafu** [comment]
Closing because it is completed with #3602
