### ISSUE TITLE
Fix breaking topgun build caused by extra creating container

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4070]
https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-topgun/builds/469 is failing because of the fix in #3301. 

The topgun test runs two identical `get` steps in quick succession, which causes two creating containers to be formed, but one of them is not required because that second `get` will end up finding the resource cache from the first one. 

In addition, the second creating container is never removed from the db, which is also problematic.

**Comment by marco-m-pix4d** [comment]
@ddadlani does this ticket require a `bug` label?

**Comment by marco-m-pix4d** [comment]
@aledeganopix4d FYI
