### ISSUE TITLE
Concourse does not renew the vault token by itself.

### ISSUE THREAD

**Issue by kaaustubh** [concourse/concourse#4077]
## Bug Report

Vault token in configured in /etc/concourse/web_enviroment file.
As per the documentation, the token should get renewed after half of its ttl. 
But concourse does not renew it.

## Steps to Reproduce

1. Configure the vault token with properties- orphaned, renewable and say ttl 10 mins.

## Expected Results

The token should get renewed by concourse after 5 mins.

## Actual Results

The vault token doesn't get renewed 

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work?: it used to work for concourse V 3.x

**Comment by marco-m** [comment]
@aledeganopix4d if I understand correctly it works for us. Could you please share our configuration?

**Comment by aledeganopix4d** [comment]
@kaaustubh We stumbled upon this ourselves.
The trick is that the token in Vault must be configured as `periodic` as explained here: https://www.vaultproject.io/docs/concepts/tokens.html
Once you set that property then Concourse correctly renew the token.

**Comment by kaaustubh** [comment]
The vault token which we configured has following properties
1. Renewable
2. Limited validity
3. Orphaned

**Comment by aledeganopix4d** [comment]
> The vault token which we configured has following properties
> 
> 1. Renewable
> 2. Limited validity
> 3. Orphaned

The `periodic` property is necessary to allow Concourse to auto-renew the token.

**Comment by kaaustubh** [comment]
I thought Renewable is periodic.. isn't it? ie the Token can be renewed periodically.

**Comment by aledeganopix4d** [comment]
> I thought Renewable is periodic.. isn't it? ie the Token can be renewed periodically.

I was confused by it as well at first, but if you read the Vault documentation clearly explain why you **need** to use `periodic` if you have a service that renews the token automatically: https://www.vaultproject.io/docs/concepts/tokens.html#periodic-tokens

**Comment by kaaustubh** [comment]
Alright, let me request such kind of token from our vault team and test it.
Once tested, I will post my results here.

**Comment by kaaustubh** [comment]
Sorry, I had forgotten.
The token that we had, already had period property set to true.
TTL: Max
orphaned (y/n): yes
periodic (y/n): Yes

And it didn't work.

**Comment by cirocosta** [comment]
@aledeganopix4d @kaaustubh there's been some recent improvements in the Vault cred mgmt docs:

**Comment by cirocosta** [comment]
(whops, clicked the wrong button)

**Comment by eedwards-sk** [comment]
alternatively, use approle authentication which doesn't seem to have this issue
