### ISSUE TITLE
Propagate FindOrCreateContainer context cancellation to BaggageClaim

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4080]
We introduce a `context.WithTimeout` to FindOrCreateContainer as part of fixing https://github.com/concourse/concourse/issues/3928. We inlined a modified version of the Garden client that uses this context so that if a worker becomes unresponsive (or is restarted), the ATC-side goroutine doesn't block forever, holding onto locks and doing other bad things to the machine.

We should do the same context propagation for Baggage Claim!

I think this is the main interface that needs to be changed: https://github.com/concourse/concourse/blob/master/atc/resource/versioned_source.go#L18-L19

**Comment by ddadlani** [comment]
closing this in favor of #4166
