### ISSUE TITLE
allow reading build badges without exposing the pipeline

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/concourse#4082]
## What challenge are you facing?

I'd like to include build status badges in my source code repositories without having to also expose the pipeline.

## What would make this better?

Being able to view build status badges (jobs or pipelines) without having to expose the pipeline.

## Are you interested in implementing this yourself?

No

**Comment by rixx** [comment]
Seems to be a duplicate of #996

**Comment by eedwards-sk** [comment]
@rixx thanks for finding that issue

closing as duplicate
