### ISSUE TITLE
Fly does not respect disabling ipv6

### ISSUE THREAD

**Issue by enugentdt** [concourse/concourse#4083]
## Bug Report

IPv6 is disabled on my system, yet when it tries to connect to my CI instance, it provides the following error:

```
Get https://ci.demilletech.com/api/v1/info: dial tcp [2606:4700:30::6812:3c20]:443: connect: no route to host
```

I'd expect it not to use v6, but it appears to be doing so? Then again, it's _very_ possible I'm screwing this up.

## Steps to Reproduce

1. Disable IPv6 on system
2. Ensure that your CI instance is v6 accessible, and the DNS record returns A and AAAA. Force it by returning no A record

## Expected Results

Ideally, it would not use v6 when it is disabled, however, it very much could be myself.

## Actual Results

Fly uses IPv6 instead of v4

## Additional Context

Running on Mac OS X 10.14

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: Custom
* Browser (if applicable): curl
* Did this used to work? Yes

**Comment by marco-m** [comment]
Hello,

>     1. Disable IPv6 on system

For reproducibility, how do you do this?

> `dial tcp [2606:4700:30::6812:3c20]:443: connect: no route to host`

Seems reasonable to me. For me to understand better, what would you expect instead? That it stopped after the DNS lookup just before the dial, since the DNS record is AAAA and IPv6 is disabled?

**Comment by enugentdt** [comment]
On a Mac, you can go into System Preferences > Networks > Advanced > TCP/IP, select the IPv6 dropdown, and disable.

The error is reasonable, sure, however, there is an alternate IPv4 address being returned with the DNS record, and I would expect that to be used instead. Ideally, throw out an IPv6 answer, though, this may be more than a little out of scope

**Comment by eedwards-sk** [comment]
may be related to underlying golang behavior e.g. https://github.com/golang/go/issues/25321
