### ISSUE TITLE
Better messaging for 'waiting for a suitable set of input versions'

### ISSUE THREAD

**Issue by vito** [concourse/concourse#409]
There are a lot of ways to get stuck at this part of the build preparation. It'd be nice if it showed which inputs are not yet available, and a reason for each one.

The reason could be one of:

* With `version: {...}`, the pinned version may not be available.
* There may be *no* versions of the resource available, if the source is misconfigured or `check` is failing or all versions are disabled.
* With `passed: [...]`, there may be no versions that satisfy the constraints.

They should be checked for in that order, since there's some overlap (e.g. version pinning + `passed` constraints - more useful to say if the pinned version doesn't exist at all).

**Comment by jmcarp** [comment]
Was this resolved? I still (using 2.0) run into "waiting for a suitable set of input versions" with no further explanation in some cases.

**Comment by jcderr** [comment]
i'm running into this as well.

**Comment by devorbitus** [comment]
me too

**Comment by aturnerbulldawg** [comment]
I am seeing this too and it doesn't seem to be any of the reasons mentioned above

**Comment by devorbitus** [comment]
I switched from multiple worker servers back to a single server and the issue went away

**Comment by benmoss** [comment]
Having this problem on 2.2.0 and not sure how to figure out what Concourse is waiting on

**Comment by staylor14** [comment]
We got into a state where there were two gets of the same resource, one of which has a `passed` constraint and one of which didn't. There was a newer version available without the constraint than with, and it sat there waiting for a suitable set of versions indefinitely.

We added a separate resource name to work around this, but the message was still super unclear, just "waiting for a suitable set of input versions."

**Comment by seanwolfecsaa** [comment]
I'm seeing this as well. We have a new concourse installation and I'm using the configurations from our previous server. My new job sticks on 'waiting on a suitable set of input versions' for hours.

**Comment by clfsoft** [comment]
same error  all jobs sticks on waiting for a suitable set of input versions.
v2.4.0  bosh aws
