### ISSUE TITLE
Attempting to drag-to-reorder pipelines in sidebar breaks entire page

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#410]
Chrome 49.0.2623.87 (64-bit) on Mac OSX 10.10.5

Not sure if there is a way to reorder pipelines in the sidebar, but I did what would be natural to me, i.e. drag-to-reorder and the moment I click and drag a pipeline name, my cursor stays as a pointer and nothing happens and then nothing is clickable.

It persists even when you refresh the pages. Only way to cause the web view to work again is to close the tab and open a new one.

**Comment by vito** [comment]
This was redone in Elm so I'm assuming it's magically better now.
