### ISSUE TITLE
Allow to specify the text for a badge

### ISSUE THREAD

**Issue by rixx** [concourse/concourse#4105]
## What challenge are you facing?

All badges currently bear the title "build", next to the build status. A project will often have several relevant badges to display, but they look interchangeable.

## What would make this better?

I think the solution that has the least impact on people already using the badge feature would be to allow to specify the badge title via the URL (`?title=documentation`, for instance). This is how shields.io does it, too.

## Are you interested in implementing this yourself?

I haven't got any experience with go projects, but sure, if somebody helps me through the process, I'd be happy to work on this.

**Comment by vito** [comment]
Makes sense! Seems like this would just need to be passed to the templates [here](https://github.com/concourse/concourse/blob/b1a1b19d6a7b032c487946a590fa4181739635ad/atc/api/jobserver/badge.go#L85). 👍
