### ISSUE TITLE
SIGSEGV on startup

### ISSUE THREAD

**Issue by dsyer** [concourse/concourse#4107]
After `fly sync` to 5.3.0:

```
$ fly targets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x95a0df]

goroutine 1 [running]:
github.com/concourse/concourse/fly/commands.GetExpirationFromString(0xc0001ec480, 0xc0001ec600, 0x1)
	/tmp/build/8885cc21/concourse/fly/commands/targets.go:59 +0xef
github.com/concourse/concourse/fly/commands.(*TargetsCommand).Execute(0x1071e70, 0xc0001d1360, 0x0, 0x1, 0x1071e70, 0x1)
	/tmp/build/8885cc21/concourse/fly/commands/targets.go:33 +0x4c7
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000068e40, 0xc00000c0b0, 0x1, 0x1, 0x40584f, 0xc0000300b8, 0x0, 0x0, 0x963241)
	/tmp/build/8885cc21/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8ce
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/tmp/build/8885cc21/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
	/tmp/build/8885cc21/concourse/fly/main.go:24 +0x148
```

**Comment by cirocosta** [comment]
Hi @dsyer ,

Thanks for submitting the issue!

Seems like it's related to us not being very careful with `parsedToken` here 😅:

https://github.com/concourse/concourse/blob/2c3e9dd527a332bd5816228ff67596da5bcf791f/fly/commands/targets.go#L55-L59

Seems like we could take a more defensive approach like in `status.go`: https://github.com/concourse/concourse/blob/2c3e9dd527a332bd5816228ff67596da5bcf791f/fly/commands/status.go#L27-L40

@xtremerui I've been seeing you the most around `fly` overall - wdyt of marking this `good first issue`?

Thanks!

**Comment by xtremerui** [comment]
@cirocosta cool go ahead thx!

**Comment by vijayb47** [comment]
Facing the same issue. Any work around meanwhile?
I am still able to 
 `fly -t team-target login`
