### ISSUE TITLE
Make auto-collapsed failed steps easier to notice

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4111]
Follow-up to #4058 / #4051 - failed steps no longer auto-expand, which is nice because it keeps them from shoving other failed steps offscreen, but I find it hard to notice *which* step failed.

For example:

![image](https://user-images.githubusercontent.com/1880/60903695-cc8ddf80-a23f-11e9-96a1-7fa793b4ee70.png)

That little ❌ is a bit hard to notice, mainly because I tend to look at the left side of the screen I guess, and it's pretty far from the step name making it hard to scan over and see what step it is.

Maybe we could make the whole header background for the step red? 😮 

/cc @pivotal-jamie-klassen @Lindsayauchin

**Comment by Lindsayauchin** [comment]
@vito How about adding a red (#C24433) outline to failing steps?

![Make auto-collapsed failed steps easier to notice #4111](https://user-images.githubusercontent.com/27746614/60994465-95423000-a31e-11e9-9413-04f80d7b7015.png)
