### ISSUE TITLE
5.3.0 Runtime Error - Out of Memory

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/concourse#4113]
## Issue Overview

This morning a concourse web node's process died. After investigation, logs revealed the following:

```
concourse-web[1452]: fatal error: runtime: out of memory
```

(see [full gist](https://gist.github.com/eedwards-sk/a6cbcbe58999fb423da40a71fa78895f) for error stacktrace)

Investigation revealed the system was never under low memory pressure:

![image](https://user-images.githubusercontent.com/34585329/60981869-bf82f600-a2fc-11e9-8950-44cfdba44c27.png)

No evidence of OOM Killer in the kernel logs, either. The system did not run out of memory.

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): N\A
* Did this used to work? First time this has crashed due to OOM

**Comment by eedwards-sk** [comment]
For posterity, apparently this is a datadog metrics issue.

Even though no OOM Killer messages happened, looks like my "percent used" metric is incorrect.

Closing as PEBCAK :)

**Comment by eedwards-sk** [comment]
I'm actually still investigating this. It might be an underlying golang issue.

The system should have been able to free up the cached memory.

**Comment by eedwards-sk** [comment]
I'm re-opening this.

Based on the stack trace:

```
runtime.growslice(0x1cee200, 0xc00bff1180, 0x4, 0x4, 0x5, 0x0, 0x0, 0x0)
    /usr/local/go/src/runtime/slice.go:181 +0x1e6 fp=0xc00bf934e8 sp=0xc00bf93480 pc=0x44fd26
github.com/concourse/concourse/atc.collectPlans(0x0, 0x0, 0xc00bf291d8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /tmp/build/70f2e240/concourse/atc/job_config.go:101 +0x7f1 fp=0xc00bf94370 sp=0xc00bf934e8 pc=0x84b731
```

It looks like during atc.collectPlans

https://github.com/concourse/concourse/blob/master/atc/job_config.go#L101

growslice ends up getting called, which resulted in the OOM (following down the stack)

Based on some general research, it seems like perhaps this memory allocation call ended up requesting too much memory at once (more than available on the system). However, this would have had to have been at least 250MB+ worth, as I had significant cached/freeable memory at the time

**Comment by pivotal-bin-ju** [comment]
Do you have sampled pipelines that may be helpful to understand this issue?

**Comment by eedwards-sk** [comment]
No, sorry. I don't have an easy way to reproduce this yet.

When I relaunched the process it was fine.

**Comment by prateeksisodia** [comment]
@eedwards-sk were you able to resolve this, my concourse version is 5.2.0 and since past few days i ma getting this OOM issue intermittently.
if you can help here:
https://github.com/concourse/concourse/discussions/6024#discussioncomment-58730
