### ISSUE TITLE
fly: 'delete-target' with command option -a not working as expected

### ISSUE THREAD

**Issue by Jayasankar-m** [concourse/concourse#4114]
## Bug Report
The fly command with 'delete-target' does not work as expected with -a command option

## Steps to Reproduce

create a target using fly command
```fly login -t <target> -c http://<url>:8080 -u <username> -p <password>```

try to delete all targets using command
```fly delete-target -a```
(without giving any target name)

## Expected Results
All targets should get deleted as per the documentation
https://concourse-ci.org/fly.html#fly-delete-target

## Actual Results
Following error is shown
```
no target specified. specify the target with -t or log in like so:

    fly -t (alias) login -c (concourse url)
```

## Additional Context
if a target is also specified as follows then all entries are getting removed
```fly -t <target> delete-target -a```

## Version Info

* Concourse version: 5.3.0

**Comment by pivotal-bin-ju** [comment]
A PR was drafted for this: https://github.com/concourse/concourse/pull/4172/commits/cd77717cdeab44e4163c5e4209bf0a4ef96d7de5
