### ISSUE TITLE
[web] Broken custom http prefix path

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#4115]
We have concourse mounted on a custom path prefix (going through traefik)

https://build.haiku-os.org/concourse/

  concourse is broken, and looks to be assuming / for artifacts on the server.

I tried setting:
  CONCOURSE_EXTERNAL_URL: https://build.haiku-os.org/concourse/

however, it doesn't seem to solve the problem.

**Comment by evanchaoli** [comment]
This should be a dup of issue #942 . Looks like Concourse doesn't support from day 1.

**Comment by pivotal-jamie-klassen** [comment]
@evanchaoli is correct this is a dupe of #942 and I think that's the best issue to center the discussion around.
