### ISSUE TITLE
UI crashes with too many events

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#412]
When we have a build that is extremely verbose (e.g. https://runtime.ci.cf-app.com/pipelines/cf-release/jobs/cf-release-unit-tests/builds/1473) it crashes chrome. Haven't tested this with other browsers, but it's a pretty poor user experience, as it's not initially obvious what is going wrong, and we can't see any build output.

**Comment by vito** [comment]
For me it says "loading" until the front falls off, which sounds more like a Chrome bug. If you've got a lot of output it's of course going to take longer to render, and of course a crash is bad UX. But there's not a lot we can do here without some sort of stack trace. How large is the output from `fly watch`?

I've had success reporting crashes to Google before - have you tried that?

**Comment by vito** [comment]
There's not a lot for us to go on here; browser crashes should be reported to whoever's making the browser. With Chrome there's not even a good way to get a stack trace without first reporting it to them.
