### ISSUE TITLE
Concourse web is not working with a nginx location different to "/"

### ISSUE THREAD

**Issue by chromz** [concourse/concourse#4123]
## Bug Report

When concourse web is deployed under a nginx location different than "/"  it shows a blank page with some JavaScript errors and warnings on the console.

## Steps to Reproduce

* Set nginx as a reverse proxy to a concourse web interface with a location different to "/" like "/concourse"  ([example config](https://gist.github.com/chromz/c2221aa0f99be7c693f585a1b28710d1)) 
* Set CONCOURSE_EXTERNAL_URL to "\<domain name\>/concourse" (e.g "www.somedomain.com/concourse")
* Enter to \<domain name\>/concourse from a web browser

## Expected Results

A functional concourse web interface

## Actual Results

A blank page with [this](https://gist.github.com/chromz/649f896f7d8a214fc368c9ac43babb7e) console output.

## Additional Context

As you can see in the console output, the search paths of the static files are wrong, as they should be preceded by "/concourse/" , I think this could be solved by just prepending CONCOURSE_EXTERNAL_URL to the url pattern of the http handlers.

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Digital Ocean
* Browser (if applicable): Firefox 68

**Comment by kallisti5** [comment]
I literally just opened a similar issue a few days ago :-)

https://github.com/concourse/concourse/issues/4115

Looks like you tried the same things I did.

**Comment by evanchaoli** [comment]
I think this is a dup of Issue #942

**Comment by pivotal-jamie-klassen** [comment]
Thanks for your great description, but let's close this and focus the discussion in #942. Some of the other consequences of this feature are being explored on that issue.
