### ISSUE TITLE
Improve `fly login` error message for nonexistent team

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#4126]
## What challenge are you facing?

When `fly login` with a team that does not exist, the error message looks like the following:

```
error: user [username] is not in team [teamname]
```

which is misleading to debug the issue.

## What would make this better?

Change the error message to something like "teamname does not exist"

## Are you interested in implementing this yourself?

maybe

**Comment by antonu17** [comment]
I faced exactly the same problem today. One of our users reported `error: user [username] is not in team [teamname]` which made me find the `[teamname]` doesn't even exist

**Comment by evanchaoli** [comment]
As a return to being granted triage permission, let me contribute a PR for this small enhancement. :)

**Comment by u5surf** [comment]
If `team Names` does not exists its elements, then I thought `checkTokenTeams` just returns error("teamname does not exist") Is it misunderstand?

**Comment by evanchaoli** [comment]
As my understanding, `checkTokenTeams` extracts teams from token, and check if login-team is one of token-teams. `checkTokenTeams` has no idea if login team exists or not.

**Comment by evanchaoli** [comment]
I'm closing this issue because currently there is no way to make enhancement as only admin user can get a full list of teams.

**Comment by analytically** [comment]
Upgrading to 6.2.0 I'm getting this error.

**Comment by jamieklassen** [comment]
@analytically are you trying to log in to a nonexistent team? or are you just seeing a similar error message to the one described here? if so, I wonder what version you were upgrading _from_ and whether you re-downloaded or synced fly - because there were [breaking changes to auth in v6.1.0](https://github.com/concourse/concourse/releases#4950)

**Comment by analytically** [comment]
Upgrading from 6.0.0 to 6.2.0, tried logging out and back in, still getting the same error on fly. error: user [] is not in team [main]

**Comment by jamieklassen** [comment]
did you re-download fly?

**Comment by analytically** [comment]
fly -t gc sync requires login which doesn't work

**Comment by jamieklassen** [comment]
actually, since v6.0.0 if you do fly sync and only pass the concourse URL it should work: https://github.com/concourse/concourse/releases/v6.0.0#4168

**Comment by analytically** [comment]
Ah indeed, running sync without login solve the issue.

**Comment by Yingsheng-eroad** [comment]
> actually, since v6.0.0 if you do fly sync and only pass the concourse URL it should work without login: https://github.com/concourse/concourse/releases/v6.0.0#4168

This was fixed since v6.

My local is 5.8.1. I get a error "unknown flag `concourse-url'",   when I try to run 'fly sync -c myurl'.

**Comment by jamieklassen** [comment]
@Yingsheng-eroad you'd need to download a new fly without using `fly sync`. You could probably do it the same way you downloaded fly in the first place -- through the web UI, or the `/api/v1/cli` endpoint, or the GitHub release. Hope that information is enough for you to figure it out!

**Comment by Yingsheng-eroad** [comment]
> @Yingsheng-eroad you'd need to download a new fly without using `fly sync`. You could probably do it the same way you downloaded fly in the first place -- through the web UI, or the `/api/v1/cli` endpoint, or the GitHub release. Hope that information is enough for you to figure it out!

That's helpful. I downloaded the new version and it worked well now. Thanks.
