### ISSUE TITLE
OIDC Secret with special characters fails

### ISSUE THREAD

**Issue by tybritten** [concourse/concourse#4127]
## Bug Report

If you configure an OIDC Client Secret that contains special characters it doesn't work

## Steps to Reproduce

deployed 5.3.0 via helm chart and configured OIDC settings there

## Expected Results

to authenticate 

## Actual Results

failed with this error message:
```Failed to authenticate: oidc: failed to get token: oauth2: cannot fetch token: 401 Response: {"error":"unauthorized","error_description":"Bad credentials"}```

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): Helm Chart
* Infrastructure/IaaS: PKS
* Browser (if applicable): Chrome
* Did this used to work?

**Comment by jama22** [comment]
Linking to #2097
