### ISSUE TITLE
UI not showing build logs

### ISSUE THREAD

**Issue by gnasr** [concourse/concourse#4132]
## Bug Report

 UI is not showing build logs randomly for most of the builds, keeps loading forever

## Steps to Reproduce

 Go to the build url and the build logs never finish loading

## Expected Results

The UI must show the build logs, since i can get them with fly and i can see the events querying the api directly.
Also i can see the output when i trigger the job from the UI but if i reload the browser i can't see it anymore.
```bash
fly -t concourse w -b 1188
179 B / 179 B [=========================================] 100.00 % 23.51 KB/s 0sinitializing
running go run git-repo/ci/tasks/json2files/main.go -f json-input/pr -o files-output
2019/07/14 02:42:18 Created file files-output/commit
2019/07/14 02:42:18 Created file files-output/pr
2019/07/14 02:42:18 Created file files-output/url
2019/07/14 02:42:18 Created file files-output/branch
2019/07/14 02:42:18 Created file files-output/base
2019/07/14 02:42:18 Created file files-output/author
initializing
2019/07/15 14:59:59 error opening file read /tmp/build/put: is a directory
initializing
missing inputs: artifacts
aborted
```
plan and events endpoints are showing the data correctly 
https://concourse/api/v1/builds/1188/plan
https://concourse/api/v1/builds/1188/events <-- events shows all the logs correctly

## Actual Results

 ![Screen Shot 2019-07-15 at 17 40 42](https://user-images.githubusercontent.com/3936970/61247576-ba241200-a727-11e9-8924-9cab44738e1a.png)

## Version Info

* Concourse version: 5.3.0, 5.2.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Kubernetes 1.11
* Browser (if applicable): Brave, Chrome, Firefox
* Did this used to work? Yes

**Comment by elsmorian** [comment]
We are seeing the same here, can't seem to find a pattern for which ones load and which do not.

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Kubernetes 1.13.7-gke.8 deployed via Helm
* Browser (if applicable): Safari, Chrome
* Did this used to work? Yes

**Comment by pikesley** [comment]
Same in Firefox

**Comment by stringfellow** [comment]
It seems to be the case that the resources load like this for a functional page:
* <event number>
* plan
* resources
* events

and for a dysfunctional page:
* <event number>
* plan
* resources
* *silence*

as @gnasr notes, you can still get to the events stream and read the output by navigating directly to it

**Comment by eedwards-sk** [comment]
I see this on aborted builds. Are you seeing it on non-aborted builds?

**Comment by gnasr** [comment]
It happens mostly in aborted builds, but it also happens sometimes in failed and successful builds 
![Screen Shot 2019-07-17 at 14 43 33](https://user-images.githubusercontent.com/3936970/61397961-63dade80-a8a1-11e9-99e6-28c632b4802c.png)

**Comment by eedwards-sk** [comment]
Do you have any kind of network filtering in place? I've seen certain A/V or endpoint protection software interfere with concourse web UI logs.

e.g. I have to disable Sophos entirely for concourse web ui logs to work on my workstation

**Comment by gnasr** [comment]
nope, i've seen the other github issues with similar description but it seems to be different, i couldn't find anything in my computer blocking connections neither my coworkers. I've tried disabling adblockers too

**Comment by elsmorian** [comment]
@stringfellow @pikesley and I all see it on failed, running and completed builds. It's maybe 10-20% of them for us, most of them work but some do not so unlikely to be network filtering etc. (We do not run such software anyway)

**Comment by stringfellow** [comment]
An interesting (?) data point: On one part of our pipeline, the details *never* load for any of 48 runs, *except* for one which failed in 13 seconds. All the other ones take upward of 1 minute. I'm not sure why this would be pertinent except that maybe it has to do with Server-Sent Event stream size?

**Comment by stringfellow** [comment]
That last comment may be a red herring as we have other stages with all sorts of run times which show up fine. Another suspicion is some value in the payload of each event ... but it seems like the events aren't even being called for and from the console for detail views that work the initiator of the events request is 'Other' so not easy to diagnose further.

**Comment by gnasr** [comment]
Well after debugging a lot, we found the problem.
We were using a custom resource that didn't have version field in check and put commands output, so the issue was the same as https://github.com/concourse/concourse/issues/1977 
After fixing that the logs of the previous and new builds appeared again.
The pattern that helped us find this was that not all the jobs were using this custom resource.

**Comment by pikesley** [comment]
This is great @gnasr , what _exactly_ does your resource output? I can't find this documented properly anywhere. 

My (Python) scripts exit with  something like `print(json.dumps({"version": "1"}))`

and I'm seeing errors like 

* `json: cannot unmarshal string into Go struct field VersionResult.version of type atc.Version` 
* `json: cannot unmarshal array into Go value of type resource.VersionResult`
