### ISSUE TITLE
fly <command> --help not outputting command specific help

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#4134]
## Bug Report
When running `fly <command> --help` on the latest rc fly binary, the top-level fly help menu is displayed instead of the command specific help menu

## Steps to Reproduce

`fly get-pipeline --help` or any other command

## Version Info

* Concourse version: latest rc (5.4.0)
* Did this used to work? Yes on `5.3.0`

**Comment by pivotal-jamie-klassen** [comment]
maybe related to the changes in #4064?

**Comment by taylorsilva** [comment]
That was it!

Check out `69b234b5c4382ecba7cccdeecd524ce6034b8f7c` which is the commit right before #4064. Can't reproduce the bug. After those commits (`914593c6d67b03c895ec01c307c96e884994181f`) we get this new behaviour.
