### ISSUE TITLE
default value for ((vars))

### ISSUE THREAD

**Issue by xNok** [concourse/concourse#4135]
## What challenge are you facing?

I made a template for my pipeline and uses a variable files to make it modular. However as I want to keep my pipeline modular my variable file grows significantly.

## What would make this better?

Having to option to define a default value for a variable would reduce the need for a complet variable file. Only required variables would be in the varible file.

We could imaginate the folowing notation:
```
((some.key:my default value))
```

## Are you interested in implementing this yourself?

Most likely yes, if this answers a need

**Comment by pivotal-jamie-klassen** [comment]
Thanks for posting! I think this is interesting and worth discussing more, but before digging into the technical details, can you describe your use case in a little more detail?
* are these variables sitting in job/resource/task configs at the pipeline level? or in task configs that get resolved from files?
* should they be kept secret?
* are they being passed as `params` to a step?
* if you're able, maybe you could share your templated pipeline?
* does the template get re-used across different teams?

I wonder how you would feel about using a [credential manager](https://concourse-ci.org/vault-credential-manager.html#vault-credential-lookup-rules) for these variables, too. In that case you can set a team-wide default that can be overridden in individual pipelines.

**Comment by xNok** [comment]
`are these variables sitting in job/resource/task configs at the pipeline level? or in task configs that get resolved from files?`
Pipeline level

`should they be kept secret?`
We manage secret with vault so no issues with that. Only sensitive variable should be added to vault. I am sceptical towards using *the credential manager* as some kind of *config server*.

`are they being passed as params to a step?`
Yes, 
_A good exemple_ is when you have a repository git that provide the script for your task. Our if you manage your environnement base on git ops principle. The you are tempted to create the following variables:
```yaml
git-env-branch: "master"
git-env-tag_filter: "1.4.*"
```
And use them ass param pour the git-ressource. Most team will use the stable environnement from the branch master, with a given major.minor. While a few of them will upgrade or use an alternative branch.

_Another example_. Teams don't all have the same maturity in terms of testing and continuous delivery, therefore we ended up adding a variable.

```yaml
continuous-delivery: true
```
Then the team may decide if a deployment is automatically triggered
```yaml
- get: git
  passed: [xxx, zzz]
  trigger: ((continuous-delivery)) 
```

`does the template get re-used across different teams?`
Yes it does, and we notice that is easier for our teams to edit and understand variable file with a lot of comments than the pipeline itself (that can got up to a 1000 lines) even with comments and documentation.

**Comment by aegershman** [comment]
Just curious, is there a way a default (we'll call `default-params.yml`) could be provided with default key/value pairs, and then when teams use the pipeline they provide their own `override-params.yml` (or some name) that selectively overrides the key/values that they need? Then they could do `fly -t myteam set-pipeline -p somepipeline -l default-params.yml -l override-params.yml`? Basically instead of putting the default values in the pipeline.yml itself, you provide all the defaults in a provided params file & if consumers decide there are key/values that are different from the default, they only need to provide those keys in the `override-params.yml`? Not trying to undercut your suggestion, just sharing this because it's a pattern we use at work a lot.

**Comment by pivotal-jamie-klassen** [comment]
linking https://github.com/cloudfoundry/bosh-cli/issues/502 since I believe that's the library we're using

**Comment by pivotal-jamie-klassen** [comment]
actually, since #3505 was merged, the vars syntax is under our control...

**Comment by jamie-pate** [comment]
@jamieklassen Can you elaborate on how #3505 helped manage your vars so that this feature is no longer needed? I'm trying to re-use a task.yml several times with a default `cpu_limit: 2` var so that I can only specify `cpu_limit: 4` on the 'big' task.
