### ISSUE TITLE
could not abort a job when it is pending

### ISSUE THREAD

**Issue by pivotal-bin-ju** [concourse/concourse#4154]
## Bug Report

Could not abort a job when it is pending

## Steps to Reproduce

Assume there are `Job A` and `Job B` in the pipeline. `Job A` `pass` to `Job B`.

1. Trigger `Job B` directly. (Without triggering `Job A`). `Job B` should be pending.
1. Abort the build for `Job B`.

## Expected Results

`Job B` is aborted.

## Actual Results

`Job B` is stuck in pending.

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP

**Comment by concourse-github-dummy** [comment]
This morning I made a pipeline tested this, we do not have this problem. I will close this.

**Comment by pivotal-bin-ju** [comment]
This morning I made a pipeline and tested it with the latest code. The result was we could cancel the build. I will close this.
