### ISSUE TITLE
Error: failed to stream in to volume; Concourse attempting to access a volume before it is created, resulting in the volume not being found.

### ISSUE THREAD

**Issue by whit-fackler-ml** [concourse/concourse#4155]
## Bug Report

In some situations I am seeing repeated build failures (errors) with only the message "failed to stream in to volume". 
In general:
- Several tasks run (mostly on a linux worker).
- A task runs (integration tests are run on a macOS server), and test results are placed in a folder.
- I attempt a put step to upload those results to S3.
- The put step fails almost immediately with the message "failed to stream in to volume".
A subsequent fly hijack shows the expected file to be uploaded.

Timestamps from the Concourse logs on my linux worker seem to indicate an attempt is made to find/access the volume before the volume itself is created.

> Jul 22 21:03:29 ip-172-31-67-89.ec2.internal bash[3118]: {"timestamp":"2019-07-22T21:03:29.485887065Z","level":"info","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.get-volume.volume-not-found","data":{"session":"3.1.28281.1","volume":"0eba59f1-619c-47db-4120-e2949f26127b"}}
> Jul 22 21:03:29 ip-172-31-67-89.ec2.internal bash[3118]: {"timestamp":"2019-07-22T21:03:29.485926652Z","level":"info","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","data":{"session":"3.1.28281","volume":"0eba59f1-619c-47db-4120-e2949f26127b"}}
> Jul 22 21:03:33 ip-172-31-67-89.ec2.internal bash[3118]: {"timestamp":"2019-07-22T21:03:33.504441871Z","level":"info","source":"guardian","message":"guardian.api.garden-server.create.created","data":{"request":{"Handle":"d9bef122-03c6-4572-5121-89031b0ebc0c","GraceTime":0,"RootFSPath":"raw:///var/db/concourse/volumes/live/55790b0f-5508-4ebd-729a-6be6a9331155/volume","BindMounts":[{"src_path":"/var/db/concourse/volumes/live/8f1c8755-cc36-4011-7618-3423262e9644/volume","dst_path":"/scratch","mode":1},{"src_path":"/var/db/concourse/volumes/live/cd3b56aa-7eb2-40e4-5ecb-8c2c03ffdc64/volume","dst_path":"/tmp/build/put","mode":1},{"src_path":"/var/db/concourse/volumes/live/7c1d98f6-9d29-4519-7f43-7fe5d9755e57/volume","dst_path":"/tmp/build/put/android-agent","mode":1},{"src_path":"/var/db/concourse/volumes/live/69b585a1-157b-42c6-57e7-602c9434a489/volume","dst_path":"/tmp/build/put/android-device-control","mode":1},{"src_path":"/var/db/concourse/volumes/live/fb0f6f80-1551-406d-5cce-da55ca149fcc/volume","dst_path":"/tmp/build/put/android-trust-browser","mode":1},{"src_path":"/var/db/concourse/volumes/live/e7fcdb57-dc0b-41cf-6473-a457847e0b79/volume","dst_path":"/tmp/build/put/android-trust-server","mode":1},{"src_path":"/var/db/concourse/volumes/live/12514010-4cf6-4cb1-6f1e-8467219c7ee8/volume","dst_path":"/tmp/build/put/build-generic","mode":1},{"src_path":"/var/db/concourse/volumes/live/0eba59f1-619c-47db-4120-e2949f26127b/volume","dst_path":"/tmp/build/put/devicebridge-osx","mode":1},{"src_path":"/var/db/concourse/volumes/live/53e964b9-1272-457a-4f9d-41a51fec5acb/volume","dst_path":"/tmp/build/put/devicebridge-windows","mode":1},{"src_path":"/var/db/concourse/volumes/live/26c0eca4-4cdf-42f9-4880-3d83222dd9ec/volume","dst_path":"/tmp/build/put/deviceconnect-server","mode":1},{"src_path":"/var/db/concourse/volumes/live/5aad3e4f-ec40-443f-74c3-585be76bb297/volume","dst_path":"/tmp/build/put/deviceconnect-test","mode":1},{"src_path":"/var/db/concourse/volumes/live/c7dabf42-4060-4629-4ed8-5e43499f5016/volume","dst_path":"/tmp/build/put/deviceconnect-test-results","mode":1},{"src_path":"/var/db/concourse/volumes/live/27a56e96-c836-4568-7cd8-eeedac768cc5/volume","dst_path":"/tmp/build/put/devicekey","mode":1},{"src_path":"/var/db/concourse/volumes/live/753cbccd-4f73-470c-48e6-d06df3b5c52e/volume","dst_path":"/tmp/build/put/docs","mode":1},{"src_path":"/var/db/concourse/volumes/live/b83fad95-a2f3-441b-7f1d-0a192a5dd451/volume","dst_path":"/tmp/build/put/ios-provisioning-tool","mode":1},{"src_path":"/var/db/concourse/volumes/live/2e303bf7-7444-4012-6200-f1d2e62055d2/volume","dst_path":"/tmp/build/put/minicap","mode":1},{"src_path":"/var/db/concourse/volumes/live/2a92f2f6-48e5-4f8b-46ed-d98398fb706e/volume","dst_path":"/tmp/build/put/ml2","mode":1},{"src_path":"/var/db/concourse/volumes/live/1513fb0b-1ab7-4fdc-4c22-1a0725a76e72/volume","dst_path":"/tmp/build/put/subset","mode":1},{"src_path":"/var/db/concourse/volumes/live/f9dec8da-9b1c-4831-6669-a450159af244/volume","dst_path":"/tmp/build/put/subset-svcrestart","mode":1},{"src_path":"/var/db/concourse/volumes/live/af4e131f-9967-4c6f-7aa8-d0da1f0e6cec/volume","dst_path":"/tmp/build/put/svcrestart","mode":1},{"src_path":"/var/db/concourse/volumes/live/db676dba-cc49-4989-6c61-4c565e84b3d1/volume","dst_path":"/tmp/build/put/trust","mode":1},{"src_path":"/var/db/concourse/volumes/live/c4bc589f-e9b5-4dbf-6c30-7e6628cc632e/volume","dst_path":"/tmp/build/put/version-number","mode":1}],"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"3.1.25889"}}

There are no additional references to the volume "0eba59f1-619c-47db-4120-e2949f26127b" in this section of the logs.

I have not noticed the same issue when attempting to upload 

## Steps to Reproduce (Updated after additional testing)

- Perform GET steps to clone a (git) repo and pull in artifacts built in previous steps (from S3).
- Perform a build (which runs on a linux container on a linux worker).
- Upload the artifact created by the build to S3.
- Perform a set of integration tests on a macOS worker, writing the logs directly to my desired "file" param of the PUT step.
- Attempt to upload the results of the integration tests to S3.

## Expected Results

A resource is uploaded to S3.

## Actual Results

The put step errors: "failed to stream in to volume".

## Additional Context

This job has been failing consistently since upgrading to Concourse 5.4.0 (Previously working on v. 5.0.1). Other jobs performing builds/tests on macOS, Windows, and Linux workers are able to complete their tasks and upload the artifacts to S3.

The job that fails is one of the longer-running jobs in the pipeline. It appears a volume and/or container created in an earlier task might be incorrectly removed at some point while the macOS task is running. However, after the failure I am able to connect via fly hijack and view the file I expect to have been uploaded to S3.

Update:
The job seems to work fine if I write the result data to temp file, then move it into the output location.

## Version Info

* Concourse version: 5.4.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: Linux master, workers and windows workers hosted in AWS. macOS worker hosted in a datacenter outside of AWS.
* Browser (if applicable): Chrome
* Did this used to work? Yes (as of Concourse v5.0.1).

**Comment by kcmannem** [comment]
Are you seeing this type of failure only on macOS tasks?

**Comment by whit-fackler-ml** [comment]
> Are you seeing this type of failure only on macOS tasks?
Yes, I have only seen this on a macOS task (although, its actually a subsequent put to upload the outputs of the macOS task that fails, not the task itself). It is a (compared to the other macOS tasks that do not have the same issue) longer-running task (specifically in the "initialization" portion - I assume this is because of a need to transfer an artifact from AWS to our datacenter). However, other longer running (and longer to initialize) macOS tasks do not have the same issue (a subsequent put to upload the outputs works fine).

**Comment by kcmannem** [comment]
According to that garden, That volume is bind mounted for the devicebridge-osx resource put.
```
      {
        "src_path": "/var/db/concourse/volumes/live/0eba59f1-619c-47db-4120-e2949f26127b/volume",
        "dst_path": "/tmp/build/put/devicebridge-osx",
        "mode": 1
      },
```
If you were to rerun this job, would the same devicebridge-osx volume fail. Or would it be a different volume every time.

**Comment by whit-fackler-ml** [comment]
If I were to rerun the job, it fails in the same way, but it is a different volume every time.

After doing some more testing with it (and comparing it to my other jobs that run builds on macOS but are still able to perform a put/etc afterwords) I was able to get some additional information (and a workaround...   maybe a resolution but it still doesn't quite seem to work the way I was expecting).

The following pattern:
> {{DO_SOME_BUILD}} >> output_folder/data
> end of task on the macOS worker
> put some resource with params file: output_folder/data
Fails with the error "failed to stream in to volume"

But if I do:
> {{DO_SOME_BUILD}} >> tmp/data
> tar zcvf output_folder/data tmp/data
> end of task on the macOS worker
> put some resource with params file: output_folder/data
The put task will upload that resource to S3 as expected, and the build continues.

I assume there is some kind of issue with the volume that output is on not getting...   "closed" (in the close file term?)  Or something similar....   so even though Concourse thinks it is there in the following steps, it throws and error.
However, moving a file into that folder (cp seems to have the same positive results as taring the file) signals to the system (at some level) that the file is "closed" and the subsequent steps are able to finish as expected.

In both scenarios, the macOS build portions return "Success", and the build will finish successfully if you don't try to access the outputs (of that task...   other outputs will work fine).

Im not sure if that is completely the intended way for it to work, but as long as I write to a directory outside of my output, then cp or mv or tar the artifact into the output, it seems to work.
