### ISSUE TITLE
Spike: Change garden to libpod?

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#4169]
The RedHat folks are betting on libpod / podman to run containers.  It's backed by some large companies, and sticks closely to the OCI (runc).  It's actively developed and supports userspace (non-root) containers.  It supports unmodified oci or docker containers, the tools are cli compatible with docker.  There is no (docker, containerd) daemon process.

It's written in go, and they provide libpod which podman uses under the hood.

Since development of garden seems a bit slow, it isn't well known outside of cloudfoundry, and there are several tickets about worker network issues / worker dns resolution issues / etc,  any thoughts on using libpod instead?

I know this isn't an easy thing, the goal here is just opening the discussion for any feedback.

https://github.com/containers/libpod
https://podman.io/

**Comment by kcmannem** [comment]
we have an investigation coming up for containerd. Garden had a containerd mode which basically translates its api to containerd api calls. That way we can test for a smoother transition.

Do you know if there are some advantages/disadvantages for using libpod over containerd?

We are planning to move out of garden. https://github.com/concourse/concourse/issues/4130

**Comment by kwri-avongluck** [comment]
https://opensource.com/article/18/10/podman-more-secure-way-run-containers is a pretty good article.  It uses traditional fork/exec and doesn't require root.

**Comment by kallisti5** [comment]
https://opensource.com/article/18/10/podman-more-secure-way-run-containers is a pretty good article. It uses traditional fork/exec and doesn't require root.

**Comment by sbkg0002** [comment]
+1 Garden needs to go.

**Comment by ddadlani** [comment]
Closing this, as we are looking to replace garden with containerd. In the future if someone would like to work on a `libpod` backend for Concourse, it would be welcome! Feel free to open a new issue for discussion.
