### ISSUE TITLE
More sharable,discoverable, versionable tasks

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#417]
Resources are a good mechanism for providing behavior - they are self-contained, which makes them discoverable, distributable, and composable, and they can be easily versioned. I think we need to provide a way for tasks (and possibly pipelines) to have the same attributes.

I'd like a way to find a way to encapsulate business logic in a way that I can share with others, that is a bit more 'first-class' than tasks (and pipelines) in git. Happy to focus on tasks to start with, but it would be worth thinking about pipelines. This might not require any significant changes to concourse, but instead might look more like process and best practices

The config for tasks (and pipelines) is plain text, and so can be stored in git, which allows versioning, but it doesn't really help with the other aspects.

One solution for tasks might take advantage of the fact that tasks need a roofts and a command. What if the task definition was extended to include running `/opt/task/run` if no custom command were provided:
- load the rootfs from this container
- run `/opt/task/run`
- ENV vars and the filesystem are the interface (as they are currently)
- I'm not sure what the default output interface should look like, but it probably has to be filesystem plus `stdout`/`stderr`

We could then also add an additional top-level field (e.g. `task_types`) which could keep the configuration in one place, and you could reference a task by name, instead of inlining all the config again. This is an optional extension, but it would help discoverability and consistency within a pipeline.

This would make tasks look a lot more like resources - sealed units of behavior that can easily be shared and versioned (via the `image` URL). This would also allow me to inline behavior into the pipeline (no need for separate task yml or shell script) as well, reducing complexity.

Using this mechanism increases the feedback loops on developing the task (I can't just git push to a repo), but I think it has some significant benefits.

**Comment by robdimsdale** [comment]
I think that this is an XY-problem. I don't think we need to focus on how tasks are run, but instead I want to see a way to define composable pieces of behavior e.g. `get resource foo -> run task bar -> put to resource baz` as a sharable entity. Currently there's a lack of discipline of task authors around versioning and sharing their logic, plus there's no way to determine what a task/resource needs without reading task config files (or resource documentation).

Put another way, I'd like to see a canonical way to glue resources and tasks together in a format that allows pipeline authors to take advantage of the work of others. I don't know what that looks like, but stronger APIs between tasks and resources, better discoverability of what resources and tasks are available, combined with some tool to validate that selected resources and tasks will work together would probably go a long way.

I think concourse has all the primitives it needs - resources, tasks and jobs are sufficient - but I think we need some sort of toolchain and user-experience layered on top of this.

@vito - thoughts?

**Comment by xoebus** [comment]
I want to explore using Bazel for some of these reusable tasks.

**Comment by robdimsdale** [comment]
@xoebus bazil like http://bazel.io/ ?

**Comment by xoebus** [comment]
Yeah, it doesnt address every task but having one way to run tests, build binaries, or build tiles would simplify a lot of them. I'm not sure how it'll fit in with Concourse though.

**Comment by jchesterpivotal** [comment]
An emerging design pattern is the task-subdirectory approach. 

Each task gets a subdirectory under `tasks/`. The subdirectory contains at least `task.yml` and `run.{sh,rb,whatever}`.

If `run.rb` needs more code, that code is bundled in the task directory. This makes it easier to bodily hoist the task into another pipeline.

Hence:

```
whatever-ci/
    tasks/
        do-the-whatever
             whatever_doer.rb
             run.rb
             task.yml
```

Still unclear at this time:

* Where do tests live? 
* Where do libs shared between tasks live?

Consequently:

* Should each task directory be considered as a "true" Ruby/whatever project directory? Gemfile, `specs/`, `lib/`, the works?
* Do we decide, at some point, to package the shared logic as rubygems?
* Or do we place our sanity at risk by using git submodules?

However, at this time, for the minimal case, this pattern makes it much easier to reuse tasks within a pipeline and across repos.

**Comment by robdimsdale** [comment]
@jchesterpivotal I've seen that pattern with both bash and go as well as ruby, and it seems to work pretty well. If I were to consume your task I would need to know the interface - do you expose all your config as ENV params in the `task.yml`? What about side-effects? Documentation?

Agreed that there's still open questions around tests and shared libs

**Comment by jchesterpivotal** [comment]
Right, you bring up that `params` are the de facto interface. It becomes less attractive when you're passing an array of arguments to a script -- in that case I switch from using ENV params to using `args` on the `run`.

Side-effects are hard to control for strictly. Documentation is an interesting question. I thinking that at the point one moves into a "full directory" model, whether served as a language-specific module (gem etc) or as a git submodule, you'd expect to at least add a README.
