### ISSUE TITLE
Feature Request: Support Custom Environments for containers

### ISSUE THREAD

**Issue by cappyzawa** [concourse/concourse#4174]
## What challenge are you facing?
[`GOPROXY`](https://tip.golang.org/cmd/go/#hdr-Module_proxy_protocol) is introduced since go1.13.

We use GitHub Enterprise and don't want to register package to GOPROXY.
So, I(concourse admin) want to force the users setting `GOPRIVATE` env.

Now, users can set `GOPRIVATE` env using task parameters.
But users may forget to do this.

### References
[GOPROXY\.IO \- A Global Proxy for Go Modules](https://goproxy.io/)
[go \- The Go Programming Language](https://tip.golang.org/cmd/go/#hdr-Module_proxy_protocol)

## What would make this better?
Allow admins to set custom environments for containers.

## Are you interested in implementing this yourself?
Maybe, I can't ... :bow:

**Comment by eedwards-sk** [comment]
>Now, users can set GOPRIVATE env using task parameters.
>But users may forget to do this.

Sounds like more of a change-approval-process issue. Concourse generally doesn't do "global parameters" because that leads to snowflaking.

Suggestion: if you want tasks to always set that value, make it a parameter and then error if it's unset in the task by checking the value

**Comment by vito** [comment]
Yeah I'm a little skeptical of these kinds of global config features too. Could this be set in your tasks by setting `ENV` in a common base image instead?

**Comment by cappyzawa** [comment]
@eedwards-sk @vito Thanks for catching!!

I'll set `ENV` to a common base image :+1:
