### ISSUE TITLE
fly should have a destroy container command

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#418]
sometimes containers (especially `check` containers) get stuck in a bad state (or just on an old rootfs).

A command: `fly destroy-container` would provide a quick and easy mechanism to reset this state.

**Comment by jchesterpivotal** [comment]
We've got a similar problem on buildpacks -- the problem of zombie hordes grows linearly with the complexity of your builds, and ours are numerous.

It'd be nice if we could reap containers en masse. Something like `fly destroy-container --all-no-seriously-all`

**Comment by jchesterpivotal** [comment]
Or, more specifically, `fly destroy-container --all-non-current`

**Comment by vito** [comment]
consolidating into https://github.com/concourse/concourse/issues/346
