### ISSUE TITLE
there should be a way to correlate volumes with container via fly

### ISSUE THREAD

**Issue by mariash** [concourse/concourse#419]
fly volumes gives volumes
fly container gives containers

Which volumes belong to which containers is unknown. You have to use API.

**Comment by robdimsdale** [comment]
You can't even get that info from the concourse API, and nor from garden API either

**Comment by vito** [comment]
seems like a good idea

**Comment by mariash** [comment]
this was solved with `life`. We can now see the container identifier if volume belongs to container.

```
handle                                worker                                type           identifier                                                                      size
0013edaf-595c-4d6b-5f78-b032a9d6a1ba  40e8b592-c608-42f7-80dd-ab665066bb38  container      d48f7a06-0da4-40f9-6445-b99a3305527e                                            unknown
```
