### ISSUE TITLE
Command to force redownloading resource

### ISSUE THREAD

**Issue by michelvosje** [concourse/concourse#4198]
# What challenge are you facing?

1. I upload a resource to a Artifactory server with a specific version number.
2. Concourse downloads the resource using Resource Type ```emeraldsquad/artifactory-resource```
3. I made a mistake and reupload the resource again with the same version number on the Artifactory server.
4. Concourse won't download the new resource again. So now i have to destroy the entire pipeline?

## What would make this better?

I'd like a command to force Concourse to redownload a specific version of a resource.

## Are you interested in implementing this yourself?

No not atm. And if this is an issue of the Resource Type ```emeraldsquad/artifactory-resource``` please let me know.

**Comment by pivotal-jamie-klassen** [comment]
I think this is really an issue about resource caches, and I can almost imagine the solution being something like `fly clear-resource-cache` but I think I might be being naive. I'm fairly sure @ddadlani has put some thought into this sort of thing and would better understand the consequences.

**Comment by ddadlani** [comment]
Yes, when we do a `get` on a resource we immediately cache it. We can add the ability to force clear a resource cache from the API but I'm not sure if that has any implementation on GC. @pivotal-jwinters thoughts?

**Comment by michelvosje** [comment]
Is there a status update for this issue/request?

**Comment by michelvosje** [comment]
Today i hit this problem again. I am not sure about it buy i think that pipelines "share" downloaded resources. So when i update a resource i had to **destroy all pipelines** using the same resource.

A  workaround for this currently would be that i temporarily deploy my resources with a timestamp during development. But that means that i would have to change the configurations of several pipelines every single time i redeploy the resource.

**Comment by ddadlani** [comment]
@clarafu do you have any thoughts on this?

**Comment by clarafu** [comment]
@ddadlani Hm I think it would be possible, but we would have to implement it carefully so it doesn't pull out a cache from a build that is currently using it. I think it would be best if we restrict it to only resource caches of resources, and not resource type caches because removing resource type caches will be a lot more difficult. Do you think that would be sufficient?

**Comment by ddadlani** [comment]
@clarafu if a resource type cache is removed, does that mean all dependent resource caches of that resource type are also removed? If so, I agree that removing resource type caches would be difficult and would also have unintended consequences. Also looking at the original use case described above, it looks like @michelvosje wanted a particular resource cache cleared, not a resource type.

**Comment by clarafu** [comment]
@ddadlani Ya that's exactly it haha it gets pretty hairy when you go down the dependency chain. Right, I guess I'm making sure that it seems intuitive to be able to allow users to remove only resource caches and not resource type caches.

Maybe I'm just being a little hesitant or paranoid to giving users the ability to peer into our caching mechanisms? Like I'm entertaining the idea of having the command be more of a user facing things like `fly redownload resource`? I'm not really sure though haha it might be fine to just let users to delete caches.

This also might be similar to #1038

**Comment by pivotal-jamie-klassen** [comment]
#4604 looks like WIP towards this
