### ISSUE TITLE
Worker-provided rootfs broke during upgrade

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#420]
@robdimsdale found that a 2 of 10 checking containers ended up broken after an upgrade from v1.0.0 to v1.2.0. This seems to be due to the move of the rootfs in the worker-provided resource from the root of the $BOSH_INSTALL_TARGET to $BOSH_INSTALL_TARGET/rootfs:

```
ls -al /proc/9029/root/
total 28
drwxr-xr-x  10 root root 4096 May  2 18:23 .
drwxr-xr-x  10 root root 4096 May  2 18:23 ..
drwxr-xr-x   4 root root 4096 May  2 18:23 dev
drwxr-xr-x   2 root root 4096 May  2 18:23 etc
dr-xr-xr-x 178 root root    0 May  2 18:23 proc
-rw-r--r--   1 root root  156 May  2 18:18 resource_metadata.json # <--------
drwxr-xr-x  17 root root 4096 May  2 18:18 rootfs # <--------
dr-xr-xr-x  13 root root    0 May  2 18:23 sys
drwxrwxrwt   3 root root 4096 May  2 18:23 tmp
```

The idea of what actually occurred is that ATC created a container with the old worker registration info, which declared the resource rootfs to be at the old location rather than the new one.

**Comment by robdimsdale** [comment]
FYI we have about 7 workers (plus one in another datacenter) and two ATCs

**Comment by RochesterinNYC** [comment]
Hi, we (the Buildpacks team) experienced the same issue when upgrading from Concourse 1.0 to 1.2. We have 1 worker. Running `bosh restart` did not fix the issue but running `bosh recreate` did, after waiting a span of 2-3 minutes.

**Comment by vito** [comment]
Now that we're past 1.3.0 which requires workers to be recreated anyway, I'm inclined to just close this. But we'll keep this kind of thing in mind for the future.
