### ISSUE TITLE
zany-looking build page tooltip

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4210]
## Bug Report

css-transform seems to do something weird when the transform would put the element outside of its parents overflow area? Maybe something to do with the other style attributes on the tooltips.

## Steps to Reproduce

visit a build page with decently long output, like https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/dev-image/builds/948, and scroll down a bit, then hover over one of the step status icons to see a duration tooltip.

## Expected Results

a nicely behaved tooltip that is connected to its arrow.

## Actual Results

this scoundrel:
<img width="207" alt="Screen Shot 2019-08-01 at 7 56 16 PM" src="https://user-images.githubusercontent.com/22056320/62334667-963a2d80-b496-11e9-8443-9c4fa64989b5.png">

## Additional context

I merged #4206 too hastily 😢 

## Version Info

* Concourse version: 5.4.0-rc (master)
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: gcp (prod)
* Browser (if applicable): chrome
* Did this used to work? yes, except for the ones at the top of the output

**Comment by robwhitby** [comment]
ah my bad, sorry! `position:fixed` doesn't play nice with scrolling the container. maybe just revert db6963d for now?

This is the same type of issue I think, but I don't know how to fix it in this case
https://stackoverflow.com/questions/40093740/tooltip-element-with-absolute-positioning-being-clipped-by-container-with-overfl
