### ISSUE TITLE
Helm Chart Bug

### ISSUE THREAD

**Issue by huguesalary** [concourse/concourse#4216]
## Bug Report

It is not possible to deploy the concourse helm chart wit Let's Encrypt Support because of conflicting parameters:

In order to enable let's encrypt support, one has to specify both `concourse.web.letsEncrypt.enabled=true` and `concourse.web.tls.enabled=true`.

However, `concourse.web.tls.enabled=true` then forces you to set `secrets.webTlsCert` and `secrets.webTlsKey`.

Now, when `secrets.webTlsCert` and `secrets.webTlsKey` are set, the concourse binary refuses to start with the following error message `* cannot specify --enable-lets-encrypt if --tls-cert or --tls-key are set`

### First Failure
```
helm install --name concourse stable/concourse \
--set concourse.web.externalUrl=https://ci.example.com \
--set concourse.web.tls.enabled=true \
--set concourse.web.letsEncrypt.enabled=true
```

Will fail with 
```
Error: render error in "concourse/templates/web-secrets.yaml": template: concourse/templates/_helpers.tpl:38:4: executing "concourse.secret.required" at <required (printf "se...>: error calling required: secrets.webTlsCert is required because secrets.create is true and concourse.web.tls.enabled is true
```

### Second Failure
```
helm install --name concourse stable/concourse \
--set concourse.web.externalUrl=https://ci.example.com \
--set concourse.web.letsEncrypt.enabled=true
```

Will fail at the pod level:
```
1 error occurred:
        * must specify --tls-bind-port to use TLS
```

### Third Failure
```
helm install --name concourse1 stable/concourse \
--set concourse.web.externalUrl=https://ci.example.com \
--set concourse.web.tls.enabled=true \
--set concourse.web.letsEncrypt.enabled=true \
--set secrets.webTlsKey="bogus value OR real certificate" \
--set secrets.webTlsCert="bogus value OR real certificate" 
```

Will fail at the pod level with:
```
1 error occurred:
        * cannot specify --enable-lets-encrypt if --tls-cert or --tls-key are set
```
## Expected Results

When `--set concourse.web.letsEncrypt.enabled=true` is used, the helm templates should automatically add the `CONCOURSE_TLS_BIND_PORT` environment variable to the concourse-web deployment.

**Comment by cirocosta** [comment]
Hi, @huguesalary !

If I understood correctly, this is the same issue as https://github.com/helm/charts/issues/14867 - would you mind confirming?

Also, we tend to keep issues that are specific to the packaging of Concourse as Helm chart under the place where the source code lives ([`helm/charts`](https://github.com/helm/charts)).


Thank you!

**Comment by huguesalary** [comment]
Hi @cirocosta, indeed, those are the same issues!
