### ISSUE TITLE
Baggage claim not removing containers/volumes

### ISSUE THREAD

**Issue by mstansberry** [concourse/concourse#4220]
## Bug Report
Baggage claim is not removing dangling garden containers or btrfs/overlay2 volumes when worker is retired. This leads to inconsistent results from database vs. `fly workers` output for containers, as well as storage not being released for volumes.

## Steps to Reproduce
Retire worker and check for contents under the following:
Garden container paths under `<worker_base_dir>/depot/` will remain running and relaunch on reboot leading to discrepancy between database and `fly workers`.
btrfs volumes under `<worker_base_dir>/volumes/live/` will persist through reboot and consume storage while not being reflected in database.
overlay2 volumes under `<worker_base_dir>/overlays/ <worker_base_dir>/volumes/live/` will persist through reboot and consume storage while not being reflected in database.

## Expected Results
For garden, as concourse is the only service orchestrating and using the service, it should be authoritative and remove all worker filesystem container references as part of garbage collection.
For volumes, volumes should be unmounted and mount paths/corresponding files should be removed prior to volumes being marked destroyed in database.

## Actual Results
Large numbers of containers and volumes/mounts persist on hosts after being retired/reconfigured leading to garden `subnet exhaustion` and all storage being claimed by unused volumes. These containers/volumes are not tracked in the database, so they are not properly reflected in metrics collected from database for the workers and lead to unexpected failures.

## Additional Context
Temporary workaround:
```
# retire worker and wait for services to stop successfully

# cleanup garden containers
sudo kill -9 `ps -aux | awk '/garden-init/ {print $2}'`
sudo rm -rf /opt/concourse/worker/depot \
            /opt/concourse/worker/garden-properties.json

# unmount and remove btrfs img
sudo umount -fl /opt/concourse/worker/volumes
sudo sync
sudo losetup -d /dev/loop0
sudo rm -rf /opt/concourse/worker/volumes.img

# unmount and remove overlay2 mounts
sudo umount -flR /opt/concourse/overlay /opt/concourse/worker/volumes
sudo sync
sudo rm -rf /opt/concourse/worker/overlay /opt/concourse/worker/volumes

# restart worker
```

## Version Info
* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: N/A
* Browser (if applicable): N/A
* Did this used to work? not that we are aware of

**Comment by vito** [comment]
This is expected behavior right now. `retire` is based on the assumption that the machine itself is going away, so we don't perform any cleanup since it'd just be a waste of time in that case.

If you're not going to be removing the machine after a `retire`, you may want to just `land` it instead.

**Comment by mstansberry** [comment]
In that case, would it be safe to assume that landing a worker should remove all running garden containers and cleanup all volumes on the worker?

Using retire was mainly meant to be a reproducible use case for validation as all volumes/containers that need to persist should be moved to other workers prior to completion. If there is another workflow we should use for testing this behavior, we're happy to try that as well.

The volume issue we're seeing currently applies to running workers where the number of live volumes/mounts greatly exceeds what is in the database and slowly consumes all free space on the worker. The container count issue happens more on hosts that crash/reboot due to a failure of some sort, and then have a skew between running containers and those which are active in the database.

Thanks a lot for your help getting this resolved.

**Comment by vito** [comment]
@mstansberry Landing won't remove anything; it'll drain, waiting for any in-flight work to finish, and shut down while leaving all of the containers and volumes there. Most importantly, they'll remain in the database as well. The worker can then come back and the `web` node will continue to use the remaining containers, re-attaching to in-flight processes if necessary. The volumes will still be around too.

Landing is the workflow for doing an in-place upgrade or restart of a worker without removing it. Retiring is the workflow for decommissioning a worker machine for good.

For handling a crash/reboot, we're working on a related issue (https://github.com/concourse/concourse/issues/4264) which *may* be affecting you if you're using the `overlay` volume driver.
