### ISSUE TITLE
UX: add a button to the build page to rerun it with the same inputs

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#4222]
The re-run button will live at the right most side of the build page to be more closely associated with triggering a particular build with the same inputs as opposed to triggering a new build of that job. 

![00_build_page_split_trigger_slice_1](https://user-images.githubusercontent.com/27746614/62575235-51344380-b868-11e9-87ee-ca346840d70e.png)

![Screen Shot 2019-08-06 at 4 15 41 PM](https://user-images.githubusercontent.com/27746614/62575401-a3756480-b868-11e9-8e70-871984827914.png)

Dropdown from the re-trigger will display the set of versions associated with that build that will e used in the new build. 

![Screen Shot 2019-08-23 at 3 59 57 PM](https://user-images.githubusercontent.com/27746614/63620363-1566e100-c5bf-11e9-96a2-09c42873f175.png)

- [ ] Asset [re-trigger_bttn.svg.zip](https://github.com/concourse/concourse/files/3498560/re-trigger_bttn.svg.zip)

**Comment by vito** [comment]
* tooltips on both trigger and re-trigger buttons.
* which builds can logically be re-triggered??

**Comment by vito** [comment]
@clarafu What will happen if I try to re-run a build that has no inputs? (i.e. aborted before they were determined)

**Comment by vito** [comment]
Work for this should occur on the `algorithm-v3` branch: https://github.com/concourse/concourse/tree/algorithm-v3

**Comment by vito** [comment]
Closing in favor of https://github.com/concourse/concourse/issues/4589 which is smaller in scope (no version previewing)
