### ISSUE TITLE
Enforce that all version fields are strings

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4236]
Versions can be specified in a few places:

1. [`image_resource.version`](https://concourse-ci.org/tasks.html#image-resource-version)
1. [`version`](https://concourse-ci.org/resources.html#resource-version) on a resource definition
1. [`version`](https://concourse-ci.org/get-step.html#get-step-version) on a `get` step

We should make sure that all of these locations only accept a string value for each field.

Right now we're inconsistent. Cases 1 and 2 unmarshal into an `atc.Version` which is an alias to `map[string]string`, so those should be OK.

Case 3 however does some wacky meta-unmarshal stuff, since that field can technically be 3 things: "latest", "every", or a version object. It looks like our current implementation simply skips any non-string values, which is...well, that's *one* way to do it:

https://github.com/concourse/concourse/blob/12b4d7cfc178e0f0639e4b5b899b4d2f3784b012/atc/config.go#L126-L134

(Also, what's that `strings.TrimSpace` doing there??)

We should have all three bail out on any non-string values. We shouldn't do any coercion; that is the path to darkness (see https://github.com/concourse/concourse/issues/1407).

**Comment by clarafu** [comment]
Closing this with the merge of #4371
