### ISSUE TITLE
Pass context into StreamIn/Out calls in ATC.

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#4242]
convert it

**Comment by cirocosta** [comment]
Hey @kcmannem , would you mind providing some details on why this would be needed? 

thank you!

**Comment by kcmannem** [comment]
Sorry for the blank message here. This is more of us being nice and cleaning up, I don't recall any troubles from unclosed streams. You might recall recently, We started passing context down to the Garden Client so that we can close connections properly (via timeouts or aborted builds). This continues that theme and closes out any streams that might have been happening during container initialization but the user has decided to abort the build.
