### ISSUE TITLE
No way to reference credentials with `.` in their name

### ISSUE THREAD

**Issue by bonzofenix** [concourse/concourse#4249]
## Bug Report

When using the atc vault integration for vars in `((..))` format keys with dots are ignored.

A secret at ``concourse/main/some.secret:key`` can not be read through variables. I think the regex that looks for key names should use the last dot to split the path and the key.

it would be nice if concourse realize that` ((some.secret.key))` is a secret at `concourse/main/some.secret:key` or to have a way to escape the key `.`, something like `((some\.secret.key))`

Regex seems to explicitly ignore paths with `.`s.
https://github.com/concourse/concourse/blob/ca0fd4cb1ed0b619fd1e083b5b3c827ffb669e63/vars/template.go#L66

## Steps to Reproduce

Try to read a secret where the path contains the `.` character.

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: vsphere

**Comment by bonzofenix** [comment]
@jvikes11

**Comment by vito** [comment]
The complication here is that `.` is used in our vars notation for field access. `((foo.bar))` means "get the `foo` key and read the `bar` field from it."

**Comment by mkkeffeler** [comment]
this blocks any integration with conjur as well, the conjur credential manager iis effectively useless wiithout this as lots of variables have dots in them

**Comment by mkkeffeler** [comment]
see screenshot of concourse not recognizing it, this variable is supposed to be from conjur
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/12587979/84412400-d13be000-abd4-11ea-8b2b-00713f20e054.png)

**Comment by vito** [comment]
@mkkeffeler Hm, do you have any docs or anything I can reference to get an idea of how common that is? Their website seems to only have examples of camelCase.

We should have a way for this to work either way, but knowing how commonplace it is will help decide whether this should be done through some sort of escaping syntax or some alternative notation for field access.

**Comment by mkkeffeler** [comment]
see https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Conjur/cv_accnt-representation.htm?tocpath=Integrations%7CCyberArk%20Vault%20Synchronizer%7CAccounts%20and%20Safes%7C_____1#Namingconventionforvariables

This is how lots of customers get credentials to conjur that are being managed by cyberark. note that part of the naming schema includes the address of the account, where address is usually a server such as myserver.<subdomain>.

**Comment by vito** [comment]
@mkkeffeler Got it, thanks. Do you have any suggestions/preference for syntax? What about something like `(("foo.bar".baz))`?

**Comment by mkkeffeler** [comment]
yeah exactly, if i double quote a variable it should process it as a whole name, where as outside of that can do the json sub attribute access or any other use cases that may be needed

**Comment by mkkeffeler** [comment]
is there somewhere to track this issue at? this is a pretty big blocker for us and we would at least like to track it and help get it prioritized if possible

**Comment by vito** [comment]
@mkkeffeler This is a good issue to follow, in addition to https://github.com/concourse/concourse/issues/5813 which is a broader issue. There's a 'Subscribe' button at the right if you're not subscribed already.

The relevant code is here, if anyone would like to contribute the JSON syntax change:

https://github.com/concourse/concourse/blob/cedbc290b62d60cdd7fdc240bdb3752acda02497/vars/template.go#L64-L67

**Comment by dwchurch** [comment]
this is very common in conjur to have special characters, so very helpful

**Comment by alogishetty** [comment]
We need this feature in concourse today for interacting with Conjur successfully!

**Comment by nhogan5** [comment]
> @mkkeffeler Got it, thanks. Do you have any suggestions/preference for syntax? What about something like `(("foo.bar".baz))`?

I think the double quote is an intuitive way to interpret string value of what is wrapped.

**Comment by alexw19** [comment]
This integration with Conjur is very much needed as it's common for special characters to be included in Conjur.
