### ISSUE TITLE
UX: `set_pipeline` steps on the build page

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4255]
This is our first new 'core' step type. How do we want it to look?

Elements:

* diff of pipeline config
* config warnings/deprecations
* config validation errors

**Comment by vito** [comment]
This is implemented by #4708 to some extent.

Currently, a diff is shown in the step's output, in the same way that `fly set-pipeline` renders it. Warnings, deprecations, and errors are printed to the step output as well.

The step renders with the breadcrumb pipeline icon as the step's icon.

Do we want to change any of this?

**Comment by zoetian** [comment]
not very beautiful
![Screen Shot 2019-12-16 at 3 28 19 PM](https://user-images.githubusercontent.com/6901732/70940615-be2ac780-2018-11ea-8068-2cdd8db5b5dc.png)

**Comment by zoetian** [comment]
output sample
![Screen Shot 2019-12-16 at 3 29 30 PM](https://user-images.githubusercontent.com/6901732/70940698-e286a400-2018-11ea-88be-0d22789951a8.png)

**Comment by Lindsayauchin** [comment]
@vito @evanchaoli Could we update the icon to a right facing arrow to represent 'set pipeline'?

The right arrow is more consistent with the icon language in the build page around input, output and tasks. 

<img width="675" alt="Screen Shot 2019-12-19 at 3 23 54 PM" src="https://user-images.githubusercontent.com/27746614/71206848-96836b80-2273-11ea-8067-b0a6ee76dd66.png">

**### Asset:**

[arrow_forward-24px.svg.zip](https://github.com/concourse/concourse/files/3985520/arrow_forward-24px.svg.zip)

**Comment by Lindsayauchin** [comment]
@vito suggested adding a label for more clarity so we sketched out a couple versions, with icons and without and we landed on taking out all of the icons all together for the`set_pipeline,` `get`, `put`, `task`steps. 

@evanchaoli thoughts?

<img width="617" alt="Screen Shot 2019-12-19 at 6 17 31 PM" src="https://user-images.githubusercontent.com/27746614/71217447-dc4c2e00-228b-11ea-9b69-ae88ffd664b0.png">

**Comment by evanchaoli** [comment]
@Lindsayauchin I'm ok with that. At least that frees contributors from struggling for icons.

**Comment by pn-santos** [comment]
Not sure by the image example, but for the `get` will it still change colour based on whether there was a new version or not? I found that pretty useful

**Comment by vito** [comment]
@pn-santos Didn't think about that, but we'll see how it looks if we just make it the same yellow color or something!
