### ISSUE TITLE
ATC memory leak rate proportional to amount of workers

### ISSUE THREAD

**Issue by odormond** [concourse/concourse#4257]
## Bug Report

We recently deployed a nightly build of concourse that include the max-active-tasks-per-worker strategy (see below for the exact commit). The installation is on AWS with an auto-scaling number of workers. The amount of workers is limited to a low value over night and week-end. After a few days of operation it's clear that the rate of memory leak observable in the graph below is proportional to the amount of workers connected to the ATC.

![image](https://user-images.githubusercontent.com/6637092/62848089-20299800-bcda-11e9-8bd2-01781b75f3af.png)

## Steps to Reproduce

Deploy and operate commit 56721145ebe9c3a02cf45183d86469758de55716. 

## Expected Results

A rather stable memory usage over time.

## Actual Results

A continuously increasing memory usage.

## Additional Context

You can find bellow the heap and goroutines dump done at the end of the graph above. (Due to size limit the heap dump was split into 5 chunks that can be concatenated together after uncompressing to reproduce the original dump.)

[atc-heap.00.zip](https://github.com/concourse/concourse/files/3491219/atc-heap.00.zip)
[atc-heap.01.zip](https://github.com/concourse/concourse/files/3491220/atc-heap.01.zip)
[atc-heap.02.zip](https://github.com/concourse/concourse/files/3491221/atc-heap.02.zip)
[atc-heap.03.zip](https://github.com/concourse/concourse/files/3491222/atc-heap.03.zip)
[atc-heap.04.zip](https://github.com/concourse/concourse/files/3491223/atc-heap.04.zip)
[atc-goroutines.txt.zip](https://github.com/concourse/concourse/files/3491224/atc-goroutines.txt.zip)

## Version Info

* Concourse version: commit 56721145ebe9c3a02cf45183d86469758de55716
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work?

cc: @marco-m @aledeganopix4d

**Comment by kcmannem** [comment]
you should try after this commit https://github.com/concourse/concourse/commit/bfc6779a8b47ce94ab3ed17aa1bf456da64207ee

**Comment by kcmannem** [comment]
@odormond any updates?

**Comment by odormond** [comment]
We didn't test commit bfc6779 directly as we really want the `max-active-tasks-per-worker` strategy but instead we tested 77c6b5e that includes 3361a51 which is identical to 68ee343 which is part of bfc6779.

Unfortunately we could not operate it for an extended period of time due to an apparent deadlock condition appearing way to frequently (a PR is pending to fix it https://github.com/concourse/concourse/pull/4277).

In the graph below, we started to operate that commit at the purple dashed line marker until the end of the graph when we reverted back to the leaky commit:
![image](https://user-images.githubusercontent.com/6637092/63161842-5a1fd480-c021-11e9-9e9b-e70eaccfc9de.png)
You can see the frequent restarts of the ATC whenever the orange line is interrupted or make a huge swing.

It's hard for me to draw a conclusion for when the system is under load. At least for the nightly period when the system is mostly idle, the increase in memory usage is significantly lower with an increase rate of 0.7MB/h compared to 2.7MB/h with commit 5672114. In my opinion this is too low in a GC environment to conclude to a leak or not.

**Comment by kcmannem** [comment]
hmmm, thats pretty strange. We haven't seen anything in 3 of our prod environments. One of which is a large scale (~25 workers). We have our prod environments metrics at https://metrics.concourse-ci.org if you're curious and want to spot something. No one has posted an issue about the leak persisting even after the 5.4.1 release. I'll keep an eye for this.

Thanks for raising.
