### ISSUE TITLE
[SPIKE] Check if we can change ResourceConfigCheckSessions to expire in a deterministic way

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4263]
Can we try to change check session expiry such that its based on the amount of times a session is used instead of a strict time.

We've ran into issues where the session could expire while a check was in progress, causing races with GC (such as #4244). We will need a fix for check sessions when we move to ephemeral check as well since we need an approach to retain cache volumes for the check containers.

**Comment by vito** [comment]
Don't think we need this kind of approach anymore; now that we have LIDAR we can have one-container-per-queued-check.
