### ISSUE TITLE
empty volumes when using overlay on Prod

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4264]
We have been seeing builds error out more frequently with some common error messages lately:

`task config 'ci/tasks/yarn-build.yml' not found` -> https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/watsjs/builds/1574

`file not found` -> https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight/builds/1569

Cert errors on checks - 
```resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31mERRO[0m[0000] failed to get remote image: Get https://index.docker.io/v2/: x509: certificate signed by unknown authority
```

@kcmannem and I theorize that this has to do with something that has recently changed with volumes -- perhaps `overlay`? streaming? A combination of the two?

We're not sure these issues are all related but this issue exists to document the work to investigate these errors.

We've been seeing these since around the time we pushed Concourse v5.4.0.

**Comment by ddadlani** [comment]
@vito suggests that it might be that the link between lowerDir and upperDir is broken after a VM restart, and we might be able to fix it by having baggageclaim walk through the volume tree and setup mount points at startup.

@xtreme-sameer-vohra has a concern about making workers stateful if we do this, revisit afterward.

**Comment by kcmannem** [comment]
We were able to reproduce the issue on our drills environment. We saw that when we let resource caches establish on an initial pipeline run. If we restarted(rebooted, not a bosh restart) a worker, the bind mounts would no longer persist. And we encountered the errors listed in the issue.
We're going to implement @vito's solution and see if its a good fix.

**Comment by ddadlani** [comment]
We tried out the solution. Our assumption was correct, i.e. the overlay itself exists. The overlay is bindmounted into the `/var/vcap/data/worker/work/volumes/live` directory, and that volume is mounted in to each container. The bindmount disappears on restart, so if we go through the overlays and bindmount them into `/var/vcap/data/worker/work/volumes/live` we should stop seeing the issue.

**Comment by vito** [comment]
@ddadlani @kcmannem slight clarification: there are two types of mounts to fix - one's a bind mount:

https://github.com/concourse/baggageclaim/blob/03f460affbf02448ff0a6fedbd3d23e92d0a95d5/volume/driver/overlay_linux.go#L28

and the other's an overlay mount:

https://github.com/concourse/baggageclaim/blob/03f460affbf02448ff0a6fedbd3d23e92d0a95d5/volume/driver/overlay_linux.go#L74-L81

**Comment by kcmannem** [comment]
@vito thanks.

I've also tried to learn why mounts disappear. It's expected behavior that the mount table is cleared on system restart. If you want certain mounts to persist between restarts, you have edit /etc/fstab to include the mount.

**Comment by vito** [comment]
yep. I don't think we want to do that though; that file is usually for actual system-wide configuration for its own hard drives and such.

**Comment by kcmannem** [comment]
Looks like there was a scenario where dead volumes could pile up and not get cleaned up.
When a restart occurs the mounts no longer exist. This makes the destroy volume call fail because its first step is to umount.
```
func (driver *OverlayDriver) DestroyVolume(path string) error {
	err := syscall.Unmount(path, 0)
	if err != nil {
		return err
	}
```

**Comment by vito** [comment]
Interesting, I wonder if that could be a root cause of the piling-up `dead` volumes we observed on Wings a while back? I think @ddadlani and @xtreme-sameer-vohra may remember that.

Or were we using `btrfs` at the time? :thinking:

**Comment by kcmannem** [comment]
here's the unmount error I was mentioning before:
```
{"timestamp":"2019-08-12T20:20:07.475029390Z","level":"error","source":"baggageclaim","message":"baggageclaim.api.volume-server.destroy.destroy-volume.failed-to-destroy","data":{"error":"invalid argument","session":"3.1.233.1","volume":"90a24379-40be-492a-6652-cd5f7d5f529a"}}
{"timestamp":"2019-08-12T20:20:07.475058739Z","level":"error","source":"baggageclaim","message":"baggageclaim.api.volume-server.destroy.failed-to-destroy","data":{"error":"invalid argument","session":"3.1.233","volume":"90a24379-40be-492a-6652-cd5f7d5f529a"}}
```

we get an os.ErrInvalidArgument returned. Which is equivalent to the EINVAL in errno.h

**Comment by kcmannem** [comment]
talked with @cirocosta to determine what the best approach to knowing when to do a bind/overlay mount is. He mentioned that an alternative is using https://en.wikipedia.org/wiki/Extended_file_attributes. Here we can apply some key-value properties to the inode which persist between reboots. This makes it so that we can easily read these values on startup and determine what mount to apply.

The other (currently implemented) approach is to apply all the bind mounts in the overalys directory and then iterate through the live directory and scan for "parent" symlinks and apply a overlay mount if it exists.

**Comment by vito** [comment]
I'm leaning towards the second (current) approach since it leverages state we're already keeping track of anyway (the `parent` symlink) without introducing a new filesystem mechanic.

**Comment by kcmannem** [comment]
@vito me too, I kept it.

**Comment by ddadlani** [comment]
This is done and pending drills testing.

**Comment by crish963** [comment]
@kcmannem Any workaround until this is fixed? we are seeing like 70% our builds failing with this "file not found" error. 
We are in v5.4.1.

**Comment by frayer** [comment]
@crish963 I'm curious too about any workarounds and what others have done to troubleshoot.  We're using the Helm release with Concourse v5.4.1 which is designed for stateless workers (a `rm -rf` is performed on the concourse work dir on startup of a worker).  I would think a restart of the Pod in that deployment style would clean things up.

If anyone else is using the Helm release, are you seeing the same?  Does this manifest itself only in the VM restart scenario mentioned above, or are others seeing it occur in the normal course of a running worker.

Link to the Helm chart where the worker dir is cleaned up in a Kubernetes `initContainer`

https://github.com/helm/charts/blob/master/stable/concourse/templates/worker-statefulset.yaml#L64

**Comment by ddadlani** [comment]
@crish963 for now you would have to recreate the worker

We will be testing our fix for this over the next week

**Comment by kcmannem** [comment]
@crish963 are you running on the helm chart? Also are you pipelines using heavy resources (size in GBs)

@frayer can you try using the btrfs volume driver. Others facing this issue on kubernetes, had  mitigated it by switching out of overlayfs.

**Comment by crish963** [comment]
> @crish963 for now you would have to recreate the worker
> 
> We will be testing our fix for this over the next week

I recreated the worker several times over the course of 1 week, but it's solving the issue temporarily for like 1 or 2hrs only and after that we are having the issue again.

**Comment by crish963** [comment]
> @crish963 are you running on the helm chart? Also are you pipelines using heavy resources (size in GBs)
> 
> @frayer can you try using the btrfs volume driver. Others facing this issue on kubernetes had mitigated it by switching out of overlayfs.

@kcmannem yes i'm running on helm and some of our pipelines are  using heavy resources like
 100GBs.

**Comment by kcmannem** [comment]
@crish963 I suggest switching to the `btrfs` volume driver as well. Let me know if that solves the problem.

**Comment by crish963** [comment]
@kcmannem I will give it a try and let you know. Thanks for the suggestion.

**Comment by crish963** [comment]
@kcmannem I switched to `btrfs` and it's working right now. Thanks!

**Comment by crish963** [comment]
@ddadlani @kcmannem Any update on this fix?

**Comment by kcmannem** [comment]
@crish963 https://github.com/concourse/baggageclaim/pull/30

It won't come till 5.5
