### ISSUE TITLE
Refactor the Get Step and Fetcher

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4265]
# Goal of this refactor
Move Runtime specific concerns in `Put` & `Get` Steps into a client implementation. This is in service of #4052 which is to have a an interface for steps or implementation of steps that is agnostic of a specific runtime.

There are 2 main areas of decoupling, `execution` of a script (garden) and `storage` of binary data (baggageclaim)

For `execution`, the worker selection, container creation and running was moved from the `Put` step into the `worker client`, which has runtime specific logic. 

For `storage`, references to `worker.Volume` were removed and we proposed introducing the concept of `Artifact` & `ArtifactSource`, with the following definitions;
`Artifact` contains runtime agnostic metadata used by Concourse to manage the life cycle of anything that needs to be stored/retrieved.
`ArtifactSource` contains an concrete implementation to be able to store and retrieve data (eg. worker.Volume) 
Details [Iteration 1](https://github.com/concourse/concourse/issues/4265#issuecomment-523619482) & [Iteration 2](https://github.com/concourse/concourse/issues/4265#issuecomment-524925507)

# Why it took long and was complex ?
The `Get` step was particularly tricky for 2 reasons;
1) it requires a worker for the `Find` logic of the Fetcher, even though we don't create a container in that flow
2) the ImageResourceFetcher also uses the same Fetcher flow, and it needs to be fetched on a particular worker.
More details [here](https://github.com/concourse/concourse/issues/4052#issuecomment-511574187)

**Comment by ddadlani** [comment]
As part of decoupling worker from the `exec` package, we started to work on removing the `worker.Volume` from the different implementations of the `worker.ArtifactSource` interface. This is because we do not need the `worker.Volume` in Core at all, we simply pass it back up to Core so that Core can give us the appropriate `ArtifactSource`s as inputs to the next step in the build. 

The `ArtifactSource` implementations are located in the `exec` package (in Core) - `getArtifactSource`, `taskArtifactSource` and `taskCacheSource`. However, the `ArtifactSource` methods aren't really called in Core. We pass those `ArtifactSource` types down into `FindOrCreateContainer`, as inputs, and call the methods there. It probably makes more sense to have the `ArtifactSource` implementation within the runtime itself, and have another type (with metadata) that gets passed down as `InputSource`s. The only exception is for task file streaming, which is done in `taskStep.Run()`.

The current implementation (on branch `remove-volume-from-artifact-source`) passes a volume handle in the `getVersionedSource` back instead, and then looks up the corresponding volume for each `InputSource` once it gets to `worker.Client`.

**Comment by ddadlani** [comment]
Today @xtreme-sameer-vohra pointed out that if we simply move the `fetcher` into a runtime-level package, we can call the `fetcher` from the `worker.Client` instead of the other way around, which allows us to keep the worker dependency on `fetcher` (i.e. we can continue to call `fetcher.Fetch()` after a worker has been selected, rather than before).

We are not currently able to put it directly in the `worker` package because of a circular import dependency (`fetcher`+`resource_instance_fetch_source` return a `resource.VersionedSource` type ->`resource` imports `worker` imports `resource`), but we can extract it into a separate new package and call it from the `worker`package just fine. This is a sign that our `worker` package is getting too broad and we may be able to break it up into smaller packages.

**Comment by ddadlani** [comment]
We have reached a point where are not calling `worker.Volume` in any of the steps (not counting `check` because that just dropped). However, the link between `runtime.Artifact` and `worker.ArtifactSource` has not been established. This means nothing will run.

Next steps (in no particular order):
[ ] convert from `runtime.Artifact` to `worker.ArtifactSource` in `worker.Client`
[ ] make tests pass
[ ] add a `RunCheckStep`
[ ] use the `resource.Resource` interface and `resource.RunScript` instead of the copied-over versions in worker
[ ] replace occurrences of FooBar with real names
[ ] make `worker.Client` an actual client and put all the current code in "implementation"
[ ] go through all the TODOs in the `new-put-get-steps` branch and resolve them

Doing all these will mean that this story is complete and can be merged in to master.

Things to do as separate stories after this gets merged:
[ ] refactor `RunGetStep`, `RunPutStep` and `RunTaskStep` to remove all the commonalities (including in their tests)
[ ] separate out `Runnable` and `Storage` interfaces

Relevant reading: https://github.com/concourse/architecture-rfcs/pull/1

**Comment by ddadlani** [comment]
We have needed to add in a `Runnable` interface as part of using the `resource.Resource` interface (which involved decoupling the `resource` and `worker` packages).

In the current iteration, we have designed a `resource` interface that directly reflects the resource contract we provide. We also cleaned up a bunch of import loops that were caused by bubbling `worker` up all the way to the `exec` package

**Comment by ddadlani** [comment]
Another change we have made is to how task caches are handled.

Previously, `taskCacheArtifactSource` implemented the `ArtifactSource` interface, which meant that it had no-op implementations of the `StreamTo` and `StreamFile` methods. We implicitly depended on the no-op implementation of `StreamTo` when creating a new volume.

If a volume is not present on the given worker, a new empty volume is created and the contents of the old volume are streamed in. In the case of a task cache, we don't stream in the contents, we just create a new empty volume, because task caches are not guaranteed to be in the same state across workers. This was implicit because it would still call `StreamTo` on the task cache volume, it just did nothing.

We made it more explicit by splitting up the `ArtifactSource` interface into `ArtifactSource`, which contains one method: `ExistsOn(worker)` (which replaces the old `VolumeOn(worker)`). There is another interface, `StreamableArtifactSource`, which adds the `StreamTo` and `StreamFile` methods on top of the `ArtifactSource` interface. A `taskCacheArtifactSource` only implements `ArtifactSource`, whereas `getArtifactSource` and `taskArtifactSource` implement `StreamableArtifactSource`.

In `worker.FindOrCreateContainer`, when cloning remote volumes, we create a new volume, and only stream into it if the original `ArtifactSource` is also a `StreamableArtifactSource`. This guards against ever accidentally calling streaming methods on a cache.

**Comment by vito** [comment]
update: testflight passes with the refactor changes.
next steps: make unit tests pass and merge with master

**Comment by xtreme-sameer-vohra** [comment]
Mid week update
Branch `new-put-get-steps`

We have unit tests in `atc/worker` passing

Currently working on `atc/worker/image` and `atc/exec` package unit tests.

**Comment by xtreme-sameer-vohra** [comment]
End of week update
Branch `new-put-get-steps`

Completed tests `atc/resource`

Working on refactoring tests in  `atc/exec`, adding coverage for `atc/worker/ -> RunScript`

**Comment by xtreme-sameer-vohra** [comment]
Easier for us to follow and track progress [CI](https://nci.concourse-ci.org/teams/main/pipelines/runtime-refactor)

**Comment by xtreme-sameer-vohra** [comment]
# End of week update
Branch `new-put-get-steps`
Pipeline [Runtime Refactor](https://nci.concourse-ci.org/teams/main/pipelines/runtime-refactor)

- Unit tests are passing now
```
    fix atc/exec/check_step_test.go
    fix atc/exec/artifact_output_step_test.go
    fix atc/exec ensure, log_error, on_abort and on_failure
    fix atc/exec/in_parallel_test.go
    fix atc/exec/on_error_test.go
    fix atc/exec/on_success_test.go
    fix atc/exec/task_config_source_test
    fix atc/exec/retry_step_test.go
    fix atc/exec/timeout_step_test.go
    fix exec/try_step_test
    fix broken exec steps
    fix get_step execution errors
    add coverage for RunScript
```
# Next Steps
- There is a consistent testflight failure that needs to be addressed
- Identify TODOs that need to be addressed prior to submitting PR
- Create issues for TODOs that can be addressed after the PR

**Comment by xtreme-sameer-vohra** [comment]
TODO
- add a summary of what we were trying to accomplish to give folks context for reviewing the PR

**Comment by xtreme-sameer-vohra** [comment]
[This](https://github.com/concourse/concourse/commit/e467b0aff21efb48fbebea83ec9979617464b486) is a temp change to validate testing and should be removed

**Comment by vito** [comment]
We might want to target this for the 6.0 beta release in order to give it more time in existing soak environments. There should be a branch `release/6.0.x` that we could PR this into first.

**Comment by xtreme-sameer-vohra** [comment]
Cleaned up history of commits
- removed concourse binary
- combined wip commits

**Comment by xtreme-sameer-vohra** [comment]
[BOSH Topgun](https://nci.concourse-ci.org/teams/main/pipelines/runtime-refactor/jobs/bosh-topgun/builds/7) is failing and we need to investigate the failures

**Comment by xtreme-sameer-vohra** [comment]
Update from last week
- branch pipeline has all relevant jobs ( bosh & k8s running - albeit experiencing genuine test failures )
- rebased off master - we had to resolve conflicts with `set_pipeline` step changes
- cleaned up commit history - squashed commits, removed WIP msgs, removed unnecessary commits

Next Steps
- review PR feedback
- resolve [BOSH Topgun](https://nci.concourse-ci.org/teams/main/pipelines/runtime-refactor/jobs/bosh-topgun/builds/7) failures

**Comment by kcmannem** [comment]
Here's the list of TODOs left before we merge:

```
TODOs before Merge:

client.go
504:		// TODO (runtime) Does it make sense to return -1 here?
540:			// TODO (runtime) This is more confusing. We should differentiate failure vs. error very explicitly
557:// TODO (runtime) don't modify spec inside here, Specs don't change after you write them

fetch_source.go
175:		// TODO: Is this compatible with previous behaviour of returning a nil when error type is NOT ErrResourceScriptFailed
178:			// TODO: we need to pass along the script error message

container.go
26:	// TODO: get rid of this, its not used anywhere
31:	// TODO: get rid of this, its not used anywhere

fetcher_test.go
58:		//TODO: stub out get()

fetcher.go
75:	// TODO: resource_instance_fetch_source.go already knows which volume to use for the resource output, can this be consolidated
80:	// TODO: just pass in imageFetcherSpec not its contents

artifact_source.go
51:// TODO: figure out if we want logging before and after streams, I remove logger from private methods
71:// TODO: figure out if we want logging before and after streams, I remove logger from private methods


get_step.go
175:	// TODO: Starting should be emitted just before the get script is executed rather than at this point
```

I've tagged the TODOs we'll tackle in another story with `// TODO (runtime/#1234):`.

**Comment by xtreme-sameer-vohra** [comment]
Fixed regression in [Testflight](https://nci.concourse-ci.org/teams/main/pipelines/runtime-refactor/jobs/testflight/builds/41)

**Comment by xtreme-sameer-vohra** [comment]
[Pipeline](https://nci.concourse-ci.org/teams/main/pipelines/runtime-refactor?group=bosh&group=k8s&group=develop) is fully 💚 this moment
