### ISSUE TITLE
Spike: Stream logs from pod task container to ATC

### ISSUE THREAD

**Issue by nader-ziada** [concourse/concourse#4266]
As part of the K8s runtime and running tasks in pods, we need to capture the logs of the task container to save in the db and show on the UI. 

Kuberenetes logging alternatives:

- Node level logging: Logs from all containers are stored on `/var/log` folder on the nodes of the clusters, running a `DaemonSet` pod in the cluster (on all nodes) to monitor this folder and stream files to a central location
- Sidecar container in the same pod as the task to capture logs and stream to the desired destination

Since we want the logs to stream back to ATC through a web socket, the sidecar might be the more suitable approach

**Comment by ddadlani** [comment]
Discussion from IPM:

* Can we wrap the `get`/`put` so that we can capture `stdout` and `stderr`? Will it be an issue to pass `get` params to `stdin` if we go down this route?
* We are trying to avoid wrapping the process because in internal environments we would need the right certs in the wrapper as well

@nader-ziada will update the issue with progress soon.

**Comment by nader-ziada** [comment]
For `step task` execution, 
 * `ATC` will call the K8s api to get a steam of the logs as soon as the pod is created and run, this will be similar to the current flow.
 * Logs from k8s api will combine `stdout` and `stderr`

For `get` and `put` steps execution
 * we need to differentiate `stdout` and `stderr` because the version of the resource will be output to `stdout` while logs will be redirected to `stderr`
 * Since we have a specific interface to what command are run in each case, when `ATC` is creating the Pod spec, it will redirect `stdout` and `stderr` to files
 * We will add a sidecar container that will monitor these files and stream the logs separately back to ATC to process

**Comment by nader-ziada** [comment]
The spike is considered complete for now, actual implementation will occur in #4391
