### ISSUE TITLE
Core: add an endpoint to re-trigger a build with the same inputs

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4268]
part of #413

A re-triggered build should:

* use the same input versions from the original build
* use a new build plan based on the current config

Implementation notes:

* We had previously discussed having re-triggered builds reuse the same exact build plan, but I think we should start simpler for now. I'm worried that might be something that's technically cool but not actually all that useful.

  One reason I can think of to *not* do that: a user may have updated their pipeline config in order to fix the build. In that case they would want to run it with the new build plan, not the old one.

  We haven't done any user validation for either case, so let's just start small. I'm not sure if it's even possible to re-use the old build plan, since it gets removed as soon as the build completes.

* If I try to re-trigger a build which is already a re-trigger, the new build should reference the *original* build, not the re-trigger. i.e. I should not end up with a nested graph.

**Comment by pivotal-jwinters** [comment]
@vito `fly execute` needs to be able to create a plan form a set of inputs too, and right now it creates that plan on its own. We should consider making an endpoint that, given a set of inputs, will spit back a plan. Both fly execute and the web could use this endpoint to get a plan, then send that plan to the builds endpoint to schedule a build. Thoughts?

**Comment by pivotal-jamie-klassen** [comment]
@pivotal-jwinters in the pursuit of 'single responsibilities' for Concourse
components, I want to propose describing this service as the 'build planner' as
distinct from a scheduler.

**Comment by vito** [comment]
@pivotal-jwinters How would the endpoint know how to construct the plan? `fly execute` specifically constructs a plan for running a single task, and each other job constructs a plan based on the YAML plan config. Isn't the plan already a pretty high-level API?
