### ISSUE TITLE
API: re-triggered builds should appear near their original build in the build history

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4270]
This is to match the desired scheduling semantics (https://github.com/concourse/concourse/issues/4269).

**Comment by Lindsayauchin** [comment]
Should look something like this...
![Screen Shot 2019-08-13 at 3 13 25 PM](https://user-images.githubusercontent.com/27746614/62970234-06bd4480-bddd-11e9-9526-cc38d917816b.png)
