### ISSUE TITLE
401 page keeps appearing

### ISSUE THREAD

**Issue by sjolicoeur** [concourse/concourse#4275]
## Bug Report
I log into a  concourse (v 5.1.0) 
I kick of a job
after a while (~60 sec)
I get presented with a 401 page
I refresh and am logged in
wait (~60-90sec)
I get presented with a 401 page
the top right button shows my username

## Expected Results

I should not see the 401 page if my session is still valid. if it is not valid I should not see my username on the top right.

## Version Info

* Concourse version: `version: v5.1.0`
* Infrastructure/IaaS: PWS
* Browser (if applicable): Chrome

**Comment by sjolicoeur** [comment]
it seems to be due to a failed response:

```
Request URL: https://concourse.com/api/v1/builds/1/events
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept: text/event-stream
Cache-Control: no-cache
Last-Event-ID: 68
Referer: https://concourse.com/teams/myteam/pipelines/mypipeline/jobs/myjob/builds/2
User-Agent: Chrome/75.0.3770.142 Safari/537.36
```

**Comment by JamesDunne** [comment]
After exactly 50 seconds of opening the build status page to monitor the logs, and where no new logs appear in those 50 seconds, Chrome inspector shows the failed `events` request as `net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)` which Concourse UI interprets somehow as a 401 Unauthorized and shows that full-page icon and message.

![image](https://user-images.githubusercontent.com/538152/63541328-77eaaf00-c4e3-11e9-89e4-c1212d37574b.png)

The inspector was cropped here to protect privacy of the full URLs being used.
