### ISSUE TITLE
Control characters in task params causes incorrect conversion of YAML to JSON

### ISSUE THREAD

**Issue by dawu415** [concourse/concourse#4276]
## Bug Report

Inputting yaml formatted data into params of tasks subsequently get converted to a JSON format when reading from a container's environment variable.  If the YAML map data contains newlines, the newlines are not escaped and become part of the JSON.    The JSON specification does not allow control characters in its format http://json.org/ and consequently, this causes some headache when trying to convert the JSON back into YAML via tools like `bosh interpolate` (https://github.com/cloudfoundry/bosh-cli/issues/248) .  

The issue maybe caused by how `"github.com/ghodss/yaml"` handles the strings in `NewTaskConfig` at https://github.com/concourse/concourse/blob/4a191e719c91fb3c8f57dff85a8f7e40e014ea64/atc/task.go#L56

## Steps to Reproduce
Assume I have a certificate in the following format in Credhub, having only newlines and no carriage returns.

```
-----BEGIN CERTIFICATE-----
MIIC3aaaaaaaDAwMQswCQYDVQQGxxxxxxxsjlsdkfjsdlkfjsdlkjsdvlskdEwJB
VTENMAsGA1UECwwEZGF3dTESMBAGA1UEAwwJKi5kYXd1LmlvMB4XDTE5MDYwNjAz
MTEzNVoXDTIwMDYwNTAzMTEzNVowMDELMAkGA1UEBhMCQVUxDTALBgNVBAsMBGRh
d3UxEjAQBgNVBAMMCSouZGF3dS5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBANBuhemwaaaaaaaaaaaaaaaaaaajCj+Yo20QhidabJ8SgrrSFJEz/btm
UQATAqLXOczhIqxJzIOIhW2klI4JQTkR96FZkqCOktKtQNjXrL+5L2Jb7ouHLak7
8j3HjhCmmfgh7MZ1wq7O+MUyDCEHI5ixd8eC8TEr1XgCJyhqlYestsWhvGUP8gth
DGgFHMBOx033RvVkTbJcagSspMsQZ/sCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
bocw2bBJfb2uvK0Ej5PpTQPBnynVsJxBvCJlSAqA7Mk9NieRSbdj7Ul+nRViSwER
41bTogRS4mhl3qaLGThB4DlsS/wqRp5ocTqBMWkCssEdCWwkJVWZxPQ42Kh5uXYY
9JsEudPLv0hh+b5Oyoi7f2asljasflkasjflkGSqEJH2xauwfZnKTjeb/tmtqtoi
coL/1owTdHspg59SQYUBJUPlc0Ids6OolsmOnO9icwJ7c1AIkpKps4mL9XgxCtD7
BVRmQ5RwTOlBLAmpU7R1gg==
-----END CERTIFICATE-----
```

If I have a task in Concourse like this

```
    - task: generate-configs
      image: some-docker-image
      params:
        CONFIGS:
           certificate: ((cert_in_credhub))
           config: abcd
      config:
        platform: linux
        run:
          path: bash
          args:
          - -c
          - |
            printenv CONFIGS
```

I will end up with an output like this

```
{"certificate": "-----BEGIN CERTIFICATE-----
MIIC3aaaaaaaDAwMQswCQYDVQQGxxxxxxxsjlsdkfjsdlkfjsdlkjsdvlskdEwJB
VTENMAsGA1UECwwEZGF3dTESMBAGA1UEAwwJKi5kYXd1LmlvMB4XDTE5MDYwNjAz
MTEzNVoXDTIwMDYwNTAzMTEzNVowMDELMAkGA1UEBhMCQVUxDTALBgNVBAsMBGRh
d3UxEjAQBgNVBAMMCSouZGF3dS5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBANBuhemwaaaaaaaaaaaaaaaaaaajCj+Yo20QhidabJ8SgrrSFJEz/btm
UQATAqLXOczhIqxJzIOIhW2klI4JQTkR96FZkqCOktKtQNjXrL+5L2Jb7ouHLak7
8j3HjhCmmfgh7MZ1wq7O+MUyDCEHI5ixd8eC8TEr1XgCJyhqlYestsWhvGUP8gth
DGgFHMBOx033RvVkTbJcagSspMsQZ/sCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
bocw2bBJfb2uvK0Ej5PpTQPBnynVsJxBvCJlSAqA7Mk9NieRSbdj7Ul+nRViSwER
41bTogRS4mhl3qaLGThB4DlsS/wqRp5ocTqBMWkCssEdCWwkJVWZxPQ42Kh5uXYY
9JsEudPLv0hh+b5Oyoi7f2asljasflkasjflkGSqEJH2xauwfZnKTjeb/tmtqtoi
coL/1owTdHspg59SQYUBJUPlc0Ids6OolsmOnO9icwJ7c1AIkpKps4mL9XgxCtD7
BVRmQ5RwTOlBLAmpU7R1gg==
-----END CERTIFICATE-----", "config": "abcd"}
```

The above is an invalid JSON per http://json.org

## Expected Results

The output of the JSON should look like this 

```
{"certificate": "-----BEGIN CERTIFICATE-----\nMIIC3aaaaaaaDAwMQswCQYDVQQGxxxxxxxsjlsdkfjsdlkfjsdlkjsdvlskdEwJB\nVTENMAsGA1UECwwEZGF3dTESMBAGA1UEAwwJKi5kYXd1LmlvMB4XDTE5MDYwNjAz\nMTEzNVoXDTIwMDYwNTAzMTEzNVowMDELMAkGA1UEBhMCQVUxDTALBgNVBAsMBGRh\nd3UxEjAQBgNVBAMMCSouZGF3dS5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\nAQoCggEBANBuhemwaaaaaaaaaaaaaaaaaaajCj+Yo20QhidabJ8SgrrSFJEz/btm\nUQATAqLXOczhIqxJzIOIhW2klI4JQTkR96FZkqCOktKtQNjXrL+5L2Jb7ouHLak7\n8j3HjhCmmfgh7MZ1wq7O+MUyDCEHI5ixd8eC8TEr1XgCJyhqlYestsWhvGUP8gth\nDGgFHMBOx033RvVkTbJcagSspMsQZ/sCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA\nbocw2bBJfb2uvK0Ej5PpTQPBnynVsJxBvCJlSAqA7Mk9NieRSbdj7Ul+nRViSwER\n41bTogRS4mhl3qaLGThB4DlsS/wqRp5ocTqBMWkCssEdCWwkJVWZxPQ42Kh5uXYY\n9JsEudPLv0hh+b5Oyoi7f2asljasflkasjflkGSqEJH2xauwfZnKTjeb/tmtqtoi\ncoL/1owTdHspg59SQYUBJUPlc0Ids6OolsmOnO9icwJ7c1AIkpKps4mL9XgxCtD7\nBVRmQ5RwTOlBLAmpU7R1gg==\n-----END CERTIFICATE-----", "config": "abcd"}
```
i.e., the newlines are escaped and become literals.  

Ths same should also apply for carriage returns 

## Actual Results

See Above in Steps to Reproduce 

## Version Info

* Concourse version: 4.2.4
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS: Any
* Browser (if applicable): All
* Did this used to work? No

## Workarounds
I would have to do this 
`awk -v ORS='\\n' '1' <(printenv CONFIGS | tr -d '\r')`
which would output this

```
{"certificate": "-----BEGIN CERTIFICATE-----\nMIIC3aaaaaaaDAwMQswCQYDVQQGxxxxxxxsjlsdkfjsdlkfjsdlkjsdvlskdEwJB\nVTENMAsGA1UECwwEZGF3dTESMBAGA1UEAwwJKi5kYXd1LmlvMB4XDTE5MDYwNjAz\nMTEzNVoXDTIwMDYwNTAzMTEzNVowMDELMAkGA1UEBhMCQVUxDTALBgNVBAsMBGRh\nd3UxEjAQBgNVBAMMCSouZGF3dS5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\nAQoCggEBANBuhemwaaaaaaaaaaaaaaaaaaajCj+Yo20QhidabJ8SgrrSFJEz/btm\nUQATAqLXOczhIqxJzIOIhW2klI4JQTkR96FZkqCOktKtQNjXrL+5L2Jb7ouHLak7\n8j3HjhCmmfgh7MZ1wq7O+MUyDCEHI5ixd8eC8TEr1XgCJyhqlYestsWhvGUP8gth\nDGgFHMBOx033RvVkTbJcagSspMsQZ/sCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA\nbocw2bBJfb2uvK0Ej5PpTQPBnynVsJxBvCJlSAqA7Mk9NieRSbdj7Ul+nRViSwER\n41bTogRS4mhl3qaLGThB4DlsS/wqRp5ocTqBMWkCssEdCWwkJVWZxPQ42Kh5uXYY\n9JsEudPLv0hh+b5Oyoi7f2asljasflkasjflkGSqEJH2xauwfZnKTjeb/tmtqtoi\ncoL/1owTdHspg59SQYUBJUPlc0Ids6OolsmOnO9icwJ7c1AIkpKps4mL9XgxCtD7\nBVRmQ5RwTOlBLAmpU7R1gg==\n-----END CERTIFICATE-----", "config": "abcd"}
```

**Comment by vito** [comment]
Good catch! Guessing you're running nightly builds? I'll put this in the v5.5 milestone so we investigate it before shipping.

**Comment by vito** [comment]
Side note: it looks like we might want to switch to https://github.com/kubernetes-sigs/yaml - I haven't checked whether it fixes this issue, but a lot of discussions are pointing to it as the successor as `ghodss/yaml`:

* https://github.com/ghodss/yaml/pull/39#issuecomment-435545024
* https://github.com/ghodss/yaml/issues/50#issuecomment-511004721

**Comment by vito** [comment]
Actually, just saw that you're running 4.2.4. We don't actually use `ghodss/yaml` in that version - just regular YAML/JSON libraries.

Would you be able to provide a repro for this? I can run it against our nightly builds and see if it's still a problem. I just got done re-doing a lot of this in #3505 which is where we introduced `ghodss/yaml` and also re-did how task params are coerced to strings (https://github.com/concourse/concourse/commit/057a857bb9e1f28f6f0443b32c741c48cd17db87).

One datapoint is that the linebreaks seem to get converted to spaces after parsing the YAML even with `gopkg.in/yaml.v2`: https://play.golang.org/p/E7jXf6njkdw

**Comment by dawu415** [comment]
cool, let me repro this.

Interestingly, I did a similar code snippet in Go playground yesterday with the `ghodss/yaml` and then `sigs.k8s.io/yaml` just before.  They exhibit the same behavior of converting the newlines to spaces.

**Comment by vito** [comment]
@dawu415 On second though, I would actually recommend you set two different env vars rather than relying on Concourse to JSON-marshal the value for you. We'll probably be moving away from automatic coercion like that because it's pretty error-prone and somewhat surprising.

So you could try doing this instead:

```yaml
params:
  CONFIG_CERTIFICATE: ((cert_in_credhub.certificate))
  CONFIG_FOO: ((cert_in_credhub.foo))
```

**Comment by vito** [comment]
Closing this per https://github.com/concourse/concourse/issues/4276#issuecomment-521650249 - we don't intend to support the automatic string coercion any more than what's already there, so we won't be fixing this. This behaviour will likely be removed or deprecated in the future.

Thanks!
