### ISSUE TITLE
fly hijack websocket bad handshake may be result of fly target saved incorrectly

### ISSUE THREAD

**Issue by aegershman** [concourse/concourse#4282]
This isn't a bug report or feature request, I just want to put this out there in case someone else comes across an issue with `fly hijack` where they get a `bad handshake`. I was debugging this by looking at https://github.com/concourse/fly/issues/108 or https://github.com/concourse/concourse/issues/1774 or https://github.com/concourse/concourse/issues/1342

My NLBs were all listening on TCP, the nginx-ingress was working just fine, etc., so it was perplexing why I was still getting a bad handshake timeout.

It turns out my `fly target` was saved using `http` rather than `https`. Example:

```sh
# was resulting in bad handshake...
# notice how it's HTTP not HTTPS as the target protocol
fly -t mytarget login c http://concourse.flarp.gov -n foo

# worked just fine
fly -t mytarget login c https://concourse.flarp.gov -n foo
```

Going to close this immediately, just wanted this out there so people could see. I was a total dingus about this and it took me a few hours to "fix", so I'm putting it out there to save others from my doofus dingusness.

Thanks!

**Comment by pratikbalar** [comment]
Thank you I checked everywhere in infra and thought something related to infra.
