### ISSUE TITLE
Why is the linux build so much bigger than the others?

### ISSUE THREAD

**Issue by retrogradeorbit** [concourse/concourse#4288]
Not a bug, just a question I'm having a hard time trying to find the answer to.

Take the 5.4.1 built artifacts for example:

darwin: 61.3MB
windows: 59.1MB
linux 537 MB!!

It's almost ten times the size!!

However the fly artifact, they are all about the same size.

What is going on here?

**Comment by kcmannem** [comment]
I believe we package linux with our base resource types (git, docker, etc...) in the linux binary. These resources are based off of ubuntu docker images which are quite large. Non-linux workers do not run resources (checks, gets, puts) but only tasks. So their binaries will be a lot smaller.

cc @cirocosta you've been working on something for this right?

**Comment by vito** [comment]
We actually package the `alpine` variants for the binary distribution since otherwise it'd be even bigger.

We're planning to extract them out: https://github.com/concourse/rfcs/pull/30
