### ISSUE TITLE
make urls in metadata clickable

### ISSUE THREAD

**Issue by cppforlife** [concourse/concourse#429]
auto link any link looking things in resource metadata shown on build page.

**Comment by xoebus** [comment]
We had some forward thinking links and markdown conventions for this at some point. Maybe those didn't make it.

**Comment by evanchaoli** [comment]
Any progress on this? This is a feature we are looking for. I was going to open an issue for this, and then found this existing one has been here for long time. My team is willing to contribute to this feature.
