### ISSUE TITLE
Sidecar container to monitor and stream logs of Put and Get steps 

### ISSUE THREAD

**Issue by nader-ziada** [concourse/concourse#4295]
As part of the K8s runtime and running get and put steps in pods, we need to capture the logs of the these steps and differentiate `stdout` and `stderr` because the version of the resource will be output to stdout while logs will be redirected to stderr.

As mentioned in #4266, the pod running `Get` and `Put` tasks will redirect the output to files and add a sidecar container to stream these logs. This issue is to to cover the implementation of the image running in this sidecar

Requirements 
 * monitor seperate logs in files for `stdout` and `stderr`
 * stream these logs back to `ATC` using a socket, probably two different sockets 
 * this image should be published in dockerhub or similar so ATC can add this sidecar container to the pod

**Comment by deniseyu** [comment]
Here's the pattern we're spiking on:

Inside the pod for the `get` step, three containers actually get scheduled:

1. the `step-container` that takes arbitrary resource config input
1. one `stdout-sidecar`
1. one `stderr-sidecar`

As a first pass, we're just going to split apart the log streams from the container execution command in the most......MVP way possible: 

```
	c := v1.Container{
		Name:    TaskExecutionContainerName,
		Image:   "concourse/git-resource:latest",
		Command: []string{"/bin/bash"},
		Args: []string{"-c",
			"echo '{\"source\": {\"uri\": \"https://github.com/vito/booklit\"}}' | /opt/resource/in /tmp/build/in >/tmp/build/stdout 2>/tmp/build/stderr"},
		VolumeMounts: volumeMounts,
		Env:          implicitEnvVars,
		WorkingDir:   "/tmp/build",
	}
```

the three containers will share a volume mount that we're calling `/tmp/build`.

The two sidecar containers will be configured to Wait for the completion of the `get` container, leveraging code that we previously wrote in Porter.

For now, both sidecar containers will just emit the contents of their respective log files to the stdout buffer so it shows up in `kubectl logs`, and hopefully in the next few days we'll be able to wire up these logs to the Concourse UI!

**Comment by deniseyu** [comment]
Random note: I updated `gcloud components` to the latest version 260 on the workstation and this code stopped working. It seems to work with v249 though. Will investigate why later....

**Comment by deniseyu** [comment]
Tasks that need doing:

- [ ] See stdout and stderr streaming to Concourse UI
- [ ] Add integration tests for porter logstreaming
- [ ] Fix gcloud sdk issue
- [ ] Integrate spike with refactored `get` step
- [ ] Manually test that we can fetch a resource with Get, put in the blobstore, then take it out of the blobstore and do a simple interaction with it in a task step

**Comment by deniseyu** [comment]
Blocked on https://github.com/concourse/concourse/issues/4265

**Comment by nader-ziada** [comment]
The spike is considered complete, actual implementation will be done in #4391
