### ISSUE TITLE
Worker VM out of space 

### ISSUE THREAD

**Issue by mike1808** [concourse/concourse#4297]
## Bug Report

We have three worker VMs and one of them was running of space while other two utilizing only ~33% of the disk.

## Steps to Reproduce

[failing pipeline where you can the actual error](https://routing.ci.cf-app.com/teams/ga/pipelines/routing/jobs/diana-tcp-perf-tests/builds/425)
[our concourse bbl and deployment](https://github.com/cloudfoundry/deployments-routing/tree/master/concourse-gcp)

## Expected Results

* disk space is spread evenly across worker VMs
* more meaningful error message when a resource is failed to be created because of out of disk space error, currently it is `failed to create volume`
* worker VMs to be able to "clean" themselves 

## Actual Results

* one of worker VM went out of space
* resources were erroring with `failed to create volume`
* jobs went "orange"

## Additional Context

We were running Concourse 4.2.3 until July 25.

## Version Info

* Concourse version: 5.7
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): N/A
* Did this used to work? we haven't had this error before

cc @tstannard

**Comment by kcmannem** [comment]
I think you might have tagged the wrong concourser version, we haven't reached 5.7 yet. You should just `bosh recreate` the workers that have run out of space.
