### ISSUE TITLE
UI bug: pipeline_operator role label

### ISSUE THREAD

**Issue by GergelyKalmar** [concourse/concourse#4306]
## Bug Report

The little role label looks wrong for teams with the pipeline_operator role:

![image](https://user-images.githubusercontent.com/5601876/63415154-90809980-c3fd-11e9-97b9-db6cab6abfb4.png)

## Version Info

* Concourse version: v5.4.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chromium 76.0.3809.100 as well as Firefox 68.0.2 running on Ubuntu 16.04
* Did this used to work? no

**Comment by pivotal-jamie-klassen** [comment]
this was fixed in #4170 on master and will be in v5.5
