### ISSUE TITLE
Docs: Add concourse version required to use in_parallel step

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#4316]
To avoid cases where people that are using an older version of Concourse to try and use features that were newly added (in this case the `in_parallel` step with #4179) we should add to the docs the Concourse version required to use the feature. 

https://concourse-ci.org/in-parallel-step.html

**Comment by jomsie** [comment]
This is probably still something we should figure out...

Looks like concourse/docs has an overarching issue https://github.com/concourse/docs/issues/25, but it's old.
