### ISSUE TITLE
web: render build output delimited by `\e]8` sequences as links

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4318]
## What challenge are you facing?

A few times, users have asked for ways to have hyperlinks in their Concourse build output.

Given that [libVTE, derived products, and some other terminal emulators](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) already use this escape sequence to delimit links, it seems uncontroversial for Concourse to do the same - it has no specified function within the ANSI standard, and the alternative is rendering something silly like 

![Screen Shot 2019-08-26 at 3 14 18 PM](https://user-images.githubusercontent.com/22056320/63716524-3bd18a00-c814-11e9-9fed-79fbf330b9c0.png)

## What would make this better?

Make them links!

## Are you interested in implementing this yourself?

:+1: but maybe it doesn't belong in a library explicitly named elm-ANSI.

**Comment by jamie-pate** [comment]
The closes 'spec' for these oc8 links that I could find mentions that if you see the escape sequence then the terminal emulator incorrectly implements OSC parsing according to ECMA-48
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#backward-compatibility

**Comment by jamie-pate** [comment]
![Screenshot from 2023-09-06 16-29-57](https://github.com/concourse/concourse/assets/682658/61f9f433-0858-4e6f-93a2-ff860aa3224b)

**Comment by analytically** [comment]
https://github.com/vito/elm-ansi/pull/12
