### ISSUE TITLE
Ability to Mark a Resource as "Do Not Cache"

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#4321]
#  What challenge are you facing?

When using the Pool resource sometimes it returns old "versions" of the resource without running the get step again. This means that it doesn't do the `check_if_file_changed_in_range` check for that build. This means that jobs run against locks that are no longer claimed.

## What would make this better?

Other than duplicating the pool resource `check_if_file_changed_in_range` check in a task, the only way I can see to address this would be to force concourse to run the get step *every* time that the pool resource is "got". This would probably necessitate a concourse feature that would allow us to mark a resource or a resource type as "DO NOT CACHE". That way the get script would run every time a build consumes the resource and so the `check_if_file_changed_in_range` check would run every time a build consumes it and then builds will be guaranteed to fail if the lock has been unclaimed.

## Are you interested in implementing this yourself?

No. My team doesn't have the bandwidth.

**Comment by vito** [comment]
I don't think this will be happening; my recent [blog post](https://blog.concourse-ci.org/reinventing-resource-types/) goes into more detail as to why I don't want to add these sorts of knobs around resources, from a high-level design standpoint.

The implication here being that the 'pool resource' really shouldn't be a resource, and should be accomplished with some other kind of pipeline abstraction.
