### ISSUE TITLE
Pipeline/Job/Build statistics/reports.

### ISSUE THREAD

**Issue by simonjohansson** [concourse/concourse#4322]
Howdie!

## What challenge are you facing?

It's unintuitive for a user to get statistics for a pipeline[1]. Whilst it's doable

```
TARGET=myTarget
PIPELINE=myPipeline
JOBS=$(fly -t $TARGET jobs -p $PIPELINE --json | jq -r '.[].name')

while read -r JOB; do
	BUILDS=$(fly -t $TARGET builds -j "$PIPELINE/$JOB" -c 1000 --json | jq -c '.[]')

	NUM_BUILDS=0
	TOTAL_TIME=0

	while read -r BUILD; do
		NUM_BUILDS=$((NUM_BUILDS + 1))
		DELTA=$(echo $BUILD | jq '.end_time-.start_time')
		TOTAL_TIME=$((TOTAL_TIME + DELTA))
	done <<< $BUILDS

	AVG_BUILD_TIME=$((TOTAL_TIME / NUM_BUILDS))
	echo $JOB has run $NUM_BUILDS times with an avarage execution time of $AVG_BUILD_TIME seconds
done <<< $JOBS
```

It's hard to tell our users that if you want this kind of information just run some bash.

## What would make this better?

It would be much neater to be able to get this kind of information directly in the Concourse UI.

I realise that the UI backlog is pretty full ATM but I think it would be very useful to have a API endpoint that we can use to render graphs/reports with a third party app ASAP as this is something that our users wants.
 
Given the following data structures we should be able to render all sorts of fancy graphs and reports 

```
type BuildReport struct {
	Name      string
	StartTime int64 // StartTime.Unix()
	EndTime   int64
	Duration  float64 // EndTime.sub(StartTime).Seconds()
	Status    BuildStatus
}

type JobReport struct {
	Name         string // Name of job
	Builds       int // Number of builds we looked at, excluding pending and started
	Aborted      int // Number of aborted builds
	Succeeded    int // Number of ...
	Failed       int // ...
	Errored      int // ...
	BuildHistory []BuildReport // More details info about each build for graphing etc.
}

type PipelineReport struct {
	Name string // Name of pipeline
	Jobs []JobReport // Stats per job in build
}
```

```
/api/v1/teams/:team_name/pipelines/:pipeline_name/jobs/:job_name/builds/:build_name/report -> BuildReport
/api/v1/teams/:team_name/pipelines/:pipeline_name/jobs/:job_name/report -> JobReport
/api/v1/teams/:team_name/pipelines/:pipeline_name/report -> PipelineReport
```

## Are you interested in implementing this yourself?

Yep.

[1] 
https://circleci.com/docs/2.0/insights/
https://www.jetbrains.com/help/teamcity/2019.1/statistic-charts.html
etc.

**Comment by simonjohansson** [comment]
Nothing would need to be stored in the dB as the BuildReport is generated from a dB.Build, JobReport is a collection of the former with some more calculations. 

The end goal would be to have this information in the Concourse web ui, like
In most other build systems. Requiring a tsdb for this info would complicate the deployment :)

**Comment by simonjohansson** [comment]
Yes/No/Maybe?

**Comment by pypmannetjies** [comment]
This would be such a useful feature IMO
