### ISSUE TITLE
ATC: users randomly but regularly logged out of Concourse

### ISSUE THREAD

**Issue by tuddenham** [concourse/concourse#4325]
## Bug Report

When logged in to our Concourse environment, users are regularly logged out  and forced to re-authenticate, in some cases up to 5 times times in an hour.  Additionally about 10% of the time, authentication times out and creates a local file in the download folder 'callback.dms' .  Authentication method is GitHub.

## Steps to Reproduce

User clicks login on Concourse web front-end and authenticates using GitHub.  After looking at pipelines for a short period, the user is de-authenticated from the groups they are logged in as and redirected to the login page. Problems with authentication occur more during working hours.

## Expected Results

For an authenticated user to remain logged in for a reasonable and predictable period, eg 8 hours.

## Actual Results

Users are logged out randomly (sometimes in under an hour) and redirected from whatever pipeline they were looking at to the login page.  Sometimes login times out / fails with an empty callback.dms file created in the users download folder.  

## Additional Context

We are using haproxy v9.4.2 in front of two atc VMS.  Authentication method is GitHub.

## Version Info

* Concourse version: v5.4.1 (but noticeable since 5.x)
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Softlayer
* Browser (if applicable): Safari and Chrome
* Did this used to work?  Yes

**Comment by taylorsilva** [comment]
Going to start by asking a silly question. What value do you have set for `--auth-duration` for your `concourse web`, if any value is even set.

```
--auth-duration=     Length of time for which tokens are valid. Afterwards, users will have to log back in. (default: 24h) [$CONCOURSE_AUTH_DURATION]
```

Second question. Can you check what the `Expires` value is in your cookie after logging in? With Chrome you can see this using the dev tools > Application > Cookies > Expires/Max Age
<img width="1577" alt="Screen Shot 2019-09-02 at 10 02 46 PM" src="https://user-images.githubusercontent.com/4583837/64139067-a6169b80-cdcd-11e9-9b4a-460544ecbffe.png">

**Comment by tuddenham** [comment]
it's not set via the bosh config for the web vms, so defaults to the 24h value - the web bpm.yml file contains `CONCOURSE_AUTH_DURATION: "24h"`.  Checking the expires / Max-Age value for sky marshal_auth (which is without the '0' in our case) it is similar to yours - set to a value 24 hours in advance and in UTC looking like '2019-09-04T09:35:35:919Z'

**Comment by taylorsilva** [comment]
Thanks for the info. I'm really not sure how to reproduce though. When the error happens to you can you check:

1. The state of the cookie in your browser
2. The logs on the concourse web server(s) for any auth-related errors

I've tried changing the value of `auth-duration` but I'm getting the expected behaviour.

**Comment by coffee-squirrel** [comment]
We seem to be running into this as well, but have mostly just been ignoring it.  I'll try to see what I can find, but to start...

* Firefox 68.0.2
* Concourse v5.4.1 (BOSH)
* 1 `web` (accessed directly via HTTPS on `8443`), 1 `db`, 2 `worker`
* The `web` instance's `/var/vcap/jobs/web/config` has `CONCOURSE_AUTH_DURATION: "24h"`
* The `skymarshal_auth` cookie, with an expiration time ~22 hours off, was apparently deleted/cleared while I had the browser+tab open (background, though).
* No `skymarshal` mentions in `/var/vcap/sys/log/web/web.stdout.log` (still skimming through)

**Comment by tuddenham** [comment]
Since logging this we have not had a re-occurance but will provide an update with cookie and log state if/when it does.
