### ISSUE TITLE
High CPU usage on ATC

### ISSUE THREAD

**Issue by aledeganopix4d** [concourse/concourse#4327]
## Bug Report

We've deployed a recent RC on our production environment, one based on 7c63f45bc1dd146b790e17fdad008e76d3487356.
Immediately after the deployment the CPU usage of the ATC jumped to ~99% and stays there almost constantly.
Whether before we would have an average usage around ~60% (both with v5.3.0 and an RC based on 56721145ebe9c3a02cf45183d86469758de55716)

## Steps to Reproduce

Deploying 7c63f45bc1dd146b790e17fdad008e76d3487356 from 56721145ebe9c3a02cf45183d86469758de55716, with all the pipelines/jobs/teams staying the same.

## Additional Context

So far the CPU usage is only seen through metrics, no impact on the final users.
We are testing the container placement strategy `limit-active-tasks` with a maximum `active_tasks == 1`, but I don't have reason to believe that's related.

I'm attaching a profile taken with pprof.

[pprof.concourse.samples.cpu.001.pb.gz](https://github.com/concourse/concourse/files/3556140/pprof.concourse.samples.cpu.001.pb.gz)

**Comment by xtremerui** [comment]
Based on the pprof, it looks like the parsing of job config is slow. Could you specify roughly how many jobs are there in total?

**Comment by aledeganopix4d** [comment]
We have 1828 jobs across 161 pipelines.
About the config of each jobs is kinda tricky to define, I would say that - on average - a job has 3 tasks each with couple of inputs/outputs.
