### ISSUE TITLE
Concourse Intermittently Stops Checking Resources

### ISSUE THREAD

**Issue by saedalavinia** [concourse/concourse#4336]
## Bug Report

Starting with Version 5.4.1, Concourse intermittently stops checking new resources 

## Steps to Reproduce

It happens intermittently and at random and we have not been able to find a specific sequence. We have also noticed that when it happens either of the following two happens: 
1. Manually checking for a resource resolves the issue (the resource check timer goes back to 0) 
2. Manually checking for a resource has no result and the timer continues. 
* Manually checking via the `UI`  reports success with checkmark but it has no effect
* Manually checking via `fly -t TARGET cr -r SOME-PIPELINE/SOME-RESOURCE` eventually times out

## Expected Results

Resources are checked every x amount of time, where x corresponds to the ` CONCOURSE_RESOURCE_CHECKING_INTERVAL`  env var

## Actual Results

The resources don't get checked
![image](https://user-images.githubusercontent.com/5727936/64031942-78083180-cb17-11e9-9bd3-fd8d69595f1d.png)

## Version Info

* Concourse version: 5.4.1
* Deployment type (BOSH/Docker/binary): Docker on K8s
* Infrastructure/IaaS: EKS
* Browser (if applicable): N/A
* Did this used to work? we never had any issue pre 5.4.1

**Comment by kcmannem** [comment]
The check engine is being redone, this maybe resolved when this gets merged: https://github.com/concourse/concourse/pull/4202

**Comment by clarafu** [comment]
@saedalavinia Is it only for specific resources that don't get checked at a time? For example, do you see that this resource hasn't been checked in 20 minutes and others have been checked within a minute or is it that all resources haven't been checked in 20 minutes.

Just to be sure, those resources that take longer don't have a `check_every` value set on the resource configuration?

Honestly we can't tell what exactly is causing your checks to not run, we have previously worked on a few issues that we were hoping to have fixed this problem (#3928). In that case we thought it might be that it was failing when concourse is trying to reach garden but merging #3928 should have solved that. It really depends on exactly where radar failed in order to know if #4202 will fix it.

**Comment by saedalavinia** [comment]
It is not for a specific resource and there is no coordination between unchecked and checked resources. 
You could have a mix of checked resources and unchecked resources for 7 minutes and unchecked resources for 17 minutes all at the same time. 
And none of those resources have a check_every explicitly deifned in the pipeline. 

Do we have an ETA for #4202

**Comment by clarafu** [comment]
@saedalavinia Yup #4202 should be shipped with the next minor release (v5.6.0). I'd like you to try out the next release and see if it fixes it, but if it doesn't can you ping me again and we can go further into debugging what exactly is causing your resource checks to not happen.

Thanks!

**Comment by miguelsimon** [comment]
We've observed this, running on kubernetes in gke. It's troublesome as there's no clear indication that things are wrong: you need to realize jobs aren't triggering when expected and navigate to the check timer to see that it's increasing to diagnose the issue.

When it happened on 5.4.1 we observed the same behaviour @saedalavinia described:
* Manually checking via the UI reports success with checkmark but it has no effect
* Manually checking via fly -t TARGET cr -r SOME-PIPELINE/SOME-RESOURCE eventually times out

We tried:
* restarting our single ATC node: no effect
* restarting the worker nodes: no effect
* restarting the postgres node: checks started working again after this

It seems to have happened again on 5.5.0 yesterday, a job triggered many hours after the commit that should have triggered it occurred (the same commit triggered several other pipelines that depended on it on time, as expected), but I didn't actually observe the behaviour as it happened in this case.
