### ISSUE TITLE
fly login is broken on Darwin if you are part of many teams.

### ISSUE THREAD

**Issue by simonjohansson** [concourse/concourse#4339]
Given https://github.com/concourse/concourse/issues/3747 we are forced to copy the token and paste it, which is unfortunately broken on Darwin if you are part of a lot of teams. 

A user which is part of only a few teams gets a token that is pretty small, but if a user is part of many teams the token will be big(mine is > 3000 chars) and login breaks.

```
OSX: 10.14.5
Fly: 5.4.1
Shell: reproducible on zsh 5.3 (x86_64-apple-darwin18.0) and GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
```

```
$ fly -t TARGET login -c https://meeh.io -n TEAM
logging in to team 'TEAM'

navigate to the following URL in your browser:

  htttps://meeh.io/login?fly_port=51847

or enter token manually: Bearer .......^C 
# Stops accepting input after 1024 chars, enter does not work, only way out is ^C
```

However

```
$ STTY=-icanon fly -t TARGET login -c https://meeh.io -n TEAM
logging in to team 'TEAM'

navigate to the following URL in your browser:

  htttps://meeh.io/login/login?fly_port=64084

or enter token manually: Bearer superSecret.Long.JWT

target saved
```

Not a problem with fly per se, but this issue is affecting the users.

**Comment by cirocosta** [comment]
Hey @simonjohansson ,

If I understood correctly, this gets solved with https://github.com/concourse/concourse/pull/4280, doesn't it? (please let me know if I got it wrong 😁 )

That was released as a backport for the 5.2.x series (https://github.com/concourse/concourse/releases/tag/v5.2.1), and will be in 5.5.0 that we'll be shipping very soon.

Thank you!

**Comment by simonjohansson** [comment]
@cirocosta looking at the code you split up the token into multiple cookies, for us to use the token we still need the full token so this change would not solve the issue.

**Comment by cirocosta** [comment]
ooooooooh got it!

thanks for the further explanation! 

just found https://superuser.com/a/219304, which points to https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/syslimits.h#L82:

```c
#define	MAX_INPUT		 1024	/* max bytes in terminal input */
```

interesting 🤔

**Comment by simonjohansson** [comment]
1024 ought to be enough for anybody.. :)
