### ISSUE TITLE
Get rid of CGO

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#4342]
## What challange are you facing?

At the moment, cross compiling Concourse to multiple platforms
from a given OS is hard (maybe even not possible?) given that we
end up having to compile native code.

I'm pretty sure there are other good reasons to remove it
(performance and safety-wise) too, although I didn't think much
about it (aside from remembering that we had to deal with a mem
leak at some point that was hard to figure out as the memory
allocations were not tracked by Go).

## What would make this better?

Remove the dependencies that we introduced that brought CGO to
our codebase:

- go-sqlite (from dex)
        - I guess we could somehow disable the "plugin-based"
          introduction of it
- zstd
        - we could replace it with something like `pierrec/lz4`
          which is all go-based

thanks!

**Comment by jchesterpivotal** [comment]
For zstd, there appear to be pure-go implementations:
* https://github.com/KillingSpark/sparkzstd
* https://github.com/klauspost/compress

**Comment by kcmannem** [comment]
@jchesterpivotal thanks for the links, gunna look into this.

**Comment by cirocosta** [comment]
🙌

**Comment by cirocosta** [comment]
One more reason to double down on removing cgo: with the `-trimpath` compile flag we could get reproducible concourse builds (e.g. https://github.com/k14s/kapp/commit/b645918be88c91b79c9ca4b3bc76a1e34ff3cadd)

**Comment by pivotal-jamie-klassen** [comment]
Happy to see https://github.com/concourse/concourse/issues/4621#issuecomment-574268276 stepping in the right direction. Too bad that using dex means opting into CGO...

**Comment by pivotal-jamie-klassen** [comment]
A story of CGO pain:
A while back we were working on a series of 5.2.x patches. While doing so, we got some early user feedback:
> `fly` doesn't work. Any time I try to run any commands it breaks with a weird error complaining about my kernel version".

Digging deeper, we discovered the user was running `fly` on a very old version of RHEL. @cirocosta worked out a way to reproduce, by creating a VM on GCP running CentOS 6. When attempting to execute `fly` on this machine, we did indeed see the error they mentioned. Why was this happening?

It turned out that we were [statically building `fly` with CGO](https://github.com/concourse/ci/issues/178) inside a container image based on Ubuntu bionic, which came with glibc 2.27+, which has a hard-coded dependency on the Linux kernel being newer than that which ships in CentOS 6.

Eventually we got things working by doing stuff like concourse/ci#135, but the result is a bit of a wart in our CI scripts - why is the `golang-builder` image (and therefore the other images that we run in our CI) [based on xenial](https://github.com/concourse/ci/blob/master/dockerfiles/golang-builder/Dockerfile#L1) when the images we ship (like base resources and the concourse image itself) are based on bionic?

If we can kill CGO, we can have the whole delivery chain using bionic-based images.

**Comment by cirocosta** [comment]
I was trying to get a sense of how we should approach the `go-sqlite` case, and it seems like there
are two promissing approaches that we could go with given that the functionality (use of `sqlite3`)
is reasonably isolated: it's all under [`storage/sql/sql.go`] and [`storage/sql/config.go`].


[`storage/sql/config.go`]: https://github.com/dexidp/dex/blob/d820fd45d80cef74d4c65f5fcc5766ddb1fa514e/storage/sql/config.go#L17
[`storage/sql/sql.go`]: https://github.com/dexidp/dex/blob/d820fd45d80cef74d4c65f5fcc5766ddb1fa514e/storage/sql/sql.go#L11


1. use `//+build functionality` and `//+build nofunctionality` tags:

```go
// +build linux,nokmem


package fs


import (
	"errors"
)


func EnableKernelMemoryAccounting(path string) error {
	return nil
}
```

https://github.com/opencontainers/runc/blob/25f3f893c86d07426df93b7aa172f33fdf093fbd/libcontainer/cgroups/fs/kmem_disabled.go#L1-L11

in the case of `dex`, that tag could be `nosqlite3`, so that by default it's turned on, but those
(like us) wanting a build of `dex` without it, could then do `go build -tags nosqlite3`.


2. use `//+build cgo` and `//+build !cgo` build tags


```go
// +build !cgo windows

package system

func GetClockTicks() int {
	// TODO figure out a better alternative for platforms where we're missing cgo
	//
	// TODO Windows. This could be implemented using Win32 QueryPerformanceFrequency().
	// https://msdn.microsoft.com/en-us/library/windows/desktop/ms644905(v=vs.85).aspx
	//
	// An example of its usage can be found here.
	// https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx


	return 100
}
```

https://github.com/opencontainers/runc/blob/2c632d1a2de0192c3f18a2542ccb6f30a8719b1f/libcontainer/system/sysconfig_notcgo.go#L1-L15

The benefits of this approach is that there's no need to know what the feature is (`sqlite3`) - you
just ask for no CGO (`CGO_ENABLED=0`), and then `go` will match the `cgo` tag:

https://github.com/golang/go/blob/d0050e2871cf3916d99b11e67a4bf34ef025ec19/src/go/build/build.go#L1739-L1742


---


For future reference, some tips on getting to these findings:

- we can find where `concourse` depends on `cgo`

        CGO_ENABLED=0 go list -f \
                "{{if .CgoFiles}}{{.ImportPath}}{{end}}" \
                $(go list -f "{{.ImportPath}}{{range .Deps}} {{.}}{{end}}" ./cmd/concourse) \
                ./cmd/concourse

        github.com/DataDog/zstd
        github.com/mattn/go-sqlite3
        github.com/opencontainers/runc/libcontainer/system
        net
        os/user
        plugin
        runtime/cgo


- the same can be done for `fly`

        go list -f \
                "{{if .CgoFiles}}{{.ImportPath}}{{end}}" \
                $(go list -f "{{.ImportPath}}{{range .Deps}} {{.}}{{end}}" ./fly) \
                ./fly

        github.com/DataDog/zstd
        net
        os/user
        runtime/cgo


- figuring out how each of those dependencies get to be used can be done through `go mod why`

        go mod why github.com/mattn/go-sqlite3

        # github.com/mattn/go-sqlite3
        # github.com/concourse/concourse/skymarshal/storage
        # github.com/concourse/dex/storage/sql
        # github.com/mattn/go-sqlite3

**Comment by DimitarKapashikov** [comment]
Hi Concourse Team, I would like to ask you whether the reported issue in CGO  https://github.com/golang/go/issues/42559, affects Concourse build ?

**Comment by vito** [comment]
@DimitarKapashikov Not anymore, since everything has been upgraded to Go 1.15.5+ as of [Nov 12](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/build-golang-builder-image/builds/19).

**Comment by vito** [comment]
Looks like the `sqlite3` cgo dependency is build flagged now! https://github.com/dexidp/dex/pull/1866

With that gone, and with our `zstd` dependency now switched to https://github.com/klauspost/compress, I think this should be good to go.

**Comment by vito** [comment]
Going to pick this up. Gonna bring the hammer down and set `CGO_ENABLED=0` in `concourse/golang-builder`, which is used by just about everything.

Will also set `GOFLAGS=-trimpath` per https://github.com/concourse/concourse/issues/4342#issuecomment-568479796 - tested it out locally and it works nicely!

**Comment by vito** [comment]
Followup: `GOFLAGS=-trimpath` breaks `packr` since it uses the call stack to figure out the asset paths. Will turn it on once we're using Go 1.16's new `go:embed` feature.

**Comment by vito** [comment]
CGO has been gotten rid of (https://github.com/concourse/ci/commit/9997e683fe914f7526e144765fd6c2dc6f56c4c3)
