### ISSUE TITLE
Teams in sidebar 'jump around'

### ISSUE THREAD

**Issue by jomsie** [concourse/concourse#4346]
## Bug Report

When having the sidebar open with many teams, sometimes the order of teams will change. 

## Steps to Reproduce

Create a bunch of teams, open the sidebar, wait.

## Expected Results

The order of teams on page load should stay in that order, probably alphabetical?

## Actual Results

Sometimes the order of the teams change.

## Version Info

* Concourse version: 5.5.x latest
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Yes

**Comment by jomsie** [comment]
@vito i remember you talking about this, couldn't find an issue about it (plz correct me if i'm wrong), so created one!

**Comment by pivotal-jamie-klassen** [comment]
i'm evolving a hypothesis that this only happens for super-admin users and started
happening after the super-admin work was deployed to prod. @pivotal-bin-ju maybe
you have some insights -- i'm also looking into this currently.
