### ISSUE TITLE
Implement step hijacking functionality for k8s

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4347]
Since we have a prototype of `task` and `get` steps working in k8s pods, we should start thinking about how we will implement hijack.

Unsorted list of things to think about:

- When a container exits non-zero, it gets deleted immediately by the pod. We can't really keep this container alive, so we will need to find a way to simulate hijacking into a Garden container. We also can't dynamically add containers to a pod after the pod is created, so we can't shoehorn an extra container into that pod (to see the state of the volumes) in the event that a user runs `fly hijack`.
- If a user runs `hijack` while the container is still running, we can attach to the container's process with `kubectl exec` but that will get booted out the moment that the container exits. We will need to think about "keepalive" behaviour

- *On a hijack request, can we re-create the container in a new pod?* We have to be careful about invisibly re-running steps, especially `get`s and `put`s because they might have non-idempotent side effects. Some tasks also might cause side effects that we don't want to invisibly cause when a user thinks they're just hijacking.

**Comment by deniseyu** [comment]
Some more thoughts after whiteboarding and rubber-ducking 😄 🦆 

It will be really tricky or impossible to implement the "hijacker container" pattern discussed above because we still want Concourse to hear a non-zero exit signal so that the job can turn red; however, Kubernetes makes it impossible to keep task containers pried open after the process exits.

We also briefly looked into container lifecycle hooks to see if post-stop hooks could be used, but these kick in after the termination signal has been sent to the container, so they cannot be interacted with at that point.

We are going to explore wrapping the task execution container in another container, similar to Tekton's `entrypoint` pattern.

**Comment by deniseyu** [comment]
More thoughts:

The "wrapper container" is also going to be not-straightforward to implement, because Concourse still needs a signal that a task failed, and Kubernetes has tight coupling between "this process has failed" and "this container should be cleaned up". Even if the outer container were to stick around while some inner process ran the actual task, it's not clear how we would tell Concourse to register the step as being failed, and turn red in the UI.

Another path we are going to try:

Head back towards a "two pods" approach, where we spin up a second pod on-demand when `hijack` is run on a failed task. The 2nd pod will override the container entrypoint to not run the task script again. On Linux containers we can use `/bin/sh sleep 1000` as the new entrypoint, and we'll eventually figure out what to do for Windows and Darwin.

Since we can take a snapshot of resources in use when a task fails and save that in the blobstore, we can create a duplicate pod with the same exact environment. We'll persist the podSpec in the db so we know the volume types and mounts and can recreate them on the new pod.

The new pod has to stay alive for long enough for a user to poke around and do the things they normally do while hijacking. We don't know what the default interval is off the top but we'll copy whatever is the current behavior!

When the next build is kicked off, we'll clean up any artifacts left in the blobstore from the previous build.

This doesn't replicate existing failed build container behaviour 100% because we create a brand new container, but it might be the closest that we can get (unless we think of something better)

**Comment by nader-ziada** [comment]
We ended up trying the wrapper (runner) approach which will keep the container `running` if the task fails so the user can hijack into it and see the exact env of the task
To make this work, ATC will get status of the task run from a config map that contains the exit code and error if any and not rely on the container status

**Comment by nader-ziada** [comment]
In the spike, the sample task does not run successfully due to an issue with running the command, however, we are able to hijack into the pod via the porter runner. Actual implementation will be completed in #4391

**Comment by ddadlani** [comment]
We will have to catch signals separately if we're using this wrapper because not all signals will be propagated to the child task process.
