### ISSUE TITLE
concourse-worker does not work in Docker

### ISSUE THREAD

**Issue by rabun788** [concourse/concourse#435]
Bigger issue referencing issue #402 
This means the entire concourse suite in unusable to users who wish to deploy this to their infrastructure with tools like Mesos and other Docker container managers.

**Comment by vito** [comment]
Could you provide more information? Folks have been doing this without issue. What exact problem are you seeing? Right now this issue is not actionable at all.

**Comment by rabun788** [comment]
Please share the docker file you have that works with a worker.

**Comment by vito** [comment]
https://github.com/gregarcara/concourse-docker

**Comment by rabun788** [comment]
That's the exact project that I tried to get it working.  The bottom of issue #402 has the exact docker file and error.

**Comment by vito** [comment]
Closing this since there are much more detailed issues already open, with many people reporting success with running 1.3 in Docker, as long as they're not using `image` (which is expected).

**Comment by DenisIzmaylov** [comment]
I've the same troubles.
