### ISSUE TITLE
How long does it take to migrate a large environment to `successful_build_outputs`?

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4353]
Do we need to perform this as a batch operation or on-the-fly migration? (#4214)

**Comment by clarafu** [comment]
With 10 mil builds and 28 mil build resource config version inputs/outputs, it took the query to migrate the data to `successful_build_outputs` 4 minutes.

This was the query we used
```
with agg as (
		(select build_id, resource_id, version_md5 from build_resource_config_version_outputs o)
		union all
		(select build_id, resource_id, version_md5 from build_resource_config_version_inputs i)
	),
 sp as (
		select build_id, resource_id, json_agg(version_md5) as v from agg group by build_id, resource_id
	)
insert into successfull_stuff (
select b.id, b.job_id, json_object_agg(sp.resource_id, sp.v) from builds b
left join sp on sp.build_id = b.id
where status = 'succeeded' group by b.id, b.job_id
);
```

**Comment by clarafu** [comment]
Seems like 4 minutes might be too long, that might be the threshold of time that it takes for bosh to get scared and terminates and runs away. 

We can try to see how complicated integrating the migration into the algorithm and decide from there what our best approach is.
