### ISSUE TITLE
Figure out our new minimum requirements with `containerd`

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4358]
* What OS distros work out of the box? Maybe we can just try the latest LTS release of various distros?
  * Debian
  * Ubuntu
  * Container-Optimized OS? Others?
* What is our minimum required kernel version?
* Can we invest in CI so we can ensure we don't break the platforms/Kernel versions we want to support?

For example, we know that on older Debian machines/images we saw an error relating to `seccomp_api_set` when trying to run the official `containerd` binary: https://github.com/concourse/concourse/issues/4130#issuecomment-519641631

I saw this on my Linux machine as well, and it was fixed by upgrading all my `apt` packages. Not sure which one - I'm guessing `libseccomp2` or something.

**Comment by muntac** [comment]
@vito and I confirmed our CI smoke tests successfully run with `containerd` on the following:

1. Ubuntu 16.04 - Kernel 4.4 
2. Ubuntu 18.04 - Kernel 5.3
3. Ubuntu 20.04 - Kernel 5.4

Pending results:
4. Debian 9 - Kernel 4.9 
5. Debian 10 - Kernel ?

**Comment by muntac** [comment]
> Can we invest in CI so we can ensure we don't break the platforms/Kernel versions we want to support?

The `bin-smoke-lts` [job](https://github.com/concourse/ci/blob/f596faad329753326cde0e46bcd08e9d78c8a728/pipelines/concourse.yml#L705) now tests against the above stated Ubuntu and Debian distros to account for this.

To Dos:
- [ ] Put updated requirements in https://concourse-ci.org/concourse-worker.html
