### ISSUE TITLE
Implement our own bespoke `containerd` Garden backend

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4361]
In the long run, we want replace Garden and just have our higher-level own worker API. In the short term, however, implementing this as a Garden backend will give us a shortcut to validating `containerd` with a fast feedback loop.

After this is done we can begin to transition away from Garden entirely. This will be recorded as a separate issue.

**Comment by vito** [comment]
I have a spike living on the [`containerd` branch](https://github.com/concourse/concourse/tree/containerd). Try it out!

```sh
./scripts/setup-oci-resource-types
docker-compose up --build -d
```

It supports running builds works and hijacking containers.

* It does *not* support our soon-to-be-legacy `rootfs/` + `metadata.json` image format.
* Instead, it supports OCI tarballs. Create a container with `oci:///path/to/oci.tar` and it'll import it into `containerd` and use it as the container's image.
  * Currently, the imported image is deleted when the container is removed.
  * We might want to change this so we don't have to keep importing the same image all the time.
  * At the same time, we don't want to leak images that are only used once. Can we tie the snapshot's lifecycle to the original Baggageclaim volume somehow? There are [ways to influence the `containerd` gc](https://github.com/containerd/containerd/blob/master/docs/garbage-collection.md#garbage-collection-labels).
* I used CNI to provide container networking in a manner similar to how Garden sets up networking: a bridge to the host and a firewall to allow outbound internet usage.
  * This could *maybe* be a performance difference; I've noted it as something to check in https://github.com/concourse/concourse/issues/4362
* Currently *no user namespacing is performed*. This is the opposite of what we want: we want all containers, even privileged ones, to be user namespaced if possible.
  * I kept it this way so that we don't conflate remapping overhead with OCI importing overhead. Once we optimize OCI image importing it might be a good time to enable user namespaces and the remapping, and optimize *that*.
  * One concern: can builds run `docker-compose` in a user namespace? We rely on this in our own pipeline, and many people in the community do, too. We should continue to support it.

**Comment by ddadlani** [comment]
We're working off of the `containerd-impl` branch, which is a clone of @vito's `containerd` but rebased from master.

Right now to get this to work we have to specify `format: oci` for the `registry-image-resource`. We will likely need to set that as the default going forward.

Some thoughts: can we get `containerd` to fetch images for us and influence their GC (as pointed out above) to ensure those images stick around? Is this even possible?

Should we get rid of packaged base resource types in the workers right now as well?

**Comment by ddadlani** [comment]
We are currently working on developing a runtime test suite to test these changes (also related to #4381). We are trying out https://github.com/stretchr/testify as an alternative to Ginkgo to make contributing tests to the future Runtime test suite easier.

Our current testing approach is to bootstrap a worker and perform API calls to test functionality. For this, we need to run the tests using `docker-compose` for Linux workers

**Comment by ddadlani** [comment]
It might be the case that initialization time is always slower but the prior `get` is faster because the registry image no longer has to unpack the image when it fetches it. We should look at overall build time as well as step initialization time.
