### ISSUE TITLE
Support for cc.xml

### ISSUE THREAD

**Issue by darrenhaken** [concourse/concourse#438]
In order to use existing Build Radiators would Concourse ever support the cc.xml endpoint like other CI tools like Jenkins and GoCd?

**Comment by vito** [comment]
Seems reasonable. We probably won't get to this ourselves, but a PR would be welcome. Is there an actual spec for the XML file format? I couldn't find one from a quick search.

**Comment by darrenhaken** [comment]
@vito the best ive been able to find is: https://github.com/robertmaldon/cc_dashboard#summary

It's what we used with http://nevergreen.io/

**Comment by darrenhaken** [comment]
@vito what is the process for PR's on Concourse? Also what language is it written in?

**Comment by vito** [comment]
@darrenhaken Go. The repo this would apply to is https://github.com/concourse/atc - it would be a new API endpoint.

**Comment by TimGrayden** [comment]
cc.xml is obsolete, and cctray was not updated for the last 5 years.

You can instead implement [CatLight open protocol](https://github.com/catlightio/catlight-protocol) and get amazing [cross-platform build monitor](https://catlight.io) that supports branches & build investigations.

**Comment by darrenhaken** [comment]
This looks more like desktop notifications than a build monitor, am I missing something?






On Sat, Mar 18, 2017 at 10:38 PM +0000, "TimGrayden" <notifications@github.com> wrote:












cc.xml is obsolete, and cctray was not updated for the last 5 years.


You can instead implement CatLight open protocol and get amazing cross-platform build monitor that supports branches & build investigations.

**Comment by TimGrayden** [comment]
You can make the window full screen and put it on a shared display for the whole team to see. But you're right - most people use it as a desktop notifier.

**Comment by darrenhaken** [comment]
@TimGrayden It's not quite the same then as [KB4013429](Nevergreen) which I work on then which is designed for large screens (and also plays sounds). If there are alternatives to cc.xml I'd definitely like to explore them though due to it clearly not being supported in a long time.

**Comment by cburgmer** [comment]
As a workaround https://github.com/BlacktoBlue/ConcourseCCtray might do it for you.

**Comment by cburgmer** [comment]
I'm starting to work on a PR (https://github.com/cburgmer/concourse/commits/master). 

One issue I don't know how to tackle yet is how to handle authentication. AFAIK Concourse speaks OAuth 2.0, but most of the monitoring tools only do Basic Auth. Help welcome.

**Comment by vito** [comment]
@cburgmer It should be possible to log in non-interactively in the same way `fly login -u foo -p bar` works, but I'm not sure if CCMenu supports it: https://github.com/concourse/concourse/blob/master/fly/commands/login.go#L120 - if it's literally basic auth or bust and there's no way to acquire a token, that may be a dead-end. Hmm. @pivotal-jwinters any thoughts? Maybe now (or soon) is a good time to think about access tokens now that we've got RBAC? Issuing read-only tokens for CI monitors would make a lot of sense.

**Comment by cburgmer** [comment]
I'm talking to the maintainer of CCMenu about OAuth. He indicated interest in supporting OAuth (see some of the issues there). My biggest questions so far are around
1) discoverability of an OAuth authenticated endpoint,
2) token renewal.

@pivotal-jwinters Deploying yet another service to translate to cc.xml (being more or less a standard) is a bit of a show stopper. Also, I understand even such a service would need a human being re-authenticating once a day via a browser?

**Comment by pivotal-jwinters** [comment]
@cburgmer It wouldn't require user intervention. You could automate the workflow if you fetched a token using the `resource owner` (local users in concourse) grant type or `client credentials` (which concourse doesn't currently support but probably should) grant type. Neither would require a browser.

And yeah i understand that deploying another service is a huge pain. I'll probably continue to argue against adding one off service integrations though. It just adds a larger maintenance burden. At least until enough people ask for it that it makes it worth it.

**Comment by cburgmer** [comment]
Concourse 5 ships with cc.xml support now. If you have a build monitor that cannot talk to Concourse' own authentication, you might try using this solution for now: https://gist.github.com/cburgmer/e22a3c078502606a8cb7e72fbf1d1713

**Comment by vito** [comment]
@cburgmer Cool!

Looks like I forgot to close this and put the PR in the 5.0 milestone - doing that now.

**Comment by jzimermann** [comment]
> @cburgmer Cool!
> 
> Looks like I forgot to close this and put the PR in the 5.0 milestone - doing that now.

@vito I was checking the documentation for the [release 5.0.0](https://concourse-ci.org/download.html#v500) and didn't find any mention to this issue or the new endpoint created. Is it possible to update it with the proper information or point me to the correct documentation? 

Thanks!

**Comment by vito** [comment]
I finally got around to adding a new section to the docs which covers this: https://github.com/concourse/docs/commit/d28eb3f4dbe10f8769389b27675bd707592867db - thanks for waiting!
