### ISSUE TITLE
checkout resource can not resolve github.com

### ISSUE THREAD

**Issue by qibobo** [concourse/concourse#4382]
**concourse_version**: 5.4.1
Check resource shows the error below:
```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/cloudfoundry/cf-deployment.git/': Could not resolve host: github.com
```
After I hijack the check container and found there is only one line in /etc/resolv.conf
`options edns0`
How web and worker start:
```
/usr/local/concourse/bin/concourse web  \
--main-team-local-user=admin \
--add-local-user=admin:password  \
--session-signing-key /etc/concourse/session_signing_key  \
--tsa-host-key /etc/concourse/host_key  \
--tsa-authorized-keys /etc/concourse/authorized_worker_keys  \
--external-url http://9.111.210.75:8080  \
--postgres-host=localhost \
--postgres-port=5432 \
--postgres-user=concourse \
--postgres-password=123 \
--postgres-database=concourse
```

```
/usr/local/concourse/bin/concourse worker \
--work-dir /var/lib/concourse \
--tsa-host 9.111.210.75:2222 \
--tsa-public-key /etc/concourse/host_key.pub \
--tsa-worker-private-key /etc/concourse/worker_key
```

**Comment by kcmannem** [comment]
What OS are you on? I presume if you hijack in and add something like 8.8.8.8, checks will start working again? I've seen a couple people post about dns issues.

**Comment by qibobo** [comment]
@kcmannem 
Thank you. I add the "8.8.8.8" but it did not work on last Friday, but when I check it just now, it works. Do not know why.
Anyway, I will close this issue.

**Comment by qibobo** [comment]
@kcmannem 
I just restart the concourse server and the check resource can not work again the error is :
Backend error: Exit status: 500, message: {"Type":"","Message":"exit status 2","Handle":"","ProcessID":"","Binary":""}

I will wait some hours to see it will recover again.

**Comment by pivotal-bin-ju** [comment]
Hi @qibobo,
Is the GOOGLE DNS 8.8.8.8 blocked at your place sometime for some reason?

**Comment by michaelklishin** [comment]
This sounds like an environment-specific problem and not an actual issue in Concourse.

**Comment by kallisti5** [comment]
This sounds like the network issues everyone keeps running into over and over with worker containers / systems.

#4424, #4085, #1667, #4131
