### ISSUE TITLE
Strengthen secret redaction to handle split secrets

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4389]
@evanchaoli got the ball rolling in https://github.com/concourse/concourse/pull/4311 by implementing a first pass of automatic credential redacting, however along the way we found one tricky problem.

There's a chance that Concourse receives "pieces" of a credential in separate `Write()` calls, at which point no redacting can occur as the full credential is never seen at once. This could happen if a sufficiently large credential is printed - say, a multiline SSH key. It might also just happen randomly; process output is received in arbitrary chunks, so it could be a timing problem too.

Relevant discussion: https://github.com/concourse/concourse/pull/4311#discussion_r319647503

**Comment by evanchaoli** [comment]
I'll working on this.

**Comment by evanchaoli** [comment]
@vito Can you please review this?
