### ISSUE TITLE
keyboard shortcuts in web UI

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#439]
I would like to see concourse web UI accept keyboard navigation. I dislike using the mouse, and this is doubly-true for the pipeline view, where a small mouse movement while clicking on a job means sometimes my click isn't registered as a click, but as a drag, and hence I do not navigate to the page I expect, but instead remain on the pipeline view, moving the image very slightly.

Other pages could benefit from keyboard shortcuts too, like the builds page (e.g. h/l for next/previous, j/k for scrolling). I'd love some way to 'jump to next failure' but that is probably too hard to solve, and is likely out of scope for keyboard shortcut MVP.

If we implement keyboard shortcuts, I'd also like to see `?` be a global shortcut (i.e. on all pages) for help.

**Comment by xoebus** [comment]
Keyboard shortcuts are infuriating unless the UI reacts "instantly" (< 100ms). I think if this were to be done then a lot of the work would be making the pages be as responsive as possible.

**Comment by vito** [comment]
This should be easier to approach once our full Elm single-page-app rework finishes (soon).

**Comment by wendorf** [comment]
I would also love keyboard shortcuts, but also for triggering events, such as `a` for aborting a build and `t` for triggering a build.

**Comment by wolfoo2931** [comment]
@wendorf +1 for the "a" and "t" shortcut

**Comment by jama-pivotal** [comment]
Currently we have:

* `h` and `l` for moving between builids
* `j` and `k` for scrolling up and down
* `T` to trigger a new build
* `A`  to abort a build
* `?` to bring up a help menu to show the shortcuts

**Comment by jgrau** [comment]
`q` to take you back to `/dashboard`? :)

**Comment by jama-pivotal** [comment]
honestly we should just implement vim key bindings.....but not today

**Comment by Lindsayauchin** [comment]
![build_shortcuts_modal](https://user-images.githubusercontent.com/27746614/31186221-0a81804c-a8fc-11e7-8c06-1baeadf01d2e.png)
