### ISSUE TITLE
Update documentation in https://concourse-ci.org/

### ISSUE THREAD

**Issue by koullislp** [concourse/concourse#4408]
At the time of writing this I am using Concourse 5.5.0 and following this documentation was the worst introduction to Concourse I could have as basically everything that I follow from here doesn't work. The compiler complains about issues and I have to find other examples online to figure out how to get things done.
https://concourse-ci.org/

Please take some time to update the documentation as there are basic things like inputs in the Tasks that simply don't work according to the documentation. 
https://concourse-ci.org/tasks.html

Also please introduce a clear definition of Resource Types, Resource, Plan, Job, Task and some clear examples how they are all put together in there.

**Comment by clarafu** [comment]
@koullislp It's unfortunate that you ran into issues with the Concourse documentation, would you be able give us the exact errors and problems you faced with it so we can fix them? Also, what do you mean by your compiler complains about issues? Are you trying to compile Concourse yourself? (Why?)
