### ISSUE TITLE
Ability to pause/drain workers

### ISSUE THREAD

**Issue by evanshort73** [concourse/concourse#442]
Some people want to bosh restart their workers without causing builds to error. They sometimes do this by manually pausing entire pipelines before restarting workers. They would like to mark a worker as not usable and wait for builds on it to finish before restarting it.

**Comment by colstrom** [comment]
This feature is useful to me. I'd like to be able to flag a worker as "not accepting new work at the moment", to facilitate non-disruptive maintenance of Concourse Workers.

**Comment by vito** [comment]
Related to https://github.com/concourse/concourse/issues/629 but I'll leave this open til we figure out a plan for this specific aspect.

@colstrom Trying to reason about what this'll look like. The plan in the above issue is to add a `landing` state to the worker, where the ATC will stop scheduling new work, wait for all in-flight work to finish, automatically unregister the worker, and then the worker would see this and exit. This makes the most sense to me from an automation perspective; the ATC is really the only component that can know if all work on a worker is completed. But I wanted to clarify that the only transition *out* of this state is the worker itself exiting. Sound good?

**Comment by vito** [comment]
Also thinking about how that process would be kicked off. Signals are tempting but not very portable. Maybe just `concourse land-worker` which somehow communicates to the running worker process?

**Comment by vito** [comment]
Here's the plan: https://github.com/concourse/concourse/issues/629#issuecomment-252117991
