### ISSUE TITLE
UX: Is it easy to see resource version metadata in get step?

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#4421]
This is really minimal and it might just be me. Wanted to know if people find it easy to locate resource version metadata when many of the get steps are expanded. The table size is different for each get step and it depends on what resource your expanding. Will adding a slight background color serve as visual guide when scanning through get steps?

![Screen Shot 2019-09-11 at 8 49 25 PM](https://user-images.githubusercontent.com/9054726/64745572-63904580-d4d6-11e9-84f3-53d18a5f4c37.png)
![Screen Shot 2019-09-11 at 8 55 07 PM](https://user-images.githubusercontent.com/9054726/64745591-77d44280-d4d6-11e9-8366-fc91bc8c71da.png)

Do we think the background color in these examples help or just make things noisy in Concourse. Theres already so many rectangles to keep track of.

cc @Lindsayauchin @concourse/ux

**Comment by evanchaoli** [comment]
I like this idea.

**Comment by kcmannem** [comment]
latest iteration:

![Screen Shot 2019-09-13 at 3 25 18 PM](https://user-images.githubusercontent.com/9054726/64987233-c9921980-d896-11e9-8f22-e256a006ec0c.png)

Planning on showing the metadata table on the left hand side rather than the right. It's hard to glance over at the right every time you expand the get step. Especially since when you expand the get step you don't care about the logs, you care about the metadata.

We're currently working on an `OnHover` state so we can make large blocks of text more readable and isolated from surroundings.

**Comment by kcmannem** [comment]
![Screen Shot 2019-09-20 at 3 49 53 PM](https://user-images.githubusercontent.com/9054726/65354786-62d66e00-dbbe-11e9-97af-0d043f8d4ecd.png)
did it

**Comment by vito** [comment]
@kcmannem I think putting the metadata there makes a lot of sense in general, especially if we can  enrich the metadata and make it more semantic so it looks nicer in the future.

The only problem I can think of is that while the `get` step is fetching, there won't be metadata to show yet - so a user will see logs streamed and then the metadata will render above and push those logs down, causing things to jump around. In practice the step will probably auto-collapse before they see this happen, but I don't know if we should rely on that as a user may have toggled it twice, and I think in that case it'll stay open (user's toggle state overrides auto-toggle state).

**Comment by Lindsayauchin** [comment]
@vito @kcmannem 
Jumping will happen no matter what while the data is fetching but, we could improve the transition and to reduce the jumping while the user is waiting for the data to load by adding an 'empty' table of one row and one column as a placeholder for the meta data. 

A"fetching meta data…" message would remain until the meta data is fetched and replaces it  creating the new table of meta data expanding from that placeholder table. 

Thoughts?

![Screen Shot 2019-09-24 at 5 08 09 PM](https://user-images.githubusercontent.com/27746614/65550968-c9c19300-deee-11e9-9fd3-7456495f1b67.png)
