### ISSUE TITLE
Containers cannot reach external networks/hosts

### ISSUE THREAD

**Issue by TheRevenantStar** [concourse/concourse#4424]
## Bug Report
Worker containers are unable to reach external networks

## Steps to Reproduce

https://gist.github.com/TheRevenantStar/024d8a68e4cb47c476109e4aacb0acad

## Expected Results

The pipeline to run scuessfully

## Actual Results

Repository Check errors with 
```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://gitlab.com/atentousa/aegis.git/': Failed to connect to gitlab.com port 443: Connection timed out
```

Intercepting the check shows I can use cURL to get the webpage at 192.168.1.100, but not for external addresses. This appears to be specific to containers spawned by concourse, as running a docker container using the docker CLI seems to function just fine.

## Additional Context

Running Ubuntu server 18.04 and consul on port 53 (set to use 8.8.8.8 as a recursor to serve DNS correctly)

## Version Info

* Concourse version: 5.5.1
* Deployment type (BOSH/Docker/binary): binary
* Did this used to work? Yes, It works on a near identical configuration on another machine.

**Comment by kcmannem** [comment]
did this break when you went from 5.4 -> 5.5.x?

**Comment by TheRevenantStar** [comment]
I believe it did, actually.

**Comment by TheRevenantStar** [comment]
Just nuked everything docker (& friends) to try a fresh installation on 5.5.1, still no luck. The issue seems to persist.

**Comment by kcmannem** [comment]
Were you ever on 5.3? Was it working then. Just trying to narrow down what change might have caused this.

**Comment by TheRevenantStar** [comment]
No on this node, this was a fresh install.

Is there something I can run to help narrow down the issue?
When I nuked the concourse data on this node, I deleted the atc database and purged docker & containerD.

**Comment by kcmannem** [comment]
is it possible for you to deploy 5.3? We noticed other people mentioning a dns issue on versions > v5.4

**Comment by TheRevenantStar** [comment]
I'll try 5.2.3, it seems to be the only available version right before 5.4.1

**Comment by TheRevenantStar** [comment]
Same error, but it pops up instantly instead of giving the backend 500 error for ~1 hour leading up to it...
```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://gitlab.com/atentousa/aegis.git/': Could not resolve host: gitlab.com
```

**Comment by TheRevenantStar** [comment]
I scoured previous issues and saw this one re-opened at one point #4382, maybe it's related?

**Comment by 242617** [comment]
I've the same issue. Worker can't check resource:
`Could not resolve host: github.com`.

And `nslookup github.com` on the worker host shows no error. Also as `git clone https://github.com/...` clones repo without errors.

How can I check connection inside worker?

P.S. Concourse 5.6.0. Ubuntu 18.

**Comment by TheRevenantStar** [comment]
It looks like this issue has resolved itself with newer versions and this issue has gone stale. **Closing**

**Comment by 95rade** [comment]
The issue persists in 5.7.2, Ubuntu 16.04, single worker. Please re-open this issue.

**Comment by wellyal** [comment]
I have the exact same problem even when running the [tutorial](https://concoursetutorial.com/basics/pipeline-resources/), is that any reason why is this closed? 


```
run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/starkandwayne/concourse-tutorial.git/': Could not resolve host: github.com
```

**Comment by vinayakasg18** [comment]
I'm also facing the similar issue following the tutorial (https://concoursetutorial.com/basics/pipeline-resources/). 

Cloning into '/tmp/git-resource-repo-cache'...

fatal: unable to access 'https://github.com/{repo}.git/': Could not resolve host: github.com

**Comment by taylorsilva** [comment]
@vinayakasg18  For errors like `could not resolve host` it's likely a DNS issue. See the docs for help https://concourse-ci.org/concourse-worker.html#troubleshooting-and-fixing-dns-resolution

**Comment by vinayakasg18** [comment]
> @vinayakasg18 For errors like `could not resolve host` it's likely a DNS issue. See the docs for help https://concourse-ci.org/concourse-worker.html#troubleshooting-and-fixing-dns-resolution

Thank you.
