### ISSUE TITLE
'in' Resources Should Receive More Version Information

### ISSUE THREAD

**Issue by coofercat** [concourse/concourse#4426]
## What challenge are you facing?

Concourse Resources are fantastically simple, but are arguably limited in scope. In particular the 'in' script is supplied with the version to work on, but is not supplied the current/previous version or any other meta. This limits what it is able to do.

Whilst fetching a Git repo at a particular ref doesn't require a 'previous version' to be specified, other trigger sources can benefit from a 'to' and 'from' type specification to work out changes or 'diffs' or whatever.

In my particular case, I'm triggering on AWS SSM parameters being changed. The parameters have a 'last modified' date, so the trigger looks for that to be larger than previously. This all works fine, but the 'in' resource is not able to report the parameters which were changed since the last build (to STDERR, so they appear in the build output).

## What would make this better?

When calling 'in' resources, Concourse should supply the previous version as well as the new version (a little like the 'check' resource receives the previous version). For example, the JSON supplied to 'in' may currently be something like this:
```
{
"source"=> {
  "user": "myuser",
  "password": "mypass"
},
"version"=>{ "id"=>"3" }
}
```
Instead, Concourse should additionally supply the previous version:
```
{
"source"=> {
  "user": "myuser",
  "password": "mypass"
},
"version"=>{ "id"=>"3" },
"previous_version"=>{ "id"=>"2"}
}
```
This is hopefully a simple change to make, hopefully doesn't add too much complexity to the operation of Resources and is also backwards-compatible for all but the most bizarre cases.

**Comment by simonjohansson** [comment]
This would be amazing.

**Comment by coofercat** [comment]
Hmm... good question.

`check` resources return all previous versions, and Concourse (should) run on each of them. So in your scenario, versions 6,7,8 & 9 should have had runs against them.

However, if a situation were to occur where the most recent version has had a run, but some previous versions have not, then yes, I would agree that the versions that have had actual jobs run against them should be returned (so "5" in your example).

Concourse knows the last version it ran against, not necessarily every version it didn't run against, so I think this change only requires Concourse to supply what it already knows to the `in` script.
