### ISSUE TITLE
Pass `FirstOccurrence` to `bin/in`

### ISSUE THREAD

**Issue by dgodd** [concourse/concourse#443]
I would like to know inside my tasks which of my dependencies have changed since the previous build.

It seems to me that a good way to do this, would be for concourse to pass `FirstOccurrence` to `bin/in` (part of `Version`) so that my resource could make that information be part of what go passed to the task as input.

I have a resource / task combination where I need to know all of the current versions of my dependencies, but would also benefit from knowing which ones haven't changed (for alerting the team purposes)

**Comment by vito** [comment]
I don't like that this introduces an implicit parameter that may cause a resource to change its behavior. Sounds like there should be some other way of knowing this, not part of the resource interface.
