### ISSUE TITLE
Bad bad queries

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#4436]
Queries to possibly optimize. These came out from the following flamegraph, where @kcmannem and I dug into possible queries that we can optimize in order to make the SetResourceConfig method faster.

<img width="2020" alt="Screen Shot 2019-09-16 at 2 50 03 PM" src="https://user-images.githubusercontent.com/19290703/64984709-618d0480-d891-11e9-9fed-12da31b91433.png">

https://github.com/concourse/concourse/blob/6c45ae069b8293de5932b1ae81e9e5b5bb52fd3e/atc/db/resource_cache.go#L132-L142

https://github.com/concourse/concourse/blob/8de8e903cc8e71f4dc64511def8d7c6b5fec70f1/atc/db/resource.go#L236-L244

**Comment by evanchaoli** [comment]
@clarafu Where would this issue impact 5.5? We are planning to upgrade to 5.5.1, if this is a serious issue, then we will have to reconsider.

**Comment by clarafu** [comment]
@evanchaoli These are just some small optimizations that we can get, it shouldn't be a big impact. Also these queries were introduced for a really long time so it won't make a difference upgrading to 5.5.1.

**Comment by clarafu** [comment]
Sorry i made the name sound a lot scarier than it is! haha
