### ISSUE TITLE
set-pipeline causes login prompt, but doesn't accept pasted tokens

### ISSUE THREAD

**Issue by benmoss** [concourse/concourse#4454]
# Bug Report

When you login regularly with `fly login`, you get a prompt to paste your bearer token if the browser isn't able to connect to fly's ephemeral port to complete the login flow. It shows:

```
logging in to team 'main'

navigate to the following URL in your browser:

  http://10.74.47.138:8080/login?fly_port=44857

or enter token manually:
```

However, if you are logged out and try to do a `fly set-pipeline` (or I'm sure a bunch of other commands) you get:

```
could not find a valid token.
logging in to team 'main'

navigate to the following URL in your browser:

  http://10.74.47.138:8080/login?fly_port=42577
```

with no prompt.

## Expected Results

You should be able to paste a token in all login modes.

## Actual Results

You can only login with token if you run `fly login`.

## Version Info

* Concourse version: 5.4.1

**Comment by xtremerui** [comment]
Hi, this behaviour is intended. Please refer to https://github.com/concourse/concourse/releases?after=v5.3.0-rc.8#v500-note-18 and https://github.com/concourse/concourse/issues/2414

thx!

**Comment by benmoss** [comment]
But now you have this broken flow where the login screen is literally lying to you, telling you to copy the token and paste it into your terminal, when that is not possible.

![Screenshot from 2019-09-18 11-30-37](https://user-images.githubusercontent.com/239754/65162801-d1250000-da07-11e9-8058-cab027e42749.png)

**Comment by lrstanley** [comment]
Duplicate of what I posted here: https://github.com/concourse/concourse/issues/4298

What you mention @xtremerui makes no sense. I would consider this a bug, because it literally breaks a feature that is also implemented (being able to use fly from a remote machine or similar).

**Comment by benmoss** [comment]
Yeah it's not enough of a problem for me that I wanted to fight that fight :smile:. It sounded like it was an intentional, if bad, choice.
