### ISSUE TITLE
Step runtime tooltip is hidden by build header bar

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4457]
## Bug Report

See the screen shot:
<img width="621" alt="tooltip-is-hiden" src="https://user-images.githubusercontent.com/18585861/65119910-6b447280-da1f-11e9-987f-e44e6fbb66cb.png">

The first step's tooltip is hidden by the build header bar. We have noticed this issue since Concourse 5.2 (5.2 is our earliest version).

## Steps to Reproduce

Put the mouse cursor on the first step's right icon, and a tooltip should pop up and it would be hidden by header bar.

## Expected Results

Tooltip should be not hidden.

## Actual Results

Tooltip is hidden.

## Additional Context

This issue is across all Concourse versions since at least 5.2.

## Version Info

* Concourse version: 5.2-5.5
* Deployment type (BOSH/Docker/binary): K8S
* Infrastructure/IaaS: K8S
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by pivotal-jamie-klassen** [comment]
related #3921. In general, I feel that the approach taken by the [sidebar](https://github.com/concourse/concourse/blob/master/web/elm/src/SideBar/Styles.elm#L254-L262) (the key part being `position: fixed`) probably scales to the greatest number of tooltip scenarios. While #4206 was a promising hack, it had some [unintended consequences](https://github.com/concourse/concourse/issues/4210) so the fix here will probably mean rolling up one's sleeves and wading into [some](https://github.com/concourse/concourse/blob/master/web/elm/src/SideBar/SideBar.elm#L67-L68) [complicated](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Effects.elm#L434-L436) [event](https://github.com/concourse/concourse/blob/master/web/elm/src/SideBar/SideBar.elm#L107-L115) [handling](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Effects.elm#L438-L440) [logic](https://github.com/concourse/concourse/blob/master/web/elm/src/SideBar/SideBar.elm#L120-L133) on the build page.
