### ISSUE TITLE
How a worker's volume count can get so high?

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4465]
## Bug Report

We are running load test on a newly deployed 5.5 clusters, and we have noticed several times that some workers got to staled. From the graphana dashboard, I noticed that some workers' volume count got crazy higher than other workers:

![worker-volumes-too-high](https://user-images.githubusercontent.com/18585861/65252149-05dda800-db2b-11e9-8782-61e402e276bb.png)

## Steps to Reproduce

Not sure

## Expected Results

All workers volume count should be at same level.

## Actual Results

One worker's volumes got to more than 6000, while other workers were less than 1000.

## Version Info

* Concourse version: 5.5.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: ATCs on K8S, Workers on vSphere VMs
* Browser (if applicable): NA
* Did this used to work? NA

**Comment by kcmannem** [comment]
We seen cases where this can happpen because GC stops on the workers. The stalls have been noticed to happen when `destroy` calls to either garden or baggageclaim hang. So I'm curious if that workers container count also shows a major increase.

**Comment by cirocosta** [comment]
@kcmannem related to https://github.com/concourse/concourse/issues/4467, I guess 🤔

**Comment by kcmannem** [comment]
@cirocosta yup I'd assume its the same bug for now at least. If we see this happening after a fix for #4467 is applied, we can consider this separately.

**Comment by evanchaoli** [comment]
@kcmannem Looks like worker container count wasn't that crazy:

![worker-volumes-too-high2](https://user-images.githubusercontent.com/18585861/65288755-71029b00-db7a-11e9-92ba-df206a2ce465.png)

At the time when the single line breaking 6000 in worker volumes count, worker count was below 200.

**Comment by evanchaoli** [comment]
Based on our observation, 5.7.0 seems to have a big optimization.
