### ISSUE TITLE
Cannot access host worker machine from container

### ISSUE THREAD

**Issue by kobylyanskiy** [concourse/concourse#4468]
## Bug Report

After upgrading to v5.4.1 I'm unable to rsync built images anymore from container to the worker.
Early I was successfully using v4.2.2, and the problem didn't occur.  

## Steps to Reproduce

Seems like I can ping container from worker, but I cannot ping worker from container. I already set
the option `allow-host-access = true` in my config and checked that IP address of worker is present in `/etc/resolv.conf`.  I even set the default policies in firewall for each of the built-in chains to `ACCEPT`, but without any luck. 

## Expected Results

Reach worker machine from container.

## Actual Results

Cannot reach worker machine from container.

## Additional Context

I'm using Concourse to build images for embedded devices. I rsync these images to my worker machine where I then use them to reflash devices, so I don't need any external place to store them. 

## Version Info

* Concourse version: 5.4.1
* Deployment type (BOSH/Docker/binary): binary
* Did this used to work? yes

**Comment by xtremerui** [comment]
Hi, there is a [breaking change about Garden config](https://github.com/concourse/concourse/releases?after=v5.3.0-rc.8#v500-note-3) on 5.0.0. Have you updated your deployment accordingly?

**Comment by kobylyanskiy** [comment]
@xtremerui hi. Yes, I have read that document and updated to config file for garden.

**Comment by xtremerui** [comment]
Without knowing the details of the deployment, the next thing I could suggest is pull out that `allow-host-access` flag to an ENV directly, just to rule out the possibily of mal-use of garden config file.
