### ISSUE TITLE
Option to tail the logs

### ISSUE THREAD

**Issue by etiennetremel** [concourse/concourse#447]
When your build dump a huge amount of logs, from the Concourse CI interface, it takes a while to see the bottom of the logs, the interface try to automatically scroll down while reading the logs. 

Another way would be to setup an option to tail the log, and if needed click a button somewhere to see the full logs.

Or maybe you have other suggestion?

**Comment by vito** [comment]
I'd rather we just make the existing build UI faster. We've been doing a lot of work in that area and it should be much better now. I don't want to give up and add work-arounds as it just makes the UI more confusing.

Thanks for the idea though!
