### ISSUE TITLE
fly shows the wrong duration for cancelled builds

### ISSUE THREAD

**Issue by jomsie** [concourse/concourse#4472]
Looks like its computing time since the epoch? Probably fly is using some kind of integer type to represent those timestamps, so if the start time is not set, it defaults to "0 milliseconds since the epoch".

![Screen Shot 2019-09-20 at 11 07 07 AM](https://user-images.githubusercontent.com/2362482/65337868-00b64280-db97-11e9-96c3-3790e51683fd.png)

I think it would make more sense to see `n/a` in the duration field, or even `cancelled` in the duration field.

**Comment by pivotal-jamie-klassen** [comment]
release note in #4565
