### ISSUE TITLE
Refresh Frequency of Team/Pipeline View

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#4482]
## What challenge are you facing?
We are seeing that some users who are a member of a large number of teams or have a large number of pipelines, resulting in a lot of data returned in calls to jobs/teams/pipelines/resources, are experiencing poor performance on their browser.

And, for example, if a call to /jobs takes 10-12 seconds to run, calling this API every 1 second or so makes no sense.  This not only leads to a lot of unnecessary data being sent to the user, but also quite a slow experience for the user and we eventually have multiple calls to /jobs stacked up and being returned at the same time.

## What would make this better?

Could the system include some mechanism where the user or administrator could choose whether and with what frequency data was refreshed?

**Comment by maxknee** [comment]
Possibly throttle or wait for the refresh calls to finish before firing off new ones

**Comment by pivotal-jamie-klassen** [comment]
@maxknee's 'wait' suggestion is nicely summarized in #4372, which is prioritized for v6.0.0.

**Comment by xtremerui** [comment]
similar to https://github.com/concourse/concourse/issues/2776

**Comment by pivotal-jamie-klassen** [comment]
as for a configurable refresh interval, I'm a bit hesitant for fear of introducing a [knob](https://github.com/concourse/concourse/wiki/Anti-Patterns#knobs) - chances are you'd only ever turn down the refresh rate as you cluster got busier and then you'd likely forget to turn it back up if/when your API became more responsive. Of course the Right Way™ to solve this problem is by having a lower-bandwidth way to communicate changes to the dashboard - something like the build events endpoint where you open a websocket and only receive messages when there is something to report, like a build starting/finishing or a resource check changing status.

**Comment by xtremerui** [comment]
per @pivotal-jamie-klassen comment, there is a note in API track [roadmap](https://project.concourse-ci.org/) named "Event streaming (optimize dashboard)" that is in our priority list.

**Comment by keithkroeger** [comment]
Perhaps, rather than introducing a 'knob,' we could at least keep the refreshes from overlapping?
the process could refresh 5s after the previous response _is recieved_ rather than every 5s.

**Comment by pivotal-jamie-klassen** [comment]
@keithkroeger I agree! do you feel that this 'non-overlapping' requirement is adequately summarized in #4372? Debating whether to keep this issue open or close in favour of that one. The one. I kinda like that this one focuses on an end-user experience whereas the other is more focused on whitebox observations of the system.

**Comment by keithkroeger** [comment]
Hi @pivotal-jamie-klassen:

I would think that one of these should live.  IMHO, which one is simply a process-management discussion.  Closing the old one makes the backlog for this work seem 'fresher' but really, that was the first example of the problem.

So, I'd think updating the https://github.com/concourse/concourse/issues/4372 to provide how that impacts the user would probably help.

Thank you for the vote.
