### ISSUE TITLE
Ordering of teams in the left hand menu

### ISSUE THREAD

**Issue by superbeeny** [concourse/concourse#4484]
## What challenge are you facing?

Our Concourse deployment has a lot of teams, with over a hundred in the left hand list it can be hard or sometimes impossible to find the one you want.

## What would make this better?

Ordering of teams, even just alphabetical would be awesome

## Are you interested in implementing this yourself?

Maybe :)

**Comment by pivotal-jamie-klassen** [comment]
Applying an ordering like https://github.com/concourse/concourse/blob/master/web/elm/src/Dashboard/Group.elm#L53-L56
(which is basically sort by role and then alphabetically on team name to break ties) might be a fairly uncontroversial first pass.
