### ISSUE TITLE
LDAP connector only returns "first" Active Directory group

### ISSUE THREAD

**Issue by shawn-roering** [concourse/concourse#4491]
## Bug Report

Only "first" Active Directory group is considered for role authorization.

## Steps to Reproduce

I created a concourse team, and specified an Active Directory security group as owner role.  

Here is the team authorization.
`
$ fly get-team -n myteam -t myconcourse
myteam/member  none          ldap:cn=build-developer,ou=global,ou=security groups,ou=city,dc=mycompany,dc=local
myteam/owner   local:admin  ldap:cn=build-administrators,ou=global,ou=security groups,ou=city,dc=mycompany,dc=local
`
Here are the relative LDAP_GROUP_SEARCH variables.
`
      CONCOURSE_LDAP_GROUP_SEARCH_BASE_DN: DC=mycompany,DC=local
      CONCOURSE_LDAP_GROUP_SEARCH_FILTER: (&(objectCategory=Person)(objectClass=user))
      CONCOURSE_LDAP_GROUP_SEARCH_USER_ATTR: sAMAccountName
      CONCOURSE_LDAP_GROUP_SEARCH_GROUP_ATTR: sAMAccountName
      CONCOURSE_LDAP_GROUP_SEARCH_NAME_ATTR: memberOf
`
This is a sample of the group membership for my account as returned by ldapsearch utility.
`
ldapsearch -H "ldap://10.1.2.3" -D "CN=svc_concourse,OU=ServiceAccounts,OU=city,DC=mycompany,DC=local" -W -b "dc=mycompany,dc=local" 'sAMAccountName=flast' | grep memberOf

memberOf: CN=DevTeam,OU=Global,OU=Security Groups,OU=City,DC=mycompany,DC=local
memberOf: CN=Build-Administrators,OU=Global,OU=Security Groups,OU=City,DC=mycompany,DC=local
memberOf: CN=Engineering,OU=city,DC=mycompany,DC=local
memberOf: CN=Passwords-Dev,OU=Global,OU=Security Groups,OU=City,DC=mycompany,DC=local
` 

## Expected Results

I expected to be authorized according to the group assignment. Concourse should consider all groups, not just the first.

## Actual Results

Authentication works, but Authorization fails. This is the relative output from the concourse server when I try to login. Notice that the only group shown in the output is the "first group" returned by the ldapsearch.

`
{"timestamp":"2019-09-24T13:34:09.092675954Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"performing ldap search DC=mycompany,DC=local sub (\u0026(objectCategory=Person)(sAMAccountName=flast))","session":"7"}}
{"timestamp":"2019-09-24T13:34:09.100459453Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"username \"flast\" mapped to entry CN=First Last,CN=Users,DC=mycompany,DC=local","session":"7"}}
{"timestamp":"2019-09-24T13:34:09.165725054Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"performing ldap search DC=mycompany,DC=local sub (\u0026(\u0026(objectCategory=Person)(objectClass=user))(sAMAccountName=flast))","session":"7"}}
{"timestamp":"2019-09-24T13:34:09.244478803Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"ldap\", username=\"flast\", email=\"First.Last@mycompany.com\", groups=[\"CN=DevTeam,OU=Global,OU=Security Groups,OU=City,DC=mycompany,DC=local\"]","session":"7"}}
{"timestamp":"2019-09-24T13:34:09.260121312Z","level":"error","source":"atc","message":"atc.sky.callback.failed-to-issue-concourse-token","data":{"error":"user doesn't belong to any team","session":"6.16"}}
`

## Additional Context

Group based authorization worked fine until IT added me to a new security group, which seems to have changed the order of the results on the group search.  Looks like the ldap connector is only returning the "first" group.

## Version Info

* Concourse version: 5.5.1
* Deployment type (BOSH/Docker/binary): Docker version 18.09.6, build 481bc77156
* Infrastructure/IaaS: Running latest docker image on a VM.
* Browser (if applicable): N/A
* Did this used to work? Yes

**Comment by xtremerui** [comment]
First thought of this is that log
```
groups=[\"CN=DevTeam,OU=Global,OU=Security Groups,OU=City,DC=mycompany,DC=local\"]"
```
indicates the group search only returns one group entry. Since this log is a direct output of Dex ldap search result (`atc.dex.event`) I would try look into detail of the [ldap config](https://github.com/concourse/dex/blob/master/connector/ldap/ldap.go#L116-L137) and try different combination of the concourse ldap group seach flags (which is one to one map to dex ldap config) to see if it makes any diferent result.
