### ISSUE TITLE
Eternal loading indicator for jobs with no builds

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4493]
![2019-09-24@14:09:46](https://user-images.githubusercontent.com/1880/65538424-46e00e80-ded5-11e9-958d-44b1ccb3faea.png)

**Comment by pivotal-jamie-klassen** [comment]
Any strong takes on whether to just show an empty page or have some placeholder text about no builds? @Lindsayauchin @matthewpereira

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen would be a good idea to surface that information to the user to improve system feedback. My suggested copy would be **"no builds for job “test” "**

<img width="587" alt="Screen Shot 2019-09-24 at 4 38 46 PM" src="https://user-images.githubusercontent.com/27746614/65548685-eb6c4b80-dee9-11e9-97bb-3bc5e2a59c46.png">
