### ISSUE TITLE
fly: `fly workers` integration test time flake

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4497]
It is possible for enough time to pass between [this initialization](https://github.com/concourse/concourse/blob/master/fly/integration/workers_test.go#L141-L147) and [this assertion](https://github.com/concourse/concourse/blob/master/fly/integration/workers_test.go#L167-L173) that the assertion fails. [Proof](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/1098#L5d8a5acd:69:92)

The Right Way™ to solve this problem is to refactor fly to use a fake clock that always returns the same time. However, the fly integration tests use [gexec.Build](https://github.com/concourse/concourse/blob/master/fly/integration/suite_test.go#L32) to compile fly and exercise it by shelling out to the compiled binary.

Instead of an 'integration' test like the above, we should be verifying the 'age' column works appropriately by externalizing our 'clock' dependency [here](https://github.com/concourse/concourse/blob/master/fly/commands/workers.go#L205), and then injecting a fake for tests. I'm thinking we should externalize the [stdout writer](https://github.com/concourse/concourse/blob/master/fly/commands/workers.go#L69) too.

**Comment by pivotal-jamie-klassen** [comment]
@evanchaoli you might be interested in this, having touched this code recently 🙂

**Comment by evanchaoli** [comment]
@pivotal-jamie-klassen I can image that. That should be because of age calculation. Because fly has only integration tests, if test case is execute slow, then age calculation at second level might be flake. I think only solution is to remove those second-level age test cases.
