### ISSUE TITLE
Add metadata info available to resources

### ISSUE THREAD

**Issue by Nopik** [concourse/concourse#45]
If one is using some resources sending notifications to external systems (Slack, email, etc.), it would be great to be able to send out info like:
```
Build #42 failed! _Click here_ to see the logs.
```
where `_Click here_` would be the precise link to build 42, e.g. `http://10.244.8.2:8080/pipelines/my-pipeline/jobs/my-testsuite/builds/42`.

Currently it is not possible to do that at all. Exposing some metadata into tasks or resources, or creating some kind of meta-resource would solve this.

**Comment by wfernandes** [comment]
+1

**Comment by drnic** [comment]
A concourse metadata resource would be handy for constructing slack/flowdock/pivotaltracker notifications indeed
