### ISSUE TITLE
When not already cached multiple simultaneous steps fetch same docker image simultaneously

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#450]
This can break concourse very badly, especially after a `bosh deploy --recreate`

The workers run out of disk space. We had 24 jobs triggered every 5 minutes. Due to each one of these fetching the same image, which took more than 20 min, this permanently crippled our concourse. We couldn't even get bosh logs from some workers since there wasn't enough space to create the archive.

The only solution we've found is to pause everything, recreate, then unpause just enough stuff to trigger the fetching of the offending docker images, then unpause everything else.

**Comment by xtreme-gavin-enns** [comment]
Here is a list of all the errors we experienced while this problem was happening (most of them on resource get steps). Some of these will be easily identifiable as unrelated, but I included them all for context. I have these in another document with links to example builds. If it would be helpful someone can ping me privately and I can get you access to our concourse instance to investigate further. I also stored some of the bosh logs from our concourse vms before we recreated them.

- Unexpected end of json input
- Insufficient subnets remaining in the pool 
- Cannot create more than 250 containers
- Volume mounted to container is missing
- Unexpected response code of: 500
- Get <URL> read tcp <IP ADDRESS> read: connection reset by peer dial tcp <IP_ADDRESS>: getsockopt: connection timed out
- container: start: exit status 2
- error running command: read tcp <IP_ADDRESS>: connection reset by peer (treated as failure, not error)
- Failed to pull image <DOCKER IMAGE> resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1
- resource_pool: creating container directory: mkdir /var/vcap/data/garden/depot/kf9n9pegmpa: no space left on device
- error running command: write /tmp/build/get/cf-1.6.1.pivotal: input/output error (treated as failure, not error)
- exit status 1
- Get http://api/containers/ket1gfefr51/properties: dial tcp <IP_ADDRESS>: getsockopt: connection refused
- resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 2
- worker for container is missing

**Comment by xtreme-gavin-enns** [comment]
Confirmed: Same issue cripples a concourse when a docker image is updated. 

Only known solution is to pause offending jobs, recreate workers, then unpause a single job so that it fetches the docker image before unpausing the rest

**Comment by xtreme-gavin-enns** [comment]
Another discovery: You can't just pause the pipelines and recreate to fix this problem. It appears you have to cancel all pending/in-progress jobs as well.

**Comment by xtreme-gavin-enns** [comment]
Another discovery: `bosh recreate worker --force` is not enough to remove the blockage. `bosh deploy --recreate` works though.

**Comment by mtekel** [comment]
+1. Empty cache really swarms worker with multiple concurrent downloads of the same image.
