### ISSUE TITLE
Clean up containers and volumes that are present on the worker and not in the DB

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4500]
We already do the inverse : i.e. clean up containers and volumes that the DB knows about but don't exist on the worker after a restart.

Recently on a customer call we saw an issue where after an upgrade, a bunch of containers were left on all the workers (which were hitting max containers) that the DB knew nothing about. We recreated the workers to clear them, which caused some downtime for their users.

We should
1) investigate to see why these containers are not being cleared up on an upgrade
2) create a mechanism to clean them up.

**Comment by cirocosta** [comment]
Hey @ddadlani ,

Seems like this one is a dup of https://github.com/concourse/concourse/issues/3600?

thanks!

**Comment by ddadlani** [comment]
yes, closing in favor of #3600.
