### ISSUE TITLE
5.5 Large number of database connections

### ISSUE THREAD

**Issue by luispabon** [concourse/concourse#4504]
# Bug Report

Upon upgrading from 5.3 to 5.5, PostgreSQL database connections opened by the master skyrocketed from 9 to 22. There were no changes in the amount of pipelines on the system in between concourse upgrades.

This killed my `db-f1-micro` gcloud postgresql instance, or rather, it prevented other apps from acquiring database connections to do any work, since by default these instances have `max_connections = 25`.

## Steps to Reproduce

Start concourse master 5.3 (no workers), connect to postgresql. Inspect number of connections. Then upgrade to 5.5. Compare number of connections

## Expected Results

Database resource usage to remain the same

## Actual Results

Database connections more than doubled.

## Version Info

* Concourse version: 5.5
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS: n/a
* Browser (if applicable): n/a
* Did this used to work? Yep

**Comment by luispabon** [comment]
![image](https://user-images.githubusercontent.com/6388823/65690257-8d18a780-e066-11e9-930c-8c9736531cc0.png)
See connection stats here. The green line is concourse. The first jump

**Comment by luispabon** [comment]
This is after restoring a db backup and downgrading to concourse 5.3:

![image](https://user-images.githubusercontent.com/6388823/65692439-72483200-e06a-11e9-93a1-b75208802b51.png)

**Comment by aegershman** [comment]
You might try setting `CONCOURSE_MAX_CONNS` on your `web` node?

**Comment by luispabon** [comment]
Thank you for your answer, looks like just the thing. This is then a non-issue, so closing.
