### ISSUE TITLE
Build is not aborted despite success message

### ISSUE THREAD

**Issue by iuztemur** [concourse/concourse#4506]
Hello,
I have the exact same problem as mentioned in this issue(https://github.com/concourse/concourse/issues/4106#issue-464854290).
I have tried nearly every possible solution (restarting VM, recreating worker, aborting build via fly and etc.). But it is not stopping that specific build although it stops further builds.
Any help is appreciated. 
Not: I was using concourse 5.5.1 version.

**Comment by kobylyanskiy** [comment]
The same issue
