### ISSUE TITLE
Not deploying minor version change as latest version

### ISSUE THREAD

**Issue by siyuantan** [concourse/concourse#4509]
Not deploying the latest version from artifactory after successfully fetching the latest version
## Bug Report

> Pipeline is unable to detect and deploy minor version change as latest version from artifactory. This is due to version number increment from X.X.99 > X.X.100 > X.X.101

## Steps to Reproduce

> After pipeline successfully run tests, version is up from X.X.99 to X.X.100. Pipeline deploys version X.X.99 on server and showing X.X.99 as latest version on pipeline while X.X.100 is placed at the bottom of the list of version as an older version. I had to disable every old version (X.X.99...) and only enabling the latest version (X.X.100) to deploy the latest version.

Note: Screen capture illustrates the issue with X.X.101 instead of X.X.100 
![concourse version issue-1-edited](https://user-images.githubusercontent.com/22017311/65750605-5cef0880-e13b-11e9-9334-26d10a5f8c44.png)
![concourse version issue-2-edited](https://user-images.githubusercontent.com/22017311/65750612-60828f80-e13b-11e9-9587-02c810b17246.png)

## Expected Results

> It should detect X.X.100 as the latest version and place it right at the top instead of X.X.99 as latest and placed X.X.100 as old version

## Actual Results

> Pipeline still deploys version X.X.99 on server and showing X.X.99 as latest version on pipeline while X.X.100 is placed at the bottom of the list of version as an older version.

## Additional Context

> N.A.

## Version Info

* Concourse version: v5.3.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: -
* Browser (if applicable): Chrome 76
* Did this used to work? No

**Comment by xtremerui** [comment]
Hi, based on the [check interface](https://concourse-ci.org/implementing-resource-types.html#resource-check), when there are new versions returned by check request, it must in chronological order, according to which concourse saves those versions in DB.

In you case, the `version 0.2.101` is returned as before `version 0.2.11` thus concourse saves it and see it as an older version of `version 0.2.11`.

You might submit this bug to the resource type repo, specifically. 

Thx!

**Comment by siyuantan** [comment]
> Hi, based on the [check interface](https://concourse-ci.org/implementing-resource-types.html#resource-check), when there are new versions returned by check request, it must in chronological order, according to which concourse saves those versions in DB.
> 
> In you case, the `version 0.2.101` is returned as before `version 0.2.11` thus concourse saves it and see it as an older version of `version 0.2.11`.
> 
> You might submit this bug to the resource type repo, specifically.
> 
> Thx!

Hi, thanks for identifying that. 

I have already posted the issue through pipeline-resource repo and awaiting for response.
https://github.com/concourse/concourse-pipeline-resource/issues/63

Thanks!
