### ISSUE TITLE
Concourse should make it so I can easily see when newer bits are moving toward downstream jobs that have already been triggered.

### ISSUE THREAD

**Issue by zachgersh** [concourse/concourse#451]
Initial Proposal (@vito's idea below is much better)

We really like to keep the history of our pipelines (it's nice to be able to look back at previous builds) but  due to the fact that our pipelines are big and have a ton of steps, we end up having to reset them so we can see artifacts we are producing progress through our pipeline.

It would be nice if concourse would allow us to keep the history and merely reset each job so that:
- its passed constraints are ready to pick up a new version
- its color has been set back to grey

Wouldn't mind having to run this via fly on each job down a pipeline that you wanted to reset.

Maybe something like this would work as a command:

`fly -t target reset-job -p pipeline/job`

**Comment by vito** [comment]
It sounds like what's really missing is having some way to see the progression of new bits through the pipeline. We're already planning on improving this. I'm not a huge fan of this particular proposal as it seems way too hands-on; you'd have to run it against every job every time a new version came in (when you cared enough). It seems like it would be better to have the UI somehow dim jobs that are downstream from new bits.

**Comment by zachgersh** [comment]
@vito love the dimming idea and I would like this to be as hands-off as possible. Did you already have something like this scheduled?

I could totally morph the title of this to add your stated goal. I would love to know if there was any design discussion going on around this. Maybe we get @kimeberz to look at this as well?

**Comment by kimeberz** [comment]
Hey @zachgersh! Thanks for opening up this issue. This sounds similar to another story in my design backlog - visualizing resources flowing through the pipeline.

Mind if I reach out to you in a couple weeks to pick your brain on this one? The scenario you mentioned above is helpful for getting a better understanding of how we can best design this. 

Thanks! 🍻

**Comment by zachgersh** [comment]
@kimeberz - of course, if you send a calendar invite along I will make sure to accept it. We could also take some time to review the pipelines that we currently have and the struggles.
