### ISSUE TITLE
Needs a term of pipeline owner

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4510]
## What challenge are you facing?

Since Concourse 5.0 RBAC has been in place, which is a big step, while we still face an OPs challenge, where every member of a team may update and destroy others' pipelines, though most likely just by mistake. 

## What would make this better?

Introducing a term of pipeline owner. A pipeline owner is who set the pipeline. A pipeline owner may grant write permission to other members, so that they may re-set/destroy the pipeline.

## Are you interested in implementing this yourself?

Yes

**Comment by vito** [comment]
Sounds interesting!

Maybe *team* owners should be able to delete the pipelines regardless? (Just so someone can delete it if the original owner goes MIA.)

Do you think you would find yourself setting this all the time, or is it more a pipeline-by-pipeline basis? I can kind of see two sides. Sometimes team members have shared ownership, and you wouldn't want whoever happened to run `fly set-pipeline` to be the "owner" and prevent other shared-owners from deleting it. But if the team is really just being used to track many individual's independent pipelines, you may want it to be a team-level default so you don't have to remember to pass it every time you create a pipeline. 🤔 

There's also the option to just have it do this by default and allow pipeline owners to explicitly share their pipelines with other team-members. This would allow write access and maybe relinquish their ownership. This would be the most conservative approach from a security standpoint.

Also just to confirm: team members will still be able to view these pipelines and see build output/etc. - they just won't be able to perform writes to the pipeline (i.e. `set-pipeline`, `destroy-pipeline`, `rename-pipeline`, etc.).

Side tangent: I suppose another option to consider would be to have individually-owned pipelines, i.e. not even associated to a team. Would that fit your use case? It raises a bunch of questions so there'd be more to map out, but we might want to think about it and weigh pros/cons so we don't end up with two redundant/confusing permission schemes.

/cc @pivotal-jwinters

**Comment by evanchaoli** [comment]
@vito

> Maybe _team_ owners should be able to delete the pipelines regardless? (Just so someone can delete it if the original owner goes MIA.)
> 

Yes, I agree team owner should be able to do anything on pipelines within the team.

> There's also the option to just have it do this by default and allow pipeline owners to explicitly share their pipelines with other team-members. This would allow write access and maybe relinquish their ownership. This would be the most conservative approach from a security standpoint.
> 

This is exactly what I'm proposing. A pipeline owner is the one who `set-pipeline`. An owner may share write permission of his pipelines to others.


> Also just to confirm: team members will still be able to view these pipelines and see build output/etc. - they just won't be able to perform writes to the pipeline (i.e. `set-pipeline`, `destroy-pipeline`, `rename-pipeline`, etc.).
> 

Yes, other team members will still have read permission. (Viewers of course have only read permission.)


> Side tangent: I suppose another option to consider would be to have individually-owned pipelines, i.e. not even associated to a team. Would that fit your use case? It raises a bunch of questions so there'd be more to map out, but we might want to think about it and weigh pros/cons so we don't end up with two redundant/confusing permission schemes.
> 

No, this doesn't fit our use cases. In our practice, Vault plays a very important role in our Concourse clusters. Some teams are big, logically they should be divided into multiple sub-teams, but Concourse doesn't support that. The reason why we still use big teams is the entire team needs to shared some secrets from Vault. If we divide a big team into multiple teams, then secrets have to be copied multiple times, and leads to more maintenance efforts. Thus individual pipeline doesn't fit to us.

General speaking, I feel pipeline owner is a reasonable concept. Maybe we can see if other users have similar requirement. If you know some active users, maybe @ them to call for opinions.

**Comment by mvdkleijn** [comment]
@evanchaoli Just trying to wrap my head around this issue... what would be the difference between a team-owner and a pipeline-owner? To me that seems to be the same thing in your setup, unless you're talking about private / personal pipelines?

**Comment by evanchaoli** [comment]
@mvdkleijn A pipeline owner is who initially set the pipeline. The pipeline still belongs to a team, because it may concourse secrets from the team's Vault (credential manager) path. Only pipeline owner can do write (re-set, destroy, rename, etc.) to the pipeline. A pipeline owner may share write permission to other team members, so who is granted with write permission can  also write to the pipeline.

A team owner is an existing concept of current Concourse. A team owner holds write permissions to all pipelines of the team, which is the current behavior.

Maybe you don't care about team in your use case, But I'd suggest to keep team there, a private pipeline can be in a private team. This should significantly simplify the implementation, as it doesn't breaking existing things.

**Comment by mvdkleijn** [comment]
@evanchaoli I definitely care about teams. Just trying to understand your use-case a little better :smile: I believe I got the gist of it though.

In my "personal pipelines" issue, I suggested creating a virtual team "me" or indeed even an actual team in the db with the same name as the user. So, I agree completely with your suggestion.
