### ISSUE TITLE
Abandoned containers on workers

### ISSUE THREAD

**Issue by aegershman** [concourse/concourse#4513]
## Bug Report

I think we're seeing this: https://github.com/concourse/concourse/issues/3600#issuecomment-535542425

After upgrading from Concourse 5.4.1 -> 5.5.0, we saw two of our workers jump to their container maximums. They don't appear to be garbage collected from the workers.

The two workers (worker-4, worker-5) were _both left in a failing crash-loop state_ during the upgrade, because of the [issue described in the discuss channel about the `overlay` driver not being found](https://discuss.concourse-ci.org/t/overlay-driver-failed-to-set-up-driver-on-5-4-1-5-5-0/1737). So both these workers were in a completely failed state at the same time the web was upgrading. I'm not sure if that makes a significant difference or really what that means, but figure it's worth mentioning.

## Steps to Reproduce

Bumped from Concourse 5.4.1 to 5.5.0, upgrading both the `web` and `worker` deployments at the same time, meaning the `workers` and `web` pods started cycling at roughly the same time.

Here's a snippet of our `workers` config:

```yml
concourse:
  worker:
    ephemeral: true
    baggageclaim:
      driver: detect
```

## Actual Results

Post-upgrade, containers on two of the workers shot _way_ up.

<img width="925" alt="Screen Shot 2019-09-27 at 11 20 51 AM" src="https://user-images.githubusercontent.com/5619476/65784965-ef31e500-e118-11e9-9260-b1defcf628df.png">

Temporarily mitigated this by adding two more workers and modifying the workers to accept more containers:

```yml
worker:
  env:
  - name: CONCOURSE_GARDEN_NETWORK_POOL
    value: "10.254.0.0/16"
  - name: CONCOURSE_GARDEN_MAX_CONTAINERS
    value: "500"
```

Recreating/terminating the worker pods does not seem to help, because as soon as the pod comes back online, it registers itself again with the web nodes && it reports as having the same number of containers. The workers are marked as `ephemeral`, and are [configured to clean their work-dir on start](https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L1509), but I don't think that means their total number of _containers_ will decrease.

I'm not 100% sure best way to remediate this, but I'm thinking I'll try destroying some of the workers _and destroying their persistent volumes_ after they've been removed. Not sure if this is the best solution, though. Advice welcome but worst case scenario is I'll just destroy/recreate the workers.

It's not _ultra-critical_ & if there's anything I can do to help add debug info I'm all ears.

Let me know if there's anything I can do to help 

## Version Info

* Concourse version: 5.4.1 -> 5.50
* Deployment type (BOSH/Docker/binary): Docker helm
* Infrastructure/IaaS: Kubernetes 1.14.5 on AWS
* Did this used to work? Yes, but it's unclear whether this is a direct result of the workers getting bonked up.

Thanks so much!

**Comment by aegershman** [comment]
A few things: I believe there were two problems we experienced that caused this problem.

## 1.) orphaned containers outliving lifespan of workers

[As discussed on `discuss`](https://discuss.concourse-ci.org/t/overlay-driver-failed-to-set-up-driver-on-5-4-1-5-5-0/1737), I believe this may be because information was stored on the PVs associated to the workers outliving the lifespan of the `ephemeral` worker pods. Even after scaling down the stateful set of worker pods to 7, letting it sit for a bit, then scaling back up to 8, the 8th worker container came back with a container listing that matched the count of containers before we scaled down/up... **tl;dr, state of the worker pods persisted on the persistent volume even though they'd have been considered "pruned" from ATC, as the worker pods were `ephemeral`**

Solution for me was to delete the entire worker deployment (not the `web`, we have them separate), or you could scale down the STS to 0 and delete all the existing PVCs and scale back up.

I also opted to use `emptyDir` rather than persistence for the worker pods, so that when the worker pod was destroyed, it _completely_ reset everything on it: containers, volumes, etc.

## 2.) When postgres pods repaved, it appears every resource `check`'d at once, regardless of whether the `checkEvery` schedule is configured for that resource. This can be pretty intense because we have 1441 and growing resources on our k8s concourse deployment. Many of them can use the globalResourceCache, but many of them are `git` repos and would have to be checked individually.

We're running the postgres DB on k8s, too. So it has to be repaved when we repave workers. It appears that when the postgres pod rotated, every resource performed a `check` at once, which caused a large spike in containers on every worker. This gets to a point where the workers would be overloaded with containers like at `256`+ containers. Once it gets to that point, for some reason it doesn't garbage collect anymore, and it just gets... stuck. So we shoot it. 

Weirdly, grafana reports that after a while the number of `check` containers active goes _way_ down after the repave, but the total number of containers on a single worker stays high until the worker is shot. Also interesting is the locks held for `ResourceConfigChecking` appears to spike on a web node & then stay there. Pics attached.

![Screen Shot 2019-09-30 at 10 46 51 AM](https://user-images.githubusercontent.com/5619476/65895137-90ff3f00-e370-11e9-919b-c340536cbb7e.png)
![Screen Shot 2019-09-30 at 10 46 06 AM](https://user-images.githubusercontent.com/5619476/65895138-90ff3f00-e370-11e9-9cf6-953d6c5f4c90.png)
![Screen Shot 2019-09-30 at 10 54 23 AM](https://user-images.githubusercontent.com/5619476/65895232-c015b080-e370-11e9-8698-3e345ec02872.png)
![Screen Shot 2019-09-30 at 10 55 34 AM](https://user-images.githubusercontent.com/5619476/65895285-d885cb00-e370-11e9-8520-ca5cc4d38d3b.png)

Current mitigation to prevent workers from being overwhelmed during `check` spikes is to set `GARDEN_MAX_CONTAINERS` back up to 500, and if one of the workers gets stuck... just like, you know, shoot it.


Let me know if there's any more info I can add to help, advice welcome, etc., but otherwise we'll just chug along with our current configuration until alternatives are available.

Thanks!

**Comment by xtreme-sameer-vohra** [comment]
Hey @aegershman,

The first issue was addressed here - https://github.com/concourse/concourse/commit/f3f7555a9de43d504dee67c6b54f37eb97f59b0f
Have you had a chance to use the latest patch on v5.5 ?

**Comment by xtreme-sameer-vohra** [comment]
Thanks for the detailed info for the postgres rolling issue. Could you rename the issue to focus on that if you feel the first issue has been addressed ?

**Comment by aegershman** [comment]
Sorry for letting this sit around; I'll go ahead and close this out. Thanks all
