### ISSUE TITLE
View Worker Job Ran On

### ISSUE THREAD

**Issue by rhysxevans** [concourse/concourse#4517]
## What challenge are you facing?

Issues troubleshooting intermittent problems. We have a number of job intermittently failing and we would like to determine if this is when the jobs run on a specific worker / set of workers.

The ability to see where the job run will help us narrow down the root cause of our issues. Be that but ruling some out or by confirming some suspicions   

## What would make this better?

Within the job run output , display the worker name, ip and any other relevant data.

## Are you interested in implementing this yourself?

I would if I could, but I am not a programmer / developer.

**Comment by evanchaoli** [comment]
I was about to raise a similar issue. Though `fly containers` shows a mapping from worker to containers, it's always hard to find a worker name from a long list.

Pipeline viewers may not care much about where a job runs on, but OPs people sometime need to know workers. One sample is as @rhysxevans mentioned of troubleshoot issues; the other sample is to verify if a build step properly landing on a worker with specific team and tags.

Let me create a PR to show worker name as well as relevant data on GUI.
