### ISSUE TITLE
Builds bar in build view doesn't scroll on Firefox

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#4531]
## What challenge are you facing?

I'm currently unable to leverage scroll in the builds section of the build view in Concourse 5.6.0
when using Firefox 69.0.1  (Chrome works just fine).

![Screen Shot 2019-09-30 at 4 08 18 PM](https://user-images.githubusercontent.com/3574444/65912896-f36e3480-e39c-11e9-8ddd-91d02101d7e0.png)

As @pivotal-jamie-klassen pointed out, it could be a problem with the way that Firefox registers mousewheel (I guess?) events.

## What would make this better?

Have it working like in Chrome 😁  

Thanks!

**Comment by friegger** [comment]
Just switched to Firefox and stumbled over this. It's really annoying. As long as this is not fixed, is there any other option to scroll the history bar, e.g. via keyboard?

**Comment by taylorsilva** [comment]
This is working in the latest version of Concourse using the latest Firefox 84
