### ISSUE TITLE
On a Concourse using cf-auth, when a user switches to the Auditor role, they lose access to their teams

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#4535]
**Summary**

Within cf-auth, a user has access to [three roles](https://docs.cloudfoundry.org/concepts/roles.html#roles) with their given org: Manager, Developer, and Auditor. It appears as though Concourse auth only recognizes the Developer role. If a user switches their role to Auditor within their cf-auth org, they lose access to their Concourse teams.

Speaking to @pivotal-jwinters, it seems as though their is a secondary API endpoint called `audited-spaces` for this role that Concourse will need to integrate with for this to work and consolidated all of the roles within spaces. 

Currently the CF auth connector hits the `v2/users/user-id/spaces` ([docs](https://apidocs.cloudfoundry.org/12.0.0/users/list_all_spaces_for_the_user.html)) endpoint to determine if a user is part of a space. This endpoint returns spaces that a user has a CF developer role for. It does not return spaces that a user is an auditor for though.

To get the spaces that a user is an auditor for we should also hit `v2/users/user-id/audited_spaces` ([docs](https://apidocs.cloudfoundry.org/12.0.0/users/list_all_audited_spaces_for_the_user.html)). We should then have the full list of spaces that a user belongs to.

**Side note**: During the call we did not confirm if a user with the CF Manager role also has the same issue. If it does then we may need to hit a _third_ API endpoint, `v2/users/user-id/managed_spaces` ([docs](https://apidocs.cloudfoundry.org/12.0.0/users/list_all_managed_spaces_for_the_user.html))

**Acceptance Criteria**

- As long as a user is within the proper org, they should have access to the Concourse teams they're auth'd against, regardless of their role being Manager, Developer, or Auditor.

**Comment by zoetian** [comment]
**Dev Note**

- created branch `pr/cf-auth-auditor-can-switch-team` on `concourse/dex` fork
- added feature in `HandleCallback` function 

Next Step:
- tested locally
- modify unit test `cf_test.go`

**Comment by zoetian** [comment]
**Note** (procedures to setup the testing env)
[1] claim an available pool from opsman via cf-cli 
- you can find all the (unclaim)claimed env here: https://environments.toolsmiths.cf-app.com/pooled_gcp_environments

In order to claim one, install `smith-cli` (https://pivotal.github.io/cf-toolsmiths-docs/pivotal-cf-experimental/toolsmiths-envs/smith/)


[2] run `env TOOLSMITHS_API_TOKEN=$FROM_LPASS_TOOLSMITHS_API_TOKEN env=$CLAIMED_OPSMAN_ENV_NAME smith cf-login` to login, then you can access/ create the users, spaces, orgs

**caveat**: if it prompts to ask for pre-requisite `om`, install it from https://github.com/pivotal-cf/om

side notes: instruct to create users on opsman env can be found here: https://docs.cloudfoundry.org/adminguide/cli-user-management.html

**Comment by zoetian** [comment]
**Update**

- modified `docker-compose.yml` with 
```
CONCOURSE_CF_CLIENT_ID: concourse_atc
CONCOURSE_CF_CLIENT_SECRET: Csp5rSat6hwGjyS_yuW8YXe0sPD-_IFE
CONCOURSE_CF_API_URL: https://api.sys.paleplum.cf-app.com
CONCOURSE_CF_SKIP_SSL_VALIDATION: "true"
```

for testing purpose 

- refactored code for handlerCallback


**Next Step**
- add unit test for `managed_spaces`
- test api with PAS env to see if users with `manager/auditor` roles can login successfully

**Comment by ukabu** [comment]
I was quite surprise that this change is acceptable and was released without the use of a flag to enable that feature.

IMHO an space auditor in CF should not have access as a team member to the pipeline.
This is quite a big security issue for us as this now give powerful privileges to people who shouldn't have them.
A space auditor in CF isn't allowed to push apps, but now they can via a pipeline.
I think this should be reverted and a 5.7.1 release made quickly.

**Comment by ukabu** [comment]
The acceptance criteria should be changed to include a flag to enable that feature.
The different roles in CF should also have different roles for Concourse.

**Comment by pivotal-jamie-klassen** [comment]
@ukabu agreed. I think there's another way to add this feature that is 'less' breaking, which would be for each space/role combination be considered a group from the perspective of the CF auth connector. We're setting up a 5.7.x release pipeline now.
