### ISSUE TITLE
Investigate: strategies to sync up number of containers between a worker and the ATC

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4537]
Splitting this out from https://github.com/concourse/concourse/issues/3600 to be more focused on the problem that workers and ATC have no current way to achieve consensus, when a container exists on a worker but has no corresponding record in the ATC DB.

Context: https://github.com/concourse/concourse/issues/3600#issuecomment-537161482

This issue is a placeholder to explore what options we have for getting back from the "secret containers on worker" problem.

**Comment by ddadlani** [comment]
we've been working on this in multiple issues:  #3600, #4671, #4562 etc so going to close this catch-all issue for now.
