### ISSUE TITLE
Should we do a v5.7 to make the v6.0 upgrade smoother?

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#4538]
We will use the implementation of #4534 to make the upgrade to v6.0 smoother but we will need to document the fact that users will need to upgrade to v5.7 before upgrading to v6.0.

**Comment by deniseyu** [comment]
From the discussion in https://github.com/concourse/concourse/pull/4508 it sounds like it might be a good idea to have a release before v6.0 to show warnings about the new naming rules somehow, and give folks a chance to migrate their pipeline names or set up display-names before enforcing the new requirement.

**Comment by vito** [comment]
Decided not to take this approach; we're doing a lazy + on-demand migration scheme instead.
