### ISSUE TITLE
Newrelic metrics emitter losing most events

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [concourse/concourse#4540]
## Bug Report

`CONCOURSE_METRICS_BUFFER_SIZE` does not have an effect with the Newrelic emitter. 

## Steps to Reproduce

Given a busy concourse deployment that emits metrics to Newrelic, the metrics are dropped after metrics buffer is full; **and it gets full in few seconds**. For example, even after I bump the buffer size to 7000 (default is 1000), the number of dropped messages will be the same (calculated that by counting the number metrics error messages in the logs).

I think the problem with this flag is that it gives a false sense of improving metrics collection. **I believe that If this flag is not combined with some kind of metrics batching, it will not have an effect on the metrics throughput.**

## Expected Results

Much fewer metrics being dropped.

## Actual Results

Most metrics are being dropped.

## Version Info

* Concourse version: 5.5.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Azure
* Did this used to work?: No

**Comment by cirocosta** [comment]
Hey @pivotal-jamil-shamy,

Thanks for submiting the issue!

<br />

As the current way that we've been submiting metrics to NewRelic seem to not be
good enough in terms of throughput, I think an approach that we can go with here
is of batching the events (just like how it was done for InfluxDB - see
[#3937]), and eventually include compression of the contents (something that
NewRelic advertises to be possible).

[#3937]: https://github.com/concourse/concourse/pull/3937


Naturally, being a SaaS, NewRelic imposes some limits on how big those requests
can be:

1. 100k POSTs in a per-min window (across the entire fleet)
2. 1MB max payload per POST (w/ compression we could pack even more stuff as long
  as the final payload is of 1MB)
  - (seems like) no limit on the number of events per payload (as long as max
    payload is respected)

It's nice to see that by leveraging batching we might be able to reduce the
probability of hitting limits that `1` might present.

btw, it's also important to have in mind that while a single actor can't really
control the total number of requests being sent in a minute by all of the
instances (`1`), we can definitly control `2`.


I'd say that as acceptance, we should:

- demonstrate that with the use of batching we can confirm that our throughput
  is higher, making it less probable to drop events

Thanks!

**Comment by cirocosta** [comment]
(ps.: Pivotal Concourse is working on this one)

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
@taylorsilva and I implemented the batch emit logic for newrelic metrics, which:
- buffer size limit is 1MB per emit
- zip is turned on when compression flat is set to true
- will flush whatever is in the queue every 2mins
- been tested with return code `403` due to account issue.

**NEXT**
- account get linked to pivotal paid account.
- manual test the batch emit
- think about the test coverage
- parameters tunable

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
Today I:
- made the flush interval configurable through parameter/environment variable
- fixed miniral bugs
- added test cases for `new relic emitter`

**NEXT**
- account link to pivotal paid account. (ask pivotal ask if there is still no response)
- continue the test cases for `new relic emitter`.

**Comment by zoetian** [comment]
**Dev Note**

@pivotal-bin-ju and I :
- improved the performance of the `enqueue` function by:
     - changed the `batchPayload` from object array to byte array 
     - used `batchPayload` array to store marshaled json data

- adapted unit test for emitter with the current changes

**Next**
- add more test coverage for `compression` in `newrelic` unit test
- keep track of the `newrelic` account from ask (right now we still have the `403` status code when emitting to `newrelic` server

**Comment by taylorsilva** [comment]
Ran a quick test of the code we have so far versus master.

Set `CONCOURSE_METRICS_BUFFER_SIZE` to `20`.

Start concourse and set the example "time-triggered" pipeline:
```
fly -t local login -u test -p test -c http://localhost:8080
fly -t local sp -p test -c sample.yml
fly -t local up -p test
```

Using `master`, checking the logs `docker logs concourse_web_1 | grep queue-full` we see this error message a bunch of times.

Switching to our `metric-newrelic` branch, `docker logs concourse_web_1 | grep queue-full` returns nothing. Our throughput is already faster!

We still have bugs to workout (newrelic says our json is incorrect 😬 ) but what we have so far looks promising.

**Comment by taylorsilva** [comment]
### Dev Note

Current working code is on `new-newrelic` branch: https://github.com/concourse/concourse/commits/new-newrelic

Currently working on the test suite. If you're picking this up, continue adding tests. There's one WIP commit that you can `--amend` on top of.

cc @pivotal-bin-ju
