### ISSUE TITLE
Better error message when .flyrc has malformed YAML

### ISSUE THREAD

**Issue by benchristel** [concourse/concourse#4549]
## What challenge are you facing?

My pair and I were confused by the error message emitted when attempting to run a `fly` command with a malformed `.flyrc`.

```
fly i -u https://my-concourse.ci/teams/main/pipelines/foo/jobs/bar/builds/1
error: error converting YAML to JSON: yaml: did not find expected key
```

## What would make this better?

If the error message stated that `.flyrc` was the problem, that would be great.

## Are you interested in implementing this yourself?

We might get around to it eventually.

**Comment by iamjarvo** [comment]
I can look into this

**Comment by benchristel** [comment]
Thanks!
