### ISSUE TITLE
Documented Concourse manifest should make fewer assumptions about cloud config

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [concourse/concourse#455]
I walked over to the Concourse team today to discuss this, but wanted to put this in writing so @vito can weigh in too.

The CF Infrastructure team is working on a tool called [bosh-bootloader](https://github.com/pivotal-cf-experimental/bosh-bootloader) (`bbl` for short) which has the goal of making it easy for people to get started with BOSH on AWS, as this is a major pain point for the CF community, and it also leads to many of the core development teams of CF re-inventing their own solutions.

The tool will allow users to spin up AWS resources, bosh-init, and create a cloud-config with a single command, only providing AWS credentials to kick it off.  An additional simple command will create ELBs for Concourse or CF -- the experience is tightly curated for these use cases to maximize simplicity.

We'd like to submit a PR to the Concourse docs so that the example manifest doesn't make hard-coded assumptions about things in cloud config, e.g. `vm_type: web`.  So we would simply replace these with `vm_type: REPLACE_ME` and some explanation of what to replace them with.  We don't want to re-write BOSH docs, so we would only add the bare minimum in addition to linking to BOSH docs if necessary.  This does imply a couple not-entirely-trivial changes, because rather than having instance types, ephemeral disk sizes, and am-I-behind-an-ELB configurations all in `vm_types`, we leverage `vm_extensions` to make this more composable.  So we would include that in our PR.

Just putting this upcoming PR on your radar.

/cc @zankich @mariash @krishicks

**Comment by vito** [comment]
merged the PR so this should be resolved now?

**Comment by Amit-PivotalLabs** [comment]
Yes, thanks!
