### ISSUE TITLE
missing lidar check metrics for non catch-all emitters

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#4551]
## Bug Report

Once we got Lidar in (see https://github.com/concourse/concourse/issues/3788), the metric that keeps track of the checks being performed was changed (see https://github.com/concourse/concourse/commit/e66e0302bed4edb3966c813a8f6b5da9eead5b7c).

As there were no emitter-specific changes, this means that those emitters that need specific formats (like Prometheus and NewRelic) do not get the events. 

## Steps to Reproduce

Run `concourse` with `CONCOURSE_PROMETHEUS_BIND_IP=0.0.0.0`, CONCOURSE_PROMETHEUS_BIND_PORT=9090`.

curl localhost:9391 | grep concourse_ | grep check

## Expected Results

Have a check metric.

## Actual Results

No check metric

## Additional Context

See https://github.com/concourse/concourse/blob/f580c2b1f59d95c862784521d710847830c41f1f/atc/metric/emitter/prometheus.go#L364-L367

ps.: I've been experimenting with getting rid of these per-emitter configurations that we must remember to do right now (see https://github.com/concourse/concourse/pull/4247)

## Version Info

* Concourse version: 5.6.0
* Did this used to work?: yes

**Comment by xtremerui** [comment]
While I am checking [newrelice](https://github.com/concourse/concourse/blob/f580c2b1f59d95c862784521d710847830c41f1f/atc/metric/emitter/newrelic.go#L114) it seems ignoring `resource checked` event. In this case do we want to add only `check finished` or add both, or even do nothing?

**Comment by cirocosta** [comment]
I think that if we're willing to still have both metrics, we need to have both being captured 🤔

**Comment by cirocosta** [comment]
(I mean, I'm not very familiar with why the name of the metric changed - if it's important to have it under a different name, assuming that one can still get the metrics from radar when lidar is not activated, then we should capture both)
