### ISSUE TITLE
Web UI Dashboard - Pagination of Pipelines

### ISSUE THREAD

**Issue by nictrix** [concourse/concourse#4552]
## What challenge are you facing?

I have 3,000 pipelines and the Web UI dashboard will load after 40-60 seconds (maybe), but it's unusable, hangs the browser page, then I have to kill the browser off. Splitting it up in teams is okay, but I'm still a member of all the teams for those pipelines, which the dashboard still shows.

## What would make this better?

The Web UI needs some sort of reduction of pipelines on the dashboard, such as paginating them. Then I could use the search to find the ones I need to look at.

## Are you interested in implementing this yourself?

I would if time permits, but most likely I would not have the time to do so myself.

**Comment by kcmannem** [comment]
if possible load on demand as a user scrolls or jumps around using the sidebar/search. I don't like page numbers.

**Comment by dnd** [comment]
I think it makes sense to avoid page numbers, but I would be concerned then that once you scroll far enough the same problem will arise with concourse then trying to load statuses for everything it has already loaded.

A way to only view pipelines for a selected team seems like it could help mitigate this, and maybe make sense from a convenience stand point. I don't think you can currently select a team, and even be take right to those pipelines. The sidebar provides the ability to nav to a specific pipeline only.

What about if concourse only tried to load information for pipelines that were visible in the viewport? That would seem to solve the problem no matter what.

**Comment by pivotal-jamie-klassen** [comment]
@dnd you can filter to only show a team's pipelines using the syntax `team: <team-name>` in the search input, like in https://ci.concourse-ci.org/?search=team:%20examples
