### ISSUE TITLE
Add metrics for LIDAR

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4554]
* [x] Size of check queue
* [x] Number of checks queued (per ATC)
* [x] Number of checks GC'd
* [x] Time it takes to run each check (start time - end time)
* [x] Time between queue and check started (create time - start time)
* [x] Check status (success/failure/error)

**Comment by xtremerui** [comment]
Is `Number of checks queued (per ATC)` still valid when there is component runner now? Since at a given period of time there will be only one checker running, I think `Size of check queue` should be enough? @vito

**Comment by vito** [comment]
@xtremerui That metric is meant to be 'number of checks added to the queue' (by whichever ATC added them) which is a bit different from 'size of check queue' (which could be emitted by anyone like you said).
