### ISSUE TITLE
tsa: remove 'register-worker' command

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4566]
following #2748 the command never actually gets issued by a worker, so let's not have the TSA listen for it.

some obvious places to change:
https://github.com/concourse/concourse/blob/d51d6997367a28e1c9768e27c7bde66b5939a2b2/tsa/commands.go#L5
https://github.com/concourse/concourse/blob/52e613930972c7361d1938b1f5b5a7d66c5adf00/tsa/README.md#L61
https://github.com/concourse/concourse/blob/a1abe28d3aeac9be021a8de7d67257551e61c661/tsa/tsacmd/server.go#L493-L496
https://github.com/concourse/concourse/blob/a1abe28d3aeac9be021a8de7d67257551e61c661/tsa/tsacmd/remote_cli.go#L141-L179

**Comment by pivotal-jamie-klassen** [comment]
Related: concourse/docs#258

**Comment by cirocosta** [comment]
cc @ddadlani  - sounds like `side-road`? 😁

**Comment by ddadlani** [comment]
@cirocosta yep that's right. As a core contributor, feel free to add issues to any of the sub-projects if you're in the mood for some Runtime triaging. I usually go through and organize the sub-projects on Monday morning, so I'll move issues around if needed and add new ones (such as this one) to the backlog then.
