### ISSUE TITLE
Countless unknown handle errors

### ISSUE THREAD

**Issue by dnd** [concourse/concourse#4567]
## Bug Report

We recently started to scale to around 3000 pipelines, the vast majority of which are very similar in terms of structure and exact resources used(don't know if that matters). 

We get unknown handle errors non-stop to the point where most of the jobs either can't run, or fail in the middle of a run because a resource disappears. 

We trigger a manual resource check sometimes, and it will take more than 10 minutes to run. Sometimes we also see a resource flip from unknown to ready, and then back to unknown in as little as 30 seconds. 

Our web, and worker nodes do not appear to be under any real pressure in terms of cpu, disk, or memory. 

I see #4366 which may be relevant? Honestly I'm not sure how to debug this. 

## Steps to Reproduce

Not sure. We had occasional unknown handles even at 100 pipelines. 

## Expected Results

We expect for resources to stay present, especially when in the middle of being used for a job

## Actual Results

Many, many unknown handle errors

## Version Info

* Concourse version: 5.5.1
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS: 5x aws m4.4xl ec2 workers, and k8s 3x web nodes
* Browser (if applicable): na
* Did this used to work? Don't think so

**Comment by kcmannem** [comment]
Thanks for reporting this. I do remember seeing this happen with someone when they set https://github.com/concourse/concourse/blob/master/atc/atccmd/command.go#L103 to a lower value which starved the amount of conns to the db. Another setting was that they changed the check interval to 5 mins https://github.com/concourse/concourse/blob/v5.5.1/atc/atccmd/command.go#L118 .

**Comment by ddadlani** [comment]
It would also help if you could share any relevant web and worker logs leading up to the occurrence of the error.

**Comment by kcmannem** [comment]
related issue https://github.com/concourse/concourse/issues/4521

**Comment by kcmannem** [comment]
errors coming from garden:

https://github.com/cloudfoundry/garden/blob/3d82d212ad6731fc9e29d6b143046716122e49eb/errors.go#L121

idk why, we've seen cases where containers are present on the worker but not in the db. This is the opposite of that, which we haven't seen before.

@dnd have you been seeing this for every version of concourse you've used? What version is the earliest you recall seeing this error.

**Comment by ddadlani** [comment]
A few more questions: 
*do you use ephemeral workers?
* What is the size of your db node?
* Is your database node under any kind of pressure?
* Is there contention for the db connections?
* are the same container handles erroring out? or is it a different one every time

We shipped a fix for this in our GC in https://github.com/concourse/concourse/issues/2588 (part of v5.0.0) but our theory right now is that this has something to do with the high load on your system

**Comment by dnd** [comment]
@kcmannem & @ddadlani thanks for the responses. Apologies for the delay in my response. I had to tackle a bunch of production issues this week.

Current configuration:
* 3 web nodes run as k8s pods, and are dedicate 12 cpu, and 8G memory
* 15 m5.4xl worker nodes running as dedicated ec2 instances in an ASG
* RDS instance is currently an m5.4xl with 2000 provisioned iops.

We currently have `CONCOURSE_MAX_CONNS=64` in our web node config. We were not specifying the value before, so I think we had the default of `32`.

The workers may be oversized at 4xl, but that was what we ramped to to at least get things working somewhat.

I don't think we have any specific pressure on the DB at this time. We did previously, which prompted us to grow to the current size. Here are some graphs from RDS. The big drop offs are from points where we took down workers for various rebuild reasons. Charts are all from the past week, with 1 minute precision

* Connections - they fluctuate a lot, but seem to have a defined floor, even though it doesn't add up to the conn max for 3 nodes x64 of 192. 
![image](https://user-images.githubusercontent.com/37888/66723361-a7c87b80-eddd-11e9-965b-cad1ebdd5896.png)
  
* CPU - tends to be pretty comfortable around 60%
![image](https://user-images.githubusercontent.com/37888/66723315-21ac3500-eddd-11e9-8d71-37f8b62b4839.png)
 
* Write IOPS - this is interesting because 900-1000 wiops is about the best we can get. When I have tried scaling to 4 web nodes, the wiops will actually decrease. I don't know if that's expected, but it does seem interesting
![image](https://user-images.githubusercontent.com/37888/66723283-c4b07f00-eddc-11e9-9211-7188f45937e4.png) 

* Read IOPs - there's hardly anything here. I *think* this is normal?
![image](https://user-images.githubusercontent.com/37888/66723373-d21a3900-eddd-11e9-8836-32e31f59d9ed.png)

All our resources are already explicitly set to check every 5m. Some of them are very static, but I'm hesitant to raise the check interval to something like 1h, or 24h, because I believe if they go away due to this unknown handle problem they may potentially not be rechecked for a very long time, and thus the pipeline jobs they're required for won't build, correct?

We are working to get through the corporate process to get a more detailed logging setup in place, which we hope will happen before end of month.

For logs there isn't really a lead up. The system is never fully functioning. From the get go resources report as unknown in the logs. There doesn't appear to be any "telling" entry of when it all goes wrong. Is there anything specific I can search for in the logs that might give a clue?

We used concourse v4.2.3, but not anything like this scale. We started moving to this scale after upgrading to 5.1.0. As mentioned in the original post we were occasionally seeing this problem even with less than 100 pipelines active.

Our workers are built to be ephemeral, although at this point we are not doing any dynamic scaling. Something interesting I have noticed with the workers is that sometimes they just stop working. Checking their metrics, their cpu shows 0% utilization, but they are **not** listed as `stalled`. The instance that is flatlined will just have a static container count. Upon restarting the node, or restarting the concourse service on the machine it returns as an active member, but concourse never seems to realize the machine isn't doing anything.

Here is the current listing of workers. The container numbers are low since they all just came back online an hour ago. Normally the container counts are around the high 100s, peaking into the low 200s. https://gist.github.com/dnd/889e39e8290cfdf9761ca1edbb1afb6b

Best I can tell no resource is safe from this. You can pick any pipeline to watch in the ui, and you will just see the resources flipping black, then back to orange, and so on at random intervals. When all the stars align the job will run. Usually the job will complete its run except for if it puts to a resource. In that case it just depends if that output resource goes away before the job completes or not.

Would this be something the new Lidar changes in 5.6 might help with? Please let me know if I can provide any more information.

**Comment by kcmannem** [comment]
@dnd thanks for the detailed response. We'll need to think about this more so I can't give you a definitive answer atm.

When you say your workers are built to be ephemeral do you mean you've set the `ephemeral` flag for them? https://github.com/concourse/concourse/blob/a342ab265db64e0d475bee24619ffcd5f5589d15/worker/workercmd/worker_config.go#L18

**Comment by dnd** [comment]
@kcmannem No problem. I appreciate the help in trying to work through this. Yes, we do have `CONCOURSE_EPHEMERAL=true` in our env config. My previous statement that workers don't get removed isn't entirely accurate. Sometimes they don't get removed, and are just in some kind of stalled state, but still report as `running`. Other times they are removed when they stall out.

I don't know enough about the new Lidar system, and don't want to jump into an upgrade just because, but given that the current situation we have seems completely resource focused, the mention of different resource handling has my interest.

Something else that has been on my mind is, is this beyond the scale of anticipated capabilities of Concourse? Not every tool is the right tool for the job. If we're using Concourse in a way that wasn't intended I don't want to go down a potentially neverending path.

The pipelines we have at present have 5 resources each currently. With all of them at a check interval of 5 minutes, that averages out to around 50 checks per second assuming a best case even distribution. This would be spread across the current 15 workers as about 3-4 checks per second which really doesn't seem terribly high, and some of the other node stats make me feel like we don't really need to have more nodes. I would be interested to get your guys thoughts on that though.

**Comment by xtreme-sameer-vohra** [comment]
Hey @dnd

**Comment by dnd** [comment]
Sorry for the delays in this again. I was hoping to be able to get some of the metrics asked for, but we're waiting for firewalls to be opened up. If that goes well I should be able to provide some metrics data next week.

@kcmannem I tried setting the workers to not be ephemeral. This did help stabilize their presence in the cluster, and apparent workloads staying continuous. I say apparent because even though `fly` will report that there are containers on the node, the node will still have 1% cpu in use, although this is less prevalent than before. 

Is there not a way to give a grace period to workers? Ejection after one missed heartbeat seems extreme. I would think `x` failures over `y` seconds or something would be a little more stable?

You mention high workloads, which I am interested to see my metrics, but at least cpu-wise I don't think I have had a single worker get over 20-30% cpu for any remotely sustained period, and most of them sit around 5-10%. Spot checks on the machines show anywhere from 1G to 20G mem free using `free`. 
 
I think we'll take a look at upgrading to see if Lidar helps. You mention `limit-active-tasks` which we have tried, but it seemed to have no impact. If I look at the detailed view for the workers, I almost never see any of them indicating they have an active task. If I'm really lucky I will see one of them have `1` active task. I don't know if this is an error in concourse's reporting, or if they're really doing nothing.

@xtreme-sameer-vohra 
* it's the error that @kcmannem references above here https://github.com/cloudfoundry/garden/blob/3d82d212ad6731fc9e29d6b143046716122e49eb/errors.go#L121 `unknown handle: <some uuid>`
* I will keep looking, but I just tried spot checking a few of them, and I can't find the uuids in the web node logs at all. Even for a resource that turned from working, to unknown right in front of me
* working on it. hope to report back next week

I noticed something else today that is very bizarre. I don't know if it's related, but we're using the `swce/metadata-resource` to get the build information to log for everything going through(yes, I know this may be frowned upon). The problem I'm seeing though is that this information that is being output should correctly identify the build, right? This happened in multiple jobs to varying degrees of inaccuracy, but I have included the most extreme example below.

![image](https://user-images.githubusercontent.com/37888/67540285-73d93a00-f6aa-11e9-972f-ab615a5b85df.png)

The build that concourse indicates this is is `37`. The metadata resource is of the belief that this is `36`, and inside the actual build where the data is referenced, the build is seen as `29`. Not only that, but the job name(which I had to redact) also does not match the job build that is currently being viewed.

The metadata-resource is pretty simple, basically just dumping some envars, but is this implying that concourse does not have a correct idea of what this build is, essentially mapping a resource from one build to a different one? There is a distinct metadata resource version for each build.

I think this ultimately happened because our workers were down for a while, and when they came back there were numerous "versions" of the git repos to build, but it seems like concourse just randomly assigned the metadata resources to the jobs as the inaccuracies aren't in a sequential order or anything.

**Comment by dnd** [comment]
Wanted to provide an update on tracking one of the unknown handle uuids. The web logs spin by too fast, and I cannot see an earlier events than the ones provided(if there are any). Something that I saw as well is that sometimes multiple web nodes may have the same unknown handle errors. I don't know if that's expected or not.

* web 1
```

**Comment by dnd** [comment]
I can log this as a separate issue, but figured it might be helpful to have anything relevant to this in one place. We tried upgrading to 5.6.0, and immediately started getting a tremendous number of these messages in the logs.

```
{"timestamp":"2019-10-28T01:40:59.997914837Z","level":"error","source":"atc","message":"atc.lidar-scanner.failed-to-create-check","data":{"error":"base resource type not found: pull-request","session":"23"}}
```

**Comment by kcmannem** [comment]
@dnd thanks for giving us this info. Based on the logs you provided theres definitely something funky going on.

Heres the place where you can change the heartbeat internval, the transition to "stalled" happens when you don't receive a heartbeat in that interval*2.

https://github.com/concourse/concourse/blob/66c450e653333e2d40ad77b1d74c24627757a3c6/tsa/tsacmd/command.go#L40

**Comment by dnd** [comment]
Looking at some of the metrics we're getting now, I see all 15 workers as having 1500-3000 volumes each, with the average around 1800.

I deleted the team that had almost all of the pipelines, and left just three very simple pipelines left. I then restarted the web nodes, and the workers. I still get unknown handle errors, and inconsistencies. All workers are still indicating 1000s of volumes each.

**Comment by dnd** [comment]
I tried terminating the worker nodes, and when the new ones came up, they reported 0 volumes in use, so possibly some type of runaway accumulation by garden?

We just tried starting with a completely fresh db, and upon applying the first pipeline(the one that builds the other pipelines), all resources were black, and things started building nicely. 

After a short while of it creating the other pipelines I watched all of the resources go yellow on that pipeline. This is happening even though those new pipelines are all paused. I don't know at exactly what number of pipelines triggered the problem because it happened so fast. 

It seems like even though a pipeline is paused that concourse still tries to check its resources. The strange thing about that is I don't see corresponding log entries for those checks(if they exist) as I would when the pipelines are all unpaused.

Whether it does or does not really doesn't matter in the long run since all the pipelines are ultimately supposed to be active.

Not sure what else to look into, or what kind of information I can provide. If there is something, please let me know soon, because this may not be around much longer. At this point we don't really have much choice other than to consider moving to something else to solve for our needs, but I would like to provide whatever I can to help the community improve concourse.

**Comment by xtreme-sameer-vohra** [comment]
Hey @dnd 
Thanks for providing the detailed log entries. You're conclusion is right in that the container with handle `3961942c-d82d-4882-64ad-c4c25bedcd95` is deleted by Garden ~5mins prior to it be sought out by the Web instances.

It might be too late to know this now, but do you know if the worker that had this handle was in `running` state the entire time or did it potentially go into a `stalled` state ?

**Comment by xtreme-sameer-vohra** [comment]
You're right when pipelines are in the paused state, there is no `checking` happening on their resources. In addition to the logs, you can confirm that by checking the results of `fly containers`

**Comment by xtreme-sameer-vohra** [comment]
@dnd 
To help us narrow the issue further, it would be helpful to understand whether the workers in your deployment are in stable `running` condition or they seem to `stall` quite often. 

You had mentioned that you might set up some metrics to monitor the concourse deployment. Were you able to set this up ?

Lastly, thank you for your patience and willingness to contribute to Concourse. We have users operating Concourse at a similar scale so I am hopeful we can sort out this problem together.

**Comment by dnd** [comment]
So some very good news here. We were doing some work trying to reconfigure something else on the image, and one of the team members pasted the current `environment` file in use for the workers. I noticed this value `CONCOURSE_GARDEN_DEFAULT_GRACE_TIME=60s`. I didn't know exactly what it was, but the fact that it was 60 seconds, and that correlated with how long containers seemed to last I got pretty excited. 

I googled that flag, and came across this https://github.com/concourse/concourse/issues/3054 where the author was indicating they set it to a "low" value of `2m` and were getting unknown handle errors. Seeing as ours was 60 seconds as mentioned that seemed like a problem. I removed the flag, and immediately the unknown handles went away. 

I started to experience insufficient subnet messages, which I remediated with the suggestion in this comment https://github.com/concourse/concourse/issues/847#issuecomment-461345629 which recommended increasing the garden subnet size to `172.16.0.0/12`.

I tried tracing how that `CONCOURSE_GARDEN_DEFAULT_GRACE_TIME=60s` got in, and it looks like it was possibly a default setting for concourse back around v4.2.1? What's strange is that we were having these unknown handle errors in our k8s cluster, and this setting was not present. It only got resurrected when we moved our workers out of the k8s cluster, and onto ec2 instances. So there may be something else about running at this scale on k8s?

So I now have 3000+ pipelines all with resources present, and accounted for. Which is absolutely fantastic, and huge progress! There are still some issues though, and I still have some concern, as I have cut down the scope of the pipelines, and vastly extended their check times.

The biggest one is probably that builds take forever to start. This does seem to be tied to the metadata resource. I can queue a job, and it will take up to an hour to start waiting to satisfy that resource requirement, even though it is indicating it is present. I *really* wish there was a better way to tie build information to external processes. I fully understand, and agree with keeping state outside of the pipeline process, but being able to tie whatever that external event is to a specific iteration of a cci pipeline job is hugely beneficial in terms of trying to understand what is going on.

Second to this is kind of general performance related. There seems to be some kind of ceiling of 256 containers per worker. All 15 workers seem to live around this point. Is there a garden setting that we can pass in to exceed this? 

![image](https://user-images.githubusercontent.com/37888/68094627-168e7700-fe68-11e9-970d-e5967c8b0e89.png)

Our workers are incredibly untaxed, at around 10% average cpu, and 5% of their 64G mem in use. Assuming that each resource does require its own container in addition to running tasks, this means that we do not have the ability to keep all the resources present(256*15=3,840). I think this contributes to the very high network usage we see still 70MiBs/s, as repository resources are continually being cycled out and have to be retrieved again. Please let me know if I'm misunderstanding how this works.

I would prefer not to run more instances, and would like to stack more work on these if possible. Mostly because there is a tangible cost to more instances as we have to pay for additional monitoring licenses per instance.

Another issue is that despite jobs running, and processing, our tasks metric always looks like this:

![image](https://user-images.githubusercontent.com/37888/68094849-14c5b300-fe6a-11e9-8a12-140ae0e38bf4.png)

Any ideas why this might be the case?

On the topic of metrics, is there some way to exclude classes of metrics? In our case the metrics that are put out per pipeline, or per build create in excess of 10,000 metrics. We filter these out, but due to the size,  the web node sometimes has difficulty returning the metrics in a timely fashion. If there isn't, I guess a feature request would be in order. There is still some relevant information we would like to capture in terms of at least aggregates for those measurements even though we can't use each on individually.

**Comment by dnd** [comment]
More specifically on the metrics front, concourse is outputting 53,000 metrics per request.

**Comment by kcmannem** [comment]
@dnd I think your tasks metric only emits stuff if you use the `limit-active-tasks` strategy.

I'm really surprised that `CONCOURSE_GARDEN_DEFAULT_GRACE_TIME` was set. It wasn't even on my mind. I hope this makes your issue go away.

I'd tread carefully around increasing the garden subnet pool. We've seen workers fall over when theres too many containers on them.

**Comment by dnd** [comment]
@kcmannem That's kind of a bummer about only getting task counts if that flag is set. I feel like it's a potentially interesting metric, at least to gauge what's going on.

The grace time setting has definitely made the unknown handle error go away.

So far no issues increasing the subnet pool. The workers appear to be doing just fine, but as I mentioned there seems to be something preventing them from going above 256 containers per host. I would really like to find a way to get more containers on each node if possible so that I can run fewer nodes. At present it costs me an extra $450 per node that I run to have metrics enabled.

I ran the sql query you requested, and got a count of `5791`. Is that inline with what you were expecting?

@cirocosta any thoughts on the metrics question? We're at the point of having to write something to stand in front of concourse to filter metrics so that they can be sanely ingested.

**Comment by kcmannem** [comment]
@dnd You can definitely set the the container limit to be higher that 250. This is a setting you'd have to pass to garden. However we have seen reduced stability the more containers you have on your system. @cirocosta also did a experiment that as you make more containers on a host, the more exhaustive each process in the container becomes (something to with exponential linux scheduling constraints?). I'd test it out with your workloads to see if this works for you. 

If your using bosh, here's the parameter to set https://github.com/concourse/concourse-bosh-release/blob/master/jobs/worker/spec#L207

**Comment by dnd** [comment]
Thanks @kcmannem I will experiment with that setting.

I have 18 workers at present which should mean a max of 4500 container. So I am somehow over by 1291?
