### ISSUE TITLE
`fly login -b` redirects to 400 page

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4572]
## Bug Report

I think fly opens the wrong URL when the `-b` flag is passed to the `login` subcommand.

## Steps to Reproduce

1. `$ fly -t ci login -c https://ci.concourse-ci.org -b`
1. do normal browser stuff to log in

## Expected Results

browser show fly success page

## Actual Results

in chrome:
![Screen Shot 2019-10-07 at 11 01 59 AM](https://user-images.githubusercontent.com/22056320/66323529-eba91580-e8f1-11e9-8dcb-45fcb40509cb.png)
URL bar says `https://ci.concourse-ci.org/sky/callback?code=<code>&state=<a jwt?>`.

## Additional Context

I think this could have broken around the time we changed the parameters to the `/login` page?

## Version Info

* Concourse version: 5.6.0 - prod
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: gcp
* Browser (if applicable): chrome
* Did this used to work? yes

**Comment by xtremerui** [comment]
While I logged in with GIthub and use `fly -t ci login -c https://ci.concourse-ci.org -b` I see login successful page. I think the 400 page happens when user is not authorized, which is something known to core/api.

I gonna update the issue accordingly. Thx!

**Comment by xtremerui** [comment]
Once we have https://github.com/concourse/concourse/issues/2936 then the concoures token issuing job will be handled in concourse accessor, not in skymarshal anymore. By then we could have a proper way to handle the callback error.
