### ISSUE TITLE
Misleading errors when ca_certs config is incorrect for an image_resource

### ISSUE THREAD

**Issue by tprobinson** [concourse/concourse#4576]
## Bug Report

When I had an incorrect configuration for the `ca_certs` key in my `image_resource`, Concourse returned the following:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest for image '<my-registry>/alpine:latest': 503 Service Unavailable
does the image exist?
```
This is a misleading error, which I unfortunately lost a fair bit of time to trying to figure out.

## Steps to Reproduce

* Create a pipeline using an `image_resource` with a configuration like the following:
```yaml
image_resource:
  type: docker-image
  source:
    repository: <something>
    ca_certs:
    - cert: <a certificate that does not match the registry>
      domain: <registry domain>
```

* Set the pipeline
* Try to run the pipeline

## Expected Results

I expect to receive an error that says something about failing SSL verification.

## Actual Results

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest for image '<my-registry>/alpine:latest': 503 Service Unavailable
does the image exist?
```

## Version Info

* Concourse version: 5.6.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Infrastructure
* Did this used to work? Unknown

**Comment by xtremerui** [comment]
Hi, I believe this bug is actually from https://github.com/concourse/docker-image-resource, could you submit there?

While there might be a case that it won't be in top priority list, you could consider using https://github.com/concourse/registry-image-resource, which I think has better error handling regarding of misconfigure certs. Thx!

**Comment by skreddy6673** [comment]
Hi there,
Any update on this? We are using v5.4.1 and we are seeing this alot in the last week. Any workaround will be great.

**Comment by tprobinson** [comment]
Oops, sorry I lost track of this. I've moved this issue over to concourse/docker-image-resource#283.
