### ISSUE TITLE
Personal Pipelines

### ISSUE THREAD

**Issue by mvdkleijn** [concourse/concourse#4585]
**What challenge are you facing?**

I'm using Concourse to run some simple personal pipelines apart from pipelines for our team or those of other teams. For example, I'm running a pipeline that checks a git repo with HTML presentations (reveal.js) and pushes them to a Cloudfoundry install so users can view the latest version.

Since Concourse is only about teams, the pipelines end up on the level of my team. This creates confusion and clutter.

**What would make this better?**

My suggestion would be to have a virtual team of "me" that you can set a (possibly limited?) amount of pipelines on. This would de-clutter the team level and still allow for longer running experiments, personal pipelines of various kind, etc.

There are multiple precedents for the idea, for example in the form of personal git repositories.

**Are you interested in implementing this yourself?**

Unfortunately, this is probably beyond my capabilities in both knowledge and time. If I had more time, I could work on the associated learning curve and do this myself but sadly not an option for me at this time.

> What would determine if a user is able to do this? Currently you can only log in if you're part of a Concourse team, which doesn't necessarily imply that you can create your own pipelines independent of that team.

My initial thought would center around two simple options which could be used separately from each other:

1. A general setting: `enable_personal_pipelines` (boolean) or something to that effect.
    This would allow anyone who is able to login (fyi - we use an oauth server) to use personal pipelines with their virtual team called "me". (for example)

2. A more specific setting: `groups_allowing_personal_pipelines` (string or array) in the config.
    This would allow the admin to specify one or more groups whose members are allowed to use personal pipelines.

This second option is very similar to what we are doing now by limiting who belongs to a certain team with the set-team fly command: ```fly -t main set-team -n mywonderfullteam --oauth-group mywonderfullgroup```

**On the topic of creation and cleanup**

The system could create a new personal "team" named the same as the username, similar to how to can talk to yourself in Slack. :smile: 

Of course, if a user doesn't login for a long time, personal pipelines would clutter the system. To prevent this, admins could maybe set an "auto-expire time" that deletes a pipeline after a set amount of time of not having logged in.

See #3021

**Comment by vito** [comment]
gonna just re-open #3021 instead
