### ISSUE TITLE
Why is concourse linux download 1G?

### ISSUE THREAD

**Issue by drnic** [concourse/concourse#4586]
https://github.com/concourse/concourse/releases

<img width="840" alt="image" src="https://user-images.githubusercontent.com/108/66496385-7586e900-ea80-11e9-969d-6e9e4a2233ef.png">

Why is the linux download 1G?

**Comment by vito** [comment]
It's all the core resource types that we still bundle with the Linux distribution. We're planning to shrink it down. See concourse/rfcs#30.

**Comment by vito** [comment]
I can reopen since it does seem like the size went up a bit more even considering that. :thinking:

**Comment by cirocosta** [comment]
eeeerp we (very likely, me) definitely messed up:

```
 /tmp/560 $ tar xvzf ./concourse-5.6.0-linux-amd64.tgz ./concourse/resource-types/cf/rootfs.tgz
x concourse/resource-types/cf/rootfs.tgz
 /tmp/560 $ tar xvzf ./concourse/resource-types/cf/rootfs.tgz ./usr/lib/os-release
x ./usr/lib/os-release
 /tmp/560 $ cat ./usr/lib/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

that should be alpine

**Comment by xtremerui** [comment]
should this be something that needs to be fix by RelEng? @cirocosta @pivotal-jamie-klassen

**Comment by xtreme-sameer-vohra** [comment]
Going to the distroless is definitely going to be great for reducing size and attack surface vector. 

We should also think about how we go about `debugging`, potentially publishing a `debug` version alongside which would include other utils we deem useful would be something we also consider.

**Comment by taylorsilva** [comment]
I still want to fix this

**Comment by camelpunch** [comment]
Yeah I still want you to.

**Comment by pivotal-jamie-klassen** [comment]
Looks like RCs since 51a7cef83be3f7817e3b220d4b8a54dc3df3d0a2 have had ~600MB size instead of ~1GB https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/build-rc/builds/67. Nice!
