### ISSUE TITLE
Fly login fails with x509 error if user is admin and --ca-cert was previously specified but not on this run

### ISSUE THREAD

**Issue by thomasmitchell** [concourse/concourse#4587]
## Bug Report

After handing over the sign-in token to fly login, if the user is an admin, a request is made to the retrieve the list of teams:
https://github.com/concourse/concourse/blob/320087838bc684fce67360078463ff89e32900d8/fly/commands/login.go#L140

However, this request is not made with the client used to handle the earlier `info` endpoint call, because this call requires authentication. While the unauthenticated client will retrieve the ca certificate from the `.flyrc` if not specified on the command line and use that, this standalone call uses the `caCert` variable, which is only populated from the command line flag. This leads to the desired ca certificate not being used, and as a result: `x509: certificate signed by unknown authority`

## Steps to Reproduce

1. Serve a non-system-trusted certificate from the Concourse ATC
2. Log in with fly as an admin user using the `--ca-cert` to specify the parent certificate.
3. Log in with fly again as the same user, but do not specify `--ca-cert`

## Expected Results

It should have used the cached CA cert for all requests.

## Actual Results

It did not use the cached CA cert for one of the requests.

## Version Info

* Concourse version: 5.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Azure
* Browser (if applicable): n/a
* Did this used to work? I think this used to work before the dex auth rework.

**Comment by pivotal-bin-ju** [comment]
Hi @thomasmitchell ,
Sorry for the late reply.

as your step 3:
> 3. Log in with fly again as the same user, but do not specify --ca-cert

Have you tried it *WITHOUT* parameter `-c`?  e.g.:
```bash
fly -t YOUR-TARGET -u USERNAME -p PASSWORD -n TEAM-NAME
```

*WITHOUT* atc url, `fly` goes to this branch:
https://github.com/concourse/concourse/blob/77489bce14821733c9667c1c5fe64433e0dd4a4e/fly/commands/login.go#L67

And then call function `rc.LoadUnauthenticatedTarget`.
You can see the `cert` is loaded from `.flyrc` at the line below:
https://github.com/concourse/concourse/blob/77489bce14821733c9667c1c5fe64433e0dd4a4e/fly/rc/target.go#L154

This happens before hitting the line:
https://github.com/concourse/concourse/blob/320087838bc684fce67360078463ff89e32900d8/fly/commands/login.go#L140
as you mentioned.

So I suggest you try the second logion without `-c` (the atc url).

Any questions please let me know.

**Comment by thomasmitchell** [comment]
It _does_ get set in LoadUnauthenticatedTarget, but only for the scope of that function. The original value of caCert remains unset in `LoginCommand.Execute` and also remains potentially unset throughout `adminCheckTeamExists`.

**Comment by pivotal-bin-ju** [comment]
Do you mean when the first time you logged in the cert is not saved in .flyrc?
When you successfully logged in it should be saved at line: https://github.com/concourse/concourse/blob/5348f18df26b956c2db4e962fdcc2d3996e9f955/fly/commands/login.go#L149

Do you mean you could not pass the authentication from the line: 
https://github.com/concourse/concourse/blob/5348f18df26b956c2db4e962fdcc2d3996e9f955/fly/commands/login.go#L121-L123
?

or at line:
https://github.com/concourse/concourse/blob/5348f18df26b956c2db4e962fdcc2d3996e9f955/fly/commands/login.go#L140
we should use target.CACert()
```
err = command.adminCheckTeamExists(target.URL(), tokenType, tokenValue, target.CACert()) 
```
because it is loaded from `.flyrc` at the line:
https://github.com/concourse/concourse/blob/77489bce14821733c9667c1c5fe64433e0dd4a4e/fly/rc/target.go#L154

**Comment by thomasmitchell** [comment]
The CA cert is saved to the `.flyrc`. 

`target.CACert()` looks like it should work!

**Comment by pivotal-bin-ju** [comment]
The  PR #4879  has been created for this issue.
