### ISSUE TITLE
web: add re-run button to build page

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4589]
Before committing to the layout change proposed by @Lindsayauchin in #4222, let's first add the button at the right-hand side for non-running builds. This means that you will always see two buttons on the right-hand side of the build header, the leftmost of which will either be an abort button or a re-run button, depending on whether or not the current build is running.

In the happy path, clicking the button will send a POST request to the API route corresponding to the current build.

For now, assume this button behaves similarly to the abort button: it always appears clickable, and if the associated API call returns a 401 the browser redirects to login, and 403s are swallowed.

The icon on this button should be https://github.com/concourse/concourse/files/3498560/re-trigger_bttn.svg.zip, and the button's background color should match the status of the current build.

Later iterations may involve a two-click rerunning flow, but for now the click will just directly re-run. Let's think about a tooltip that describes what this button does in words - maybe "re-run with the same inputs"

**Comment by pivotal-jamie-klassen** [comment]
Mentioning here for posterity that the re-run button should not appear on the one-off build page, and that its appearance impacts the appearance of the 'manual triggering disabled in job config' tooltip.

**Comment by pivotal-jamie-klassen** [comment]
re-run build should insert into the build history tabs in the same place that the API will return it from the ListBuilds endpoint

**Comment by pivotal-jamie-klassen** [comment]
When implementing this feature, we noticed a surprising behaviour of the UI - now the sort order of builds is not necessarily chronological. That is to say that the build that ran most recently is not necessarily the last build in the history list. We found this a bit jarring when clicking on a job from the dashboard, for example. The build page that loads can be somewhere in the middle of the history (if the _most recent_ build was a rerun).

The API response payload for a job includes a `finished_build` field, which, at this point, always shows the _most recent_ finished build, rather than the _last_ build according to the history sort order. Is this wrong? Does it make sense to consider a job to be 'failing' if an older rerun failed after the 'last' build succeeded? @vito @clarafu @Lindsayauchin @matthewpereira

**Comment by vito** [comment]
Yeah we should fix that. Finished_build shouldn't be updated by reruns of an older build.

**Comment by pivotal-jamie-klassen** [comment]
While we're on the topic, we also did the experiment of rerunning an aborted build:
![Screen Shot 2019-10-17 at 3 28 59 PM](https://user-images.githubusercontent.com/22056320/67041113-ecf8f000-f0f2-11e9-9773-139c74dfa6c3.png)
and it sure looks like the rerun stays pending forever:
![Screen Shot 2019-10-17 at 3 29 07 PM](https://user-images.githubusercontent.com/22056320/67041123-f2563a80-f0f2-11e9-8b65-05e1616f9deb.png)
If we're gonna prevent rerunning cancelled builds, we can certainly hide the rerun button on them but the API should obviously enforce it too.

**Comment by vito** [comment]
@pivotal-jamie-klassen An aborted build should be able to be re-run, just not if it was aborted before its inputs have been determined (i.e. aborted while 'pending'). Not sure how we should express that technical detail. :thinking:

**Comment by pivotal-jamie-klassen** [comment]
that's what "cancelled" means to me, in contrast to "aborted".

**Comment by clarafu** [comment]
@pivotal-jamie-klassen Good catch!! I think builds that doesn't have their inputs determined yet shouldn't be allowed to be rerun. We can add a quick check for that in the API.

**Comment by pivotal-jamie-klassen** [comment]
I haven't thoroughly tested it, but on my local instance it looks like all scheduling died after i queued up those reruns
