### ISSUE TITLE
web: simplify resource page pagination

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4595]
As discussed [here](https://github.com/concourse/concourse/pull/4588#issuecomment-540635963), the resource page behaves in a few surprising ways with regards to version pagination. Let's propose something simpler here. In an ideal world there are two main user stories:
1. When I am looking at the resource page with no particular URL query parameters, I want to always up to 100 of the latest versions, and when the page autorefreshes I want new versions to flow in, potentially pushing down or causing older versions to disappear.
2. When I am looking at a specific page of versions (by visiting a URL with query parameters or by clicking the pagination chevrons), I expect the current URL to always show the exact same list of versions that I'm currently looking at.

As it stands we have two realities that make 2. above impossible: We specify pagination by anchoring the beginning or end of the page at a specific version id together with the page size, and the underlying list of versions can re-order depending on what gets returned from checks (@clarafu implemented this behaviour around the time global resources were introduced, as I recall).

The simplest proposal we can think to make right now would be not to have "permanent" pagination -- if you want to visit a specific page of versions you have to click your way there every time and the `since`, `until`, `from`, `to`, and `limit` query parameters to the resource page URL go away.

**Comment by vito** [comment]
> and the underlying list of versions can re-order depending on what gets returned from checks (@clarafu implemented this behaviour around the time global resources were introduced, as I recall).

I don't think we should focus on this aspect when designing the UX as it's not a behavior we *expect* of resources. They're meant to have an immutable, stable ordering, so I don't think it's wrong for our UI to reflect that assumption.

I don't feel strongly about the rest, I just want to make sure our motivations are coming from the right place. :slightly_smiling_face:
