### ISSUE TITLE
Unable to trigger job based on another job failure

### ISSUE THREAD

**Issue by Nopik** [concourse/concourse#46]
For example, having single job sending out notifications about failures (e.g. `put` on hypothetical email-sending-resource) is not possible now. If failure could trigger some job, it should be possible to add some 'notify-about-fail' job to the pipeline and hook it up such way that any other failing job would trigger notification.

**Comment by mariash** [comment]
@Nopik there is https://concourse.ci/on-failure-step.html that might do what you need.

**Comment by friegger** [comment]
@mariash The `on_failure` step works of course, but given a bigger pipeline, one might want to declare `on_failure` on a job level instead. Besides avoiding duplication when many tasks have the same attributes, this seems to be the right place for notifications. When a job fails it's usually not relevant for the notification itself, which specific task failed.

Other (probably out of scope) ideas:
- A global `default` section which is applied to all tasks and/or get/put steps. This would be a generally useful feature as things like `tags` are often used throughout the pipeline:
```yaml
defaults:
  tasks:
    on_failure: ...
  put:
    tags: ['x']
```
- A global on_failure definition for a complete pipeline run, thus a single event containing a summary of all job results/failures. Although, it seems, there is not such a thing as 'a pipeline run'.

**Comment by jadekler** [comment]
+1 this feature would be nice. As an extra note, a way to distinguish this relationship would be nice - maybe a dotted line, or something like that?

**Comment by JohannesRudolph** [comment]
I think this is partly addressed in v2.4 which adds job-level `on_success` and `on_failure`

**Comment by vito** [comment]
Not really; that's just syntactic sugar so you don't have to wrap the whole `plan` in a `do` step.

**Comment by vito** [comment]
I don't really like the idea of "left to right" in the pipeline view meaning anything but successful progression.

I'm gonna close this since it's a "no" to the initial proposal, but a more open-ended issue covering the root of the desire (i.e. notifications/push to Slack channels/etc) may be worth having to re-open the discussion from a fresh viewpoint.
