### ISSUE TITLE
How to use concourse fly command in server side

### ISSUE THREAD

**Issue by sohu234** [concourse/concourse#4619]
Hi,
In my case,I need to  integrate concourse with my system. We know concourse have not RESTful API (eg: login),so we have to use fly command for login.But Concourse fly command is a local interactive command,it does not be used  in remote shell. How can i do ? thank you very much.

**Comment by pivotal-jamie-klassen** [comment]
You've already commented on #1116 so I kinda think this is more of a support request, and thus better suited to the [forum](https://discuss.concourse-ci.org), where there have been some (not very exhaustive) discussions, or [Discord](https://discord.gg/MeRxXKW).

It's a known pain point, but the core team is pretty occupied with other priorities at the moment. I have seen a few approaches to automating interactions with the Concourse API - myself, I once wrote a script that used the Python `requests` library to headlessly log in to my auth provider (CF UAA) and recover a token from the resulting cookies, automatically pasting it into the stdin stream of the fly process. Depending on what you mean by

> fly command is a local interactive command,it does not be used in remote shell

if your system has any components written in go you could depend on the code in [go-concourse](https://github.com/concourse/concourse/tree/master/go-concourse).
