### ISSUE TITLE
Notify committer of build outcome

### ISSUE THREAD

**Issue by glyn** [concourse/concourse#462]
One project I work on wants to notify the committer of a commit which triggered a failing (or a successful) build. It's tricky to implement this without explicit support from Concourse because it is not possible in general to determine which resource(s) triggered a build. Indeed, Concourse is designed so that such _ephemeral_ information is not available and therefore cannot influence the behaviour of the pipeline.

So there needs to be a way of determining the relevant committer(s!) and, perhaps separately, of notifying them (via email, slack DM, etc.). These aspects might need to be implemented separately with some sort of abstraction of a user passed between them, for example.

Discussion in slack channel: https://concourseci.slack.com/archives/general/p1465305093000341

**Comment by jama-pivotal** [comment]
Hi @glyn , I'm going to close this issue in favor of #1052 , which is a proposal to incorporate notifications into the pipeline definition to replace the current pattern of using something like a Slack resource.
