### ISSUE TITLE
fly execute sometimes returns 500 error when loading an input directory containing a terraform state file

### ISSUE THREAD

**Issue by simonxca** [concourse/concourse#4621]
## Bug Report

We were trying to run `fly execute -i terraform-state-file=$TERRAFORM_PATH` and we receive 500 errors around 80% of the time because it fails to upload the input directory. The other 20% of the time, the input directory uploads successfully.

## Steps to Reproduce

1. Run Concourse on Kubernetes.

1. Deploy Ops Manager on AWS  using terraform by following the instructions here: https://docs.pivotal.io/pivotalcf/2-6/om/aws/prepare-env-terraform.html

1. After deploying Ops Manager, you should end up with a `terraform.tfstate` file.

1. Put this `terraform.tfstate` file in an empty directory.

1. Use this directory as an input into a Concourse task (for example, name it `terraform-state-file`).

1. Run `fly execute -i terraform-state-file=$PATH_TO_DIRECTORY_ABOVE`.

## Expected Results

Input directory should upload successfully and say "Done".

## Actual Results

Uploading fails 80% of the time with 500 error.

## Additional Context

Does not happen with Bosh-deployed Concourse, error only occurs with Kubernetes-deployed Concourse.

We found a workaround for this issue. By creating a copy of the input directory inside the input directory, it uploads successfully 100% of the time. More specifically:

This **doesn't work**:
```
terraform-state-file/
|-- terraform.tfstate
```

This **does work**:
```
terraform-state-file/
|-- terraform.tfstate
|-- terraform-state-file/
    |-- terraform.tfstate
```

## Version Info

* Concourse version: 5.6.0
* Deployment type (BOSH/Docker/binary): Kubernetes (Helm)
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Not sure.

**Comment by xtremerui** [comment]
Could you provide the problematic terraform.tfstate? It seems a bit too much to do step 2 for reproducing this issue if the source of problem is the tfstate file and k8s concourse.

**Comment by xtremerui** [comment]
Also when you see the 500 error do you have access to concourse logs so you could grap the detail error message?

**Comment by simonxca** [comment]
Sure we can do that.

**Comment by antonyoneill** [comment]
Hey guys, I've just fallen foul of this same issue.

Initially I saw it while uploading a git repo as an input to a job and have since managed to narrow it down to a reproducible example:

```bash
#!/usr/bin/env bash

# Navigate to a temporary dir
mkdir tmp-4621
(
cd tmp-4621

# Write dummy task file
cat << EOF > task.yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: "10"

inputs:
- name: source

run:
  path: bash
  args:
    - -c
    - |-
      echo "Hello World"
EOF

# Generate large file
truncate -s 128k 128k_file

# Fly execute
fly --target ci execute --config ./task.yaml --input source=.
)

rm -rf ./tmp-4621
```

Output:
```
uploading source ⠸ (697b/s)
error: 'uploading source' failed: Unexpected Response
Status: 500 Internal Server Error
Body:
```

Output using a 100kb file instead:
```
uploading source done
executing build 1 at https://my-concourse/builds/1
initializing
running bash -c echo "Hello World"
Hello World
succeeded
```

The only interesting log entry from the atc during the large file upload:
```
{"timestamp":"2019-11-21T12:23:46.072574964Z","level":"error","source":"atc","message":"atc.create-artifact.failed-to-stream-volume-contents","data":{"error":"failed to stream in to volume","session":"48445"}}
```

Hope this helps to reproduce and resolve

**Comment by camelpunch** [comment]
(we run ATC in a k8s cluster, workers in separate VMs)

**Comment by vito** [comment]
Seeing this myself. Definitely seems related to the payload somehow. The other end of the '500' error is Baggageclaim logging `baggageclaim.api.volume-server.stream-in.bad-stream-payload`. The message isn't very helpful though, just says `exit status 2`.

**Comment by pivotal-jamie-klassen** [comment]
wise observation from @kcmannem https://github.com/concourse/ci/issues/221#issuecomment-559886396

**Comment by kcmannem** [comment]
@vito if you have a consistent file failing for fly exec. We can use the zstd cli to pack and unpack it to make sure it can encode/decode successfully. I can also check using the zstb lib we use as a dependency.

**Comment by zoetian** [comment]
It seems like having vim swap file in the directory can cause this problem as well.

**Comment by kcmannem** [comment]
is it a specific permission or file attribute that causes this?

**Comment by vito** [comment]
@kcmannem Have you tried the repro in https://github.com/concourse/concourse/issues/4621#issuecomment-557085786 ?

**Comment by kcmannem** [comment]
@antonyoneill thanks for the reproducible steps, I can confirm its payload related. I haven't quite figured out if its some magical byte pattern that causes this to fail or some file attributes. I notice that as soon as I add a file with actual content (non zero byte filled), the fly execute will start working again. I'll try to dig more and follow up with this issue on the info I come across.

**Comment by kcmannem** [comment]
Theres a race condition in the upload code for fly execute. This existed prior to the implementation of zstd encoding. And might have happened more often.

https://github.com/concourse/concourse/blob/master/fly/commands/internal/executehelpers/uploads.go#L16-L26

This function spawns a go routine to write zstd/tar encoded payload to a pipe. However, the function may return before everything is actually written to the pipe.
I added a simple sleep for 10s and fly exec started working again with the the repro given by @antonyoneill 

```
func Upload(bar *mpb.Bar, team concourse.Team, path string, includeIgnored bool, platform string) (atc.WorkerArtifact, error) {
	files := getFiles(path, includeIgnored)

	archiveStream, archiveWriter := io.Pipe()

	go func() {
		err := archiveWriter.CloseWithError(tarfs.Compress(zstd.NewWriter(archiveWriter), path, files...))
	}()

	time.Sleep(10*time.Second)
	return team.CreateArtifact(bar.ProxyReader(archiveStream), platform)
}
```


cc @concourse/runtime

**Comment by kcmannem** [comment]
adding context, still haven't determined why we aren't transmitting the full payload. Additional logging shows tar is erring out which means that zstd has already parsed the payload and passed it onto the tar binary. 
```
web_1     | this the body &{0xc000a367b0 0xc0006c5800 0xc0001f8600 false true {0 0} false false false 0x15df670}
worker_1  | tar: Unexpected EOF in archive
worker_1  | tar: Unexpected EOF in archive
worker_1  | tar: Error is not recoverable: exiting now
worker_1  | {"timestamp":"2020-01-14T16:00:25.540020200Z","level":"info","source":"baggageclaim","message":"baggageclaim.api.volume-server.stream-in.bad-stream-payload","data":{"error":"exit status 2","session":"3.1.8","volume":"2da5e2e4-28cd-4609-64e4-3fd8050ec8fa"}}
```

**Comment by kcmannem** [comment]
the datadog/zstd library was giving us problems, so we are going to switch over to https://github.com/klauspost/compress which is written in pure go and works for this edgecase.

**Comment by kcmannem** [comment]
i really haven't been able to repro the case where sleeping will actually make fly execute work on another machine. It only happend on that single machine...

The new library seems to work fine with this case. As there is no possible way for validate every edge case, why don't we just leave this issue open for a while after release and see if everyones previously failing uploads work again.

**Comment by pivotal-jamie-klassen** [comment]
+1 to dogfooding on k8s deployments - this is a such a weird and intermittent issue...

**Comment by antonyoneill** [comment]
Thanks for sorting this out @kcmannem
