### ISSUE TITLE
Spin up containerd daemon on worker node with existing process management conventions

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4627]
In our spike branch containing the `containerd` work, the `containerd` process is kicked off by the Dockerfile which won't work in prod 😄 

Investigate:

- [x] Using `ifrit` or similar process manager on workers
- [ ] What minimum system requirements should we enforce, to guarantee that we can access the `containerd` feature we'll need, such as snapshotting
- [ ] Explore portability of the containerd/runc binary (previous issues faced with missing libraries)
- [ ] How will those system features differ across Linux/Windows/Darwin?

**Comment by cirocosta** [comment]
> Using ifrit or similar process manager on workers

The current implementation (introduced in __) can be found here:

https://github.com/concourse/concourse/blob/f31c222b485bbccf1f988068155996c702c1a796/worker/workercmd/containerd.go#L67-L78

It brings up `containerd` as a separate `ifrit` "process", which takes care of the lifecycle of `containerd`, and then a separate `ifrit` process takes care of the garden backend (our implementation that's backed by `containerd`).

It currently uses the same pattern as the `BeaconRunner`

https://github.com/concourse/concourse/blob/f31c222b485bbccf1f988068155996c702c1a796/worker/beacon_runner.go#L43-L50

with the difference that our backend can currently restart indefinitely (something we could improve soon to perhaps limit restarts based on a time window).

**Comment by cirocosta** [comment]
Hey,

I'll close this one in favor of [Figure out our new minimum requirements with `containerd` ](https://github.com/concourse/concourse/issues/4358) as we already covered what the title says, and the rest of the body (checklist) is covered in #4358. 

Thanks!
