### ISSUE TITLE
feature request: auto self reset pipeline

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4634]
## What challenge are you facing?

When comparing concourse with other CI/CD tools, like GitLab CI/CD, when pipeline itself has some change, then user has to re-`set-pipeline` manually. 

## What would make this better?

Most likely user will store pipeline yml file itself in SCM, e.g. `git`, as well. So I'm proposing a solution like the following.

1. Add a section to pipeline yaml file, like:

       resource:
       - name: pipeline-code-repo
          type: git
          config: 
       job:
       - name: auto-reset-pipeline
         plan:
          - get: pipeline-code-repo
             trigger: true
          - reset
             main: pipeline-code-repo/my-pipeline.yml
             vars:
                  a: b
                  c: d
             var_files:
                  - pipeline-code-repo/var1.yml
                  - http://mycompany.com/chaol/var2.yml
           - put: slack
              params: 
                  msg: "pipeline is reset successfully"

In this proposal, we add a job that contains a new step, called `reset`. This job can be triggered as a normal job, either by `get` or by manual. The `reset` step takes all necessary parameters, like the main yaml file, variables and variable files. Once the job is triggered, it reset the pipeline itself.

With this enhancement, most of users will no longer need to manually reset pipeline, which would be a revolution to Concourse.

## Are you interested in implementing this yourself?

Yes.

**Comment by vito** [comment]
Ehh this sounds a *lot* like Projects (concourse/rfcs#32) - closing to focus the conversation there.

**Comment by evanchaoli** [comment]
@vito 

Will `set_pipeline` step support self reset? With self reset, meaning that `pipeline name` no need to set, because a step knows its pipeline name already.

Also, is there any plan and ETA for `project`?

**Comment by vito** [comment]
@evanchaoli `set_pipeline` doesn't self-set, it would typically be used within a project to set the project's own pipelines. It could of course be used anywhere and also set its own pipeline, but it does need a specific name to be given. If you'd like to dig in to that aspect, the `set_pipeline` RFC would be the appropriate place!

No ETA for projects yet, but it's on our [roadmap](https://project.concourse-ci.org/projects). We're still wrapping up our pipeline/resource scheduling rewrites (Algorithm v3 and Chequeue), after which I plan to finalize each of the v10 RFCs. Once that's done, theoretically anyone on the community could start to implement each epic in parallel, as the design and details are all fleshed out in the public. That could be an X-factor in having it delivered sooner - but it's also why it's hard to give a good ETA.

**Comment by evanchaoli** [comment]
@vito Let's move the discussion to the RFC.
