### ISSUE TITLE
Pool resource possible race conditions with multiple pipelines erroring out

### ISSUE THREAD

**Issue by freelock** [concourse/concourse#464]
Hi,

My setup: 
- 1.3.0 binaries (rc.85).
- ATC on Ubuntu 16.04, on Google Cloud Engine
- Untagged worker on Ubuntu 16.04 on GCE, different host
- Tagged worker on Ubuntu 14.04, on LAN
- Gitolite server/Docker registry on EC2

Pipelines:
- Parameterized pipeline that is identical outside of parameters that specify different project repos. They all share the same support resources -- git repos for the pipelines and scripts, another for mapping aliases to different servers, S3 resources for test artifacts/semver per pipeline, and a pool resource backed by a git repository on our gitolite server.
- Nightly resource set to start at 12:00am and end at 03:00am, that triggers 3 jobs in each pipeline. These jobs use shell/ssh scripts to go run various commands on several different servers (to check whether environments are clean, notify of anomolies, etc)
- Pool resource has a single lock available in a "deploy" pool

Last night, there were 18 pipelines active, so 54 jobs got triggered soon after 12:00am. These jobs all ran as expected, one at a time, until approximately 12:37, when a bunch of jobs that were waiting to acquire the lock started failing:

![selection_215](https://cloud.githubusercontent.com/assets/46937/15870296/a6fdecf6-2ca4-11e6-84ea-558da1a5c277.png)

![selection_216](https://cloud.githubusercontent.com/assets/46937/15870340/d4ef7102-2ca4-11e6-9e41-5c42c5905837.png)

... something like 18 jobs failed with one or two of those messages over the next 10 minutes.

Then, an hour later, more jobs failed with a different error:

![selection_217](https://cloud.githubusercontent.com/assets/46937/15870513/605cffa2-2ca5-11e6-8e4b-1f3068b1f29f.png)

All told, somewhere around 24 of the jobs errored out with one of those 3 errors -- the rest ran successfully. Overall it took 2 hours and 8 minutes for the 30 jobs that did successfully acquire a lock to run.

We've had issues with every night's run, but many of them seemed to go away after upgrading our git server, moving the ATC to a dedicated box with more RAM, and upgrading the ATC and untagged worker from Ubuntu 14.04 to 16.04 and configuring them to run under systemd. But still, we're erroring out on 1/3 of the jobs just trying to acquire a lock from the pool.

**Comment by mariash** [comment]
same as https://github.com/concourse/pool-resource/issues/25

**Comment by vito** [comment]
closing as a dupe as mentioned above
