### ISSUE TITLE
Main Page Loads Slowly when logging in as Admin

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [concourse/concourse#4646]
## Bug Report

Given a concourse installation with many pipelines, when I log-in as `admin` user, it takes around 30 seconds to load the main concourse page. 
I can see that HTTP calls for `pipelines`, `resources`, `teams`,  and `jobs` are very slow (around 30 seconds), where the response payload can be around 5 MB.
Since the UI calls these endpoints every 5 seconds, there is a lot of latency that happens in the UI , and it becomes unresponsive.

## Steps to Reproduce

Log-in as `admin` to a concourse deployment that has hundreds of pipelines and teams.

## Expected Results

The main concourse page to load more efficiently. One idea could be to have an option to specify the team for which you want to see the pipelines for after you log in. So:
1- Login ad `admin`
2- See all the teams in a list
3- Choose the team I want to see the pipelines for.

## Actual Results

The main concourse page loads very slowly, and it becomes unresponsive. 

## Version Info

* Concourse version: 5.5.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: N/A
* Browser (if applicable): Google Chrome

**Comment by pivotal-jamie-klassen** [comment]
related: #2776, #4482, #4372, #4552

**Comment by pivotal-jamil-shamy** [comment]
Hi, would it be possible to re-open this issue? It was closed by the bot due to inactivity, but I do not think the issue was resolved, yet.

Thanks
