### ISSUE TITLE
Timeout failures to provision containers

### ISSUE THREAD

**Issue by jvigil-pivotal** [concourse/concourse#4652]
## Bug Report

We are seeing many timeout failures to provision containers. Referring to issue #4562, we believe we are facing a similar problem. However, we're not sure that the fix for issue #4562 will address the timeout issue. If the timeout is set at a constant 5 minutes (https://github.com/concourse/concourse/blob/0e1b195bf964cf11e88c6cbd75775f5160cce1df/atc/config.go#L19), but we are still hitting the timeout, our containers will never successfully provision.

## Steps to Reproduce

We are using a fairly large container image (0.5Gb), with overlay storage_driver. Some of our tasks require privileged containers. Also, we are scheduling many containers at once (random placement strategy), but our concourse deployment has 5 large (16cpu, 60Gb memory) workers. In addition, we are only running one pipeline (50ish jobs) on this deployment. We are running Concourse 5.6.0. 

## Expected Results

Either faster container provisioning, or a configurable container provision timeout.

## Actual Results

Many jobs are orange with the error message: `Post http://127.0.0.1:8080/containers: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`. Also, our findings are consistent with the description in issue #4562.

## Version Info

* Concourse version: 5.6.0
* Deployment type: BOSH 
* Infrastructure/IaaS: GCP
* Did this used to work? yes, recently upgraded from 4 to 5.6.0

**Comment by joegit1344** [comment]
@vito Any assistance with this issue is greatly appreciated. We are severely impacted by this issue post v5.6.0 upgrade.

**Comment by kcmannem** [comment]
Whats the cadence of the error? Is it happening for every build. Also how many containers are on each of your workers on average? What are your builds doing? Are they CPU heavy?

you're right the fix we applied will not make things better for you. We'll need to increase the timeout to help out with this. But we need to figure out what the right value is. In our experimentation, it never took garden longer than 40s to make a container when we requested 250 containers to be created in parallel. if you go back to one of your previous builds that happened before the upgrade and hover over the check mark  for a  step that never exhibited the error. What is the initialization time?

**Comment by xtreme-sameer-vohra** [comment]
Hey @joegit1344 

Thank you for reporting the issue. If you could provide some of the information that @kcmannem  requested that would be very helpful in determining our course of action. Specifically, around is the timeout occurring because the combo of a large image + privileged + overlay driver and only for these cases or is it happening for all steps, which might point to another underlying issue.

We're certainly amenable to making the timeout configurable but want to ensure that doing so will not mask other systematic issues that could be resolved more directly.

**Comment by joegit1344** [comment]
Here's our info:

Symptom: After the build steps we have test job fan out. The problem appears to occur after quick succession of builds initiated through the pipeline.

Number of pipelines: 2 (The larger of the two is experiencing this issue.

Deployment Manifest info:
driver: overlay

We are seeing errors in various `get` steps errors (even for the builtin git resource).

Several jobs are being run with `privileged: true`. We have been tracking down product core files and this ability helps in analysis.

Images used:

```
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
pivotaldata/gpdb6-centos6-build       latest              3bf2fa9526a9        20 hours ago        1.49GB
pivotaldata/gpdb6-ubuntu18.04-build   latest              d9ab2a9f9f97        2 days ago          719MB
pivotaldata/gpdb6-centos7-build       latest              29c76de18544        2 days ago          1.43GB
pivotaldata/gpdb6-centos7-test        latest              4f30991c343b        2 days ago          1.28GB
pivotaldata/gpdb6-centos6-test        latest              afc50c990116        2 days ago          1.36GB
pivotaldata/gpdb6-ubuntu18.04-test    latest              2a1b9ab8ffc6        9 days ago          631MB
pivotaldata/ccp                       7                   ac50c4d61216        6 weeks ago         940MB
```

Workers (not necessarily overloaded):

```
name                                  containers  platform  tags  team  state    version  age
46fd67a0-953d-4315-9b08-82d3b294f0b1  52          linux     none  none  running  2.2      4d
75cd2f29-5fa7-4f8a-ab4f-845990434755  24          linux     none  none  running  2.2      4d
a72effb0-4c28-4fb9-9b5a-6cf436e43b42  56          linux     none  none  running  2.2      4d
d1758919-b88f-401e-bf6a-078d1f812d1b  66          linux     none  none  running  2.2      4d
da3691a0-cb45-4b9a-863a-6e36c53d9d99  48          linux     none  none  running  2.2      4d
```
