### ISSUE TITLE
RBAC is not working as expected 

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse#4654]
We are using concourse as Kubernetes based deployment using helm chart. Currently, we are in version 5.4.1.

I have enabled the rbac with version 5.4.1. My role definition looks like below,

```
roles:
- name: member
  github:
    teams: ["abcorg:abcteam"]
- name: admin
  local:
    users: ["admin_user"]
```
After running the set-team command along with the above role, the person who is not part of the specified GitHub team still able to see my concourse TEAM. Ideally, this should not be the case?

Another user from discord also mentioned the same issue:
interestingly I think I have the same problem. if I remove a local user I created from a team entirely, it can still see the team

I am part of the main team with owner permission.
```
➜  concourse git:(master) ✗ fly --target concourse get-team -n main
name/role   users                  groups
main/owner  local:admin_concourse  github:abcorg,github:abcorg:abcteam
```

As per this https://github.com/concourse/concourse/releases#v550-note-3 if someone part of main team with owner permission should able to see all the teams and access pipelines, jobs, resources, builds, etc for all teams right?

Can you confirm ?

BRs, Gowrisankar

**Comment by pivotal-jamie-klassen** [comment]
The thing that jumps out at me in your example is that `admin` is not a role that you can actually define per-team. Admin is just a term for `owner`s of the `main` team.

The next thing I wonder is, are you trying to remove somebody from this team? as in, they were a member and then you did `fly set-team`. In this case their team memberships won't be updated until they get a new token, either by waiting the default expiry period (24 hours I think) or by logging out and logging back in.

Finally you mentioned you are running 5.4.1, but you linked a 5.5.0 release note. Are you asking about whether you will see that behaviour when you upgrade, or whether you should expect to see it in 5.4.1?
