### ISSUE TITLE
Secret redaction incorrectly "redacts" empty string resulting in mangled logs.

### ISSUE THREAD

**Issue by YenTheFirst** [concourse/concourse#4656]
## Bug Report

When a secret in credential management contains an empty line, such as a trailing newline, and secrets redaction is enabled, a `((redacted))` is inserted between every character of the job log.

## Steps to Reproduce

1. Have a large multiline secret, such as a private RSA key, in credential management (such as Hashicorp Vault.
2. the secret should include a trailing newline.
3. configure concourse to use credential management, and configure a pipeline & job that references that secret
4. configure concourse to use secret redaction
5. Run the job.

## Expected Results

I expect the first lines of my particular job's output to be
```
waiting for docker
```

## Actual Results

Actual logged lines were 
```
((redacted))w((redacted))a((redacted))i((redacted))t((redacted))i((redacted))n((redacted))g((redacted)) ((redacted))f((redacted))o((redacted))r((redacted)) ((redacted))d((redacted))o((redacted))c((redacted))k((redacted))e((redacted))r((redacted))
```

## Additional Context

I manually removed the trailing newline from the affected secret, and re-ran the job, and the expected log output was output, so I'm fairly confident in the cause.

## Version Info

* Concourse version: 5.6.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Kubernetes
* Did this used to work? This is a bug in a new feature.

**Comment by evanchaoli** [comment]
I will take a look.

**Comment by esauser** [comment]
We are also having this same issue and can confirm that removing the trailing new line from a secret resolved the issue.

**Comment by vito** [comment]
Ha, that's a fun one. Thanks for the report!
