### ISSUE TITLE
When a new pipeline is configured it should start checking/scheduling within 10 seconds

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4662]
Currently we trigger a full LIDAR scan when a new pipeline is configured, but this causes a lot of extra load. Is there another way we can meet our SLO?

**Comment by pivotal-jwinters** [comment]
We don't actually create a lot of load, overall our load has actually decreased. We do see some spiky behaviour in the number of goroutines, but after talking with @vito we've decide that this is fine.
