### ISSUE TITLE
Proposal: add possibility to create pipelines through web GUI without running fly cli command.

### ISSUE THREAD

**Issue by allomov** [concourse/concourse#468]
Hello, all.

Yesterday I showed how Concourse work to one if our customer. The customer's workflow is tied to using Microsoft products, including Windows (by default work stations have win7). At this moment user experience in windows terminal is no so good as it should be and the response, that I've got was that it would be wonderful to have possibility to add pipelines through web GUI.

I understand benefits of having stateless GUI (and as a developer I like it), but is not so good from a customer perspective. Since the main problem is that using GUI turns concourse deployment into snow flake, I think it can be added a link to repo that has a pipeline description. This will make windows user experience much more better.

Thank you,
Alex L.

**Comment by vito** [comment]
Windows users have my sympathy, but this won't be happening, at least as part of Concourse core. Not being modifiable from the GUI is one of the core tenants of Concourse's philosophy and one of the reasons we started on Concourse in the first place.

There could be third-party projects that implement this, and that's fine, so long as the entrypoint to Concourse proper stays the same: YAML submitted over the API, validated, and likely checked into a repo.

Thanks for providing your use case though! I don't mean to shut it down so hard, this is just a particularly touchy subject. :)

**Comment by allomov** [comment]
Thank you for response @vito. I personally very like idea of stateless GUI. I will think of implementing pipeline manager service as a possible contribution in future to get an answer for windows oriented clients.
