### ISSUE TITLE
api/v1/teams/{}/builds?timestamps=y&since={}&limit={} API never returns empty list which is unexpected

### ISSUE THREAD

**Issue by mgsolid** [concourse/concourse#4683]
## Bug Report

> api/v1/teams/{}/builds?timestamps=y&since={}&limit={} API never returns empty list which is unexpected. 
when timestamp of `since` is a value bigger than the start_timestamp of the latest build, it will return LIMIT number of records, while 0 number of record is expected.

## Steps to Reproduce

> api/v1/teams/main/builds?timestamps=y&since=2572494457&limit=1000

## Expected Results

> 2572494457 is timestamp of future, api should return an empty list.

## Actual Results

> 1000 records returned if there are.

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary):Docker
* Infrastructure/IaaS: K8S
* Browser (if applicable): Chrome
* Did this used to work? Never.

**Comment by evanchaoli** [comment]
#4682 will fix this bug.

**Comment by pivotal-jamie-klassen** [comment]
fixed in #4682
