### ISSUE TITLE
Do the Concourse pipeline image resource mount a local volume?

### ISSUE THREAD

**Issue by sohu234** [concourse/concourse#4685]
I have a case below:
![image](https://user-images.githubusercontent.com/10140444/67939795-44c44a80-fc0d-11e9-8f40-93e92698d893.png)
In the docker image "pipeline" hava a maven command,it download its dependencies everytime when executing 'package' goal,so i want to know how i can mount my local .m2 directory to the my pipeline image through the configuration.

**Comment by pivotal-jamie-klassen** [comment]
I'm having a bit of trouble understanding your question, but if you're trying to save time by not re-downloading Maven dependencies on every run of your task, perhaps https://concourse-ci.org/tasks.html#caches will solve your problem?

**Comment by sohu234** [comment]
I'm very sorry for my poor English. I mean, does concourse support the - V parameter in docker?

**Comment by pivotal-jamie-klassen** [comment]
No, the concourse build context doesn't really have a one-to-one mapping with any particular `docker` CLI invocation. The actual container runtime is [garden](https://github.com/cloudfoundry/garden), not docker at all. Technically task caches still take the form of volumes, and I think the [actual problem](http://xyproblem.info/) you're trying to solve is that you want your maven builds to run faster by caching the local repository. I'm pretty sure if you add a `caches:` entry to your task config, you can achieve this. We do something similar with our Go builds in our main delivery pipeline: https://github.com/concourse/ci/blob/master/tasks/unit.yml#L12-L13.

**Comment by sohu234** [comment]
I got it ! Thank you very much.


On 10/31/2019 21:26, Jamie Klassen wrote:

No, the concourse build context doesn't really have a one-to-one mapping with any particular docker CLI invocation. The actual container runtime is garden, not docker at all. Technically task caches still take the form of volumes, and I think the actual problem you're trying to solve is that you want your maven builds to run faster by caching the local repository. I'm pretty sure if you add a caches: entry to your task config, you can achieve this. We do something similar with our Go builds in our main delivery pipeline: https://github.com/concourse/ci/blob/master/tasks/unit.yml#L12-L13.

**Comment by sohu234** [comment]
@pivotal-jamie-klassen Hi,jamie,i added the `caches` to my task config,but it doesn't work.Perhaps i am using the concourse pipeline with a wrong way. i need to show you how i am using the concourse pipeline more detail,pls give me some help.
   i have a docker image named 'build'  written by myslef. The 'build' image have 2 functions,which are git clone and maven build. The content for my pipeline yaml file are below:

jobs:
- name: git.project_build
  public: true
  plan:
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: sohu234/build
          tag: 3.0.x
      run:
        path: sh
        args: ["/opt/entry.sh","build"]
      caches:
      - path: .m2
      params: {"GIT_URL": "git.url",
                         "GIT_GROUP":"git.group",
                         "GIT_PROJECT":"git.project",
                         "GIT_BRANCH":"git.branch",
                         "GIT_ACCESS_TOKEN":"git.access.token",
                         "GIT_EMAIL":"git.email",
                         "PROJECT_BASE_NAME":"project.base.name",
                         "VERSION":"version",
                         "APP_MODULE_NAME":"app.module.name",
                         "CONFIG_CENTER_GROUP":"config.center.group",
                         "REGISTRY_CENTER_GROUP":"registry.center.group",
                         "DOCKER_HUB_ADDR":"docker.hub.addr",
                         "DOCKER_DAEMON_ADDR":"docker.daemon.addr",
                         "DOCKER_USER_NAME":"docker.user.name"
      }

  
    When i trigger a job, the maven building in the 'build' image always re-download its dependencies. My mean, can the concourse  map  .m2 in the HOST with a  specific directory  in the 'build' image? wait online for your help! Thank you very much!

**Comment by pivotal-jamie-klassen** [comment]
Probably your `/opt/entry.sh` needs to pass the `-Dmaven.repo.local=$PWD/.m2` flag to the `mvn` cli https://stackoverflow.com/a/7071791... Can you understand why, based on the docs I linked before?

**Comment by sohu234** [comment]
The main thing blocked me is i can't mount `.m2` on my localhost to any volumes that in docker image. Do you understand what my problem is?

**Comment by pivotal-jamie-klassen** [comment]
Yeah, it sounds like your script needs some way to run differently on localhost vs on CI - the Maven repository path could maybe be an optional parameter that defaults to `~/.m2/repository`

**Comment by sohu234** [comment]
I run Maven builds inside a docker container

**Comment by pivotal-jamie-klassen** [comment]
I'm guessing that you edit your code on your host machine (like your laptop or work computer), and when you build it, you mount `~/.m2` into the build container via a docker volume. Is this correct? It seems like you're very attached to this mental model of the local maven repository being a mounted volume and I'm struggling to see why that is so important

**Comment by sohu234** [comment]
My code is not on my host machine.In docker container ,i use the git cli to clone my code from gitlab,and then use mvn cli build it,then maven will use the repository,I hope it can use the repository outside the container but not the one inside the container . The concourse task config not support .




On 11/01/2019 19:06, Jamie Klassen wrote:

I'm guessing that you edit your code on your host machine (like your laptop or work computer), and when you build it, you mount ~/.m2 into the build container via a docker volume. Is this correct? It seems like you're very attached to this mental model of the local maven repository being a mounted volume and I'm struggling to see why that is so important

**Comment by pivotal-jamie-klassen** [comment]
I think the most important piece of information is:
what is the _absolute_ path in the container that you want to mount the volume at? If you're used to using the docker CLI, what exactly is the value of the `-v` flag that you are accustomed to using?

Following that: can you share the contents of the `/opt/entry.sh` script?

**Comment by sohu234** [comment]
The variables in params in task configuration can be used as - e of docker to the docker container. Is there a parameter corresponding to - V in docker in task configuration?

**Comment by pivotal-jamie-klassen** [comment]
@sohu234 thanks for sharing your script, I'm almost at the point of being able to sow you exactly what changes to make to get this working.

To answer your question, there are a few different parameters that act a bit like the `-v` flag to docker, and they are [`inputs:`](https://concourse-ci.org/tasks.html#task-inputs), [`outputs:`](https://concourse-ci.org/tasks.html#task-outputs) and [`caches:`](https://concourse-ci.org/tasks.html#task-caches). So one more time:

what is the path that you want to mount a volume at? If you're using to using `docker` with `-v <path-on-host-machine>:<path-inside-container>`, what are the values for those paths?

**Comment by sohu234** [comment]
The path on host machine  that I want to mount at  is ~/.m2,and the path inside container is /opt/.m2

**Comment by pivotal-jamie-klassen** [comment]
I'm going to go out on a limb and suggest something. Assuming that `pipeline.jar` will pass through maven configuration options, I think this might work:

change to `/opt/entry.sh`:
```diff
@@ -1,5 +1,11 @@
 #!/usr/bin/sh

+if [ -z "$MAVEN_REPO_LOCAL" ]; then
+  MAVEN_REPO_LOCAL=/opt/.m2/repository
+else
+  MAVEN_REPO_LOCAL=$PWD/$MAVEN_REPO_LOCAL
+fi
+
 java -DgitUrl=${GIT_URL} \
   -DgitGroup=${GIT_GROUP} \
   -DgitProject=${GIT_PROJECT} \
@@ -21,4 +27,5 @@
   -DdockerUserName=${DOCKER_USER_NAME} \
   -DclusterName=${CLUSTER_NAME} \
   -DclusterName=${CLUSTER_NAME} \
+  -Dmaven.repo.local=${MAVEN_REPO_LOCAL} \
   -jar /opt/pipeline.jar $@
```
change to your pipeline yml:
```diff
@@ -14,7 +14,7 @@
         path: sh
         args: ["/opt/entry.sh","build"]
       caches:
-      - path: .m2
+      - path: maven-repo
       params: {"GIT_URL": "git.url",
                          "GIT_GROUP":"git.group",
                          "GIT_PROJECT":"git.project",
@@ -28,5 +28,6 @@
                          "REGISTRY_CENTER_GROUP":"registry.center.group",
                          "DOCKER_HUB_ADDR":"docker.hub.addr",
                          "DOCKER_DAEMON_ADDR":"docker.daemon.addr",
-                         "DOCKER_USER_NAME":"docker.user.name"
+                         "DOCKER_USER_NAME":"docker.user.name",
+                         "MAVEN_REPO_LOCAL":"maven-repo"
       }
```

Maybe these exact changes aren't what you need, but do you see what I'm illustrating?

**Comment by sohu234** [comment]
@pivotal-jamie-klassen I think I see what you mean.I'am going to change it and have a try .Thanks for your help!

**Comment by sohu234** [comment]
@pivotal-jamie-klassen  According to your prompt, I modified the script and code, and now it works fine. Thank you my friend.

**Comment by apogre** [comment]
> @sohu234 thanks for sharing your script, I'm almost at the point of being able to show you exactly what changes to make to get this working.
> 
> To answer your question, there are a few different parameters that act a bit like the `-v` flag to docker, and they are [`inputs:`](https://concourse-ci.org/tasks.html#task-inputs), [`outputs:`](https://concourse-ci.org/tasks.html#task-outputs) and [`caches:`](https://concourse-ci.org/tasks.html#task-caches). So one more time:
> 
> what is the path that you want to mount a volume at? If you're using to using `docker` with `-v <path-on-host-machine>:<path-inside-container>`, what are the values for those paths?

@pivotal-jamie-klassen Is there a way to map outputs folder to local file e.g. /tmp/outputs_folder_name?
