### ISSUE TITLE
failed to migrate database: pq: Relation »schema_migrations« does not exist

### ISSUE THREAD

**Issue by ftsell** [concourse/concourse#4689]
## Bug Report

When installing Concourse on a bare-metal machine following the [install guide](https://concourse-ci.org/install.html) i get the following output:

```
{"timestamp":"2019-10-31T14:36:58.345676428Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}                                           
{"timestamp":"2019-10-31T14:36:58.360548753Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":76667,"session":"1"}}                         
failed to migrate database: pq: Relation »schema_migrations« does not exist
```

## Steps to Reproduce

1. Download binaries (version 5.6 on linux bare metal)
2. Setup a postgres node with
```
create user concourse with encrypted password 'concourse';
create database concourse with owner concourse;
```
3. Set environment variables accordingly
```
export CONCOURSE_POSTGRES_USER=concourse                                                                                                             
export CONCOURSE_POSTGRES_DATABASE=concourse                                                                                                         
export CONCOURSE_POSTGRES_SOCKET=/var/run/postgresql                                                                                                
export CONCOURSE_TSA_AUTHORIZED_KEYS=/etc/concourse/authorized_worker_keys                                                                          
export CONCOURSE_TSA_HOST_KEY=/etc/concourse/keys/tsa_host_key                                                                                       
export CONCOURSE_SESSION_SIGNING_KEY=/etc/concourse/keys/session_signing_key                                                                        
export CONCOURSE_MAIN_TEAM_LOCAL_USER=myuser                                                                                                     
export CONCOURSE_ADD_LOCAL_USER=myuser:foobar123                   
```
4. run `./bin/concourse web`

## Expected Results

Concourse should create the appropriate database schemas if  they are not already present.

## Actual Results

No migrations were applied.

## Additional Context

I did try to run `./bin/concourse migrate` commands as well but they resulted in basically the same error.

## Version Info

* Concourse version: 5.6.0
* Deployment type (BOSH/Docker/binary): binary downloaded from Github Release
* Infrastructure/IaaS: My own machine

**Comment by xtremerui** [comment]
do you include CONCOURSE_POSTGRES_PASSWORD? The error indicates the user doesn't have permission to view the DB.

**Comment by ftsell** [comment]
I tried setting that as well but got the same error.

I've now also tried connecting over network instead of local socket but no difference.

I can also verify that authentication to the database works because in the database logs I found the following instead of a wron-password-error.
```
2019-11-01 11:42:50.508 CET [2069] concourse@concourse FEHLER:  Relation »schema_migrations« existiert nicht bei Zeichen 15                                                                                
2019-11-01 11:42:50.508 CET [2069] concourse@concourse ANWEISUNG:  SELECT * from schema_migrations
```

When logging in interactively to the database using psql I can list relations just fine with the result that there aren't any.

**Comment by pivotal-jamie-klassen** [comment]
I'm gonna chime in with some context, hoping to ease this asynchronous debugging. We actually [continuously test](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke) the running Concourse in a bare-metal environment in our pipeline, and we use [this script](https://github.com/concourse/ci/blob/master/deployments/smoke/smoke.tf#L77-L85) to provision the machine. I'm hoping that if you take a look, maybe you'll notice any significant differences between the way our test machine is set up and how your machine is.

**Comment by xtremerui** [comment]
@ftsell thx for your patience. After investigation I found there is an old issue https://github.com/concourse/concourse/issues/3772 that same to yours and the solution is making your user `concourse` a superuser of postgres by
```
`alter user concourse with superuser`;
```

For one who doesn't want to grant superuser, we still need to look into this case.

**Comment by ftsell** [comment]
> I'm gonna chime in with some context, hoping to ease this asynchronous debugging. We actually [continuously test](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke) the running Concourse in a bare-metal environment in our pipeline, and we use [this script](https://github.com/concourse/ci/blob/master/deployments/smoke/smoke.tf#L77-L85) to provision the machine. I'm hoping that if you take a look, maybe you'll notice any significant differences between the way our test machine is set up and how your machine is.

The only difference I could find is that I use postgresql 11 and not 10. Now I can't just go and replace my whole database because I use it for other things as well but when I find the time I'll try and setup a version 10 server in parallel.

---

And @xtremerui thanks for the clue but unfortunately it didn't help.

**Comment by ftsell** [comment]
Ok guys I figured it out. After looking at the code changed in #4701 i noticed that you currently parse the error message.

Of course this can't work on my system because it is set to german. I also apologize for translating the error message in the original Issue description. I just thought it would make getting help easier; lesson learned I guess :)

Anyways, #4701 should fix this.
