### ISSUE TITLE
Add GitHub milestones for use in the issue tracker

### ISSUE THREAD

**Issue by philwebb** [concourse/concourse#471]
It would be helpful if the GitHub issue tracker made use of milestones so that it's easy to see what release contains a fix.

It's currently it's quite hard to track things down. For example, I was looking at the following issue:
- https://github.com/concourse/concourse/issues/270

Milestones aren't set on the issue and since commit messages also don't tie back to the GitHub issue it's not possible to jump directly to the commit.

I tried following the tracker link to (https://www.pivotaltracker.com/n/projects/1059262/stories/113028975) but again I couldn't see anything obvious telling me the version. There is an activity link to https://github.com/concourse/concourse/commit/d48a87f72e713ce01eee90ef10689732981f49fb which does seem to imply that it's for `v1.2.0` but doesn't really show me the relevant code. For that I need to jump to https://github.com/concourse/atc/commit/612524f6d7ac5cf5f67e215d2caef8f642e143a6.

Apologies if I've missed something obvious in Pivotal Tracker.

**Comment by pivotal-topher-bullock** [comment]
@philwebb as of .. **fiddles with the milestone a bit**.. 3.0.0 we're using GitHub milestones more actively now.
