### ISSUE TITLE
Ability to detect user who initiated build

### ISSUE THREAD

**Issue by kaedys** [concourse/concourse#4714]
## Context

I am part of a team that maintains a suite of software used for deployment and CI/CD internally within my company.  We maintain a set of hosted services that run the actual deployments, as well as a client application used to interact with those services.  This client application can be run locally or run within the context of a Concourse pipeline for automation of these deployments.  We are currently in the middle of a push to increase the visibility and auditability of deployments made using our tooling.

## What challenge are you facing?

With the current stateless design of Concourse and the intentional limiting of information, I lack two very distinct capabilities that are limiting my team's ability to effectively use Concourse:

1) We do not have the ability to link a particular build to the user who triggered it (or if it was automatically triggered), preventing us from auditing builds or back-tracing issues that arise from an erroneous build.
2) We lack the ability to detect if we are running within Concourse, meaning we cannot enable selective behavior (such as only permitting certain actions within the context of a Concourse pipeline and not permitting those actions for a local run of the binary, or vice versa) without maintaining two separate editions of the binary in question (one for Concourse, one for local runs), a significant increase in project maintenance.

Of the two, the first one is the more critical for our use case.  Our Concourse server is integrated with our corporate SSO system, but the user information is not exposed to the pipelines, so our build process cannot detect who initiated a particular build (or which pipeline initiated it, or if it was automatically triggered).  This seriously limits our ability to audit deployments and builds, and do any sort of forensics if we encounter issues with a build down the line (especially since the pipeline-specific and build-specific information appears to be completely deleted if the pipeline itself is deleted).  We can collect this information if the deployment is triggered using a local run of the client binary, but not if it is triggered via Concourse.

## What would make this better?

Exposing the user information to the build process, perhaps through environment variables or some sort of local metadata service we could `curl` to.  Implementing a solution to 1) will most likely effectively solve 2) at the same time.

## Are you interested in implementing this yourself?

Unlikely I'd have the bandwidth to do so.

**Comment by vito** [comment]
Can you provide more technical detail on how this information is needed/used at build-time? It sounds like you want to thread the username along to an external deployment service but I don't really know how that works and how that is used to authenticate. Would tracing audit events not be sufficient?

If this is interacting with an external service, it sounds like something that could/should be modeled as a resource (or in the future, as a [prototype](https://blog.concourse-ci.org/reinventing-resource-types/)). As there is already a need for resources/prototypes to have build information for the notifications use case, and they're already the encouraged way of performing side-effects, it seems like a pretty obvious choice. They are currently lacking the 'who triggered the build' info but that would be easy to add. And by modeling it as a resource type/prototype it would inherently know that it's 'running in concourse'.

**Comment by kaedys** [comment]
Our Concourse servers are integrated with our LDAP and SSO systems.  What I'd like is to be able to attach the LDAP ID of the user that kicked off a pipeline (or note that it was automatically triggered, if such was the case), and I want to attach that to the request being set to our deployment service, so it can record it, alongside other information useful for auditing and ensuring compliance over the entire deployment process.

One thing that's notable here is that this software suite is capable of doing both production and dev deployments, but we specifically do not permit Concourse to do production deployments to avoid "oopsies" that might happen from configured pipeline values that the dev didn't notice (that's one reason I'd like a way to detect if we're running in Concourse).  On the flip side, in order to ensure that images we build are tested first in dev, we bar production deployments from building images (they have to use one that was built previously during a dev deployment), and generally for safety, we don't really support triggering an image build when run outside of Concourse.  We mandate user information for production deployments as well, while dev deployments currently completely lack that (though we'd still like to have that data for non-automatic-trigger deployments).

I'm honestly not entirely certain what you mean by modeling it as a resource.  I hope you're not suggesting writing a plugin similar to the Docker one (which we use heavily), as that would require essentially a complete re-write of the entire process we have in place.  If you simply mean that the client application be run in a docker container, we already do that.  However, since that docker container needs to be publicly accessible (well, "publicly" as in on our corporate intranet), we can't store secrets in it, and we also can't rely on users not just pulling it and running it locally.

So that generally explains the use case we're going after here.  We're trying to find a set where we can positively identify if we're in Concourse, without that being able to be easily mimicked by local configuration (our current Docker container system is easily mimicked, it just uses a `$CONCOURSE=1` env var), and be able to record LDAP information and propagate that through the entire deployment process.

**Comment by kaedys** [comment]
Yes, it is still important.

**Comment by luigizhou** [comment]
+1 to this feature.

I saw this enhancement was already mentioned in the past:
https://github.com/concourse/concourse/issues/194 and here https://github.com/concourse/concourse/issues/233 so hopefully some work has been done already? 

Cheers

**Comment by chrised** [comment]
+1 from myself and my team also, we'd really like this for [SOC 2 Compliance](https://www.imperva.com/learn/data-security/soc-2-compliance/); otherwise we're probably going to have to resort to deploying something like [RunDeck](https://github.com/rundeck/rundeck) alongside our Concourse deployment, which would suck.

**Comment by nekrondev** [comment]
+1

I'm pushing this, too as we are currently evaluating a deployment process for our customers that needs to fit corporate compliance standards like logging who did trigger a build (this is a must have).

I think the easiest way would be to capture the user who triggered a build into the build history that can be quereid with fly -t <team> bs.

**Comment by kaedys** [comment]
I'd rather it not depend on the CLI tool to access that information.  User information _should_ be available natively to the build itself, so that the build process can _capture_ that data.  It's absolute lunacy that Concourse effectively mandates that all builds are functionally anonymous.

**Comment by jchesterpivotal** [comment]
A drive-by thought bubble for the Concourse team. Could this be modeled in Concourse as a  resource version? Then it would be visible alongside other triggers in a uniform way.

Eg clicking the build button might give a version like

```json
{
	"version": { "uuid": "9DA01BC8-C40D-4CCE-B085-7566392E5C7F" },
	"metadata": {
		"user": "joebloggs",
		"team": "bloggsandco",
		"atc": "https://ci.bloggs.example.com",
		"pipeline": "bloggs-ci",
		"job": "do-thing",
		"triggered_by": "button_build", // or fly_build, button_rebuild
		"timestamp": "2020-10-23T04:20:51.17Z"
	}
}
```

That would capture what I think is the relevant data into the version metadata tables. It could also be `get` in a job, written out with a task and then `put` to an external system.
