### ISSUE TITLE
Visualize test results (e.g. TAP output)

### ISSUE THREAD

**Issue by ibotty** [concourse/concourse#4716]
## What challenge are you facing?

When some tests in a testsuite fail, the whole box around the job is red (as expected).  It would be great to have an overview on which parts of the testsuite failed.

## What would make this better?

I guess a job (in the detailed pipeline view) would not be one uni-colored box but further divided to show the individual test's result.  Of course it should still be red-ish if any test fails.  Further UI thoughts required.

## Are you interested in implementing this yourself?

Yes, but I am no designer.

**Comment by jchesterpivotal** [comment]
Somewhere, I don't recall where, I've suggested that tasks should be able to emit richer results in addition to exit codes, analogous to how resources can attach metadata to a version. For example a ginkgo task could emit structured output about tests passing and failing.

Admittedly not quite the same as what you're proposing. I had in mind a usecase of analysing large collections of builds for flaky builds, common factors in failures etc.

**Comment by vito** [comment]
@jchesterpivotal I worked that into https://github.com/concourse/rfcs/pull/37 somewhat - prototype actions can return objects and metadata. Maybe we could establish a schema for the returned objects that Concourse could interpret or something. :thinking:
