### ISSUE TITLE
GitHub auth should be case-insensitive for orgs and teams

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#472]
Hi there,

The `github_auth.authorize.organization` field in the BOSH deployment manifest is one of those places where Github is case-sensitive for organization names.

Maybe this should be documented, or maybe just this issue being closed is good enough.

Thanks,
C.J.

**Comment by vito** [comment]
We should probably make it case-sensitive, considering GitHub's API appears to be: https://api.github.com/orgs/CoNcOuRsE

**Comment by billimek** [comment]
👍 for this as well.  We make heavy use of github oauth for org-level and personal ID-level authorization.

One of the biggest problems we encounter is when people don't use the 'correct' case of the github org name or their username, and authorization fails

**Comment by jama-pivotal** [comment]
Linking to our user auth work #1888 , will close this issue when that one is released

**Comment by deniseyu** [comment]
As of 4.0.0, all GitHub team names and organisations are persisted as lowercase strings: https://github.com/concourse/skymarshal/blob/d485fccfae6c18c18f883e705042e0d50b3e2b5f/skycmd/flags.go#L61-L67 so we will close this issue.
