### ISSUE TITLE
Metrics code is not covered by tests

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#4739]
## What challenge are you facing?
Metrics code is NOT tested and it is quite easy to break the functionality inadvertently. 

## What would make this better?
Reminders to the dev to either add automated tests ( best case ) or at least ensure they have manually tested the changes
To add a blocker to ensure the later - a solution is to add a test that will fail whenever the metrics section of the code changes and the user has to address the failing test to proceed. This failing test would remind the dev to perform manual tests

**Comment by pivotal-jamie-klassen** [comment]
This just happened in our most recent release #4985. I'm taking a stab at adding better metrics tests right now.
