### ISSUE TITLE
Documentation for implementing a resource type

### ISSUE THREAD

**Issue by aquavitae** [concourse/concourse#474]
I'm trying to implement a new resource type for caching - it basically tars a folder, stores it on a remote server, and pulls it down again as needed.  In short (without the boilerplate), the scripts look something like:

```sh
# in
curl --output cache.tar $SOURCE_REMOTE_URL
tar xf cache.tar -C $1

# out
tar -cf cache.tar -C $1
curl -T cache.tar $SOURCE_REMOTE_URL
```

However, the directory passed in as `$1` is the root of all resources. so it contains, for example:
* git_repo_1
* git_repo_2
* folder_to_be_cached

As far as I can see from looking at the public resource types, and from looking at the documentation, the `out` script identifies the name of the resource through assumptions about an undocumented naming convention.  How can I deterministically calculate the name of the folder to be cached?  

If there is some convention then this should be documented, and if not then the method to determine the name should be documented.

**Comment by vito** [comment]
The `out` script does not make assumptions, it is told which things to care about via `params`.

**Comment by aquavitae** [comment]
So does that mean that the name of the resource needs to be passed into the params like this:

```yaml
- put: cached-resource
- params:
    name: cached-resource
```

Surely that's just a duplication?  Or am I missing something obvious?

**Comment by zachgersh** [comment]
@aquavitae wanted to ask - what would this caching resource actually be used for? Concourse internally is doing its own caching of assets you are passing around via Baggageclaim.

**Comment by vito** [comment]
@aquavitae the name of a resource does not directly affect its behavior. it's duplication in that you happened to type the same thing twice. that won't always be the case.

in your example you should call it `path`, not name. the interface to `put` is via the filesystem; this is what makes build plans so flexible (e.g. you can swap out a `get` for a task's output).

**Comment by aquavitae** [comment]
@zachgersh Hmm... I can't find a lot in the docs about caching or how it works.  There are two scenarios I'm trying to handle: 1. storing local package caches between builds (e.g. `~/.ivy2`) and 2. Caching `node_modules` after `npm install` between tasks and, possibly between builds.  If baggageclaim already does this that's great, but how would it be configured?  

@vito Ok, I think I get it.  In the task I would make sure to copy the resources to a specific location (e.g. `output-resources`.  Then in the build plan I would have something like:

```yaml
- put: cached-resource
  params:
    name: output-resources
```

**Comment by vito** [comment]
The caching discussion leads to https://github.com/concourse/concourse/issues/230 - and I think the rest of this is answered; closing!
