### ISSUE TITLE
How concourse contributors want to be recognized?

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#4747]
Concoures has been always thinking about how to reward contributors better.

As the first step we want to have a place or a way to allow concourse contributors to be better recognized both internally and externally. Currently we are looking at using [All Contributors](https://github.com/all-contributors/all-contributors)([website](https://allcontributors.org/)) in Concourse.

Any opinions, suggestions and likes/dislikes are welcome!

**Comment by eedwards-sk** [comment]
👍 to `all-contributors`

Vito once mentioned something about a T-Shirt. I'm also happy with that :)

**Comment by evanchaoli** [comment]
T-Shirt, Mug, etc. LinkedIn recommendation also maybe.

**Comment by vito** [comment]
Not stale! Let's pin this actually to get more responses. :)

**Comment by kcmannem** [comment]
`concourse/fly credits` subcommand

**Comment by skreddy6673** [comment]
Something like a badge that can be used in LinkedIn or on a Resume.
