### ISSUE TITLE
Support Vault Namespaces

### ISSUE THREAD

**Issue by andhadley** [concourse/concourse#4748]
## What challenge are you facing?

The enterprise version of Hashicorp Vault enables the use of [namespaces](https://www.vaultproject.io/docs/enterprise/namespaces/index.html) to make managing secrets easier. Currently there is no way to use these namespaces with Concourse.

## What would make this better?

Updating the vault package used by Concourse to a newer version (currently it is pegged at v1.0.1) would allow the user to set the VAULT_NAMESPACE environment variable and use a namespace. Ideally, having first class support for this setting would be nice but is not a necessary first step. 

## Are you interested in implementing this yourself?

I can bump the version number but I assume that it will require several of the other hashicorp dependencies to be updated as well. If others have already run into issues doing this or related tasks, that would be helpful to know.

**Comment by deniseyu** [comment]
hey @andhadley, thanks for raising this! We're actually currently in the middle of upgrading our own Vault installation so this is good timing.

As a general rule I think that security features are sensible things to support. In addition to bumping the dependency version(s), we'd have to add a web configuration flag which would show up in the `--help` text and be documented, so the only thing that gives me pause is adding a flag that everyone would see, but that only Hashicorp's enterprise users can use... that doesn't seem in the spirit of open source. But then again, credentials managers arguably are beyond the scope of Concourse core, and it's sort of buyer-beware territory, so I'm not sure.

This feels like a gray area for product so gonna tag in @scottietremendous @vito.

**Comment by vito** [comment]
@deniseyu Supporting enterprise features is fine; for example we support configuring a different GitHub API URL for GitHub enterprise users.

+1 to bumping the dependency and also adding explicit config flags. We shouldn't be relying on the Vault Go package's use of environment variables for config (if indeed that's what it does - haven't checked).

**Comment by andhadley** [comment]
@deniseyu @vito  Thanks for the input. I will bump the version(s) and add a config flag. I hope to have a PR for you shortly.
