### ISSUE TITLE
Explore: Get Concourse to ping a separate containerd daemon when running the healthcheck

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4753]
As part of building out a new backend interface for containerd on workers, we want to see if we can get worker healthchecks working with an arbitrary containerd daemon.

**Comment by cirocosta** [comment]
Hey,

After https://github.com/concourse/concourse/pull/4752, we already got the ability to do so as stated in this issue.

With the following modification to `docker-compose.yml`

```diff
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -44,6 +44,8 @@ services:
       CONCOURSE_LOG_LEVEL: debug
       CONCOURSE_TSA_HOST: web:2222

+      CONCOURSE_GARDEN_USE_CONTAINERD: 'true'
+
       # avoid using loopbacks
       CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
```

one can reach `:7777/ping` and get a response back once `containerd` is up 😁  

Thanks!
