### ISSUE TITLE
Resource with "&" in the name causes 404 in web UI

### ISSUE THREAD

**Issue by RichardBradley** [concourse/concourse#4756]
## Bug Report

I created a resource with a "&" in its name, and it broke the web UI.

## Steps to Reproduce

The resource is named "tod\&#x4F;-checker-src"

This causes an ajax request to https://ci.example.com/api/v1/teams/main/pipelines/my-pipeline/resources/tod&#x4F;-checker-src/versions when on the https://ci.example.com/teams/main/pipelines/my-pipeline/resources/tod%26%23x4F%3B-checker-src page, which fails with a 404

## Expected Results

I expected the web UI to display normally.

## Actual Results

The page switched to a 404 display

## Additional Context

I was hoping to escape the word "TODO" in my pipeline.yaml so that it did not trigger an automated job which looks for "TODO"s in my source code.

This page suggests that "\&#x4F;" escapes work in YAML, but they clearly don't here.
https://riptutorial.com/yaml/example/25838/escaping-characters

Do you know how I can escape a string in a yaml file used by concourse?

## Version Info

* Concourse version: v5.4.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: "control-tower"
* Browser (if applicable): Chrome
* Did this used to work?: I doubt it.

**Comment by RichardBradley** [comment]
> Do you know how I can escape a string in a yaml file used by concourse?

This is explained here: https://github.com/go-yaml/yaml/issues/121

**Comment by deniseyu** [comment]
hey @RichardBradley, thanks for raising this - we're going to be moving towards stricter naming conventions for all user-facing abstractions in a future major version of Concourse so this is unlikely to be fixed. Special characters not only mess up web browsers -- we _could_ serialize all strings for URLs, but many third-party integrations can't handle special characters. Think logging tools, credentials managers, etc. etc. There's more historical context in this issue: https://github.com/concourse/concourse/issues/3985

**Comment by RichardBradley** [comment]
Sure, no problem.

As a programmer, the idea that some characters are "special" and need forbidding makes me a little sad, as it usually just means that you have loads of escaping bugs, which are at their core **type** bugs (i.e. confusing a String with a URL). It is of course easier to just forbid certain characters and skip encoding at context boundaries though, especially if you don't have a strong type system to build on (and it looks like Go doesn't exactly help with this).  

Thanks for your reply.
