### ISSUE TITLE
Feature Request: I would like the ability to leave a comment on a (failed) build 

### ISSUE THREAD

**Issue by utako** [concourse/concourse#476]
Our team currently documents the reasons why our builds have failed in a spreadsheet. I'd rather have this persisted on Concourse. This way, our developers can note the reason for a failed build next to the build number and other build information, and it'll be easier for us to keep track of common failures and flakes. This was the most useful thing about Jenkins, and it'd be nice to have similar functionality on Concourse.

I looked for a similar issue but wasn't able to find it.

**Comment by JesseTAlford** [comment]
This sounds relevant to my interests. I would also like to be able to change the display color of builds once I have commented on them - perhaps to a lovely purple, to indicate it's been investigated?

**Comment by vito** [comment]
@zrob @wendorf @utako @JesseTAlford @kimeberz 

Can we consolidate these?

https://github.com/concourse/concourse/issues/380
https://github.com/concourse/concourse/issues/476 (this one)
https://github.com/concourse/concourse/issues/401

They all sound very similar but if I squint my eyes I can see subtle differences between them. But I don't want to do that if y'all really just didn't find the previous issue before opening your own.

Here's my thinking of different vectors for this kind of thing, some of which we already planned, and some of which was brought up in these issues:

* Tagging w/ autocomplete on an entire build and being able to look up builds by tags.
* Leaving a comment on a build itself.
* Leaving a comment on a line of output.
* Marking a build as "triaged", presumably by doing one of the above things.

I'd like to evaluate the pros/cons of doing one of these over the other ones, or at least which one to do first. I personally like the idea of commenting on and linking to individual lines (so long as those comments are easy to notice). I also like tagging for being able to collect data and such in a more structured (but low barrier to entry) way.

**Comment by wendorf** [comment]
I'm fine with closing #401 in favor of this one.

Commenting on a line of output is not too useful for my use cases. I'd probably use the feature if it existed, but it's not compelling to me compared to build-level notes/tags.

If tagging were available, I'd probably mark a build as "dealt with" by _removing_ any tags suggesting "look at this". In that case, I'd like to be able to define a default "failed build" tag, potentially on a per-job or per-task basis, e.g.:

```
jobs:
- name: clean-kitchen
  tag_on_failure: [dirty-kitchen]
  plan:
  - task: wash-dishes
    tag_on_failure: [busted-dishwasher]
```

**Comment by vito** [comment]
@wendorf Is the intent of the tagging visibility into which part failed? I wonder how far we could get (and save on config boilerplate) by just using the name of the task that failed.

**Comment by vito** [comment]
I suppose then you lose the distinction between predicted failures/known flake vectors vs unpredicted ones, if everything gets a tag by default?

**Comment by wendorf** [comment]
For me, default tagging by job/task is heavyweight. It categorizes _everything_, when I probably only want to selectively categorize. I think I'd rather see opt-in tagging, and understand how I start to use it to see if default tagging feels useful.

Type is the primary way I think about failures (e.g. "mail-server-connection-timeout", "deployment-unhealthy"), so another option (potentially heavyweight) is to provide an exitcode->tag map. This feels like a lot of upfront work, though, so "human reviews unsorted failures*, and tags" is probably sufficient to start with.


*What about a failed-job-resource that can trigger a notification that there are pending failures to review?

**Comment by zrob** [comment]
I'm happy to close #380 in favor of this as long as we're focusing on leaving actual comments, which allow a dev to leave thorough thoughts and findings.

Per build would be plenty to make me happy
per task sounds like it could be nice but build level would really help

tags are a tool that can help with one but not all of the underlying reasons to want comments.  they solve the visibility concern of quickly grouping similar failures.   i really like that idea but don't think it's the same as the request to store notes, so i'm not sure it should be rolled into this.

on the topic of tags it'd be nice if they worked similar to tracker tags.  something i can just type in and maybe give a color to, although auto-assigned colors that tried not to repeat too much would be groovy.  i don't know that i'm excited about going down into messing with configs to get tags.

**Comment by vito** [comment]
I think the most natural split is #401 for tagging and this one for commenting (since we have all the discussion here). Should we close #380 and reopen #401?

It sounds like we'll start with being able to comment on a build, and having a visual cue for builds with comments.

Being able to comment on individual lines is mainly useful for test suites that have a bunch of useful logging and such inline. It'd be a nice way to communicate the diagnosis (e.g. "this log line here shows it failed to create a container"). But we can get there iteratively; there are definitely cases where it'd just be an extra step to hunt for an appropriate line to comment on. In my mind this all is very similar to comments on commits in GitHub, which can either be on a line of code or on the entire commit.

Re: tags, I agree with anything that reduces the need for additional config. Auto-assigning colors sounds great. Either way it's nice that it'd be consistent across all Concourses.

**Comment by JesseTAlford** [comment]
In addition to being able to leave notes - which I'd enjoy having at every level but would be happy to take at the build level, initially, - my primary concern is the ability to mark a build, at a glancible level, as triaged.

Principally, this means the option to make it not be orange/red anymore.

Relatedly, it would be helpful to be able to reset the color of builds to something neutral, if not the "unrun" initial color. Back on releng, we'd sometimes want to watch a specific pipeline run and monitor its progress. We ended up re-creating pipelines a lot so we could watch the green flow across the grey.

I think these are dependent on being able to leave build-level comments, so a user can explain the reason for the override of the build color.

**Comment by davewalter** [comment]
All of this discussion has been around failed builds, which sounds like a great feature to have, but I think it would also be useful to be able to put a comment on a paused job to let anyone looking at a pipeline know why a job was paused. I'm happy to open a separate feature request for that if desired, but I didn't want to unnecessarily add to the potential duplication of related requests.

**Comment by XenoPhex** [comment]
....BUMP FOR GREAT JUSTICE

**Comment by anoop2811** [comment]
This would be a great feature to have. Especially the red jobs are what catches our eye the most, if we could communicate that this is being worked on by someone or waiting for some dependency to be available, it would save us a whole lot of communication overhead
