### ISSUE TITLE
iptables v1.6.2: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded

### ISSUE THREAD

**Issue by sohu234** [concourse/concourse#4771]
os: red hat enterprise linux release 8.0
kernel: 4.18.0-80.18.x86_64
concourse image: concourse/concourse:latest (v5.5.3)

**Comment by xtreme-sameer-vohra** [comment]
Hey @sohu234,

Could you please provide some more information regarding when you see this error and steps to reproduce the issue ?

**Comment by taylorsilva** [comment]
If someone comes across this, this error means your kernel does not have the iptables filter module loaded. You can try running `sudo modprobe iptable_filter` which should load the module.

Sources:
- https://askubuntu.com/questions/20070/whats-the-difference-between-insmod-and-modprobe/59193#59193
-
