### ISSUE TITLE
Resource view: Remove Pin bar

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#4780]
Remove Pin bar from top of Resource view

## Current State:

![Screen Shot 2019-11-18 at 10 34 21 AM](https://user-images.githubusercontent.com/27746614/69066717-cf6bbe80-09ef-11ea-913d-e82bb0f5d444.png)

## Desired State:

![Screen Shot 2019-11-18 at 10 38 49 AM](https://user-images.githubusercontent.com/27746614/69066721-d1358200-09ef-11ea-9fd4-91518c8c4a70.png)

**Comment by pivotal-jamie-klassen** [comment]
Fixed in #5309
