### ISSUE TITLE
Resource view: dismissing comment overlay

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#4786]
![Screen Shot 2019-11-19 at 11 15 55 AM](https://user-images.githubusercontent.com/27746614/69164432-fee8fc80-0abd-11ea-8d97-c75effade21f.png)

**Comment by vito** [comment]
Closing as we're going with inline comment editing instead: https://github.com/concourse/concourse/issues/4781#issuecomment-574338705
