### ISSUE TITLE
Resource view: no overlay by default

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#4787]
![Screen Shot 2019-11-19 at 11 17 19 AM](https://user-images.githubusercontent.com/27746614/69164571-335cb880-0abe-11ea-9528-28fcb244e682.png)

**Comment by vito** [comment]
Closing in favour of inline comment editing.

**Comment by pivotal-jamie-klassen** [comment]
On master we still have an overlay, so this issue is probably still useful to track the point at which it gets removed.
