### ISSUE TITLE
Re-runs should not become the 'last finished build'

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4790]
Currently, if I have builds `7 8 9` and I click the job in the pipeline, it takes me to `9`.

Once I re-trigger `8`, the pipeline shows a 'running' animation, and clicking the job takes me to `8.1`. I feel like this isn't too unreasonable since I most likely want to see what's running.

However, once `8.1` completes, I would expect clicking the job to take me to `9`.

**Comment by vito** [comment]
@Lindsayauchin @matthewpereira We should figure out the UX for this as it's kind of confusing - ping me when you have a moment!

**Comment by vito** [comment]
* `next_build` should point to a rerun *only* if it's a rerun of the latest build
* `finished_build` should point to a rerun *only* if it's a rerun of the latest build

Right now we update `finished_build` whenever a build finishes; might need to make this conditional?

**Comment by xtremerui** [comment]
@zoetian @pivotal-jamie-klassen could UX team provide some insight of the usage of `transtion_build` in `/api/v1/jobs` in dashboard? With the context of re-run builds and per vito's comment for `next_build` and `finished_build`, what behavior is expected from UX for 'transition_build' ? Thx.

**Comment by xtremerui** [comment]
`transition_build` depends on the `finished_build`. By inheritance, 

`transition_build` should point to a status changed rerun only if it's a rerun of the latest build
