### ISSUE TITLE
Memory Consumption on Web Nodes

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [concourse/concourse#4794]
## Bug Report - Web Nodes Memory Consumption

This is more of an optimization suggestion rather than a bug report. Given a concourse deployment, most of the memory consumption (around 40%) is isolated to two sections of the code; please see the profiling graphs (more profiling can be provided when requested).

[<img src="https://raw.githubusercontent.com/pivotal-jamil-shamy/parking/master/images/concourse-memory-1.png">]()
[<img src="https://raw.githubusercontent.com/pivotal-jamil-shamy/parking/master/images/concourse-memory-2.png">]()

## Steps to Reproduce

Profile the concourse web nodes using `pprof`

## Expected Results

Less memory consumption on web nodes, especially the two isolated sections of the code that consume around 40% of the total consumption. 

## Version Info

* Concourse version: 5.5.5
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: N/A
* Browser (if applicable): N/A
* Did this used to work?: Memory consumption significantly increased in version 5.x of concourse.

**Comment by osis** [comment]
Yea, might not really be bug in the code but maybe an ask for the docs?

https://docs.pivotal.io/concourse-pcf/v5/architecture/#operating-concourse-at-scale

@scottietremendous maybe we can add memory to the ATC nodes on that page so folks don’t get caught off guard?

Thanks for pointing this out @pivotal-jamil-shamy! 🙇

**Comment by xtreme-sameer-vohra** [comment]
The first graph will be impacted ( positively ) by the `algo` changes are being planned for v6. May be @clarafu can provide more context :)

The second graph is for the underlying stack for the Web <-> Worker communication.  Are there any suggestions on how the memory footprint could be reduced for this ? One option that has been raised by @cirocosta is looking at switching from SSH -> TLS

**Comment by cirocosta** [comment]
> [@osis]  maybe we can add memory to the ATC nodes on that page so folks don’t get caught off guard?

at the moment, these are the values for `web` nodes:

```yaml
# ...
    replicas: 3
    resources:
      requests:
        cpu: 1500m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 1Gi
```

https://github.com/concourse/hush-house/blob/a14d0832ecac5753c138a9287e12a3be375cc1a5/deployments/with-creds/hush-house/values.yaml#L41-L47

> [@xtreme-sameer-vohra ] Are there any suggestions on how the memory footprint could be reduced for this

(a not very useful answer below)

thinking literally only about this part (streaming bits from workers from one side to another) and nothing else, having more web nodes would help (as you'd have a lower probability of a given at involved w/ the task of streaming), buut, naturally, that's not as simple as it sounds 😅 


> One option that has been raised by @cirocosta is looking at switching from SSH -> TLS

(shameless plug hehe) https://ops.tips/notes/concourse-workers-streaming-improvements/

**Comment by cirocosta** [comment]
just adding some more context on the "expensiveness of SSH" - in the past, I've done an experiment where I added 300 workers to a cluster that has a single web node, and this is how things look like:

<img width="926" alt="profile-300-workers" src="https://user-images.githubusercontent.com/3574444/69567520-85eb1880-0f87-11ea-9c16-8a927edb2b22.png">
<img width="1757" alt="web-profile-workers-doing-nothing" src="https://user-images.githubusercontent.com/3574444/69567523-87b4dc00-0f87-11ea-8244-ec3610f7caaf.png">

that's a for a web node w/ 1GB  ram, 1CPU, with no workloads going on (i.e., 35% cpu util comes from the heartbeating, etc).

**Comment by kcmannem** [comment]
@cirocosta are we doing the ssh dance on every single heartbeat. Wouldn't it just persist the connection?

**Comment by xtreme-sameer-vohra** [comment]
@kcmannem The SSH connection is persistent and recycled based on `CONCOURSE_REBALANCE_INTERVAL`.
Depending on the experiment setup @cirocosta used, if it included the initial registration of the 300 workers, then we can expect to see the ssh connection setup showing up on the graph. However, if it was after the initial registration of the workers, then I'd not expect to see ssh connection setup to take such a significant portion.

**Comment by xtreme-sameer-vohra** [comment]
My mistake folks, the original issue was referencing Memory utilization. Ciro's suggestion for SSH->TLS for the web worker comms was primarily dealing with CPU utilization.

**Comment by clarafu** [comment]
As @xtreme-sameer-vohra suggested about the v6 work we are doing on the core team, it is implementing a new scheduler that no longer relies on holding a bunch of data in memory in order to figure out if a build needs to be scheduled. 

That memory consumption is the `db.(*pipeline).LoadVersionsDB` that you see on the graph. That work was tracked in issue #3602, which is finished and will be in the next major release.
