### ISSUE TITLE
lets encrypt ACMEv1 disabled

### ISSUE THREAD

**Issue by fredwangwang** [concourse/concourse#4795]
## Bug Report

The autocert client used by concourse is disabled by letsencrypt, resulting the following error message when running web with letsencrypt=true:
```
2019/11/20 01:45:30 http: TLS handshake error from 50.232.79.2:49366: acme/autocert: missing certificate
2019/11/20 01:45:33 http: TLS handshake error from 50.232.79.2:61681: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

## Steps to Reproduce

Running web with letsencrypt function

## Expected Results

Certs obtained automatically

## Actual Results

error msg listed above

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: 5.7.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP

**Comment by vito** [comment]
More context: https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

**Comment by suhlig** [comment]
Still getting the same old issue with `5.7.2`:

```
Dec 07 18:27:24 ci concourse-web[901]: 2019/12/07 18:27:24 http: TLS handshake error from [REDACTED]:52411: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

Any hints to further debug this? 

Config:

```
export CONCOURSE_TLS_BIND_PORT="443"
export CONCOURSE_ENABLE_LETS_ENCRYPT="True"
```

**Comment by vito** [comment]
Ack, looks like it's because we still have the v1 endpoint as the default value for the flag:

https://github.com/concourse/concourse/blob/c77d756b416274697000837f5712ec3e8bb744ce/atc/atccmd/command.go#L101

Sorry about that. At least the client has been upgraded to support v2 endpoints now.

Until we bump the default value, here's the config you can set to get it working:

```sh
export CONCOURSE_LETS_ENCRYPT_ACME_URL=https://acme-v02.api.letsencrypt.org/directory
```

**Comment by suhlig** [comment]
That env var helped. I am back in (secure) business. Thanks a lot!

**Comment by mpontillo** [comment]
The workaround worked for me, but in addition to the new directory URL I also needed to `setcap` the binary and ensure port `443` was being used (I was being lazy and trying to use `8443` at first, which didn't work).

This worked for me:
```bash
export CONCOURSE_TLS_BIND_PORT=443
export CONCOURSE_ENABLE_LETS_ENCRYPT=true
export CONCOURSE_LETS_ENCRYPT_ACME_URL=https://acme-v02.api.letsencrypt.org/directory
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/concourse/bin/concourse
```

**Comment by pivotal-jamie-klassen** [comment]
@mpontillo we ran into the same thing when setting up our smoke tests too https://github.com/concourse/ci/blob/master/deployments/smoke/systemd/smoke-web.conf.tpl#L2
