### ISSUE TITLE
stdout forced to buffer in build logs in v5.6+

### ISSUE THREAD

**Issue by zoetian** [concourse/concourse#4799]
## Bug Report

We got reports from Concourse users that their terminal-based download progress bars never displayed in the build output until the download was completely finished. Since they were regularly running 10 gigabyte downloads, this was pretty troublesome UX.

We did some digging, and it seems that stdout doesn't get flushed appropriately in the build logs as of v5.6.0.

## Steps to Reproduce

Run
```bash
$ fly -t target execute -c <(cat <<EOF
platform: linux
image_resource:
  type: registry-image
  source: {repository: ubuntu}
run:
  path: bash
  args:
  - -c
  - |
    for i in {1..10}; do
      printf "$i\r"
      sleep 0.5
    done
    echo
EOF
)
```

and curl the events endpoint for the resulting build, something like

```bash
$ fly -t target curl /api/v1/builds/<build id>/events
```

## Expected Results

One event per loop iteration, like

```bash
# ... initial events ...

id: 49
event: event
data: {"data":{"time":1574267342,"origin":{"id":"5dd569c8"},"config":{"platform":"linux","image":"","run":{"path":"bash","args":["-c","for i in {1..10}; do printf \"$i\\r\"; sleep 0.5; done\necho\n"],"dir":""},"inputs":null}},"event":"start-task","version":"5.0"}

id: 50
event: event
data: {"data":{"time":1574267342,"origin":{"id":"5dd569c8","source":"stdout"},"payload":"1\r"},"event":"log","version":"5.1"}

id: 51
event: event
data: {"data":{"time":1574267343,"origin":{"id":"5dd569c8","source":"stdout"},"payload":"2\r"},"event":"log","version":"5.1"}

id: 52
event: event
data: {"data":{"time":1574267343,"origin":{"id":"5dd569c8","source":"stdout"},"payload":"3\r"},"event":"log","version":"5.1"}

# and so on ...
```

## Actual Results

one big buffered event, like
```
id: 25
event: event
data: {"data":{"time":1574267470,"origin":{"id":"5dd56a41","source":"stdout"},"payload":"1\r2\r3\r4\r5\r6\r7\r8\r9\r10\r\r\n"},"event":"log","version":"5.1"}
```

## Additional Context

It looks like the `dbEventWriterWithSecretRedaction` is always used (https://github.com/concourse/concourse/blob/master/atc/engine/builder/delegate_factory.go#L378-L389), and it buffers all bits before a newline (https://github.com/concourse/concourse/blob/master/atc/engine/builder/delegate_factory.go#L510).

Seems like secret redaction might not actually be opt-in? We didn't get all the way to the bottom of this, but maybe @evanchaoli will be able to help, having last changed this code? In any case, we noticed that [`newDbEventWriter`](https://github.com/concourse/concourse/blob/master/atc/engine/builder/delegate_factory.go#L420-L426) is never used.

## Version Info

* Concourse version: v5.6.0
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): n/a
* Did this used to work? yes, tested and working with v5.4 and v5.5.6

**Comment by evanchaoli** [comment]
@zoetian This should be related to the secret redaction feature (PR #4311 and #4398). As a workaround, you may turn off the feature.

**Comment by evanchaoli** [comment]
I have just created PR #4817 to fix this regression, which doesn't really handle "\r" for secret redaction, instead it changes to call `newDBEventWriter` when secret redaction is not enabled.

@vito This PR, together with #4757 and #4808, maybe worthy a minor release of 5.6.1.
