### ISSUE TITLE
Improve error message output

### ISSUE THREAD

**Issue by Nopik** [concourse/concourse#48]
When loading pipeline with loading multiple parameters file through --vf options, if one of the loaded file is ill-formed (e.g. contain tabs instead of spaces), error message is spit out saying that file is bad, but it doesnt say which file. Needlessly to say, it would be useful to print out the filename which caused the problem.

**Comment by robdimsdale** [comment]
@vito how do the new `fly` changes impact this story?

**Comment by kimeberz** [comment]
Closing this since it's been inactive for over a year. We would appreciate a pull request for this if it's still an issue. Thanks!
