### ISSUE TITLE
systemd service for worker

### ISSUE THREAD

**Issue by ernado** [concourse/concourse#480]
I'm trying to use concourse binary release on **ubuntu 16.04** that uses **systemd**.
It is non-trivial how to do it correctly.
For example, systemd is unable to stop /tmp/garden-init while doing `stop` or `restart`, 
i. e. `systemctl restart concourse-web` will wait for timeout and then just kill all processes in CGroup.

Second issue was with resource management - systemd has defaults on [resource-control](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html) and if "TaskMax" is not set to "infinity" garden will fail to start tasks with weird (and unhelpfull) error message.

My .service file now is 

```
ernado@ci:/opt/concourse$ sudo systemctl cat concourse-worker.service
# /etc/systemd/system/concourse-worker.service
[Unit]
Description=Concourse worker
After=network.target

[Service]
ExecStart=/bin/concourse worker --tsa-public-key host_key.pub --tsa-worker-private-key worker_key --tsa-host=ci.cydev.ru --work-dir /opt/concourse/worker
Type=simple
RestartSec=3s
Restart=always
WorkingDirectory=/opt/concourse/worker
TasksMax=infinity
MemoryLimit=infinity

[Install]
WantedBy=multi-user.target
```

I don't know how to fix "restarting" for worker. Also, my host will wait for concourse worker while restarting, and only workaround is to set small timeout.

**Comment by DenisIzmaylov** [comment]
Up

**Comment by databus23** [comment]
I'm also hitting this. Not sure what systemd does to prevent concourse from shutting down properly.

**Comment by hfinucane** [comment]
I've been running concourse-worker in 16.04 successfully for a while, with only these limit changes:
```
LimitNPROC=infinity
LimitNOFILE=infinity
TasksMax=infinity
```

Hopefully that helps. Not seen any problems starting or stopping.

**Comment by devdavidkarlsson** [comment]
https://gist.github.com/tomwhoiscontrary/f67bd114f193e481d3f2525ee1e323dd

**Comment by antonu17** [comment]
And I'll put my two cents in as well. To make concourse worker properly retire. The point is, after sending SIGUSR2, it is important to wait for `concourse worker` process gone, with a certain timeout, of course. The `KillMode` directive is set to `process` because even after `concourse worker` process is gone, there are still some `/tmp/garden-init` processes remaining in the service's CGroup.

```ini
[Unit]
Description=Concourse Worker
After=network.target

[Service]
EnvironmentFile=/opt/concourse/etc/worker.conf
ExecStart=/opt/concourse/bin/concourse worker
KillMode=process
LimitNPROC=infinity
LimitNOFILE=infinity
TasksMax=infinity
Restart=on-failure
RestartSec=3
ExecStop=/bin/kill -USR2 $MAINPID ; /usr/bin/tail --pid $MAINPID -f /dev/null
TimeoutStopSec=300

[Install]
WantedBy=multi-user.target
```

And just in case, this is how my worker.conf look like:
```ini
CONCOURSE_WORK_DIR=/opt/concourse/worker
CONCOURSE_LOG_LEVEL=error
CONCOURSE_TSA_HOST=<tsa_address>:2222
CONCOURSE_TSA_PUBLIC_KEY=/opt/concourse/keys/tsa.pub
CONCOURSE_TSA_WORKER_PRIVATE_KEY=/opt/concourse/keys/worker
CONCOURSE_GARDEN_BIND_IP=0.0.0.0
CONCOURSE_GARDEN_DNS_SERVER=8.8.8.8
CONCOURSE_GARDEN_DESTROY_CONTAINERS_ON_STARTUP=
CONCOURSE_GARDEN_LOG_LEVEL=error
CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=error
CONCOURSE_BAGGAGECLAIM_BIND_IP=0.0.0.0
CONCOURSE_BAGGAGECLAIM_DRIVER=btrfs
```

**Comment by vito** [comment]
@antonu17 We actually have some movement in #3735 so I'm going to close this issue - thanks for the example! `KillMode=process` makes sense - we also set [`Delegate=yes`](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#Delegate=) to keep systemd from mucking with the Garden cgroup. For the moment we're maintaining [`.service` files for our smoke tests](https://github.com/concourse/concourse/tree/master/ci/deployments/smoke/systemd), which we plan on shipping with Concourse once they've solidified.

**Comment by ernado** [comment]
I'm so grateful that even such "ancient" issues are getting resolved, thank you and all participants!
