### ISSUE TITLE
Record pipelines creation/update time

### ISSUE THREAD

**Issue by aledeganopix4d** [concourse/concourse#4809]
##  What challenge are you facing?

Sometimes users (or overzealous automation scripts) set pipelines and forget about them forever.
These ghost pipelines stays there, their resources running, but no job was ever triggered and thus is difficult for a human operator as well for an automated tool to distinguish between a pipeline that was created 5 minutes ago and one that's been there for 5 months.
For the above reason is difficult to cleanup these types of pipelines.

## What would make this better?

By simply adding a column in the `pipelines` table of the DB called `last_updated` that would keep track of when the pipeline is created/updated (e.g. when the set-pipeline has been invoked) and then exposing this datum through `fly pipelines` as well would simplify enormously the job of cleaning up forgotten pipelines.

Also consider that this could benefit #4673 which is now unable to distinguish between just-created-pipelines and long-forgotten-pipelines.
This is also related to #3281. 

## Are you interested in implementing this yourself?

Yes: I think I could do it quickly, I just want to gauge consensus :)

**Comment by evanchaoli** [comment]
@aledeganopix4d Looks like we have same use case. IMO, we should consider a pipeline as a ghost by last build time rather than last update time. It's common that a mature pipeline is not updated for long time, but it keeps generating new builds.

**Comment by aledeganopix4d** [comment]
> @aledeganopix4d Looks like we have same use case. IMO, we should consider a pipeline as a ghost by last build time rather than last update time. It's common that a mature pipeline is not updated for long time, but it keeps generating new builds.

Sure, but we already have the last time a pipeline built something, what we don't know is when the pipeline itself was (re-)set.
This is why it's difficult to know what to do with pipelines that never ran a job...

**Comment by aledeganopix4d** [comment]
@vito do you mind leaving your thoughts on this one so I know if I should proceed or not? :smile: 

Thanks!

**Comment by aledeganopix4d** [comment]
Hello @vito, a gentle reminder to give a quick look at this proposal, please!

Thank you!

**Comment by vito** [comment]
@aledeganopix4d Hey, sorry for the wait, I've been trying to tidy up the v10 RFCs so my GitHub notifications slipped for a bit. This sounds perfectly reasonable and useful to me!
