### ISSUE TITLE
Allow resources to specify/validate config schema

### ISSUE THREAD

**Issue by ellerycrane** [concourse/concourse#481]
From slack:

https://concourseci.slack.com/archives/general/p1466098712001031

Quality of life improvement feature request: allow a resource/task/etc to define the schema for its config and then notify you if you're passing in stuff that isn't in that schema. Spent a good chunk of time debugging something that turned out to be me passing in a string to a config param instead of a list containing a single string.

**Comment by vito** [comment]
possibly relevant to #534

**Comment by jaresty** [comment]
I totally agree that json-schema would be great to have for concourse pipelines. In fact, there is tooling available for various IDEs that can validate against json-schema and would make developing pipelines easier.
