### ISSUE TITLE
Make it easier to identify the wiring of a resource into jobs in the pipeline view

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#4812]
## What challenge are you facing?
The pipeline view makes it easy to understand the relationship of a resource and the jobs in a pipeline. 
Furthermore, hovering over the resource, highlights all the connections ( grey solid or dotted line ) between the resource and all the jobs in the pipeline.
<img width="958" alt="screen-highlight" src="https://user-images.githubusercontent.com/1062564/69452683-3e1e8400-0d30-11ea-8f27-53f78dbb188f.png">

However, when there is sufficient complexity ( high # of resources into jobs resulting in a lot of connections ), it is difficult to accurately visualize the relationships from the pipeline view. For example, trying to see how many connections are emitted from `unit-image` resource flowing into `watsjs`, `upgrade`, `downgrade` & `testflight`, while the answer is all of them, it is not super clear from the UI.

It would be great if we can reduce the cognitive load in trying to pick out the connections when there are a lot of them.

## What would make this better?
One idea would be to have a different color for the connections upon the hover state on a resource.

**Comment by kcmannem** [comment]
what if on hover, we hide other resources connections? The fade/highlight on the lines it does currently is subtle.
