### ISSUE TITLE
atc/api unit test breaks

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4815]
## Bug Report

I started to hit this unit test error since last Thursday after I sync-ed code from the master branch. Before that, I never saw this error. Now even if I stay on the master branch, I still hit this unit test failure. 

I guess the failure could be related to my environment, but I didn't change any of my environment at all before and after I hit the failure. My Go version is 1.13.1. 

Anyone has idea what could cause the failure? Should we make this test case more compatible?

```
------------------------------
• Failure [0.508 seconds]
Pipelines API GET /api/v1/info/creds credhub get credhub health info returns error [It] returns configured creds manager with error
/Users/chaol/Documents/go-workspace/src/github.com/concourse/concourse.fork/atc/api/info_test.go:367

  Expected
      <string>: not ok
  to contain substring
      <string>: no such host

  /Users/chaol/Documents/go-workspace/src/github.com/concourse/concourse.fork/atc/api/info_test.go:380
------------------------------
•

Summarizing 1 Failure:

[Fail] Pipelines API GET /api/v1/info/creds credhub get credhub health info returns error [It] returns configured creds manager with error
/Users/chaol/Documents/go-workspace/src/github.com/concourse/concourse.fork/atc/api/info_test.go:380

Ran 863 of 863 Specs in 4.537 seconds
FAIL! -- 862 Passed | 1 Failed | 0 Pending | 0 Skipped
```

## Steps to Reproduce

Sync the latest code from master branch.

## Expected Results

Unit tests should pass.

## Actual Results

Hit one failure.

## Version Info

* Concourse version: master branch
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by pivotal-bin-ju** [comment]
Hi @evanchaoli,
I tested this case without a problem with `go1.12 darwin/amd64`.
I can still pass the test after I upgrade my golang to `go1.13.3 darwin/amd64`
And `go1.13.1 darwin/amd64` works as well.

I looked at the code from:
https://github.com/concourse/concourse/blob/master/atc/creds/credhub/manager.go#L126-L134

It seems you reached the code at line 132.

Do you have some dns proxy tool that is enabled? like `dnsmasq` or some modification of `/etc/hosts`?

**Comment by evanchaoli** [comment]
@pivotal-bin-ju Thanks for spending time on this issue. Finally I figured out the root cause. It was because I exported `http_proxy` in my environment, and the proxy returned 503. I have to use proxy to download some go mod.
