### ISSUE TITLE
Add fly command for scheduling a job

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#4820]
With algorithm V3, we will be scheduling *on demand* rather than every 10 seconds. This allows for more room for error, in the worst case where the scheduler for a job does not run when a user expects it to. In order to ease the pressure on this new scheduler logic, the beta version of v6.0.x can include a fly command to allow users to kick off the scheduler for a job manually.

The ultimate goal for the new scheduler is to have users never need to use this command, where the scheduler will always kick off at the exact time it needs to. But in the meantime, it would be nice to have a safe way to have a way to recover from the scheduler not running.

**Comment by vito** [comment]
* New API endpoint
* New `fly` command (`request-schedule-job`)
* Database method already exists: `(db.Job).RequestSchedule`
