### ISSUE TITLE
Worker infinite connection refused 7777 on "blank garden-properties.json"

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#4833]
When starting a worker, an infinite loop of errors results:
```
Nov 27 08:02:20 hci01.discord.local concourse_worker[1766]: {"timestamp":"2019-11-27T14:02:20.706028813Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
Nov 27 08:02:21 hci01.discord.local concourse_worker[1766]: {"timestamp":"2019-11-27T14:02:21.706246243Z","level":"info","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.retrying","data":{"addr":"127.0.0.1:7777","network":"tcp","session":"4.1.4"}}
Nov 27 08:02:21 hci01.discord.local concourse_worker[1766]: {"timestamp":"2019-11-27T14:02:21.706530757Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
Nov 27 08:02:22 hci01.discord.local concourse_worker[1766]: {"timestamp":"2019-11-27T14:02:22.706732310Z","level":"info","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.retrying","data":{"addr":"127.0.0.1:7777","network":"tcp","session":"4.1.4"}}
Nov 27 08:02:22 hci01.discord.local concourse_worker[1766]: {"timestamp":"2019-11-27T14:02:22.706922065Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
```

The cause seems to be this line at startup:
```
Nov 27 08:01:11 hci01.discord.local concourse_worker[1766]: {"timestamp":"2019-11-27T14:01:11.623524821Z","level":"error","source":"guardian","message":"guardian.failed-to-load-properties","data":{"error":"EOF","propertiesPath":"/opt/concourse/worker/garden-properties.json"}}
```

Checking /opt/concourse/worker/garden-properties.json shows an empty file.  After removing the empty file, things startup as expected.

## Version Info

* Concourse version: v5.7.1
* Deployment type (BOSH/Docker/binary): binary
* Did this used to work? Yes

**Comment by kallisti5** [comment]
This occurred after an upgrade from 5.6.0 to 5.7.1

**Comment by kallisti5** [comment]
The mentioned properties file is passed to garden without any checks of its contents:

https://github.com/concourse/concourse/blob/master/worker/workercmd/worker_linux.go#L121

So either:
  * Concourse needs to check the garden-properties.json for size > 0 before providing it to garden
  * Garden needs to "be better" and accept an empty garden-properties.json file like it doesn't exist.
  * Concourse needs to get away from the buggy / horrible garden :-)

**Comment by kallisti5** [comment]
Opened issue here:
```
https://github.com/cloudfoundry/guardian/issues/158
```

**Comment by kcmannem** [comment]
@kallisti5 containerd work is currently underway :), thanks for posting the issue to the garden team as well.

**Comment by tjhiggins** [comment]
Looks like garden fixed this issue (https://github.com/cloudfoundry/guardian/issues/158). Should I open a new issue to bump concourse's version of garden?

**Comment by pivotal-jamie-klassen** [comment]
@kallisti5 are you still experiencing this issue?

**Comment by kallisti5** [comment]
Yeah..  Saw it as of 5.7.1.   This tends to happen when concourse workers are left to "startup on their own at boot".    If you ```systemctl disable concourse``` then run a ```systemctl start concourse``` after boot, it doesn't tend to happen.
