### ISSUE TITLE
Set non-zero default value for CONCOURSE_REBALNCE_INTERVAL

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#4847]
# Issue
Large Concourse deployments can suffer from worker registration not being evenly distributed across the web nodes. This can result in a single web node having a majority of workers registered with it, with all the traffic being routed via that web node. This results in poor performance of the cluster and Concourse not effectively leveraging available resources.

# Current Solution
A Concourse operator can configure `CONCOURSE_REBALANCE_INTERVAL`  to a non-zero value resulting the workers re-registering at a set interval. This alleviates the un-even load issue. 

# Recommended Solution
Having a default value for `CONCOURSE_REBALANCE_INTERVAL` would work well for most deployments and prevent this issue.

**Comment by vito** [comment]
Note: In the real-world example where we saw this, the ATC that was showing high CPU & memory usage was not the same ATC that had the vast majority of workers registered to it (which would also result in more heartbeat-triggered queries). High resource overload might be decoupled from rebalancing, but this is still worth investigating independently.

**Comment by kcmannem** [comment]
check what we're doing in our ci/hh env to verify our soak tests and we can do this.

**Comment by xtreme-sameer-vohra** [comment]
Survey of our envs setting rebalance as of Feb 7th 2020

wings: 1h
old ci: 30m
hush-house: 2h
ci: 2h

**Comment by xtreme-sameer-vohra** [comment]
Taking a conservative factor of 2x with the largest duration 2x 2h = 4h
