### ISSUE TITLE
Document job scheduling

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4848]
* When does a job need to be scheduled?
* Document `fly schedule-job`
* Add as section under `Jobs`

**Comment by mstockd** [comment]
I was not able to find the documentation on `fly schedule-job` here: https://concourse-ci.org/jobs.html#managing-jobs
Is it already online somewhere?

**Comment by vito** [comment]
@mstockd The scheduling docs are here: https://concourse-ci.org/scheduler.html (looks like we have some broken images though 🤔)
