### ISSUE TITLE
Create a dev Dockerfile to support running integration tests on any OS

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4850]
Currently we use a GCP VM to run integration tests in a Linux environment. We should write a quick little Dockerfile so we can run integration tests in a sandboxed environment, from any OS. Also I'm really lazy and want to use Goland and Linux at the same time without having to push/pull from git.

Requirements:

Base image should come with:

- Golang (don't need ginkgo/gomega)
- Systemd

Things we need to run as part of Dockerfile:

- Download and extract runc binary to somewhere sensible
- Download and extract containerd binary to somewhere sensible
- Add chmod +x permissions if they're missing
- Start runc and containerd at their default socket locations by adding lines into systemd config (this will probably help: https://github.com/cirocosta/containerd-install)
- Restart systemd.. maybe? I don't know how it works because it's not monit......
- Possibly need to modify the superuser config in order to talk to runc and containerd sockets (but maybe not, because Docker?)
- Make sure that GOPATH subfolders are set up

Then in theory, to run it, we can just volume-map the local working directory in like `docker run -v $HOME/workspace/concourse:/go/src/github.com/concourse/concourse concourse/concourse:containerd-dev -f Dockerfile.containerd`.

**Comment by vito** [comment]
We may not be able to use systemd from a container, that might a host-level utility. Might be able to use `entrypoint` to run the processes, and also look at the spike branch from when we switched Garden to use the containerd runtime.

**Comment by cirocosta** [comment]
fixed by https://github.com/concourse/concourse/pull/4853
