### ISSUE TITLE
Worker memory usage

### ISSUE THREAD

**Issue by acarsercan** [concourse/concourse#4855]
Hi,

Running
-  Kubernetes 1.13.11
-  Concourse 5.6.1
- Stolon as psql
- 10 workers
- 3 web nodes

I have 0 pipelines in concourse and yet memory usage of workers seem to be unsual?

```

  | min | max | avg
-- | -- | -- | --
{pod_name="concourse-worker-4"} | 1.446 GiB | 1.507 GiB | 1.479 GiB
{pod_name="concourse-worker-8"} | 1.467 GiB | 1.483 GiB | 1.476 GiB
{pod_name="concourse-worker-6"} | 1.208 GiB | 1.312 GiB | 1.264 GiB
{pod_name="concourse-worker-0"} | 1.149 GiB | 1.212 GiB | 1.182 GiB
{pod_name="concourse-worker-3"} | 1.169 GiB | 1.187 GiB | 1.179 GiB
{pod_name="concourse-worker-1"} | 1.112 GiB | 1.175 GiB | 1.139 GiB
{pod_name="concourse-worker-2"} | 1.137 GiB | 1.137 GiB | 1.137 GiB
{pod_name="concourse-worker-7"} | 327 MiB | 1.429 GiB | 978 MiB
{pod_name="concourse-worker-9"} | 758 MiB | 817 MiB | 782 MiB
{pod_name="concourse-worker-5"} | 588 MiB | 671 MiB | 634 MiB
```

Is this expected?

**Comment by kcmannem** [comment]
wonder if this is related to https://github.com/concourse/concourse/issues/4861

**Comment by xtreme-sameer-vohra** [comment]
@acarsercan Does the deployment currently not have any pipelines or it never had any pipelines?

Also, could you share the MemStats block ( end of the [heap dump](https://github.com/concourse/concourse/wiki/Taking-a-Heap%2C-CPU-or-other-profile-Dump) ) for workers with high reported memory usage ?
