### ISSUE TITLE
Concourse worker failing on command 'iptables create-instance-chains'

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#486]
Concourse web+worker 1.3.1 running on standard AWS AMI.

With the simple [hello world](https://concourse.ci/hello-world.html) concourse demo, every run gives me this immediately:

Snippet:

`errors.errorString{s:\\\"iptables create-instance-chains: iptables v1.4.18: unknown option \\\\\\\"--wait\\\\\\\"\\\\nTry 'iptables -h' or 'iptables --help' for more information.`

This might be a guardian thing - I'm seeing `cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:44` in the log.

Full:

```
runc start: exit status 1: process_linux.go:329: running prestart hook 0 caused "exit status 2: {\"timestamp\":\"1466369914.619743586\",\"source\":\"kawasaki\",\"message\":\"kawasaki.hook.start\",\"log_level\":1,\"data\":{\"config\":{\"HostIntf\":\"wmcnismvpm14-0\",\"ContainerIntf\":\"wmcnismvpm14-1\",\"IPTablePrefix\":\"w--\",\"IPTableInstance\":\"mcnismvpm14\",\"BridgeName\":\"wbrdg-0afe0000\",\"BridgeIP\":\"10.254.0.1\",\"ContainerIP\":\"10.254.0.2\",\"ExternalIP\":\"172.31.30.19\",\"Subnet\":{\"IP\":\"10.254.0.0\",\"Mask\":\"/////A==\"},\"Mtu\":1500,\"DNSServers\":null},\"pid\":908,\"session\":\"1\"}}\n{\"timestamp\":\"1466369914.773725510\",\"source\":\"kawasaki\",\"message\":\"kawasaki.hook.panicked\",\"log_level\":3,\"data\":{\"config\":{\"HostIntf\":\"wmcnismvpm14-0\",\"ContainerIntf\":\"wmcnismvpm14-1\",\"IPTablePrefix\":\"w--\",\"IPTableInstance\":\"mcnismvpm14\",\"BridgeName\":\"wbrdg-0afe0000\",\"BridgeIP\":\"10.254.0.1\",\"ContainerIP\":\"10.254.0.2\",\"ExternalIP\":\"172.31.30.19\",\"Subnet\":{\"IP\":\"10.254.0.0\",\"Mask\":\"/////A==\"},\"Mtu\":1500,\"DNSServers\":null},\"error\":\"\\u0026errors.errorString{s:\\\"iptables create-instance-chains: iptables v1.4.18: unknown option \\\\\\\"--wait\\\\\\\"\\\\nTry `iptables -h' or 'iptables --help' for more information.\\\\n\\\"}\",\"pid\":908,\"session\":\"1\",\"trace\":\"goroutine 1 [running]:\\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc82000f5c0, 0x97e0e0, 0x8, 0x7f2251de0028, 0xc8201e1950, 0x0, 0x0, 0x0)\\n\\t/tmp/build/9674af12/garden-runc-release/src/github.com/pivotal-golang/lager/logger.go:131 +0xc5\\nmain.main.func1(0xc820199c08)\\n\\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:44 +0x13c\\npanic(0x8a3540, 0xc8201e1920)\\n\\t/usr/local/go/src/runtime/panic.go:443 +0x4e9\\nmain.main()\\n\\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:92 +0x171b\\n\"}}\npanic: iptables create-instance-chains: iptables v1.4.18: unknown option \"--wait\"\nTry `iptables -h' or 'iptables --help' for more information.\n [recovered]\n\tpanic: &errors.errorString{s:\"iptables create-instance-chains: iptables v1.4.18: unknown option \\\"--wait\\\"\\nTry `iptables -h' or 'iptables --help' for more information.\\n\"}\n\ngoroutine 1 [running]:\npanic(0x8a3540, 0xc8201e1950)\n\t/usr/local/go/src/runtime/panic.go:481 +0x3e6\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc82000f5c0, 0x97e0e0, 0x8, 0x7f2251de0028, 0xc8201e1950, 0x0, 0x0, 0x0)\n\t/tmp/build/9674af12/garden-runc-release/src/github.com/pivotal-golang/lager/logger.go:152 +0x698\nmain.main.func1(0xc820199c08)\n\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:44 +0x13c\npanic(0x8a3540, 0xc8201e1920)\n\t/usr/local/go/src/runtime/panic.go:443 +0x4e9\nmain.main()\n\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:92 +0x171b\n"
```

**Comment by jadekler** [comment]
Also, the AWS AMI iptables certainly does not seem to have a `--wait` option:

```
[ec2-user@ip-172-31-30-19 ~]$ man iptables | grep wait
[ec2-user@ip-172-31-30-19 ~]$
```

**Comment by jadekler** [comment]
It seems as though ubuntu does have this option:

```
ubuntu@ip-172-31-44-239:~$ man iptables | grep wait
       -w, --wait
              the program wait until the exclusive lock can be obtained.
ubuntu@ip-172-31-44-239:~$
```

I'm no longer sure if this issue belongs on this project. This might be something to document / check before allowing users to fall over / get frustrated by, or perhaps it should get fixed in guardian and there's no problems here.

**Comment by jadekler** [comment]
After reading guardian explicitly state that it only supports Ubuntu, I'm leaning towards maybe making a note on the concourse readme or some check during concourse startup that mentions ubuntu must be used.

**Comment by thecodethinker** [comment]
This happens to me too, but only sometimes, and it usually doesn't happen if i try re running the test.

**Comment by vito** [comment]
This should be fixed in 1.4.0. We've stopped seeing it ourselves.

**Comment by jackgray** [comment]
I am getting this error but only for this package/image. I see above about making a note that ubuntu must be used.. Is concourse not supported on mac? I'm not a docker expert but thought that was the entire point of using containers to make it agnostic. The quickstart has instructions for launching the container on mac. This is the only docker image I'm having issues with and I am following the installation/getting started guide straight forward.  I know this is an old issue but have been stuck for a while not much seems to be out there. I am running on ARM (M1) but again docker runs all my other containers just fine. Thanks for any help!

**Comment by taylorsilva** [comment]
I wonder if you need to add `platform: "linux/amd64"` to your docker-compose?
https://erica.works/docker-on-mac-m1/

**Comment by taylorsilva** [comment]
FYI, we don't test concourse on any ARM machines, linux or mac. We only have test machines for amd64.
