### ISSUE TITLE
Monitor actual memory by Concourse

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#4861]
## What challenge are you facing?
Monitoring the memory consumed by Concourse as reported by the OS changed behaviour after the introduction of [MADV_FREE](https://golang.org/doc/go1.12#runtime). While, this is a performance enhancement for the Go runtime, it negatively affects a Concourse operator's ability to measure memory consumed by Concourse.

We have observed cases where the actual Concourse memory in use ( 300 MB ) vs memory allocated as per the OS ( 20 GB ) have large discrepancies making it hard for the operator to understand how the system is performing - should they be concerned, do they need to scale the cluster ?

## What would make this better?

Relying on the OS allocated memory metric (eg. top -> RES ) can be misleading. It would be useful if there was an another metric in addition to the SLIs that could be monitored for health of the system.

**Comment by cirocosta** [comment]
Hey,

> It would be useful if there was an another metric in addition to the SLIs that could be monitored for health of the system.

If I understood correctly ("go uses `madvise(2)` w/ `MADV_FREE`, leaving to the kernel to releasing mem when under pressure"), I *think* the best we can do here is either/both:

1. rely on the mem statistics from the point of view of the go runtime
  - with the drawback of not accounting cgo allocations (maybe a reason to go towards https://github.com/concourse/concourse/issues/4342 😁 )
2. rely on cgroup's report of inactive mem (as that's what `madvise` ends up turning the memory advised as `free` into) - that's a field under `memory.stat`, which IIRC cadvisor takes into consideration when estimating what the working set is

While `1` is something that we can control from `concourse/concourse` perspective (e.g., ensuring that we give such metric to all emitters in the set of metrics reported), `2` seems more like an ops thing.

Wdyt?

thx!

**Comment by xtreme-sameer-vohra** [comment]
Thanks @cirocosta 

1 seems useful, so we're equipping operators to understand how the system is perform. [ReadMemStats](https://golang.org/src/runtime/mstats.go?s=5620:15036#L445) would allow that, however, it executes with a `stopTheWorld ` context. Which, would not be something we want to run too often.

I don't have much context on 2, I'll need to do some more research :)

**Comment by xtreme-sameer-vohra** [comment]
[This](https://bwplotka.dev/2019/golang-memory-monitoring/) post provides detailed context and tips ( similar to what @cirocosta  )
