### ISSUE TITLE
Add containerd unit and integration tests to CI

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4878]

**Comment by xtreme-sameer-vohra** [comment]
Unit tests might be already running as we do a `ginkgo -r`. We should verify that

**Comment by pivotal-bin-ju** [comment]
unit tests for `containerd` are run in main pipeline.
https://nci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/44#L5de9418b:1135:1265

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
Today I:
- double check  the unit test for containerd is already run in the main pipeline.
- moved the `Dockerfile` in worker/backend/integration to the `integration` dir in  `ci` repo.
- the new `integration` docker file is `FROM concourse/unit`, with containerd env ready for both the regular integration test and `containerd` integration test.
- docker pushed the image to `concourse/integration`.

**NEXT**:
- modify `concourse.yml` to use the image `concourse/integration` as the image for integration test
- add script in `testflight` to run `containerd` integration test.
- verify the pipeline `testflight` in `nci`.

**Comment by xtreme-sameer-vohra** [comment]
Looks like there are still some steps remaining as per Bin's comment. Moving this back to in progress but paused.

**Comment by cirocosta** [comment]
integration: https://github.com/concourse/ci/pull/253
