### ISSUE TITLE
unknown capability "CAP_AUDIT_READ"

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#488]
Server: Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-9abea4fb
Concourse version: 1.3.1

With the simple [hello world](https://concourse.ci/hello-world.html) pipeline, my worker blows up with the following error:

```
say-hello
runc start: exit status 1: unknown capability "CAP_AUDIT_READ"
```

This seems to be a [runc requirement](https://github.com/opencontainers/runc/blame/master/libcontainer/SPEC.md#L168).

I assume my image is missing some capability or software - any ideas what it might be?

**Comment by jadekler** [comment]
Made a bug for this over in guardian: https://github.com/cloudfoundry-incubator/guardian/issues/38

**Comment by DenisIzmaylov** [comment]
I have the same issue.

**Comment by DenisIzmaylov** [comment]
@jadekler did you solve that? I have the same issue on clean Ubuntu 14.04.4 LTS:

![image](https://cloud.githubusercontent.com/assets/1690596/16413136/b8c8a012-3d38-11e6-96ce-3d9086f237fe.png)

**Comment by DenisIzmaylov** [comment]
The issue is fixed. It was related on Ubuntu 14.04.4 kernel version. I've [explained details here].

**Comment by DenisIzmaylov** [comment]
The issue is fixed. For me it was related on Ubuntu 14.04.4 kernel version. I've [explained details here](https://github.com/cloudfoundry-incubator/guardian/issues/38#issuecomment-229208740).

When I checked it:
```bash
$ uname -r
3.13.0-88-generic
```
The example above means I had a kernel version is 3.13 while Concourse (and guardian) requires a 3.19+ kernel. It means I had have to update it. For [Ubuntu 14.04.4 LTS](https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Server) it was a quite simple:
```bash
sudo apt-get install --install-recommends linux-generic-lts-wily 
```

Then I reboot the server and now everything is working. You can read full discussion [here](https://github.com/opencontainers/runc/issues/924#issuecomment-229207866). Have a good update! :)

**Comment by vikas027** [comment]
Well, I am seeing this even in latest kernel 

```
root@box66:~/concourse-tutorial/tutorials/basic/task-hello-world# fly -t tutorial execute -c task_hello_world.yml
executing build 5 at https://concourse.<my-domain>/builds/5
initializing
runc run: exit status 1: container_linux.go:348: starting container process caused "unknown capability \"CAP_AUDIT_READ\""

errored
root@box66:~/concourse-tutorial/tutorials/basic/task-hello-world# uname -r
4.16.3-1.el7.elrepo.x86_64
root@box66:~/concourse-tutorial/tutorials/basic/task-hello-world#
```

**Comment by SergeyMuha** [comment]
I am seeing same issue. 
Concourse has been installed by
#wget https://concourse-ci.org/docker-compose.yml
#docker-compose up -d
then #fly --target tutorial login --concourse-url http://127.0.0.1:8080
[sergey:centos_work_vm:~/ci-cd/concourse/concourse-tutorial/tutorials/basic/task-hello-world]
██fly -t tutorial execute -c task_hello_world.yml
executing build 2 at http://127.0.0.1:8080/builds/2 
initializing
runc run: exit status 1: container_linux.go:348: starting container process caused "unknown capability \"CAP_AUDIT_READ\""

errored
[sergey:centos_work_vm:~/ci-cd/concourse/concourse-tutorial/tutorials/basic/task-hello-world]
██docker -v
Docker version 18.03.0-ce, build 0520e24

**Comment by predatorian3** [comment]
@SergeyMuha , I would do what @DenisIzmaylov did and check your Kernel version using 

```bash
uname -a 
```

or

```bash
uname -r
``` 

and verify that your kernel is above 3.13+. I ran into this issue today but I am on Kernel 3.10 on an Oracle Linux 7 server. Currently testing this out as well to see if I can bump up to a newer kernel version.

**Comment by predatorian3** [comment]
Well, OEL uses 3.10 or at least that's what our internal repositories have. So I'm going to try the Docker Images and see if that works. 

https://github.com/cloudfoundry/guardian/issues/38#issuecomment-461941296
