### ISSUE TITLE
Don't pile-on slow API requests when polling against the dashboard

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4885]

**Comment by vito** [comment]
I don't think the pipeline UI is affected by this; updated the title.

**Comment by zoetian** [comment]
Dragging while the dashboard requests (i.e list pipelines) are still inflight can cause some weird UI changes. For instance, the users may not be able to see the latest pipeline cards update after dropping, or trying to re-order the pipeline card that is no longer existed after the latest update from dashboard request remove such card. Jamie and I thought about 3 diff. ways to handle it:

1) display a loading spinner when this "drag-while-request-not-finished" situation happens
2) cancel the dropping UI
3) disable the dragging UI while waiting for the latest changes 

(caveat: for a really fast and frequently updated api requests, user may run into the scenario that they attempted to re-order the pipeline cards for multiple times but all attempts were disabled/ cancelled).

**Comment by zoetian** [comment]
We're going to move forward with 1.
* when a pipeline card is dropped, the pipeline list should go into a loading state that looks a bit like
![Screen Shot 2020-01-09 at 9 53 39 AM](https://user-images.githubusercontent.com/6901732/72077845-f3e46880-32c5-11ea-82a3-c896fe48dcd3.png)

where the cards have opacity 0.5 and cannot be interacted with (`pointer-events: none`).
* when a pipeline card is dropped, an `OrderPipelines` call should be made, and a `ListAllPipelines` call be made immediately after
* the list should stay in this loading state until the `ListAllPipelines` call finishes.
