### ISSUE TITLE
build_resource_config_version_inputs is never cleaned up?

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4887]
## Bug Report

Today during debugging an issue, my team noticed that table `build_resource_config_version_inputs` has more than a million of tuples, even tuples with `build_id: 1`.

Then I quickly went through the related code. The scheduling algorithm is very complex, so I'm not sure if I understand correctly. As far as I can see, `build_resource_config_version_inputs` is used during scheduling builds, thus once a build finishes, its related tuples should be deleted from `build_resource_config_version_inputs`.

## Steps to Reproduce

On any Concourse cluster, log to the Concourse database, and:

```sql
select count(*) from build_resource_config_version_inputs
select * from build_resource_config_version_inputs limit 5
select count(distinct(build_id)) from build_resource_config_version_inputs
```

## Expected Results

Ideally, `build_resource_config_version_inputs` should be a small table.

## Actual Results

The table is huge, seems never get cleaned up.

## Version Info

* Concourse version: 5.7.2
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by SimonXming** [comment]
Actually, we are investigating potential memory leak. We observed `LoadVersionsDB` take 95+% of memory and keep growing. I guess this huge `build_resource_config_version_inputs` table could cause continuously memory growing. WDYT?
