### ISSUE TITLE
Support for more modes than success/failure

### ISSUE THREAD

**Issue by annaken** [concourse/concourse#4888]
## What challenge are you facing?

We have a number of pipelines that have more than two exit modes, typically:
* success
* failure
* nothing to do here

For example, one pipeline only does stuff if the last git commit was not a merge -if it was a merge we just exit the script immediately. But we're forced to flag this as either a success or failure, when really it's neither. 

Technically the script runs successfully, so we usually choose success, but that makes the notifications very noisy because on_success is triggered every time.

Another pipeline we have runs bazel, which uses a whole host of exit codes. It exits 4 if no tests were found, but concourse interprets this as failure, so we had to wrap bazel in an additional script to re-interpret 4 as 0.

I appreciate this problem is partially a reflection of bash exit codes, but it makes for somewhat misleading pipelines.

## What would make this better?

One option would be to allow a pipeline to access on_abort, since that already exists.

Alternatively, maybe we could have some other "nothing happened" status/exit code.

## Are you interested in implementing this yourself?

I don't know enough to implement this myself but am willing to help if I can.

**Comment by tjhiggins** [comment]
Would also appreciate an alternative status like 'skipped' of 'nothing happened'. Have a series of tasks that may or may not do any work depending on the values in a gcs folder.
