### ISSUE TITLE
Cannot run dotnet core tests in concourse ci

### ISSUE THREAD

**Issue by vector623** [concourse/concourse#4892]
## Bug Report

I cannot successfully run dotnet tests on concourse ci, via fly CLI.

## Update

Just tested with Concourse CI in Docker on Debian 10 as base host and things work as expected.

`uname -a` for Debian machine is:

```
Linux granite.xounges.net 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

So, the problem seems to be the runc containers, when concourse is running on a Ubuntu 18.04 base host.  Some other searching seems to point to problems with Linux kernel 5.0.0.

This is probably unrelated to Concourse CI.  You can close this issue out anytime.

## Steps to Reproduce

Clone this repo: `https://github.com/vector623/concourse_dotnet_repro`

Chdir to repo.

Execute job via fly CLI: `fly -t concourseci e -c run_dotnet_test.yml -i repo=.`

## Expected Results

Here's the normal `dotnet test` output for this project:

```
nodev@xounges.net:~/gits/tmp/concourse_dotnet_repro git:(master)
> dotnet test
Test run for ~/gits/tmp/concourse_dotnet_repro/PrimeService.Tests/bin/Debug/netcoreapp2.2/PrimeService.Tests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 11
     Passed: 11
 Total time: 1.5319 Seconds
```

## Actual Results

```
+ dotnet test
/usr/share/dotnet/sdk/3.1.100/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6004: The specified task executable location "/rootfs/usr/share/dotnet/dotnet" is invalid. [/tmp/build/e55deab7/repo/PrimeService/PrimeService.csproj]
failed
```

## Additional Context

I can run these dotnet tests in the dotnet sdk docker image, if I create a container via Docker CLI.  This issue seems to be specific to Concourse CI's runc configuration.

## Version Info

* Concourse version:
    * fly CLI version: 5.7.2
    * Concourse docker image: concourse/concourse@sha256:ada57604edea58db43b35eecc6853a17ce451ff41f98b0809d1620018dea0b6a (latest as of today)
* Deployment type (BOSH/Docker/binary):
    * docker
* Infrastructure/IaaS:
    * docker image running in Ubuntu 18.04 in GCP
    * uname -a: Linux 13d31566-d994-4042-549e-a686b3e26171 5.0.0-1026-gcp #27~18.04.1-Ubuntu SMP Fri Nov 15 07:40:39 UTC 2019 x86_64 GNU/Linux
* Did this used to work? No

**Comment by deniseyu** [comment]
Hey @vector623, are you normally able to run these in an out-of-the-box Ubuntu environment? I haven't used .NET before but I'm guessing based on [this page](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904) that a .NET environment doesn't ship by default in the public Ubuntu docker images, so you may have to build a custom image?

**Comment by vector623** [comment]
I followed the official Microsoft documentation to set up on Ubuntu:

https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804

I also ran this on a local Ubuntu box, in addition to Ubuntu in GCP.

**Comment by vector623** [comment]
Also, I ran I used this docker image for the task: mcr.microsoft.com/dotnet/core/sdk

It's Microsoft's image for building dotnet core.  This one is based on deb 10 and I experienced this issue with a Ubuntu docker host + Deb10/Ubuntu1804 build images.

**Comment by deniseyu** [comment]
Thanks for doing extra investigation and updating the issue!

**Comment by vector623** [comment]
Happy to help!  Just getting started on Concourse CI, but so far it seems to have a lot of promise.

**Comment by zlzforever** [comment]
I have this issue too. And the workaround is:
![image](https://user-images.githubusercontent.com/3038592/180921802-cc95c42c-fba4-4712-b77f-df8985fe3d58.png)
I don't know why run dotnet build command in the repo folder, then used "/rootfs/usr/share/dotnet/dotnet". Is it a concourse ci load image enviroment issue ? or dotnet sdk issue?
