### ISSUE TITLE
use-case: handling *lots* of git repos effectively (probably by caching)

### ISSUE THREAD

**Issue by devcurmudgeon** [concourse/concourse#49]
I'd like to use Concourse to CI something like a full-stack OS integration - bootloader, kernel, middleware, apps.  Based on practical experience some sizing of the typical load for this:

- 100-1000 individual software components. 

- The components start life on one or more remote (possibly public) git servers - around 50-200GB of git data. Some of the repos change every day, some rarely.

- Depending on number of cores, processor performance of build worker, building the full stack can take anywhere from 1-48 hours.

Ideally Concourse would allow a persistent local cached resource to serve the git data for a given build worker. Seems it needs to be local to the worker, because cloning 50-200GB from remote per worker per run will be a) slow and b) expensive on public infrastructure. Need to be able to check for updates to update the local mirror(s) too.

Also, would like to re-use artifacts (a cache of built components) from previous runs if nothing has changed, and drop old artifacts to avoid using an infinite amount of storage.

**Comment by vito** [comment]
This should indeed be something made much better by our "caching" track:

https://www.pivotaltracker.com/n/projects/1059262

**Comment by vito** [comment]
The bulk of this is there now as of 0.64. Yay!

http://concourse.ci/release-notes.html#v0.64.0
