### ISSUE TITLE
Replace all queries that query by `version` with `version_md5`

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4905]

**Comment by vito** [comment]
@clarafu @xtremerui Is this done through https://github.com/concourse/concourse/pull/4886 and the follow-up https://github.com/concourse/concourse/pull/4972 or was there more to it?

**Comment by xtremerui** [comment]
This is done. There wasn't much to do for the replacing part. Just some cleanup https://github.com/concourse/concourse/pull/4886/commits/4935bd8aa25c3af76dcfd3aa372d7aa72d20300d, whihc is merged in already. @vito
