### ISSUE TITLE
Release v5.7.3

### ISSUE THREAD

**Issue by YoussB** [concourse/concourse#4908]
Placeholder for the release v5.7.3:
- [ ] https://github.com/concourse/git-resource/issues/294

**Comment by evanchaoli** [comment]
@YoussB I would suggest include #4846

**Comment by deniseyu** [comment]
hey @evanchaoli v5.7.3 is planned as only a CVE patch, #4846 will be part of v5.8.0 which will be out shortly!

**Comment by YoussB** [comment]
decided on skipping 5.7.3 in favor of 5.8.0
