### ISSUE TITLE
Anyway to get concourse spin up AWS EC2 instances without bosh?

### ISSUE THREAD

**Issue by farahfa** [concourse/concourse#491]
Hello,

Is there a way to spin up EC2 instances from Concourse via pipeline?

Fadi

**Comment by jadekler** [comment]
@farahfa You could use the [AWS CLI](https://aws.amazon.com/cli/) as part of a bash script in a job.

**Comment by MerlinDMC** [comment]
@farahfa I use terraform to spin up a small setup for playing around: https://github.com/MerlinDMC/concourse-aws

Feel free to use that as a starting point.

**Comment by vito** [comment]
This won't be supported by Concourse itself; there are simply too many ways to do it, and it feels wrong for us to pick one or implement one ourselves. Worker autoscaling is out-of-scope for Concourse. You can use generic resources like [Terraform](https://github.com/ljfranklin/terraform-resource) for this if you want.
