### ISSUE TITLE
Allow copying auth token even when browser copy/paste is disabled

### ISSUE THREAD

**Issue by Logiraptor** [concourse/concourse#4914]
## What challenge are you facing?

I'm supporting an operations team using concourse. The organization has the policy to disable automated copy/paste in the browser. Copying using the 'manual' (ctrl+c / right-click + copy) methods still work as expected. This means that when logging in to fly on a remote machine, two things happen:

1. The browser is unable to send the token to fly automatically
2. The user is unable to click the copy token to clipboard button

Our current workaround is to right-click+inspect the 'copy token to clipboard' button and copy the token out of the `data-clipboard-text` attribute.

![Screenshot from 2019-12-17 13-51-06](https://user-images.githubusercontent.com/1882804/71029100-4d48e580-20d4-11ea-9296-39a33444fb8f.png)

Also of note, we checked the value of `ClipboardJS.isSupported()` and it returns `true`, so it doesn't seem easy to automatically determine if the feature is blocked. We have validated this behavior on Chrome and Firefox.

## What would make this better?

We think it would be valuable to somehow display the token in a box so it can be highlighted and copied manually by the user. This would mirror the approach taken for example on GitHub with repository remote urls:

![Screenshot from 2019-12-17 13-52-42](https://user-images.githubusercontent.com/1882804/71029212-85e8bf00-20d4-11ea-88b2-e89ad980653b.png)

## Are you interested in implementing this yourself?

We're open to submitting a PR if there is a path to getting it accepted.

**Comment by xtremerui** [comment]
I think this is a valid use case. We could iterate on the UI once the PR is submitted. Thanks!

**Comment by Logiraptor** [comment]
@xtremerui We created a super-simple PR, #4951, would you mind taking a look?

**Comment by pivotal-jamie-klassen** [comment]
There's still useful discussion on #4951!

**Comment by JonathanGrant92** [comment]
I'm trying to paste my authentication token using ctrl+v in the admin cli after gh auth login > github.com > authentication token, but the string does not paste. I enabled ctrl+c/ctrl+v under cli properties. I check that I captured the string by pasting in an editor. It's just not working when cli is running gh auth login operation. It pastes when cli does not run that operation, so the problem is with gh-cli program, not my cli. Please help!

**Comment by zoetian** [comment]
@JonathanGrant92 my late night brain is a little bit fuzzy here... 
Did you get this error purely from the cli? If so, do you mind creating a new issue for it and mention this issue as well? 
Seems like there are something interesting related to gh cli 🤔
