### ISSUE TITLE
Ability to see who Paused a job 

### ISSUE THREAD

**Issue by Geeman201** [concourse/concourse#4917]
## What challenge are you facing?
We are a team of about 60 developers and have ~600 pipelines. At a high level most do `build -> dev -> stg -> prd`

Over the christmas period we want all pipelines/job/builds to be unpaused so if there is a production incident we can roll forwards a fix. 

We often spend a lot of time trying to figure out who paused a job and why.

## What would make this better?
When a job is paused being able to see who paused it (this might be a quickwin that gets most of the way there) and enter an optional comment as to why that individual paused the pipeline

## Are you interested in implementing this yourself?
In the immediate future I will be unable to.

**Comment by evanchaoli** [comment]
Not sure if you have realized the audit log feature. Turning on and watching audit logs may archive what you need.
