### ISSUE TITLE
[Firefox][UI] Drag-and-drop state doesn't save

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#4920]
## Bug Report

Using Firefox, I can drag pipelines around on the main dashboard. Changes are not saved though and everything I drag gets reset to it's original position

## Steps to Reproduce

Using Firefox, drag a pipeline to another position. Wait ~5s and the tile will go back to its original position

## Expected Results

The tile state is saved.

## Actual Results

Tile state is not saved.

## Version Info

* Concourse version: v5.7.2
* Browser (if applicable): Firefox v71
* Did this used to work? Dragging didn't even work before! At least it drags now.

**Comment by zoetian** [comment]
I also noticed that even on Google Chrome, after drag and drop, the UI would still have this `flakey` behaviour where the dragged pipeline card would come back to its original position and wait for a second, then go to its dropped position.

**Comment by taylorsilva** [comment]
Tested on ci with Firefox right now and it's saving state again! Looks like the dashboard changes fixed this.
