### ISSUE TITLE
invalid configuration for build_log_retention using concourse image: concourse/concourse:4.2.1

### ISSUE THREAD

**Issue by lxiaopei** [concourse/concourse#4931]
## Bug Report

> (summarize the issue)
Using image: concourse/concourse:4.2.1
in my job, I used 
jobs:
- name: run-job
  build_log_retention:
    days: 7
  plan:
...
error: invalid configuration:
unknown/extra keys:
  - jobs[0].build_log_retention
## Steps to Reproduce

> (please include any pipelines/tasks using https://gist.github.com)

## Expected Results
pipeline can run successfully
> (what did you expect to happen?)

## Actual Results

> (what actually happened?)

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version:
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by pivotal-jamie-klassen** [comment]
[`build_log_retention`](https://concourse-ci.org/jobs.html#job-build-log-retention) was added in [v5.2.0](https://github.com/concourse/concourse/releases/tag/v5.2.0#v520-note-8) -- please upgrade!

**Comment by kirillbilchenko** [comment]
test

**Comment by kirillbilchenko** [comment]
test

**Comment by kirillbilchenko** [comment]
test
