### ISSUE TITLE
Expose build ENV variables to tasks

### ISSUE THREAD

**Issue by ellerycrane** [concourse/concourse#494]
[As discussed in slack](https://concourseci.slack.com/archives/general/p1466713520002433), it would be useful to have access to the same [running build metadata ENV variables available to resources](http://concourse.ci/implementing-resources.html#section_resource-metadata) when running Tasks. 

The most specific use case would be to write tasks that can publish/log notifications about specific jobs that fail without having to write an entire resource type to accomplish it. 

Slack conversation:

- https://concourseci.slack.com/archives/general/p1466711283002415
- https://concourseci.slack.com/archives/general/p1466713125002426
- https://concourseci.slack.com/archives/general/p1466713520002433
- https://concourseci.slack.com/archives/general/p1466714624002439

**Comment by vito** [comment]
Resources are the correct way to express this. For now that means you'll have to write one every now and then. That problem will go away over time as more and more people provide a resource for each service.
