### ISSUE TITLE
Only perform checks for resources that are used as inputs

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4944]
Right now we perform `check`s across all resources. This is redundant for resources that are only ever used as `put` steps, since these versions won't be used for scheduling at all.

For better or for worse, lots of users have `put`-only resources for things like notifications and collecting build metadata, so this could be a nice short-term win now that we have this information readily available in the `job_inputs` table.

Some context in #4940

**Comment by evanchaoli** [comment]
Per https://github.com/concourse/concourse/issues/4940#issuecomment-568083030, this change depends on table `job_inputs` and `job_inputs` will only be available from 6.0.

**Comment by tkellen** [comment]
Yes please!

**Comment by vito** [comment]
This was implemented by https://github.com/concourse/concourse/pull/5149 :slightly_smiling_face:
