### ISSUE TITLE
Allow setting maximum resource_config_versions per resource

### ISSUE THREAD

**Issue by ryanaross** [concourse/concourse#4946]
##  What challenge are you facing?

Background: We are running Concourse 5.6.0 deployed to GKE using the helm chart, using CloudSQL as a backend. Our CloudSQL performance kept getting worse. I looked at slow queries and noticed most had to do with the resource_config_versions table.

I connected to our CloudSQL instance and noticed the resource_config_versions had 4.5 million records.

We tested `TRUNCATE TABLE resource_config_versions CASCADE;` in sandbox and it seemed to work okay.

This is what happened to our 32 CPU CloudSQL instance when we ran that on our largest Concourse instance:

![Screen Shot 2019-12-23 at 9 27 43 AM](https://user-images.githubusercontent.com/7442411/71373566-84077b80-256c-11ea-8e38-e394ac51e14a.png)

Our developers have created pipelines that look like this:
```
- name: trigger
  source:
    interval: 1s
  type: time
```
Which is certainly the problem, but not one we can easily control since pipelines are written by a wide variety of people.

## What would make this better?

If we could set a global limit on the number of resource versions to keep, say 100 or 1000, that would be a huge benefit for us. 

## Are you interested in implementing this yourself?

Out of my range of expertise I'm afraid.

**Comment by vito** [comment]
I think this will actually be addressed in v6.0. :thinking: It includes a massive rework of the scheduler, and it no longer loads up the entire version history of resources into memory. This is likely the source of your database performance woes, as we've observed the same in our own long-lived environments.

IMO the underlying need here is to be able to have timed triggers without having an ever-growing history of useless versions. I have a very loose start on that in [RFC #27](https://github.com/concourse/rfcs/pull/27). More context here: https://blog.concourse-ci.org/core-roadmap-towards-v10/#rfc-27-trigger-resources
