### ISSUE TITLE
Build fails with an error "could not read file "metadata.json" from tar"

### ISSUE THREAD

**Issue by timothyakampa** [concourse/concourse#495]
I have installed concourse on a Debian jessie box. Am trying out pipeline examples from the user guide but I keep getting this cryptic error. `could not read file "metadata.json" from tar`

Here is my console stack trace.

`Pulling ubuntu@sha256:f1b592e2de671105255a0c0b7b2f71a92b829403e8fc845e3482667ecc301780...
sha256:f1b592e2de671105255a0c0b7b2f71a92b829403e8fc845e3482667ecc301780: Pulling from library/ubuntu
5ba4f30e5bea: Pulling fs layer
6874f9870f5f: Pulling fs layer
4c876570bd7d: Pulling fs layer
10fb34ebccea: Pulling fs layer
10fb34ebccea: Waiting
4c876570bd7d: Verifying Checksum
4c876570bd7d: Download complete
6874f9870f5f: Verifying Checksum
6874f9870f5f: Download complete
10fb34ebccea: Verifying Checksum
10fb34ebccea: Download complete
5ba4f30e5bea: Verifying Checksum
5ba4f30e5bea: Download complete
5ba4f30e5bea: Pull complete
6874f9870f5f: Pull complete
4c876570bd7d: Pull complete
10fb34ebccea: Pull complete
Digest: sha256:f1b592e2de671105255a0c0b7b2f71a92b829403e8fc845e3482667ecc301780
Status: Downloaded newer image for ubuntu@sha256:f1b592e2de671105255a0c0b7b2f71a92b829403e8fc845e3482667ecc301780

Successfully pulled ubuntu@sha256:f1b592e2de671105255a0c0b7b2f71a92b829403e8fc845e3482667ecc301780.

could not read file "metadata.json" from tar`

**Comment by vito** [comment]
Make sure you're running Linux kernel 3.19+

**Comment by timothyakampa** [comment]
Upgrading the kernel fixed the issue. However, I don't know if this a long term solution.

**Comment by vito** [comment]
@timothyakampa It is - that's documented here: https://concourse.ci/binaries.html#prerequisites

I've opened an issue previously on Guardian here: https://github.com/cloudfoundry-incubator/guardian/issues/29 - so I'll close this one since it's not really an issue with us (and it's documented)
