### ISSUE TITLE
Hijacking one-off build fails

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#4952]
## Bug Report

When a `fly execute` is kicked off, fly outputs the `url` to the one-off build in form;

```
executing build SOME_BUILD_ID at https://ci.concourse-ci.org/builds/SOME_BUILD_ID
```

Opening the link in the browser allows anyone to follow the progress of the build. 
However, performing `fly hijack -u https://ci.concourse-ci.org/builds/SOME_BUILD_ID` results in;
```
error: Team in URL doesn't match the current team of the target
```

This can be worked around by passing hijack the manually formatted url with the team in the path `fly -t nci hijack -u https://ci.concourse-ci.org/teams/SOME_TEAM_NAME/builds/SOME_BUILD_ID`.

Note: The `url` in the form of `https://ci.concourse-ci.org/teams/SOME_TEAM_NAME/builds/SOME_BUILD_ID` works for fly hijack but doesn't in the browser, as the path is not handled by the server (web node). User is taken to the pipelines page.

## Steps to Reproduce

See above

## Expected Results

The url outputted by fly should allow one to hijack the build ( fly could default to using the logged in team )

## Actual Results

Received the error 
```
error: Team in URL doesn't match the current team of the target
```

## Version Info

* Concourse version: 5.7.2
* Did this used to work? Not sure

**Comment by pivotal-jamie-klassen** [comment]
In terms of 'Did this used to work?' the `-u` feature for fly was added in v3.7.0 via concourse/fly#164.
