### ISSUE TITLE
testflight's test for mounting input in the same place as output fails to materialize volume

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#4964]
### Bug Report

As observed by @vito and @clarafu, `testflight` running on nci.concourse-ci.org
recently started having the test where a task has the path of an `input` the
same as an `output`:

https://github.com/concourse/concourse/blob/f8ae6998684f05a1f93e0b9b3be03ab6f20007d5/testflight/volume_mounting_test.go#L39-L43

https://github.com/concourse/concourse/blob/f8ae6998684f05a1f93e0b9b3be03ab6f20007d5/testflight/fixtures/volume-mounting.yml#L175-L180

https://nci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight/builds/283#L5e0e4e39:1220

The timing of the failures (since this morning - 2020/01/03) seem to be quite
related to the moment of the bump from GKE 1.14.x to 1.15.4 which incurred in a
bump from Linux 4.15.x to 5.0.0.

Looking inside the task and inspecting the logs from the worker:

```json
{
  "timestamp": "2020-01-03T18:42:15.750634604Z",
  "level": "error",
  "source": "baggageclaim",
  "message": "baggageclaim.api.volume-server.create-volume-async.create-volume.failed-to-materialize-strategy",
  "data": {
    "error": "device or resource busy",
    "handle": "4af3ce40 -b08e-4481-6532-c63afd635f44",
    "session": "3.1.4500.1"
  }
}
```

```json
{
  "timestamp": "2020-01-03T18:42:15.750705655Z",
  "level": "error",
  "source": "baggageclaim",
  "message": "baggageclaim.api.volume-server.create-volume-async.failed-to-create",
  "data": {
    "error": "device or resource busy",
    "handle": "4af3ce40-b08e-4481-6532-c63afd635f44 ",
    "privileged": false,
    "session": "3.1.4500",
    "strategy": {
      "type": "cow",
      "volume": "a6ad87cf-6162-44cb-5c80-2fb8854b2e97"
    }
  }
}
```

### Steps to Reproduce

"reproduce":

1. run the `testflight` job in the pipeline
  - this will have the container running in our new linux 5.0-based machines on top
     of a privileged kubernetes pod
2. once it fails, hijack into it, run the docker daemon, and then run the test.

### Expected Results

test succeeds

### Actual Results

test fails

### Additional Context

- the test passes on Docker for Mac (Docker version 19.03.5, build 633a0ea) Linux
 4.19.76-linuxkit .
- the test passes on Linux 5.3.0-1009-gcp
- setting the same job in `nci` and `hh` then triggering the job (that fails to
  run on `testflight` works flawlessly

~my *guess* is that this is coming from a `mount(2)` that `runc` is trying to perform
when it tries to go from the OCI runtime spec to a container.~ err, this is from `baggageclaim`, so, no `runc` involved.

being from `mount(2)`, `EBUSY` would then interpreted as follows:

```

       EBUSY  An attempt was made to stack a new mount directly on top of an
              existing mount point that was created in this mount namespace
              with the same source and target.

```

~and yeah, indeed, we're trying to perform a stack mount there (as both input and
output would be mounted in the same directory, one would be "stacked" upon the
other).~

~what doesn't seem to make a lot of sense if the "with same source and target" -
why in `testflight` that'd be the case (assuming this is the problem)?~

### Version Info

* Concourse version: master (f8ae6998684f05a1f93e0b9b3be03ab6f20007d5)
* Deployment type (BOSH/Docker/binary): k8s on GKE (v1.15.4-gke.22)
  - `Linux gke-hush-house-ci-workers-79a0ea06-bkbz 5.0.0-1022-gke #22~18.04.3-Ubuntu SMP` Thu Oct 10 19:41:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Infrastructure/IaaS: GCP
* Browser (if applicable):
* Did this used to work? yes

**Comment by cirocosta** [comment]
hey,

I was doing some tracing to see where that EBUSY was coming from, and it's indeed from a `mount(2)` coming from baggageclaim (i.e., from the `concourse` worker process), but more specifically, from `overlay`:

```
RETVAL = -16
 SRC: overlay
 DST: /worker-state/volumes/init/f2520737-3d24-47d4-709a-328783a2943b
TYPE: overlay
DATA: lowerdir=/worker-state/overlays/8b8674d3-67a5-443a-7dcd-4986a3b
```

having instrumented with the following [`bpftrace`](https://github.com/iovisor/bpftrace) program:

```awk
#!/snap/bin/bpftrace

tracepoint:syscalls:sys_enter_mount
/ comm == "concourse" /
{
        @src[tid] = args->dev_name;
        @dst[tid] = args->dir_name;
        @type[tid] =args->type;
        @data[tid] =args->data;
}


tracepoint:syscalls:sys_exit_mount
/ comm == "concourse" && @src[tid] /
{
        printf("RETVAL = %d\n", args->ret);
        printf(" SRC: %s\n", str(@src[tid]));
        printf(" DST: %s\n", str(@dst[tid]));
        printf("TYPE: %s\n", str(@type[tid]));
        printf("DATA: %s\n", str(@data[tid]));
        printf("-----\n");

        delete(@src[tid]);
        delete(@dst[tid]);
        delete(@type[tid]);
}
```

**Comment by vito** [comment]
@cirocosta Ah, looks like it's actually failing in the second task, which attempts to use the 'output' volume as an input:

https://github.com/concourse/concourse/blob/f8ae6998684f05a1f93e0b9b3be03ab6f20007d5/testflight/fixtures/volume-mounting.yml#L189-L205

So the interesting thing here is it's making a copy-on-write of a copy-on-write. Which Baggageclaim is supposed to handle here, by finding the ancestry chain:

https://github.com/concourse/baggageclaim/blob/dc362b1f055e4836dc2afb16639383c61cee637a/volume/driver/overlay_linux.go#L71-L75

...but something doesn't seem to be working obviously. :thinking:

**Comment by cirocosta** [comment]
Hey,

Just to narrow down from the kernel perspective why this is happening now:

when the error occurs, we can see `overlayfs` printing to `kmsg` (can be
seeing through `dmesg`):


        [189906.098512] overlayfs: lowerdir is in-use as upperdir/workdir


it turns out that this very exact message was added in a recent commit that has
all to do with detecting problems like this:

```c
err = -EBUSY;
if (ovl_is_inuse(stack[i].dentry)) {
        pr_err("overlayfs: lowerdir is in-use as upperdir/workdir\n");
        goto out;
}
```

https://github.com/torvalds/linux/commit/146d62e5a5867fbf84490d82455718bfb10fe824#diff-2b85a3c5bea4263d08a2bdff639192c3R1321

now, what might seem weird is that this commit only comes after 5.2, despite us
facing that in a 5.0 kernel:

        git remote -v
                origin  https://github.com/torvalds/linux (fetch)

        git tag --contains 146d62e5a5867fbf84490d82455718bfb10fe824
                v5.2
                v5.2-rc4
                v5.2-rc5
                v5.2-rc6
                ...
                v5.5-rc3

and, it turns out that that's bacause this was backported to the 5.0-gke series
that Canonical maintains (I guess it's Canonical, but it could be Google
🤷‍♂ )


        git remote -v
                origin  https://git.launchpad.net/~canonical-kernel/ubuntu/+source/linux-gke/+git/bionic (fetch)

        git tag --contains dded475c90fd140a3f3265f279a138b1f0f7a5c7
                Ubuntu-gke-5.0-5.0.0-1019.19_18.04.1
                ...
                Ubuntu-gke-5.0-5.0.0-1022.22_18.04.1   << OURS!
                Ubuntu-gke-5.0-5.0.0-1022.22_18.04.3
                ...
                Ubuntu-gke-5.0-5.0.0-1027.28_18.04.1


ps.: the commit SHA *is* different, but that's because the trees are different -
the contents are the same though.


The problem with this commit is that it activated what used to be a feature
guarded by the `index=on` feature flag. On a later commit (that made to 5.4),
the same author end up getting back to what was the status quo:


```c
/*
 * Determine how we treat concurrent use of upperdir/workdir based on the
 * index feature. This is papering over mount leaks of container runtimes,
 * for example, an old overlay mount is leaked and now its upperdir is
 * attempted to be used as a lower layer in a new overlay mount.
 */
static int ovl_report_in_use(struct ovl_fs *ofs, const char *name)
{
	if (ofs->config.index) {
		pr_err("overlayfs: %s is in-use as upperdir/workdir of another mount, mount with '-o index=off' to override exclusive upperdir protection.\n",
		       name);
		return -EBUSY;
	} else {
		pr_warn("overlayfs: %s is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.\n",
			name);
		return 0;
	}
}
```


https://github.com/torvalds/linux/commit/0be0bfd2de9dfdd2098a9c5b14bdd8f739c9165d#diff-315c61b86e39b9b47f4ab0cd9efc2467

and yeah, as expected, this fix is *not* in the version of `linux-gke` that we
currently use (5.0.0-1022-gke).

It turns out that such patch *is* present in newer versions though:

        git show 63f5c82c10ea5f2f71a8ee3f7f24c0795393de58
                ovl: fix regression caused by overlapping layers detection


        git tag --contains 63f5c82c10ea5f2f71a8ee3f7f24c0795393de58
                Ubuntu-gke-5.0-5.0.0-1024.24_18.04.1
                Ubuntu-gke-5.0-5.0.0-1025.26_18.04.1
                Ubuntu-gke-5.0-5.0.0-1026.27_18.04.1
                Ubuntu-gke-5.0-5.0.0-1026.27_18.04.2
                Ubuntu-gke-5.0-5.0.0-1027.28_18.04.1


while that's good news for us, users will still get warned on `kmsg` about
what's going on, and those who can't have fast updates like us, can end up
having such problems.

**Comment by vito** [comment]
Interesting. Assuming the warning is something to be heeded, I can think of a couple of options:

1. Do nothing and just assume "undefined behavior" will always be fine. 😅 This honestly might not be a big deal because in our case the upper dir probably won't change in the other mount, since it's an output of something that's no longer running. However the [commit message](https://github.com/torvalds/linux/commit/146d62e5a5867fbf84490d82455718bfb10fe824#diff-2b85a3c5bea4263d08a2bdff639192c3R1321) doesn't necessarily indicate that everything will be OK if no writes are performed.
1. Copy the parent's upper directory into to the child's upper directory. This sounds slow but at least it only copies the *modified* bits, so in cases where the input isn't modified at all or only a few files are modified it shouldn't be that bad. These are sort of edge-cases anyway.

I'm *slightly* leaning towards the second option, considering `index=on` can be set at the system level, and it'd be nice if Concourse worked out of the box on those systems. ...Also relying on undefined behavior could come back to bite us anyway.

The second option also has the effect of avoiding an ancestry depth limit, since there'd only ever be one upper directory. 🤔 That could give us another way to potentially speed up task caches, which currently "flatten" into a regular volume at the end of each run in order to avoid an infinitely growing depth, but do so by copying the *entire* content, not just the delta, which can sometimes nullify the performance improvement of using the cache in the first place.

**Comment by cirocosta** [comment]
Hey,

I created a more targetted reproducible to help with debugging:

```sh
#!/bin/bash

set -o errexit

readonly URL=localhost:7788/volumes
readonly VOLUMES_DIR=/tmp/bclaim

main() {
        case $1 in
        run)
                empty "handle"
                cow "cow-handle" "handle"
                cow "cow-cow-handle" "cow-handle"
                ;;

        clean) 
		cleanup "cow-cow-handle" || true
		cleanup "cow-handle" || true
		cleanup "handle"
		;;

	*)
                echo "usage: $0 (run|clean)"
                exit 1
                ;;

        esac

}

cleanup () {
	local handle=$1

	sudo umount $VOLUMES_DIR/live/$handle/volume
}

empty() {
        local handle=$1
        local data=$(payload::empty $handle)

        curl $URL -d "$data"
}

cow() {
        local handle=$1
        local parent=$2
        local data=$(payload::cow $handle $parent)

        curl $URL -d "$data"
}

payload::empty() {
        local handle=$1

        printf '{
  "handle": "%s",
  "strategy": {
    "type": "empty"
  },
  "properties": null
}' $handle
}

payload::cow() {
        local handle=$1
        local parent=$2

        printf '{
  "handle": "%s",
  "strategy": {
    "type": "cow",
    "volume": "%s"
  },
  "properties": {}
}' $handle $parent
}

main "$@"
```

having baggageclaim running pointing at `/tmp/aa` (`sudo baggageclaim --volumes=/tmp/aa --driver=overlay`), run `./script.sh run` and you'll hit the case.

**Comment by cirocosta** [comment]
with https://github.com/concourse/baggageclaim/pull/35 haven gotten in, now it's a matter of bumping baggageclaim and consuming the new tag here in `concourse/concourse`.

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta @xtreme-sameer-vohra - this issue affects v5.2.x and v5.5.x as well - if we want those versions to be compatible with Linux v5, should we just bump baggageclaim in those repos as well, or are there any v6-specific changes that could mess things up, like
> Switch CGO-based Zstd library by a pure go one

😬 https://github.com/concourse/concourse/blob/master/release-notes/latest.md#5160
