### ISSUE TITLE
Cancel a build when new version of resource arrives, then trigger new build

### ISSUE THREAD

**Issue by tomgs** [concourse/concourse#4968]
It's often the case that a developer on my team will push two commits to a branch in successive order. It's usually done in the scope of a PR (i.e. not relevant for the official `git` resource, but for the community-built `pull-request` resource), but for the sake of the discussion let's assume they're pushing directly to `master`, and I use a `git` resource in my pipeline.

This means that there are two checks of the PR resource that return two different versions of the resource - one later than the other one. In most CI systems there's some sort of mediation for cancelling in-progress builds if the system detects a new commit coming into the PR (something like Azure DevOps's [`autoCancel` PR trigger](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger)). 

What I _thought_ the [`serial` flag does](https://concourse-ci.org/serial-job-example.html) is enable me to only have the job running once **for the newest version of the resource**, but I now understand that is not the case.

But this makes a lot of sense for many other flows as well. If you see a new version of something you need to do work on, it makes sense to ditch the old version and start work on the new version immediately. 

Is there some way to create such a flow in Concourse? I've looked into the following issues that GitHub's related issues feature sent my way before asking here, but to no avail:

https://github.com/concourse/concourse/issues/1560 - This basically confirmed that I was right on the money that this happens to other people as well, just from a different angle. No solution there, though - they just moved the problematic piece of work into the task itself.
https://github.com/concourse/concourse/issues/92 - This has to do more with looping back to old steps of the build, so it not really relevant (although adjacent, in the sense that they also had a flow that Concourse does not like and they attempted to hand-wrangle it into submission).
https://github.com/concourse/concourse/issues/2270 - This is more a problem of a resource not triggering a pipeline, which is not exactly my case.

Thanks in advance for any help!

**Comment by shreyasbharath** [comment]
Has anyone found a workaround for this?

**Comment by reiser** [comment]
Still open?

**Comment by msorens** [comment]
Further discussion, including a suggested partial solution: https://github.com/concourse/concourse/discussions/6764
