### ISSUE TITLE
Show who aborted the build

### ISSUE THREAD

**Issue by Zteve** [concourse/concourse#497]
As an owner/manager of a pipeline I’d like to know ​_who_​ triggered a build or (more interestingly) aborted one.

I would like a feature whereby the trigger/abort protocol asks for some description and id before taking the action.

This information could then be added to the log _For Great Good_!

**Comment by vito** [comment]
We'll probably start on this after Teams is done, which is around the time we'll start collecting user information (i.e. so that we can know you're @vito on GitHub who left the comment).

**Comment by vito** [comment]
Tightening the scope of this to just aborting, as https://github.com/concourse/concourse/issues/233 is already around for triggering.

**Comment by mariash** [comment]
closing in favor of https://github.com/concourse/concourse/issues/194
