### ISSUE TITLE
concourse_workers_registered metric is incorrect

### ISSUE THREAD

**Issue by oded-dd** [concourse/concourse#4974]
## Bug Report

concourse_workers_registered returns incorrect result.

our concourse current status is 3 workers are in running state, and 0 workers are in stalled state.
This was tested using `fly concourse workers` and also looking directly in the workers table in the DB.

De facto, concourse metric returns 3 workers are in running state, and 2 workers are in stalled state.

## Steps to Reproduce

concourse_workers_registered metric 

## Expected Results

As the metric checks the number of workers per state as seen by the database I should expect it to show 3 running, 0 stalled.

## Actual Results

concourse metric returns 3 workers are in running state, and 2 workers are in stalled state.

## Version Info
5.7.2

**Comment by kirillbilchenko** [comment]
[#4895 ] check if this is related, but I think it is
