### ISSUE TITLE
Shortcuts help popover gets covered by step headers

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#4978]
![Screen Shot 2020-01-07 at 4 18 57 PM](https://user-images.githubusercontent.com/9054726/71931180-32194500-316b-11ea-9810-f1dbedc3db9b.png)

I'm taking a guess but this might be a side effect of stick step headers?

cc @zoetian @pivotal-jamie-klassen

**Comment by hoegaarden** [comment]
I see the same issue:

<a href="https://user-images.githubusercontent.com/1401333/75457683-ab1b6880-5974-11ea-8af7-1cb83007d4a7.png">
  <img width="200px" src="https://user-images.githubusercontent.com/1401333/75457683-ab1b6880-5974-11ea-8af7-1cb83007d4a7.png" />
</a>

**Comment by zoetian** [comment]
Thanks for bringing this up, I'll try to solve this on Friday =)

**Comment by zoetian** [comment]
This issue had been solved earlier than my PR in Feb with this commit. It's just not in master at that time: https://github.com/concourse/concourse/commit/e664c21e1228b465921192221c45e844b2f3b356

I think we can close this issue now 😃
