### ISSUE TITLE
Inputs provided by other tasks sometimes missing

### ISSUE THREAD

**Issue by mariash** [concourse/concourse#498]
Several people reported this issue, that after they upgraded to 1.3.1 sometimes task might miss an input that is generated by another task.

They report that when they hijack they don't see the input. So it is most likely not a race condition.

**Comment by databus23** [comment]
I can reproduce this on concourse 1.3.1.

I have a pipeline that looks like this.
```
- name: bin-rc
  public: true
  serial: true
  plan:
  - aggregate:
    - get: concourse
    - get: garden-runc
    - get: garden-runc-src
    - get: bin
    - get: build
  - task: fetch-version
     ---> OUTPUT: final-version
  - task: checkout-release-tag
  - aggregate:
    - task: build-darwin-cli
     <--- INPUT: final-version (ok)
    - task: build-cli-artefacts
     <--- INPUT: final-version (ok)
  - task: build-linux
    <--- INPUT: final-version (ok)
  - task: build-release
    <--- INPUT: final-version (missing/directory empty)
```

Between the `fetch-version` task and the failing `build-release` task the build runs between 8-15 minutes and fails everytime.

**Comment by friegger** [comment]
Some facts:
- we mostly see this issue in a put step within the ensure block of a task (https://main.bosh-ci.cf-app.com/pipelines/bosh-openstack-cpi-liberty/jobs/deploy-centos-manual/builds/917), but also have examples where it happens in the following task (https://main.bosh-ci.cf-app.com/pipelines/certify-openstack/jobs/e2e-centos/builds/82)
- @cunnie suggested that forcing all steps to run on the same worker prevents this problem to occur, but we see it on this [pipeline](https://main.bosh-ci.cf-app.com/pipelines/bosh-openstack-cpi-liberty/jobs/deploy-centos-manual/builds/917) which uses a single worker tag everywhere
- we were able to hijack the put container for [this build](https://main.bosh-ci.cf-app.com/pipelines/bosh-openstack-cpi-liberty/jobs/deploy-centos-manual/builds/918) and saw other files that have been generated in the previous step, but the one to be used was missing:
```
fly -t production hijack -j bosh-openstack-cpi-liberty/deploy-centos-manual
targeting https://main.bosh-ci.cf-app.com

bash-4.3# pwd
/tmp/build/put
bash-4.3# ls
bosh-cpi-dev-artifacts  bosh-init               deployment              stemcell
bosh-cpi-src-in         bosh-release            director-state-file     version-semver
bash-4.3# cd director-state-file/
bash-4.3# ls
centos-manual-director-manifest-state.json  url                                         version
bash-4.3# cat centos-manual-director-manifest-state.json
{}
bash-4.3# cd ../deployment/
bash-4.3# ls
bosh-openstack-cpi.tgz  bosh-release.tgz        stemcell.tgz
bash-4.3#
```

**Comment by databus23** [comment]
Not sure if this helps but here is some log output from the worker where a job failed because the `final-version` input was missing (empty directory).
The last log line is about the task (in `/tmp/build/7c4e1319`) that ended up having an empty input dir.
The between the first and the last log line (613 seconds ~ 10 minutes passed)
```
{"timestamp":"1467197969.716048956","source":"guardian","message":"guardian.api.garden-server.create.created","log_level":1,"data":{"request":{"Handle":"","GraceTime":0,"RootFSPath":"raw:///workdir/volumes/live/ff526be7-d42b-41a6-57cd-43e782a50d94/volume/rootfs","BindMounts":[{"src_path":"/workdir/volumes/live/3e19bc4c-045f-49ba-6849-b17dd96e0e2c/volume","dst_path":"/tmp/build/4b62a6ba/final-version/","mode":1},{"src_path":"/workdir/volumes/live/fe4baa41-7705-4a8e-5703-0b1b30f74c3a/volume","dst_path":"/tmp/build/4b62a6ba/concourse","mode":1},{"src_path":"/workdir/volumes/live/37cebafe-ce3c-4488-6c3f-650c63606c7a/volume","dst_path":"/tmp/build/4b62a6ba/garden-runc","mode":1},{"src_path":"/workdir/volumes/live/87854d11-e72e-44f3-7fa9-2154654c8812/volume","dst_path":"/tmp/build/4b62a6ba/build","mode":1}],"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{}}},"session":"2.1.21349"}}
{"timestamp":"1467197970.351098299","source":"guardian","message":"guardian.api.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/4b62a6ba/final-version/","handle":"79bad0f7-86ff-4371-5fd6-882127774315","session":"2.1.21361","user":""}}
{"timestamp":"1467198128.379202843","source":"guardian","message":"guardian.api.garden-server.stream-out.streamed-out","log_level":1,"data":{"handle":"79bad0f7-86ff-4371-5fd6-882127774315","session":"2.1.21862","source":"/tmp/build/4b62a6ba/final-version/","user":""}}
{"timestamp":"1467198155.447828293","source":"guardian","message":"guardian.api.garden-server.stream-out.streamed-out","log_level":1,"data":{"handle":"79bad0f7-86ff-4371-5fd6-882127774315","session":"2.1.21936","source":"/tmp/build/4b62a6ba/final-version/","user":""}}
{"timestamp":"1467198233.914607286","source":"guardian","message":"guardian.api.garden-server.stream-out.streamed-out","log_level":1,"data":{"handle":"79bad0f7-86ff-4371-5fd6-882127774315","session":"2.1.22207","source":"/tmp/build/4b62a6ba/final-version/","user":""}}
{"timestamp":"1467198233.970328569","source":"guardian","message":"guardian.api.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/9674af12/final-version/.","handle":"5d5b58d9-72b2-4d15-76c6-c178cfc742b8","session":"2.1.22208","user":""}}
{"timestamp":"1467198582.874435902","source":"guardian","message":"guardian.api.garden-server.stream-out.streamed-out","log_level":1,"data":{"handle":"79bad0f7-86ff-4371-5fd6-882127774315","session":"2.1.23417","source":"/tmp/build/4b62a6ba/final-version/","user":""}}
{"timestamp":"1467198582.946283579","source":"guardian","message":"guardian.api.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/7c4e1319/final-version/.","handle":"2599311a-927e-48e1-7226-9bfba668d9e2","session":"2.1.23422","user":""}}
```

**Comment by databus23** [comment]
I'm not sure but maybe this issue is related: https://github.com/concourse/concourse/issues/373

**Comment by disintegrator** [comment]
I'm also experiencing this issue. My job's plan fetches two git resources, runs a task and finally puts to an `s3-resource-simple`. That last put step sees the two git resource but not the task output. I'm using a dockerised concourse 1.3.1 setup deployed on AWS ECS.

**Comment by cunnie** [comment]
We're experiencing this issue on BOSH CPI: https://main.bosh-ci.cf-app.com/pipelines/bosh-aws-cpi/jobs/bats , builds 38 through 43 failed, but we were able to get it to pass by tagging all tasks on the same worker (but @friegger indicates this is not a sure-fire fix).

**Comment by dannysullivan** [comment]
We have this issue in a job that contains two tasks, the first of which passes some output to the second.  Specifically, the output seems to disappear if the image_resource used by the tasks is updated and needs to be pulled - both tasks pull the latest version of the image, and the second task ends up losing the output of the first task in the process.

**Comment by utako** [comment]
CAPI is also experiencing this issue, especially when passing an artifact from one task to another. We also don't see the resource after hijacking.

**Comment by youreddy** [comment]
As an update to the above, this issue is happening often in the CAPI pipeline on different jobs. 

https://capi.ci.cf-app.com/pipelines/capi/jobs/migration-backwards-compatibility-test/builds/156
http://capi.ci.cf-app.com/pipelines/capi/jobs/deploy-and-test-xena/builds/758

Please let us know if having access to our pipeline would be helpful in debugging this issue.
