### ISSUE TITLE
job status via cli or api

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#499]
Is there a way to retrieve the job status via cli / api, and to see the list of jobs in a pipeline?

I'm hoping to build a little LED board to be a visual YES/NO push to prod indicator using concourse state.

**Comment by vito** [comment]
The API exists, but is not documented or officially supported (i.e. expected to be stable). Given that, I'm gonna close this in favor of https://github.com/concourse/atc/issues/80

Until then, you can find the endpoints here:

https://github.com/concourse/atc/blob/master/routes.go
