### ISSUE TITLE
Routing to `<hostname>/builds/` 404s, without the slash `<hostname>/builds` doesn't

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#500]
When I navigate to `builds/` we get a 404 but it gets through without the trailing slash.

I'd expect that either would work

**Comment by jadekler** [comment]
@vito @cjcjameson I think this is intended. All routes respond to `/whatever/` with `404` - only `/whatever` would give you the content.

Also as a sidenote `<hostname>/builds` is now deprecated.
