### ISSUE TITLE
[Build Logs] Build Step Header - Step Type Indicator

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5005]
As a user viewing the build logs, I can't deduce the meaning behind icons without labels.

In addition, the colour yellow isn't often enough to figure out that a given step is using new inputs.

- [ ] Combine < v5.5.7 style icons with > v5.5.8 style get/build/put/etc labels
- [ ] Add 'new' icon or label indication so we aren't reliant on colours and tooltips

**Comment by kcmannem** [comment]
ive wanted that new label for a while now

**Comment by kcmannem** [comment]
![Screen Shot 2020-01-15 at 8 21 37 PM](https://user-images.githubusercontent.com/9054726/72485092-a3dd3880-37d4-11ea-90c4-0da311506dd9.png)

Just a thought, it'd be nice to have the new label next to the version metadata. It reads nice, eg. new ref, new digest, new sha... Also putting it on the right side, makes it so the yellow color is not distracting while reading the plan.

**Comment by matthewpereira** [comment]
@kcmannem I like it, nice idea. 💪

**Comment by matthewpereira** [comment]
Switched from icons to labels in v5.8.x, we can revisit the 'NEW' labelling again in the future. Closing this for now.
