### ISSUE TITLE
Spaces appear as '%20' in tab titles when viewing pipeline in web UI

### ISSUE THREAD

**Issue by houlahaj** [concourse/concourse#5016]
## Bug Report
If the pipeline name has a space in it, the tab title (on firefox v72) shows `%20` instead of the space.

## Steps to Reproduce
`fly -t mytarget set-pipeline --pipeline="Name With Spaces" --config=myconfig.yml`

## Expected Results
Viewing the pipeline in web viewer shows name "Name With Spaces".

## Actual Results
Viewing the pipeline in web viewer shows name "Name%20With%20Spaces".

## Version Info
* Concourse version: 5.8.0
* Browser: Firefox 72.0.1 (Arch Linux)

**Comment by vito** [comment]
related: https://github.com/concourse/rfcs/pull/40
