### ISSUE TITLE
Pipeline cannot pass resource check due to missing file

### ISSUE THREAD

**Issue by sqlsolver** [concourse/concourse#5017]
## Bug Report
Starting a pipeline build always fails at the resource check. The pipeline is a simple test of getting an image that was pushed to Docker Hub. After un-pausing the pipeline in the UI fly workers returns information, and you can hijack the container. However once you kick off the job that verifies the docker image it fails (hangs forever in UI), and subsequently the worker container is MIA.
````
[command path]>fly -t local check-resource --resource test_delete/ubuntu-java13
id  name        status     check_error
13  docker-hub  succeeded
id  name           status   check_error                                                                                                                                                                                             
14  ubuntu-java13  errored  Backend error: Exit status: 500, message: {"Type":"ExecutableNotFoundError","Message":"exec failed: container_linux.go:346: starting container process caused \"exec: \\\"/opt/resource/check\\\": stat /opt/resource/check: no such file or directory\"","Handle":"","ProcessID":"","Binary":""}
````

## Steps to Reproduce
The issue was happening initially with an Alpine based image I'd added Eureka to, and I thought it was something to do with bash itself being missing so switched to Ubuntu. The dockerfile used to create the current image and pipeline are [here](https://gist.github.com/sqlsolver/6bc2eac813a59008e7c4ff10e7bee397). To reproduce:
 - Run fly set-pipeline
 - Switch to UI and un-pause pipeline
 - Start build in UI, watch it spin... never more than two checkmarks passed
 - Switch back to console and check the resource with fly

## Expected Results

Expected the resource to be validated and the docker-image to be pulled

## Actual Results

Pipeline job never runs

## Additional Context
The worker can be found before the resource check. Hijacking the container however, shows there is no /resource/opt directory in it so the error is valid.
````
[command path]>fly -t local workers -d .
name          containers  platform  tags  team  state    version  age  garden address   baggageclaim url        active tasks  resource types
d6cbc9c0a3cd  3           linux     none  none  running  2.2      3d   127.0.0.1:46159  http://127.0.0.1:36729  0             bosh-io-release, bosh-io-stemcell, cf, docker-image, git, github-release, hg, mock, pool, registry-image, s3, semver, time, tracker
````

````
[command path]>fly -t local hijack -c test_delete/ubuntu-java13
root@85cb3ae0-59ac-4c1e-6273-8ef5070070e4:~# ls /opt/resources
ls /opt/resources
ls: cannot access '/opt/resources': No such file or directory
````

After build hangs you container disappears:
````
[local path]>fly -t local hijack -c test_delete/ubuntu-java13
no containers matched your search parameters!

they may have expired if your build hasn't recently finished.
````

## Version Info

* Concourse version: 3, modified docker-compose file
* Deployment type (BOSH/Docker/binary): docker-image
* Infrastructure/IaaS: New installations of Concourse and Vault on WIndows. Both using external domain names. Vault https, Concourse unsuccessful in setting that up - so http.
* Browser (if applicable): Generally Firefox, else Chrome
* Did this used to work? No

**Comment by pivotal-jamie-klassen** [comment]
@sqlsolver I'm inclined to say this actually isn't a bug - I think your pipeline may be mixing up the notions of resources vs resource types here. If you are putting an image in the [`resource_types`](https://concourse-ci.org/resource-types.html) section of your pipeline, it must satisfy a certain [contract](https://concourse-ci.org/implementing-resource-types.html), and from what I can see [here](https://gist.github.com/sqlsolver/6bc2eac813a59008e7c4ff10e7bee397#file-dockerfile-ubuntu-openjdk13) your image doesn't have the `/opt/resource/{check,in,out}` scripts so it is not a resource type.

In fact, based on the contents of that image, I'm guessing you want to use it to maybe build/test some java code. That is to say, you want to use it to run a task, rather than to get/put resource versions. So you don't really need it to be a resource type anyway! In this case, you probably want a pipeline more like this:
```yaml
---
resources:
- name: ubuntu-java13
  type: docker-image # upgrade to concourse 5 and use registry-image? it's better supported
  source:
    repository: [redacted]
    tag: UbuntuJava13.2020-01-12
    username: ((docker_user))
    password: ((docker_pass))

jobs:
- name: image-get-test
  plan: 
  - get: ubuntu-java13
```

Does this make sense?

**Comment by sqlsolver** [comment]
It does make sense, and is a very helpful and concise answer. 

The resource definitions do mention that registry image is the way forward from docker-image, but also note that it is only for pushing and pulling - not building. I had intended to pull the base image with Ubuntu and Java and then build a final image per app in the pipeline. Is it recommended to avoid docker-image and script the build of the new one?

I'm closing this issue because the resource check is now happy:
````
[command path]>fly -t local check-resource --resource test_delete/ubuntu-java13
id  name           status     check_error
4   ubuntu-java13  succeeded
````
However, using the pipeline as you wrote it above is still hanging without pulling the image:

![image](https://user-images.githubusercontent.com/4545063/72379962-490aea80-36c9-11ea-9fa4-6cb6983c6a14.png)

**Comment by pivotal-jamie-klassen** [comment]
@sqlsolver it is recommended to do any image-building in a task, and https://github.com/vito/oci-build-task provides a decent solution - that's what we use when building images as part of the [development pipeline](https://ci.concourse-ci.org/teams/main/pipelines/concourse) for concourse itself, which is defined [here](https://github.com/concourse/ci/blob/master/pipelines/concourse.yml).
