### ISSUE TITLE
Investigate memory usage in long-running "algorithm v3" environment

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5020]
This don't look too good:

![image](https://user-images.githubusercontent.com/1880/72279373-fca9a700-3603-11ea-960f-3911b4def2ce.png)

Let's take a heap dump and figure out what's using all the RAM.

Graph: https://app.datadoghq.com/dashboard/e2x-kuz-6md/concourse?from_ts=1578333287623&live=true&tile_size=m&to_ts=1578938087623&tpl_var_environment=concourse-algorithm

**Comment by clarafu** [comment]
closing cause I made #5022
