### ISSUE TITLE
Concourse incompatible incompatible with Red Hat based distributions because of older kernel versions and CAP

### ISSUE THREAD

**Issue by jamesread** [concourse/concourse#503]
Hi folks. When trying to start a Concourse build on Red Hat Enterprise Linux (and based distros) - Scientific Linux, and CentOS 6.x and 7.x (the latest versions at time of writing), it will fail due to #488 - CAP_AUDIT_READ. 

These distributions won't change their Kernel version in their whole lifetime (RHEL6 is on 2.6.32 and RHEL7 is on 3.10), but the kernels are not necessarily that "old" - the Red Hat model is to backport bits and pieces from newer kernels into these older versions. The fix here would be to silently catch CAP_AUDIT_READ and ignore (ad this is unlikely to get backported) 

Adding this as a separate bug because it excludes a large number of potential Concourse users.

**Comment by jamesread** [comment]
Ah, this is documented upstream here; https://www.pivotaltracker.com/n/projects/1158420/stories/119257379

**Comment by vito** [comment]
There's nothing for us to fix on our end - you'll want to track https://github.com/cloudfoundry-incubator/guardian/issues/38 instead.

**Comment by Lyr** [comment]
Hi, I need to run concourse on redHat 7 and It could be usefull to access on this link : https://www.pivotaltracker.com/story/show/123689971 this but currently, is no more readable :(. Anything to provide an read access on this story?

**Comment by dolph** [comment]
@Lyr I tried running Concourse 6.0.0 on CentOS 7 and found the worker to be completely unsupported on kernel 3.10. I had to switch to CentOS 8.

**Comment by Lyr** [comment]
Currently, this migration is impossible on my context so it's a showstopper to use Concourse, it's bad cause this looks as a good solution, but, in some firm it's impossible to have a newest OS (centos 8 has been released at 2019-09-24, for a big compagny it's a bit short to assume a migration). Thanks for your feedback @dolph

**Comment by tiredpixel** [comment]
Maybe use CentOS 7 with ELRepo kernel-ml to get v4 kernel? I've run it successfully previously.
https://www.elrepo.org/tiki/kernel-ml

I doubt you'll have much success with Kernel v3.10; `CAP_AUDIT_READ` is needed. You might like to take a look through this conversation; only half of it is directly relevant, but there's a discussion regarding why v3.10 won't work, from when I was working on that in 2017.
https://github.com/concourse/concourse/issues/1640

CentOS 8 still has some issues with various packages… I've switched to it for main production infrastructure, but I wouldn't recommend it unless you're willing to resolve sporadic issues, patch in some packages from other distributions, and occasionally compiled some SELinux modules yourself. (General opinion about CentOS 8; not specifically related to Concourse CI.)
