### ISSUE TITLE
Build step fails with duplicate key violation

### ISSUE THREAD

**Issue by databus23** [concourse/concourse#504]
Running concourse 1.3.1 binaries.

I just had a build fail and go into "orange" because of a postgres constraint violation.
The error happened in the get step following a put of a custom *pipeline resource*:

![image](https://cloud.githubusercontent.com/assets/439223/16520542/f30c9774-3f90-11e6-83a3-58f8908d228e.png)

The error from the postgres log:
```
2016-07-01 11:24:00 UTC ERROR:  duplicate key value violates unique constraint "image_resource_versions_build_id_plan_id_key"
2016-07-01 11:24:00 UTC DETAIL:  Key (build_id, plan_id)=(2848, 57764e85) already exists.
2016-07-01 11:24:00 UTC STATEMENT:
				INSERT INTO image_resource_versions(version, build_id, plan_id, resource_hash)
				VALUES ($1, $2, $3, $4)

```

**Comment by vito** [comment]
That's extra weird; that insertion should always be unique as long as one ATC is managing the build (which should also be guaranteed via a lock surrounding the whole build). Do you know if anything funny happened around the same time? e.g. ATC crash?

**Comment by databus23** [comment]
We only run one ATC. I don't recall atc crashing at that point in time. We are running postgres 9.5.2 in a docker container (not that it should matter).

**Comment by vito** [comment]
I'm afraid we won't really be able to investigate this sort of thing without a way to reproduce it. The error should be impossible so I'm not really sure where to begin. Was there anything interesting about that particular step? e.g. is it using a custom resource type?

**Comment by vito** [comment]
Saw this on another environment; I think if the database is slow enough, locks will end up being released and the ATC (even if there's just one) will start doing what should be unique workloads in parallel (i.e. processing the same build twice).

**Comment by gabro** [comment]
This occurred to me today. What happened in my case was a manual build started at the same time of a "triggered" build.
