### ISSUE TITLE
How to use concourse with apigateway?

### ISSUE THREAD

**Issue by devopsprosiva** [concourse/concourse#5041]
Hi,

I want to use concourse as a backend service exposed via an apigateway. I plan to have the apigateway act as the authentication and authorization service for the backend services. Once the apigateway autheticates a user and gets the authorization token, I want to pass that token to the concourse server. Is this possible to do with concourse? If so, could you please refer some documentation for this?

Thanks,
Siva

**Comment by xtreme-sameer-vohra** [comment]
Hi @devopsprosiva 
Concourse supports a bunch of auth providers documented [here](https://concourse-ci.org/configuring-auth.html) 
Is there a specific need for a API gateway for doing auth for Concourse ?

Concourse uses `dex` as a library for generating tokens using [skymarshall](https://github.com/concourse/concourse/tree/master/skymarshal), so if tokens were to be generated by another component that you use, they would have to be compliant with what skymarshall produces.

**Comment by xtreme-sameer-vohra** [comment]
Lastly, if you're looking for help, I'd recommend using
[Forums - Discuss](https://discuss.concourse-ci.org/
[Chat - Discord](https://discuss.concourse-ci.org/t/join-us-in-discord/34) 
as Github issues are meant for bugs or feature requests.
