### ISSUE TITLE
no way to use a reference repository (or similar technique) with the git resource

### ISSUE THREAD

**Issue by benjumanji** [concourse/concourse#505]
At the moment the git resource does a complete clone on `in` which is prohibitively expensive. I made a very tiny patch to the `in` script that creates a bare repo in `/tmp` if it doesn't exist then clone using that as a reference into the required destination.

This doesn't seem to work because I guess the `get` container doesn't have any kind of persistence / sharing for a given version at all?

Cloning is prohibitively expensive for the repository that I would like to use concourse with. Any advice on either a) how I could implement this kind of resource myself, or b) an upstream fix would be greatly appreciated.

**Comment by vito** [comment]
This is unlikely to change. Even if it were able to reuse an already cloned repo, there'll still always be the initial clone. Every clone runs from a pristine environment, as you said, and sharing state between fetches is a pandora's box I'd rather not open.

You may want to try the `depth` flag.

**Comment by benjumanji** [comment]
Ok cool. That's fine. It makes sense. I'll see if I can slim the repository a bit more. Depth doesn't get me what I need, but perhaps that indicative of other things that need fixing. I'll close this.

**Comment by vito** [comment]
Thanks for understanding!
