### ISSUE TITLE
GUI shows no errors when non-existing tag for resource_type is specified

### ISSUE THREAD

**Issue by Hertog-PJ** [concourse/concourse#5058]
## Bug Report

When specifying an unexisting tag for a resource_type, in this case `git-multibranch`, the GUI does not show any errors for the resources you specify of that type, it says `checking successfully`. 

Similar to: https://github.com/concourse/concourse/issues/612

When using `fly` to verify the resource you will get the following error: 
```
id    name             status     check_error
2366  git-multibranch  succeeded
error: parent type has no version
```
## Steps to Reproduce

https://gist.github.com/Hertog-PJ/72e0f04672a7b5cd1b1d80d5fa406982

## Expected Results

To get clear feedback from the GUI that the version of the defined resource type does not exist.

## Actual Results

No feedback from the GUI indicating any error whatsoever.

## Version Info

* Concourse version: 5.7.0
* Browser (if applicable): chrome
* Did this used to work? no

**Comment by DanielJonesEB** [comment]
Encountering the same issue, currently trying to validate that the cause is that the image tag isn't available.

**Comment by eltoru** [comment]
For us, this problem turned out to be missing credentials to our own docker registry server for a image resource-type.
insecure_registries: [ "((docker-registry)):5000" ]
username: ((user))
password: ((password))

**Comment by professor** [comment]
I'm working on a new concourse resource and I had this happen to me. My docker hub has a public repo, so it's not a credential issue. 

Using the fly check-resource allowed me to see that there's information in standard error that is not showing up in the web UI.
