### ISSUE TITLE
Documentation is misleading re: task file conventions

### ISSUE THREAD

**Issue by camelpunch** [concourse/concourse#506]
http://concourse.ci/running-tasks.html says that "Conventionally a task's configuration is placed in the same repository as the code it's testing", but it appears that Concourse itself and most CF projects I can find put all of their Concourse config into one repo.

Is this true, or am I making all of this up?

**Comment by vito** [comment]
The answer is always going to be "it depends". [Our CI scripts](https://github.com/concourse/concourse/tree/master/ci) live with [the code they're testing](https://github.com/concourse/concourse/tree/master/src) and I imagine that's the case for most people. But if you don't have much code that you're testing, for example if you're on a team that basically focuses on CI and acts as an integration point for separate teams, things will be different.

**Comment by camelpunch** [comment]
So you have concourse trigger scripts in one repo and e.g. test scripts in the specific project repo. That makes sense. Thanks.
