### ISSUE TITLE
Workers keep failing after a few days due to zombie processes

### ISSUE THREAD

**Issue by georgehaidar** [concourse/concourse#507]
After a few days of running ConcourseCI on AWS ECS, I start noticing the worker failing completely. I've been manually destroying and rebuilding the worker every time this happens (it is guaranteed to happen every few days). In the failed state, I am unable to SSH into the host machine where the worker is running. My suspicion is that the host machine is out of disk space. I am not sure where to go from here and I would really appreciate some help debugging this issue.

I have attached the worker log file below for inspection.

**Environment**
My web and worker docker images use ubuntu 16.04 as the base image. The worker is running with privileged flag.
Some other useful information:
ConcourseCI version: 1.3.1

AWS Region: ap-southeast-2
ECS AMI: amzn-ami-2016.03.c-amazon-ecs-optimized (ami-697a540a)
Number of workers tasks: 1
Number of web tasks: 1

Worker log file: [worker.txt](https://github.com/concourse/concourse/files/345959/worker.txt)

**Comment by vito** [comment]
Those logs look like runtime system resources are running out - perhaps memory, threads, etc. The more interesting logs are probably the events leading up to this situation. In Slack you had this log entry (https://concourseci.slack.com/archives/general/p1467618460004288):

```json
{
  "timestamp": "1467618330.111963987",
  "source": "baggageclaim",
  "message": "baggageclaim.repository.destroy-volume.failed-to-destroy",
  "log_level": 2,
  "data": {
    "error": "remove /opt/concourse/volumes/dead/a6d0f9e7-87fd-45cd-6d5a-9bac3713d10d/volume: operation not permitted",
    "session": "3.357919",
    "volume": "a6d0f9e7-87fd-45cd-6d5a-9bac3713d10d"
  }
}
{
  "timestamp": "1467618330.112021446",
  "source": "baggageclaim",
  "message": "baggageclaim.tick.failed-to-reap",
  "log_level": 2,
  "data": {
    "error": "1 error(s) occurred:\n\n* failed to destroy a6d0f9e7-87fd-45cd-6d5a-9bac3713d10d: remove /opt/concourse/volumes/dead/a6d0f9e7-87fd-45cd-6d5a-9bac3713d10d/volume: operation not permitted",
    "session": "29689"
  }
}
```

...which also looks suspect. If volumes cannot be destroyed the worker will surely run out of disk, possibly leading to other things failing.

**Comment by georgehaidar** [comment]
@vito The thing is I'm not sure how concourse could gobble up 200GB of disk space in just a few days when I have two very simple pipelines (both are git resource -> npm test job).

Furthermore, I realised that I did not have a persistent data directory volume mapped to my worker container as per http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html
I was assigning a nonpersistent one (the second option on that page). It's possible that the docker daemon on the host was interfering and deleting the volume's contents.

**Comment by georgehaidar** [comment]
@vito I redeployed concourse environment two days ago and waited for the issue to reappear. Today the issue happened again but I managed to capture the logs. I've attached them here:
[concourse-worker.txt](https://github.com/concourse/concourse/files/351266/concourse-worker.txt)

**Comment by georgehaidar** [comment]
Also the following graph shows the memory utilisation over the two days as reported on the ECS cluster running concourse worker. The worker is allocated 7GB of memory on an m4.large container instance.
<img width="843" alt="aws_ecs_memory_utilisation" src="https://cloud.githubusercontent.com/assets/17603282/16641833/a5edb066-4447-11e6-9acf-d731203a1756.png">

**Comment by georgehaidar** [comment]
Adding ulimits and sysctl dump
[sysctl.txt](https://github.com/concourse/concourse/files/351389/sysctl.txt)
[ulimits.txt](https://github.com/concourse/concourse/files/351390/ulimits.txt)

**Comment by vito** [comment]
Compared the sysctl to our own and didn't see anything significant.

Comparing ulimits, our workers are indeed configured higher for for max user processes (31884 vs. 60073), but I really don't think that should matter (in principle; that number's already huge).

**Comment by georgehaidar** [comment]
I've redeployed my concourse environment once again with version 1.4 now. I've also started exporting certain logs such as dmesg, docker daemon and ecs agent to cloudwatch log groups.
Is there anything else I can capture (metrics or logs) that can help diagnose this issue?

**Comment by vito** [comment]
Metrics are definitely useful, thanks for all you've reported so far. Useful metrics could be # OS threads, disk usage, memory usage, CPU usage.

**Comment by tobyirvine** [comment]
Seeing this on my concourse set up too. v1.3.1 running under docker but with Rancher managing. Resources running out on container hosts running concourse workers, ultimately leaving the box unresponsive over ssh. Top shows high load averages but low cpu/mem:

```bash
top - 08:16:12 up 4 days, 21:54,  1 user,  load average: 91.50, 91.40, 91.10
Threads: 9843 total,   3 running, 2429 sleeping,   0 stopped, 7411 zombie
%Cpu(s):  5.8 us,  2.9 sy,  0.0 ni, 90.8 id,  0.0 wa,  0.0 hi,  0.2 si,  0.3 st
KiB Mem :  4045088 total,    73524 free,  1635988 used,  2335576 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2100280 avail Mem
```
Sorting by process status in top show lots of garden-init processes stuck in uninterruptible sleep:

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  510 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
  540 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
  643 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
  721 root      20   0       0      0      0 D  0.0  0.0   0:00.02 garden-init
 1829 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 1741 root      20   0       0      0      0 D  0.0  0.0   0:00.02 garden-init
 2811 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 3296 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 3588 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 4237 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 4342 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 5278 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 5539 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 5664 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 5608 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 5717 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 6247 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 6120 root      20   0       0      0      0 D  0.0  0.0   0:00.07 garden-init
 6558 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 6546 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 6777 root      20   0       0      0      0 D  0.0  0.0   0:00.05 garden-init
 6943 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 7265 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 7498 root      20   0       0      0      0 D  0.0  0.0   0:00.06 garden-init
10154 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
 8143 root      20   0       0      0      0 D  0.0  0.0   0:00.00 garden-init
```

I'll keep investigating and see if I can find out more.

**Comment by georgehaidar** [comment]
@vito I think I found the culprit with the help of @tobyirvine. It appears that there are a ton of zombie iodaemon and ssh-agent processes that are not getting reaped. I just ssh'd into a working environment where a worker is running and saw the following:
```
[ec2-user@ip-10-0-35-55 ~]$ ps aux | grep iodaemon | wc -l
1480
[ec2-user@ip-10-0-35-55 ~]$ ps aux | grep ssh-agent | wc -l
432
```
This is for a worker that has been running for 1 day only. So I guess after a few days this number will reach the limit I have (~32k processes).

**Comment by georgehaidar** [comment]
This is possibly related to recent issues with docker and zombie process handling: https://github.com/docker/docker/search?q=zombie&type=Issues&utf8=%E2%9C%93

**Comment by tobyirvine** [comment]
Just to add another data point:

```
$ ps aux | grep iodaemon | wc -l
5783

$ ps aux | grep ssh-agent | wc -l
1621

$ ps aux | grep Zs | awk '{print $11}' | sort | uniq -c
      1 [exe]
     65 [garden-init]
      1 grep
   1612 [ssh-agent]
```

**Comment by georgehaidar** [comment]
I just switched the docker daemon running on my ECS instance to use overlayfs storage driver instead of the default devicemapper and it seems to have fixed the issue. I am not sure if this a recommended solution but I am happy to run with it for a few days and see what happens.

**Comment by tobyirvine** [comment]
Attaching a full process tree from a container host running two concourse workers with ~1000 zombie processes.

[process-tree.txt](https://github.com/concourse/concourse/files/357204/process-tree.txt)

**Comment by vito** [comment]
@georgehaidar @tobyirvine Ah-hah! I didn't realize or appreciate that you're both running on Docker hosts.

You'll need an init that will reap zombies - Docker doesn't. you could use https://github.com/Yelp/dumb-init or just use https://github.com/gregarcara/concourse-docker which implements it

This explains exactly the issue @georgehaidar has been seeing: leaking memory, running out of threads, but no other metrics seemingly affected. Each zombie process will have a memory footprint lost until it's reaped, and we run processes literally all the time for resource checking, so it makes sense for that to eventually die.

This isn't really a Concourse or Garden bug - these processes are intentionally handed off to the init process so that the worker can be restarted and re-attach to them. It assumes that the init process is "proper" and will reap zombies, which is not something that Docker does out of the box.

**Comment by tobyirvine** [comment]
Updated my container images to launch concourse with dumb-init and no more zombies. All concourse hosts ticking along nicely, thanks vito.

**Comment by vito** [comment]
sweet!
