### ISSUE TITLE
Blinking issue 

### ISSUE THREAD

**Issue by gzamoran-ford** [concourse/concourse#5071]
## Bug Report

Some logs shows blinking text

## Steps to Reproduce
i can see a "ansi-blink" css class, there is a way to remove it? i tried but bosh put it again after every redeploy

![concourse](https://user-images.githubusercontent.com/20976045/73190220-a94f5280-40f3-11ea-9050-52d2900a81e7.gif)

## Expected Results

do not have blinking

## Version Info

* Concourse version: version: v4.2.3
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Azure
* Browser (if applicable): Chrome
* Did this used to work? never

**Comment by taylorsilva** [comment]
@gzamoran-ford Are you able to reproduce this on any of the `5.x` versions of Concourse? Curious as to why you're using 4.2.3? We're not making any fixes for `4.x` Concourse anymore.
