### ISSUE TITLE
Continual web panic until workers are redeployed

### ISSUE THREAD

**Issue by robwhitby** [concourse/concourse#5077]
This issue happens rarely, maybe once a month, but the biggest problem is that after it starts it keeps happening across all the web nodes until we resort to redeploying all the workers.

```
panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb4a25a]goroutine 175554 [running]:github.com/concourse/concourse/atc/exec.(*RetryStep).Succeeded(0xc066d64690, 0x2)
/tmp/build/1c3187db/concourse/atc/exec/retry_step.go:47 +0x2agithub.com/concourse/concourse/atc/exec.OnSuccessStep.Succeeded(0x2841da0, 0xc066d64690, 0x284a7e0, 0xc0680fe400, 0x424101)
/tmp/build/1c3187db/concourse/atc/exec/on_success.go:45 +0x31github.com/concourse/concourse/atc/exec.OnSuccessStep.Succeeded(0x2841e20, 0xc066d647b0, 0x284a7e0, 0xc0680fe4c0, 0xc05ec4cc90)
/tmp/build/1c3187db/concourse/atc/exec/on_success.go:45 +0x5cgithub.com/concourse/concourse/atc/exec.OnFailureStep.Succeeded(...)
/tmp/build/1c3187db/concourse/atc/exec/on_failure.go:44github.com/concourse/concourse/atc/exec.EnsureStep.Succeeded(0x284a7a0, 0xc0680fe640, 0x2841da0, 0xc066d64870, 0xc051486660)
/tmp/build/1c3187db/concourse/atc/exec/ensure_step.go:58 +0x31github.com/concourse/concourse/atc/engine.(*engineBuild).Run(0xc03c79bd60, 0x2895fa0, 0xc00578d020)
/tmp/build/1c3187db/concourse/atc/engine/engine.go:215 +0x8cdcreated by github.com/concourse/concourse/atc/builds.(*Tracker).Track
/tmp/build/1c3187db/concourse/atc/builds/tracker.go:49 +0x425
```

There was a similar issue - https://github.com/concourse/concourse/issues/3989 - so perhaps it was only partially fixed.

## Version Info

* Concourse version: 5.7.0

**Comment by vito** [comment]
Totally still a bug, thanks for the report - sorry it got prematurely closed.

Someone else just ran into this very issue, so we should probably fix this more thoroughly in the retry step itself; having an implicit dependency between the `.Run` and `.Succeeded` calls is clearly too dangerous.

**Comment by vito** [comment]
It would be great if we could also address the broader issue of one pipeline taking down the cluster: https://github.com/concourse/concourse/issues/3594 - but my understanding is that's pretty difficult to do, since we'd have to `defer recover()` in every single goroutine. That being said, there are only so many steps - maybe we just need to diligently implement them?

**Comment by xtremerui** [comment]
Could we just add a nil check of step.LastAttempt? It seems like the panic is a combination of in_parallel and retry steps where in_parallel runs a succeeded check on a retry_step that hasn't been ran yet (LastAttempt is set only in retry_step.Run())

**Comment by vito** [comment]
@xtremerui Yeah - I think just checking for `nil` and returning `false` would be appropriate.

**Comment by xtreme-sameer-vohra** [comment]
> Could we just add a nil check of retry_step.LastAttempt? It seems like the panic is a combination of in_parallel and retry steps where in_parallel runs a succeeded check on a retry_step that hasn't been ran yet (LastAttempt is set only in retry_step.Run())

The suggestion makes sense. However, I am still uncertain how the system got into the state.
Is this possible from the code ? All the calls to Run would be blocking prior to checking Succeeded right?

**Comment by vito** [comment]
@xtreme-sameer-vohra Unfortunately I didn't keep the pipeline config, but I was able to reproduce this with a setup like the following:

```yaml
plan:
- in_parallel:
    limit: 1
    steps:
    - task: sleep
      attempts: 2
    - task: sleep
      attempts: 2
```

...and then aborting the build while one of the `sleep`s are running. In that case the `in_parallel` step will call `.Succeeded` on both `sleep` calls, and one of them won't have `.Run` yet (because of the `limit: 1`).
