### ISSUE TITLE
Build containers are not interceptable after failed/success

### ISSUE THREAD

**Issue by chbiel** [concourse/concourse#5081]
Hi,
I currently try to debug one pipeline step by intercepting it (fly intercept -j ...).

The problem is, that containers are only available while they are running and a very short period of time after then ended.
Also some container (especially sucessful build) are not available at all after run.

Is there a config option to adjust the cleanup of those containers?
I would expect such explaination on https://concourse-ci.org/caching-and-retention.html#build-retention but it very empty :)

Thanks in advance

**Comment by pivotal-jamie-klassen** [comment]
Looking at the code here:
https://github.com/concourse/concourse/blob/master/atc/db/build_factory.go#L88-L106
the build collector will mark every successful build as non-interceptible.

Some questions:
1. Why do you need to debug builds that are successful? Would it make sense for your scripts to make some assertions and fail under certain circumstances? Maybe you could inject some `sleep`s in your scripts if you need to observe them more carefully?
1. Are the containers you're interested in strictly task containers? Could you use `fly execute` to get feedback? If you need to inspect resource containers too this is less helpful.
1. Can we really carefully validate the usefulness of a new feature where the build collector should grant a grace period to _all_ containers, not just failed ones? On large/busy clusters this could have a heavy operational impact.

If none of the above is useful, you could slow down GC for your entire cluster by increasing `--gc-interval`/`CONCOURSE_GC_INTERVAL` to a value larger than the default of `30s`. But this is probably going to have unintended consequences.

**Comment by chbiel** [comment]
Thanks for your suggestions.
The challenge is that we experience a flaky test jobs. As we cannot reproduce it locally we would need to analyse in more depth what is happening in the pipeline.
One step here would be to compare the environments in a failing and a successful build. But this would mean that the containers need to be interceptable for some time.
