### ISSUE TITLE
Add pipeline config viewer to UI

### ISSUE THREAD

**Issue by benschmaus** [concourse/concourse#5083]
## What challenge are you facing?

My team runs a fairly large Concourse deployment that supports 400+ teams and in the ballpark of 3k pipelines.  Our users often have questions that require viewing pipeline configurations to help them with troubleshooting.  It would be convenient to be able to view a pipeline's YAML configuration directly from the UI.  As it is we use fly to login as different teams and then use the `get-pipeline` command to retrieve pipeline config.  Obviously using fly works just fine but it would save us some time if pipeline config viewing was built right into the UI.

## What would make this better?

In addition to the graphical pipeline visualization in the UI, it would be helpful to be able to view a pipeline's YAML configuration without having to switch to a terminal and execute fly commands.  (This is similar to https://github.com/concourse/concourse/issues/1718 though is a simpler implementation since it involves viewing the current pipeline config rather than tracking the config per execution.)

## Are you interested in implementing this yourself?

Possibly although UI development isn't in my wheelhouse.

**Comment by robwhitby** [comment]
We had the same idea, so use a browser plugin like tampermonkey to modify the pipeline view. It puts a link to `/api/v1/teams/<team>/pipelines/<pipeline>/config` in the bottom-right corner of the screen, under the concourse version.

```javascript
function addConfigLink() {
	let configUrl = window.location.href.replace('hostname.com/', 'hostname.com/api/v1/') + '/config';
	var cell = document.querySelector("table.lower-right-info").insertRow(-1).insertCell(0);
	cell.colSpan = 2;
	cell.innerHTML = `<a href="${configUrl}">pipeline config</a>`;
}
```

**Comment by gturri** [comment]
Thanks @robwhitby , your suggestion works fine! (well, having this feature built-in in the UI would be better than letting each user configure its tampermonkey script, but it's a very nice workaround! 👍)

As a tamper monkey noob it took me quite some time to get it to work as I wanted, in particular to get the link when I click on a pipeline link from Concourse main page (because in this case Concourse does not reload the page, it just changes the URL). In case it might save time to other people, here is the script I ended up with:

```
// ==UserScript==
// @name         concourse config
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Add a link on concourse pipeline pages which display the pipeline config
// @author       robwhitby
// @match        https://hostname.com/*
// @icon           https://hostname.com/public/images/favicon.png
// @require      http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
// @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
// @grant        none
// ==/UserScript==

waitForKeyElements("table.lower-right-info", addConfigLink);

function addConfigLink() {
    'use strict';

    var element = document.querySelector("table.lower-right-info");
    if (element != null) {
         let configUrl = window.location.href.replace('hostname.com/', 'hostname.com/api/v1/') + '/config';
         console.log("Going to insert url " + configUrl);
	 var cell = element.insertRow(-1).insertCell(0);
	 cell.colSpan = 2;
	 cell.innerHTML = `<a href="${configUrl}" target="_blank">pipeline config</a>`;
    } else {
      console.log("Not on a pipeline page");
    }
}
```
