### ISSUE TITLE
Retry steps upon worker disappearing

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#5086]
## What challenge are you facing?

In any cloud infra, VM crashing is something "normal". As most of Concourse workers run in cloud, Concourse should be able to handle worker disappearing.

Currently, when a worker disappears, Concourse just fails the running steps, and log an error on the Web UI, which makes production pipelines unreliable.

In our production clusters, this is becoming a very serious issue.

## What would make this better?

Concourse should be able to handle errors of worker disappearing, and automatically rerun failed steps on other workers.

I also realize blindly rerunning some `put` steps may lead to problem, so we may add a flag to `put` step to allow user to turn off auto rerun.

## Are you interested in implementing this yourself?

I can try.

**Comment by evanchaoli** [comment]
@vito Can you please comment on this issue?

**Comment by kcmannem** [comment]
any insight as to why they're disappearing?

**Comment by evanchaoli** [comment]
> any insight as to why they're disappearing?

It could be various reasons. For example, 1) The VM where worker runs on crashes; 2) The host where worker VM runs on goes offline. Not really related to Concourse itself.

**Comment by robwhitby** [comment]
this would be great as it would allow us to use spot instances/pre-emptible vms and save big $$

**Comment by vito** [comment]
Makes sense to me! This is in the spirit of Concourse as all steps are meant to be idempotent.

That being said, we may want to start by having this sort of thing off by default while we feel things out. If things seem OK I could see us making it the default in the future.
