### ISSUE TITLE
Add a default resource check interval for webhooked resources

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#5088]
## What challenge are you facing?

Many pipelines use Gitlab resources, and resource checks poll Gitlab every 1 minute, which generate significant API calls to Gitlab, thus we have received a concern from the Gitlab team. Plus https://github.com/concourse/concourse/issues/4940, I'm consider to prompt usage of webhook.

When a resource has webhook configured, resource checks are supposed to be driven by webhook. Though periodical checks are still there, they don't have to be as short as 1m, maybe 1h is good enough.

But I don't want to ask users to add two more parameters `webhook_token: xxxxx` and `check_every: 1h`. When `webhook_token` is configured, Cocnourse should default check interval to 1h (configured by another atc parameter).

## What would make this better?

Add a new CLI option to `concourse web`, named `--resource-with-webhook-checking-interval`, default to 1h. When a resource has webhook configured, use this value for its default check interval.

## Are you interested in implementing this yourself?

Yes, I can.

**Comment by vito** [comment]
Really wish there was a way to configure stale bot to not concern itself with issues that have associated PRs...
