### ISSUE TITLE
Implement tracing for the algorithm

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5094]
* [x] Trace algorithm recursion and etc. through the various resolvers
* [x] Trace spans or events for when incremental migrations are performed

**Comment by cirocosta** [comment]
👍  

using [hush-house](https://github.com/concourse/hush-house), you can target it:

```
http://simplest-collector.jaeger.svc.cluster.local:14268/api/traces
```

then access it on `localhost:25000`:

```
kubectl -n jaeger port-forward service/simplest-query 25000:16686
```
