### ISSUE TITLE
containerd: ensure we're not leaking contexts

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5099]
### What challenge are you facing?

In our first iteration of using [`context.WithTimeout`] for guaranteeing that
our requests have a bounded amount of time to return, we end up doing so
without taking proper care of their `cancel` functions.

e.g., in 

https://github.com/concourse/concourse/blob/4d739fd1a91866fcd648593bc8be23d6aecbe3f0/worker/backend/backend.go#L103-L108

we're clearly ignoring `cancel` there, making the the context to "leak" until
the timer is reached, i.e.  in the way we're doing, we're keeping contexts
around for longer than they should:

[`context.WithTimeout`]: https://golang.org/pkg/context/#WithTimeout

> The WithCancel, WithDeadline, and WithTimeout functions take a Context (the
> parent) and return a derived Context (the child) and a CancelFunc. Calling the
> CancelFunc cancels the child and its children, removes the parent's reference
> to the child, and stops any associated timers. **Failing to call the CancelFunc
> leaks the child and its children until the parent is canceled or the timer
> fires**. The go vet tool checks that CancelFuncs are used on all control-flow
> paths.

https://github.com/golang/go/blob/0d34f5f09b155a9a7496490d6204f6f18179f098/src/context/context.go#L16-L23

### What would make this better?

Have `cancel` always captured, and call it when not needing that context anymore (the usual `defer cancel()`).

Related:

- https://github.com/concourse/concourse/issues/5051

**Comment by pivotal-jamie-klassen** [comment]
how about a CI job that runs `go vet` to keep us honest?

**Comment by cirocosta** [comment]
@pivotal-jamie-klassen that'd be greeeeat! I remember Topher had https://github.com/golangci/golangci-lint running in a job 👀

**Comment by cirocosta** [comment]
@pivotal-jamie-klassen https://github.com/concourse/ci/issues/263
