### ISSUE TITLE
Refactor scheduler interfaces

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5122]
The [scheduler runner](https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/runner.go) currently does a lot of fancy footwork to get data passed around in ways for the scheduler and algorithm to consume.

First, we get all the jobs to schedule...:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/runner.go#L50-L53

This part is fine, but then we make this complicated job-to-pipeline and pipeline-to-job mapping:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/runner.go#L171-L197

We later loop over all the *pipelines* and "schedule" each pipeline:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/runner.go#L61-L68

To schedule a pipeline, we fetch all of its resources and fetch all of its jobs, and then construct a job-name-to-id map:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/runner.go#L86-L89

We then pass the job we're scheduling, along with its pipeline, the pipeline's resources, and this job-name-to-id map down to the actual scheduler:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/runner.go#L141-L148

The first thing the scheduler does is to get the job's inputs:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/scheduler.go#L38-L41

This method returns a slice of `atc.JobInput` types, which have **names**, not **IDs** for its references resources and jobs. So the query converts the IDs in the database to names:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/db/job.go#L194-L203

The algorithm then converts those **names** back into **IDs**:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/algorithm/resolver.go#L53-L60

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/algorithm/resolver.go#L86-L90

Going back up the stack, the scheduler also passes the resources to two places:

First, it passes it to `manuallyTriggeredBuild`, which uses is to wait for its upstream resources to have `check`ed after the build was created:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/buildstarter.go#L107-L114

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/build.go#L26-L40

Second, it passes it to the build factory, to be used when constructing the build plan:

https://github.com/concourse/concourse/blob/8f75b035f398367468c58018df337f1cede61f59/atc/scheduler/buildstarter.go#L221-L234

(Note that immediately above it we just fetch the resource types directly from the pipeline. Interesting. :thinking: )

## A modest proposal

* If we change `(db.Job).Inputs` to return a scheduler or algorithm type instead, using IDs and `JOIN`ing to the `resources` table to collect its pinned version, we won't have to pass the resources and job-name-to-ID-map to the algorithm at all.
* If we change `manuallyTriggeredBuild` to just join through `job_inputs` to check if any of them have checked, we won't need to pass the resources to it.
* If we change `JobsToSchedule` to something that fetches not only the jobs, but all the information necessary to schedule a job, we can avoid the complicated mapping done in the runner, and we might have better guarantees about collecting the various pipeline configs atomically (imagine someone does a `fly set-pipeline` in the middle of a scheduling tick) and not have to query for pipeline resources or resource types throughout the build factory.

My overall goal is to shrink the amount of arguments being passed around such that the scheduler runner is literally something that just does "get all jobs to schedule" -> "loop over them and schedule them with a max-in-flight".

**Comment by clarafu** [comment]
To do:
- [ ] move config pinned version into separate column in jobs table
- [ ] Add method to `db.Job` that returns back `algorithm.InputConfigs`
- [ ] check if resources have been checked through the `job_inputs` table
- [ ] refactor `JobsToSchedule` to return necessary information (?)
