### ISSUE TITLE
fly: passing a nonexistent `--team` gives a misleading error

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#5126]
## Bug Report

When I run `fly hijack`, `fly jobs`, `fly trigger-job`, `fly pause-job` or `fly unpause-job`  with the `--team` flag set to a nonexistent team, the error suggests that something is not found, but doesn't always make clear that the team in question doesn't exist.

## Steps to Reproduce

```bash
$ fly -t ci pause-job -j concourse/unit --team doesntexist
```

## Expected Results

something like 'no such team'.

## Actual Results

```
error: concourse/unit not found on team doesntexist
```

## Additional Context

the `Team` method on the `Team` interface in the `concourse` package under `go-concourse` is quite confusing.

## Version Info

* Concourse version: 6.0.0-pre (master)
* Deployment type (BOSH/Docker/binary): n/a
* Infrastructure/IaaS: n/a
* Browser (if applicable): n/a
* Did this used to work? No

## TODO

- [x] Trigger-job
- [x] hijack
- [x] job
- [x] pause-job
- [x] unpause-job

**Comment by taylorsilva** [comment]
After much context loading we removed the `found` return value from
FindTeam from the concourse.Client struct. We brought back the
switch..case statement so we can return a custom error message when we
get a 404. All other errors are returned as is. In the fly code we can
now return the error from go-concourse as-is and it should be a helpful
error message ("team 'doesnotexist' not found").

cc @muntac

**Comment by taylorsilva** [comment]
The refactoring continues! We found that it's really hard to return helpful error messages with go-concourse. We're slowly refactoring by creating a new interface that meets our needs and using it in the code paths and tests that we're currently concerned with. The hope is that we'll use this new client everywhere in go-concourse and ditch the old `connection` client.

**Comment by taylorsilva** [comment]
Commits have been squashed on our branch `issue/5126`! We need to remove the `adminATCServer` and update all the related tests to ensure they make sense and pass.
