### ISSUE TITLE
containerd: support configuring default DNS nameservers

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5138]
### what challange are you facing

the current implementation has a hardcoded set of values for `/etc/resolv.conf`:

https://github.com/concourse/concourse/blob/54991b2f1f17bd7d229a3ebbe6d6c16f3ff495a3/worker/backend/cni_network.go#L183-L186

while this is meant to work for those who rely only on external services (on ThE
InTeRwEbS), it's not something that would fit those who

- run jobs that require any form of internal DNS resolution
- do not trust 8.8.8.8

### what would make this better

allow one to configure the set of nameservers listed under `/etc/resolv.conf`
(like `guardian` allows with the `--dns-server` flag)

https://github.com/cloudfoundry/guardian/blob/bcca70921740300398648046496790876981b158/guardiancmd/command.go#L157-L158

**Comment by cirocosta** [comment]
ps.: with the ability to have the set of nameservers configured, we'll be able to allow those folks who run in environments where the use of `CONCOURSE_GARDEN_DNS_PROXY_ENABLE` is necessary to make use of Concourse's DNS server.

**Comment by vito** [comment]
Acceptance criteria: when running `concourse worker --container-dns-server 1.1.1.1 --container-dns-server 1.1.2.2`, if I `fly intercept` into a build container I should see those addresses listed in `/etc/resolv.conf` in the order that the flags were given.

**Comment by muntac** [comment]
TODO: Verify the format of resolv.conf in Guardian containers matches containerd containers.
