### ISSUE TITLE
containerd: support the use of concourse worker's DNS server

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5139]
### what challange are you facing

with the inability to configure the set of nameservers that containers should
use by default (see #5138), users who rely on
`CONCOURSE_GARDEN_DNS_PROXY_ENABLE` (e.g., to run `concourse` as part of a
`docker-compose` set up and reach other services in the docker network) can't
move to `containerd` because it'd never put Concourse's DNS server as a
nameserver under `/etc/resolv.conf` inside the containers.

### what would make this better

have Concourse's proxy DNS server listed as a nameserver in the set of
nameservers on the `/etc/resolv.conf` that gets injected into containers.

**Comment by vito** [comment]
Sounds like we just need to change the `/etc/resolv.conf` content to include the IP address of the proxy server instead.
