### ISSUE TITLE
`set-pipeline` with new groups doesn't refresh the Groups bar

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#514]
In our case, the specific behavior was we had no groups before. We were simultaneously renaming many jobs, but that part worked great--the pipeline view auto-refreshed as expected. But our groups did not auto-refresh. Refreshing the page caused the groups to appear.

**Comment by vito** [comment]
This should be done now. It takes a bit for it to refresh, but that should be good enough for CI monitors and such.
