### ISSUE TITLE
Removing a worker makes it impossible to build a job

### ISSUE THREAD

**Issue by aquavitae** [concourse/concourse#516]
I had a problem with one of my workers (missing internet access), so while it's being sorted out I removed it and added another temporary worker. However, a job which previously ran on the missing worker fails with the error "worker for container missing".  The docs don't say much about how to stop workers so I assumed that if I simply stopped it concourse would start using another one instead, but this doesn't seem to be the case. What is the right way of removing a worker, or is this actually just a bug?

I can get it to work by destroying the pipeline and recreating it, but that seems like overkill and loses any history.

**Comment by vito** [comment]
This should recover over time (>5 mins - the amount of time it takes for the `check` containers to expire).

Workers can go away and come back and we'll continue to use the containers that were on it. Once the `check` containers that were on it expire, we'll create them somewhere else. Builds that were in flight at the time the worker disappeared however will error; it's not safe to assume we can re-run them.

Long-term we should implement draining, so you can safely remove a worker, but it sounds like in this case the worker was misbehaving, so I'm not sure that would help.

**Comment by aquavitae** [comment]
I didn't wait 5 min, so waiting for the container to expire could be the issue.  I don't think that this behaviour is particularly problematic, but it's not at all transparent.  How about adding something to the documentation about worker removal? Or at least making the error message a bit more informative?  I'll happily write a PR for the docs if you can point me in the direction of the appropriate section.

**Comment by vito** [comment]
This should be fixed by https://github.com/concourse/concourse/issues/629 - collapsing discussion into there. Thanks!
