### ISSUE TITLE
Allow `fly execute` to run using params defined/stored in an existing Concourse task

### ISSUE THREAD

**Issue by bendodd** [concourse/concourse#517]
It appears that to run a task using `execute` you need to define all the params as env vars. This is both time consuming to configure, assuming a task with 15 or so params and multiple spaces/environments, and likely to result in errors/typos. I.e. it's hard to ensure the task is re-run with the only change being the input code [and not the tasks environment]

**Comment by edespino** [comment]
With complex & long running pipelines, being able to execute a task is indispensable.  Support for "--load-vars-from“ in fly execute would be very helpful.  We can’t afford to accidentally leak credentials into a public repo.  Thanks for the help and for listening.

**Comment by vito** [comment]
see https://github.com/concourse/concourse/issues/291#issuecomment-236266633

**Comment by vito** [comment]
Am I reasonable in thinking this is the same as https://github.com/concourse/concourse/issues/454 ? Gonna pre-emptively close, but feel free to reply or reopen (not sure if you can actually) if you disagree.
