### ISSUE TITLE
aws security: how to limit ec2-metadata access from the container execution environment?

### ISSUE THREAD

**Issue by avoidik** [concourse/concourse#5182]
Hello,

could you please suggest a way how to prevent concourse's container runtime engine (garden?) accessing the EC2 instance metadata, but in the same time keep it available for the worker/server internal needs? i.e. isolation of the container's execution layer from the host.

Kind regards

**Comment by cirocosta** [comment]
Hey @avoidik ,

If I correctly understood what you're trying to achieve, you could do something like this:

```
    - name: CONCOURSE_GARDEN_DENY_NETWORK
      value: "169.254.169.254/32"
```

https://github.com/concourse/hush-house/blob/290f5fdecc0c160147e6fef7c00349c6690f0a56/deployments/with-creds/ci/values.yaml#L75-L76

which would make [`guardian`] place a `REJECT` jump for that subnet, but only for traffic from the containers

```
-A w--default -d 169.254.169.254/32 -j REJECT --reject-with icmp-port-unreachable
``` 

[`guardian`]: https://github.com/cloudfoundry/guardian

**Comment by avoidik** [comment]
Thanks @cirocosta for your great advice! Have you tried to access metadata service by using octal representation like `curl 0251.254.169.254` after setting this parameter?

**Comment by avoidik** [comment]
Another option to prevent possible privileges escalation might be AWS IMDSv2

I'm going to close it
