### ISSUE TITLE
containerd: add back tests for Container & Backend destroy

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5184]
### challange

As @aoldershaw  pointed out in https://github.com/concourse/concourse/pull/5114#discussion_r378928924, during the transition from `container_stopper` to using a bare `killer` for taking care of stopping processes using a certain behavior, I end up "pausing" (commenting out) most of the tests that touched that functionality, and didn't add it back.

https://github.com/concourse/concourse/blob/50fbe0a0a58037262000222080db87b7285ba493/worker/backend/container_test.go#L42-L68

https://github.com/concourse/concourse/blob/50fbe0a0a58037262000222080db87b7285ba493/worker/backend/backend_test.go#L266-L302
 
### better

It'd be better to have that functionality tested again! Otherwise, it'd be pretty hard to be able to quickly iterate on that part of the codebase with confidence.

**Comment by muntac** [comment]
Reopening as I forgot to backfill tests in the container suite
