### ISSUE TITLE
Mount btrfs loopback device with discard option

### ISSUE THREAD

**Issue by pothos** [concourse/concourse#5187]
The loopback file uses more and more disk space when the filesystem gets used a lot. Mount the loopback btrfs filesystem with the `discard` mount option so that the loop device can punch holes in the backing file for deleted filesystem blocks.

**Comment by pothos** [comment]
Here the benefits of remounting manually with `discard` and triggering a discard action via fstrim (not needed if it stays mounted with this option because btrfs will do it itself in the future):
```
# Filesystem      Size  Used Avail Use% Mounted on
# /dev/sda3       435G  335G   78G  82% /
$ sudo mount -t btrfs -o remount,rw,relatime,space_cache,subvolid=5,subvol=/,discard /dev/loop0 /var/lib/concourse/volumes
$ sudo fstrim -v /var/lib/concourse/volumes
/var/lib/concourse/volumes: 335,9 GiB (360686080000 bytes) trimmed
# Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       435G  164G  249G  40% /
```

**Comment by mikroskeem** [comment]
I think that this is still important, adding `discard` option shouldn't be hard.

**Comment by pothos** [comment]
Definitely, thanks for picking this up!

**Comment by pothos** [comment]
Maybe to explain the issue again, but I may have slightly wrong memory: When the loopback file was created its size was calculated based on the size of the root file system and available space but when other things also write to the root filesystem, there is not enough space for the loop device anymore to grow to its maximum which it does without the discard option, filling the root filesystem up with this large loopback file.

**Comment by vito** [comment]
Thanks for bringing this to our attention, sorry I missed this! (And thanks @mikroskeem for submitting a PR!)

I hadn't heard of this option, but it sounds like exactly what we need. Further reading [here](https://outflux.net/blog/archives/2012/02/15/discard-hole-punching-and-trim/) for anyone curious.

This seems like a pretty cheap win. Space creep has been a bit of a known issue with the loopback device - if not just a metrics curiosity, as worker disk utilization would go up but never go back down. Not a huge problem when your workers VMs are single-tenant, but definitely a problem if you've got other things writing to disk. It'll be interesting to see if this one-line change magically fixes that.

**Comment by pothos** [comment]
You can also verify that it helps on a running system with the commands I pasted here: https://github.com/concourse/concourse/issues/5187#issuecomment-586297767

**Comment by muntac** [comment]
closed by https://github.com/concourse/baggageclaim/pull/37 Thanks, @mikroskeem!
