### ISSUE TITLE
fly execute fails to upload multiple inputs with `-x` if one is not a git repo

### ISSUE THREAD

**Issue by zaksoup** [concourse/concourse#519]
when running:
```bash
fly execute -i input1=. -i input2=../something_else -x` 
```

the upload will fail if `../something_else` is not a git repository.

The expected behavior would be that `-x` tells Fly to ignore relevant git files in inputs that are git repos and transparently upload the full directory when it is not a git repo.

Seems like this line here: https://github.com/concourse/fly/blob/master/commands/internal/executehelpers/uploads.go#L27 returns an error when trying to upload an input that is not a git dir when -x has been specified.

**Comment by vito** [comment]
consolidating into https://github.com/concourse/fly/issues/94
