### ISSUE TITLE
web: preload pipelines/jobs from local storage on dashboard

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5193]
## What challenge are you facing?

One significant source of slowness for loading the dashboard on large deployments is fetching the list of all jobs/pipelines. Even though the pipelines and their shape (their jobs and the dependencies between them) will likely change infrequently, we currently have to wait for these network requests to resolve before rendering anything meaningful on the dashboard.

## What would make this better?

Since the pipelines on the dashboard are likely to look about the same (ignoring build statuses), we can get a much faster first render by locally caching (probably localStorage) the pipelines/jobs responses and first rendering the dashboard with that stale information - once the actual requests finish and we have up-to-date information, we can update the view.

This introduces a few risks/things to keep in mind:

1. Once the network request finishes, the rendered pipelines may shift - if this network request finishes quickly, the dashboard could feel fairly jumpy and erratic
2. Before the network request finishes, we're displaying stale info - we need to make it clear somehow that this isn't necessarily the current state of the world. Any recommendations on how we can make this obvious (and just feedback on the feature generally) would be appreciated @Lindsayauchin @matthewpereira 
3. Unlike the size/shape of the pipeline cards, the build statuses *are* likely to change between page loads. I'm not sure what the best approach is for displaying build statuses when we only have the cached value - it might even make sense to ignore the last known build status and render the jobs as having an "unknown" status (again, not sure how this should look)

## Are you interested in implementing this yourself?

Yep

**Comment by matthewpereira** [comment]
Looks like you've made a ton of progress on this last week! Once you're back to working on it again, I'd love to pair up and see what we can do about visualizing what's going on.

**Comment by aoldershaw** [comment]
@matthewpereira I'd be happy to pair with you on this. [The PR](https://github.com/concourse/concourse/pull/5262) has a gif of what it looks like when you reload a page. I'm curious to hear your feedback on it!
