### ISSUE TITLE
Enable retry from conditions: [error] task

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#52]
Currently we can use `conditions: [failure]` but not `conditions: [error]`.

The initial driver for this is when using concourse to redeploy itself - see #51. Currently the redeploy step will error, although the underlying bosh deploy succeeds. This feature would enable an automatic retry, which would be a no-op and hence the overall job succeeds.

However, there's a more general use case for this feature - it could be useful to run specific tasks if/when others error (e.g. notifications, or cleanup)

**Comment by vito** [comment]
see also https://www.pivotaltracker.com/story/show/92634258

**Comment by xoebus** [comment]
Should be fixed in v0.57.0 with resources not returning `errored` when they fail and the new hooks!
