### ISSUE TITLE
Serial groups containing 0 running builds can have pending builds waiting on max-in-flight

### ISSUE THREAD

**Issue by anEXPer** [concourse/concourse#520]
It appears to be possible for a pending job to consider max-in-flight reached even when there are no other running jobs in the serial group.

We've seen this behavior a couple of times, and I think this is probably how to trigger it:

Given a serial group with multiple jobs, one of which is paused with a build pending on `checking job is not paused`, the rest of which are not paused, (and one of which is running)

When one of the unpaused jobs triggers (as a consequence of the completion of the running job),

It should see max-in-flight as not reached and start, but instead it sees max-in-flight as reached and waits on `checking max-in-flight is not reached`.

I don't have a clean reproduction of this yet. The parenthetical parts of the conditions above may or may not be necessary, but match the observed circumstances where this issue has arisen for us.

**Comment by anEXPer** [comment]
This bites us all the time and is infuriating. Any chance this bug will get prioritized anytime soon?

**Comment by jezemine** [comment]
we are also hitting this. it's a PITA.

**Comment by chendrix** [comment]
There is an explicit test case to trigger this behavior found in https://github.com/concourse/concourse/issues/994#issue-218579799

**Comment by cnelson** [comment]
Any idea on when this might be addressed?  This impacts us almost daily.
