### ISSUE TITLE
Releases RSS Feed

### ISSUE THREAD

**Issue by rubenv** [concourse/concourse#522]
Call me a dinosaur, but I love RSS feeds as a way to avoid having to poll every website. The only way I can currently find out about a Concourse release is by checking the website periodically.

I'd love to have an RSS feed for the releases page.

Is the website tracked in git somewhere? I'll gladly hack it in myself.

**Comment by vito** [comment]
You could follow the GitHub releases feed:

https://github.com/concourse/concourse/releases.atom

**Comment by rubenv** [comment]
Good enough! Thanks!
