### ISSUE TITLE
containerd: support max containers limit

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5226]
## What challenge are you facing?

In https://github.com/concourse/concourse/pull/5225, we can support setting CPU and memory limits according to the Garden spec. However, `gdn` supports going beyond the Garden spec for resource limits. In particular, we should add support for the `max-containers` flag.

https://github.com/cloudfoundry/guardian/blob/7818ab761574cbcf345f9ac33f0c6d8cba9f376f/guardiancmd/command.go#L176

## What would make this better?

Support this functionality so that our containerd backend achieves parity with `gdn`

**Comment by aoldershaw** [comment]
@cirocosta I added this story https://github.com/concourse/concourse/issues/5179, but after re-reading that epic description, I'm not sure if it's actually necessary.

While it is necessary for having the same functionality as Guardian, I'm not sure if this is something we use/Concourse users will want to use. What do you think?

**Comment by vito** [comment]
Investigate how Guardian keeps tabs on its containers; we'll want to make sure this is able to guard against concurrent creates, so we can't just check if we've hit the limit.

Related links:

* https://github.com/cloudfoundry/guardian/blob/master/gardener/gardener.go#L230-L241 (where Guardian checks if we've hit the limit)
* https://github.com/cloudfoundry/guardian/blob/b9201b81a0a5adfe9cafec2cb954e676a28e567b/guardiancmd/command.go#L115 (where Guardian has a flag to destroy containers on start)

If we have to keep track of this in-memory, let's make sure the value correctly resets back to the active number of containers on restart - assuming containers are still present after restart. Maybe just ask the `containerd` API prior to accepting create requests?

**Comment by xtreme-sameer-vohra** [comment]
As discussed in IPM with @scottietremendous , we're proceeding with Option 2
