### ISSUE TITLE
Job has no next build when there are multiple build re-runs

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5236]
## Bug Report

Jobs that have more than 1 build re-run are not rendered as "running" in the UI.

This doesn't seem to be a UI issue, however, since the API response for `/jobs` has `"next_build": null`

## Steps to Reproduce

1. Set a pipeline with any job
1. Run the job to completion (creates a `1` build)
1. Re-run the job to completion (creates a `1.1` build)
1. Re-run the job again (creates a `1.2` build)

## Expected Results

The UI displays the job as running and the `/jobs` endpoint includes a `next_build`

## Actual Results

`next_build` was `null`, so nothing was rendered in the UI

## Version Info

* Concourse version: master
* Deployment type (BOSH/Docker/binary): Docker

**Comment by pivotal-jamie-klassen** [comment]
I'm reminded of https://github.com/concourse/docs/pull/293/files?file-filters%5B%5D=.lit#diff-c8fdad2184c365a234324ad1f79eda2fR30-R36:
> if you rerun an old build, the status of the build will not show up in the pipeline page for the status of the job

I'm guessing this was an oversight in the interpretation of
> it isn't treated as the "latest" build of the job (unless it is a rerun of the latest build)

**Comment by aoldershaw** [comment]
Seems to be a result of the following query:

https://github.com/concourse/concourse/blob/7ec73b9be6203dd5e1ee7aaecd4e92daad9a6572/atc/db/build.go#L1569-L1578

In particular, `b.rerun_of = j.latest_completed_build_id`. `j.latest_completed_build_id` points to the latest completed rerun, while `b.rerun_of` seems to always point to the original build (e.g. builds `1.1` and `1.2` both have `rerun_of` pointing to `1`).

**Comment by clarafu** [comment]
@aoldershaw @pivotal-jamie-klassen Thanks for the detailed investigation and information! That seems to be exactly the problem, I added a fix for it with #5270
