### ISSUE TITLE
Cached versions of s3 resources should be invalidated when the resource is deleted (marked with a delete marker)

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#524]
We had a pipeline that was using a s3 resource that we deleted in AWS, however the pipeline did not error out. We discovered that it was using a cached version of the resource. This should have given us an error.

When you delete versioned resources in AWS, they are marked with a `Delete Marker`:
http://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html

The s3 object is not actually deleted in AWS, but AWS behaves as if it was. However, currently concourse will continue using a cached version of resources that are marked with `delete markers`

**Comment by vito** [comment]
Implementing this risks diminishing a lot of the benefits of caching. The caching works assuming no one's going out of band and muddying with what should be an immutable history. Do you have a proposal for how to accomplish this generic to all resources? I just don't want to make it too defensive, as a lot of assumptions it makes work great as long as best practices are followed.

**Comment by andrewedstrom** [comment]
As you suspected, the file that the s3 resource in question was pointing to is not an artifact generated by a pipeline. It's a snowflake artifact we uploaded manually to S3 and it's solely used as an input to a job in our pipeline.

We don't think this fix would need to be generic to all resources, because it seems like it's a problem with the `check` for the s3 resource specifically. Specifically, the `check` for this resource is succeeding and returning no versions when the resource definition refers to a filename pattern that no longer has any matching files in the bucket.  This happened because our pipeline was misconfigured, and in that situation, we expected that the `check` step would fail rather than happily return no new versions.  It's possible that the `check` container is not actually able to tell that we've deleted the old file because Amazon is marking it as "deleted" with a delete marker rather than making it actually go away. That's just speculative, though.

Also, sorry, we realized after we filed this that it should have been against concourse/s3-resource.

**Comment by vito** [comment]
No worries about the filing, `concourse/concourse` is always a safe bet. 👍 

I don't think this can be fixed specifically by the S3 resource.

Two issues in my mind:

1. Having a file that it's pointing to not exist is perfectly valid: it may be that the artifact has not yet been published, not that it was removed. So checking should not fail in this case.
1. The version will already have been detected - there's no way for a resource to convey that versions should be considered "deleted".
1. The cache is also already present - in principle if we had the second bullet point implemented we could run a `check` before every `get` of a resource, but that feels costly. Which brings me back to my original point of diminishing caching performance in order to be defensive.

**Comment by andrewedstrom** [comment]
Regarding point 1, there might be a way for Concourse to distinguish between artifacts that have not yet been published and artifacts which have been removed. From the delete marker documentation (http://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html):

> If you try to get an object and its current version is a delete marker, Amazon S3 responds with:
> - A 404 (Object not found) error
> - A response header, x-amz-delete-marker: true

If Concourse watched for the `x-amz-delete-marker: true` response header, S3 resource checks could fail when resources have been deleted without compromising the desired behavior of being able to point resources to files that don't exist yet.

Per your second bullet point, this would require implementation of a way for resources to convey that resources have been deleted.

**Comment by vito** [comment]
I still just don't think it's worth it. We'd have to do bullet points 2 and 3, which adds a pretty high cost for what will be a no-op 99% of the time. Thanks for the issue though; it was interesting to ponder, in relation to the new resource interface we're iterating on: https://github.com/concourse/concourse/issues/534
