### ISSUE TITLE
Ship patch releases

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#5240]
* [x] v5.2.7
    * [x] ~#5241~
* [x] v5.5.8
    * [x] ~bump baggageclaim to v1.6.6?~
    * [x] helm chart

**Comment by pivotal-jamie-klassen** [comment]
currently blocked on #5241 in the case of v5.2.7

**Comment by pivotal-jamie-klassen** [comment]
after discussion with @xtreme-sameer-vohra, @pivotal-izabela-gomes and @taylorsilva, we agreed that we can just pend the cow-cow testflight test on these two branches. Even though we're failing to meet Linux's stricter overlay semantics in v5, we're confident that our code is working _for all practical purposes_ on linux v4, which currently is the majority of production uses. As long as this test is the only place we're seeing incompatibility between 4 and 5, we're comfortable moving forward assuming our testing (against Linux 5) validates functionality on Linux 4.

**Comment by jomsie** [comment]
some scheduler changes are preventing the `rc` job from running. It feels like a can of worms. For now we will turn off and on the `serial: true` constraint on those jobs and see if it helps. Otherwise, we will pursue the full-fledged "emergency pipeline" strategy outlined in #5247

**Comment by jomsie** [comment]
looks like we made a slight misjudgement - the `rc` job does not have `serial: true` set - instead it has `serial_groups: [version]`. We were in a case where both the `rc` and `patch` jobs had a pending build, but neither had actually started. It seems they were deadlocking each other on that `serial_group`. Don't know if this sort of scenario ever arose pre-algorithm v3. Maybe worth making an issue...

**Comment by pivotal-izabela-gomes** [comment]
It's shipped!
