### ISSUE TITLE
Feature Request: Enhance testing on a github branch

### ISSUE THREAD

**Issue by youreddy** [concourse/concourse#525]
Travis makes it easy to run tests against new branches in github. Currently in Concourse, I would have to update the resource on my pipeline, reset the pipeline configuration, and remember to set it back to the original branch when I'm done. 

On Travis, I can push up a new commit to my branch and it automatically kicks off a build to run tests against the newly created branch.

**Comment by bendodd** [comment]
@youreddy Perhaps this might be of use? https://github.com/jtarchie/pullrequest-resource Even if just the basis to create your own branch resource?

**Comment by xoebus** [comment]
I don't know if @vito is ready to unleash it on the world but: https://github.com/vito/git-branches-resource is pretty legit.

**Comment by vito** [comment]
There's a related resource I want to make, `git-branch-heads`, which monitors `HEAD` of all branches and emits a version for each branch that changed. Then you can use `{version: every}` to run things across all branches, Travis-style.

The `git-branches` resource is more useful for the more heavyweight flow of automating entire pipelines. But if all you want is to run some unit tests across all branches, the `git-branch-heads` resource would be what you want.

**Comment by jtarchie** [comment]
`git-branch-heads` like it. Let me take a look.

**Comment by vito** [comment]
Consolidating discussion into https://github.com/concourse/concourse/issues/239 - thanks for the feedback though!
