### ISSUE TITLE
Documentation on `get` page is misleading / incorrect and needs deprecation

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#527]
The documentation of the `get:` and `resource:` fields are lagging behind the actual behavior (correct me if there's something in 1.4.0 that I'm missing; we're still running 1.3.0)

http://concourse.ci/get-step.html
- the description of `resource:` refers to `name:`, which doesn't exist any more
- however, `fly set-pipeline` doesn't validate that `name:` is an incorrect or deprecated parameter

So I thought I was getting it right, when I actually had things turned around

**Comment by jama-pivotal** [comment]
I think there were some recent PRs and changes to docs that makes it a bit more clear. Closing

**Comment by cjcjameson** [comment]
confirmed that #1185 did this and it carried over in the new booklit documentation. Thanks!
