### ISSUE TITLE
Smoke tests against the RC binary failing

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#5271]
## Bug Report

For each merged PR the [CI](https://github.com/concourse/ci) [pipeline](https://ci.concourse-ci.org/teams/main/pipelines/concourse) builds binaries. Smoke tests then run against the linux-ubuntu binary. These tests are now failing on two consecutive commits with the same error message.

## Steps to Reproduce

This will now likely occur whenever a new PR is merged in, and makes it through the pipeline.

## Expected Results

Smoke tests should pass, or fail due to reasons specific to the commit.

## Actual Results

The failing [builds](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke/builds/100) on the `bin-smoke` job have the following error:

```
BROWSER (error): Failed to load resource: the server responded with a status of 500 ()
  ✖ running pipelines Rejected promise returned by test
BROWSER (error): Failed to load resource: the server responded with a status of 500 ()
BROWSER (error): Failed to load resource: the server responded with a status of 500 ()
  ✔ running one-off builds (9.3s)
BROWSER (error): Failed to load resource: the server responded with a status of 500 ()
  ✖ reaching the internet Rejected promise returned by test
```

## Additional Context

The pipeline definition is in https://github.com/concourse/ci.

The `bin-smoke` [job](https://github.com/concourse/ci/blob/f228cc6892257c47d6189281b2c6779ce12f03c3/pipelines/concourse.yml#L744) takes the latest RC build of Concourse (put out by the previous step in `build-rc`), and remotely executes that binary on a long running VM. This VM until then was running the previous RC build. The job then runs some fly operations (via [wats](https://github.com/concourse/concourse/tree/master/web/wats)) against this Concourse deployment.

@pivotal-jamie-klassen pointed out this might be due to bad db migrations. He says that it might be the case that the migrations on master are broken, and that this [PR](https://github.com/concourse/concourse/pull/5113) that was recently merged probably includes a migration that needs its timestamp modified.

## Version Info

* Concourse version: Master since commit 1ae69250ceef7480f56732377478c46642c8791a
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: GCP

**Comment by pivotal-jamie-klassen** [comment]
- [ ] assess the root cause by SSHing into the machine, inspecting the logs and potentially the `schema_migrations` table in the database.
- [ ] If this confirms the theory, open a PR bumping the timestamp on the `1580135204_add_pipelines_last_update` migration. Ideally this change alone should fix the smoke environment on its next deploy.

**Comment by pivotal-jamie-klassen** [comment]
- [ ] Also let's check whether the `bosh-smoke` environment is in a similar state

**Comment by pivotal-jamie-klassen** [comment]
Finally, let's step back and understand that this really represents a limitation of our automation itself. The only reason we're so delicate about the order of timestamps is for the sake of these long-lived smoke environments that have RCs deployed to them. If we only ever deployed official releases to these environments we'd never encounter these skipped migrations.

How can we improve this scenario?
- is there some way the smoke deployments can be made migration-smart?
- can (or should) the migration library be smart enough to run new migrations even if they have an old timestamp?
- can we at least improve the diagnostic in these failure modes? Some kind of `check-migration-order` task in the smoke jobs could at least improve messages like "I saw a 500 error" to "12345_migration_xxx has the wrong timestamp"
- can we shift this feedback signal left? How much earlier could we learn about these kinds of problems in our codebase? Maybe a dedicated migration-checking job right at the very beginning could catch this stuff.

**Comment by YoussB** [comment]
A nice thing to know how to do:
```
fly -t ci i -j concourse/bin-smoke -s terraform-smoke -- ssh -i ci/deployments/smoke/keys/id_rsa <IP of bin-smoke VM>
```
we thought about automatically determining the IP in the same one-liner, but it got pretty hairy.

**Comment by YoussB** [comment]
running `journalctl -u concourse-web | grep pq` we see a ton of logs saying `column p.last_updated does not exist`, which confirms that the `1580135204_add_pipelines_last_update` did not run. The 1580135204 timestamp also does not appear in the `migrations_history` table in the DB.

**Comment by YoussB** [comment]
Informally, we think that the flow of control for migrations is as follows:
1. web node starts up
1. web node checks what the latest migration timestamp in the `migrations_history` table is
1. web node compares this to the list of migrations that were packaged into the binary via packr
1. any migrations that are newer than the timestamp in the DB are run in the correct order (via the "voyager" library)

Perhaps a better flow (less coupled to packr and hopefully allowing more sophisticated migration logic) would be
1. web node starts up
1. web node writes down every migration it was packaged with in a `all_migrations` (or similarly named) table
1. web node tells "voyager" library to figure out what to do.

We're particularly fond of this suggestion because it means that the DB alone can become a useful means of observing migration behaviour.

**Comment by pivotal-jamie-klassen** [comment]
I'm going to try to address the "new migration that _may have_ already run" question [here](https://github.com/concourse/concourse/pull/5293#issuecomment-597277452) by looking for the 1580135204 ftimestamp in the `migration_history` table in the hush-house database.

**Comment by pivotal-jamie-klassen** [comment]
Confirmed that bosh-smoke is in the same state:
```
concourse/ce8bab7c-042a-4de3-9b65-d1ac024f3cf3:~$ sudo grep pq /var/vcap/sys/log/web/web.stdout.log
```
also has many many lines mentioning the missing `last_updated` column.

**Comment by pivotal-jamie-klassen** [comment]
based on https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/downgrade/builds/144#L5e66cf37:154:158, we need to make the down migrations idempotent as well.

**Comment by pivotal-jamie-klassen** [comment]
Jobs are green!
