### ISSUE TITLE
set_pipeline to support var

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#5276]
## What challenge are you facing?

I'm building a pipeline that dynamically generates child pipelines and utilize the new `set_pipeline` step to submit child pipelines. But now `set_pipeline` can takes a static pipeline name, thus I'm blocked.

## What would make this better?

When I developed `set_pipeline` step, there was no `load_var` step. If we use var in pipeline name, then only way to pass value to var is via var_source or credential manager, which doesn't sound very useful.

As we 6.0 is going to introduce `load_var`, build a pipeline name dynamic by a previous step is very useful. Even the pipeline name can contain vars.

## Are you interested in implementing this yourself?

Yes

**Comment by vito** [comment]
This sounds like a fit for pipeline instances: https://github.com/concourse/rfcs/pull/34

**Comment by vito** [comment]
Closing per https://github.com/concourse/concourse/pull/5277#issuecomment-624282622
