### ISSUE TITLE
Managing multiple concourse instances with fly

### ISSUE THREAD

**Issue by cgfrost** [concourse/concourse#528]
I have to look after several different installs of Concourse at different versions, e.g. 1.4.1, 1.3.1, 1.2.0. This means I keep multiple copies of the `fly` executable around and have to remember which one is versioned right for the pipeline I'm working with today. Please find a better solution or just make the `fly` cli more flexible.

**Comment by cppforlife** [comment]
+1

**Comment by chendrix** [comment]
Is this any different than being forced to run `fly sync` between all the times you switch between various concourse versions?

I'm going to close this as we haven't seen much traction on it since July of last year.

Someone please re-open it if they have a compelling reason to.
