### ISSUE TITLE
Meta issue: CI monitor/radiator UI

### ISSUE THREAD

**Issue by vito** [concourse/concourse#531]
This issue aggregates feedback and feature requests pertaining to the CI monitor use case, as opposed to https://github.com/concourse/concourse/issues/530 which pertains to the desktop use case of browsing around and such. Right now they're the same UI, but we're planning on differentiating them, and splitting into two much more useful UIs.
- https://github.com/concourse/concourse/issues/227 was requested a while back and addresses the root concern which is higher-level "what's on fire" information radiation

**Comment by georgehaidar** [comment]
How will the radiator be accessed when Github OAuth is in use? Currently sessions are short and we would need to create a Github user with some automation around `fly login` on radiator machine

**Comment by robdimsdale** [comment]
we have too many pipelines to show them all so need an aggregator for our radiator. We rolled our own during hackday: bit.ly/cs-ci but before we spend effort improving it we would like to known what concourse's plans are and whether there are alternatives that already exist?

cc @kimeberz

**Comment by gregarcara** [comment]
Here's another solution posted to the slack channel today you might want to check out:

https://github.com/dgodd/concourse-summary

**Comment by robdimsdale** [comment]
Thanks, we will take a look.

Also @kimeberz a nice-to-have for us would be if a radiator could surface how "stale" a job/pipeline is - how long since it last ran. I haven't seen this feature request anywhere

**Comment by databus23** [comment]
This was posted in Slack yesterday: https://github.com/moodev/concourseci-radiator

**Comment by jama-pivotal** [comment]
We're finally doing something around this! Take a look at our proposed multi-pipeline views https://github.com/concourse/concourse/issues/1462 and https://github.com/concourse/concourse/issues/1442 . I'm going to close this issue in favor of those two master issues, but we'd love to get your thoughts on the two multi-pipeline proposals
