### ISSUE TITLE
Git resource only detects last commit in series of multiple commits

### ISSUE THREAD

**Issue by RochesterinNYC** [concourse/concourse#535]
This is the relevant part of our pipeline. The `trigger-node-builds` job will create multiple commits and then make one `put`s operation to the `node-builds` git resource. These multiple commits all make it to the git repo. However, in the `node-builds` resource, only the last commit in the series is detected. 

![screen shot 2016-07-14 at 11 09 58 am](https://cloud.githubusercontent.com/assets/1504464/16844543/8cea3014-49b3-11e6-8caf-20592393d1d4.png)

To be more explicit, the `node-builds` resource represents: https://github.com/cloudfoundry/buildpacks-ci/commits/binary-builds

Multiple commits `1ae604f` and `2dd2b81` were made and then both were pushed to the repo. However, the `node-builds` only detects `1ae604f`. This is despite us using the `version: every` directive on the `build-node` job's `get` for `node-builds`.

![screen shot 2016-07-14 at 11 13 47 am](https://cloud.githubusercontent.com/assets/1504464/16844686/0f610ffe-49b4-11e6-8739-93661c5aff28.png)

**Comment by RochesterinNYC** [comment]
We've come up with a fairly simple/minimalistic reproduction pipeline for this:

https://github.com/cloudfoundry/buildpacks-ci/blob/multiple-commit-repro/pipelines/repro-multiple-commits.yml

Pipeline: https://buildpacks.ci.cf-app.com/pipelines/repro-multiple-commits

**Comment by vito** [comment]
Ah, yep that's tricky. The `put` only yields one version, even though it technically pushed many. Perhaps something to think about with the next resource interface iteration.

**Comment by RochesterinNYC** [comment]
Ah gotcha, so removing the passed constraint for `node-builds` in our `build-node` in our first scenario wouldn't help at all?

**Comment by vito** [comment]
Right, the issue is in how the versions are being collected for the one you're `put`ing to.

See https://github.com/concourse/concourse/issues/535 - I may actually just close this issue if you don't mind.

**Comment by RochesterinNYC** [comment]
I think you linked the wrong issue?

**Comment by vito** [comment]
Woops my bad. https://github.com/concourse/concourse/issues/534

**Comment by RochesterinNYC** [comment]
gotcha. Yup, closing this in favor of that issue.
