### ISSUE TITLE
The status is still on "checking job is not paused"

### ISSUE THREAD

**Issue by YuPengZTE** [concourse/concourse#536]
The status is still on "checking job is not paused", when we do step by step on "Getting Started Takes 5 Minutes" of http://concourse.ci/ 
![image](https://cloud.githubusercontent.com/assets/20062886/16868761/0a3ef09c-4aac-11e6-991f-bed770d651b5.png)

**Comment by vito** [comment]
Dumb question, but is your job paused? Click `hello-world` on the build view and look for a play/pause button.

**Comment by YuPengZTE** [comment]
Thanks @vito

**Comment by vito** [comment]
No worries!

**Comment by srunix88** [comment]
I just wanted to add some additional commands that may help new users. I had the same thing happen. It seems to happen when you try to execute the job with the + sign when the pipeline is paused, then you realize that and you unpause the pipeline - it does not unpause the job.

using bb as the target:
fly -t bb jobs -p helloworld
name             paused  status   next   
job-hello-world  yes     aborted  pending

fly -t bb unpause-job --job helloworld/job-hello-world

**Comment by acambera-nearsoft** [comment]
I'm using 3.0.1 and tried to start a paused job and got `checking job is not paused`. Tried to start a job a few other times after setting the pipeline on "play" but it didn't work. I had to delete and restore the pipeline to make it work.
