### ISSUE TITLE
fly curl -- does not pass options to curl

### ISSUE THREAD

**Issue by HariSekhon** [concourse/concourse#5366]
## Bug Report

Running

```
fly curl <url_path> -- <curl_options>
```

does not seem to pass <curl_options> to the underlying curl command as documented here:

https://concourse-ci.org/administration.html#fly-curl

## Steps to Reproduce

```
fly -t ci curl /api/v1/teams/main/cc.xml -- -vvi
<Projects><Project activity="Sleeping" lastBuildLabel="1" lastBuildStatus="Success" lastBuildTime="2020-03-25T13:28:53Z" name="pytools/build" webUrl="http://localhost:8080/teams/main/pipelines/pytools/jobs/build"></Project><Project activity="Sleeping" lastBuildLabel="3" lastBuildStatus="Success" lastBuildTime="2020-03-25T21:52:05Z" name="bash-tools/build" webUrl="http://localhost:8080/teams/main/pipelines/bash-tools/jobs/build"></Project></Projects>
```

## Expected Results

You'd expect to see significant curl headers, such as:

```
...
> GET /api/v1/teams/main/cc.xml HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
...
```

## Actual Results

Only the XML output is shown implying the curl command never received the `-vvi` options from the fly command, unless the fly command is somehow sanitising and removing the extra curl output they generate??

I realize I could work around via:

```
fly -t ci curl /api/v1/teams/main/cc.xml --print-and-exit
```

but it's not clear to me whether this is a bug in the `--` behaviour supposedly passing raw options to curl.

Update: the below command triggers curl's pipeline output to stderr which doesn't get silenced by the curl `-s` switch appended after `--` implying that it is not an output filtering issue but rather the `-s` switch never arriving on the curl command line:

```
fly -t ci curl /api/v1/teams/main/cc.xml -- -s | cat
```

## Version Info

* Concourse version: 5.8.0
* Deployment type: Docker

**Comment by vito** [comment]
Looks like this was broken in https://github.com/concourse/concourse/commit/1d403d3fc94d8406b27c4f62ee71db41209eabf8 which added a 'query' argument. Not sure why.

It can be worked around by adding a bogus query param:

```
$ fly -t ci curl /api/v1/info foo=bar -- -vvv
```

**Comment by pivotal-jamie-klassen** [comment]
you can also pass an empty string for the the query. @xtremerui knows a lot about this issue.

**Comment by xtremerui** [comment]
My mistake here. I have submitted #5371 to fix it. Sorry!
