### ISSUE TITLE
Resource Types query is possibly causing database slowness

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5373]
## Bug Report

There have been a few cases where grabbing all the resource types in a pipeline query is possibly causing database slowness. 

```
SELECT r.id, r.name, r.type, r.config, rcv.version, r.nonce, r.check_error, ro.check_error FROM resource_types r LEFT JOIN resource_configs c ON c.id = r.resource_config_id LEFT JOIN resource_config_scopes ro ON ro.resource_config_id = c.id LEFT JOIN LATERAL ( SELECT rcv.* FROM resource_config_versions rcv WHERE rcv.resource_config_scope_id = ro.id AND rcv.check_order != 0 ORDER BY rcv.check_order DESC LIMIT 1 ) AS rcv ON true WHERE r.active = $1 AND r.pipeline_id = $2 ORDER BY r.name
```

## Steps to Reproduce

Possibly configure a concourse deployment with a lot of custom resource types?

## Additional Context

This is more of an issue to investigate if this query, under high load, can result in slowness. We are not exactly sure if it is the source of the problem but when we run a query to find the queries that are currently running, it seems to show that this resource types query is being run a lot.

## Version Info

* Concourse version: v6
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by agurney** [comment]
I've also seen a variation of this query at the top of our AWS "performance insights" chart of queries ordered by waits - in particular, it is showing up for CPU waits. The one I'm seeing ends with `... where r.active=true and r.id=12345` (for example; it's parameterized on the id), which is coming from `resourceType.Reload()`. It's not obvious to me that the full strength of this query is needed just for the reload - for example, the `rcv.version` looks to be ignored by the subsequent logic - but it's also not obvious to me what it's trying to do.

**Comment by clarafu** [comment]
Fixed by https://github.com/concourse/concourse/pull/7176
