### ISSUE TITLE
hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"create working directory: exit status 2","Handle":""}

### ISSUE THREAD

**Issue by piyush0101** [concourse/concourse#538]
We are using Concourse 1.4.1 and seeing this issue from time to time on S3 and Git resources. This usually goes away with a restart of concourse.

```
hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"create working directory: exit status 2","Handle":""}
```

**Comment by vito** [comment]
Can you collect more information from the worker logs?

**Comment by piyush0101** [comment]
@vito Here are the worker logs. Seems like the worker crashed resulting in this problem. Not sure why it crashed though.

[https://gist.github.com/piyush0101/60dd89327b50f725602d458b26143cdb](url)

**Comment by vito** [comment]
Weird, I don't see a single `exit status 2` in there. Maybe check if the worker is out of free disk space?

**Comment by piyush0101** [comment]
@vito 

Here are the last 2000 lines from the worker logs. I think the other gist is truncated.

https://gist.github.com/piyush0101/ecaf3cb171f76b91d5564d1d1f07fc39

**Comment by vito** [comment]
Hm, that file also appears to be truncated; it doesn't include the error message for the panic.

**Comment by piyush0101** [comment]
Ohk, this one should be the complete log

https://s3-us-west-2.amazonaws.com/concourse-logs/concourse-worker-1.log

**Comment by vito** [comment]
Looks like the worker machine (container?) ran out of threads. If you're deploying in Docker you may want to make sure the worker has a proper `init` that'll reap zombies:

```
{"timestamp":"1468630577.728555679","source":"baggageclaim","message":"baggageclaim.driver.run-command.failed","log_level":2,"data":{"args":["qgroup","show","-F","--raw","/var/lib/concourse/work/volumes/live/c9374be0-d4c7-4350-7541-116df9f06e45/volume"],"command":"/var/lib/concourse/work/1.4.1/linux/btrfs/btrfs","error":"fork/exec /var/lib/concourse/work/1.4.1/linux/btrfs/btrfs: resource temporarily unavailable","session":"1.25408","stderr":"","stdout":""}}runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f5f2d70c418 m=2

goroutine 0 [idle]:

goroutine 1 [select, 285 minutes]:
```

See also https://github.com/concourse/concourse/issues/507

**Comment by piyush0101** [comment]
Ahh ok, yea we are running the stand alone binaries in docker. Perhaps we should use something like https://github.com/Yelp/dumb-init

**Comment by piyush0101** [comment]
We are also running into insufficient subnets issues quite a bit, may be a proper `init` that will reap zombies also resolve that problem?

**Comment by vito** [comment]
You may want to take a look at https://github.com/MeteoGroup/concourse-ci

The 'insufficient subnets' issue is unrelated to zombie reaping, but I did see those other worrisome log entries related to container creation, and maybe those are leaving partially-instantiated containers around. Maybe the above linked image will fix that too?

**Comment by piyush0101** [comment]
Thanks. That's great!

We are already using the MeteoGroup repository with a few modifications. Will get the latest changes from them and that would hopefully fix a bunch of issues.

**Comment by vito** [comment]
Looks like they already had `dumb-init` in there, but it wasn't as pid 1 so things probably weren't being reaped. It was fixed 10 days ago: https://github.com/MeteoGroup/concourse-ci/commit/bd1e9e72af0e8404e8b5ac82d5d14be900551b65

**Comment by georgehaidar** [comment]
@vito this zombie reaping issue will come up a lot for teams deploying ConcourseCI using docker. Is it worth updating docs with instructions or know pitfalls when deploying the standalone binaries? We can quote the original error @piyush0101 seeing because it will be observed by any user that is not using an init process

**Comment by vito** [comment]
I'm gonna chat with one of the concourse Docker image maintainers to try
and make one official and document it.

**Comment by piyush0101** [comment]
@vito @georgehaidar We included `dumb-init` to our docker based deployments and it looks much much better now. Thanks for the suggestion.

**Comment by vito** [comment]
Glad to hear. Thanks for circling back!

**Comment by tuanphpvn** [comment]
My case. Follow the tutorial: https://concourse.ci/flight-school.html
The reason because: build.yml error. Just use yamllint fix it.

**Comment by gdenn** [comment]
Encountered the problem on 4.2.1
