### ISSUE TITLE
tracing demo

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#5382]
Against our prod environment, can we ask:
* average runtime of `put` steps to a `slack-notifier` resource?

**Comment by taylorsilva** [comment]
We have learned that the Jaeger all-in-one image uses an in-memory span store, that is difficult to query, so for this demo to work we need to deploy Jaeger with a more queryable storage solution.

**Comment by cirocosta** [comment]
@taylorsilva totally! might be worth doing it as part of https://github.com/concourse/hush-house/issues/119 I guess

**Comment by taylorsilva** [comment]
Let's get a minimal example going with elasticsearch and hopefully we can demo the queries we want with a simple frontend like mirage or dejavu - failing that, we may need to use elasticsearch as a datasource backing a grafana dashboard.

**Comment by taylorsilva** [comment]
Dashboard that displays the duration of the build step per pipeline in a cluster
<img width="1234" alt="Screen Shot 2020-03-31 at 3 58 57 PM" src="https://user-images.githubusercontent.com/4583837/78069734-9877c300-7368-11ea-92fc-d758fcefa817.png">

**Comment by taylorsilva** [comment]
We struggled with using grafana to visualize our data - it seems that the elasticsearch datasource is still a bit experimental or difficult to use.

Next steps:
* deploy elasticsearch/kibana via their helm charts in our GKE cluster - have the jaeger instance that is currently instrumenting prod store its spans in the new elasticsearch.
* gather realistic span data over time and show more compelling graphs

We realized that it might be good for spans associated to resource-related steps to be tagged with the resource type of the resource in question - this would enable queries like "show me the average runtime of all `put` steps to `slack-notifier` resources".

**Comment by taylorsilva** [comment]
Another interesting piece of data to surface would be a sampling of task exit codes, potentially binned by some pattern in the task name. E.g. "how many `deploy-*` tasks have a 5 exit code?"

**Comment by cirocosta** [comment]
@taylorsilva are y'all still only trying to answer that initial question

> *[what's the ...] average runtime of put steps to a slack-notifier resource?*

?

could you elaborate a bit more on what you're trying to do here? curious about the problem :grin:

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta the medium-term outcome is a compelling blog post that explains the tracing feature. What we're trying to do in this issue is take the first minimal steps towards driving out a narrative that lies somewhere between the blog post and the following probably-too-specific story:

Let's pretend I work at a big enterprise and we're adopting a company-wide "migration to the cloud" from our old on-prem suite of enterprise Java applications. My team is responsible for defining the way these applications get deployed to the cloud. Our mandate is to provide a very high value line: our "customers" (the teams of developers who work on those enterprise apps) should be able to consume our tool, which uses Concourse under the hood, and they should be able to have their apps deployed to the cloud but still be able to develop the apps as though they are running on legacy application servers.

We've settled on an approach where we provide a custom Concourse resource and a single job template such that our users can provide a few parameters and build themselves a pipeline that renders that job template (which includes a `get` step to our custom resource). The job template works by actually setting, unpausing, executing and pausing a second pipeline. The jobs/steps of this new pipeline are determined from the parameters provided by the team using some business-specific logic, and there is some sophisticated control flow managing the execution of those steps. Personally I've found it helpful to think of this "child pipeline" as mirroring the concept of a [Spinnaker pipeline](https://www.spinnaker.io/concepts/pipelines/).

Loosely speaking I have created a "deployment app" with a slightly unorthodox architecture, and I want application-level tracing of this app - when my users initiate a deployment request, I'd like to have a breakdown of all the spans involved in getting their code deployed -- essentially these are just the steps of the child pipeline. However, because I know these child pipelines are generated by my own business logic, I can, in some sense, consider them subsystems of my deployment app, so I might want to have cross-cutting views into their behaviour.

As a hypothetical example inside my hypothetical example: A common operation that gets executed in these child pipelines is a pre-deployment security scan. Suppose my whole deployment app is operating at scale, performing deployments for thousands of apps, but for some reason, whenever the ephemeral child pipelines perform their scanning step, they are taking much longer than usual (perhaps because they involve integrating with a third-party security tool, and I'm getting rate limited, or it's having a service disruption). I want to clearly visualize this impact - ideally in some kind of value-stream so I can tell my business partners where the deployment bottlenecks are, but also perhaps I'd like to alert on unusual execution time for these tasks so I can more easily debug or optimize them.

Knowing about the existence of characters like the one I've outlined above - can we demonstrate how they can leverage the existing tracing feature together with open-source data tools to achieve some of their desired outcomes? Would such a demonstration be compelling to your average "vanilla" Concourse user? Can we compromise and demonstrate some desired outcomes somewhere between the two?

**Comment by cirocosta** [comment]
gooooottttt iit, that makes a ton of sense - thanks!

**Comment by pivotal-jamie-klassen** [comment]
Assume that certain "step types" (tasks with `deploy` in their name, or resource puts to a certain resource type, etc) are reused across many teams/pipelines. Example views:
* has any step type started to take longer than usual lately? ("mean lead time")
* has any step type changed its exit behaviour lately? ("change failure rate")
* how often are the various step types executing? ("deployment frequency")
* maybe something related to "mean time to recovery" but this might be forcing the metaphor

Against our own prod environment, can we ask these questions about spans
* related to "bosh"
* related to "k8s"
* related to "smoke"
* related to "deploy"

**Comment by pivotal-jamie-klassen** [comment]
In the long-run we should document how to view tracing/related data visualizations in https://github.com/concourse/boarding-pass.

**Comment by pivotal-jamie-klassen** [comment]
before we consider this work done, we should make sure that jaeger consistently creates indices with `num-replicas: 0`

**Comment by pivotal-jamie-klassen** [comment]
Since we now have the relevant tools deployed and monitoring our production environments, the work today is around exposing Kibana to the internet (with GitHub authentication and TLS) and documenting its existence in boarding-pass.

**Comment by pivotal-jamie-klassen** [comment]
kibana and jaeger are exposed to the internet, and all the secrets are hidden away. Configuring kubernetes ingresses for helm charts was mostly pretty painless! Maybe not quite as simple as a `cf create-route`, but still pretty friendly and very flexible. Right now I own the OAuth client ID & secret for the tracing oauth2-proxy -- that should probably move over to the Concourse org.

**Comment by pivotal-jamie-klassen** [comment]
so as of now, the remaining items are:
* [ ] document tracing.concourse-ci.org in boarding-pass
* [ ] transfer oauth app to concourse org
* [ ] ensure jaeger creates elasticsearch indices with `num-replicas: 0`
* [ ] write a blog post?

**Comment by pivotal-jamie-klassen** [comment]
From https://operatorhub.io/operator/jaeger:

> On OpenShift, the operator can delegate creation of an Elasticsearch cluster to the Elasticsearch Operator if deployed.

wow, the magic of operators 😮 . Of course GKE is not OpenShift, and I don't mind having figured out how to deploy our own elasticsearch anyway.

**Comment by pivotal-jamie-klassen** [comment]
Closing this so it stops clogging our roadmap project - could still do a blog post, but it's feeling a bit less useful? @scottietremendous maybe you could describe the blog post requirements in another issue?
