### ISSUE TITLE
Deadlock in notifications bus causes all builds to hang

### ISSUE THREAD

**Issue by agurney** [concourse/concourse#5385]
## Bug Report

There is a deadlock scenario involving the "notifications bus" used in build management, where the delivery of notification messages contends with registration and deregistration of listeners. Both of those processes want to hold the same mutex. A deadlock occurs when the notification queue (a go channel internal to the pq library) is full. Briefly,
1. If the notification queue is full, then new notifications cannot be inserted by pq, and the goroutine that is meant to do that will block.
2. If it is blocked, then it cannot signal successful completion of a listen or unlisten request.
3. If that signal is not received, then a goroutine that is waiting for it (in ATC) will continue to wait. While it waits, it holds a mutex.
4. The ATC process that is meant to drain messages from the queue cannot do so until it acquires that same mutex. But it will never get it.

The outcome is that build initialization is stalled on that ATC, because there will eventually be many goroutines waiting to acquire that one mutex in order to register listeners. All of those builds appear "stuck" indefinitely. The number of stuck builds grows until the ATC process is shut down.

## Steps to Reproduce

We saw this after upgrading our Postgres DB to a more capable size in AWS RDS. My theory is that because the new DB is faster, it's filling up the queue more reliably. It may be possible to reproduce in a toy environment by blasting out a lot of notifications very quickly, but I haven't tried.

## Expected Results

Builds would run normally.

## Actual Results

For an affected ATC node, all builds become stuck. Build tracking locks are acquired, but not released, so we see that metric climbing consistently. Once this starts, all new builds on that ATC are affected; builds that had already started are able to "almost finish" but appear to hang after all steps are complete. Builds for which some other ATC is responsible, are fine.

We have been resolving this in practice by recreating the ATC node, which is a very forcible way to clear its mutexes and queues. This also entails some cleanup work in the database in order to mark affected builds as aborted, rather than have them appear "started". (That's not only cosmetic, but affects the max-in-flight calculations.)

## Additional Context

_Brace yourself, reader_, for stack dump trawling. The following excerpts were obtained from the `pprof` debugging endpoint on an affected ATC.

There are many instances of the following:
```
goroutine 1723146649 [semacquire, 30 minutes]:
sync.runtime_SemacquireMutex(0xc000dcbfdc, 0x423800, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000dcbfd8)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/concourse/concourse/atc/db.(*notificationsBus).Listen(0xc000dcbfc0, 0xc06f6d0760, 0x13, 0x0, 0x0, 0x0)
	/tmp/build/1c3187db/concourse/atc/db/notifications_bus.go:48 +0x2c4
github.com/concourse/concourse/atc/db.newConditionNotifier(0x2879920, 0xc000dcbfc0, 0xc06f6d0760, 0x13, 0xc08530a9b0, 0xc06f6d0760, 0x13, 0xc0005803b0, 0xc0154d1a20)
	/tmp/build/1c3187db/concourse/atc/db/notifier.go:13 +0x49
github.com/concourse/concourse/atc/db.(*build).AbortNotifier(0xc062e92780, 0x2895f01, 0x0, 0x0, 0x282c0a0)
	/tmp/build/1c3187db/concourse/atc/db/build.go:462 +0x135
github.com/concourse/concourse/atc/engine.(*engineBuild).Run(0xc023ec1900, 0x2895fa0, 0xc0014eccc0)
	/tmp/build/1c3187db/concourse/atc/engine/engine.go:170 +0x411
created by github.com/concourse/concourse/atc/builds.(*Tracker).Track
	/tmp/build/1c3187db/concourse/atc/builds/tracker.go:49 +0x425
```
with variations on the length of time of waiting for the mutex. These are attempts to start tracking a build, part of which involves registering in the notifications bus. (There are three such buses, but this particular one is the interesting one.) The attempt to `Listen` requires acquisition of the `notificationsL` mutex, in order to put new entries in the `notifications` map which it guards. We also see parallel stuck attempts to `Unlisten`.

The actual holder of the mutex is:
```
goroutine 1722571740 [chan receive, 34 minutes]:
github.com/lib/pq.(*ListenerConn).ExecSimpleQuery(0xc00096cac0, 0xc036b43c48, 0x1d, 0xc0225f0100, 0x0, 0x0)
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:304 +0x141
github.com/lib/pq.(*ListenerConn).Unlisten(0xc00096cac0, 0xc08bfaff00, 0x12, 0x12, 0xc055ca0138, 0xc036b43c01)
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:224 +0x92
github.com/lib/pq.(*Listener).Unlisten(0xc00060d960, 0xc08bfaff00, 0x12, 0x0, 0x0)
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:560 +0x150
github.com/concourse/concourse/atc/db.(*notificationsBus).Unlisten(0xc000dcbfc0, 0xc08bfaff00, 0x12, 0xc052d90070, 0x0, 0x0)
	/tmp/build/1c3187db/concourse/atc/db/notifications_bus.go:78 +0x155
github.com/concourse/concourse/atc/radar.(*intervalRunner).Run(0xc0282b2820, 0x2879520, 0xc004fafc80, 0x2830840, 0xc0761d33e0)
	/tmp/build/1c3187db/concourse/atc/radar/interval_runner.go:73 +0x376
github.com/concourse/concourse/atc/radar.(*Runner).scanResources.func1(0xc006722460, 0x2895fa0, 0xc03c258540, 0x2879520, 0xc004fafc80, 0x28c4a00, 0xc045c2c160, 0xc0771cd910, 0x10)
	/tmp/build/1c3187db/concourse/atc/radar/runner.go:118 +0x147
created by github.com/concourse/concourse/atc/radar.(*Runner).scanResources
/tmp/build/1c3187db/concourse/atc/radar/runner.go:113 +0x316
```
In this case, it's an `Unlisten` attempt for the same bus (at `0xc000dcbfc0`). Behind the scenes, this goes off to https://github.com/lib/pq to run the `UNLISTEN` SQL command. The process is blocked on `chan receive` because it is waiting for a signal from pq that the `UNLISTEN` was successful. That signal is meant to come from another goroutine, which does the actual database communication, and hence processes _both_ `LISTEN`/`UNLISTEN` requests, and the delivery of notifications.

_That_ goroutine is here (note the same address for `ListenerConn`):
```
goroutine 122 [chan send, 34 minutes]:
github.com/lib/pq.(*ListenerConn).listenerConnLoop(0xc00096cac0, 0x0, 0x0)
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:148 +0x31d
github.com/lib/pq.(*ListenerConn).listenerConnMain(0xc00096cac0)
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:188 +0x2f
created by github.com/lib/pq.newDialListenerConn
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:81 +0x124
```
It is blocking on `chan send`, because it's trying to send a message over a different channel. Instead of using `replyChan`, which is the one hooked up waiting for the "I successfully unlistened" signal, it's using `notificationChan`, which is the one for delivering actual notifications from the DB into application code. This is a bounded channel of size 32, which means the go runtime will block if all 32 slots are in use. So this goroutine cannot make progress until somebody pops something off the channel. That somebody is:

```
goroutine 115 [chan send, 34 minutes]:
github.com/lib/pq.(*Listener).listenerConnLoop(0xc00060d960)
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:781 +0x1b7
github.com/lib/pq.(*Listener).listenerMain(0xc00060d960)
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:795 +0x2b
created by github.com/lib/pq.NewDialListener
	/tmp/build/1c3187db/gopath/pkg/mod/github.com/lib/pq@v0.0.0-20181016162627-9eb73efc1fcc/notify.go:464 +0x12c
```
which is another bit of internal pq plumbing. Here, we're in a tight loop of pulling messages off `notificationChan` and stuffing them into `l.Notify`, but we're blocked because the latter channel - also of bounded capacity - is full. This `Notify` is the channel which is _actually_ hooked up to the application-side code. In Concourse, it's used in `(*notificationsBus).wait`, which is the routine that takes those notifications from the DB and routes them to the appropriate waiting goroutines in ATC. Here's the relevant instance of `wait`:

```
goroutine 116 [semacquire, 34 minutes]:
sync.runtime_SemacquireMutex(0xc000dcbfdc, 0xc000016600, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000dcbfd8)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/concourse/concourse/atc/db.(*notificationsBus).wait(0xc000dcbfc0)
	/tmp/build/1c3187db/concourse/atc/db/notifications_bus.go:92 +0x2a9
created by github.com/concourse/concourse/atc/db.NewNotificationsBus
	/tmp/build/1c3187db/concourse/atc/db/notifications_bus.go:33 +0x89
```
The goroutine is waiting on the very same `notificationsL` mutex, currently held elsewhere. It wants this mutex because it needs to traverse the `notifications` map of destination channels. But it will not get it: it's being held by goroutine 1722571740 above.

So we have a deadlock, because the holding goroutine won't release the mutex until it's informed that the `UNLISTEN` worked. It won't get that signal until the tracking goroutines inside pq deliver it, but that code is blocked waiting for messages to come off the `Notify` channel. The code which could do that, is waiting for its chance on the mutex.

## Version Info

* Concourse version: 5.7.0
* Deployment type (BOSH/Docker/binary): bosh workers, binary ATC
* Infrastructure/IaaS: AWS
* Browser (if applicable): N/A
* Did this used to work? yes, but since we bumped up the DB size, it's been recurring every couple of days

**Comment by vito** [comment]
Neat! Thanks for digging into this, I'll chuck it onto the roadmap so we can take a look. I'm kind of surprised we haven't seen this before, but it may also be the case that we *have* and just didn't know it because no sleuthing was done.

**Comment by agurney** [comment]
I expect it's a combination of us having a lot of load, a big/fast DB, and the sleuthing. It may be pretty sensitive to the relative speeds of the different components. We're taking our own look but are definitively appreciative of anything the central community and maintainers can come up with - this is a part of the codebase I haven't thought about before.

**Comment by vito** [comment]
@agurney FYI, looks like we just ran into the same issue in one of our environments. Great timing on the report! 😄
