### ISSUE TITLE
Archiving a pipeline purges its config

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5389]

**Comment by YoussB** [comment]
We did some research to find out how the implementation of this will work.

- The following tables have a `config` column in the db that we can clear out to an empty json object `{}` and the pipeline doesn't break in the UI:
  - jobs
  - resources
  - resource_types
  - **open question**: if db encryption is set, do we have to worry/handle this use-case in the code we write at the db layer? Can we re-use the functions that the `db.Team.SavePipeline()` calls (e.g. `team.SaveJobsAndSerialGroups()`)?

Next Steps:
Explore the functions used by `db.Team.SavePipeline()` to see if they can be re-used to clear out a pipeline's job, resource, and var_source configs. Can probably start writing some real code and tests.

**Comment by aoldershaw** [comment]
@YoussB: really sorry, @jomsie and I actually started on this last week, but I guess we forgot to push our WIP! I think we got to clearing job and resource configs, but didn't yet tackle resource_types.

You can find our work here: https://github.com/concourse/concourse/tree/issue/5389

**Comment by YoussB** [comment]
We took @aoldershaw and @jomsie's WIP commit and cherry-picked it onto a new branch here: https://github.com/concourse/concourse/tree/issue/5389-purge-config

This branch is sitting on top of all the rebasing we did. We tried to rebase on `issue/5389` but it got weird and we weren't confident that it had all the commits we wanted.
