### ISSUE TITLE
Check stderr output should appear in the UI

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#540]
Just like we can see the contents of stderr for a resource's `get` and `put`, we should also allow users to see the output of `check`. Currently resources have to write to a log file, which requires intercepting the correct container in order to view the output.

Each `check` runs quite frequently so there is a potential for concourse to store a lot of output here, but I would be surprised if it's much more than what is already saved in the database.

**Comment by vito** [comment]
it already does if it's failing. do you want this in the happy path too?

**Comment by robdimsdale** [comment]
I didn't see that it printed the output on error - that's a big help so thanks for that.

I think I would also like a way to view the happy-path output too, the case i'm thinking of is the resource is misconfigured in such a way that it will exit 0, but it doesn't return what the user expects (e.g. the wrong branch in git, the wrong regex in s3).

**Comment by vito** [comment]
consolidating this into https://github.com/concourse/concourse/issues/406
