### ISSUE TITLE
Retention period for failed containers should be configurable

### ISSUE THREAD

**Issue by ebilling** [concourse/concourse#5411]
##  What challenge are you facing?

We have lots of failed jobs for various reasons and it causes the number of containers to balloon.  This in turn kills performance and those containers sit around forever, so the problem just gets worse.  We've started pausing pipelines to clean up check containers, and that helps, but for the failed jobs, there is nothing we can do.

The point of leaving the failed job containers around is that engineers can log into those containers and poke around.  In our environment we don't allow that access, so there is no practical reason to keep the containers around for us.

## What would make this better?

Garbage collection should remove containers that have been sitting around for some period of time.  In our situation, because we don't allow for logging into the containers anyway, it could be immediate, but for others, it may be a day or week.  As with other configuration settings having it set to 0 should maintain the current infinite behavior.

## Are you interested in implementing this yourself?

This is a big problem for us, and we are willing to put in the time to make the contribution.  Would like to discuss the implementation beforehand though.

**Comment by cirocosta** [comment]
Hey @ebilling , thanks for submitting the issue!

I think this is pretty much the same as https://github.com/concourse/concourse/issues/3892, which @vito indeed marked as "help wanted" - your help would be much appreciated 👍 

 In https://github.com/concourse/concourse/pull/5305, @pivotal-jwinters did some work with regards to how containers get GCed (even though it was focusing more on hijacked containers), so I guess that'd be a nice point to take a look at 😁  

Let us know if you need any further help 👍 

thank you!

**Comment by ebilling** [comment]
Thanks.  Definitely very similar.  Fine marking this as a duplicate of #3892 and I'll see if I can pick this up.  Thanks for the pointer at #5305.  Very helpful.
