### ISSUE TITLE
API concurrency limiting

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#5421]
## operator configuration

```
concourse web \
  ...
  --concurrent-request-limit ListAllJobs=5 \
  --concurrent-request-limit ListAllPipelines=10
```

* values are `<api action>=<non-negative integer>`.
* what happens if the flag doesn't parse? barf with an error
* what happens if they specify a non-existent/illogical endpoint?
    * the only supported endpoint, for now, should be `ListAllJobs` - so we can avoid any footguns
* does setting a value of zero effectively disable the endpoint? should this replace the `--disable-list-all-jobs` implementation?

## API behaviour
* error log when the limit is hit
* give a `429 Too Many Requests` when the limit is hit. We may add a `Retry-After` in a later change.
* let's make sure that, for scoped handlers (like those returned by the `pipelineserver.ScopedHandlerFactory`) the concurrency-limiting logic takes place before any DB conns get opened.
* please ensure this is zero-cost -- any endpoints that do not have a concurrency limit in place should not get slower because of this change.
* Implementation reference: https://pauladamsmith.com/blog/2016/04/max-clients-go-net-http.html

* web UI should handle it gracefully - what this means is TBD, but let's track the work in #2935.

**Comment by cirocosta** [comment]
Might be worth considering timeout'in those endpoints too to avoid scenarios like https://en.wikipedia.org/wiki/Slowloris_(computer_security)
