### ISSUE TITLE
Reflect Favorite Pipeline State between the Sidebar, Dashboard, Pipeline Views

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5438]
> As a user, I want the state of pipeline favorites to be consistently up to date in the sidebar, the dashboard, and the pipeline view.

### Summary

When a user selects a pipeline to add it as a 'favorite', its state should be updated everywhere that pipeline can be seen: in the sidebar, on the dashboard, and in the Pipeline view. 

For this iteration, we're excluding the HD view.

See issue #5441 to find more information on expected behavior.

### Acceptance Criteria

- [ ] When a user selects or deselects a favorite pipeline in the sidebar, that state is written to local storage and updated in the dashboard view and pipeline view immediately
- [ ] When a user selects or deselects a favorite pipeline in the dashboard view, that state is written to local storage and updated in the sidebar and pipeline view immediately
- [ ] When a user selects or deselects a favorite pipeline in the pipeline view, that state is written to local storage and updated in the sidebar view immediately, and in the dashboard view the next time it loads

**Comment by scottietremendous** [comment]
Add as acceptance criteria to local storage issue

**Comment by scottietremendous** [comment]
Added as a requirement for #5441 instead of a standalone issue.
