### ISSUE TITLE
Docs site example is broken 

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#5444]
![Screen Shot 2020-04-15 at 10 11 13 AM](https://user-images.githubusercontent.com/1062564/79354044-7d2cbc00-7f01-11ea-81ea-23b1a88128b1.png)

Ref - https://concourse-ci.org/pipeline-vars-example.html

**Comment by pivotal-jamie-klassen** [comment]
fixed in concourse/docs#306, deploying now https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/publish-docs/builds/5.

**Comment by pivotal-jamie-klassen** [comment]
fixed!
<img width="777" alt="Screen Shot 2020-04-15 at 11 25 43 AM" src="https://user-images.githubusercontent.com/22056320/79355603-e1ed1400-7f0b-11ea-8ff1-a330f8c19271.png">
