### ISSUE TITLE
Builds can be stuck in max in flight with a mix of rerun and regular builds

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5452]
## Summary

Seems like the fix with #5331 missed a part where the builds that are fetching during the next pending build for max in flight query 

https://github.com/concourse/concourse/blob/fab3de1722a2ce998d3710bd066453594f24ec57/atc/db/job.go#L937-L948

should also be ordered in the same way that grabbing the next pending builds are ordered.

https://github.com/concourse/concourse/blob/fab3de1722a2ce998d3710bd066453594f24ec57/atc/db/job.go#L625-L632

## Steps to reproduce

Have two builds, one rerun build and one regular build, where the rerun build is created before the regular build. They will both be stuck with max in flight reached.

## Expected results

Max in flight should not be reached.

**Comment by pivotal-jwinters** [comment]
@clarafu can we try taking the max-in-flight logic out of the scheduler/build starter? If we had a max-in-flight "pre-step" at the beginning of each build plan, we wouldn't have to distinguish between reruns and normal builds.

**Comment by clarafu** [comment]
@pivotal-jwinters Are you suggesting to put the max-in-flight logic at when we start builds (pre start maybe?) rather than in the scheduler when we decide whether or not we can schedule this build?

**Comment by pivotal-jwinters** [comment]
@clarafu yeah! 

I don't want to derail the fix for this issue if it's small though.

**Comment by clarafu** [comment]
@pivotal-jwinters Hmm I think that would mean that we would be setting inputs for builds that actually would not be able to be started, which could cause builds to have old inputs if they are stuck in max in flight for a long time.

**Comment by pivotal-jwinters** [comment]
> Hmm I think that would mean that we would be setting inputs for builds that actually would not be able to be started

Why wouldn't they be able to be started?

> which could cause builds to have old inputs if they are stuck in max in flight for a long time.

I'm of the opinion that this is fine. I never really bought into the idea that a pending build should always get the latest inputs. I think it's fine that concourse create a build with whatever inputs it has at the time, because there will always be another build created later.

**Comment by clarafu** [comment]
@pivotal-jwinters It wouldn't be started because it is stuck on max-in-flight right? I think we wouldn't want to create a build every time we have a set of inputs because that could cause a growing number of builds if you have a job that is stuck on max in flight. That was the main reason why we didn't want to get rid of pending builds yet, so that we can overwrite the inputs on a pending build when we get a new set of inputs.

**Comment by pivotal-jwinters** [comment]
Oh I thought you meant "never be able to be started" lol.

> that could cause a growing number of builds if you have a job that is stuck on max in flight

ugh, maybe, it kinda sucks to optimize for an edge case though.

Even if we don't want all these builds to run, I still think creating them makes a lot of sense. That way the input set still exists, and can be re-triggered later if needed. Maybe the max-in-flight step can know about all the builds that are in-flight, and skip itself (marking the build skipped) if there's a newer build. Is that weird?

**Comment by gowrisankar22** [comment]
Same issue with us as well with 6.0
https://github.com/concourse/concourse/issues/5360#issuecomment-615239361

**Comment by clarafu** [comment]
Hmm that's true but I would be worried about weighing that against a lot of more time spent running builds that the user doesn't really need or care about? 🤔Or if there is the skipped build, it might clutter the build page with a lot of skipped builds that the user will probably almost never need to go to. If the purpose of the skipped build is to have the user be able to rerun a specific set of inputs, that might also be hard because they would almost need to click on each skipped build in order to see the inputs.

I think overall I don't really see a strong case for changing the current behaviour of pending builds in the perspective of a user? That could just be my opinion though but I think I liked the idea of having the set of inputs that would be used for the next build be relayed to the user from a main build page and them being able to adjust the input versions from that screen in order to run a build with older inputs. I remember us creating an issue for that too but I don't remember where it is hahah

**Comment by pivotal-jwinters** [comment]
I don't imagine there would be that many skipped builds. It only serves to guard against the rare case where max-in-flight causes a huge delay in executing builds. 

Overall I don't really care about that specific implementation, however I do care about separating the build starter out of the scheduler. I added #5452 so we don't overload this one, but basically the work proposed in that issue isn't really possible if the build starter is responsible for max-in-flight as well.

**Comment by Houlistonm** [comment]
@clarafu Is there a way to recover from this condition?
We have at least one concourse installation that is stuck.
