### ISSUE TITLE
accessing output jar file

### ISSUE THREAD

**Issue by hsine55** [concourse/concourse#546]
Hi,
I'm configuring a simple concourse pipeline to build a spring-boot app with maven and then deploy it to pivotal cloudfoundry. The problem is, that when deploying to CF I am unable to access the jar builded during the execution of maven package. Here is the pipeline and tasks files.
Pipeline:
**jobs:

name: package-deploy serial: true plan:
get: source-code trigger: true
task: package privileged: true file: source-code/ci/tasks/package.yml
put: resource-deploy-web-app params: manifest: source-code/manifest.yml path: project-package ---- resources:
name: source-code
type: git
source:
uri: MY_GIT_RESOURCE
branch: master

name: resource-deploy-web-app
type: cf
source:
api: https://api.run.pivotal.io
username: MY_USER_NAME
password: MY_PASS
organization: MY_ORG
space: MY_SPACE
skip_cert_check: true**

and the task yaml file:
**platform: linux

image_resource:
type: docker-image
source:
repository: nitram509/debian-openjdk8-maven-cmake-gcc
tag: latest

inputs:

name: source-code
outputs:

name: project-package
run:
path: mvn
args: ["-f", "source-code/pom.xml", "-DskipTests=true","-DoutputDirectory=project-package","package"]**

Here is the error message that pops when trying to PUT the jar file to the CF resource :
"error invalid path: found 0 files instead of 1 at path: /tmp/build/put/project-package/

I think there is some configuration that need to be done to be able to access the output of the package task during the PUT step but I couldn't find my way around it. 
Thank you.

**Comment by jchesterpivotal** [comment]
I've seen this issue before. The problem is that each step in your plan is in a different container.

The task which builds the code is in a different container from the `put` operation which would run `cf push` for you.

The way around this is to create an `output` on the build task. `cp` your build artifacts into that directory. Then, in the `put`, declare that as an input and give the name as the path for `cf push` to look at.

I would put an example here, unfortunately I am unable to access it as it's a private repo.

**Comment by hsine55** [comment]
Hi @jchesterpivotal , thank you for you answer. I have actually done except the cp part. I thought that I configured Maven so it puts directly the artifacts in the output folder but I was wrong. So it was mainly a bad maven configuration on my side. I will close this issue but before that I would like to ask, do you have an idea if I can use the output of a task in say Job1 as an input for a task in job2. Or do I have to publish the artifacts to git for example and then use the git repo as resource in job2 ?

**Comment by jchesterpivotal** [comment]
No, you can't define an output on one job that becomes an input on another, unless you use a resource. Only within a single job.

Resources represent the subject that a pipeline operates on, so they are the only way to move something from job to job.

Git is not ideal for storing binaries. I'd look at some other kind of store -- S3, OpenStack Swift, even FTP if that's your internal environment.

**Comment by hsine55** [comment]
Thank you Jacques.
