### ISSUE TITLE
atc: `--disable-list-all-jobs` alias for `--concurrent-request-limit ListAllJobs=0` in 5.5.x

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#5467]

**Comment by cirocosta** [comment]
@pivotal-jamie-klassen do you think we could drop `--disable-list-all-jobs` from 6.x given that it was a 5.x thing, and 6.x is a major bump? :thinking:

**Comment by pivotal-jamie-klassen** [comment]
Yeah I guess there is _one particular upgrade path_ I'm thinking of, but sure let's leave it off master.

**Comment by pivotal-jamie-klassen** [comment]
Honestly we could probably remove it from 5.5 as well... as long as the config exists on the BOSH release

**Comment by pivotal-jamie-klassen** [comment]
fixed in #5484
