### ISSUE TITLE
v5.8.0 - v6.0.0: No way to Log on Programtically to LDAP based Concourse Server

### ISSUE THREAD

**Issue by coofercat** [concourse/concourse#5487]
## Summary

There is no way to authenticate with Concourse in a programatic way. That is, you can't (reasonably) write a script to authenticate with Concourse, such that it might be able to write out a `.flyrc` or else make HTTP calls to the server. In our particular use-case, we want to authenticate a script so it can push in RBAC configs.

## Steps to reproduce

You'll need an LDAP connected Concourse Master. If you have other authentication methods, it helps highlight the issue somewhat, but it's not necessary.

1) In a browser head to the homepage (eg. http://localhost:8080)
2) Click 'login'

The browser now redirects to `http://localhost:8080/sky/issuer/auth`. If you have other authentication methods available these are displayed, otherwise the browser redirects to `http://localhost:8080/sky/issuer/auth/ldap?req=xvduaygd42w7zohtj25ot5q2b`

It's not reasonably possible to log in programatically here. Whilst we have, in the past, used `mechanize` to request the logon page to get the crumb before submitting a POST with the username/password, this extra step to obtain the `req=???` token makes that too complex and fragile. 

It's true that on systems with only LDAP, we could follow the redirects and obtain the token, but that relies on LDAP-only auth, so is again, rather fragile. We could also add a local user for the script to use, but then every human will need to click past the page offering local auth.

There doesn't appear to be a way to use the `/sky/issuer/auth/ldap` endpoint without previously obtaining the `req` token.

`fly login --username=myuser --password=mypass` also doesn't work with LDAP (and error is returned, see below).

## Expected results

Some way to authenticate with the server, perhaps using the old method of `GET /sky/login` followed by POST to submit secrets (perhaps using the `/sky/issuer/auth/ldap` endpoint?), or rather, some alternative method. There appears to be some support for Basic auth, so perhaps make that work here too.

## Actual results

In the browser flow, the extra steps make mechanising rather tricky and fragile.

In `fly`, logging on with `fly -t dev logon -c http://localhost:8080 --username=myuser --password=mypass' returns:

```
logging in to team 'main'

error: oauth2: cannot fetch token: 401 Unauthorized
```
(reported here: https://github.com/concourse/concourse/issues/5027 but closed due to inactivity)

## Additional context

We're looking to automated RBAC configs in Concourse, via config management. Config Management will write the RBAC config files to disk, and if they change will use `fly set-team` to insert them into Concourse.

## Triaging info

* Concourse version: 5.8.0 - 6.0.0
* Browser (if applicable): n/a
* Did this used to work? In 5.6.0 there was a method that worked.

**Comment by vito** [comment]
Thanks for the report! There's a lot of discussion in https://github.com/concourse/concourse/issues/3208 around this, and the context you've provided sounds like more evidence that we need first class support for automating team configuration. This was the same use case described in https://github.com/concourse/concourse/issues/3208#issuecomment-603395182

I would support browser-less login flows and happily merge a PR for it, but it's hard for me to prioritize fixing it ourselves; in all examples that I've seen reported it would be used as an 'escape hatch' which can easily hide opportunities for higher-impact improvements. In the long run I think it's more beneficial to look at the context (thank you for providing it!) and figure out how the underlying goal could be done with Concourse proper. It feels redundant to me to have automation around a tool which is meant for automating things.

In your case it seems like something that could be accomplished with a `set_team` step, which wouldn't take long to implement at all and would hopefully simplify your automation stack so you don't need to orchestrate `fly` in the first place.

I'm pretty sure we've never supported browser-less login flows for anything except basic auth, so I don't think this is a bug. 🤔 If it happened to work in v5.6 it must have been unintentional or at least undocumented. I'm going to close this to focus the discussion into #3208. Hope that's OK!

**Comment by coofercat** [comment]
I'll have to take your word for the `set_team` step, but yes, happy to roll this into an pre-existing issue (as that one's clearly had lots of thought already).
