### ISSUE TITLE
ship 5.5.11

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#5489]
* [x] release pipeline
    * [x] `Error: transport is closing` - could be a version problem. https://github.com/helm/helm/issues/3409 has some ideas. Maybe the tiller is crashing, potentially because it is low on resources?
* [x] shipit (to github/dockerhub/boshio)
* [x] ship chart
* [x] OSL chart/boshrelease
* [x] tanzu network chart/boshrelease

**Comment by pivotal-jamie-klassen** [comment]
@xtremerui and I noticed errors like https://ci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/k8s-smoke/builds/61.1#L5e8217a2:26, and we tracked down a segfault in the tiller. Looks like we are hitting helm/helm#7812, which was resolved by https://github.com/helm/helm/commit/dd2e5695da88625b190e6b22e9542550ab503a47 in https://github.com/helm/helm/releases/tag/v2.16.6. So we are re-triggering `unit-image` to get an update to helm, and hopefully this resolves the problem!

**Comment by pivotal-jamie-klassen** [comment]
We had a few issues with the docker-compose-based jobs yesterday where concourse was failing to start claiming that key-related flags were not being provided. This was resolved by https://github.com/concourse/ci/commit/a354fd900ff65b5255c221cf3b29c7670e2443db.

Today:
* [ ] k8s-smoke is still failing, but with a different message: `timed out waiting for the condition` https://ci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/k8s-smoke/builds/62.1#L5e87c9a7:25
* [ ] [bosh-smoke](https://ci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/bosh-smoke/builds/70.1#L5e8803e6:68) and [bosh-topgun](https://ci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/bosh-topgun/builds/80#L5e87bea8:168:172) are failing, asking us to look into the VM logs

**Comment by pivotal-jamie-klassen** [comment]
now blocked on k8s-topgun, which seems to actually _be_ broken! maybe because of something to do with GKE, it seems to be failing because our code is giving an error with an absolute path rather than a relative one.

**Comment by pivotal-jamie-klassen** [comment]
having just shipped CVE-related patches for the git and pool resources, we might as well package those into 5.5.11 as well. Unfortunately in attempting to do so, I noticed concourse/ci#307 which I will attempt to resolve before moving on.

**Comment by pivotal-jamie-klassen** [comment]
Note: I forgot to bump the `imageTag` in the `values.yaml` in the latest chart release, so we should probably re-ship that with the correction.

**Comment by pivotal-jamie-klassen** [comment]
Still to do:
* [x] enterprise docs - https://github.com/pivotal/docs-concourse-pcf/pull/47 thanks @osis
* [ ] ship to tanzu network
    * the thing I'm concerned about
* [ ] OSL request
    * looking at our norsk-config we can figure out which scan roots need to be attached. Is it worth having some kind of automated check for this? a _scan root_ consists of a type, name, and version. Can we create a simple correspondence between concourse resource versions and scan roots, maybe?

**Comment by pivotal-jamie-klassen** [comment]
apparently shipping the _enterprise_ helm chart involves making a commit on the pivotal/concourse-for-k8s repo.

**Comment by pivotal-jamie-klassen** [comment]
Today I'm dealing with some flagged dependencies.

**Comment by jamieklassen** [comment]
it's finally done!
