### ISSUE TITLE
Concourse 6.0.0, and other releases, Linux Binary is almost 10x the size of other releases.

### ISSUE THREAD

**Issue by jaredallard** [concourse/concourse#5494]
## Summary

See title.

## Additional context

Linux: https://github.com/concourse/concourse/releases/download/v6.0.0/concourse-6.0.0-linux-amd64.tgz 745MB
Darwin: https://github.com/concourse/concourse/releases/download/v6.0.0/concourse-6.0.0-darwin-amd64.tgz 98.1MB
Windows: https://github.com/concourse/concourse/releases/download/v6.0.0/concourse-6.0.0-windows-amd64.zip 95.3MB

## Triaging info

* Concourse version: 6.x.x, 5.x.x, etc
* Browser (if applicable): n/a
* Did this used to work? No.

## Open Questions

Is this intentional, if so, why are they so much larger for Linux? It looks like this releases contains docker images, containerd binaries, and etc. This shouldn't be needed?

**Comment by vito** [comment]
Same as...:

* https://github.com/concourse/concourse/issues/4586
* https://github.com/concourse/concourse/issues/4288

The Linux package is larger because it bundles all of the core resource types, which it has to do until we resolve the plan for concourse/rfcs#30

**Comment by jaredallard** [comment]
Sorry for the duplicate!
