### ISSUE TITLE
Vagrant box does not work behind a proxy

### ISSUE THREAD

**Issue by tyyko** [concourse/concourse#55]
As title, the Vagrant box is made to test it locally, but in many occasion there is a proxy in local networks.. I tried to set the proxy variables in the vagrant configuration but without success.

Also tried with a local bosh-lite deployment (behind a proxy too) but with no luck too.

In any case I get stuck when I try  `https://github.com/starkandwayne/concourse-tutorial/blob/master/01_task_hello_world/task_hello_world.yml`
with

```
 initializing with docker:///busybox
repository_fetcher: GetRepositoryData: could not fetch image busybox from registry https://index.docker.io/v1/: Get https://index.docker.io/v1/repositories/busybox/images: dial tcp: lookup index.docker.io: no such host
errored
```

**Comment by rodcloutier** [comment]
@tyyko Have you tried using the http proxy plugin? I am using it with success with our corporate proxy.
http://tmatilai.github.io/vagrant-proxyconf/

**Comment by tyyko** [comment]
Hi, thanks for the reply but this was opened almost 2 years ago. Meanwhile I don't have any proxy in between so I can't reproduce.
