### ISSUE TITLE
The linux binary for 1.5.1 appears to be broken

### ISSUE THREAD

**Issue by aquavitae** [concourse/concourse#550]
I've just downloaded the 1.5.1 linux binary, but get a segfault with no logs when running it on the server (ubuntu 14.01).  I tried downloading it on a second machine to check that the download was ok, and get matching md5sums  so it doesn't look link a network issue. When trying to run it locally (Arch linux) I get the following:

```
$ concourse web --help

panic: open /proc/self/uid_map: no such file or directory

goroutine 1 [running]:
panic(0xf4b320, 0xc820264660)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cloudfoundry-incubator/guardian/sysinfo.must(0x0, 0x7f0dcd3cffc0, 0xc820264660, 0x7f0dcd3cffc0)
        /tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/sysinfo/max_valid_uid.go:69 +0x4b
github.com/cloudfoundry-incubator/guardian/sysinfo.MustGetMaxValidUID(0x0)
        /tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/sysinfo/max_valid_uid.go:15 +0x58
github.com/cloudfoundry-incubator/guardian/guardiancmd.init.1()
        /tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/guardiancmd/command.go:214 +0x3b
github.com/cloudfoundry-incubator/guardian/guardiancmd.init()
        /tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/guardiancmd/seccomp.go:1597 +0x27e
main.init()
        /tmp/build/9674af12/gopath/src/github.com/concourse/bin/cmd/concourse/worker_unix.go:23 +0xd3
```

**Comment by vito** [comment]
That particular error is probably from either being on too old of a kernel or having user namespaces disabled.

Not sure about the segfaults. For the binaries to have been shipped they'll have made it past our integration suite. Make sure you're not e.g. running on 32-bit Linux or something?

**Comment by aquavitae** [comment]
Turned out to be something weird in installing it that broke the binary. Nothing wrong with concourse.

**Comment by Orbixx** [comment]
For anybody who stumbled across this like I did when searching about this error, if you are trying to run it on Arch it's failing because of a lack of namespace support in the default kernel. You can use AUR to compile a kernel with userns support here: https://aur.archlinux.org/packages/linux-userns/

Though you're probably better off running it on a different distro, even if just for testing.
