### ISSUE TITLE
Docker image resource fails to download on system with low MTU

### ISSUE THREAD

**Issue by manno** [concourse/concourse#551]
We're running concourse on OpenStack. Due to the virtual network switch we have an MTU of 1350 inside our worker.
While running the hello-world example from the tutorial the `docker pull` command from the docker image resource fails to download the Ubuntu image layers. After several retries all layers have been cached and the test works.

```
Pulling ubuntu@sha256:7ce82491d6e35d3aa7458a56e470a821baecee651fba76957111402591d20fc1...
sha256:7ce82491d6e35d3aa7458a56e470a821baecee651fba76957111402591d20fc1: Pulling from library/ubuntu
43db9dbdcb30: Pulling fs layer
85a9cd1fcca2: Pulling fs layer
c23af8496102: Pulling fs layer
e88c36ca55d8: Pulling fs layer
e88c36ca55d8: Waiting
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/ac/ac526a356ca46f915e822e2f8051b9cf3404c756b725661c51191564ae4e6ea7/data?Expires=1469201014&Signature=hEKORWJUHTegq8diARI1Dgp6soCgJlz0dLNaTSpbovUsjsKr3JrzQFQ239Ns08WpaYUJV9hL-0q1JILqNFsXyLk8zh0TUjxxQVhYr0MV~hKj1Ito4g9OXyOLnuyNnBBrJdJbf181zQh~gu-eXBDZ7nSrTBVupJNNFH8ZIgsPYG8_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
```

Installing docker directly into the Ubuntu worker results in a working `docker pull` when triggered manually. 
Can you give any advice how to debug this further?

**Comment by vito** [comment]
Hmm. Try setting `--garden-mtu 1350` on the worker?

**Comment by manno** [comment]
Thanks. I changed the --mtu argument in `/var/vcap/data/jobs/garden/0250f0c9e994c76022d84b02eb5ceaca967a57be-3ddd7c8bcdee305fe02ec344c02b1ce834a2116d/bin/garden_ctl` from 1500 to 1350 and the `docker pull` worked.

Can I put this into the bosh deployment manifest for concourse somewhere?

**Comment by vito** [comment]
There's a property you can set:

http://bosh.io/jobs/garden?source=github.com/cloudfoundry-incubator/garden-runc-release&version=0.4.0#p=garden.network_mtu

**Comment by manno** [comment]
This works great. Thanks!

**Comment by manno** [comment]
I'm closing this and will open a new ticket for the discussion of a possible iptables rule enhancement.
