### ISSUE TITLE
Customise RBAC is not working 

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse#5514]
I have customised the RBAC  for member role globally allow only below policies.
‘’’
    ## Ref: https://concourse-ci.org/user-roles.html#configuring-rbac
    ## Example:
    ## configRBAC: |
    ##   owner:
    ##   - SetTeam
    ##   member:
    ##   - CreateBuild
    ##
    configRBAC: |
      member:
      - SaveConfig
      - CreateBuild
      - DeletePipeline
      - OrderPipelines
      - HidePipeline
      - RenamePipeline
      - CreatePipelineBuild
      - CreateArtifact
      - GetArtifact
      - HijackContainer
‘’’
But this is not applied with member rather still default memer role policy is applied .. example able to still list workers , prune etc ... 

Can you help ?? 
@evanchaoli

**Comment by evanchaoli** [comment]
Say, if you don't want member to list workers, then you need to move list worker permission to a higher role, like:

```yaml
owner:
- ListWorkers
```

Looks like you are trying to redefine a list of permissions to member, but config rbac should define delta based on default roles.

**Comment by pivotal-jamie-klassen** [comment]
It says in the docs that "if an action does not appear in the file, then the default role will be assigned to that action". If you want to restrict members from listing workers, then you need to assign the `ListWorkers` action to a more-privileged role, i.e. `member`. Does that make sense? It's not a very intuitive auth model.

**Comment by gowrisankar22** [comment]
@evanchaoli as @pivotal-jamie-klassen mentioned document is not that clear. Can you update the same?
So, from the member role whatever default policy I remove that should move to action to a more-privileged role, i.e. owner ?

**Comment by pivotal-jamie-klassen** [comment]
@gowrisankar22 I wrote those docs initially. You found them confusing; now that you know how the feature works, maybe you could propose a way to help inform others? I suggest you make a PR to https://github.com/concourse/docs. For guidance, I outlined the role hierarchy and definition of an action being _assigned_ to a role here:

https://github.com/concourse/docs/blob/b4c80b42dcac7420c7bad7ce2e741e586b0f0845/lit/docs/auth/roles.lit#L19-L27

and then described the mechanic of promoting and demoting actions here, where I give the example that you can restrict which roles are permitted to perform an action by assigning it to a more-privileged role.

https://github.com/concourse/docs/blob/b4c80b42dcac7420c7bad7ce2e741e586b0f0845/lit/docs/auth/roles.lit#L280-L319

**Comment by gowrisankar22** [comment]
@pivotal-jamie-klassen For now, we can leave as it is. If we see other users face a similar issue I will create a PR.
