### ISSUE TITLE
Support for self-signed certificates

### ISSUE THREAD

**Issue by jhiemer** [concourse/concourse#552]
Currently it is not possible to use self signed certificates for the web component (`{"error":"Get https://**.******.***:4443/api/v1/pipelines: x509: certificate signed by unknown authority","session":"86"}}`). It would be helpful to support this.

**Comment by jhiemer** [comment]
Any update regarding the implementation of this update?

**Comment by vito** [comment]
This flag should support it:

https://github.com/concourse/atc/blob/master/atccmd/command.go#L90

Also this will generally go away in upcoming releases as we no longer have the web UI calling into the API from the server-side; it'll all be client-side JS.
