### ISSUE TITLE
Tasks: Outputs: Folders not created automatically.

### ISSUE THREAD

**Issue by Grimeton** [concourse/concourse#5544]
## Summary
Tasks: Outputs: Folders not created automatically.
> A brief summary of the problem.

When using outputs in a Task, then the folders of the outputs are not created automatically. The documentation states otherwise:

https://concourse-ci.org/tasks.html#schema.task.outputs

## Steps to reproduce

- Create a pipeline with a task that is using outputs.
- Run the task with something like "ls -al"
- See the folders are not there.

> Starting from `docker-compose up`, what steps can be followed to reproduce
> the problem?
>
???

> Please use https://gist.github.com for large snippets!

## Expected results
Folder's with the name of the output are created.

## Actual results
Folder's with the name of the output are not created.

## Additional context
None

## Triaging info

* Concourse version: 6.0.0
* Browser (if applicable): Vivaldi
* Did this used to work?
According to the documentation: Yes.

**Comment by pivotal-jamie-klassen** [comment]
Unfortunately I couldn't reproduce your issue, but I think it will make a difference if you can provide two more details:
* the exact pipeline YAML that you are using, or an anonymized version of it if you have some privacy concerns
* a description of your concourse deployment configuration - bosh/k8s/docker/systemd, scale (if relevant), what flags are being provided to the web/worker processes

It also sounds like you had some confusion around the meaning of

> Starting from `docker-compose up`, what steps can be followed to reproduce the problem?

So I'll give an especially-detailed example:

1.
    ```bash
    $ docker-compose -f <(cat <<EOF
    version: '3'
    services:
      concourse-db:
        image: postgres
        environment:
          POSTGRES_DB: concourse
          POSTGRES_PASSWORD: concourse_pass
          POSTGRES_USER: concourse_user
          PGDATA: /database
      concourse:
        image: concourse/concourse:6.0.0
        command: quickstart
        privileged: true
        depends_on: [concourse-db]
        ports: ["8080:8080"]
        environment:
          CONCOURSE_POSTGRES_HOST: concourse-db
          CONCOURSE_POSTGRES_USER: concourse_user
          CONCOURSE_POSTGRES_PASSWORD: concourse_pass
          CONCOURSE_POSTGRES_DATABASE: concourse
          CONCOURSE_EXTERNAL_URL: http://localhost:8080
          CONCOURSE_ADD_LOCAL_USER: test:test
          CONCOURSE_MAIN_TEAM_LOCAL_USER: test
          CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
          CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
          CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
    EOF
    ) up -d
    ```
1. Wait for concourse to listen on port 8080
1. `fly -t dev login -c http://localhost:8080 -u test -p test`
1.
    ```bash
    $ fly -t dev set-pipeline -p pipeline -n -c <(cat <<EOF
    jobs:
    - name: task-with-output
      plan:
      - task: task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}
          outputs:
          - name: output # <--- Here's the output
          run:
            path: ls
            args: ["-al"]
    EOF
    )
    ```
1. `fly -t dev unpause-pipeline -p pipeline`
1. `fly -t dev trigger-job -w -j pipeline/task-with-output`

When I follow the above steps, I get the following output at my console:

```
started pipeline/task-with-output #1

initializing
fetching busybox@sha256:a2490cec4484ee6c1068ba3a05f89934010c85242f736280b35343483b2264b6
e2334dd9fee4 [======================================] 743.0KiB/743.0KiB
running ls -al
total 12
drwxr-xr-x    3 root     root          4096 May  5 12:03 .
drwxr-xr-x    3 root     root          4096 May  5 12:03 ..
drwxr-xr-x    2 root     root          4096 May  5 12:03 output # <--- Here's the output
succeeded
```

I did my best to infer what you meant from the details you gave, but I wasn't able to reproduce the problem as I understood it. Hopefully we can get to the bottom of this together!

**Comment by vito** [comment]
Converting this to a Discussion until we can confirm there's a bug afoot.
