### ISSUE TITLE
containerd: compare performance of containerd against guardian

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#5545]
**What problem are you facing**
We currently have no idea of the performance differences between running Concourse with `containerd` vs `guardian`. Without having solid numbers it is difficult to get users to try out  `containerd` quickly and gain feedback.

**What would make this better**
Similar to the work for Algorithm v6, we should test two deployments of Concourse, one running `guardian` and another `containerd`, and come up with a set of scenarios to test them under. We should also agree on metrics and benchmarks.

**Comment by muntac** [comment]
As demonstrated in a [post](https://www.engineerbetter.com/blog/increasing-concourse-container-limits/) by @andy-paine  it would be useful to know the upper bound for the number of containers `containerd` and `guardian` Concourse workers can handle, and sharing those numbers with users as guidelines.

**Comment by muntac** [comment]
@izabelacg posed the following questions
- Which clusters should we set up the two deployments in?
- How do we mimic the resourcing of our existing production environments? Can we use Greenpeace as it's already setup to deploy our CI environment from scratch?
- Does it make sense to make a copy of the CI database to simulate load?

**Comment by muntac** [comment]
- Are there any significant performance differences for a BOSH deployed Concourse vs. a Kubernetes deployed Concourse?
- For algorithm v6 drills where the deployment manifests stored in a specific repository?

**Comment by muntac** [comment]
On October 9th, @izabelacg and I set up drills with two environments, one running `guardian` and the other `containerd`. 

1. The deployment manifests are [here](https://github.com/concourse/drills/tree/master/deployments/containerd-drills).
2. We edited the following [script](https://github.com/concourse/drills/blob/master/longevity/lidar-test/setup) to set up one team with 30 pipelines.
3. Two dashboards were setup on datadog using the `containerd-drills` and `guardian-drills` section in this [file](https://github.com/concourse/greenpeace/blob/master/terraform/dashboard/examples/main.tf).


On October 19th, the `containerd-drills` environment started showing errored builds. The web nodes are in the `CrashLoopBackOff` state because it cannot connect to the database. Turns out the database reached its allocated limit of 64 GB.

The `guardian-drills` environment is around 58 GB at the moment, and is operating normally.

Things to try:
- Resize the PVC for the postgres node.
- Investigate why `containerd-drills` reached disk limit earlier
- Investigate why `containerd-drills` had errored builds even when disk limit was not reached

**Comment by izabelacg** [comment]
These are the steps we took to resize the PostgreSql Persistent Volume Claim, based on this [article](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/): 

1. Find out what PVC we want to update
   ```bash
   kubectl get pvc -n containerd-drills
   ```
2. Edit the field `resources.requests.storage` from the PVC claim to `128Gi` 
   ```bash
   kubectl edit pvc data-containerd-drills-postgresql-0 -o yaml -n containerd-drills
   ```
3. Confirm if the changes were applied and wait for the db pod to restart as well as the web nodes
   ```sh
   kubectl get pvc data-containerd-drills-postgresql-0 -o yaml -n containerd-drills
   kubectl get all -n containerd-drills
   ```

**Comment by muntac** [comment]
**Database Observations**
`containerd-drills` has about 3 million (2907856) builds

_Disk Limits_
`guardian-drills` - went near limit after 6 days. Slow increase since then. We're seeing connection numbers consistently top out at 50 today.
`containerd-drills` - went near limit after 4 days. On 4th day we saw spike in errored builds. Connection numbers go up and down.

TODO:
- Confirm if any additional configuration is needed to clean up database when it's near limit.
- Compare build numbers and database behaviour with Hush House.

**Comment by muntac** [comment]
**Query to see size of tables**
```
select table_name, pg_size_pretty(pg_total_relation_size(quote_ident(table_name))) from information_schema.tables where table_schema = 'public' order by pg_size_pretty desc;
```

**Query to see number of rows in tables**
```
SELECT 
  nspname AS schemaname,relname,reltuples
FROM pg_class C
LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
WHERE 
  nspname NOT IN ('pg_catalog', 'information_schema') AND
  relkind='r' 
ORDER BY reltuples DESC;
```

**Comment by muntac** [comment]
@xtremerui and I saw that pausing pipelines causes the build reaper to skip over the pipeline. As a result, builds don't get cleaned up.

We also noticed this https://github.com/concourse/concourse/issues/6090, where it suggests creating the following index to speed up deletion:
```
   CREATE INDEX successful_build_outputs_rerun_of_idx ON successful_build_outputs (rerun_of); 
```
This was added in https://github.com/concourse/concourse/pull/6125 (after v6.6.0 which we're testing with), and was introduced due to `destroy-pipeline` taking a long time, perhaps due to a potential deadlock. The index should speed up deletion.

We manually introduced this index to `containerd-drills` and `guardian-drills` hoping deletion will be faster. We have also unpaused the first 10 pipelines and paused all their jobs to enable the build reaper to clean them up.

We are considering removing the paused pipeline constraint on the build reaper. One scenario where we may want to keep this is if someone pauses a pipeline hoping that the build logs will stay around longer than the default or max settings allow.

**Comment by muntac** [comment]
Closing this. We saw similar performance for both runtimes. The setup took a while to get through, and we ran into some infrastructure challenges. As a result we didn't feel it was worth the effort to put out detailed results and graphs at this time since they wouldn't show any significant differences..
