### ISSUE TITLE
Build plan tasks using file definition of task should validate params

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [concourse/concourse#555]
If I have a build plan with a task defined by a `file: task.yml`, and in my task step in my build plan, I specify some params that _aren't_ specified in the task.yml, I should see a nice validation error.

In other words, as a task.yml author, I want better validation/control over how build plans consuming my task.yml pass in params.

> Alex Suraci: you don't need to declare them, which i want to fix
> Alex Suraci: would prefer to have a validation there, e.g. to call out that a task is consuming an undeclared param

[[link](https://concourseci.slack.com/archives/general/p1469219969001805)]

**Comment by Amit-PivotalLabs** [comment]
Has this been fixed?  Recently tried a `VAR1=val1 VAR2=val2 fly -t myci execute -c conf.yml`.  It picked up `VAR1` but not `VAR2`, only difference I could see is my `conf.yml` doesn't specify `VAR2`. If it has been fixed, great!  If not, maybe I'm doing something else wrong...

**Comment by vito** [comment]
It works in `fly execute` because `fly` only selects values from your environment that are present in the task .yml - otherwise it'd be sending along `$HOME`, `$USER`, `$SSH_AGENT_PID`, etc.

It's still not fixed in the pipeline case.

**Comment by Amit-PivotalLabs** [comment]
Makes sense, thanks.

**Comment by jmcarp** [comment]
Is the idea to throw a validation error on undeclared params in https://github.com/concourse/atc/blob/master/task.go#L116-L134? I'd be down to give that a try if it seems like the right approach.

**Comment by vito** [comment]
@jmcarp 🐢 yep

**Comment by vito** [comment]
This was addressed by https://github.com/concourse/atc/pull/297 - thanks @edtan!

**Comment by chendrix** [comment]
@vito please don't turn this into an error without a way of turning this validation off.

We have a use case for dynamically specifying ENV vars via pipeline templating.
