### ISSUE TITLE
Build failures when bosh-init-deployed workers show up with `name:` `unknown`

### ISSUE THREAD

**Issue by cunnie** [concourse/concourse#556]
When a worker VM is deployed with `bosh-init`, its worker-id is [`unknown`](https://github.com/cloudfoundry/bosh-init/commit/feae56e5fac1a7bcaea556414dcb605c135394d5). If there are several workers that are deployed with `bosh-init`, only 1 worker at any given moment is available, causing our builds to fail with the dreaded burnt-orange hue (`no workers satisfying: resource type 'time', tag 'vsphere-v5.1'`)

Worker's name is derived from `spec.id` which is `unknown` for bosh-init deployed VMs (this is the [intended behavior](https://www.pivotaltracker.com/story/show/118348587) for bosh-init).

It appears that this [commit](https://github.com/concourse/concourse/commit/d4aab6f3e53259b8529caf1b5135906fae1b0fc2) caused the change — perhaps reverting to the old behavior?

```
$ fly -t cpi workers
targeting https://bosh-cpi.ci.cf-app.com

name                                  containers  platform  tags
2a7467b0-b598-421f-b9b8-348057ab6a6f  3           linux     suse-liberty
85e36f7a-39b2-471a-8329-7aab70a7c36d  4           linux     suse-liberty
b046aebe-9adc-4265-b44e-75d321e7ebe2  48          linux     none
ec63d10d-4a21-41d3-ab59-4a216fc1bf8e  75          linux     none
f689d9e2-d7af-49c9-9fcf-dc48d8648f4c  60          linux     none
unknown                               0           linux     vcloud-v5.6
```

**Comment by vito** [comment]
Ugh.

As long as little things like this keep coming up I honestly just can't recommend anyone using `bosh-init` for anything beyond the BOSH director itself. I don't plan to fix this any time soon - it's way nicer having it be the instance ID (and was also a requested feature):

https://github.com/concourse/concourse/issues/333

I would however accept a PR for adding a job property for the worker name, and having it default to `spec.id` if it's not specified.

**Comment by ljfranklin** [comment]
@cppforlife would you be opposed to a bosh-init PR that generates an actual ID for `spec.id` seeing as how you requested #333 in the first place :)

**Comment by cppforlife** [comment]
will change bosh-init.

**Comment by vito** [comment]
cool - gonna close this issue then since there's nothing to fix on our end. thx
