### ISSUE TITLE
Terraform CI metrics

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5563]
Not sure what's involved here, either!

**Comment by YoussB** [comment]
we were able to  get both prometheus and grafana up and running, but found that we are not using grafana any more, this story needs a bit more work to get the metrics and traces to datadog, and eventually to wavefront.

**Comment by YoussB** [comment]
Metrics are being emitted to datadog via the prometheus emitter + telegraf, and the dashboards are terraformed.
