### ISSUE TITLE
Incorrect script path leads to "unexpected response code of: 404"

### ISSUE THREAD

**Issue by dsabeti** [concourse/concourse#558]
Hey there,

We saw a weird error message when we misconfigured a concourse pipeline. A task was configure like this:
```
...
- task: my-task
  file: scripts/ci/my-task/task.yml
```
But the actual path for the task was slightly different -- let's say `scripts/ci/my-other-task/task.yml`.

The error that concourse gives is `unexpected response code of: 404`. It took us a pretty long time to figure out the problem with our pipeline config. It would be great to see a helpful error like "could not find task scripts/cf/my-task/task.yml".

**Comment by jfrank-pivotal** [comment]
+1 for this.  Without an error message, this is extremely difficult to debug, especially for new Concourse users.  Even to an experienced Concourse user, the first thought is likely to be that something is wrong with Garden and it's time to recreate a worker.

**Comment by mehrotra-prateek** [comment]
+1 a useful error message of what it cannot find will help
