### ISSUE TITLE
Bootstrap initial CI teams/pipelines

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5582]
When we deploy CI for the first time, we'll need to configure the initial set of teams/pipelines.

For teams, this can come from configuration files within `concourse/ci`: for instance, `ci/teams/*.yml`. We can have a task that iterates over this list, and runs `fly set-team` for each file (and delete teams that were removed from this list? that sounds like it could be dangerous...)

For pipelines, it probably makes sense to just `fly set-pipeline` the `reconfigure.yml` ~and `reconfigure-contributor.yml`~ pipelines to CI in a script that's run locally, and the `reconfigure.yml` pipeline will use the `set_pipeline` step to set the greenpeace pipeline.

This poses the question - how do we bootstrap all of the Vault secrets that our pipelines require? That's a bit out of scope for this issue, though.

Opened #5583 for Vault secrets

**Comment by YoussB** [comment]
dup for #5582

**Comment by aoldershaw** [comment]
We ended up exporting the team config into CI (https://github.com/concourse/ci/tree/master/teams) and added a job to the reconfigure pipeline to update the teams when this config changes (https://ci.concourse-ci.org/teams/main/pipelines/reconfigure-pipelines/jobs/reconfigure-teams). We also had to add the admin credentials into vault so that `fly` could authenticate with the deployment (would be nice to have a `set_team` step)
