### ISSUE TITLE
prevent overloading the workers

### ISSUE THREAD

**Issue by cas0016** [concourse/concourse#559]
We have run into an issue where we will deploy a new pipeline and all of a sudden 15 jobs will wake up and try to run and then the server becomes overloaded, causing concourse to become unresponsive. We have also seen this happen with a lot of code check-ins happening at the same time and could also happen if someone approves a lot of pull requests etc.  Basically it looks like `serial: true` on all our jobs would do the trick, but only letting one job run at a time would be over-kill and would like to do something along the lines of: no more than x jobs running at the same time across an entire pipeline (or server), any more are waiting in a queue to execute.  Jenkins has a similar concept with customizable number of build executors and then a build queue.

**Comment by vito** [comment]
I think this would be resolved by some combination of  https://github.com/concourse/concourse/issues/675 and https://github.com/concourse/concourse/issues/676
