### ISSUE TITLE
resource_config_versions.id reaching its maximum causes checking to fail

### ISSUE THREAD

**Issue by agurney** [concourse/concourse#5667]
## Summary

In the database, `resource_config_versions` has an `id` column defined as `serial`, which means it has an effective range up to 2^31. Enough activity on this table can cause the range to be exhausted. When this happens, checks will return an internal error saying `pq: integer out of range` instead of usefully taking place. There is no in-built mechanism for recovering: some operational intervention in the database is needed.

## Steps to reproduce

This was reported in Discord for a cluster that had been up since 2018 with about 150 pipelines. The behavior could be reproduced by manually editing the `resource_config_versions_id_seq` sequence in the database to a large enough number (say, 2^31 - 5) and then doing a few checks in order to run "naturally" into the overflow.

While 2^31 is a large number of versions, this error doesn't necessarily mean that somebody actually _has_ that many past versions. Because of Postgres's behavior for sequences, the ID values will tend to have gaps when there are lots of roughly-concurrent inserts to the same table. So while this problem would be more likely on an older or busier cluster, it's not as unrealistically out of reach as the numbers first suggest.

## Expected results

"stuff continues to happen normally"

## Actual results

New resource versions are not detected.

## Additional context

Earlier this year, I had feared something bad might happen on our cluster when I noticed that our maximum id for this table was over 1.5bn. Usefully, the table is actually quite sparse - hardly any of those ids are actually being used in rows. (Running `select max(id), count(id) from resource_config_versions` will likely show a big difference.) So I was able to run some SQL to arrange for the rows to be effectively "compacted" to a small, contiguous range.

The actual command was https://gist.github.com/agurney/911ed18841809c6975b8b3ebcc4989e2, which executed during scheduled downtime (to avoid contention on this table due to user activity). This arranges for the table rows to be correctly renumbered, so long as there is enough space _above_ the prior `max(id)` value to hold them. The two-step dance for renumbering avoids any bad effects for overwriting existing rows. If there were _not_ enough space then it might be possible to do something similar with a temporary table. In our case, this ran for a couple of minutes and worked fine.

For the user who encountered the actual failure, a suggested mitigation was to truncate the entire `resource_config_versions` table. That certainly removes some of the data. Consequently, it has the user-visible effect of losing version history, requiring some amount of `fly check-resource --from` to get it back. (That may also not be sufficient in the case of something like an S3-backed semver resource, where past versions are not available at "source", but people might still want them to be present for pinning.)

Probably the easiest change to make here is for the schema to convert `serial` to `bigserial` for the id column, which moves from 4 bytes to 8. That would make the overflow harder to reach. This would also mean touching the two columns in other tables (`next_build_inputs`, `independent_build_inputs`) which refer to this one. 

## Triaging info

* Concourse version: 5.0.0+? (the table is new with the "global resources" feature)
* Browser (if applicable): N/A
* Did this used to work? This only has a chance of happening for <1 year, since the table hasn't been around for that long. As more people's installations grow in age, it might happen more often.

**Comment by agurney** [comment]
Fresh numbers from us: we have a max ID of 56188730 on this table, but only 1822031 rows actually present. This is just an indicator of how sparse the usage is.

**Comment by jclarksnps** [comment]
We did an analysis on this table also (we are the user who ran into this), the resources that made up the versions table were pretty much all of type time.

**Comment by vito** [comment]
> We did an analysis on this table also (we are the user who ran into this), the resources that made up the versions table were pretty much all of type time.

Good to know - thanks for looking into it! I should finish up https://github.com/concourse/rfcs/pull/27 so that we can replace the time resource with a time var source, which should eliminate the infinitely-growing-version-history problem which is probably a major contributor to this issue.

**Comment by xtremerui** [comment]
Some updates:

With concourse version 6.5, the reference of resource_config_versions.id in `next_build_inputs` and `independent_build_inputs` table are all gone. So the migration will just be one line of altering column.

We tried running the altering query on:

 - A DB that has 1m entries in `resource_config_versions` table, it took about 5~10sec.
 - A DB that has 0.4m entries with active concourse deployment i.e. normal work loads by 75 pipelines 45 time-resource configs and 450 resources. It took 3 sec.

It seems the query is straight forward and linear to number of entries only. By this assumption, for an edge case above that a total of 2m entries might just need at most `20 sec` to finish. I think it is acceptable to make the fix to the next minor release instead of waiting for a major. 

Knowing the query is "lightweight", we will try run the migration on concourse CI to confirm. @chenbh
