### ISSUE TITLE
add `statx` to containerd's seccomp

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5677]
## Summary

Though #5228 achieved parity with Guardian in terms of seccomp rules for unprivileged containers, it does not achieve parity with Docker. In particular, the `statx` syscall is not allowed in Guardian or our Containerd backend, while it is in Docker: https://github.com/moby/moby/blob/41ac6bef8d449b3064ad1378a28d95c79c4b9350/profiles/seccomp/default.json#L346

This causes commands like `ls -l .` to fail on certain images (e.g. `clearlinux`)

## Steps to reproduce

```sh
$ docker-compose -f docker-compose.yml -f hack/overrides/containerd.yml up -d
$ cat task.yml
platform: linux
image_resource:
  type: registry-image
  source:
    repository: clearlinux
run:
  path: sh
  args:
  - -c
  - |
    ls -l .
$ fly -t dev execute -c task.yml
initializing
running sh -exc ls -l .

+ ls -l .
ls: cannot access '.': Operation not permitted
failed
```

## Expected results

`ls -l .` doesn't fail

## Actual results

Fails with `Operation not permitted`

## Additional context

Start of relevant discord discussion: https://discordapp.com/channels/219899946617274369/413770960089382922/715154754803597378

Note that this works in docker: `docker run --rm clearlinux sh -exc ls -l .` succeeds

Recompiling containerd with `AllowSyscall("statx")` makes this succeed

## Triaging info

* Concourse version: 6.1.0

**Comment by aoldershaw** [comment]
I wonder if there are other syscalls that differ between Docker and Guardian. We should investigate this further for our Containerd backend.

**Comment by hoegaarden** [comment]
I am seeing the same issue, where a task with `debian:latest`¹ works, but not with `debian:sid`² anymore.

¹ `sha256:68f4e2259032a4e6f5035804e64438b52af8dd5889528b305b9059183ea4cd2a`
² `sha256:39087b3138dbb1d6f58a738880ac1800603b31bd7f4c829393b16b1e6910f8c6`

<details><summary>my test setup</summary>

Running a local docker-compose env:
- `concourse/concourse-docker` @ `f658ed7`
- `concourse --version`: `6.4.0`
- `gdn -v`: `51480bc73a282c02f827dde4851cc12265774272`
- `runc --version`:
  ```
  runc version 1.0.0-rc10+dev
  commit: 13431e0ecef0a5aeafd2113167853f96047543f6-dirty
  spec: 1.0.2
  ```

```yaml
---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: debian
    tag: ((tag))
outputs:
- name: test-output
caches:
- path: test-cache
run:
  path: /usr/bin/env
  args:
  - bash
  - -xc
  - ls -la
```

```console
$ fly -t local e -c t.yaml -v tag=latest
uploading concourse-docker done
executing build 19 at http://localhost:8080/builds/19
initializing
running /usr/bin/env bash -xc ls -la
+ ls -la
total 16
drwxr-xr-x 4 root root 4096 Jul 26 11:04 .
drwxr-xr-x 3 root root 4096 Jul 26 11:04 ..
drwxr-xr-x 2 root root 4096 Jul 26 11:04 test-cache
drwxr-xr-x 2 root root 4096 Jul 26 11:04 test-output
succeeded
$
```

```console
$ fly -t local e -c t.yaml -v tag=sid
uploading concourse-docker done
executing build 20 at http://localhost:8080/builds/20
initializing
running /usr/bin/env bash -xc ls -la
+ ls -la
ls: cannot access '..': Operation not permitted
ls: cannot access 'test-output': Operation not permitted
ls: cannot access '.': Operation not permitted
ls: cannot access 'test-cache': Operation not permitted
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
d????????? ? ? ? ?            ? test-cache
d????????? ? ? ? ?            ? test-output
failed
$
```
</details>

**Comment by muntac** [comment]
Checking manually against the list @aoldershaw posted here's the list of syscalls Concourse's containerd seccomp profile is missing. I'm not sure which of these are necessary.

```
				
				"adjtimex",
				"clock_adjtime",
				"clock_adjtime64",
				"clock_getres_time64",
				"clock_gettime64",
				"clock_nanosleep_time64",
				"faccessat2",
				"fanotify_mark",
				"fchdir",
				"fchmod",
				"fchmodat",
				"futex_time64",
				"io_pgetevents",
				"io_pgetevents_time64",
				"io_uring_enter",
				"io_uring_register",
				"io_uring_setup",
				"membarrier",
				"mq_timedreceive_time64",
				"mq_timedsend_time64",
				"openat2",
				"ppoll_time64",
				"preadv2",
				"pselect6_time64",
				"pwritev2",
				"recvmmsg_time64",
				"remap_file_pages",
				"rseq",
				"rt_sigtimedwait_time64",
				"sched_rr_get_interval_time64",
				"semtimedop_time64",
				"sigprocmask",
				"statx",
				"timer_gettime64",
				"timer_settime64",
				"timerfd_gettime64",
				"timerfd_settime64",
				"utimensat_time64",
```

**Comment by muntac** [comment]
Opened https://github.com/concourse/concourse/issues/6044 to address the wider compatibility question beyond `statx`.
