### ISSUE TITLE
Create Upgrade v5.5.x to v6.3.x Upgrade Documentation for Helm

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5692]
### Background

- With the release of Concourse v6.3.0, we'll want to create an upgrade guide for customers moving from v5.5.x to v6.3.x
- This will be the first time we have a formal upgrade guide between version for the helm release. You should be able to port over the [existing upgrade guide](https://docs.pivotal.io/p-concourse/v5/helm/upgrading-from-5-helm/)

### Requirements 

- [x] Port over the existing v5.5.x upgrade guide
- [x] Run through a v5.5.x to v6.3.x upgrade on Helm and edit as necessary

### Acceptance Criteria 

- [ ] New upgrade section is created

**Comment by xtremerui** [comment]
WIP work is in https://github.com/pivotal/docs-concourse-pcf/commits/v6-helm-upgrade
