### ISSUE TITLE
Create Install v6.3.0 Documentation for BOSH

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5695]
### Background

- With the release of Concourse v6.3.0, we'll want to create a new installation guide for customers

### Requirements 

- [x] Port over the existing v5.5.x [installation guide](https://docs.pivotal.io/p-concourse/v5/installation/install-concourse-bosh/)
- [x] Run through a v6.3.x upgrade on BOSH and edit as necessary

### Acceptance Criteria 

- [ ] New installation section is created

**Comment by jamieklassen** [comment]
is the user roles and permissions snippet supposed to be duplicated in each of the 'Configuring Team Authentication' sections?

**Comment by jamieklassen** [comment]
In https://docs.pivotal.io/p-concourse/v5/installation/install-concourse-bosh/#set-up-a-deployment, it says

> Configure authentication in your deployment manifest by providing `tls_cert` and `tls_key` values.

but I don't think TLS is related to authentication?

**Comment by jamieklassen** [comment]
```
Error: Release version 'backup-and-restore-sdk/1.15.0' doesn't exist
```

arises from the use of `cluster/operations/backup-atc.yml` - let's just consider this a problem with the `backup-atc.yml` ops file and fix it in the upstream `concourse-bosh-deployment` repo.

**Comment by jamieklassen** [comment]
install guides should make a reasonable attempt at deploying something enterprise-ready by default -- in particular, the deploy instruction should enable DB encryption and TLS.

**Comment by jamieklassen** [comment]
To whoever picks this up -- we branched the [`v6-bosh-install` branch](https://github.com/pivotal/docs-concourse-pcf/tree/v6-bosh-install) from the [`develop`](https://github.com/pivotal/docs-concourse-pcf/tree/develop) branch and didn't realize there were already `v6` and `v6-install-upgrade` branches. @matthewpereira I suspect you have the most context on how the `docs-concourse-pcf` repo is organized so you're probably the person to ask when merging time arrives.

**Comment by xtremerui** [comment]
@jamieklassen yesterday we had the same question and talked to @scottietremendous , `v6.3` will be the branch eventually have all the docs.

**Comment by xtremerui** [comment]
We cherry-pick the commit in `v6-bosh-install` to a branch of `v6` and force pushed `v6-bosh-install`.
