### ISSUE TITLE
cannot upgrade to 6.2.0 when previous encryption key not 16 or 32 character length  

### ISSUE THREAD

**Issue by alexdulin** [concourse/concourse#5710]
## Summary

With the change in 6.2.0 that fixed validation of environment variables it is not possible to upgrade to 6.2.0 if the encryption key was anything besides 16 or 32 characters in length. The enforcement of 16/32 characters applies to both the `--encryption-key` flag and the `--old-encryption-key` flag, making the `--old-encryption-key` invalid if not 16 or 32 characters.

This makes the upgrade to 6.2.0 impossible without data loss. The proper enforcement of environment variable values is definitely a major improvement, but there should be a way to migrate to 6.2.0 with previously invalid values. 

## Steps to reproduce

On concourse 6.2.0 with an old encryption key of 44 characters:

```shell
docker run --rm -t \
  -e CONCOURSE_OLD_ENCRYPTION_KEY="ea6313da1ab26890cb739539f1d6d31ae774a987de2c" \
  -e CONCOURSE_ENCRYPTION_KEY="cfc9eea59ad5981f6ed08a963996cb02" \
  concourse/concourse:6.2.0
``` 
results in:

```
error: invalid argument for flag `--old-encryption-key' (expected flag.Cipher): failed to construct AES cipher: crypto/aes: invalid key size 44
```

while the same for 6.1.0 does not.

## Expected results

Migrating from an invalid old (invalid) encryption key should be possible.

## Actual results

It is not possible to upgrade.

## Triaging info

* Concourse version: 6.1.0 to 6.2.0
* Did this used to work? It did, but should not have. There needs to be an upgrade path though unless data loss is expected.

**Comment by vito** [comment]
You might want to check that your database is *actually* encrypted. We ran into this with our own environment and found that the encryption keys were actually being completely ignored due to the validation errors. If that is the case you can probably just omit the old encryption key as it was never used.

**Comment by alexdulin** [comment]
Thanks @vito, you are correct that it was not encrypted to begin with. Removing the `--encryption-key` flags entirely made the upgrade work fine. However, passing a valid 32 character encryption key causes it to fail with:

```
error: failed to migrate database: 1 error occurred
``` 

Is there a way to get concourse to encrypt a currently un-encrypted database?

I wonder if this is something worth noting in the changelog for 6.2.0 or in an upgrade guide of some sort. Seeing as you ran into the same problem, I bet its likely others will as well.

**Comment by vito** [comment]
Hm, the only error we hit was from the flag being invalid, which is what the release notes mention already. We didn't run into any migration errors. Is there any more information in the logs?

**Comment by alexdulin** [comment]
Setting `--old-encryption-key` to an empty string and a new encryption key seems to have worked. The data appears to be encrypted now.

Thanks for the help @vito
