### ISSUE TITLE
fly login does not allow enough characters to paste in bearer token

### ISSUE THREAD

**Issue by ryanmattcollins** [concourse/concourse#5717]
## Summary

When doing a `fly login` while unable to use the `login_port` feature (i.e., while ssh'd into another machine), the other option is to paste the token in by using the "Copy to Clipboard" button in the login prompt. However, when you try to copy and paste the token, the token gets trimmed due to a character limit. (You can't even hit "Enter").

## Steps to reproduce

1. `fly -t <some-concourse> login`
1. Navigate to the login url provided, but change the port number in the url so it doesn't log you in automatically
1. Press the "Copy to Clipboard" button in your browser
1. Attempt to paste the bearer token into the awaiting `fly-cli` prompt
1. Attempt to hit enter

## Expected results

I get logged in.

## Actual results

I cannot hit enter and the bearer token is trimmed

## Triaging info

* Concourse version: _6.2.0_
* Browser (if applicable): _Chrome (but should be irrelevant because the clipboard actually still has the whole token)_
* Did this used to work? _I assume so :|_

**Comment by bmhkb4** [comment]
Also broke in 6.1

**Comment by bmhkb4** [comment]
workaround is manually add the token to <home>/.flyrc

**Comment by vito** [comment]
What platform/OS is this on? I'm not seeing a limit on allowed characters:

![image](https://user-images.githubusercontent.com/1880/83947663-6fe7cb80-a7e6-11ea-9c6c-20bc8df5de78.png)

**Comment by bmhkb4** [comment]
The token is like 10x longer than that.  I'm on centos linux.  I copy paste it to notepad and you can see it is missing like maybe 10% of the token

**Comment by jamieklassen** [comment]
I think I remember something like this happening on macos too and it was a terminal setting... Like a buffer size on stdin? Can you paste that much text into other terminal programs? Especially ones written in golang...

**Comment by ryanmattcollins** [comment]
@vito I'm using iTerm on macOS Catalina. The token I'm copying is ~2000 characters long, looks like it's getting capped at 1024 characters.

@jamieklassen I tried using iTerm and terminal on macOS, both had the same issue. I had trouble installing aminal, so I haven't tested it on something else yet.

Worth noting that when I just run `read` and try to paste my token, it stops it at the same 1024 character limit, so definitely seems to be the buffer limit like you mentioned. Although this isn't explicitly a concourse issue, maybe it's something that needs to change about the instructions presented for `fly login` given it seems to affect both macOS and Linux out of the box?

**Comment by jamieklassen** [comment]
@ryanmattcollins i could imagine a warning somewhere on the fly success page, or the terminal output from fly telling you to paste, or in the docs, to the effect of

> your token might get truncated if it is huge. paste at your own risk!

but maybe there's a way to do some kind of custom input buffering, like rather than relying on readline or whatever drives the terminal to do the buffering, the CLI puts the terminal into "raw" mode, writes to an in-memory buffer that it flushes once it sees a carriage return.

I learned this idea from [this insightful SO answer](https://stackoverflow.com/questions/52250059/bash-read-discards-terminal-line-input-after-4096-bytes#answer-52260142).

Does this explanation make sense? Is it easy enough to understand that you'd want to try a PR? This feels like a chunk of work and a chunk of risk, too.

**Comment by vito** [comment]
@jamieklassen We actually should be reading in raw mode already: https://github.com/vito/go-interact/blob/4f1a3a40eb4d79b8b1bca90afecaac6c0cb06925/interact/interaction.go#L62-L76

...But in local testing this doesn't seem to help. 🤔

**Comment by vito** [comment]
Ah - this const looks fairly sinister: https://github.com/golang/crypto/blob/70a84ac30bf957c7df57edd1935d2081871515e1/ssh/terminal/terminal.go#L326

```go
const maxLineLength = 4096
```

**Comment by jamieklassen** [comment]
I found the place where we talked about this before -- and @cirocosta found a similarly sinister constant: https://github.com/concourse/concourse/issues/4339#issuecomment-527161365

**Comment by vito** [comment]
@jamieklassen Nice snag. This might be hard to fix on Darwin, especially if it's already hitting that lower limit *with* the raw terminal mode.

I think what's happening is that all of this input arrives at once via the user pasting, and the CLI can't even process the input before it hits that buffer and gets trimmed.

This [SO comment](https://superuser.com/questions/219225/command-limits-when-pasting-into-tcsh-mac-os-x/219304#comment352300_219304) points out that some terminal applications actually have functionality to "paste slowly" - I remember playing with that in iTerm and being amused that it even existed. This must be why.

**Comment by vito** [comment]
Maybe we could switch to a flow that opens `$EDITOR` when the user presses <kbd>Enter</kbd>, the user pastes the token into the file, and then we read it back from the file?

**Comment by bmhkb4** [comment]
What changed, originally? Longer token size?

**Comment by vito** [comment]
@bmhkb4 Yeah - now that we just use the tokens issued directly by Dex, they can be much larger. For example, if you log in with GitHub the token will contain a list of all of your teams (x2 - one for team name, one for team slug) and organizations. This data is used by the API endpoints to check against the requested team's configured list of authorized users/teams/orgs/etc.

Previously this limit could only be hit if you were a member of many Concourse teams, since team names were encoded in the token, which is probably less common.

**Comment by jamieklassen** [comment]
I definitely assumed that our big token problems would be reduced when we stopped minting them. Ironically the upstream tokens are often even bigger...

**Comment by vito** [comment]
Re: my previous suggestion, opening `$EDITOR` is probably can of worms - there's no Windows equivalent, and sometimes the command isn't configured correctly with `--wait`. 😕 

Maybe we could fall back on something like this?:

```go
Please write the token to the following file:

    /tmp/blahblahblah

After saving, run:

    fly login -c <url> --token /tmp/blahblahblah
```

**Comment by aoldershaw** [comment]
@vito what if the "Copy to Clipboard" button in the UI broke the token up into multiple lines, and `fly` stitched it back together by removing all `\n`? We'd lose the benefit of the copied token being a valid JWT, though - not sure where else you'd be using the copied token directly

**Comment by vito** [comment]
@aoldershaw I think that would fix the `maxLineLength ` const issue, but I don't think it would fix the OS X case - my understanding is the data gets truncated before `fly` would even have an opportunity to read it, linebreaks or no.

**Comment by aoldershaw** [comment]
Ah you're right - I misunderstood the issue on OS X. One option would be to allow reading from stdin. That means users would need to call `fly login` twice though - once to do the login and give you access to the "Copy to Clipboard" button, and the other to read from stdin:

```
$ fly login
logging in to team 'main'

navigate to the following URL in your browser:

  https://domain.com/login?fly_port=51543
^C
$ pbpaste | fly login
```

**Comment by vito** [comment]
@aoldershaw I was tempted to use something like [`github.com/atotto/clipboard`](https://github.com/atotto/clipboard) to have `fly` grab the token off your clipboard, but then I realized if we're able to directly access the token on your clipboard from `fly` (or `pbpaste`) you probably wouldn't be in this situation in the first place.

This tends to happen when you're using `fly` remotely, i.e. over SSH - so it'd be a different machine without access to your clipboard. So whatever approach we take probably has to work in that context.

This issue is so annoying haha.

**Comment by aoldershaw** [comment]
Oh right, damn. Though, worth noting I am able to paste my full token into iTerm directly (not into `fly login`), so I could do something like:

```bash
$ cat <<TOKEN | fly login
bearer .................
TOKEN
```

which would be portable to SSH sessions. I still don't really get what this 1024 byte limit is on OS X tbh

**Comment by aoldershaw** [comment]
Interestingly enough, if I run:

```bash
$ stty -icanon
$ fly login
...
$ stty sane # to reset
```

I'm able to paste long tokens (at least 5000 characters) into `fly login`

**Comment by aoldershaw** [comment]
With the following diff to `go-interact` (though, more accurately `golang.org/x/crypto/ssh/terminal`):

```diff
diff --git a/interact/terminal/terminal.go b/interact/terminal/terminal.go
index c41223d..9b0b754 100644
--- a/interact/terminal/terminal.go
+++ b/interact/terminal/terminal.go
@@ -306,8 +306,6 @@ func (t *Terminal) clearLineToRight() {
        t.queue(op)
 }

-const maxLineLength = 4096
-
 func (t *Terminal) setLine(newLine []rune, newPos int) {
        if t.echo {
                t.moveCursorToPos(0)
@@ -561,9 +559,6 @@ func (t *Terminal) handleKey(key rune) (line string, ok bool) {
                if !isPrintable(key) {
                        return
                }
-               if len(t.line) == maxLineLength {
-                       return
-               }
                t.addKeyToLine(key)
        }
        return
```

and the following diff to `fly`:

```diff
diff --git a/fly/commands/login.go b/fly/commands/login.go
index 748969193..a03d7b6c8 100644
--- a/fly/commands/login.go
+++ b/fly/commands/login.go
@@ -213,10 +213,6 @@ func (command *LoginCommand) authCodeGrant(targetUrl string, browserOnly bool) (
 	openURL = fmt.Sprintf("%s/login?fly_port=%s", targetUrl, port)
 
 	fmt.Printf("  %s\n", openURL)
-	if !browserOnly {
-		fmt.Println("")
-		fmt.Printf("or enter token manually: ")
-	}
 
 	if command.OpenBrowser {
 		// try to open the browser window, but don't get all hung up if it
@@ -287,21 +283,23 @@ type tcpKeepAliveListener struct {
 }
 
 func waitForTokenInput(tokenChannel chan string, errorChannel chan error) {
+	fmt.Println("")
 	for {
-		var tokenType string
-		var tokenValue string
-		count, err := fmt.Scanf("%s %s", &tokenType, &tokenValue)
+		var token string
+		err := interact.NewInteraction("or enter token manually").
+			Resolve(interact.Required(&token))
 		if err != nil {
-			if count != 2 {
-				fmt.Println("token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'")
-				continue
-			}
-
 			errorChannel <- err
 			return
 		}
 
-		tokenChannel <- tokenType + " " + tokenValue
+		parts := strings.Split(token, " ")
+		if len(parts) != 2 {
+			fmt.Println("token must be of the format 'TYPE VALUE', e.g. 'Bearer ...'")
+			continue
+		}
+
+		tokenChannel <- token
 		break
 	}
 }
@@ -409,11 +407,6 @@ func (command *LoginCommand) legacyAuth(target rc.Target, browserOnly bool) (str
 		fmt.Println("")
 		fmt.Printf("    %s", theURL)
 
-		if !browserOnly {
-			fmt.Println("")
-			fmt.Printf("or enter token manually: ")
-		}
-
 		if command.OpenBrowser {
 			// try to open the browser window, but don't get all hung up if it
 			// fails, since we already printed about it.
```

This issue appears to be fixed

**Comment by aoldershaw** [comment]
Alternatively, we could just replace `fmt.Scanf(...)` with `bufio.Reader.ReadString('\n')`, which also seems to fix the issue. However, the user can't e.g. backspace, which is probably fine if they're just pasting, anyway.

**Comment by Nerigal** [comment]
This problem is not solved, at least on Windows 10, the fly.exe has this exact issue on login prompt for token where its trucking like half of it
