### ISSUE TITLE
cannot login at the command line when using ldap

### ISSUE THREAD

**Issue by speculatrix** [concourse/concourse#5726]
## Summary

fly -t aa login doesn't work if you are using ldap authentication

## Context

we had to leave a local login set up in order for automated scripts to work

here's a bit of systemd file:
  EnvironmentFile=/var/concourse/concourse_web.env
  ExecStart=/usr/local/sbin/concourse web

here's a bit of /var/concourse/concourse_web.env
  CONCOURSE_ADD_LOCAL_USER=admin:secret
  CONCOURSE_MAIN_TEAM_LOCAL_USER=admin

  CONCOURSE_LDAP_HOST=ldap.example.com

...

**Comment by jamieklassen** [comment]
Please correct me if I'm misinterpreting, but it seems like you're saying "why doesn't browserless LDAP login 'just work'". If so, I regret to inform there's a bigger story.

the big (huge) discussion about logging in without a browser is #3208. I suspect that discussing your use-case (what are these 'automated scripts' doing? could Concourse itself, as an automation engine, be doing this stuff for you?) in more detail on that issue would be the most valuable contribution to the community.

FWIW browserless login for LDAP specifically has come up several times: #3096, #5027, #5487.

**Comment by speculatrix** [comment]
there are a number of use cases for command line login I am surprised you can't imagine them

* web interface
we have a simple web overview which lists important statistics for our developers which the concourre web doesn't give you - build slave count, container count, that, recent job history

* monitoring
I have a zabbix plugin which tells me about the workers, how many workers, how many containers etc etc, and alerts me if things go bad.

* automated pipeline deployment
using repository tags in AWS to mark the type of pipelines, we scan all repos and generated pipelines automatically


all these tools use a low privilege hashicorp access token to get the username and password in order to talk to concourse. unfortunately that means using the static username/password in vault rather than being able to rotate the password in ldap and put that programmatically into vault.

**Comment by speculatrix** [comment]
I've copied my comment to https://github.com/concourse/concourse/issues/3208

**Comment by roDew** [comment]
Hi, I saw that the PR related with this topic was already merged but I don't see clearly how the concourse configuration should be done to set this Password Connector to my ldap. Has anybody tried it? Thank you in advance :)

**Comment by speculatrix** [comment]
the #3208 thread refers to a pull request here: https://github.com/dexidp/dex/pull/1621

here's what I have in my concourse_web.env file
```
CONCOURSE_LDAP_DISPLAY_NAME='LDAP Server'
CONCOURSE_LDAP_HOST=ldap.example.com
CONCOURSE_LDAP_BIND_DN='cn=ldapadm,dc=aws,dc=example,dc=com'
CONCOURSE_LDAP_BIND_PW='mypasswordhere'
CONCOURSE_LDAP_USER_SEARCH_BASE_DN='ou=People,dc=aws,dc=example,dc=com'
CONCOURSE_LDAP_USER_SEARCH_USERNAME=uid
CONCOURSE_LDAP_USER_SEARCH_ID_ATTR=uid
CONCOURSE_LDAP_USER_SEARCH_NAME_ATTR=cn
CONCOURSE_LDAP_USER_SEARCH_EMAIL_ATTR=cn

CONCOURSE_LDAP_GROUP_SEARCH_BASE_DN='ou=Group,dc=aws,dc=example,dc=com'
CONCOURSE_LDAP_GROUP_SEARCH_USER_ATTR=uid
CONCOURSE_LDAP_GROUP_SEARCH_GROUP_ATTR=memberUid
CONCOURSE_LDAP_GROUP_SEARCH_NAME_ATTR=cn

CONCOURSE_LDAP_MAIN_TEAM_LDAP_GROUP=users
```

this works with the web interface. we're using concourse 6.1.0 which came after that merge, but it still doesn't work with ldap logins at the command line :-(

**Comment by roDew** [comment]
Oh ok... Thank you very much, as I saw this and other threads closed referring to the same issue, I thought that I was missing how to make it work with the command line :( 
I've tried to write in #3208 but it seems it's restricted to collaborators so I could not ask. I will open an issue referring to these 2 threads again :)

**Comment by speculatrix** [comment]
please post a link to the issue here so i can follow that one too

we're likely to be abandoning Concourse at some point because too many quirks, too many gaps in the documentation particularly when it comes to troubleshooting.. likely to switch to gitlab+runners.

**Comment by roDew** [comment]
Sure, I opened this one: #6050
