### ISSUE TITLE
Concourse Web UI login fails if password contain a $ character

### ISSUE THREAD

**Issue by sureshbonda** [concourse/concourse#573]
Hi,
I tried launching concourse using the docker-compose.yml at https://concourse.ci/docker-repository.html
I changed the password to C0ncour$e in the yml.  fly command works, but the login on the Web UI failed.  Finally I found that $ is the culprit and it worked after I changed the $ back to s.

May be we need to check on which special characters create problem and either add in the documentation or handle special characters.

Thank You,
Suresh

**Comment by vito** [comment]
Maybe Docker interpreted the `$e` as an env var interpolation? I don't see a reason this wouldn't work otherwise.

**Comment by topherbullock** [comment]
This issue is stale, and it doesn't look like a clear reproduction was provided, so I'm going to close it off.
Please re-open with more details if this is still a problem.
