### ISSUE TITLE
Current releasing steps:

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5751]
1. Once all the commits are into master for your release, create your release branch on the `concourse/concourse` github repo with the following format `release/M.m.x` (M being the major version and m being the minor version)
1. Create the release branch on the `concourse/concourse-bosh-release` repository. Make any missing changes to the spec of `web` or `worker` depending on if the release contains any changes that adds or modifies any flags.
    - Any changes you make on the branch will not get automatically merged back to master so try to make the changes on master and then create the branch from there.
    - We should really have something that will merge the branch back to master. (like we do for the `concourse/concourse` branches)
1. Create the release branch on `concourse/concourse-bosh-deployment` repository.
1. Create the release branch on `concourse/concourse-chart` repository. Same with the `concourse-bosh-release` repo, make any missing changes to `values.yaml` or `templates/web-deployment.yaml` for changes to flags on web or `templates/worker-deployment.yaml` for changes to flags on the worker.
    - Same with `concourse-bosh-release`, nothing will auto merge the branch back to master so make sure your changes are on both master and the release branch.
1. Go to the `https://project.concourse-ci.org/releases` page and take a look at what resource types have had new PRs merged in. If the PRs that got merged in were only small fixes, then bump a patch release of that resource type in `ci.concourse-ci.org`. If they add features then do a minor version bump. If it adds breaking changes then do a major version bump.
1. Add your release pipeline to the `reconfigure-pipeline`
1. Bump the appropriate versions for resource types. Go to the releases page `https://project.concourse-ci.org/releases` and take a look at which resource type repositories have had new commits or PRs. Take a look at what those changes entail and bump the version in their respective pipeline in `ci.concourse-ci.org`.
    - If the changes were only README or repo restructuring changes with no user impact, you don't need to bump the version
    - If the changes were small bug fixes or changes, you can do a patch version bump
    - If the changes were adding of features, you can do a minor version bump
    - If the changes involve a breaking changes, that should be a major version bump
1. Create the release notes. Inside your release branch, pull everything off of `release-notes/latest.md` and put the contents into a new release note file of `release-notes/v<M.m.p>`. Go through all the undocumented PRs in the release page for your milestone `https://project.concourse-ci.org/releases/concourse?milestone=v<M.m.p>` and make sure that everything has release notes. You can organize which PRs by clicking on the button to add whichever label best fits that PR.
    - If there is an existing release note, add a `release/documented` label
    - If there is no release note and the changes have no user impact, add a `release/no-impact` label
    - If there is no release note and the changes have user impact, document it (or delegate) and add a `release/documented` after finished.

**Comment by clarafu** [comment]
What went wrong and what can we do to avoid this in the future:

- docker image resource was broken! we shipped it and it broke all the jobs that were using a docker image resource
- deploying to k8s failures (was not able to rollback because of the bug in the concourse-charts with the old-encryption-key)
- 6.2 release notes were not merged into master
- concourse-chart did not have proper changes from 6.2 (needed to remove static worker flags)

**Comment by jamieklassen** [comment]
was it the docker-image-resource or the registry-image-resource? just because we should probably stop using the docker-image-resource in our pipelines anyway

**Comment by clarafu** [comment]
@jamieklassen It was the docker-image-resource, it was breaking because for the resource types pipelines we are pulling in the docker-image-resource as the resource type from dockerhub (thats why it started failing immediately after I shipped)

https://github.com/concourse/ci/blob/cc452fd1cc97829a8cdbdac40ebc3304e85e0f3f/pipelines/resources/template.jsonnet#L352-L355

for the `resource-image-dev-alpine` resource

https://github.com/concourse/ci/blob/cc452fd1cc97829a8cdbdac40ebc3304e85e0f3f/pipelines/resources/template.jsonnet#L182-L186

and the jobs were failing with this error https://ci.concourse-ci.org/teams/main/pipelines/git/jobs/publish-patch/builds/3. 

We should stop using it in our pipelines and we should add some sort of testing for it too. Right now our ci is the docker image test suite ahah

**Comment by jamieklassen** [comment]
while we're on the topic, concourse/docs#284 is probably worth revisiting.
