### ISSUE TITLE
Change how we do release notes

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5768]
There are a few reasons why I am incentivized to change how we do release notes.

- Our release process involves creating a separate branch for the release and that means there will be two different states of the `latest.md` and whatever release the branch is for (ex. `v6.4.0.md`) within both master and the release branch. The flow right now is that all the PRs that come in will create release notes onto `latest.md` and then once we have all the PRs merged in for the release, we will create a release branch and move all the contents of `latest.md` into a file for the release (ex. `v.6.4.0.md`). The problem comes with merging the release branch back into master, which happens automatically when we ship. When we merge back to master, any new release notes that got merged into the `latest.md` on master after the release branch was created will be removed along with all the release notes of the release. Also, if we make any changes to the release notes on the release branch after shipping, those changes will not be in the master branch.
- Having contributors need to create a separate commit with them needing to know to write in their release note in a certain style (ex. `#### <sub><sup><a name="5429" href="#5429">:link:</a></sup></sub> feature` as the header with the name being the number of the issue or PR and also specifying feature or fix) Usually release notes are not written when a PR is submitted and only when a PR is approved, which means that contributors would need to create a whole new commit for the addition of the release note that will need to wait for the PR tests to run again before it can be merged. Also the back and forth process of needing to ask a contributor to create a release note could take sometimes days before getting it through to merging.

There were a few proposed solutions to solving these problems.
- Using pull requests as the source of truth for release notes. We can use a github app that can help with this (https://github.com/apps/release-drafter). We currently use it for the `git-resource`. This would mean that we would manage our release notes purely through github and no longer have the release notes in code. We would need a job prior to `ship-it` that would create a pre-release or a draft release which you would edit in place and then shipit “promotes” it to a real release
- Move the release notes into a separate repository which only uses a `master` branch. All the release notes for each release will be edited within the `master` branch so there will be no more complexities with different branches of release notes. We would have our contributors write the release note for their PR into the PR description and when the PR is merged, automatically move the release note into the `latest.md`. 
- Have each release within the release notes be a separate folder rather than file (proposed in https://github.com/concourse/ci/issues/329) This will ensure that there will be no merge conflicts between branches when editing different notes within the same release. 

I personally like the idea of having pull requests be the source of truth and no longer having release notes in code. I think we can explore this idea and see if it can work with our process first?

**Comment by clarafu** [comment]
@vito and I investigated using the release-drafter (https://github.com/release-drafter/release-drafter#readme) github app to compile release notes and bump concourse versions for us using their `version-resolver` https://github.com/release-drafter/release-drafter#version-resolver. We ended up not choosing to use the app because it doesn't support releasing versions out of the regular semver ordering (ie. we release LTS releases which means we could release versions in the following order v6.4.0 -> v5.5.1 -> v6.5.0). The reason why it doesn't support it is because it grabs all the pull requests that have been merged after the **latest** release based on a timestamp. So that would mean that if we released v5.5.1 in between releasing v6.4.0 and v6.5.0, the release notes would not compile the pull requests merged between the time of v6.4.0 and v5.5.1. 

We decided to create our own tool that would help us compile release notes based on our workflow, where it would need to grab all the pull requests merged after a specific commit of the latest tag. This way it won't matter if we release LTS releases in between our regular OSS releases. The first pass at this tool can be found here https://github.com/clarafu/release-me.

Currently, the CLI grabs all the pull requests merged after commit that is referenced by the latest tag of concourse. Then it sorts the pull requests by number in ascending order and fetches the optional release note description from the pull request body. It uses the labels on the pull request to sort them into sections and uses the go templating library to construct the release note and output it to `stdout`.

The CLI depends on certain labels to exist on each pull request in order to group them into the correct sections. This means that the pull request reviewer must label the pull request before merging with the label(s) that they think best fit. Typically, you should only need to label it with one of the following labels but if the reviewer decides to attach more than one label, the CLI will group the pull request based off the labels' hierarchy. Here's an overview of the labels (and sections in the release note) that need to be considered:
  - `breaking`: this means that the pull request contains a breaking change or in other words backwards-incompatible. An example of this would be the new algorithm in v6.0.0, where it introduced a change in behaviour in how versions would be determined for the next build of a job. Normally we try our best to avoid introducing any breaking changes, but if it happens it would mean a major version bump in the concourse version.
  - `enhancement`: another word for feature, where we are introducing something new that adds on to the existing concourse functionality. An example would be a new fly command. 
  - `bug`: a pull request that fixes an existing bug within a previous released version of concourse would be labelled as bug. An example would be a pr that fixes a bug in concourse that caused the web nodes to panic.
  - `release/no-impact`: you would add a no impact label if the pull request introduces no changes to the existing concourse functionality or behaviour. For example, a README.md change or refactors that do not change any behaviour.

  In order to ensure that the proper labels are applied by the time the release note is generated, we will add a test to each pull request that will check to see if it has the appropriate labels before it can be merged. The test will make sure that the pull request has at least one of the labels mentioned above and that the pull request is documented (if it needs to be). The test that ensures that the pull request is documented will first check to see if the pull request has been labelled `release/no-impact` or `release/undocumented`. The `release/undocumented` label should be one that is attached to a pr that does have some behavioural changes to concourse but does require any docs changes. If a pull request is not labelled with either one of those labels, the test will check for if the pull request has a linked pr to the docs repo. If it does then the test will succeed. This is to ensure that before the pull request is merged, there is an existing pull request already submitted to the docs repo for this change (if needed).
**To summarize, a pull request will need to be labeled with either `breaking`, `enhancement`, `bug` or `release/no-impact` for it grouped into the corresponding section in the release note and for the test to pass in order to merge the pr. The other requirement for the test is if the pr is not labelled with either `release/no-impact` or `release/undocumented`, there needs to be a pull request opened (or merged) in the docs repo that is linked to the original pr.**
A few examples of the labels that need to be attached to a pull request is:
  - concourse/concoursePR#1: `feature`, `release/undocumented`
  - concourse/concoursePR#2: `breaking`, `feature`, linked to concourse/docsPR#2
  - concourse/concoursePR#3: `bug`, `release/undocumented`
  - concourse/concoursePR#4: `release/no-impact`
As a side note, this information should be documented somewhere easier to find (maybe concourse wiki?) in order to help reviewers properly label the pull requests. 

The responsibility of the release anchor would be to look over the draft release that will be created through the job that generates the release note and creates a draft release using the generated release note in the release pipeline. If any changes need to be made to the release note, they can directly edit the release note of the draft release, which will then be converted into a real release when the `publish` job is run. 

With this change to the release notes, this means there will no longer be huge descriptions within the release note for any big changes that it contains. Rather, we can move towards using blog posts to write lengthy descriptions for any big changes that we want to go into more detail about.

**Things to do:**
-[ ] Add a job in the release pipeline that runs the `release-me` cli to generate a release note and create a draft release using the release note. The publish a github release job will change to be converting the draft release into a real release.
-[ ] We need to update the pull request template in order to add a section `## Release Note` and give a proper description that this is where you can add more details about your change in order to be displayed within the release note. We also need to write in the pull request template that the title of the pr will be used to generate the release note, so writing a good title is very important.
-[ ] Add a `priority` label and have the CLI generator place pull requests at the top of the section if it is labelled with `priority`. If there are multiple pull requests labelled with `priority` in the section, the ordering will be determined through the pull request number. `priority` pull requests will always be placed ahead of pull requests without the `priority` label within the section.


**Possible Future Steps:**
- Have the tag that we fetch the commit from in order to grab all the pull requests merged after that commit be configurable. That way we can support releasing LTS releases, where we can pass the CLI the specific tag that we want it to grab the commit from in order to fetch all the commits merged after it. This will need to be pointed to the LTS release branch, which the CLI already currently supports configuring a specific branch for it to look for commits from.

**Comment by jamieklassen** [comment]
> The first pass at this tool can be found here https://github.com/clarafu/release-me.

https://www.youtube.com/watch?v=6J3mYaAZJ68
