### ISSUE TITLE
Cannot drag pipelines in web UI while using a team filter 

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#5781]
## Summary

Without anything on the search box I can re-order pipelines via the web UI. However, if I use a `team: <name>` search filter, then the pipelines can no longer be re-ordered. 

Tried looking through the release notes and didn't find anything regarding this, not sure if it was an intentional change or an accidental one...

## Steps to reproduce

1. Setup concourse with 2 (or more) teams and a couple of pipelines in each team
1. On the UI without any search input, try to re-order pipelines (this works)
1. Filter pipelines by a team (click search box, select `team` then a team name)
1. Try to re-order pipelines (this no longer works)

## Expected results

Should be able to re-order pipelines while using a team name filter

## Actual results

Cannot re-order pipelines while using a team name filter

## Triaging info

* Concourse version: `6.1`
* Browser (if applicable): Firefox `77.0.1` on Linux
* Did this used to work? Worked up until `6.0`

**Comment by aoldershaw** [comment]
This was an oversight introduced in #5118, which simply assumed that you won't need to reorder pipelines when you have a query active. Obviously, with a `team: ...` query, it makes perfect sense to reorder pipelines.

I addressed the finicky drag and drop code in 7baebe2bce18f626e89742dd8f353b980ac1f744, which should make it easy to fix this behaviour (once #5777 gets merged).
