### ISSUE TITLE
cannot login concurse gui with basic auth

### ISSUE THREAD

**Issue by mliu5715k** [concourse/concourse#579]
Hi, I am doing a binary install on a centos VM. I've followed the document carefully. Upon starting up the web and the worker, I can bring up the home page but when I click "login with basic auth" I get "this site can't be reach, <server> refused to connect" what's causing that? Thanks.

{code}
concourse_linux_amd64 web --basic-auth-username atc --basic-auth-password atc --session-signing-key session_signing_key --tsa-host-key host_key --tsa-authorized-keys authorized_worker_keys --external-url http://10.252.197.130 &{code}

**Comment by vito** [comment]
Should `--external-url` have `:8080` at the end? Or do you have it behind a router?

**Comment by mliu5715k** [comment]
@vito 
Yes! that's it. Thanks.

**Comment by vito** [comment]
np
