### ISSUE TITLE
Stop using docker-image-resource!

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5792]
We are deprecating the docker image resource so we should stop suggesting it in our docs and using it in our pipelines. Originally, we were still using it in our pipelines sort of as a "test" for it, but with https://github.com/concourse/concourse/issues/5784 we no longer need to. Let's remove it's usage in the resource types pipelines

https://github.com/concourse/ci/blob/16a0010d58b510e71b1c171c9b212646a734885a/pipelines/resources/template.jsonnet#L351-L356

and also in the docs (concourse/docs#284)

https://concourse-ci.org/resource-types.html#schema.resource_type.source

We can replace it with the registry-image-resource!

**Comment by vito** [comment]
Blocking this on https://github.com/concourse/registry-image-resource/pull/214 - once this is implemented we should be able to simplify the jsonnet template and switch entirely to the `registry-image` resource.

**Comment by vito** [comment]
Done! 

* https://github.com/concourse/ci/commit/df06ec513736acb8de7721366b5377fc561c861c
* https://github.com/concourse/ci/commit/cba5c714b0292f932405f7c8d6c5b13103be8523
* https://github.com/concourse/ci/commit/8824d85e1cee93e8883a3e02c29736455871a734

Tested this by shipping a new minor release of the `mock` resource.
