### ISSUE TITLE
Worker randomly forgets about resources

### ISSUE THREAD

**Issue by Nopik** [concourse/concourse#58]
I have custom resource configured (slack notification), which seems to be configured properly. It was also working fine. For past few builds, it actually stopped to work (`no workers satisfying: resource type 'slack-notify'`) without me touching anything (I'm the only one with access to that installation). I re-checked configuration and restarted beacon, no success.

Interestlingly, it sometimes work half-way: 'put' works fine (and slack message is sent), but 'get' which automatically follows that says:

```
no workers satisfying: resource type 'slack-notify'

available workers: 
  - platform 'linux'
```
![image](https://cloud.githubusercontent.com/assets/554841/8130896/bb991974-1116-11e5-837d-828e38eb7196.png)

**Comment by Nopik** [comment]
It turns out that I had 4 beacons running, due to this bug: https://www.pivotaltracker.com/n/projects/1059262/stories/96902056

**Comment by drnic** [comment]
@Nopik is your `slack-notify` resource finished? Can we try it out?

**Comment by Nopik** [comment]
I'm using it all the time and it works for me. Certainly some additions can be made (e.g. support for attachments or reading message from file), but for simple pass/fail notifications it does the job.

**Comment by drnic** [comment]
@Nopik is the plugin open source; or would you be interested in making it? URL? thanks

**Comment by drnic** [comment]
Sorry, should have looked in your org first - https://github.com/Nopik/slack-notification-resource
