### ISSUE TITLE
no workers

### ISSUE THREAD

**Issue by mliu5715k** [concourse/concourse#580]
Hi there again,  I am running binary install on centos vm, followed the documentation. I am now able to login the gui and submit the "hello world" pipeline. but when I manually invoked the job. I get a `no worker` error.
when I started the worker:
`sudo concourse_linux_amd64 worker --work-dir /opt/concourse/worker --tsa-host 127.0.0.1 --tsa-public-key host_key.pub --tsa-worker-private-key worker_key`
I saw this error at the console:
```/opt/concourse/worker/1.6.0/linux/iptables/sbin/iptables: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/concourse/worker/1.6.0/linux/iptables/sbin/iptables)```

the worker process doesn't seem to be running, when check `ps -ef | grep concourse` i only see the `web`

showing what i have on the server:
`[root@test-concourse-01 atc]# ls -l /lib64/libc.so.6
lrwxrwxrwx 1 root root 12 Apr 29 18:42 /lib64/libc.so.6 -> libc-2.12.so`

`[root@test-concourse-01 atc]# uname -r
4.6.4-1.el6.elrepo.x86_64`

so apparently i need a new glibc version. (2.14) Documentation only says to get newer kernel.

**Comment by mliu5715k** [comment]
it's the glibc version, i am trying to get version 2.14.

**Comment by vito** [comment]
Closing this as it should probably be fixed as part of https://github.com/concourse/bin/pull/20 and possibly other PRs that leads to.

Thanks!
