### ISSUE TITLE
Bagageclaim cache

### ISSUE THREAD

**Issue by abbeygamesci** [concourse/concourse#581]
I have a situation where a git repository is checked out of 2GB and then 16 different configurations of this repository are build on windows workers. This causes a lot of traffic between nodes. With a single worker the repository data seems to be transferred 16 times (x2GB=a lot of data). 

Would it be possible to have concourse identify that it will send the same data 16 times and only send it once? I noticed that something like this landed in 1.5.0 for resources, would it also be possible for bagageclaim data?

**Comment by vito** [comment]
The trouble is there's risk that any one of those 16 copies gets modified and mutates shared state. If you know of any copy-on-write semantics we could add to Baggageclaim on Windows I'd love to hear about it though (or see a PR). It just falls back on naive copying on anything but Linux:

https://github.com/concourse/baggageclaim/blob/master/volume/driver/naive.go

**Comment by baszalmstra** [comment]
Ah, so the data is already not send over the network 16 times. I assumed
that was the case.

Would it otherwise be possible to mark the volume as read only? That would
save me 16 copies since I am doing out of source builds and not writing to
the source anyway.

My builds now take 20 minutes of which 11 minutes is just setting up
workers.

**Comment by baszalmstra** [comment]
I'll try ReFS (https://en.m.wikipedia.org/wiki/ReFS) to see if copying is
faster there since it should support cow.

**Comment by vito** [comment]
One thing to clarify is that since it's going from a `git` resource running on Linux to a task running on Windows, it *will* be going over the network. If however someone were to implement a `git` resource type for Windows, that network traffic, along with a lot of slowness, would go away.

**Comment by baszalmstra** [comment]
So I finally had the chance to check out ReFS and it improved build times for me with about 30%. It also reduced disk space quite significantly. All in all definitely worth switching! 

@vito How much do you recon a git resource for windows will improve the performance?

**Comment by vito** [comment]
@baszalmstra Neat! Did you write a backend or something? Is that something that can be PR'd?

A windows implementation of the Git resource would definitely speed things up, as the network overhead would go away.

**Comment by baszalmstra** [comment]
@vito No, I noticed that the native bagage claim just calls `cp` so I assumed I wouldn't have to change a thing. Probably by specifying flags or something you can optimize it further but for me this already works quite well.

I'll start looking into a windows git resource next.

**Comment by vito** [comment]
Ah, OK; I guess if ReFS just optimizes `cp` and stuff you won't need a backend.
