### ISSUE TITLE
Enforce restrictions for valid identifiers

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5810]
## Summary

This issue is for implementing concourse/rfcs#40 as described.

## Context

* RFC: concourse/rfcs#40
* Depends on: #5811

**Comment by mouellet** [comment]
@vito, with #5811 closed and merged, I could work on this if no one else is? It looks like a good next in line...

**Comment by vito** [comment]
@mouellet That would be greatly appreciated!

One thing to note before you dive in: there's a bit of a "soft dependency" on https://github.com/concourse/concourse/issues/5808 - see this comment (and my reply) for details: https://github.com/concourse/rfcs/pull/40#issuecomment-620611206

The tl;dr is that people are currently encoding information in pipeline names that would become invalid once we enforce these restrictions. Those folks *should* switch to pipeline instance vars for encoding that information, but that feature hasn't been implemented yet, so they may be left painted into a corner if we implement validation first.

We could feature-flag the validation, making it either opt-in or opt-out. It's a little silly to have optional validation, but having it opt-out could help guide new users while not blocking existing users. Once we're confident that we've eliminated the need for funny characters in names, we can remove the flag.

Alternatively, if you're interested in working on pipeline instances I'm happy to chat about that too, but it's definitely more work. 🙂

**Comment by mouellet** [comment]
@vito, I haven't gone through everything, but here's what I have in mind so far:
* In `configvalidate.Validate()`, add a `atc.ConfigWarning` of some type (i.e. _invalid_identifier_) for each invalid identifiers.
* For fly commands, make `flaghelpers.PipelineFlag.Validate()` (and `flaghelpers.TeamFlag`) return typed error for invalid identifiers.

This would make it so warnings are emitted instead of erroring (as stated in the rfc) but we can also add a feature-flag w/ checking on warning/error type.

Questions:
1. Should Group names & ResourceType names also be valid identifiers?
2. Should I validate the Step names in each `atc.StepValidator` or at the `configvalidate` level?

**Comment by vito** [comment]
@mouellet Ah, right, I forgot we're opting with warnings first. I think we can skip the feature flagging then. 👍

> 1\. Should Group names & ResourceType names also be valid identifiers?

Yeah, I think so. These are easy to rename with minimal consequense, and I don't think I've ever seen them contain special characters anyway.

> 2\. Should I validate the Step names in each `atc.StepValidator` or at the `configvalidate` level?

`StepValidator` sounds good to me. `configvalidate` actually calls out to it.

**Comment by mouellet** [comment]
> I think it would be better to perform validation for team/pipeline names server-side, and have `fly` propagate an error message to the client.

@vito, I agree but it means the API has to change to return the messages (except for `configserver.SaveConfig` that already returns it)...

Is that Ok?

btw, is the API documented somewhere?

**Comment by vito** [comment]
@mouellet Changing the API is OK - it is currently undocumented and not supported for external use, and `fly` will complain when it's out of sync so it shouldn't break in strange ways. (Admittedly, documenting the API may help contributors change it, but it can also tie our hands as people grow to rely on it.)

**Comment by mouellet** [comment]
@vito, just opened a PR but still have one question..
> * For fly commands, make `flaghelpers.PipelineFlag.Validate()` (and `flaghelpers.TeamFlag`) return typed error for invalid identifiers.
I implemented the server-side validation, but it feel weird to only have that because some `fly` commands ask for confirmation and we only get the warning after... Are you sure you don't want to have both client and server?

**Comment by vito** [comment]
@mouellet Ah, good point - I think it's fine to have client-side validation as long as there is *also* server-side - the important thing to me was that it not be client-side only. 👍
