### ISSUE TITLE
Renaming pipeline resources

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5811]
## Summary

Jobs can be renamed by configuring an [`old_name`](https://concourse-ci.org/jobs.html#schema.job.old_name) and configuring the pipeline. Afterwards, the `old_name` field can be removed.

This issue is for implementing the same functionality, but for resources. This way the data for disabled and pinned versions can be preserved through changing the resource name.

## Context

* Needed by #5810

**Comment by mouellet** [comment]
Hey @vito, this looks simple enough for a first time contributor! I'll start working on it and have a PR ready soon.

**Comment by vito** [comment]
@mouellet Awesome, thanks! Feel free to reach out for any questions.
