### ISSUE TITLE
Concourse 6.3.0 upgrade from 6.2.0 fails to download docker images from ECR

### ISSUE THREAD

**Issue by analytically** [concourse/concourse#5817]
## Summary

After upgrading to 6.3.0 from 6.2.0, I'm getting `not found: manifest unknown: Requested image not found` when running jobs that ran fine before (using custom resources and ECR).

**Comment by analytically** [comment]
Both docker-image and registry-image won't work anymore with ECR via instance roles in 6.3.0. This breaks all our Concourse pipelines.

**Comment by jamieklassen** [comment]
The issue template for bug reports has a section like

```markdown
## Steps to reproduce

<!--
All bug reports must have steps to reproduce, starting from the instructions in
CONTRIBUTING.md for running Concourse locally:

https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#running-concourse

Starting from `docker-compose up`, what steps can be followed to reproduce the
problem?

Please use https://gist.github.com for large snippets!
-->
```

Can you provide a reproducible (docker-compose.yml and pipeline config) so somebody can effectively work on this bug? If you can't, either because the issue is intermittent or because you're not allowed to share your config, then it probably makes more sense for this to be converted to a discussion so that others can collaborate, exploring the problem details until it becomes a viable work item. This triage flow has been implemented somewhat recently, detailed in this [blog post](https://blog.concourse-ci.org/nobody-wants-a-stale-bot/). Thanks!

**Comment by analytically** [comment]
Yeah sorry about the lack of detail. I just destroyed the pipeline, and recreated, and it's working again, seems like the SHA somehow gets cached or corrupted during an upgrade.

**Comment by jamieklassen** [comment]
A clue that I can contribute, just off the top of my head, is that the versions of the resource types bundled with concourse 6.3.0 are different from concourse 6.2.0.

docker-image went from 1.3.1 to 1.3.3

```bash
$ docker run --rm --entrypoint cat concourse/concourse:6.2.0 /usr/local/concourse/resource-types/docker-image/resource_metadata.json
{
  "type": "docker-image",
  "version": "1.3.1",
  "privileged": true,
  "unique_version_history": false
}
$ docker run --rm --entrypoint cat concourse/concourse:6.3.0 /usr/local/concourse/resource-types/docker-image/resource_metadata.json
{
  "type": "docker-image",
  "version": "1.3.3",
  "privileged": true,
  "unique_version_history": false
}
```

and registry-image went from 0.9.0 to 0.10.1:

```
$ docker run --rm --entrypoint cat concourse/concourse:6.2.0 /usr/local/concourse/resource-types/registry-image/resource_metadata.json
{
  "type": "registry-image",
  "version": "0.9.0",
  "privileged": false,
  "unique_version_history": false
}
$ docker run --rm --entrypoint cat concourse/concourse:6.3.0 /usr/local/concourse/resource-types/registry-image/resource_metadata.json
{
  "type": "registry-image",
  "version": "0.10.1",
  "privileged": false,
  "unique_version_history": false
}
```

EDIT: Ok, just saw you closed the issue, but maybe this knowledge will be relevant for others who get the same error on an upgrade.

**Comment by analytically** [comment]
Could it be that the SHA is stored in the Concourse DB somehow?
