### ISSUE TITLE
fetching the image did not produce a volume

### ISSUE THREAD

**Issue by acarsercan** [concourse/concourse#5818]
## Summary

Getting error
```waiting for docker to come up...

Pulling troykinsella/concourse-fly-resource@sha256:ad6e997c29fde4e50a455918cea8e46e32ba061ec5570d01ca09ab01e5f3d2e6 (attempt 3 of 3)...

Failed to pull image troykinsella/concourse-fly-resource@sha256:ad6e997c29fde4e50a455918cea8e46e32ba061ec5570d01ca09ab01e5f3d2e6.

fetching the image did not produce a volume

```

## Steps to reproduce
Trying different resource tag
example
```resource_types:
- name: fly
  source:
    repository: troykinsella/concourse-fly-resource
    tag: latest
  type: docker-image
```

## Expected results
The step to download the new image as tagged

## Actual results
Error above

## Triaging info

* Concourse version: 6.3.0
* Browser (if applicable): firefox
* Did this used to work? yes in 5.8.0

**Workaround**

Renamed the resource
example
````
- name: fly
```
```
- name: flyy
```

**Comment by analytically** [comment]
@jamieklassen same issue I was seeing with 6.3.0

**Comment by analytically** [comment]
After downgrading to 6.2.0, and destroying/creating the pipeline (exact same config) it works again.

**Comment by analytically** [comment]
Just downgrading doesn't work, something must be stuck in the DB.

**Comment by xtreme-sameer-vohra** [comment]
Hey @acarsercan 
I'll try to reproduce the issue shortly on my end.

**Comment by xtreme-sameer-vohra** [comment]
Hey @acarsercan , @analytically 
I wasn't able to reproduce the issue following these steps

1. Ran v6.3.0 of Concourse using Docker with 1 web and 1 worker
1. Set pipeline
```
resources:
- name: fly
  source:
    repository: troykinsella/concourse-fly-resource
    tag: latest
  type: docker-image

jobs:
- name: test
  plan:
  - get: fly
```
1. Ran 2 builds and they both were able to fetch the image 
<img width="958" alt="Screen Shot 2020-06-29 at 1 11 10 PM" src="https://user-images.githubusercontent.com/1062564/86040651-0a17e980-ba0a-11ea-8008-0e69c54c45b9.png">

Did I miss any steps ?

**Comment by ukconcourse** [comment]
Unfortunately my route to the problem wasn't the same and I'm not sure if its reproducible, but here it goes anyways

**Existing setup**

Concourse 5.8
Existing pipeline using the fly resource

**Upgrade to 6.3 using helm**
Fly step no longer completes errors

```
Failed to pull image troykinsella/concourse-fly-resource@sha256:ad6e997c29fde4e50a455918cea8e46e32ba061ec5570d01ca09ab01e5f3d2e6.

fetching the image did not produce a volume
```
We have only seen this with the fly resource

Unfortunately I don't a debug output, so happy for this to be closed until I can get more details

**Comment by acarsercan** [comment]
Unfortunately my route to the problem wasn't the same and I'm not sure if its reproducible, but here it goes anyways

**Existing setup**

Concourse 5.8
Existing pipeline using the fly resource

**Upgrade to 6.3 using helm**
Fly step no longer completes errors

```
Failed to pull image troykinsella/concourse-fly-resource@sha256:ad6e997c29fde4e50a455918cea8e46e32ba061ec5570d01ca09ab01e5f3d2e6.

fetching the image did not produce a volume
```
We have only seen this with the fly resource

Unfortunately I don't a debug output, so happy for this to be closed until I can get more details

**Comment by shyamz-22** [comment]
@xtreme-sameer-vohra  We are facing this issue too in 6.3.0 and multiple teams have reported this. What can we do to provide more insights on this? At the moment it is tough for us to reproduce. when it does happen can you point out where we should have a look at which logs will be helpful for you to fix this issue?
