### ISSUE TITLE
Don't always `get` after a `put` to resources that are never `get`ted.

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#582]
Talked about this on Slack some time ago, formalizing this as an issue now.

In a setup where the the end of the pipeline is a `put` to a resource (which might never be consumed back by the pipeline) there's an unnecessary additional `get` happening every time. A simple example would be a pipeline that has a task that prepares the contents of an image and then `put`s to `docker-image-resource` which pushes the image to docker hub and is never consume back by the pipeline. In such case, `pull`ing the image is a waste of resources and time.

Thx!

**Comment by joshzarrabi** [comment]
Hi, we are not going to add this.. Sorry https://stackoverflow.com/questions/38964299/why-does-concourse-get-a-resource-after-puting-it/38964300#38964300
