### ISSUE TITLE
v6.0.0 -> v6.3.0: pq: column "hijacked" does not exist

### ISSUE THREAD

**Issue by chriseaton** [concourse/concourse#5826]
## Summary
After upgrading concourse and migrating the database from v6.0.0 to v.6.3.0 my builds now fail with what looks like a missing column in the database:

![image](https://user-images.githubusercontent.com/5247568/85897664-a3978f00-b7af-11ea-8984-f0ebc7dfd0cc.png)

## Steps to reproduce
Go to an existing job and start it.

## Expected results
The job runs and completes the task.

## Actual results
The task starts but immediately fails with: `pq: column "hijacked" does not exist`

## Additional context
This job definition existed before the upgrade.

## Triaging info

* Concourse version: v6.3.0
* Database version: 1591025749
* Did this used to work? Yes

**Comment by jamieklassen** [comment]
The issue template for bug reports has a section like

```markdown
## Steps to reproduce

<!--
All bug reports must have steps to reproduce, starting from the instructions in
CONTRIBUTING.md for running Concourse locally:

https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#running-concourse

Starting from `docker-compose up`, what steps can be followed to reproduce the
problem?

Please use https://gist.github.com for large snippets!
-->
```

Can you provide a reproducible (docker-compose.yml and pipeline config) so somebody can effectively work on this bug? If you can't, either because the issue is intermittent or because you're not allowed to share your config, then it probably makes more sense for this to be converted to a discussion so that others can collaborate, exploring the problem details until it becomes a viable work item. This triage flow has been implemented somewhat recently, detailed in this [blog post](https://blog.concourse-ci.org/nobody-wants-a-stale-bot/). Thanks!

**Comment by chriseaton** [comment]
Sorry - you're right, not a bug.

Looks like our concourse instance was hanging on to an old worker registration in the `public.workers` table and it was causing a bunch of headache. Once I removed that record everything went smoothly.

**Comment by lrstanley** [comment]
This is the first time we're seeing a similar error today, after having v6.3.0 run fine for a few weeks (we completely recreate workers from scratch after every upgrade).

The error:

```
pq: column "hijacked" does not exist
```

It resolved itself for the user a few minutes after, so not sure if it's a one-time error or an intermittent error.

Also worth noting, we do not have any stale workers or workers in the workers list (`fly workers` or db) that shouldn't be there.

v6.1.0 seems to have changed the way hijacking works (and [dropped a column named "hijacked" for containers](https://github.com/concourse/concourse/blob/e2b44a07bde9ce20a80152b727d649d194384995/atc/db/migration/migrations/1584109185_add_last_hijack_to_containers.up.sql#L2)), so I suspect that could be related (we went from v5.7.0 to v6.3.0), but looking through the code, I'm not sure where the reference could be unless there were other places where migrations didn't fully occur.

Also really odd that this shows up in the UI, but doesn't show up in the log files. This makes it extremely difficult to get more information. Also, why are SQL errors **STILL showing up in the UI after so many major versions**? Isn't that user-interfaces 101?

   * v6.3.0
   * bosh deployed (both db and CC are fully bosh managed)
   * postgres 11.7
