### ISSUE TITLE
No arm64 fly binaries available

### ISSUE THREAD

**Issue by rossburton** [concourse/concourse#5841]
The buttons to download fly binaries are hard-coded to amd64, but my servers are arm64.

**Comment by taylorsilva** [comment]
Duplicate of mentioned issue^
Closing this issue.

**Comment by aramprice** [comment]
Any chance `fly` binaries could be provided in Github release before the whole system is converted to support `arm64`?

**Comment by taylorsilva** [comment]
Not feasible or worth the effort on our part. fly is also the easiest piece to compile locally if you really want your own version. Clone the `concourse/concourse` repo and run `go install ./fly`

**Comment by aramprice** [comment]
@taylorsilva - that make sense, thanks for the context.
