### ISSUE TITLE
waiting for suitable set of input version/ discovering any new versions 

### ISSUE THREAD

**Issue by ashmeet72** [concourse/concourse#5844]
## Expected results

all 3 jobs should green when executed

## Actual results
when we commit code then 1 job get executed because of auto trigger.but 2 job is not auto trigger so if we trigger job 3 without triggering job 2
then we got this error waiting for suitable set of input version/ discovering any new versions infinite situation

.but then i stop 3 job & run 2 job manually then again re-run 3 job then it work fine.

![image](https://user-images.githubusercontent.com/40124674/86493248-6d997280-bd8e-11ea-9d94-2761df92f6ca.png)

**Comment by jamieklassen** [comment]
I'm closing this because you already opened a discussion -- let's continue the conversation there: https://github.com/concourse/concourse/discussions/5843
