### ISSUE TITLE
fly sync from v5.8.1 to v6.3.0 issue

### ISSUE THREAD

**Issue by maxknee** [concourse/concourse#5848]
## Summary
When upgrading to 6.3.0 from 5.8.1, running `fly sync`

```bash
WARNING:

fly version (5.8.1) is out of sync with the target (6.3.0). to sync up, run the following:
```
but getting an error after I log in

```bash
error: user [] is not in team [name]
```

## Steps to reproduce

fly sync 

asks me to login, and successfully logs in, but fails

## Expected results

fly sync upgrades successfully 

## Actual results

`error: user [] is not in team [team-1]`

## Triaging info

* Concourse version: 6.3.0 (fly 5.8.1)
* Browser (if applicable):  Chrome
* Did this used to work? (i think so?)

**Comment by jamieklassen** [comment]
@maxknee there is a release note describing this backwards incompatibility -- https://github.com/concourse/concourse/releases/tag/v6.1.0#4950. We don't have an exhaustive upgrade matrix and I don't know if we want to commit to it. That said, what kind of documentation do you think would have led you to re-download fly?
