### ISSUE TITLE
Provide documentation on the `teams` functionality

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#585]
I only see a few mentions of teams in the code or documentation; I would like to see a lot more before the release candidate gets promoted.

As someone responsible for evaluating new Concourse versions and recommending to 4+ teams whether they should upgrade, I'd like to know more about what's involved (more than release notes typically would).

My immediate feedback is that the REST endpoint changes may break various team's hyperlinks, or merely add confusion if an instance is only used by one team (so it's just URL cruft for them).

In our particular case, splitting teams into separate Concourse instances is directly motivated by stability and workload considerations (40+ devs, 30+ pipelines, hitting container limits and memory load issues). The concept of roles and access control is a secondary benefit.

**Comment by cjcjameson** [comment]
Btw, _filing this issue just so that you get a story in your backlog_, mostly

**Comment by vito** [comment]
We never launch a feature without docs unless it's intentionally hidden away. :) We'll get to this before releasing.
