### ISSUE TITLE
Some passed triggers don't work after upgrade from v5.8 to v6.1

### ISSUE THREAD

**Issue by akshaymankar** [concourse/concourse#5856]
## Summary

After upgrade from v5.8 to v6.1 (via v6.0 and unsuccessful upgrade to v6.3), some passed triggers don't work. Even manually triggering such jobs doesn't make them `get` the latest resource.

## Steps to reproduce

Unfortunately, I haven't gotten around to reproducing this error in a completely new environment as following the steps would be quite cumbersome.

## Expected results

Jobs should continue getting triggered and new resources should be fetched on manual trigger.

## Actual results

Some jobs don't get triggered

## Additional context

The concourse instance was upgraded from v5.8 to v6.0 to make sure everything was fine. An upgrade to concourse v6.3 failed on workers due to some issue with the ansible role we depend on, but the web instance had been upgraded. We rolled back the version to v6.1 and things looked fine, until we noticed this issue.  

My pipeline looks like this:

- Job A gets triggerd on a pull request, puts a semver
- Job B gets the pull request with `passed: [Job A]`, `trigger: true`, `version: every`
- Job B also gets the semver with `passed: [Job A]`, but without `trigger: true` and `version: every`. 
- Job C gets the pull request with `passed: [Job A]`, `trigger: true`, `version: every`
- Job C doesn't get semver at all

For me, Job A and Job B keep getting triggered for each pull request. But Job C doesn't. When I trigger Job C, it gets some old version of the pull request.

I removed the `passed` and `trigger` settings from Job C, set the pipeline, added them back and set the pipeline again. Now, everything works as intended.

I wonder if something has gone wrong with migrations due to the downgrade. It would be nice if there was a guide to downgrade concourse versions.

## Triaging info

* Concourse version: 5.8 -> 6.0 -> 6.3 -> 6.1
* Browser (if applicable): Not applicable
* Did this used to work? 
  The upgrade: never tried before.
  The trigger: yes.

**Comment by jamieklassen** [comment]
Thanks for giving a detailed report of your experience. Until we have a consistent local reproducible, though, I'm going to convert this to a discussion following https://blog.concourse-ci.org/nobody-wants-a-stale-bot/#an-update-on-triage. In the meantime, can you give an actual pipeline YAML or excerpt?

Did you follow https://concourse-ci.org/concourse-web.html#downgrading for the downgrade? Downgrading is not a workflow that's very extensively supported, but we do test some really basic workflows continuously: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/downgrade:

https://github.com/concourse/ci/blob/342c2822c43c8c52d746d45fe4a1f0f6ee766578/pipelines/concourse.yml#L389-L411
