### ISSUE TITLE
Shell-Script Based Task Error from garden-runc

### ISSUE THREAD

**Issue by davewalter** [concourse/concourse#587]
Saw this error at the end of a shell-script based task:

connection: process error: could not find the exitcode file for the process: stat /var/vcap/data/garden/depot/b60c3c9e-8cf8-4cd0-5e06-caa91f92adeb/processes/24e4a6fa-650f-4d73-70c0-de206dee635f/exitcode: no such file or directory

Please let me know if you need more information. Unfortunately, the job has been re-run so the container is no longer available to hijack.

**Comment by vito** [comment]
Pretty sure this should only happen if the ATC went down, then the process exited, and it came back and failed to reattach because it already exited. Check the uptime of the ATC?

**Comment by vito** [comment]
Not likely to resolve this at this point.
