### ISSUE TITLE
missing bash makes hijack appear to fail

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#5877]
## Summary

```
Backend error: Exit status: 500, message: {"Type":"ExecutableNotFoundError","Message":"OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\": unknown","Handle":"","ProcessID":"","Binary":""}
```

## Steps to reproduce

Use @vito buildkit container, or any container which does not contain bash.

## Expected results

Fall back to the default shell sh.

## Actual results

Failure to log in.

## Additional context

`fly -t target hijack -u https://url`
where
`fly -t target hijack -u https://url sh`
works.

## Triaging info

* Concourse version: 6.3.0
* Browser (if applicable): Firefox
* Did this used to work? Not sure, I think so far all containers had bash.

**Comment by vito** [comment]
Some prior art in https://github.com/concourse/concourse/pull/4755 and prior discussion in https://github.com/concourse/concourse/issues/1073

👍 I think it'd be nice to try `bash`, catch the error, and then try `sh`. I left some suggestions in https://github.com/concourse/concourse/pull/4755#issuecomment-556296316 for anyone interested in taking another swing at this.

**Comment by shua** [comment]
I'd be glad to take this on, I took a stab this evening in a branch, currently stumped on:
```golang
if _, ok := err.(garden.ExecutableNotFoundError); ok {
  // this doesn't seem to ever get hit...
}
```
added into
https://github.com/concourse/concourse/blob/91261376be0997fe9ca35b27907c1ad19e9a4de0/atc/api/containerserver/hijack.go#L231-L237
and just going through the strokes of getting a debugger running and connected.
