### ISSUE TITLE
disable_manual_trigger not working as expected

### ISSUE THREAD

**Issue by PhiSDev** [concourse/concourse#5906]
## Summary

I was trying to configure a job which is not able to be triggered manually but it is possible to do it via UI and CLI.

## Steps to reproduce

- set the example pipeline with attached configuration
- unpause and trigger pipeline in frontend or via CLI

## Expected results

I expect to not see the trigger button or to be able to trigger the job.

## Actual results

The button is enabled and I'm able to start the job.

## Triaging info
[example.txt](https://github.com/concourse/concourse/files/4959480/example.txt)

* Concourse version: 6.3.0 and 6.4.0
* Browser (if applicable): Chrome 84.0.4147.89 & FF 77.0.1

**Comment by jamieklassen** [comment]
I have reproduced this locally - I also cracked open the database and saw
```
concourse=# select disable_manual_trigger from jobs;
 disable_manual_trigger
------------------------
 f
(1 row)
```
so I suspect the config-saving flow is to blame.

**Comment by jamieklassen** [comment]
Further confirmed that this works on v5.8.1 but does not work on v6.0.0 -- I strongly suspect #4862 caused this.

**Comment by clarafu** [comment]
Ah wow thanks for finding this bug! It looks like the `disable_manual_trigger` column is not being filled in when we save the job into the database.

https://github.com/concourse/concourse/blob/f184cf41ec0c43700016334b3d7d6545ef278f98/atc/db/team.go#L1064-L1071

**Comment by PhiSDev** [comment]
> Ah wow thanks for finding this bug! It looks like the `disable_manual_trigger` column is not being filled in when we save the job into the database.

No problem. Thanks for this really fast response!
