### ISSUE TITLE
Listing all teams takes a long time due to redundant auth checking

### ISSUE THREAD

**Issue by agurney** [concourse/concourse#5912]
## Summary

When the web UI asks for `/api/v1/teams`, and you're on Concourse 6.1.0+, and there are a few hundred teams, and you're not an admin, the response can take a long time to come back. In our case I'm seeing it taking about 30s for a normal user who is in a handful of teams. Admin users can retrieve the full list very speedily (milliseconds).

Whichever web node happens to be receiving the bulk of load-balanced traffic can be taking about 40% CPU (in our case) serving these requests.

## Steps to reproduce

* We are on 6.4.0 but I think the same behavior will be seen on 6.1.0.
* Have lots of teams - we have about 600, and I expect the performance degradation to be linear in the number of teams, so it could still be subjectively "bad" with a smaller number
* Be a logged-in non-admin
* From the web UI or directly, look at response times for `/api/v1/teams`.

## Expected results

I don't know how critical this data is for the dashboard - and since it doesn't change frequently, things should typically be basically fine as soon as the browser has the results of the first call. In general, though, it would be nice to have snappy responses. If nothing else, that helps with our operational tooling where we'd like to have alerts for "HTTP responses are super slow" without distractions from this particular endpoint.

## Actual results

```sh
$ time fly -t ci curl /api/v1/teams
[...list of the 8 teams for this user comes back...]

real	0m29.448s
user	0m0.111s
sys	0m0.048s
```

![](https://gist.githubusercontent.com/agurney/2f89322ba2674d5f530cb9e92a048d63/raw/9a1209026213066d6413a20d688205027692a5e6/flamegraph.png)

In this flame graph, the `ListTeams` bar is taking 37% of CPU. The four `rolesForTeam` bars together account for the bulk of that, about 31%. Within each `rolesForTeam`, it's about half-and-half between the four calls that ultimately ask for federated claims, and some map iteration costs. The tiny sliver on the far right is DB access, which does not appear to be a big contributor to the time taken. (As evidenced by the fact that _admin_ users can get the full team list very quickly - in their case, we make the exact same DB call, but then only have to pass the first `IsAdmin()` test against each team.)

## Additional context

Inspection of 🔥 flame graphs 🔥 and the code shows that the time taken is driven by a few factors:
1. `access.IsAdmin` is called three times for each team
2. each of those, plus `access.hasRequiredRole`, invokes `access.rolesForTeam`
3. the resulting (number of teams) * 4 calls to `access.rolesForTeam` each involve several further calls to `access.federatedClaim`, and some iteration over maps

Much of this work seems to be redundant in a formal sense, and while it's not too expensive to do once, it is adding up over the larger number of teams. For example, `teamserver/list.go` has, for each team,

```go
		if acc.IsAdmin() || acc.IsAuthorized(team.Name()) {
```

but then `IsAuthorized()` also ends up asking for `IsAdmin()` first of all anyway. Then, within `IsAuthorized()`, the call to `TeamNames()` also checks for admin status before querying `hasRequiredRole()`. It seems like this could be simplified to remove the redundancy. (The same redundancy appears to be in place for some other endpoints, but this one is the expensive one because of the repeated cost of inspecting the _team_ structure.)

![](https://gist.githubusercontent.com/agurney/2f89322ba2674d5f530cb9e92a048d63/raw/bb936b75706499553f061796111403b4baa8e946/roles-for-team.png)

Within `rolesForTeam()`, we first ask for four of the federated claims (groups, connector ID, user ID and user name). The leaves of these seem taken up by invocations of `runtime.fastrand` and `runtime.duffzero`; I don't know enough about go internals to understand why some map lookups and typecasts should involve these. Other runtime functions used in `rolesForTeam()` are `runtime.mapaccess1_faststr`, `runtime.mapiterinit`, and `runtime.mapiternext`, presumably for the looping over `auth`, `auth["users"]` and `auth["groups"]`. There may be ways to make this more efficient, perhaps again by reducing the redundancy.

The caching logic and general changes in https://github.com/concourse/concourse/pull/5897 might alter the overall performance characteristics, but I haven't tested.

## Triaging info

* Concourse version: 6.4.0 but probably true on 6.1.0 as well, since that is when the token format change happened
* Browser (if applicable): not a browser issue since this can be seen with `curl` just as well
* Did this used to work? On 6.0.0 with the same number of teams, our metrics show the same call taking ~10ms. We upgraded yesterday and saw this behavior change immediately, although all other performance is very good. (In particular, builds/checks/etc. are going through speedily even though this is happening.)

**Comment by aoldershaw** [comment]
Thanks for digging into this! The changes in #5897 don't improve this at the moment, but I'll optimize this soon as it seems crazy inefficient

**Comment by aoldershaw** [comment]
I put together a benchmark to try to capture the performance issues you're running into. The benchmark does the following:

* Create 600 fake teams
  * Each team has 10 groups associated with it, all for the owner role
* Create a "user" that's a member of 10 user groups (and so, 10 teams)
* Then, simulate the `ListAllTeams` endpoint by calling `acc.IsAdmin()` and `acc.IsAuthorized` for each team

```go
func BenchmarkAccessor(b *testing.B) {
	numTeams := 600
	numGroupsPerTeam := 10
	numUserGroups := 10

	teams := make([]db.Team, numTeams)
	for i := range teams{
		team := new(dbfakes.FakeTeam)
		team.NameReturns("team" + strconv.Itoa(i))
		groups := make([]string, numGroupsPerTeam)
		for j := range groups {
			groups[j] = "connector:group" + strconv.Itoa(i + 10 * j)
		}
		team.AuthReturns(atc.TeamAuth{
			"owner": map[string][]string{
				"groups": groups,
			},
		})

		teams[i] = team
	}
	userGroups := make([]string, numUserGroups)
	for i := range userGroups {
		userGroups[i] = "group" + strconv.Itoa(i)
	}
	verification := accessor.Verification{
		HasToken:     true,
		IsTokenValid: true,
		RawClaims:    map[string]interface{}{
			"groups": userGroups,
			"federated_claims": map[string]interface{}{
				"connector_id": "connector",
			},
		},
	}
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		acc := accessor.NewAccessor(verification, "owner", "system", []string{"a"}, teams)
		for _, team := range teams {
			acc.IsAdmin()
			acc.IsAuthorized(team.Name())
		}
	}
}
```

I'm not seeing the 30s that you're experiencing (though I'm sure this simulation is not the most representative) - but I am seeing it take ~1.5s (which is still really slow).

**Comment by aoldershaw** [comment]
Actually, I realized that the locking for recording invocations in `FakeTeam` was a bit of a bottleneck - replacing the `FakeTeam` with the following stub actually improves the time to ~0.25s. Could you give any insight into how auth is structured to make it easier to simulate the poor performance (e.g. number of groups per team, typical number of groups per user, etc.)

**Comment by aoldershaw** [comment]
I added an optimization to only compute `teamRoles` once, which drops the time down to ~8ms (~25x speedup) - though I'm hesitant to say "problem solved" since your initial slow computation time is so much slower than what I was able to get with 600 teams

**Comment by aoldershaw** [comment]
A bit of optimization later, and it's down to ~0.15ms (~1500x speedup) for the same 600 team benchmark. There's now a one-time upfront cost to computing `teamRoles` and whether the user is an admin, and everything else comes really cheap. While I wasn't able to experience the same slowness as you were facing, I think this should address the issue based on your flame graph analysis

**Comment by agurney** [comment]
Wow, thanks for your efforts on this!

It's worth pointing out explicitly that our web nodes are doing a bunch of other concurrent work, such as scheduling builds and whatnot, which could affect the timing behavior in all sorts of non-obvious ways.

I looked at our full dump of auth settings. Most teams are like the following:
```json
  {
    "id": 116,
    "name": "foo",
    "auth": {
      "owner": {
        "groups": [
          "github:foo"
        ],
        "users": []
      }
    }
  },
```
with there being a single GHE organization tied to the Concourse team. A few have more involved setups, such as
```json
  {
    "id": 323,
    "name": "xfinity",
    "auth": {
      "member": {
        "groups": [
          "github:bar:concourse-members"
        ],
        "users": []
      },
      "owner": {
        "groups": [
          "github:bar:concourse-owners"
        ],
        "users": []
      },
      "pipeline-operator": {
        "groups": [
          "github:bar:concourse-pipeline-operators"
        ],
        "users": []
      },
      "viewer": {
        "groups": [
          "github:bar"
        ],
        "users": []
      }
    }
  },
```

There are not too many in that category, and it seems a bit doubtful to me that the comparatively small number of such teams could be responsible for such a large effect.

We may be able to try out a local patch of your changes to `accessor` (but probably not _very_ soon), as that seems self-contained from the other changes in #5897. If we do it might provide an interesting benchmark.
