### ISSUE TITLE
Enable containerd on CI

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#5914]
# Motivation
This is the next natural step in getting containerd epic to being GA. Enabling containerd on CI will allow us to 
- get operational confidence in 'containerd'
- a snapshot of the impact the switch has on performance
- identify if there are any pain points or gaps in the feature set

## Next Steps
- [x] Can we setup a drills like environment with contaienrd as a preliminary step ?
- [x] Identify the main metrics we'd want to observe when switching
- [x] Plan to make the change in coordination with the next release or independently

**Comment by muntac** [comment]
@clarafu and I talked about some possible Metrics for Containerd drills. It would be useful to have two drill environments, one with containerd and the other with Guardian, running similar workloads.

* How long a build takes to complete? - Use the Build Time metric (e.g. on Datadog). Scatter plot of build times for a single job.

* Worker Containers over time

* Worker Volumes (likely less effect, and reliant on baggage claim)

* Garbage Collection - Containers and volumes (likely less effect, and reliant on baggage claim)

* Maximum number of containers - a particular number doesn't necessarily make too much sense as task CPU utilization is highly variable. In an ideal world container creation would be throttled by CPU utilization. However, having a limit is still important to prevent the stampeding herd problem.

* Using tracing to see how long it takes to complete a step

* CPU and Memory Utilization for the same workload on Guardian vs Containerd

**Consider types of pipelines**

Have all the different types of containers - check, build

Types of steps for Builds - get, put, and task steps.

Focus on container creation - this means triggering lot of builds. Jobs that run really often e.g. every minute would do this. Can use Time resource.

**Comment by muntac** [comment]
`containerd` has been re-enabled on CI. No further problems have arised.
