### ISSUE TITLE
Active user tracking causes frequent DB-level deadlocks

### ISSUE THREAD

**Issue by agurney** [concourse/concourse#5915]
## Summary

Following an upgrade of our largest Concourse instance from 6.0.0 to 6.4.0, we've seen:
* at any given time, some of the ATCs will have a large number of DB queries per second (like 1000 more than the next ATC)
* our DB (in AWS RDS) is showing an elevated number of active sessions, attributable to the `INSERT INTO users...` query from `db.UserFactory.BatchUpsertUsers`
* DB error logs are full of complaints about deadlocks between these queries

## Steps to reproduce

We have 3300+ users in total according to the current state of the `users` table, but they're not all using it at once. Access logs show that over a 1h period today there were about 450-500 distinct users. The SQL statements reported as deadlocking are each trying to insert about 200 entries. Currently we're running 10 ATC nodes.

It would probably be annoying to try to replicate this artificially (e.g. by creating a bunch of fake users and having them generate fake traffic to the desired volume). Generating a bunch of raw SQL queries of the desired form might be better for demonstrating the situation, absent actually having a production cluster of this size. Some more details from our cluster are below.

## Expected results

The ATCs and DB are not hugely stressed by trying to update last-access times.

## Actual results

They are!

This does not seem to be causing real "problems" with the system, since nothing really depends on the upserts happening, and it's only one thread on each ATC that has to hang around waiting for Postgres. Equally, the DB is currently "happy" in that it's within its capacity to have lock-induced churn on `users` while still being able to handle general queries properly. But this is taking up extra resources in the ATC and DB tiers, which is not desirable.

## Additional context

A typical chunk of Postgres complaints is [here](https://gist.githubusercontent.com/agurney/e05aadec532e9d6ee8d272df5b309ad4/raw/610bbbabf78a849f3b9ab990ea770ec8072d91cd/postgres-log-sample.txt). This particular one has five contending transactions, but some others have more. Per [PostgreSQL docs](https://www.postgresql.org/docs/current/explicit-locking.html), part of what's going on is that the `UPDATE` attempt for a field with a `UNIQUE` constraint will need a `FOR UPDATE` lock. That conflicts with the `FOR SHARE` lock (see Table 13.3), which I _think_ might be acquired as a result of the other transaction checking for uniqueness of `sub`. I believe these are the `AccessExclusiveLock` and `ShareLock` referred to in the logs.

Readers not totally immersed in PostgreSQL may like to read [this blog post](https://rcoh.svbtle.com/postgres-unique-constraints-can-cause-deadlock) about a similar scenario with conflicting updates in the presence of a UNIQUE constraint.

The performance results, according to RDS Performance Insights, are thus:
![](https://gist.githubusercontent.com/agurney/e05aadec532e9d6ee8d272df5b309ad4/raw/610bbbabf78a849f3b9ab990ea770ec8072d91cd/rds-perf-insights.png)

In our installation, we have tuned PostgreSQL timeout settings so that these transactions will be aborted on the DB side after a few minutes. I fear that if we hadn't done this, the deadlock would persist until connections were broken (e.g. by ATC restart).

I am guessing that since user requests are being load-balanced among the several ATCs, and that fact is batched up on each one for upsertion, we're getting a bunch of API traffic for the same user essentially conflicting with itself: multiple ATCs are trying to update the same row at about the same time.

The [batcher](https://github.com/concourse/concourse/blob/master/atc/api/accessor/batcher.go) configuration is currently hardcoded to batches of 100 every 15s. The [construction](https://github.com/concourse/concourse/blob/master/atc/atccmd/command.go#L1812) means that all the API traffic, not just logins, get funneled through the batcher. (So, it appears that what's called the last-login time would be effectively the last-API-call-made time instead? It's a little tricky for me to test that at the moment since so many of the upserts that should record this data are failing.)

Perhaps the issue can be partially mitigated by attaching this logic to the login endpoints instead, which should result in a lot less volume of updates. I don't think that tuning the current hardcoded batch parameters will be of any help, since no tweaking will remove the basic logical issue.

The SQL query in [BatchUpsertUsers](https://github.com/concourse/concourse/blob/master/atc/db/user_factory.go#L38) could be tuned. It might be the case that sorting the values to be inserted could result in the locks being acquired in a consistent order across parallel transactions. Otherwise, since this kind of scenario is fairly common (conflicting batch updates causing deadlock), some friendly SQL wizard might have other neat ideas on how to restructure the table or query.

## Triaging info

* Concourse version: 6.4.0, but probably the case in 6.1.0+ as well.
* Browser (if applicable): N/A
* Did this used to work? The batch-upsert code was introduced in https://github.com/concourse/concourse/pull/5257, part of 6.1.0, so that's the critical change.

**Comment by taylorsilva** [comment]
Quickly read your post, but I think #5897 will resolve this scaling problem. Not a core part of the PR but a positive side-affect:

> It also changes to user tracking behaviour - rather than updating a user's last login on every authenticated request, only update it on login. This affords us some simplification in the API auth flow (in particular, we no longer need to batch user update requests).

wdyt?

**Comment by jamieklassen** [comment]
+1 to @taylorsilva's observation -- part of the "opaque tokens" change should mean that the whole 'last-API-call-made' (@agurney you are correct about that) tracking is replaced with actual 'last login' tracking. I just came by to say what an excellent report this is. @agurney thank you so much for your thorough investigation and thoughtfulness!

**Comment by agurney** [comment]
In pursuit of this theory (and pending its resolution by #5897 removing the batch-upsert code entirely), we deployed a local patch that altered the upsert behavior. After deployment, load went down:

![](https://gist.githubusercontent.com/agurney/e05aadec532e9d6ee8d272df5b309ad4/raw/32f6ac46c02a9638fe33ce3fee979e9164f5adb5/load-after-patch.png)

and deadlocks went to zero per minute, where they had been happening every second:

![](https://gist.githubusercontent.com/agurney/e05aadec532e9d6ee8d272df5b309ad4/raw/32f6ac46c02a9638fe33ce3fee979e9164f5adb5/deadlocks-after-patch.png)

The altered code in `atc/db/user_factory.go` takes care to construct the `INSERT INTO users` query such that values are always ordered consistently. Since the `sub` is `UNIQUE` anyway, it seemed like a reasonable choice to use.

```go
	users := make([]User, 0, len(userMap))
	for _, user := range userMap {
		users = append(users, user)
	}

	sort.Slice(users, func(i, j int) bool {
		return users[i].Sub() < users[j].Sub()
	})

	for _, user := range users {
		builder = builder.Values(user.Name(), user.Connector(), user.Sub())
	}
```

This is done locally to that function in lieu of making a more extensive change to the mechanism, because we wanted to keep the patch tightly scoped.

Because of this change, overlapping `INSERT INTO users` transactions from different ATC nodes will always have the `VALUES` in a consistent order. So when Postgres executes them, it always acquires row-level locks in that same order. (I am not clear on the extent to which this is guaranteed by Postgres or by the SQL spec, but it does seem to work empirically.) This applies to existing `sub` values, for which the `UPDATE` rider gets run, and for new ones. In any case, the queries can now be put in some order of execution where they can succeed one after the other, instead of blocking each other.

Since the batch-upsert code should be gone completely in the next release, I haven't made a PR out of this, but it may still be of interest to anyone having the same problem who can't wait for the next release, and for people who like to think about database deadlocks. The resolution here is roughly the same as in Dijkstra's _Solution of a problem in concurrent programming control_ (Comm. ACM 8(9):569, September 1965), if you squint enough.

**Comment by aoldershaw** [comment]
Whoops, forgot to close this after merging #5897 - but really awesome investigation @agurney! It'll definitely help us work through other issues (e.g. https://github.com/concourse/concourse/issues/5947 sounds like the same problem)
