### ISSUE TITLE
Lack of generic authentication options

### ISSUE THREAD

**Issue by benjumanji** [concourse/concourse#593]
Ideally I'd love some LDAP, but I would definitely take the option to have a header set the user, the idea being that you would bind the web to localhost, throw some authenticating proxy in front that sets the username and be done with it.

Failing all of these options, how hard would it be to add phabricator as an oauth option?

**Comment by benjumanji** [comment]
I suppose I can do the generic stuff right now by putting development mode and sticking the proxy in front, I just don't get to pass username info to co concourse. I guess that's not so bad, but it feels bad?

**Comment by vito** [comment]
Not sure what you mean by setting the username. Currently there's not really a notion of a 'user' - in 1.7 there will be a 'team' but it's really just pushing down today's static configuration to being dynamic (and multitenant).

Someone's working on a generic OAuth provider here which may be what you're looking for: https://github.com/concourse/atc/pull/101

**Comment by benjumanji** [comment]
Ok, I was thinking concourse had users because of the basic auth stuff. Fine. Generic OAuth sounds great, in the meantime I'll throw a proxy in front.
