### ISSUE TITLE
admins can log into nonexistent teams

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#5939]
## Summary

With concourse/concourse#5749 we were a bit too permissive -- certainly admins can now log into any team, but we even allowed them to log into teams that don't exist!

## Steps to reproduce

1. `docker-compose up --build -d` using the default dev `docker-compose.yml` in this repo
1. wait for the web component to be running
1. download fly (I used `fly sync -c http://localhost:8080` because I happened to have a post-6.0 fly)
1. `fly -t dev login -c http://localhost:8080 -u test -p test -n doesntexist`

## Expected results

```
$ fly -t dev login -c http://localhost:8080 -u test -p test -n doesntexist
logging in to team 'doesntexist'


error: you are not a member of 'doesntexist' or the team does not exist
```

## Actual results

```
$ fly -t dev login -u test -p test -n doesntexist
logging in to team 'doesntexist'


target saved
```
... and then it gets worse ...
```
$ fly -t dev set-pipeline -p pipeline -c web/wats/fixtures/smoke-pipeline.yml
resources:
  resource mockery has been added:
+ name: mockery
+ source: null
+ type: mock

jobs:
  job say-hello has been added:
+ name: say-hello
+ plan:
+ - get: mockery
+ - config:
+     image_resource:
+       source:
+         mirror_self: true
+       type: mock
+     platform: linux
+     run:
+       args:
+       - Hello, world!
+       path: echo
+   task: hello
+ - params:
+     version: put-version
+   put: mockery

apply configuration? [yN]: y
error: Unexpected Response
Status: 500 Internal Server Error
Body:

```

## Triaging info

* Concourse version: 6.3.0, 6.4.0, master
* Browser (if applicable): n/a
* Did this used to work? 6.2.0 works

**Comment by clarafu** [comment]
Hm I don't think this will be a simple fix because when we grab the user info for an admin user, it only returns back the teams that the user is a member of. So for an admin user, we will need to add some way of grabbing all the teams within a deployment and verifying that the team they are trying to login to is valid.

**Comment by chenbh** [comment]
I can also use `fly edit-target -n doesntexist` or even just edit my `.flyrc` directly
