### ISSUE TITLE
Concourse with garden-runc 0.5.0 and bosh-cli output issue

### ISSUE THREAD

**Issue by JamesClonk** [concourse/concourse#594]
I didn't know whether it makes more sense to report my issue here or on the garden-runc repo, but I ran into a strange problem when using garden-runc 0.5.0 for the Concourse workers. (Problem does not exist with 0.4.0 workers)
See https://github.com/cloudfoundry/garden-runc-release/issues/13

What version of garden-runc is officially supported by Concourse?
(In the sample manifests it just says "latest" everywhere 😝 😆 )

**Comment by vito** [comment]
Should be the versions listed on this page:

https://concourse.ci/downloads.html

**Comment by JamesClonk** [comment]
ah, silly me. I completely overlooked that. Thanks!
