### ISSUE TITLE
Worker extremely slow when running in a docker container on mac os x with docker for mac

### ISSUE THREAD

**Issue by willejs** [concourse/concourse#596]
The way in which the worker provisions a btrfs filesystem for workers means that it [falls back to the vfs graph driver](https://github.com/concourse/concourse/blob/9bb58ca099aab471521edd819584594778e38a5e/docs/release-notes/v0.58.0.any#L49) if btrfs is not present on the host.

This means that when you are performing builds (especially docker-images) its painfully slow.

The underlying VM image and kernel for docker for mac doesent support btrfs. I am wondering if there is an alternative to creating a btrfs volume that is more performant than tmpfs?

**Comment by andrewedstrom** [comment]
@willejs Are you still experiencing this issue now that we've moved off of btrfs as of 3.1.x?
