### ISSUE TITLE
Use the current ci db (or a snapshot) with the new cluster

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5960]
Checklist:

* [ ] Ensure no ATC is running on the new cluster
* [ ] Restore the database from a backup
* [ ] Re-encrypt the database with the new encryption key

In proper greenpeace fashion, we should automate this as much as possible in case we want to do this in the future

**Comment by aoldershaw** [comment]
It's not so easy to fit this kind of operation into Terraform, so we will just write scripts to automate this.

The `gcloud` CLI gives us a `gcloud sql backup restore` function that makes this easier.

One missing component is rotating the encryption key. `concourse migrate` doesn't currently provide a way to do this, and it's not ideal to run the ATC with the old encryption key since it's just a one-time operation.

**Comment by chenbh** [comment]
Added scripts for it under the `scripts/restore-db-backup` and `scripts/reencrypt-db` along with instructions in the README of greenpeace.
