### ISSUE TITLE
containerd containers on Kubernetes can't talk to web

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#5967]
## Summary

`k8s-topgun` test suite is failing.

**Why is the job failing?**
1. [k8s-topgun](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/288) is still failing because of [these two DNS Proxy tests](https://github.com/concourse/concourse/blob/38e7816949904367a7eb51ebf2ceafad3a401ba3/topgun/k8s/dns_proxy_test.go#L98-L107) that run with containerd.

2. The tests turn off the DNS proxy server and expect that containers will be able to reach the web node in the cluster whether it uses the full address `...-web-namespace-svc.cluster.local:8080` or not `...-web-namespace:8080`. The containers currently cannot reach either address without DNS proxy server running.

3. Previously to enable the DNS proxy for guardian and containerd we used `CONCOURSE_GARDEN_DNS_PROXY_ENABLE`

4. Now we use `CONCOURSE_GARDEN_DNS_ENABLE_PROXY` for guardian, and `CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE` for containerd

**So why do the same tests only fail for containerd and not guardian?**
1. In Guardian's case the contents of the resolv.conf of the worker is copied into the container's resolv.conf. 

2. Containerd does not do this although I remember the topic being brought up before and vaguely remember validating making it happen.

**How did it pass for containerd before?**
1. I've tried Helm installing with the image and chart used in the last passing build of k8s-topgun, and the same is true for containerd's resolv.conf behaviour there. I even rerun that last passing [build](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/272), intercepted it and ran the tests according to the ci script and watched the tests fail contrary to CI.

2. I now have no idea how those two tests ever passed before.

**How to fix this?**
1. Implement the same behaviour that Guardian has. When the proxy isn't enabled put the contents of the worker's resolv.conf into the container.

2. Watch out for this red herring that I spent a while on - the concourse/concourse Docker image is built from this Dockerfile in concourse/concourse-docker , and always sets `CONCOURSE_GARDEN_DNS_ENABLE_PROXY` to true. So I thought whether or not you want to have a proxy DNS server, set or not set it in BOSH release or Helm chart, it always runs.  But setting that value to "false" in the chart, which the tests do, does override this. More [here](https://github.com/concourse/concourse/issues/4085#issuecomment-561733322). To validate whether a proxy server is running you can run the following on the worker:

```
apt-get update && apt-get install net-tools
netstat -lunp | grep -w ':53’
```

3. Figure out what to do with the [Dockerfile](https://github.com/concourse/concourse-docker/blob/master/Dockerfile#L11) setting CONCOURSE_GARDEN_DNS_ENABLE_PROXY to true. It was [introduced](https://github.com/concourse/concourse-docker/commit/a729a4293160fae7e2cc32241999b5bd943594da) a few years ago to deal with this [issue](https://github.com/concourse/concourse/issues/1145). Here are [two](https://github.com/cloudfoundry/guardian/issues/42#issuecomment-304295875) [posts](https://github.com/concourse/concourse/issues/1145) talking about solutions. On Friday I had [disabled](https://github.com/concourse/ci/pull/357/files) this for the concourse/dev Dockerfile but that needs to be reconsidered too given that a lot of people may run into problems according to the posts I linked.

## Triaging info

* Concourse version: 38e7816949904367a7eb51ebf2ceafad3a401ba3
* Did this used to work? Apparently, yes - https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/272

**Comment by muntac** [comment]
Here's how Guardian sets up the `resolv.conf` - https://github.com/cloudfoundry/guardian/blob/ca905e542c224efde27f5c2070ac6c6f9bc37c0c/kawasaki/resolv.go#L30

**Comment by muntac** [comment]
Running a local version of the Helm chart and acceptance tests.
```
gcloud container clusters get-credentials topgun

export HELM_CHARTS_DIR=/Users/pivotal/workspace/charts/
export CONCOURSE_CHART_DIR=/Users/pivotal/workspace/concourse-chart
export CONCOURSE_IMAGE_NAME=concourse/concourse-rc

# update fly to latest (i.e. after 6.0) if you're working with latest concourse. can sync with hushhouse.

# go to concourse/concourse-chart
# in values.yml change the image name to concourse/[YOUR_IMAGE_NAME] and image tag to "latest" or the 
# tag you pushed with. 
# set ImagePullPolicy to Always to avoid potential caching issues. I like to not use image tag and 
# put in the `imageDigest: sha256:xxxxx....` directly.

# go to topgun/k8s. if desired, focus the specific test suite.

ginkgo -nodes=8 . -v

```

**Comment by xtreme-sameer-vohra** [comment]
> Here's how Guardian sets up the `resolv.conf` - https://github.com/cloudfoundry/guardian/blob/ca905e542c224efde27f5c2070ac6c6f9bc37c0c/kawasaki/resolv.go#L30
> 
> Here's where we setup `resolv.conf` with `containerd`:
> 
> https://github.com/concourse/concourse/blob/38e7816949904367a7eb51ebf2ceafad3a401ba3/worker/runtime/cni_network.go#L217
> 
> We probably want to copy the contents of the worker's `resolv.conf` into the container's one. This includes nameservers and search fields.
> 
> Example
> 
> **Running Guardian with DNS Proxy disabled and no DNS servers passed:**
> 
> _etc/resolv.conf on the worker_
> 
> ```
> nameserver 10.56.0.10
> search guardian-flags-test.svc.cluster.local svc.cluster.local cluster.local c.cf-concourse-production.internal google.internal
> options ndots:5
> ```
> 
> _etc/resolv.conf on a container_
> 
> ```
> nameserver 10.56.0.10
> search guardian-flags-test.svc.cluster.local svc.cluster.local cluster.local c.cf-concourse-production.internal google.internal
> options ndots:5
> ```
> 
> **Running Containerd with DNS Proxy disabled and no DNS servers passed:**
> 
> _etc/resolv.conf on the worker_
> 
> ```
> nameserver 10.56.0.10
> search containerd-proxy-flags-test.svc.cluster.local svc.cluster.local cluster.local c.cf-concourse-production.internal google.internal
> options ndots:5
> ```
> 
> _etc/resolv.conf on a container_
> 
> ```
> nameserver 8.8.8.8
> ```

This looks like a good manual acceptance test, with the K8s topgun suite providing the automated tests.

**Comment by xtreme-sameer-vohra** [comment]
> ## Summary
> **How to fix this?**
> 
> 1. Implement the same behaviour that Guardian has. When the proxy isn't enabled put the contents of the worker's resolv.conf into the container.

For parity with Guardian, the worker's resolv.conf contents should be put into the container only when no DNS servers are configured as opposed to when the proxy isn't enabled. The proxy being enabled/disabled is independent of the [Guardian's treatment of the container's resolv.conf entry ](https://sourcegraph.com/github.com/cloudfoundry/guardian@13eee1c31070110d93c80f2b9c42d885a0a51ab3/-/blob/kawasaki/dns/resolv_compiler.go#L12-29)

**Comment by YoussB** [comment]
after understanding the problem more, thanks to @xtreme-sameer-vohra.
- Current state:
  - if `containerd-dns-servers` is provided this will correctly use these inside the container's `resolv.conf` without anything else, correctly mimicking `garden`.
  - if `containerd-dns-servers` is not provided; resolv.conf will be populated with `nameserver 8.8.8.8`. The correct contents should be the values of the host's resovl.conf.
  - there is no implementation for `containerd-additional-servers` to mimic `garden-addtional-servers` uses either the value provided by the `garden-dns-servers` or the host's resolv.conf with along with the provided additional servers.

- TODO:
  - [ ] read the hosts resolv.conf and add it to container, if `containerd-dns-servers` is not provided.
  - [ ] limit the number of servers to 3 (per: [resolv.conf man page](https://man7.org/linux/man-pages/man5/resolv.conf.5.html)
  - [ ] implement `containerd-additional-servers` <-- can be done in a separate issue.
