### ISSUE TITLE
Search/Filtering overhaul

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5969]
## Summary

Update the current appearance/behavior of Concourse's Search/Filter behavior,

!['Before' state screenshot](https://user-images.githubusercontent.com/6372810/94476371-64a61a80-019e-11eb-8148-974cfcf69846.png)

...to achieve the following normal state,

!['After' state screenshot](https://user-images.githubusercontent.com/6372810/94476379-6839a180-019e-11eb-8ef7-8e2a0f3ad063.png)

...and the following state when 'active' with a search query,

![Screen Shot 2020-09-28 at 3 25 49 PM](https://user-images.githubusercontent.com/6372810/94476766-e5fdad00-019e-11eb-857e-5f45cae0653f.png)

## Acceptance Criteria
- [ ] Make the placeholder text more explicit than 'search'. Try 'Filter pipelines by name, status, or team'.

### Default state:
- [ ] Hide the 'X' icon from view instead of just dimming it when it's unavailable, to avoid confusion
- [ ] Background should be Grey 90 #262626
- [ ] Placeholder text should be Grey 30 #C6C6C6 for adequate reading contrast
- [ ] Default border is Grey 60 #666666

### Active/focused state:
- [ ] Show the 'X' icon and highlight the search border (both Grey 30 #C6C6C6)
- [ ] Search query text is Grey 100 #F2F2F2

## Context

* Part of #5964 Web UI/UX experience

**Comment by jomsie** [comment]
Discussed with @chenbh and since there's a lot of colour work, we're going to merge these commits into #5974 (branch issue/5974) and when that one is done finish off both issues.

**Comment by chenbh** [comment]
Closing this as #6168 has been merged
