### ISSUE TITLE
Change 'menu' icon in header

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5970]
## Summary

Update the current appearance/behavior of Concourse's sidebar/menu button behavior to achieve the following:

**Sidebar closed, button indicates to open sidebar:**
![Sidebar closed](https://user-images.githubusercontent.com/6372810/97012666-19212b00-1516-11eb-96f6-10ad635bd6a4.png)

**Sidebar closed, hovering on button to open sidebar:**
![Sidebar closed hover](https://user-images.githubusercontent.com/6372810/97012686-1e7e7580-1516-11eb-8868-1fe22a46ed3e.png)

**Sidebar open, button indicates to close sidebar:**
![Sidebar open](https://user-images.githubusercontent.com/6372810/97012701-23dbc000-1516-11eb-9209-c0fdd6585e12.png)

**Sidebar open, hovering on button to close sidebar:**
![Sidebar open hover](https://user-images.githubusercontent.com/6372810/97012717-2b02ce00-1516-11eb-86fc-af65f44c47d8.png)

If the icons don't look crisp in these screenshots, click to view at 100% (Github resizes images).

[Click here for an interactive prototype](https://www.figma.com/proto/fuoFSVcTGptiS21P2POA2XbN/Concourse-UI-kit-and-Experiments?node-id=1639%3A136072&scaling=min-zoom). The prototype doesn't show a tooltip (tool limitations - I can only change so much on hover) but ideally we would show a tooltip to further explain what the button does when a user hovers.

### Open the sidebar

<img width="16" alt="sidebar_16" src="https://user-images.githubusercontent.com/6372810/90803210-6a2e5c00-e2e6-11ea-9821-0ae92bca0f4e.png">

![Screen Shot 2020-08-20 at 1 41 13 PM](https://user-images.githubusercontent.com/6372810/90806340-dca13b00-e2ea-11ea-8007-d1496dbc736f.png)

```svg
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="0.5" y="0.5" width="15" height="15" stroke="#C6C6C6"/>
    <rect x="0.5" y="0.5" width="6" height="15" fill="#C6C6C6" stroke="#C6C6C6"/>
</svg>
```
### Close the sidebar

![sidebar button closed](https://user-images.githubusercontent.com/6372810/90806212-b2e81400-e2ea-11ea-8cd2-1954c0cb225d.png)

![Screen Shot 2020-08-20 at 1 38 41 PM](https://user-images.githubusercontent.com/6372810/90806379-ec208400-e2ea-11ea-86bd-47926952acd9.png)

```svg
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="0.5" y="0.5" width="15" height="15" stroke="#C6C6C6"/>
    <rect x="6" y="13" width="1" height="1" fill="#C6C6C6"/>
    <rect x="6" y="11" width="1" height="1" fill="#C6C6C6"/>
    <rect x="6" y="9" width="1" height="1" fill="#C6C6C6"/>
    <rect x="6" y="7" width="1" height="1" fill="#C6C6C6"/>
    <rect x="6" y="5" width="1" height="1" fill="#C6C6C6"/>
    <rect x="6" y="3" width="1" height="1" fill="#C6C6C6"/>
    <rect x="6" y="1" width="1" height="1" fill="#C6C6C6"/>
</svg>
```

The prototype illustrates some changes to stroke and fill colour to highlight things for different states, but if this is tricky to do (I think we're using `<img src="icon.svg">` as a strategy for display and that is probably an obstacle) then I can provide different SVGs to achieve active/inactive/hover states.

## Tooltip suggestion

![Screen Shot 2020-10-23 at 10 07 12 AM](https://user-images.githubusercontent.com/6372810/97013828-884b4f00-1517-11eb-9c7d-1f4e7d19c069.png)

## Acceptance Criteria

- [ ] Match icon for opening and closing the sidebar to the opened/closed sidebar states above instead of the current hamburger menu icon
- [ ] Reconcile hover/state colors - default state is Grey 30 (#C6C6C6), hover state is white (#FFFFFF)
- [ ] Ensure that the background/foreground colours meet contrast guidelines (more deets in #5974 , feel free to ping @matthewpereira)
- [ ] Provide a tooltip on hover so that users can 'preview' button's behavior before clicking

## Context
* https://www.nngroup.com/articles/state-switch-buttons/
* Part of #5964 Web UI/UX experience

**Comment by kcmannem** [comment]
I feel like tooltips are a crutch. You only have to click the icon once to figure out what it does. Great looking icon though.

**Comment by chenbh** [comment]
@matthewpereira it looks like we'll need the 2 extra hover/active versions of the svgs. Unless Grey 30 can be derived from white using `opacity` values.

**Comment by matthewpereira** [comment]
@chenbh @EstebanFS Can we just change the colour values in the SVG code above and then save it to a different file?

```svg
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="0.5" y="0.5" width="15" height="15" stroke="EDIT HERE"/>
    <rect x="0.5" y="0.5" width="6" height="15" fill="EDIT HERE" stroke="EDIT HERE"/>
</svg>
```
