### ISSUE TITLE
CI monitor and Pipeline tile alignment adjustments

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5971]
### Current state

![Screen Shot 2020-08-21 at 11 14 46 AM](https://user-images.githubusercontent.com/6372810/90906466-b8536600-e39f-11ea-8115-970c4db11f64.png)

Inspecting the dom and adding gridlines, we can see that the CI monitor dashboard uses a variety of different spacings and paddings (7px, 12px, 30px, etc). The team names and section headers line up with the pipeline labels rather than the pipeline tiles themselves, and over time these values have shifted as different enhancements were introduced to the dashboard.

### Proposed state

![Screen Shot 2020-08-21 at 11 07 36 AM](https://user-images.githubusercontent.com/6372810/90906359-8f32d580-e39f-11ea-940f-e32b5b69d35d.png)

By using 32px spacing around all of our elements, and lining up the team and section headers with the pipeline tiles, we get a more consistent and orderly view.

### Current state

![Screen Shot 2020-09-01 at 9 48 36 AM](https://user-images.githubusercontent.com/6372810/91859344-5369fc80-ec38-11ea-9327-91d12a203af6.png)

Likewise, there are a number of different units dividing up the pipeline tile.

### Proposed state

![Screen Shot 2020-09-01 at 9 45 25 AM](https://user-images.githubusercontent.com/6372810/91858988-e48ca380-ec37-11ea-98cc-b3b3cc148c9b.png)

We can simplify the layout a fair bit and create symmetry between the header and footer by aligning everything in an orderly way.

## Figma mockups

[Mockups are available in Figma to get a detailed look at spacing and alignment](https://www.figma.com/file/fuoFSVcTGptiS21P2POA2XbN/Concourse-UI-kit-and-Experiments?node-id=1675%3A0). Look for the highlighted frames for the target variations.

## Acceptance Criteria

- [x] Line up team names with pipeline tiles so that dashboard has consistent margins
- [x] Pipeline tile spacing to be 32px, remove any alternative padding or margins wherever possible
- [x] Ensure icon sizing and stroke is consistent on pipeline icons
- [x] 16px, 8px spacing between elements in the pipeline tile

## Context

* Part of #5964 Web UI/UX Experience

**Comment by jomsie** [comment]
So @xtreme-vikram-yadav and I had a bit of time before lunch, so we took a quick look at this!

For the issue with the pipeline title not being aligned with the pipeline card, you have to change things in a bunch of places:
1. pipeline card itself has a translate in `Dashboard/Group.elm` and uses the padding variable in `PipelineGrid/Constants.elm`
2. "all pipelines" header has a padding in `Dashboard/Styles.elm`
3. team name has a calculation for left padding in`css/dashboard.less`

We aren't going to take this on at the moment, was just poking around and learning!

**Comment by matthewpereira** [comment]
@jomsie Any chance we could consolidate elements like this into one reusable component that has one set of style properties coupled to it?

**Comment by jomsie** [comment]
@matthewpereira 
1. to the first part of that comment, i'll have to look into it, because (and i might be completely off base) i think a good part of the dashboard is still styled with less (as opposed to being fully in the elm-y world)

2. i think one issue is fine!
