### ISSUE TITLE
Understand Service Account User / Service Account Admin roles

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#5973]
The service account greenpeace-terraform@cf-concourse-production.iam.gserviceaccount.com has role `Service Account User` and `Service Account Admin`.

We need to understand how those permissions work and if it is neccesarry that we grant both permissions not only to green-peace but some other service accounts (e.g. concourse-platform-automation) across the whole project.

**Comment by aoldershaw** [comment]
Service account user allows you to run operations as the service account

Service account admin allows you to create service accounts (in Greenpeace, we create a service account for our Vault instance to access GCS)

Source: https://cloud.google.com/iam/docs/understanding-roles

**Comment by xtremerui** [comment]
The main concern is the `iam.serviceAccounts.actAs` permission of `Service Account User`. The question is what user the service account will "actAs". In the entire project we have several service accounts, when they are granted `Service Account User` role, I think we need to think about the permissions that user has. So that the service account has an `at least` privilege but not as powerful as an G suit user  like us developer. (correct me if anything wrong here as I am also new to IAM)

**Comment by aoldershaw** [comment]
I might be wrong, but based on https://cloud.google.com/iam/docs/understanding-service-accounts:

> Permission to impersonate the service account is provided by any role that includes the iam.serviceAccounts.actAs permission

it seems to me like that `iam.serviceAccounts.actAs` doesn't mean the service account can act as a user - it means users can act as the service account

**Comment by xtremerui** [comment]
> it seems to me like that `iam.serviceAccounts.actAs` doesn't mean the service account can act as a user - it means users can act as the service account

So following the doc of IAM `who has what roles for which resources`, in the case of greenpeace, I assume the `who` is greenpeace service account and the `which` should be node pool resources. Why `compute.admin` role is not enough as `what `?

**Comment by xtremerui** [comment]
when we tried to test the changes of `bootstrap/bootstrap.tf` we could only test it by removing the terraform deployed dispatcher and production. Then we realized there is no easy way to `terraform destroy` any of them. 

The current way to do so is pulling the `resource_backend_config.json` from the put step of `terraform` in `pipelines/greenpeace.yml` and the `dispatcher.tfstate` from `concourse-greenpeace/terraform` bucket and finally run terraform destroy locally.

Wondering is there any other way to test the permissions set and should we script the terraform destroying to make greenpeace more portable?

**Comment by aoldershaw** [comment]
@xtremerui good point, I ran into that myself. The terraform resource supports an `action: destroy` param, so the easiest way would probably be to just add a job that is manual trigger only for destroying the environment.

See `action` under the [Put parameters](https://github.com/ljfranklin/terraform-resource#put-parameters) docs and the `destroy-env-and-lock` job in https://github.com/ljfranklin/terraform-resource#pool-of-environments for an example

**Comment by xtremerui** [comment]
blocked by issue https://github.com/concourse/concourse/issues/6067
