### ISSUE TITLE
Build reaper misses builds if first logged id is after the first page

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5977]
## Summary

The build log collector pagination logic is flawed such that if the number of builds between the `first_logged_build_id` and the most recent build for a job is > 500, it will not reap the `first_logged_build_id`

## Steps to reproduce

1. Set a pipeline with a job that has `build_log_retention.days = 1` (make sure it's the first pipeline to be created - the script to follow relies on job + pipeline + team IDs all being 1)
1. Run the following script:

```sh
# Pause the build reaper
PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "UPDATE components SET paused = true WHERE name = 'reaper';"

# Create 501 builds (1 more than the page size)
for i in `seq 1 501`; do
  PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "INSERT INTO builds(name, status, end_time, job_id, team_id, pipeline_id) VALUES ('$i', 'succeeded', now(), 1, 1, 1);"
done

# Set the end_time of the first build to before 1 day ago
PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "UPDATE builds SET end_time = now() - '2 days'::interval, completed = true WHERE name = '1';"

# Unpause the build reaper
PGPASSWORD=dev psql -h localhost -p 6543 -U dev concourse -c "UPDATE components SET paused = false WHERE name = 'reaper';"
```

## Expected results

Eventually, the first build should get reaped

## Actual results

It never does

## Additional context

The `build-reaper` always logs:
```
web_1     | {"timestamp":"2020-08-11T18:21:06.632844500Z","level":"debug","source":"atc","message":"atc.reaper.tick.build-reaper.after-first-round-filter","data":{"buildsToConsiderDeleting":500,"session":"25.119.2"}}
web_1     | {"timestamp":"2020-08-11T18:21:06.633361400Z","level":"debug","source":"atc","message":"atc.reaper.tick.build-reaper.after-second-round-filter","data":{"retainedBuilds":0,"retainedSucceededBuilds":0,"session":"25.119.2"}}
```

Note how `buildsToConsiderDeleting` is only 500 - it should be 501, I believe

## Triaging info

* Concourse version: 6.3.0
* Browser (if applicable):
* Did this used to work?

**Comment by xtreme-sameer-vohra** [comment]
I assume its specifically broken because the very first call to [getBuildsWithPagination](https://github.com/concourse/concourse/blob/master/atc/db/build_factory.go#L256) ends up going through [this flow](https://github.com/concourse/concourse/blob/master/atc/db/build_factory.go#L272-L274) as `page.Until` is 0. The resulting query is in `DESC` order, which results in build ids that are < (last run build - 500 ) never being reaped.

**Comment by xtreme-sameer-vohra** [comment]
Deleting builds in a DESC ordering might also be related to [pipeline delete deadlock issue](https://github.com/concourse/concourse/issues/5287) issue

**Comment by scottietremendous** [comment]
We might want to backport this for v6.3.x. Let's look into what the effort would be for that.
