### ISSUE TITLE
Containerd runtime has location of Concourse binaries hard-coded for Docker

### ISSUE THREAD

**Issue by andy-paine** [concourse/concourse#5984]
## Summary
The `containerd` runtime has the location of the Concourse `init` binary [hard-coded](https://github.com/concourse/concourse/blob/d0b12f86b6b47320e16a790b2e6b1575f8f6d19d/worker/runtime/spec/mounts.go#L7). This works fine for the containerised Concourse but BOSH places those binaries in `/var/vcap/packages/concourse/bin`.

## Steps to reproduce
1. Deploy Concourse with BOSH, using the `runtime: containerd` (after working around [this issue](https://github.com/concourse/concourse-bosh-release/issues/115)).
1. Try to run a container (I used a `timer` check container)
1. Observe `stat /usr/local/concourse/bin/init: no such file or directory: unknown` errors in check container

## Expected results
Check container finds a new version

## Actual results
`stat /usr/local/concourse/bin/init: no such file or directory: unknown` error is shown and resource goes orange

## Additional context
Symlinking with `ln -sf /var/vcap/packages/concourse/bin /usr/local/concourse/bin` is an ugly but quick way of fixing it but it at least shows that it is just a location problem. This path should probably be configurable though since BOSH will always want to put stuff in `/var/vcap/packages` or `/var/vcap/jobs`

## Triaging info

* Concourse version: concourse-6.4.0+dev.261.d0b12f8.linux-ubuntu.amd64.tgz
* Browser (if applicable): N/A
* Did this used to work? Nope - new feature

**Comment by martin-g** [comment]
Is this released ?
I experience the same error with v6.7.3 (latest available at the moment) ?

**Comment by mpb10** [comment]
@martin-g I believe this is.

I was experiencing the same issue on v6.7.4, but upgrading to 7.4.0 solved it.
