### ISSUE TITLE
set_pipeline step header should indicate whether changes were applied

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6000]
When viewing a build that reconfigures pipelines, it's hard to tell which pipelines were actually changed:

![image](https://user-images.githubusercontent.com/1880/90666449-6b468700-e21b-11ea-95cd-4dd939642a21.png)

Quick suggestion: highlight it in yellow, like the `get` step? Or the opposite - dim steps which had no changes to apply? No strong preference!

This would likely involve emitting an event from the `set_pipeline` step so that the UI can know to highlight the step.

**Comment by matthewpereira** [comment]
We have a highlight-in-yellow approach piggybacking off the get step highlighting in #6011
