### ISSUE TITLE
Build view spacing enhancements

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#6029]
### Current state

![Screen Shot 2020-08-31 at 4 30 58 PM](https://user-images.githubusercontent.com/6372810/91765692-64b6f880-eba7-11ea-9025-ef9d912e4d27.png)

Inspecting the DOM and adding gridlines, we can see that the build log view uses a variety of different spacings and paddings (7px, 12px, 30px, etc). There's room for improvement here.

### Proposed state

By using consistent spacing increments around all of our elements, and lining up the top bar, the build header bar, the build history list, and the build log area, we get a more consistent and orderly view. Icons can be sized more appropriately as well. In these examples the smallest square is 4x4 pixels, S is 8x8 pixels, M is 16x16 pixels, and L is 32x32 pixels:

![Screen Shot 2020-10-09 at 11 11 09 AM](https://user-images.githubusercontent.com/6372810/95600535-4d79ef00-0a20-11eb-9a22-3010cb322108.png)

Here's the same view with emphasis on the grid/spacing:

![Screen Shot 2020-10-09 at 11 18 28 AM](https://user-images.githubusercontent.com/6372810/95601244-2ff95500-0a21-11eb-9847-579d961a8856.png)

Detail on the grid/spacing:
![Screen Shot 2020-08-31 at 4 38 38 PM](https://user-images.githubusercontent.com/6372810/91766448-98dee900-eba8-11ea-969a-51b414e408cc.png)

And finally, a view without gridlines or embellishments:

![Screen Shot 2020-10-09 at 11 11 52 AM](https://user-images.githubusercontent.com/6372810/95600570-5b2f7480-0a20-11eb-82f8-8447556c214d.png)

## Figma mockups

[Mockups are available in Figma to get a detailed look at spacing and alignment](https://www.figma.com/file/fuoFSVcTGptiS21P2POA2XbN/Concourse-UI-kit-and-Experiments?node-id=1675%3A0). Look for the highlighted frames for the target variations.

## Acceptance Criteria

- [ ] Sidebar icon, build header, build list, and build log all have consistent left spacing
- [ ] Small text in build header has appropriate contrast on backgrounds of every possible color/state (success, failure, error, aborted, pending, etc)
- [ ] Items on build history list are 32px tall
- [ ] Build trigger and build retrigger icons have consistent size and padding
- [ ] Build log items have consistent margins and padding
- [ ] Build step icons are 16x16

## Context

* Extension of #5971
* Part of #5964 Web UI/UX Experience

**Comment by vito** [comment]
Nice! Love the attention to detail.

The only thing I'm not a fan of here is the spacing between `get:` and the resource name. It's meant to read like the YAML source code, where the spacing between the `:` and the name is literally just a space character, like `get: resource-name`. So to me it looks weird with extra spacing.

**Comment by matthewpereira** [comment]
Gotcha - I didn't realize they were meant to read as one item. I think the previous icon + text setup threw me off. I've updated the Figma mockup and made new screenshots for the issue above. LMK if that's better.
