### ISSUE TITLE
worker ephemeral disk full (/var/vcap/data) 

### ISSUE THREAD

**Issue by markstokan** [concourse/concourse#603]
We recently converted our custom resource type (https://github.com/pivotal-cf-experimental/cron-resource) to use the new "docker-image-resource" style deployment and within 17 hours the ephemeral disk on our aws-hosted concourse workers filled to 100%.

![screen shot 2016-08-22 at 10 10 42 am](https://cloud.githubusercontent.com/assets/5225342/17904889/f0732956-6925-11e6-818c-61bfde8f5f64.png)

Working with the Concourse team we were able to identify a large number of volumes as being the culprit

```
± ms+gd |master ✗| → fly -t tc volumes | wc -l
    1433
```

However, we could not identify why so many volumes were being created.  We have since reverted back to the bosh-deployed custom resource type and saw the disk usage flat-line.

We have a lot of jobs that use this custom resource type to run every 5, 10, 30 minutes, so our usage pattern is atypical.  We have created a small test pipeline that runs a "hello-world" job every five minutes for your team to use in debugging.

---

resource_types:
  - name: cron
    type: docker-image
    source:
      repository: cftoolsmiths/cron-resource

resources:
  - name: 5-min-trigger
    type: cron
    source:
      expression: "*/5 * * * *"
      location: "America/New_York"

jobs:

- name: hello-world
  plan:
  - aggregate:
    - get: 5-min-trigger
      trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]

**Comment by alext** [comment]
This could be related to #565

**Comment by vito** [comment]
Yeah I think it's the same as #565, which should be fixed by #629
