### ISSUE TITLE
`set-pipeline --var` no longer supports nested keys

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#6041]
## Summary

In upgrading from 6.4.1 to 6.5.1, we saw that our use of `set-pipeline --var` no longer worked. We were previously specifying nested variables like `--var foo.bar=baz` and using them in the pipeline like `((foo.bar))`. However, with the introduction of https://github.com/concourse/concourse/pull/5896, the variable needs to be referred to as `(("foo.bar")`.

## Steps to reproduce

With this config:
```
jobs:
  - name: ((foo.bar))
    plan: []
```

Using fly 6.5.1, set the pipeline: `fly -t ci set-pipeline --pipeline foo --config foo.yaml --var foo.bar=baz`

## Expected results

```
jobs:
  job baz has been added:
+ name: baz
+ plan: []
```

## Actual results

```
jobs:
  job ((foo.bar)) has been added:
+ name: ((foo.bar))
+ plan: []
```

## Triaging info

* Concourse version: 6.5.1
* Did this used to work? Yes, in 6.4.1

**Comment by mouellet** [comment]
@wendorf, https://github.com/concourse/concourse/pull/5896 hasn't been merge yet... I believe this is linked to https://github.com/concourse/concourse/pull/5898.
