### ISSUE TITLE
Compare performance of containerd against Guardian

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#6043]
After phase two feature sets of `containerd` are in it will be useful to have metrics on the containerd's performance against guardian so we can effectively measure the success of the feature set, especially the performance around privileged containers.

Related: https://github.com/concourse/concourse/issues/4358 will help us figure out minimum requirements.

Figuring out a reasonable max container limit for Guardian beyond the default of 250 could be done here as well.

**Comment by DanielJonesEB** [comment]
Might be worth speaking to the PWS team - I think they recently moved over to a ContainerD backend, so maybe there's learnings that can be shared?

**Comment by muntac** [comment]
Closing as there's a duplicate issue #5545
