### ISSUE TITLE
Fly command to list jobs of a pipeline

### ISSUE THREAD

**Issue by Sufyaan-Kazi** [concourse/concourse#605]
I love the UI for Concourse, I also love using terminal. I'd like to be able to track jobs in my pipeline by using the watch command, it would be nice if I could remind myself of the names of jobs in my pipeline using fly, to help me fill in the -j param when using watch, rather than having to open the UI or pipeline.yml or using 'get-pipeline'

**Comment by chendrix** [comment]
Closing as same as #868
