### ISSUE TITLE
Confusing experience with Concourse

### ISSUE THREAD

**Issue by epinault** [concourse/concourse#6055]
## Summary

I created a new pipeline and job. I find the UI very confusing. 
The pause Job vs Pause pipeline in the UI without any label makes it very difficult at first to understand that both need to be unpause the first time.. .

## Steps to reproduce

1. Create a new pipeline and a job

2. go in the pipeline and job then press start
  color change for part of it 

3. go back t pipeline view, and then unpause/start the pipeline , more color change.. But it would be nice to have labels because I would expect start pipeline to start it all or same when I was in the job. 

I admit that I am still quite novice but thought that just adding a little label around the button would help removing the confusion

## Expected results

* more visually clear what happened when you click the button
*. a popup to tell me the "job was started" or "pipeline was started"

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?

**Comment by taylorsilva** [comment]
It's hard for us to get this kind of feedback often, thanks for the sharing! Tagging our designer so he can see it when he gets back from vacation. 
cc: @matthewpereira
