### ISSUE TITLE
Where can I find https://github.com/Pix4D/concourse-pool-boy?

### ISSUE THREAD

**Issue by lxiaopei** [concourse/concourse#6063]
## Summary
Anyone knows where I can find https://github.com/Pix4D/concourse-pool-boy?
I am using concourse pool resource https://github.com/concourse/pool-resource
and sometimes when ensure fails, the lock becomes stale.

I googled and found https://github.com/Pix4D/concourse-pool-boy is to fix this, but the link is broken. Thanks in advance for your help~

name: acquire-1
plan:
put: acquire-pool
params: {acquire: true}
task: BLAHBLAHBLAH
ensure:
put: acquire-pool
params: {release: acquire-pool}

**Comment by taylorsilva** [comment]
Closing because you opened https://github.com/concourse/concourse/discussions/6062 already.
Please don't spam the repo :)
