### ISSUE TITLE
Add job to greenpeace CI pipeline to cleanup deployments

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#6067]
## Summary

Currently greenpeace CI pipeline allows terraform deployments of service accounts, dispatcher and concoruse production, no easy way to clean them up however.

It'd be nice if we could utilize the concourse terraform resource `action: destroy` to remove those deployments. Notice there might be some terraform resource configs are config to be indestructible e.g. https://github.com/concourse/greenpeace/blob/18f6a0014c68fc2937f36540032b2a6a7b29e8c2/terraform/production/vault.tf#L17

We will need to consider the orders of descustrction i.e. production -> discpatcher -> service account to make sure no zombie gcp services are left behind.

The goal should be creating a job that could remove all greenpeace deployments. And running a greenpeace deployment after the cleanup should be successful.

**Comment by aoldershaw** [comment]
https://github.com/concourse/greenpeace/blob/9471d142f3b7593319b9a1e7db61a6902140d281/pipelines/greenpeace.yml#L68-L77
