### ISSUE TITLE
Feature Request: Concourse job changes colour when task has run for a significantly long time

### ISSUE THREAD

**Issue by chewymeister** [concourse/concourse#607]
The PCF-Redis team came across a situation where a test ran for over 2 days waiting for a job to execute, even though we have timeouts present in our test.

We would like to see a configurable multiple that can be provided to a job, e.g. 3x. This multiple will then be applied to the average time of the last 5 job runs and will produce a sensible timeout. When this timeout is reached, the job will not error, but go into a different state `long-running-task`. The colour of this job will change from whatever it's previous state was to purple (or something less egregious).

Thoughts? Questions?

Thanks!

**Comment by jama-pivotal** [comment]
Interesting suggestion. I guess this would be similar to #386 where you could gauge the health of the pipeline
