### ISSUE TITLE
Precedence of `var_files` in the `set_pipeline` step is reversed

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6072]
## Summary

As documented in https://concourse-ci.org/jobs.html#schema.step.set-pipeline-step.var_files:

> if a variable appears in multiple files, the value from a file that is passed later in the list will override the values from files earlier in the list

Instead, the precedence is flipped, so var files appearing earlier take precedence.

Note that the behaviour of `fly set-pipeline`'s `--load-vars-from` works as above (i.e. files specified later take precedence)

## Steps to reproduce

Use the following pipeline definition

```sh
$ cat pipeline.yml
resources:
- name: files
  type: mock
  source:
    create_files:
      var_file_1: "var: from file 1"
      var_file_2: "var: from file 2"
      pipeline.yml: |
        jobs:
        - name: print
          plan:
          - task: print
            config:
              platform: linux
              image_resource:
                type: registry-image
                source: {repository: busybox}
              run:
                path: echo
                args: [START_VARvarEND_VAR]

jobs:
- name: set
  plan:
  - get: files
  - set_pipeline: child
    file: files/pipeline.yml
    var_files:
    - files/var_file_1
    - files/var_file_2
```

1. `fly -t dev sp -p parent -c pipeline.yml`
1. `fly -t dev up -p parent`
1. `fly -t dev tj -j parent/set -w`
1. `fly -t dev tj -j child/print -w`

## Expected results

`child/print` prints:

```
from file 2
```

## Actual results

`child/print` prints:

```
from file 1
```

## Triaging info

* Concourse version: 6.5.1
* Did this used to work? Don't think so

**Comment by vito** [comment]
Is this a duplicate of https://github.com/concourse/concourse/issues/5455?

**Comment by aoldershaw** [comment]
Whoops, yup!
