### ISSUE TITLE
Implement mitigations for stricter Docker Hub rate limits

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6073]
## Summary

Docker Hub will begin enforcing pretty strict rate limits on November 1. ([Announcement.](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/))

The main problem is that the `registry-image` and `docker-image` resource types both make requests during `check` that count towards the rate limit. This means that pipelines will most likely be affected shortly after these new limits take effect. The impact will probably be severe; both resource types retry with exponential backoff but give up after an hour, while the limits are enforced for 6-hour windows.

Tasks which use `image_resource` pointing to an unauthenticated Docker Hub repository will likely start to hang. Same for resource types provided by public images on Docker Hub.

## Context

* Prior discussion: https://github.com/concourse/concourse/discussions/6039

**Comment by d-amit** [comment]
Any update or workaround for this issue?

**Comment by vito** [comment]
Should be able to close this now as v6.7.0 and v6.7.1 were shipped with mitigations:

https://github.com/concourse/concourse/releases
