### ISSUE TITLE
Use HEAD requests in `registry-image` resource checking

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6075]

**Comment by xtreme-sameer-vohra** [comment]
Motivation
---
<img width="1057" alt="Screen Shot 2020-09-17 at 3 26 00 PM" src="https://user-images.githubusercontent.com/1062564/93524504-31d86880-f8fa-11ea-9493-5ed614bd38ac.png">

[Source](https://docs.docker.com/docker-hub/download-rate-limit/)
