### ISSUE TITLE
Discussion: Extract resource storage drivers into reusable library/binary/whatever

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#608]
Many resource authors will have to tackle the problem of storing state. While it isn't too difficult to add a basic S3 client implementation, your users will soon want to use S3-compatible blobstores that require v2 signing + endpoint configuration or server-side encryption + KMS integration. Some users might not even want to use S3 and would prefer store state in something like a GitHub repo. Adding this level of flexibility would require a steep investment for a single resource.

Extracting common "storage" libraries from the existing resources would help release authors get up and running quickly. It would also allow a single PR to benefit all stateful resources rather than a single resource.

**Comment by robdimsdale** [comment]
@ljfranklin what would you like to see as a "library" - what would your interface be? A API in a specific language? Multiple languages? A binary interface? Files on the filesystem?

**Comment by ljfranklin** [comment]
@robdimsdale good question, don't really know what the best approach would be. Reworded the title to be a bit more open-ended. My main goal was to call attention to the amount of duplicate effort going on across resources relating to S3 features and to see if anyone else was feeling pain around missing S3 features like v2 signing or server-side encryption in resources.
