### ISSUE TITLE
Deleting pipeline deadlocking.. again!

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#6090]
## Summary

We previously fixed a common deadlocking issue with deleting a pipeline and deleting of build events happening at the same time https://github.com/concourse/concourse/issues/5287. On our large deployment `hush-house`, we saw that many of the DB metrics were under heavy load so I poked into the database to see what could be causing it.

![Screen Shot 2020-09-28 at 2 26 36 PM](https://user-images.githubusercontent.com/19290703/94497437-325be380-01c5-11eb-9d6b-f6f0d6bf4963.png)
![Screen Shot 2020-09-28 at 2 26 32 PM](https://user-images.githubusercontent.com/19290703/94497438-338d1080-01c5-11eb-8669-dae4ac358e6d.png)
![Screen Shot 2020-09-28 at 2 26 26 PM](https://user-images.githubusercontent.com/19290703/94497439-338d1080-01c5-11eb-9906-a9ddd859664c.png)

I ran the query to find all the current running queries and I noticed these queries that have been running for hours.
![Screen Shot 2020-09-28 at 2 24 57 PM](https://user-images.githubusercontent.com/19290703/94497440-3425a700-01c5-11eb-8b30-5bacfa3037cc.png)

I suspected that the query to update the `schedule_requested` field on the jobs table could be causing a deadlock with the deleting of the pipeline. This is because updating the `schedule_requested` field is done in a transaction where we loop over all the jobs that need to be updated and if the order that it needs to update the jobs in is different than the order that the pipeline is trying to delete it's jobs, this can cause a deadlock.

https://github.com/concourse/concourse/blob/95a40195a507ca058549a0eb7e7a4b52e703706e/atc/db/resource_config_scope.go#L353-L364

After I cancelled the query to update the `schedule_requested`, after about 10 minutes I saw the number of queries for deleting the pipeline reduce to 2. After I checked back in a 2 hours, I saw the queries were all finished and the db metrics were back to normal.

## Expected results

No deadlock occurs.

## Actual results

A possible deadlock occurs.

## Additional context

I'm thinking we might want to think about setting a `lock_timeout` or something similar for when we try to destroy a pipeline. I'm worried there might just be many different places that we can run into this. We could try to completely solve it by having concourse always delete things in the same order.

https://www.postgresql.org/docs/9.3/runtime-config-client.html

## Triaging info

* Concourse version: 6.5
* Browser (if applicable):
* Did this used to work?

**Comment by clarafu** [comment]
We saw this happen again in `hush-house`, we tried cancelling the queries again but the deleting of pipeline queries were still taking really long. @vito pointed out that this can possibly not be a deadlock situation, but rather that the pipeline deletion queries were just taking a really long time. The slowness with pipeline deletion might have been introduced as a regression with v6.0 with the `successful_build_outputs` table but adding this index 

https://github.com/concourse/concourse/blob/1746cf68a49e35fde96f8b7ecde873b517abf2f4/atc/db/migration/migrations/1601993582_add_successful_build_outputs_rerun_of_index.up.sql#L1-L3

should speed up the deletion. We tried adding it to `hush-house` and it seemed to cause the rest of the pipeline deletion queries to succeed quickly.

I'm going to close this issue for now because we are not sure if it was really a deadlock situation or not. And the index should solve the problem of deleting pipeline queries causing db CPU to spike.

**Comment by avanier** [comment]
Just pinging. I think I'm experiencing this issue or _"something"_ related to this. We're running an equivalent of concourse/oxygen-mask and we flush the pipeline of the fake jobs on a regular basis. We've had two instances since upgrading to 6.7 from 6.3 in the past two months where deleting this pipeline with a very large number of builds caused either _ATC_ or `postgres` to lock up.
