### ISSUE TITLE
fly pin-resource fails without error

### ISSUE THREAD

**Issue by scottillogical** [concourse/concourse#6094]
## Summary

Attempting to pin a resource via the concourse UI is successful.  
Using the fly cli though, I am not able to 

## Steps to reproduce
1. Attempt to pin a resource with the CLI 
2. Observe it does not work
3. Observe it does work if pinned via UI
```
➜  concourse git:(master) ✗ fly -t zc-carsharing-dev pin-resource -r scott/deployment-manifests
➜  concourse git:(master) ✗
➜  concourse git:(master) ✗ fly -t zc-carsharing-dev resources -p scott
name                  type  pinned
deployment-manifests  git   n/a
```

## Expected results
Resource is pinned

## Actual results

Resource is not pinned, operation is a no-op
I didn't see anything in the logs at all really when tailing the logs while attempting this operation

## Triaging info

* Concourse version: v6.5.1
* Did this used to work? didn't work on 5.x either

**Comment by jamieklassen** [comment]
the real bug here is that fly should error out if you try to pin a resource without a version!
