### ISSUE TITLE
Badges "not authorized" in v2.0

### ISSUE THREAD

**Issue by drnic** [concourse/concourse#610]
http://engineering.pivotal.io/post/concourse-badges/ came out just in time for v2.0, where the API and authorization changed.

I guessed that I need to include `/teams/main` in the URL; but when I try to get the badge for a public job I get:

```
$ curl -k https://ci.vsphere.starkandwayne.com/api/v1/teams/main/pipelines/dingo-postgresql-release/jobs/rc/badge
not authorized
```

A bug in new teams; or something I need to enable to support public badges?

/cc @cunnie

**Comment by vito** [comment]
Seems OK for me: https://ci.concourse.ci/api/v1/teams/main/pipelines/main/jobs/atc/badge

Make sure you've run `expose-pipeline` for the pipeline to be public.

Also: I completely forgot about the badge API endpoint; we probably should've at least kept that working. Crap.

**Comment by drnic** [comment]
Awesome. expose-pipeline did the trick






On Mon, Aug 29, 2016 at 11:44 AM +1000, "Alex Suraci" <notifications@github.com> wrote:












Seems OK for me: https://ci.concourse.ci/api/v1/teams/main/pipelines/main/jobs/atc/badge



Make sure you've run expose-pipeline for the pipeline to be public.



Also: I completely forgot about the badge API endpoint; we probably should've at least kept that working. Crap.

**Comment by emcniece** [comment]
Is there any way to have public badges for private pipelines?

**Comment by mbana** [comment]
^ just wondering if anyone has a workaround for this.

is there a view-only mode so if one does decide to make it public, others can't start a build or some operation that modifies that state in any way?

**Comment by emcniece** [comment]
@mbana nope, nothing official yet.

I made a deploy job that pushes the badges to an S3 bucket as a workaround 😅

**Comment by cunnie** [comment]
@mbana I use [`expose-pipeline`](http://concourse-ci.org/fly-expose-pipeline.html) but require auth to trigger a build, which allows people to see my badges but they can't view any job outputs or trigger builds or anything (read-only, with a limited read)

For example, if you browse to https://ci.nono.io/ you can see my Concourse server and if you browse to https://sslip.io/ you can see the badge being displayed, but you won't be able to trigger a build or see job output without logging in first. I believe that's what you're looking for.  Here's my Concourse manifest: https://github.com/cunnie/deployments/blob/69116c060e1bc9ce72e168bdbc55709546bf14aa/concourse-ntp-pdns-gce.yml#L29

**Comment by mohsen0** [comment]
The option to only expose the badge publicly would have made this feature useful

**Comment by vito** [comment]
@mohsen0 Good point. I think that should probably be opened as a new issue though. Comments on resolved issues tend to not go anywhere.

**Comment by apolegoshko** [comment]
Why it close ? And will it be implemented ?

**Comment by taylorsilva** [comment]
@apolegoshko I think #5252 fixes this

**Comment by apolegoshko** [comment]
@taylorsilva 👍

**Comment by itsouvalas** [comment]
> @mbana I use [`expose-pipeline`](http://concourse-ci.org/fly-expose-pipeline.html) but require auth to trigger a build, which allows people to see my badges but they can't view any job outputs or trigger builds or anything (read-only, with a limited read)
> 
> For example, if you browse to https://ci.nono.io/ you can see my Concourse server and if you browse to https://sslip.io/ you can see the badge being displayed, but you won't be able to trigger a build or see job output without logging in first. I believe that's what you're looking for. Here's my Concourse manifest: https://github.com/cunnie/deployments/blob/69116c060e1bc9ce72e168bdbc55709546bf14aa/concourse-ntp-pdns-gce.yml#L29

Heya there @cunnie, great workaround you got there. I understand its been quite sometime since your update, but, is there a chance you could elaborate further on what yielded the user experience demonstrated?

That said +1 on the thread/feature 😃

**Comment by cunnie** [comment]
@itsouvalas :

> Heya there @cunnie, great workaround you got there. I understand its been quite sometime since your update, but, is there a chance you could **elaborate further on what yielded the user experience demonstrated**?

I would say that typing the command yielded the user experience demonstrated:

```
fly -t nono expose-pipeline -p sslip.io
```

**Comment by itsouvalas** [comment]
Thanks for the update @cunnie! I must have mixed it up with the _401 Unauthorized_ you get from [u2date-integration](https://ci.nono.io/teams/main/pipelines/u2date/jobs/integration/builds/1). [sslip.io](https://ci.nono.io/teams/main/pipelines/sslip.io) still has unit and dns-servers... unless there is more to it and it is hidden from plain sight, though `fly -t nono expose-pipeline -p sslip.io` alone I'm (almost) certain doesn't do that...

**Comment by cunnie** [comment]
> ... _401 Unauthorized_ you get from [u2date-integration](https://ci.nono.io/teams/main/pipelines/u2date/jobs/integration/builds/1).

Yeah, u2date is a weird pipeline because it only has 1 job, so browsing to the pipeline brings you to that one job, which you can't see any output because although I've exposed the pipeline, I haven't made the jobs public.

Here's the URL to retrieve the badge for u2date pipeline: <[401 Unauthorized you get from [u2date-integration](https://ci.nono.io/teams/main/pipelines/u2date/jobs/integration/builds/1).](https://ci.nono.io/api/v1/teams/main/pipelines/u2date/jobs/integration/badge)>
