### ISSUE TITLE
2.0.0 Web UI doesn't really work with Safari

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#611]
Tried browsing to pipelines in Safari, and no diagrams were rendered of the pipeline, just empty screens. When I view individual jobs, the top bar gets hidden, until i click the logout option, and then deselect it, at which point it kind of shows up, but the CSS is still weird.

Seems like there might be an issue with CSS validation on Safari?

`Unexpected css token: :` on a bunch of lines in `main.css`

<img width="1882" alt="concourse-css" src="https://cloud.githubusercontent.com/assets/7180882/18056725/21ab6cb8-6ddb-11e6-95bf-287cd85bd5ed.png">

**Comment by drnic** [comment]
I see this issue on iOS Chrome






On Tue, Aug 30, 2016 at 1:37 AM +1000, "Geoff Franks" <notifications@github.com> wrote:












Tried browsing to pipelines in Safari, and no diagrams were rendered of the pipeline, just empty screens. When I view individual jobs, the top bar gets hidden, until i click the logout option, and then deselect it, at which point it kind of shows up, but the CSS is still weird.



Seems like there might be an issue with CSS validation on Safari?



Unexpected css token: : on a bunch of lines in main.css

**Comment by databus23** [comment]
@drnic Chrome on iOS uses `UIWebView` so its practically the same as Safari on iOS. See: https://developer.chrome.com/multidevice/ios/overview
