### ISSUE TITLE
Self-Signed certificate and UAA/CF

### ISSUE THREAD

**Issue by shinji62** [concourse/concourse#613]
Hi,

I try to set a team using _pcfdev_ which use a self-signed certificate, I am using this command

``` bash
fly -t docker set-team -n gwenn-concourse-https --uaa-auth-client-id concourse --uaa-auth-client-secret concourse-secret --uaa-auth-auth-url https://login.local.pcfdev.io/oauth/authorize --uaa-auth-token-url https://login.local.pcfdev.io/oauth/token --uaa-auth-cf-space e6167107-d2a5-478d-a5c4-27222d595fcd --uaa-auth-cf-url https://api.local.pcfdev.io --uaa-auth-cf-ca-cert ./cert/cf.pem
```

Actually this failed with this log 

``` json
{"timestamp":"1472518233.028209448","source":"atc","message":"atc.oauth-callback.callback.failed-to-exchange-token","log_level":2,"data":{"error":"Post https://login.local.pcfdev.io/oauth/token: x509: certificate signed by unknown authority (possibly because of \"x509: invalid signature: parent certificate cannot sign this kind of certificate\" while trying to verify candidate authority certificate \"*.local.pcfdev.io\")","session":"11.2"}}
```

_pcfdev_ certificate is self-signed and there is no root certificate https://github.com/pivotal-cf/pcfdev/blob/master/assets/scripts/run#L36

It seems Go do not like this kind of certificate https://golang.org/src/crypto/x509/x509.go#L642

Workaround is to not use `https` or creating certifcate using a rootCA

**Comment by shinji62** [comment]
Could be nice to have a switch like "--uaa-auth-ignore-ssl-validation" or something like that.

**Comment by vito** [comment]
Would rather not skip SSL validation. You sure the cert was formatted correctly? Is it the same cert for both CF and UAA? Maybe we need a flag for that? I'm not sure if we use the same cert for both UAA and CC.

**Comment by cf-identity** [comment]
Getting a similar error , and we used to have a `-k` option in earlier releases, but adding -k yields unknown flag.

     fly -t identity-ci login
     could not reach the Concourse server called identity-ci:

      Get https://identity.ci.cf-app.com/api/v1/info: x509: certificate signed by unknown authority

     is the targeted Concourse running? better go catch it lol

**Comment by mvdkleijn** [comment]
@vito The issue lies in "self-signed". Even if the cert is correctly formatted, etc., Concourse would either need to add the self-signed cert to its trust store, or as @shinji62 suggested it should skip validation. Not really a bug either I guess unless you consider not taking self-signed certs into account as a bug.

**Comment by vito** [comment]
It shouldn't matter if it's self-signed. Self-signed just means the CA for the cert is the cert itself, so it should be possible to just pass it as the `--uaa-auth-cf-ca-cert` flag.

Make sure the certificate was generated with the `CA` flag set to `true`.

**Comment by akamalov** [comment]
So, what's the workaround here?  What is it I can do get this thing to work?
