### ISSUE TITLE
column for memory consumption

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#6140]
a garden client has the method

https://github.com/cloudfoundry/garden/blob/62470dc86365fb365be099df5c4b59650d695c4b/client/client.go#L63

which returns a

https://github.com/cloudfoundry/garden/blob/62470dc86365fb365be099df5c4b59650d695c4b/container.go#L239-L252

Let's grab some interesting memory numbers (experiment with this) and put them in the CLI output.

**Comment by jamieklassen** [comment]
Interesting formula for `TotalUsageTowardLimit`:

https://github.com/cloudfoundry/guardian/blob/b48a5e072ce3a7feabcbd93f31573abfeeba9c25/rundmc/runrunc/stats.go#L97

**Comment by jamieklassen** [comment]
from https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

> 5.5 usage_in_bytes
> 
> For efficiency, as other kernel components, memory cgroup uses some optimization
to avoid unnecessary cacheline false sharing. usage_in_bytes is affected by the
method and doesn't show 'exact' value of memory (and swap) usage, it's a fuzz
value for efficient access. (Of course, when necessary, it's synchronized.)
If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP)
value in memory.stat(see 5.2).

**Comment by cirocosta** [comment]
w/ regards to what to pick: for Go at least, it's worth considering "working set" (i.e. usage - inactive) as that'll give a more accurate view of what's really used (as `M_ADVISE`, used during Go's "free"s will .. just advise 😁 ) 

`cadvisor` reports that in a metric on its own, but it's ultimately derived from `usage` - `inactive`. 

- some details on `m_advise`: https://github.com/concourse/concourse/issues/4861
- cadvisor implementation https://github.com/google/cadvisor/blob/90f391fddf71801f76f408d8ed191ddc006df323/container/libcontainer/handler.go#L862-L870

**Comment by jamieklassen** [comment]
@cirocosta thanks for the info! This is a more challenging subject than i realized. It sounds like you're talking about how to measure memory consumption specifically for containers running Go programs - is that right? Potentially a container running a JVM would have different suitable measurements?

**Comment by cirocosta** [comment]
@jamieklassen np! I'm no expert on this, but I *think* the answer is the classic "it depends" - let me expand on it.

If the goal is to see how close one is to hit the cgroup's OOM, then usage is what matters at the end of the day (as, IIRC, cgroup page accounting is made towards the same counter that reports `memory.usage_in_bytes`, and failing to charge that counter is what triggers OOM if no swap is available).

buuut, if the language runtime does `free`s memory in a way that's similar to Go where it just advises that it doesn't need the memory, but doesn't necessarily gives it completely back to the system, looking at `usage` makes one think that the program is just never releasing memory sporadically allocated (e.g., there's a spike from 100MB to 1GB and then it never comes back to 100MB, even though that other 0.9GB is "inactive") - what other runtimes / memory allocators do that? that I really don't know 🤷‍♂️ 

to be fair, if the goal is to know if an application is properly behaving memory wise, it'd be safer to actually look at the runtime metrics (e.g., go exports heap alloc etc, and so does the jvm)

I hope that makes sense 😁

**Comment by jamieklassen** [comment]
@cirocosta totally! I thought about making exactly the distinction you just did but decided against it -- but since we're here: If you're an "operator" and you treat your concourse workloads as black boxes, then the amount of memory requested by a container is what you're concerned with, regardless of whether that corresponds with actual "space complexity" in the program it's running.

If you actually wanted to provide "useful performance profiling" for concourse containers, then I think we'd be in the world where you would want to use something like the profiling tools/metrics available for the specific runtime that the task is using.
