### ISSUE TITLE
Web UI seems to be stripping tab characters in 6.6.0

### ISSUE THREAD

**Issue by jghiloni** [concourse/concourse#6149]
## Summary

After upgrading to 6.6.0 this morning, we found the build history of a job that creates a tab-based text table to not be very tabular anymore.

## Steps to reproduce

Create a task whose output has tab characters in it

## Expected results

The tabs would be there

## Actual results

The tabs are not there

## Additional context

Screenshot of job pre-6.6.0:
![image](https://user-images.githubusercontent.com/1834264/95768137-164f4c00-0c73-11eb-9139-624b275b91c3.png)

Screenshot of same job at 6.6.0:
![image](https://user-images.githubusercontent.com/1834264/95768323-5f070500-0c73-11eb-9ebe-c40949cdf712.png)

## Triaging info

* Concourse version: 6.6.0
* Browser (if applicable): Chrome
* Did this used to work? Yes

**Comment by analytically** [comment]
Seeing the same in our Terraform pipelines.

**Comment by vito** [comment]
Likely culprit: https://github.com/concourse/concourse/commit/646c8dc62e8f0062763c8fff28c14722b4a47d23

**Comment by mtharrison** [comment]
Also seeing this with spaces too. Confirmed that that CSS rule does seem to be the culprit indeed @vito as you can see below: 
![whitespace](https://user-images.githubusercontent.com/916064/96008714-c077d100-0e37-11eb-92f3-ed799b3c0b52.gif)
