### ISSUE TITLE
Expose team name as environment variable for resources.

### ISSUE THREAD

**Issue by joharohl** [concourse/concourse#616]
Currently, the team name of the build is not available in the in/out step of a resource. For many resources (especially notifications) this would be of great help.

**Comment by geofffranks** [comment]
+1

**Comment by geofffranks** [comment]
Actually, just looked through the code to see how hard it would be to fix.. it appears to already be there, and exposed as `BUILD_TEAM_NAME`. Can this be closed? Do there need to be additional documentation updates somewhere?

**Comment by vito** [comment]
It's documented here; this can be closed: https://concourse.ci/implementing-resources.html#resource-metadata

Thanks for checking in!
