### ISSUE TITLE
$ATC_EXTERNAL_URL includes incorrect team name

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#617]
In v2.0.1, the `$ATC_EXTERNAL_URL` variable always ends with `/teams/main` regardless of the actual team name.  The URL should end with the name of the team that owns the job that the value is passed to.

**Comment by vito** [comment]
Huh, that's pretty wack. It shouldn't have *any* team in it. See https://github.com/concourse/concourse/issues/616

**Comment by vito** [comment]
I'm not actually seeing it end with `/teams/main`. Where're you seeing that?

```
~/w/c/s/g/c/atc (master) $ fly -t ci i -c main/concourse -- env
ATC_EXTERNAL_URL=https://ci.concourse.ci
RESOURCE_PIPELINE_NAME=main
RESOURCE_NAME=concourse
TERM=screen-256color
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
USER=root
HOME=/root
```

**Comment by nebhale** [comment]
Ah no, you're right.  I was looking at URL after the `/teams/main` redirect.

**Comment by nebhale** [comment]
Closing in lieu of #616
