### ISSUE TITLE
6.6.0 does not ship /var/gdn/assets while it requires an update

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#6179]
## Summary

Updating the native concourse (non container, non bosh) worker node to 6.6.0 causes one to run into the publicly denoted breaking change https://github.com/concourse/concourse/releases/tag/v6.6.0 which is only mentioning bosh deployments, but not the binary one.

## Steps to reproduce

Run worker v6.3.1 or v6.5.0 and update. Run into the mentioned error. Due to lack of information assume those would be auto re-generated and wipe the folder.
Be stuck with the option to downgrade.

## Expected results

Regenerate /var/gdn (it's in var after all!) on restart OR ship for _all_ releases on breaking changes.

## Actual results

Be stuck with a non-functional concourse.

After a 6.6.0 update:

> See release notes first entry

Without the files 

```
fly -t spearow trigger-job -j cargo-spellcheck/pr-validate -w
started cargo-spellcheck/pr-validate #389

selected worker: cabin
selected worker: lemonaid
selected worker: cabin
runc state: runc: fork/exec /var/gdn/assets/linux/bin/runc: no such file or directory: 
runc state: runc: fork/exec /var/gdn/assets/linux/bin/runc: no such file or directory: 
runc state: runc: fork/exec /var/gdn/assets/linux/bin/runc: no such file or directory: 
```

With the files copied back on 6.5.1
```
runc run: exit status 1: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write c 5:1 rwm to devices.allow: write /sys/fs/cgroup/devices/system.slice/garden.service/garden/e96f42a6-1696-42af-4f1a-ddefdf028542/devices.allow: operation not permitted\\\"\""
```

## Triaging info

* Concourse version: 6.6.0
* Did this used to work? Yes

**Comment by drahnr** [comment]
Related issue with 6.3.0 https://discuss.concourse-ci.org/t/cent-os-8-issues-dadoo-no-such-file-or-directory/2316

**Comment by drahnr** [comment]
Note that downgrading to `6.5.1` (both worker and web) and copying the `/var/gdn` dir from another worker made the worker recover after a restart of the bare metal machine. Just copying and downgrading the worker was not enough, not sure which of the other changes resolved it finally.

**Comment by drahnr** [comment]
Reading the release notes of 6.7.2 this is related to #6236

**Comment by vito** [comment]
Ah, yep I think this can be closed now. The fix we implemented is to just remove `/var/gdn/assets` on start, so it should get generated fresh from now on. Thanks for the report!

**Comment by drahnr** [comment]
I just tested `6.7.2` and the issue is not resolved.
