### ISSUE TITLE
Add switch to bosh manifest to set up MTU clamping on workers

### ISSUE THREAD

**Issue by manno** [concourse/concourse#618]
We ran into MTU problems with our infrastructure. Setting the MTU for garden (https://github.com/concourse/concourse/issues/551) was not enough to fix our networking issues completely. Git clone was still extremely slow and certain downloads would not work at all. 

After reading https://github.com/docker/docker/issues/22028 we were able to fix the problem by adding the MTU clamping firewall  rule into the forward chain on all workers:

`sudo iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu`

Git clone is now at least twice as fast as before and all hosts can be reached. The MTU inside the container is not that important anymore, packages are adjusted to the detected path MTU when leaving the worker.

However there seems to be no way to make this permanent, for example by adding it to the BOSH manifest. It seems wrong to manually tweak the workers after deployment.

What do you think, would it make sense / be possible to add support for a 'clampMTU' switch to the manifest?

**Comment by vito** [comment]
I really wouldn't want this in Concourse itself; it seems like more of a Garden concern. Maybe open an issue on https://github.com/cloudfoundry/guardian?

There's a discussion going on at https://github.com/docker/docker/issues/22297 that makes me a bit skeptical of the change.

**Comment by vito** [comment]
(Thanks for the follow-up, though.)
