### ISSUE TITLE
Size of pipeline overspills for many concurrent jobs

### ISSUE THREAD

**Issue by nderjung** [concourse/concourse#6182]
## Summary

<img width="613" alt="image" src="https://user-images.githubusercontent.com/905927/96617152-8b6df180-1303-11eb-8fce-d7252334a885.png">

## Steps to reproduce

In the image above, I am trying to run 12 concurrent jobs.

## Expected results

"click" to be the same size as, in the above image, "lib-test".

## Actual results

N/A.

## Additional context

N/A.

## Triaging info

* Concourse version: v6.6.0
* Browser (if applicable), problem exists in the following browsers:
  - Firefox, 81.0.2 (64-bit)
  - Safari, 14.0 (15610.1.28.1.9, 15610)
* Did this used to work? N/A

**Comment by aoldershaw** [comment]
This isn't really a bug - this was a deliberate design decision. The cards can even grow to 3x the height (and width) of `lib-test` if the number of jobs (or depth of job dependencies) exceeds 24

https://github.com/concourse/concourse/blob/0e8560d9b2ca285870a752a43fa0954642ac7297/web/elm/src/Dashboard/PipelineGrid/Layout.elm#L16-L26

For pipelines with a ton of concurrent jobs, we've found that the 1x height makes it very difficult to see what's going on.

Going to close this, but if you disagree with the design decision, feel free to re-open this as a GitHub Discussion.

**Comment by nderjung** [comment]
Hi, should two boxes still not fill the space in which case?  Since it creates unused space:

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/905927/100160323-a22dd800-2eaf-11eb-98e6-c6ec1a0de219.png">
