### ISSUE TITLE
Discussion: I'd like all my pipelines to be public, but it's easy to forget to run `expose-pipeline`

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#619]
Capturing a convo from Slack: https://concourseci.slack.com/archives/general/p1472662539001002
## Context

We're an open-source team and we'd like all our pipelines to be public so we can link to them on GitHub. With the Concourse v2.0.0 release, pipelines are hidden by default. You can run `expose-pipeline` to make them visible, but this seems easy to forget as most users will be logged in most of the time.
## Discussed possibilities
- Add a `pipelines_viewable_by_default` property to invert the default behavior
  - @vito is not a fan: https://concourseci.slack.com/archives/general/p1472662616001003
- Add an icon next to the pipeline name indicating hidden or visible - 👁

cc @kimeberz

**Comment by geofffranks** [comment]
What about adding a per-pipeline flag to the pipeline manifest to allow public visibility of just that pipeline? Something similar to the job-level `public: true`, but for the whole pipeline itself

**Comment by marco-m** [comment]
Resource [concourse-pipeline-resource](https://github.com/concourse/concourse-pipeline-resource) just got merged [PR 49](https://github.com/concourse/concourse-pipeline-resource/pull/49) which introduces the `exposed` flag. This allows to obtain the behavior requested.
