### ISSUE TITLE
Remove : char from certain field names in atc.audit logs

### ISSUE THREAD

**Issue by VigneshVRP** [concourse/concourse#6193]
## Steps to reproduce

1. Set CONCOURSE_ENABLE_SYSTEM_AUDITING=true 
2. Use fly set-pipeline to make changes to a pipeline
3. A log event is generated like - Oct 21 19:53:46 concourse-web-stage-abc concourse-web[1111]: {"timestamp":"2020-10-21T19:53:46.953938877Z","level":"info","source":"atc","message":"atc.audit","data":{"action":"SaveConfig","parameters":{":pipeline_name":["test-pipeline"],":team_name":["test"]},"user":"testuser"}}
4. The ":pipeline_name" and ":team_name" fields have a : in front of them

## Expected results
These 2 fields should just be "pipeline_name" and "team_name"

## Actual results
These 2 fields have a : in front of them

## Triaging info

* Concourse version: 6.5.1
* Browser (if applicable):
* Did this used to work?
6.3.0 also had the same issue. Haven't checked before that.

**Comment by jamieklassen** [comment]
I'm having trouble understanding why you consider this a bug -- was there a version of concourse prior to 6.3.0 where these fields _didn't_ have the colons in the logs? do you have some system consuming these logs that can't handle the colons?
