### ISSUE TITLE
git and gist resources have perl warnings

### ISSUE THREAD

**Issue by jbayer** [concourse/concourse#62]
using the @drnic examples, the git resource now outputs some perl warnings about the locale. happens with the gist as well.

```
Cloning into '/tmp/build/src'...
e8c6632 Added trigger: true to autostart both jobs after update.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by drnic** [comment]
Hmm all those warnings were fixed in more recent concourse




Perhaps look in the Vagrantfile - I might be fixing the base box version to ensure I can guarantee the tutorials work. Try changing to a newer version of Concourse. I don't believe there are any recent regressions.

**Comment by jbayer** [comment]
i almost certain i'm using concourse 0.54.0, i issued a `vagrant box update` before `vagrant up` and it does list several boxes.

@vito is there a way i can confirm on the file system of the vagrant box which version of concourse is being used?

**Comment by jbayer** [comment]
resolved when i for sure used the right box.
