### ISSUE TITLE
`fly sync` requires login when using basic auth

### ISSUE THREAD

**Issue by voelzmo** [concourse/concourse#621]
Seems like you cannot `fly sync` without having done `fly login` first, when concourse is configured with basic auth. That's pretty bad when switching from a 2.x concourse to a 1.x with basic auth: You cannot do `fly login`, because the path has changed. You cannot do `fly sync` because you are not logged in.

### Steps to reproduce
* Have a concourse 2.x, do `fly sync` to get the newest CLI
* Have a concourse 1.x with basic auth
* Try to `fly sync` with the 1.x concourse

### Expected
* It works(tm)

### Actual
* Cannot `fly sync` because not logged in
* Cannot `fly login` because new fly CLI has different URL to login

**Comment by vito** [comment]
I'm guessing you mean `login` first so that the target is saved - not because it requires auth? The `sync` endpoint should be wide open.

**Comment by voelzmo** [comment]
This is what's happening to me:
```
$ fly targets
name         url                             expiry
a  http://<redacted>:8080        Tue, 02 Aug 2016 09:53:08 UTC
b      http://<redacted>:8080       Tue, 30 Aug 2016 07:27:44 UTC
local        http://192.168.100.4:8080       n/a
production   https://<redacted>.com  Fri, 02 Sep 2016 06:41:32 UTC

mv at WDFM32386574A in ~/workspace/bosh on develop [!?]
$ fly -t b sync
not authorized. run the following to log in:

    fly -t b login
```

**Comment by vito** [comment]
how old is the instance you were trying to sync from? it may be before we
opened up the endpoint. if so there's not a lot we can do; sync is the
intended way out

**Comment by voelzmo** [comment]
I edited this in the above comment: the target I'm `fly sync`ing to is on 1.6.0
That's pretty recent to me :)

**Comment by vito** [comment]
Kind of a bummer that this didn't work, but there's not a whole lot we can do about it *now* since it's affected by versions that have already shipped. I'll keep it in mind for the future though; we should start doing upgrade testing and ensuring you can `fly sync` in both directions.

Thanks for the report!

**Comment by voelzmo** [comment]
Sounds like a reasonable test case to me. Thanks for keeping an eye on this in the future!
