### ISSUE TITLE
Build failures when CI is deployed with containerd

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#6246]
## Summary

Recently, the CI environment used by core Concourse team was redeployed with `containerd` enabled as were the workers used for testing PRs.

Several jobs failed with errors that went away when we switched back to Guardian.

1. [Postgres errors](https://ci.concourse-ci.org/teams/contributor/pipelines/prs/jobs/unit/builds/1179) when running unit tests

```
[e][initdb] initdb: removing contents of data directory "/tmp/concourse-pg-runner/postgres139775784"

createdb: could not connect to database template1: could not connect to server: No such file or directory

	Is the server running locally and accepting

	connections on Unix domain socket "/tmp/.s.PGSQL.5435"?


[e][postgres] 2020-11-03 22:09:57.856 UTC [39428] LOG:  database system was not properly shut down; automatic recovery in progress

[e][postgres] 2020-11-03 22:09:57.859 UTC [39428] LOG:  redo starts at 0/164E518

[e][postgres] 2020-11-03 22:09:57.872 UTC [39445] FATAL:  the database system is in recovery mode

psql: FATAL:  the database system is in recovery mode
```

```
/tmp/build/0df9eea0/concourse/atc/postgresrunner/postgresrunner.go:297

```

2. [OOM Score Error](https://ci.concourse-ci.org/teams/contributor/pipelines/prs/jobs/containerd-integration/builds/1098) In `containerd-integration`

```
starting task: new task: io.containerd.runc.v2: failed to adjust OOM score for shim: set shim OOM score: write /proc/4105/oom_score_adj: invalid argument
```

3. [Docker build failure](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/dev-image/builds/603)

```
#5 2.727 container_linux.go:367: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: mkdir /sys/fs/cgroup/cpuset/buildkit: read-only file system
```

## Triaging info

* Concourse version: 6.7.1 (for PR workers), custom for CI (checks as builds on)
* Browser (if applicable):
* Did this used to work?

**Comment by aoldershaw** [comment]
For 1., it's worth noting that the logs are riddled with `no space left on device`, e.g.

```
[o][initdb] running bootstrap script ... [e][initdb] 2020-11-03 22:09:49.289 UTC [39198] FATAL:  could not write to file "pg_wal/xlogtemp.39198": No space left on device
```

I hijacked into the container, and checked the mounts:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         738G   22G  716G   3% /
overlay          49G   11G   38G  23% /tmp/gdn-init
tmpfs            64M     0   64M   0% /dev
shm              64M   24K   64M   1% /dev/shm
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
tmpfs            64M     0   64M   0% /run
/dev/sdb        738G   22G  716G   3% /scratch
overlay         738G   22G  716G   3% /tmp/build/0df9eea0/concourse
tmpfs            64M     0   64M   0% /dev/tty

$ df -h /tmp/concourse-pg-runner
Filesystem      Size  Used Avail Use% Mounted on
shm              64M   24K   64M   1% /dev/shm
```

The `shm` mount is pretty small. It looks like we're actually explicitly setting it to that size: https://github.com/concourse/concourse/blob/a0b6080b84c21c83ca28a38ed98042bd9775408c/worker/runtime/spec/mounts.go#L31

We do the same with some other mounts. Guardian, however, does not:

https://github.com/cloudfoundry/guardian/blob/3da697a62154c6d1f797aede3a0fb23f2297e6cd/guardiancmd/command_linux.go#L199-L226

Not sure why we're setting `size=65536k` in the first place...

**Comment by muntac** [comment]
Seems like folks in the community were already running into #3 - https://github.com/vito/oci-build-task/issues/38

**Comment by muntac** [comment]
After setting the OOM score for the base containerd to -999 @aoldershaw and I saw the following error on the containerd integration test:
```
=== CONT  TestSuite

    integration_test.go:220: 

        	Error Trace:	integration_test.go:220

        	Error:      	Not equal: 

        	            	expected: 1

        	            	actual  : 0

        	Test:       	TestSuite

=== CONT  TestSuite/TestContainerNetworkEgress

    testing.go:1048: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```

**Comment by muntac** [comment]
Looks like the idea of setting the `/dev/shm` size to `65536k` may have come from [here](https://github.com/containerd/containerd/blob/4cd5de74bd0ba0179a9fec15135c0d5170df5070/oci/spec.go#L187).

**Comment by scottietremendous** [comment]
Let's check back into this once we unpause CI.

**Comment by xtremerui** [comment]
CI is back to normal @muntac .
