### ISSUE TITLE
Dashboard Redirects to 127.0.0.1:8080 on /login resulting in 404

### ISSUE THREAD

**Issue by darktempla** [concourse/concourse#6250]
## Summary

When installing via the helm chart concourse CI gets up and running no problem.
I can port forward (port: **8082** -> 8080) and hit the UI but when I click the login link I get a 404 as it seems to redirect to the following URL resulting in a 404:
```
http://127.0.0.1:8080/sky/issuer/auth?access_type=offline&client_id=concourse-web&redirect_uri=http%3A%2F%2F127.0.0.1%3A8080%2Fsky%2Fcallback&response_type=code&scope=openid+profile+email+federated%3Aid+groups&state=xxxx
```

## Steps to reproduce

Install concourse via Helm Charts using the following command:
```bash
helm install concourse concourse/concourse \
--namespace concourse --create-namespace \
--set persistence.enabled=false \
--set postgresql.persistence.enabled=false
```
Port forward to the dashboard using the following command (note I expose on localhost:8082 not 8080):
```bash
k port-forward --namespace concourse concourse-web-85684c98fb-d66kt 8082:8080
```
Hit the home page and click on either of the login links and you should get a URL similar to the one in the Summary.

## Expected results

Login screen to display as expected.

## Actual results

404
```
http://127.0.0.1:8080/sky/issuer/auth?access_type=offline&client_id=concourse-web&redirect_uri=http%3A%2F%2F127.0.0.1%3A8080%2Fsky%2Fcallback&response_type=code&scope=openid+profile+email+federated%3Aid+groups&state=xxxx
```

## Triaging info

* Concourse version: 6.7.0
* Browser (if applicable): Firefox 81.01
* Did this used to work? Only when forwarding to port 8080. However when forwarding to 8082 it still should work not redirect to port 8080 which nothing is listening on.

**Comment by andy-paine** [comment]
For the login redirects to work you need to set the `CONCOURSE_EXTERNAL_URL` env var or `--external-url` flag to tell Concourse where users access it so it can generate redirect links. For the chart that setting is here https://github.com/concourse/concourse-chart/blob/master/values.yaml#L218. You can include a port too if you aren't using a default (80 for HTTP, 443 for HTTPS) port.

**Comment by darktempla** [comment]
@andy-paine thanks for the tip mate. Closing issue.

Changing my helm install command to the following (original above), adding the `concourse.web.externalUrl` option worked a treat.
```bash
helm install concourse concourse/concourse \
--namespace concourse --create-namespace \
--set persistence.enabled=false \
--set postgresql.persistence.enabled=false \
--set concourse.web.externalUrl=http://localhost:8082
```
