### ISSUE TITLE
Add index to fix performance issues with pipeline deletion (6.7.2)

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6269]
## Summary

This was added on `master` in 38b12fa85e7269f0318271a250a5a70268862ad8, but was not included in the 6.7.0 release for simplicity. Without the index, we experienced deadlocks on pipeline deletion on hush-house (to the point of needing to add the index manually to avoid issues).

Given that 6.7.2 is our LTS release, we should probably get this in.

Note that just adding the index as-is will cause issues with migration ordering - so we'll likely need to do some migration reordering on master so as not to break things in the next release

**Comment by muntac** [comment]
Closing this as the change has been made to 6.7.2, and https://github.com/concourse/concourse/issues/6277 has been opened to address the merge back into `master`.
