### ISSUE TITLE
Destroy an instance pipeline through fly

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#6278]
## Summary

Currently we don't have a way to destroy an instance pipeline through fly. We can probably implement this by adding a flag to `fly destroy-pipeline` with an instance var similar to how we set an instance pipeline through `fly set-pipeline`. It should probably only delete an instance only if the instance vars completely match, this way if you only enter a subset of the instance vars it won't delete all the instances that match that subset of vars.

**Comment by aoldershaw** [comment]
It's actually possible to do this now - you can specify instance vars for any `fly` command which expects a pipeline flag like so:

```sh
$ fly -t dev dp -p release/version:6.7.x
```

Similarly for job/resource flags:

```sh
$ fly -t dev tj -j release/version:6.7.x/shipit
```

`fly set-pipeline` is the odd one out here - you would set the above pipeline as:

```sh
$ fly -t dev sp -p release -i version=6.7.x -c pipeline.yml
```

Do you think it'd be better as:

```sh
$ fly -t dev sp -p release/version:6.7.x -c pipeline.yml
```

?

With `-i`, you have consistency with setting other vars (`-v`, `-y`), but in the pipeline flag, you have consistency with how you reference pipelines elsewhere in `fly`. Also, as @vito noted in the instanced pipelines RFC:

> `:` vs. `=` is a little weird but it's consistent with fly check-resource - we use `=` for assignment and `:` for partial filtering.

...though that was under the assumption the `-i` flag would be used everywhere.

**Comment by clarafu** [comment]
Ohh I see! Sorry I was under the assumption that it was still using the `-i` flag like in the RFC. Would you use commas to specify multiple vars within the pipeline flag? Hm I think its fine with the set-pipeline command using `-i` still, as long as we document it nicely how to specify instance vars in the help text for other fly commands!

**Comment by aoldershaw** [comment]
Yeah, commas to specify multiple, dot notation to go into subfields, etc.

The test suite showcases some of the more niche use cases: https://github.com/concourse/concourse/blob/dcb37aee4ebc6acc1856e752457bbdc65fb0b42d/fly/commands/internal/flaghelpers/pipeline_flag_test.go#L40-L49
