### ISSUE TITLE
Increased containers count after upgrade to 6.7.1 from 6.5.1

### ISSUE THREAD

**Issue by odormond** [concourse/concourse#6286]
## Summary

We recently upgrade our Concourse deployment in AWS from 6.5.1 to 6.7.1 and since then we see an increase in the number containers being used on the workers.

Our setup includes multiple teams and dynamically scale the number of workers based on the number of active tasks as well as the max number of containers on the workers to avoid hitting the max-containers limit (this scale out happen at 220 containers). The first two graphs below focus on the default team which is only active during working hours. With Concourse 6.5.1, as can be seen on the first graph, we usually can maintain a max of less than 200 containers:
![image](https://user-images.githubusercontent.com/6637092/99391144-07932f00-28da-11eb-875a-2e55548995e0.png)

One week later (same week day to try to match usage patterns) on 6.7.1, we can no longer do that and often breach the 220 threshold:
![image](https://user-images.githubusercontent.com/6637092/99391075-e92d3380-28d9-11eb-835f-bee3cc014509.png)

As you can see, with 6.7.1 we very frequently break the 200 containers mark but also hit the limit of 250 many times during early morning when we have a load spike. It looks like we roughly jumped from 135 to 180 max containers per worker averaged over 1 hour.

## Expected results

Same level of containers used.

## Actual results

A ~33% increase in containers used.

## Additional context

I don't what role this might play but I noticed that the lidar checks increased significantly after the update. On the day we did the update (around 9:25), we can clearly see a ~65% increase in the number of lidar checks (from ~40 to ~66):
![image](https://user-images.githubusercontent.com/6637092/99379355-da8a5080-28c8-11eb-8ffd-ca09623658ab.png)
(the yellow line shows the average over 1h of the green line and a huge spike at the deployment time has been suppressed).

## Triaging info

* Concourse version: 6.7.1
* Browser (if applicable): N/A
* Did this used to work? Much better on 6.5.1

**Comment by taylorsilva** [comment]
A user on discord also reported this: https://discord.com/channels/219899946617274369/604330872992432150/773580355986391070

**Comment by vito** [comment]
Based on the description I think this is addressed by https://github.com/concourse/concourse/pull/6271 - though it will be behind a feature flag (`--enable-skip-checking-not-in-use-resources`) as it technically breaks some usage scenarios (which was the reason this optimization was reverted in v6.7). I would recommend setting the flag if the increased container count is no bueno and you're comfortable with that usage scenario being just as broken as it was before. (Details in #5872.) 

https://github.com/concourse/concourse/pull/6281 will land in v7.0 and remove the need for the feature flag.

**Comment by muntac** [comment]
@odormond What's your resource usage like? If cpu and memory usage seem to be fine you could also increase `CONCOURSE_GARDEN_MAX_CONTAINER` to 500 and use a larger subnet range to allow for the higher number of containers by setting `CONCOURSE_GARDEN_NETWORK_POOL` to something like `10.80.0.0/16`.

**Comment by odormond** [comment]
Hi @vito !

Thanks a lot for the explanation and the fix. We look forward to 6.7.2. As we didn't notice any issue with the previous behaviour we will turn it back on.

@muntac, thanks for the suggestion. We did consider it but are not convinced it's entirely safe given our usage (we build c++ code and workers can be hit hard).

**Comment by evanchaoli** [comment]
#6271 has been merged to branch 6.7.x. We have been running a private build with fix of #6271 on one of our clusters, and saw container count back to same level as 6.4.0 (6.5 should be same, but we skipped 6.5, we jumped to 6.7 directly from 6.4).
