### ISSUE TITLE
More explicit worker, container, volume lifecycles

### ISSUE THREAD

**Issue by vito** [concourse/concourse#629]
# Goals
- A worker should be able to remain registered even in a hostile network. Today's heartbeating approach results in ambiguity; it can either be gone because the network blipped or gone because it's never coming back. Workers should only go away by being explicitly unregistered.
- A worker should remain registered when it's being updated in-place. Today if it's gone for long enough it'll become unregistered, and in many cases a worker missing will lead to failed builds.
- A worker that is physically going away should enter a "draining" state, where we wait for all in-flight work to complete and stop scheduling new work on it.
- Reduce network and database thrashing caused by heartbeating. This isn't going to scale very well as the number of containers and volumes increases.
- Explicitly `.Destroy` volumes and containers so that we can see any errors that may result in leaking containers and volumes. Today a worker can be failing to reap containers or volumes, which can leak resources. Calling `.Destroy` increases visibility.
- Define an explicit lifecycle for containers and volumes such that we can write a safe garbage collector.
# Proposal

Workers would have the following states:
- `running` - the "normal" state
- `landing` - stop scheduling new work, wait for existing workloads to finish, then unregister
- `stalled` - stop scheduling new work; the worker is temporarily unavailable but may come back with the same state as before

The following transitions would occur:
- any -> `running`: a worker has joined the cluster
- `running` -> `landing`: a worker is going to safely leave the cluster
- `landing` -> (gone): all work scheduled on a worker has finished, and the worker has been removed automatically
- `running` -> `stalled`: a worker is going to be updated in-place, or has failed to heartbeat, so expect connectivity issues
- `stalled` -> `running`: a worker has come back and is in normal operations

The next question is how to remove heartbeating. Heartbeating basically gives us garbage collection "for free" - as long as nothing's using a container or volume, it'll go away on its own accord. So to replace that we'll need explicit reaping.

Containers and volumes would be correlated to wherever they're being used. For example, containers launched by a build would be related via a join table. This way we can know that if the build is no longer running, its containers are no longer needed. Containers used for `check`ing resources would be kept so long as they haven't reached their "best if used by" date.

The other issue is that we don't want to destroy a container that's being hijacked. Currently hijacking heartbeats to the container just like anything else, so it'll stick around as long as the user's using it. Without heartbeating, we'll just have to mark the container as "hijacked", and ensure that for "hijacked" containers we set a TTL, rather than calling `.Destroy`. This way Garden's 'grace period' will take effect, and the countdown will begin once the user has left the container.

**Comment by vito** [comment]
Another problem this would solve is that volumes and containers in the database cannot be safely removed when their worker is gone, because we don't know if the worker will be coming back. This removes that ambiguity, and would allow us to garbage-collect any containers and volumes on record that refer to a worker that does not exist.

**Comment by vito** [comment]
Oh geez this will make debug logs so much less chatty too.

**Comment by jchesterpivotal** [comment]
I'm a big fan of state machines for comprehensibility and debuggability.

One thing I notice is that the hardest case is around intercepted or intercept-ready containers (ie failed builds).

I don't know if there's any thinking about relocating containers, but that'd make this easier. You'd be in a position to drain to existing works.

Though, now that I write this, I smell a juicy cascading failure condition for a group of workers operating close to maximum load.

**Comment by vito** [comment]
In principle relocating should work, given that:

1. all `get`s are repeatable
2. all `put`s are idempotent
3. all `task`s have no side-effects

1 and 2 are true, and 3 we try to convince people of. But yeah, the cascading failure mode is a bit worrying. I suppose there could be a limit.

We're already planning on implementing draining via the `landing` state, but it means we'll have to wait for existing builds to finish, rather than evacuating them. Evacuating could be an interesting alternative mode later on.

**Comment by jchesterpivotal** [comment]
Well relying on folks to produce idempotent tasks is a bit optimistic.

A while back I did one of my hand-waving suggestion for us to look at [CRIU](https://criu.org/Main_Page) checkpoints as a way to relocate containers. I think that'd be a Garden responsibility, though.

**Comment by vito** [comment]
@jchesterpivotal Yep - which is why we're not starting with that. But it would be interesting to have an `evacuatable: true` or something on tasks. Or flip the default 'cause we're opinionated like that.

**Comment by vito** [comment]
Here's the plan for landing, explaining in terms of the binaries but this applies to BOSH as well:

`concourse land-worker <worker-name>` -> runs SSH command against a TSA which transitions it to `landing` via ATC

TSA then polls for the worker to be gone while it's in `landing` state, and will then exit any `forward-worker` or `register-worker` processes with exit status 0. This will then result in `concourse worker` exiting all on its own.

**Comment by vito** [comment]
As an addendum to this, we've elected to keep the worker heartbeating, and upon the TTL elapsing, it will enter the `stalled` state automatically. We've also expanded the meaning of `stalled` to mean "stop scheduling work on the worker", rather than just a feedback indicator. This way if a worker hard-crashes it won't remain stuck in the pool forever causing problems.

Later we'll add a `fly` command to reap these workers, possibly in bulk.

**Comment by k0s** [comment]
How would a worker become unregistered? Would that be something that is tunable?  My use case is mostly as following: I want workers to be cattle, which is to say short lived but highly scalable.  So I mostly want worker time to life (as acted on by the master) to be as small as possible.  A worker node could go away quickly at any time:  as an example, consider the AWS spot market (though that's actually not what I'm doing).  Will there be the ability for TSA to have a very low TTL for workers?  Will there be the ability to retry a job on worker B if worker A disappears in a short window?

**Comment by vito** [comment]
@k0s That's an interesting angle to take and one I can get behind; it also makes sense for GCE preemptable instances for example.

For retrying, that's essentially the discussion @jchesterpivotal and I had above. I'm inclined to make that a separate issue though.

The TTL is up to the worker, so you could just say 30 seconds or something. I'd recommend some value high enough to cover network blips at least, which happen all the time.

Once the TTL expires the worker will enter `stalled` state, until it either comes back or gets explicitly removed (assuming we add that `fly` command I mentioned before).

**Comment by MaikuMori** [comment]
> Disclaimer: I have limited understanding of the whole architecture.

I'm somewhat disappointed by current worker implementation. They should be as stupid as possible.

Heartbeat is fine. If it stops beating, stop scheduling stuff on it, start reconnect timer. If the timer reaches zero assume any running tasks to be failed and "reap" the worker. 

I understand the issue of tasks being _at most once_ or _at least once_. This maybe could be configurable in the pipeline/task. If it's _at most once_, don't restart it, just fail it.

Trying to run workers in Kubernetes right now is hell. You can't expect them to gracefully shutdown, that's the whole point that nodes can come and go and so does worker containers. Having to manually reap the workers is somewhat ridiculous.

Obviously graceful shutdown is a nice thing. Being able to remove workers via API is also nice and could be integrated with cluster scheduler like the one in k8s since it knows when stuff comes and goes.

From my limited understanding there is also issue of volumes. What if they could be replicated across master and all workers?

**Comment by vito** [comment]
@MaikuMori The current worker implementation is already as stupid as possible, which is why it doesn't work for a bunch of people.

Heartbeating for the *worker* is fine, which is why we're keeping it. But I don't believe in having it totally gone just because another glorified TTL counted down - that's exactly the problem we're trying to *fix*.

We've already discussed task retrying, and that's pretty much the conclusion we already reached.

Not everyone is using k8s. As a later pass we can easily add a way to have a worker considered "ephemeral", and rather than going to `standby` it just goes away. This would be trivial to add after we have the world in a sane place, which is what this issue is for. We already started talking about that just before your comment.

Even without that, though, things'll still work a lot better than they did before; you'll just have some crud in your database for the workers that disappeared, and until we add a notion of ephemeral workers you could just have something reaping them on an interval. It doesn't sound like the end of the world.

**Comment by MaikuMori** [comment]
I'm sorry about the tone before.

K8s is just an example, there are quite many environments like that. The one described by @k0s is another example. In general people seem to be moving towards stateless systems where you can kill nodes/replicas without interruption to the service. The problem was extra painful on k8s because it seems like interaction between the worker containers and k8s is making k8s go bonkers and restart the worker/node many times. I wouldn't mind trying to help track the problem down, but for now I've settled to run concourse outside on plain VMs.

It was rather frustrating experience because simple 2 job pipeline that I put together had maybe 10% success rate. Other times it would either get stuck or error out.

In general ability to run concourse in a container cluster + service container support in pipelines would in my humble opinion make Concourse phenomenal.

What's the advantage of stalled state?

**Comment by jchesterpivotal** [comment]
I've already made my ha-ha-only-serious-we-should-use-Diego joke in this thread. But I'm partial to @vito's argument to approach fully fledged container orchestration slowly.

**Comment by cjcjameson** [comment]
In the meantime while this is worked on, we're likely to prepare a PR describing caveats and more explanation on container lifecycles. Would you like that to go into http://concourse.ci/architecture.html#section_architecture-worker, probably as a separate github issue, I assume?

Since we'll just be writing up our best understanding, we will welcome lots of feedback. But to start... to what extent should documentation of container lifecycles live in Garden docs vs. Concourse docs? Considerations:
- Would what we write apply to other Garden use cases, like Diego?
- How much verbosity do you want in your docs, vs. as links for further reading?
- How much can we assume a BOSH deployed concourse? Will more documentation not be acceptable if it doesn't speak to the binary distribution?

**Comment by vito** [comment]
@MaikuMori No worries.

The `stalled` state is pretty much the same thing you suggested, only without the second TTL that causes it to go away for good (that's the problem today we're fixing - time isn't enough in most of today's use cases). It provides visibility into flaky network situations and/or workers being updated in-place.

Let's defer the discussion around ephemeral workers to #755 which is the actual feature that we'd have to implement. This issue is about fixing today's design to at least be good at one thing (stable worker lifecycle) rather than being bad at everything.

**Comment by iSynaptic** [comment]
Has anyone evaluated Docker's SwarmKit/InfraKit or HashiCorp's Serf library to see how it fits into this enhancement?

**Comment by jchesterpivotal** [comment]
Is SwarmKit compatible with Garden?

InfraKit seems to be a cut-down BOSH, so I can folk making it an installation path.

Serf is a library for syncing data -- based on the experience of Diego, distributed data stores promise more than they deliver. Plain old databases work fine for any sensible scale -- Diego are team are past 100k containers under management on MySQL and PostgreSQL last I looked.

**Comment by freelock** [comment]
Coming here from #707... Question about if a heartbeat is missed/worker goes into Stalled state -- we have 2 workers, one untagged one that runs the check jobs, and a tagged worker in a different LAN. If there's an intermittent interruption to a heartbeat, I take it that the proposal is to make the worker "stalled". 

If this happens, will the next jobs up fail with "no available workers?" Or can it wait a few minutes for the worker to respond before failing? Don't really want to have to have a bunch of redundant workers, we're a small shop...

**Comment by vito** [comment]
@iSynaptic @jchesterpivotal Serf is more about communicating membership and not a lot more. You may be thinking about Consul. That being said, I'm not interesting in tying Concourse to either out of the box; we should just provide the APIs necessary for you to use whatever cluster membership tool you want.

@freelock Haven't worked that out yet, but that sounds something we could do. Now that we know the worker isn't *meant* to be gone, we can be a bit more forgiving.

@cjcjameson I'm not sure what you mean by container lifecycles; maybe just open an issue with questions you either have for us or have the answer to yourself and we'll see where it can fit in to the docs? I would prefer verbiage that's not distribution-specific. This may just mean defining what exactly "restarting a worker" vs "recreating a worker" means so people can map it to however their Concourse is deployed. Also I prefer delegating to other docs as much as possible to lower the maintenance of our own (out-of-date docs can be worse than no docs at all).

**Comment by jchesterpivotal** [comment]
> You may be thinking about Consul.

I believe I might be :)

**Comment by jchesterpivotal** [comment]
For pun consistency, `running` should be `in_flight`. 

Alternatively `stalled` should be something like `halted` and `landing` should be something like `halting`.

**Comment by petemounce** [comment]
> For pun consistency, running should be in_flight.
`aloft`?

**Comment by andreasf** [comment]
Hi,

it seems like none of the stories covered issue concourse/fly#98. It would be great to have a non-interactive way to hijack a failed build step. Currently, fly will ask whether to hijack the check or the task container. Should I open a new issue?
