### ISSUE TITLE
Migrate dutyfree deployment to greenpeace

### ISSUE THREAD

**Issue by chenbh** [concourse/concourse#6293]
It's currently deployed on cluster-1 which is pretty much empty. We should move dutyfree over to greenpeace and run pipeline. 

Steps to take:
- Greenpeace should bootstrap dutyfree. We think this currently means making a certificate for `resource-types.concourse-ci.org` and storing it in the `production` k8s cluster under the namespace that dutyfree will be running from
- Dutyfree pipeline should be updated to deploy to the `production` cluster. The kubeconfig it's using in the pipeline probably needs to be updated to point to the `production` cluster; that's it.

**Comment by taylorsilva** [comment]
We took the first step of moving dutyfree off of cluster-1 and onto the production cluster. It's currently still deploying using the dutyfree pipeline. We updated the kubeconfig the pipeline was using so it points to the production cluster.

**Comment by xtremerui** [comment]
dutyfree is now built in dutyfree pipeline in CI and deployed in greenpeace pipeline.
