### ISSUE TITLE
Create Concourse v6.7.3 Release Notes

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#6294]
## Background
As part of the commercial release of Concourse v6.7.2 we will need to add [release notes](https://docs.pivotal.io/p-concourse/v6/rn/) encompassing all releases from v6.4.0 to v6.7.2. 

## Requirements
* [ ] Update Release Notes
* [ ] Vet Breaking Changes with the release engineering pair
* [ ] Document bug found in https://pivotal-io.atlassian.net/browse/CONC-6 (tldr: `allow_host_access` was always enabled on pre-6.6.0 releases. If someone was relying on this behaviour they will need to turn this setting on now. Root cause not determined)

**Comment by muntac** [comment]
- [ ] Update with release notes for 6.7.3

**Comment by aoldershaw** [comment]
looks like we missed the `allow_host_access` bug
