### ISSUE TITLE
Create v6.7.2 Installation Documentation for BOSH

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#6295]
## Background

- With the commercial release of Concourse v6.3.0, we'll want to create a new installation guide for customers on BOSH

## Requirements 

- [x] Port over the existing v6.3.x [installation guide](https://docs.pivotal.io/p-concourse/v6/installation/install-concourse-bosh/) 
- [x] Run through a v6.3.x upgrade on BOSH and edit as necessary

**Comment by chenbh** [comment]
Done in https://github.com/pivotal/docs-concourse-pcf/pull/92/commits/b2717834265f2e15984c7b3e1a0c4aa2200905d2, which is now part of the big 6.7.2 PR
