### ISSUE TITLE
Create v6.7.3 Installation Documentation for Helm

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#6296]
## Background

- With the commercial release of Concourse v6.7.2, we'll want to create a new installation guide for customers on Helm

## Requirements 

- [ ] Port over the existing v6.7.x [installation guide](https://docs.pivotal.io/p-concourse/v6/installation/install-concourse-helm/) 
- [ ] Run through a v6.7.x upgrade on Helm and edit as necessary

**Comment by chenbh** [comment]
Possible scenarios we'll need to document:
- fresh k8s cluster (no previous deployment of Concourse on k8s)
  - install helm3
  - install Concourse chart
- existing Concourse installed with helm2 (likely if they used 6.3.1 installation instructions)
  - upgrade helm2 -> helm3
  - upgrade Concourse chart/release
- existing Concourse installed with helm3 (unlikely, but possible if they're experimenting with OSS releases)
  - upgrade Concourse chart/release

**Comment by muntac** [comment]
[ ] - Obtain TKGi environment from Toolsmiths
[ ] - Install v6.7.3 on TKGi

**Comment by chenbh** [comment]
Installation on a fresh TKGi went fine

I noticed that the TanzuNet packaged chart referred to `v6.6.0` tag (TanzuDocs does give instructions to use another tag), however I wonder if we should be concerned about people downloading the chart and blindly using it.
