### ISSUE TITLE
"fly save-target" help does not describe the TARGET_NAME

### ISSUE THREAD

**Issue by jbayer** [concourse/concourse#63]
the current help does not show that you can or should provide a target name and "fly" is shown as "command". i would expect usage to look something like `fly save-target TARGET_NAME [command options] [arguments...]`

but it actually looks like this:

```
$ fly help save-target
NAME:
   save-target - save a fly target to the .flyrc

USAGE:
   command save-target [command options] [arguments...]

OPTIONS:
   --api 		api url to target
   --username, --user 	username for the api
   --password, --pass 	password for the api
   --cert 		directory to your cert
```

**Comment by vito** [comment]
This'll be fixed in the next release; we've switched option parsers and stopped using arguments entirely. Using flags for everything makes it so there's only one place to look for options when learning a command.
