### ISSUE TITLE
concourse fails with postgres with ssl mode enabled (since 2.0)

### ISSUE THREAD

**Issue by stepanstipl** [concourse/concourse#631]
After update to concourse 2.0.2 (from 1.6.1), web will not start anymore _(running official docker containter from Docker Hub)_, the only message I get in logs is:

```
{"timestamp":"1472836271.278480053","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"2"}}
x509: certificate signed by unknown authority
```

(running with -d flag doesn't give any more output.)

By trial/error - it seems to be related to ssl connection to the DB, I had `?sslmode=verify-full&sslrootcert=/concourse-certs/aws-rds-ca-2015-root.pem` in postgres connection string and this used to work previously (golang postgres client supports this), if I disable ssl, concourse will start fine.

Running with `sslmode=prefer` throws

```
{"timestamp":"1473070877.764324665","source":"atc","message":"atc.db.migrations.failed-to-acquire-lock-retrying","log_level":2,"data":{"error":"pq: unsupported sslmode \"prefer\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported","session":"2"}}
```

The problem seems to be `https://github.com/jackc/pgx` which in comparison to `https://github.com/lib/pq` has only limited support for ssl related settings in Postgres connection string.

I've come up with a workaround that seems to be working fine - instead of passing location of trusted root ca in postgres string (`sslrootcert=/concourse-certs/aws-rds-ca-2015-root.pem`), add these certs to system bundle.

In my case (running CoreOS) it means:
- copy desired ca certificates to `/etc/ssl/certs/`
- run `/sbin/update-ca-certificates` to update system bundle
- mount these inside Concourse web container `-v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt`

Passing custom location in postgres string used to work in 1.6 I've used previously and is kind of standard way how to do it (https://www.postgresql.org/docs/9.1/static/libpq-ssl.html).

I understand this will probably depend on support from `pgx` library, but I would suggest at least to add some documentation abut this. It's something that was working just fine before 2.0.

(related to #449)

**Comment by vito** [comment]
We should maybe just split that field up into separate flags. That'd at least make it more obvious to configure things like this rather than figuring out the connection string syntax, and which bits are portable.

**Comment by stepanstipl** [comment]
Yep, that sounds reasonable - the important point from my perspective is that there should be way (ideally easy to setup & documented) how to configure ssl & verify server cert for DB connection.

**Comment by vito** [comment]
This should be resolved now.
