### ISSUE TITLE
Deploy Concourse for Platform Automation v6.7.3 Release and Docs

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#6314]
## Background

As part of the commercial release of Concourse v6.7.2, we'll need to release a new version of Concourse for Platform Automation as well as double check the current docs. 

## Summary

- [x] Go to the [enterprise platform automation pipeline](https://ci.concourse-ci.org/teams/main/pipelines/enterprise-platform-automation)
- [x] In the [concourse-bosh-deployment job](https://ci.concourse-ci.org/teams/main/pipelines/enterprise-platform-automation/resources/concourse-bosh-deployment), pin v6.7.2
- [x] Run the Pipeline
- [ ] If the pipeline succeeds, a new Concourse for Platform Automation release should be added to [Tanzu Network](https://network.pivotal.io/products/p-concourse/) with all of the corresponding components
- [ ] The enterprise platform automation pipeline will validate the [installation docs](https://docs.pivotal.io/p-concourse/v6/installation/install-platform-automation/) (it'll fail if there are differences to the steps outlined in the docs), but it would be a good idea to double check the docs to see if things like stemcell version need to be updated.

**Comment by vito** [comment]
Started on this but the first job currently fails: https://ci.concourse-ci.org/teams/main/pipelines/enterprise-platform-automation/jobs/create-opsman-gcp/builds/16

The pipeline YAML is here: https://github.com/pivotal/concourse-for-platform-automation/blob/579b4e7163495c47bcc9c8f1bdbcb3d689ce98be/pipeline.yml

But it looks like a bunch of files were deleted that the pipeline references: https://github.com/pivotal/docs-platform-automation/commit/716bfe3535f3b712d38ce88dbd8988beb2d5b1de

Poked the platform automation folks on Slack to see what we should do.

**Comment by vito** [comment]
Fixed the pipeline in https://github.com/pivotal/concourse-for-platform-automation/commit/b61be3159812343d1be7346ea862324b00726728
