### ISSUE TITLE
unable to fly hijack into failed task running apt-get install -y git-all

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#632]
The task fails at some point with not error message from apt-get. Subsequently attempts to fly hijack into this container fail silently

I switched to `apt-get install -y git` and everything works as expected

**Comment by xtreme-gavin-enns** [comment]
For a little more context, here is the Dockerfile that was used to generate the image this task was running in:

```
FROM ubuntu:16.04

WORKDIR /tmp/docker
ENV GOPATH /go
RUN mkdir ${GOPATH}

RUN apt update
RUN apt install -y wget

#Install UAA client
RUN apt install -y ruby-dev
RUN apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
RUN gem install cf-uaac

RUN apt-get install -y default-jre

RUN apt-get install -y jq

RUN apt install -y golang=2:1.6-1ubuntu4

#Install CF Cli
RUN wget -O /tmp/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.21.1&source=github-rel"
RUN tar xvzf /tmp/cf.tgz -C /usr/local/bin/
```

**Comment by vito** [comment]
I don't know any reason why this would fail on Concourse's end. Maybe `git-all` made you run out of disk or something?

**Comment by vito** [comment]
Closing for now as we're unlikely to progress on this.

**Comment by vij2** [comment]
The task fails at some point with not error message from apt-get. Subsequently attempts to fly hijack into this container fail silently
apt-get install -y git
sh: apt-get: not found
