### ISSUE TITLE
Set up the new MacStadium Darwin worker

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6325]
* Credentials are in LastPass as something like 'MacStadium (new)'
* Please use Terraform
  * You can use the `null` resource with the machine IP as a 'trigger'
  * Use the SSH connection type using credentials from LastPass
  * Maybe use 'remote-exec' and have the machine download the `concourse.tgz` just like the Windows worker terraform does
  * I think the worker can be run as a launchctl service
* Retire the Mac Pro (Alex: return it to the Toronto office)

**Comment by aoldershaw** [comment]
It's up and running builds. Terraform is here: https://github.com/concourse/ci/tree/master/deployments/darwin-worker

It's currently using the same worker key as the regular linux CI workers - perhaps when we convert it to greenpeace we can give it a unique key
