### ISSUE TITLE
Pipeline web view crashes on chrome for linux when not the primary tab.

### ISSUE THREAD

**Issue by jfmyers9** [concourse/concourse#633]
Currently I have only reproduced this on linux, however I have not tried to reproduce this on any other operating systems.

Steps to reproduce:
1. Open the pipeline view i.e. https://diego.ci.cf-app.com/
2. Switch tabs.
3. Wait until chrome `Aw snaps` the pipeline view.

I have also noticed that when leaving the tab as the primary (focused) tab, everything will continue to operate successfully.

Versions:
Chromium (Version 53.0.2785.92 (64-bit)), Chrome (Version 52.0.2743.116 (64-bit))

**Comment by beyhan** [comment]
I can't reproduce the steps described above on OS X. I observe unresponsive Chrome page on OS X with Concourse 2.0.2 when I click around on Concourse pipelines. Currently, I can't find a pattern for it but same behavior can't be reproduced with Concourse 1.6. Also Concourse 2.0.2 doesn't seem to have the unresponsive page issue on Safari (Version 9.1.2).

**Comment by ahelal** [comment]
Also on Mac very slow and sometime unresponsive and consumes a lot of resources. This happened only with the 2.0.X

**Comment by vito** [comment]
We were accidentally re-rendering twice as much as we should have (and were in previous versions). A fix has gone through and I'll check if that's all it was. It should also be faster than it was before, since it won't redraw if the dataset hasn't changed.

**Comment by kosh01** [comment]
Me too facing this issue and found out that the chrome plugin BlazeMeter was causing it. It works fine now after the plugin is disabled.
