### ISSUE TITLE
Fly on OS X (darwin) does not support custom CA certifiaces

### ISSUE THREAD

**Issue by stepanstipl** [concourse/concourse#634]
On OS X `fly` cli will fail to connect if concourse is set up with certificates issued by private CA, even if this CA is correctly imported to system as trusted. Error message is:
```
could not reach the Concourse server called df:

Get https://ci.df.yoti.aws/api/v1/info: x509: certificate signed by unknown authority
```

This is due to https://github.com/golang/go/issues/14514, where golang's crypto/x509 prior to 1.7 does not support loading certificates from other Keychains than "System Roots" one. Unfortunately since El Capitan it's not possible for user to import anything into this keychain. Correct way is to respect CAs from other keychains as well (System, Admin, User).

This can be fixed by **using go 1.7 to build the fly command line tool**. I have tried this and didn't see any issues so far with using go 1.7 for cli.

**Comment by databus23** [comment]
The suggested fix only works of fly is compiled natively on darwin (with cgo) which it is not atm. See https://github.com/concourse/concourse/issues/601

**Comment by stepanstipl** [comment]
Didn't realise that, thanks, good point.

Should we close this as dupe of #601 then?

**Comment by databus23** [comment]
Yeah, I guess this is a duplicate.

**Comment by stepanstipl** [comment]
Just realised there're two aspects of this - need cgo & go > 1.7.

I've just tried using **xgo** (https://github.com/karalabe/xgo) to cross-compile fly for darwin with CGO enabled and it seems to work just fine.

**Comment by vito** [comment]
Closing in favor of https://github.com/concourse/concourse/issues/601 which we'll fix by building `fly` on each platform natively. We'll also provide the `fly` binaries as part of our GitHub release, for bonus points.
