### ISSUE TITLE
generate a preview of a pipeline.yml file

### ISSUE THREAD

**Issue by jaresty** [concourse/concourse#635]
When debugging pipelines, I have commonly found myself setting the pipeline just to get a look at how it visually looks.  There is already [an atom plugin](https://atom.io/packages/concourse-vis) that attempts to solve this problem, but it would be nice to see something that is supported and also that doesn't require a specific editor to use.  `fly -t pipeline preview x.yml` perhaps?

**Comment by vito** [comment]
Running `set-pipeline` and leaving it paused seems like the way to go. The cost of doing anything else seems too high from an engineering perspective.
