### ISSUE TITLE
Default metric attributes aren't propagated to prometheus emitter

### ISSUE THREAD

**Issue by chenbh** [concourse/concourse#6351]
## Summary

Any additional attributes set by `--metrics-attribute=NAME:VALUE` are ignored by the prometheus emitter 

## Steps to reproduce

config.yml:
```
version: '3'

services:
  web:
    environment:
      CONCOURSE_METRICS_ATTRIBUTE: foo:bar
```

1. Run `docker-compose -f docker-compose.yml -f hack/overrides/prometheus.yml -f config.yml up -d`
1. Navigate to http://localhost:9090/graph?g0.expr=concourse_http_responses_duration_seconds_count

## Expected results

I should see the metrics with a `foo="bar"` attribute:
```
concourse_http_responses_duration_seconds_count{instance="web:9100", job="concourse", method="POST", route="RegisterWorker", status="200", foo="bar"}
```

## Actual results

```
concourse_http_responses_duration_seconds_count{instance="web:9100", job="concourse", method="POST", route="RegisterWorker", status="200"}
```

## Additional context

We handle prometheus in a weird way, we're defining all the metrics and possible tags at:
https://github.com/concourse/concourse/blob/a851d623b0cf4ea705ad3d3fa3af755b8a9627b2/atc/metric/emitter/prometheus.go#L325-L333

When the emitter is handling an event, `event.Attributes` should contain all the event attributes in addition to the default ones, but they're being ignored by the handler
https://github.com/concourse/concourse/blob/a851d623b0cf4ea705ad3d3fa3af755b8a9627b2/atc/metric/emitter/prometheus.go#L754-L774

## Triaging info

* Concourse version:
* Browser (if applicable): 
* Did this used to work? probably not

**Comment by analytically** [comment]
@aoldershaw seeing this as well, would you be able to have a look?

**Comment by taylorsilva** [comment]
Both Aidan and Daniel are on the Concourse team here at VMware. We need time to prioritize this and get it fixed. It's kinda fallen off on the list of things to do 😓 We don't have any metrics work  planned in general.
