### ISSUE TITLE
Testflight failures

### ISSUE THREAD

**Issue by nickhyoti** [concourse/concourse#6353]
## Summary

Current master throwing failures when running ginkgo testflight
## Steps to reproduce
Clone concourse to local system
Build concourse as per build instructions
Start local instances running docker-compose up
Run tests using ginkgo testflight

## Expected results
I would expect to see zero failures

## Actual results

```
Summarizing 7 Failures:

[Fail] Flying [It] works 
/var/tmp/hindleni/mtls/concourse/testflight/suite_test.go:286

[Fail] Flying uploading inputs with and without --include-ignored [It] uploads git repo input and non git repo input, IGNORING things in the .gitignore for git repo inputs 
/var/tmp/hindleni/mtls/concourse/testflight/suite_test.go:286

[Fail] Flying hijacking [It] executes an interactive command in a running task's container 
/var/tmp/hindleni/mtls/concourse/testflight/flying_test.go:104

[Fail] Flying uploading inputs with and without --include-ignored [It] uploads git repo input and non git repo input, INCLUDING things in the .gitignore for git repo inputs 
/var/tmp/hindleni/mtls/concourse/testflight/suite_test.go:286

[Fail] Flying pulling down outputs [It] works 
/var/tmp/hindleni/mtls/concourse/testflight/suite_test.go:286

[Fail] Flying aborting [It] terminates the running task 
/var/tmp/hindleni/mtls/concourse/testflight/flying_test.go:232

[Fail] Flying when an optional input is not provided [It] runs the task without error 
/var/tmp/hindleni/mtls/concourse/testflight/suite_test.go:286

Ran 113 of 115 Specs in 354.893 seconds
FAIL! -- 106 Passed | 7 Failed | 0 Pending | 2 Skipped


Ginkgo ran 1 suite in 5m56.325097464s
Test Suite Failed

```

## Triaging info

* Concourse version: 6.7.2
* Browser (if applicable): N/A
* Did this used to work? Yes - certainly earlier this year
[test3.txt](https://github.com/concourse/concourse/files/5672261/test3.txt)

**Comment by taylorsilva** [comment]
Just ran and they all passed:
```
Ran 115 of 115 Specs in 1113.829 seconds
SUCCESS! -- 115 Passed | 0 Failed | 0 Pending | 0 Skipped
```

What OS are you on? I'm on mac and our CI runs testflight on linux.
What go version are you on? I'm on 1.15.5

**Comment by nickhyoti** [comment]
I'm on ubuntu 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
Go version is  go1.15.6 linux/amd64

I first had this on a local laptop installation - thinking it may be something I'd done on there, we built out a VM to repeat it on there too

**Comment by taylorsilva** [comment]
Are you also having those same seven tests fail on that vm you made?

When I run the tests I run `ginkgo -p ./testflight` btw; not sure if that'll help you figure out what they're failing. Looking at `testflight/suite_test.go:286` hasn't helped me, it's just running fly which obviously worked for the 100+ other tests that did pass.

**Comment by nickhyoti** [comment]
Yes that was the test I was running - I've also tried it without the '-p' flag as well but it made no difference.

I couldnt see any reason why this should fail either - but I'll have another look

**Comment by nickhyoti** [comment]
Using latest code base, 6.7.4 unable to reproduce.
