### ISSUE TITLE
Add ability to use multiple containers as resources for a build

### ISSUE THREAD

**Issue by pdilyard** [concourse/concourse#637]
I haven't seen a lot of examples of testing that require external services, so maybe I'm thinking about this the wrong way (and I'm definitely open to ideas that would work right away on Concourse).

For local development, we have an environment set up with Docker Compose. Devs can simply run `docker-compose up`, and get a working version of the app. Containers for Redis, Postgres, and the app itself are all run.

Similarly, we can run `docker-compose -f docker-compose.test.yml up --build`, and the same Redis and Postgres containers will be launched, but this time a different Dockerfile will be used on the app that runs the test suite instead of running a debug server.

The test suite relies on Redis and Postgres, so those services need to be available to the application. I'm proposing one of the following features for Concourse:

- Support for Docker Compose (spin up some containers and use them for the build)
- Or, support for using multiple images as resources for a build. For example, you might have a database image that your app build can connect to, and that image would be spun up/down each time the app tests run.

**Comment by pdilyard** [comment]
I think this may be related to or a duplicate of #324

**Comment by macropin** [comment]
We also require similar functionality.

**Comment by vito** [comment]
consolidating this into #324
