### ISSUE TITLE
Cannot set CONCOURSE_MAIN_TEAM_*_GROUP for group with commas in it

### ISSUE THREAD

**Issue by Asherslab** [concourse/concourse#6372]
## Summary

Pretty simple, my OIDC/Oauth2 server has roles on it with commas in the names (taken from an LDAP server). 
Attempting to set the CONCOURSE_MAIN_TEAM_OIDC_GROUP env var with something like: `CN=Administrators,OU=Identity Server,OU=_Security Groups,DC=company-name,DC=com` doesn't work as concourse interprets each of those as seperate groups. i've also tried using `\` to escape those commas to no avail.

## Steps to reproduce

1. Setup concourse to use an OIDC server.
2. Setup groupsKey / scopes / etc
3. Setup `CONCOURSE_MAIN_TEAM_OIDC_GROUP` to have a name with commas in it (but is only one group)
4. Attempt to login and notice that use with above role is not part of the Main team.

## Expected results

Allow some form of escaping for commas actually a part of group names

## Actual results

Commas in group names that should be escaped (`\`) are still split

## Triaging info

* Concourse version: v6.7.2
* Browser (if applicable): Brave
* Did this used to work? (no idea)

**Comment by chenbh** [comment]
The library we use to parse env vars [doesn't seem to support](https://github.com/jessevdk/go-flags/blob/c17162fe8fd74f119ff938c5c67af63e3bac5ded/option.go#L316-L318) escaping delimiters, but you should be able to work around it by passing it in as a flag instead:
`concourse web --main-team-oidc-group CN=Administrators,OU=Identity Server,OU=_Security Groups,DC=company-name,DC=com`

**Comment by Asherslab** [comment]
thank you, that works as a solution
