### ISSUE TITLE
Concourse v6.7.1 is not compatible with v6.7.2

### ISSUE THREAD

**Issue by kramerul** [concourse/concourse#6373]
## Summary

Concourse v6.7.1 is not compatible with v6.7.2, because it uses the new release of github-release-resource which requires the new github V4 API.

The new release should be v6.8.0

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?

**Comment by taylorsilva** [comment]
Thanks for the report! Could you provide more details about the error you got going from 6.7.1 to 6.7.2? Did you have to update the `source` field for your resources that were using the `github-release` resource?

**Comment by kramerul** [comment]
We are using an enterprise github. For this case we had to set the `github_v4_api_url` additionally, which was introduced with [this commit](https://github.com/concourse/github-release-resource/commit/c82c11ccfe7ce1c20601a8a5e67b42fd44fcf45e)
