### ISSUE TITLE
v6.7.2 Secret cache does not expire secret when secret lease duration is 0, Vault secret backend

### ISSUE THREAD

**Issue by PinkTeddy** [concourse/concourse#6378]
## Summary

Using concourse v6.7.2 and vault KV store version 2

**When:** 
 - CONCOURSE_SECRET_CACHE_DURATION=1m
 - Vault secret lease duration is 0 

**Expected results:** Secret stayed cached for at most 1 minute or secret does not get cached. 
Since duration of 0 is non nonsensical CONCOURSE_SECRET_CACHE_DURATION should probably be used if secret lease duration is 0.  

**Actual results**: Secret stays cached forever.

## Steps to reproduce

- Vault KV store version 2
- CONCOURSE_VAULT_PATH_PREFIX= <KV store name>/data/<secret path>
- Secret  "lease_duration": 0

Vault kv store v2 does not seem to respect ttl, default_lease_ttl and max_lease_ttl so there seems to be no work around for lease_duration.
 
## Additional context

Example vault response body:
```
{
    "request_id": "040f7407-4f1c-564b-0605-8488e84d9e2c",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "data": {
            "1": "v7",
            "ttl": "1h"
        },
        "metadata": {
            "created_time": "2020-12-28T13:35:47.036768342Z",
            "deletion_time": "",
            "destroyed": false,
            "version": 11
        }
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}
```

[From docs](https://concourse-ci.org/creds-caching.html):
> Credential cache duration can also determined by the credential manager itself - for example, if Vault returns a lease duration for a credential, the shorter value between the configured cache duration and the credential's lease duration will be used.

So if **"lease_duration": 0** is returned this value is used.  I believe this is messing up cache because **github.com/patrickmn/go-cache** used in **atc/creds/cached_secrets.go** does not expire values if time is set at 0. 

```
package main
import (
	"fmt"
	"github.com/patrickmn/go-cache"
	"time"
)
func main() {
	c := cache.New(5*time.Minute, 10*time.Minute)
	c.Set("foo", "bar", 0 * time.Second)
	c.Set("foo2", "2", 1 * time.Second)
    time.Sleep(3 * time.Second)
    
    //returns: bar true
	fmt.Println(c.Get("foo"))

    //retruns: <nil> false
	fmt.Println(c.Get("foo2"))
}
```
## Triaging info

* Concourse version: v6.7.2

**Comment by evanchaoli** [comment]
First of all, 6.7.2 has no code change about Vault. Second, `lease-duration` is only about re-login to Vault, but nothing about secret cache.

Have you turned on `CONCOURSE_SECRET_CACHE_ENABLED`?

**Comment by PinkTeddy** [comment]
@evanchaoli I did not realize that kv v2 was not supported 
I did turn on CONCOURSE_SECRET_CACHE_ENABLED, the issue was that secrets were never expiring. 

I tested with kv v1 and everything works. Thanks!
