### ISSUE TITLE
Fly does not support /etc/resolver DNS resolution configuration hierarchy on OS X

### ISSUE THREAD

**Issue by johnegrosjean** [concourse/concourse#6382]
When using domain based DNS resolvers as in the case of split-tunnel VPN, fly only looks at /etc/resolv.conf rather than using the full OS DNS resolution.  Believe this is the same issue as https://github.com/concourse/concourse/issues/3691 that was fixed in 5.3.  Related to the Go bug at https://github.com/golang/go/issues/12524.  I'm using Fly v6.2.0, so I'm guessing the builder has again disabled cgo somehow despite the fix in 3691.  Steps to reproduce, etc, are identical to 3691.

**Comment by taylorsilva** [comment]
I'll re-open the original issue. Closing this one. Thanks for flagging it!
