### ISSUE TITLE
Invalid job name throws 500 with no output; should show 404

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#639]
As of 2.1.0, browsing to a build with the job name misspelled throws a 500 with no other output. I would expect this to be a 404 instead, and to get a more useful error page.

/teams/<team>/pipelines/<pipeline>/jobs/<MISSPELLED-JOB>/builds/<build>

**Comment by chendrix** [comment]
Similar to #1131

**Comment by chendrix** [comment]
needs #1131

**Comment by chendrix** [comment]
Closing to consolidate
