### ISSUE TITLE
Step timing tooltips text color same as background color

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6391]
## Summary

![image](https://user-images.githubusercontent.com/1880/103659386-56546100-4f3a-11eb-8144-f4b5a29f33ff.png)

## Steps to reproduce

Hover over any of the step statuses here:

https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/dev-image/builds/660.3

## Expected results

Should see readable text.

## Actual results

Text color seems to be the same color as the background.

## Additional context

I think this happens because the tooltip lives under `div > #tooltips` and doesn't specify a color, so it inherits the color set by `body`, which is a really light grey.

## Triaging info

* Concourse version: `master` (as of cb0b076)
* Browser (if applicable): Firefox, Chrome
* Did this used to work? yerrrr

**Comment by chenbh** [comment]
Also applies to the gears icon, I've asked Aidan to sneak the fix into the instance pipelines PR at https://github.com/concourse/concourse/pull/6105#issuecomment-754234713
