### ISSUE TITLE
Feature request: Visualize pipeline status in browser when not focused on the tab

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#640]
/cc @kimeberz 

I love the new feature to see build status by the color of the favicon, and it is has made it clear that the pipeline view would also benefit from something like this. If I have a resource making its way through my pipeline, I would like to be able to focus on something else and still have a "heads-up" display showing me the status of my pipeline. For example, the title of the tab could use custom characters to show the build status of each "column" like "my-pipeline: 🍏🍏🍊🍏🍏🍏🍎🍏🍏🍏" with marquee effects (or squashing of multiple columns into one) for long pipelines.

**Comment by vito** [comment]
You had me at marquee.

We were initially thinking of doing a notification-style indicator on the icon, we just didn't get that far yet. That would mean showing the black icon as it is today, with dots showing the statuses present in the pipeline. Not sure if it'd be a single dot showing lowest-common-denominator (i.e. red if any are red, green if all are green), or one dot for each status present.

**Comment by jtarchie** [comment]
When I have many tabs open, I cannot even see the whole tab title. For any significant pipeline, would this be that beneficial as an information radiator?

**Comment by wendorf** [comment]
It's a fair point. It's hard to communicate much with just a favicon and a dynamic-width label. But that's why it's a feature request and not a PR! I think the general need of getting updates about the progress of a pipeline without having the full page open is valid, and I'm open to creative solutions.

Maybe opt-in use of the notifications API? A browser extension? A police scanner chatter emulator?

**Comment by wendorf** [comment]
One idea that @ryanmoran had to condense this is to just show "status edges". e.g. if there are four green columns, a red column, two green columns, and a yellow column (e.g. "🍏🍏🍏🍎🍏🍏🍊"), just show state transitions: 🍏🍎🍏🍊

Something like this could condense the information into something still useful.

**Comment by wendorf** [comment]
`.dashboard-pipeline-banner` on the new Dashboard view gives a single color to a pipeline. Can this same color be used in the pipeline favicon?
