### ISSUE TITLE
Feature Request: Selecting a different pipeline group should push the previous selection to the browser history

### ISSUE THREAD

**Issue by davewalter** [concourse/concourse#641]
/cc @kimeberz 

I really like the "no-refresh" update of the pipeline view when you select a different combination of groups, but got used to being able to switch between selections using the browser history navigation capabilities.

It would be cool if the browser history could be updated as the pipeline groups are changed, just as it is when a new build is triggered on the job view page.

**Comment by vito** [comment]
Hmm, noted. During implementation I considered both and did a quick poll of folks around me and they preferred updating-in-place, but we obviously didn't put much thought into it. I could go either way; it's just a one-line change. If it felt intuitive to you to try going back, then that's enough for me; I hate when webapps break those established interactions.
