### ISSUE TITLE
Self-contradictory info in user roles docs about owner access

### ISSUE THREAD

**Issue by Krenair** [concourse/concourse#6422]
## Summary

https://concourse-ci.org/user-roles.html#team-owner-role

It says:
`Team owners have read, write and auth management capabilities within the scope of their team, but they cannot rename or destroy the team.`
But then:
```
Actions assigned to the owner role by default:
[...]
- RenameTeam
- DestroyTeam
```

Can owners rename/destroy their team or not?

**Comment by taylorsilva** [comment]
Looking at the code it looks like they can rename and destroy their own team:

https://github.com/concourse/concourse/blob/df62ba0d8a2d4b1b2d99bff9a25bb00874e8eb6e/atc/api/accessor/roles.go#L94-L96

Looks like this got missed when the docs were updated when configurable rbac was introduced.
https://github.com/concourse/docs/blob/110802cbe48cae25a1219fa8b56c0c3ef9ff1eab/lit/docs/auth/roles.lit#L57-L68

We'd happily accept a correction in the docs repo for this!
