### ISSUE TITLE
Bump concourse/golang-builder image to Bionic

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6427]
It's been set to Xenial for... a while. Some investigation (read: interrogating former team members) indicates that this may have been done to work around build failures in the pipeline when we were trying out `zstd` via a cgo package. I don't think we use that anymore, so we should probably roll this forward to Bionic so it's consistent with everything else.

**Comment by vito** [comment]
this led to `watsjs` failures which is not totally unexpected. investigating now and hoping to be able to reproduce locally.

**Comment by vito** [comment]
rolling back to `xenial` immediately fixed watsjs. 🤔 tried rolling forward to Bionic with `CGO_ENABLED=0` (#4342 had some hope of resolving the original issues we ran into) but that didn't fix anything, so it seems like we're running into some new issues to investigate.

**Comment by aoldershaw** [comment]
Fixed in https://github.com/concourse/ci/commit/497fabb825e7b15fb8f38a584d41a5067baf69c3 - `watsjs` is now passing using a `unit-image` (and `dev-image`, though that wasn't the issue) based on Bionic
