### ISSUE TITLE
OIDC authentication stopped working with 6.7.3

### ISSUE THREAD

**Issue by konstl000** [concourse/concourse#6435]
## Summary
We use OIDC authentication with Keycloak for Concourse. It used to work up until Concourse 6.7.3. Now, the corresponding dex event in the logs reports no groups ([]), albeit groups are present in the corresponding token.

## Steps to reproduce
Deploy Concourse 6.7.3, connect it to Keycloak (12.0.1), log in with any user that has any groups, see that groups are not there in the logs and that the user has no permissions.

## Expected results

`{"timestamp":"2021-01-16T00:44:27.810496550Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"oidc\", username=\"wherearemygroups\", email=\"test@test.com\", groups=[\"CCADMINS\"]","session":"15"}}`
(This was generated with the same user with Concourse 6.7.2)

The user has permissions as defined by the corresponding groups.

## Actual results

`{"timestamp":"2021-01-16T00:43:25.392091032Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"oidc\", username=\"wherearemygroups\", preferred_username=\"wherearemygroups\", email=\"test@test.com\", groups=[]","session":"14"}}`

The user has no permissions in concourse.

## Additional context

The claim for the user looks like that with my go-based OIDC tester:
`{
    "OAuth2Token": {
        "access_token": "*REDACTED*",
        "token_type": "Bearer",
        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMDUyZDkxYi04ZGYzLTQ1ZDEtYTBjNi04NjI0YTMwZDUzMzMifQ.eyJleHAiOjE2MTA3NTk3ODQsImlhdCI6MTYxMDc1Nzk4NCwianRpIjoiZTYzMDU0M2YtYzA0MC00ZGFiLThkZGEtOTkyMDQ0ZDQzNTRmIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmNsb3VkeWZtZS5kZS9hdXRoL3JlYWxtcy90cnVlZGV2b3BzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoLmNsb3VkeWZtZS5kZS9hdXRoL3JlYWxtcy90cnVlZGV2b3BzIiwic3ViIjoiNDlmNjBmYmItY2NiNy00ZGJmLTgxMDctZmNjMDE3MjU3NGQ1IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InRlc3QiLCJzZXNzaW9uX3N0YXRlIjoiODYzNDFiNTQtMzI4YS00YjYyLTkyNjUtOGU0NzY5YTcwNzJkIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwifQ.RWdm5GhYWlOpzgHWkDNtcN8mPHiPHoNmdJ8mQUB6T4s",
        "expiry": "2021-01-16T00:51:24.818199987Z"
    },
    "IDTokenClaims": {
        "exp": 1610758284,
        "iat": 1610757984,
        "auth_time": 1610757630,
        "jti": "5846434b-b1d5-4692-be87-e8950077d36e",
        "iss": "****",
        "aud": "test",
        "sub": "49f60fbb-ccb7-4dbf-8107-fcc0172574d5",
        "typ": "ID",
        "azp": "test",
        "session_state": "86341b54-328a-4b62-9265-8e4769a7072d",
        "at_hash": "LQ4g8NPNCPGG6DYsdh6MqA",
        "acr": "0",
        "email_verified": true,
        "name": "Test Test",
        "groups": [
            "CCADMINS"
        ],
        "preferred_username": "wherearemygroups",
        "given_name": "Test",
        "family_name": "Test",
        "email": "test@test.com",
        "username": "wherearemygroups"
    }
}`

Keycloak itself evaluates the token like this:

`{
  "exp": 1610758417,
  "iat": 1610758117,
  "jti": "4fde8dfb-92f8-4bdb-aa05-3e2c4d191b0d",
  "iss": "****",
  "sub": "49f60fbb-ccb7-4dbf-8107-fcc0172574d5",
  "typ": "Bearer",
  "azp": "edge",
  "session_state": "2afc57a1-5c7d-4abc-8009-187046669348",
  "acr": "1",
  "scope": "openid profile groups email",
  "email_verified": true,
  "name": "Test Test",
  "groups": [
    "CCADMINS"
  ],
  "preferred_username": "wherearemygroups",
  "given_name": "Test",
  "family_name": "Test",
  "email": "test@test.com",
  "username": "wherearemygroups"
}`
## Triaging info

* Concourse version: 6.7.3
* Browser (if applicable): Any
* Did this used to work? yes

**Comment by kberzinch** [comment]
I am seeing the same behavior.

**Comment by konstl000** [comment]
After analyzind the code, I found the issue. The new version of dex sets InsecureEnableGroups in the OIDC config to false by default. This is not overruled by Concourse, so that the groups coming via OIDC are always ignored (see https://github.com/concourse/dex/blob/13cd495873aa655533c7db7322c68ea108d046c7/connector/oidc/oidc.go#L382).
To fix this, I would propose to add a new OIDC flag that allows to override this default false value.
See https://github.com/concourse/concourse/pull/6436.
