### ISSUE TITLE
resource.check_every does not accept 'never'

### ISSUE THREAD

**Issue by robwruck** [concourse/concourse#6437]
## Summary

The [docs](https://concourse-ci.org/resources.html#schema.resource.check_every) state that `check_every` accepts a value of `never` but if you use it, resource checks error with `time: invalid duration "never"`.

## Steps to reproduce

Configure a resource with `check_every: never`

## Expected results

Resource is not checked periodically

## Actual results

Resouce check errors with `time: invalid duration "never"`

## Additional context

n/a

## Triaging info

* Concourse version: 6.7.2
* Browser (if applicable): n/a
* Did this used to work? no

**Comment by taylorsilva** [comment]
So this is the problem when your docs are versioned 😬 sorry you ran into this.

This feature was PR'd in recently and will be out in the next release: https://github.com/concourse/concourse/pull/6386

This feature is not currently available in any released version of Concourse, including the most recent `6.7.3`
