### ISSUE TITLE
Recommendation for combining `fly set-pipeline ... <(fly get-pipeline) ...` leads to misuse of Concourse

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#646]
Hi there,

Can [the documentation here](http://concourse.ci/fly-set-pipeline.html) please de-emphasize the point about `fly set-pipeline ... <(fly get-pipeline) ...`? Perhaps it belongs lower down on the page, perhaps it should be only on the specific `set-pipeline` page.

As a broader engineering group, we've let some engineers who've received little/no formal training on concourse start using it, and fly, to set pipelines, play around. It's the wild west, and we're experimenting!

One thing that's happened is that many engineers are used to relying on their CI system to run private builds and tests of their forks before making a pull requests. So with Concourse, they eagerly "fork" the pipeline. Tragedy of the commons ensues, there are too many pipelines, etc.

We have worked to clean up our directory structure and provided education so that people don't simply send the `fly get-pipeline` output into `fly set-pipeline`. We had been experiencing bucket clobbering and general credential pollution & creep/leakage, but now that people do a clean `fly set-pipeline` it's a little better.

We wish that fewer people had known about the "get-pipeline --> set-pipeline" trick, because it made our life harder while teaching people to embrace running `fly set-pipeline` in a repeatable way based on the pipeline files available in the code.

**Comment by vito** [comment]
Ehh, I don't know. There are a ton of ways to misuse any tool if there's not enough direction. Some folks have found that useful. It's a neat trick to show the importance of composability in `fly`s design. I use it pretty frequently to migrate pipelines between instances. Granted, usually by pausing the original one first.

What kind of changes would you propose to make with the wording?

**Comment by jtarchie** [comment]
This a process problem, not a tooling problem. De-emphasizing is not going to stop people from shooting themselves in the foot.

Are you able to put the documentation on your CI repo, so that becomes the source of truth for your project?

**Comment by cjcjameson** [comment]
Mmm, in our engineering group, it was a matter of degree. That is to say, if fewer people had shot their foot in the first place, it would have been easier to triage and get folks onto a good dev workflow. So I agree it won't solve everything, but it will help.

Composability of `fly` commands is pretty sweet, but not obvious -- it takes a spark of realization or a recommendation in a tutorial. So demoting it to a later section in the docs will strike an appropriate balance of full-functionality vs. user friendliness.

The current docs, by having this composability trick come before the `{{parameters}}` documentation, make it seem to readers like it's best to just copy pipelines and let "the experts" do the parameter interpolation. When I would hope that it's the reverse.

Regardless, I do want to sneak in the caveat about resources clobbering each other. There's a definite danger of confusion once you've piped `get-pipeline` to `set-pipeline` if the original pipeline is still running, and you didn't update the resource references. And even if it's only confusion (because under the hood Concourse is keeping track of proper version ordering), it's a danger zone.

We absolutely have documentation and various other ways of teaching people throughout our organization (it's not just for one repo/pipeline, it's for all the repos); this is just part of full-on feedback to the Concourse team across technical and usability factors.

**Comment by vito** [comment]
merged the docs PR
