### ISSUE TITLE
[SPIKE] Define what privileged means in context to containerd

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#6475]
Figure out what the minimal set of permissions and capabilities for privileged containers when using containerd as a runtime.

**Comment by vito** [comment]
Goals:

1. Folks should still be able to run containers-in-containers (e.g. `docker-compose up`).
2. Make image building faster.
    * Approach A: make it so we can build images without `privileged: true`.
    * Approach B: eliminate performance overhead of using `privileged: true`.
      * Caveat: this approach must not conflict with goal 1.

**Comment by muntac** [comment]
Question to think about from a capabilities standpoint: can we get get away without [using](https://github.com/concourse/concourse/blob/370b34f7524696627c0047da39a71c2d114f9dd6/worker/runtime/spec/capabilities.go#L72) `CAP_SYS_ADMIN` as it is highly permissive?

https://lwn.net/Articles/486306/

**Comment by muntac** [comment]
As @vito pointed out - Kubernetes and Docker **don't have user namespaces on by default**, and do not do any uid and gid mapping.

Docker [allows](https://docs.docker.com/engine/security/userns-remap/) user namespaces but only for non-privileged containers. This means that Docker does not support building of images or docker-in-docker when user namespaces are enabled (see [comment](https://github.com/concourse/concourse/issues/6537#issuecomment-781434714)).

For more on Kubernetes support: 
PR to support user namespaces: https://github.com/kubernetes/enhancements/pull/2101
Reading: https://kinvolk.io/blog/2020/12/improving-kubernetes-and-container-security-with-user-namespaces/#bringing-user-namespaces-to-kubernetes

**Comment by muntac** [comment]
So far for scenarios where we are using user namespaces within a privileged container:
1. Image building works
2. Docker compose does **not** work
See: https://github.com/concourse/concourse/issues/6538#issue-809442105

For any scenario in non-privileged containers image building does **not** work.
See: https://github.com/concourse/concourse/issues/6537#issue-809438194

**Comment by muntac** [comment]
Possible next steps:
1. Figure out how to make docker-compose work in a user namespace. This possibly requires better understanding of how uid/gid mapping is being done in `baggageclaim` but could also involve Kernel level issues.
2. Figure out how to make image building in non-privileged containers work.
- Using current oci-build-task that uses buildkit
- Use a buildkit alternative. Something that allows building images in non-privileged containers.
3. Get performance benefits some other way
- Allow developers to optionally turn on user namespaces for their privileged workloads. This would only work for image building purposes

**Comment by muntac** [comment]
Revisiting the question: What other privileged container use cases (outside docker-compose) would a user namespace break?

Here are some answers we got from @cirocosta 

1. In depth tracing ([bpftracing](https://github.com/iovisor/kubectl-trace)) or debugging (e.g. https://github.com/concourse/concourse/issues/4361#issuecomment-547943792)
2. Network File Systems or anything that needs to install/update kernel modules (this seems highly permissive)
3. GPU workloads (e.g. ML usecases) - https://github.com/concourse/concourse/issues/2353

**Comment by taylorsilva** [comment]
@cirocosta pointed us to this recent commit in the kernel: https://github.com/torvalds/linux/commit/7d6beb71da3cc033649d641e1e608713b8220290

id-mapping mounts will solve this problem in the future.

**Comment by taylorsilva** [comment]
### Conclusion

We are not changing how we run privileged containers. We do plan to change what files baggageclaim remaps to reduce initialization time.

We suggest investigating any isolation/security related goals like #5997 in a separate epic.

Result of this spike: #6620

**Comment by taylorsilva** [comment]
Follow-up from RPM:
- Could we enable this overlayfs feature which should reduce the size of the copy https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#metadata-only-copy-up
  - Is this feature old enough to be on a lot of production kernels now?
- For errors related to re-mounting cgroups, could we do cgroup mounting for privileged containers AND put them in a user-namespace?
