### ISSUE TITLE
Update web UI top bar to use new display_user_id field

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6498]
## Summary

#6369 tracks the user who created the build (either manual trigger or rerun) and also tweaked the `api/v1/user` endpoint to contain a new `display_user_id` field. The new field should be used to show the user in the top bar, since it reflects the same value that Concourse tracks as the build creator.

We should be able to replace [this function](https://github.com/concourse/concourse/blob/37c4aebfb90fcbd1f7b7504846a9860f783b3a2d/web/elm/src/Login/Login.elm#L96-L102) with one that just uses the `display_user_id` field.

## Context

* Prior discussion: #6369

**Comment by johnatanbs** [comment]
How do I find a good, reliable developer? How much do I pay for the same work?
