### ISSUE TITLE
sometimes build timestamps show further in past than they are

### ISSUE THREAD

**Issue by jbayer** [concourse/concourse#65]
later it cleared up on it's own, but for awhile new builds consistently showed 17 minutes ago.

![job-hello-world__4_-_concourse](https://cloud.githubusercontent.com/assets/1139532/8147010/c8fd10d2-120d-11e5-9945-54d8ca83df56.png)

**Comment by vito** [comment]
Sounds like an ntp issue (system clock in the VM was probably out of wack and then synced up). Not a whole lot we can do about that.

**Comment by jbayer** [comment]
ok, sounds plausible.
