### ISSUE TITLE
Jobs that are paused will continue to have their build logs reaped

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#6520]
## Summary

When a pipeline is paused we will not reap the pipeline's build logs in order to retain any existing information because the pipeline will not be producing any new builds.

https://github.com/concourse/concourse/blob/370b34f7524696627c0047da39a71c2d114f9dd6/atc/gc/build_log_collector.go#L57-L59

But when a job is paused it will continue to be reaped. Maybe we should add a check within the build log collector to check if the job is paused as well?

## Triaging info

* Concourse version: v7.0.0
* Browser (if applicable):
* Did this used to work? No

**Comment by aoldershaw** [comment]
Just wondering, what's the reason for not reaping old builds when the pipeline is paused in the first place?
