### ISSUE TITLE
[Spike] Build images in non-privileged containers

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#6537]
## Summary

Try to build images in a non-privileged container, skipping privileged performance issues.

## Context

* Prior discussion: #6475 

We did some testing already and got this result:
```
- in a non-privileged container
- that has all capabilities
- insde a user_namespace
- and root maps to non-root user
    - build image fails with a mounting error
    - verified capabilities by looking at cat /proc/self/status | grep Cap 
      and then using capsh --decode=0000003fffffffff to see the list of capabilities granted. They were the listed privileged capabilities.
    - Can replicate error with
      mount -o rbind,ro /scratch/buildkitd/runc-native/snapshots/snapshots/1/ /tmp/buildkit-mount214419184
    - can only real root mount stuff?
```

Other tests where privileged was true:
```
- privileged true
- insde a user_namespace
- insde a cgroup_namespace
- root inside maps to max_id outside
- baggageclaim does not chown/chmod the files
  - build-task-image works!

---

- privileged true
- insde a user_namespace
- insde a cgroup_namespace
- with root mapping to root
    - build image task works

---

- privileged true
- insde a user_namespace
- with root mapping to root
  - build image works
```

**Comment by taylorsilva** [comment]
Can we run oci-task-image in a regular docker container? A: nope! mounting errors

We're curious about file ownership when concourse downloads an image. What user currently owns that image file system? Do we do re-mapping for non-privileged containers filesystem? Seems like we could if the the ownership is wrong....
Next step: change baggageclaim to a noop-namespacer and see what breaks!

#### Scenario 1
- in a non-privileged container
-

**Comment by muntac** [comment]
Scenario: Build image (with vito/oci-build-task) in a **non-privileged** container
Result: Fails with:
```
#2 [internal] load .dockerignore
#2 sha256:749a2b73284ff26c4faf9703e83296a01e93e7fbc9a53c66a9d879322e8202f8
#2 transferring context:
#2 CANCELED
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to mount /tmp/buildkit-mount598442456: [{Type:bind Source:/tmp/buildkitd/runc-native/snapshots/snapshots/1 Options:[rbind ro]}]: operation not permitted
FATA[0000] failed to build: build: exit status 1
FATA[0000] failed to run task: exit status 1
```

Scenario: Build image (with vito/oci-build-task) in a **privileged** container
Result: Succeeds

**Comment by andy-paine** [comment]
We have this task which uses kaniko in non-privileged mode and keeps (mostly) the same params as the oci-build-task https://github.com/EngineerBetter/concourse-tasks/blob/main/build-oci-image-unprivileged/task.yml

**Comment by muntac** [comment]
@andy-paine are you building images in non-privileged mode for performance reasons, security reasons or both?

**Comment by taylorsilva** [comment]
Not exploring this further. There are options for users like Kaniko if they want to not use privileged containers.
