### ISSUE TITLE
fly parameter -i / --instance-var produce "unknown flag" error

### ISSUE THREAD

**Issue by adhondt42** [concourse/concourse#6541]
## Summary

Following the official documentation here https://concourse-ci.org/instanced-pipelines.html#instanced-pipelines
I am trying to instanciate multiple pipeline under the same group.

The only result I get is:
`error: unknown flag 'i'`

or in long:
`error: unknown flag 'enable-pipeline-instances'.`

## Steps to reproduce

```bash
$ fly -t $target sp -c ci/pipeline.yml -p $pipelineName -i branch=dev
error: unknown flag 'i'

$ fly -t $target sp -c ci/pipeline.yml -p $pipelineName --instance-var  branch=dev
error: unknown flag 'instance-var'
```

I also try to add 

```bash
$ export CONCOURSE_ENABLE_PIPELINE_INSTANCES=true
$ fly -t $target sp -c ci/pipeline.yml -p $pipelineName -i branch=dev
error: unknown flag 'i'

# or even 

$  fly -t $target --enable-pipeline-instances sp -c ci/pipeline.yml -p $pipelineName -i branch=dev
error: unknown flag 'i'
```

But it works with the old fashion way:
```bash
$ fly -t $target sp -c ci/pipeline.yml -p $pipelineName -v  branch=dev
no changes to apply
```

## Additional context

Here is the example pipeline declaration: 
```yaml
---
resource_types:
  - name: merge-request
    type: docker-image
    source:
      repository: samcontesse/gitlab-merge-request-resource

resources:
  - name: some-repo
    type: merge-request
    source:
      uri: https://git.com/project/code.git
      target_branch: ((branch))
      private_token: abcdef

jobs:
  - name: merge-request-builder
    plan:
      - get: some-repo
        trigger: true
      - task: tests
        file: some-repo/ci/tasks/unit-test.yml
```

## Triaging info

* fly version: 6.7.3
* Concourse version: latest docker image. Re-build today.
* Did this used to work? No

**Comment by aoldershaw** [comment]
Heh, unfortunate timing here - this is a feature that will be shipped with 7.0.0 (which we're planning to release today). Since we don't have versioned docs, this accidentally got added to the documentation when we shipped the 6.7.5 patch release.

So, it's just a documentation issue. I'll ping you when we ship 7.0.0 which has this feature

**Comment by aoldershaw** [comment]
7.0.0 is out now: https://github.com/concourse/concourse/releases/tag/v7.0.0

**Comment by taylorsilva** [comment]
looks like there's some confusion here. @marian2267 

The flag `--enable-pipeline-instances` is for the `concourse` binary, specifically the subcommand `web`. When starting concourse you would include the flag `--enable-pipeline-instances` or env var `CONCOURSE_ENABLE_PIPELINE_INSTANCES` when starting your web nodes to enable instanced pipelines on the **server side**. Like this:
```
concourse web --enable-pipeline-instances ...
```

On the **client side**, you can then use `-i`/`--instance-var` with `fly` to create instance pipelines.
```
fly -t ci sp -c ci/pipeline.yml -p $pipelineName --instance-var  branch=dev
```
You may need to `fly sync` first to ensure you have the correct version of `fly` that matches your concourse instance.

**Comment by marian2267** [comment]
Hello @taylorsilva,

Thank you for your quick response and for clarifying the issue. I managed to do that successfully now.
