### ISSUE TITLE
Bump elm-ansi to 9.0.2 to fix blinking caused by bad ANSI escape code parsing

### ISSUE THREAD

**Issue by awshew** [concourse/concourse#6542]
## Summary

Due to some failure to interpret ANSI 256 colour codes documented in https://github.com/concourse/concourse/issues/5071 and https://github.com/concourse/concourse/issues/2390 , log output that should appear with colour actually ends up blinking and becoming unreadable. 

## Steps to reproduce

* Run concourse as a webserver
* Create a mark (https://github.com/kovetskiy/mark ) job, or some job that outputs ANSI colour codes as outlined in https://github.com/concourse/concourse/issues/2390
* Watch the web UI render it as blink

## Expected results

Output on the console looks like:

![image](https://user-images.githubusercontent.com/26572445/108110523-38edd900-7048-11eb-9ff8-44fcc3b78d3b.png)

## Actual results
Looks like the image in https://github.com/concourse/concourse/issues/5071

## Triaging info

* Concourse version: 6.7.0
* Browser (if applicable): Brave (chromium)
* Did this used to work? Before mark started outputting ANSI colour

**Comment by vito** [comment]
I think we just need to bump `vito/elm-ansi` to 9.0.2 for this. Will prioritize.
