### ISSUE TITLE
var interpolation ignores var source

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6543]
## Summary

When setting a pipeline using static vars (including instances vars), var references to a var source's variable with the same name as the interpolated var are incorrectly interpolated

## Steps to reproduce

```
$ cat pipeline.yml
jobs:
- name: print
  plan:
  - across:
    - var: my-var
      values: [from local var source]
    task: print
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: echo
        args:
        - ((my-var))
        - ((.:my-var))

$ fly -t dev set-pipeline -p test -c pipeline.yml -v my-var="from static var"
$ fly -t dev trigger-job -j test/print -w
```

## Expected results

Prints:

```
from static var from local var source
```

## Actual results

```
from static var from static var
```

## Additional context

This happens because `vars.StaticVariables.Get` ignores `ref.Source`: https://github.com/concourse/concourse/blob/ab76fa8cf13879020112e0c18d56043fb1e1f114/vars/static_vars.go#L7

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable):
* Did this used to work? not sure

**Comment by evanchaoli** [comment]
I believe 6.7 has the same problem. One of our users reported the same issue and she finally worked around by renaming local var.
