### ISSUE TITLE
GitHub login broken after 7.0.0 upgrade

### ISSUE THREAD

**Issue by kurtmc** [concourse/concourse#6551]
## Summary

After upgrading to 7.0.0 from 6.7.1 the github auth seems to be broken.

## Steps to reproduce

Run 7.0.0 with github integration, try login;

## Actual results
```
Failed to authenticate: redirect_uri_mismatch: The redirect_uri MUST match the registered callback URL for this application.
```

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable): Firefox
* Did this used to work? Yes

**Comment by vito** [comment]
Is the failure message accurate? Perhaps this check just wasn't enforced prior to 7.0.

**Comment by kurtmc** [comment]
I definitely have my GitHub OAuth application callback url set to `https://<myconcoursehostname>/sky/issuer/callback`, has this URI been updated?

**Comment by taylorsilva** [comment]
A user reported this same error is discord before. Ended up being a config issue. The following is my response from discord.

---

dex was previously not passing the `redirect_uri`  to github. This worked fine before, github would just send the user to the configured callback url in the github app. Now that the `redirect_uri` is being passed to github, github will instead redirect users to that uri. This `redirect_uri` should match the callback url in the github app. Concourse generates the `redirect_uri` based on the `CONCOURSE_EXTERNAL_URL` provided, which should be in this format: `https://example.com`. If that does not match what's in your github app's callback url, then that would be the cause of your misconfiguration.

**Comment by kurtmc** [comment]
@taylorsilva Thanks for the update. I have fixed my setup now. I had `CONCOURSE_EXTERNAL_URL=http://...` instead of `CONCOURSE_EXTERNAL_URL=https://...`

**Comment by ljfranklin** [comment]
As an additional data point, I hit the same issue. Apparently when I setup my GitHub OAuth client a few years ago I was missing the `/sky/issuer/callback` suffix on the callback URL field in the GitHub UI. Worked fine until upgrading to Concourse 7.0.0. Not sure if I just messed up that step originally or if the docs were different in the long-long ago. Maybe worth a bullet in the release notes to have users double-check they have the right callback URL prior to upgrading.
