### ISSUE TITLE
Essentials metrics absent

### ISSUE THREAD

**Issue by dmytro-zhernosiekov-rft** [concourse/concourse#6552]
## Summary

There are several metrics missing on our Concourse CI:
`concourse_tasks_waiting_duration`
`concourse_tasks_waiting`
which really important for autoscalling and tracking user pipeline delays

## Steps to reproduce

Deploy Concourse CI with Helm chart, Concourse version 6.7.5

## Expected results

Get concourse_task_waiting metrcs on prometheus svc. 

## Actual results
Port forward:
```
kubectl port-forward service/concourse-web-prometheus -n concourse 9391:9391
Forwarding from 127.0.0.1:9391 -> 9391
Handling connection for 9391
Handling connection for 9391
```
In terminal:
```
$> curl http://localhost:9391/ | grep wait
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
dmytro@centos: ~/Documents/refi/sdp-app-deploy $> 

```
Other metrics are present.

## Additional context

Concourse run in AWS EKS, deployed with Helm Chart.

## Triaging info

* Concourse version: 6.7.5
* Browser (if applicable):  does not matter
* Did this used to work? no

**Comment by taylorsilva** [comment]
One important thing about this metric, and a few others, is that they only appear when there's actually data. They will not appear if there's zerp data. I know this from the few PR's I've done acceptance on. Never figured out why, I assume it's just how the prometheus lib behaves 🤷 

I'll usually run this pipeline: https://github.com/concourse/concourse/blob/master/topgun/pipelines/task-waiting.yml
which waits indefinitely, and set `--max-active-tasks-per-worker` to 1. 

After starting a second build, I see both task waiting metrics emitting. I do not see the task waiting metrics until after I start the second build which waits is forced to wait.
```
$ curl http://localhost:9100 | grep wait
...
# HELP concourse_tasks_wait_duration Elapsed time waiting for execution
# TYPE concourse_tasks_wait_duration histogram
...
# HELP concourse_tasks_waiting Number of Concourse tasks currently waiting.
# TYPE concourse_tasks_waiting gauge
concourse_tasks_waiting{platform="linux",teamId="1",workerTags=""} 1
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
```

The same is may be happening to your concourse, no tasks are waiting! 😁

**Comment by dmytro-zhernosiekov-rft** [comment]
Hi @taylorsilva,
I tried to set pipeline:
```
$> fly -t dev set-pipeline -c wait_job.yml -p wait-for-workers
jobs:
  job simple-job has been added:
+ name: simple-job
+ plan:
+ - config:
+     image_resource:
+       source:
+         mirror_self: true
+       type: mock
+     platform: linux
+     run:
+       args:
+       - -c
+       - |
+         until test -f /tmp/stop-waiting; do
+           echo 'waiting for /tmp/stop-waiting to exist'
+           sleep 10
+         done
+         echo done
+       path: sh
+   task: simple-task
  
apply configuration? [yN]: y
pipeline created!
you can view your pipeline here: https://concourse.dev.xxxxxxxxxxx/teams/main/pipelines/wait-for-workers

the pipeline is currently paused. to unpause, either:
  - run the unpause-pipeline command:
    fly -t dev unpause-pipeline -p wait-for-workers
  - click play next to the pipeline in the web ui
```
When I trigger it stuck at 
```
checking pipeline is not paused
checking job is not paused
```
No metric appeared:
```
$> curl localhost:9391 | grep wait
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
$> 
```
Also we collect metrics with Prometheus and if metric was appeared at least once it will be in database. Our users compliance that sometime they are waiting for workers till timeout reached. So `concourse_tasks_waiting` should be in Prometheus DB for sure, but there is not.

**Comment by taylorsilva** [comment]
> When I trigger it stuck at

That's very odd, given how simple the pipeline is. Only thing I can think to ask is, did you unpause the pipeline? If yes, then you might be hitting some bug in the scheduler...

Back to the task waiting metrics. Some questions:
- Have you seen a task waiting yourself and emitting `All workers are busy at the moment, please stand-by` as it waits?
- In the web logs, are there any logs with `failed-to-increase-active-tasks`?

**Comment by dmytro-zhernosiekov-rft** [comment]
Hi @taylorsilva  sorry for long delay. I don't know what I forgot to did when run last pipeline, was overloaded with tasks. I managed to run `wait-for-workers` pipeline and still have no metrics:
![image](https://user-images.githubusercontent.com/65401313/109523568-2ba90380-7ab8-11eb-91e4-21d088fe41dd.png)

Job were running for 20 minutes, I permanently checked logs, but got no output:
```
$> kubectl logs deployment.apps/concourse-web -n concourse | grep failed-to-increase-active-tasks   
$> kubectl logs pod/concourse-web-684bf5b7fb-t7pbj -n concourse | grep failed-to-increase-active-tasks
```
Also same in Grafana, what fetch data from Prometheus:
![image](https://user-images.githubusercontent.com/65401313/109523515-1d5ae780-7ab8-11eb-9945-85a1550b809d.png)

So if there were at least once this metric appeared it should display it.

**Comment by taylorsilva** [comment]
Glad you got the pipeline working. I'm sad to see that the task waiting metric is still not emitting for you though :(

I tried to reproduce this issue again on 6.7.5 (I forget if I tested on the latest `master` or 6.7.5) and I can get the metric to emit. I'm using the docker-compose.yml + promethus override file in the concourse/concourse repo. Here are the environment variables I'm setting on my web node. I've highlighted the relevant ones:
```diff
      CONCOURSE_SESSION_SIGNING_KEY: /concourse-keys/session_signing_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /concourse-keys/authorized_worker_keys
      CONCOURSE_TSA_HOST_KEY: /concourse-keys/tsa_host_key
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CLUSTER_NAME: dev
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
+      CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER: 1
+      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: "limit-active-tasks"
+      CONCOURSE_PROMETHEUS_BIND_IP: "0.0.0.0"
+      CONCOURSE_PROMETHEUS_BIND_PORT: "9100"
```

If you do a `kubectl describe` on the web pods, could you share the results of what environment variables are being set on the pod. Maybe the helm chart isn't setting them correctly, like the container placement strategy one.

**Comment by dmytro-zhernosiekov-rft** [comment]
Hi @taylorsilva 
We don't have CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER parameter defined in deployment. What we have is:
```
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY:             volume-locality
      CONCOURSE_PROMETHEUS_BIND_IP:                       0.0.0.0
      CONCOURSE_PROMETHEUS_BIND_PORT:                     9391
```
If we add missing parameter will it help?

**Comment by taylorsilva** [comment]
That will do it! By default it is zero, which results in no tasks ever waiting, which means you always have zero tasks waiting all the time. That's why that metric never emits, it never gets updated.

**Comment by dmytro-zhernosiekov-rft** [comment]
@taylorsilva hi. That's really valuable info. I have just question about version. We are using v6.7.5 and as I can see `limit-active-task` strategy will be added in v7.0.0 https://newreleases.io/project/github/concourse/concourse/release/v7.0.0 
Could I use your proposal on 6.7.5 version?

**Comment by taylorsilva** [comment]
Not sure what you're looking at in the release notes, but the limit-active-tasks strategy has been in Concourse since 2019 and looks like version 5.5.x
https://github.com/concourse/concourse/commit/aab8f4a85d0146a3b2ae2e166c83f459afecb4e3

**Comment by dmytro-zhernosiekov-rft** [comment]
I changed configuration:
```
        - name: CONCOURSE_CONTAINER_PLACEMENT_STRATEGY
          value: limit-active-tasks
        - name: CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER
          value: "200"
```
Then run pipeline you recommended:
![image](https://user-images.githubusercontent.com/65401313/109956076-e3722700-7ceb-11eb-9859-f4bd2515e9a5.png)


Pipeline had been running for 15 minutes:
```
13:00:36  selected worker: concourse-workers-worker-0
13:00:36  waiting for /tmp/stop-waiting to exist
13:14:36  waiting for /tmp/stop-waiting to exist
```
But metrics still not appeared:
```
$> curl -s localhost:9391 | grep wait
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
$> 
```
nor in Prometheus:
![image](https://user-images.githubusercontent.com/65401313/109956182-0ac8f400-7cec-11eb-9612-9abed6009108.png)

**Comment by taylorsilva** [comment]
Oh I think I caused some confusion for you.
That pipeline I provided results in only one task running. As a concourse dev it's very useful to help me debug!

With your config (max tasks set to 200 per worker) you would need to run **at least** `200*number of works you have` builds of that one job before you would see any metrics.

Something else that may help you trouble shoot is to actually look at the workers table. See what the web nodes see!

Connect to the Concourse database and run `select name,active_tasks from workers;`. The tasks waiting metric will only emit when all workers have 200 tasks and a task is waiting to run.

**Comment by dmytro-zhernosiekov-rft** [comment]
If I set limit to 1 and run 2 pipelines this metric should appear?

**Comment by taylorsilva** [comment]
Yes! Even just two builds of that pipeline at the same time would cause the metric to emit.

**Comment by dmytro-zhernosiekov-rft** [comment]
Hi @taylorsilva 

Error appeared on our production environment:
![image](https://user-images.githubusercontent.com/65401313/110913064-564b5580-831d-11eb-9ea9-59f1b6a551e6.png)

Here is logs:
![image](https://user-images.githubusercontent.com/65401313/110914561-3583ff80-831f-11eb-9132-dbb61c5bc7cf.png)

Workers on prod:
```
name                        containers  platform  tags  team  state    version  age
concourse-workers-worker-0  213         linux     none  none  running  2.2      10d
concourse-workers-worker-1  194         linux     none  none  running  2.2      10d
concourse-workers-worker-2  209         linux     none  none  running  2.2      10d
concourse-workers-worker-3  216         linux     none  none  running  2.2      10d
concourse-workers-worker-4  187         linux     none  none  running  2.2      10d
concourse-workers-worker-5  245         linux     none  none  running  2.2      10d
concourse-workers-worker-6  236         linux     none  none  running  2.2      10d
concourse-workers-worker-7  245         linux     none  none  running  2.2      10d
concourse-workers-worker-8  239         linux     none  none  running  2.2      10d
concourse-workers-worker-9  217         linux     none  none  running  2.2      10d
```

**Comment by dmytro-zhernosiekov-rft** [comment]
A lot `concourse_` metrics present in Prometheus but no `task_wait`

**Comment by taylorsilva** [comment]
So the error `max containers reached` comes directly from the worker. The default max number of containers per workers is 250. 

In prod, what do you have `CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER` set to? 

Remember, the containers on a worker include all check/get/put step containers along with task step containers. The `limit-active-task` placement strategy is only counting task containers, not **all containers**.

**Comment by dmytro-zhernosiekov-rft** [comment]
Hello @taylorsilva 
Sorry I didn't update ticket, because we decided to deploy new Concourse (7.1.0) with new Helm (15.0.1) on our dev. Parameters set as:
```
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY:             limit-active-containers,volume-locality,fewest-build-containers
      CONCOURSE_MAX_ACTIVE_CONTAINERS_PER_WORKER:         4
```
and this is really works. Error now:
![image](https://user-images.githubusercontent.com/65401313/114050370-e0db9200-9894-11eb-8143-44bd4a71d88f.png)

Concourse builds do not wait for workers, just fail the build. 
And there is no `concourse_task_wait` metrics in list. Even when I try to check `concourse_workers_tasks` it shows only 0 values all the time. `concourse_workers_containers` show correct values. 

Could we change behavior of Concourse to not fail task immediately and wait for workers? Also `concourse_workers_tasks` does not show correct values, but this is another task should be. I cannot track how many active containers in system.

**Comment by taylorsilva** [comment]
It'll only wait when using the `limit-active-tasks` strategy. That's the only strategy that currently has a waiting functionality. I don't see that strategy in your chain `limit-active-containers,volume-locality,fewest-build-containers`.
The metrics `concourse_task_wait` and `concourse_workers_tasks` only emit when using using the `limit-active-tasks` strategy.

All of this should better align with what you're expecting in next release thanks to #6635
From the PR:

> Similar to how the task step would wait for a worker to become available when using the limit-active-tasks strategy, this expands that functionality to all strategies (like the newly introduced limit-active-containers and limit-active-volumes), as well as applying it to all build step types (ie. check/get/put/task). Additionally, this PR adds a waiting-for-worker event to notify the user when a build is stuck waiting for a worker to become available.

**Comment by dmytro-zhernosiekov-rft** [comment]
@taylorsilva thank you for help. Metrics appeared on helm version 15.0.1 and concourse version 6.7.2. Everything is ok now, exactly as you explained. Issue could be closed.
