### ISSUE TITLE
Can't Upgrade 2.2.0 by docker-compose

### ISSUE THREAD

**Issue by patapata23** [concourse/concourse#656]
I could not have been trying to upgrade concourse-2.2.0 by docker-compose.

It was confirmed dockerHub, but did not have the tag of 2.2.0.
https://hub.docker.com/r/concourse/concourse/tags/

concourse-2.2.0 will not supported by docker-compose ?

**Comment by vito** [comment]
hmm that's pretty weird. fixed. not sure why that happened
