### ISSUE TITLE
? as permissions, failed access (Guardian runtime)

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#6566]
## Summary

when running with `containerd`, it happens that some particular task loses access to items passed between tasks.

## Steps to reproduce

Not clear when this happens:
![image](https://user-images.githubusercontent.com/667047/108830611-e3767680-75c9-11eb-9623-6f56cc404830.png)

The first task `validate-spellcheck` works just fine, the second one `validate-reflow` fails repeatedly, they are executed on the same worker in the same container.

```
        - task: validate-spellcheck
          timeout: 10m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-repo
            outputs:
            - name: binary
            run:
              # user: root
              path: sh
              args:
              - -exc
              - |
                export CARGO_HOME="$(pwd)/../cargo"
                sudo chown $(whoami): -Rf ${CARGO_HOME} .
                cargo +stable run --release -- --version
                cargo +stable run --release -- spellcheck demo/Cargo.toml
                cargo +stable run --release -- spellcheck -vvvv demo/src/main.rs
                cargo +stable run --release -- spellcheck demo/
                cargo +stable run --release

                sudo cp -vf target/release/cargo-spellcheck ../binary/cargo-spellcheck-$(git rev-parse HEAD)
              dir: git-repo
            caches:
            - path: cargo

        - task: validate-reflow
          timeout: 5m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-repo
            - name: binary
            run:
              # user: root
              path: sh
              args:
              - -exc
              - |
                export EXE="../binary/cargo-spellcheck-$(git rev-parse HEAD)"
                sudo chown $(whoami): -f "${EXE}" .
                sudo chmod +x "${EXE}"
                ls -al
                "${EXE}" --version
                "${EXE}" reflow demo/Cargo.toml
                "${EXE}" reflow -vvvv demo/src/main.rs
                "${EXE}" reflow demo/
                "${EXE}" reflow demo/README.md
                "${EXE}"
              dir: git-repo
```

<!--
All bug reports must have steps to reproduce, starting from the instructions in
CONTRIBUTING.md for running Concourse locally:

https://ci.spearow.io/teams/main/pipelines/cargo-spellcheck/jobs/master-validate/builds/199.1

## Expected results

Succeed

## Actual results

Fail with a lot "?" for permissions in the second task

## Additional context

Used to work yesterday, same setup.

## Triaging info

* Concourse version: 6.7.2
* Browser (if applicable): x
* Did this used to work? yes

**Comment by aoldershaw** [comment]
Is it possible to try running this on Concourse 7.0.0? There were some bug fixes around permissions for containerd:
* Possibly relevant: https://github.com/concourse/concourse/releases/tag/v7.0.0#6142
* Probably not relevant: https://github.com/concourse/concourse/releases/tag/v7.0.0#6348

Based on the screenshot, the user seems to be `sirmergealot` - is that set in the image metadata? Have you tried setting `task.config.run.user` to `sirmergealot` explicitly? I see you've commented out `user: root` - did that not work?

**Comment by drahnr** [comment]
`# user: root` is there from a while back, it's not relevant. The default user set in the container is `sirmergealot` which is part of the `wheel` group, so the follow up lines should fix the access rights.

**Comment by aoldershaw** [comment]
Tagging @muntac as he has more context on the containerd work.

Is there any info you can share about the `env-glibc` image to help us come up with a reproducible?

**Comment by drahnr** [comment]
It's public and can be pulled from here: https://quay.io/repository/drahnr/rust-glibc-builder

**Comment by drahnr** [comment]
Updating to 7.0.0 just greeted me with a bag of errors...

**Comment by drahnr** [comment]
The same issue persists with version 7.0.0

**Comment by drahnr** [comment]
I sew these two error messages in the log on the worker where I get the `?` operators, probably a red herring.
```
Feb 24 07:33:00 redbeard concourse[1832804]: {"timestamp":"2021-02-24T06:33:00.301212002Z","level":"error","source":"baggageclaim","message":"baggageclaim.api.volume-server.list-volumes.list-volumes.failed-hydrating-volume","data":{"error":"EOF","session":"4.1.97728.1"}}
Feb 24 07:33:00 redbeard concourse[1832804]: {"timestamp":"2021-02-24T06:33:00.302096772Z","level":"error","source":"baggageclaim","message":"baggageclaim.api.volume-server.list-volumes.list-volumes.failed-hydrating-volume","data":{"error":"EOF","session":"4.1.97728.1"}}
```

**Comment by drahnr** [comment]
Due to the lack of other options, I did a `fly -t yada set-pipeline ...` again, and it seems to have fixed the issues. I'd still like to understand what caused this in the first place.

**Comment by drahnr** [comment]
It turns out the artifact passed between the two containers is not passed. Nothing is showing up when `sudo ls -al` or `ls -al` in the binary dir, the PR pipeline is equivalent in that case and works.

**Comment by drahnr** [comment]
As it seems, `ls -al` does not work as anticipated, no matter permissions I modify. Other operations work just fine (`cp`, `chmod`, `chown`, ..), so I assume all the missing pieces are due to the formerly mentioned missing trailing quotes `"` in two distinct lines.

The original questions stands: why are the permissions all `?` in the container.

**Comment by taylorsilva** [comment]
> The original questions stands: why are the permissions all ? in the container.

I decided to google it since I don't know why linux does this. Found this SO answer:
https://unix.stackexchange.com/a/393603
So maybe when you're doing `sudo chown $(whoami): -f "${EXE}" .` you need to add `a+X`?

Question: Why do you make `CARGO_HOME` one dir up from `pwd`? Why not make it `$pwd/cargo`?

**Comment by drahnr** [comment]
I already did that this morning as one of my first reflex actions, rechecked just now - no change

```
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ sudo chmod a+X -Rf .
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ ll
ls: cannot access 'cargo': Operation not permitted
ls: cannot access 'git-pull-request-resource': Operation not permitted
total 0
d????????? ? ? ? ?            ? cargo
d????????? ? ? ? ?            ? git-pull-request-resource
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ ls -al
ls: cannot access '.': Operation not permitted
ls: cannot access '..': Operation not permitted
ls: cannot access 'cargo': Operation not permitted
ls: cannot access 'git-pull-request-resource': Operation not permitted
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
d????????? ? ? ? ?            ? cargo
d????????? ? ? ? ?            ? git-pull-request-resource
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ ls -al cargo/
ls: cannot access 'cargo/': Operation not permitted
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ ll^C
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ sudo chmod a+X -Rf cargo
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ ll^C
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ ll
ls: cannot access 'cargo': Operation not permitted
ls: cannot access 'git-pull-request-resource': Operation not permitted
total 0
d????????? ? ? ? ?            ? cargo
d????????? ? ? ? ?            ? git-pull-request-resource
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ ll cargo/
ls: cannot access 'cargo/': Operation not permitted
[sirmergealot@33ee4d3c-73e9-4f09-77b2-6f4202fa5fbc 8fee9a7d]$ 

```

**Comment by rickyshelton** [comment]
@drahnr I witnessed something like this recently:

```
selected worker: a488073366a4
root
ls: cannot access '..': Operation not permitted
ls: cannot access '.': Operation not permitted
ls: cannot access 'some-dir'
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
d????????? ? ? ? ?            ? some-dir
```

After some failed investigations, I contrasted to some other jobs which were still functioning correctly, and the only difference I could find was with the base image used in the build step - I have an image that takes an ubuntu image and installs some tooling.

Older working jobs were using an older version of ubuntu:
`FROM ubuntu:bionic`

Newer jobs were using:
`FROM ubuntu:groovy`

Reverting to the older version has worked for now, although I have no idea why.

**Comment by aoldershaw** [comment]
Sorry for the delay, just tried to reproduce this using the following minimal task:

```yaml
platform: linux
image_resource:
  type: registry-image
  source: {repository: quay.io/drahnr/rust-glibc-builder}
run:
  path: ls
  args: [-al]
```

I'm able to reproduce this on our CI server (running on Ubuntu VMs on GKE), but for some reason I can't reproduce it on a local `docker-compose` setup. Will keep looking

**Comment by aoldershaw** [comment]
As a workaround, running the tasks as `privileged: true` seems to fix things (at least on our setup) because of the uid remapping done in baggageclaim

**Comment by taylorsilva** [comment]
@aoldershaw we actually always do the uid remapping on every container we bring up.

We create a Privileged and Unprivileged mapper: https://github.com/concourse/baggageclaim/blob/master/uidgid/mapper_linux.go

And then we `walk` through the entire container: https://github.com/concourse/baggageclaim/blob/cc2c3140310612ea2c5d3503a3a781d9b0be9228/uidgid/namespace.go#L30-L32

and try to modify any files that aren't owned by the uid that processes will be run under inside the container: https://github.com/concourse/baggageclaim/blob/cc2c3140310612ea2c5d3503a3a781d9b0be9228/uidgid/translator.go#L34-L52

We ignore any chown/chmod errors. Maybe exposing those for debugging would be helpful?

**Comment by aoldershaw** [comment]
@drahnr hmm this is odd - we recently discovered that we were accidentally running the Guardian runtime on our CI server (whoops). Switching that over to containerd seems to fix the error for me, at least with the repro task in https://github.com/concourse/concourse/issues/6566#issuecomment-794080205

So, I'm seeing the task fail on Guardian, but pass on containerd - but you seem to be seeing the opposite, right?

**Comment by drahnr** [comment]
I see failing containers no matter which backend I use, it seems to only depend upon the container used.

**Comment by drahnr** [comment]
Launching a 7.0.0 worker yielded `?` with `gdn` but right now I can't reproduce the case with `containerd`, so either that was a mistake on my end (mixup) or resolved from 6.x tyo 7.0 for `containerd`.

**Comment by aoldershaw** [comment]
Thanks for trying to repro. Glad that matches what we’re seeing. Would be interesting to understand what changed between gdn and our confainerd runtime to lead to this difference

**Comment by drahnr** [comment]
Closing, it's been too long and I only use `containerd` these days.
