### ISSUE TITLE
Switching to containerd runtime breaks email resource

### ISSUE THREAD

**Issue by holgerstolzenberg** [concourse/concourse#6578]
## Summary
Last week we updated to 7.0.0 what in general worked like a charm  👍🏻.
I also switched to the `containerd` runtime and initially it looked like everything still worked, what was true for 99% of the pipes but later on I realized that the email resource we are using a lot (in `put` steps) broke.

My initial thought was that this is a problem of the email resource (https://hub.docker.com/r/pcfseceng/email-resource) and stated in issue there:

https://github.com/pivotal-cf/email-resource/issues/41

Actually - it was the point in time that I remembered opening up this quite a while before, as upgrading to `containerd` earlier already failed with the same issue.

I tried to get a glimpse on what is going on but failed building the resource on my own (I am not a Go dev).

Thinking about this a bit more I came to the conclusion that this might not be an issue of the resource but rather with Concourse itself. Running the following command `docker run -it pcfseceng/email-resource:1.0.19` you can see that there is no file `/tmp/gdn-init` present in the container.

So I guess this is something special on how concourse bootstraps the containers. Digging around Google and other Concourse issues I could not find something meaningful, still there is some code in Concourse that deals with that file:

https://github.com/concourse/concourse/search?q=%2Ftmp%2Fgdn-init

Any help on this is really appreciated. Sounds crazy but the feature set of the offending email resource is very important to us.

## Steps to reproduce
Starting from `docker-compose up`, what steps can be followed to reproduce the
problem?

Did not actually try this but implementing a simple pipe using that resource should be sufficient to examine the problem.

## Expected results
The email resource still works in the pipeline as it should not depend on the container runtime

## Actual results
The email resource cannot be used any more.
```
run check step: run check step: find or create container: starting task: new task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/tmp/gdn-init": stat /tmp/gdn-init: no such file or directory: unknown
```

## Additional context
Garden runtime is scheduled to be dropped in 7.1. We heavily rely on the given resource in our pipes and there is no alternative out there. This might become a nasty one for us, as I am trying to keep our cluster up-to-date.

## Triaging info
* Concourse version: 7.0.0
* Did this used to work?: YES (with garden runtime)
* OS: Debian Buster

**Comment by aoldershaw** [comment]
@muntac tagging you in case you have any idea. FYI we aren't planning on removing the Guardian runtime in 7.1 if I'm not mistaken - just changing the default (but you can still use `CONCOURSE_RUNTIME: guardian` to opt-in). We are planning to remove it eventually, though.

**Comment by aoldershaw** [comment]
Able to trivially reproduce without actually pointing it at an SMTP server:

```
```

**Comment by aoldershaw** [comment]
Was able to fix the issue by making the volume mounts more consistent with Guardian:

```diff
diff --git a/worker/runtime/spec/mounts.go b/worker/runtime/spec/mounts.go
index 47b71dbb0..829f6e3ca 100644
--- a/worker/runtime/spec/mounts.go
+++ b/worker/runtime/spec/mounts.go
@@ -7,10 +7,10 @@ const DefaultInitBinPath = "/usr/local/concourse/bin/init"
 var (
        DefaultContainerMounts = []specs.Mount{
                {
-                       Destination: "/proc",
-                       Type:        "proc",
-                       Source:      "proc",
-                       Options:     []string{"nosuid", "noexec", "nodev"},
+                       Destination: "/sys",
+                       Type:        "sysfs",
+                       Source:      "sysfs",
+                       Options:     []string{"nosuid", "noexec", "nodev", "ro"},
                },
                {
                        Destination: "/dev",
@@ -18,12 +18,6 @@ var (
                        Source:      "tmpfs",
                        Options:     []string{"nosuid", "strictatime", "mode=755", "size=65536k"},
                },
-               {
-                       Destination: "/dev/pts",
-                       Type:        "devpts",
-                       Source:      "devpts",
-                       Options:     []string{"nosuid", "noexec", "newinstance", "ptmxmode=0666", "mode=0620", "gid=5"},
-               },
                {
                        Destination: "/dev/shm",
                        Type:        "tmpfs",
@@ -37,16 +31,10 @@ var (
                        Options:     []string{"nosuid", "noexec", "nodev"},
                },
                {
-                       Destination: "/sys",
-                       Type:        "sysfs",
-                       Source:      "sysfs",
-                       Options:     []string{"nosuid", "noexec", "nodev", "ro"},
-               },
-               {
-                       Destination: "/sys/fs/cgroup",
-                       Type: "cgroup",
-                       Source: "cgroup",
-                       Options: []string{"ro", "nosuid", "noexec", "nodev"},
+                       Destination: "/dev/pts",
+                       Type:        "devpts",
+                       Source:      "devpts",
+                       Options:     []string{"nosuid", "noexec", "newinstance", "ptmxmode=0666", "mode=0620", "gid=5"},
                },
                {
                        Destination: "/run",
@@ -55,27 +43,51 @@ var (
                        Options:     []string{"nosuid", "strictatime", "mode=755", "size=65536k"},
                },
        }
+
+       UnprivilegedMounts = []specs.Mount{
+               {
+                       Destination: "/proc",
+                       Type:        "proc",
+                       Source:      "proc",
+                       Options:     []string{"nosuid", "noexec", "nodev"},
+               },
+       }
+
+       PrivilegedMounts = []specs.Mount{
+               {
 32         },
+                       Destination: "/proc",
+                       Type:        "proc",
+                       Source:      "proc",
+                       Options:     []string{"nosuid", "noexec", "nodev"},
+               },
+               {
+                       Destination: "/sys/fs/cgroup",
+                       Type:        "cgroup",
+                       Source:      "cgroup",
+                       Options:     []string{"ro", "nosuid", "noexec", "nodev"},
+               },
+       }
 )

 func ContainerMounts(privileged bool, initBinPath string) []specs.Mount {
-       mounts := append(
-               []specs.Mount{
-                       {
-                               Source:      initBinPath,
-                               Destination: "/tmp/gdn-init",
-                               Type:        "bind",
-                               Options:     []string{"bind"},
-                       },
-               },
-               DefaultContainerMounts...,
-       )
+       var mounts []specs.Mount
+       mounts = append(mounts, DefaultContainerMounts...)
+       mounts = append(mounts, specs.Mount{
+               Source:      initBinPath,
+               Destination: "/tmp/gdn-init",
+               Type:        "bind",
+               Options:     []string{"bind"},
+       })
        // Following the current behaviour for privileged containers in Docker
        if privileged {
+               mounts = append(mounts, PrivilegedMounts...)
                for i, ociMount := range mounts {
                        if ociMount.Destination == "/sys" || ociMount.Type == "cgroup" {
                                clearReadOnly(&mounts[i])
                        }
                }
+       } else {
+               mounts = append(mounts, UnprivilegedMounts...)
        }
        return mounts
 }
@@ -88,4 +100,4 @@ func clearReadOnly(m *specs.Mount) {
                }
        }
        m.Options = opt
-}
\ No newline at end of file
+}
```

Haven't pinpointed exactly what the change was that fixed this bug yet, though. Will submit a PR when I do

**Comment by aoldershaw** [comment]
The problem seems to be the ordering of mounts - we put the `/tmp/gdn-init` mount first, which causes issues for whatever reason.

The problem is because of something on the base image, `progrium/busybox`. the issue can be reproduced by running a task with that image:

```
$ cat /tmp/task.yml
platform: linux

image_resource:
  type: registry-image
  source: {repository: progrium/busybox}

run:
  path: pwd
$ fly -t dev execute -c /tmp/task.yml
find or create container on worker 0de37fd3f3ff: starting task: new task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/tmp/gdn-init": stat /tmp/gdn-init: no such file or directory: unknown
errored
```

I'm guessing it has something to do with how the rootfs is setup on that image: https://github.com/progrium/busybox/blob/master/rootfs.tar

There's a `/tmp/ldconfig` directory, and `/run` is a symlink to that dir, so maybe something funky happens when we try to mount to `/run` after we've already mounted to `/tmp/gdn-init`? Not sure exactly why, but hey, this seems to fix it

**Comment by aoldershaw** [comment]
Sure enough, an alternative fix is just to remove the `/run` mount in the first place. Not sure where that came from - it's neither used by Guardian nor Docker. So maybe best to get rid of it
