### ISSUE TITLE
BBR backup of Concourse fails because the code does not include lock scripts for the PostgresDB

### ISSUE THREAD

**Issue by Hermen-Nicolau** [concourse/concourse#6588]
## Summary

When using Bosh Backup and Restore (BBR) to backup a Concourse deployment the Backup fails with the following error message:

```
pg_dump: saving database definition
pg_dump: [archiver (db)] query failed: ERROR:  relation "public.build_event_id_seq_4327391" does not exist
LINE 1: SELECT last_value, is_called FROM public.build_event_id_seq_...
                                          ^
pg_dump: [archiver (db)] query was: SELECT last_value, is_called FROM public.build_event_id_seq_4327391
2020/08/07 06:01:21 You may need to delete the artifact-file that was created before re-running.
```

## Steps to reproduce

As of right now, the Concourse release does not include a lock on the Postgres DB as part of its code. Therefore, the backup will run concurrently with other database operations. Since new tables are created/destroyed when setting/deleting pipelines, it's possible to get into this state where the backup and the DB are out of sync and the backup fails.
To reproduce run a BBR backup while creating or deleting pipelines. 

## Expected results

Concourse would have a pre-backup-lock script to lock the system before the backup starts, and also a post-backup-unlock script to unlock the system when the backup is done.

## Additional context

This is something that can only be changed at the Concourse Release level and not the BBR level. There are detailed docs on the contract here: https://docs.cloudfoundry.org/bbr/index.html

A few notes on this behavior from BBR R&D:
Concourse uses the pg_dump utility for backing up a PostgreSQL database, which per definition makes consistent backups even if the database is being used concurrently. However, Concourse doesn’t perform table specification (evidence is that https://github.com/concourse/concourse-bosh-release/blob/master/jobs/bbr-atcdb/templates/config.json.erb doesn’t configured the tables property).
This may be occurring as a result of how Concourse uses the DB. This comment in pg_dump (https://github.com/postgres/postgres/blob/master/src/bin/pg_dump/pg_dump.c#L14-L23) leads me to believe that Concourse does frequent DDL like actions (evidenced by the name of the table in question public.build_event_id_seq_4327391). Because of this Concourse ought to implement locking or change how they use an RDMS. The table name leads me to believe that DDL activity is happening often

* Concourse version:6.3.0
* Browser (if applicable):
* Did this used to work? No

**Comment by scottietremendous** [comment]
@Hermen-Nicolau - Let's fine some time to pair on this in the next week or so

**Comment by Hermen-Nicolau** [comment]
@scottietremendous I'm scheduling a working session for tomorrow and if someone can join me we can go over this particular issue. I will reach out through our internal channels.

**Comment by taylorsilva** [comment]
@xtremerui and I have been doing a bunch of brain storming. The general solution we've fallen on is to connect to the db before starting the backup to pause all components:
```sql
UPDATE components
SET paused = true;
```
running the backup binary from the [backup-and-restore-sdk-release](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release) and then unpausing all components
```sql
UPDATE components
SET paused = false;
```

We would do the same for the restore path.

The problem we're having is determining the best way to connect to the database. We have all the info we need in `config.json` that the `bbr-atcdb` job generates, but we don't have a nice way capture all those connection details and pass them to `psql` (which is available to us from the backup-and-restore-sdk-release). Actually, the hard part is when SSL is required for the connection. We need to pass in all certs/key via file paths and we don't have a nice way of storing all those certs/keys in files. We may just copy code from https://github.com/concourse/concourse-bosh-release/blob/master/jobs/web/templates/pre_start.erb to store the certs/keys in files.

**Comment by taylorsilva** [comment]
Docs are super clear on how this works, but an alternative may be https://postgresqlco.nf/doc/en/param/default_transaction_read_only/

**Comment by clarafu** [comment]
Hi @Hermen-Nicolau I'm curious to know what exactly Concourse is configuring wrong in https://github.com/concourse/concourse-bosh-release/blob/master/jobs/bbr-atcdb/templates/config.json.erb so that `pg_dump` cannot acquire `AccessShareLocks` on the tables so that database operations can be performed without any downtime?

**Comment by taylorsilva** [comment]
@clarafu there is nothing further we can configure/set in `config.json`. All options for it are listed here https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/blob/develop/docs/database-backup-restore.md#config-options

`config.json` has mainly connection info details. We can't change the behaviour of the bbr-sdk :(

**Comment by taylorsilva** [comment]
@Hermen-Nicolau Check out the PR and let us know your thoughts.

This issue could still happen but we tried to make the backup process more resilient. Basically you would want to run `pg_dump` when no builds are going to finish while `pg_dump` is running. We can see if builds are currently running but we have no way of figuring out if a build is going to finish in 1s from now, 2hrs from now, 4mins from now.... you get the idea. You don't want a build finishing while `pg_dump` is running because concourse will then `DROP` a `public.build_event_id_seq_####` table. We hope the stuff we added will workaround this problem.

**Comment by Hermen-Nicolau** [comment]
@taylorsilva I have been following all that you guys have added and I think that adding a call to the bbr backup binary up to three times if it fails might do the trick. Most if not all the times we have seen this, a retry immediately fixes the issue. If we are not able to actually put a lock on the database before the BBR the suggestions on the PR seem like a good solution.

**Comment by taylorsilva** [comment]
@Hermen-Nicolau The problem with the locking/read-only method is that it only works on new connections to postgres. We'd have to restart the web nodes and there's no way to do that from the backup job. So that solution ended up not being viable.
