### ISSUE TITLE
Add a fly subcommand to logout

### ISSUE THREAD

**Issue by timbod7** [concourse/concourse#660]
In an environment where security is a concern, we don't want to leave targets (with their associated tokens)  in `~/.flyrc` longer than necessary. Whilst it is possible to manually edit the file, it would be more convenient (and scriptable) to have a logout subcommand:

```
fly -t sometarget logout
```

**Comment by mkreibe** [comment]
Added. Also added a `-a` or `--all` where the target is not required, and this deletes all targets from the file.

**Comment by mkreibe** [comment]
Documentation was added with this [Pull request](https://github.com/concourse/concourse/pull/691)
