### ISSUE TITLE
`fly watch -b` broken on 2.2.0

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#661]
It works fine with `-j`, but refuses to run with only `-b`, which seems like a problem for some use cases, like `fly execute`. I'm using the `ids` in the first column of `fly builds`, as recommended in the release notes.

Error message returned:
```
error: failed to get build pipeline name required
```

**Comment by jvshahid** [comment]
I'm seeing that as well. I think this is even the case pre-2.2.0.

**Comment by hfinucane** [comment]
Works in 1.6, I managed to miss much of the 2.x series.
