### ISSUE TITLE
7.0.0 breaks build related metrics

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#6614]
## Summary

We have upgraded a test cluster to 7.0.0, then we found that, as 7.0.0 changes `check`s to run as builds, the metrics`BuildStarted`, `BuildFinished` etc. now include `check` builds, which breaks existing dashboards/reports.  

From resource consumption perspective, I agree `check` builds are not much different from normal builds. But from other perspective, we regularly monitor normal build status and generate report on team level builds. This change causes us to have to add a filter criteria `build_name != "check"` to all build queries.

I feel Concourse should exclude `check` builds from build metrics. I see there is a `ChecksStarted` already, we can easily add a new chart, but we don't want to update all existing charts.

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable): NA
* Did this used to work? Yes

**Comment by scottietremendous** [comment]
@evanchaoli  - You think we can/should introduce `JobBuildStarted`, `JobBuildFinished`, `CheckBuildStarted`, `CheckBuildFinished` as a way to solve this? 

Or alternatively can we add a tag to create more metadata?

**Comment by evanchaoli** [comment]
To me, I think we can just exclude check build count from `BuildStarted`. There is already `CheckStarted`, that is good enough. The other way is, keep `BuildStarted` and add a new `CheckBuildStarted`. In any way, we don't want to rename `BuildStarted` to `JobBuildStarted`. Refactoring checks to run as build is an internal thing, users don't have to realize that.
