### ISSUE TITLE
Support re-ordering instanced pipelines

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6617]
## Summary

Allow instanced pipelines to be re-ordered within their group from the UI/fly. Currently, instanced pipelines are displayed in the order they were created, and there's no way to manually re-arrange them.

Currently, it's required that instanced pipelines all have the same global ordering, and their IDs are used as a secondary ordering. This feature involves creating a new secondary ordering (perhaps a sub-ordering field in the DB?) and API endpoints to reorder an instance group

## Context

* Follow up to #6105, which omitted that feature for simplicity

**Comment by EstebanFS** [comment]
@taylorsilva and I think the fly command would look something like this
`fly oi -p my-pipeline -i first=var,second=another,third=lastOne -i first=var,second=anotherrr,third=lastTwo`

**Comment by EstebanFS** [comment]
A gotcha we ran into while thinking about the above format: what happens when the value is a complex type like yaml and contains commas already
```
fly oi -p my-pipeline -i "first={myKey: [1,2,3]},second=another,third=lastOne"
```
We can't split on the commas in this case.

**Comment by aoldershaw** [comment]
@EstebanFS @taylorsilva we already support something similar to this syntax for parsing instance vars
https://github.com/concourse/concourse/blob/2279a059b91fb8ad056d8e1037060965e40fefc7/fly/commands/internal/flaghelpers/pipeline_flag.go#L65

It uses `:` instead of `=`. Its logic is smarter than just splitting on commas, allowing for YAML with commas in it
