### ISSUE TITLE
Concourse bosh deployment issues

### ISSUE THREAD

**Issue by kondurupurandhar** [concourse/concourse#662]
Hi,

Using the below concourse.yml given in the "https://concourse.ci/single-page.html, getting the errors:
e replaced the valid entries and tried, but still getting the error as **" Failed: Instance group 'web' references an unknown vm type 'medium' (00:00:00)"**
I hav
ManifestFile:

---
name: concourse

# replace with `bosh status --uuid`
director_uuid: REPLACE_ME

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: REPLACE_ME
  vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # this instance group to your ELB
  - REPLACE_ME
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: REPLACE_ME

      # replace with username/password, or configure GitHub auth
      basic_auth_username: REPLACE_ME
      basic_auth_password: REPLACE_ME

      # replace with your SSL cert and key
      tls_cert: REPLACE_ME
      tls_key: REPLACE_ME

      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: REPLACE_ME
  stemcell: trusty
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: REPLACE_ME
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: REPLACE_ME
        password: REPLACE_ME

- name: worker
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: REPLACE_ME
  vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # sufficient ephemeral storage to VMs in this instance group.
  - REPLACE_ME
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

Error: 

Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 15781
  Started preparing deployment > Preparing deployment. Failed: Instance group 'web' references an unknown vm type 'medium' (00:00:00)

Error 140004: Instance group 'web' references an unknown vm type 'medium'

Task 15781 error

For a more detailed error report, run: bosh task 15781 --debug

--------------------

Please help me the right manifest file for BOSH concourse deployment.

Regards
Purandhar

**Comment by jtarchie** [comment]
@kondurupurandhar, it appears that you didn't setup your cloud config correctly. The [documentation](https://bosh.io/docs/cloud-config.html) gives examples of `vm_types`. For concourse, setup `vm_types` for `web` and `worker`.

**Comment by vito** [comment]
What @jtarchie said - you need a VM type `medium` in your cloud config.
