### ISSUE TITLE
fly.exe unable to authenticate to concourse server

### ISSUE THREAD

**Issue by poida** [concourse/concourse#664]
I'm trying to run `fly` against concourse (v2.2.0) that is using git hub authentication. After doing `fly login` to the server and pasting the token as instructed, `fly` commands against the server fail with error message:

```
c:\> fly login -t targetname -c concourseurl
    <-snip-pasted-token->
c:\> fly -t targetname workers
not authorized. run the following to log in:
    fly -t targetname login
```
## Work-Around

The following steps seem to work, indicating that they way `fly` sets the token is incorrect:
1. Do `fly login` to your concourse server and do as `fly` says, authenticating in the browser and pasting the token.
2. When the login process is complete, manually copy the token into your `%USERPROFILE%\.flyrc` file from the browser, stripping off the `Bearer` part. Ensure you are updating the correct entry for the corresponding target.
3. Run `unix2dos` on the `%USERPROFILE%\.flyrc` file.
4. Profit!

(if you need unix2dos - http://dos2unix.sourceforge.net/)

**Comment by vito** [comment]
Can you confirm that you've pasted the full token with `Bearer` and such at the start?

**Comment by poida** [comment]
@vito yes, full token. It rejects the action on the command line if I don't include the `bearer` part.

**Comment by jama-pivotal** [comment]
We'll need to bump go interact, but once its done this should be fixed (https://github.com/vito/go-interact/commit/8355fc314be16c98d654c45ee419fa30b3558028)

**Comment by vito** [comment]
bumped!

**Comment by titan2215** [comment]
This is happening to me as well
