### ISSUE TITLE
fly: ignore proxy

### ISSUE THREAD

**Issue by killermoehre** [concourse/concourse#667]
Hi,

I would love an option in .flyrc to choose to ignore the proxy set with $http_proxy instead of prefixing fly always.

**Comment by databus23** [comment]
Why not just add the concourse host to the $no_proxy env var? No need for a specific flag in fly.

**Comment by killermoehre** [comment]
Because $no_proxy can only be used if you have a hostname (+domain). If you access the API by IP (as necessary at $workplace), than $no_proxy is no option.

**Comment by vito** [comment]
This feels weird. The point of setting `http_proxy` is to tell it to use a proxy. I don't believe that every tool should both implement support for these vars and then implement a tooling-specific way of then ignoring those vars. They just shouldn't be set.

You could have a wrapper in your shell or on your `$PATH` that just unsets the var instead.

**Comment by databus23** [comment]
@killermoehre As a closing remark no_proxy also works for ip addresses, just add then the same was as hostnames.
