### ISSUE TITLE
Provisioning with Vagrant page is gone

### ISSUE THREAD

**Issue by benmoss** [concourse/concourse#67]
The README links to http://concourse.ci/deploying-with-vagrant.html, which seems to have disappeared. The [file](https://github.com/concourse/concourse/blob/master/docs/deploying/vagrant.any) is still there, so I have no clue what would be going wrong.

**Comment by vito** [comment]
Sorry, will fix. The page it should be linking to is now http://concourse.ci/getting-started.html

**Comment by vito** [comment]
Updated the README. Thanks for the notice!
