### ISSUE TITLE
More control over container deletion.

### ISSUE THREAD

**Issue by shijinabraham** [concourse/concourse#671]
Hi,

We faced a situation where the build task passed, but the later stage using the artifact produced in the build failed and we wanted to examine the build task container, but that was gone.   Also we have long running task where the cost of keeping the containers around is less than that of running the tasks again. 

As I understand the  containers of successful tasks are kept for  5 minutes and failed containers are kept until the next build. Can the following be made configurable

1) Amount of time successful task container is kept around
2) Number of any container to be kept around

**Comment by vito** [comment]
All containers for a failed build are kept around, even the ones that were for a successful task. Were you seeing otherwise?

**Comment by shijinabraham** [comment]
Isn't the successful containers deleted after 5 minutes?  I was making more of a feature request where this 5 minutes is configurable and the number of containers that should be kept is also configurable

**Comment by vito** [comment]
*All* containers in a *successful* build are reaped after 5 minutes.

*All* containers in a *failed* build are either: kept indefinitely, if the build is the latest one, or reaped after 5 minutes.

**Comment by shijinabraham** [comment]
Is it possible to make the 5 minutes configurable. We have a usecase where we might want to examine the contents of a containers of a successful build?

**Comment by vito** [comment]
Rather than making it configurable, is there a way your build could tell Concourse to keep it? I would rather not let that value be changed as we're likely to switch to immediate removal soon anyway.

**Comment by chendrix** [comment]
This issue has been open a while and has become stale. I'm going to close it now.
