### ISSUE TITLE
Are there build instructions? Yarn command fails.

### ISSUE THREAD

**Issue by yurivict** [concourse/concourse#6712]
I couldn't find build instructions in the documentation: https://concourse-ci.org/install.html The "Install" section doesn't contain instructions how to build it.

-------------------------

From the Arch port build procedure I concluded that the first command is probably "yarn" (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=concourse).

But the ```yarn``` command fails:
```
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/5] ⠠ elm
[-/5] ⠠ waiting...
[3/5] ⠠ elm-format
[4/5] ⠠ elmi-to-json
error /usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer
Output:
/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/helper.js:279
    throw new Error(message);
    ^

Error: Unsupported platform: freebsd
    at assert (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/helper.js:279:11)
    at new BrowserFetcher (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/BrowserFetcher.js:96:7)
    at module.exports.createBrowserFetcher (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/Puppeteer.js:82:12)
    at Object.<anonymous> (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/install.js:39:34)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
```

-----------------------

Another concern is that NodeJS is a security risk - it downloads packages straight from GitHub and runs them immediately.

Could you please make pre-built web frontend available as a separate tarball? The Authelia project does this: 
https://github.com/authelia/authelia/releases, for example.

**Comment by taylorsilva** [comment]
> From the Arch port build procedure I concluded that the first command is probably "yarn" (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=concourse).

Didn't know about this. We don't maintain (or even know about) that port. None of the people listed as users/maintainers on that are familiar to me in the Github or discord community. 

You can find our pre-built web and worker tarballs on the release page: https://github.com/concourse/concourse/releases

**Comment by yurivict** [comment]
> You can find our pre-built web and worker tarballs on the release page: https://github.com/concourse/concourse/releases

I'm only seeing pre-built binaries at this URL. Where are the web tarballs?

-----------------------

Another question is: What is the minimal set of node modules required to run Concourse? What causes concern is the "puppeteer``` module that fails on FreeBSD (see error in the OP), Puppeteer downloads binaries of various browsers (see here https://github.com/puppeteer/puppeteer/blob/main/experimental/puppeteer-firefox/lib/BrowserFetcher.js)

Downloading binaries is problematic on many levels:
1. Downloaded binaries might be compromised. Their origin, who compiled them is unclear.
2. We already have all browsers installed from packages.
3. Why having externally built browsers is required to run Concourse?

Concourse build is failing because browser binaries aren't available for FreeBSD. Are they really required?

**Comment by taylorsilva** [comment]
Going to convert in a discussion since there's no bug here.
