### ISSUE TITLE
ATC's Default peer url remains 127.0.0.1:8080 when bind port is changed

### ISSUE THREAD

**Issue by donaldguy** [concourse/concourse#672]
I `setcap 'cap_net_bind_service=ep'`'ed my concourse standalone binary so it could bind 443 as non-root. I also set bind-port to 80 to enable the redirect, but I didn't think to change peer-url. This has left all my workers just spewing

```
{"timestamp":"1475005985.415484667","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-register","log_level":2,"data":{"error":"Post http://127.0.0.1:8080/api/v1/workers?ttl=1m0s: dial tcp 127.0.0.1:8080: getsockopt: connection refused","remote":"172.31.39.102:58274","session":"5.1.8"}}
```

into their logs and no jobs running.

I didn't notice this for a while. Probably the default value should follow the bind port.

**Comment by donaldguy** [comment]
(setting CONCOURSE_PEER_URL to 127.0.0.1:80 and restarting atc does indeed restore jobs to running)

**Comment by jinlee** [comment]
I also saw this, had to revert to the default `8080` port on version `2.4.0`.

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/2519
