### ISSUE TITLE
Database migration failed - from 6.7.3 to 7.1.0

### ISSUE THREAD

**Issue by Berber31** [concourse/concourse#6725]
## Summary

Database migration failed (in init-container, running with `migrate --migrate-to-latest-version` args) upgrading concourse 6.7.3 to 7.1.0.

## Steps to reproduce

Concourse 6.7.3 already deployed and started.
Upgrade concourse to 7.1.0 deploying with concourse helm chart v15.0.1.

## Expected results

Init container (running with `migrate --migrate-to-latest-version` args) successed migrating concourse DB

## Actual results

Init container (running with `migrate --migrate-to-latest-version` args) crashed (almost instantly) with this log: 
` error: migration '1606068653_build_events_partitions_bigint.up.sql' failed and was rolled back: pq: index "pipeline_build_events_14_build_id" does not exist                 │
│ stream closed  `

## Additional context

Helm chart deployment v15.0.1.

## Triaging info

* Concourse version: 7.1.0
* Browser (if applicable): NA
* Did this used to work?

**Comment by taylorsilva** [comment]
What version of postgres are you using?

**Comment by xtremerui** [comment]
this seems like an issue caused by the DDL operations on going while migrations runs. @Berber31 could you give how many web nodes are there in the cluster?

**Comment by Berber31** [comment]
> this seems like an issue caused by the DDL operations on going while migrations runs. @Berber31 could you give how many web nodes are there in the cluster?

Only 1 instance

**Comment by clarafu** [comment]
Hm maybe we should only delete or alter those indexes if they exist, so add an `IF EXISTS` to those lines

https://github.com/concourse/concourse/blob/2279a059b91fb8ad056d8e1037060965e40fefc7/atc/db/migration/migrations/1606068653_build_events_partitions_bigint.up.sql#L11-L12

**Comment by taylorsilva** [comment]
@Berber31 how many times was the entire migration process attempted? Did you try once and then give up? Or did this happen every time you ran it?

Our current theory is that this is a race condition, where a pipeline gets deleted in the middle of the migration, so suddenly some tables we thought exist no longer do. If our theory is correct, it's extremely unlikely that you would run into this same error multiple times in a row.

**Comment by Berber31** [comment]
> What version of postgres are you using?

@taylorsilva 

postgresql:11.8.0-debian-10-r76 


> @Berber31 how many times was the entire migration process attempted? Did you try once and then give up? Or did this happen every time you ran it?
> 
> Our current theory is that this is a race condition, where a pipeline gets deleted in the middle of the migration, so suddenly some tables we thought exist no longer do. If our theory is correct, it's extremely unlikely that you would run into this same error multiple times in a row.

@taylorsilva 
yes, i tried several times to migrate.

i also tried to rollback following this https://concourse-ci.org/concourse-web.html#downgrading 
and then try migrate again, with the same result

is there any debug/verbose options to get more log to provide ?

**Comment by taylorsilva** [comment]
How odd. If you do `select count(*) from pipelines where id=14;` in the Concourse database, do you get a pipeline back?

**Comment by taylorsilva** [comment]
Also, the error it's printing already tells us everything we need to know. Sorry for not stating that earlier. It's telling us that there's a pipeline with id 14. That means there should be an index named `pipeline_build_events_14_build_id` but there isn't. The index should have been created on a table named `pipeline_build_events_14`. You could check to see if that table exists and if there's an index with that name on it.

**Comment by Berber31** [comment]
> in the Concourse database, do you get a pipeline back?

Yes there is a pipeline with id 14

and table pipeline_build_events_14 exists

**Comment by taylorsilva** [comment]
Does it have an index `pipeline_build_events_14_build_id` on it?
```sql
SELECT
    tablename,
    indexname,
    indexdef
FROM
    pg_indexes
WHERE
    tablename = 'pipeline_build_events_14_build_id'
```

**Comment by Berber31** [comment]
no, there is no index `pipeline_build_events_14_build_id` on it

**Comment by taylorsilva** [comment]
hmm that's the mystery then, why did you not have an index on that table? Have you been able to get around this error though and upgrade?

**Comment by bgandon** [comment]
Migrating from Concourse v6.7.5 to v7.6.0 I get some similar error: `error: failed to connect to database: migration '1606068653_build_events_partitions_bigint.up.sql' failed and was rolled back: pq: relation "team_build_events_6" does not exist
`
