### ISSUE TITLE
Checksums should be published for concourse binaries

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#674]
This would give people more confidence in their use of release binaries. Currently I download them and compute the checksum myself, and then plug that into my deployment.

SHA256 is popular with configuration management systems, and sha1 and md5 are popular with humans.

**Comment by xoebus** [comment]
I think signing them would be useful too.

**Comment by joonas** [comment]
Just wanted to chime in that I'm a big fan of this idea.

**Comment by vito** [comment]
Oh hey this is done now (as of v3.13+).
