### ISSUE TITLE
Metric tasks_waiting should be labeled with team name instead of team numeric ID

### ISSUE THREAD

**Issue by marco-m-pix4d** [concourse/concourse#6751]
## Context

Concourse supports multiple teams. Each team is added with a name, and Concourse assigns to it a numeric ID that is stored in the Concourse database and is (correctly) persisted also if the associated team is removed.

The ID is auto incremented each time a team is added, so if two Concourse instances at a certain point in time have the same teams, but one of them in the past added and deleted some other teams, the corresponding team IDs will be different.

For example, assume Concourse P is in production and Concourse S is in staging.

Concourse P:
- add team `foo` (ID will be 1)
- delete team `foo`
- add team `bar` (ID will be 2)

Concourse S:
- add team `bar` (ID will be 1)

As long as the team ID is used only internally, this discrepancy has no effect. Unfortunately the team ID leaks to the outside world via Prometheus metrics.

## Problems

The metric `concourse_tasks_waiting` is not labelled by team name but by team ID. This causes two problems:

### 1. autoscaling decisions

Such metric can be used to take autoscaling decisions (spawn additional Concourse workers VMs).

Since the team ID is used, according to the “Context” section, this means that the staging and prod environment cannot share the same autoscaling rules, since the same team `bar` has ID 2 in prod and ID 1 in staging.

This causes either staging being unable to reproduce prod, or even worse, introduce a scaling bug in prod after having obtained a correctly working configuration in staging. (This is what happened to us and triggered this ticket).

### 2. display

The display of the metric on Grafana is not human understandable, since it will show teams with their numeric IDs instead than with their names. (This impacts everybody displaying these metrics).

## Proposed fix

All metrics that use the team ID should use the team name instead, starting with metric `concourse_task_waiting`.

Two approaches are possible:
1. Breaking change. Replace the team ID with the team name.
2. Non breaking change: Add the team name as an additional label. This has the drawback of increasing the cardinality of all the impacted metrics, so at least from our point of view this is not worth it.

**Comment by pnsantos** [comment]
Metric is now `concourse_steps_waiting` btw. Still has the same "issue" though, the team ID is not really all that useful, people (operators/users) know the team names not IDs.

**Comment by marco-m-pix4d** [comment]
@pnsantos you are right, thanks, I forgot to update the ticket with this change. BTW my team is working on a PR.

**Comment by marco-m-pix4d** [comment]
Thanks @Esysc for the implementation and thanks @taylorsilva for shepherding the PR.

**Comment by robwhitby** [comment]
This is a handy change but unfortunately the metric `concourse_steps_waiting` was missed - it still does not have `teamName` as of 7.4.0

**Comment by marco-m-pix4d** [comment]
@robbyice thanks for reporting. We will look into it.
