### ISSUE TITLE
Feature request: ability to limit number of tasks per worker

### ISSUE THREAD

**Issue by hryamzik** [concourse/concourse#676]
Let's say you run tests with iOS simulator on OSX worker. Multiple simultaneously running task may conflict.

> I'd model it as something more general though, i.e. have tasks marked with a uniqueness identifier and a max-in-flight-per-worker associated with it, rather than having a worker say it can only run one thing at a time © @vito.

**Comment by hryamzik** [comment]
That's also useful for resources to avoid multiple simultaneous puts at the same time.

**Comment by matt-royal** [comment]
This would be very helpful for my team. In our case, we need to ensure that a given worker is only running 1 instance of a specific task (since the task will fail if it has to compete for resources).

**Comment by oppegard** [comment]
This would be useful for the Pivotal Tracker team to prevent overload of workers (assuming that Concourse would schedule jobs on workers with less container utilization).

**Comment by baszalmstra** [comment]
This would be useful to run graphics heavy tests on a worker and not overload the worker with multiple tests.

**Comment by mervyn777** [comment]
Any updates on this issue. I'm having the same problem when more than one job is run simultaneously on the Darwin worker, even if the jobs are in different pipelines triggered by their corresponding git commits. Other than the first one, that started using the worker resource, the rest of the jobs fail. They will have to be manually triggered one after the other to pass. Is there some workaround to this. This is a huge limitation and defeats the whole purpose of setting up concourse on darwin if the max number of jobs cannot be overridden and set to 1.

**Comment by clarafu** [comment]
@mervyn777 Sorry, this issue is currently not prioritized so it might be a bit until it gets worked on. You might be able to use the pool-resource as a workaround to ensure that only one task is being run at a time.

**Comment by mervyn777** [comment]
@clarafu : Thanks for that great resource! Solves my problem for the moment. Is it possible to get a lock for individual tasks within a job? So that no 2 similar tasks run in different pipelines but the jobs can run concurrently as long as they are running different tasks requiring different resources.

**Comment by msarahan** [comment]
I recommend also adding a Windows label, but more broadly, this is a critical feature for any system where docker containers are not an option.

**Comment by leshik** [comment]
I'd like to have such an option, too – but unrelated to macOS. In my case, there are not very powerful VPS in the cloud that currently hosts ATC & TSA along with a worker, and also the much more powerful server in office as an external worker. Something like worker weight would be very helpful to schedule workload to office server more often than to the cloud one.

**Comment by ddadlani** [comment]
This is related to https://github.com/concourse/concourse/issues/2928, which is currently in progress.

**Comment by ddadlani** [comment]
Closing this since it has been implemented in #4118
