### ISSUE TITLE
containerd not populating /etc/hostname

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#6811]
## Summary

Running `hostname --fqdn` returns an error when using the containerd runtime. It does not return an error when using guardian.

## Steps to reproduce

Bring up concourse with a worker using `CONCOURSE_RUNTIME: containerd`.

Bring up a container
```
fly -t dev sp -p test -c topgun/pipelines/task-waiting.yml
fly -t dev up -p test
fly -t dev tj -j test/simple-job
```
Intercept the container and run `hostname --fqdn`.

## Expected results

A hostname is printed.

## Actual results

Error is thrown
```
hostname: Name or service not known
```

## Additional context

Error is returned because `/etc/hosts` is not populated. If you look at `/etc/hosts` on a container started with containerd you'll see
```
$ cat /etc/hosts
127.0.0.1 localhost
```
While with guardian:
```
$ cat /etc/hosts
127.0.0.1 localhost
10.80.0.10 fd3610f2-5c06-42a0-669b-a8a437d1a9ca
```

Related PR https://github.com/containerd/cri/pull/1042

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?

**Comment by staylor14** [comment]
I actually believe that the problem is that `/etc/hostame` is empty.  The fact that `/etc/hosts` is also not populated may be related to this issue, but is not the direct cause.

**Comment by jwatson0** [comment]
+1 - I have a build task that expects the hostname to be listed in /etc/hosts and accessible via that IP.  Going back to guardian runtime for now.

**Comment by simonjohansson** [comment]
We are also hitting this issue.
