### ISSUE TITLE
Concourse README badges working in github?

### ISSUE THREAD

**Issue by rothgar** [concourse/concourse#683]
I was trying to add a badge to a README at cloudfoundry-incubator/datadog-firehose-nozzle#13 but the badge svg picture always shows broken. I found other repos that also appeared to have broken badge images from concourse and it appears all of the working badges I've seen have image suffixes (.svg, .png, etc.) but the documentation [here](http://engineering.pivotal.io/post/concourse-badges/) says concourse doesn't add a suffix. I tried adding one anyway and the links don't work.

Is this a known issue? Maybe it's just me. If it is a problem is there a way to fix this from the README url or does it require an api update to add the suffix?

**Comment by vito** [comment]
Seems to work for us: https://github.com/concourse/atc/blob/master/README.md

**Comment by rothgar** [comment]
It was suggested I use http://crossorigin.me/ which appears to work in this PR and also from this example https://github.com/cloudfoundry/dropsonde/pull/21/files

I'm still not sure why it seems to work in some cases but not others.

**Comment by xoebus** [comment]
Do you have an Nginx (or alike) inserting the CORS headers into the Concourse responses?

**Comment by rothgar** [comment]
I don't control the instance (just a contributor) so I'm not sure what is going on on the back end. If it's working for others I'll just close this because it appears to only be select repos that are broken.
