### ISSUE TITLE
Documentation for placement strategy out of date? ("limit-max-containers" not valid)

### ISSUE THREAD

**Issue by chbiel** [concourse/concourse#6831]
## Summary

The documentation gives an example what can be set: https://concourse-ci.org/container-placement.html#chaining-placement-strategies

The release notes say something similar: https://github.com/concourse/concourse/releases/tag/v7.0.0

> Add new container placement strategies: limit-max-containers and limit-max-volumes

Error logs says:
> error: Invalid value `limit-max-containers' for option `--container-placement-strategy'. Allowed values are: volume-locality, random, fewest-build-containers, limit-active-tasks, limit-active-containers or limit-active-volumes

## Steps to reproduce

Use v7.1.0

Configure concourse with
```
CONCOURSE_CONTAINER_PLACEMENT_STRATEGY=limit-max-containers,limit-max-volumes,volume-locality,fewest-build-containers
CONCOURSE_MAX_ACTIVE_CONTAINERS_PER_WORKER=150
CONCOURSE_MAX_ACTIVE_VOLUMES_PER_WORKER=75
```

Look at the logs and see the error

## Expected results

Documentation and code should be in sync, but I don't know what should be the correct state.

## Triaging info

* Concourse version: v7.1.0

**Comment by taylorsilva** [comment]
Derp, that's a typo! Thanks for catching that! It should be `limit-active-containers` and `limit-active-volumes`.
