### ISSUE TITLE
Pipeline UI crashes with circular pipeline dependencies

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#685]
I was playing around with the pool resource, and this pipeline: https://gist.github.com/hfinucane/ef0e2d7933b794492162b0a8aa5f3230 seems to lock Chrome up fairly reliably. I get a blank screen and screaming fans. Concourse 2.2.1, Chrome 53.0.2785.143.

**Comment by vito** [comment]
Yep, it's because the pipeline results in a circular dependency, which throws our graph code for a loop.

**Comment by jama-pivotal** [comment]
Closing the loop 🕶

**Comment by hfinucane** [comment]
Is that an official WONTFIX or did it get fixed?

**Comment by vito** [comment]
It's a WONTFIX, mainly because we don't really have the bandwidth to target this at a high enough priority. We may just redo the UI entirely before we get to this particular aspect.
