### ISSUE TITLE
Generic oAuth for Google Apps users

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#687]
Our team uses google apps. Using the "hd" parameter, users of concourse could plug google oauth into concourse and restrict the team to a particular (custom) domain.

https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

There are are some doubts whether it is effective though: http://stackoverflow.com/questions/34220051/oauth2-restrict-to-emails-with-specfic-domain-name-using-hd-not-working

Alternatively, we could implement this validation in (concourse) code before granting access. How would I go about writing a custom provider based on the generic oauth provider?

**Comment by vito** [comment]
Have a look at https://github.com/concourse/atc/tree/master/auth/genericoauth and https://github.com/concourse/atc/tree/master/auth/github - you could probably pattern-match your way through the code 'til things work.

**Comment by JohannesRudolph** [comment]
How would I go about installing my custom extension into an existing (docker-based) concourse installation? Do I need to build a full concourse installation + docker containers myself?

**Comment by vito** [comment]
I would run `atc` directly and skip the `concourse` binaries; they don't provide a very good feedback loop as they're so expensive to build.

This should be a good start:

https://github.com/concourse/atc/blob/master/CONTRIBUTING.md
