### ISSUE TITLE
Force resource check from web UI

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#688]
While developing a new pipeline a lot of time is spent waiting for something. Many times I will have the resource updated, but I will be stuck waiting for the next resource check. It will be nice if can force a resource check.

Note that for some resources like time resource for example - the force check might always detect new revision - ignoring the provided schema. This will allow for triggering the pipeline jobs, which by the ways is not covered from job (+) because it very often stuck waiting for resource updated versions.

**Comment by vito** [comment]
There's already a [`check-resource` command](https://concourse.ci/fly-check-resource.html). No button in the UI though.

**Comment by JamesClonk** [comment]
A UI button for forcing a `check-resource` on a particular resource would be **very** helpful, we're doing this a lot while developing (and its a pain to type in the fly command everytime, we have long pipeline / resource names 😄)
👍

**Comment by sampeinado** [comment]
@ggeorgiev and @JamesClonk are you imagining that this button would be shown on the pipeline view or on the individual resource page?

**Comment by JamesClonk** [comment]
@sampeinado I guess on the individual resource page.
Would be great to finally have this feature! 👍 
(Believe it or not, literally the most commonly used command on the fly cli for us currently is "check-resource". It would be great to not have to login and use the cli all the time just for this 😄)

**Comment by jama-pivotal** [comment]
This might be a good design snack for @sampeinado or @Lindsayauchin to pick up!

**Comment by Lindsayauchin** [comment]
Proposal to add a check resource button beside the status output for the resource check. 
## **Default:**
![screen shot 2018-08-08 at 10 38 01 am](https://user-images.githubusercontent.com/27746614/43844198-29fe1438-9af7-11e8-84da-38f6580815c0.png)
## **Active:** 
![screen shot 2018-08-08 at 10 43 48 am](https://user-images.githubusercontent.com/27746614/43844539-f8d91712-9af7-11e8-8c5e-b37f84d847b3.png)

**Comment by JamesClonk** [comment]
Looking good! :+1:

**Comment by wesm-outreach** [comment]
yes please

**Comment by jama-pivotal** [comment]
If you are not logged in you can click and be redirected to login (401 response)
if you are not authorized to do this (e.g. not part of the team), permanently leave it greyed out

This function is scoped to team member and above 

If the check itself fails, make sure to show the message in the UI

**Comment by pivotal-jamie-klassen** [comment]
## pending state
@Lindsayauchin loading state for the refresh icon -- maybe the `fa-circle-o-notch` until the `check-resource` call returns? Maybe the 'trigger check' button stays the same but the green check at the far right turns into a spinner?

**Comment by pivotal-jamie-klassen** [comment]
* check button is 28px x 28px square
* background color is #1e1d1d
* margin-right is 5px
* icon is https://material.io/tools/icons/?icon=refresh&style=baseline in white
* disabled := logged in but not authorized to check resource
* `opacity: 0.5` when disabled or enabled and unhovered
* `opacity: 1` when enabled and hovered
* change to white loading spinner on click and remove status icon (check/triangle)
* change back to refresh icon when check resolves
* update status according to response from check endpoint
   * if successful, show green check and re-fetch resource and versions
   * if unsuccessful, show orange exclamation triangle and re-fetch the resource
   * if 401, redirect to login

**Comment by Lindsayauchin** [comment]
## Updated design:

Disabled or enabled and unhovered:
<img width="1077" alt="screen shot 2019-01-10 at 3 00 31 pm" src="https://user-images.githubusercontent.com/27746614/50993831-95d14980-14e8-11e9-8bbe-3b13227c1cdf.png">
Enabled and hovered:
<img width="1078" alt="screen shot 2019-01-10 at 3 00 19 pm" src="https://user-images.githubusercontent.com/27746614/50993832-9669e000-14e8-11e9-9c99-bcb90ed91774.png">

**Comment by Lindsayauchin** [comment]
Adding asset: 
[resource_check_ic.svg.zip](https://github.com/concourse/concourse/files/2756038/resource_check_ic.svg.zip)

**Comment by pivotal-jamie-klassen** [comment]
* show `currently checking` when user clicks the refresh button
* show white refresh icon, no change on hover, default cursor when user clicks the refresh button
* when check resolves, go back the the above behaviours
