### ISSUE TITLE
Ability to execute a step once a job recovers

### ISSUE THREAD

**Issue by hryamzik** [concourse/concourse#689]
Travis and many other CIs support notifications on first success after 1+ failures. I'd love to see this in concourse as well as getting notified on every single build is a bit annoying.

**Comment by vito** [comment]
Rewording the title; "missing" implies that it was meant to be there. This is a feature request, not a bug.

**Comment by vito** [comment]
Probably best to just meld this into https://github.com/concourse/rfcs/issues/10 as the root of the request is notifications-specific.
