### ISSUE TITLE
Large pipeline_build_events tables in Postgresql

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#6892]
## Summary

Seeing ~50GiB of storage usage in Postgres in the atc database.

```CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN: 200``` is set

## Actual results

```
SELECT pg_size_pretty( pg_database_size('atc') );
pg_size_pretty 
----------------
 46 GB
```

Omitting any small tables in the summary...
```
              table_name        | row_estimate | total_bytes | index_bytes | toast_bytes | table_bytes |   total    |   index    |   toast    |   table    
--------------------------------+--------------+-------------+-------------+-------------+-------------+------------+------------+------------+------------
 pipeline_build_events_37       |   3.1397e+06 |  7692189696 |  1170931712 |      450560 |  6520807424 | 7336 MB    | 1117 MB    | 440 kB     | 6219 MB
 pipeline_build_events_58       |   3.1649e+06 |  1406099456 |   219668480 |       57344 |  1186373632 | 1341 MB    | 209 MB     | 56 kB      | 1131 MB
 pipeline_build_events_38       |   3.2804e+06 |  7732789248 |  1232650240 |       32768 |  6500106240 | 7375 MB    | 1176 MB    | 32 kB      | 6199 MB
 pipeline_build_events_39       |  1.70617e+06 |  3162284032 |   520151040 |      147456 |  2641985536 | 3016 MB    | 496 MB     | 144 kB     | 2520 MB
 pipeline_build_events_40       |  1.65486e+06 |  2761957376 |   474767360 |       73728 |  2287116288 | 2634 MB    | 453 MB     | 72 kB      | 2181 MB
 pipeline_build_events_41       |  1.89653e+06 |  2032214016 |   261038080 |       32768 |  1771143168 | 1938 MB    | 249 MB     | 32 kB      | 1689 MB
 pipeline_build_events_42       |  1.71394e+06 |  1632993280 |   270311424 |      139264 |  1362542592 | 1557 MB    | 258 MB     | 136 kB     | 1299 MB
 pipeline_build_events_44       |  1.54104e+06 |   925065216 |    79462400 |      933888 |   844668928 | 882 MB     | 76 MB      | 912 kB     | 806 MB
 pipeline_build_events_45       |  6.33945e+06 |  7613923328 |  1120288768 |      999424 |  6492635136 | 7261 MB    | 1068 MB    | 976 kB     | 6192 MB
 pipeline_build_events_46       |  7.17916e+06 |  7937892352 |  1252499456 |     1769472 |  6683623424 | 7570 MB    | 1194 MB    | 1728 kB    | 6374 MB
 pipeline_build_events_47       |  3.39602e+06 |  2932613120 |   512655360 |      622592 |  2419335168 | 2797 MB    | 489 MB     | 608 kB     | 2307 MB
 pipeline_build_events_48       |  1.30711e+06 |   462782464 |    77996032 |      909312 |   383877120 | 441 MB     | 74 MB      | 888 kB     | 366 MB
 pipeline_build_events_49       |  3.78245e+06 |  1970601984 |   284893184 |       81920 |  1685626880 | 1879 MB    | 272 MB     | 80 kB      | 1608 MB
 pipeline_build_events_56       |       182565 |   101154816 |     9306112 |       98304 |    91750400 | 96 MB      | 9088 kB    | 96 kB      | 88 MB
 pipeline_build_events_57       |  2.75644e+06 |  1330970624 |   193060864 |        8192 |  1137901568 | 1269 MB    | 184 MB     | 8192 bytes | 1085 MB
```

## Triaging info

* Concourse version: 6.7

**Comment by kallisti5** [comment]
The log reaping seems to be working as expected. Here's an example of older logs which were cleared:
https://ci.haiku-os.org/teams/continuous/pipelines/master-arm/jobs/haiku-master-arm/builds/1200

**Comment by clarafu** [comment]
I'm not sure what exactly the bug is here, I think a large `pipeline_build_events` tables is expected with large concourse clusters that run many builds. The log reaping should help remove old builds that will help with infinitely growing build events tables.

**Comment by kallisti5** [comment]
The bug is i'd expect pipeline_build_events to reduce?  We have 1500+ builds consuming 46 GiB of disk space with no CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN defined.

We set CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN to 200, and the logs were reaped.  Database disk usage didn't change much from the 46 GiB.  It "feels" like concourse / atc should have reaped more data from pipeline_build_events... but didn't.

**Comment by kallisti5** [comment]
I mean.. just one pipeline_build_events table has over 3 million entries for... 200 builds per CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN

**Comment by kallisti5** [comment]
Ok..  So I have this one figured out.

Since atc's pipeline_build_events tables have grown so large historically, we're in desperate need of a
```VACCUM ANALYZE; ``` and a ```VACCUM FULL pipeline_build_events_X;```  on each table to reclaim space in postgresql. 

Essentially setting CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN on it's own isn't enough to free additional disk space from postgresql, and we also need to manually vaccum these tables individually to clean up disk usage.


We were at 46GiB. After the vaccum we're down to 14GiB
