### ISSUE TITLE
Rerun Job when Worker Disappears Infinite Retry

### ISSUE THREAD

**Issue by maxknee** [concourse/concourse#6919]
## Summary
We run a fairly large cluster 6 ATCs, 30~ish workers, we've recently upgraded from 6.4.1 to 6.5.1 and turned on `ENABLE_RERUN_WHEN_WORKER_DISAPPEARS`, since then we've seen some behavior where it ends up an a loop trying the same worker over and over again. This happens intermittently and not all jobs that have a worker disappear on them exhibit this behavior. 

## Steps to reproduce
Job runs, but not sure where the worker disappearing happens
https://gist.github.com/maxknee/b93adb93db1bde8b9cfae17cd7492518

## Expected results

Job to land on new worker

## Actual results

Job tries to land on the same worker or different worker over and over again
Need to go and mark the job as aborted in the database to ensure it's fully cancelled.
## Additional context

Given the variability of jobs that run it's hard to know if a job knocks a worker offline and causes it to spin indefinitely. 

## Triaging info

* Concourse version: 6.5.1
* Browser (if applicable): Chrome/Firefox
* Did this used to work? Not sure

**Comment by evanchaoli** [comment]
There is a fix in 6.7.6 that prevents such retry from an aborted build.

**Comment by maxknee** [comment]
@evanchaoli do you have a link to the fix?

**Comment by evanchaoli** [comment]
@maxknee #6197 made the fix to master, and #6598 back ported the fix to 6.7.x.
