### ISSUE TITLE
Pipeline menu opens with no content 50% of the time

### ISSUE THREAD

**Issue by ctaymor** [concourse/concourse#692]
We're seeing this bug quite often:
I'm in a job view, looking at the logs for a build. I click the hamburger menu to open the menu to go to a different pipeline. The menu opens, but has no content. I close the menu and reopen it, still no content.

I have not seen this from the pipeline view, only from the job view. However, we are seeing this about 50-75% of the time from the job view. We're on concourse 2.2.1. We recently upgraded from 1.6.0, where we did not see this problem.

![screen shot 2016-10-11 at 10 07 41 am](https://cloud.githubusercontent.com/assets/4574361/19280519/137b39b6-8f9b-11e6-830b-0e4893aa739e.png)

**Comment by vito** [comment]
this is fixed; it's actually there but scrolls with the page. haven't shipped in a while; waiting for a story to land.

thanks!

**Comment by ctaymor** [comment]
Okay, thanks!
