### ISSUE TITLE
Resource version shows as output of build twice

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [concourse/concourse#693]
<img width="945" alt="screen shot 2016-10-11 at 11 29 08 am" src="https://cloud.githubusercontent.com/assets/3108318/19283274/12cdc38e-8fa6-11e6-84b3-e871b7e88457.png">

We see the resource version is output of "rc" build `#23` and `#23` twice.

You can see this here: https://runtime.ci.cf-app.com/teams/main/pipelines/cf-release/resources/cf-release-release-candidate

**Comment by vito** [comment]
Yeah that page has been the redheaded stepchild of our UI for a while. We'll be killing it soon in favor of something much cooler, so I'll close this out for now.
