### ISSUE TITLE
REST api v1 with Concourse v2 does not authenticate with HTTP basic auth

### ISSUE THREAD

**Issue by dsharp-pivotal** [concourse/concourse#697]
We were trying to set up Checkman to work with teams. We saw in the Checkman code that @Amit-PivotalLabs [updated it](https://github.com/cppforlife/checkman/commit/5cc6113a7b114367d56ef8b726630bac9da2e3a6) -- thanks Amit!

To give Checkman access to our Concourse instance for which we don't even want to make the pipelines public (need to be signed in to see even the status / shape of the pipeline), we provide both Github OAuth and basic HTTP auth for the `main` team via the BOSH deployment manifest.

To recreate:
- On a concourse v2 instance, configure a team (could be main or another team, we tried both) to have http authentication
- set a pipeline for that team; do not make the pipeline public.
- In a new browser window, confirm that the simple Username + Password login is working
- from the terminal, run `curl http:///api/v1/teams/<team-name>/pipelines/<pipeline-name>/jobs/<job-name>' -u 'username:password' -i`; observe the 401 Unauthorized response

This was working in Concourse v1.x (pre-teams feature). We realize that this is an edge case, and you do say that the API is not a supported interface. In particular, Checkman is not a main workflow, http authentication should be discouraged, and you probably want to encourage use cases where people are comfortable having the broader pipeline public (still keeping job details private). `fly checklist` still exists, but doesn't do anything to support passwords.

Thanks!
-- d# and @cjcjameson

**Comment by vito** [comment]
This was an intentional change; see https://github.com/concourse/atc/issues/42 for what'd end up being the long-term solution. Thanks for the details though!

**Comment by jagregory** [comment]
So is there no way to make Checkman work now without making your pipelines public?
