### ISSUE TITLE
No visible error messages when resource can no longer pull

### ISSUE THREAD

**Issue by aarondl** [concourse/concourse#699]
I have a Github resource, it fails to pull because of bad credentials being pushed (after good credentials had been in and working for some time).

When I visit the web UI I don't see any kind of error message anywhere about the resource, it looks green and happy. However when I go to my build it's stuck forever in "pending" with the check "waiting for a suitable set of input versions" remaining to be checked (it's the circle icon and grey).

In the atc logs I found an error message that said:

``` text
{"timestamp":"1476384318.388684034","source":"atc","message":"atc.handler.get-build.failed-to-get-build","log_level":2,"data":{"build":"44","error":"not authorized","job":"build-all","pipeline":"test-pipeline","session":"5692628.1"}}
```

This was hard to debug, these errors should be surfaced to the user in the resource/inputs area of the UI and in the past was - at least for new pipelines that had never pulled their resources the first time. I wonder if this is the only error being swallowed for resources that fail to pull after some time.

**Comment by aarondl** [comment]
It's also worth it to mention that the pipeline was unrecoverable after this. I could see the new inputs, but they were never being picked up and the same behaviour continued until I destroyed the pipeline and re-pushed it.

**Comment by vito** [comment]
That log line seems unrelated.

Resources that are misconfigured should go orange (errored color) in the pipeline - however there's currently a bug where resources that only show up as outputs do not go orange. Do you think that's the same issue?

To confirm, you could click the resource's box in the pipeline - if you see an error message there (you should, under the 'checking failed' header), then it's just that issue.

**Comment by aarondl** [comment]
The resource box in the UI was green. And all the refs inside it were green. There was no indication of failure anywhere in the system that I could see from the UI (at least that I know about).

**Comment by aarondl** [comment]
And are you sure that log line is unrelated? It was for the specific build that was failing to start, and indeed the problem was that it wasn't able to auth because I had put in a bad credential.

**Comment by vito** [comment]
Resource boxes aren't green; they're either black (and possibly semitransparent) or orange.

That log line is from the web UI, saying the user isn't authorized.

**Comment by charlieoleary** [comment]
For what it's worth, I've had this happen in relation to https://github.com/concourse/concourse/issues/707 -- when the worker that was performing the check disappears the ATC never reassigns that task, so it just kind of sits in limbo.  It still remains black and doesn't indicate any sort of failure or lack of assignment.
