### ISSUE TITLE
concourse.ci still doesn't have a favicon

### ISSUE THREAD

**Issue by zaksoup** [concourse/concourse#70]
nuff said

**Comment by xoebus** [comment]
what?

![screen shot 2015-07-16 at 1 41 32 pm](https://cloud.githubusercontent.com/assets/38814/8734682/6612d764-2bc0-11e5-8193-2904460befce.png)

**Comment by zaksoup** [comment]
lol chris brown ur wrong

**Comment by xoebus** [comment]
good point

**Comment by zaksoup** [comment]
Thanks Chris!
