### ISSUE TITLE
v2.3.1 After authentication timeout, login returns you to the default pipeline, not your previous pipeline

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#703]
probably related to https://github.com/concourse/concourse/issues/700

**Comment by vito** [comment]
Is this more simply "logins don't redirect back to where login was initiated from"? If so, that story's in flight.

**Comment by xtreme-gavin-enns** [comment]
yup. seemed new to me on 2.3.?

**Comment by jchesterpivotal** [comment]
Buildpacks are seeing this too. Speaking only for myself, this is somewhere between the NYC kitchenette coffee grinder and roadworks as a source of annoyance.

**Comment by vito** [comment]
this should be fixed now
