### ISSUE TITLE
Display the name of the current pipeline somewhere on the page.

### ISSUE THREAD

**Issue by charlieoleary** [concourse/concourse#706]
When you have multiple pipelines, unless you specifically look at the browser tab there is no way to tell which pipeline you are currently viewing.  This is especially troublesome when you dig into the resources and jobs views.

Suggested improvement: add the current pipeline name to the topbar between the home button and the groups.

**Comment by vito** [comment]
Already open as https://github.com/concourse/concourse/issues/295
