### ISSUE TITLE
Sidebar is Empty after Login (auth timeout)

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#708]
# Bug Report

V 2.3.1

Cannot get back to the sidebar by navigating (home button, jobs etc), had to refresh the page.

![screen shot 2016-10-19 at 11 22 52 am](https://cloud.githubusercontent.com/assets/1178694/19525327/9c745f78-95ee-11e6-9594-d8d25f58f8d2.png)

**Comment by vito** [comment]
should be fixed already. just haven't shipped yet
