### ISSUE TITLE
concourse_tasks_waiting metric doesn't exist in 7.3.0

### ISSUE THREAD

**Issue by funkypenguin** [concourse/concourse#7084]
## Summary

The docs at https://concourse-ci.org/container-placement.html#limit-active-containers-strategy indicate that the metric `concourse_tasks_waiting` can be used to monitor for the effects of the limit-active-tasks container placement strategy. However, under Concourse 7.3.0, this metric does not seem to exist.

## Steps to reproduce

* Deploy concourse using the helm task, set `containerPlacementStrategy: limit-active-tasks`
* Set `prometheus.serviceMonitor.enabled = true`

## Expected results

In Prometheus, `concourse_tasks_waiting` should return a value (zero or otherwise)

## Actual results

Prometheus reports that `concourse_tasks_waiting' doesn't exist
![image](https://user-images.githubusercontent.com/1524686/119807616-6b587d80-bf37-11eb-8ec3-78f2918380df.png)

However, _other_ Concourse metrics _are_ present:

![image](https://user-images.githubusercontent.com/1524686/119807713-875c1f00-bf37-11eb-855a-f73221c14d1f.png)

## Triaging info

* Concourse version: 7.3.0
* Browser (if applicable): N/A
* Did this used to work? N/A

**Comment by aoldershaw** [comment]
We generalized this metric to apply to all steps in 7.2.0. https://github.com/concourse/concourse/releases#6635 mentions:

> The metric `concourse_tasks_waiting` was removed and replaced with `concourse_steps_waiting{type="task"}`

Sorry for the confusion!

**Comment by aoldershaw** [comment]
Just noticed that you mentioned the docs were still referring to the old name - fixed in concourse/docs#340
