### ISSUE TITLE
I would like to know I have invalid pipeline YAML *without* committing to a pipeline change

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#709]
Right now, I can see the _diffs_ to a pipeline before I accept or reject the change:

```
fly -t example set-pipeline --pipeline example --config example.yml

...

+ job: whatever
+ plan:
+   get: this-resource-is-missing-right-now

apply configuration? [yN]: y

invalid jobs:
blah blah can't recreate it here, you get the idea, concourse tells me "this-resource-is-missing-right-now" is missing right now.
```

But here's the problem. I _can't_ get that YAML validation _before_ I accept the pipeline change.

This sucks if, for example, I _thought_ that's how it works and then made several commits to a -ci develop branch, safe in the knowledge that I wasn't committing broken YAML.

Preferred behaviour would be:

```
fly -t example set-pipeline --pipeline example --config example.yml

invalid jobs:
blah blah can't recreate it here, you get the idea, concourse tells me "this-resource-is-missing-right-now" is missing right now.
```

That is, _don't even bother diffing invalid pipeline descriptions_. Validate first. Save an engineer's pride.

**Comment by vito** [comment]
Sounds similar to https://github.com/concourse/fly/issues/99 - there's a PR in progress here: https://github.com/concourse/fly/pull/113

**Comment by jchesterpivotal** [comment]
👍  it sure does. 

I'd still be happier if this was the default, though, given we run the validation no matter what.

**Comment by vito** [comment]
Yeah having the ordering the other way around would be nicer. Would just need a validate API endpoint.

**Comment by jchesterpivotal** [comment]
Of interest, I'm not the first to notice this. 18F seem to have written a Python script, [pipecleaner](https://github.com/alphagov/paas-cf/blob/c6f066cc8d8901377b8b375338043f62841b4885/concourse/scripts/pipecleaner.py) for this purpose.

**Comment by chendrix** [comment]
Closing as provided by `fly validate-pipeline`
