### ISSUE TITLE
Worker 7.3.0 error on amazon linux (guardian.failed-to-wire-containerizer)

### ISSUE THREAD

**Issue by jansepke** [concourse/concourse#7095]
## Summary
concourse worker stopped working after upgrading from 7.2.0 to 7.3.0

## Steps to reproduce

Start a worker node on a server with amazon linux OS with
```bash
docker run \
  --privileged \
  --restart=on-failure \
  --name concourse-worker \
  --mount type=bind,source=/opt/concourse/concourse-keys,target=/concourse-keys \
  --mount type=bind,source=/opt/concourse/worker-storage,target=/opt/concourse/worker \
  -p 7777:7777/tcp \
  -p 7788:7788/tcp \
  -p 7799:7799/tcp \
  --label-file /etc/docker/labels \
  --env-file /opt/concourse/concourse_worker_env_file \
  -d concourse/concourse:7.3.0 \
  worker
```

## Expected results
worker starts without errors

## Actual results
worker error:
`{"timestamp":"2021-05-28T06:06:38.761312487Z","level":"error","source":"guardian","message":"guardian.failed-to-wire-containerizer","data":{"error":"Malformed version: 4.14.231-173.361.amzn2.x86_64"}}`

## Triaging info
* Concourse version: 7.3.0
* Did this used to work? yes

**Comment by aoldershaw** [comment]
Fixed in 7.3.1: https://github.com/concourse/concourse/releases/tag/v7.3.1

For more context, this was a bug in our container runtime (guardian): https://github.com/cloudfoundry/guardian/issues/232
