### ISSUE TITLE
logging-in with basic auth does not redirect to team

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#710]
* Concourse version: **2.3.1**
* Deployment type (BOSH/Docker/binary): **bosh**
* Browser (if applicable): chrome

Logging-in with the correct, default basic auth credentials redirects me to `/` rather than `/teams/main/pipelines/:pipeline-name`. This is very confusing because no pipelines are visible and it looks like logging-in failed, when actually it succeeded.

**Comment by joshzarrabi** [comment]
Hi @robdimsdale, 

We've recently fixed an issue where after logging you can't see the sidebar pipelines and the top bar still has a login button and we're wondering if that will fix what you're describing. But even before that fix you should be seeing the pipeline visible in the middle of the page. Is that correct or are you seeing a different issue?

**Comment by robdimsdale** [comment]
It might be a combination of the two things you describe, plus the fact that the first pipeline in our list is actually empty (we use empty pipelines as a marker in the hamburger bar because we have about 25 pipelines and without markers to break them up it's very confusing).

I've confirmed that dragging another pipeline to the top of the hamburger (a real pipeline, not a "marker") and logging-out and back in again results in the pipeline being visible even though the URL is wrong and the bar still has a login button.

It sounds like we can close this issue.

Thanks for digging in to this.
