### ISSUE TITLE
'concourse web' doesn't read CONCOURSE_SESSION_SIGNING_KEY and still asks for --tsa-host-key

### ISSUE THREAD

**Issue by yurivict** [concourse/concourse#7115]
I am following this page from the documentation: https://concourse-ci.org/concourse-web.html

However, ```concourse web``` fails:
> error: the required flag `--tsa-host-key' was not specified

despite ```CONCOURSE_SESSION_SIGNING_KEY``` environment variable presence.

**Comment by yurivict** [comment]
Sorry, my bad.

**Comment by taylorsilva** [comment]
Feel free to ask questions or ask for help troubleshooting in Discussions: https://github.com/concourse/concourse/discussions
