### ISSUE TITLE
Integration with 3rd party systems

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#714]
# Feature Request
## What challenge are you facing?

For me as developer the CE (continuous everything) is as a dashboard. This is what I always have as open page on my machine. Concourse that is really nice and superior in many aspects in this aspect does not offer too much.

Even with extremely nice UI and near perfect visualisation of what is going on Concourse is very self-centric. I would love to see abilities that allow for integration in both directions.

This can go really far and I trust that the team will be able to design it better than me, so just few examples:

git resource - It will be nice if it provides link to the repo page. Also on resource page - every version could provide a direct link to the exact sha.

I have a lot of jobs that generate reports and upload them to codecov.io and similar. It will be nice if I can 'put' or something a link to the page where the report is as part of the execution of the job.

**Comment by vito** [comment]
These sound like a bunch of different requests which would be valid as their own issues. For example one would just be a matter of auto-linking `https://` fields in metadata. Someone already submitted a PR to the `git` resource for linking to GitHub. The other requests sounds like it'd be a new resource, which we probably won't make ourselves but the point of resources is that anyone can make them. :)
