### ISSUE TITLE
Visual Indicator of Archived Pipeline

### ISSUE THREAD

**Issue by reskin89** [concourse/concourse#7163]
## Summary

Currently, if an archived pipeline is linked to, there's no visual indication that it is archived. 

There is only a lack of a "run job" play button, but everything else looks as if it is a normal operational pipeline.

The only minor differentiator otherwise is its absence from the sidebar.

Some type of visual indication of a pipeline that it is indeed archived would be helpful, since it still loads in the GUI if a link is provided, which is common in README's, and other documentation.

**Comment by chenbh** [comment]
Would a greyed out topbar (similar to how we use blue for paused pipelines) be sufficient?
![Screen Shot 2021-07-08 at 5 33 27 PM](https://user-images.githubusercontent.com/17577073/124993632-a2c84880-e012-11eb-9ee5-90bcc8eb338b.png)

**Comment by reskin89** [comment]
I think that would work, and potentially adding the text [archived] or something next to the name at the top since colors don't always denote a specific functionality if it isn't potentially used much.

**Comment by clarafu** [comment]
I agree with @reskin89, I think some sort of highlighted header that says "archived" along with the greyed out toolbar might be nice because without the text it is not obvious what the grey toolbar means.
