### ISSUE TITLE
--peer-ip broken in 2.3.1

### ISSUE THREAD

**Issue by aquavitae** [concourse/concourse#717]
In earlier version I faced issue #452 (binary deploy), and found that specifying `--peer-ip` on the command line solved it. However, `--peer-ip` seems to be broken in version 2.3.1. When using it, the heartbeat fails with "connection refused" errors.

I've managed to reproduce this using docker, and have a working (or rather, not working) example [here](https://github.com/aquavitae/concourse-bug). Obviously, you'll need to update `CONCOURSE_EXTERNAL_URL` to run it.

**Comment by vito** [comment]
you'll also need to configure the bind IPS for garden and baggageclaim,
which default to 127.0.0.1 for security reasons. are you sure specifying
peer up is what actually fixed it? seems unlikely.

**Comment by baszalmstra** [comment]
How do you configure the bind IPS for garden and baggageclaim?

**Comment by vito** [comment]
@baszalmstra there are flags to `worker` for it - they should be in `worker --help`. probably `--garden-bind-ip` and `--baggageclaim-bind-ip`?
