### ISSUE TITLE
Getting 403 with Vault in concourse 7.3.1

### ISSUE THREAD

**Issue by Jasstkn** [concourse/concourse#7178]
## Summary

After upgrade to concourse 7.3.1 from 6.7.5 I've experienced errors related to Vault.

```
{"timestamp":"2021-06-16T13:29:08.185964432Z","level":"info","source":"atc","message":"atc.tracker.tick.run.finish.errored","data":{"build":"1.2","build_id":78,"error":"failed to interpolate task config: Error making API request.\n\nURL: GET https://vault.example.com/v1/secret/data/data/XXX/XXX/XXX\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n","job":"sync","pipeline":"sync","session":"23.8.2.5","team":"main"}}
```

## Steps to reproduce

1. Upgrade to 7.3.1 and try to get secrets from Vault kv2

## Expected results

No errors

## Actual results

```
{"timestamp":"2021-06-16T13:29:08.185964432Z","level":"info","source":"atc","message":"atc.tracker.tick.run.finish.errored","data":{"build":"1.2","build_id":78,"error":"failed to interpolate task config: Error making API request.\n\nURL: GET https://vault.example.com/v1/secret/data/data/XXX/XXX/XXX\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n","job":"sync","pipeline":"sync","session":"23.8.2.5","team":"main"}}
```

## Additional context

Login to vault was successful. After rollback it works as expected.
```
{"timestamp":"2021-06-16T13:28:13.776120904Z","level":"info","source":"atc","message":"atc.credential-manager.login.succeeded","data":{"lease-duration":3600,"name":"vault","policies":["default","test"],"session":"7.1","token-accessor":"XXXXX"}}
```

Can be related to https://github.com/concourse/concourse/pull/6115

## Triaging info

* Concourse version: 7.3.1
* Browser (if applicable): N/A
* Did this used to work? yes, on 6.7.5

**Comment by EstebanFS** [comment]
@chenbh and I are taking a look into the issue, can you tell us a little bit more about the process you followed when you upgraded Concourse to 7.3.1?

We guess you made the following steps:

1) Upgraded Concourse from 6.7.5 to 7.3.1
2) Enable kv2 on vault instance
3) Try to run the same pipeline with no configuration changes and have an error

When you downgraded Concourse, did you also disable the kv2 engine?

is the `/data/data/` actually on the error you saw? (Concourse automatically append /data to the path, that would mean your `CONCOURSE_VAULT_PATH_PREFIX` is set to `/data`)

if the `CONCOURSE_VAULT_PATH_PREFIX` was changed from the default `/concourse` to `/data` you would also need to update the [concourse policy](https://concourse-ci.org/vault-credential-manager.html#configuring-the-secrets-engine)

**Comment by Jasstkn** [comment]
@EstebanFS I've made following steps:
1. Used kv2 in Vault as I used it before
2. Upgraded concourse from 6.7.5 to 7.3.1
3. Verify that it doesn't work. 

PREFIX: /secret/data/example/test/

> is the /data/data/ actually on the error you saw? (Concourse automatically append /data to the path, that would mean your CONCOURSE_VAULT_PATH_PREFIX is set to /data)
Yes. I think that's the problem. Should I omit the /data/ from prefix?

**Comment by chenbh** [comment]
> Should I omit the /data/ from prefix?

Yep, that should be all that's needed. After that it should follow the standard [credential lookup rules](https://concourse-ci.org/vault-credential-manager.html#vault-credential-lookup-rules) and search for your secret in the following locations:
- `$PREFIX/$TEAM_NAME/$PIPELINE_NAME/$secret`
- `$PREFIX/$TEAM_NAME/$secret`

(assuming you haven't changed the [path templates](https://concourse-ci.org/vault-credential-manager.html#vault-lookup-templates))

**Comment by Jasstkn** [comment]
Thanks. I managed to fix this with removing data and .data from secret reference.
