### ISSUE TITLE
S3 resource triggering build only of latest version despite version : "every" being specified

### ISSUE THREAD

**Issue by shijinabraham-leapyear** [concourse/concourse#718]
[temp.yml.txt](https://github.com/concourse/concourse/files/549167/temp.yml.txt)
# Bug Report

In the pipeline attached, I am trying to run the compare task on all the version of the s3 resource temp1-exe and temp2-exe,but specifying the "version:every"  in the "get". But the task seems to only run on the the latest version of the s3 resource.  

If I click on the resource temp1-exe and temp2-exe, multiple versions are seen (and this matches the number of files in the correponding s3 bucket). But when "compare" task that is triggered  by a new version of s3 file, it runs on the latest version only.

The following can also be handy:
- Concourse version: 
- Deployment type (BOSH/Docker/binary): Concourse running as docker compose. Latest docker as on 24-Oct-2016
- Browser (if applicable): Chrome

**Comment by vito** [comment]
A new job will start from the latest version, rather than running through all of them, as that could take a very very long time (i.e. with a git repo with hundreds of commits). `version: every` just means don't skip versions, but it'll initially start from "now".

**Comment by shijinabraham-leapyear** [comment]
Hi

I did not understand the meaning of " version: every just means don't skip versions, but it'll initially start from "now"."

**Comment by shijinabraham-leapyear** [comment]
The use-case I am trying to implement is  (reference temp.yml attached)

- I have 2 artifacts temp1-exe and temp2-exe which are stored in s3
- Whenever a version of the artifact (say temp1-exe) is built, I need to test it against all "matching " versions of temp2-exe
- matching is defined as pairs temp1-exe and temp2-exe that pass "compare" step
- To find all matching, I have to compare each new version of temp1-exe that gets built against ALL versions of temp2-exe. I was hoping that version:every will allow me to do that. 

Do you know whether this can be implemented in concourse?

**Comment by shijinabraham-leapyear** [comment]
I went through https://github.com/concourse/concourse/issues/358 and got a better understanding on version: every. Turns out that I was assuming that version:every will trigger builds on a permuation of the input specified, which is wrong (It is discussed in the bug). This bug can be closed. I will raise a new feature request for the permutation.
