### ISSUE TITLE
CLI download links on "no pipelines configure" page don't go anywhere

### ISSUE THREAD

**Issue by DanielJonesEB** [concourse/concourse#719]
Concourse version: 2.3.1
Deployment: Vagrant
Browser: Chrome

The CLI download links on the front page just link page to the front page. The behaviour is the same regardless of whether you log in or not.

**Comment by vito** [comment]
By "front page" do you mean pipeline view, or the "no pipelines configured" view?

Possibly related: https://github.com/concourse/concourse/issues/719

**Comment by DanielJonesEB** [comment]
@vito Sorry for the late reply - "no pipelines configured". We noticed it when introducing new users to Concourse, so it was on first viewing the web UI on a fresh `vagrant up`.
