### ISSUE TITLE
Hung time resource - latest version of resource not found

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#7197]
## Summary

I saw a mention of hung time resources here:
https://github.com/concourse/concourse/issues/5360#issuecomment-615239361

Seeing something similar on a new pipeline deployment.

![stuck](https://user-images.githubusercontent.com/100110/122806517-066f1980-d290-11eb-92f4-0caa9246497d.png)

## Steps to reproduce

Pipeline Code
https://github.com/haiku/infrastructure/blob/master/concourse/pipelines/haiku-release.yml#L8

## Expected results

Being able to run pipeline

## Actual results

Pipeline hangs

## Triaging info

* Concourse version: 7.2.0
* Did this used to work? Yes, pre 6.x

**Comment by kallisti5** [comment]
I collected a stack trace per https://github.com/concourse/concourse/issues/5360#issuecomment-615239361

[worker-trace.log](https://github.com/concourse/concourse/files/6688608/worker-trace.log)
[web-trace.log](https://github.com/concourse/concourse/files/6688609/web-trace.log)


Job can be seen hung right now here:
https://ci.haiku-os.org/teams/r1beta3/pipelines/r1beta3-x86_64/jobs/repo-r1beta3-x86_64/builds/2

**Comment by kallisti5** [comment]
@vito  pinging you since you made the last known comment around this :-)

https://github.com/concourse/concourse/issues/5360#issuecomment-637540437

**Comment by clarafu** [comment]
I saw your time resource `pipeline-time-trigger` has a start time of `1 AM` and a stop time of `6 AM`. Did you try to grab a version of the resource within that time range?

**Comment by kallisti5** [comment]
eek. The day is limited to Sunday as well.   So the builder can't pull the resource and you can't force a build until 7 days from now?

**Comment by kallisti5** [comment]
I updated the pipeline temporarily:
```
resources:
  resource pipeline-time-trigger has changed:
  icon: alarm
  name: pipeline-time-trigger
  source:
    days:
+   - Sunday
    - Monday
+   - Tuesday
+   - Wednesday
+   - Thursday
    - Friday
+   - Saturday
    location: America/Chicago
-   start: 1:00 AM
-   stop: 6:00 AM
+   start: 2:00 PM
+   stop: 4:00 PM
  type: time
  
pipeline name: r1beta3-x86_64

configuration updated
```

Yup. Now it's pulling + triggering.  So time resources will refuse to pull except within the configured time window?  I thought the goal after 6.x was to allow manual triggering of time-based resources :-)

**Comment by taylorsilva** [comment]
I don't think there was anything in 6.x that would change the behaviour of resources. That probably would've been a breaking change if there was something. You might be thinking about some of the scheduling and algorithm changes introduced in 6.x, maybe the component we call [lidar](https://github.com/concourse/concourse/tree/master/atc/lidar) specifically.

**Comment by clarafu** [comment]
Yup, the time resource has not changed in that it will only create versions within the configured time window. I'm going to close this issue because it doesn't seem to be a bug within Concourse!

**Comment by kallisti5** [comment]
For future lurkers, concourse documented a way to make a manual trigger on a time trigger here:

https://concourse-ci.org/time-triggered-pipeline-patterns.html#2---multiple-time-triggers

It's a little... odd but works as a workaround for this.

**Comment by szberko** [comment]
> For future lurkers, concourse documented a way to make a manual trigger on a time trigger here:
> 
> https://concourse-ci.org/time-triggered-pipeline-patterns.html#2---multiple-time-triggers
> 
> It's a little... odd but works as a workaround for this.

I tried this solution, but it didn't work for me. The manual trigger seems to work only within the already specified time window.
