### ISSUE TITLE
Switch between teams easily

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#720]
# Feature Request
## What challenge are you facing?

Switching teams is slow and many clicks. (logout, log in)
## A Modest Proposal
- Nice: Keep me logged in to multiple teams and provide a dropdown to choose team.
- Super nice: Keep me logged in to multiple teams and show teams and their pipelines in the sidenav.

**Comment by vito** [comment]
I think we can get ambitious here and just say you should be able to log in to multiple teams at once.

Nice thing is with oAuth this can even be done with one click - we just need to know who you are on GitHub and then we can check each team's config.

**Comment by jadekler** [comment]
👍 👍 👍 👍 👍 👍 👍 👍

**Comment by ls-avanier** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 indeeed !!!

**Comment by ls-avanier** [comment]
Do we have the required work areas identified to achieve this? We just went from testing Concourse with a few people to deploying this with proper SSL and GitHub authentification. Having this would make our lives much more fun!

@typositoire ! Help me out! Let's set @hartfordfive loose on this one! 😝

**Comment by alefebvre-ls** [comment]
👍

**Comment by hartfordfive** [comment]
👍

**Comment by vito** [comment]
@ls-avanier @hartfordfive I think the more complicated bits will be the web UI flow, but maybe we could start with `fly` just to drive out the API?

Something like:

```
fly login -t foo -n team-1 -n team-2 -n team-3
```

Or, alternatively, just having login auth you with whichever teams have oAuth config to match. That probably doesn't scale as well though; we'd need to load up all the teams and process all their configurations.

**Comment by ls-avanier** [comment]
My feeling is that from a CLI usage point of view, it made more sense to me to specify the team when I do `set-pipeline` something akin to `fly -t my-target sp -c ci/pipeline.yaml -p my-pipeline -l ci/secrets.yaml -n dat-team` or even `fly -t my-target/dat-team -c ci/pipeline.yaml -p my-pipeline -l ci/secrets.yaml`.

I'll have to read up on the login and oAuth code to get a good sense of the flow, but if we need to call oAuth for every instance of a given oAuth target in every given team... that might not be optimal. We'd need a mechanism to resolve the mappings and call converged oAuth target a single time.

**Comment by vito** [comment]
You should only need to do the oAuth dance once. For example, it's only one call to GitHub to see which orgs and teams the user is a member of. From there you can just load the verification config for each team and see which ones are satisfied by their GitHub memberships.

Your `fly` example is interesting but it seems to be translatable to just having different targets to different teams. Mechanically, anyway. UX wise it'd be nicer to have a hierarchy, though it raises the question of what the team would be if you didn't specify it, which seems like it'd add some mental overhead.

**Comment by TimJones** [comment]
Is this issue still under development, or has been dropped??

**Comment by marco-m** [comment]
Hello, any news ?

**Comment by jama-pivotal** [comment]
oh hai! I can give some updates. One of the key themes of work this year that the Concourse core team has committed to in 2018 is introducing Users in Concourse. This means that, instead of logging into a team, you can login as a user and be able to access all teams that you belong to. This is the first step in a long road towards auditable logs and fine grained role based access control. That said, when we introduce users we will be rejigging the UI so that switching between teams won't be such a pain 🤞 

If you'd like to follow along our progress on users you can check out the [skymarshall repo](https://github.com/concourse/skymarshal)

**Comment by marco-m** [comment]
Super happy, thanks (again!) to all the Concourse crew!

**Comment by jama-pivotal** [comment]
Linking this issue to #1888 because it will indeed be easy to switch between teams you have access to once we roll out this change!

**Comment by jama-pivotal** [comment]
WE DID IT 🎉
