### ISSUE TITLE
Download client links don't work on no-pipeline screen (fresh setup).

### ISSUE THREAD

**Issue by MaikuMori** [concourse/concourse#721]
# Bug Report

The client download links don't work on the startup screen with no pipelines. Once you have your first pipeline set up, the small links on bottom right do work.

Inspecting the empty-pipeline screen "links" in DevTools show that the icons doesn't have link attached.

* Concourse version: 2.3.1
* Deployment type (BOSH/Docker/binary): Docker
* Browser (if applicable): N/A

**Comment by vito** [comment]
same as https://github.com/concourse/concourse/issues/721
