### ISSUE TITLE
`fly validate-pipeline --strict` exits with "error unmarshaling JSON" if YAML anchors are used

### ISSUE THREAD

**Issue by OddBloke** [concourse/concourse#7228]
## Summary

`fly validate-pipeline` will run against a pipeline that uses YAML anchors (either reporting success or errors) whereas calling `fly validate-pipeline --strict` will fail (regardless of pipeline validity) with (given an anchor name of `anchor`):

```
error: error unmarshaling JSON: while decoding JSON: json: unknown field "anchor"
```

## Steps to reproduce

Write out this pipeline:

```yaml
anchor: &anchor
  get: code

jobs:
- name: test
  plan:
  - *anchor
```

and execute these two commands:

```sh
fly validate-pipeline -c pipeline.yml
fly validate-pipeline -c pipeline.yml --strict
```

## Expected results

Both invocations of `validate-pipeline` emit the same errors (perhaps with additional ones in the `--strict` invocation).

## Actual results

The `--strict` invocation exits non-zero with:

```
error: error unmarshaling JSON: while decoding JSON: json: unknown field "anchor"
```

## Triaging info

* Concourse version:
```
fly --version
7.3.2
```
* *Did this used to work?* I don't know, but this bug is present in 6.7.5 also.

**Comment by chenbh** [comment]
This is working as intended, the help text for `--strict` is a bit misleading: in addition to failing on warnings, it also enforces that all fields used must match one of the ones declared in the schema.

In this case, the [top level pipeline schema](https://concourse-ci.org/pipelines.html#schema.pipeline) does not declare a `anchor`  field, so it fails the strict validation. This type of validation guards against cases where you misspell a field, for example `job` instead of `jobs`.

**Comment by OddBloke** [comment]
Hi Daniel, thanks for the response! That makes sense to me. I have a couple of follow-up Qs:

* Should I file an issue for prettifying the `--strict` output? It _looks_ like an unexpected error at the moment, compared to the usual failure output.
* Anchors are a common way of doing reuse in Concourse, in our pipelines at least: if we wanted to have strict validation, is there a way we can continue to use them? (Would an issue to add, e.g., a top-level `_anchors` key to the schema be worthwhile?)

**Comment by chenbh** [comment]
> Should I file an issue for prettifying the --strict output? It looks like an unexpected error at the moment, compared to the usual failure output.

Go for it, I agree that the current output is cryptic and doesn't really let you know why it failed.

> Anchors are a common way of doing reuse in Concourse, in our pipelines at least: if we wanted to have strict validation, is there a way we can continue to use them?

In our pipelines, we define the anchors at the [location of their first use](https://github.com/concourse/ci/blob/ecdae4873b73e9c93949b84752f949ac758ed7f3/pipelines/concourse.yml#L95-L99). It is slightly less readable than having a dedicated block for them at the top, but I find it's still easy enough to locate them by searching for the first occurrence of the name. Would this approach work for you?


> Would an issue to add, e.g., a top-level `_anchors` key to the schema be worthwhile?

I don't particularly have an opinion on this, but these kinds of questions can be posted to the RFCs repo (https://github.com/concourse/rfcs/discussions) to make it easier for others to chime in
