### ISSUE TITLE
top-bar doesn't re-render (color change or URL change) when switching between pipelines -- special circumstances?

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#723]
# Bug Report

When I switch from one pipeline to another pipeline, the top-bar doesn't re-render:
- The color doesn't change (one pipeline is paused and the other is not)
- The group links don't update to the new pipeline name; they stay as the old links

This has only happened to us in this particular situation:

- First pipeline in listing: named 'gpdb4', unpaused
- Second pipeline: named 'gpdb4.3.10.0', paused
- Both have the exact same group names and order (7 groups).
- We recently (about 3 PM PDT today) dragged to reorder the 'gpdb4' pipeline from 4th position to become the first one; the 'gpdb4.3.10.0' pipeline used to be first.
- At some point ~2 weeks ago, we renamed what had been called 'gpdb4' to become 'gpdb4.3.10.0'. A few days after that (say ~12 days ago), we `fly set-pipeline`d to get a new 'gpdb4'.

We don't know when this behavior started, but we think we would have noticed if it had been happening for a while. This most commonly is noticed when you're in a job of Pipeline A, and you click on a group name, intending to stay in Pipeline A, but it takes you to Pipeline B. Or it's noticed if you see the light blue "paused" and are like "golly, it's not paused!"

Could this be related to #700 ? It doesn't feel like exactly the same thing, because we observe the same error in both directions -- it isn't necessarily some special case about the first item. That is to say:
- Start on Pipeline number 7 (or whatever, just not one of the top two).
- Click to 'gpdb4', the first one. The header bar is dark blue (unpaused) and the links go to 'gpdb4'
- Click to 'gpdb4.3.10.0', the second one. The header bar is still dark blue, and the links still go to 'gpdb4'
- Click to the 7th pipeline (or whatever), just to reset things again. The top-bar re-renders to the correct state for the given pipeline
- Click to 'gpdb4.3.10.0', the second one. The header bar is light blue (paused), and the links go to 'gpdb4.3.10.0'.
- Click to 'gpdb4', the first one. The header bar is still light blue, and the links still go to 'gpdb4.3.10.0'.

* Concourse version: 2.3.1 (upgraded from 2.2.1 at ~10 AM PDT today)
* Deployment type (BOSH/Docker/binary): BOSH on latest stemcells
* Browser (if applicable): Chrome 53.0

**Comment by vito** [comment]
We fixed some weirdness in this area but haven't yet shipped it. It should be out today. I'll close this for now; reopen if you still see it in 2.4!
