### ISSUE TITLE
Add `btrfs` tools to the Docker image.

### ISSUE THREAD

**Issue by MaikuMori** [concourse/concourse#724]
# Feature Request

## What challenge are you facing?

Dockerized version doesn't have btrfs tools included so it will always fall back to naive backend.

## A Modest Proposal

Add btrfs tools to the Docker container.

**Comment by vito** [comment]
It packages them in the binary; this shouldn't be necessary. Is `btrfs` supported by your kernel?

**Comment by MaikuMori** [comment]
You're absolutely right. I mixed up two log messages while glancing over them. The missing executable is `modprobe` which is fine since it's running inside docker container and host has aufs module.

I read run-command.failed .... bash ... btfs followed by a line of `executable not found in path`.

btrfs failed because I'm currently not mounting btrfs volume which is expected.

My bad. Lack of sleep :(.

**Comment by vito** [comment]
No worries!
