### ISSUE TITLE
Time distribution of non time pressing jobs - throttle resource 

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#725]
# Feature Request
## What challenge are you facing?

For some jobs, for example, dynamic code analysis for code coverage and performance impact testing I would like to have tests running over every single version, but not necessarily as soon as it arrives. Having such jobs running during the night or other time distribution will allow for freeing resource for other tasks that are more time pressing during the day.
## A Modest Proposal

I would like to propose a throttle resource. It will have as an argument any other resource, say: 'pump' and a pass-through scheme. The throttle resource in and out will simply do whatever 'pump' resource does. The check also will rely on the check of the pump resource, but will regulate when new versions get in the system based on the pass-through scheme.

The pass-through scheme can be a simple - say one new version per period of time. A more sophisticated scheme could be to distribute the accumulated versions from one period in 'allow' period. For example, every new commit in git-repo during the day could be passed through at even intervals during the night.

**Comment by vito** [comment]
Is this the same as https://github.com/concourse/concourse/issues/604 ?

**Comment by ggeorgiev** [comment]
Does not seem the same as use case - but I feel like it can be solved with a throttle resource as well - it will need a bit more complex scheme logic though.

**Comment by ggeorgiev** [comment]
The biggest difference is that #604 request would like to create some form of aggregation of the versions, while in my request I just want time redistribution. Solving the two at once might be possible if say the new resource type (if decided to address it this way) has also (optional) aggregation aspect.

**Comment by vito** [comment]
Pretty sure you could do this with #604 using the existing time resource to emit a version every day. Otherwise it sounds like a new resource - we don't really take requests for those ourselves since those are much more scalable as a community-driven thing.

**Comment by ggeorgiev** [comment]
@vito I agree that when #604 in place it will allow for covering the need pointed out here. This though is true vise verse too.

There are resources and there are trigger options already, but yet somehow the suggested option seems to me as unnatural and misaligned with the semantics of a resource and a pipeline.
