### ISSUE TITLE
It should be more obvious which resources will be used before a build

### ISSUE THREAD

**Issue by jcderr** [concourse/concourse#726]
# Feature Request

## What challenge are you facing?

When manually triggering a task, it is not obvious which versions of the input resources will be used, and how they are linked together. The resource leading into that task requires significant mental bookkeeping to determine if it has passed the previous task and thus is actually eligible to be used in the next task; it also does not make it clear which other resource tags along with it.

For example, if DockerContainerA and SemVerA are an output of TaskA and an input to TaskB, but I for whatever reason, I need to retrigger TaskB manually (as a retry, or perhaps a redeploy after an operations failure), I cannot easily tell which versions of those resources will be used.

When inspecting DockerContainerA and SemVerA resources, the latest semver resource was 1.0.2-rc.5, but there was somehow a "newer" DockerContainerA that matched an "older" SemVerA (1.0.2-rc.2), so when I re-ran TaskB, it re-deployed the container that matched the older SemVerA. The only way to actually determine this is to run the task and just look at what happens.

## A Modest Proposal

When viewing the task page and/or perhaps when manually triggering a task, there should be a hint as to which versions of all resources will be used.

**Comment by vito** [comment]
Same as https://github.com/concourse/concourse/issues/269 ?

**Comment by jcderr** [comment]
Yeah. I thought I'd seen that issue before, but couldn't find it just now. Thanks.
