### ISSUE TITLE
Resource scripts should have resource name available as env variable

### ISSUE THREAD

**Issue by laurentverbruggen** [concourse/concourse#727]
It would be useful if the in/out scripts in custom resource types have the resource name available as environment variable, e.g. $RESOURCE_NAME.

It would avoid having to pass the path of the input directory as param to get/put tasks. E.g. the git-resource where the input repository needs to be specified.

**Comment by vito** [comment]
This has come up before, but I can't find the issue. I think it's the wrong direction. A resource's name has no bearing on its behavior, and I think it would be misleading to have that be the default. Thanks though.
