### ISSUE TITLE
Visualize Tasks inside Jobs

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#729]
# Feature Request
## What challenge are you facing?

Let me preface that I'm fairly new to concourse (using it 2 months now). I did struggle to understand the ordering of tasks inside a job, in particular the notion that a job can have multiple inputs and outputs and in which order they are fetched/executed (e.g. parallel vs. serialize). 

A concrete example is that I have a job that has a `put` to Cloud Foundry and after that another `put` that should push a message to Slack. While concourse did the right thing, the UI left me unclear about this, showing only the job and resources: 

![image](https://cloud.githubusercontent.com/assets/130103/19777643/82401c3c-9c79-11e6-81a1-f9de8c9b1ce3.png)

See also slack discussion for additional context discussing this exact scenario:
https://concourseci.slack.com/archives/general/p1477586703011483
## A Modest Proposal

I suggest the concourse pipeline UI should either (or both): 
- include some additional legend entries (coloured boxes = Jobs, black boxes = resources)
- show tasks (and their ordering) inside the pipeline view. Possibly with an optional toggle

I think this would help beginners better understand how concourse works, as the UI should be a great aid in understanding more or less "flat" yaml pipeline files.

**Comment by jama-pivotal** [comment]
Assigning to Design inbox for ....design
