### ISSUE TITLE
Web-UI: Animated legend creates high cpu usage

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#730]
# Bug Report

While the UI is beautiful to look at, I have some performance issues with it. Having the concourse UI open in a tab (as I frequently have it to monitor build status) creates high CPU usage even if the pipeline is idle:

![image](https://cloud.githubusercontent.com/assets/130103/19777794/2b14afee-9c7a-11e6-85dc-6e7af3e19c23.png)

Browser: 
OS X Google Chrome	53.0.2785.143 (Official Build) (64-bit)
Concourse v 2.3.1

**Comment by vito** [comment]
Same as https://github.com/concourse/atc/issues/88
