### ISSUE TITLE
Pipeline legend should explain difference between dashed and solid lines

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#731]
# Feature Request
## What challenge are you facing?

The concourse UI shows dashed and solid lines between resources. As a fairly new concourse user I have no idea what these are about and couldn't find anything in the docs on it.

![687474703a2f2f636c2e6c792f33793069305a3276326232462f646f776e6c6f61642f496d616765253230323031362d30322d32382532306174253230392e30392e3134253230706d2e706e67](https://cloud.githubusercontent.com/assets/130103/19778103/7f83005c-9c7b-11e6-936c-edf707b5fdae.png)
## A Modest Proposal

Expose them in the legend or make it obviously documented. This issue here should help the google visibility of the issue as well ;-)

**Comment by chriswhitcombe** [comment]
Does anyone know what the difference is?

**Comment by jchesterpivotal** [comment]
AFAICT it's [only documented in the release notes for 0.73](http://concourse.ci/downloads.html#section_v0730). 

Solid lines are for triggering resources, dotted for non-triggering.

**Comment by JohannesRudolph** [comment]
So... would be a great idea to add it to the docs, no? ;-)

**Comment by fushewokunze-pivotal** [comment]
I think this will be useful to add this to the docs.

**Comment by JohannesRudolph** [comment]
Reading the 3.1 release notes, I think this can be closed. Thanks!

**Comment by JohannesRudolph** [comment]
I verified this is in 3.2.1 
![image](https://user-images.githubusercontent.com/130103/27536345-f97dbf30-5a6e-11e7-8c88-94dae4db8bbc.png)

Thanks for fixing this!

**Comment by jamespollard8** [comment]
It's hard to tell the difference between the solid and dashed dependency lines in the legend. It would be more clear if the dashed dependency icon included more than just a dot.
