### ISSUE TITLE
Build log GC using "build_event" is very costly

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#7321]
## Summary

I just noticed that build log GC use `build_events` in the delete SQL statement:

https://github.com/concourse/concourse/blob/c466e1b0ae72881e69672f8651c3ec3b90918aec/atc/db/pipeline.go#L959-L987

Which will iterate through all pipeline build event log tables, which is very costly. For example, on our prod cluster, having 4000+ pipeline, the execution plan of `delete from build_events where build_id in (1,2,3,4,5,6,7,8,9,10)` looks like:

```
Node Type	Entity	Cost	Rows	Time	Condition
ModifyTable	build_events	0.00 - 1375132.24	0	15154.636	[NULL]
Seq Scan	build_events	0.00 - 0.00	0	0.009	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Index Scan	pipeline_build_events_1008	0.29 - 46.94	0	5.771	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Bitmap Heap Scan	pipeline_build_events_1046	35.32 - 160.49	0	2.340	[NULL]
Bitmap Index Scan	pipeline_build_events_1046_build_id_event_id	0.00 - 35.30	0	2.336	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Index Scan	pipeline_build_events_1047	0.28 - 37.57	0	7.900	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Bitmap Heap Scan	pipeline_build_events_1048	35.39 - 140.90	0	6.205	[NULL]
Bitmap Index Scan	pipeline_build_events_1048_build_id_event_id	0.00 - 35.38	0	6.204	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Seq Scan	pipeline_build_events_1049	0.00 - 111.57	0	0.738	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Bitmap Heap Scan	pipeline_build_events_1056	5.63 - 16.13	0	0.009	[NULL]
Bitmap Index Scan	pipeline_build_events_1056_build_id_event_id	0.00 - 5.62	0	0.008	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Seq Scan	pipeline_build_events_1062	0.00 - 21.29	0	0.107	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Index Scan	pipeline_build_events_1063	0.29 - 46.94	0	11.234	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Index Scan	pipeline_build_events_1064	0.29 - 701.85	0	2.460	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Index Scan	pipeline_build_events_1069	0.29 - 749.34	0	8.731	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
Index Scan	pipeline_build_events_1070	0.29 - 729.06	0	6.482	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
...omit rests...
```

We can see the cost is `0.00-1375132.24`, time is `15154.636`.

But if I specify a pipeline event log table `delete from pipeline_build_events_4050`, then the plan is:

```
Node Type	Entity	Cost	Rows	Time	Condition
ModifyTable	pipeline_build_events_4050	0.29 - 46.85	0	0.029	[NULL]
Index Scan	pipeline_build_events_4050	0.29 - 46.85	0	0.028	(build_id = any ('{1,2,3,4,5,6,7,8,9,10}'::integer[]))
```

The delete function is on `pipeline` object, why don't just delete from the pipeline's build event table?

## Triaging info

* Concourse version: all versions
* Browser (if applicable): na
* Did this used to work? no

**Comment by aoldershaw** [comment]
Yeah that's a good point - don't think there's any reason to *not* delete from the `pipeline_build_events_x` table. Good catch.

I'm sure this'll improve things a fair bit, and is a pretty easy win, but I'll also point out #6080 - as was suggested in the issue, we could have a separate GC component just for deleting the build events after we've marked a build as reaped **in batches**, rather than trying to delete everything all at once.

**Comment by evanchaoli** [comment]
@aoldershaw Thanks for pointing out #6080. But I think #6080 requires a bigger change, whereas this fix would be tiny and quick. So let's make this change first.
