### ISSUE TITLE
github oauth verification failed when hyphen in github team name

### ISSUE THREAD

**Issue by gregorycox** [concourse/concourse#733]
Deployed concourse using BOSH, after clicking "login with GitHub" on a new deployment, I always received "verification failed" on browser.  basic_auth worked fine when changed concourse to use basic_auth, github_auth when I changed concourse to authenticate a specific user it worked fine.  When setting concourse to use Org/Team, kept getting verification failed no matter which user tried in the team.  

The github team name had a hyphen, after creating a new team on github without the hyphen and only changing that for the concourse deployment.  All members of the team can authenticate as expected.  Putting single or double quotes did not resolve the team name when it included a hyphen.
# Bug Report

Bug is hyphen's are allowed in team names on github, but concourse will not verify users in a github team name that has a hyphen in it.
- Concourse version: 2.3.1, 2.3.0, 2.2.1
- Deployment type (BOSH/Docker/binary): BOSH

**Comment by vito** [comment]
Make sure you had configured the team's name as it appears in the GUI, not as it appears in the github URLs?

**Comment by billimek** [comment]
Can confirm:  You need to use the org & team names as they appear in the Github interface and not the abbreviated names as they show in the URL.  I dealt with the same exact thing just yesterday

**Comment by stepanstipl** [comment]
This is probably sorted by https://github.com/concourse/atc/pull/137 which allows you to use both forms of team name (name & slug) - I guess it should be in next release as Vito merged it now. Currently you might need to unicode encode the hyphen (or any other special chars) as '\u2010'.

**Comment by vito** [comment]
Yep closing as concourse/atc#137 was merged.
