### ISSUE TITLE
Feature request. Ability to trigger builds on multiple versions  and permutation of input

### ISSUE THREAD

**Issue by shijinabraham-leapyear** [concourse/concourse#734]
# Feature Request

Concourse cannot express the following 
"Trigger builds on "all" available versions of a resource"

I am requesting  a new option to 'version' param for get.
 version: "all" , which would fetch all available versions of a resource

For example :

```
  - get: res 
     version: "all"
```

will trigger a build on all resources of resource "res" which is available 
- get: res 
  version: "all"
  passed: [task1]

will trigger builds on all versions  that has passed task1 (similar semantics to version :"every")

and version "all" on more than one resource should trigger builds on permutation of the version
- get: res1
    version: "all"
- get: res2
    version: "all"
  if res1 has version a1 a2 and res2 has version b1 b2  available then builds should be triggered for 
  (a1 b1 ) ,(a1 b2), (a2 b1) (a2 b2)

This feature request is discussed in https://github.com/concourse/concourse/issues/358 in the implementation of version: "every" but it rejected due the reason that running (number of )permutation of versions) jobs will be expensive. But I would argue that max_in_flight already helps with controlling the load part.

https://github.com/concourse/concourse/issues/718 was raised due to the assumption that "version":every will perform the functionality requested in this issue.

**Comment by chendrix** [comment]
Closing as it seems to be captured by #739
