### ISSUE TITLE
fly rename-pipeline must not allow new name to be empty

### ISSUE THREAD

**Issue by suhlig** [concourse/concourse#7365]
## Summary

Renaming a pipeline with `fly -t some-target rename-pipeline -o "example" -n ""` succeeds and leaves a pipeline with an empty name. 

The renamed pipeline is visible in the web UI (with an empty name), but cannot be renamed again or even deleted.

## Steps to reproduce

```command
$ fly -t some-target rename-pipeline -o "example" -n ""
```

## Expected results

Error message from `fly` saying that the new name must not be empty.

## Actual results

`fly` accepted the empty string as new pipeline name. The renamed pipeline is visible in the web UI (with an empty name), but cannot be renamed again or even deleted.

## Additional context

We were able to rectify this situation by 

1. Finding the database id of the pipeline:

    ```command
    $ fly -t some-target pipelines --json
    ```

    It shows the pipeline id as `42` for the one pipeline with an empty name.

1. Updating the name using `psql`:

    ```sql
    # update pipelines set name='example' where id=42;
    ``` 

## Triaging info

* Concourse version: v7.3.2
* Browser (if applicable): n/a
* Did this used to work? don't know
* #6410 may be related

**Comment by taylorsilva** [comment]
We ignore the error from `ValidateIdentifier()` and rename the pipeline anyways. The API should stop and return the error as soon as it gets it.
https://github.com/concourse/concourse/blob/b047d257f2531c119e15d627e3799d9d931bad03/atc/api/pipelineserver/rename.go#L35-L37

**Comment by taylorsilva** [comment]
`ValidateIdentifier` only returns an error now when the identifier is an empty string. We should always stop when we get this error now. Found the same problem with renaming a team.
