### ISSUE TITLE
v2.4.0 Chrome - Clicking Home from a build sometimes leads to empty/blank pipeline

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#738]
I wasn't able to reproduce it to take a screenshot, but you believe me, right?

**Comment by vito** [comment]
no

**Comment by vito** [comment]
Interestingly this seems to happen in PhantomJS, but I've never seen this irl. hmm

**Comment by xtreme-gavin-enns** [comment]
I had a hunch at one point that the pipeline was just scrolled/zoomed off screen, but my memory is pretty fuzzy on that

**Comment by vito** [comment]
shouldn't be possible; there's a zoom and pan limit.
