### ISSUE TITLE
Concourse supports push notifications

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#74]
Something like an endpoint on the ATC that, when triggered, re-checks all resources.

Open questions around authentication, how to prevent DoSing

**Comment by kimeberz** [comment]
Hey @robdimsdale can you provide more information about what you're trying to do with this feature? Thanks!

**Comment by robdimsdale** [comment]
Sure, I was thinking that the ATC should expose an endpoint to force checking of resources, which is one way to implement webhooks.

The use case is to essentially switch from a polling,pull model of checking resource state to a webhook/push model. This generally has faster responses and is more efficient use of resources.

I know this is now technically possible with the `force-check` endpoint, and I know other conversations are going on around the sort of thing I discuss here, so I will close this issue now.
