### ISSUE TITLE
Allow Resource Authors to Customize Triggering Behaviour

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#740]
## What challenge are you facing?

My office used to have a shared pipeline for tearing down and redeploying pcf installations for testing on. We moved locks between pools in order to reflect the states of an environment; ready, dirty, or some other intermediate states. 

We were not able to find a very good solution to the problem of triggering the right number of jobs in order to, for example, destroy each environment as it was put into the dirty pool. One of the criteria for an acceptable solution was that we wouldn't see superfluous failed jobs on our pipelines .

The pool trigger resource was the best we could come up with and it is far from perfect.

I would like to propose a change to the resource api whereby the author can control whether a new version should trigger a job. The put script could indicate whether the returned version should trigger, or perhaps an additional script could check params passed in addition to "trigger: true".

P.S. It may be that these difficulties are a symptom of misusing versioned resources. Unfortunately there isn't any other way to trigger jobs (short of periodic scripts that trigger jobs through the api).

This is potentially related to https://github.com/concourse/concourse/issues/739#issuecomment-257589466

**Comment by chendrix** [comment]
I think you're right that this is actually just a symptom of us not having all of the appropriate resource semantics. This is definitely related to #739 and #1172
