### ISSUE TITLE
Not able to delete pipelines with trailing whitespace in name

### ISSUE THREAD

**Issue by dkfhui** [concourse/concourse#7416]
# Summary
When trying to delete a pipeline with trailing whitespace from the fly cli, it can't find the pipeline. 

# Steps to reproduce
Create a pipeline with trailing whitespace
`fly -t target_name destroy-pipeline --pipeline "pipeline_name "`

# Actual results
```
!!! this will remove all data for pipeline `pipeline_name `

are you sure? [yN]: y
`pipeline_name ` does not exist
```

# Additional context
I've tried multiple different ways to test the parsing of the white space including:
#### Without quotes

`fly -t target_name destroy-pipeline --pipeline pipeline_name `

#### With single quotes

`fly -t target_name destroy-pipeline --pipeline 'pipeline_name '`

The URL to the pipeline also has a space encoded in it e.g. 

`https://concourse-server/teams/main/pipelines/pipeline_name%C2%A0`

whereas it would normally be

`https://concourse-server/teams/main/pipelines/pipeline_name`

Thus, I've also tried deleting the pipeline with

`fly -t target_name destroy-pipeline --pipeline pipeline_name%C2%A0`
`fly -t target_name destroy-pipeline --pipeline 'pipeline_name%C2%A0'`
`fly -t target_name destroy-pipeline --pipeline "pipeline_name%C2%A0"`

# Triaging info
Concourse version: 5.8.1

**Comment by EstebanFS** [comment]
Hi @dkfhui , is there any particular reason you can not upgrade Concourse?

I was checking the newer versions of Concourse and this particular error doesn't appear on those ones.

**Comment by dkfhui** [comment]
Yeah, I was unable to upgrade it because of my company's automatic Concourse server build process, but I might be able to manually upgrade it
