### ISSUE TITLE
"no workers satisfying" error when worker with matching platform and non-matching tags is present

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#743]
I added a tag to a worker, but then realized I didn't need it. I reconfigured my pipeline to remove the `tags: [darwin]` from the build plan, but did not remove the tag from the worker. The error I got when trying to run the build was this:

```
no workers satisfying: platform 'darwin'

available workers: 
  - platform 'windows'
  - platform 'darwin', tag 'darwin'
  - platform 'linux'
```

It looks a bit misleading--there *is* a worker with that platform. It's just that the tasks were no longer tagged, and the tag on the worker means that those tasks can't run there.

I'm not sure how to improve this error messaging other than it'd be nice to know why that darwin platform worker wasn't suitable without having to remember that the tasks aren't tagged the same as the worker.

**Comment by vito** [comment]
could probably just tack ', no tags' or something to the end
