### ISSUE TITLE
baggageclaim fails to start with a small disk

### ISSUE THREAD

**Issue by cromega** [concourse/concourse#745]
Hi there!

We have just deployed concourse using BOSH and our deployment failed to start because the baggageclaim job crashed. Upon investigating logs we found that the startup script has an incorrectly templated value caused by this line:

https://github.com/concourse/concourse/blob/master/jobs/baggageclaim/templates/baggageclaim_ctl.erb#L36

If the disk is small (8gb in our case) the maths at the end of the line yields a negative number.

output of `df -m /var/vcap/data`:

```
Filesystem     1M-blocks  Used Available Use% Mounted on
/dev/xvdb2          4227   730      3260  19% /var/vcap/data
```

* Concourse version: 2.4.0
* Deployment type: BOSH

**Comment by vito** [comment]
fixed via #826
