### ISSUE TITLE
v2.4.0 with docker does not support downloading fly CLI

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#746]
Using the `docker-compose` concourse deployment:

Given I hit the root page,
When try to download the fly CLI through the web browser
Then a download does not occur.

Screenshot from Inspect:

![screenshot 2016-11-02 21 39 17](https://cloud.githubusercontent.com/assets/75184/19955217/e079a438-a144-11e6-9f6f-70e22c1ced69.png)

The following can also be handy:

* Concourse version: 2.4.0
* Deployment type (BOSH/Docker/binary): docker
* Browser (if applicable): Chrome v54.0.2840.71 (64-bit)

**Comment by carltongibson** [comment]
I've just run into this. It's the exact behaviour I'm seeing.

**Comment by chromerobv** [comment]
same here. any work around in the meantime?

**Comment by carltongibson** [comment]
My _solution_ was to `curl` the binary from the release page... 

https://github.com/concourse/concourse/releases/tag/v2.4.0 

YMMV :-)

**Comment by chromerobv** [comment]
sorry do you mean you didn't run the docker or did you go into the docker and grab that binary and run it?

**Comment by carltongibson** [comment]
I mean I ran concourse in docker, but just fetched the `fly` binary from the release page.

**Comment by chromerobv** [comment]
gotcha

**Comment by jdelic** [comment]
I have the same problem with the standalone 2.4.0 concourse binary. This problem is not limited to the Docker release.

**Comment by vito** [comment]
same as https://github.com/concourse/concourse/issues/719
