### ISSUE TITLE
Add 'fly verify -c config'

### ISSUE THREAD

**Issue by laurentverbruggen** [concourse/concourse#747]
I'd like to be able to get the JSON format of some yml configuration of a pipeline but only after it was validated by concourse. Now I have to set the pipeline and then retrieve the pipeline config with `fly get-pipeline -p <pipeline> --json`.

I propose to add a verify call to fly which does the same thing as first setting the pipeline and getting it afterwards but without actually adding it to concourse.  It would have the combined options of both `set-pipeline` and `get-pipeline` with the exception of `--pipeline` and `--non-interactive`.

**Comment by laurentverbruggen** [comment]
Apparently there is already a pending PR at https://github.com/concourse/fly/pull/113, but it doesn't cover the JSON part..

**Comment by chendrix** [comment]
That fly change got merged and I am hesitant to add in a `--json` option to it.

Why can't your "grab the json once it's been validated" be solved at the bash level?

`fly validate-pipeline -c <config> && fly get-pipeline -p <pipeline>`
