### ISSUE TITLE
[garden/seccomp]  Unable to run 32-bit binaries in concourse containers

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#7471]
## Summary

After upgrading to concourse 7.4.0 to from 7.2.0, and the container host to Fedora 34 from 33, unable to run 32-bit binaries in concourse

Originally reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=1998392

They mentioned an issue with seccomp.

Maybe something is missing here?
https://github.com/concourse/concourse/blob/master/worker/runtime/spec/seccomp.go

## Steps to reproduce

Container host: Fedora 34, x86_64

Image: `docker.io/fedora:34`
```
yum install git nasm autoconf automake texinfo flex bison gcc gcc-c++ make glibc-devel zlib-devel xorriso curl-devel byacc libstdc++-static glibc-devel.i686 libstdc++-devel.i686 libstdc++-devel python36
```

Steps to Reproduce:
1. `echo "void main(void) {}" > test.c`
2. `gcc -m32 test.c -o test-32bit`
3. `./test-32bit`

## Expected results

It to work

## Actual results

./test-32bit: error while loading shared libraries: libc.so.6: cannot stat shared object: Operation not permitted

## Triaging info

* Concourse version: 7.4.0

**Comment by taylorsilva** [comment]
Muntac is off right now so don't expect a reply from him any time soon :)

Could this be a bug with Fedora 34? Have you tested running 7.4.0 on Fedora 33? Would be interesting to see if the same error occurs there. From what I can tell, briefly looking at the `seccomp.go` and your comments, it _seems_ like Concourse's seccomp profile should allow the statx and arch_prctl calls. I'm not immediately sure what we would need to change to make this work for you on Fedor 34.

**Comment by fweimer-rh** [comment]
As I said on the Fedora bug, it's a bug in the container environment. Fedora 34 simply uses slightly different parts of the Linux system call interface than previous versions.  [This comment](https://github.com/concourse/concourse/issues/7471#issuecomment-907180339) above hints to the reason why:

```
statx(3, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_BASIC_STATS, 0xff9ad920) = -1 EPERM (Operation not permitted)
```

Container environments need to return `ENOSYS` for system calls that they do not implement or  are not prepared to handle, like regular Linux does.  There have been extensive discussions about this in various places:

* [Change seccomp default error from EPERM to ENOSYS](https://groups.google.com/a/opencontainers.org/g/dev/c/8Phfq3VBxtw)
* [seccomp filter should return ENOSYS for unknown syscalls](https://github.com/opencontainers/runc/issues/2151)

**Comment by kallisti5** [comment]
@fweimer-rh I'm a bit confused here.  Isn't the EPERM error coming from the kernel ioctl and not anything concourse is doing?

Unless i'm missing something, it seems that the github.com/opencontainers/runtime-spec/specs-go go module or the kernel is the cause?   I'm not seeing ant ENOSYS returns anywhere in the concourse code.

**Comment by kallisti5** [comment]
@fweimer-rh @taylorsilva 

https://github.com/opencontainers/runtime-spec/issues/960 this seems related.  I guess the "default" in the runtime-spec go module is EPERM, and that needs adjusted to ENOSYS on "all platforms"?  (or just Fedora platforms?)

**Comment by kallisti5** [comment]
I opened https://github.com/opencontainers/runc/issues/2151 about potentially changing the default in runtime-spec since it causes breakages.  The alternative is I just stop using Fedora :laughing:

**Comment by rcsalome** [comment]
Thanks for making this issue @kallisti5 , it came at the perfect time! We have noticed that the latest Debian Bullseye release has also had issues due to the `statx` system call.

After some testing, we have been able to get around this by changing our container runtime to containerd.
```
CONCOURSE_WORKER_RUNTIME=containerd
```
https://concourse-ci.org/concourse-worker.html#containerd-runtime

Not sure if it will also help with Fedora, but it might be worth a try.

**Comment by kallisti5** [comment]
I love workarounds. Trying this out now. :-)

**Comment by kallisti5** [comment]
confirming that switching from the default garden to containerd solves this issue! :fireworks:   Thanks @rcsalome !
I'll leave it open for potential investigation of the garden code.

**Comment by taylorsilva** [comment]
Stuff like this is actually why we worked on the containerd runtime. I don't see the garden team keeping up with the recent OCI changes. They already don't support cgroupsV2 and that's been the default on Fedora for a while now and starting with Debian Bullseye as well.
