### ISSUE TITLE
After `fly delete-pipeline`, `fly containers` reports task containers as non-pipelined, "check" containers

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#748]
After running `fly delete-pipeline`, the containers from that pipeline take a little bit to get cleaned up. That's reasonable. However, we see that for each task in the pipeline that had been running before it was deleted, there's a "check" container listed. Its `pipeline` attribute is "none", it's name is the task name.

It's short-lived, so not that bad, but confusing.

**Comment by chendrix** [comment]
@cjcjameson have you verified this in the latest versions of concourse 3.0+?

**Comment by cjcjameson** [comment]
Hi there, yep good question, sorry no not yet. I agree that this is probably not an issue in the new architecture, from what I hear

**Comment by andrewedstrom** [comment]
@cjcjameson Thanks for the issue! I'm closing it since this doesn't seem to be a problem anymore, but if you do see this again please feel free to reopen.
