### ISSUE TITLE
validate when resource types are unused

### ISSUE THREAD

**Issue by zachgersh** [concourse/concourse#749]
## A Modest Proposal

concourse recently started validating unused resources - can it do the same for unused resource types as well?

**Comment by zachgersh** [comment]
@vito how hard do you think this would be to do? I'd actually be able to just do this and throw it in as a PR.

**Comment by vito** [comment]
Hmm this is actually impossible to determine statically. Resource types are available for image_resource in a task config, which may be loaded at runtime via file:.

**Comment by jama-pivotal** [comment]
Closing since it seems impossible to do this statically.
