### ISSUE TITLE
UI issue with forward slashes in jobs/resources

### ISSUE THREAD

**Issue by laurentverbruggen** [concourse/concourse#751]
It is allowed to use forward slashes in jobs and resources but when clicking those jobs/resources in the UI the matching REST call fails because the `/` is not escaped and even if escaping is forced, it isn't handled properly. 

For example, assume we have a job `hello/world` in pipeline `test` then clicking the job will call the following url: `<host>/teams/main/pipelines/test/jobs/hello/world`

The url changes but the view remains the same. When escaping it with %2F the request fails with a 404: `<host>/teams/main/pipelines/test/jobs/hello%2Fworld`

**Comment by dflor003** [comment]
+1 to this! We are using concourse with the branch manager plugin to run pipelines for our branches and we are using feature branches with the `feature/` prefix. At the moment we basically had to start naming all of our branches with the `feature-` prefix instead because of this issue.

**Comment by nrvale0** [comment]
This just bit me hard. Hours spent wondering why I couldn't get my jobs to execute. :+1:

**Comment by topherbullock** [comment]
This also happens with emoji... we should fix it ASAP.

**Comment by chendrix** [comment]
This is due to https://github.com/bmizerany/pat/pull/46

**Comment by mhuangpivotal** [comment]
We made the fix in tedsuo/rata#7.

**Comment by jmerinen** [comment]
Resource names with forward slash don't fully work in 4.2.2.

The resource works, but when clicking the resource to see its details, concourse returns HTTP 404.
