### ISSUE TITLE
((secret.field)) syntax does not work with AWS Secrets Manager

### ISSUE THREAD

**Issue by james-pollard-leapyear** [concourse/concourse#7522]
We'd love to be able to use the `((secret.field))` syntax, but there seems to be a little bit of missing logic on the concourse side to actually use this with AWSSM.

Is this something that y'all might be willing to take a look at?

FWIW, AWSSM appears to do a pretty great job implementing secret `fields` on their end.

## Steps to reproduce
1. `aws secretsmanager create-secret --name /concourse/main/test --secret-string '{"user":"foo","password":"bar"}'`
2. Reference `((test.user))` secret in a pipeline:
`failed to interpolate task config: cannot access field 'user' of non-map value ('string') from var: test.user`
3. Just echo `((test))` in a pipeline:
`user:foo password:bar`

## Triaging info

* Concourse version: latest (7.4)
* Browser (if applicable): n/a
* Did this used to work? Unclear

**Comment by jdziat** [comment]
@james-pollard-leapyear what happens when you use:`((test/user))`?

**Comment by james-pollard-leapyear** [comment]
> @james-pollard-leapyear what happens when you use:`((test/user))`?

`failed to interpolate task config: undefined vars: "test/user"`

**Comment by james-pollard-leapyear** [comment]
Awesome - thank you @kurtmc!
