### ISSUE TITLE
Check containers went missing unexpectedly

### ISSUE THREAD

**Issue by jingyimei** [concourse/concourse#753]
We were looking at our team's pipeline, and noticed that we hadn't triggered or run on any recent commits (we were ~48 hours behind). We looked at `fly containers` and saw that maybe only ~20% of our resources had their check containers around. The important ones that we had expected to be there were indeed missing.

Unfortunately, we never caught ATC or other logs from that time. But if we had been able to track some logs down, what should we have looked for?

Our resolution was to restart the `web` VMs, but the behavior was not fully reproducible:
- Reproduction part 1: restarting one of our two VMs brought up almost all of our check containers (one was noticed to not be up; it was overnight so we're not sure). Over the course of between 2-18 hours, we experienced attrition -- the number of check containers dropped slightly over time, settling around ~50%.
- Reproduction part 2: Restarting the web VM we did the previous evening didn't increase the percentage further. Only when we restarted both `web` VMs did we get back to 100% check coverage. Since then, we've been at 100% for ~4 hours, and resources are flowing fine.

Feature request: the resource in the pipeline UI should show orange if there is no `check` container for that resource (after some reasonable time missing heartbeats / checks)

Feature request: the ATC should proactively look out for these situations and try to revive missing check containers. (probably gets deferred into https://github.com/concourse/concourse/issues/629)

_Specs_:

* Concourse version: v2.4.0
* Deployment type (BOSH/Docker/binary): BOSH

_Concomitant conditions_:

We're most interested in the features to make this failure more easy to recognize and respond to. We don't think this is related, and but this is the same instance as https://github.com/concourse/atc/issues/130 and https://github.com/concourse/concourse/issues/748

-- Jingyi and @cjcjameson

**Comment by jingyimei** [comment]
@schubert @tom-meyer @dsharp-pivotal bump

**Comment by tom-meyer** [comment]
We haven't had another occurrence of this since our initial reporting of the issue. But we wanted to make a couple notes on what we found while investigating.

`fly containers` will not list a check container for resources that:
* Are used only as output
* Are not triggering resources (trigger: false)

We'll wait another week or so to see if this crops up again. If not, we'll suggest this issue be closed.

**Comment by databus23** [comment]
We are seeing  this multiple times a week now (2.4.0). The only solution for us is to restart the atc.

**Comment by databus23** [comment]
We just lost most of our check containers, and they don't come back. Right before the check containers went missing we had to restart all workers because they were gone from the atc because of this issue: https://github.com/concourse/concourse/issues/750.

**Comment by databus23** [comment]
We are still seeing this regularly and it really seems to coincide with the loss of workers as reported in in #750. So there seems to be an edge cases where check containers that were running on a worker that went missing are not recreated unless the web component is restarted.

**Comment by dsharp-pivotal** [comment]
That seems to fit with what we see: After restarting workers, it's necessary to restart atc to get workers fully connected and accounted.

I think it might have gotten a little better with 2.5.0. That is, we've seen at least one check container go from "missing worker" to correctly checking, on its own, but it did take a few minutes.

**Comment by donaldguy** [comment]
This is, I believe, being tracked in the current sprint/iteration as concourse/atc#121 ... yes?

**Comment by vito** [comment]
Consolidating this into https://github.com/concourse/concourse/issues/844 as there are a few related issues and I'd like to highlight the above diagnostics collection.

Thanks for the information provided thus far! But if you could, going through the linked issue would be a great help.

@donaldguy No concrete progress on this yet - that was just a chore in-flight showing that we're involved in the discussion.
