### ISSUE TITLE
timeout per job

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#757]
# Feature Request

## What challenge are you facing?

Probably it is not very common when the system is operational but with bug #707 I am having jobs limboing forever very often - sometimes even several reboots of the whole system does not help. The only option is to force stop the job.

## A Modest Proposal

Timeout per job. Note I have timeouts per tasks. I would assume it is the worker that controls the task timeout. This obviously does not help at all if the worker is dead. It will be nice if there is a timeout controlled from the server on a job level.

**Comment by ggeorgiev** [comment]
It will be nice if the job timeout by default is a sum of all belonging steps timeouts.

**Comment by vito** [comment]
Timeouts are enforced by the server, not the worker. You can achieve this via:

```yaml
- do:
  - ...
  - ...
  timeout: 24h
```

**Comment by ggeorgiev** [comment]
when I try this I get: failed to unmarshal configStructure: yaml: line 364: did not find expected key

By the way, if the server controls the timeouts, it is not doing very well, when the worker is down.

**Comment by ggeorgiev** [comment]
I am on 2.4.0

**Comment by vito** [comment]
@ggeorgiev Could you paste the code you tried to use that yielded that syntax error?

**Comment by ggeorgiev** [comment]
nevermind; tried it again - it works
