### ISSUE TITLE
concourse fly not working on mac os X 

### ISSUE THREAD

**Issue by amulyas** [concourse/concourse#76]
sfo1502393292a:Downloads 502393292$ fly
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x633ed5)
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/panic.go:491 +0xad fp=0x7fff5fbffab0 sp=0x7fff5fbffa80
runtime.goenvs()
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/os_darwin.c:104 +0x70 fp=0x7fff5fbffac8 sp=0x7fff5fbffab0
runtime.schedinit()
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbffaf0 sp=0x7fff5fbffac8
runtime.rt0_go(0x7fff5fbffb28, 0x1, 0x7fff5fbffb28, 0x0, 0x0, 0x1, 0x7fff5fbffc30, 0x0, 0x7fff5fbffc6c, 0x7fff5fbffc88, ...)
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbffaf8 sp=0x7fff5fbffaf0

**Comment by vito** [comment]
Is your machine running low on resources or something? Works fine for us.

**Comment by amulyas** [comment]
my machine is not running low on resources .. my team member has the same issues .. can you send me the link of fly cli you are using for your mac here is my OS Details 
Yosemite 10.10.3  

Darwin sfo1502393292a 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by xoebus** [comment]
Do you have the `DYLD_INSERT_LIBRARIES` environment variable set?

If so, run `unset DYLD_INSERT_LIBRARIES` before running `fly`. It seems like setting custom dynamic libraries upsets the Go runtime.

**Comment by amulyas** [comment]
@xoebus thanks for your time I tried that but it still failing 
sfo1502393292a:Downloads 502393292$ echo $DYLD_INSERT_LIBRARIES

sfo1502393292a:Downloads 502393292$ unset DYLD_INSERT_LIBRARIES
sfo1502393292a:Downloads 502393292$ fly
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x633ed5)
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/panic.go:491 +0xad fp=0x7fff5fbffa40 sp=0x7fff5fbffa10
runtime.goenvs()
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/os_darwin.c:104 +0x70 fp=0x7fff5fbffa58 sp=0x7fff5fbffa40
runtime.schedinit()
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbffa80 sp=0x7fff5fbffa58
runtime.rt0_go(0x7fff5fbffab8, 0x1, 0x7fff5fbffab8, 0x0, 0x0, 0x1, 0x7fff5fbffbd0, 0x0, 0x7fff5fbffc0c, 0x7fff5fbffc28, ...)
	/var/vcap/data/packages/golang/25b17958ab3f23231ddfe6bc2d15a8d20a96dcab.1-0ee6cbb73eed0f25c14cea9c6f3ec64b0f8b2787/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbffa88 sp=0x7fff5fbffa80

**Comment by xoebus** [comment]
Strange. Do you have any other `$DYLD_*` environment variables set?

**Comment by xoebus** [comment]
The other thing people are suggesting that causes this is antivirus software. Are you using any of that?

**Comment by amulyas** [comment]
@xoebus thanks again .. I turning off the Antivirus and checked if any DYLD is set but no help .. :( stuff on internet is not helpful for this issue ..

**Comment by drnic** [comment]
Try building from source.




I had issues with cf plugins into the GE computers; but once built from source on a GE laptop then they started working.

**Comment by xoebus** [comment]
Thanks @drnic!

**Comment by xoebus** [comment]
@amulyas Did you try building from source? Did it work?

**Comment by xoebus** [comment]
@amulyas I'm going to close this for now but if you're still seeing the error after rebuilding then please feel free to re-open.
