### ISSUE TITLE
Safari 15 - Web UI is broken

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#7605]
### Discussed in https://github.com/concourse/concourse/discussions/7587

<div type='discussions-op-text'>

<sup>Originally posted by **andrew-edgar** September 23, 2021</sup>
Has anybody else seen that the latest Safari 15 does not work well with concourse UI.  I see lots of problems with the header becoming very large and icons overlapping etc when navigating around the concourse UI. 

We have v7.4.0 of concourse running.</div>

See discussion for screenshots.
The more you navigate in the UI the more the web page starts shifting in weird ways. If you refresh at any point everything renders correctly. The UI only gets weird when you start navigating to new pages.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/4583837/135679957-f633156e-cb27-4868-a531-05226d4b9cb7.png">

**Comment by taylorsilva** [comment]
Trying to dig into this right now and I'm finding that I can't consistently reproduce this. I think the problem might actually be how Safari is rendering stuff. I'm not confident this is something we can actually address. This is looking like a bug in Safari.

This always reproduces it for me:
1. Close any safari tabs/windows you have open
2. Open Safari
3. Go to https://ci.concourse-ci.org
4. Click on the **header** of any pipeline, like `docs-prs`
The header section should look weird with everything left-aligned, like this:
<img width="596" alt="concourse header left-aligned" src="https://user-images.githubusercontent.com/4583837/135680734-38412fbf-5ff0-4fff-aa42-67171a2d48cd.png">

It appears refreshing the page once it's gone weird fixes it for the life of that tab and for any other tabs that are loaded and that you interact with before closing that first tab. Try the following.

1. Repeat steps 1-4 above
2. With the UI all weird refresh the page. The page should now look normal. Navigate anywhere else in the UI. Everything should continue to appear normal. Click back to the home page, click on any other pipeline. It should all render fine.
3. Open a new tab, leaving the first one open wherever you left it, and visit https://ci.concourse-ci.org again. Click into any pipeline, everything should look fine. (NOTE: this didn't always work for me, but most of the time the second tab would render fine)

I performed step three in various different ways (open second tab, load page, close first tab, then interact with the second tab, oh no everything looks weird!) and sometimes things worked and sometimes they didn't. It was very inconsistent.

**Comment by taylorsilva** [comment]
Submitted a bug report via this form https://www.apple.com/feedback/safari.html

```
Steps to Reproduce:
1. Close all existing Safari Windows. Open Safari.
2. Visit https://ci.concourse-ci.org/
3. Click on the "docs-prs" header. All the top-level elements will appear left-aligned.
4. Refresh the page. It should render correctly.

No errors are printed in the console. More details in https://github.com/concourse/concourse/issues/7605

Page renders fine in all other major browsers. Only started happening with the release of Safari 15.

Safari version: Version 15.0 (16612.1.29.41.4, 16612)
```

**Comment by taylorsilva** [comment]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/4583837/144635847-e9307b01-85f3-429d-a34e-72fb217657d6.png">
Can't reproduce this on Safari anymore. Guess it's fixed? 🤷

**Comment by metskem** [comment]
I am having it all day still: 
<img width="197" alt="image" src="https://user-images.githubusercontent.com/555693/144651360-19dc3d87-6b73-4562-886d-fc215557a0e0.png">

**Comment by mjnorman** [comment]
Same, having the issue, a hard refresh fixes it until the next time you visit the page :(
Safari Version 15.1 (17612.2.9.1.20)
