### ISSUE TITLE
resource type cf failed with api-endpoint api.run.pivotal.io

### ISSUE THREAD

**Issue by ntdt** [concourse/concourse#761]
# Bug Report

* Concourse version: 2.4.0
* Deployment type: Docker image concourse/concourse version 2.4.0

Job of cf type error:

>Setting api endpoint to https://api.run.pivotal.io...
>OK

>API endpoint:   https://api.run.pivotal.io (API version: 2.64.0)
>Not logged in. Use 'cf login' to log in.
>API endpoint: https://api.run.pivotal.io
>Authenticating...
>OK
>Use 'cf target' to view or set your target org and space

>Cloud Foundry API version 2.64.0 requires CLI version 6.22.0.  You are >currently on version 6.21.1+6fd3c9f. To upgrade your CLI, please visit: >https://github.com/cloudfoundry/cli#downloads

If I do the hijack and launch `cf push`, it works fine.
Inside the hijack session:

>bash-4.3# cf version
>cf version 6.21.1+6fd3c9f-2016-08-10

**Comment by vito** [comment]
This should be fixed now.
