### ISSUE TITLE
Concourse jobs do not exit even when complete

### ISSUE THREAD

**Issue by jdeppe-pivotal** [concourse/concourse#763]
Hi,

Running Concourse v2.4.0 we're occasionally seeing jobs complete but the running container does not seem to exit. When I am able to hijack into the container I do not see any running processes.

Sometimes I am also not even able to hijack into these containers.

The jobs, in question, already have a concourse timeout defined, but that doesn't seem to be kicking in either.

I am able to abort the job, however if I try and look at the job (build) all I get is a 'Loading...' message and a nice spinner.

I do not recall this happening before 2.4.

I'm happy to try and provide additional debug info if you can suggest what would be helpful to report.

**Comment by jdeppe-pivotal** [comment]
Possibly related to this https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ and https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html.

Trying this to see if it helps: https://github.com/Yelp/dumb-init

**Comment by oppegard** [comment]
@jdeppe-pivotal Any update on whether `dumb-init` helps?

**Comment by jdeppe-pivotal** [comment]
I _think_ it's reduced the occurrences, but it hasn't fully resolved the problem as I just had a system get stuck again yesterday. I'm going to give it another week or so in our environment but we might also try this: https://github.com/krallin/tini. Apparently it has slightly different code to reap child processes.

Just for my own reference: https://github.com/Yelp/dumb-init/issues/44

**Comment by beyhan** [comment]
We are observing similar issues with some of our concourse instances. We have different concourse instances running on different infrastructures. We don't observe the issue on all of them.  Wich is strange because all of them are running with concourse 2.5.1, are using the same docker container and running the same pipeline. They should actually behave the same if there is a docker container issue. Our setup is with `workers` connected via `tsa` to `atc`. Therefore, I suspect that connection issues between the `worker/container` running the task and `atc` are the reason for endless jobs. We have also a concourse timeout defined but it has no effect.  These are the logs of a job which ran forever until I aborted it through the concourse UI: 

```
./atc.stdout.log.2:36914:{"timestamp":"1483051490.678934336","source":"atc","message":"atc.syncer.bosh-openstack-cpi:scheduler.tick.scheduling.try-start-next-pending-build.do.task.create-container.image.check-image.init.created","log_level":1,"data":{"build-id":49848,"build-name":"2886","container":"55a2414a-398e-4568-69c6-506293e1b438","session":"13.10.56571.3.15.4.13.4.1.1.1"}}
./atc.stdout.log.2:37888:{"timestamp":"1483051588.606828451","source":"atc","message":"atc.syncer.bosh-openstack-cpi:scheduler.tick.scheduling.try-start-next-pending-build.do.task.started","log_level":1,"data":{"build-id":49848,"build-name":"2886","session":"13.10.56571.3.15.4.13"}}
./atc.stdout.log.1:11952:{"timestamp":"1483073288.409373999","source":"atc","message":"atc.syncer.bosh-openstack-cpi:scheduler.tick.scheduling.try-start-next-pending-build.do.aggregate.get.continuous-heartbeat.tick.failed-to-get-volume-size","log_level":2,"data":{"build-id":49848,"build-name":"2886","error":"failed to get volume stats","name":"bosh-cpi-src-in","session":"13.10.56571.3.15.4.14.3.2.731","volume":"0776fdf3-c1a1-481a-7ef3-8284d379e171"}}
./atc.stdout.log.1:110173:{"timestamp":"1483082078.327053308","source":"atc","message":"atc.syncer.bosh-openstack-cpi:scheduler.tick.scheduling.try-start-next-pending-build.aborting","log_level":1,"data":{"build-id":49848,"build-name":"2886","session":"13.10.56571.3.15"}}
```

There is a `failed to get volume stats` error which most probably is caused by network issues. Also the log entry is many hours after the last log entry for this job. I don't know what happened in the meantime. 
@jdeppe-pivotal: Do you see any network issues in your `atc` log file?

**Comment by friegger** [comment]
Any update on this? We are still seeing this problem frequently on concourse 2.7.

**Comment by jdeppe-pivotal** [comment]
We've switched to using [ https://github.com/krallin/tini]() which seems to do a better job than `dumb-init` (with Concourse 2.7.0). The occurrences of the issue have dropped _significantly_, however not 100% resolved. I couldn't find a documented way to use `tini` within a shebang line so wrote this simple Go wrapper:
```
package main

import (
	"os"
	"syscall"
	"os/exec"
	"log"
)

func main() {
	tini, err := exec.LookPath("tini")
	if err != nil {
		log.Panicf("Unable to find 'tini' in PATH")
	}

	os.Setenv("TINI_SUBREAPER", "1")

	tiniArgs := []string{"-s", os.Args[1], "--"}
	for _, v := range os.Args[2:] {
		tiniArgs = append(tiniArgs, v)
	}

	err = syscall.Exec(tini, tiniArgs, os.Environ())
	if err != nil {
		panic(err)
	}
}
```

**Comment by vito** [comment]
Don't think there's anything to do on our end. The output might be "done", but technically there's no way for Concourse to know that without the full process tree existing. This is a system behavior with waiting on a child process tree, not a Concourse-specific behavior.
