### ISSUE TITLE
Web UI stops updating - v2.4.0

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#765]
# Bug Report

Not really sure what is causing this, but we are frequently (~daily) seeing the web ui on our CI monitor mac mini failing to keep up-to-date.

This has happened in both chrome and safari.

Might it have to do with significant pipeline changes, such as removing resources?

The next time it happens we'll grab Topher and get him to help us investigate the console.
![screen shot 2016-11-11 at 11 15 41 am](https://cloud.githubusercontent.com/assets/1178694/20221900/3946db9a-a801-11e6-8e16-b20018a362dd.png)

**Comment by xtreme-gavin-enns** [comment]
Caught this one in the act again. v2.5.0

Two safari windows on our CI monitor mac mini; one updates, the other doesn't. Topher has access to the machine

**Comment by andrewedstrom** [comment]
@xtreme-gavin-enns Are you still observing this in v3.1.x?

**Comment by xtreme-gavin-enns** [comment]
I haven't seen this since then, but then I'm not on a project with a CI monitor at the moment.
