### ISSUE TITLE
chrome rendering issue with the pulsing of a job from the pipeline view

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#766]
# Bug Report

We have some jobs, which are pulsating the rendering looks _off_.

Watch this video from [slack](https://concourseci.slack.com/files/jtarchie/F3100MW3T/untitled.mov)

The following can also be handy:

* Concourse version: 2.4.0
* Deployment type (BOSH/Docker/binary): BOSH
* Browser (if applicable): Chrome 54.0.2840.71

**Comment by chendrix** [comment]
Closing as captured by #1127

**Comment by jtarchie** [comment]
First!
