### ISSUE TITLE
Read-only access for authenticated users

### ISSUE THREAD

**Issue by dryewo** [concourse/concourse#769]
# Feature Request

## What challenge are you facing?

We want to adopt Concourse in our big team (actually, many small teams).
We use Github OAuth for authenticating and authorizing users.
The challenge is as follows:
If there are teams TeamA and TeamB, and TeamA owns a pipeline Pipeline1, we will need to restrict access in the following way:

- users logged in to TeamA has full access to Pipeline1 - triggering, modifying etc. - this is already implemented in Concourse.
- users logged in to TeamB can see Pipeline1, but cannot trigger and otherwise modify it.
- unlogged users cannot see Pipeline1.

This will enable TeamA accept pull requests from TeamB and let them see the results of builds.

## A Modest Proposal

Current implementation allows to expose a pipeline for both unautenticated users and users in other teams. This is not fine-grained enough for our use case.

I didn't carefully think it through, but I guess it can be implemented by adding `--internal` flag to `expose-pipeline` subcommand:

    $ fly expose-pipeline -t foo -p helloworld --internal

This should make `helloworld` pipeline visible only to logged-in users.

If there is already some solution to this, please point me to the docs, as I was not be able to find anything.

Thanks in advance.

**Comment by freelock** [comment]
For us, we want a different (but related) scheme, perhaps this can be included in whatever knobs are created.

We basically want to create read-only users. Pipelines by default should not be visible to the public. We'd like to be able to create a pipeline within a team, and provide a read-only login to the team -- users using the read-only login can see pipelines related to the associated team, but nothing else, and no ability to update a pipeline.

I also would like to have logins that may see a pipeline AND trigger a build, but NOT update the pipeline or execute any tasks -- though my current solution for triggering a job is via a bot that can authorize users appropriately.

**Comment by csterwa** [comment]
I would like to add my support to this feature request. We have a need for finer grained access control per pipeline if possible but even a more simple approach would be useful such as:

* Team A has full access to all pipelines
* Team B has read only access to all pipelines
* Unauthenticated user has no access to pipelines

**Comment by bacoboy** [comment]
Since the corresponding pivotal tracker ticker is a "not found" page, can I assume this got lost in the mists of time?

At some point it looked like it was slated for 3.6.0 and then got pushed.

Or is there a better ticket to track this on?  Story is coming up on its 2 year birthday soon 🎂

**Comment by jama-pivotal** [comment]
Closing in favour of the details in RFC https://github.com/concourse/rfcs/pull/6

oh and its also done :D

**Comment by ralekseenkov** [comment]
@jama-pivotal doesn't look like it's done though... at least not in 4.2.1. right now if user is a member of teams A and B, he has both read/write/trigger access to both A and B team pipelines. it's not possible to restrict access to read-only for a given team until roles are fully there
