### ISSUE TITLE
Add documentation on integrating and configuring blackbox

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#77]
Understanding how to incorporate and configure blackbox is nothing short of black(box) magic.

Knowing that the adding blackbox release before the others results in automagical logging is not obvious. 

Blackbox README also mentions `paths` for both datadog and papertrail - what are these for and how do we configure them?

**Comment by robdimsdale** [comment]
@vito it sounds like you're moving away from blackbox - feel free to point me to Riemann docs and close this issue

**Comment by xoebus** [comment]
Blackbox will still be used for syslog. It shouldn't need any extra properties in the manifest. I'm not sure which part of the README mentions DataDog.

The manifest ordering gotcha will be fixed with BOSH links.

**Comment by robdimsdale** [comment]
Cool thanks. Let's leave this open to capture any docs changes (and the simplification when the bosh links stuff lands)

**Comment by topherbullock** [comment]
Closing this in favour of using https://github.com/cloudfoundry/syslog-release instead
