### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by stepanstipl** [concourse/concourse#771]
Hi,
currently there's no API documentation (apart from the bit on workers API - https://concourse.ci/worker-api.html). It would be really nice to have docs for the whole API, including some brief info on how auth works and similar. I think this is important when you try to interact with Concourse and you don't want to use fly cmd utility.

(My use case is currently trying to automate repeatable setup of Concourse teams via Ansible and fly does not have any way to list current teams nor their details.)

**Comment by vito** [comment]
same as https://github.com/concourse/concourse/issues/771

**Comment by akshaymankar** [comment]
I guess the issue is moved to this: https://github.com/concourse/concourse/issues/1122
