### ISSUE TITLE
job/build log does not show, keeps loading

### ISSUE THREAD

**Issue by ppaulweber** [concourse/concourse#772]
* Concourse version: `2.4.0`
* Deployment type (BOSH/Docker/binary): `binary`, `Ubuntu 16.04 LTS`, `4.4.0-47`, `x86_64`
* Browser (if applicable): `Chromium 54.0.2840.100`, `Mozilla Firefox 49.0.2`, `Opera 41.0.2353.56`

I've discovered a problem with my concourse.ci installation. If I click on a job in the web UI and the details view is loaded, the loading of the log never stops and does not show any output. But, by accident, I've discovered that if the `concourse web` instance stops (program abort etc.) the log is shown.

- could it be that the web UI correctly fetches the build log, but the display logic does not recognize it?
- a closer look in a debugger points out that the GET request to the `api/v1/builds/<ID>/events` seems to be broken, because it delivers after a very long loading time (see screenshot below) the following error message: 
  ~~~
  GET https://<URL>/api/v1/builds/<ID>/events net::ERR_INCOMPLETE_CHUNKED_ENCODING
  ~~~
  ![concourse_ci_log_loading_bug](https://cloud.githubusercontent.com/assets/6830431/20265390/0ece3e5e-aa71-11e6-8930-8bef27f044df.png)

**Comment by vito** [comment]
If you have a load balancer or reverse-proxy, make sure it supports SSE. This may mean configuring it to do raw TCP forwarding rather than HTTP/HTTPS.

**Comment by ppaulweber** [comment]
@vito: thanks for the fast answer and input! Yes I'm using a reverse proxy but in this case I forgot about the SSE. I've updated my `nginx` configuration and added the following configuration to support SSE and it works flawless! Thank you!

~~~
server {
	// ...
	location / {
		// ...
		proxy_set_header          Connection '';
		proxy_http_version        1.1;
		chunked_transfer_encoding off;
		proxy_buffering           off;
		proxy_cache               off;
		// ...
	}
	// ...
}
~~~
