### ISSUE TITLE
Hello World example does not work

### ISSUE THREAD

**Issue by riglar** [concourse/concourse#774]
Hi,

I'm following the Hello World example. I've loaded the config via the fly CLI as per the docs, but my UI is missing the '+' button and seems mostly functionless. I'm using 2.4.0.

Tom

![screenshot-hello-world - concourse-2016-11-14-15-06-29](https://cloud.githubusercontent.com/assets/10271319/20269703/450ab4ba-aa7c-11e6-81bf-f0a0558f1a1b.jpeg)

**Comment by vito** [comment]
Anything in the web console?
