### ISSUE TITLE
Login page gives no indication of authentication failure - v 2.4.0

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#776]
# Bug Report

Like, I enter bad username/password and click login and there is no UI change.

Chrome, Bosh Deployed.

I thought this was a symptom of another bug, but it appears to always be the case. Probably already been fixed for the next release, but I didn't see an issue for it, so.

**Comment by chendrix** [comment]
Is this an issue @xtreme-gavin-enns ?

**Comment by xtreme-gavin-enns** [comment]
Yes, as of 2.7.3

http://i.imgur.com/zcTTBHy.gif

**Comment by ClaraFuPivotal** [comment]
https://github.com/concourse/concourse/issues/885

**Comment by Lindsayauchin** [comment]
Design for error state on authentication failure. ![Login_error_01.png](https://codetreeusercontent.s3.amazonaws.com/uploads/3a7173ae-08de-43c7-96e6-1f611d9bf853/Login_error_01.png)

**Comment by mariash** [comment]
This currently shows `login error: not authorized`.

**Comment by mariash** [comment]
Since there is an indication present now for user when failing to login I am going to close this issue.
