### ISSUE TITLE
"Pipeline ((vars)) example" builds have expired

### ISSUE THREAD

**Issue by curiositycasualty** [concourse/concourse#7792]
## Summary

Looking over the examples doc page (https://concourse-ci.org/examples.html), [example 2.3](https://concourse-ci.org/pipeline-vars-example.html) points to 2 jobs that have passed (and are now gone).
- `initial-job` -- https://ci.concourse-ci.org/teams/examples/pipelines/pipeline-vars/jobs/initial-job/builds/1
- `level-9000-job` -- https://ci.concourse-ci.org/teams/examples/pipelines/pipeline-vars/jobs/level-9000-job/builds/1

## Expected results

Example builds do not expire in the demo environment.

## Actual results

Example builds in the demo environment are passed (and are now gone).

## Additional context

I'm unfortunately not familiar with this codebase. But it would seem to me that example builds shouldn't expire such that they continue to be meaningful examples as the docs seem to intend.

**Comment by xtremerui** [comment]
Thx for reporting it! Unfortunately the build log retention policy is cluster wide so we can't make the build log to last forever. But we can just rerun the job to create a new one. 

It should be good now.
