### ISSUE TITLE
Email resource

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#78]
An email resource would be useful, especially when combined with `on_success` and `on_failure` hooks to e.g. email notification with state of job

**Comment by rosenhouse** [comment]
@cunnie and I have begun working on this, and expect to soon have something basic but functional.

**Comment by rosenhouse** [comment]
current rough but working thing: https://github.com/pivotal-cf/email-resource

**Comment by robdimsdale** [comment]
Good enough for me - closing.
