### ISSUE TITLE
In-progress build job title difficult to read

### ISSUE THREAD

**Issue by troykinsella** [concourse/concourse#7815]
## Summary

The white text against the yellow background of a build page job title is very difficult to read:

![Screenshot_2021-11-17_20-59-13](https://user-images.githubusercontent.com/1655907/142354986-b22c61c8-b07f-4c94-ab6e-6ca3f70c7c01.png)

## Steps to reproduce

* Start a build of any job such that it enters the `started` state
* Navigate to the build output page
* Observe the job title in the header

## Expected results

* A colour scheme that is easily readable and accessible

## Actual results

* Difficulty reading the title despite 20/20 vision and no accessibility needs

## Additional context

N/A

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): Firefox in Linux
* Did this used to work? Yes, it used to be adequately readable

**Comment by xtremerui** [comment]
it is fixed in https://github.com/concourse/concourse/pull/7756. Will be in next release.
