### ISSUE TITLE
OIDC hostedDomains Rejects Everything

### ISSUE THREAD

**Issue by ikegentz** [concourse/concourse#7826]
## Summary

Related to https://github.com/concourse/concourse-chart/issues/281, wasn't sure which place was better to file the issue so feel free to close one or the other.

We are attempting to get Concourse (helm chart) working via OIDC so our team can log into it using their Google accounts. This is working, however we then attempted to restrict the domain to only be our organization via the following setting:

```
        oidc:
          enabled: true

          displayName: "Google"

          hostedDomains:
            - "*********.com"
          
          issuer: "https://accounts.google.com"

          userNameKey: email
```

we get the error `unexpected hd claim ***********.com`

I can confirm that this is indeed setting the correct environment variable in the `web` pod:

`kubectl describe pod -n concourse <pod ID>`
```
      CONCOURSE_OIDC_HOSTED_DOMAINS:                      [<*********>.com]
```

I have experimented with wildcards as well, such as simply doing this:
```
...
        hostedDomains:
        - "*"
...
```

However whenever signing in, no matter what value is set for `hostedDomains` we get this error:
```
unexpected hd claim ***********.com
```

We have browsed through the [Dex Code](https://github.com/dexidp/dex/blob/49e59fb54fb308c2cb17508232c28073964d3e35/connector/oidc/oidc.go#L220-L242) that appears to handle this, and it looks like a simple string comparison, not sure how this could not be working unless I am possibly missing another setting?

## Steps to reproduce

1. Configure basic OIDC settings for Google authentication
2. In the `web` container, set the environment variable `CONCOURSE_OIDC_HOSTED_DOMAINS` to anything (even just a wildcard `*`).
3. Attempt to sign in with any google account

## Expected results
You are successfully logged in (such as wen **NOT** setting anything for `hostedDomains`)

## Actual results
Concourse returns the following error:
```unexpected hd claim ***********.com```

## Additional context
We are running Concourse via helm. Google authentication works perfectly if `hostedDomains` is unset, but is then wide-open

## Triaging info

* Concourse version:
7.6.0
* Browser (if applicable):
Chrome
* Did this used to work?
Have never been able to get this to work

**Comment by nwade** [comment]
I am seeing this issue as well!

**Comment by akath19** [comment]
@ikegentz  @nwade This is an issue with the way the chart is constructed, [this](https://github.com/concourse/concourse-chart/blob/ee175ceb91f6523df3be9535d12f2ad10239c73c/templates/web-deployment.yaml#L1290) line in the web-deployment is the one that passes the hostedDomains and it's not an array, it's a plain string.

Dex expects the hostedDomains key to be a string array but the chart expects a simple string, my fix was to pass the hostedDomains as a comma-separated list like this:

`hostedDomains: domain.com,domain-2.com,domain-3.com`

With this, all hosted domains are able to login and all non-hosted domains will get `unexpected hd claim`

**Comment by xtremerui** [comment]
@ikegentz is your issue resovled if the value of `hostedDomains` is just a string?

**Comment by ikegentz** [comment]
Yes, thank you @akath19 and @xtremerui . You can close this

**Comment by akath19** [comment]
Before I forget, I had an issue in which the last domain in the list wasn't picked up and got the same `unexpected hd claim` error, I solved it by adding an extra `,` at the end of the list, might be a bug, might be the way it is intended to work
