### ISSUE TITLE
ATC runs into file descriptor limits (FD usage scales with container count)

### ISSUE THREAD

**Issue by dsharp-pivotal** [concourse/concourse#784]
* Concourse version: 2.5.0
* Deployment type (BOSH/Docker/binary): BOSH

After increasing the number of workers we use, we've started to see our ATCs crash with out-of-file-descriptors errors.

We have also observed that the number of FDs in use by the ATC increases when we run builds.

To capture FD usage across our Web VMs, we used this monstrosity:

```sh
for n in 0 1 ; do echo -n "$(date) web/$n "; bosh ssh --gateway_host 10.32.120.6 --gateway_user vcap --gateway_identity_file $id_rsa web/$n "sudo bash -c '(pid=\$(pidof atc); echo \$(grep \"^Max open files\" /proc/\$pid/limits) \"open files:\" \$(lsof -p \$pid | wc -l) ; )'" 2>/dev/null | grep '^Max open files'; done
```

Our theory is this manifests into scaling situation where we need to run roughly 1 web VM for every ~4 worker VMs, because of the default FD limit of 1024 vs the container limit of a worker of 250.
- if you're worker-heavy in this ratio (more than 4 per web), you might see the FD issues more often. We're at 12 worker VMs and 2 web VMs right now, for example
- if you're worker-light in this ratio (less than 4 per web), you might see `insufficient subnets available` as your limiting resource -- Garden reporting that it can't make any more containers. When we had 6 worker VMs and 2 web VMs, we saw this more often.
- our math is a little fuzzy: we see pipes for `stdin`, `stdout`, `stderr`, and `exit`, so we're not sure which might double-up or be sent over individual sockets for a particular container back to the ATC.

To compare sockets vs. pipes on a worker VM (this example doesn't look for `stdin` pipes -- seemed like the closest pairwise correlation for us):

```awk
lsof -p $(pidof guardian) | awk '/std(err|out)|exit/{pipes++}/:7777/{sockets++}END{print "pipes: " pipes; print "sockets: " sockets}'
```

We don't think this is the same as #547 -- that was for FD limits on the worker processes.

d#, @cjcjameson, @schubert

#### Next steps:
- If the guardian-atc connection were to multiplex pipes into one socket, how would that affect other parts of the system?
- Has anyone else in the community ever tried telling ATC to raise its FD limit up from 1024 to the hard-limit of 4096?

**Comment by shijinabraham-leapyear** [comment]
I also saw a similar issue. The web node was ejected from load balanecer (health check is pings on 8080 and 2222 ). The atc logs contain "socket: too many files open" message.  One web node servers 3 workers, behind load balancers in AWS. 

I have restarted the web node with higher FD limits.

**Comment by mariash** [comment]
@shijinabraham-leapyear could you also run `lsof` to see what process have most open files and what are these files?

**Comment by shijinabraham-leapyear** [comment]
I restarted the concourse process. I will do it next time I run into the issue.

**Comment by schubert** [comment]
@shijinabraham-leapyear "I have restarted the web node with higher FD limits." how did you do this? Is your change persisted across restarts or did you do this manually?

**Comment by shijinabraham-leapyear** [comment]
@schubert  I just ran ulimit -n 4096 before running concourse. I was assuming that concourse will pick up the values from the shell.

**Comment by tylerschultz** [comment]
We saw this issue on our atc vm this morning. We're running v2.5.1. We have lsof output. Ping me if you'd like to see it.

**Comment by shijinabraham-leapyear** [comment]
After 2 days the lsof shows a count of 2000 for concourse web process.
Majority of the form 
concourse 7295 ubuntu 2137u     IPv6 6320729        0t0     TCP ip-<ipadders>.us-west-2.compute.internal:38522->ip-<ipaddress>.us-west-2.compute.internal:41296 (ESTABLISHED)
where ipaddress is the external ip address of the system.

Is this tsa <-> atc tcp connections?

**Comment by cunnie** [comment]
We have used the [ulimit release](https://github.com/pivotal-cf/ulimit-release) to get around this bug.

Here's the [Concourse BOSH manifest](https://github.com/pivotal-cf/bosh-concourse-deployments/blob/master/concourse/concourse-cpi.yml)

**Comment by ctaymor** [comment]
We seem to be running into this very frequently as well. (At least a few times a week, sometimes more often, bringing concourse to a total halt). Have not yet tried the ulimit release, though we will as soon as we're able.

**Comment by bbokorney** [comment]
@ctaymor the `ulimit` release fixed this for us, I would recommend giving it a try.

**Comment by mariash** [comment]
We created an aggregate issue for running out of file descriptors -
 https://github.com/concourse/concourse/issues/1201. If you still seeing this please report the appropriate data in that issue. Thanks!
