### ISSUE TITLE
Jobs won't start or cancel

### ISSUE THREAD

**Issue by Osis** [concourse/concourse#785]
* Concourse version: 2.5.0
* Deployment type (BOSH/Docker/binary): Bosh
* Browser (if applicable): N/A

I upgraded to 2.5.0 on Friday morning and everything was great. Resource issue had been resolved and I started and stop many manual jobs without any issues.

Fast forward to Monday morning, I manually started a job that won't actually start. It sits forever in this state...

![screen shot 2016-11-21 at 10 12 12 am](https://cloud.githubusercontent.com/assets/347097/20487863/052ea0d4-afd3-11e6-8812-08a372c6fb24.png)

Also, when canceling these stuck jobs it sits in this state...
![screen shot 2016-11-21 at 10 13 40 am](https://cloud.githubusercontent.com/assets/347097/20487915/396ab130-afd3-11e6-8ee9-14d95938209d.png)

I've checked the logs for atc, tsa, and groundcrew w/ @pivotal-topher-bullock and didn't see anything out of the ordinary.

**Comment by mariash** [comment]
@Osis 

what is happening in atc and garden logs? 

Is it stuck downloading image? Are you using `image` vs `image_resource`?

Was container created for build? Can you hijack into container and see what processes are there?

Is anything of this helps? restarting atc, restarting worker, recreating worker.

can you run the following db query:
`select * from jobs where name='your_job_name'`?

**Comment by paulcwarren** [comment]
@mariash: in our case we had a job that had previously ran and failed, now stuck in pending after a manual restart.  On our concourse around the time the pending job got stuck we saw 

```
{"timestamp":"1479755150.207756042","source":"atc","message":"atc.get-build-plan.failed-to-generate-plan","log_level":2,"data":{"error":"unknown build engine: ","session":"494532"}}
{"timestamp":"1479755782.605330467","source":"atc","message":"atc.get-build-plan.failed-to-generate-plan","log_level":2,"data":{"error":"unknown build engine: ","session":"496235"}}
{"timestamp":"1479755786.711224079","source":"atc","message":"atc.get-build-plan.failed-to-generate-plan","log_level":2,"data":{"error":"unknown build engine: ","session":"496263"}}
{"timestamp":"1479755789.380217075","source":"atc","message":"atc.get-build-plan.failed-to-generate-plan","log_level":2,"data":{"error":"unknown build engine: ","session":"496283"}}
{"timestamp":"1479755818.213109016","source":"atc","message":"atc.get-build-plan.failed-to-generate-plan","log_level":2,"data":{"error":"unknown build engine: ","session":"496354"}}
{"timestamp":"1479755840.028091431","source":"atc","message":"atc.get-build-plan.failed-to-generate-plan","log_level":2,"data":{"error":"unknown build engine: ","session":"496455"}}
``` 

is the atc logs.  Nothing in the tsa logs of note.

We could hijack the container for the job and we assume we are looking at the result of the previous failed run because we can see cloned git artifact inputs as well as other artifacts that are generated when the job runs.  

Running the query yeilds:-

```
SELECT inputs_determined, max_in_flight_reached FROM jobs where name='cf-deploy';
 inputs_determined | max_in_flight_reached
-------------------+-----------------------
 t                 | f
(1 row)
```

After monit restarting the atc the job started.

HTH

**Comment by Osis** [comment]
@mariash Restarting the worker helped for awhile but it seems like it's stuck again.

I checked out the garden logs with @pivotal-topher-bullock & @ClaraFuPivotal and they didn't see anything in particular.

[garden.txt](https://github.com/concourse/concourse/files/605429/garden.txt)

I'm using image_resource. Doesn't look like it's stuck downloading. It's run this many times and there aren't any changes to grab.

When I do ```fly containers``` I don't see any containers for my build. Looks like it hasn't reach to that stage yet.

Query output...
```atc=> select inputs_determined, max_in_flight_reached from jobs where name='your_job_name';
 inputs_determined | max_in_flight_reached 
-------------------+-----------------------
(0 rows)
```

**Comment by Osis** [comment]
We took a look at some more logs and found that ATC is complaining about not having a worker for the container. This cluster has always had 1 worker and works fine until I leave for the night.

[atc.txt](https://github.com/concourse/concourse/files/606902/atc.txt)
[v1_workers.txt](https://github.com/concourse/concourse/files/606903/v1_workers.txt)

**Comment by Osis** [comment]
Again, looks like restarting ATC solves the issues temporarily...

```bosh restart web --force```

or the quicker, more involved way...

```
bosh ssh web
sudo su
monit restart atc
```

**Comment by Osis** [comment]
One possible explanation is that Concourse is leaking containers? Maybe that's why it fails every morning? After leaving it for awhile it then thinks there aren't enough resources to run jobs.

**Comment by RochesterinNYC** [comment]
Buildpacks team is seeing this too:

![screen shot 2016-11-22 at 11 19 54 am](https://cloud.githubusercontent.com/assets/1504464/20532164/07526f38-b0a7-11e6-9d67-476f79cd68f6.png)

For us, the containers do not exist and hijack says `no containers matched your search parameters!` when we try to hijack the specific build for that job.

The Concourse VM vitals look normal:

```
+-------------------------------------------------+---------+----+----------+----------------+-----------------------+-------+-------+------+--------------+-------------+------------+------------+------------+
| VM                                              | State   | AZ | VM Type  | IPs            |         Load          | CPU   | CPU   | CPU  | Memory Usage | Swap Usage  | System     | Ephemeral  | Persistent |
|                                                 |         |    |          |                | (avg01, avg05, avg15) | User  | Sys   | Wait |              |             | Disk Usage | Disk Usage | Disk Usage |
+-------------------------------------------------+---------+----+----------+----------------+-----------------------+-------+-------+------+--------------+-------------+------------+------------+------------+
| db/0 ([redacted])     | running | z1 | database | 10.150.0.3     | 0.16, 0.26, 0.26      | 2.6%  | 1.0%  | 2.6% | 1% (186.2M)  | 0% (0B)     | 43%        | 0%         | 0%         |
| web/0 ([redacted])    | running | z1 | web      | 10.150.0.2     | 0.59, 0.39, 0.37      | 7.2%  | 3.3%  | 0.1% | 3% (201.1M)  | 0% (0B)     | 43%        | 2%         | n/a        |
|                       |         |    |          | 104.196.47.170 |                       |       |       |      |              |             |            |            |            |
| worker/0 ([redacted]) | running | z1 | worker   | 10.150.0.4     | 2.75, 2.96, 1.87      | 34.5% | 15.5% | 0.2% | 17% (2.4G)   | 5% (765.3M) | 43%        | 24%        | n/a        |
| worker/1 ([redacted]) | running | z1 | worker   | 10.150.0.7     | 0.16, 0.34, 0.46      | 4.5%  | 2.8%  | 0.1% | 13% (1.9G)   | 1% (79.9M)  | 43%        | 9%         | n/a        |
| worker/2 ([redacted]) | running | z1 | worker   | 10.150.0.9     | 2.58, 1.58, 0.93      | 26.9% | 6.0%  | 0.8% | 11% (1.6G)   | 2% (290.5M) | 43%        | 11%        | n/a        |
| worker/3 ([redacted]) | running | z1 | worker   | 10.150.0.6     | 0.46, 0.36, 0.34      | 5.0%  | 2.2%  | 0.1% | 10% (1.4G)   | 37% (5.5G)  | 43%        | 9%         | n/a        |
| worker/4 ([redacted]) | running | z1 | worker   | 10.150.0.5     | 0.76, 2.09, 1.60      | 5.6%  | 3.7%  | 0.8% | 12% (1.7G)   | 14% (2.1G)  | 43%        | 12%        | n/a        |
| worker/5 ([redacted]) | running | z1 | worker   | 10.150.0.8     | 0.26, 0.28, 0.37      | 3.8%  | 3.0%  | 0.2% | 10% (1.5G)   | 5% (803.1M) | 43%        | 9%         | n/a        |
+-------------------------------------------------+---------+----+----------+----------------+-----------------------+-------+-------+------+--------------+-------------+------------+------------+------------+
```

`atc.stdout.log.1`:

```
{"timestamp":"1479823187.337899923","source":"atc","message":"atc.container-keepaliver.looking-up-container","log_level":1,"data":{"handle":"4e4d355a-e4c2-4e67-44e8-810d9a353599","session":"18"}}
{"timestamp":"1479823187.399357557","source":"atc","message":"atc.container-keepaliver.looking-up-container","log_level":1,"data":{"handle":"99eb6089-76d0-4ce5-592b-58ac4ac58ccf","session":"18"}}
{"timestamp":"1479823189.621998310","source":"atc","message":"atc.syncer.stacks:radar.scan.tick.check-failed","log_level":1,"data":{"exit-status":1,"pipeline-scoped-name":"stacks:resource:stacks-diego-deployment","session":"13.25.17.3468"}}
{"timestamp":"1479823193.516378880","source":"atc","message":"atc.syncer.stacks-nc:radar.scan.tick.init.created","log_level":1,"data":{"container":"54ea4a0e-ae1e-45e2-42ec-2dca4ef3af7f","pipeline-scoped-name":"stacks-nc:resource:stack-github-release-final","session":"13.27.24.3969.1"}}
{"timestamp":"1479823197.213425636","source":"atc","message":"atc.syncer.stacks:radar.scan.tick.check-failed","log_level":1,"data":{"exit-status":1,"pipeline-scoped-name":"stacks:resource:stacks-cf-deployment","session":"13.25.16.3468"}}
{"timestamp":"1479823197.499479055","source":"atc","message":"atc.syncer.edge-2-gcp:radar.scan.tick.check-failed","log_level":1,"data":{"exit-status":1,"pipeline-scoped-name":"edge-2-gcp:resource:cf-deployment","session":"13.3.3.3885"}}
```

`atc.stdout.log`:

```
{"timestamp":"1479832427.054923534","source":"atc","message":"atc.container-keepaliver.looking-up-container","log_level":1,"data":{"handle":"9c3b5d26-9061-4892-6204-d61ab6a50013","session":"18"}}
{"timestamp":"1479832430.158047438","source":"atc","message":"atc.syncer.stacks:radar.scan.tick.check-failed","log_level":1,"data":{"exit-status":1,"pipeline-scoped-name":"stacks:resource:stacks-cf-deployment","session":"13.25.16.3924"}}
```

`atc.stderr.log`:

```
2016/11/22 16:11:50 http2: server: error reading preface from client 86.62.119.171:50059: timeout waiting for client preface
2016/11/22 16:11:59 http2: server: error reading preface from client 86.62.119.171:55022: timeout waiting for client preface
2016/11/22 16:14:44 http2: server: error reading preface from client 86.62.119.171:50266: timeout waiting for client preface
2016/11/22 16:16:14 http2: server: error reading preface from client 92.38.9.82:65425: timeout waiting for client preface
2016/11/22 16:16:26 http2: server: error reading preface from client 68.87.42.110:34010: timeout waiting for client preface
2016/11/22 16:16:35 http: TLS handshake error from 92.38.9.82:65427: EOF
2016/11/22 16:17:07 http2: server: error reading preface from client 31.173.100.120:3069: timeout waiting for client preface
2016/11/22 16:18:38 http: TLS handshake error from 31.173.100.120:10831: EOF
2016/11/22 16:32:19 http2: server: error reading preface from client 94.188.78.138:56271: timeout waiting for client preface
2016/11/22 16:32:22 http: TLS handshake error from 94.188.78.138:56273: EOF
2016/11/22 16:32:45 http2: server: error reading preface from client 84.47.137.226:59904: timeout waiting for client preface
2016/11/22 16:32:50 http: TLS handshake error from 84.47.137.226:59906: EOF
```
As a side note, the errors from the `atc.stderr.log` look like some bots were running port scans, so interesting but not probably relevant to this issue.

Additionally, we are having the ATC do SSL termination and our public IP points directly to the atc.

**Comment by mariash** [comment]
We are suspecting a stuck goroutine. If anyone sees that again could you run `curl http://127.0.0.1:8079/debug/pprof/goroutine?debug=2` on ATC VM to get stack dump.

**Comment by Osis** [comment]
Output of the curl command you provided right after the symptoms returned.

[curl.txt](https://github.com/concourse/concourse/files/608027/curl.txt)

**Comment by JesseTAlford** [comment]
We've got this on CF RelInt, too. We're working around it by restarting the web jobs.

**Comment by databus23** [comment]
We are also getting this 2-3 times a week.

[Here is a stackdump](https://mdocs.sap.com/mcm/public/v1/open?shr=9_XyxXHo4gs1SUgU05VCOtiUiS86azHDOpo17FGoX8E&obj=4FezXhdcPumg2MF7bwAxnrIHOQEGk1KAD4e36b_nLl0) from our single 2.5.0 web component

At the time of the stackdump we had at least 4 jobs stuck like described above.

**Comment by ese** [comment]
Same problem here.

dump file: https://filebin.net/td2tp70iih1w6hp0/dump

**Comment by databus23** [comment]
I don't know whats different today but I already had to restart our concourse 4 times because of this. Some pretty rough weather out there right now...

**Comment by vito** [comment]
FYI we resolved this in-person and it ended up being hanging `check` scripts for some (many) of the resources, likely caused by the default MTU (1500) being higher than GCP's (1460), leading to dropped packets and thus hanging network calls.

It may not be an MTU issue for some of you, but I'd still check for hanging `check` scripts in all the resources feeding into the job - it may be a bug with the resource type.

**Comment by Osis** [comment]
I've tried MTU settings of 1500 (default), 1450 (GCP recommends < 1460), and 1430 (just in case) which has yielded no change in behaviour.

While in-person though we did discover that it was one particular resource (Pivnet) stuck in this state, so I'm following up with them to dig deeper.

**Comment by databus23** [comment]
We just had another occourence and I can't find any hanging check containers.
![image](https://cloud.githubusercontent.com/assets/439223/20926468/b3a1cc6e-bbbc-11e6-84cd-ad23ce63400d.png)

The task that won't start has 4 inputs and I can only find check containers for two of the inputs:
```
$> fly containers | grep agent-image-master.git                                                                                                                                                     
5bf27eed-11bd-411c-689d-48d849b8a851  00:04:14  00:05:00  mo-a5b515ae6   monasca               none                 none  none  check  agent-image-master.git                           n/a
$> fly containers | grep agent-image.version
$>
$> fly containers | grep agent-master.swift
$>
$>fly containers |  fly containers | grep  build-scripts-master.git                                                                                                                                                  
7255772f-16da-475a-5823-29094bf105be  00:04:29  00:05:00  mo-9beadb7bb   monasca               none                 none  none  check  build-scripts-master.git                         n/a
```

Hijacking into the two existing containers shows nothing running in there:
```
$>fly hijack -c monasca/build-scripts-master.git ps auwx
PID   USER     COMMAND
    1 root     /proc/self/exe init
 2357 root     ps auwx
$> fly hijack -c monasca/agent-image-master.git ps auwx
PID   USER     COMMAND
    1 root     /proc/self/exe init
  514 root     ps auwx
```

So it doesn't look to me like this is caused by hanging check containers.

Is this maybe related to #753 or are the two missing check containers nothing to be worried about?

**Comment by databus23** [comment]
And another one:
![image](https://cloud.githubusercontent.com/assets/439223/20926904/34fed322-bbbf-11e6-9d6a-53e4cfed9a8a.png)

Again one of the check containers was missing (notification.image). The other three didn't have any processes running in them.

**Comment by beeva-carlosleon** [comment]
This issue is corrected in version 2.5.1?
`The Docker Image resource will now propagate the correct --mtu value to the daemon, fixing image fetching flakiness on IaaSes like GCP, which have a default MTU lower than 1500.`

We are facing the same issue sometimes. Remove the pipeline and recreate works, but we lose the history.

Thanks!

**Comment by ese** [comment]
I am running 2.5.1 with same problems

**Comment by ahelal** [comment]
same issue delete and recreate fixes it

**Comment by JesseTAlford** [comment]
We're hitting this again today, too, and previously useful fixes like restarting the web jobs aren't working. Any update on this? We're not running concourse on GCP yet.

**Comment by vito** [comment]
Consolidating this into https://github.com/concourse/concourse/issues/844 as there are a few related issues and I'd like to highlight the above diagnostics collection.

Thanks for the information provided thus far! But if you could, going through the linked issue would be a great help.
