### ISSUE TITLE
I want to see builds trigger when I upgrade my Concourse instance

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#786]
# Feature Request

## What challenge are you facing?

In our CI Docker image, we install the `fly` CLI [using the HTTP endpoint provided by our concourse deployment](https://github.com/cloudfoundry/buildpacks-ci/blob/master/Dockerfile#L68). 

When we update our Concourse version, the `fly` CLI on the docker image is out of sync. We only find out about this through `fly` CLI errors in builds that use the CI Docker image. To resolve, we have to manually trigger the `Dockerfile` build (and remember that this is necessary!).

## A Modest Proposal

It would be great to have a first-class Concourse resource that gives the version of a Concourse deployment.

This would make it possible for us to have the Dockerfile job trigger on an upgrade without manual intervention.

One possibility would be to add an `in`/`get` to the `bosh-deployment-resource`. The `get` could return information about the deployment given by `bosh deployments`.

Another would be a simple standalone Concourse resource simply for this purpose.

A third alternative would be a general resource wrapping several Concourse endpoints.

**Comment by chendrix** [comment]
Hi there,

The bosh-deployment-resource has officially been deprecated in favor of the [cloudfoundry/bosh-deployment-resource](https://github.com/cloudfoundry/bosh-deployment-resource)

It looks like they've created an `in`. 

Thanks again for your time.
