### ISSUE TITLE
Resource types in a pipeline in the web UI are difficult to distinguish

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#788]
# Feature Request

## What challenge are you facing?

When eyeballing a complex pipeline with many resources being passed from place to place, it becomes odious to add resource types (`foo-git`, `bar-s3`) to the name to indicate what is what. It's also difficult to visually inspect.

## A Modest Proposal

It would be nice if resources could publish an icon, which would be shown next to the resource name at each step in a pipeline. At a glance I could see which resources were git repos, S3 files, PivNet resources and so on.

As an intermediate step, a tooltip showing metadata about the resource, including its type and current version information, could be shown when I hover over a resource.

**Comment by vito** [comment]
Related to https://github.com/concourse/atc/issues/64

**Comment by jchesterpivotal** [comment]
I searched but didn't see that one. Do you want me to close this one?

**Comment by vito** [comment]
I'm not inclined to close either yet; they're very close but slightly different. They both request resource type icons but the other also requests to show user-specified information (e.g. `.deb`/etc.).

I like this issue more for the resource type indicator alone, and the other one we can keep open for the extra bit (or close it if I decide it's too much).

**Comment by jtarchie** [comment]
Related to https://github.com/concourse/concourse/issues/1120

**Comment by jama-pivotal** [comment]
Merging in comments from #1120 and closing that one off 

We'll need to do a few things here before getting started:

- [ ] Get a sense of how those icons will be shown on the UI
- [ ] specify the preferred image dimensions and preferred formats
- [ ] define how the icons should be provided (special filename?)
- [ ] Update docs

**Comment by CAFxX** [comment]
I agree, the more we build pipelines and the harder it gets to remember how each works by just looking at the dashboard. Just a small note, it may be worthwile to consider that each resource may provide configuration-dependent icons (e.g. for the cf resource I would love to have different icons for normal and b/g deploys -- and maybe tomorrow for additional ops that the cf resource may provide)

**Comment by marco-m** [comment]
GoCD uses icons for resources, see for example the icons for git and hg:
![gocd-value-stream](https://user-images.githubusercontent.com/3075069/51964533-25727400-2467-11e9-9a66-388e43f25125.png)

**Comment by vito** [comment]
@Lindsayauchin had some mockups in https://github.com/concourse/concourse/pull/3220 for adding tooltips. That seems like a good start?

**Comment by marco-m** [comment]
I would prefer the approach in #3169 (same icon sets in details and overview pages), but if for any reasons that is not possible, then yes, the tooltips would be a good start.

**Comment by pivotal-jamie-klassen** [comment]
@jchesterpivotal @vito @marco-m can we consider this fixed by #3581?

**Comment by jchesterpivotal** [comment]
I like it a lot. In future I hope we can also add this to the v2 resources as an option. I consider this one closeable for now.

**Comment by marco-m** [comment]
@pivotal-jamie-klassen  Yes, I consider this fixed, thanks!
