### ISSUE TITLE
Job Stuck - discovering any new versions of <<resource-name>> v2.5.0

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#789]
# Bug Report

I added a new repo to my pipeline. Clicking on the resource shows a version, but jobs are stuck "discovering new versions". 

Lower down under waiting for a suitable set of input versions it says "no versions available" for the newly added resource.

Didn't help to force a check with fly, or to abort and retry the job.

deployed via bosh on aws.

**Comment by xtreme-gavin-enns** [comment]
FYI after aborting the hanging jobs they never finish loading in the web ui

**Comment by mariash** [comment]
@xtreme-gavin-enns can you run 2 db queries:

```
select * from jobs where job_name='YOUR_JOB_NAME';
select * from next_build_inputs where job_id=YOUR_JOB_ID;
```

**Comment by mariash** [comment]
@xtreme-gavin-enns is fly check-resource also hanging?

**Comment by xtreme-gavin-enns** [comment]
Debugging with Topher atm
![screen shot 2016-11-23 at 10 18 05 am](https://cloud.githubusercontent.com/assets/1178694/20567328/413adffe-b166-11e6-94d7-3119932223b5.png)
![screen shot 2016-11-23 at 10 17 58 am](https://cloud.githubusercontent.com/assets/1178694/20567327/413897ee-b166-11e6-99e8-42fde09baacd.png)

**Comment by xtreme-gavin-enns** [comment]
fly check-resource succeeds, the resource shows two versions. Topher grabbed the atc stack dump. It looks like the atc thinks there are several workers when there is only one

**Comment by xtreme-gavin-enns** [comment]
[db-stuffs.txt](https://github.com/concourse/concourse/files/609265/db-stuffs.txt)

**Comment by mariash** [comment]
looks like resource does not have versions for build. Are all passed constraints satisfied?

**Comment by xtreme-gavin-enns** [comment]
There are none.
![screen shot 2016-11-23 at 1 56 17 pm](https://cloud.githubusercontent.com/assets/1178694/20574866/a9e0eab2-b184-11e6-9459-008812dda9b1.png)

**Comment by xtreme-gavin-enns** [comment]
Oh, one more fyi:

bosh deploy --recreate fixed it, with no changes to the pipeline or resource history

**Comment by vito** [comment]
Not sure we'll be able to do much more with this unfortunately. If it happens again, could you grab a stack dump from the ATC and reopen? If a redeploy fixed it it may have been a stuck goroutine, which we should investigate. A restart probably would have also sufficed in that case.

You can get a stack dump by either sending `SIGQUIT` to the pid, which will dump it to stderr and cause it to exit, or by curling `http://127.0.0.1:8079/debug/pprof/goroutine?debug=2` on the VM.

**Comment by xtreme-gavin-enns** [comment]
topher grabbed a stack dump last time, but we didn't want to post it here due to potential leaks of sensitive info. He should still have it. I'll totally do that next time it crops up

**Comment by vito** [comment]
cool. for future reference there shouldn't be anything sensitive in a stack
dump

**Comment by Murryy79** [comment]
I am stuck with same issue "discovering any new versions"

![image](https://user-images.githubusercontent.com/19574664/28345773-e55aea52-6bf1-11e7-86a4-86d518ad81c0.png)

my concourse is 2.7.4

how was this issue fixed?

thanks

**Comment by padgett59** [comment]
I had this same issue. I simply destroyed the existing pipeline (set-pipeline) and recreated it with set-pipeline. This cleared the issue and it built and ran file.

**Comment by balajigit2506** [comment]
@padgett59 - your solution worked for me on the first try!

**Comment by saami97** [comment]
@padgett59 unfortunately this didn't work for me. I tried destroying and setting pipeline multiple times. 

![image](https://user-images.githubusercontent.com/25372729/209951027-b77f179b-0f53-4c0f-969e-5c0816754082.png)
