### ISSUE TITLE
Jobs and resources with periods in their name do not show up under groups.

### ISSUE THREAD

**Issue by dennisjbell** [concourse/concourse#7896]
## Summary

Jobs with names that contain periods or having resources with names containing periods do not show up in groups.

## Steps to reproduce

Create a pipeline that contains a group that consists of one job.  That job has one task and one resource.  The job name or the resource name contains a period (ie -  resource: concourse-go_1.16_github ).  set the pipeline via fly.  Attempt to view the pipeline group on the webui -- confirm that no job or resource boxes show.  Change periods to underscores, refly pipeline, refresh concourse, confirm pipeline now shows up.

## Expected results

The pipeline should show up under the group tab.

## Actual results

No boxes show up under that group tab.  If you have other groups that do not have job or resource names containing periods, those groups will show up under their respective tab.

## Additional context

According to https://concourse-ci.org/config-basics.html#schema.identifier, periods should be valid identifiers.

## Triaging info

* Concourse version: v7.5.0
* Browser (if applicable): tested on Chrome and Firefox (latest)
* Did this used to work? Yes

**Comment by taylorsilva** [comment]
Was fixed in 7.6.0 by https://github.com/concourse/concourse/pull/7616
