### ISSUE TITLE
Some invalid pipeline yaml silently ignored

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#791]
# Bug Report

when a job has
```
 inputs:
      -name: credentials
```
concourse silently ignores the inputs.

While it *is* valid yaml if concourse doesn't know what to do with it it should complain instead of silently ignoring it.

**Comment by xtreme-gavin-enns** [comment]
P.S. I've seen this come up in more troublesome scenarios, but I can't remember any examples. I've seen it happen that larger sections of pipeline get ignored silently. Usually it's easy to spot when builds fail due to missing inputs or whatever, but sometimes it's a helluva gotcha

**Comment by chendrix** [comment]
Hopefully this can be included in #709
