### ISSUE TITLE
Groups as attribute to the jobs

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#793]
# Feature Request

## What challenge are you facing?

I find that maintaining the pipeline groups section a bit annoying (especially if you generate your pipelines) and there are many ways it to be simplified - without any additional complication of the software.

## A Modest Proposal

One option will be the groups setting to support regular expression. This way having group `all` for example will be very easy to define and maintain.

What I think is probably the best solution though is to have the groups a job belongs to, to be part of the job configuration itself. This is exactly what I do, and then I use scripts to change it to the expected format.

**Comment by vito** [comment]
yep! sounds the same as https://github.com/concourse/concourse/issues/469
