### ISSUE TITLE
Build logs get immediately reaped while re-running an already reaped build with the same inputs

### ISSUE THREAD

**Issue by anijayn** [concourse/concourse#7951]
## Summary

While re-running a build whose logs have been already reaped, the build runs but the newer build's logs gets reaped immediately.

## Steps to reproduce

1. Set `maxBuildLogsToRetain` to 10.
2. Create a sample pipeline with one or more jobs.
3. Run more than 10 builds. 
4. Run the 11th build so that the build # 1 gets reaped.
5. Re-running the build # 1  with the same inputs.

## Expected results
The build logs of the build # 1.1 should not be reaped.

## Actual results
The build logs of the build # 1.1 gets reaped.

## Additional context
Attaching screenshots from our actual builds:
<img width="1784" alt="Screenshot 2022-01-12 at 3 06 39 PM" src="https://user-images.githubusercontent.com/63807864/149109524-e45da025-f7c1-4b32-899b-482e33a70ba9.png">
<img width="897" alt="Screenshot 2022-01-12 at 2 46 56 PM" src="https://user-images.githubusercontent.com/63807864/149116813-7ed4dc32-db6b-4570-b162-b62196babd53.png">

## Triaging info

* Concourse version: v6.7.6
* Browser (if applicable): Microsoft Edge

**Comment by xtremerui** [comment]
Hi @anijayn thx for reporting the issue. After investigation, not only build 1.1 got reaped but build 2 also gone too.
