### ISSUE TITLE
Fly intercept with url does not work

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#7954]
## Summary

When I try to run `fly intercept -u <url>`, it errors with 
```
fly -t ci intercept -u https://ci.concourse-ci.org/teams/main/pipelines/<build-path>
error: URL doesn't match that of target
```

Not sure if it's just me or if there is a bug in fly intercept with url. When I use other flags such as job/pipeline to intercept, it works.

## Expected results

It should be able to intercept using the url.

## Actual results

Run `fly intercept -u <url>` and it should fail.

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable):
* Did this used to work? Yes

**Comment by xtremerui** [comment]
Works for me
```
⟩ fly -t ci intercept -u https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/integration/builds/795
1: build #795, step: concourse-image, type: get
2: build #795, step: dev-image, type: get
3: build #795, step: notify, type: put
4: build #795, step: slack-notifier, type: check, expires in:
choose a container: 1
root@7c6a2bff-4d8a-4863-740b-ebfde478a96f:/tmp/build/get#
```

what is your fly version and have you tried `fly sync`?

**Comment by clarafu** [comment]
I have tried fly sync 🤔

**Comment by clarafu** [comment]
No idea what caused it so just closing this 🤷  probably something that went wrong in my end
