### ISSUE TITLE
workers fail to start after CentOS Stream 8 system upgrade

### ISSUE THREAD

**Issue by x3nb63** [concourse/concourse#7985]
upgraded the full system and now the concourse-worker pods fail to start with:

```
...
concourse-worker error: Exit trace for group:
concourse-worker garden exited with error: Exit trace for group:
concourse-worker containerd-garden-backend exited with error: setup host network failed: create chain or flush if exists failed: running [/sbin/iptables -t filter -N CONCOURSE-OPERATOR --wait]: exit status 3: iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
concourse-worker Perhaps iptables or your kernel needs to be upgraded.
concourse-worker
concourse-worker containerd exited with nil
concourse-worker
concourse-worker container-sweeper exited with nil
concourse-worker debug exited with nil
concourse-worker healthcheck exited with nil
concourse-worker volume-sweeper exited with nil
concourse-worker baggageclaim exited with nil
concourse-worker beacon exited with nil
```

this is CentOS Stream 8 and the pods run with `privileged: true`. Concourse image is `concourse/concourse:7.6.0` and that very image works fine on other hosts still running CentOS 8, the non-Stream release.

At that point I am lost and don't unterstand the error either. So no workaround for me.

_Originally posted by @x3nb63 in https://github.com/concourse/concourse/issues/6859#issuecomment-1015569799_

Since I am still stuck I played with iptables and see this

```
[root@kc01 ~]# docker run -it --rm --entrypoint /bin/sh concourse/concourse:7.6.0
# id
uid=0(root) gid=0(root) groups=0(root)
# /sbin/iptables -t filter -N CONCOURSE-OPERATOR --wait
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```
so, here is the error at least. Unfortunately this looks very similar on a node where the concourse-worker does start:

```
[root@kc03 ~]# docker run -it --rm --entrypoint /bin/sh concourse/concourse:7.6.0
# id
uid=0(root) gid=0(root) groups=0(root)
# /sbin/iptables -t filter -N CONCOURSE-OPERATOR --wait
iptables v1.6.1: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

now I am lost on Why does it start on that kc03 node?

The Kubernetes `StatefulSet` is the very same for both, same capabilities granted and whatever else the helm chart does. So the machines only differ in that kc01 was upgraded to CentOS Stream two days ago.

I verified ist not the kernel version, see #6859

**Comment by neumayer** [comment]
Thanks for posting your findings! We have the same issue with Oracle Linux from 8.4, and I was mid debugging myself.

**Comment by Gems** [comment]
Resolved by applying this comment https://github.com/concourse/concourse/commit/eed48c6f4f2ff27a477925f3a3c9da506336921a

change `CONCOURSE_WORKER_RUNTIME: "containerd"` to `CONCOURSE_WORKER_RUNTIME: "houdini"`
