### ISSUE TITLE
conditional put on_success, on_failure

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#799]
Hi there!

# Feature Request
Missing support for conditional put

## What challenge are you facing?

I want to put to a slack-resource if a task fails, currently you are allowed to add a conditional sub-tasks in on_success, on_failure hooks, but I only need a conditional put to a resource so adding a task file is unnessecary

## A Modest Proposal

conditional put in the same manner as sub-tasks can be conditional

**Comment by devdavidkarlsson** [comment]
**Example:** 

 - task: run-tests # Docker in docker composing the test stack:
    privileged: true
    file: devops-repo/pipeline/tasks/test-e2e.yml
    image: docker-registry-dind
    on_fail:
      - put: slack-alert
            params:
              channel: '#oasis-ci'
              icon_emoji: ':concourse:'
              text: |
                :warning: Build failure!

**Comment by adamwg** [comment]
That works for me today (I'm using concourse 2.5.0), it's just not well documented. Anything that can go in a job (`get`, `put`, `do`, `aggregate`, etc.) can go in an `on_failure` or `on_success`.

**Comment by chendrix** [comment]
Yeah this is definitely possible. I'm going to close this but label it with docs so we can see it when we get to later docs stories.
