### ISSUE TITLE
Stateful Hooks

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#80]
Other CI systems have features like "perform some action (e.g. email/slack) on every failure and once when the build is fixed, but not every time the build passes."

Is something similar planned for concouse

**Comment by Osis** [comment]
@robdimsdale does the on_success on_failure fulfill this need?

**Comment by robdimsdale** [comment]
@Osis no - the intention here is to be able to capture scenarios like:
- this job passed on the most recent run, and because the previous run failed I will send an email
- this job passed on the most recent run, but because the previous run failed I will *not* send an email

The challenge here is that the existing hooks like `on_failure` and `on_success` are stateless; they do not take into account any history. This is by design, and makes concourse much simpler, but also much less powerful.

I've used this proposed feature on other CI tools with success - I think there's a lot of value in this conditional notification.

**Comment by fiddlerpianist** [comment]
Wouldn't it be simpler for the statefulness to exist in a resource that provides input to the task that is called from `on_failure` or `on_success`? That way, you're keeping the state in the resource (where it belongs).

**Comment by robdimsdale** [comment]
@fiddlerpianist yes, that would be simpler from concourse's perspective, and I agree would fit much more cleanly into the stateless architecture of concourse.

Except now we have to extend each and every resource with this feature. Instead of consolidating this logic in once place we have to re-invent it multiple times. Once for the email resource, once for slack resource, etc.

To be clear, I don't expect this feature to land precisely because it's quite far from concourse's current architecture and philosophy, but it's a feature I miss from other CI systems, and I think there's value in capturing this conversation in a public form for future reference.

**Comment by jama-pivotal** [comment]
Hi there, while it is very interesting to do, there isn't much traction on this so we're closing it for now.
