### ISSUE TITLE
Containers with created and meta_type check not recycling.

### ISSUE THREAD

**Issue by blyles** [concourse/concourse#8001]
## Summary

Containers with state of created and type check aren't being recycled despite check_recycle_period: 30m 

## Steps to reproduce

Unsuccessfully able to reproduce this point through docker.

## Expected results

created/check containers to be recycled after 30 minutes.

## Actual results

Max containers being reached daily and no containers being recycled.

## Additional context

ephemeral disks, bosh deploy, the resource_config_check_session_id is not present in the resource_config_check_sessions table.  A backup and restore was done from another concourse to recover it into this one, brand new build.

## Triaging info

* Concourse version: Concourse 7.6
* Browser (if applicable): 
* Did this used to work?: Yes

**Comment by taylorsilva** [comment]
You might not have enough space for all the containers your pipelines generate. You may need more workers.

To confirm this, have you been able to track a single container, based on its ID/handle, and see that it never gets deleted? You can do this with `fly containers`. Pick any check container and check if it still exists 30m+ later.

**Comment by blyles** [comment]
It's consumption of max containers at 2000 takes 24 to 48 hrs thus a need
to recreate the workers.

They weren't going on the last check I'll give it one more time.

There's a total of 15 workers and not all pipe lines are used only 20 or
so.  2000 containers hits and it never goes down

**Comment by blyles** [comment]
We definitely aren't seeing check containers recycled and are counting against the system we filled the containers up twice over 4 days.  There's only a hand full of pipelines being run.

I checked several containers over 2-3 day period and fly containers still picks things up and its stuck in the database.   We're about to resort to deletion of the entire infrastructure to start again assuming somethings corrupt.

Doing some more analysis today.

**Comment by blyles** [comment]
We've found the following;

- Containers and volumes that were to previous registered workers.
**IF we recreate workers previous containers and workers in the database are still there, this is done via a bosh recreate.   The workers get de-registered and a new one spins up, the disks are ephemeral.

- fly volumes ceases to work.  throws a 500 internal server error.  This is only rectified by removing volumes or containers manually that aren't registered to a worker in workers table.

- containers continue to not be recycled for check/created containers.

**Comment by blyles** [comment]
![image](https://user-images.githubusercontent.com/5386554/151830916-75a0e9f3-64db-478d-ba95-dbb3611702b5.png)

You can see here that the container volume comes up and (not sure if this is right).

      select count(*) from containers where state = 'created' and meta_type = 'check';
    
Comes back with 7892 containers.

       select count(*) from containers 

Comes back wit 7851 containres, so less then 50 actual containers.

Anything i could be looking at to determine why this is the case, nothing is showing up in query logging error logging, atc or tsa.

**Comment by taylorsilva** [comment]
I have no idea how this could be happening. GC logic hasn't changed for a while and this, like you said, seems like GC is not happening at all.

In your logs, do you see any of the GC components being called at all?

You can also check the `components` table in the database. It'll show the last time `collector_volumes` and `collector_containers` ran. Maybe they're not running for some reason?

**Comment by blyles** [comment]
12,collector_containers,30s,2022-02-02 16:27:47.976204 +00:00,false
15,collector_workers,30s,2022-02-02 16:27:50.331240 +00:00,false

We're resorting to destroying it all and starting again, maintenance windows are planned to scorch earth.  We suspect its a bad state of workers/registered through bosh recreate and resource cache.

resource_config_session is that a required field for the container referencing? If it is, its missing for 50% of the containers, our other 7 instances of concourse all check containers have a correlated row in this table.

Turning on logging for the database doesn't show us waht's going on either been incredibly frustrating.

**Comment by blyles** [comment]
Just an update here, we gave up and found sequence problems in the system causing the resource_config session tables to get all out of whack.

So we burned the database to the ground, exported all pipelines and settings and rebuilt the cluster and container recycling is stable and not showing more then max containers then 50-60 on 5 workers where we were burning 2000 containers on 15 workers in under 12 hours.

There's definitely something not getting caught or logged in the container create - i was unfortunately unable to replicate to a point of catching the exception.

**Comment by xtremerui** [comment]
@blyles since the deployment is repaved, have you seen the problem again?

**Comment by blyles** [comment]
We've not seen the problem again - I want to say that he did a pg_dump but i can't be sure what he did, i got to work and he said it was ready :)

**Comment by blyles** [comment]
We've not seen a re-appearance of this issue since we blew it up, we suspect it was a data corruption with the tear down of the workers.  We can't even re-create the scenario after numerous tests.
