### ISSUE TITLE
`bind_port` property is overloaded when using colocated jobs with bosh-init

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#801]
# Feature Request

## What challenge are you facing?

I'm using `bosh-init` to deploy concourse to GCP. Several of the jobs use `bind_port` as the property to set the port for that job, which conflict when those jobs are coloated.

Since, `bosh-init` doesn't support the BOSH 2.0 manifest syntax, I'm unable to actually set the port for `atc` to 80.

## A Modest Proposal

Provide a way to set ports, maybe support `bind_port` and `job_name.bind_port`, then have to evaluate with precedence.

```
port = p("job_name.bind_port") || p("bind_port")
```

Thanks.

**Comment by vito** [comment]
I don't want to fix this; `bosh-init` shouldn't force releases to have so much clutter. 😢

I can't recommend using it for anything more than the BOSH director itself these days - there are too many gotchas. A better solution for single-VM deploys would probably be BOSH Lite - maybe we could convince @cppforlife to have a GCP version of it?

**Comment by vito** [comment]
Hmm, alternatively, I wonder how far could you get with `bosh-init`ing a director with the Garden CPI? Never tried it.

**Comment by jtarchie** [comment]
I got something to [work](https://github.com/jtarchie/concourse-bosh-init-gcp/blob/master/manifest.yml). I'm just stalk with port 8080, instead of port 80, which makes for nice domains. :-)

As for the garden-cpi, would the idea be to just bring up a vm-instance on GCP, then just use the cpi to install things?

**Comment by cppforlife** [comment]
for gcp anf in future aws going to use cloudfoundry/bosh-deployment. there is bosh-lite ops file to turn director to use garden.

**Comment by jtarchie** [comment]
It would also be nice if GCP supported port forwarding vis load balancer.

**Comment by jtarchie** [comment]
Alright I'll close this. Doesn't seem to be a clean solution.
