### ISSUE TITLE
Concourse continues serving a revoked Let's Encrypt certificate

### ISSUE THREAD

**Issue by kberzinch** [concourse/concourse#8021]
## Summary

I operate a small Concourse cluster that uses the Let's Encrypt integration to retrieve a certificate with `CONCOURSE_ENABLE_LETS_ENCRYPT`. This uses TLS-ALPN-01 validation to prove control of the domain.

Let's Encrypt recently revoked 2+ million certifications using this validation method due to a pair of bugs in their issuance system. [[announcement](https://community.letsencrypt.org/t/2022-01-25-issue-with-tls-alpn-01-validation-method/170450)]

While I was aware of this issue when it was originally announced, I did not realize it impacted Concourse until a pipeline operator brought it to my attention.

https://crt.sh is currently showing the certificate as revoked via OSCP.

## Steps to reproduce

Start a Concourse web node and configure it to retrieve a Let's Encrypt certificate. Make some requests to it until one is issued.

Revoke the certificate. Let's Encrypt has documentation on doing this [here](https://letsencrypt.org/docs/revoking/).

## Expected results

The web node should retrieve a new certificate.

## Actual results

The web node continues serving the old certificate, even after restarting the service.

## Additional context

This is a rare situation, but I think it is one that Concourse should handle better.

Some possible changes:

- Poll OCSP, or at least check OCSP on node startup, and retrieve a fresh certificate if the existing one is revoked
- Add a parameter to provide an email to the ACME client, so that the CA can contact the account owner if necessary
- Add a parameter to force the web node to retrieve a new certificate

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): I use Chrome 97 on Ubuntu 20.04, which does not seem to be checking OCSP. The operator that notified me encountered this issue on Firefox 91.5.1esr and Safari 14.0.2 on macOS 10.14.
* Did this used to work? Not sure

**Comment by kdihalas** [comment]
Same issue here, is there a way to force web to issue a new cert?

**Comment by kdihalas** [comment]
Replying to my question, certs are stored in the database, deleting the record and restarting web fixes it.

**Comment by xtremerui** [comment]
The table is `cert_cache`.

> Replying to my question, certs are stored in the database, deleting the record and restarting web fixes it.

**Comment by oozie** [comment]
```
psql -h my-postgresql.host.com -U dbmasteruser -d my_concourse_db
my_concourse_db=> DELETE FROM cert_cache WHERE domain = 'example.com';
```
and restart the `web` instance.
