### ISSUE TITLE
Bitbucket authentication broken with api deprecation

### ISSUE THREAD

**Issue by villecoder** [concourse/concourse#8025]
## Summary

Atlassian officially deprecated the API Concourse uses to get team membership.  As a result, users can no longer use bitbucket credentials to authenticate to Concourse.

## Steps to reproduce

1. Configure concourse for bitbucket authentication by specifying `CONCOURSE_BITBUCKET_CLOUD_CLIENT_ID` and `CONCOURSE_BITBUCKET_CLOUD_CLIENT_SECRET` in the environment.
2. `docker-compose up -d`
3. Click `Login`.
4. Click `Bitbucket Cloud`.

## Expected results

User is authenticated via bitbucket and authorized to use Concourse.

## Actual results

The following error message is displayed:
```
Internal Server Error
Failed to authenticate: bitbucket: get user teams: 404 Not Found: {"type": "error", "error": {"message": "This endpoint has been removed. See our documentation for more information. https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-user-permissions-teams-get"}}
```

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): n/a
* Did this used to work?: Yes

**Comment by villecoder** [comment]
Looks like the Dex project is aware of this in https://github.com/dexidp/dex/issues/2391

**Comment by taylorsilva** [comment]
We'll have to rebase our fork once they merge their PR in: https://github.com/concourse/dex

**Comment by tpoland** [comment]
Dex project has merged their change as part of https://github.com/dexidp/dex/pull/2397

**Comment by xtremerui** [comment]
Concourse will update its fork based on their release 2.30.3.
