### ISSUE TITLE
Scheduled tasks `check` and `get` are often scheduled to different workers than the `task` itself.

### ISSUE THREAD

**Issue by pms1969** [concourse/concourse#8030]
## Summary

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/2762128/152117373-5c85c190-9bf7-44cd-aa63-3f5f8ddc21fb.png">

Scheduled tasks `check` and `get` are often scheduled to different workers than the `task` itself.

As you can see in the screenshot, the check is scheduled to worker-10, the get to worker-3 and the task itself to worker-6.

## Steps to reproduce

* many workers
* run any job
* examine where the `task`, it's `get` and `check` are scheduled

## Expected results

The `check` and `get` run on the same node as the selected task.  In the example above, all should run on worker-6.

## Actual results

Often all 3 get scheduled to different workers.  In fact, it is very rare that all 3 get scheduled on the same worker.

## Additional context

We run in a k8s cluster, with the following container placement strategy.
```
    containerPlacementStrategies:
      [
        limit-active-containers,
        fewest-build-containers,
        volume-locality,
        limit-active-tasks,
      ]
```

Given that the worker where the task gets allocated doesn't barf if the image isn't present, I'm wondering why the ATC does any `check`s/`get`s on the tasks containers at all.

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): N/A
* Did this used to work? Uncertain.

**Comment by andy-paine** [comment]
This looks pretty similar to https://github.com/concourse/concourse/issues/6218. The reason the worker doesn't barf if the image isn't present is because the image is being streamed from the worker that _did_ do the `get` so it is present by the time the task container actually starts.

**Comment by pms1969** [comment]
Ah, Thank you.  I had anticipated that I wasn't the first, but couldn't find a ticket having already reported it. I'll go away now.  :)
