### ISSUE TITLE
Bug Report 

### ISSUE THREAD

**Issue by jovitha** [concourse/concourse#804]
Hi there!

**Delay in display of logs of a job in concourse v2.5.0**

Earlier was using concourse v1.2.0 , time taken to display the logs of a job was 4-5 seconds at the maximum 10-14 seconds,
now upgraded concourse to v2.5.0 , time taken to display the logs of a job is 29-35 seconds, even to load the main pipeline page it takes a lot of time and sometimes only a black screen is visible. So there is a delay in displaying the logs of the job.
Time before logs is displayed: 11:22:11 am IST
Time after logs is displayed: 11:22:40 am IST
Attached images for the same issue.
Can someone please look into this issue and try to fix it at the earliest?

![img_before_log](https://cloud.githubusercontent.com/assets/22680486/20866520/bae7606a-ba54-11e6-83a2-8baa1ddee8d8.PNG)
![image_after_log2](https://cloud.githubusercontent.com/assets/22680486/20866522/c164c5fe-ba54-11e6-9707-5649331fd57b.PNG)

**Comment by vito** [comment]
This is inactionable. There's all kinds of information missing that we'd need to be able to even know where to begin, or even to determine if it's some issue regarding your infrastructure or local networking, let alone whether it's a bug with Concourse itself.

I'd start with profiling and determine how much time is spent in the network vs. actual client-side work being done, both on the build page and on the pipeline view.
