### ISSUE TITLE
P2P volume streaming changes have changed worker API

### ISSUE THREAD

**Issue by andy-paine** [concourse/concourse#8040]
## Summary
The changes to P2P volume streaming in #7942 mean that the worker and ATC both require upgrading in order for containers with large streamed volumes to run.

## Steps to reproduce
* Deploy some workers running post-7942 (what will become 7.7.0)
* Deploy a web node running pre-7942 (7.6.0) with P2P streaming enabled
* Run a build that requires a volume to be streamed that takes >30s

## Expected results
* The build waits for the whole volume to stream

## Actual results
* The build attempts to start a container before the volume has finished streaming (after 30s) and `runc` complains that it cannot find the file or directory (this is a pretty opaque error that required a _lot_ of debugging to solve)

## Additional context
Using Jaeger we eventually noticed that all the volume streaming was taking exactly 30s which seemed wrong. This is the frequency at which the workers now send a "tick" back to the ATC when streaming large volumes and it appears the old ATC instances think this means streaming has completed successfully. Upgrading the ATC to run from `master` fixed this issue immediately.

The workers have a version which is supposed to track their compatibility for backwards-incompatible changes which I think should be bumped to 2.4. Whilst this isn't ideal for users who aren't using P2P streaming (as I assume this would have scheduling implications during deploys), the error is both consistent and highly confusing for those that are using P2P streaming.
https://github.com/concourse/concourse/blob/2fc810fcc27d6edcdeb5a651b3b657b45458e739/versions.go#L7-L14

## Triaging info

* Concourse version: `master`
* Browser (if applicable): N/A

**Comment by xtremerui** [comment]
The reason we didn't bump the worker version is P2P streaming suppose to be an opt-in experimental feature. It'd avoid forcing user to redeploy their workers if the feature is not used.

Would updating the release note of this feature to require worker bump good enough?

**Comment by andy-paine** [comment]
I think as long as it is clear that it is a breaking change for P2P users that should be okay but I think at some point the long-running experimental features that a bunch of users are probably utilizing may need to graduate to fully supported.

**Comment by sconrod-tester** [comment]
Hello, I upgraded concourse to the latest version and since the upgrade the volume streaming is exessively slow....is there a way to debug this and to improve the speed?
