### ISSUE TITLE
Chaining straties volume-locality and fewest-build-containers won't work as expected

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#8068]
## Summary

When I set container placement strategy to "volume-locality,fewest-build-containers", my expected result is that: find workers best meet volume-locality, and multiple workers fit volume-locality, then further choose the one that has the fewest containers.

But real result is that only "fewest-build-containers" is applied. Chained strategies was added by me, but after that, placement strategy was re-implemented with Order-Approve model, which lead to this bug.

To be honest, this is not a critical bug, but it may confuse users. My purpose of filing this bug is more to make users to be aware of this problem rather than making a fix in short term.

## Triaging info

* Concourse version: 7.6, master (maybe other 7.x versions)
* Browser (if applicable): NA
* Did this used to work? NA

**Comment by andy-paine** [comment]
Where did you see this issue come up? The following test passes for me were fewest-build-containers is used when there is a draw between volume-locality workers:
```
Describe("Chained", func() {
	strategy, err := worker.NewPlacementStrategy(worker.PlacementOptions{
		Strategies: []string{"volume-locality", "fewest-build-containers"},
	})
	Expect(err).ToNot(HaveOccurred())

	Test("sorts the workers", func() {
		scenario := Setup(
			workertest.WithBasicJob(),
			workertest.WithWorkers(
				grt.NewWorker("worker1").
					WithVolumesCreatedInDBAndBaggageclaim(grt.NewVolume("input1")).
					WithJobBuildContainerCreatedInDBAndGarden().
					WithJobBuildContainerCreatedInDBAndGarden().
					WithJobBuildContainerCreatedInDBAndGarden(),
				grt.NewWorker("worker2").
					WithVolumesCreatedInDBAndBaggageclaim(grt.NewVolume("input2")).
					WithJobBuildContainerCreatedInDBAndGarden().
					WithJobBuildContainerCreatedInDBAndGarden(),
				grt.NewWorker("worker3").
					WithJobBuildContainerCreatedInDBAndGarden(),
				grt.NewWorker("worker4").
					WithJobBuildContainerCreatedInDBAndGarden().
					WithJobBuildContainerCreatedInDBAndGarden().
					WithJobBuildContainerCreatedInDBAndGarden().
					WithJobBuildContainerCreatedInDBAndGarden(),
			),
		)

		workers, err := strategy.Order(logger, scenario.Pool, scenario.DB.Workers, runtime.ContainerSpec{
			TeamID:   scenario.TeamID,
			JobID:    scenario.JobID,
			StepName: scenario.StepName,

			Inputs: []runtime.Input{
				{
					Artifact:        scenario.WorkerVolume("worker1", "input1"),
					DestinationPath: "/input1",
				},
				{
					Artifact:        scenario.WorkerVolume("worker2", "input2"),
					DestinationPath: "/input2",
				},
			},
		})
		Expect(err).ToNot(HaveOccurred())
		Expect(workerNames(workers)).To(Equal([]string{"worker2", "worker1", "worker3", "worker4"}))
	})
})
```

**Comment by evanchaoli** [comment]
Oops!!! Looks like the tricky is at `sort.SliceStable()` that will keep equal items in original order.
