### ISSUE TITLE
Login fails if invalid ATC-Authorization cookie is set

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#808]
# Bug Report

When I have an invalid/expired ATC-Authorization cookie set I cannot login using the browser. It returns a 401. If I delete the cookie I'm able to login again. 

Maybe if we visit the 'login' page clear the cookie?

Repro steps (these might work):
1. Visit a concourse pipeline, login and close the browser before the token expires.
1. Wait for the token to expire.
1. Visit the concourse pipeline again - you will be logged out
1. Attempt to login - it will fail
1. View cookies and you will see the ATC-Authorization cookie

Auxiliary Information
* Concourse version: 2.5.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? Not sure (probably not)

**Comment by vito** [comment]
Thanks, confirmed this myself.

I think this only occurs in the basic auth flow, which may explain why we haven't run into it.

**Comment by joshzarrabi** [comment]
@chendrix and I are having trouble reproducing this on develop. @vito what exactly were your repro steps?

**Comment by dprotaso** [comment]
@joshzarrabi @chendrix I was able to do this with 2.6.0 by bumping the bosh stemcell and deploying
