### ISSUE TITLE
Build Page Stops Tailing Logs Sometimes

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#811]
# Bug Report

It seems to happen when the task script outputs a large blob of text. I can get it to tail again by scrolling to the bottom but it stops again fairly quickly.

* Concourse version: 2.5.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? Unsure

**Comment by jama-pivotal** [comment]
Closing due to staleness
