### ISSUE TITLE
Left align pipeline names in the list

### ISSUE THREAD

**Issue by stickfigure** [concourse/concourse#816]
Here on services we have a lot of pipelines. Concourse's pipeline list currently right-aligns them, which is pretty but makes it hard to see groupings (common prefixes). 

We humbly request left-alignment. The alternative is changing our pipeline names so that they read right-to-left (ie most specific on left), which is highly nonintuitive :-(

**Comment by vito** [comment]
this has come up before and honestly there's about an even mix of those who
have generic suffixes and prefixes. e.g. ruby-buildpack, python-buildpack,
foo-service-broker, bar-service-broker, etc.

I'm not sure we should change this at the moment.

**Comment by vito** [comment]
that being said you may want to check out the issue for pipeline
hierarchies. I think I made one. on a phone so hard to link. sorry.

**Comment by vito** [comment]
I'll close this to direct more discussion towards https://github.com/concourse/concourse/issues/532
