### ISSUE TITLE
feature request: descriptions on jobs

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#822]
# Feature Request

## What challenge are you facing?

In a team with a huge amount of pipelines doing things like deployment, it can be hard to understand exactly what a job is doing and what its limitations / context / pitfalls / etc are just from the name. For instance, the 'bump-release' job might only work the first time, but might fail on subsequent runs. It's hard to keep all this information in your head (esp when EVERY job has some kind of context).

## A Modest Proposal

Allow me to provide a description in my job config that is visible somewhere in the UI; perhaps when I click on a job, or hover over a job, or as an icon on the job I can click to bring up a modal. Whatever!

**Comment by jama-pivotal** [comment]
Closing in favour of #569
