### ISSUE TITLE
Vagrant box 'concourse/lite' starts without cable connected on vb network interface

### ISSUE THREAD

**Issue by biels** [concourse/concourse#823]
To reproduce the issue:
`vagrant init concourse/lite`
`vagrant up`
It will take a long time and finally timeout while trying to ssh the vm. The virtual network cable happens to be disconnected by default.
As a solution that worked for me, I propose adding the following configuration inside Vagrantfile:
```
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
      vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
   end
```
Note that the added line is only `vb.customize ['modifyvm', :id, '--cableconnected1', 'on']`

I'm new to concourse and I'm still not familiar with the repository structure, so please move the issue or point me in the right direction if this is not the right place to discuss this issue.

**Comment by vito** [comment]
Same as https://github.com/concourse/concourse-lite/issues/9 - the fix is to upgrade VirtualBox. We suspect they made some backwards-incompatible change with box building, so this happened when we bumped the VirtualBox version on our builder.

**Comment by gsf** [comment]
Thanks for the configuration fix -- this issue can be seen with the version of VirtualBox still present on Ubuntu 14.04.
