### ISSUE TITLE
contribution documentation issue - phantomjs is needed

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#824]
# Bug Report

I was getting some test errors, because I needed to install phantomjs. Please add this to the readme file.

Also, it will be nice if a few hints about obtaining the project correctly (git submodules) are added for faster bootstrapping - it should not be assumed that every developer is familiar with such model.

**Comment by jama-pivotal** [comment]
We recently moved away from phantomjs so I guess this issue is technically not valid anymore. In the future I think the best way to get these changes in quickly is to issue a PR to the README itself!
