### ISSUE TITLE
timeouts in the tests

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#825]
# Bug Report

I am running the concourse tests on a pretty decent machine and I am getting (from time to time) timeouts:

• Failure [20.829 seconds]
Resource Pausing pausing a resource [It] can view the resource
/Users/george/github/concourse/src/github.com/concourse/atc/acceptance/resource_pausing_test.go:134

  Timed out after 10.210s.
  Expected selection 'Link: "resource-name" [single]' to be found

  /Users/george/github/concourse/src/github.com/concourse/atc/acceptance/resource_pausing_test.go:103
------------------------------
••••

Summarizing 1 Failure:

[Fail] Resource Pausing pausing a resource [It] can view the resource
/Users/george/github/concourse/src/github.com/concourse/atc/acceptance/resource_pausing_test.go:103

Ran 33 of 33 Specs in 38.597 seconds
FAIL! -- 32 Passed | 1 Failed | 0 Pending | 0 Skipped

**Comment by ClaraFuPivotal** [comment]
I wouldn't say this is a bug within concourse itself since this is just a flake within our acceptance tests which we have been meaning to fix for a while. This story (https://www.pivotaltracker.com/story/show/144212721) outlines fixing these tests.
