### ISSUE TITLE
Display name in UI displaying Microsoft User ID not Username with Concourse 7.7.1

### ISSUE THREAD

**Issue by kmoorfield** [concourse/concourse#8262]
## Summary

Hey Concourse Team,

We recently upgraded from v7.2.0 to v7.7.1 to make use of the new features / performance upgrades. After the upgrade everything worked fine except that the username display on the UI, displays an unique user ID instead of an user name like in v6.2.0 for the Microsoft Auth option.

## Steps to reproduce

Use Microsoft Auth option / add an Azure group to the "main" team
Upgrade from v7.2.0 to v7.7.1
Able to log in, but the display name in the top right is now displaying an ID / Build logs have ID, not username

## Expected results
Username is displayed in the UI / Build logs

## Actual results
User ID is displayed in the UI / Build logs

## Additional context
This is not a blocker, but would be great to be able to track users based on username when triggering builds as opposed to user ids which are hard to audit.

## Triaging info

* Concourse version: 7.7.1
* Browser (if applicable): Latest Chrome
* Did this used to work? Yes, it works with v7.2.0

**Comment by xtremerui** [comment]
Could you give examples of user ID and username?

**Comment by xtremerui** [comment]
The current behaviour is expected as shown in the code here
https://github.com/concourse/concourse/blob/master/skymarshal/skycmd/flags.go#L283-L305

If [display user ID flag](https://github.com/concourse/concourse/blob/master/atc/atccmd/command.go#L262) is not configured, it will fall back to the default rule where preferred username > user ID > username. Since microsoft auth connector doesn't return preferred username in user identity, you then see user ID being used. 

I believe it will work once you configure the command flag with `microsoft:name`.

**Comment by kmoorfield** [comment]
Thank you @xtremerui ,
I added the below to my web_environment config file and restarted the web server and it works!

CONCOURSE_DISPLAY_USER_ID_PER_CONNECTOR=microsoft:name

Just a note that the existing jobs weren't changed, i.e. build test 40 uses my user id in the logs, build test 41 uses my username after the config change.

**Comment by xtremerui** [comment]
yes those were the user identifiers got saved with build event that are unchangeable.

**Comment by kmoorfield** [comment]
@xtremerui  - Feel free to close this bug now that it's working. 
Still unsure as to why this configuration option was required when in v7.2.0 the default used the username? 
Regardless this helps unblock our upgrade path for our other instances going forward.
Thanks for your help :)

**Comment by xtremerui** [comment]
Glad it works for you. The full context can be found in this https://github.com/concourse/concourse/pull/6369
