### ISSUE TITLE
Add SHA256 sums

### ISSUE THREAD

**Issue by kostyrevaa** [concourse/concourse#827]
# Feature Request
## A Modest Proposal

As a user
I want to be sure that I've downloaded untampered binary.

Example: See the consul_0.6.4_SHA256SUMS file at https://releases.hashicorp.com/consul/0.6.4/
Would be great if you sign the file with a GPG key -- e.g.: consul_0.6.4_SHA256SUMS.sig

**Comment by vito** [comment]
consolidating this with https://github.com/concourse/concourse/issues/674
