### ISSUE TITLE
Resource governor

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#828]
# Feature Request

## What challenge are you facing?

The resource concept and the versioning are extremely powerful and obviously can take you really far. It is unbelievable how many real live concepts could be fit in this abstraction.

There are cases though where it failing. Mostly in real live scenarios where the resources having a life cycle - or they can appear and disappear.

Example for this is a feature/task/dev branch in a git repo. The existence of project like this: https://github.com/pivotaltracker/concourse-branch-manager proves that.

## A Modest Proposal

New abstraction `Resource governor`. Using the resource abstraction as example: it can have check, get, put assets, but unlike resource where this operates over versions for the governor this will manage resources.

For example git-resource-governor could list git-resources - one per branch.

I realize that this is very serious thing, but I really would love to see something like this in concourse 3.0

**Comment by vito** [comment]
Could you expand a bit more on a more precise scenario you're trying to accomplish? Ya kinda breezed by a few things there. 😛 

If it's feature branches, there are a few proposals made in https://github.com/concourse/concourse/issues/239 which just use resources, either by having a resource for monitoring all the branches (Travis-style), or having a resource monitoring the state of the branches themselves and dynamically creating a pipeline for each.

**Comment by ggeorgiev** [comment]
Keeping thing simple as possible is very important. Sometimes though this gets on our way and we start hacking in semantic things that do not belong to it.

Resource and versioning obviously can take you very far, but almost every scenario where the lifecycle of the resource is not the same as the live cycle of the pipeline the need of a workaround emerges.

 #239 is a good example of problems a governor can solve. But the very first use case where I notice this is - the pull-request - resource. The way it "combines" all different prs together in a single versioning line is very off. The (+) button means nothing - because it restarts the last revision, that could be a random other pr. The history is polluted with prs from other prs etc. It seems to fit way more cleanly if every pr is a new resource for the concourse and every change in a pr branch is versioned independently. Obviously, new pr need to be added, merged/closed removed.

How this could work: As part of the pipeline one or more governors are defined - same as now we do for jobs, resources. When we have a governor additionally to every other resource we declare we can also use a governor-resource ... or resource that is created by the governor. When governor do check it returns a list of resources (instead of list of versions) - that's it on config side. On execution side concourse will seamlessly make "internal copy" of every job that operates over governor-resource for every resource returned from the governor and removes all the jobs that are against resources that are no longer in the governor list of resources.

Now you could picture how this could easy apply not only for pull-requests but for feature/release branches as well ... or any other dynamic list of inputs that right now you will need to create a separate pipeline or loop over the list in a single job. 

This concept will work not only for inputs, though, but for targets too. Let say you have a list of clusters you would like to deploy to - adding new cluster will be noticed from the cluster-governor instead of the need to change the pipeline(s).


 With all this said, I am perfectly clear that all this could be achieved outside of concourse, but it seems to me that it belongs to the ci system.

**Comment by ggeorgiev** [comment]
Forget to mention. Probably the most work for this will be in the UI - which by the way is something that none of the current approaches can solve. I really would like to be able to see in the UI how all these different resources are in fact related, jobs running on them are similar - aggregation, collapsing/expanding filtering grouping features might emerge to make the experience better.

**Comment by ggeorgiev** [comment]
Note that not always the splits on a resource list will be e2e for the pipeline. In same cases you might have split in the middle where you prepared the artifacts and then split to deploy ... or you could collapse back to send an email with a report of the deployment.

More I think about it more and more applications of such abstraction I see.

**Comment by clarafu** [comment]
@ggeorgiev I'm actually not sure if I completely understand your proposed approach but what I got was that you wanted to solve the problem of the lifecycle of the versioned resources is not the same as the lifecycle of the pipeline (for some cases like a PR pipeline). We actually have a few approaches ourselves that I would like for you to look at, https://github.com/concourse/concourse/issues/1172 and a proposed solution to a similar problem you are facing: https://github.com/concourse/concourse/issues/413#issuecomment-311399474.

**Comment by ggeorgiev** [comment]
@clarafu #413 does not solve the problem - this is just one of the things that I am facing without governor type abstraction.

A pipeline that creates and removes other pipelines is the closest thing to a resource governor. The issues with multiple pipelines that I was facing with 2.x.x was resource overuse when many similar pipelines are there. Unfortunately, with 3.x.x not all of these issues are resolved - for example, the disk usage increases with growing number of pipelines, even most of the resources suppose to be shared.

**Comment by vito** [comment]
I *think* this is captured by #1707.
