### ISSUE TITLE
Using long filepaths in the image causes test fails

### ISSUE THREAD

**Issue by wieslaw-gat** [concourse/concourse#829]
# Bug Report

The `docker export` command has issues with long filenames (as reported in https://github.com/docker/docker/issues/29360). Since `docker-image-resource` uses it for extracting image contents (https://github.com/concourse/docker-image-resource/blob/6a9153480c64f776a5305b3553d9c301ccc8e4e9/assets/in#L78) this makes using some images impossible.

For example:
I have an image that has long paths in it because it contains a lot of npm modules installed - it's currently impossible to use it to build an application.

Do you have any suggestions on how to work around the problem?

**Comment by vito** [comment]
Looks like a potential fix made it into Go 1.8?: https://github.com/golang/go/issues/17630

We'd need to wait for Docker to have a new version out built with Go 1.8, I suppose.

I can't think of a *clean* workaround, but I guess you could just tar up the `node_modules` and manually extract them in your task.

**Comment by vito** [comment]
As the fix is upstream I'm not sure there's anything for us to do here beyond making it so we pick up the new Docker version. I just noticed we hardcode it to 1.12.1 in the Dockerfile, so I'll turn this into a feature for us to make it continuously pull down versions as they ship.
