### ISSUE TITLE
Going to url for a non-existent job for a pipeline results in confusing behavior

### ISSUE THREAD

**Issue by RochesterinNYC** [concourse/concourse#832]
# Bug Report

If you go to any url for a Concourse deployment that is associated with a legitimate pipeline but a non-existent job, the page will often show unhelpful "Loading" messages that never resolve.

Behavior observed:

- The job page for a job that did exist at one point but does not currently exist in the pipeline will show one permanently "Loading" message and the previous builds.
- The job page for a job that does not exist and has never existed will show dual "Loading" messages on the page. 
- The individual build page for a job that does not currently exist in the pipeline will only show a permanently "Loading" message (this includes builds that previously executed and had logs when the job did exist in the pipeline).

For example, on the Buildpacks Team/CI, we have a pipeline called `stacks`. We had a job called `deploy-rootfs-and-cf-and-diego-to-cf-release`.

We performed 2 builds of this job and then removed the job from the pipeline.

Results:

Job page for the job that does not exist in the `stacks` pipeline anymore: https://buildpacks.ci.cf-app.com/teams/main/pipelines/stacks/jobs/deploy-rootfs-and-cf-and-diego-to-cf-release:

![screen shot 2016-12-22 at 11 29 50 am](https://cloud.githubusercontent.com/assets/1504464/21432521/f8473550-c839-11e6-99f3-de489b0e4b8c.png)

A build page of the job that does not exist in the `stacks` pipeline anymore: https://buildpacks.ci.cf-app.com/teams/main/pipelines/stacks/jobs/deploy-rootfs-and-cf-and-diego-to-cf-release/builds/2:

![screen shot 2016-12-22 at 11 26 44 am](https://cloud.githubusercontent.com/assets/1504464/21432432/87460a52-c839-11e6-8a6c-b6c1108f21f7.png)

A job that has never existed in the pipeline showing the dual "Loading" messages (ex. https://buildpacks.ci.cf-app.com/teams/main/pipelines/stacks/jobs/non-existent):

![screen shot 2016-12-22 at 11 25 59 am](https://cloud.githubusercontent.com/assets/1504464/21432406/6bf7150c-c839-11e6-8f62-6cf9aa95e274.png)

I would expect some kind of output that makes it clear that nothing is actually loading and that I'm viewing a job that is invalid or that never existed for the case where the job never existed.

For the job that once existed, I might expect to be able to see the previous build logs (instead of just the "Loading" message) and no stuck "Loading" messages anywhere.

* Concourse version: `2.5.1`
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome

**Comment by cjcjameson** [comment]
Going to the `builds/<number>` endpoint also exhibits some of this bad behavior: 403 (often because you're logged in to the wrong team) and 404 both hang "Loading..." . But the `builds/` endpoint is deprecated, so I wouldn't belabor that particular issue. I'm guessing there's an underlying general thing.

**Comment by pivotal-topher-bullock** [comment]
Workin' on better 404 pages; #1131
