### ISSUE TITLE
`fly hijack` should provide details regarding missing executable

### ISSUE THREAD

**Issue by coreyti** [concourse/concourse#833]
# Feature Request

## What challenge are you facing?

When `fly hijack`ing, my task picked up the wrong/default Docker image (due to a mistake on my end). That image does not contain `bash`. This fact lead to the `fly hijack`  attempt bailing out, with no output.

Examining the ATC logs, I was able to determine that the issue was indeed that `bash` was missing. Simplified log output:

```json
{
  "source": "atc",
  "message": "atc.hijack.hijack.failed-to-hijack",
  "log_level": 2,
  "data": {
    "error": "hijack: Backend error: Exit status: 500, message: {\"Type\":\"\",\"Message\":\"runc exec: exit status 1: exec failed: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"bash\\\\\\\": executable file not found in $PATH\\\"\\n\",\"Handle\":\"\"}\n",
    "process": {
      "path": "bash",
      "args": null,
      "env": [
        "<redacted>"
      ],
    }
  }
}
```

## A Modest Proposal

```
$ fly -t target hijack -b 123
Sorry, you can't do that. `bash` executable file not found in $PATH on the container
```

**Comment by jagregory** [comment]
Confirming same behaviour here. Silent fail from fly, ATC logging:

```
{
  "error":"hijack: Backend error: Exit status: 500, message: {\"Type\":\"\",\"Message\":\"runc exec: exit status 1: exec failed: container_linux.go:259: starting container process caused \\\"exec: \\\\\\\"bash\\\\\\\": executable file not found in $PATH\\\"\\n\",\"Handle\":\"\"}\n"
  ...
}
```

**Comment by eruvanos** [comment]
Any update on this issue?

**Comment by marco-m** [comment]
The real problem is that `fly` returns an exit status of zero (all OK) so this makes it error-prone or impossible to use in scripts

**Comment by marco-m** [comment]
@jama-pivotal just to be sure you are aware: this is actually a bug, not a feature request:

fly intercept /non/existing/command

will silently fail and report 0 as exit status.

Ticket #758, which more explicitly talks about bug, has been closed as duplicated of this one.

**Comment by srkiNZ84** [comment]
This is also affecting us and is a difficult issue to investigate as we don't immediately think to search the ATC logs.

**Comment by cirocosta** [comment]
Hey,

after https://github.com/concourse/concourse/commit/bab9bc2fa8a14de15cbb682c84fd07388d3c8307 you should be able to see any errors related to the underlying container backend.

E.g, trying to run `bash` on a container w/out `bash` in it's `$PATH`:

```
# try to hijack execution `bash`
fly -t dev hijack -j mypipeline-2/running 'bash'
Backend error: Exit status: 500, message: {"Type":"ExecutableNotFoundError","Message":"exec failed: container_linux.go:336: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n","Handle":"","ProcessID":"","Binary":""}

# check the exit code as captured by fish
echo $status
255
```

I hope it helps!

thx!

**Comment by marco-m** [comment]
Thanks @cirocosta !
