### ISSUE TITLE
Cannot change port number of HTTP API in quickstart docker container

### ISSUE THREAD

**Issue by readmodifywrite** [concourse/concourse#8335]
## Summary

Changing the default port number from 8080 in the quickstart docker compose to anything else will break the web interface.

## Steps to reproduce

Use the docker-compose from the quickstart: https://concourse-ci.org/quick-start.html

There are two different failure mechanisms:

1. Change the host bind port to something other than 8080, but leave the Concourse container's internal port as 8080:

ports: ["8888:8080"]

In this case, you'll be able to open the front page at port 8888.
If you click "login", you will get a 404 not found, and notice the URL is redirecting to port *8080* instead of 8888.

So then you might be tempted to try the next obvious thing:

2. Change the internal and external ports to 8888, so the HTTP links work.

ports: ["8888:8888"]
and:
CONCOURSE_EXTERNAL_URL: http://localhost:8888

You will get a blank page.  No 404 or connection refused - it looks like the TCP connection works and you get an empty HTML page.

I have also tried setting CONCOURSE_PEER_URL and CONCOURSE_BIND_PORT, to no avail.

Might be related to #2514? 
It looks like the "ATC" is still listening on the default port 8080.  I cannot find any documentation on how to change or configure that.  Here is the log message from docker:

> concourse_1     | {"timestamp":"2022-05-10T18:23:55.855346778Z","level":"info","source":"atc","message":"atc.listening","data":{"debug":"127.0.0.1:8079","http":"0.0.0.0:8080"}}

## Expected results

Web interface works.

## Actual results

Web interface is broken/unavailable.

## Additional context

Linux Mint 20

## Triaging info

* Concourse version: 7.7.1

* Browser (if applicable): Firefox

* Did this used to work?
New user, so I have no idea.  So, technically, no, from my perspective.

**Comment by ibokuri** [comment]
The `CONCOURSE_EXTERNAL_URL` flag is what you're looking for. It specifies the URL your Concourse `web` node(s) can be accessed from.

By default, it's set to `http://localhost:8080` in the `docker-compose.yml` file used in the Quick Start, which is why you got those redirects after logging in. Update it to match your host port and you should be good to go!
