### ISSUE TITLE
`fly execute` should support providing a custom build image

### ISSUE THREAD

**Issue by coreyti** [concourse/concourse#834]
# Feature Request

## What challenge are you facing?

I would like to be able to `fly execute` a task, given a `task.yml` that does not specify `image`. Our pipelines use private Docker images and we don't want to have the credentials in the task files. Currently there does not appear to be a way to have the execution pick up the custom image, and it pulls in the default barebones image instead.

## A Modest Proposal

When `fly execute`-ing, a task that does not specify a Docker image I would like to be able to provide an image via any/all of:

- A path on local disk
- A URI, with basic auth credentials
- A Docker Hub config, via JSON

Something like:

```
# from local disk
$ fly -t target execute -c path/to/task.yml -i input=. \
  --task-image=path/to/image

# from HTTP URI
$ fly -t target execute -c path/to/task.yml -i input=. \
  --task-image=https://user:pass@www.example.com/image

# from JSON config
$ fly -t target execute -c path/to/task.yml -i input=. \
  --task-image='{ "repository": "org/image", "tag": "lala", "username": "user", "password": "pass" }'
```

**Comment by matt-royal** [comment]
+1

**Comment by vito** [comment]
`image_resource` supports params now, via the credential manager support introduced in [v3.3.0](http://concourse.ci/downloads.html#v330). Does that help?

**Comment by BenElgar** [comment]
Is there any movement on this? What's the best way to input an image into the `fly execute` command that is usually specified in the pipeline?

**Comment by vito** [comment]
There's now an `--image` flag which can be used in combination with `-j` to use one of the job's inputs as the image:

```
~/w/concourse (master) $ fly -t ci e -c ci/tasks/prep-release-assets.yml -j concourse/publish-binaries --image unit-image
executing build 4974344 at https://ci.concourse-ci.org/teams/main/pipelines/concourse/builds/1563 
initializing
running concourse/ci/tasks/scripts/prep-release-assets
# ...
succeeded
```

That *seems* like it should be sufficient for this. If you're using a task without an image that means the task's image is normally provided by the pipeline, so you should just refer to a job that uses the task so you can use the exact same image.

I'm going to close this assuming that makes y'all happy, but let me know if you need something else and I'm happy to reopen!

**Comment by DanielJonesEB** [comment]
I don't _think_ this is documented, either in the `fly` help or in the docs website. Adding this comment in case I forget before I have time to raise a PR.

**Comment by vito** [comment]
@DanielJonesEB Good catch - I've just added docs for it in https://github.com/concourse/docs/commit/7f3639ebe699b46d78b6aa24bdd0d3d24f39844e

**Comment by DanielJonesEB** [comment]
Nice one @vito!

**Comment by dannystaple** [comment]
Hello, I have been searching and not found out how, but how can you use an image from a previous buildstep in task this way? IE if I've managed to get the output of that build locally as an output?
