### ISSUE TITLE
Concourse cannot handle more than 2147483647 checks/builds

### ISSUE THREAD

**Issue by cbowman0** [concourse/concourse#8364]
## Summary

When build_id id in the builds table exceeds 2147483647, all future builds fail to create.

Errors in the logs like:
```
concourse-web-1     | {"timestamp":"2022-05-19T20:54:03.056255000Z","level":"error","source":"atc","message":"atc.tracker.tick.run.lock.acquire.failed-to-register-in-db","data":{"build":"26","build_id":2147483660,"error":"pq: value \"2147483660\" is out of range for type integer","id":[1,2147483660],"job":"job","pipeline":"example","session":"26.486.4.1.1","team":"main"}}
concourse-web-1     | {"timestamp":"2022-05-19T20:54:03.056311307Z","level":"error","source":"atc","message":"atc.tracker.tick.run.failed-to-get-lock","data":{"build":"26","build_id":2147483660,"error":"pq: value \"2147483660\" is out of range for type integer","job":"job","pipeline":"example","session":"26.486.4","team":"main"}}
concourse-db-1      | 2022-05-19 20:54:03.056 UTC [70] ERROR:  value "2147483660" is out of range for type integer
concourse-db-1      | 2022-05-19 20:54:03.056 UTC [70] CONTEXT:  unnamed portal parameter $2 = '...'
concourse-db-1      | 2022-05-19 20:54:03.056 UTC [70] STATEMENT:  SELECT pg_try_advisory_lock($1,$2)
concourse-db-1      | 2022-05-19 20:54:03.056 UTC [70] ERROR:  value "2147483656" is out of range for type integer
concourse-db-1      | 2022-05-19 20:54:03.056 UTC [70] CONTEXT:  unnamed portal parameter $2 = '...'
```

## Steps to reproduce

1. Start up the dev env: `docker-compose up`
2. Start the every 30s pipeline: `fly -t dev set-pipeline -p example -c examples/pipelines/time-triggered.yml`
3. Unpause the pipeline
4. Let it run for a few minutes, but may not be strictly necessary
5. Log into the DB: ./hack/db
6. Restart the builds_id_seq sequence to start at 2147483647.
> ```
> concourse=# alter sequence builds_id_seq restart with 2147483647;
> ALTER SEQUENCE
> ```
> 

## Expected results

Builds continue to work

## Actual results

Concourse system stops executing new builds

## Additional context

1. Unupdated schema columns
We noticed there were a few build_id and related fields that were not updated in the transition to bigint:

https://github.com/concourse/concourse/blob/8c8eb0565101b287107fe9d36ef970505ad166b7/atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql

```
table: build_comments
column: build_id

table: builds
column: rerun_of

table: successful_build_outputs
column: rerun_of

table: jobs
column: first_logged_build_id
```
There may be more.

2. In our production Concourse cluster on which this originally happened,
one of the errors we saw was:
```
LOG: execute <unnamed>: SELECT completed FROM builds WHERE id = $1
DETAIL: parameters: $1 = '2147493588'
ERROR: value "2147493588" is out of range for type integer
```
What’s weird is that builds and id are already bigint, including the sequence.

That error message, happens if Postgres is told to typecast from a string to an integer, as can be seen reproduced below:
```
testdb=# CREATE TABLE foobar (test_id bigint);
CREATE TABLE
 
testdb=# SELECT * FROM foobar WHERE test_id = 2147483648;
test_id
---------
(0 rows)
 
testdb=# SELECT * FROM foobar WHERE test_id = '2147483648'::integer;
ERROR: value "2147483648" is out of range for type integer
```

So likely the case, that this is somewhere in code a string is being passed to Postgres and told to typecast to an integer,
before storing to a bigint field.

## Triaging info
Concourse version: 7.4.4.  Test was against master Concourse branch.
Browser (if applicable):
Did this used to work? Not likely

**Comment by cbowman0** [comment]
Upon further diagnosis, the locking via pg_try_advisory_lock(key, key) only supports integer arguments.  There is no way this design, as implemented will support bigint values.

**Comment by evanchaoli** [comment]
Concourse has increased build id from 32bit to 64bit. 2147483647 is max signed int. `pg_try_advisory_lock(int, int)` takes two int as parameters that cannot utilize Concourse 64bit ids. 

But given it would take time for build ids to reach to 2147483647, meaning that, when build id reach to 2147483647, 1 should have been a history value. Based on that, a simple solution is like `pg_try_advisory_lock(lockType, id % max-int)`.

**Comment by xtremerui** [comment]
> pg_try_advisory_lock(lockType, id % max-int)

@evanchaoli what is `int` here?

**Comment by cbowman0** [comment]
I read it like `pg_try_advisory_lock(lockType, id % 2147483647)`.

**Comment by xtremerui** [comment]
> I read it like `pg_try_advisory_lock(lockType, id % 2147483647)`.

right i was scrathing my head to understand why he wants the residue of id%max to minus an int ....

**Comment by cbowman0** [comment]
Yeah, max-int (aka 2147483647) not max something minus a random int.

I think it should work out for the reasons presented, but I haven’t had a chance to test it.

**Comment by evanchaoli** [comment]
@xtremerui Sorry for the confusion. I think Concourse uses 64bit Golang, where `int` is actually `int64`, while based on [PG doc ](https://www.postgresql.org/docs/9.6/functions-admin.html):

```
pg_try_advisory_lock(key bigint)
pg_try_advisory_lock(key1 int, key2 int)
```

The lock function takes 1 `bigint` or 2 `int`, where `bigint` should be `int64` and `int` should be `int32`.

I think a fix can be here:

https://github.com/concourse/concourse/blob/f465f1eee6aa0411b6805e5258475c5a7fd5dd6f/atc/db/lock/lock.go#L296-L303

Something like:

```golang
func (l LockID) toDBArgs() []interface{} {
	result := []interface{}
	for i := range l {
		result = append(result, l[i] % math.MaxInt32)
	}

	return result
}
```

**Comment by evanchaoli** [comment]
@xtremerui To provide more info, I tried directly acquire a lock using SQL statements:

```sql
select pg_try_advisory_lock(1000, 2147483647)
```
returned successfully.

```sql
select pg_try_advisory_lock(1000, 2147483648)

SQL Error [42883]: ERROR: function pg_try_advisory_lock(integer, bigint) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
```

```sql
select pg_try_advisory_lock(1000, 2147483648::int)

SQL Error [22003]: ERROR: integer out of range
```

**Comment by cbowman0** [comment]
Additionally, to match the error string in the Concourse logs, pass the args as strings, since that seems to be how squirrel or the pg driver is handling it:

```
=> select pg_try_advisory_lock('1000', '2147483648');
ERROR:  value "2147483648" is out of range for type integer
LINE 1: select pg_try_advisory_lock('1000', '2147483648');
```

**Comment by aglees** [comment]
It looks like we've hit the limit of `2147483647` as also mentioned in #6354 today, and are therefore pretty broken. Is a new public release imminent that will address this, or are there other mitigations that we can put in place now?

**Comment by vijaymck** [comment]
We hit the same issue. Is there any quick fix or upgrading to 7.9.0 or 7.9.1 is the only way to fix this?

**Comment by vijaymck** [comment]
We did upgrade to 7.9.1 but still seeing the error in web logs:

{"timestamp":"2023-07-12T19:18:31.371643437Z","level":"error","source":"atc","message":"atc.tracker.tick.run.finish.failed-to-finish-build","data":{"build":"269","build_id":2147496908,"error":"**pq: value \"2147496908\" is out of range for type integer**","job":"Build Java Artifacts","pipeline":"va-ecb2bva","session":"28.521.107.56","team":"xyz"}}

**Comment by vijaymck** [comment]
For us, it seems to `builds` table's **index** that seems to be in integer mode. We rebuilt the index and builds records can be saved and able to run the builds.

atc=> \d builds_pkey;
     Index "public.builds_pkey"
 Column |  Type  | Key? | Definition
--------+--------+------+------------
 id     | bigint | yes  | id
primary key, btree, for table "public.builds"

<<< this fixed the mismatch b/n table col & sequence type:
REINDEX INDEX builds_pkey;

**Comment by databus23** [comment]
We ran into this problem with concourse 7.10.0 grinding our instance to complete halt.
The postgres container logs were spewing out errors like the following as fast as possible:

```
2023-09-04 08:55:48.813 GMT [3397819] ERROR:  value "2147730068" is out of range for type integer
2023-09-04 08:55:48.813 GMT [3397819] STATEMENT:  SELECT max(id) FROM builds WHERE status NOT IN ('pending', 'started') AND job_id = $1 AND rerun_of = $2
```

In our case for unknown reasons the migration that is supposed to have updated a couple of fields to `bigint` in https://github.com/concourse/concourse/pull/8390 somehow skipped the `rerun_of` field from the `builds` table which was still sitting at `integer`.

https://github.com/concourse/concourse/pull/8390/files#diff-580a127d23298e2cd2403b907ca448153f7a11d76324faa8d67b3adcfcafcb40R6-R7

The other 4 fields in the same migration file were converted to `bigint` properly.

After running `ALTER TABLE builds ALTER COLUMN rerun_of TYPE bigint;` the system recovered eventually.

No idea how it happened that a migration was not applied completely. 🤷

**Comment by xtremerui** [comment]
@lrstanley @databus23 the `rerun_of` is not updated to bigint because of this https://github.com/concourse/concourse/issues/8499

**Comment by lrstanley** [comment]
That issue seems counter-intuitive to me -- if large deployments have very long migration times due to this issue, that also means they are much more likely to run into this exact issue where they would need the migration in question. (larger/more heavilyh used deployments == more build logs, which would push someone over the limit). No?

Guess I'm not sure I follow -- it's not like there is an alternative to the migration, it has to be done otherwise the entire platform breaks, like in our case. 0 out of the 7000 pipelines we had for the environment could do anything. Didn't see anything mentioned in the release notes asking folks to manually apply that migration either.
