### ISSUE TITLE
Generic skip `get` for the `put` step

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#837]
# Feature Request

## What challenge are you facing?

There are a lot of scenarios where the `put` the goal of the job and there are no following steps that can benefit from the get. It seems this was recognized for docker image resource and this is how get_params: skip_download: true emerged.

 It seems to me this should be solved in a generic way.

## A Modest Proposal

Add an option to the `put` task that allows for removing the `get` substep. This will allow to be applied to any resource and also will allow for improving how the UI looks with getting rid of the get step when set to be skipped.

**Comment by vito** [comment]
See http://stackoverflow.com/questions/38964299/why-does-concourse-get-a-resource-after-puting-it - we won't be adding a flag to disable this.

**Comment by ggeorgiev** [comment]
It seems as a lost cause, but I am not sold at all on the argumentation.
1. Needed from following steps - being optional it will allow for using it only when appropriate. 
2. It also acts as validation that the put actually had the desired effect - having my pipeline failing because of bad put in job A or job B does not make a big difference.
3. Having the get part of put to warm up the cache on one worker - I might have 50 workers, worming one that I might never use helps nothing. Getting as part of the job that needs it not only will be on a worker that really needs is, but also could be aggregated with several other steps, to really save the time.
4. Having the question: "why do only SOME put steps imply a get?" I think asking such a question as part of the learning curve for concourse is worth 10-20 minutes of the pipeline every session. Also this does not apply if the option has to be explicitly used from the maintainer of the pipeline.
5. we resist adding so many knobs - This and number 4 are in direct contradiction. So I will provide contradictive point - make it fully automatic and safe then.

**Comment by ggeorgiev** [comment]
One more thing to add - it seems that not having a difference between puts that need get and not triggers questions as well. I personally observed several such discussions for the past month or so.

**Comment by ArunSenthoorPandian** [comment]
Hello, 
Does anyone know if we have an option to skip the implicit get after the put? If so, could you point me. 
Thanks in advance.

**Comment by will-gant** [comment]
> Hello, Does anyone know if we have an option to skip the implicit get after the put? If so, could you point me. Thanks in advance.

Way too late to be of use to you, but in case anybody else sees this: no. A few specific resources implement this via a `get_param`- e.g. the [registry image resource](https://github.com/concourse/registry-image-resource) has a `skip_download` get param (documented [here](https://github.com/concourse/registry-image-resource#get-step-params)). In a similar vein, the [s3 resource](https://github.com/concourse/s3-resource) has a `get_param` that lets you skip downloading the file in question (docs [here](https://github.com/concourse/s3-resource#parameters)).

Where the resource doesn't offer something like this, I'm afraid you're stuck with the implicit get.
