### ISSUE TITLE
please detect that task image is missing its own "get"

### ISSUE THREAD

**Issue by larham** [concourse/concourse#840]
# Feature Request

Can you help us catch a task image that lacks a "get"?  

We created an erroneous task which specified and image without a get, such as

```
- name my_task
   - task: my_task
      image: someimage
```

where "someimage" had no corresponding "get" clause, we ran into the error:

```
failed-to-lookup-source-for-image-artifact
```

However, this error message did not lead us to the root cause immediately, since we were inexperienced.  When we posted to the concourseci slack, we were encouraged to create this feature request. 

Ideally, the set-pipeline configuration check would detect this problem and refuse to set the pipeline.

* Concourse version: 2.5.0

**Comment by vito** [comment]
What showed up in the UI? We can't really detect this 100% as the image may also come from a preceding task's output. In principle we could say conclusively that if there are no preceding `task` or `get` steps that it's probably error, but it'd feel awkward to have an error that only works in that edge case; we'd still want to improve the UX for the error itself.

**Comment by ggeorgiev** [comment]
All I said to help few people was: there is task image without `get`. Even something simple like this could be helpful

**Comment by larham** [comment]
the error shows up as attached. 

if detection is not clean, then please consider just re-wording the error message like "check that each of the images in the task is supplied with a "get" or otherwise"

![failed-to-lookup-source](https://cloud.githubusercontent.com/assets/467739/21534047/45977d3e-cd16-11e6-8504-4f790df6fb5e.png)
