### ISSUE TITLE
Resource cache broken in 7.8.1?

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#8473]
## Summary

After upgrading to `7.8.1` (coming from `7.7.1`) every single step, be it a `task`, `get` or `put` will always download the required image to run instead of re-using a previously downloaded image. 

A `task` seems to always download the `image_resource`, and `get`/`put` to always download the corresponding `resource_type` image (obviously only applies to custom resource types).

For whatever reason it never re-uses an resource image from cache. In `7.7.1` it was often the case one would see the message: 
```
INFO: found existing resource cache
```
whenever a `get` was performed on an image of a `resource_type`. Same for `get` on a task's `image_resource`.

In `7.8.1` one of two things happen, either:
- The `get` for the `resource_type` image (or for the task's `image_resource`) immediately downloads the image
- The `get` for the `resource_type` image logs `INFO: waiting to acquire resource lock` and gets stuck there anywhere between a couple of seconds and several minutes, _then_ downloads the image

This happens even if, either within the same pipeline or across builds the `get` for the `resource_type` image lands on the same worker.

## Steps to reproduce

The only thing I could think of that might be relevant is that we are using global resources. 

_TODO: I'll try and setup a repo with docker compose, but maybe the bug report raises some flags for people more familiar with recent changes that might have caused this_ 

## Expected results

Once a `resource_type` image is downloaded, subsequent uses of that image (assuming no changes to the `resource_type` definition nor to the image sha256) re-use an image from cache.

## Actual results

Concourse is always re-downloading the same `resource_type` images and `image_resource` (from `tasks`) over and over again on every step.

## Additional context

Here's an example:
![resource-lock](https://user-images.githubusercontent.com/23340138/178578015-8c9b7284-cb11-4d90-8b40-daaa5a1df2cb.png)

It's pulling the _same_ image that was pulled in a previous step and it's doing it on the _same worker_.

I can provide any relevant info and metrics if necessary.

## Triaging info

* Concourse version: `7.8.1`
* Browser (if applicable):
* Did this used to work? Yes, in `7.7.1` we never had this issue

**Comment by pn-santos** [comment]
Small update: I tried to reproduce with `docker-compose` but wasn't able to, seems whatever triggered this issue is associated with either our DB state or the configs we are running concourse with - or both (though fact remains we didn't have this problem with `7.7.1`).

If anyone has any suspicions on what it could be, please shout ^_^

**Comment by pn-santos** [comment]
We've decided to do a rollback back to `7.7.1` but we'll keep an eye for this bug fix and attempt to upgrade again then :+1:

**Comment by dhantha** [comment]
We had a similar issue recently. We upgraded to v7.8.1 and in our case, the `github-pr-resource` resource checks were not triggering and manual checks seem to be hung up on `INFO: waiting to acquire resource lock`. On further investigation, we looked into the [`attempGet`](https://github.com/concourse/concourse/blob/v7.6.0/atc/exec/get_step.go#L324) function which is responsible for retrieving the cache resource or creating if not found. According to the function comment:

```
`attemptGet` performs the following flow:
	
 * Check if resource is cached
     * If yes, then use the cache and exit
     * If no, then proceed to next step
 * Attempt to acquire a lock that's unique to the resource (and possibly
   also the worker, if EnableCacheStreamedVolumes is disabled)
     * If lock acquisition failed, give up (and try again after
       GetResourceLockInterval)
     * If lock acquisition succeeded, then run the get script and initialize the volume as a resource cache.
```

If the volume is not in the cache, then this function acquires a lock and calls the [`performGetAndInitCache`](https://github.com/concourse/concourse/blob/v7.6.0/atc/exec/get_step.go#L352).  This function gets the volume and initialize the resource cache by calling [`InitializeResourceCache`](https://github.com/concourse/concourse/blob/e3d9f5bb1d41e56b5de584e2b96505a90f1fe2b6/atc/exec/get_step.go#L499). `InitializeResouceCAche` then updates the [`volumes`](https://github.com/concourse/concourse/blob/e3d9f5bb1d41e56b5de584e2b96505a90f1fe2b6/atc/db/volume.go#L448) table with a `worker_resource_cache_id`

By looking into the cloud watch logs during that time we were able to see an error for `ERROR: duplicate key value violates unique constraint "volumes_worker_resource_cache_unique"`

```
2022-07-11 17:02:03 UTC:10.142.25.47(22874):concourse@atc:[22737]:ERROR: duplicate key value violates unique constraint "volumes_worker_resource_cache_unique"
2022-07-11 17:02:03 UTC:10.142.25.47(22874):concourse@atc:[22737]:DETAIL: Key (worker_resource_cache_id)=(669352) already exists.
2022-07-11 17:02:03 UTC:10.142.25.47(22874):concourse@atc:[22737]:STATEMENT: UPDATE volumes SET worker_resource_cache_id = $1, team_id = $2 WHERE id = $3
2022-07-11 17:03:16 UTC:10.142.25.47(22898):concourse@atc:[22743]:ERROR: duplicate key value violates unique constraint "volumes_worker_resource_cache_unique"
2022-07-11 17:03:16 UTC:10.142.25.47(22898):concourse@atc:[22743]:DETAIL: Key (worker_resource_cache_id)=(669381) already exists.
2022-07-11 17:03:16 UTC:10.142.25.47(22898):concourse@atc:[22743]:STATEMENT: UPDATE volumes SET worker_resource_cache_id = $1, team_id = $2 WHERE id = $3
```

Looking at the error statement for this [`update`](https://github.com/concourse/concourse/blob/e3d9f5bb1d41e56b5de584e2b96505a90f1fe2b6/atc/db/volume.go#L456)

```
another volume was 'blessed' as the cache volume - leave this one
owned by the container so it just expires when the container is GCed
```

The issue got resolved after doing a worker refresh through our ASG. The fact that this issue got resolved after a worker refresh means that the worker volumes got GCed.

**Comment by evanchaoli** [comment]
@dhantha The root cause is that invalid entries in `worker_resource_caches` are not properly GC-ed. I'm working on a fix.

Before that, workaround is to manually cleanup `worker_resource_caches` with the following SQL:

```
delete from worker_resource_caches where worker_base_resource_type_id is null;
```

Our clusters now use a clone job to run the SQL every 3 hours. In theory, we can run it more frequently, even every 60 or 30 minutes.
