### ISSUE TITLE
Feature request: 'all' group

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#848]
Often we'll break up a pipeline with groups, e.g.:

- ui
- backend
- deploy

It'd be great to be able to specify an 'all' group that automagically captures all jobs in the manifest, so that we can see all our things before we need to filter down to a specific group:

- all
- ui
- backend
- deploy

Currently we have to create this group and manually spell out every single job, which is tedious and not-scalable.

**Comment by vito** [comment]
Consolidating this into https://github.com/concourse/concourse/issues/469 - it's come up before

**Comment by jadekler** [comment]
👍
