### ISSUE TITLE
Concourse seems to hang when build iOS files with fastlane and xcpretty

### ISSUE THREAD

**Issue by xtreme-shane-lattanzio** [concourse/concourse#851]
Hi there!

# Bug Report

I have seen an issue with iOS building for a while now and have been seeing a strange hang issue. We are using fastlane to build our ipa files with gym and there is a parameter we can set inside of it to disable xcpretty. If we do not set this, concourse seems to hang. Setting it as disabled lets it work. It is fine if we run the fastlane script locally but concourse seems to not like it.

Specifically the command that seems to freeze is "bundle exec fastlane build_ipa internal:true"

This command runs xcodebuild inside of it and freezes on the following:

"set -o pipefail && xcodebuild -workspace ../testapp/testapp.xcworkspace -scheme testapp-na -configuration Staging -destination 'generic/platform=iOS' -archivePath /Users/office/Library/Developer/Xcode/Archives/2017-01-04/test-NA-1.0.1-20170104-Staging-Internal\ 2017-01-04\ 16.39.34.xcarchive clean archive | tee /Users/office/Library/Logs/gym/Blindside-test-na.log | xcpretty"

When I run that command on its own it does not hang. Also when I run the bundle exec command on the local box, there is no hang. The issue is a weird combination between fastlane without disabling xcpretty and concourse. Any ideas?
 
I have this link to show what I am talking about as well: https://docs.fastlane.tools/actions/#push

* Concourse version: 2.5.1
* Did this used to work? No

**Comment by vito** [comment]
What does xcpretty actually do? I'm unfamiliar with a bunch of these terms since I don't have an iOS dev background.

**Comment by xtreme-shane-lattanzio** [comment]
@vito From a very basic level, it just takes the normal build output and makes it "pretty". It strips out output that is difficult to read or repetitive and the output that remains gets formatted to look nicer and easier to read. The reason why I want this to work is the build output that I have is too long and often when I try to look back at old build in concourse, I cannot view it because it crashes the browser due to the fact the output is too large.
