### ISSUE TITLE
Making the login workflow easier / more automatable

### ISSUE THREAD

**Issue by joonas** [concourse/concourse#852]
# Feature Request

## What challenge are you facing?

We have a reasonably good number of teams that we've set up for our Concourse installation, and it's getting to be a little bit tedious having to do the `fly login` dance with each one of those. While we've already gone ahead and increased the `auth-duration` to help alleviate this, some of our users are still having to login to a number of different teams every so often. 

## A Modest Proposal

Couple of alternatives that came to mind as we were first discussing this are:

1. What if `fly login` could simply open up the auth url for you in the browser so you could avoid having to click on the link in the terminal.

2. What if there was an option to simply have `fly login` return the full auth url to you on the command-line so that you could then pass as an argument to another command, say `open`, to do whatever handling you'd like.

Thoughts?

I should also point out that I'm happy to take a pass at implementing something if this is deemed worthwhile addition and we can settle on an approach.

**Comment by vito** [comment]
I like both points. I'd accept a PR for either. https://github.com/pkg/browser may be worth a look

**Comment by mariash** [comment]
`fly login` now opens URL in browser automatically.

Also, there is a proposal to be able to login to multiple teams at once https://github.com/concourse/concourse/issues/720

I am going to close this issue.
