### ISSUE TITLE
Concourse's CI is private now

### ISSUE THREAD

**Issue by h4xnoodle** [concourse/concourse#8526]
## Steps to reproduce

Visit https://ci.concourse-ci.org/teams/main/pipelines/concourse when unauthorized/have no account

- 403s from trying to view the previously-public pipeline

## Expected results

I can see the pipeline

## Actual results

I cannot see the pipeline and there are other effects (github repo for concourse references its status from the same place)

![Screen Shot 2022-08-16 at 18 19 49](https://user-images.githubusercontent.com/105841/185013870-6e350996-c2f4-47d9-9e90-10432862d2d7.png)

## Additional context
n/a

## Triaging info

* Concourse version: whatever is running currently that hosts that instance
* Browser (if applicable): doesn't matter
* Did this used to work? 
yep, was showing other people an example a while ago from here. I visit sometimes to look at how the project is doing.

**Comment by taylorsilva** [comment]
@xtremerui what was the reason for this change? Could we instead make build logs private for certain jobs we're worried about leaking secrets for?

**Comment by xtremerui** [comment]
CI got repaved and the pipeline was not exposed in the process. Now it should be public. Thx for reporting!

**Comment by h4xnoodle** [comment]
thanks!
