### ISSUE TITLE
I can view workers that are not part of my team

### ISSUE THREAD

**Issue by derwei** [concourse/concourse#853]
Hi!
I have a team in a shared concourse deployment. When I deployed a pipeline with a misconfigured worker tag, I was shown a list of all workers that were connected to the concourse deployment. 
I expected to only see the ones that were associated with my team.

![screen shot 2017-01-05 at 11 19 21 am](https://cloud.githubusercontent.com/assets/2145272/21694174/e3704874-d351-11e6-9c59-7d8063b89268.png)

**Comment by ddadlani** [comment]
The ability to display available workers was removed in https://github.com/concourse/concourse/commit/03b7d909291caf1f59a3e81f8a743c72bcf956b7
