### ISSUE TITLE
Docker image from the tutorial has errors

### ISSUE THREAD

**Issue by sgri** [concourse/concourse#8531]
## Summary
I am unable to start a local Concourse instance as described at [https://concourse-ci.org/quick-start.html](https://concourse-ci.org/quick-start.html)
## Steps to reproduce

My OS is Ubuntu 22.04. I have installed Docker with "sudo snap docker install".
I follow instructions at [https://concourse-ci.org/quick-start.html](https://concourse-ci.org/quick-start.html)

$ curl -O https://concourse-ci.org/docker-compose.yml
$ docker-compose up -d
Creating docs_concourse-db_1 ...
Creating docs_concourse-db_1 ... done
Creating docs_concourse_1 ...
Creating docs_concourse_1 ... done

At this point  Concourse should be running
Then I tried to download fly
wget  http://localhost:8080/api/v1/cli?arch=amd64&platform=linux

```
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
```
## Expected results
Concourse should be running and I should be able to connect to localhost port 8080

## Actual results
I cannot connect to localhost port 8080 and Concourse prints errors
```
concourse_1     | {"timestamp":"2022-08-19T13:13:34.378554561Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 172.26.0.2:5432: connect: connection timed out","session":"3"}}

```
Looks like the root cause is that Concourse can't connect to postgresql. Why does Concourse tries to reach postgresql at 172.26.0.2:5432 ?  Shouldn't it be localhost:5432 ?

## Triaging info

* Concourse version: latest from Docker image
* Browser (if applicable): Firefox
* Did this used to work? Never

**Comment by Esysc** [comment]
Concourse DB is not mapped, you can try to modify the Dockerfile to have the service mapped to `localhost`. However it looks like a network isolation between containers.

**Comment by taylorsilva** [comment]
Did postgres actually come up? Maybe the container started and then exited? What does `docker compose ps -a` show?

**Comment by sgri** [comment]
@taylorsilva , I have tried docker-compose ps -a,  then I got an error

```
$ docker-compose ps -a
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 712, in ps
TypeError: '<' not supported between instances of 'Container' and 'Container'
[31144] Failed to execute script docker-compose
```

**Comment by sgri** [comment]
Eventually this bug has dissolved by itself. Looks like the  https://concourse-ci.org/docker-compose.yml has been updated recently. Thank you for assistance, and I close this ticket.

**Comment by Esysc** [comment]
> TypeError: '<' not supported between instances of 'Container' and 'Container'

Eventually related to this https://github.com/docker/compose/issues/6579
