### ISSUE TITLE
Request for machine to machine authentication

### ISSUE THREAD

**Issue by mjj209** [concourse/concourse#854]
# Feature Request

## What challenge are you facing?

How can our web app authenticate to the PCF Concourse-Tile to create pipelines?

We are moving from the Open source Concourse to the PCF Concourse-Tile. We have moved everything except for a set of pipelines that are made by a custom web application. Our custom application needs to create concourse pipelines when a user initiates an action inside our web app. We currently do this with basic authentication, but that doesn't work with the PCF Concourse-Tile. I also do not think basic-auth is a good long term strategy. Our web app needs to be able to create pipelines on the fly, as these pipelines deploy PCF to one of 100 available vSphere resource pools, with the version of PCF that the user requires. We would really like to turn off our Open Source concourse server, and rely only on the PCF Concourse-Tile.

I don't have any solution proposals :-(

**Comment by vito** [comment]
Sounds like https://github.com/concourse/atc/issues/42
