### ISSUE TITLE
OpenID Connect seems to ignore 'groups' (on v7.8.2)

### ISSUE THREAD

**Issue by jdelic** [concourse/concourse#8543]
## Summary

OpenID Connect appears to ignore the groups claim. This is **concourse 7.8.2**.

## Steps to reproduce

My [authserver](https://github.com/jdelic/authserver/) sends the following claims to Concourse/dex:
```json
{
    "sub": "e64e8afd-9cdd-4fc1-acf9-0df043f3f393", 
    "email": "[redacted]", 
    "username": "[redacted]", 
    "groups": ["developers"], 
    "email_verified": true, 
    "user_id": "[redacted]"
}
```

Which makes concourse log:
```json
{
    "@timestamp":"2022-09-03T20:48:04.896279+00:00",  
    "timestamp": "2022-09-03T20:48:04.895970241Z", 
    "level": "info", "source": "atc", "message": "atc.dex.event", 
    "data": { 
        "fields": { }, 
        "message": "login successful: connector \"oidc\", username=\"[redacted]\", preferred_username=\"[redacted]\", email=\"[redacted]\", groups=[\"developers\"]", 
        "session": "18" 
    } 
}
```

But the user is not logged into the group `developers`. If I set up a generic OAUTH2 configuration with the same endpoints, it works fine.

## Expected results

The user should be logged into the `developers` group.

I'd be really happy about pointers for how to debug this further. From the concourse log message I gather that concourse has all the info, but doesn't use it. If I can provide any more information, please let me know.

**Comment by xtremerui** [comment]
Have you tried the flag `CONCOURSE_OIDC_DISABLE_GET_USER_INFO` in https://github.com/concourse/concourse/pull/8353?

**Comment by jdelic** [comment]
@xtremerui 
Hey.. thank you for the hint. Just in case this changes anything I tried it with `CONCOURSE_OIDC_DISABLE_GET_USER_INFO` set to `true` and `false`. The result stays the same. However, as you can see from the log messages I posted in my original description, Concourse always _picked up_ the groups. 

Log message excerpt:
```json
{ 
    "fields": { }, 
    "message": "login successful: connector \"oidc\", username=\"[redacted]\", preferred_username=\"[redacted]\", email=\"[redacted]\", groups=[\"developers\"]", 
    "session": "18" 
}
```

The interesting bit is that even though I get a log message saying `groups=[\"developers\"]` the user doesn't get logged into the group "developers". 🤷

**Comment by xtremerui** [comment]
the root cause is concourse doesn't provide a config for [InsecureEnableGroups](https://github.com/dexidp/dex/blob/a483f5b504c6da150cc72f634a200de58651e890/connector/oidc/oidc.go#L41)

@jdelic this will be fixed in next release.

**Comment by jdelic** [comment]
@xtremerui amazing. Unfortunately I was traveling and missed your question above. Thank you for looking into this :).

**Comment by jdelic** [comment]
Hi @xtremerui,
I just tested this on 7.8.3 and it doesn't work. Did the fix make it into that release or were you referring to 7.9 perhaps? Thank you :)

**Comment by jdelic** [comment]
(I just realized that this is assigned to the 7.9.0 milestone.... my bad)

**Comment by xtremerui** [comment]
@jdelic yeah 7.8.3 meant to patch the CVE only. Thank you for your patience.

**Comment by xtremerui** [comment]
@jdelic my mistake here. Actually the config is available [here](https://github.com/concourse/concourse/blob/master/skymarshal/skycmd/oidc_flags.go#L31). By default `InsecureEnablegroups` is set to `true` on concourse dex setting.

**Comment by xtremerui** [comment]
> Hi @jdelic could you verify in your teams config in `teams` table, what do you see the groups mapping in colume `auth` for your concourse team?

you might want to double check the value here.

**Comment by jdelic** [comment]
@xtremerui 
Hey.. of course you were right. The developers team in `teams` was still linked to `oauth:developers` instead of `oidc:developers`. I think the best thing I can claim is that the log messages could perhaps be clearer 😬.

Thank you for helping me out here. I should have checked that already back then.
