### ISSUE TITLE
Build Page Out Of Date

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#856]
v 2.6.0

Some jobs are showing old data. In the case of the job shown in the screenshot this job had already mostly completed before I even navigated to the build page for the first time. So it seems like it's not a question of the page updating slowly, but of getting out of date data on page load. This has happened twice since updating to 2.6.0
![screen shot 2017-01-06 at 12 00 49 pm](https://cloud.githubusercontent.com/assets/1178694/21725904/577b4e24-d408-11e6-90cc-7bd1869db360.png)

**Comment by xtreme-gavin-enns** [comment]
Some more info: 
- After several minutes the page eventually updates, but continues to lag.
- Initially the spinners on the build steps weren't animating at all. After updating partly the appropriate spinners animated, but the build log output was still stalled

**Comment by xtreme-gavin-enns** [comment]
Here it is again, with the network traffic. Notice the lack of events of which there are many in a different chrome session that is not having trouble keeping up to date. 

![screen shot 2017-01-06 at 12 19 11 pm](https://cloud.githubusercontent.com/assets/1178694/21726361/6f833caa-d40a-11e6-9aa1-31a551608a32.png)

**Comment by vito** [comment]
I don't believe it's possible to get old data. We don't store that. We store an event stream and then the UI replays it, so if the network is slow it may take a while to replay it. And if there's a ton of output it may just take a while to process all that before the browser gets a chance to redraw.

Make sure you capture the network traffic right from the beginning; that screenshot doesn't seem to show the `events` request which is what would be doing the bulk of the work.

**Comment by xtreme-gavin-enns** [comment]
I'll see about opening the console before going the the build page next time we see this

**Comment by xtreme-gavin-enns** [comment]
Looks like the events call is hanging

![screen shot 2017-01-06 at 3 03 12 pm](https://cloud.githubusercontent.com/assets/1178694/21731230/60a6e706-d421-11e6-9f8c-a6595f735722.png)

**Comment by xtreme-gavin-enns** [comment]
Took 4.5 minutes
![screen shot 2017-01-06 at 3 08 08 pm](https://cloud.githubusercontent.com/assets/1178694/21731352/fc90aeb8-d421-11e6-8f1a-8ff8058a029c.png)

**Comment by xtreme-gavin-enns** [comment]
But subsequent calls don't do any better
![screen shot 2017-01-06 at 3 07 59 pm](https://cloud.githubusercontent.com/assets/1178694/21731381/1739d762-d422-11e6-9644-5fb10c0ec502.png)

**Comment by xtreme-gavin-enns** [comment]
This is on a 4 year old macbook air and the internet connection seems a bit slow. Maybe that's all it is but this seemed extreme.

**Comment by chendrix** [comment]
Hi there, I'm going to close this as it looks like your question was resolved. Feel free to reopen or to ask on [slack](https://slack.concourse.ci) or on [stackoverflow](http://stackoverflow.com/questions/tagged/concourse%3E)
