### ISSUE TITLE
Volumes not GCed due to in use resource caches for next built input

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#8563]
## Summary

[Topgun test](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-topgun-runtime/builds/10.1#L6323170a:8251:8267) fails by following
```
• Failure [371.892 seconds]
Worker failing
github.com/concourse/concourse/topgun/runtime/worker_failing_test.go:10
  when the worker becomes unresponsive
  github.com/concourse/concourse/topgun/runtime/worker_failing_test.go:20
    puts the worker in stalled state and does not lock up garbage collection [It]
    github.com/concourse/concourse/topgun/runtime/worker_failing_test.go:41

    Timed out after 120.000s.
    Expected
        <[]string | len:2, cap:2>: [
            "fffb6b48-a919-47de-597e-88ab29291b3c",
            "8c4659a4-111a-47ea-5fc5-311c536bf30a",
        ]
    to be empty

    github.com/concourse/concourse/topgun/runtime/worker_failing_test.go:57
```
The test is basically expecting volumes for old versions to be GCed when there is new version being found.

The root cause is from PR https://github.com/concourse/concourse/pull/8504. When there is a new version of a non trigger resource in a job, the [Schedule](https://github.com/concourse/concourse/blob/master/atc/scheduler/scheduler.go#L29) function is not called, within which the algorithm `Compute` would run to find the new input version and `SaveNextInputMapping` will remove the old input versions (and thus the resource caches reference gone). Then the volumes for old versions will be considered [orphaned](https://github.com/concourse/concourse/blob/70748a87c13f1503993baa9f7cc77e7267649b37/atc/db/volume_repository.go#L539) and GCed. 

## Steps to reproduce

1. docker compose local concourse
2. set a pipeline `test`
```
---
resources:
- name: controlled-trigger
  type: mock
  source: {initial_version: first}

jobs:
- name: use-safe-worker
  plan:
  - get: controlled-trigger
```
3. trigger the job and verify the version  `first` exist in `resource_config_versions`
3. `fly check-resource -r test/controlled-trigger -f  version:second`
4. verify version second is in table `resource_config_versions`
5. verify in volumes table the volume for fist version still exist after GC tick 

## Expected results

In step 5, after newer version found, `next_build_inputs` should only have the newer version for the job so that resource cache for old version will be GCed (cascading the `worker_resource_cache_id` in volumes table to be nil) so the volume can be GCed

## Actual results

`worker_resource_cache_id` not nil

## Triaging info
@SimonXming @evanchaoli

* Concourse version: latest dev
* Browser (if applicable):
* Did this used to work?

**Comment by xtremerui** [comment]
@SimonXming FYI we still have plenty of time (before November) to fix this regression. However if things don't work out as planed, we will have to revert #8504 just because it is failing topgun test, which is blocking for releasing v7.9.

**Comment by SimonXming** [comment]
> @SimonXming FYI we still have plenty of time (before November) to fix this regression. However if things don't work out as planed, we will have to revert #8504 just because it is failing topgun test, which is blocking for releasing v7.9.

Hi @xtremerui, sorry for the delay... I will looking into this issue.

**Comment by SimonXming** [comment]
Hi @xtremerui, I'm assessing the impact of this issue, and here is my thoughts for https://github.com/concourse/concourse/pull/8504
- Before this PR, after every time any resources(trigger or not) found a new version, the resource cache for old version will be marked as GC-ready, so volumes can be GCed later.
- After this PR, after trigger resources found a new version(or there is `pending` build), the resource cache for old version will be marked as GC-ready.
- Of course, there will be some outdated volumes which are not get GCed in time. And if a pipeline don't have a trigger resource and there are no build get triggered, old resource cache will never not get GCed.

**Comment by xtremerui** [comment]
It is in https://github.com/concourse/concourse/blob/eaab65373b1cb35b62c859e69099c330452a46ca/atc/db/job.go#L1193-L1200 where old inputs will be deleted (so the cache will be gone) and new version of input (comes from algorithem.Compute) will be inserted.

**Comment by SimonXming** [comment]
Hi @xtremerui, I'm thinking keep the latest cache used in builds(remove it until a new build triggered) instead of remove it immediately every time a new version detected is reasonable. So I create a branch for fix the topgun test, what do you think?
* https://github.com/concourse/concourse/compare/master...SimonXming:concourse:fix-topgun-test

**Comment by xtremerui** [comment]
@SimonXming my gut feeling is the resouce cache should be GCed once the new resource version is found, since it won't be needed for the next build whatsoever. 

The most use cases are multiple resource inputs of one job are getting new versions more frequent than the build triggering rate (e.g releasing kind of job), which means the unneeded resource cache could be kept for a very long time by your suggestion change. 

I think we should free resource allocation as soon as we can instead of waiting.

**Comment by SimonXming** [comment]
OK, to unblock the v7.9 release maybe we could revert the previous PR https://github.com/concourse/concourse/pull/8504 before we came up a better solution for this redundant job schedule issue... Thanks @xtremerui
