### ISSUE TITLE
Not possible for check step to recover resource metadata (?)

### ISSUE THREAD

**Issue by breathe** [concourse/concourse#8576]
## Steps to reproduce

I implemented a custom resource without a concept of `check` step.  Its usage in our pipeline was:

`put: resource`

... later in pipeline

`get: resource`

and we were intending to rely on the history of versions that were pushed.  There was no other notion of 'version' that we cared about tracking for this resource type aside from 'the thing went through that particular put step in the pipeline with some set of arguments'.

This worked fine until concourse decided to lose the history of versions associated with the resource.  I understand that there exists scenarios where the concourse version history is expected to be lost -- namely around changing the declaration of the resource or resource type -- however there are other scenarios where the history of what was 'previously pushed by' the resource became 'lost' which I don't understand or expect.  In my experience, the history associated with the resource would become truncated down to just a few recent results sometimes and I don't have an explanation for why.

So -- we decided to work around this issue by adding a check step to the custom resource type which rebuilds the history of versions from a source of truth.

That works, however from what I can tell from the documentation the [check step](https://concourse-ci.org/implementing-resource-types.html#resource-check) for a custom resource is only supposed to output a list of versions.  Is there an undocumented mode to allow the check step to also output a list of `Metadata`'s ?

I noticed the git resource seems to be able to recover metadata's for versions retrieved by a check step -- however its [doing the same thing](https://github.com/concourse/git-resource/blob/6b4aba79bf5c1fd5c813bc8472f509fdbc75f417/assets/check#L175) I do in my custom resource and only actually outputs the list of versions in its implementation ... 

## Expected results

Could author a check step that recovers versions of a resource _and_ the metadata associated to each version

## Actual results

Can author a check step that recovers only versions

## Triaging info

* Concourse version: v7.8.0
* Did this used to work? No

**Comment by evanchaoli** [comment]
As far as I know, `check` only generate versions, then `get` generate metadata for version it runs against. Also `put` may generate metadata for version it generated. So, `check` has no way to recover metadata.

**Comment by marco-m** [comment]
The `check` step does not emit metadata. On the other hand, the `version` object is a _map_ of k/v and you can have as many keys as you want. From https://concourse-ci.org/implementing-resource-types.html#resource-check:

> `version` is a JSON object with string fields, used to **uniquely** identify an instance of the resource.

Then it goes on with an example for the git resource:

```json
[
  { "ref": "61cbef" },
  { "ref": "d74e01" },
  { "ref": "7154fe" }
]
```

So an hypothetical resource check step could emit:

```json
[
  { "key1": "61cbef", "key2": "foo" },
  { "key1": "d74e01", "key2": "bar" },
  { "key1": "7154fe", "key2": "foo" }
]
```
and so on. This might (or not) help you...
