### ISSUE TITLE
Forever (young) Spinner

### ISSUE THREAD

**Issue by dprotaso** [concourse/concourse#858]
# Bug Report

Visiting a build page (ie. .../builds/21) when you are not authenticated redirects to the login page with a spinner that spins forever.

I've reproduced this in Chrome & Safari - if it doesn't happen the first time paste the link in the address bar and load the page.

* Concourse version: 2.6.0
* Deployment type BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Latest Chrome & Safari
* Did this used to work? Yes

**Comment by jama-pivotal** [comment]
@dprotaso I havent been able to reproduce this issue using the latest Concourse 3.4.0. Feel free to re-open if you're able to repro it!
