### ISSUE TITLE
Wrong variable name in testflight suite

### ISSUE THREAD

**Issue by elliot-gould** [concourse/concourse#8591]
## Summary

The wrong variable name is being used when assigning the atcGuestUser value from the environment.
https://github.com/concourse/concourse/blob/582941fa3f47e64a2e4187462fa6dd31855c6a4b/testflight/suite_test.go#L99

This should be corrected to:
```suggestion
config.ATCGuestUsername = atcGuestUsername 
```

## Steps to reproduce
When running testflight and using environments variable to override the default login credentials, testflight fails to log in as the guest user with an incorrect username/password error.

## Expected results
testflight should be able to log into the guest user.

**Comment by xtremerui** [comment]
thx for reporting the bug. Would you be able to open a PR for that?

**Comment by elliot-gould** [comment]
Sure, i've opened #8594.
Let me know if this is ok!
