### ISSUE TITLE
Hijack Security Risk - Solutions?

### ISSUE THREAD

**Issue by gaigaslab-operations** [concourse/concourse#8599]
Developers have access to hijack concourse containers.  Within these containers are secrets (in environment variables) and, often, in state files (e.g. ~/.cf/config).  These allow escalated access.

Are there any ways to restrict access in the interactive shell that the hijack drops a user into?  For example, a restricted shell that blocks access to the `cf` command - or, alternatively a list of permitted commands.

We've thought about having separate teams with separate pipelines for deployments to upper environments, but that seems overly complex.  
For example, this is unwieldy - double the number of teams and pipelines:
<team>-dev with pipelines for deployment to dev where developers already have SpaceDeveloper (on CF/Tanzu) access - this would be the 'Member' role in Concourse
<team> with pipelines for deployment to non-dev where developers have restricted access to the underlying cloud platform and would only have 'Viewer' role in Concourse

Options
Restricted shell for interactive mode shells (i.e. hijack)?
Optional per-job role mapping?

**Comment by taylorsilva** [comment]
OPA is probably the best tool you can use with Concourse to accomplish some of the things you're looking for: https://concourse-ci.org/opa.html

The tldr is that OPA let's you make custom rules for various API's inside some app; some app being Concourse in this case.

You wouldn't be able to restrict the users shell when they hijack in anyway; something like that would be a new feature that would need to be added to Concourse.

The per-job role mapping; not sure what exactly you meant by that but it sounds like something that OPA could help accomplish

**Comment by gaigaslab-operations** [comment]
Thank you, @taylorsilva, I did not know that OPA was integrated into Concourse.

I don't, however, see how this would prevent a user from running the `cf` command while in a hijacked container.  I could see how this would prevent or put additional considerations on being able to hijack a container, but not once they are in the container.  

I'm by no means an OPA expert, however.

**Comment by taylorsilva** [comment]
You are correct and that's exactly what I was saying with my comment. OPA was the only thing I could think of that would kinda help. Definitely not a complete solution though and won't allow you to lock down commands run inside a shell.

**Comment by gaigaslab-operations** [comment]
I think that we have a plan.

If we can create an OPA policy that limits access to hijack non-development-environment jobs for non-administrative users (therefore allowing administrators to hijack higher environment tasks), we should be good.

Thank you!

**Comment by taylorsilva** [comment]
Glad you figured something out. Gonna close this issue.
