### ISSUE TITLE
Docker documentation incorrect

### ISSUE THREAD

**Issue by jrhoward** [concourse/concourse#863]
# Bug Report

The documentation for a docker install at https://concourse.ci/docker-repository.html is incorrect.

The commands

```
ssh-keygen -t rsa -f ./keys/web/host_key -N ''
.

cp ./keys/web/host_key.pub ./keys/worker
```

should be: 

```
ssh-keygen -t rsa -f ./keys/web/tsa_host_key -N ''
.

cp ./keys/web/tsa_host_key.pub ./keys/worker
```

docker inspect reveals that the the worker and the web containers are looking for a file called tsa_host_key and tsa_host_key.pub not host_key and host_key.pub

Also for us running SELinux enforcing this command is useful

`chcon -Rt svirt_sandbox_file_t keys`

**Comment by dmt** [comment]
I had the same problem and it's pretty grating. Having your one page "hey let's just try this out" page fail you with non-helpful errors made me feel a little frustrated.

For better googleability:
`concourse-web_1     | failed to configure SSH server: open : no such file or directory`

**Comment by shakfu** [comment]
I've had the same problem. Very frustrating out of the box experience!
