### ISSUE TITLE
Broken CSS on single-page docs 

### ISSUE THREAD

**Issue by asehra** [concourse/concourse#865]
# Bug Report

Single-page Docs appear broken when viewed on a browser window narrower than 1200px. Observed on both chrome and firefox.

![screen shot 2017-01-10 at 22 56 52](https://cloud.githubusercontent.com/assets/553687/21828443/6545bf7a-d788-11e6-98ab-c57582c1ba1e.png)

**Comment by jama-pivotal** [comment]
closing this issue thanks to @asehra fix!
