### ISSUE TITLE
unpause-job should't succeed when unpausing an invalid job

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#867]
# Bug Report

* Concourse version: **2.5.1**
* Deployment type (BOSH/Docker/binary): **binary**
* Infrastructure/IaaS: **N/A**
* Browser (if applicable): **N/A**
* Did this used to work? **Unknown**

## Steps to reproduce:
* Run `fly -t <target> unpause-job some_pipeline_that_doesnot_exist/asdf`

## Actual Behavior:
Running `fly unpause-job some_pipeline_that_doesnot_exist/asdf` returns with `unpaused 'asdf'

## Expected Behavior:
Running `fly unpause-job some_pipeline_that_doesnot_exist/asdf` should return with an error saying the pipeline doesn't exist.

**Comment by doty-pivotal** [comment]
I can confirm that this is still an issue in Concourse version `4.2.1`.

Also note that the return code after pausing a job that doesn't exist is 0.
