### ISSUE TITLE
Missing versions.yml in concourse-bosh-deployment for tag v7.9.0

### ISSUE THREAD

**Issue by Kump3r** [concourse/concourse#8671]
## Summary

After the [bump commit for v7.9.0](https://github.com/concourse/concourse-bosh-deployment/commit/1f5211f7957651c84840f9e4dbeb72e46c093432), the [CI Bot deleted](https://github.com/concourse/concourse-bosh-deployment/commit/e28596a703a0fc35eab2f787cecb46ad3b756a31) the contents of `versions.yml` for v7.9.0. There is an open issue on [concourse-bosh-deployment](https://github.com/concourse/concourse-bosh-deployment/issues/245), however there isn't any progress/updates
Also there is a [thread in Discord](https://discord.com/channels/219899946617274369/413770960089382922/1060550477294600313), however no replies yet.
Can someone please take a look and or fix this?
Thanks in advance,

* Concourse version: 7.9.0
* Did this used to work? Yes

**Comment by xtremerui** [comment]
the file is now restored. Thx for reporting.

**Comment by Kump3r** [comment]
It is fixed for the 7.9.x branch, but can someone also fix the tag for 7.9.0?

**Comment by xtremerui** [comment]
@Kump3r the tag is pushed again. Please let me know if it fixes the problem.

**Comment by Kump3r** [comment]
Fixed, thank you!
