### ISSUE TITLE
New "jobs" command for fly

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#868]
# Feature Request

## What challenge are you facing?

I am trying to pause all jobs within concourse (yes, jobs, not pipelines). In order to do that, I need a list of all of the jobs currently configured so I can put them into the `pause-job` command. Similar to the `pipelines` command, a `jobs` command would be super useful to see a list of all jobs (either globally or for a specific pipeline).

**Comment by xtremerui** [comment]
fly has `jobs` command now as in concourse 4.0.0. Closing.
