### ISSUE TITLE
New 'resources' command for fly

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#869]
# Feature Request

## What challenge are you facing?

I am trying to pause all resources within concourse (yes, resources, not pipelines). In order to do that, I need a list of all of the resources currently configured so I can put them into the `pause-resource` command. Similar to the `pipelines` command, a `resources` command would be super useful to see a list of all resources (either globally or for a specific pipeline).

**Comment by jama-pivotal** [comment]
Would also be nice to have `fly resource-versions` to support the pinning/unpinning features in #2702

**Comment by mhuangpivotal** [comment]
`fly resources` command has been added in #2868.

It is no longer possible to pause a resource (even in the UI) because resource versions are now global (#2386). Instead, a resource can be pinned to a specific version (#2439, #2508).
