### ISSUE TITLE
Interface fake implementations auto-generate for unit test seems broken

### ISSUE THREAD

**Issue by SimonXming** [concourse/concourse#8710]
## Summary
Interface fake implementations auto-generate for unit test seems broken for `atc/db/worker_factory.go`.

## Steps to reproduce
```
> cd concourse
> go generate ./...
...
/concourse/concourse/atc/db/worker_factory.go:141:29: cannot use rows (variable of type *sql.Rows) as scannable value in argument to scanWorker: wrong type for method Scan
atc/db/resource_cache.go:24: running "counterfeiter": exit status 1
```

## Expected results
`go generate` should run successfully.

## Actual results
`go generate` failed for `atc/db/worker_factory.go`.

## Triaging info

* Concourse version: current master branch
* Browser (if applicable): None
* Did this used to work?

**Comment by evanchaoli** [comment]
I encountered the issue and managed to resolve it, see https://github.com/concourse/concourse/pull/8709/files#diff-46357deb3d4d7428251d3c0a42c4e990c1db47255ff830e7819ce9e1659eca91R24
