### ISSUE TITLE
Concourse GitHub Discussions offline

### ISSUE THREAD

**Issue by jwatson0** [concourse/concourse#8715]
## Concourse GitHub Discussions offline

The GitHub Discussions forum for Concourse seems to have been removed.  Is this intentional?  Perhaps it was accidentally disabled?  There are many helpful topics there that are indexed by Google that can help people use Concourse.

## Steps to reproduce

Open the discussions url or a Google search result such as:
- https://github.com/concourse/concourse/discussions
- "[Troubleshooting "no space left on device" #5463](https://github.com/concourse/concourse/discussions/5463)

The Discussions forum is also linked from the https://concourse-ci.org/ home page

## Expected results

View the forum post

## Actual results

GitHub 404 page

## Additional context

- Search Google for "concourse no space left on device" and view the first result pointing to GitHub discussions.  This was working within the last couple of weeks.
- Perhaps this was accidentally disabled in https://github.com/concourse/concourse/settings

**Comment by taylorsilva** [comment]
@xtremerui what happened?

**Comment by xtremerui** [comment]
@taylorsilva i have no idea why it was disabled. I have enable it now. Thx for reporting and pinning. I'd appreciate such pins as there are too many places to look over now.

**Comment by jwatson0** [comment]
@xtremerui @taylorsilva
Thanks!  However, it looks like the urls for discussions have changed since the re-enable.  Google still has the old urls indexed, but those links return a 404.

For example:
https://www.google.com/search?q=concourse+no+space+left+on+device
    returns the first result as:
    https://github.com/concourse/concourse/discussions/5463
    which gives a 404.

Changing the url to
    https://github.com/orgs/concourse/discussions/5463
shows the forum post correctly.

I don't know if github org admins even have control over that part of the url. Hopefully google will re-index and fix the urls eventually.

**Comment by xtremerui** [comment]
@jwatson0 i understand now there is a github action somewhere that disables the discussion, constantly. Will need sometime to fix it.

**Comment by jwatson0** [comment]
@xtremerui  It looks like this is working now.   Thanks!

**Comment by marco-m-pix4d** [comment]
@xtremerui I think this can be closed as fixed.
