### ISSUE TITLE
Admin access scoped to individual teams

### ISSUE THREAD

**Issue by pivotal-todd-ritchie** [concourse/concourse#872]
# Feature Request

## What challenge are you facing?

We've got a multi-tenant concourse installation where we'd like to give individual teams the ability to manage their own authentication. That way they can do things like add a limited permission user for concourse-summary.

## A Modest Proposal

Allow admin rights to be scoped to a particular team rather than globally.

**Comment by vito** [comment]
Teams can already update their own auth config. Is that not sufficient?

**Comment by pivotal-todd-ritchie** [comment]
Seems I made a mistake and thought they couldn't. We can close this one off.
