### ISSUE TITLE
fly -t TARGET builds -p pipeline --team OTHER_TEAM returns pipeline/job not found

### ISSUE THREAD

**Issue by eitah** [concourse/concourse#8722]
## Summary

We have several concourse teams at my company and use the `--team` option to issue a command from, say, the `main` team and see pipelines in other concourse teams. However for `fly builds` the `--team` arg is accepted but always returns `pipeline/job not found` unless your team matches the team of the builds requested.

## Steps to reproduce

Make a pipeline 'my-pipeline' in 'other' target. 
From a fly cli target with team main, issue `fly -t main --team other builds -p my-pipeline`

## Expected results

builds would be returned.

## Actual results

Pipeline/job not found

## Additional context

As a workaround we issue the below bash script
```
for team in `fly -t main teams --json | jq -r '.[].name'` ; do fly -t $team login -b --concourse-url my-concourse --team-name=$team ; done
```
then just run the builds command per usual

## Triaging info

* Concourse version:
```
$ fly -v
7.9.1
```

* Browser (if applicable):
* Did this used to work? unsure.

**Comment by xtremerui** [comment]
Hi, just want to confirm, if you remove `-p my-pipeline`, would the cmd work?

**Comment by pd** [comment]
If you drop `-p`, then the `--team` flag is honored, yes.

But with `-p` or `-j`, fly will only return results for the current team: https://github.com/concourse/concourse/blob/ebeefc5780d3546a5492b0747b2b1bea3e056657/fly/commands/builds.go#L76-L82

You can also see this with `fly --verbose`:

```
$ fly --verbose -t main builds --team=other-team --job test/job
...
2023/10/13 08:45:20 GET /api/v1/teams/main/pipelines/test/jobs/job/builds?limit=50 HTTP/1.1
```
