### ISSUE TITLE
Large amounts of log output are cumbersome in the browser

### ISSUE THREAD

**Issue by dolph** [concourse/concourse#875]
# Feature Request

## What challenge are you facing?

Some jobs / tasks result in many megabytes of log output, which is very cumbersome to load in a browser as concourse tries to continuously scroll down to keep up. This behavior is acceptable if you've been watching the job since it started, but it's very cumbersome after such a job has already had a chance to generate many megabytes of output. It radically increases the amount of time it takes to switch from viewing the progress of one job to the next.

## A Modest Proposal

Instead of showing the complete log file, "tail" it. Only show the last few hundred lines and start streaming it from there. Further, allow all the output to be downloaded from the UI to browse and manipulate offline with tools better capable of coping with that amount of data (such as `less`).

**Comment by kdvolder** [comment]
I've also noticed that large logs tends to make the browser hosting the concourse ui unresponsive (as in the OS notices that the process is no longer responding to UI event-loop and greys out the window, for seconds at a time).

**Comment by swift1911** [comment]
+1

**Comment by timrchavez** [comment]
This seems like it could be related to https://github.com/concourse/concourse/issues/1543

**Comment by ericmillin** [comment]
+1
