### ISSUE TITLE
Jobs hang as "started" even after the task has exited

### ISSUE THREAD

**Issue by dolph** [concourse/concourse#876]
# Bug Report

I generally use the run -> path attribute when writing concourse jobs. Despite having written 10 or so different scripts to call from concourse, 2 of them specifically refuse to exit the task, even after the script has reportedly exited. There's nothing special about the commands at the end of my build scripts as far as I can tell. I can even set trace and use exit at the end of a job explicitly, which will appear in the log file, but the job will still hang as "started". Deleting the pipeline and using `fly set-pipeline` again consistently results in the same behavior.

It will eventually timeout and another attempt will begin.

* Concourse version: 2.5.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Rackspace public cloud, 8GB general purpose VM

One such script that is public is here:

Pipeline: https://github.com/dolph/grenade-deploy/blob/d5985246b40bf7683a1526e478e06183fc43c643/ci/pipeline.yml

The run -> path: https://github.com/dolph/grenade-deploy/blob/d5985246b40bf7683a1526e478e06183fc43c643/ci/deploy.sh

All 3 jobs behave the same way.

When I have time, I'll attempt to reproduce with a simpler pipeline & script to narrow things down. I just wanted to go ahead and file this issue in case other had the same problem (I couldn't find an existing issue).

**Comment by jdeppe-pivotal** [comment]
I think this is a duplicate of #763.

If you hijack into the job do you see any `<defunct>` (aka zombie) processes? We started launching our scripts with `dumb-init` which has helped but has not solved the problem completely.

**Comment by dolph** [comment]
I agree, this is a dupe of #763. I'll check for zombies and report back in that bug if I find anything. Thanks!
