### ISSUE TITLE
UI: Brace, bracket, parenthesis at end of line in task output wraps to a new line in Firefox

### ISSUE THREAD

**Issue by saj** [concourse/concourse#8767]
## Summary

If a brace `{`, bracket `[`, or parenthesis `(` appears at the end of a line, and is preceded by a space, the Concourse web UI will display the brace, bracket, or parenthesis on a line of its own.  The line is soft wrapped when all content should instead appear together on one line.  Screenshots below demonstrate the effect.

The quirk only seems to manifest on Firefox -- not on Chrome.  I was able to repro in a new, blank Firefox profile.

Output looks fine from `fly watch`.  No unexpected line breaks are present in the event stream.

I don't think this quirk is a big deal, though it can make it a little bit harder to eyeball some output, particularly from stuff like Terraform.  (I have not tried to dump source code to task output.  Trailing braces may appear in diff output, which might also suffer from the same problem.)

## Steps to reproduce

Have a dummy task write the following output.  `cat` should suffice.

```
  # redact.reda_redac__redac_redacte_redac_redactedredactedr_red_123.redactedre_red_redac.r will be destroyed
  # (because redactedre_red_redac.r is not in configuration)
  - resource "redactedre_red_redac" "r" {
      - check_interval   = 1234 -> null
      - contact_groups   = [
          - "123456",
        ] -> null
      - follow_redirects = false -> null
      - id               = "123456" -> null
      - paused           = false -> null

      - alert_config {
          - alert_at    = [
              - 1,
              - 2,
              - 12,
            ] -> null
          - on_broken   = true -> null
          - on_expiry   = true -> null
          - on_mixed    = false -> null
          - on_reminder = true -> null
        }

      - monitored_resource {
          - address = "https://redac.redacte.redac.redactedredactedr.red" -> null
        }
    }
```

Navigate to the Concourse web UI in Firefox, and expand the task output.

## Expected results

Chrome 114.0.5735.106:

<img width="376" alt="image" src="https://github.com/concourse/concourse/assets/194389/19380cb2-678a-4133-8b6f-1da25d2b55c1">

## Actual results

Firefox 113.0.2 (stable):

<img width="376" alt="image" src="https://github.com/concourse/concourse/assets/194389/5b293b87-0f0a-4028-8bf6-822c2718aaa1">

Firefox 116.0a1 (nightly):

<img width="452" alt="image" src="https://github.com/concourse/concourse/assets/194389/a5e112f3-db42-4c3b-9485-417c505c8ad5">

<img width="805" alt="image" src="https://github.com/concourse/concourse/assets/194389/f4fd602d-fd8d-4e8c-b30c-49b6306c639d">

All screenshots were captured on the same machine.

## Triaging info

* Concourse version: 7.9.1
* Browser (if applicable): Firefox 116.0a1
* Did this used to work?  I don't know. :)  We only started writing output like this recently.  Unable to compare with previous Concourse releases.

**Comment by saj** [comment]
I think this got worse in 7.10.0?

<img width="738" alt="image" src="https://github.com/concourse/concourse/assets/194389/82e763c9-0829-4349-8170-fdaa085fed12">

Now, the last character on many lines is wrapped to the next line -- even part way through a 'word'.  (Like in 'MiB' in the example pictured above.)

Behaviour appears to be random.  Some lines exhibit the problem but not all.  I'm yet to determine the difference between the good/bad cases.

**Comment by saj** [comment]
![image](https://github.com/concourse/concourse/assets/194389/68425d62-50d1-4f21-a62c-90729681331f)

The first line is fine.  The second wraps.

<img width="883" alt="image" src="https://github.com/concourse/concourse/assets/194389/5cb57ea1-fa8b-4cfc-a55d-6fd7c1b2a067">

The second line has a trailing `\n`.  Is that supposed to be there?

**Comment by ei-grad** [comment]
Wonder if #7464 may be related

**Comment by saj** [comment]
This problem magically disappeared very recently in Firefox Nightly -- maybe in the last day or two.

I am on Fx 121.0a1 (20231120095246).  Output looks normal to me.

A colleague is on Fx 119.0.1 (stable).  They still observe spurious line breaks.

Perhaps this was a Firefox bug?  I suppose we may know more once Fx 120/121 is released to stable.

**Comment by saj** [comment]
> A colleague is on Fx 119.0.1 (stable). They still observe spurious line breaks.

Colleague reports the problem still present in Firefox 120.0.
Meanwhile, the Concourse UI looks OK for me on Fx 122.0a1 (20231121045833).

> Perhaps this was a Firefox bug? I suppose we may know more once Fx 120/121 is released to stable.

Scratch 120.  Perhaps we must wait for 121. 🤞

**Comment by saj** [comment]
> Perhaps we must wait for 121. 🤞

Whatever it was, it was seemingly fixed in Firefox 121, which was released to stable in the past couple of days.  Task output looks OK to us now (on Concourse v7.10.0).

Sorry for the noise.
