### ISSUE TITLE
Update Minimum Postgres Version

### ISSUE THREAD

**Issue by sig-piskule** [concourse/concourse#8790]
## Summary

I upgraded using HELM from  7.8.1 to 7.9.1 (17.0.31 -> 17.1.1)
```
$ helm ls -n concourse | grep concourse
concourse   concourse   5           2023-05-05 12:51:14.592305 +0530 +0530  deployed    concourse-17.0.31   7.8.1    
```
to
```
$ helm search repo concourse
NAME                CHART VERSION   APP VERSION DESCRIPTION                                 
concourse/concourse 17.1.1          7.9.1       Concourse is a simple and scalable CI system.
```

Running a CloudSQL Instance which was running Postgres 9.6. The upgrade failed due to
```
$ kubectl logs -n concourse concourse-web-77b78544bb-tp9lw -c concourse-migration
error: migration '1653924132_int_to_bigint.up.sql' failed and was rolled back: pq: syntax error at or near "AS"
```

Investigating this file, I found:
https://github.com/concourse/concourse/blob/4ca828100f9ab862b7d96d888e34e8f2ab3635cf/atc/db/migration/migrations/1653924132_int_to_bigint.up.sql
```
ALTER SEQUENCE resource_config_versions_id_seq AS bigint;
```

Where the `AS bigint` section was not introduced until PG 10.
9.6: https://www.postgresql.org/docs/9.6/sql-createsequence.html
10: https://www.postgresql.org/docs/10/sql-createsequence.html

The concourse documentation indicates that 9.6 is still the minimum version:
https://concourse-ci.org/postgresql-node.html

And the release notes did not seem to indicate there was a version upgrade required from 7.8.1 to 7.9.1.
https://github.com/concourse/concourse/releases

**I am currently upgrading our Postgres to V13 to see if that resolves the issue. If there are further issues, I will update this ticket.**

## Steps to reproduce

1. Install Concourse 7.8.1 with a Postgres 9.6 database.
2. Upgrade Concourse to 7.9.1
3. The upgrade should fail

## Expected results

Postgres 9.6 is end-of-life at this point. I honestly don't expect a fix for this, other than to update documentation to inform users postgres must be updated.

## Actual results

Release notes somewhere should have indicated the minimum version of Postgres changed.

## Additional context

This is an old test database, and I did not realize no-one had updated Postgres yet.

## Triaging info

* Concourse version: 7.8.1 -> 7.9.1
* Browser (if applicable): NA
* Did this used to work?: 7.8.1 was successfully deployed.

**Comment by xtremerui** [comment]
In the `Breaking` section of [release note v7.9.0](https://github.com/concourse/concourse/releases/tag/v7.9.0) it mentions the minimum version of PSQL should be v11.

The docs is updated [here](https://github.com/concourse/docs/commit/735f68c141e2bad8f444765e58ecda5c1d0c03da)
