### ISSUE TITLE
Net_cls on RO error on Amazon ECS

### ISSUE THREAD

**Issue by jasonamyers** [concourse/concourse#881]
# Bug Report

I'm attempting to run Concourse web on Amazon ECS, and I'm running an error because it attempts to create a net_cls file. Log output is below

The following can also be handy:

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Amazon ECS
* Browser (if applicable): Chrome
* Did this used to work? Initial Setup

`{"timestamp":"1484578620.828733683","source":"guardian","message":"guardian.cgroups-tmpfs-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup"}}
{"timestamp":"1484578620.830541611","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/cpuset","session":"6","subsystems":"cpuset"}}
{"timestamp":"1484578620.837197542","source":"guardian","message":"guardian.mount-cgroup.subsystems-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup/cpuset","session":"6","subsystems":"cpuset"}}
{"timestamp":"1484578620.837271214","source":"guardian","message":"guardian.mount-cgroup.finished","log_level":1,"data":{"path":"/sys/fs/cgroup/cpuset","session":"6","subsystems":"cpuset"}}
{"timestamp":"1484578620.837315559","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/cpu","session":"7","subsystems":"cpu"}}
{"timestamp":"1484578620.843442917","source":"guardian","message":"guardian.mount-cgroup.subsystems-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup/cpu","session":"7","subsystems":"cpu"}}
{"timestamp":"1484578620.843492508","source":"guardian","message":"guardian.mount-cgroup.finished","log_level":1,"data":{"path":"/sys/fs/cgroup/cpu","session":"7","subsystems":"cpu"}}
{"timestamp":"1484578620.843523502","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/cpuacct","session":"8","subsystems":"cpuacct"}}
{"timestamp":"1484578620.849552631","source":"guardian","message":"guardian.mount-cgroup.subsystems-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup/cpuacct","session":"8","subsystems":"cpuacct"}}
{"timestamp":"1484578620.849600792","source":"guardian","message":"guardian.mount-cgroup.finished","log_level":1,"data":{"path":"/sys/fs/cgroup/cpuacct","session":"8","subsystems":"cpuacct"}}
{"timestamp":"1484578620.849628925","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/blkio","session":"9","subsystems":"blkio"}}
{"timestamp":"1484578620.855498314","source":"guardian","message":"guardian.mount-cgroup.subsystems-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup/blkio","session":"9","subsystems":"blkio"}}
{"timestamp":"1484578620.855555058","source":"guardian","message":"guardian.mount-cgroup.finished","log_level":1,"data":{"path":"/sys/fs/cgroup/blkio","session":"9","subsystems":"blkio"}}
{"timestamp":"1484578620.855585814","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/memory","session":"10","subsystems":"memory"}}
{"timestamp":"1484578620.861447334","source":"guardian","message":"guardian.mount-cgroup.subsystems-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup/memory","session":"10","subsystems":"memory"}}
{"timestamp":"1484578620.861505270","source":"guardian","message":"guardian.mount-cgroup.finished","log_level":1,"data":{"path":"/sys/fs/cgroup/memory","session":"10","subsystems":"memory"}}
{"timestamp":"1484578620.861580133","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/devices","session":"11","subsystems":"devices"}}
{"timestamp":"1484578620.867287636","source":"guardian","message":"guardian.mount-cgroup.subsystems-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup/devices","session":"11","subsystems":"devices"}}
{"timestamp":"1484578620.867334604","source":"guardian","message":"guardian.mount-cgroup.finished","log_level":1,"data":{"path":"/sys/fs/cgroup/devices","session":"11","subsystems":"devices"}}
{"timestamp":"1484578620.867368698","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/freezer","session":"12","subsystems":"freezer"}}
{"timestamp":"1484578620.873271227","source":"guardian","message":"guardian.mount-cgroup.subsystems-already-mounted","log_level":1,"data":{"path":"/sys/fs/cgroup/freezer","session":"12","subsystems":"freezer"}}
{"timestamp":"1484578620.873325109","source":"guardian","message":"guardian.mount-cgroup.finished","log_level":1,"data":{"path":"/sys/fs/cgroup/freezer","session":"12","subsystems":"freezer"}}
{"timestamp":"1484578620.873403072","source":"guardian","message":"guardian.mount-cgroup.started","log_level":1,"data":{"path":"/sys/fs/cgroup/net_cls","session":"13","subsystems":"net_cls"}}
{"timestamp":"1484578620.878956079","source":"guardian","message":"guardian.start.completed","log_level":1,"data":{"session":"5"}}
{"timestamp":"1484578620.878991604","source":"guardian","message":"guardian.failed-to-start-server","log_level":2,"data":{"error":"starting starter: mkdir '/sys/fs/cgroup/net_cls': mkdir /sys/fs/cgroup/net_cls: read-only file system"}}`

**Comment by psellars-hyprnz** [comment]
@jasonamyers - I had the same issue. Setting the `"privileged": true` task definition parameter solved the issue for me. In the Docker documentation the worker has privileged mode, guessing this is the reason why.
