### ISSUE TITLE
Pipelines in the UI don't update paused status

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#883]
# Bug Report
* Concourse version: **2.6.0**
* Deployment type (BOSH/Docker/binary): **Binary**
* Infrastructure/IaaS: **Infrastructure - Ubuntu 16.04**
* Browser (if applicable): **Chrome**
* Did this used to work? **Not that I'm aware of**

Observed Behavior:
When person A is viewing the list of pipelines in the UI and person B unpauses one of the pipelines, person A's browser doesn't update showing that the pipeline has been unpaused.

Expected Behavior:
Pipelines should automatically update their paused status on the UI when the paused status is changed outside of that browser window.

**Comment by jama-pivotal** [comment]
I think this actually works properly now! helps that our sidebar is actually gone in 4.x 
![nov-20-2018 10-05-07](https://user-images.githubusercontent.com/19274230/48782268-d6ac9f00-ecab-11e8-9d8f-1157d6a6abd6.gif)
