### ISSUE TITLE
UI sometimes shows or doesn't show pipelines after login/logout

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#884]
# Bug Report
* Concourse version: **2.6.0**
* Deployment type (BOSH/Docker/binary): **Binary**
* Infrastructure/IaaS: **Infrastructure - Ubuntu 16.04**
* Browser (if applicable): **Chrome**
* Did this used to work? **Not that I'm aware of**

Observed Behavior:
Sometimes when logging in, the list of pipelines in the dropdown menu don't show up unless I refresh the page. Additionally, when logging out, the list of pipelines continues to show in the menu.

Expected Behavior:
The list of pipelines should automatically populate after successfully logging in into the UI.
The list of pipelines should automatically depopulate after logging out.

**Comment by topherbullock** [comment]
This is stale, but let's make sure this isn't still an issue, please! 🙏

**Comment by jama-pivotal** [comment]
Still haven't heard back from @pcman312 , closing
