### ISSUE TITLE
Team menu should not be sticky

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#886]
When opening the team menu in the pipeline view and then choosing another pipeline, the team menu is still open.

I expect when I click another pipeline (or even click elsewhere on the current pipeline), the team menu closes automatically.

* Concourse version: 2.5.1
* Browser (if applicable): Chrome on Linux
* Did this used to work? I don't know.

**Comment by vito** [comment]
https://github.com/concourse/concourse/issues/108
