### ISSUE TITLE
Allow slice for on_failure, on_success and ensure

### ISSUE THREAD

**Issue by mastertinner** [concourse/concourse#887]
# Feature Request

## What challenge are you facing?

I would like to run a `task` and a `put` sequentially in an `on_success`. Currently, there's no way of doing that because I can only put one statement in an `on_success`. Would it be possible to allow a slice of actions there just like any flight plan?

**Comment by vito** [comment]
You can do it via the [`do`](https://concourse.ci/do-step.html#do) step.

**Comment by mastertinner** [comment]
Silly me. Thanks, @vito!
