### ISSUE TITLE
Job crashing with an error about finding a container in namespace "concourse"

### ISSUE THREAD

**Issue by sebastienbonami** [concourse/concourse#8883]
## Summary

Hi, I have a job in a Concourse pipeline that result often (but not always) in an error like this:
`wait for process completion: backend error: Exit status: 500, message: {"Type":"","Message":"get container: container \"e91b65f1-a04a-4bda-49ba-058520a956dc\" in namespace \"concourse\": not found","Handle":"","ProcessID":"","Binary":""}`

The task that fails in the job is this one here: https://github.com/Ferlab-Ste-Justine/clin-prescription-ui/blob/2fce0427177eed8f72198e361c2830c7eec2f61c/ci/template.yml#L69-L75

My Concourse setup is in Kubernetes using this Helm chart: https://github.com/concourse/concourse-chart

I'm wondering what container Concourse is trying to find. The namespace `concourse` doesn't even actually exist in my Kubernetes cluster. The `targetNamespace` in my `HelmRelease` is not `concourse` so all Concourse resources like worker pods are in a namespace that is not named `concourse`.

Thanks for your help.

## Triaging info

* Concourse version: v7.11.0
* Helm chart version: v17.2.1

**Comment by taylorsilva** [comment]
Links are 404'ing in this issue, therefore closing it.
