### ISSUE TITLE
Configuration management friendly interface

### ISSUE THREAD

**Issue by miromode** [concourse/concourse#889]
Hi there!

We're pretty excited about Concourse, but it's a bit of a challenge automating (scripting) the use of the `fly` client. For us at least, I think the ideal for any self-hosted CI would be to make maintenance low-overhead by having something like Chef/Puppet/Ansible/Salt be able to create or update pipelines and other objects across teams.

I think the main impedances are:
  1. Ability to login under "main" team, but manage pipelines of another team. It's very difficult for a script to log into a team that has github oauth setup.
  2. Access to an HTTPS API (I'm guessing something must already be there for `fly` to use, but it appears to be purposefully undocumented)

In any case, this is just my take. What do you think we (us + concourse team) can do to address these problems?

**Comment by ahelal** [comment]
@miromode i am working on that. I am writing an Ansible module currently supports team and working on pipelines https://github.com/ahelal/ansible-concourse/pull/12  Will probably have an initial version in the next week or two

Most of the routes info i got from https://github.com/concourse/atc/blob/master/routes.go and using tcpdump and fly to understand the rest

**Comment by miromode** [comment]
Thanks @ahelal - we're using SaltStack. I'll see if I can do something similar based on your work.

**Comment by dolph** [comment]
Regarding number 2 (an HTTPS API), you just have to run concourse on HTTPS, and give fly an HTTPS concourse endpoint.
