### ISSUE TITLE
Viewing a specific build of a pipeline that has been deleted does not 404

### ISSUE THREAD

**Issue by GarfieldIsAPhilosopher** [concourse/concourse#89]
For example, we were viewing `https://concourse.example.com/pipelines/pipeline-name/jobs/job-name/builds/2` and then deleted that pipeline and refereshed the view. The UI only shows a white screen with no status codes or error messages. The console does show a 404 if you open up the developer tools window.

**Comment by Osis** [comment]
Confirmed that this still happens today, but in a different way.

**UI**
![screen shot 2017-03-16 at 11 05 51 am](https://cloud.githubusercontent.com/assets/347097/24003968/5f5dbadc-0a3b-11e7-8cd1-53e25a3204dc.png)

**Network**
![screen shot 2017-03-16 at 11 06 17 am](https://cloud.githubusercontent.com/assets/347097/24008607/78ac37cc-0a48-11e7-9a8e-fe794633f4ef.png)

**Comment by chendrix** [comment]
Similar to #1131

**Comment by chendrix** [comment]
needs #1131
