### ISSUE TITLE
"state cookie not set" when misconfigured GitHub OAuth redirect url

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#890]
I had a deployment which was using GitHub for OAuth which stopped working when someone changed the DNS settings for the deployment, which meant the redirect url given to GitHub no longer matched the OAuth application's configured redirect url.

The resulting error message in the browser is "state cookie not set". The URL has more information from GitHub, saying the redirect url must match.

I think it would be vastly more helpful if Concourse would show the error from GitHub and some debug information to help investigate it, such as the redirect url that was sent.

**Comment by PavanDevops** [comment]
Hi There,

Do we have any news or solution here ?

thanks,

**Comment by Mikulas** [comment]
This has happend to me when I deployed with `concourse.authDuration: 7d`. Setting `concourse.authDuration: 48h` fixed this issue for me.
