### ISSUE TITLE
Login redirect has different ideas about quoting than the rest of Concourse

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#891]
# Bug Report

I have a job called "environment cleanup", whose logs are not public. When I want to see them in the morning, I need to log in. I am using the 'basic authentication' mode. After logging in, I am redirected to `teams/main/pipelines/cleanup-pipeline/jobs/environment+cleanup/builds/478`. This gives me a blank page. The correct url is `teams/main/pipelines/cleanup-pipeline/jobs/environment%20cleanup/builds/478`.

The following can also be handy:

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS:
* Browser (if applicable): Chrome and Firefox
* Did this used to work? No

**Comment by jama-pivotal** [comment]
Just tested this on 3.3.4 and the URL redirection seems to work fine. Closing this for now. @hfinucane if you get a chance, please upgrade to the latest concourse and let us know if it works for you as well!

**Comment by hfinucane** [comment]
On the frontend side, you're encoding the redirect with [encodeURIComponent](https://github.com/concourse/atc/blob/f50acd2c28480dfd4af03fd1b5c2b44d9193f194/web/index.html#L48). It looks like [the redirect test](https://github.com/concourse/atc/blob/3ebc884148404830465c50178a6852ab527b4851/acceptance/login_test.go#L117) is run with [url.QueryEscape](https://golang.org/src/net/url/url.go?s=7163:7196#L254), which doesn't match the Javascript `encodeURIComponent`, it replaces spaces with `+` characters instead of `%20`.

I can't figure out where the redirect happens in `atc`, the only redirects I see are in the oauth code, I'm using basic auth, so I'm not sure that any of that is applicable.
