### ISSUE TITLE
Fly execute does not exclude MacOS extended file attributes

### ISSUE THREAD

**Issue by selzoc** [concourse/concourse#8916]
## Summary

`fly execute`, when run from a recent MacOS machine, does not pass the `--no-mac-metadata` flag to the `tar` command.  This results in the upload of many files prepended by `._` that represent extended file attributes, which causes issues with builds.  For example, if you are running git operations, suddenly you have many untracked files that were not apparent on your local computer.

From the [bsdtar man page](https://man.freebsd.org/cgi/man.cgi?query=bsdtar&sektion=1&format=html):
> --no-mac-metadata
	       (x mode only) Mac OS X specific.	 Do  not  archive  or  extract
	       ACLs  and  extended file	attributes using [copyfile(3)](https://man.freebsd.org/cgi/man.cgi?query=copyfile&sektion=3&apropos=0&manpath=FreeBSD+14.0-RELEASE+and+Ports) in	Apple-
	       Double format.  This is the reverse of --mac-metadata.  and the
	       default behavior	if tar is run as non-root in x mode.

## Steps to reproduce

Clone this repository to `$HOME/workspace/concourse`, verify that your MacOS machine uses these extended attributes with:
```shell
> cd $HOME/workspace/concourse
> xattr -l .github
com.apple.provenance:
```
Then, using this task.yml:
```yaml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang

inputs:
- name: repo

run:
  path: bash
  args:
  - -ec
  - | 
    pushd repo && ls -a | head && popd

```

run
```shell
> fly -t <target> e -c task.yml -i repo=$HOME/workspace/concourse
```

## Expected results
```shell
> ./fly -t <target> e -c task.yml -i repo=$HOME/workspace/concourse
uploading repo   done
executing build 545401549 at ...
<clipped irrelvant stuff>
... running bash -ec pushd repo && ls -a | head && popd
/tmp/build/e55deab7/repo /tmp/build/e55deab7
.
..
.agignore
.deepsource.toml
.dockerignore
.env
.github
.gitignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
/tmp/build/e55deab7
succeeded
```

## Actual results
(note that every file has a "double" prepended with `._`)
```shell
> fly -t <target> e -c task.yml -i repo=$HOME/workspace/concourse
uploading repo   done
executing build 545405592 at...
<clipped irrelevant stuff>
...running bash -ec pushd repo && ls -a | head && popd
/tmp/build/e55deab7/repo /tmp/build/e55deab7
.
..
._.agignore
._.deepsource.toml
._.dockerignore
._.env
._.gitignore
._CODE_OF_CONDUCT.md
._CONTRIBUTING.md
._Dockerfile
/tmp/build/e55deab7
succeeded
```

## Additional context

I made a similar fix to the [bosh cli](https://github.com/cloudfoundry/bosh-utils/commit/f79167bd43f3afc154065edc95799a464a80605f), and that change made locally to `fly` results in the expected output.

However, I saw that the library that `fly` uses, https://github.com/vmware-archive/go-archive, has been archived for ~2 years (and the last commit was 5 years ago).  The library that it was forked from, https://github.com/cloudfoundry/archiver, seems to be maintained, but the interface is different, so it wouldn't be a drop-in replacement.

I am happy to make a PR to https://github.com/vmware-archive/go-archive, but that would necessitate that it be unarchived and eventually bumped in this repo.

What do y'all think would be a good path forward?

## Triaging info

* Concourse version: `7.11.0`
* Browser (if applicable): N/A
* Did this used to work? Probably not!

**Comment by selzoc** [comment]
Another thing we _could_ do is just inline the code used from https://github.com/vmware-archive/go-archive and make the fix there.  I'd also be happy to PR that, but I'd like to get a go-ahead first.

**Comment by taylorsilva** [comment]
@selzoc I'd be happy with a PR bringing in the `go-archive` code and fixing this issue for mac OS users. If you have time I say go for it! I can help shepherd the PR along.

**Comment by selzoc** [comment]
@taylorsilva here you go: https://github.com/concourse/concourse/pull/8939.
