### ISSUE TITLE
Worker status in the UI

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#893]
# Feature Request

## What challenge are you facing?

My Darwin workers appears to be stalling, there is no way to tell this from the UI as far as i can see.
So I must fire up a terminal get access to the atc through fly and run the workers command

## A Modest Proposal

I would like to see the workers and their status somewhere in the UI

**Comment by JohannesRudolph** [comment]
With the work on placement strategies to address https://github.com/concourse/concourse/issues/1741, it would be very helpful to have a visualisation of workers and the containers running on them in the concourse UI.  Possibly also with a segregation of "active" containers and those that are just beeing kept around. 

I think this could fit very well with the work that is right now being done on the multi-pipeline view.
