### ISSUE TITLE
concourse/flag v2.1.0 breaks flags parsing

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#8978]
Found the bump 
```
github.com/concourse/flag/v2 v2.0.2 - > v2.1.0
```
breaks concourse flag parsing in the renovatebot [PR](https://github.com/concourse/concourse/pull/8893) where panic error shows as
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x35b5075]
goroutine 1 [running]:
main.QuickstartCommand.LessenRequirements({0x0, 0x0}, 0x0)
	github.com/concourse/concourse/cmd/concourse/quickstart.go:25 +0x35
main.ConcourseCommand.LessenRequirements({0x4659600, {{0x0, 0x0}, 0x0, 0x0}, {{{0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...}, ...}, ...)
	github.com/concourse/concourse/cmd/concourse/command.go:27 +0x68
main.main()
	github.com/concourse/concourse/cmd/concourse/main.go:23 +0x125
```

It is related a line added by the this [PR](https://github.com/concourse/flag/commit/9334a3e9b3bfe287372e95f356ebd0b78faab078) where a bool type has a default value
```
BinaryParameters bool `long:"binary-parameters" description:"Whether or not to use binary parameters for prepared statements." default:"false"`
```
Refer to https://github.com/jessevdk/go-flags/issues/175. The default is not necessary here.

**Comment by xtremerui** [comment]
@taylorsilva we need to resolve this in order to merge the renovatebot PR for dependency bumping.

**Comment by taylorsilva** [comment]
Should be unblocked now

**Comment by taylorsilva** [comment]
Panic error is gone, closing.
