### ISSUE TITLE
Documentation for `fly execute` does not document the `--tag` argument

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#898]
# Bug Report

When using `fly execute`, it is sometimes necessary to have it run on workers with a particular tag. The `fly execute` command documentation does not mention any such ability. However, using `--tag=<tag name>`, we were able to achieve our purpose.

We would make a PR, but the docs are written in WaT?eX.

**Comment by ClaraFuPivotal** [comment]
Good catch! That should definitely be in our docs, thanks for letting us know.
