### ISSUE TITLE
`fly execute` panics due to premature task "completion"

### ISSUE THREAD

**Issue by jraqula** [concourse/concourse#899]
Hi there!

# Bug Report

We are attempting to do a `fly execute` equivalent to [this task](https://github.com/cloudfoundry/bosh/blob/master/ci/pipelines/os-images/tasks/build.yml), and download the output (a tarball roughly 330MB). However, `fly` crashes with this error:

```
panic: tar extract failed (unexpected EOF). output: ""

goroutine 28 [running]:
panic(0x40e400, 0xc42042fe00)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/concourse/fly/commands/internal/executehelpers.Download(0x68e700, 0xc42017e200, 0x7fff5fbff699, 0x8, 0x7fff5fbff6a2, 0x10, 0xc420322990, 0x24, 0xc4201ad4a0, 0x51, ...)
	/Users/pilot/Worker/workdir/containers/000018vtuvb/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x1c3
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0x68e700, 0xc42017e200, 0x7fff5fbff699, 0x8, 0x7fff5fbff6a2, 0x10, 0xc420322990, 0x24, 0xc4201ad4a0, 0x51, ...)
	/Users/pilot/Worker/workdir/containers/000018vtuvb/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/execute.go:106 +0x7d
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/Users/pilot/Worker/workdir/containers/000018vtuvb/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/execute.go:110 +0x89c
```

It will do this at different points in the build strategy each time we try it. Seems like fly is deciding that the build has finished, even though it hasn't (we can see the build is still running in UI); and so downloading the output we want (which is not a tarball yet).

* Concourse version: 2.5.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): n/a
* Did this used to work? Yes

**Comment by joshzarrabi** [comment]
@jraqula Are you still seeing this on later versions?

**Comment by jraqula** [comment]
haven't seen this in at least a month

**Comment by joshzarrabi** [comment]
@jraqula Cool, I'm gonna close the issue for now. Looks like we ignored it for long enough that it went away.
