### ISSUE TITLE
fly cli can not work

### ISSUE THREAD

**Issue by jackyting825** [concourse/concourse#9001]
## fly not work,The fly command has no output prompt

According to the official documentation, after installing concourse with docker compose, the web ui can be accessed normally. Download fly from it and then install it. When using the fly command, fly does not have any output.
## Triaging info

![image](https://github.com/user-attachments/assets/5c0086d2-7777-498f-b757-1439d58e9558)
![image](https://github.com/user-attachments/assets/db9e6bfc-79eb-42de-9cd3-d90d6de9be61)
![image](https://github.com/user-attachments/assets/629ec3c3-05ad-4858-9aa2-b3ea6ab9634d)
![image](https://github.com/user-attachments/assets/db134eaa-9c69-4033-843a-024e71084893)
![image](https://github.com/user-attachments/assets/e84a206d-6502-4367-a83a-0b86cb2636ff)

* Concourse version: 7.11.2
* OS Rocky Linux 9.3

**Comment by taylorsilva** [comment]
What happens when you run:

```
file $(which fly)
```

I have a feeling something went wrong with how you downloaded `fly...

**Comment by jackyting825** [comment]
> What happens when you run:
> 
> ```
> file $(which fly)
> ```
> 
> I have a feeling something went wrong with how you downloaded fly...

![image](https://github.com/user-attachments/assets/0f723910-0f54-47e2-95af-3800ae514bb7)

output empty

**Comment by jackyting825** [comment]
> Yeah something went wrong with your download of fly. You can see that it's zero bytes in size. This is what I get on my system:
> 
> ![image](https://private-user-images.githubusercontent.com/4583837/368609066-8f1addb8-c70e-49e4-8f91-03904d7dd1f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDkyMTIsIm5iZiI6MTcyNjcwODkxMiwicGF0aCI6Ii80NTgzODM3LzM2ODYwOTA2Ni04ZjFhZGRiOC1jNzBlLTQ5ZTQtOGY5MS0wMzkwNGQ3ZGQxZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDEyMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU5ZWRlNjFlOTFkNGJkNWExZTQyZjVlYjU5ZGRkMjllYzg4M2M1MDQxYjA3NWJkOTY3NDc2NjE0NzIzZDZmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3gWZ_UdDDtN0ys5mAE7gx0D5UHNb5aA1mJ0xpA_mHpE)
> 
> What steps did you take to download fly? Did you follow this one here: https://concourse-ci.org/quick-start.html#install-fly

Yes, I installed it according to this document, but I downloaded fly not through the curl command, but directly by clicking the linux icon on the web interface. It should be the same file as the one downloaded by curl. I remember the file seems to be around 77M.
![image](https://github.com/user-attachments/assets/e8125c04-3ce0-4cd8-aad4-32c99c736a2c)

**Comment by jackyting825** [comment]
> > Yeah something went wrong with your download of fly. You can see that it's zero bytes in size. This is what I get on my system:
> > ![image](https://private-user-images.githubusercontent.com/4583837/368609066-8f1addb8-c70e-49e4-8f91-03904d7dd1f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDkyMTIsIm5iZiI6MTcyNjcwODkxMiwicGF0aCI6Ii80NTgzODM3LzM2ODYwOTA2Ni04ZjFhZGRiOC1jNzBlLTQ5ZTQtOGY5MS0wMzkwNGQ3ZGQxZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDEyMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU5ZWRlNjFlOTFkNGJkNWExZTQyZjVlYjU5ZGRkMjllYzg4M2M1MDQxYjA3NWJkOTY3NDc2NjE0NzIzZDZmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3gWZ_UdDDtN0ys5mAE7gx0D5UHNb5aA1mJ0xpA_mHpE)
> > What steps did you take to download fly? Did you follow this one here: https://concourse-ci.org/quick-start.html#install-fly
> 
> Yes, I installed it according to this document, but I downloaded fly not through the curl command, but directly by clicking the linux icon on the web interface. It should be the same file as the one downloaded by curl. I remember the file seems to be around 77M. ![image](https://private-user-images.githubusercontent.com/8901160/368806376-e8125c04-3ce0-4cd8-aad4-32c99c736a2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTAwMDEsIm5iZiI6MTcyNjcwOTcwMSwicGF0aCI6Ii84OTAxMTYwLzM2ODgwNjM3Ni1lODEyNWMwNC0zY2UwLTRjZDgtYWFkNC0zMmM5OWM3MzZhMmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDEzNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjdiNmZkYmFmNzllYzY0MjMyYTc0MmVkZWFmMGNiZGEyZmVmNmQ0MmE4MjZhNmE1NjI2MWUxYTM4ZjBlNmIxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.utY65WrJ_djYPzf14Bs4ssaKpkaY-d3FV7xh2IBf-5s)


I just re-used the command to download a fly file, the file is still around 77M. Overwrite the previously downloaded file, it seems to be OK. Thank you very much !
