### ISSUE TITLE
Concourse is not FIPS compliant

### ISSUE THREAD

**Issue by Kump3r** [concourse/concourse#9007]
## Summary

Concourse uses `md5` hashing, which is forbidden in a FIPS environment. Some major IaaS providers, like [Azure](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview#enterprise-grade-security:~:text=Azure%20Database%20for%20PostgreSQL%20flexible%20server%20uses%20the%20FIPS%20140%2D2%20validated%20cryptographic%20module%20for%20storage%20encryption%20of%20data%20at%20rest.%20Data%20are%20encrypted%2C%20including%20backups%20and%20temporary%20files%20created%20while%20running%20queries), started enabling FIPS for their PostgreSQL servers, which will break Concourses using such instances.

## Steps to reproduce

Enable FIPS on your database instance

## Expected results

Concourse works normally

#### Example error:
```
save versions: pq: could not compute MD5 hash: disabled for FIPS
```

## Additional context

A change from `md5` to `scram-sha256` would also most likely require a database migration

## Triaging info

* Concourse version: N/A
* Browser (if applicable): N/A
* Did this used to work? I am not sure if anyone ever tested it, but most likely no

**Comment by Kump3r** [comment]
Will reopen, when we gather some more information from Azure

**Comment by jsievers** [comment]
can we please re-open regardless? missing information does not mean the bug is fixed

**Comment by jsievers** [comment]
related Azure postgres announcement to remove MD5
https://learn.microsoft.com/en-us/answers/questions/2105015/postgres-flexible-server-15-8-no-longer-supports-a
