### ISSUE TITLE
concourse-7.12.0-windows-amd64.zip is empty

### ISSUE THREAD

**Issue by suzuki-shunsuke** [concourse/concourse#9018]
## Summary

https://github.com/concourse/concourse/releases/tag/v7.12.0

[concourse-7.12.0-windows-amd64.zip](https://github.com/concourse/concourse/releases/download/v7.12.0/concourse-7.12.0-windows-amd64.zip) is empty.

The file size is apparently small (170 Bytes).

<img width="934" alt="image" src="https://github.com/user-attachments/assets/73f33a60-96b8-4fb5-9939-cda445317869">

## Steps to reproduce

Download [concourse-7.12.0-windows-amd64.zip](https://github.com/concourse/concourse/releases/download/v7.12.0/concourse-7.12.0-windows-amd64.zip).

```console
$ sha256sum concourse-7.12.0-windows-amd64.zip 
fd6b8bf7f86a9bbf6ddbf1709421c0ea04ace2c110fd92bd67058f89aaddaa66  concourse-7.12.0-windows-amd64.zip

$ zipinfo concourse-7.12.0-windows-amd64.zip 
Archive:  concourse-7.12.0-windows-amd64.zip
Zip file size: 170 bytes, number of entries: 1
drwxr-xr-x  3.0 unx        0 bx stor 24-Oct-22 04:59 concourse/
1 file, 0 bytes uncompressed, 0 bytes compressed:  0.0%

$ unzip concourse-7.12.0-windows-amd64.zip 
Archive:  concourse-7.12.0-windows-amd64.zip
   creating: concourse/

$ tree concourse 
concourse

0 directories, 0 files
```

## Expected results

[concourse-7.12.0-windows-amd64.zip](https://github.com/concourse/concourse/releases/download/v7.12.0/concourse-7.12.0-windows-amd64.zip) includes an executable binary `concourse.exe`.

In case of v7.11.2:

```console
$ zipinfo concourse-7.11.2-windows-amd64.zip 
Archive:  concourse-7.11.2-windows-amd64.zip
Zip file size: 140070110 bytes, number of entries: 4
-rwx---     2.0 fat 102419968 b- defN 24-Feb-07 04:31 concourse\bin\concourse.exe
-rw----     2.0 fat 32991836 b- defN 24-Feb-07 04:18 concourse\fly-assets\fly-darwin-amd64.tgz
-rw----     2.0 fat 33026420 b- defN 24-Feb-07 04:19 concourse\fly-assets\fly-linux-amd64.tgz
-rw----     2.0 fat 32704810 b- defN 24-Feb-07 04:19 concourse\fly-assets\fly-windows-amd64.zip
4 files, 201143034 bytes uncompressed, 140069484 bytes compressed:  30.4%
```

## Actual results

[concourse-7.12.0-windows-amd64.zip](https://github.com/concourse/concourse/releases/download/v7.12.0/concourse-7.12.0-windows-amd64.zip) includes only an empty directory `concourse`.

## Additional context

- https://github.com/aquaproj/aqua-registry/pull/28127

## Triaging info

* Concourse version: v7.12.0
* Browser (if applicable):
* Did this used to work?

**Comment by suzuki-shunsuke** [comment]
I'm not sure how concourse is released.
I can't find GitHub Actions Workflows for it.

**Comment by taylorsilva** [comment]
See #8938

Had migrated to a different build script and there was a small error with how the windows artifacts were zipped up.

**Comment by taylorsilva** [comment]
I'll get around to manually zipping up a windows binary and uploading it to the release

**Comment by taylorsilva** [comment]
Windows package has been uploaded!
