### ISSUE TITLE
All resource repositories should have levelled tags that show which Concourse version they were in

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#902]
# Feature Request

## What challenge are you facing?

When inspecting the repository of one of the included resources, it would be nice to be able to know which Concourse release corresponds to which commit in the resource repo.

They also don't seem to appear in the `src/` directory as a submodule link.

## A Modest Proposal

We suggest that all official resources be tagged, at release time, with the version of Concourse they appeared in.

**Comment by chendrix** [comment]
I'm going to close this as we're instead attacking it from the other direction in concourse/concourse#1264
