### ISSUE TITLE
go build/install is failing

### ISSUE THREAD

**Issue by winkingturtle-vmw** [concourse/concourse#9023]
## Summary

When building the fly cli from master branch after bumping to apimachinery v0.31.2, it's failing with an error.

## Steps to reproduce

```
go install  github.com/concourse/concourse/fly@master

```

## Expected results

should be able to build a fly cli

## Actual results

```
../../go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/managedfields/internal/structuredmerge.go:56:4: unknown field IgnoredFields in struct literal of type merge.Updater
../../go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/managedfields/internal/structuredmerge.go:73:4: unknown field IgnoredFields in struct literal of type merge.Updater
```

## Triaging info

* Concourse version: master branch
* Browser (if applicable):
* Did this used to work? Yes (https://github.com/concourse/concourse/commit/da8e4b2c30d9fbb60a7cb789beff812260e43556)

**Comment by Kump3r** [comment]
I think [this comment](https://github.com/concourse/concourse/pull/9022#issuecomment-2454866788) explains the cause

**Comment by taylorsilva** [comment]
@Kump3r Thanks for the FYI! You are correct, I ended up running into this and investigating as well. For now I just reverted the commit that bumped to that version.
