### ISSUE TITLE
Extended information on the UI taken from jobs output

### ISSUE THREAD

**Issue by sayden** [concourse/concourse#906]
# Feature Request

## A Modest Proposal

I'd like some way to show info on the UI boxes. For example, coverage of a package, job execution time. I think it could be easily achieved by shipping a job with a 'ui-info' folder as an output that the UI can read plain text from it (and, from there, we could improve it to read markdown or HTML).

So, for example, I have a Go project that I run tests with `go test -cover` and I redirect the output to `ui-info/` like `go test -cover > ../ui-info`. On successful completion, the job could take the plain text stored in ui-info and insert it into some row in Postgres so it can be available later as a side info on each box.

I'd code myself but I'll need some help to know where to start within Concourse codebase.

Thanks!

**Comment by PurHur** [comment]
i like to extended this future request a little bit. I'd would be nice to add a 'class' or something to the box to redender some custom statuses for the latest job
