### ISSUE TITLE
Your rbx version is 3.70, but your Gemfile specified rbx 3.69 while building documentation

### ISSUE THREAD

**Issue by tetralix** [concourse/concourse#908]
Hi there!

# Bug Report

Trying to build documentation using following command: 
fly -t lite execute -x -c ci/build-docs.yml -o built-docs=/tmp/docs

I get following output
> running concourse/ci/scripts/build-docs
>  BUILT_DOCS=/tmp/build/e55deab7/built-docs
>  cd concourse/docs/
>  bundle install
> Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
> installing your bundle as root will break this application for all non-root
> users on this machine.
> **Your rbx version is 3.70, but your Gemfile specified rbx 3.69**

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): Vagrant Box
* Did this used to work? Never tried before

The reason afaik is that it stores hash bangs if you install gem with the current Ruby. During docker image build probably updated the Rubinius version, but the gems were already installed with old one.
I guess re-generate shebans during "concourse/docs-ci" image build must fix issue:
gem pristine --all --env-shebang --only-executable
Changing rbx engine_version to 3.70 also worked as temporary solution.

**Comment by vito** [comment]
should be fixed now
