### ISSUE TITLE
Sidebar remains when logged out

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#911]
Open the sidebar, log out, see the sidebar remains with the "no pipelines configured" message.

Expected: sidebar is destroyed/cleared out when logging out.

Concourse v2.5.1

![sidebar-logged-out](https://cloud.githubusercontent.com/assets/79357/22655896/80903c7e-ec46-11e6-9f11-0b2652833f23.png)

**Comment by jama-pivotal** [comment]
Closing because sidebar is gone now F
