### ISSUE TITLE
Undefined resource_types should error out

### ISSUE THREAD

**Issue by benmoss** [concourse/concourse#915]
* Concourse version: 2.6.0

We just tried `set-pipeline`-ing with a PivNet resource but forgot to add a `resource_types` section that defined it. 

```pipeline.yml
resources:
- name: a-product
  type: pivnet
  source:
    product_slug: p-concourse
```

We were able to successfully set-pipeline and then were confused for a while why it could not find any versions of our product. The resource just was empty and our build would not start without a seed version.

We eventually realized when we looked at `fly containers` that it hadn't started a check container because it didn't know what docker image to use.

**Comment by devdavidkarlsson** [comment]
Somewhat relateable to 913...
