### ISSUE TITLE
Make the git SHA available as environment variable

### ISSUE THREAD

**Issue by analytically** [concourse/concourse#916]
Useful for notifications.

**Comment by chendrix** [comment]
Hi there,

As it stands, we are probably unlikely to do this. We have a very strict philosophy on Concourse that we do not want to propagate information between steps via anything other than the filesystem. We very strongly believe that you should be using tasks to be the translation layer between your resources (which should have all relevant metadata information persisted from them) and your tasks or your puts.

I hope my explanation makes sense. We're still in the process of making a better formalization of our philosophies behind Concourse.

I'm going to close this, but feel free to continue the discussion here or on [slack](https://slack.concourse.ci)
