### ISSUE TITLE
atc should use let's encrypt to generate certs for the external domain

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#918]
Hi there!

# Feature Request

## What challenge are you facing?

Paying for SSL certs is expensive and hard -- all those credit cards and copying and pasting.

## A Modest Proposal

Let's Encrypt gives free SSL certs. Concourse should use this service for SSL certs!

**Comment by TimJones** [comment]
We use a reverse nginx proxy, and have that manage LetsEncrypt certs.

**Comment by jtarchie** [comment]
@TimJones, that's great. Concourse supports TLS from `atc`. I was looking to do it from there.

**Comment by zachgersh** [comment]
Does this just mean that the ATC would no longer require you to supply your
own certificates? Seems like a big win as you drop off an item that is
generally misconfigured and become secure by default.

**Comment by chendrix** [comment]
@zachgersh could this be something that someone writes a bosh release to do? :)

As a general rule this seems like an [duplicate-effort Anti-Pattern](https://github.com/concourse/concourse/wiki/Anti-Patterns#duplicate-effort)

**Comment by pivotal-topher-bullock** [comment]
+1 to what @chendrix said. Seems useful, but outside of the realm of what Concourse should be worrying about.  *Maybe* if there was a go library that did this magically without much effort on the ATC's part to integrate with it. Offloading this to the layer of BOSH, Docker, whatever infrastructure automation people are using is probably best.

**Comment by pivotal-topher-bullock** [comment]
Sorry @jtarchie ..

**Comment by takeyourhatoff** [comment]
Hi I have been working on a patch for this using the [golang.org/x/crypto/acme/autocert](https://golang.org/x/crypto/acme/autocert) package. The core logic is this in atccmd/command.go:

```go
var tlsConfig *tls.Config
if cmd.Autocert {
	if cmd.TLSCert != "" || cmd.TLSKey != "" {
		return nil, errors.New("cannot enable autocert if --tls-cert or --tls-key are set")
	}
	if p := cmd.ExternalURL.URL().Port(); !(p == "" || p == "443") {
		return nil, errors.New("cannot enable autocert if external port is not 443")
	}
	m := autocert.Manager{
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist(cmd.ExternalURL.URL().Hostname()),
		Client:     &acme.Client{DirectoryURL: cmd.ACMEURL.URL().String()},
	}
	tlsConfig = &tls.Config{
		GetCertificate: m.GetCertificate,
		NextProtos:     []string{"h2"},
	}
} else {
	cert, err := tls.LoadX509KeyPair(string(cmd.TLSCert), string(cmd.TLSKey))
	if err != nil {
		return nil, err
	}

	tlsConfig = &tls.Config{
		Certificates: []tls.Certificate{cert},
		NextProtos:   []string{"h2"},
	}
}
```

I have swapped my patched binary onto a running BOSH deployment and verified I can access the concourse with a valid certifcate from letsencrypt.org. The remaining work is to integrate this with the BOSH release and ensure it's adequately tested. Does this look like something you would be happy to merge?

cc @jtarchie @TimJones @zachgersh @topherbullock

**Comment by jtarchie** [comment]
@takeyourhatoff that sounds awesome. Let us have a discussion about it. We need to revisit Let's Encrypt and remember how it works. 😛

**Comment by takeyourhatoff** [comment]
The above pull request will require bumping golang.org/x/crypto in this repo.
