### ISSUE TITLE
VM stuck att error -12 out of memory and 100% cpu

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#920]
# Bug Report

VM stuck att error -12 out of memory and 100% cpu after being left alone for 5 days.

![screen shot 2017-02-13 at 09 11 40](https://cloud.githubusercontent.com/assets/2795016/22876363/a8db481a-f1d0-11e6-872b-40ad76536940.png)

Looking at the disk space used at the mac (df -h) shows no signs of running out of disk.
Restarting the VM and it is back up again.
Might seem a little bit slower on executing fly commands after resetting the vm though.

Possibly related to some memory leak issue reported earlier...

The following can also be handy:

* Concourse version: 2.6.0
* Deployment type: Docker on docker-machine on OSX, nfs.

**Comment by devdavidkarlsson** [comment]
#892

**Comment by devdavidkarlsson** [comment]
Will try the following as a temporary fix:
http://www.oracle.com/technetwork/articles/servers-storage-dev/oom-killer-1911807.html


# Configuring the OOM Killer

The OOM killer on Linux has several configuration options that allow developers some choice as to the behavior the system will exhibit when it is faced with an out-of-memory condition. These settings and choices vary depending on the environment and applications that the system has configured on it.

**Note:** It's suggested that testing and tuning be performed in a development environment before making changes on important production systems.

In some environments, when a system runs a single critical task, rebooting when a system runs into an OOM condition might be a viable option to return the system back to operational status quickly without administrator intervention. While not an optimal approach, the logic behind this is that if our application is unable to operate due to being killed by the OOM killer, then a reboot of the system will restore the application if it starts with the system at boot time. If the application is manually started by an administrator, this option is not beneficial.

The following settings will cause the system to panic and reboot in an out-of-memory condition. The sysctl commands will set this in real time, and appending the settings to sysctl.conf will allow these settings to survive reboots. The X for kernel.panic is the number of seconds before the system should be rebooted. This setting should be adjusted to meet the needs of your environment.

sysctl vm.panic_on_oom=1
sysctl kernel.panic=X
echo "vm.panic_on_oom=1" >> /etc/sysctl.conf
echo "kernel.panic=X" >> /etc/sysctl.conf

**Comment by chendrix** [comment]
@devdavidkarlsson is this still an issue?
