### ISSUE TITLE
Bug? ATC_EXTERNAL_URL unbound

### ISSUE THREAD

**Issue by flightofthunder** [concourse/concourse#921]
Hi there,

I was modifying a third party resource, [gitlab-merge-request-resource](https://github.com/swisscom/gitlab-merge-request-resource) to be specific, and as I was testing some changes, I found that the `ATC_EXTERNAL_URL` metadata variable was unbound. I am running Concourse via Docker Compose on `127.0.0.1:8080`. I ended up doing a quick workaround, but I'm not sure if this is normal, as I believe the variable should be automatically set to `127.0.0.1:8080`, no?

**Comment by SeerUK** [comment]
Hi @flightofthunder, what was the workaround you used? I'm also experiencing this issue, also running Concourse in Docker.

**Comment by flightofthunder** [comment]
It's been a while but iirc, it was simply a case of using `127.0.0.1` in `CONCOURSE_EXTERNAL_URL`. Concourse would just assign nothing rather than `127.0.0.1`.

**Comment by bcwaldon** [comment]
I encountered a similar issue, but it ended up being a lack of scheme in the value of `CONCOURSE_EXTERNAL_URL`. For example, `example.com` is what I had set, but I needed to set `http://example.com`.

**Comment by vito** [comment]
Folding into https://github.com/concourse/concourse/issues/1668
