### ISSUE TITLE
Feature request: Variadic tasks (that is, tasks with a variable number of inputs)

### ISSUE THREAD

**Issue by dsabeti** [concourse/concourse#923]
# Feature Request

## What challenge are you facing?

We're trying to build a task with an variable number of inputs. Specifically, we're trying to build tasks to do a BOSH deploy with an arbitrary number of ops files. Currently, our interface looks something like this:
```
inputs:
- name: deployment-manifest
- name: director-creds
- name: ops-files
```
But what if the ops files come from different resources? What if somebody wants to deploy without any ops files? It would be silly to create a series of tasks `deploy`, `deploy-with-one-ops-file`, `deploy-with-two-ops-files`, etc.

We have some workarounds for the time being. In this case, our task runs all ops files in the `ops-files` input. A separate task would be responsible for "centralizing" the ops files into a single input -- essentially a bunch of `cp`s. But, without support for an arbitrary number of inputs, even that task would either 
a) have a fixed number of inputs and thus be hand-crafted for this particular problem; or 
b) move precisely one file into the target `ops-files` input, and be called repeatedly for each file to centralize.

[This github issue](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/issues/2) is the origin of the feature request.

## A Modest Proposal

I'm sure there are many ways to do this, and few of them are probably any good. Here are a few strawmen to get you started:

One might be doing the variadic `...` supported by many programming languages:
```
- name: ops-files...
```

Another might be to allow for input "types":
```
- name: ops-files
  type: array # (or `variable size`, ...)
```

In both of these proposals, you'd have to work out a way for the task to access them. Subdirectories?
```
...
tree ops-files
.
├-- ops-files-0
├-- ops-files-1
├-- ops-files-2
```

Here's a weirder one: match on globs/regexes:
```
- name: *-ops-file
```
The nice thing about this approach is that you would get them all in the build directory, they'd be nicely named, and you can even create a policy for how to get your input included in the array input.

Anyway, I'm not sure about any approach. But we want to be able to generalize a few of our tasks, and an interface like this would allow us to do that.

**Comment by robdimsdale** [comment]
I found myself wanting this recently; trying to use a (non-trivial) task executable with different directories required me to create my own task yaml with different inputs but duplicating output and image resource info.
