### ISSUE TITLE
More clarity on timed out tasks

### ISSUE THREAD

**Issue by eamonryan** [concourse/concourse#924]
# Feature Request

## What challenge are you facing?

When a task times out, the UI shows the task in an error state with the red text of "Interrupted" without much more data other than the logs for the preceding steps.

This caused confusion and time wastage because it wasn't immediately obvious that the reason for the "interrupted" message was due to exceeding the configured task timeout value and not some other issue such as container worker death/hang/etc.

## A Modest Proposal

For tasks that do exceed the configured timeout value, the message should not say "Interrupted" but instead could say something much more clear such as "Task exceeded configured timeout value of: <value>"

**Comment by JohannesRudolph** [comment]
Came here after hitting the same issue. The error is really non-descript and it's probably just a 10s fix....

**Comment by joshzarrabi** [comment]
This makes sense... We are aware that there are issues with the error reporting in Concourse and we hope to get to these in the future. Feel free to submit a pr if you are confident in how to fix it.

**Comment by jama-pivotal** [comment]
Linking to https://github.com/concourse/concourse/issues/2249

**Comment by pivotal-saman-alvi** [comment]
Fixed as part of https://github.com/concourse/atc/blob/5703ea830dbaa0e88c6d5683ed52058adf41327f/exec/log_error_step.go

Timeout error now shows as `"timeout exceeded"`
