### ISSUE TITLE
Concourse not launching containers on Docker for Mac

### ISSUE THREAD

**Issue by timatooth** [concourse/concourse#927]
A few other new users have reported a similar error in Slack

```
preparing build
checking pipeline is not paused
checking job is not paused
waiting for a suitable set of input versions
checking max-in-flight is not reached
say-hello
Pulling ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950...
sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950: Pulling from library/ubuntu
8aec416115fd: Pulling fs layer
695f074e24e3: Pulling fs layer
946d6c48c2a7: Pulling fs layer
bc7277e579f0: Pulling fs layer
2508cbcde94b: Pulling fs layer
2508cbcde94b: Waiting
bc7277e579f0: Waiting
946d6c48c2a7: Verifying Checksum
946d6c48c2a7: Download complete
695f074e24e3: Download complete
2508cbcde94b: Verifying Checksum
2508cbcde94b: Download complete
bc7277e579f0: Verifying Checksum
bc7277e579f0: Download complete
8aec416115fd: Verifying Checksum
8aec416115fd: Download complete
8aec416115fd: Pull complete
695f074e24e3: Pull complete
946d6c48c2a7: Pull complete
bc7277e579f0: Pull complete
2508cbcde94b: Pull complete
Digest: sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950
Status: Downloaded newer image for ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950

Successfully pulled ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950.

docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/ce858db29abcc2eee80cd7ab8bdf46a96aa66b9c279f2993446937b01d19ae18-init: invalid argument.
See 'docker run --help'.

resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 125
```

Only known workaround is to install the older docker-machine version to run inside a VM or use Vagrant.

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): Docker Compose using the 'Native' docker for mac following the installation instructions here: https://concourse.ci/docker-repository.html
* Infrastructure/IaaS: Mac OSX 10.12; Docker version 1.13.1; docker-compose version 1.11.1, build 7c5d5e4 (Not running inside docker-machine/Docker Toolbox)
* Unsure if this previously worked on Native Docker for Mac.

**Comment by devdavidkarlsson** [comment]
docker-machine-nfs instead of just running AUFS?

**Comment by doubledgedboard** [comment]
This is likely the same issue \ highly related to: https://github.com/concourse/concourse/issues/896

**Comment by Nelyus** [comment]
For information, I have the same issue
- concourse: 2.7.0
- docker for Mac: 17.03.0-ce-mac2 (15654)

**Comment by anandu** [comment]
Workarround suggested by Nelyus works...

**Comment by chendrix** [comment]
Hi there, it appears your question has been answered. I'm going to close this now but I've tagged this with several labels so that we can reference it when we get to later stories around improving documentation and troubleshooting.

**Comment by ericis** [comment]
FYI: Workarround suggested by Nelyus worked for me on Windows 10 too
