### ISSUE TITLE
Issue with colour coding with `attempts:`

### ISSUE THREAD

**Issue by thelangley** [concourse/concourse#931]
Hi there,

We configure some jobs with `attempts: 3` which tries three times to do a thing. However, if the first attempt fails but the second is successful, the colour coding for the job still goes red.

It appears to be not doing the `on_failure:` section (which is great) so it is making the right decision that it was successful. It just appears to be the colouring is not right.

* Concourse version: 2.7.0
* Deployment type: BOSH
* Browser (if applicable): Chrome
* Did this used to work? Not sure, we've only just noticed

**Comment by chendrix** [comment]
Can you please add screenshots so we can see what you're talking about?
