### ISSUE TITLE
Metadata is missing for cached versions if used in multiple pipelines

### ISSUE THREAD

**Issue by databus23** [concourse/concourse#932]
# Feature Request

## What challenge are you facing?

I've noticed that sometimes the metadata of a cached version is missing.

Here is an example of a git-resource:
![image](https://cloud.githubusercontent.com/assets/439223/23258641/62c5257a-f9c9-11e6-95ce-c337197b9c5e.png)

I briefly brought this up on Slack and it turns out that this happens when multiple pipelines use the same versions (e.g. each has a git-resource pointing to the same repository).
What seems to happen is that one pipeline is performing the `get` step and populates the cache. Other pipelines subsequently never perform `get` for that version but use the cached version.

So while the versions are cached globally the metadata of a version seems to be cached locally by the pipeline that is populating the cache.

## A Modest Proposal

The metadata of a version should be cached globally so that every pipeline has access to it when it uses a cached version of a resource.

**Comment by joshzarrabi** [comment]
We see this and feel this pain, we will get to it in the near future hopefully.

**Comment by andrewedstrom** [comment]
@databus23 what version of concourse are you running against?

**Comment by databus23** [comment]
@andrewedstrom 2.7.4 but this was also the case with earlier versions.

**Comment by chendrix** [comment]
Even without multiple pipelines, you should be able to see the metadata for the same inputs versions.

We checked the code to figure out where this information is coming from, and even just the "same pipeline" version is going to be *hard*.

**Comment by chendrix** [comment]
This comes from ContainerFetchSource's `versioned_resource`. https://github.com/concourse/atc/blob/master/resource/container_fetch_source.go#L61-L69

The problem is that this versioned source only gets populated when performing `Initialize`. If it has already been Initialized, it doesn't set up the versioned source correctly and thus doesn't emit the correct build events.

**Comment by chendrix** [comment]
It also traces alllllllll the way back to https://github.com/concourse/atc/blob/master/dbng/build.go#L129 in the engine metadata.

@vito my thoughts are this is too hard to have prioritized so highly.

**Comment by vito** [comment]
@chendrix Can you show the trace that led there? Pretty sure it happens
dynamically, as at least the first build that fetches it doesn't have the
metadata until the fetch happens. My thinking is that the metadata can be
attached to the resource cache, which we have to find or create as part of
the `get` already.

If it does end up looking harder I agree that we should deprioritize below
the encrypting db stuff, but it's definitely annoying how broken it is
today. I ran into it all of today while babysitting the 2.7 pipeline.

**Comment by vito** [comment]
Woops didn't see the previous comments.

**Comment by vito** [comment]
Cross-referencing https://github.com/concourse/concourse/issues/534 as the new interface would also inherently fix this (metadata would come straight from `check`).

**Comment by mariash** [comment]
We decided to store metadata on a resource_cache. So in the case when fetching resource results in using resource cache we will get metadata from resource cache. We still gonna keep it on versioned resource. First, old resource versions are not gonna have resource caches. Second, it will minimize the number of DB queries when requesting resource versions with their metadata (e.g. resource page).

**Comment by mariash** [comment]
looking at logs we do pass metadata to build event:
```
{"timestamp":"1495643482.677804232","source":"atc","message":"atc.syncer.main:scheduler.tick.scheduling.try-start-next-pending-build.do.aggregate.get.finished","log_level":1,"data":{"build-id":38845,"build-name":"2598","name":"concourse","session":"17.16.341.3.31.4.5.2","version-info":{"Version":{"ref":"e41784a63e8137256f4ca17ee83c3e8aa0ed1edc"},"Metadata":[{"name":"commit","value":"e41784a63e8137256f4ca17ee83c3e8aa0ed1edc"},{"name":"author","value":"CI Bot"},{"name":"author_date","value":"2017-05-24 15:55:05 +0000"},{"name":"committer","value":"CI Bot"},{"name":"committer_date","value":"2017-05-24 15:55:05 +0000"},{"name":"branch","value":"master"},{"name":"message","value":"update docker-image-resource blob\n"}]}}}
```
but it is not saved in build event for some reason
