### ISSUE TITLE
List all workers in the cluster to the main team in fly

### ISSUE THREAD

**Issue by dmlemos** [concourse/concourse#935]
Hi there!

# Feature Request

## What challenge are you facing?
I added a new worker for a specific team and noticed I was not able to see it with `fly` when logged in on the **main team**. It took me a while to figure out that I would only see the worker when logged in to the specific team. For now it is only one worker to manage, however as the workers for specific teams increase, the pain into logging into each one of the teams will also increase.

## A Modest Proposal
The main team should be able to see all the workers in the cluster. It makes troubleshooting a lot easier for the people who’s operating concourse.

Alternatively remove the 'team' column from the output as it doesn't seem relevant.

**Comment by joshzarrabi** [comment]
Hi, this is related to #1012. Please put your suggestions there.
