### ISSUE TITLE
Running Concourse on Kubernetes

### ISSUE THREAD

**Issue by PavelPrischepa** [concourse/concourse#936]
Is there any ways to deploy Concourse (both worker and web parts) via Kubernetes?
I faced an issue https://github.com/concourse/docker-image-resource/issues/102 in Concourse+Kubernetes, so I wonder is it bug or limitation?

Thank you.

**Comment by thaniyarasu** [comment]
pre installation

install AWS CLI and setup access key,secret,region
install kops, kubectl

step 1 ) create kubernetes cluster using kops.

user@ubuntu:~$ aws s3 mb s3://my-cluster-domain.com-state-store
user@ubuntu:~$ export KOPS_STATE_STORE=s3://my-cluster-domain.com-state-store
user@ubuntu:~$ kops create cluster --node-count 3 --zones us-east-1a,us-east-1c,us-east-1d --master-zones us-east-1a --image 293135079892/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-01-31 --topology private --networking weave --node-size m4.large --master-size m4.large --kubernetes-version 1.5.2 --network-cidr 10.1.0.0/16 --associate-public-ip=false --bastion=true \
--ssh-public-key ~/.ssh/id_rsa.pub us-east-1.cluster-0.my-cluster-domain.com

user@ubuntu:~$ kubectl get nodes
user@ubuntu:~$ helm init
user@ubuntu:~$ helm install stable/concourse

follow the guides, then locate browser url at http://127.0.0.1:8080/
there you are in.

**Comment by PavelPrischepa** [comment]
@thaniyarasu Thank you!

Have you any issues with docker-image-resource put (docker push)?

**Comment by thaniyarasu** [comment]
i got this error https://github.com/concourse/concourse/issues/937
i am going to test by changing to public networking (topology: public) and let you know.

**Comment by PavelPrischepa** [comment]
Everything works Ok if Concourse Worker running in Docker container but on a host machine, not under k8s.

**Comment by thaniyarasu** [comment]
Fixed
https://github.com/concourse/concourse/issues/937

**Comment by chendrix** [comment]
Hi there, I'm going to close this as it looks like your question was resolved. Feel free to reopen or to ask on [slack](https://slack.concourse.ci) or on [stackoverflow](http://stackoverflow.com/questions/tagged/concourse%3E)
