### ISSUE TITLE
sort the pipeline list

### ISSUE THREAD

**Issue by majewsky** [concourse/concourse#940]
From the really-surprised-that-no-one-reported-this-earlier dept.: The pipeline list is unsorted (or at least, not following any discernible pattern). Our Concourse has some 50 pipelines, which makes it really hard to find stuff.

**Comment by vito** [comment]
you can drag them around to re-order them

**Comment by xulsitatirev** [comment]
@vito Hey, really? Drag and reorder? I have almost 35 pipelines at the moment?
Do you really want people to manually drag and drop things?
It's 2019. We try to do manually as little as possible.

**Comment by pivotal-jamie-klassen** [comment]
There's also `fly order-pipelines` https://github.com/concourse/concourse/blob/master/fly/commands/ordering_pipeline.go

**Comment by vito** [comment]
@xulsitatirev Could you try being less rude to the people that work on the things that you use for free? There's really no need for that. This issue was requested by someone else and closed 2 years ago. State your case in a new issue and why drag and drop (and `fly order-pipelines`) is not sufficient, and I'd be happy to take a look at it.

**Comment by xulsitatirev** [comment]
@vito  I am deeply sorry, if you took it as any kind of attack or being rude. 
Sometimes it is difficult to express the thoughts without face-to-face contact. 
I was rather surprised people you closed an issue.  Re-odering is one thing and might be useful, the other is alphabetically order pipelines over web-UI.

I will open another ticket. At the moment I am completing work over the `confile` tool, that does something similar that `helmfile` and I have added a functionality to scroll over pipelines and sort them alphabetically, but it would be useful to have it as Web UI internal.

Thank you for your work on Concourse.

**Comment by vito** [comment]
@xulsitatirev It's all good!
