### ISSUE TITLE
iptables: create-instance-chains: iptables: Index of insertion too big

### ISSUE THREAD

**Issue by wmariuss** [concourse/concourse#944]
Hi,

I'm playing with `councourse` and `fly` using your vagrant image. I create two pipelines, one with hello word and one with `go` application.
When I try to start from UI/cli a job, it's showing me an error.
Error:
`iptables: create-instance-chains: iptables: Index of insertion too big`

**Comment by chendrix** [comment]
Hi there, you may have more luck asking your question in [slack](https://slack.concourse.ci)
