### ISSUE TITLE
Top bar gets messed up if too many groups

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse#946]
Hi there

# Bug Report

The top bar does not know how to handle too many groups, we should do the same thing we do with the build numbers

![screen shot 2017-03-01 at 5 57 52 pm](https://cloud.githubusercontent.com/assets/3689026/23489728/e4c29010-fea8-11e6-9e02-cf270621061f.png)

**Comment by joshzarrabi** [comment]
Cool issue!

**Comment by B1Sandmann** [comment]
We would like to have this fixed as well. It seems https://github.com/concourse/atc/pull/174 is broken, what's missing to make this work?

**Comment by jama-pivotal** [comment]
Hi @B1Sandmann we're actually in the process of redesigning some of the groups, and in fact we're thinking of just switching completely over to tags #469 

Would you mind letting us know how many groups you typically deal with? If you can take a screenshot of what you have right now that would be helpful!

**Comment by B1Sandmann** [comment]
We're using a single pipeline for all our OS Builds and a group per distribution/OS/flavor so it gets pretty clustered as can see here. Missing in that window is the cirros group which is out of the window on the right hand side. As far as I can tell we have the only pipeline that uses so many groups, all others are either using none, 2-3 and a few use ~5-6 with short names which all fit nicely. Of course we could split the pipeline but we would rather not if we can avoid it. The tag system discussed in #469 sounds like it would also do the job and fix some issues so from my point of view there are no objections to switch from groups to tags (for us).

<img width="1435" alt="concourse_group_view" src="https://user-images.githubusercontent.com/25345569/31016776-51b94ed8-a526-11e7-9be8-31964ac68c48.png">

**Comment by joshzarrabi** [comment]
@jama-pivotal That would be cool. We really need an easy way to click around the groups or tags though.

**Comment by jama-pivotal** [comment]
Created issue #2130 with new designs to help with this. @joshzarrabi and @B1Sandmann go ahead and take a look, let us know what you think

**Comment by jama-pivotal** [comment]
Hurray we fixed this!~

**Comment by B1Sandmann** [comment]
Thanks a lot
