### ISSUE TITLE
Dragging the pipeline view ALSO opens build/resource page

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#947]
# Bug Report

Expected: If I drag the pipeline view around it won't count also as clicking to open an item.
Actual: If you click on a clickable item when dragging around your pipeline view it also opens the item under the mouse cursor.

http://imgur.com/eAOMWG0

**Comment by xtreme-gavin-enns** [comment]
observed on v 2.7.0 and 2.6.0

**Comment by jama-pivotal** [comment]
Fixed!
