### ISSUE TITLE
pipelines sidebar does not render as of 0.59.0

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#95]
![screen shot 2015-08-03 at 10 33 13 am](https://cloud.githubusercontent.com/assets/7230694/9043545/0dd273fc-39cb-11e5-8cc0-06f4c710828b.png)

It indents correctly but it contains no pipelines

I'm using chrome

**Comment by vito** [comment]
Seems to work fine for me. Try messing with adblock or checking the status
of your network requests?

**Comment by xoebus** [comment]
@vito I can't reproduce either. It happens on both machines in the office. The request is made but nothing is rendered. Adblock is disabled.

**Comment by robdimsdale** [comment]
we should check the versions of chrome - the machines that are failing are using: `44.0.2403.125 (64-bit)`

On the same machine, it works fine with safari and firefox

**Comment by xoebus** [comment]
I'm running 44.0.2403.107 but it's asking me to update.

**Comment by xoebus** [comment]
Just updated to 44.0.2403.125 and it still works.

**Comment by robdimsdale** [comment]
we just tried another 3 machines running various versions of OSX and it renders fine in chrome, firefox and safari.

**Comment by xoebus** [comment]
Does it still not work on our workstations?

**Comment by robdimsdale** [comment]
No, but we have discovered that it works fine when using incognito mode. That points to it being a plugin/extension issue.

**Comment by robdimsdale** [comment]
disabling the SEE extension (https://chrome.google.com/webstore/detail/see/dkihcccbkkakkbpikjmpnbamkgbjfdcn?hl=en) fixes the issue
