### ISSUE TITLE
Feature Request: Add JSON stdout to Fly CLI

### ISSUE THREAD

**Issue by iSynaptic** [concourse/concourse#952]
In order to better support automation, could Fly support a flag that would make all Fly responses write JSON to STDOUT? Tools like JQ could be used to easily extract information from the response and use that in downstream automation tasks, without having to resort to using grep.

Example: `fly -t target --json workers -d | {tool that reads JSON from stdin}`

**Comment by ploef** [comment]
This would a great feature and a required feature as it seems the api can no longer be accessed using basic authentication. I'm in the process of writing, my first, resource and I need to query Concourse for pipelines and jobs. I thought I could use the api for this but I just can't seem to work out how the api authorization works. An alternative would be using Fly.

**Comment by xtremerui** [comment]
what set of command needs to support this flag e.t.c workers, volumes, builds ? @jama-pivotal

**Comment by jama-pivotal** [comment]
@vito please

**Comment by jama-pivotal** [comment]
Feature is now available on `builds`, `workers`, `volumes`, `containers`, `jobs`, `pipelines`, `teams`

**Comment by nukarajusundeep** [comment]
this is not working

**Comment by nukarajusundeep** [comment]
fly -t con5 builds --json
error: unknown flag `json'

**Comment by jomsie** [comment]
Hi @nukarajusundeep, just wondering if you could give me some more details on your concourse / fly version.

I can verify it works on my 5.6.0 environment.

Thanks!

**Comment by nukarajusundeep** [comment]
@jomsie I was using concourse 3 and fly version 3 I think is the reason it did not work for me.

We have upgraded our version to concourse 5 and also fly version5 it is working for me now 

Thanks for the response
