### ISSUE TITLE
Env vars not working for docker container

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#955]
`--postgres-data-source` works, but the env var `CONCOURSE_POSTGRES_DATA_SOURCE` does not

* Concourse version: docker container, concourse/concourse:latest
* Deployment type: Docker

Works with the commandline switch passed directly.

**Comment by clarafu** [comment]
We've redone how these flags work entirely as of v2.7.2. Maybe you were setting the var with a linebreak or extra whitespace after it, which one of our drivers chokes on but that should be fixed now too. Can you try it again with our latest version of concourse?

**Comment by drahnr** [comment]
I will do so at some point this week

**Comment by drahnr** [comment]
This issue was unrelated, I would have needed to explicitly pass the ENV values to docker, which I forgot.
