### ISSUE TITLE
concourse worker container consistently fails to start, "Directory renamed before its status could be extracted" 

### ISSUE THREAD

**Issue by markmark206** [concourse/concourse#956]
# Bug Report

Starting concourse in containers fails -- concourse worker exits with an error.

Details:

I setup a fresh instance of concourse (AWS instance of Ubuntu 16.04 server, current [as of this morning] docker-ce / docker-compose, using docker-compose.yml from https://concourse.ci/docker-repository.html, concourse keys generated).

Most of the time, running `docker-compose up` causes concourse worker to quickly exit with an error:

```
concourse-worker_1  | {"timestamp":"1488922689.021008015","source":"worker","message":"worker.garden.extract-resources.extract.failed-to-extract-resource","log_level":2,"data":{"error":"exit status 2","output":"/worker-state/2.7.0/linux/bin/tar: usr/sbin: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: usr/lib: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: usr/bin: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: sbin: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: etc/ssl/certs: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: etc/ssl: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: etc: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: dev: Directory renamed before its status could be extracted\n/worker-state/2.7.0/linux/bin/tar: Exiting with failure status due to previous errors\n","resource-type":"s3","session":"1.2.11"}}
concourse-worker_1  | {"timestamp":"1488922689.021169186","source":"worker","message":"worker.garden.extract-resources.failed-to-extract-resource","log_level":2,"data":{"error":"exit status 2","session":"1.2"}}
```

If I try running `docker-compose up` enough times, concourse worker might actually start successfully, and things work.

I wanted to check if this was somehow an intermittent problem, specific to that instance, so I setup another AWS instance from scratch (same steps), and I am seeing the same problem.

* Concourse version:
   Whatever is currently in dockerhub (i am using https://concourse.ci/docker-repository.html)
* Deployment type (BOSH/Docker/binary):
   Docker
* Infrastructure/IaaS:
   AWS
* Browser (if applicable):
   N/A
* Did this used to work?
  Yes, I setup a number of concourse instances running in aws, using https://concourse.ci/docker-repository.html, without problems.

**Comment by occelebi** [comment]
I hit that as well. You need to change to aufs instead of overlay. Currently they have a bug in overlayfs implementation I guess.

**Comment by kevinzurek** [comment]
I am currently experiencing the same issue in AWS after including my SSL cert/key in the docker-compose.yml file.

**Comment by Sharor** [comment]
We have this issue as well, @occelebi how do you go about doing this ? Wouldnt that require rebuilding the docker image resource?

**Comment by occelebi** [comment]
@Sharor as long as you are using AUFS as docker storage driver it should be fine I guess.

**Comment by clarafu** [comment]
Sounds like this is an issue upstream, possibly in `overlay`? I don't think there's much we can do about this. :(
