### ISSUE TITLE
Concourse binary worker on OSX extremely slow for building iOS

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#959]
## What challenge are you facing?

The concourse binary worker 2.7.0 is extremely slow on OSX, a simple iOS build takes **2hours** or more for me!

**Is it limited by the garden containerisation?
Is the filesystem not mounted correctly (This reminds me of issues I had with docker when not mounting using NFS).**

Running a build for test on the iOS simulator goes acceptably quick.
Building a release version for iOS, totally cumbersomely slow. :'(

# Bug Report

The following can also be handy:

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): binary worker - Darwin, docker based ATC
* Infrastructure/IaaS: real hardware, mac mini's
* Browser (if applicable): negative
* Did this used to work? Never built a release version before.

**Comment by chendrix** [comment]
In regards to mounting the filesystem, the "garden server" used by the OSX workers is actually an instance of https://github.com/vito/houdini which is a fake containerization solution.

**Comment by devdavidkarlsson** [comment]
**Step one:**

`$ security list-keychains -d user
`
Probably should not contain duplicates. If it does, clean up the com.apple.security.plist:
`$ open ~/Library/Preferences/com.apple.security.plist
`
