### ISSUE TITLE
How can run a remote script?

### ISSUE THREAD

**Issue by xwjdsh** [concourse/concourse#961]
Hi!

Now i got a binary file from build plan, and need update program on server.
I found [rsync-resource](https://github.com/mrsixw/concourse-rsync-resource]) can instead `scp` command.
How can run a remote script like `ssh -p $port $user@$p 'cmd'`? (except modify docker image) 

Thanks!

**Comment by devdavidkarlsson** [comment]
- You can run a docker image with ssh in it and run ssh from the task.
- You could write your own SSH resource.

Do you really need to SSH out from concourse?
