### ISSUE TITLE
UX: Command line parameter names are different on Windows, making it jarring cross-platform 

### ISSUE THREAD

**Issue by petemounce** [concourse/concourse#962]
# Bug Report

On Windows, the parameter names for fly and concourse use the `/` prefix instead of the `-` that nix systems use.

Example:
```
λ  .\fly.exe --help
error: Usage:
  C:\Users\Pete\concourse\fly.exe [OPTIONS] <command>

Application Options:
  /t, /target:               Concourse target name
  /v, /version               Print the version of Fly and exit
      /print-table-headers   Print table headers even for redirected output
```

This means that for any scripts that I want to write to manage pipelines and so forth, I need to account for this.

## 🎉 How was I able to work around this?

It turns out that the binaries recognise the `-` flag prefix form fine.

## I would modestly propose that

... the help text be changed to show the `-` variants of the flags rather than the `/` variants because:

* this makes them more in-line with how powershell takes flags - it uses single-`-` prefix then starts-with matching (which I realise isn't the _same_ but it's closer to that)
* MS are intending to deprecate `cmd`, which is where `/` comes from (I believe)
* powershell supports `/` as a filesystem separator, so potential collisions during typos
* People (like me!) maintaining cross-platform build scripts won't have to either
  0. account for the difference because we didn't try out both forms
  0. be confused by the usage docs

## The following can also be handy:

* Concourse version:
  * 2.7.1
* Deployment type (BOSH/Docker/binary):
  * binary
* Infrastructure/IaaS:
  * n/a
* Browser (if applicable):
  * n/a
* Did this used to work?
  * n/a

**Comment by vito** [comment]
This is actually in our `go-flags` dependency, but it looks like this change will make it so we can undo it:

https://github.com/jessevdk/go-flags/commit/d2c1a5901680487f9205cb3b8b4b0a73a8ff46df

We'd have to change how we build `fly` in our pipeline.
