### ISSUE TITLE
fly execute should cache an input if it is unchanged since last time

### ISSUE THREAD

**Issue by petemounce** [concourse/concourse#963]
# Feature Request

## What challenge are you facing?

I have a repository that's a couple of GB. If I run `fly execute` on it, then that's tar'd and pushed per invoke. This takes some time.

## A Modest Proposal

It would be nice if, instead, `fly execute` could skip long parts of this if nothing has changed.

This can be the case if I'm trying out different tasks one by one.

## The following can also be handy:

* Platform:
  * Windows 10 (with linux subsystem installed)
* Concourse version: 
  * `2.7.1`
* Deployment type (BOSH/Docker/binary): 
  * `binary`
* Infrastructure/IaaS: 
  * n/a
* Browser (if applicable): 
  * n/a
* Did this used to work? 
  * 2.7.0 is earliest version tried.

**Comment by vito** [comment]
This could fit pretty well with our existing resource caching model, by having `fly` compute a sha-256 of the contents and specifying that as the archive version. We would then just need to define the garbage collection for caching of one-off build resources.

**Comment by vito** [comment]
Note: this isn't really easy anymore since inputs/outputs no longer use the `archive` resource. We would have to define our own lifecycle and caching semantics for these volumes.

**Comment by pivotal-jamie-klassen** [comment]
Probably related to #2826, might need some kind of additional "checksum" feature on the API side?
