### ISSUE TITLE
fly execute /i:name=value on Windows will fail when tar is not in PATH

### ISSUE THREAD

**Issue by petemounce** [concourse/concourse#964]
# Bug Report

## What was I trying to do?

Run a build locally via `fly execute`.

If I have a Windows computer and I don't have `tar` present in my PATH, `fly execute .../i:name=value` fails.

```
C:\src\s\iw\everythingPS>C:\users\pete\concourse\fly.exe /t lite execute /config:.\ci\concourse\build-test-publish\btp-windows.task.yml /input:everything=.
executing build 6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
12.168.100.4:008080/api/v1/pipes/ 1542M    5940ccb2-eb4d-4181-547c-e56c9ebfc39e:0  1GetFileAttributesEx C:\src\s\iw\everything\Fabric\Scala\fabri5c42M\target\scala-2.11\classes\improbable\bridge\subscription\Radi    0  alChunkInterestRegionCalculator$$anonfun$i mprobable$bridge$subscription$RadialChun  0  15.1M      0kInterestRegionCalcul --:--:--  0:01:42 --:--:-- 14.2M
ator$$findPointsWithinRadius$1$$anonfun$apply$1.class: The system cannot find the path specified.
initializing
no workers satisfying: platform 'windows'

available workers:
  - platform 'linux'
errored
```

## What did I expect?

Flawless execution of my build! :)

It would be great to - before shelling out to a tool that is depended on - try executing that tool and if that fails, yielding back an error message like `blah is not present on your PATH; please install it`.

## 🤞 😢 How did I work around this?

(This didn't work)
I have an msys2 install, which is in my PATH (`c:\tools\msys64\usr\bin`), so I ran
```shell
pacman -S tar
```
to install the tar.exe binary. 

I think the dependency site is https://github.com/concourse/go-archive/blob/master/tgzfs/compress.go.

## Any other business:

For fun, the tar binary is also vendored into the following common development tool packages for Windows:
* git
* chef development kit
* linux subsystem

* Platform:
  * Windows 10 (with linux subsystem installed)
* Concourse version: 
  * `2.7.1`
* Deployment type (BOSH/Docker/binary): 
  * `binary`
* Infrastructure/IaaS: 
  * n/a
* Browser (if applicable): 
  * n/a
* Did this used to work? 
  * Didn't work in 2.6.x either, no idea before then.

**Comment by petemounce** [comment]
Actually, I don't think this is a tar problem, now, I think this is a Windows-doesn't-support-long-paths-without-inflicting-pain problem.

**Comment by vito** [comment]
Yeah that sounds more likely. When `tar` is unavailable we fall back on a native Go implementation.
