### ISSUE TITLE
Attempting to run a job in a paused pipeline gives unhelpful logs

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#97]
Trying to run a job in a paused pipeline gives very generic logs, below:

```
{"timestamp":"1438627237.202865601","source":"atc","message":"atc.trigger-build.triggering","log_level":0,"data":{"job":"job-with-hooks","session":"11"}}
{"timestamp":"1438627237.210858822","source":"atc","message":"atc.db.build-did-not-schedule","log_level":0,"data":{"buildID":"\u0003","reason":"pipeline-paused","session":"2"}}
{"timestamp":"1438627237.210936546","source":"atc","message":"atc.trigger-build.trigger-immediately.build-could-not-be-scheduled","log_level":0,"data":{"build":3,"job":"job-with-hooks","session":"11.1"}}
```

We should say something like `job cannot be scheduled as pipeline is paused`

**Comment by xoebus** [comment]
Lager promotes using more machine parse-able strings so that the logs can be used for more interesting trace tasks. That said we can switch the `reason` attribute to be more user friendly.

**Comment by vito** [comment]
We shouldn't start to mix up human readable and machine readable in our logs. I much prefer to have small greppable keywords/phrases than human readable messages.
