### ISSUE TITLE
Difficulty debugging build failures on Windows that appear to be concourse errors

### ISSUE THREAD

**Issue by petemounce** [concourse/concourse#972]
# Bug Report

In #967 (where I also came across #966), I had an error that looked like a concourse application-level error. I basically see 
<img width="431" alt="concourse-doesnt-give-much-away" src="https://cloud.githubusercontent.com/assets/69720/23960348/aa46305c-099f-11e7-9590-9ecc113161ef.PNG">
and then I
* didn't have a stack trace to go on to confirm that it was a concourse-web issue vs a my-side build issue
* didn't have the operation's input to see whether it looked legit
* didn't see anything relating to that text in the worker's stdout (the worker is running on my workstation)
* didn't understand very much about the worker's work directory to go looking in it, though I found I think the `input` that that task takes - no worker logs or similar
* didn't know where to find server-side logs
  * ... or how to interpret them (they look structured, which is _great_, but I didn't find docs that for example told me what each event meant)

I'm using the concourse-in-a-vagrant-box option for the time being.

I'm happy to PR into your docs to try to address some of this, but I'd ask for a steer, since it would be adding new content and therefore I'd like to know where you might want it to live (or, better, give me stubs that I can add to?).

**Comment by ddadlani** [comment]
is this issue still occurring?

**Comment by petemounce** [comment]
You would need to try to reproduce it. Based on the lack of engagement I got from filling issues that had reproduction recipes at the time, our trial with concourse was abandoned.

**Comment by ddadlani** [comment]
Hi @petemounce, I'm sorry you feel that way. We are always trying to improve our community engagement here at Concourse and we welcome feedback on ways we can improve.

For this issue, I'm going to remove it from the Runtime icebox for now. If anyone comes across this in the future, please do let us know and we will re-prioritize it.
