### ISSUE TITLE
Generic skip `get` for the `put` step

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#974]
please reconsider your position about #837

I do not have so much more to add, except that all the arguments about not having this are more of the type -- this is not so bad at it seems -- but the fact is that it is. 

An option to allow to drop this extra step for scenarios that do not need it is a rational, backward compatible, learning zero for people that do not care for the feature, and extremely simple to implement and test.

Scenarios that will benefit from it:

- Resource put at the end of the job (or that are not going to be used for the same job). This is extremely common a job to finish with a put of resource preparing it for one or likely many other jobs that follow in the pipeline. Having multiple workers and jobs that depend on multiple resources, makes the cache mechanisms ineffective to repay the pointless get price.

- Resources with side effect puts that do not change the resource data. This probably was not the case in the beginning but currently, there are many such examples - the most often used one: pull-request. The ability to change the check status with a put operation is an example of that. Following get operation is pointless and despite the assurance that the resource will be fastly obtained from the cache in reality that's very often not true - forcing the job to obtain the resource 2 or 3 times instead of once. For git repo with 12000 commits, that's a lot of extra traffic.

Forking and adding such feature to every resource - one by one - is a very unserious suggestion and I am very disappointed that I heard that from the concourse team. Especially after my pull requests are unscheduled for review for months - despite multiple requests for them from the community.

**Comment by joshzarrabi** [comment]
We really don't want to do this... It will almost certainly confuse newer concourse users who will expect resources to be available in later tasks in the same job.

**Comment by kdvolder** [comment]
> We really don't want to do this... It will almost certainly confuse newer concourse users who will expect resources to be available in later tasks in the same job.

Fair enough... but what if there are no later tasks? Maybe concourse should simply be smart enough to avoid needless gets in that case. Seriously pulling down megabytes of gigabytes of data you don't need for anything is kind dumb really.

**Comment by vito** [comment]
We were planning to address this as part of concourse/rfcs#1 - by making the `get` opt-in (not opt-out). That RFC is on the way out and its replacement (concourse/rfcs#24) doesn't mention it (yet?), so I'll just re-open this to explicitly keep track of it.

**Comment by vito** [comment]
Woops just noticed I'm already tracking this as https://github.com/concourse/concourse/issues/3299
