### ISSUE TITLE
No dockerfile for concourse/concourse

### ISSUE THREAD

**Issue by gerrickw** [concourse/concourse#975]
Summary:
Currently at https://hub.docker.com/r/concourse/concourse/ there is no reference to the dockerfile, nor concourse/*.  There is https://github.com/concourse/concourse-docker that is a wrapper for pulling concourse/concourse.  What is used to build your containers?  Seems like a simple thing to throw up as probably part of your build process or I am having trouble finding it within your repos.   

I usually expect most of the popular repos to have the linked dockerfile file, so was surprised to see after 1+ million pulls no link existed.

**Comment by gerrickw** [comment]
Learned through slack this isn't a wrapper, but there are inputs within concourse-docker git repo that are assumed inputs.  I am wondering if it would be better to have those inputs pulled than assumed they exist.  This would make it easier for people to build the container than having to go through the whole concourse build pipeline to get the artifacts they desire. 

It also seems this would be easier to troubleshoot issues as they occur.

**Comment by chendrix** [comment]
The docker image is provided as-is and we do not support people building the docker image from scratch.

This seems like a nice-to-have but one that we are unlikely to ever get to.
