### ISSUE TITLE
Support AWS IAM roles for all AWS services

### ISSUE THREAD

**Issue by willejs** [concourse/concourse#976]
# Feature Request

## What challenge are you facing?

I am deploying concourse in AWS, on top of ECS. I am using instance roles, and task roles to give instances and tasks permission to use AWS resources. As you know, AWS's best practice is to use IAM roles/Instance profiles at all times to carry out operations against their API. Whilst the Docker-image resource supports that, as it uses the ecr-credential helper and aws sdk underneath, other resources such as S3, and semver do not. Right now, I dont want to put my AWS credentials in plain text into the DB, or have them put in a credentials.yml and templated at build time.

## A Modest Proposal

Enabling the use of instance profiles/IAM roles is simple and just relies on us not setting them when configuring the aws sdk, and optional in the resource config. I think this is ok, until secret management is sorted in the next epic? I understand that people want simple json inputs into a resource, and no other 'magical' things happening, but I also thing that enabling this for now isnt the end of the world.

**Comment by sbkg0002** [comment]
+1!

**Comment by ClaraFuPivotal** [comment]
We have an upcoming epic involving integration with vault and an earlier story to encrypt any pipeline config (or anything that might contain credentials) in our backlog so those might solve your problem with plaintext in the database. https://www.pivotaltracker.com/story/show/143418287

**Comment by willejs** [comment]
@clarafu Im totally on board with that, if the backend is pluggable. KMS & IAM should be sufficient for AWS right?

**Comment by mariash** [comment]
I am re-openning this issue for now. There are several problems with this proposal:

1) resource configuration should be independent from your IAAS configuration. That means you should be able to easily migrate your pipeline. In case if you change IAAS you will have to change your resource configuration. For example, if you migrate your pipeline from AWS to GCP you can still use the same s3-resource configuration if it is based on credentials. If you relied on IAM roles you'll have to change how you access your resource now.

2) IAM profiles will require workers to have state. Which goes against Concourse idea that workers are ephemeral and can be easily recreated.

3) From security standpoint this is also not a good idea. If worker has access to a resource that means every job that is running on that worker can have access. Especially this is dangerous in multi-tenancy environment. In that case different teams are not protected from each other and some team can get access to another team's resource. If it is not meant to be public then it should be properly protected on a team level.

4) Requiring this across all resources will be a contributor burden. If we are trying to make consistency in this behavior then that would be expectation from all resources.

5) Concourse team is currently working on Vault integration. In particular AWS integration https://www.vaultproject.io/docs/secrets/aws/ will allow to securely generate short-lived credentials on fly and not store them in database. This is the solution that we would prefer and encourage users to follow. We are going to investigate if this will be a valid solution. Until then we will keep this issue open.

**Comment by willejs** [comment]
@mariash I agree with all your points. 
Implementing vault support and using STS credentials would be ideal, this is what i have been waiting for for over a year. I hope this drops soon, and we can start using it, however, it will add more overhead to peoples setups, and complexity.

In the mean time, I have forked and patched providers to use IAM instance profiles and ECS task roles which works, but isn't ideal, as the above. Using tags to run tasks on workers with the correct IAM roles does not seem too crazy in the mean time, whilst is a bit 'magical' and goes against the concourse philosophy, its practical, and more secure than putting AWS credentials into the pipeline config!

**Comment by ringods** [comment]
@mariash out of interest: 
* which component of Concourse will call into Vault and retrieve these short-lived credentials?
* how will that Concourse component authenticate to Vault as a valid client? Currently, I use the Vault AWS Auth backend to make sure that scripts on a certain EC2 instance are valid, but that breaks again your statement that `resource configuration should be independent from your IAAS configuration`.

**Comment by mariash** [comment]
@ringods the ATC will be making requests to Vault (or any other credential provider, e.g. Credhub in future). Pipeline yaml will be saved as is with credential references in database and ATC will populate those references with values from Vault right before running the build. 

ATC will be configured with Vault read token to prefixed namespace. Individual pipelines will have credentials in namespace of `/team/pipeline`. And vault can be separately configured with namespaces read/write access for individual teams. So that basically means Vault configuration is going to be set up in your concourse installation which is specific to IAAS and not in pipeline yaml.

Please read more about Vault or if you have questions/suggestions here: https://github.com/concourse/concourse/issues/291

**Comment by willejs** [comment]
Now vault is implemented i am going to close this.
