### ISSUE TITLE
Question: Resource design issue around storing state

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#977]
Hi all,

Running into a design challenge with the [Terraform Resource](https://github.com/ljfranklin/terraform-resource) and was hoping for some extra eyes. Up to this point, the resource has stored all state files in S3. This enables `check` to see new versions by checking the LastModified time on the files. The timestamp as a version detect mechanism is maybe not ideal but works okay.

However, Terraform 0.9 added support for [state file backends](https://www.terraform.io/docs/backends/config.html). With this change, you now specify where to store the state file directly in your Terraform configuration files. While it would be nice to delegate storing state to Terraform as it supports several different backends (e.g. S3, Azure, Consul), I'm having trouble figuring out how to make this work with `check`. Normally the user uses the `git` resource or similar to fetch the Terraform config files prior to a `put` to the Terraform resource. If all versions come from `put` this works fine, but seems like Concourse is moving towards all versions [coming from check](https://github.com/concourse/concourse/issues/534). Seems a bit awkward to have the `check` fetching all those same git repos in order to know which backend is in use.

I realize this question is pretty Terraform specific, but any ideas are appreciated!

**Comment by Seraf** [comment]
Hello, any news on this topic ?

**Comment by chendrix** [comment]
@ljfranklin have you looked at the way that the https://github.com/concourse/semver-resource exposes what look like "drivers"?

**Comment by ljfranklin** [comment]
@chendrix gonna close this out as I didn't explain my question well. Question wasn't about the name of the parameters, it was around how Concourse assumes resources manage their own state and `check` should always know how to check for new versions. If I delegate state storage to Terraform rather than handling it directly, `check` will no longer be able to detect new versions. Honestly I don't mind if `check` is just a no-op, but the discussion [here](https://github.com/concourse/concourse/issues/534) made it seem like **all** versions would soon need to be generated by `check`. I'll add my thoughts there and close this out.
