### ISSUE TITLE
Docs: step missing from "Local VM with Vagrant" / "Hello, world!"

### ISSUE THREAD

**Issue by jfirebaugh** [concourse/concourse#978]
I got briefly stuck in the ["Local VM with Vagrant"](https://concourse.ci/single-page.html#setting-up) and ["Hello, world!"](https://concourse.ci/single-page.html#setting-up) tutorial flow. At the point where the latter section says "If you refresh the main page, you should now see the world's tiniest pipeline!", I did so, and didn't see any change.

The solution, apparently, was to log in to the "main" team. A necessary step like this should be explicitly spelled out in the documentation (or the default behavior for a Local VM install should be to auto-log-in).

* Concourse version: v2.7.0

**Comment by jama-pivotal** [comment]
Closing because Vagrant is no longer supported for single-vm deployment
