### ISSUE TITLE
Can't scroll table of contents on single-page docs

### ISSUE THREAD

**Issue by jfirebaugh** [concourse/concourse#979]
When I view https://concourse.ci/single-page.html on a 1920x1080 monitor, the sidebar is cut off at the top of the "Implementing a Resource" section and does not scroll either independently or with the main body of the page:

![image](https://cloud.githubusercontent.com/assets/98601/24171875/5c83bac6-0e43-11e7-940b-41d09ea4cf35.png)

Expected behavior is that there's some way to view the entire table of contents, such that I can access a link to any section regardless of my current position in the documentation.

**Comment by jama-pivotal** [comment]
closing, because we removed the single page version of the docs in the latest version of the docs
