### ISSUE TITLE
Failed subtask did not fail build

### ISSUE THREAD

**Issue by wcamarao** [concourse/concourse#98]
The [deploy task failed](https://main.bosh-ci.cf-app.com/pipelines/vsphere-cpi/jobs/deploy-ubuntu-manual/builds/88), yet the build was marked green

![screen shot 2015-08-03 at 4 22 51 pm](https://cloud.githubusercontent.com/assets/777396/9049865/c4176a34-39fb-11e5-897b-5c7ed0c6894a.png)

cc: @calebamiles

**Comment by xoebus** [comment]
@calebamiles @wcamarao Thanks for reporting this! Could you post an anonymized version of the plan YAML for that job?

**Comment by xoebus** [comment]
Pipeline was using `conditions: [success, failure]` which un-intuitively masks the result of the step above. Switching to the new hooks (i.e. [ensure](http://concourse.ci/ensure-step.html) in this case) will make this work and be easier to reason about.

**Comment by xoebus** [comment]
@wcamarao @calebamiles As above, switching to hooks will make everything better here. We're going to be removing conditionals in the next release.
