### ISSUE TITLE
Authenticate using Github personal access token

### ISSUE THREAD

**Issue by crstamps2** [concourse/concourse#982]
# Feature Request

## What challenge are you facing?

I am trying to start spinning up pipelines based on a new branch name (using this tool https://github.com/pivotaltracker/concourse-branch-manager). My Github instance is an enterprise github. My Concourse instance has a enterprise governance restriction that the only users to access concourse are those that authenticate via Github OAuth. 

When a script runs to login using `fly -t example login`, it gets to the prompt screen to either navigate to a URL (which then proceeds to make you login to GHE for authentication) or manually enter the token (if callbacks are not enabled). 

This is really hard to achieve programatically.

## A Modest Proposal

I believe a viable solution for those instances where the basic auth is turned off but Github OAuth is  enabled is to leverage Github's Personal Access Token. 

For instance I should be able to login using `fly -t example login -u [username] -p [access_token]` and the behind the scene piece essentially curls as described in this Github article: https://developer.github.com/v3/auth/

**Comment by billimek** [comment]
May be related to https://github.com/concourse/atc/issues/42

**Comment by vito** [comment]
I don't think think https://github.com/concourse/atc/issues/42 is related. This is just for logging in to a team with GitHub auth configured, but being able to provide a personal access token, rather than the web UI oAuth flow.

**Comment by crstamps2** [comment]
@vito that's right. So instead of authing with the ui, I would like auth from fly and my -p is a personal access token. Make sense?

**Comment by crstamps2** [comment]
I believe this is completed as of today's 3.4.0 release, yeah?

**Comment by myles-mcdonnell** [comment]
I'm running 3.8.0 and this doesn't seem to be working for me?

**Comment by vito** [comment]
This feature was removed due to security concerns. Sorry.

If we want something like this again it'll probably be by having the ATC itself grant its own tokens.

**Comment by myles-mcdonnell** [comment]
np.  Maybe there is another solution for my use case.  So I want to run a pipeline that sets other pipelines.  The other pipelines are all in teams secured by OAuth.

**Comment by billimek** [comment]
We face the same issue and 'get around' it now by creating a special concourse team secured with basic auth.  It's a clunky solution and we feel dirty doing it, but we have not found a better approach yet.

**Comment by brownjohnf** [comment]
@vito What is the suggested approach for connecting to concourse from within a concourse job? We want to run jobs in concourse that interact with concourse itself. I don't want to create a separate team for this, because we need members of the existing team to be accessing/maintaining these jobs, and we're using Github OAuth already.
