### ISSUE TITLE
Additional state "waiting" for manually triggered jobs with new available resources

### ISSUE THREAD

**Issue by mraidel** [concourse/concourse#983]
# Feature Request

## The challenge

I have a pipeline with manual steps (for example staging test) and currently when there is a new pipeline run and it has finished the job before the manual one everyhing is green again. By looking at the pipeline there is no visual clue that there is something in progress (and that I would have to trigger a job manually to proceed). This requires additional communication and reminders which wouldn't be necessary if the pipeline communicated that there is a job waiting to be triggered.

## The proposal

I would propose a color/indicator for "waiting" (job with new resource input waiting for a manual trigger) which flashes just like pending or started, just with another color.

**Comment by joshzarrabi** [comment]
This is an interesting idea, but I doubt we will get to it in a reasonable time frame...
