### ISSUE TITLE
Changing Paused Pending jobs to have a static halo

### ISSUE THREAD

**Issue by professor** [concourse/concourse#987]
# Feature Request

## What challenge are you facing?

I find that the visual display for the dashboard provides misinformation at first glance. In particular, a Paused Pending job has the active halo icon and appears to be doing something, when it is not: it is just waiting. A static halo (much like failed) would better communicate what is happening. 

The legend does not help me figure this out. Each item in the legend appears to be a separate state, so I would expect to see a blue box with a gray active halo to show paused pending. 

## A Modest Proposal

I suggest that we replace the active / pulsating halo with a static halo for Paused Pending jobs.

**Comment by professor** [comment]
These are notes in progress....

The html g tag has the attributes "node job paused pending"
We want this to act like "node job failed" 

What does the "started-ripples" on pending, and make it act like failed.

In the legend, the dt.pending tag has this styling:

dt.pending{-webkit-animation:small-pending-ripple-concourse 1s linear infinite;animation:small-pending-ripple-concourse 1s linear infinite}
dt.failed{box-shadow:0 0 0 2px #273747,0 0 0 5px rgba(231,76,60,.7)}

The pipeline-svg.css says that .job.node.started .animation has started-rippling

How is it that pending is getting the started-rippling animation?

**Comment by joshzarrabi** [comment]
Issue #1008 seems to be a good place to aggregate these types of complaints, maybe we should just get rid of the flashing thing all together? @vito?

**Comment by professor** [comment]
We're thinking of working on improving the animation speed and removing the paused halo for hack day...

The css is coming from:
https://github.com/concourse/atc/blob/bdf157188a51beadc069e6f0c286769eca8438e3/web/assets/css/colors.less

**Comment by d** [comment]
![fix to legend and cpu utilization of halos](https://user-images.githubusercontent.com/440892/27978679-c2944164-6325-11e7-80ed-193bc23decd0.png)
