### ISSUE TITLE
Visual Indication of failed Pipelines in the Sidebar

### ISSUE THREAD

**Issue by Rukenshia** [concourse/concourse#988]
# Feature Request

## What challenge are you facing?

We start to have a bigger number of pipelines and would like to have the ability to see if any pipeline has failed without having to click through everything.

## A Modest Proposal

Add a small red box to the sidebar that have currently failed jobs. Maybe this would even be useful for started pipelines, but I would very much appreciate just seeing whether any pipeline failed.

**Comment by joshzarrabi** [comment]
Hi, check out this third party tool, it might be useful. https://github.com/dgodd/concourse-summary
