### ISSUE TITLE
more info on the resource page

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#990]
# Feature Request

## What challenge are you facing?

When the resource does not have the default 1m check interval, but longer - say 24h it becomes unfriendly that there is no place where such info can be seen.

## A Modest Proposal

An info section in the resource page that includes information Check interval; Last checked at.

Of course, if you would like you can get a bit crazier and provide more details:  Check interval; Last successful check; last failed check; Next check in, ratio success/failing; avg time taking for check ... etc.

**Comment by joshzarrabi** [comment]
Cool idea... feel free to submit a pr if you want.
