### ISSUE TITLE
96 jobs make browsers unusably slow

### ISSUE THREAD

**Issue by gerhard** [concourse/concourse#991]
With 96 jobs, our pipeline is stalling both Chrome & Firefox, it's completely unusable.

I attempted to get some performance graphs, but the entire browser process would just stop responding. I don't know how else to troubleshoot this. Are we the only ones seeing terrible UI performance from pipelines with over 50 jobs?

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome 56 & Firefox 51

cc @michaelklishin @dumbbell

**Comment by ahelal** [comment]
We are facing the same issue after upgrade. Initial load of UI is much slower and performance is slower.
It takes up to 15 seconds to load a Pipeline if it has many jobs. The issue appears with firefox, chrome and Safari.

**Comment by michaelklishin** [comment]
In case you need an example to reproduce, try [this RabbitMQ pipeline](https://ci-aws.rabbitmq.com/teams/main/pipelines/server-release:v3.6.x?groups=QA). I'm not sure if 100% of it is public but even if not, it takes 30-40 seconds to load that page for me in Chrome and some report crashing tabs.

**Comment by vito** [comment]
@ahelal After an upgrade from which version?

**Comment by ahelal** [comment]
@vito Sorry after further investigation we discovered it is a DB issue

**Comment by michaelklishin** [comment]
This is a major issue for RabbitMQ, to the point that the UI sometimes is completely unusable.
It has been going on for more or less the entire time we've been using Concourse, which is over 6 months now.

**Comment by pivotal-lyle-murphy** [comment]
@michaelklishin we have seen this on a few teams with many pipelines, it is something we, the Concourse team are working on addressing, but is a much more difficult problem than we thought. Looking to find a solution in the future, but for for now, you can use an alternative summary UI, found here: https://github.com/dgodd/concourse-summary

This will allow you to [generate a summary UI like this](https://concourse-summary-crystal.cfapps.io/host/ci-aws.rabbitmq.com/teams/main/pipelines/server-release:v3.6.x?groups=QA), that you can click into each pipeline when needed, hope this helps for now.

**Comment by michaelklishin** [comment]
We are aware of Concourse Summary and tried it. It is not a Concourse UI replacement, at least for our team.

**Comment by michaelklishin** [comment]
Our team recently upgraded to Concourse 4.1 where dashboard is the new home page. This is an improvement in terms of home page rendering which has usability choices which should not be discussed in this issue.

The CPU burn is still very bad: over 1 core completely utilized (120-125%) of the CPU used at all times, 45 Avg. Energy Impact reported by MacOS Activity Monitor with just one Firefox 62 tab running a large Concourse pipeline with jobs in progress and a tab I'm typing this issue in.

@jama-pivotal may I ask why this was moved into the icebox? Concourse UI is still far from being a speed demon and energy consumption of just 1 tab with 1 pipeline makes it prohibitively power hungry to use while working on battery power.

**Comment by michaelklishin** [comment]
I see some specific improvements (namely event batching in UI code) have been implemented as of https://github.com/concourse/concourse/issues/1543#issuecomment-398188077 and https://github.com/concourse/concourse/issues/1543#issuecomment-400361619 concludes that those improvements are sufficient for now (5s vs. 28s for some workloads).

@gerhard combined with job grouping changes in RabbitMQ's main pipelines, should we close this? At least the "browser stops responding" part seems to be resolved 🤷‍♂️ .

**Comment by vito** [comment]
@michaelklishin FWIW, I don't think we're going to spend any more effort optimizing the current pipeline UI. We're soon going to completely redesign and reimplement the pipeline UI in Elm when we launch Spaces (#1707), so it'd end up being a lot of effort for an only temporary improvement.

We can leave this open to make sure the new UI is still fast enough for huge pipelines, but that probably explains why the issue was de-prioritized.

**Comment by gerhard** [comment]
With Concourse v4.2.1 this is slightly better in the sense that the browser is usable, but CPU utilisation is still crazy high. To give specifics, with https://ci.rabbitmq.com/ open in my browser this is the 60s CPU average on web & db instances (all [n1-highcpu-8](https://cloud.google.com/compute/pricing)):

```
bosh -d concourse ssh -c "sudo apt install -y dstat; dstat --cpu 60 1 > dstat; cat dstat; rm dstat"

# after some editing we have our results:
worker/8a328a4a-7d24-412c-83f4-a026c35b2029: stdout | ----total-cpu-usage----
web/236cbaf7-3e80-4a1d-93c6-377411faff52: stdout | usr sys idl wai hiq siq
web/236cbaf7-3e80-4a1d-93c6-377411faff52: stdout |  29   1  70   0   0   0
web/1d13b97c-f964-4802-beac-ea6483c84385: stdout | ----total-cpu-usage----
web/1d13b97c-f964-4802-beac-ea6483c84385: stdout | usr sys idl wai hiq siq
web/1d13b97c-f964-4802-beac-ea6483c84385: stdout |  12   1  87   0   0   0
db/d02f1a90-7a49-4cbf-8816-55d039b80d76: stdout | ----total-cpu-usage----
db/d02f1a90-7a49-4cbf-8816-55d039b80d76: stdout | usr sys idl wai hiq siq
db/d02f1a90-7a49-4cbf-8816-55d039b80d76: stdout |   6   2  90   1   0   0
```

All this is `atc` burning 1 CPU on web1 & >2 CPUs on web2.

This is what the deployment currently looks like, with just 3 jobs running (all workers are n1-highcpu-16):

```
Instance                                     Process State  AZ  IPs         VM Created At                 Uptime          Load              CPU    CPU    CPU   CPU   Memory        Swap         System      Ephemeral   Persistent
                                                                                                                          (1m, 5m, 15m)     Total  User   Sys   Wait  Usage         Usage        Disk Usage  Disk Usage  Disk Usage
db/d02f1a90-7a49-4cbf-8816-55d039b80d76      running        z2  10.0.32.6   Wed Sep 26 16:17:37 UTC 2018  0d 18h 1m 28s   0.60, 0.68, 0.72  -      4.8%   1.7%  1.1%  8% (614 MB)   0% (0 B)     44% (33i%)  1% (1i%)    56% (0i%)
web/1d13b97c-f964-4802-beac-ea6483c84385     running        z2  10.0.32.5   Wed Sep 26 16:21:47 UTC 2018  0d 17h 57m 34s  1.71, 1.76, 1.81  -      24.4%  0.5%  0.0%  23% (1.7 GB)  0% (0 B)     44% (33i%)  9% (2i%)    -
web/236cbaf7-3e80-4a1d-93c6-377411faff52     running        z2  10.0.32.4   Wed Sep 26 16:17:48 UTC 2018  0d 18h 1m 33s   1.43, 1.58, 1.60  -      18.8%  0.6%  0.0%  23% (1.7 GB)  0% (0 B)     44% (33i%)  9% (2i%)    -
worker/0a08291c-1f6b-4d14-974e-7ba446c8f24d  running        z2  10.0.32.8   Wed Sep 26 16:21:42 UTC 2018  0d 17h 57m 8s   1.24, 1.22, 1.23  -      5.9%   1.9%  0.1%  13% (2.0 GB)  1% (111 MB)  44% (33i%)  9% (1i%)    -
worker/22385291-93e9-4630-8a6a-8265831486f2  running        z2  10.0.32.9   Wed Sep 26 16:25:56 UTC 2018  0d 17h 52m 54s  2.08, 1.62, 1.34  -      5.6%   1.8%  0.0%  11% (1.6 GB)  0% (36 MB)   44% (33i%)  10% (1i%)   -
worker/3d3982b3-0adc-4d30-b16a-6c762975bd55  running        z2  10.0.32.11  Wed Sep 26 16:30:08 UTC 2018  0d 17h 48m 43s  0.99, 1.26, 1.23  -      5.5%   1.6%  0.0%  11% (1.7 GB)  0% (36 MB)   44% (33i%)  12% (1i%)   -
worker/8a328a4a-7d24-412c-83f4-a026c35b2029  running        z2  10.0.32.10  Wed Sep 26 16:34:21 UTC 2018  0d 17h 44m 29s  1.14, 1.55, 1.47  -      9.8%   2.7%  0.1%  12% (1.8 GB)  0% (66 MB)   44% (33i%)  9% (1i%)    -
worker/aae20483-ed0e-41fb-a8db-d9b108d8504b  running        z2  10.0.32.7   Wed Sep 26 16:17:33 UTC 2018  0d 18h 1m 18s   0.96, 1.14, 1.21  -      4.6%   1.1%  0.0%  12% (1.7 GB)  0% (33 MB)   44% (33i%)  9% (1i%)    -
worker/ea8e2613-8584-416f-99d8-fe25761fc37e  running        z2  10.0.32.12  Wed Sep 26 16:38:45 UTC 2018  0d 17h 40m 4s   1.84, 1.37, 1.25  -      6.6%   1.9%  0.1%  11% (1.6 GB)  0% (27 MB)   44% (33i%)  7% (1i%)    -
```
I'm going to close this since it served it's purpose of conveying the issue. It makes sense to open a new issue after we isolate pipelines to specific workers - right now we have sprawl of many containers across many workers, there are still things which we can do to make our Concourse experience better. Who knows, maybe by then Spaces will be out which might improve things even further.

cc @dumbbell
