### ISSUE TITLE
Failed to create volume error for darwin worker when task has outputs

### ISSUE THREAD

**Issue by challiwill** [concourse/concourse#992]
# Bug Report

We have a Darwin worker that is unable to create volumes.

relevant log message:

```
{"timestamp":"1490917642.317673683","source":"baggageclaim","message":"baggageclaim.repository.create-volume.failed-to-materialize-strategy","log_level":2,"data":{"error":"mkdir /Users/pivotal/workspace/concourse/darwin_work_dir/volumes/init: file exists","handle":"","session":"1.3"}}
```

We have two tasks that this worker runs. The main difference is that one (the task that is failing) produces an output volume, whereas the other just has inputs.

Worker is getting run as

```
/usr/local/bin/concourse worker \
  --work-dir darwin_work_dir/ \
  --tsa-host 127.0.0.1 \
  --tsa-public-key keys/web/tsa_host_key.pub \
  --tsa-worker-private-key keys/worker/worker_key
```

Usually as the user (because then we don't have to deal with it being a launchdaemon), but still doesn't work when run as root. Tried blowing away and recreating the work directory, still doesn't work.

The machine the worker is on has more than enough space for it to run (unless it somehow needs 1 TB of space)

---

* Concourse version: 2.8.0 RC 52
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Mac Mini
* Browser (if applicable): n/a
* Did this used to work?: Maybe
* OS version: macOS 10.12.3

**Comment by joshzarrabi** [comment]
We've fixed a ton of bugs on 2.8.0, so I am going to close this for now as we have not seen this in later rcs.
