### ISSUE TITLE
Auto-scaling based on build start/end

### ISSUE THREAD

**Issue by wrl** [concourse/concourse#993]
# Feature Request
## What challenge are you facing?

I'm interested in using Concourse to automate the release process for an OpenWRT-based system. The builds on a Kaby Lake i5 laptop take between 30 and 45 minutes to complete, so this is a project of considerable size. My best-case scenario would be to either have a very small worker running 24/7 checking the `git` resource, and when the check succeeds and the build gets scheduled, a very powerful (and hence more expensive) worker gets spun up, executes the build, and then shuts down when the build is complete.

AWS autoscaling groups don't seem like they'd be appropriate because I would like the scaling to take place *before* the build, since there would be no way of moving the container from a small worker to a larger one once it's started.

**Comment by joshzarrabi** [comment]
@wrl This is really interesting and would be super cool, but it is beyond the abstraction that concourse provides. Concourse assumes a pool of ready workers that are ready to do any task. You could tag a specific worker for the job that needs specific hardware, but this worker still needs to be on all the time.

What you could do, is have a task that spins up the fancy worker that you want, and uses some sort of cli or something to run the code you want on that worker, and then returns an exit code based on its success. We do something similar for our integration testing suite.

https://ci.concourse.ci/teams/main/pipelines/main/jobs/bosh-testflight/builds/1547
The `tf-deployment` `put` step in our `bosh-testflight` job spins up a concourse instance on another worker that concourse does not know anything about. The next task, `testflight`, runs tests based on an `ATC-URL` parameter that we pass in. You can see this here: https://github.com/concourse/pipelines/blob/master/ci.concourse.ci/concourse.yml#L304
