### ISSUE TITLE
Following outside links to pipelines aren't going to expected destination

### ISSUE THREAD

**Issue by pronoiac** [concourse/concourse#999]
Hi there!

Our documentation includes links to specific pipelines, and on Concourse 2.7.0, those links seem to end up at the default page - the one we'd land on just after logging in. I'd prefer that the displayed page we see matches the one in the url in the address bar. 

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome 57.0.2987.133 on Mac
* Did this used to work? Yes

**Comment by joshzarrabi** [comment]
@pronoiac Thats weird... Going to the home page is the equivalent of a 404. This probably means that the the user does not have access to the pipeline or something....
